### ISSUE TITLE
Palm swipes without onTouchEnded event

### ISSUE THREAD

**Issue by vinchkovsky** [cocos2d/cocos2d-x#10001]
I use Cocos2d-x 3.3 final, Samsung Galaxy S5, Android 4.4.2

There's a possibility to make a palm swipe to take screenshot: http://www.samsung.com/us/support/faq/FAQ00047978/52118/SCH-I535RWAVZW

When I'm doing that, onTouchBegan is called 2-4 times (all touches have different IDs) while onTouchEnded for this touches is never called.

Also if I do palm swipe without taking screenshot, onTouchEnded is called randomly for 50% of touches, according to my feelings

**Comment by walzer** [comment]
Using palm swipes to take a screenshot is really a cool feature for samsung phones.
But I had to regard it as low priority. Set it as unplanned unless we have enough human resources.
