### ISSUE TITLE
[Mac]Cpp Tests->BillBoard Test: sprites added seems to be wrong 

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#10020]
![bilboardtest](https://cloud.githubusercontent.com/assets/4231014/5752298/9272bc9a-9cad-11e4-8064-364d30525b29.gif)

This display has different from the 3.4beta0,and test codes didn't do too much changes.

**Comment by darkdukey** [comment]
That looks correct, I think
