### ISSUE TITLE
Button disappeared when setFlippedX(true) on 3.3final

### ISSUE THREAD

**Issue by daneric** [cocos2d/cocos2d-x#10031]
Code is very simple:
Button\* arrow = Button::create();
arrow->loadTextureNormal("arrowbtn.png", TextureResType::PLIST);
arrow->setFlippedX(true);
addChild(arrow);

on v3.3rc0 is OK, on v3.3final the arrow button not display, but it still can be clicked.

Please help!

**Comment by zilongshanren** [comment]
@daneric 
Could you give me your game assets?
I have included the flip test of ui::Button in cpp-tests. I think it's ok.

**Comment by zilongshanren** [comment]
@daneric 
How about this issue now?

**Comment by walzer** [comment]
This issue can't be reproduced, and inactive for already 3 months.
