### ISSUE TITLE
建议在win32的FileUtils中加上区分文件路径和名字大小写

### ISSUE THREAD

**Issue by qiutaoleo** [cocos2d/cocos2d-x#10041]
因为在win32下面开发的时候，资源和文件名windows平台忽略大小写区别，所以之前出的问题就是打包到Android和ios上面有出错，再去排查麻烦。
不如就让win32和linux下面表现一样也区分大小写。
自己已经改了，希望官方加入。

**Comment by zilongshanren** [comment]
thanks, @qiutaoleo 
Can you send a PR?

**Comment by qiutaoleo** [comment]
PR #10042

**Comment by walzer** [comment]
@qiutaoleo Thanks for contribution. I already asked @minggo to merge your pull request as soon as possible.
