### ISSUE TITLE
libcurl on linux

### ISSUE THREAD

**Issue by joewan** [cocos2d/cocos2d-x#10057]
we need install "libcurl" on ubuntu in build/install-deps-linux.sh.

**Comment by joewan** [comment]
sudo apt-get install libcurl4-openssl-dev

**Comment by zilongshanren** [comment]
@joewan 
We do install the libcurl in install-deps-linux.sh

**Comment by zilongshanren** [comment]
@joewan 
we install the libcurl4-gnutls-dev in the above script.
