### ISSUE TITLE
[Win 7] Crash in cpp-test -> Multi Touch example 

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#10056]
Again after 2-3 sec im getting :

```
First-chance exception at 0x004FFD24 in cpp-tests.exe: 0xC0000005: Access violation reading location 0x00000000.
Unhandled exception at 0x004FFD24 in cpp-tests.exe: 0xC0000005: Access violation reading location 0x00000000.

```

**Comment by minggo** [comment]
What's the engine version?

**Comment by meiry** [comment]
3.4 rc1

**Comment by dabingnn** [comment]
I think it is similar as #10054, could you please try the latest v3 branch?

**Comment by meiry** [comment]
by try the latest v3 branch? you mean to check out from git or download the v3.3 zip  again ?

**Comment by dabingnn** [comment]
If you have a git repo for cocos2d-x, I think you can test it by checkout the latest code of v3 branch.

**Comment by meiry** [comment]
@dabingnn @minggo
now that i thinking about it , how can i test this bug in v3 ? 
it  didn't Happened in v3.3 so the results will be the same ...

**Comment by minggo** [comment]
@meiry 
Yep, it is brought in v3.4 rc1.
There is a shader that use more than 8 attributes.

I think the best way is to use [git cherry-pick](http://git-scm.com/docs/git-cherry-pick) to merge that pull request to have a try.

**Comment by meiry** [comment]
@minggo
Can you please give me the right commands i need to execute in git shell by order 
so i could do it right

**Comment by minggo** [comment]
`git cherry-pick 79eee9b`
But it may cause conflict.

**Comment by minggo** [comment]
If you have already cloned cocos2d-x, then the convenient way is to update to latest codes.

**Comment by meiry** [comment]
So if i understand it right  to start from clean / fresh  
1. git clone  https://github.com/cocos2d/cocos2d-x.git
2. git cherry-pick 79eee9b

**Comment by minggo** [comment]
You didn't clone cocos2d-x?
How did you test?
Download released zip file?

**Comment by meiry** [comment]
i download the zip

**Comment by minggo** [comment]
Got it.

So i think you should do like this

git clone https://github.com/cocos2d/cocos2d-x.git
cd cocos2d-x
./download-deps.py

Then you can have a try.

**Comment by meiry** [comment]
@minggo 
You can close the bug its working now

**Comment by minggo** [comment]
Thanks @meiry.
