### ISSUE TITLE
 3.3中 子节点不跟随父节点移动 

### ISSUE THREAD

**Issue by sss316** [cocos2d/cocos2d-x#10063]
子节点label不跟随父节点移动，子节点是label，父节点是3d场景的UI层。

发现：
lua-tests 中，我在UI层增加了一个label. 创建方法 cc.Label:createWithTTF。
UI层移动，label不跟着移动，
最后发现下面这句代码导致，label是不是有bug？

local camera = cc.Camera:createPerspective(60.0, size.width/size.height, 10.0, 4000.0)
camera:setCameraFlag(cc.CameraFlag.USER1)
self:addChild(camera)

另外系统字label在3d场景中显示不出来，ttf可以。

**Comment by zii** [comment]
UI里是这样的, 可能是设计上的选择. 感觉应该增加相对位置和绝对位置的概念.

**Comment by sss316** [comment]
另外系统字label在3d场景中显示不出来，ttf可以。希望这个尽快支持，因为我想在模型上显示玩家名字，名字是玩家输入

**Comment by sss316** [comment]
相对位置一定要保留啊，多年的开发习惯了

**Comment by dabingnn** [comment]
@sss316 
Can you give a detailed description of bug, which version has the bug?
Could you create a short test case for the bug?

**Comment by sss316** [comment]
Where to upload resources?
version:cocos2d-x3.3. Written in lua language and cocos code ide.
I uploaded to this,  http://dl.vmall.com/c07xe8gsj3

email:sss316@163.com
qq:469222092

**Comment by sss316** [comment]
描述： 我增加了2个label，第一个可以看见，第二个看不见
        local ttfconfig = {outlineSize=7,fontSize=50,fontFilePath="fonts/britanic bold.ttf"}
        local blood = cc.Label:createWithTTF(ttfconfig,"-100")
        blood:enableOutline(cc.c4b(0,0,0,255))
        blood:setColor(cc.c3b(255,0,0))
        blood:setRotation3D({x=90,y=0,z=0})
        self:addChild(blood)
        blood:setPosition(500,500)
        blood:setPositionZ(150)
        blood:setCameraMask(2)
        blood:runAction(getAction())

```
    ---------------------test bug---------------------------------
    local label = cc.Label:createWithSystemFont("-100", "Arial", 50)
    label:setColor(cc.c3b(255,0,0))
    label:setRotation3D({x=90,y=0,z=0})
    self:addChild(label)
    label:setPosition(600,500)
    label:setPositionZ(150)
    label:setCameraMask(2)
    label:runAction(getAction())
```

![3](https://cloud.githubusercontent.com/assets/6467105/5940207/4992fc3c-a744-11e4-91f3-d8d619ebdce4.jpg)

 self._settingLayer移动，图片移动，绿色字没有移动。
    local background=cc.Sprite:create("zbbackground.png")
    background:setPosition(cc.p(160,240))
    self._settingLayer:addChild(background)

```
---------------------test bug---------------------------------

local nameLable = cc.LabelTTF:create("test label,not move", "Arial", 36)
self._settingLayer:addChild(nameLable)
nameLable:setPosition(cc.p(160,450))
nameLable:setColor(cc.c3b(0, 255, 0))
```

![1](https://cloud.githubusercontent.com/assets/6467105/5940290/052ab444-a745-11e4-9901-46c9b879eb54.jpg)
![2](https://cloud.githubusercontent.com/assets/6467105/5940291/05648638-a745-11e4-87c8-9145346b52d0.jpg)

源代码和资源下载地址上面提供，有问题随时联系我。

**Comment by sss316** [comment]
Two bugs.
detailed description:
https://github.com/cocos2d/cocos2d-x/issues/10063

At 2015-01-26 09:52:16, "Huabing.Xu" notifications@github.com wrote:

@sss316
Can you give a detailed description of bug, which version has the bug?
Could you create a short test case for the bug?

¡ª

**Comment by yuanotes** [comment]
This is annoying. Any suggestion to solve this problem?

**Comment by yuanotes** [comment]
The same here: http://discuss.cocos2d-x.org/t/label-as-child-doesnt-move-when-parent-position-updated-with-2-cameras/20267

**Comment by minggo** [comment]
@darkdukey 
@super626 
Any suggestion?

**Comment by yuanotes** [comment]
I think we solved this issue. The scene iterates all cameras in every frame. When the node tree is visited with the 1st camera, the parent node of the label processed `_transformUpdated` and `_contentSizeDirty` and set them to `false`. 

If the label's camera mask is the same with the 1st camera, it would be processed correctly. Otherwise, it won't update with its parent node.

**Comment by wantnon2** [comment]
our solution:
uint32_t Node::processParentFlags(const Mat4& parentTransform, uint32_t parentFlags)
{
    if(_usingNormalizedPosition) {
        CCASSERT(_parent, "setNormalizedPosition() doesn't work with orphan nodes");
        if ((parentFlags & FLAGS_CONTENT_SIZE_DIRTY) || _normalizedPositionDirty) {
            auto s = _parent->getContentSize();
            _position.x = _normalizedPosition.x \* s.width;
            _position.y = _normalizedPosition.y \* s.height;
            _transformUpdated = _transformDirty = _inverseDirty = true;
            _normalizedPositionDirty = false;
        }
    }

```
uint32_t flags = parentFlags;
flags |= (_transformUpdated ? FLAGS_TRANSFORM_DIRTY : 0);
flags |= (_contentSizeDirty ? FLAGS_CONTENT_SIZE_DIRTY : 0);


if(flags & FLAGS_DIRTY_MASK)
    _modelViewTransform = this->transform(parentTransform);

if (isVisitableByVisitingCamera())//if the camera is not match this node, do not consume _transformUpdated.  [wantnon,  yuanotes]
{
    _transformUpdated = false;
    _contentSizeDirty = false;
}


return flags;
```

}

**Comment by WenhaiLin** [comment]
We have fixed this issue. https://github.com/cocos2d/cocos2d-x/pull/10730 and https://github.com/cocos2d/cocos2d-x/pull/11413
