### ISSUE TITLE
Add Animation::getCurrentFrame()

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#10085]

**Comment by minggo** [comment]
Can refer to this ticket for detail information https://github.com/cocos2d/cocos2d-html5/issues/1050#issuecomment-70594064.

**Comment by WenhaiLin** [comment]
Done https://github.com/cocos2d/cocos2d-x/pull/12786

**Comment by pandamicro** [comment]
Thanks I will add a function to the web engine too
