### ISSUE TITLE
setDisplayStats (false) moving fasttmx Crash

### ISSUE THREAD

**Issue by fqamic** [cocos2d/cocos2d-x#10091]
Before 3.4rc0 version has disappeared BUG reproduced on 3.4rc1 again.
In cpp-tests, AppDelegate.cpp file director-> setDisplayStats (false), after TileMapTest2.cpp use fasttmx, moving scene, when there does not appear in the original part of the map screen, it will collapse. The BUG in the previous version have been fixed amazing.

Collapse at:
CCTextureAtlas.CPP 644 line
glDrawElements (GL_TRIANGLES, (GLsizei) numberOfQuads \* 6, GL_UNSIGNED_SHORT, (GLvoid *) (start \* 6 \* sizeof (_indices [0])));

**Comment by fqamic** [comment]
sorry!
I found 3.4rc0 The cpp-tests is also a problem, but for my own projects in 3.4rc0 does not crash.

**Comment by minggo** [comment]
@fqamic 
How to reproduce it?

**Comment by fqamic** [comment]
@minggo 
![qq20150120-1](https://cloud.githubusercontent.com/assets/7044155/5813911/aa51ad60-a0bf-11e4-9f0e-bbc63454cb76.png)
![qq20150120-2](https://cloud.githubusercontent.com/assets/7044155/5813913/abab521a-a0bf-11e4-81fd-776c0b5046e9.png)
![qq20150120-3](https://cloud.githubusercontent.com/assets/7044155/5813923/c0913cda-a0bf-11e4-941c-810cf7755df7.png)

crash!
version 3.4rc1 cpp-tests

**Comment by fqamic** [comment]
@minggo 
This seems to have a relationship and Label.
I found that if you do not have any Label on the current screen you can see, it will not collapse.
Hope that helps

**Comment by minggo** [comment]
@fqamic 
Would you try it.
It is fixed in #10138.

**Comment by fqamic** [comment]
@minggo 
Can, thank you very much!
