### ISSUE TITLE
binding AnimationInfo to lua 

### ISSUE THREAD

**Issue by geron-cn** [cocos2d/cocos2d-x#10107]
need add AnimationInfo (it is a struct in CCActionTimeline.h) into cocos2dx_studio.ini line:33

**Comment by samuele3hu** [comment]
The related api as follows were all bound to lua:
virtual void play(std::string animationName, bool loop); 
virtual void addAnimationInfo(const AnimationInfo& animationInfo);
virtual void removeAnimationInfo(std::string animationName); 
virtual bool IsAnimationInfoExists(const std::string& animationName); 
virtual AnimationInfo getAnimationInfo(const std::string& animationName);

In the current mechanism, The AnimationInfo struct was converted to the table like this {name = stringValue,  startIndex = numberValue,  endIndex = numberValue}, you could call ccs.AnimationInfo(stringValue, numberValue1, numberValue2) to construct it if you require "cocos.cocostudio.CocoStudio"

@pandamicro, i think jsb should also increase this binding.

@geron-cn, i have send the pr https://github.com/cocos2d/cocos2d-x/pull/10125, you could pull this pr to check it.
