### ISSUE TITLE
[Android] Some device will crash on armeabi-v7a lib

### ISSUE THREAD

**Issue by Yehsam23** [cocos2d/cocos2d-x#10112]
Version: 3.3 and 3.4rc0
NDK version: r10c
device: ASUS Eee Pad Transformer TF101
reproduce: change cpp-tests Application.mk
and Add
APP_ABI := armeabi-v7a

It will only build armeabi-v7a lib.

Some device will crash if only has armeabi-v7a lib.
But it works fine at cocos2dx v2.2

Please help us

D/JniHelper( 9668): JniHelper::setJavaVM(0xd0c3e0), pthread_self() = 1074152584
D/main    ( 9668): cocos_android_app_init
D/TextView( 9668): Constructor - Got Res id for appearance for textColorPrimaryInverse
W/ResourceType( 9668): Skipping entry 0x1060003 in package table 0 because it is not complex!
D/TextView( 9668): Constructor - Got appearance for textColorPrimaryInverse
D/TextView( 9668): Constructor -- Got mEditTextBackgroundColor
D/Cocos2dxActivity( 9668): model=Transformer TF101
D/Cocos2dxActivity( 9668): product=TW_epad
D/Cocos2dxActivity( 9668): isEmulator=false
F/libc    ( 9668): Fatal signal 4 (SIGILL) at 0x5cf08f38 (code=1)
D/dalvikvm(  168): GC_EXPLICIT freed 154K, 33% free 13948K/20551K, paused 3ms+5ms
V/TabletStatusBar(  273): setLightsOn(true)
D/libEGL  ( 9668): loaded /system/lib/egl/libEGL_tegra.so
D/libEGL  ( 9668): loaded /system/lib/egl/libGLESv1_CM_tegra.so
D/libEGL  ( 9668): loaded /system/lib/egl/libGLESv2_tegra.so
D/OpenGLRenderer( 9668): Enabling debug mode 0
I/DEBUG   (   84): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   (   84): Build fingerprint: 'asus/TW_epad/TF101:4.0.3/IML74K/TW_epad-9.2.1.27-20120615:user/release-keys'
I/DEBUG   (   84): pid: 9668, tid: 9683  >>> org.cocos2dx.cpp_tests <<<
I/DEBUG   (   84): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 5cf08f38
I/DEBUG   (   84):  r0 5dabbb48  r1 5dabbb0c  r2 00000000  r3 0000003c
I/DEBUG   (   84):  r4 5d698a28  r5 00eed940  r6 00000000  r7 56e2ff44
I/DEBUG   (   84):  r8 5dabbbd8  r9 56e2ff3c  10 00000008  fp 5dabbb14
I/DEBUG   (   84):  ip 40000000  sp 5dabbb00  lr 5cec4a6c  pc 5cf08f38  cpsr 60000010
I/DEBUG   (   84):  d0  0000006442c80000  d1  3ff0000042c80000
I/DEBUG   (   84):  d2  437e8000000000fe  d3  000000003f000000
I/DEBUG   (   84):  d4  000001fd00000000  d5  4047800000000000
I/DEBUG   (   84):  d6  4026000000000000  d7  0000003c00000000
I/DEBUG   (   84):  d8  0000000000000000  d9  0000000000000000
I/DEBUG   (   84):  d10 0000000000000000  d11 0000000000000000
I/DEBUG   (   84):  d12 0000000000000000  d13 0000000000000000
I/DEBUG   (   84):  d14 0000000000000000  d15 0000000000000000
I/DEBUG   (   84):  scr 60000012
I/DEBUG   (   84): 
I/DEBUG   (   84):          #00  pc 0154bf38  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so (_ZNK7cocos2d5Value8asDoubleEv)
I/DEBUG   (   84):          #01  pc 01507a68  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so (_ZN7cocos2d8Director16setDefaultValuesEv)
I/DEBUG   (   84):          #02  pc 015071b4  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so (_ZN7cocos2d8Director4initEv)
I/DEBUG   (   84):          #03  pc 0150700c  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so (_ZN7cocos2d8Director11getInstanceEv)
I/DEBUG   (   84):          #04  pc 0111fcd8  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnResume)
I/DEBUG   (   84):          #05  pc 0001ec30  /system/lib/libdvm.so (dvmPlatformInvoke)
I/DEBUG   (   84):          #06  pc 000593ca  /system/lib/libdvm.so (_Z16dvmCallJNIMethodPKjP6JValuePK6MethodP6Thread)
I/DEBUG   (   84):          #07  pc 0005b0f8  /system/lib/libdvm.so (_Z22dvmResolveNativeMethodPKjP6JValuePK6MethodP6Thread)
I/DEBUG   (   84):          #08  pc 00030ad0  /system/lib/libdvm.so
I/DEBUG   (   84): 
I/DEBUG   (   84): code around pc:
I/DEBUG   (   84): 5cf08f18 ea00001d e51b3008 e5933008 e3530002  .....0...0....S.
I/DEBUG   (   84): 5cf08f28 1a000004 e51b3008 e5933000 ee073a90  .....0...0...:..
I/DEBUG   (   84): 5cf08f38 eef80be7 ea000014 e51b3008 e5933008  .........0...0..
I/DEBUG   (   84): 5cf08f48 e3530003 1a000003 e51b3008 edd37a00  ..S......0...z..
I/DEBUG   (   84): 5cf08f58 eef70ae7 ea00000c e51b3008 e5933008  .........0...0..
I/DEBUG   (   84): 
I/DEBUG   (   84): code around lr:
I/DEBUG   (   84): 5cec4a4c e24b3014 e51b0020 e1a01002 e1a02003  .0K. ........ ..
I/DEBUG   (   84): 5cec4a5c ebffb2a4 e1a03000 e1a00003 eb0110ce  .....0..........
I/DEBUG   (   84): 5cec4a6c e14b01fc e24b3014 e1a00003 eb010bcb  ..K..0K.........
I/DEBUG   (   84): 5cec4a7c e24b3024 e1a00003 fa0f411c e24b3028  $0K......A..(0K.
I/DEBUG   (   84): 5cec4a8c e1a00003 fa0e7ded eef71b00 ed5b0b07  .....}........[.
I/DEBUG   (   84): 
I/DEBUG   (   84): memory map around addr 5cf08f38:
I/DEBUG   (   84): 5b8bd000-5b9bd000 /dev/ashmem/dalvik-jit-code-cache (deleted)
I/DEBUG   (   84): 5b9bd000-5d587000 /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so
I/DEBUG   (   84): 5d587000-5d588000 
I/DEBUG   (   84): 
I/DEBUG   (   84): stack:
I/DEBUG   (   84):     5dabbac0  00000000  
I/DEBUG   (   84):     5dabbac4  5dabbadc  
I/DEBUG   (   84):     5dabbac8  5dabbae4  
I/DEBUG   (   84):     5dabbacc  5cb3e240  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so
I/DEBUG   (   84):     5dabbad0  00000000  
I/DEBUG   (   84):     5dabbad4  00eb2f34  [heap]
I/DEBUG   (   84):     5dabbad8  00000005  
I/DEBUG   (   84):     5dabbadc  00000000  
I/DEBUG   (   84):     5dabbae0  5dabbaf4  
I/DEBUG   (   84):     5dabbae4  5cdacee0  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so
I/DEBUG   (   84):     5dabbae8  5dabbb0c  
I/DEBUG   (   84):     5dabbaec  5dabbb08  
I/DEBUG   (   84):     5dabbaf0  5dabbb14  
I/DEBUG   (   84):     5dabbaf4  5dabbb14  
I/DEBUG   (   84):     5dabbaf8  df0027ad  
I/DEBUG   (   84):     5dabbafc  00000000  
I/DEBUG   (   84): #00 5dabbb00  5dabbb38  
I/DEBUG   (   84):     5dabbb04  00eb2ef8  [heap]
I/DEBUG   (   84):     5dabbb08  00000000  
I/DEBUG   (   84):     5dabbb0c  5dabbb48  
I/DEBUG   (   84):     5dabbb10  5dabbb5c  
I/DEBUG   (   84):     5dabbb14  5cec4a6c  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so
I/DEBUG   (   84): #01 5dabbb18  5dabbb2c  
I/DEBUG   (   84):     5dabbb1c  5cec8e38  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so
I/DEBUG   (   84):     5dabbb20  00e29b08  [heap]
I/DEBUG   (   84):     5dabbb24  00eb2dc0  [heap]
I/DEBUG   (   84):     5dabbb28  5dabbb6c  
I/DEBUG   (   84):     5dabbb2c  5dabbb6c  
I/DEBUG   (   84):     5dabbb30  00000008  
I/DEBUG   (   84):     5dabbb34  00eb2dc0  [heap]
I/DEBUG   (   84):     5dabbb38  00e91c7c  [heap]
I/DEBUG   (   84):     5dabbb3c  00eb2ef8  [heap]
I/DEBUG   (   84):     5dabbb40  00e29908  [heap]
I/DEBUG   (   84):     5dabbb44  00e29908  [heap]
I/DEBUG   (   84):     5dabbb48  0000003c  
I/DEBUG   (   84):     5dabbb4c  00eeddec  [heap]
I/DEBUG   (   84):     5dabbb50  00000002  
I/DEBUG   (   84):     5dabbb54  00e29908  [heap]
I/DEBUG   (   84):     5dabbb58  5dabbb84  
I/DEBUG   (   84):     5dabbb5c  5cec41b8  /data/data/org.cocos2dx.cpp_tests/lib/libcpp_tests.so

**Comment by minggo** [comment]
I think it is related to #9968.

**Comment by Yehsam23** [comment]
Yes~~

Thanks you

**Comment by Yehsam23** [comment]
Please close this issue~~~

thanks a lot
