### ISSUE TITLE
[WP8]cpp-empty-test and cpp-tests flash back on both simulator and device

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#10161]
DXGI WARNING: Process is terminating. Using simple reporting. Please call ReportLiveObjects() at runtime for standard reporting. [ STATE_CREATION WARNING #0: ]
DXGI WARNING: Live Producer at 0x0059ECD8, Refcount: 5. [ STATE_CREATION WARNING #0: ]
DXGI WARNING:   Live Object at 0x005A1C48, Refcount: 3. [ STATE_CREATION WARNING #0: ]
DXGI WARNING: Live                         Object :      1 [ STATE_CREATION WARNING #0: ]

**Comment by minggo** [comment]
@stammen
Could you please help to fix it?
Thanks.

**Comment by stammen** [comment]
@huangshiwu Would you please provide more detail? What is "flash back"? Thanks.

**Comment by ghost** [comment]
@stammen It means crash at starting the app.I try to debug and find it crash in GLProgramCache::loadDefaultGLProgram --- case kShaderType_PositionTexture_uColor  --- GLProgram::initWithByteArrays --- initWithPrecompiledProgramByteArray --- CCPrecompiledShaders::getInstance()->loadProgram  --- glProgramBinaryOES

**Comment by ghost** [comment]
@stammen It seems I found the reason, we change the shaders in pr #10115 and do not update the precompiledshader for WP8, I will update it.

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/10163
