### ISSUE TITLE
When building cpp-tests with VS2013, the Chinese font name generates errors

### ISSUE THREAD

**Issue by ryukbk** [cocos2d/cocos2d-x#10170]
Hello, when building cpp-tests with VS2013, the Chinese font name in the code generates errors.

```
1>..\Classes\LabelTest\LabelTestNew.cpp(598): error C2144: syntax error : 'auto' should be preceded by ')'
```

...

https://github.com/cocos2d/cocos2d-x/blob/32632896800e573281170f26a4fd6b324bc09023/tests/cpp-tests/Classes/LabelTest/LabelTestNew.cpp#L600
https://github.com/cocos2d/cocos2d-x/blob/32632896800e573281170f26a4fd6b324bc09023/tests/cpp-tests/Classes/LabelTest/LabelTestNew.cpp#L1068

The comment seems to suggest it's OK with '啊' at the end, but it still produces errors in my environment.

**Comment by minggo** [comment]
I haven't met the problem, so close it.
