### ISSUE TITLE
[FantasyWarrior3D] Shadow bug.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10197]
All of the shadows in the game may be blink sometimes, and the shadow of the ice trail cover the ice trail itself.

**Comment by darkdukey** [comment]
Can you create a test-case that can easily reproduce this? otherwise it's going to take time

**Comment by darkdukey** [comment]
Should be fixed by #10248
Also require to merge https://github.com/chukong/FantasyWarrior3D/pull/202
