### ISSUE TITLE
Bug on GLProgram::setUniformLocationWith3fv

### ISSUE THREAD

**Issue by super626** [cocos2d/cocos2d-x#10207]
It will crash when we modify the config file to set the max directional/point/spot light to 3. It fails to pass the light array to the shader.

However, it works if we modify the MeshCommand::setLightUniforms like this,
the function call setUniformLocationWith3f to glUniform3fv

There may be bugs on the hash cache of GLProgram::setUniformLocationWith3f.

**Comment by masterhou** [comment]
I found glUniform**v , have a cache, buffer length is stable at first, but when cache data length is changed, may larger than last time, memcpy will overflow.
