### ISSUE TITLE
Many Audios are playing together, will crash 

### ISSUE THREAD

**Issue by masterhou** [cocos2d/cocos2d-x#10217]
10+ audios are playing in battle, will crash.
mp3 44100
device: ipad2

**Comment by WenhaiLin** [comment]
@masterhou  I can't reproduced on iPhone4S and iPhone5S. This issue can be reproduced only on ipad2?

**Comment by walzer** [comment]
@masterhou 
1. Which version of cocos2d-x are you using? 
2. Are you using `AudioEngine` or `SimpleAudioEngine`?
3. Which API you used for play audios? `SimpleAudioEngine::playEffect`?
4. Which iOS version is running on your ipad2?

**Comment by walzer** [comment]
Well, this is a bug report from 南京炉石。
1. cocos2d-x v3.5
2. use `AudioEngine::play2d`
3. iOS 8.2 & 8.3
4. iPad2

**Comment by WenhaiLin** [comment]
I can't reproduced this issue.
Tested on:
- iPad Air
- iPad 2
- iPhone 4S
- iPhone 5S
- iPhone 6S

**Comment by jxianglonggg** [comment]
We have met this problem.
it crashed here
void AudioEngineImpl::_play2d(AudioCache *cache, int audioID)
![qq 20150716100340](https://cloud.githubusercontent.com/assets/10494088/8713980/7d829790-2ba2-11e5-9746-b952a2e0196c.png)

**Comment by jxianglonggg** [comment]
We have met this problem.
it crashed here
void AudioEngineImpl::_play2d(AudioCache *cache, int audioID)
![qq 20150716100340](https://cloud.githubusercontent.com/assets/10494088/8714032/0b600084-2ba3-11e5-9d9c-6f0b0ea6dc1a.png)

**Comment by WenhaiLin** [comment]
@jxianglonggg WIN32 platform? Which version of cocos2d-x are you using?

**Comment by jxianglonggg** [comment]
@WenhaiLin   both win32  and Android.Android is more frequence.version is cocos2d-x 3.3

**Comment by WenhaiLin** [comment]
Fixed possible crash on mac/ios at : https://github.com/cocos2d/cocos2d-x/pull/13311
