### ISSUE TITLE
Transparent 3d sprite + 2d sprite can not work correctly

### ISSUE THREAD

**Issue by super626** [cocos2d/cocos2d-x#10212]
There are transparent 3d girl and 2d circle on the scene. The girl or circle stay on top alternatively. Look the girl's legs. 

![tmp736df607](https://cloud.githubusercontent.com/assets/4159090/5896278/d01b7518-a564-11e4-9e1e-4ebfbd14bc38.png)
![tmp0f1fd2c7](https://cloud.githubusercontent.com/assets/4159090/5896283/ed87a82e-a564-11e4-94df-d4a842c2bac6.png)

**Comment by minggo** [comment]
Related test case is #10211
