### ISSUE TITLE
Unable to load CocoStudio files

### ISSUE THREAD

**Issue by zawasp** [cocos2d/cocos2d-x#10221]
With the latest commits, I am unable to load files published with the current CocoStudio version available for download (2.1beta from cocos2d-x.org). I get this error at runtime:

`Assert failed: The reader build id of your Cocos exported file() and the reader build id in your Cocos2d-x(2.1.0.0) are not match.
Please get the correct reader(build id )from http://www.cocos2d-x.org/filedown/cocos-reader and replace it in your Cocos2d-x`

The published binary csb files have 2.0.8.0 in them.

**Comment by hamburml** [comment]
Try cocos studio 2.1 from http://cocos2d-x.org/download

**Comment by zawasp** [comment]
Yes, it works with the final version. The problem was the repo was updated to version 2.1 and CocoStudio was still on 2.1 beta.

**Comment by hamburml** [comment]
I am sorry for writing on a closed issue but I have a problem with cocos studio 2.1 and cocos2d-x 3.4. What did you load? did you load json or binary? 

I get following error ASSERT FAILED ON LUA EXECUTE: The reader build id of your Cocos exported file(t???) and the reader build id in your Cocos2d-x(2.1.0.0) are not match. He is unable to load the right id out of the binary files (i am using binary...)

**Comment by zawasp** [comment]
I loaded the binary version (.csb) from C++. I neeeded to export the project again from Cocos Studio (2.1 final).
