### ISSUE TITLE
using scheduleOnce(..., std::string & key) has a critical bug

### ISSUE THREAD

**Issue by smartcompany** [cocos2d/cocos2d-x#10232]
I am making simple game using cocos2d-x 3.3 final 
i used schedule function with lamda 
void schedule(const std::function<void(float)>& callback, const std::string &key);

and also used
void scheduleOnce(SEL_SCHEDULE selector, float delay);

but it maked a crash some times usually on android JNI build
I found wrong codes in your source named CCScheduler.cpp

 for (int i = 0; i < element->timers->num; ++i)
        {
            TimerTargetCallback _timer = static_cast<TimerTargetCallback_>(element->timers->arr[i]);

```
        if (key == timer->getKey())
        {
            CCLOG("CCScheduler#scheduleSelector. Selector already scheduled. Updating interval from: %.4f to %.4f", timer->getInterval(), interval);
            timer->setInterval(interval);
            return;
        }        
    }
```

this code casts TimerTargetCallback type but timer could be type of TimerTargetSelector 
if you called "void scheduleOnce(SEL_SCHEDULE selector, float delay);" function 
so I think wrong memory is accessed 
could please fix this?

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10241
