### ISSUE TITLE
Multitouch doesn't work on windows phone 8.1

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#10240]
Reproduce:
1. Create clean project (I'm using cocos2d-x 3.3 c++).
2. Open wp8-xaml project in visual studio (i'm using 2013 community).
3. Add this in helloworldscene.cpp in init method:

```
    auto listener = EventListenerTouchAllAtOnce::create();

    listener->onTouchesBegan = [](std::vector<Touch*> touches, Event* event){
        log("onTouchesBegan: %d", touches.size());
    };

    listener->onTouchesMoved = [](std::vector<Touch*> touches, Event* event){
        log("onTouchesMoved: %d", touches.size());
    };

    listener->onTouchesEnded = [](std::vector<Touch*> touches, Event* event){
        log("onTouchesEnded: %d", touches.size());
    };

    _eventDispatcher->addEventListenerWithSceneGraphPriority(listener, this);
```
1. In project (Windows Phone 8.0) go into properties and in debug tab select 'Native Only' below UI Task.
2. Run app on device (I tested on nokia lumia 730 with windows phone 8.1). 

And you always see there's only one touch. 

I tested it after retargeting project to 8.1 - the same result.
I tested it on android - multitouch working like a charm.
I also made native code:

Add this in MainPage.xaml.cs:

```
void Touch_FrameReported(object sender, TouchFrameEventArgs e)
        {
            if (Visibility == Visibility.Collapsed)
                return;
            TouchPointCollection pointCollection = e.GetTouchPoints(this);
            Debug.WriteLine("points touched: " + pointCollection.Count);
        }
```

and in constructor:

```
Touch.FrameReported += Touch_FrameReported;
```

You'll see right amount of touches in logs. 10 fingers - no problem.

**Comment by walzer** [comment]
Duplicated with #123

**Comment by pandamicro** [comment]
@walzer why is this issue reopened? The previous solution didn't work?

**Comment by stammen** [comment]
Look at https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-tests/Classes/MutiTouchTest/MutiTouchTest.cpp. 

You are supposed to keep track of the touches yourself in a manner similar to  MutiTouchTest.cpp, I send all of the touches to the callbacks when they are received or changed.

**Comment by pandamicro** [comment]
Thank you Dale ! I will close this issue
