### ISSUE TITLE
If the parent of DrawNode setScale, the effect is different on the each platform.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10257]
`Version:` 3.3Final
`Reproduce:` Copy the following code to HelloWorld project.

``` cpp
auto draw = DrawNode::create();
    this->addChild(draw, 10);
    for (int j = 0; j < visibleSize.height; j+= 40)
    {
        draw->drawSegment(Point(0, j), Point(visibleSize.width, j), 0.5, Color4F(1, 0, 0, 1));
    }
    for (int j = 0; j < visibleSize.width; j+= 40)
    {
        draw->drawSegment(Point(j,0), Point(j,visibleSize.height), 0.5, Color4F(1, 0, 0, 1));
    }

    this->setScale(0.5);
```

`Mac`
![2015-01-28 15 26 04](https://cloud.githubusercontent.com/assets/5085300/5934372/70972172-a709-11e4-9540-5491e39d3a12.png)
`iOS simulator`
![2015-01-28 15 30 35](https://cloud.githubusercontent.com/assets/5085300/5934377/7d11c9c0-a709-11e4-88f5-635491841d28.png)
`iOS`
![2 pic](https://cloud.githubusercontent.com/assets/5085300/5934519/7c92a422-a70b-11e4-8289-6b190c539fe1.jpg)
`Android`
![screenshot_2015-01-28-15-25-56](https://cloud.githubusercontent.com/assets/5085300/5934381/8b600faa-a709-11e4-8b4e-8cb01724c92d.png)

**Comment by Luoweihong** [comment]
Did it fixed?
