### ISSUE TITLE
Build system: strict use of external libraries

### ISSUE THREAD

**Issue by reagentoo** [cocos2d/cocos2d-x#10264]
Should be allowed to build totaly without libs in /external directory (cocos2d-x-3rd-party-libs-bin). It would be useful to build packages for various distributions. Include libraries in cocos2d-x do not meet the standard ways in the directory (/usr/include/...). It is also preferred build shared libraries instead of static. At this time there is no way to build packages using unfinished cmake build system of cocos2d-x.

**Comment by walzer** [comment]
We have finished this in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src for v4.
Why is for v4 only? Because it will change the folder structure, remove some 3rd party libs source code in v3, and break the backward compatibility. I will not move this feature to v3, but left it to v4 only.
