### ISSUE TITLE
[win32]cpptests-->Node:Cliping-->Clipping to RenderTexture: Show different after click button 'Reproduce bug'

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#10276]
![qq 20150129165810](https://cloud.githubusercontent.com/assets/5234286/5954864/128918e0-a7d8-11e4-84c8-95970feedcc1.png)
![qq 20150129165827](https://cloud.githubusercontent.com/assets/5234286/5954865/16eef97c-a7d8-11e4-9504-721a90c85e5f.png)

**Comment by WenhaiLin** [comment]
Android have this problem.

**Comment by Dhilan007** [comment]
Android have this problem.

**Comment by ghost** [comment]
This had already fixed in #10278

**Comment by minggo** [comment]
@Dhilan007 
Please check it.

**Comment by WenhaiLin** [comment]
@minggo It is fixed.
