### ISSUE TITLE
某些Activity切换情况，会导致Cocos2dxRenderer onDrawFrame不再调用

### ISSUE THREAD

**Issue by jasonzhangxx** [cocos2d/cocos2d-x#10280]
某些Activity切换的情况（我这边是使用小米2，在接入应用宝SDK，使用QQ登录，很高概率发生），会导致Cocos2dxRenderer实效，onDrawFrame不再被调用，mainloop停止。

cocos2dx原代码如下：

```
 @Override
public void onResume() {
    super.onResume();
    this.queueEvent(new Runnable() {
        @Override
        public void run() {
            Cocos2dxGLSurfaceView.this.mCocos2dxRenderer.handleOnResume();
        }
    });
}

@Override
public void onPause() {
    this.queueEvent(new Runnable() {
        @Override
        public void run() {
            Cocos2dxGLSurfaceView.this.mCocos2dxRenderer.handleOnPause();
        }
    });
    //super.onPause();
}
```

//super.onPause();是被注释的。

我修改为：

```
  @Override
  public void onResume() {
    super.onResume();
    Cocos2dxGLSurfaceView.this.mCocos2dxRenderer.handleOnResume();
}

@Override
public void onPause() {
    Cocos2dxGLSurfaceView.this.mCocos2dxRenderer.handleOnPause();
    super.onPause();
}
```

回复surfaceview的正常super.onPause， Cocos2dxRenderer可以正常工作。

但是，对cocos2dx的事件处理造成的影响就未知了，请问下有没有更完善的解决方案？或者如何可以更好的处理surfaceview的onPause?  以及我这样修改造成的cocos2dx的异常可能会有哪些？

**Comment by minggo** [comment]
The reason `super.onPause` is commented is that, it will make glContext lost every time return from background. Then, all resources should be reloaded every time.

**Comment by jasonzhangxx** [comment]
all resources包括所有图片都要重新加载吗？而且是每次切后台都会发生……？reload的操作需要自己完成吗……？

**Comment by minggo** [comment]
Yep, it includes all pictures, and it will do every time.
Engine will reload it automatically.

**Comment by jasonzhangxx** [comment]
3Q，有新的发现会继续发上来。

**Comment by zhangyi** [comment]
@firegames  最后你是如何处理的啊   :)

**Comment by jasonzhangxx** [comment]
暂时把这个bug留着……现在影响的用户还算比较少，不敢动

**Comment by minggo** [comment]
I think it is better to do special operation for xiaomi2.

**Comment by zhangyi** [comment]
我参与的游戏也遇到类似的问题，从360手机助手下载游戏后，它会自动安装。安装完成后，如果游戏已经启动，通过360手机助手再点击启动游戏，就会黑屏。这边的处理方法是，再弄一个Activity，然后启动游戏的主Activity（相当于外层套了一个壳子）

public class MainActivity extends Activity
{
    @Override
    public void onCreate(Bundle savedInstanceState) 
    {
        super.onCreate(savedInstanceState);

```
    setContentView(R.layout.main_activity);

        Intent localIntent = new Intent(this, GameActivity.class);
        localIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK
                    | Intent.FLAG_ACTIVITY_SINGLE_TOP
                    | Intent.FLAG_ACTIVITY_CLEAR_TOP);
        this.startActivity(localIntent);
        this.finish();
}
```

}

**Comment by jasonzhangxx** [comment]
感谢分享啊！
