### ISSUE TITLE
remove vs2012 supporting

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#10288]
Only supports VS2013.
Refer to [this ticket](http://discuss.cocos2d-x.org/t/how-about-remove-supporting-vs2012/19208) for detail information.

**Comment by ghost** [comment]
So, we have to wait 998 years for Visual Studio, which will support the Cocos.
Please correct misspell :D

**Comment by minggo** [comment]
@CasteyDaSilva 
What did you mean?

**Comment by minggo** [comment]
Oh, i got it.
Correct it.

Thanks:)

**Comment by WenhaiLin** [comment]
Done https://github.com/cocos2d/cocos2d-x/pull/10418
