### ISSUE TITLE
More mobile features requested: Album access, Camera access etc

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#10293]
There are some common used features in mobile games, like Album for save screen captions or upload user images. Camera access for taking photos or reality augmented games. If Cocos2d-x can provide a common API across iOS / Android / Windows Phone, it should be very useful.

Here is a what I can image:
- Album
- Camera
- Microphone
- Geolocalisation

You can add your own ideas to this list

**Comment by zilongshanren** [comment]
+1 for Vibration

**Comment by gyf19** [comment]
+1

**Comment by yagjak** [comment]
Yes, it will be very useful for us, thanks cocos team.

**Comment by 0xJimmyBeh** [comment]
Any milestone for this feature to be implemented? Need to bind them to use in Cocos2d-JS for cross platform project.

Thanks!

**Comment by ricardoquesada** [comment]
sounds good to me.

What other useful features are missing? Let's identify them and then prioritize them.

**Comment by 0xJimmyBeh** [comment]
From the post on Cocos2d-x forum : 
http://discuss.cocos2d-x.org/t/more-mobile-features-requested-album-access-camera-access-etc/19694/3

Gyroscope
Text to speech
Local Notifications
Gesture Support
Social
Payments
Advertising

**Comment by ricardoquesada** [comment]
What do you mean by Text-to-Speech ?

I think these features should be divided in two:

a)
those features that are offered by the device itself. eg: camera, gyroscope, etc.

b)
those features that are services. eg: social, payments, advertising

this issue should only cover a)... a different issue should be created for b).

regarding a)... this is the list so far, any other feature ?
- Gyroscope
- Camera
- Gestures
- Microphone
- Photo Albums
- Geolocalization

**Comment by 0xJimmyBeh** [comment]
Those features are copy from the comments of forum post as summary.

From what i understand, Text-to-Speech is more to feature provided by the app itself, so should not related to this issue.

I'm not sure what mobile features does Cocos2d-X provided, so i just listed out what may fall on category a)
- Gyroscope
- Camera
- Gestures
- Microphone
- Photo Albums
- Geolocation (GPS)
- Magnetic Sensor
- Light Sensor
- Proximity Sensor
- Vibration
- Accelerometer (Implemented)
- NFC

Does NFC consider a mobile feature?

**Comment by ricardoquesada** [comment]
thanks.... probably NFC could be considered a mobile feature.

**Comment by 0xJimmyBeh** [comment]
Found Vibration is being implemented.

https://github.com/cocos2d/cocos2d-x/pull/10530
http://discuss.cocos2d-x.org/t/vibrate-requirement-collection/20207/23

**Comment by folgerhu** [comment]
Call system sharing API, like this:

![screen shot 2015-04-10 at 2 03 31 pm](https://cloud.githubusercontent.com/assets/3455415/7082680/73339eb0-df8a-11e4-8f11-2f142c3939ac.png)

**Comment by zii** [comment]
Hoo ah! So many new features!
