### ISSUE TITLE
ui::Text cause seperated letter - in persian or arabic

### ISSUE THREAD

**Issue by emadpres** [cocos2d/cocos2d-x#10309]
I did some project with `cocos2dx 2.x` and `CCLabelTTF` works fine with Persian(Farsi) fonts ( both Windows and Android output )
Now, when I do the same with `ui::Text` of `cocos2dx 3.3rc` ( and I think also `3.3` final ), I face the word's letter are breaking aprat in Android devices.
for clarity, check below screenshot:

![sceenshot](https://cloud.githubusercontent.com/assets/2047884/5975635/45575280-a898-11e4-8c16-9e9c7d67a1a5.jpg)

As you see top text's letter are separated unfortunately :(

PS:
This problem is about all persian fonts. but for more detail, the font which is used in screen shot is `BMorvarid.ttf` (Download link:http://awebfont.ir/fonts?cat_id=1&file_id=1065&file_type=ttf)

**Comment by MohHeader** [comment]
I have the same problem with Arabic fonts,
as a workaround try to use 
Label::createWithSystemFont method.

**Comment by Emadpres** [comment]
@MohHeader Thanks dude. I know that when I give a fake font name ( and make `ui::Text` to use system default font) letters look ok again. But I need to have not only sticked-together letters, but also use my desire font.

**Comment by MohHeader** [comment]
You can use your own font
Label::createWithSystemFont("Text", "fonts/font.ttf",  FONT_SIZE_INT );

**Comment by emadpres** [comment]
@MohHeader wow. Thanks my friend. your suggestion solve my problem ! Thanks a lot :+1:  :)
