### ISSUE TITLE
Apple/IOS 8.1 naming conventions are causing users to get apps rejected.

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#10312]
Forum chatter is stating that users using v3.2 and v3.3 and submitting to the App Store are having apps rejected due to the face "ios" is my default in the `Product Name`. This is due to the target containing "ios" in it and `Product Name` by default uses it. The simple change is manually changing `Product Name` however there some users feel that out of the box we are setting them up to have apps rejected because they dont realize how to change this as they might be new to Cocos2D and XCode.

If me change the target names this solves the issue for an "out of the box, no changes required" solution.

This was discussed here: http://discuss.cocos2d-x.org/t/apple-rejected-8-1-use-of-ios-in-app-bundle-name/19612/11

My feeling is that I can see why this is an issue for new users as I think experienced users know about this. We haven't heard a lot of users ever having an error with this before. At the same time  I can see that users might rush to create a game, get excited to deploy it and forget to look over build settings before submitting.

**Comment by walzer** [comment]
+1

We do create new games with target "YourProduct iOS" and "YourProduct Mac".
Please consider to change it, @minggo

**Comment by minggo** [comment]
Yep, i think we should modify the product name.
But we should use different names for iOS an Mac OS X to distinguish them.

How about `YourProduct-mobile` and `YourProduct-desktop`?

**Comment by slackmoehrle** [comment]
These names are perfect.

**Comment by natural-law** [comment]
I have rename the target name of xcode project in templates.
"iOS" is renamed to "-mobile"
"Mac" is renamed to "-desktop".
The related PR : https://github.com/cocos2d/cocos2d-x/pull/11660

**Comment by walzer** [comment]
Well done.
