### ISSUE TITLE
[v3.3] ui::TextField wrong Event happen

### ISSUE THREAD

**Issue by emadpres** [cocos2d/cocos2d-x#10311]
`ui::TextField` in v3.3 gives wrong `TextField::EventType`.
I test it in windows ( but maybe other platform also).

**Scenario:**
**TAP 1**: If you press on a `TextField` ,  the `ATTACH_WITH_IME` event happens.
**TAP 2**: if in this condition (you pressed once), touch the area again , you get two event (in sequence): `ATTACH_WITH_IME` === and immediately then==>  `DETACH_WITH_IME`.

Also after **TAP 2**, TextField is still in focus and you can type (and this is OK and expcted),  but the second event(`DETACH_WITH_IME`) is happening wrongly. I use this event to check if the focus is on `TextField` or not. But the second event (`DETACH_WITH_IME`) make me wrong.

**Comment by zilongshanren** [comment]
@Emadpres 
Thanks, we have transpose the the Attach event and Detach event in v3.4, please check it out.

**Comment by walzer** [comment]
Fixed in v3.4.
