### ISSUE TITLE
AudioEngine bug (iOS only)

### ISSUE THREAD

**Issue by joewan** [cocos2d/cocos2d-x#10314]
AudioPlayer.mm

```
alSourcePlay(_alSource);
_ready = true;
auto alError = alGetError();

if (alError != AL_NO_ERROR) {
    log("%s:alSourcePlay error code:%x\n", __FUNCTION__,alError);
    return false;
}
```

sometimes alError is -1.

my cocos2d-x's version is 3.3rc1.

**Comment by joewan** [comment]
@Dhilan007  I have provided code and res to @samuele3hu.

**Comment by joewan** [comment]
this bug will happen in both AudioEngine and SimpleAudioEngine on ios.

another question is about mutex,
why we do not use try_lock() in invokingCallbacks, AudioCache.mm
_callbackMutex.lock();

sometimes this will cause crash.  @minggo  @Dhilan007

**Comment by joewan** [comment]
maybe this bug is resource-related,
if we change "get_coin.mp3" to another sound res,  this bug disappear.
it is a little strange.

**Comment by WenhaiLin** [comment]
@joewan Thank you for feedback. Could you provide me the audio file for test?

**Comment by WenhaiLin** [comment]
@joewan Sorry, i have "get_coin.mp3" file already.

**Comment by joewan** [comment]
all bad sounds(like get_coin.mp3) have a common feature: it is single channel. @Dhilan007

**Comment by joewan** [comment]
after we change the sound res to 2-channel, it is fixed.
We'd better do some resource-checking, give users some warning info.

And we'd better add a reset function into audio engine.
User can reset audio engine during switching scene, it can reduce the problems brought by Audio Engine.  it can break the audio bugs from spreading everywhere.
maybe AudioEngine::stopAll can use in this situation,  but it does not reset all the audio engine.
After resetting, it becomes a new engine instance just like restart game. @minggo @Dhilan007

**Comment by zengKun2002** [comment]
i have the same problem.Change the single-channel to 2-channel, problem solved. Still dont know why?!

**Comment by walzer** [comment]
Sounds reasonable.
1. Add warning info or return false after resource checking
2. Consider the `AudioEngine::reset` design.

@WenhaiLin

**Comment by WenhaiLin** [comment]
@joewan I can't reproduce this issue on iPhone 4s(iOS 7.1.2) and iPhone 5s(iOS 8.3)

**Comment by WenhaiLin** [comment]
@joewan Is it has lower fault probability?

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12604

**Comment by joewan** [comment]
“after we change the sound res to 2-channel, it is fixed.
We'd better do some resource-checking, give users some warning info.

And we'd better add a reset function into audio engine.
User can reset audio engine during switching scene, it can reduce the problems brought by Audio Engine. it can break the audio bugs from spreading everywhere.
maybe AudioEngine::stopAll can use in this situation, but it does not reset all the audio engine.
After resetting, it becomes a new engine instance just like restart game.
1. Add warning info or return false after resource checking
2. Consider the AudioEngine::reset design.“

I am so sorry to reply so late.  @WenhaiLin @walzer
it will be very appreciate if we support "AudioEngine::reset" and resource checking.

And why we do not use fmod replace with OpenAL,
now AudioEngine brought us so the most trouble.
I feel so frustrated.

**Comment by ewersp** [comment]
I know this is an old thread, but I just wanted to share my joy in that converting a bunch of mono wavs to stereo resolved this issue for me on an ancient, SimpleAudioEngine (CocosDenshion) cocos2d-objc project. It seemed to only happen on the iPhone X (randomly some sounds would stop playing after 2-3 minutes of app usage), but this hail mary saved my bacon! Thanks!! :D
