### ISSUE TITLE
[v3.4 with cocos studio 2.1 and cocos code IDE 1.1.0] not working, simulator shows 3.4rc1, errors

### ISSUE THREAD

**Issue by hamburml** [cocos2d/cocos2d-x#10316]
http://discuss.cocos2d-x.org/t/update-project-to-cocos2d-x-3-4/19705

**Comment by hamburml** [comment]
i would appreciate some help here
_edit_

I know it! The v 3.4 final is working. It's the cocos2d.dll which is inside of templates/lua-template-runtime/runtime/win32. It's downloaded with download_deps (the v3_lua_runtime_1.9.zip). It is build for cocos2d-x v3.4rc1. The cocos studio readers changed between 3.4rc1 and 3.4final. So the dll isn't working with cocos studio 2.1. Please update the lua_runtimes so I am able to develop further! Thanks! @minggo @dabingnn

**Comment by hamburml** [comment]
Anything? You want to release v4 alpha0 this friday but 3.4 release has errors :(

**Comment by minggo** [comment]
@Michael-Hamburger 
I have asked @dualface to take a look.

**Comment by hamburml** [comment]
FYI. The lua-template-runtimes in version 4.0alpha0 is still from 3.4rc1.

![image](https://cloud.githubusercontent.com/assets/7239350/6438952/307bdacc-c0ce-11e4-88dc-096344a4176a.png)

**Comment by walzer** [comment]
Thanks for your feedback. Since v4.0-final is work, and we are taking lua-runtime back in v3.6, I think this issue has been resolved.
