### ISSUE TITLE
Error compiling clean HelloWorld sample with latest v3 branch

### ISSUE THREAD

**Issue by SilkyPants** [cocos2d/cocos2d-x#10324]
Hi,

I've noticed a problem after attempting to create a new project with the latest (commit 173578c) v3 branch. If I create a new cpp project and try to compile I get an error about compiling cocos2d/extensions/assets-manager/Downloader.cpp on android (used cocos compile -p android)

```
error: 'curl_multi_wait' was not declared in this scope
             rc = curl_multi_wait(multi_handle,nullptr, 0, MAX_WAIT_MSECS, &maxfd);
```

Also if I try to compile the sample for iOS/Mac I get the following errors

```
~/Documents/Development/Testing_Ground/Cocos2dX/HelloWorld/cocos2d/extensions/assets-manager/Downloader.cpp:635:18: Use of undeclared identifier 'curl_multi_wait'; did you mean 'curl_multi_fdset'?
~/Documents/Development/Testing_Ground/Cocos2dX/HelloWorld/cocos2d/extensions/assets-manager/Downloader.cpp:635:59: Cannot initialize a parameter of type 'fd_set *' with an rvalue of type 'int'
```

If I roll back the cocos2d folder in the project to one from a different project (according to the changelog it is cocos2d-x-3.3 Dec.12 2014) I can compile fine, but not with the latest.

Comparing my two version, it seems that it might have been cause by [this commit](https://github.com/cocos2d/cocos2d-x/commit/7328c2eea0938e8eb030ce8fa6bfa951efc51d2a#diff-11f51bb90efb4a010bda7bf7182e9fb3), but I unfortunately do not have a Linux machine to confirm or attempt to fix.

**Comment by zilongshanren** [comment]
@SilkyPantsDan 
Have you downloaded the latest 3rd-party deps? I mean you should run `python download-dpes.py` in your root directory of cocos2d-x.

**Comment by SilkyPants** [comment]
@andyque 

This was on a clone of the repository that had already been set up and dependancies downloaded, redownloading now.

Thanks for the help, confirming that it has fixed this issue. :)
