### ISSUE TITLE
如何选中3d场景中的模型

### ISSUE THREAD

**Issue by sss316** [cocos2d/cocos2d-x#10320]
3d世界中，因为相机视角是可移动的，所有每个模型显示在屏幕上的位置也不确定，
问题来了，我触摸屏幕，怎么得到我触摸了哪个模型？
例如：war3游戏中，必须选中敌人才能攻击它。

**Comment by super626** [comment]
@sss316 

3D模型有aabb属性，aabb是模型的包围盒
从相机发出一条射线与aabb判断是否相交，相交则为选中该模型。
auto size = Director::getInstance()->getWinSize();
Vec3 screenPos(x, y, 1.f); //z == 1.0 远裁剪面上的点
Vec3 posWorld;
camera->unproject(size, &screenPos, &posWorld); // convert it into world space
//cameraPos is the camera's position in world
Ray ray; //3d 射线
ray._origin = cameraPos;
ray._direction = posWorld - cameraPos;

//decide which sprite3d to pick up
foreach sprite3d in sprite3ds
        if (ray.intersects(sprite3d->getAABB()))
             {
                //intersect this
                break;
             }

如果可能多个sprite3D跟射线相交可以选择一个最近的aabb对应的Sprite3D最为拾取对象。这样参照intersects的最后一个参数distance，该参数表示从origin出发多远与aabb相交。
可以在所有相交的aabb中找个distance最近的。

**Comment by sss316** [comment]
Thanks!!

在 2015-02-06 14:58:20，"XiaoYang" notifications@github.com 写道：

@sss316

3D模型有aabb属性，aabb是模型的包围盒
从相机发出一条射线与aabb判断是否相交，相交则为选中该模型。
auto size = Director::getInstance()->getWinSize();
Vec3 screenPos(x, y, 1.f); //z == 1.0 远裁剪面上的点
Vec3 posWorld;
camera->unproject(size, &screenPos, &posWorld); // convert it into world space
//cameraPos is the camera's position in world
Ray ray; //3d 射线
ray._origin = cameraPos;
ray._direction = posWorld - cameraPos;

//decide which sprite3d to pick up
foreach sprite3d in sprite3ds
if (ray.intersects(sprite3d->getAABB()))
{
//intersect this
break;
}

如果可能多个sprite3D跟射线相交可以选择一个最近的aabb对应的Sprite3D最为拾取对象。这样参照intersects的最后一个参数distance，该参数表示从origin出发多远与aabb相交。
可以在所有相交的aabb中找个distance最近的。
