### ISSUE TITLE
 Label::createWithBMFont and text with accents does not show

### ISSUE THREAD

**Issue by KrissMu** [cocos2d/cocos2d-x#10321]
Hi,

I'm trying to use image based fonts (with a PNG and the associated .fnt file) and to display text containing accents with it.

It does not work, the labels are not shown at all.
After investigation, I found that setString() calls StringUtils::UTF8ToUTF16() that will consider the accent as invalid character (in ConvertUTF.c) since its ASCII value is not in the range of 0x80 - 0xC2 (128 - 194).

Thanks

**Comment by WenhaiLin** [comment]
@KrissMu Could you please make a sample project/code for reproduced this  issue?

**Comment by KrissMu** [comment]
I can't provide full code, but this should behave the same that mine:

```
auto label = cocos2d::Label::createWithBMFont("fonts/futura-48.fnt", "Démarrer");
```

It will call:
- Label::setString
  - StringUtils::UTF8ToUTF16
    - UTF8ToUTF16
      - llvm::ConvertUTF8toWide
        - ConvertUTF8toUTF16
          - isLegalUTF8

The last will return false while processing the "é" character.

```
case 3: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false;
```

The hex code for "é" is 233, the code uses the table "trailingBytesForUTF8", maybe the problem is related to this.

**Comment by WenhaiLin** [comment]
@KrissMu The 'é' character without appearing to show cause by the 'futura-48.fnt' file not contains the 'é' character. What font that you use in your project?

**Comment by KrissMu** [comment]
I modified the picture and the .fnt file to include the missing character. Also, note that the issue is not the character is missing but the whole label does not show.

**Comment by WenhaiLin** [comment]
@KrissMu  Could you provide me the font file for test?

**Comment by KrissMu** [comment]
Well I'm not sure how to include non-image files here, so I'll put the contents of the file.

Image:

![futura-48](https://cloud.githubusercontent.com/assets/9886322/6002161/51c929fc-aaf1-11e4-88b0-d07d2847ab11.png)

fmt file:

info face="Futura-CondensedExtraBold" size=48 bold=0 italic=0 charset="" unicode=0 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=2,2
common lineHeight=62 base=48 scaleW=512 scaleH=256 pages=1 packed=0
page id=0 file="futura-48.png"
chars count=96
char id=92 x=2 y=2 width=35 height=56 xoffset=0 yoffset=7 xadvance=32 page=0 chnl=0 letter="\"
char id=47 x=39 y=2 width=35 height=56 xoffset=-1 yoffset=7 xadvance=32 page=0 chnl=0 letter="/"
char id=125 x=76 y=2 width=22 height=56 xoffset=-1 yoffset=7 xadvance=19 page=0 chnl=0 letter="}"
char id=123 x=100 y=2 width=21 height=56 xoffset=1 yoffset=7 xadvance=19 page=0 chnl=0 letter="{"
char id=40 x=123 y=2 width=19 height=56 xoffset=1 yoffset=7 xadvance=18 page=0 chnl=0 letter="("
char id=41 x=144 y=2 width=19 height=56 xoffset=0 yoffset=7 xadvance=18 page=0 chnl=0 letter=")"
char id=91 x=165 y=2 width=19 height=56 xoffset=2 yoffset=7 xadvance=18 page=0 chnl=0 letter="["
char id=93 x=186 y=2 width=19 height=56 xoffset=0 yoffset=7 xadvance=18 page=0 chnl=0 letter="]"
char id=106 x=207 y=2 width=16 height=55 xoffset=0 yoffset=8 xadvance=13 page=0 chnl=0 letter="j"
char id=36 x=225 y=2 width=24 height=52 xoffset=3 yoffset=5 xadvance=28 page=0 chnl=0 letter="$"
char id=124 x=251 y=2 width=15 height=50 xoffset=7 yoffset=10 xadvance=27 page=0 chnl=0 letter="|"
char id=81 x=268 y=2 width=33 height=46 xoffset=0 yoffset=10 xadvance=31 page=0 chnl=0 letter="Q"
char id=100 x=303 y=2 width=28 height=45 xoffset=0 yoffset=7 xadvance=26 page=0 chnl=0 letter="d"
char id=98 x=333 y=2 width=28 height=45 xoffset=1 yoffset=7 xadvance=26 page=0 chnl=0 letter="b"
char id=107 x=363 y=2 width=29 height=44 xoffset=1 yoffset=7 xadvance=26 page=0 chnl=0 letter="k"
char id=63 x=394 y=2 width=28 height=44 xoffset=1 yoffset=8 xadvance=27 page=0 chnl=0 letter="?"
char id=104 x=424 y=2 width=27 height=44 xoffset=1 yoffset=7 xadvance=26 page=0 chnl=0 letter="h"
char id=102 x=453 y=2 width=21 height=44 xoffset=-1 yoffset=7 xadvance=16 page=0 chnl=0 letter="f"
char id=33 x=476 y=2 width=16 height=44 xoffset=2 yoffset=8 xadvance=17 page=0 chnl=0 letter="!"
char id=108 x=494 y=2 width=14 height=44 xoffset=1 yoffset=7 xadvance=13 page=0 chnl=0 letter="l"
char id=37 x=2 y=60 width=39 height=43 xoffset=0 yoffset=9 xadvance=37 page=0 chnl=0 letter="%"
char id=105 x=43 y=60 width=16 height=43 xoffset=0 yoffset=8 xadvance=13 page=0 chnl=0 letter="i"
char id=64 x=61 y=60 width=38 height=42 xoffset=1 yoffset=10 xadvance=37 page=0 chnl=0 letter="@"
char id=38 x=101 y=60 width=36 height=42 xoffset=1 yoffset=10 xadvance=34 page=0 chnl=0 letter="&"
char id=79 x=139 y=60 width=33 height=42 xoffset=0 yoffset=10 xadvance=30 page=0 chnl=0 letter="O"
char id=71 x=174 y=60 width=32 height=42 xoffset=0 yoffset=10 xadvance=30 page=0 chnl=0 letter="G"
char id=48 x=208 y=60 width=31 height=42 xoffset=0 yoffset=10 xadvance=28 page=0 chnl=0 letter="0"
char id=85 x=241 y=60 width=30 height=42 xoffset=1 yoffset=10 xadvance=29 page=0 chnl=0 letter="U"
char id=51 x=273 y=60 width=29 height=42 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="3"
char id=54 x=304 y=60 width=29 height=42 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="6"
char id=53 x=335 y=60 width=29 height=42 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="5"
char id=56 x=366 y=60 width=29 height=42 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="8"
char id=103 x=397 y=60 width=28 height=42 xoffset=0 yoffset=21 xadvance=26 page=0 chnl=0 letter="g"
char id=112 x=427 y=60 width=28 height=42 xoffset=1 yoffset=21 xadvance=26 page=0 chnl=0 letter="p"
char id=113 x=457 y=60 width=28 height=42 xoffset=0 yoffset=21 xadvance=26 page=0 chnl=0 letter="q"
char id=67 x=2 y=105 width=26 height=42 xoffset=0 yoffset=10 xadvance=24 page=0 chnl=0 letter="C"
char id=83 x=30 y=105 width=24 height=42 xoffset=0 yoffset=10 xadvance=21 page=0 chnl=0 letter="S"
char id=74 x=56 y=105 width=21 height=42 xoffset=-1 yoffset=10 xadvance=19 page=0 chnl=0 letter="J"
char id=87 x=79 y=105 width=45 height=41 xoffset=-1 yoffset=10 xadvance=40 page=0 chnl=0 letter="W"
char id=77 x=126 y=105 width=43 height=41 xoffset=0 yoffset=10 xadvance=41 page=0 chnl=0 letter="M"
char id=65 x=171 y=105 width=33 height=41 xoffset=-1 yoffset=10 xadvance=28 page=0 chnl=0 letter="A"
char id=86 x=206 y=105 width=32 height=41 xoffset=-1 yoffset=10 xadvance=28 page=0 chnl=0 letter="V"
char id=88 x=240 y=105 width=32 height=41 xoffset=-1 yoffset=10 xadvance=28 page=0 chnl=0 letter="X"
char id=90 x=274 y=105 width=32 height=41 xoffset=-1 yoffset=10 xadvance=27 page=0 chnl=0 letter="Z"
char id=89 x=308 y=105 width=31 height=41 xoffset=-1 yoffset=10 xadvance=27 page=0 chnl=0 letter="Y"
char id=52 x=341 y=105 width=31 height=41 xoffset=0 yoffset=10 xadvance=28 page=0 chnl=0 letter="4"
char id=75 x=374 y=105 width=31 height=41 xoffset=1 yoffset=10 xadvance=29 page=0 chnl=0 letter="K"
char id=82 x=407 y=105 width=31 height=41 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="R"
char id=55 x=440 y=105 width=31 height=41 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="7"
char id=68 x=473 y=105 width=30 height=41 xoffset=1 yoffset=10 xadvance=29 page=0 chnl=0 letter="D"
char id=78 x=2 y=149 width=30 height=41 xoffset=1 yoffset=10 xadvance=30 page=0 chnl=0 letter="N"
char id=50 x=34 y=149 width=30 height=41 xoffset=0 yoffset=10 xadvance=28 page=0 chnl=0 letter="2"
char id=66 x=66 y=149 width=30 height=41 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="B"
char id=72 x=98 y=149 width=29 height=41 xoffset=1 yoffset=10 xadvance=29 page=0 chnl=0 letter="H"
char id=80 x=129 y=149 width=29 height=41 xoffset=1 yoffset=10 xadvance=27 page=0 chnl=0 letter="P"
char id=57 x=160 y=149 width=29 height=41 xoffset=1 yoffset=10 xadvance=28 page=0 chnl=0 letter="9"
char id=121 x=191 y=149 width=29 height=41 xoffset=-1 yoffset=21 xadvance=24 page=0 chnl=0 letter="y"
char id=35 x=222 y=149 width=27 height=41 xoffset=2 yoffset=10 xadvance=28 page=0 chnl=0 letter="#"
char id=84 x=251 y=149 width=25 height=41 xoffset=-1 yoffset=10 xadvance=20 page=0 chnl=0 letter="T"
char id=69 x=278 y=149 width=23 height=41 xoffset=1 yoffset=10 xadvance=22 page=0 chnl=0 letter="E"
char id=70 x=303 y=149 width=22 height=41 xoffset=1 yoffset=10 xadvance=21 page=0 chnl=0 letter="F"
char id=76 x=327 y=149 width=22 height=41 xoffset=1 yoffset=10 xadvance=20 page=0 chnl=0 letter="L"
char id=49 x=351 y=149 width=18 height=41 xoffset=6 yoffset=10 xadvance=28 page=0 chnl=0 letter="1"
char id=73 x=371 y=149 width=15 height=41 xoffset=1 yoffset=10 xadvance=14 page=0 chnl=0 letter="I"
char id=60 x=388 y=149 width=29 height=39 xoffset=1 yoffset=11 xadvance=28 page=0 chnl=0 letter="<"
char id=62 x=419 y=149 width=29 height=39 xoffset=1 yoffset=11 xadvance=28 page=0 chnl=0 letter=">"
char id=59 x=450 y=149 width=20 height=39 xoffset=-2 yoffset=21 xadvance=14 page=0 chnl=0 letter=";"
char id=116 x=472 y=149 width=20 height=37 xoffset=-1 yoffset=14 xadvance=16 page=0 chnl=0 letter="t"
char id=111 x=2 y=192 width=28 height=31 xoffset=0 yoffset=21 xadvance=26 page=0 chnl=0 letter="o"
char id=97 x=32 y=192 width=28 height=31 xoffset=0 yoffset=21 xadvance=26 page=0 chnl=0 letter="a"
char id=101 x=62 y=192 width=28 height=31 xoffset=0 yoffset=21 xadvance=26 page=0 chnl=0 letter="e"
char id=117 x=92 y=192 width=27 height=31 xoffset=1 yoffset=21 xadvance=27 page=0 chnl=0 letter="u"
char id=115 x=121 y=192 width=24 height=31 xoffset=0 yoffset=21 xadvance=21 page=0 chnl=0 letter="s"
char id=99 x=147 y=192 width=19 height=31 xoffset=0 yoffset=21 xadvance=16 page=0 chnl=0 letter="c"
char id=58 x=168 y=192 width=16 height=31 xoffset=0 yoffset=21 xadvance=14 page=0 chnl=0 letter=":"
char id=119 x=186 y=192 width=41 height=30 xoffset=-1 yoffset=21 xadvance=37 page=0 chnl=0 letter="w"
char id=109 x=229 y=192 width=40 height=30 xoffset=1 yoffset=21 xadvance=39 page=0 chnl=0 letter="m"
char id=120 x=271 y=192 width=30 height=30 xoffset=-1 yoffset=21 xadvance=26 page=0 chnl=0 letter="x"
char id=118 x=303 y=192 width=29 height=30 xoffset=-1 yoffset=21 xadvance=24 page=0 chnl=0 letter="v"
char id=110 x=334 y=192 width=27 height=30 xoffset=1 yoffset=21 xadvance=26 page=0 chnl=0 letter="n"
char id=122 x=363 y=192 width=26 height=30 xoffset=0 yoffset=21 xadvance=23 page=0 chnl=0 letter="z"
char id=114 x=391 y=192 width=21 height=30 xoffset=1 yoffset=21 xadvance=18 page=0 chnl=0 letter="r"
char id=43 x=414 y=192 width=29 height=29 xoffset=1 yoffset=16 xadvance=28 page=0 chnl=0 letter="+"
char id=42 x=445 y=192 width=25 height=24 xoffset=3 yoffset=7 xadvance=28 page=0 chnl=0 letter="*"
char id=94 x=472 y=192 width=31 height=23 xoffset=-1 yoffset=10 xadvance=27 page=0 chnl=0 letter="^"
char id=44 x=2 y=225 width=19 height=22 xoffset=-2 yoffset=38 xadvance=14 page=0 chnl=0 letter=","
char id=34 x=23 y=225 width=24 height=20 xoffset=0 yoffset=10 xadvance=22 page=0 chnl=0 letter="""
char id=39 x=49 y=225 width=14 height=20 xoffset=0 yoffset=10 xadvance=12 page=0 chnl=0 letter="'"
char id=61 x=65 y=225 width=29 height=19 xoffset=1 yoffset=21 xadvance=28 page=0 chnl=0 letter="="
char id=46 x=96 y=225 width=16 height=16 xoffset=0 yoffset=36 xadvance=14 page=0 chnl=0 letter="."
char id=126 x=114 y=225 width=31 height=15 xoffset=4 yoffset=6 xadvance=36 page=0 chnl=0 letter="~"
char id=96 x=147 y=225 width=15 height=13 xoffset=5 yoffset=10 xadvance=27 page=0 chnl=0 letter="`"
char id=45 x=164 y=225 width=16 height=12 xoffset=-1 yoffset=30 xadvance=11 page=0 chnl=0 letter="-"
char id=95 x=182 y=225 width=32 height=11 xoffset=-1 yoffset=49 xadvance=27 page=0 chnl=0 letter="_"
char id=32 x=216 y=225 width=0 height=0 xoffset=-106 yoffset=168 xadvance=14 page=0 chnl=0 letter="space"
char id=32 x=227 y=221 width=0 height=0 xoffset=-106 yoffset=168 xadvance=14 page=0 chnl=0 letter="space"
char id=130 x=227 y=221 width=28 height=35 xoffset=0 yoffset=10 xadvance=26 page=0 chnl=0 letter="é"
kernings count=82
kerning first=81 second=81 amount=-1
kerning first=63 second=93 amount=-2
kerning first=63 second=100 amount=-3
kerning first=63 second=98 amount=-3
kerning first=63 second=37 amount=-5
kerning first=63 second=38 amount=-5
kerning first=63 second=90 amount=-5
kerning first=63 second=78 amount=-5
kerning first=63 second=80 amount=-5
kerning first=63 second=84 amount=-2
kerning first=63 second=76 amount=-5
kerning first=63 second=58 amount=-1
kerning first=63 second=94 amount=-5
kerning first=63 second=44 amount=-4
kerning first=63 second=96 amount=-2
kerning first=63 second=32 amount=-1
kerning first=65 second=93 amount=-2
kerning first=65 second=100 amount=-2
kerning first=65 second=37 amount=-2
kerning first=65 second=38 amount=-2
kerning first=65 second=90 amount=-3
kerning first=65 second=80 amount=-3
kerning first=65 second=84 amount=-1
kerning first=65 second=76 amount=-4
kerning first=65 second=44 amount=-4
kerning first=65 second=96 amount=-2
kerning first=55 second=100 amount=-2
kerning first=55 second=63 amount=-4
kerning first=55 second=65 amount=-4
kerning first=55 second=68 amount=-4
kerning first=55 second=66 amount=-4
kerning first=55 second=32 amount=-2
kerning first=68 second=92 amount=-4
kerning first=68 second=91 amount=-4
kerning first=68 second=37 amount=-3
kerning first=68 second=38 amount=-3
kerning first=68 second=90 amount=-4
kerning first=68 second=80 amount=-4
kerning first=68 second=84 amount=-2
kerning first=68 second=76 amount=-4
kerning first=68 second=97 amount=-3
kerning first=68 second=44 amount=-4
kerning first=68 second=96 amount=-3
kerning first=68 second=32 amount=-1
kerning first=66 second=93 amount=-1
kerning first=66 second=37 amount=-1
kerning first=66 second=38 amount=-1
kerning first=66 second=90 amount=-1
kerning first=66 second=80 amount=-1
kerning first=66 second=76 amount=-2
kerning first=66 second=44 amount=-2
kerning first=66 second=96 amount=-1
kerning first=70 second=125 amount=-5
kerning first=70 second=123 amount=-5
kerning first=49 second=44 amount=-3
kerning first=60 second=125 amount=-5
kerning first=60 second=123 amount=-5
kerning first=60 second=81 amount=-1
kerning first=59 second=41 amount=-3
kerning first=59 second=101 amount=-1
kerning first=59 second=44 amount=-4
kerning first=59 second=32 amount=-1
kerning first=58 second=81 amount=-3
kerning first=58 second=61 amount=-3
kerning first=43 second=35 amount=-1
kerning first=42 second=105 amount=-3
kerning first=44 second=100 amount=-1
kerning first=44 second=98 amount=-1
kerning first=44 second=63 amount=-4
kerning first=44 second=65 amount=-4
kerning first=44 second=68 amount=-4
kerning first=44 second=66 amount=-2
kerning first=44 second=97 amount=-1
kerning first=44 second=32 amount=-3
kerning first=61 second=63 amount=-1
kerning first=61 second=65 amount=-1
kerning first=61 second=68 amount=-1
kerning first=61 second=66 amount=-1
kerning first=32 second=63 amount=-1
kerning first=32 second=71 amount=-3
kerning first=32 second=68 amount=-1
kerning first=32 second=44 amount=-3

**Comment by WenhaiLin** [comment]
The UTF16 code for 'é' character is 233,please view  the image
![20150202231341](https://cloud.githubusercontent.com/assets/5234286/6002798/7c17e3de-ab31-11e4-998c-4bebf6f98857.png)

**Comment by WenhaiLin** [comment]
@KrissMu You can test the code-set conversion like this:

``` cpp
#include <codecvt>
//...
std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> cvt;
//...
auto utf16String = cvt.from_bytes(utf8String);
```

**Comment by KrissMu** [comment]
Do you mean I need to change Cocos2d files or this can be done in my code ?

**Comment by WenhaiLin** [comment]
@KrissMu You should modified the font file.

**Comment by KrissMu** [comment]
Sorry, what should I change in the font file ? I just noticed that the font file I sent above contains "id=130" for letter="é", I modified it to 233 but with the same result.

The code that causes the failure does not seem to be related to the font file, but with the conversion to UTF16 that does not work for this character.

**Comment by WenhaiLin** [comment]
@KrissMu What platform you test on?

**Comment by KrissMu** [comment]
I'm working on Windows 7.

**Comment by Blackbunny12** [comment]
Hi folks!

The same problem occurs with Label::createWithTTF  with Labels containing a German Umlaut (öäü).

I made sure the TTF I use contains these characters. (Same String in MS Word with same TTF displays fine).

But all labels with those characters dont show up at all in my cocos2dx app. Other strings are displayed fine.

**Comment by KrissMu** [comment]
Yes it won't work for the exact same reason: the isLegalUTF8 function considers any "unusual" character as an error and returns false, that makes the whole UTF16 string empty, and then the Label draw function exits at the beginning.

I don't understand how this has not been detected earlier.

**Comment by KrissMu** [comment]
Any news about this ? Am I suppose to update Cocos2d sources to make it work ?

**Comment by KrissMu** [comment]
Hi,

Any news ?

**Comment by iPruch** [comment]
@KrissMu This is strange, because I use BMFonts with PNG and FNT files as well with Spanish (áéíóú and ñ) and it works perfectly. I checked my FNT file and the ID of 'é' is 233. The only difference I can spot is the `unicode=0` at the beginning, where in my FNT file it is `unicode=""` 

**Edit:** I just remembered that, for whatever reason (probably the one you noted), the `Label::createWithBMFont(args)` didn't work for me. But I got it working creating an empty label first and setting the FNT file and string afterwards:

``` c++
auto myLabel = Label::create();
myLabel->setBMFontFilePath("bitmapfont.fnt");
myLabel->setString("test: é");
```

**Comment by KrissMu** [comment]
Well, I updated my fnt file and my code to what you suggest but it still does not work for me.

My string is "Démarrer", and the problem comes in isLegalUTF8, the "case 3" is called because the trailingBytesForUTF8 table matches "3" with the 233 code.

If I replace this "3" value with "0", then it works. So the issue is with this "extra bytes to read" ...

So if I don't want to randomly change this table (I don't know the effects it could have), I replace the accent in my string with a special character I don't use and I modify the fnt file according to that ...

**Comment by iPruch** [comment]
@KrissMu Then I have no clue of why it is working for me. Which version of Cocos2D-X are you using? And editor/IDE? Operating System? It may be a codification incompatibility between the file where you have the string "Démarrer" (I don't know if you have it hard-coded inside a C++ class or stored in a localization file) and cocos.

In my case, I am using Cocos2D-X 3.4, Mac OS X Yosemite and Xcode, and all my classes and text files such as the JSON localization files are in UTF-8 codification.

I'm sorry I can't help you more.

**Comment by KrissMu** [comment]
I'm using 3.4 on Windows 7, Visual C++, but, again, the problem is in the code:

```
cocos2d\external\ConvertUTF\ConvertUTF.c
```

Contains

```
static const char trailingBytesForUTF8[256] = {
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,4,4,4,4,5,5,5,5
};
```

This is used to map the character code to a misterious number. For '233' (é), the mapping is "2", then the function isLegalUTF8 uses the value 2+1 = 3, and considers the value 233 as outside of valid range:

```
case 3: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false;
```

I don't want to waste your time, as I have a kind of work-around for this, but if you can check your call stack corresponding to the value setting (see my second message), and tell me where it goes adn which values are used for the processing of the "é" character (loop on characters is in ConvertUTF8toUTF16), I think it might help to understant where the difference is.

But don't worry if you can't, it seems that I'm the only one using accent and having the issue, so I guess it is something related to some local stuff I cannot identify.

**Comment by iPruch** [comment]
@KrissMu I can't tell you now as I'm not at work, but tomorrow I'll take a look to the call stack and report back.

**Comment by WenhaiLin** [comment]
@KrissMu `isLegalUTF8(const UTF8 *source, int length)`:The value of `*source` is 195 for `é`.I test on mac 10.10.3 and window 8.1.

**Comment by WenhaiLin** [comment]
I can't reproduced this issue.
![ii](https://cloud.githubusercontent.com/assets/5234286/7509625/bf3f83aa-f4c5-11e4-99a2-73d3a950dd42.png)

**Comment by iPruch** [comment]
@KrissMu Well, I took a look and this is what is happening for me:

![screenshot1](https://cloud.githubusercontent.com/assets/2997598/7510490/d515438c-f49c-11e4-9b62-9fd92cdae182.png)

![screenshot2](https://cloud.githubusercontent.com/assets/2997598/7510493/da902a0c-f49c-11e4-8524-75f6f35e8a4f.png)

The switch enters `case 2:` because the length received from parameter is 1 (+1), but it does not enter the if statement. It continues trough all the function without entering any if, so it ends returning true.

![screenshot3](https://cloud.githubusercontent.com/assets/2997598/7510561/a9229562-f49d-11e4-84a3-e33e37ed1d63.png)

Then, the difference is that in my case `unsigned short extraBytesToRead = trailingBytesForUTF8[*source];` from `ConvertUTF8toUTF16` is returning 1.

See the `*source` value: `'\xc3` (which is 195 in decimal if I'm correct. Don't know why this doesn't match the 233 code)
![screenshot4](https://cloud.githubusercontent.com/assets/2997598/7510881/f8117564-f4a0-11e4-83b2-631099ef6aa2.png)

I still think this could be a problem of the encoding of the file where you have the string with "é", so I would double check if your file is encoded in UTF-8.

I hope this helps!

**Comment by KrissMu** [comment]
@iPruch @WenhaiLin The problem seems to be related to the code of my "é", for some reason it is 233 when I debug the execution, where it is 195 (= 0xC3) in your test cases.
I don't think my input files are encoded in UTF-8, that seems to be the issue. I can't test for now, but as soon as I can, I'll report my results here !

Thanks for taking time to investigate this, it really helps !

**Comment by KrissMu** [comment]
Last comment just to confirm that it works perfectly with files converted to UTF8. It's worth noting that some editors can have a different default charset.

**Comment by iPruch** [comment]
I'm glad to read that! The different encodings and default configurations of text editors is a problem I can't understand why is still present nowadays. UTF-8 should be the default encoding in all text editors (or any program which reads/writes text files) and the 99% of these problems would go away.
