### ISSUE TITLE
Anchor point bug when loading csb file

### ISSUE THREAD

**Issue by transdb** [cocos2d/cocos2d-x#10334]
Hello,

in CSLoader.cpp there is bug with loading anchor point from csb file.
How to reproduce: 
1) in cocos studio place button to scene set anchor point 0.5, 0.5 set position in % to 50%
![screen shot 2015-02-02 at 21 48 34](https://cloud.githubusercontent.com/assets/6638080/6008919/82cf85ee-ab25-11e4-9b8d-d7f75ce64ff3.png)
2) export csb file
3) load in your cocos C++ project (in cocos studio preview it works)
4) observe, button is not in the middle of screen
![screen shot 2015-02-02 at 21 49 06](https://cloud.githubusercontent.com/assets/6638080/6008936/a24a9422-ab25-11e4-90d8-13af54ec95f9.png)

search this:
if(anchorx != 0.5f || anchory != 0.5f)
    node->setAnchorPoint(Point(anchorx, anchory));

should be this:
if(anchorx != 0.0f || anchory != 0.0f)
    node->setAnchorPoint(Point(anchorx, anchory));

Thank you.

**Comment by piotrros** [comment]
I wanted to make an issue about that. This is not a bug with cocos2d-x, it's a bug with cocos studio on mac os. Actually it only happens to me on mac os, try exporting csb on windows :)
And it's not only anchor point, the same goes for scale. Looks like cocos studio on mac os is writing wrong data to csb file.

**Comment by transdb** [comment]
ok thanks for info :)

**Comment by Cybertwip** [comment]
See https://github.com/cocos2d/cocos2d-x/issues/14520, we started using normalized positions and percent positions to solve this situation.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
