### ISSUE TITLE
请问如何对Sprite3D批次渲染?

### ISSUE THREAD

**Issue by gcheih** [cocos2d/cocos2d-x#10337]
请问如何对Sprite3D做批次渲染

**Comment by super626** [comment]
@gcheih 
你所说的批次渲染是什么概念呢。
我们目前对于单材质单mesh的Sprite3D如果相邻，有一定的优化措施，
1. 设置顶点buffer，渲染状态
2. 渲染所有模型
所有模型公用顶点buffer及渲染状态。

把所有模型合并到一个渲染批次提交到显卡，无法做到，尤其是对于带骨骼动画的模型，合并起来很复杂，动态合并代价也大，不建议使用。

**Comment by gcheih** [comment]
@super626 
我是想做Dynamic batching:在一定范围内去判断在同个material的mesh做mesh合并合并到一个渲染批次提交到显卡，以及可能的话，场景内所有静态物件可以一次做合并的static batching
所以你认为这两种在现在的架构下，会有实行的困难，以及没有那个效益？

另外可否了解一下现阶段的mesh render优化更详细原理？
 谢谢！ QQ

**Comment by super626** [comment]
@gcheih 
理解你说的内容。
静态物体合并批次很容易，带骨骼动画的物体合并批次比较麻烦，意义不大。
但静态物体合并批次是否值得呢，也分情况。现在的架构实现起来很容易，但有个问题就是需要动态根据场景中的物体来合并批次，这个合并需要创建VBO，拷贝顶点数据，索引数据等等，这个代价很大的。所以这种方法不一定能提高效率。这种优化可以放到美术做模型阶段，就是美术不要把模型分的太细，这个本身就增加渲染批次了，那么模型太大好不好呢？也不好，3.4中可以开启视锥裁剪功能，可以剔除一部分模型，根本不用提交到GPU，如果模型太大，这个视锥裁剪就不起作用了。所以这也是一个平衡。

我们有同学做技术支持。吕龙，群里边论坛上都有他的身影，吼一下他就到。
