### ISSUE TITLE
How can I use "getNumBytesForUTF8(UTF8 firstByte)" In cocos2dx V3.4 version?

### ISSUE THREAD

**Issue by BangHee** [cocos2d/cocos2d-x#10349]
Hi

How can I use "getNumBytesForUTF8(UTF8 firstByte)" In cocos2dx V3.4 version?

I'm getting these unfamiliar errors when attempting to compile it

error LNK1120 and error LNK2019. 

What the check is going on ?

**Comment by walzer** [comment]
Please ask usage questions in the forum. Issue tracker here is only for bug report and new requests.
