### ISSUE TITLE
audios are playing together in android will crash

### ISSUE THREAD

**Issue by puckery** [cocos2d/cocos2d-x#10342]

**Comment by minggo** [comment]
@puckery 
How to reproduce it?
What's the engine version?

**Comment by puckery** [comment]
02-26 17:25:35.216: A/libc(21526): bionic/libstdc++/src/pure_virtual.cpp:6: void __cxa_pure_virtual(): assertion "!"Pure virtual function called. Are you calling virtual methods from a destructor?"" failed
02-26 17:25:35.216: A/libc(21526): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 21526 (mediaserver)
02-26 17:25:35.316: V/AudioFlinger(21526): presentationComplete() reset: mPresentationCompleteFrames 652937 audioHalFrames 4233
02-26 17:25:35.316: I/DEBUG(236): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
02-26 17:25:35.316: I/DEBUG(236): Build fingerprint: 'vivo/msm8226/msm8226:4.3/JLS36C/eng.compiler.20140829.112201:user/dev-keys'
02-26 17:25:35.316: I/DEBUG(236): Revision: '0'
02-26 17:25:35.316: I/DEBUG(236): pid: 21526, tid: 21526, name: mediaserver  >>> /system/bin/mediaserver <<<
02-26 17:25:35.316: I/DEBUG(236): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
02-26 17:25:35.316: I/DEBUG(236): Abort message: 'bionic/libstdc++/src/pure_virtual.cpp:6: void __cxa_pure_virtual(): assertion "!"Pure virtual function called. Are you calling virtual methods from a destructor?"" failed'
02-26 17:25:35.326: W/NativeCrashListener(995): Couldn't find ProcessRecord for pid 21526
02-26 17:25:35.326: D/NativeCrashListener(995): Closing socket connection: FileDescriptor[105]
02-26 17:25:35.406: D/WifiNative-wlan0(995): doString: SIGNAL_POLL
02-26 17:25:35.506: I/DEBUG(236):     r0 00000027  r1 00000000  r2 00000008  r3 deadbaad
02-26 17:25:35.506: I/DEBUG(236): AM write failure (32 / Broken pipe)
02-26 17:25:35.506: I/DEBUG(236):     r4 00000000  r5 bec281d4  r6 b6f3ca33  r7 00000000
02-26 17:25:35.506: I/DEBUG(236):     r8 00000000  r9 b7399110  sl 00000000  fp bec28a7c
02-26 17:25:35.506: I/DEBUG(236):     ip 00000000  sp bec281d0  lr b6f7322b  pc b6f70784  cpsr 60000030
02-26 17:25:35.506: I/DEBUG(236):     d0  6c2f63696e6f6962  d1  2b2b636474736269
02-26 17:25:35.506: I/DEBUG(236):     d2  7275702f6372732f  d3  6175747269765f65
02-26 17:25:35.506: I/DEBUG(236):     d4  2a65f23d2126832d  d5  3c8c2d9134253b58
02-26 17:25:35.506: I/DEBUG(236):     d6  000003e89cd522d1  d7  3f800000447a0000
02-26 17:25:35.506: I/DEBUG(236):     d8  0000000000000000  d9  0000000000000000
02-26 17:25:35.506: I/DEBUG(236):     d10 0000000000000000  d11 0000000000000000
02-26 17:25:35.506: I/DEBUG(236):     d12 0000000000000000  d13 0000000000000000
02-26 17:25:35.506: I/DEBUG(236):     d14 0000000000000000  d15 0000000000000000
02-26 17:25:35.506: I/DEBUG(236):     d16 642061206d6f7266  d17 6f74637572747365
02-26 17:25:35.506: I/DEBUG(236):     d18 206e6f6974636e75  d19 202e64656c6c6163
02-26 17:25:35.506: I/DEBUG(236):     d20 20756f7920657241  d21 20676e696c6c6163
02-26 17:25:35.506: I/DEBUG(236):     d22 206c617574726976  d23 2073646f6874656d
02-26 17:25:35.506: I/DEBUG(236):     d24 3f973dcde3ad9db2  d25 bf973dcdfaa04f01
02-26 17:25:35.506: I/DEBUG(236):     d26 3fe0000000000000  d27 4000000000000000
02-26 17:25:35.506: I/DEBUG(236):     d28 3ffcd21dbdf1fb71  d29 bfcd3dd59fd409e0
02-26 17:25:35.506: I/DEBUG(236):     d30 3ff0000000000000  d31 3f83a7bab3fa813c
02-26 17:25:35.506: I/DEBUG(236):     scr 60000010
02-26 17:25:35.516: I/DEBUG(236): backtrace:
02-26 17:25:35.516: I/DEBUG(236):     #00  pc 0001e784  /system/lib/libc.so
02-26 17:25:35.516: I/DEBUG(236):     #01  pc 0001c784  /system/lib/libc.so (abort+4)
02-26 17:25:35.516: I/DEBUG(236):     #02  pc 000123b9  /system/lib/libc.so
02-26 17:25:35.516: I/DEBUG(236):     #03  pc 000118c9  /system/lib/libc.so (__assert2+20)
02-26 17:25:35.516: I/DEBUG(236):     #04  pc 00034af5  /system/lib/libmediaplayerservice.so (android::MediaPlayerService::Client::notify(void_, int, int, int, android::Parcel const_)+144)
02-26 17:25:35.516: I/DEBUG(236):     #05  pc 0006357f  /system/lib/libstagefright.so
02-26 17:25:35.516: I/DEBUG(236):     #06  pc 00064d07  /system/lib/libstagefright.so (android::AwesomePlayer::notifyListener_l(int, int, int)+40)
02-26 17:25:35.516: I/DEBUG(236):     #07  pc 00067175  /system/lib/libstagefright.so (android::AwesomePlayer::seekTo_l(long long)+172)
02-26 17:25:35.516: I/DEBUG(236):     #08  pc 00067241  /system/lib/libstagefright.so (android::AwesomePlayer::seekTo(long long)+68)
02-26 17:25:35.516: I/DEBUG(236):     #09  pc 00033b93  /system/lib/libmediaplayerservice.so (android::MediaPlayerService::Client::seekTo(int)+24)
02-26 17:25:35.516: I/DEBUG(236):     #10  pc 0005996f  /system/lib/libmedia.so (android::BnMediaPlayer::onTransact(unsigned int, android::Parcel const&, android::Parcel_, unsigned int)+906)
02-26 17:25:35.516: I/DEBUG(236):     #11  pc 00018185  /system/lib/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel_, unsigned int)+60)
02-26 17:25:35.516: I/DEBUG(236):     #12  pc 0001bdb5  /system/lib/libbinder.so (android::IPCThreadState::executeCommand(int)+508)
02-26 17:25:35.516: I/DEBUG(236):     #13  pc 0001c1c3  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+182)
02-26 17:25:35.516: I/DEBUG(236):     #14  pc 00001f3d  /system/bin/mediaserver
02-26 17:25:35.516: I/DEBUG(236):     #15  pc 0000dd37  /system/lib/libc.so (__libc_init+50)
02-26 17:25:35.516: I/DEBUG(236):     #16  pc 00001980  /system/bin/mediaserver
02-26 17:25:35.516: I/DEBUG(236): stack:
02-26 17:25:35.526: I/DEBUG(236):          bec28190  00000000  
02-26 17:25:35.526: I/DEBUG(236):          bec28194  00000000  
02-26 17:25:35.526: I/DEBUG(236):          bec28198  ffffffff  
02-26 17:25:35.526: I/DEBUG(236):          bec2819c  b6f9d208  
02-26 17:25:35.526: I/DEBUG(236):          bec281a0  b6f9014d  /system/lib/libc.so
02-26 17:25:35.526: I/DEBUG(236):          bec281a4  bec281b6  [stack]
02-26 17:25:35.526: I/DEBUG(236):          bec281a8  b6f9a264  /system/lib/libc.so
02-26 17:25:35.526: I/DEBUG(236):          bec281ac  b6f9a1c4  /system/lib/libc.so
02-26 17:25:35.526: I/DEBUG(236):          bec281b0  00000000  
02-26 17:25:35.526: I/DEBUG(236):          bec281b4  b6f7322b  /system/lib/libc.so (_fwalk+34)
02-26 17:25:35.526: I/DEBUG(236):          bec281b8  b6f724d5  /system/lib/libc.so (_cleanup)
02-26 17:25:35.526: I/DEBUG(236):          bec281bc  bec281d4  [stack]
02-26 17:25:35.526: I/DEBUG(236):          bec281c0  b6f3ca33  /system/lib/libstdc++.so
02-26 17:25:35.526: I/DEBUG(236):          bec281c4  00000000  
02-26 17:25:35.526: I/DEBUG(236):          bec281c8  df0027ad  
02-26 17:25:35.526: I/DEBUG(236):          bec281cc  00000000  
02-26 17:25:35.526: I/DEBUG(236):     #00  bec281d0  b6f9d218  
02-26 17:25:35.526: I/DEBUG(236):          bec281d4  fffffbdf  
02-26 17:25:35.526: I/DEBUG(236):          bec281d8  b6fad000  
02-26 17:25:35.526: I/DEBUG(236):          bec281dc  000000af  
02-26 17:25:35.526: I/DEBUG(236):          bec281e0  ffffffff  
02-26 17:25:35.526: I/DEBUG(236):          bec281e4  00000000  
02-26 17:25:35.526: I/DEBUG(236):          bec281e8  00000003  
02-26 17:25:35.526: I/DEBUG(236):          bec281ec  bec28214  [stack]
02-26 17:25:35.526: I/DEBUG(236):          bec281f0  00000006  
02-26 17:25:35.526: I/DEBUG(236):          bec281f4  b6f6e788  /system/lib/libc.so (__pthread_clone)
02-26 17:25:35.526: I/DEBUG(236):     #01  bec281f8  00000000  
02-26 17:25:35.526: I/DEBUG(236):          bec281fc  b6f643bd  /system/lib/libc.so
02-26 17:25:35.526: I/DEBUG(236):     #02  bec28200  bec28624  [stack]
02-26 17:25:35.526: I/DEBUG(236):          bec28204  000000aa  
02-26 17:25:35.526: I/DEBUG(236):          bec28208  bec28214  [stack]
02-26 17:25:35.526: I/DEBUG(236):          bec2820c  bec282be  [stack]
02-26 17:25:35.526: I/DEBUG(236):          bec28210  bec28613  [stack]
02-26 17:25:35.526: I/DEBUG(236):          bec28214  6e6f6962  
02-26 17:25:35.526: I/DEBUG(236):          bec28218  6c2f6369  
02-26 17:25:35.526: I/DEBUG(236):          bec2821c  74736269  
02-26 17:25:35.526: I/DEBUG(236):          bec28220  2b2b6364  
02-26 17:25:35.526: I/DEBUG(236):          bec28224  6372732f  
02-26 17:25:35.526: I/DEBUG(236):          bec28228  7275702f  
02-26 17:25:35.526: I/DEBUG(236):          bec2822c  69765f65  
02-26 17:25:35.526: I/DEBUG(236):          bec28230  61757472  
02-26 17:25:35.526: I/DEBUG(236):          bec28234  70632e6c  
02-26 17:25:35.526: I/DEBUG(236):          bec28238  3a363a70  
02-26 17:25:35.526: I/DEBUG(236):          bec2823c  696f7620  
02-26 17:25:35.526: I/DEBUG(236):          ........  ........
02-26 17:25:35.526: I/DEBUG(236): memory near r5:
02-26 17:25:35.526: I/DEBUG(236):     bec281b4 b6f7322b b6f724d5 bec281d4 b6f3ca33  
02-26 17:25:35.526: I/DEBUG(236):     bec281c4 00000000 df0027ad 00000000 b6f9d218  
02-26 17:25:35.526: I/DEBUG(236):     bec281d4 fffffbdf b6fad000 000000af ffffffff  
02-26 17:25:35.526: I/DEBUG(236):     bec281e4 00000000 00000003 bec28214 00000006  
02-26 17:25:35.526: I/DEBUG(236):     bec281f4 b6f6e788 00000000 b6f643bd bec28624  
02-26 17:25:35.526: I/DEBUG(236):     bec28204 000000aa bec28214 bec282be bec28613  
02-26 17:25:35.526: I/DEBUG(236):     bec28214 6e6f6962 6c2f6369 74736269 2b2b6364  
02-26 17:25:35.526: I/DEBUG(236):     bec28224 6372732f 7275702f 69765f65 61757472  
02-26 17:25:35.526: I/DEBUG(236):     bec28234 70632e6c 3a363a70 696f7620 5f5f2064  
02-26 17:25:35.526: I/DEBUG(236):     bec28244 5f617863 65727570 7269765f 6c617574  
02-26 17:25:35.526: I/DEBUG(236):     bec28254 203a2928 65737361 6f697472 2122206e  
02-26 17:25:35.526: I/DEBUG(236):     bec28264 72755022 69762065 61757472 7566206c  
02-26 17:25:35.526: I/DEBUG(236):     bec28274 6974636e 63206e6f 656c6c61 41202e64  
02-26 17:25:35.526: I/DEBUG(236):     bec28284 79206572 6320756f 696c6c61 7620676e  
02-26 17:25:35.526: I/DEBUG(236):     bec28294 75747269 6d206c61 6f687465 66207364  
02-26 17:25:35.526: I/DEBUG(236):     bec282a4 206d6f72 65642061 75727473 726f7463  
02-26 17:25:35.526: I/DEBUG(236): memory near r6:
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca10 8400b0b0 00000000 696f7600 5f5f2064  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca20 5f617863 65727570 7269765f 6c617574  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca30 62002928 696e6f69 696c2f63 64747362  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca40 2f2b2b63 2f637273 65727570 7269765f  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca50 6c617574 7070632e 50222100 20657275  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca60 74726976 206c6175 636e7566 6e6f6974  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca70 6c616320 2e64656c 65724120 756f7920  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca80 6c616320 676e696c 72697620 6c617574  
02-26 17:25:35.526: I/DEBUG(236):     b6f3ca90 74656d20 73646f68 6f726620 2061206d  
02-26 17:25:35.526: I/DEBUG(236):     b6f3caa0 74736564 74637572 223f726f 412f4e00  
02-26 17:25:35.526: I/DEBUG(236):     b6f3cab0 00000000 00000000 00000000 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b6f3cac0 00000000 00000000 00000000 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b6f3cad0 00000000 00000000 00000000 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b6f3cae0 00000000 00000000 00000000 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b6f3caf0 00000000 00000000 00000000 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b6f3cb00 00000000 00000000 00000000 00000000  
02-26 17:25:35.526: I/DEBUG(236): memory near r9:
02-26 17:25:35.526: I/DEBUG(236):     b73990f0 00000001 00000002 b73990e4 00000001  
02-26 17:25:35.526: I/DEBUG(236):     b7399100 00000000 000000ab b7399018 00005416  
02-26 17:25:35.526: I/DEBUG(236):     b7399110 b6ea25e8 b74f51f0 00000000 00000007  
02-26 17:25:35.526: I/DEBUG(236):     b7399120 00000004 b6ea2630 b750a7e8 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b7399130 00000007 00000004 00000000 b73991b0  
02-26 17:25:35.526: I/DEBUG(236):     b7399140 00000030 00000100 00000030 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b7399150 00000000 00000000 00000000 00010001  
02-26 17:25:35.526: I/DEBUG(236):     b7399160 00000000 00000000 00000000 b73992b8  
02-26 17:25:35.526: I/DEBUG(236):     b7399170 00000000 00000100 00000000 00000000  
02-26 17:25:35.526: I/DEBUG(236):     b7399180 00000000 00000000 00000000 00010001  
02-26 17:25:35.526: I/DEBUG(236):     b7399190 00000000 00000000 00000000 0000595c  
02-26 17:25:35.526: I/DEBUG(236):     b73991a0 00002773 00000100 00000000 0000010b  
02-26 17:25:35.526: I/DEBUG(236):     b73991b0 0000720c 80287202 b74e4a08 b74d3104  
02-26 17:25:35.526: I/DEBUG(236):     b73991c0 0000000a 00000010 0000595c 00002773  
02-26 17:25:35.526: I/DEBUG(236):     b73991d0 00000044 00000000 b5fbd0cc b5fbd110  
02-26 17:25:35.526: I/DEBUG(236):     b73991e0 b5fbd0cc 00002773 00000040 00000000  
02-26 17:25:35.526: I/DEBUG(236): memory near fp:
02-26 17:25:35.526: I/DEBUG(236):     bec28a5c 00000000 00000000 b6fc3984 b6fc5d00  
02-26 17:25:35.526: I/DEBUG(236):     bec28a6c b6fc5d08 b6fc5d14 bec28a80 00000000  
02-26 17:25:35.526: I/DEBUG(236):     bec28a7c b6fb1859 00000001 bec28b76 00000000  
02-26 17:25:35.526: I/DEBUG(236):     bec28a8c bec28b8e bec28bcb bec28bf3 bec28c06  
02-26 17:25:35.526: I/DEBUG(236):     bec28a9c bec28c1b bec28c36 bec28c49 bec28c62  
02-26 17:25:35.526: I/DEBUG(236):     bec28aac bec28c7c bec28c95 bec28f00 bec28f22  
02-26 17:25:35.526: I/DEBUG(236):     bec28abc bec28f45 bec28f71 bec28f9b bec28fc1  
02-26 17:25:35.526: I/DEBUG(236):     bec28acc 00000000 00000010 0007b0d7 00000006  
02-26 17:25:35.526: I/DEBUG(236):     bec28adc 00001000 00000011 00000064 00000003  
02-26 17:25:35.526: I/DEBUG(236):     bec28aec b6fc2034 00000004 00000020 00000005  
02-26 17:25:35.526: I/DEBUG(236):     bec28afc 00000008 00000007 b6fb0000 00000008  
02-26 17:25:35.526: I/DEBUG(236):     bec28b0c 00000000 00000009 b6fc3920 0000000b  
02-26 17:25:35.526: I/DEBUG(236):     bec28b1c 000003f5 0000000c 000003f5 0000000d  
02-26 17:25:35.526: I/DEBUG(236):     bec28b2c 000003ed 0000000e 000003ed 00000017  
02-26 17:25:35.526: I/DEBUG(236):     bec28b3c 00000000 00000019 bec28b62 0000001f  
02-26 17:25:35.526: I/DEBUG(236):     bec28b4c bec28fe4 0000000f bec28b72 00000000  
02-26 17:25:35.526: I/DEBUG(236): memory near sp:
02-26 17:25:35.526: I/DEBUG(236):     bec281b0 00000000 b6f7322b b6f724d5 bec281d4  
02-26 17:25:35.526: I/DEBUG(236):     bec281c0 b6f3ca33 00000000 df0027ad 00000000  
02-26 17:25:35.526: I/DEBUG(236):     bec281d0 b6f9d218 fffffbdf b6fad000 000000af  
02-26 17:25:35.526: I/DEBUG(236):     bec281e0 ffffffff 00000000 00000003 bec28214  
02-26 17:25:35.526: I/DEBUG(236):     bec281f0 00000006 b6f6e788 00000000 b6f643bd  
02-26 17:25:35.526: I/DEBUG(236):     bec28200 bec28624 000000aa bec28214 bec282be  
02-26 17:25:35.536: I/DEBUG(236):     bec28210 bec28613 6e6f6962 6c2f6369 74736269  
02-26 17:25:35.536: I/DEBUG(236):     bec28220 2b2b6364 6372732f 7275702f 69765f65  
02-26 17:25:35.536: I/DEBUG(236):     bec28230 61757472 70632e6c 3a363a70 696f7620  
02-26 17:25:35.536: I/DEBUG(236):     bec28240 5f5f2064 5f617863 65727570 7269765f  
02-26 17:25:35.536: I/DEBUG(236):     bec28250 6c617574 203a2928 65737361 6f697472  
02-26 17:25:35.536: I/DEBUG(236):     bec28260 2122206e 72755022 69762065 61757472  
02-26 17:25:35.536: I/DEBUG(236):     bec28270 7566206c 6974636e 63206e6f 656c6c61  
02-26 17:25:35.536: I/DEBUG(236):     bec28280 41202e64 79206572 6320756f 696c6c61  
02-26 17:25:35.536: I/DEBUG(236):     bec28290 7620676e 75747269 6d206c61 6f687465  
02-26 17:25:35.536: I/DEBUG(236):     bec282a0 66207364 206d6f72 65642061 75727473  
02-26 17:25:35.536: I/DEBUG(236): code around pc:
02-26 17:25:35.536: I/DEBUG(236):     b6f70764 461ce00b 2b006823 e026d1fb b12468e4  
02-26 17:25:35.536: I/DEBUG(236):     b6f70774 21014a18 6011447a 4b1247a0 24002027  
02-26 17:25:35.536: I/DEBUG(236):     b6f70784 f7fc7018 2106ee0e e884f7fe 5180f04f  
02-26 17:25:35.536: I/DEBUG(236):     b6f70794 a9029104 94022006 9403460a ec30f7fd  
02-26 17:25:35.536: I/DEBUG(236):     b6f707a4 46224629 f7fd2002 f7fcec3c 2106edfa  
02-26 17:25:35.536: I/DEBUG(236):     b6f707b4 e870f7fe f7fc2001 6960eaa6 d1dc2800  
02-26 17:25:35.536: I/DEBUG(236):     b6f707c4 bf00e7d4 deadbaad 00029894 ffffff9c  
02-26 17:25:35.536: I/DEBUG(236):     b6f707d4 0002cb38 0002cb1c 2400b510 aa04b088  
02-26 17:25:35.536: I/DEBUG(236):     b6f707e4 46699002 94014620 94039400 eb7ef7fd  
02-26 17:25:35.536: I/DEBUG(236):     b6f707f4 db0642a0 b1139b07 1c419806 98069106  
02-26 17:25:35.536: I/DEBUG(236):     b6f70804 4620e000 bd10b008 4b1eb40e b082b5f0  
02-26 17:25:35.536: I/DEBUG(236):     b6f70814 447b491d f107af00 585e021c f8522101  
02-26 17:25:35.536: I/DEBUG(236):     b6f70824 68354b04 f852607d 31015b04 d1fa2d00  
02-26 17:25:35.536: I/DEBUG(236):     b6f70834 320e008a 0507f022 0220f107 0d05ebad  
02-26 17:25:35.536: I/DEBUG(236):     b6f70844 f107603a 46690224 9400466d 4c04f852  
02-26 17:25:35.536: I/DEBUG(236):     b6f70854 f8453204 2c004f04 f8dfd1f8 f853c030  
02-26 17:25:35.536: I/DEBUG(236): code around lr:
02-26 17:25:35.536: I/DEBUG(236):     b6f73208 4a0e4b0d e92d447b 260041f0 4680589c  
02-26 17:25:35.536: I/DEBUG(236):     b6f73218 686768a5 f9b5e007 2b00300c 4628dd02  
02-26 17:25:35.536: I/DEBUG(236):     b6f73228 430647c0 3f013554 6824d5f5 d1ef2c00  
02-26 17:25:35.536: I/DEBUG(236):     b6f73238 e8bd4630 bf0081f0 00026dc8 ffffffc4  
02-26 17:25:35.536: I/DEBUG(236):     b6f73248 43f0e92d fb01461e 4b16f502 4916460f  
02-26 17:25:35.536: I/DEBUG(236):     b6f73258 447bb087 aa014614 20019001 95029203  
02-26 17:25:35.536: I/DEBUG(236):     b6f73268 90049505 681a585b b1124698 f0094630  
02-26 17:25:35.536: I/DEBUG(236):     b6f73278 4630fd26 f7ffa903 4681fe9c 0000f8d8  
02-26 17:25:35.536: I/DEBUG(236):     b6f73288 4630b110 fd28f009 0f00f1b9 9c05d005  
02-26 17:25:35.536: I/DEBUG(236):     b6f73298 1b284639 eaaef017 46204604 e8bdb007  
02-26 17:25:35.536: I/DEBUG(236):     b6f732a8 bf0083f0 00026d7a ffffff60 46036842  
02-26 17:25:35.536: I/DEBUG(236):     b6f732b8 60411e51 da012900 bb9ef000 f8126802  
02-26 17:25:35.536: I/DEBUG(236):     b6f732c8 601a0b01 00004770 4a104b0f b570447b  
02-26 17:25:35.536: I/DEBUG(236):     b6f732d8 589b4604 461e6819 f009b109 6860fcf0  
02-26 17:25:35.536: I/DEBUG(236):     b6f732e8 60651e45 da042d00 f0004620 4605fb85  
02-26 17:25:35.536: I/DEBUG(236):     b6f732f8 6822e003 5b01f812 68336022 4620b113  
02-26 17:25:35.536: I/DEBUG(236): memory map around fault addr deadbaad:
02-26 17:25:35.536: I/DEBUG(236):     bec08000-bec29000 rw- [stack]
02-26 17:25:35.536: I/DEBUG(236):     (no map for address)
02-26 17:25:35.536: I/DEBUG(236):     ffff0000-ffff1000 r-x [vectors]
02-26 17:25:35.706: W/AudioFlinger(21526): write blocked for 398 msecs, 1 delayed writes, thread 0xb5717008
02-26 17:25:35.706: W/AudioFlinger(21526): AudioOut_2: track underrun: 398 msecs
02-26 17:25:35.706: I/BootReceiver(995): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
02-26 17:25:35.716: W/CameraBase(20093): Camera service died!
02-26 17:25:35.716: I/ServiceManager(229): service 'media.camera' died
02-26 17:25:35.716: I/ServiceManager(229): service 'listen.service' died
02-26 17:25:35.716: I/ServiceManager(229): service 'media.audio_flinger' died
02-26 17:25:35.716: I/ServiceManager(229): service 'media.player' died
02-26 17:25:35.716: I/ServiceManager(229): service 'media.audio_policy' died
02-26 17:25:35.716: W/AudioSystem(995): AudioFlinger server died!
02-26 17:25:35.716: W/AudioSystem(2265): AudioPolicyService server died!
02-26 17:25:35.716: W/IMediaDeathNotifier(995): media server died
02-26 17:25:35.716: W/IMediaDeathNotifier(22876): media server died
02-26 17:25:35.716: W/AudioSystem(995): AudioPolicyService server died!
02-26 17:25:35.716: W/AudioSystem(22876): AudioFlinger server died!
02-26 17:25:35.716: E/libOpenSLES(22876): Error after prepare: 100
02-26 17:25:35.716: E/libOpenSLES(22876): Error after prepare: 100
02-26 17:25:35.716: E/libOpenSLES(22876): Error after prepare: 100
02-26 17:25:35.716: E/libOpenSLES(22876): Error after prepare: 100
02-26 17:25:35.966: W/libOpenSLES(22876): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:822: pthread 0x65d802b0 (tid 32684) sees object 0x64f93d98 was locked by pthread 0x5ddb49f0 (tid 22908) at frameworks/wilhelm/src/itf/IObject.c:411

**Comment by puckery** [comment]
@minggo 
cocos version 3.2

**Comment by walzer** [comment]
Which android device and android version?
I remember that Samsung i9100 series has a bug in android v2.2 or v2.3. If more than 32 sound effects are put into its audio buffer, the game will crash immediately.

This is a bug in Samsung i9100's hardware driver layer, it suffers all game on all engines. The only way to avoid it, is to limit the sound effect numbers in your game. Please remember: no more than 32 sound effect in one time.
