### ISSUE TITLE
Acceleration bug.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10346]
`version:` 3.4Final
`platform:` iphone
`issue:` the acceleration sprite will delay obviously after 30s. if you back to home screen, then return to the game, the direction of the acceleration is error.
`reproduce:` TestCpp-EventDispatcher-Sprite receives acceleration event test.

`ps:` this issue comes from the cocos support.

**Comment by minggo** [comment]
We should fix it in v3.x and synchronize to v4.

**Comment by WenhaiLin** [comment]
Accelerometer has lagged when the update interval of Accelerometer is too small on iOS. Fixed at https://github.com/cocos2d/cocos2d-x/pull/10436.
