### ISSUE TITLE
using removeAllChildren on Scene causes Camera to be destroyed

### ISSUE THREAD

**Issue by mannewalis** [cocos2d/cocos2d-x#10355]
Like the title says. The camera is added to the scene during creation, but if you call remove all children it destroys the camera. Why is the camera a child? Can't it be a protected member? The scene or the renderer should just visit its list of cameras directly, and not rely on the scene graph IMO.

**Comment by darkdukey** [comment]
Maybe put it in a Vector container so it will increase the reference count.

**Comment by super626** [comment]
@mannewalis 
@darkdukey 
Thanks. It is a problem should be fixed.

The advantage of treating the default camera as a child of scene is that it can move and rotate with scene.

What Nite said can not work well in some situation.
option 1,
auto scene = Scene::create();
scene->removeAllChildren(); //in fact, the scene is empty in the user's opinion
acene->addChild(sprite);
option 2,
auto scene = Scene::create();
acene->addChild(sprite);
The scene graph is different in the two above ways.

So there are two ways to fix it.
1. As what Justin said. But the default camera will not move with the scene.
2. Override the removeAllChildren in Scene, remove all children except the default camera.

What is your opinion?

**Comment by minggo** [comment]
> 1. Override the removeAllChildren in Scene, remove all children except the default camera.

I like this solution.
And i think we should separate transform from Node in v4.
