### ISSUE TITLE
新的V3.4中，new一个新工程编译好了运行时发现少了 MSVCR110.DLL。

### ISSUE THREAD

**Issue by syswow** [cocos2d/cocos2d-x#10356]
我的系统是WIN8.1 X64, VS 2013 DESKTOP EXPRESS, 
后来从http://www.microsoft.com/en-us/download/details.aspx?id=30679#
下载了Visual C++ Redistributable for Visual Studio 2012 Update 4 x86 才行。
请问这是为什么呢？ 3.4还依赖VS2012吗？

**Comment by minggo** [comment]
VS2013 should not depend on VS2012.
It is strange that you need to install VS2012 Update 4.
