### ISSUE TITLE
is this a bug? Sprite3D and Sprite mixture draw have different zorder between 3.4 and 3.4rc1[v3.4]

### ISSUE THREAD

**Issue by flamefox** [cocos2d/cocos2d-x#10353]
这是3.4的[this is v3.4]
![image](https://cloud.githubusercontent.com/assets/3197993/6024053/609f408e-ac03-11e4-9d37-34d9912f8388.png)

``` c++
auto spr = Sprite::create("Images/blocks.png");
    spr->setRotation3D(Vec3(-90, 0, 0));
    _layer3D->addChild(spr);
```

添加顺序绝对在sprite3d之前，
Camera3DTest.cpp的332行之后添加即可
add after Camera3DTest.cpp line 332.

这是3.4rc1的[this is v3.4rc1]
![image](https://cloud.githubusercontent.com/assets/3197993/6024122/ddaab07c-ac03-11e4-82cc-1c6995079b0b.png)

``` c++
    auto spr = Sprite::create("Images/blocks.png");
    spr->setPositionY(spr->getContentSize().height / 2);
    spr->setRotation3D(Vec3(-90, 0, 0));
    _layer3D->addChild(spr);
```

因为3d旋转锚点有问题，这里调整了下位置，可以看到角色和精灵的位置完全不一样啊。。我更认同3.4rc1的表现。。

**Comment by lvlonggame** [comment]
In 3.4final, you need to set the global-z like this "spr->setGlobalZOrder(-1)", after that ,the 3d-sprite will be drawn behind the 2d-sprite, just try it.

**Comment by flamefox** [comment]
at last, I use an empty node, and it works!

``` c++
    auto back = Sprite3D::create();  // create an empty node
    auto img = Sprite::create("Images/blocks.png"); 
    _layer3D->addChild(back);   
    img->setRotation3D(Vec3(-90,0,0));  
    back->addChild(img);
```

**Comment by darkdukey** [comment]
We did this change because the previous way don't supports camera rotation correctly.
