### ISSUE TITLE
Stats labels are recreated 3 times during launch

### ISSUE THREAD

**Issue by mannewalis** [cocos2d/cocos2d-x#10357]
createStatsLabel() is called 3 times during launch. This is a fairly expensive operation as the font atlas cache does not hold on to the atlas since no other labels refer to it.
1. setOpenGLView
2. setContentScaleFactor
3. updateDesignResolutionSize

Perhaps they should be marked as invalid and have the frame update do it, or just find a better place to put it.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10744
