### ISSUE TITLE
cocos2d-x v3.3 lock screen issue

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#10363]
Detail information please refer to [this ticket](http://discuss.cocos2d-x.org/t/cocos2d-x-v3-3-lock-screen-issue/19619).

**Comment by WenhaiLin** [comment]
I can't reproduced this issue.Test base on the latest code on github

**Comment by WenhaiLin** [comment]
This issue have been fixed.
https://github.com/cocos2d/cocos2d-x/pull/9711
https://github.com/cocos2d/cocos2d-x/pull/9931
