### ISSUE TITLE
UIListView显示都是正常的，但是截屏的图片：整张白色背景，UIListView背景是绿色的等问题

### ISSUE THREAD

**Issue by wangzongjun** [cocos2d/cocos2d-x#10361]
使用cocos2dx-2.2.4，关于截屏分享这一块，发现一个问题问题
CCScene中包含UIListView，使用如下函数截屏：
bool saveScreenshot(const string strImageName,string &strFullPath)
{
    CCSize size = CCDirector::sharedDirector()->getWinSize();
    CCRenderTexture\* texture = CCRenderTexture::create((int)size.width, (int)size.height);
    texture->setPosition(ccp(size.width/2, size.height/2));
    texture->begin();
    CCDirector::sharedDirector()->getRunningScene()->visit();
    texture->end();
    bool bRe = texture->saveToFile(strImageName.c_str(), kCCImageFormatJPEG);
    CC_SAFE_DELETE(texture);
    if(bRe)
        strFullPath = CCFileUtils::sharedFileUtils()->getWritablePath() + strImageName;
    return bRe ;
}
UIListView显示都是正常的，但是截屏的图片：整张白色背景，UIListView背景是绿色的等问题

网上说修改如下代码，也已经修改：
public class MainActivity extends Cocos2dxActivity {
public Cocos2dxGLSurfaceView onCreateView() {
Cocos2dxGLSurfaceView glSurfaceView = new Cocos2dxGLSurfaceView(this);
glSurfaceView.setEGLConfigChooser(5, 6, 5, 0, 16, 8);
return glSurfaceView;
}
}

**Comment by zilongshanren** [comment]
For saving screenshot with stencil buffer enabled, you should create the RenderTexture like this:

```
CCRenderTexture* texture = CCRenderTexture::create((int)size.width, (int)size.height, Texture2D::PixelFormat::RGBA8888, GL_DEPTH24_STENCIL8);

```

**Comment by wangzongjun** [comment]
![buy_gift](https://cloud.githubusercontent.com/assets/4986683/6035974/53027642-ac78-11e4-93c9-e8d6077b06d2.jpg)

**Comment by wangzongjun** [comment]
Thank you reply so soon.
Texture2D::PixelFormat::RGBA8888在2.2.4是什么？

**Comment by wangzongjun** [comment]
o ,i see kTexture2DPixelFormat_RGBA8888.

**Comment by wangzongjun** [comment]
All right now! Many thanks!
