### ISSUE TITLE
setTouchPriority() is misleading

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10366]
`version:` 2.2.x
`issue:` 

``` cpp
void CCLayer::setTouchPriority(int priority)
```

couldn't used to change the priority of the layer dynamically, it is easy to mislead developers.

`The real method is`

``` cpp
    CCDirector *pDirector=CCDirector::sharedDirector();
    pDirector->getTouchDispatcher()->setPriority(-127, this);
```

**Comment by walzer** [comment]
The mechanism of touch priority in v2.x is a big problem, and we have already refactor this in v3. You know it.

There's no plan to refactor the touch dispatching mechanism in v2.
