### ISSUE TITLE
Non-standard names and usage in function.lua

### ISSUE THREAD

**Issue by litefeel** [cocos2d/cocos2d-x#10371]
```
table.insertto
table.indexof
table.keyof
table.removebyvalue
```

Why not use camel name?

```
table.map
table.filter
```

why not return an new table?

**Comment by litefeel** [comment]
https://github.com/cocos2d/cocos2d-x/blob/v4-develop/cocos%2Fscripting%2Flua-bindings%2Fscript%2Fcocos2d%2Ffunctions.lua#L445-L502

**Comment by litefeel** [comment]
@minggo @dualface

**Comment by minggo** [comment]
@dualface
Please take a look.
I think @lite3 is right.

**Comment by dualface** [comment]
1. All functions in "functions.lua" file, used naming rule is same as Lua standard library, all chars is lowercase.
2. table.map(), table.filter() should return a new table, @lite3 is right.

**Comment by litefeel** [comment]
@dualface  and do not modify param value .

**Comment by litefeel** [comment]
@dualface 
I think we use cocos2dx  not pure base lua. so use camel name is OK.
like `string.formatnumberthousands` in function.lua. 
https://github.com/cocos2d/cocos2d-x/blob/v4-develop/cocos%2Fscripting%2Flua-bindings%2Fscript%2Fcocos2d%2Ffunctions.lua#L625

it's bad. it's so long, and not clear.
change to `string.formatNumberThousands`.
it's clear.
What you think?

so I think we can use camel name.

**Comment by dualface** [comment]
please close thie issue, thanks.

**Comment by dualface** [comment]
@pandamicro please close thie issue, thanks.
