### ISSUE TITLE
NewAudioEngine bug.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10381]
`version:` 3.4Final
`platform:` iPhone ( with siri )
`issue & reproduce:` open the Test-Cpp, New AudioEngine, audio control test, click the `play` button. now the music is playing, then press and hold the home button to show the siri interface, after that return to the Test-Cpp, music is stopped and couldn't play again.

**Comment by fusijie** [comment]
I open the issue here. @Dhilan007

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10440

**Comment by minggo** [comment]
@fusijie 
Could you please check it?

**Comment by fusijie** [comment]
@minggo @Dhilan007 thanks, it's fixed.
