### ISSUE TITLE
ui::TextField hitTest not working as expected

### ISSUE THREAD

**Issue by Elrinth** [cocos2d/cocos2d-x#10386]
If you do: setTouchSize and setTouchAreaEnabled(true) and have setAnchorPoint(Vec2::ANCHOR_MIDDLE_LEFT)
Then it will do the hit collision wrong. Plus why isn't the Rect function containsPoint used?

My suggested solution is replace the function code with (my code might be wrong, but it seems to work okay for me now):
bool TextField::hitTest(const Vec2 &pt)
{
    if (_useTouchArea)
    {
        Vec2 nsp = convertToNodeSpace(pt);
        Rect bb = Rect(-_touchWidth \* _anchorPoint.x, -_touchHeight \* _anchorPoint.y, _touchWidth, _touchHeight + _touchHeight \* _anchorPoint.y \* 0.5f);
        return bb.containsPoint(nsp);
    }
    else
        return Widget::hitTest(pt);
}

**Comment by walzer** [comment]
Unconfirmed and un-reproduced bug.
I think it's not very hard to fix, so put in v3.8 roadmap.
