### ISSUE TITLE
Add in Data or in Texture2D the initial file name as string member name

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#10384]
This is feature request
when set new Texture2D from file , if i don't keep track of the name of the file in some class 
i actually don't know which file i did setup the Texture2D.
it will be very useful to know it . by querying this member file 
something like :

```
Texture2D *texture = Director::getInstance()->getTextureCache()->addImage(filename);
texture->getFileNameStr();
```

**Comment by walzer** [comment]
Many developers, including us, are actually asking for this requirement.
The basic requirement is that, after add an image into the texture, I want to read its pixel data. So, we need the image file name.

@andyque is adding .9.png support in v3.7, he need this too. But @andyque worry about the memory consuming. We have a design in discussion in the last week.

**Comment by walzer** [comment]
Duplicate with #11349
