### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by JOOpdenhoevel** [cocos2d/cocos2d-x#10390]
A support for Raspberry Pi would be nice. You can't use the Linux-options, because the is no FMODX for ARM devices.

**Comment by zilongshanren** [comment]
@Janonard  I will try to port to Raspberry Pi this weekend. If I'm lucky, I will post the solution here.

**Comment by fusijie** [comment]
I am very interested in this issue.

**Comment by JOOpdenhoevel** [comment]
Maybe you can make it work without X, that would save resources.

**Comment by JOOpdenhoevel** [comment]
Another aspect of RaspPi-support: a possibility to switch between HDMI and analog audio output.

**Comment by elnormous** [comment]
Is there any progress on this?

**Comment by JOOpdenhoevel** [comment]
I've never heard anything since Feb..

**Comment by zilongshanren** [comment]
Sorry, @Janonard 
I'm really very busy these days...  I will do the porting soon, but I can't promise the exactly date.

**Comment by JOOpdenhoevel** [comment]
no problem!

**Comment by walzer** [comment]
I also have a Raspberry Pi. But considering the human resources, market share of Raspberry Pi and the task priorities, I had to say:
**Cocos2d-x have no plan to support Raspberry Pi in the near future.**

We can reopen and discuss this issue in 6 months later.

**Comment by stirem** [comment]
This would be a nice feature for using Cocos2d-x and Pi in homemade arcade machines ;) Especially with the Pi2's amazing gpu power!

**Comment by JOOpdenhoevel** [comment]
That's what thought when I opened this issue. The Raspberry Pi is already a common platform for emulating old games, so if cocos2d-x would support emulationstation, there would be hundreds or even thousands of devices waiting for new games. I should have wrote that when I opened this issue.

**Comment by partlyhuman** [comment]
It would also be very useful for developing games on custom hardware for installation art/advertising. I'm doing just this with custom sensors and display for a game you play throwing physical balls at a screen. Raspi is the perfect form-factor for our low-resolution LED array display, and serial interface to the ball sensors. I have experience with Cocos2d on iOS and was hoping to write the game code with Cocos2d-X and C++.

**Comment by stirem** [comment]
I have some experience with [openFrameworks](http://openframeworks.cc/setup/raspberrypi/) on the Raspberry Pi. openFrameworks is a similar type of open C++ library as Cocos2d-x, except it is not primarily targeting games, but creative coding in general. It has great graphical performance on the Pi. Maybe there are useful code there if someone with more experience then me, are into making Cocos2d-x run on the Pi?

**Comment by pengan1987** [comment]
I find someone was tried to port Cocos2d-x to ARM and OpenGLES, it was used to port for i.MX 6
https://github.com/yangosoft/cocos2d-x-arm-opengles
It seems will work on Raspberry Pi too (I haven't tried yet), at least we may estimate the work amount for RPi port.

**Comment by slackmoehrle** [comment]
@pengan1987 it's been quite a while since I tried to compile on Raspberry Pi. I am not sure where it stands at this point. What model Pi are you trying on?

**Comment by donmor** [comment]
Hey guys,
Recently I'm trying to build cocos2d-x on loongarch64. I commented out all tests and successfully made the project itself. I then created a demo project and tried compiling it. Now I fails on libfmod.so because it is incompatible. Maybe it can run on loongarch64 if I can make some fake fmod libraries, and so does aarch64.
