### ISSUE TITLE
flatbuffers main()

### ISSUE THREAD

**Issue by newnon** [cocos2d/cocos2d-x#10405]
flatbuffer already have main() in file flatc.cpp
it must be excluded from all project because of linker conflict with main()
Exemple 
CMakeLists.txt
set(FLATBUFFERS_SRC
./flatc.cpp
./idl_gen_cpp.cpp
./idl_gen_fbs.cpp
./idl_gen_general.cpp
./idl_gen_go.cpp
./idl_gen_text.cpp
./idl_parser.cpp
)
must be without flatc.cpp

**Comment by minggo** [comment]
@newnon 
Any problem of it?

**Comment by newnon** [comment]
Yes 2 main functions in one program raise linker error.
Duplicate symbol main ...
on some systems declaration of main can be different and you can get result program with entry point in flatbuffers main();

**Comment by minggo** [comment]
How to reproduce it?

**Comment by newnon** [comment]
try to compile it under linux with cmake. or under windows with mingw. on linux you will get linker error on windows can get wrong entry point. flatc.cpp - it is a simple test program it must not be compiled to library.

**Comment by minggo** [comment]
But the jenkins doesn't detect the compiling issue.
It uses cmake in linux.

**Comment by WenhaiLin** [comment]
@minggo I agree with @newnon, the 'flatc.cpp' file must not be compiled to library.

**Comment by minggo** [comment]
@Dhilan007 
Please fix it.

**Comment by newnon** [comment]
The same problem in android.mk

**Comment by minggo** [comment]
Now flatbuffer samples is not ocmpiled.
