### ISSUE TITLE
Label breakLineWithSpace (CJKUnicode) Issue

### ISSUE THREAD

**Issue by ebenmo** [cocos2d/cocos2d-x#10407]
Default TTF Label's Space can't break line when characters are CJKUnicode. 
I temporarily fixed this by modifying  function below:
bool LabelTextFormatter::multilineText(Label *theLabel)

//issue #8492:endless loop if not using system font, and constrained length is less than one character width
                if (isStartOfLine && last_word.size() == 0)
                    last_word.push_back(character);
                else
                    --j;

To:
if (isStartOfLine && tIndex == 0 && last_word.size() == 0)
                    last_word.push_back(character);
                else
                    --j;

**Comment by minggo** [comment]
@ebenmo 
cocos2d-x only supports utf-8.
