### ISSUE TITLE
Bug in Physics manual Lua binding

### ISSUE THREAD

**Issue by lzubiaur** [cocos2d/cocos2d-x#10411]
Hi, the PhysicsShape***::getPoints does not return any value in Lua and this is because the following functions in lua_cocos2dx_physics_manual.cpp should return 1 instead of 0.

lua_cocos2dx_physics_PhysicsShapeBox_getPoints
lua_cocos2dx_physics_PhysicsShapePolygon_getPoints
lua_cocos2dx_physics_PhysicsShapeEdgeBox_getPoints
lua_cocos2dx_physics_PhysicsShapeEdgePolygon_getPoints
lua_cocos2dx_physics_PhysicsShapeEdgeChain_getPoints

**Comment by samuele3hu** [comment]
I think you are right, i would fix it as soon as possible.
