### ISSUE TITLE
Why don't you delete ui/proj.win32/libui.vcxproj and filters file?

### ISSUE THREAD

**Issue by cpascal** [cocos2d/cocos2d-x#10419]
https://github.com/cocos2d/cocos2d-x/blob/v4-develop/cocos/ui/proj.win32/libui.vcxproj
https://github.com/cocos2d/cocos2d-x/blob/v4-develop/cocos/ui/proj.win32/libui.vcxproj.filters

They seems unmaintained files now.
- 'UIWebViewImpl-win32.cpp/h' (removed file because of ATL-dependencies) still exist in the vcxproj.
- 'UIEditBox/UIEditBoxImplWin.cpp' instead of 'UIEditBox/UIEditBoxImpl-win32.cpp' in the vcxproj.
- Other removed files(Win32InputBox.cpp, ...?) still exist in the vcxproj.
- Project Configuration Type is DLL instead of Static library.

Why don't you delete vcxproj and vcxproj.filters files?

**Comment by minggo** [comment]
@cpascal 
Thanks.
We will check it, and delete it if it is useless.

**Comment by zilongshanren** [comment]
@cpascal 
Thanks, we should remove it.

**Comment by zilongshanren** [comment]
@cpascal 
I have removed it in https://github.com/cocos2d/cocos2d-x/pull/10430
