### ISSUE TITLE
Vibrate phone effect missing in SimpleAudioEngine.

### ISSUE THREAD

**Issue by Dipakce** [cocos2d/cocos2d-x#10415]
Unable to vibrate the Phone either in iOS or android as SimpleAudioEngine Does not has a support for that.If vibrate effect is added somewhere else please let me know.

**Comment by minggo** [comment]
@Dipakce 
It is a feature required, but why does this effect needs to be in `SimpleAudioEngine`?

**Comment by Dipakce** [comment]
@minggo 
I don't force that this effect needs to be in SimpleAudioEngine but it has to be somewhere else...which is what I can't find in cocos2dx v3.2.It was previously existed in lower version of cocos2dx .Please do add it as early as possible.

**Comment by walzer** [comment]
Duplicated with #10530, let's discuss there.
