### ISSUE TITLE
spine binary support.

### ISSUE THREAD

**Issue by hsienwei** [cocos2d/cocos2d-x#10438]
Do you have any plans to support spine's binary file?

**Comment by minggo** [comment]
Is it a new feature?
We use spine official runtime.

**Comment by hsienwei** [comment]
![spine](https://cloud.githubusercontent.com/assets/1848607/6142607/7f24e724-b1f4-11e4-9a6b-c37f364cf9db.png)
It's a new export format.
But actually cannot find more detail in spine's official website.
Below text is part of [website](http://en.esotericsoftware.com/spine-using-runtimes).

> To export animation data from Spine, click the logo in the top left of the Spine window and choose Export. Choose JSON or Binary (note: binary is not currently supported by most runtimes) .

i just wanna know have any plan on it?

**Comment by minggo** [comment]
Got it, thanks.
I think the author will support it in cocos2d-x runtime.
We will update it when it is ready.

**Comment by hsienwei** [comment]
thank for your reply :)

**Comment by minggo** [comment]
You are welcome.
Thanks for the notification.

**Comment by yanggee** [comment]
Do you have any plans to support spine's binary file?

**Comment by yanggee** [comment]
好了 不装逼了 什么时候能提供一下spine binary format 的支持啊 ，json的解析速度太慢了

**Comment by minggo** [comment]
@yanggee as i said, the spine runtime is maintained by Spine author. We will connect him about it. And please use english in future, your english is good.

**Comment by ricardoquesada** [comment]
I think the best way to do it is by opening a ticket on the spine repository:
https://github.com/EsotericSoftware/spine-runtimes

**Comment by ricardoquesada** [comment]
this is the spine PR: https://github.com/EsotericSoftware/spine-runtimes/pull/716

**Comment by yanggee** [comment]
@ricardoquesada Thank you very much, Spine binary support is what I want.

**Comment by ricardoquesada** [comment]
don't merge this PR until the PR in the spine repo is merged. thanks.

**Comment by yanggee** [comment]
the spine runtime is unresolved

程序卡在这里了，不知道你的注释是什么意思

At 2016-09-28 10:10:12, "minggo" notifications@github.com wrote:

@yanggee as i said, the spine runtime is maintained by Spine author. We will connect him about it. And please use english in future, your english is good.

**Comment by yanggee** [comment]
I used the spine binary library ，but The program crashed。
In the create bones when the prompt name equal to null。

I need your help[http://p1.bqimg.com/4851/1be710ab8ff3c3a0.png](url)

**Comment by yanggee** [comment]
when the release version of 3.14? 
I really need spine binary support.
There is another problem, spine animation out of frame, how to optimize.

**Comment by ricardoquesada** [comment]
@yanggee what's the issue again? is it crashing with the new binary support patch?
if so, could you attach the code to reproduce it? thanks.

**Comment by yanggee** [comment]
@ricardoquesada Can i hava you email address ?  I want to send you a  about  binary spine file (.zip).
Spine binary support loads json file  is successed,but it loads binary file is faild .

**Comment by yanggee** [comment]
[player_double_sword.zip](https://github.com/cocos2d/cocos2d-x/files/526786/player_double_sword.zip)

**Comment by ricardoquesada** [comment]
@yanggee how do I use it? what's the skin and animation that I should use?

**Comment by yanggee** [comment]
@ricardoquesada 
I written some names in source code file.
You can get it by open the image, and you can open .cpp file .
[source code.zip](https://github.com/cocos2d/cocos2d-x/files/528605/source.code.zip)
