### ISSUE TITLE
Default bit depth is too low on desktop 

### ISSUE THREAD

**Issue by Sheado** [cocos2d/cocos2d-x#10457]
The default bit depth on desktop is too low - causing pixelization and color banding issues on sprites with smooth gradients.

In CCGLView.cpp

```
GLContextAttrs GLView::_glContextAttrs = {5, 6, 5, 0, 16, 0};
```

This should probably be defaulted to the following instead:

```
GLContextAttrs GLView::_glContextAttrs = {8,8,8,8, 16, 0};
```

**Comment by oilandrust** [comment]
Confirmed that I had the same issues on some mac devices, GLContextAttrs GLView::_glContextAttrs = {8,8,8,8, 16, 0}; makes more sense in my opinion, this should be changed.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/18508#issuecomment-347388581
