### ISSUE TITLE
Cant upload v3.4 project to windows store because of error 'CreateEventExA() isn’t allowed in assembly libcurl.dll'

### ISSUE THREAD

**Issue by bhonzo** [cocos2d/cocos2d-x#10471]
uploaded an app on windows phone store developed using v3.4  and the following error is produced

Validation errors

1028: The native API api-ms-win-core-synch-l1-2-0.dll:CreateEventExA() isn’t allowed in assembly libcurl.dll. Update it and then try again.

1028: The native API api-ms-win-core-localization-l1-2-0.dll:FormatMessageA() isn’t allowed in assembly libcurl.dll. Update it and then try again.

**Comment by minggo** [comment]
@stammen
Could you please take a look?

**Comment by piotrros** [comment]
I've got the same error. Previously I was successfully sending apps with 3.3 version.

Fix:
copy & replace cocos2d-x-3.4\external\curl\prebuilt\wp8\arm with the same files from 3.3.

**Comment by stammen** [comment]
I will be making a pull request tomorrow with updated libcurl dlls.

**Comment by sienlam** [comment]
copy & replace cocos2d-x-3.4\external\curl\prebuilt\wp8\arm with the same files from 3.3. 
it work???????

**Comment by bhonzo** [comment]
Thanks it worked

**Comment by richieyan** [comment]
Why 3.6 not fix this problem?
[It's fixed! Thanks]

**Comment by stammen** [comment]
It is fixed in v3.6. Just copy the DLL's to your v3.4 project.
