### ISSUE TITLE
SetColor will overwrite Label's outline color

### ISSUE THREAD

**Issue by darkdukey** [cocos2d/cocos2d-x#10486]
``` cpp
    auto myLabel6 = Label::createWithTTF("LabelTTF with Outline", "Marker Felt.ttf", 32);
    myLabel6->setColor(Color4B::RED);
    myLabel6->enableOutline(Color4B::WHITE, 1);
```

Result:
![screen shot 2015-02-12 at 2 58 36 pm](https://cloud.githubusercontent.com/assets/371584/6178855/e51093c0-b2c7-11e4-8f71-a9588e432cba.png)

Expected Result:
![screen shot 2015-02-12 at 2 59 35 pm](https://cloud.githubusercontent.com/assets/371584/6178859/edaac08c-b2c7-11e4-9ea5-69fbc154c910.png)

**Comment by WenhaiLin** [comment]
@darkdukey You should replace Node::setColor with Label::setTextColor

**Comment by minggo** [comment]
@darkdukey 
Any question now?
