### ISSUE TITLE
Memory leak via autorelease with no pool in place on iOS 5.1.1

### ISSUE THREAD

**Issue by ondesly** [cocos2d/cocos2d-x#10484]
Cocos2d-x 3.4, iPad 1 with iOS 5.1.1.

There is an infinite cycle in networkThread function in HttpClient-ios.mm. In this cycle autoreleased NSStrings and other NS objects are created. But this thread hasn't NSAutoreleasePool.

So I see warning messages:
objc[2897]: Object 0x5edbc90 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[2897]: Object 0x5edbd50 of class NSURL autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[2897]: Object 0x5edbd80 of class NSMutableURLRequest autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[2897]: Object 0x156ae00 of class NSConcreteData autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug

Only on 5.1.1.

**Comment by Mazyod** [comment]
@ondesly Nice find, I submitted a PR that should fix this issue:
https://github.com/cocos2d/cocos2d-x/pull/10545
