### ISSUE TITLE
android上连续分配的内存无法销毁？

### ISSUE THREAD

**Issue by puckery** [cocos2d/cocos2d-x#10491]
cocos2d-x版本： 3.2
测试机： vivo x3L

class TestData
{
public:
    TestData() {}
    ~TestData() {}
    std::string name;
};
std::map<int, TestData*> _testMap;

clicked button1:

```
for (int i=0; i<1000000; i++)
{
    TestData* td = new TestData();
    td->name = "test";
    _testMap[_testMap.size()] = td;
}
```

clicked button2:
    CCLOG("remove begin...");
    for (auto iterator = _testMap.begin(); iterator != _testMap.end(); ++iterator)
    {
        CC_SAFE_DELETE(iterator->second);
    }
    CCLOG("remove end...");
    _testMap.clear();

产生的内存无法被销毁? PC上没有问题

**Comment by minggo** [comment]
It is nothing about engine.
And how did you know the memory is not released?
