### ISSUE TITLE
screen rotation not supported on ios8 and above

### ISSUE THREAD

**Issue by prespondek** [cocos2d/cocos2d-x#10518]
on ios8 and above rotation is handled through at new method: 
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator>)coordinator

rather than the old:
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation

suggest adding a new method to RootViewController.mm

**Comment by minggo** [comment]
There is not `didRotateFromInterfaceOrientation` in `RootViewController.mm`. 
Now we use 
- `supportedInterfaceOrientations` for old iOS6 and upper versions
- `shouldAutorotateToInterfaceOrientation` for lower iOS versions

**Comment by minggo** [comment]
I haven't found screen rotation issue, so close this issue.
