### ISSUE TITLE
CCLabelTTF and setGlobalZOrder

### ISSUE THREAD

**Issue by radekluner** [cocos2d/cocos2d-x#10517]
v3.4
It seems that CCLabelTTF is not working correctly with setGlobalZOrder.
If i create Sprite with Z 10, then CCLabelTTF with Z 11. Sprite is still above CCLabelTTF.

**Comment by stevetranby** [comment]
Are you setting both setPositionZ() and setGlobalZOrder()? We are setting both and it seems to work as expected in v3.4

**Comment by darkdukey** [comment]
Can you provide some code snippets what can reproduce this issue?

**Comment by walzer** [comment]
Close issues inactive in more than 2 months.
