### ISSUE TITLE
helloworld linux target fails while linking against libchipmunk.a  "could not read symbols: Bad value"

### ISSUE THREAD

**Issue by nicolas33** [cocos2d/cocos2d-x#10522]
`$ cocos new myGame -p com.mycompagny.mygame -l cpp -d myGame-sandbox`
`$ cd myGame-sandbox/myGame`
`$ cocos run -p linux -j4`
`Linking CXX executable bin/MyGame
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/../../../../x86_64-pc-linux-gnu/bin/ld: ../cocos2d/external/chipmunk/prebuilt/linux/64-bit/libchipmunk.a(chipmunk.c.o): relocation R_X86_64_32 against '.rodata' can not be used when making a shared object; recompile with -fPIC
../cocos2d/external/chipmunk/prebuilt/linux/64-bit/libchipmunk.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status`
- git HEAD at 1b482b2c3fe5da6468c2b77986191ca065d11774
- g++ (Gentoo Hardened 4.8.3 p1.1, pie-0.5.9) 4.8.3

**Comment by walzer** [comment]
Please use stable version instead of edge version on github.
Linux platform has low priority in cocos2d-x, so we normally test and fix bugs only before version release.
