### ISSUE TITLE
missing cocos bin for complete install from cocos2d-x-3.4.tar.gz

### ISSUE THREAD

**Issue by alexodus** [cocos2d/cocos2d-x#10523]
step:
1) tar xvzf cocos2d-x-3.4.tar.gz 
2) cd cocos2d-x-cocos2d-x-3.4/
3) python download-deps.py

result:
tools/cocos2d-console/ IS EMPTY

**Comment by minggo** [comment]
@alexodus 
console is a submodule, you can not use cocos2d-x like that.
You use use cocos2d-x in two ways:
- use git to clone cocos2d-x and run `python download-deps.py` to download 3rd party libs
- download full package here http://www.cocos2d-x.org/download

**Comment by piotrros** [comment]
Unfortunetly download-deps doesn't download cocos2d-console.
So you have also do this:

```
cd tools/
git clone https://github.com/cocos2d/cocos2d-console.git
cd cocos2d-console/
python download-bin.py
```

yet, still bin directory is missing and you have to copy it from downloaded zip (from github)

**Comment by v1993** [comment]
Correct way is using `git submodule update --init`, refer to readme.

**Comment by piotrros** [comment]
You're right, I forgot about this :)
