### ISSUE TITLE
Missing essential sound functions in new AudioEngine for 3.4

### ISSUE THREAD

**Issue by Kugagames** [cocos2d/cocos2d-x#10548]
1. There is no function for changing the pitch if the sound plays already. 
2. It would be nice to have some basic effects on sound effects like fading in and out and crossfading between two sounds.

**Comment by walzer** [comment]
New `AudioEngine` is being implemented on multiple platforms. We're not using the cross platform code like `Sprite` based on OpenGLES. As the result, adding advanced features in `AudioEngine` is very expensive on engineer resources.

So my idea is that, keep `AudioEngine` as simple as it meet the majority of game development. For advance requirements, please use `fmod` instead.
