### ISSUE TITLE
Building mode is not working on Linux

### ISSUE THREAD

**Issue by antkillerfarm** [cocos2d/cocos2d-x#10540]
I want to use gdb to debug my app.
But when I run

`cocos run -s ~/my/HelloWorld -p linux -m debug`

it still cannot use gdb or CCLOG.

After researchment, I find that:
tools/cocos2d-console/plugins/project_compile/project_compile.py Line 1242~1243

```
   with cocos.pushd(build_dir):
       self._run_cmd('cmake %s' % os.path.relpath(cmakefile_dir, build_dir))
```

may be changed to:

```
    with cocos.pushd(build_dir):
        if self._mode == 'debug':
            self._run_cmd('cmake -DCMAKE_BUILD_TYPE=Debug %s' % os.path.relpath(cmakefile_dir, build_dir))
        else:
            self._run_cmd('cmake -DCMAKE_BUILD_TYPE=Release %s' % os.path.relpath(cmakefile_dir, build_dir))
```

**Comment by natural-law** [comment]
@antkillerfarm 
Thanks for your feedback. I have fixed this problem on branch v3 by this PR: 
https://github.com/cocos2d/cocos2d-x/pull/10591

The related PR of cocos2d-console is : https://github.com/cocos2d/cocos2d-console/pull/226

Also, I will fix the problem on branch v4 with this issue: https://github.com/cocos2d/cocos2d-x/issues/10593

Thank you once more!
