### ISSUE TITLE
New iOs project won't build

### ISSUE THREAD

**Issue by kagakuninja** [cocos2d/cocos2d-x#1054]
cloned gles20 branch on 21-June-2012, reinstalled templates using install-templates-xcode.sh and the -f option.  Created a new Xcode project using cocos2dx_box2d template.  When building, I get 2 compile errors:

CCDrawingPrimitives.cpp: 'actions/CCActionCatmullRom.h' file not found
CCDirector.cpp: 'extensions/CCBReader/CCNodeLoaderLibrary.h' file not found

**Comment by minggo** [comment]
We have modified many codes, and forgot to modify corresponding xcode project.
I am sorry about it.
We will fix it ASAP.

**Comment by minggo** [comment]
An issue is created for it
http://www.cocos2d-x.org/issues/1343

**Comment by minggo** [comment]
I have fixed it in the commit
https://github.com/cocos2d/cocos2d-x/pull/1055

Thank you for your feed back.

**Comment by kagakuninja** [comment]
Works for me now, thanks
