### ISSUE TITLE
addImageAsync crashes on Android/Windows (and probably others platforms)

### ISSUE THREAD

**Issue by mariusz102102** [cocos2d/cocos2d-x#10554]
I found that current async implement is incorrect.
Below test cases when it crashes:

Step1 
Added 10 images to _asyncStructQueue

Step2
Thread1 calls 10 times but _imageInfoQueue is empty (i.e. thread2 did not start job)
void TextureCache::unbindImageAsync(const std::string& filename)

Step3
Thread2 
in void TextureCache::loadImage() _asyncStructQueue has 10
_imageInfoQueue is empty but _asyncStructQueue has 10 images
thread2 add to _imageInfoQueue 

Step4
Thread 1 call 
TextureCache::addImageAsyncCallBack
_imageInfoQueue is not empty but we called unbindImageAsync for filename in step 2 - Crash

Regards,
Mariusz

**Comment by walzer** [comment]
What's your engine version?

**Comment by mariusz102102** [comment]
cocos2d-x 3.5

**Comment by WenhaiLin** [comment]
@zilongshanren The `TextureCache::addImageAsync` has been reimplemented by @yangws . So I think this issue should be closed.
https://github.com/cocos2d/cocos2d-x/pull/12735
