### ISSUE TITLE
CCBReader null pointer crash

### ISSUE THREAD

**Issue by kagakuninja** [cocos2d/cocos2d-x#1056]
CCBReader::readNodeGraphFromFile allows the pOwner parameter to be null (the default value is null, so this implies that null is a legal value for pOwner).  However, CCBReader::readNodeGraphFromFile will crash when attempting to call pOwner->retain.  If null is not a legal value, the default param value should be removed.

**Comment by walzer** [comment]
Thanks for your report. http://www.cocos2d-x.org/issues/1382 is created to trace it.
