### ISSUE TITLE
I think Value needs asUInt() or maybe asLong() issue parsing TMX

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#10562]
The following overflows for unsigned integers > INT_MAX 
if (_type == Type::STRING)
{
 return atoi(_field.strVal->c_str());
}
Could maybe add an option to convert to uint (32 or 64), maybe figure out how to make sure it overflows into a negative number (unsigned int > INT_MAX cast into int). Possibly switch to using strtol or stringstream?

**Comment by stevetranby** [comment]
Solved specific related Issue is from discussion: 
http://discuss.cocos2d-x.org/t/problem-with-cctmxtiledmap/20102?u=stevetranby
Edit: fixed get const char\* from attributeDict

```
// the XML parser calls here with all the elements
void TMXMapInfo::startElement(void *ctx, const char *name, const char **atts)
{
// ...
// Approx. Line 320 (CCTMXXMLParser.cpp)
// Erroneous
//uint32_t gid = static_cast<uint32_t>(attributeDict["gid"].asInt());
//
// #1 don't need to change CCValue.h (use string to unsigned long)
std::string gidString = attributeDict["gid"].asString();
const char* gidStr = gidString.c_str();
uint32_t gid = strtoul(gidStr, NULL, 10);
//
// #2 need to add a new asUnsignedInt() to VAlue
//uint32_t gid = static_cast<uint32_t>(attributeDict["gid"].asUnsignedInt());
}
```

If you want to go with #2 you can add the following to Value's impl

```
// inside CCValue.cpp (removed braces '{', '}' for brevity)
unsigned int Value::asUnsignedInt() const {
    CCASSERT(...);
    if (_type == Type::INTEGER) 
        return static_cast<unsigned int>(_field.intVal); // unsure if cast necessary
    if (_type == Type::BYTE)
        return _field.byteVal;
    if (_type == Type::STRING)
        return static_cast<unsigned int>(strtoul(_field.strVal->c_str(), NULL, 10));
    if (_type == Type::FLOAT)
        return static_cast<unsigned int>(_field.floatVal);
    if (_type == Type::DOUBLE)
        return static_cast<unsigned int>(_field.doubleVal);
    if (_type == Type::BOOLEAN)
        return _field.boolVal ? 1 : 0;
    return 0;
}
```

**Comment by stevetranby** [comment]
I did submit a PR for this issue. I didn't add tests or anything else because I wasn't sure it was necessary. If you are testing CCValue I will look to add tests.
https://github.com/cocos2d/cocos2d-x/pull/13785

Note that not having unsigned causes a bug with TMX parsing and flipped tiles.

**Comment by minggo** [comment]
It is already added.
