### ISSUE TITLE
[win7-cpptests]Node:Clipping-->Some objects in a strange position

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#10578]
Test base on the latest code of v4-develop branch on github.

![qq 20150225140712](https://cloud.githubusercontent.com/assets/5234286/6365775/b53b665e-bcf7-11e4-9144-794f7ebe2a41.png)

![qq 20150225140727](https://cloud.githubusercontent.com/assets/5234286/6365779/bb9f5780-bcf7-11e4-9d5c-ffafc5c385d7.png)

![qq 20150225140739](https://cloud.githubusercontent.com/assets/5234286/6365795/e51a0fa6-bcf7-11e4-9326-1ffe10795aaa.png)

**Comment by WenhaiLin** [comment]
This issue applies to Mac/iOS platform, too.

**Comment by mannewalis** [comment]
fixed with PR https://github.com/cocos2d/cocos2d-x/pull/10599

**Comment by mannewalis** [comment]
Reopening for testing.

**Comment by WenhaiLin** [comment]
@minggo I've checked it, it is OK now.
