### ISSUE TITLE
[win7-cpptests]Node:Spine-->The debug draw of bones is incorrect.

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#10584]
Test base on the latest code of v4-develop branch on github.

![qq 20150225151941](https://cloud.githubusercontent.com/assets/5234286/6366531/e0602450-bd01-11e4-9019-5294896c9a9b.png)

![qq 20150225151952](https://cloud.githubusercontent.com/assets/5234286/6366538/f0bb5216-bd01-11e4-82d6-cf32cb29c44b.png)

**Comment by WenhaiLin** [comment]
This issue applies to Mac/iOS platform, too.

**Comment by samuele3hu** [comment]
This bug would be triggered on Linux platform.

**Comment by fusijie** [comment]
Is the issue need to be fixed in v3.8? @pandamicro

**Comment by WenhaiLin** [comment]
This issue no longer exist.
