### ISSUE TITLE
[win7-cpptests]Node:Particle3D(PU)-->BlackHole:Crash

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#10583]
Test base on the latest code of v4-develop branch on github.

![qq 20150225144147](https://cloud.githubusercontent.com/assets/5234286/6366198/0f0bbf30-bcfd-11e4-96d5-3c7c7ff68a02.png)

**Comment by minggo** [comment]
We should remove particle3d in from v4-develop

**Comment by WenhaiLin** [comment]
Remove Particle3D: https://github.com/cocos2d/cocos2d-x/pull/10631
