### ISSUE TITLE
MoveTo::reverse() have no effect

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10589]
`version:` 3.4Final
`issue:` MoveTo::reverse() have no effect.
`How to reproduce:` add following code to HelloWorld Project.

``` cpp
    MoveTo* x = MoveTo::create(1, Vec2(100,100));
    MoveBy* y = x->reverse();
    sprite->runAction(Sequence::create(x, y, nullptr));
```

`How to fix?`

``` cpp
    MoveTo* x = MoveTo::create(1, Vec2(100,100));
    x->startWithTarget(sprite);
    MoveBy* y = x->reverse();
    sprite->runAction(Sequence::create(x, y, nullptr));
```

startWithTarget(Node *target) initial the `_positionDelta` property. if you don't call the function, `y action` will be wrong.

**Comment by minggo** [comment]
Because MoveTo is just to move to a absolute position, there is not meaning for MoveTo::reverse().

**Comment by minggo** [comment]
After thinking more about it, i think it is a bug.

**Comment by fusijie** [comment]
I also confused it a bug or not. Because if `MoveTo`'s reverse action is a `MoveTo` action, nobody know the d

**Comment by fusijie** [comment]
I also confused it is a bug or not. Because if `MoveTo`'s reverse action is a `MoveTo` action too, nobody know the destination of the target(It has no target for now), such as,

``` cpp
    MoveTo* x = MoveTo::create(1, Vec2(100,100));
    MoveTo* y = x->reverse();//what's the destination?
```

But now, the reverse action of `MoveTo` is a `MoveBy` action( from base class). the implemention is 

``` cpp
MoveBy* MoveBy::reverse() const
{
    return MoveBy::create(_duration, -_positionDelta);
}
```

So the destination issue should be resolved by `_positionDelta`.  `startWithTarget()` is a internal API, should we need some other public API to bind target to Action for implementing the reverse action?

**Comment by minggo** [comment]
I think MoveTo::reverse() should move to its original position.
What's your opinion?

**Comment by fusijie** [comment]
Yes, MoveTo::reverse() should move to its original position.
But no matter to use MoveBy or MoveTo, we need a target so that we can get the original position from the target by `target->getPosition()`.

**Comment by minggo** [comment]
Yep, what's your suggestion?

**Comment by fusijie** [comment]
＝。＝

A.enable MoveTo::reverse()
add a new API to bind target and record the original position, and note the limits. It's not a good idea.  

B.disable MoveTo::reverse()
overrite the `reverse()` API, such as

``` cpp
MoveTo* MoveTo::reverse() const
{
    CCASSERT(false, "reverse() not supported in MoveTo");
    return nullptr;
}
```

**Comment by vermilliontear** [comment]
I agree with fusijie. MoveTo is just an action, any Sprite can use it. So before startWithTarget(), the action doesn't know who will be using it. I think the MoveTo::reverse() should be disabled. Maybe we need a class, just like MoveToFrom, and we can use MoveToFrom::reverse() to reverse the action.

**Comment by minggo** [comment]
Thanks guys.
I think disable `MoveTo::reverse()` is reasonable.

**Comment by minggo** [comment]
@fusijie
Could you send a pull request to disable `Move::reverse()`?

**Comment by fusijie** [comment]
@minggo the pr is https://github.com/cocos2d/cocos2d-x/pull/10789

**Comment by minggo** [comment]
Thanks.
