### ISSUE TITLE
CocosBuilderTest crashes in v4 

### ISSUE THREAD

**Issue by SvDyer** [cocos2d/cocos2d-x#10600]
Cpp-tests > Extensions> CocosBuilderTest crashes in v4. Verified on Win32 and Universal App platforms.

**Comment by WenhaiLin** [comment]
This issue applies to Mac/Android platform, too.

**Comment by samuele3hu** [comment]
This crash also happened on ubuntu platforms.

**Comment by minggo** [comment]
Fixed in #10649.
