### ISSUE TITLE
[ios-cpptests]Node:Particles-->issue3990,setTotalParticle should work-->Render incorrectly or crash

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#10609]
![img_0203](https://cloud.githubusercontent.com/assets/5234286/6387970/f82ac2ca-bdce-11e4-9b0c-3d3758932199.png)

![qq 20150226154840](https://cloud.githubusercontent.com/assets/5234286/6388027/bf284032-bdcf-11e4-826d-eab0955e2127.png)

**Comment by samuele3hu** [comment]
This error would be triggered on linux platform.

**Comment by mannewalis** [comment]
Should be fixed with PR https://github.com/cocos2d/cocos2d-x/pull/10649
I'll merge it as soon as it passes jenkins

**Comment by mannewalis** [comment]
merged. ready for verification.

**Comment by minggo** [comment]
@Dhilan007 
Please verify this issue and other crash issues.
Thanks.

**Comment by minggo** [comment]
I tested on Mac, it is fixed.
