### ISSUE TITLE
Action listener isn't auto delete?

### ISSUE THREAD

**Issue by DionysosLai** [cocos2d/cocos2d-x#10611]
As we know, we can play an action , and can set an action listener function to know whether action plays complete or not that the action is not loop.This function is setMovementEventCallFunc().But there is a problem in v2\v3. When we set a new action, and the old listner funtion is not delete.
An animation can have many action lists. As example, there is an animation that have two actions with are not loop.And first we w`ll play one action, and we`ll play another action when the first action play completed.The code as following:
.h
    ///@brief listening an action whether play complete
    ///@return 
    void onActionOK( cocostudio::Armature *pArmature, cocostudio::MovementEventType eventType, const char *animationID );

```
cocostudio::Armature* m_arTestanimation;
```

.cpp
void StartLayer::onEnter()
{
    Layer::onEnter();

```
ArmatureDataManager::sharedArmatureDataManager()->addArmatureFileInfo("AnimationTest/DH_baonanguaola/DH_baonanguaola.ExportJson");
m_arTestanimation = Armature::create("DH_baonanguaola");
m_arTestanimation->getAnimation()->play("OLASpeak1");
m_arTestanimation->setPosition(ccp(640, -90));
this->addChild(m_arTestanimation, 1);
m_arTestanimation->getAnimation()->setMovementEventCallFunc(this, movementEvent_selector(StartLayer::onActionOK));  ///< listening sprite`s action state! 
```

}

void StartLayer::onActionOK( cocostudio::Armature *pArmature, cocostudio::MovementEventType eventType, const char *animationID )
{
    if (eventType == COMPLETE)
    {
        m_arTestanimation->getAnimation()->stop();
        m_arTestanimation->getAnimation()->play("OLASpeak3");
    }
}

My original ideal is play action 'OLASpeak1' and 'OLASpeak3' only one times. But I found m_arTestanimation would play action 'OLASpeak3' many times, because fuction onActionOK would be always called when action 'OLASpeak3' play complete. This problem is that when i play new action:m_arTestanimation->getAnimation()->play("OLASpeak3"), the onActionOK should be delete, but it`s not!!!

**Comment by chengstory** [comment]
Thanks @DionysosLai,   I ask @yushenglu to take a look.

**Comment by Rumist** [comment]
@DionysosLai  
I think that this method functionally is normal, you used abnormally.

See this comment in CCArmatureAnimation.h(Line 188).

/**
     \* Set armature's movement event callback function
     \* To disconnect this event, just setMovementEventCallFunc(nullptr, nullptr);
     */
    CC_DEPRECATED(v3) void setMovementEventCallFunc(cocos2d::Ref *target, SEL_MovementEventCallFunc callFunc);

Comment will notify to you about disconnect event method.

**Comment by DionysosLai** [comment]
@Rumist 
Yeah, I know what your mean.But I think this problem may is a design bug.For a game engine, a open engine and many people use to develop game,what you do is made the engine more easily, not set some invisible barriers.Such as this ex,many developer may ignore the function prompt, and do not  know how to deal with it.Why don`t engine do this thing, 'To disconnect this event'.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
