### ISSUE TITLE
[Linux and iOS]cpp-tests->Node:Particles->reset total particles would crash or display error in v4-develop

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#10610]
Click `add 10 particles` an `remove 10 particles` randomly, then trigger this bugs.The wrong display as follows:
![image](https://cloud.githubusercontent.com/assets/4231014/6388193/f094b7de-bdd1-11e4-8b78-8044cd0815c9.png)

**Comment by minggo** [comment]
Please check if it is fixed in #10649

**Comment by samuele3hu** [comment]
Yes,It has already been fixed.
