### ISSUE TITLE
Add Gradient Color Stops Feature to LayerGradient 

### ISSUE THREAD

**Issue by dingpinglv** [cocos2d/cocos2d-x#10615]
Add Gradient Color Stops Feature to cc.LayerGradient, The H5 canvas implement at  https://github.com/cocos2d/cocos2d-html5/pull/2693

**Comment by drelaptop** [comment]
JS feature request for 3 years ago with no one concern.

**Comment by drelaptop** [comment]
JS feature request for 3 years ago with no one concern.
