### ISSUE TITLE
TextView - Android - Displays White Background

### ISSUE THREAD

**Issue by si-design** [cocos2d/cocos2d-x#10616]
On certain devices such as the Nexus 4 (mine is running 4.4.4), a TextView will display a white background over the entire game. Also, things like setMaxLength do not work.

This does not happen on other devices such as the Galaxy S3.

I suspect the TextView is being displayed in the foreground, when it should be in the background.

**Comment by zilongshanren** [comment]
@si-design  TextView is the native Android control, right?
How do you add it to your scene?

**Comment by drelaptop** [comment]
no response for 3 years.
