### ISSUE TITLE
wrong GLFW import path

### ISSUE THREAD

**Issue by kenanb** [cocos2d/cocos2d-x#10648]
CCGLViewImpl-desktop.h is looking for glfw by `#include "glfw/glfw3.h"` while the path of GLFW 3 include file in my system (ArchLinux x64) is `GLFW/glfw3.h` (upcase directory name). I don't know this is the case in all systems. So I don't know if this is a bug in all platforms.

**Comment by minggo** [comment]
@kenanb 
Please refer to [this ticket](http://discuss.cocos2d-x.org/t/linux-64bit-and-32bit-support/20187/26) for detail information.

Now we use prebuilt version of GLFW.

**Comment by kenanb** [comment]
I see, still there probably is a problem with include path because I get `cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.h:32:24: fatal error: glfw/glfw3.h: No such file or directory` error while building my game. I just pulled the latest sources. I downloaded latest external deps and I am on branch v4-develop. The problem still exists.

**Comment by minggo** [comment]
You can find the header file in `external/linux/x86-64/include/glfw/glfw3.h`.

**Comment by zilongshanren** [comment]
@kenanb 
Why in your system the glfw directory is GLFW(upper case)?  Could you paste your cmake config output here?

**Comment by kenanb** [comment]
@andyque it is for the systemwise GLFW installation, here is the Arch Linux official GLFW package file list: https://www.archlinux.org/packages/community/x86_64/glfw/files/

**Comment by zilongshanren** [comment]
@kenanb 
But now we are using prebuilt version of GLFW. Why it will search the system GLFW installation?

**Comment by kenanb** [comment]
@andyque @minggo it turns out I didn't change the CMakeLists.txt in my project path with the new one in the template directory. That was the cause of the problem. My mistake. Sorry for the confusion and thank you so much for the help :) Closing.
