### ISSUE TITLE
C++ crash in flatbuffers?

### ISSUE THREAD

**Issue by zawasp** [cocos2d/cocos2d-x#10650]
Ever since I'm using binary csb files, I get these random (rare) crash reports in my Google Play console. They seem to be releated to flatbutffers somehow:

`backtrace:
#00 pc 0017fecc /data/app-lib/com.x.y-2/libxy.so (cocos2d::CSLoader::nodeWithFlatBuffersFile(std::string const&)+99)
#01 pc 0017fec9 /data/app-lib/com.x.y-2/libxy.so (cocos2d::CSLoader::nodeWithFlatBuffersFile(std::string const&)+96)`

Please investigate. Thank you.

**Comment by zhuoyikang** [comment]
i also get this crash...

#1  0x0000000100ae9a7d in std::**1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(char const_) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1968
#2  0x0000000100ae9a5f in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(char const_) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1972
#3  0x0000000100ae9a5f in cocos2d::CSLoader::nodeWithFlatBuffersFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/zhuoyikang/Source/games/T2/cocos2d/cocos/editor-support/cocostudio/ActionTimeline/CSLoader.cpp:762
#4  0x0000000100ae545f in cocos2d::CSLoader::createNodeWithFlatBuffersFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/zhuoyikang/Source/games/T2/cocos2d/cocos/editor-support/cocostudio/ActionTimeline/CSLoader.cpp:739
#5  0x0000000100ae52d4 in cocos2d::CSLoader::createNode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/zhuoyikang/Source/games/T2/cocos2d/cocos/editor-support/cocostudio/ActionTimeline/CSLoader.cpp:252
#6  0x000000010060187b in HelloWorld::init() at /Users/zhuoyikang/Source/games/T2/Classes/HelloWorldScene.cpp:46
#7  0x000000010060221f in HelloWorld::create() at /Users/zhuoyikang/Source/games/T2/Classes/HelloWorldScene.h:24
#8  0x00000001006016f6 in HelloWorld::createScene() at /Users/zhuoyikang/Source/games/T2/Classes/HelloWorldScene.cpp:15
#9  0x00000001006015ce in AppDelegate::applicationDidFinishLaunching() at /Users/zhuoyikang/Source/games/T2/Classes/AppDelegate.cpp:41
#10 0x000000010065f6c4 in cocos2d::Application::run() at /Users/zhuoyikang/Source/games/T2/cocos2d/cocos/platform/ios/CCApplication-ios.mm:53
#11 0x00000001006040b8 in -[AppController application:didFinishLaunchingWithOptions:] at /Users/zhuoyikang/Source/games/T2/proj.ios_mac/ios/AppController.mm:84
#12 0x0000000101903475 in -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]()
#13 0x0000000101903fbc in -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]()
#14 0x0000000101906d2c in -[UIApplication _runWithMainScene:transitionContext:completion:]()
#15 0x0000000101905bf2 in -[UIApplication workspaceDidEndTransaction:]()
#16 0x000000010610a2a3 in __31-[FBSSerialQueue performAsync:]_block_invoke ()
#17 0x000000010435c53c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK** ()
#18 0x0000000104352285 in __CFRunLoopDoBlocks ()
#19 0x0000000104352045 in __CFRunLoopRun ()
#20 0x0000000104351486 in CFRunLoopRunSpecific ()
#21 0x0000000101905669 in -[UIApplication _run]()
#22 0x0000000101908420 in UIApplicationMain ()
#23 0x00000001006046bf in main at /Users/zhuoyikang/Source/games/T2/proj.ios_mac/ios/main.m:6
#24 0x0000000104fd5145 in start ()

**Comment by zawasp** [comment]
This was caused by my own code, not the engine. Closing.

**Comment by ManuGinobili20** [comment]
我也出现了这个问题，能告知是什么错误引起的吗
