### ISSUE TITLE
proper process for different Lua bytecode on different platform (32/64 bit) or different Lua implementation

### ISSUE THREAD

**Issue by davidxifeng** [cocos2d/cocos2d-x#10675]
Lua bytecode is different between 32-bit and 64-bit platform, and so does luajit bytecode,

add process for these in Cocos2dxLuaLoader.cpp and `cocos-console` (plugin_luacompile) would be better, I have written a little **dirty fix** for this, but it is still not ready for send pull request.

Lua字节码因为word size和byte order的原因而在不同平台上不兼容(如iphone 4s/ iphone 6), luajit字节码和lua字节码也不兼容, 如果游戏使用加密后的字节码的话, 则需要带上至少两份, 而现在的Cocos2dxLuaLoader并没有处理这个问题, cocos-console工具也没有做此处理,建议加上这个处理.

我已经在我们的项目中(ios only)紧急加了此修复, 但还不完善,准备完成后发pull request, 或者其他朋友完善此功能也行~

**Comment by darkdukey** [comment]
Is this been fixed? or its still a problem?

**Comment by davidxifeng** [comment]
我已经简单的解决了这个问题: 带上两份字节码文件, 修改`Cocos2dxLuaLoader`来根据不同的平台加载不同的字节码,不过晚上紧急加的,代码比较dirty.

@darkdukey

**Comment by darkdukey** [comment]
Thanks a lot @dualface worth look at it.

**Comment by davidxifeng** [comment]
另外,我们项目现在使用的cocos2d-x 3.2, (iOS) 我发现这个版本附带的liblua.a只有64位的,然后libluajit.a只有32位的.

就是说项目在不同的平台上使用的Lua也不一样, 如果带字节码的话,也要注意好使用不同的编译工具生成字节码, 需要修改 `plugin_luacompile`.

**Comment by xpol** [comment]
这个确实需要啊。比起各自修改各自的，不如官方统一改一下。

**Comment by pandamicro** [comment]
@dualface Please take a look, seems a good proposition
