### ISSUE TITLE
rotated sprite displays incorrectly if a physics body is attached

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#10676]
1. In Cocos Studio, add a rectangular sprite to a layer and set it's Rotation value to 90 via the Properties pane in Cocos Studio.
2. Run the app to verify that the sprite is displaying with the correct rotation value.  It should display correctly at this point.
3. Add C++ code to bind the sprite to a variable. Then, attach a static physics body to this variable.
   In this example, the variable name is: _leftWall

```
  Sprite * _leftWall;
  (add code here to bind _leftWall to corresponding sprite created in cocos studio..)

   // attach a physics body to the sprite
   auto body = PhysicsBody::createBox (_leftWall->getBoundingBox().size);
    body->setDynamic(false);
    _leftWall->setPhysicsBody(body);
```
1. What seems to be happening after a physics body is attached to the sprite, is that 
   the sprite no longer displays with the correct rotation. Instead it displays with a rotation of 0 degrees. 
   Interestingly, the physics shape itself is correct.

```
// to verify the physics shape is correct
 (getPhysicsWorld()->setDebugDrawMask(PhysicsWorld::DEBUGDRAW_ALL);)
```

**Comment by Yehsam23** [comment]
I fix this issue by set "_updateTransformFromPhysics" default value to false at CCNode.ccp

CCNode.cpp

, _updateTransformFromPhysics(false)

**Comment by ginobean** [comment]
It doesn't seem to work for me. As a test, I set _updateTransformFromPhysics(false) both in the constructor and in Node::updatePhysicsBodyTransform, where it was again setting it to true. 
```
@@ -2083,7 +2083,7 @@ void Node::updatePhysicsBodyTransform(const Mat4& parentTransform, uint32_t pare
 {
     _updateTransformFromPhysics = false;
     auto flags = processParentFlags(parentTransform, parentFlags);
-    _updateTransformFromPhysics = true;
+//    _updateTransformFromPhysics = true;
     auto scaleX = parentScaleX * _scaleX;
```
Also be sure to enable physics debug shapes:
```
    _physicsWorld->setDebugDrawMask(PhysicsWorld::DEBUGDRAW_SHAPE);
```
It sort of looks like it's working, but if you set the debug draw shapes flag, you'll see that the physics shape and the sprite no longer match on the screen..

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11383

**Comment by minggo** [comment]
@ginobean 
Will you test the PR?
