### ISSUE TITLE
cpp-tests crashes constantly on Asus zenfone 6 and Galaxy Tab 3 10.1" when using x86

### ISSUE THREAD

**Issue by abcjjy** [cocos2d/cocos2d-x#10674]
The two devices all uses Atom 25xx cpus. And their primary architecture is x86. If I compiles only with armeabi or armeabi-v7a, cpp-tests runs smoothly. However, when x86 is enabled, the tests crashes constantly. 

Here is the stack:

Build fingerprint: 'asus/CUCC_a600cg/ASUS_T00G:4.3/JSS15Q/CUCC_user_1.18.40.16_20140911_3821:user/release-keys'
pid: 22647, tid: 22662, name: Thread-8692  >>> org.cocos2dx.cpp_tests <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
Stack frame #00  pc 009b623c  /data/app-lib/org.cocos2dx.cpp_tests-2/libcpp_tests.so: Routine cocos2d::Node::getNodeToParentTransform() const at /Users/jianyingjia/code/cocos2d-x-3.4/build/../cocos/2d/CCNode.cpp:1763
Stack frame #01  pc 009bb1d4  /data/app-lib/org.cocos2dx.cpp_tests-2/libcpp_tests.so: Routine cocos2d::Node::transform(cocos2d::Mat4 const&) at /Users/jianyingjia/code/cocos2d-x-3.4/build/../cocos/2d/CCNode.cpp:1381
Stack frame #02  pc 009bc85b  /data/app-lib/org.cocos2dx.cpp_tests-2/libcpp_tests.so: Routine cocos2d::Node::processParentFlags(cocos2d::Mat4 const&, unsigned int) at /Users/jianyingjia/code/cocos2d-x-3.4/build/../cocos/2d/CCNode.cpp:1304
Stack frame #03  pc 00001f9f  <unknown>

Reproduce:

Build with x86 architecture, use release mode. 

Launch the app, tap randomly and crash shortly.

The stack traces are all the same.

![screenshot_2015-02-28-20-44-37](https://cloud.githubusercontent.com/assets/1791493/6426223/2c551b78-bf8b-11e4-8e6e-8e3f576b750a.jpg)

**Comment by zawasp** [comment]
I get the same reports on a production game - it only crashes on x86 Atom devices:
Venue 8 (yellowtail)
Fonepad 7 (K00Z)
ZenFone 6 (ASUS_T00G)
ZenFone 4 (ASUS_T00I)
ZenFone 5 (ASUS_T00J)
MeMO Pad 7 (K01A)
ASUS MeMo Pad ME302C (ME302C)
Iconia One 8 (vespa8)
Iconia Tab 8 (ducati2hd)

This is a sample crash log:

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'asus/WW_FonePad/K00Z:4.3/JSS15Q/WW_FonePad-V3.5.6-20140520:user/release-keys'
Revision: '0'
pid: 29549, tid: 29566, name: Thread-12109 >>> com.x.y <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
eax 6197f98c ebx 61573b1c ecx 6197f98c edx 6197f9fc
esi 6197f9fc edi 6197f98c
xcs 00000073 xds 0000007b xes 0000007b xfs 00000000 xss 0000007b
eip 611f59e0 ebp 63f5daf0 esp 6197f8fc flags 00210202`

**Comment by abcjjy** [comment]
I found a workaround for this issue. 

Turn off following optimization options:
#LOCAL_CPPFLAGS += -ftree-pre 
#LOCAL_CPPFLAGS += -fgcse
#LOCAL_CPPFLAGS += -fcaller-saves 

Use -O1 and add all the optimization options in -O2 except the above ones. Then the test can run without crash.

But I think it is only a workaround, not an ideal solution. 

And this issue only happens on the Atom 25xx series. I tested on Atom 35xx, it works there.

**Comment by walzer** [comment]
Solved by issue owner.

**Comment by zawasp** [comment]
This is not really a solution. Even if it works for x86 builds, a script which enables these optimizations on ARM builds is required. Please reopen this - there are more and more x86 devices on the market.
