### ISSUE TITLE
Two Camera,"experimental :: TMXTiledMap" black

### ISSUE THREAD

**Issue by fqamic** [cocos2d/cocos2d-x#10704]
Use two custom Camera, after the "Add" into the scene camera, add map "experimental :: TMXTiledMap" created, move it out of the screen when originally appeared on the screen inside the area, the black, not drawn . First "Add" into the scene camera, no problem.
Code:
void initTmx()
{
    Layer\* _backgroundlayer = Layer::create();
    addChild(_backgroundlayer, 1);
    Camera\* _backgroundcamera = Camera::createOrthographic(visibleSize.width, visibleSize.height, -1024.f, 0.f);
    _backgroundcamera->setCameraFlag(CameraFlag::USER1);
    _backgroundcamera->setPosition3D(Vec3(0.f,0.f,0.f));
    _backgroundcamera->setRotation3D(Vec3(0.f,0.f,0.f));
    _backgroundlayer->addChild(_backgroundcamera);

```
Layer* _foregroundlayer = Layer::create();
addChild(_foregroundlayer, 3);
Camera* _foregroundcamera = Camera::createOrthographic(visibleSize.width, visibleSize.height, -1024.f, 0.f);
_foregroundcamera->setCameraFlag(CameraFlag::USER3);
_foregroundcamera->setPosition3D(Vec3(0.f,0.f,0.f));
_foregroundcamera->setRotation3D(Vec3(0.f,0.f,0.f));
_foregroundlayer->addChild(_foregroundcamera);
```

// any TMX file can be
    _tmxtiledmap = cocos2d::experimental::TMXTiledMap::create("TileMaps/orthogonal-test2.tmx");

```
_foregroundlayer->addChild(_tmxtiledmap);   //1.png
```

//  _backgroundlayer->addChild(_tmxtiledmap); //2.png

```
_backgroundlayer->setCameraMask(2);
_foregroundlayer->setCameraMask(8);

this->scheduleUpdate();
```

}

void HelloWorld::update(float delta)
{
    _tmxtiledmap->setPositionX(_tmxtiledmap ->getPositionX() - 2_delta_60);
}
![1](https://cloud.githubusercontent.com/assets/7044155/6460265/b5b0c9d4-c1d0-11e4-872f-231a220e41f6.png)
![2](https://cloud.githubusercontent.com/assets/7044155/6460267/b5e06fc2-c1d0-11e4-9678-314cd435de2d.png)

**Comment by fqamic** [comment]
@minggo 
Hello, may I ask this question can be resolved? Project more anxious! Thank you.

**Comment by walzer** [comment]
Sorry for late response. What's your engine version?

**Comment by fqamic** [comment]
@walzer 
Too happy, in the latest version --3.6 official version has solved this problem.
![qq20150502-1 2x](https://cloud.githubusercontent.com/assets/7044155/7441493/c75e6f4e-f11c-11e4-87be-ae1ce708d956.png)

**Comment by fqamic** [comment]
@walzer 
Thank you very much！
