### ISSUE TITLE
Label transform not updating correctly if masked

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#10705]
It seems in testing that Label (possibly others) don't update their transforms because the Node visit method processes the nodes flags before the isVisitingCamera check is called. But in Label the checking of camera mask/flag is done before processing the parent/transform flags.

Reference discussion of solving the issue.
http://discuss.cocos2d-x.org/t/label-as-child-doesnt-move-when-parent-position-updated-with-2-cameras/20267/5

Fix?

```
void Label::visit(Renderer *renderer, const Mat4 &parentTransform, uint32_t parentFlags)
{
    if (! _visible || _originalUTF8String.empty())
    {
        return;
    }

    // moved process flags before return if not in camera's view 
    // because updating transforms needs to occur when parent 
    // transform changes, regardless of which camera is active
    uint32_t flags = processParentFlags(parentTransform, parentFlags);

    if(! isVisitableByVisitingCamera()) { return; }

    // ...
}
```

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10730

**Comment by minggo** [comment]
@stevetranby 
Could you please check it?

**Comment by stevetranby** [comment]
I reverted my fix, applied this fix, and it worked as expected for me. Thanks!

**Comment by minggo** [comment]
Thanks @stevetranby .
