### ISSUE TITLE
Decouple GL_DEPTH_TEST and glDepthMask

### ISSUE THREAD

**Issue by jdedona** [cocos2d/cocos2d-x#10729]
Can't draw 2D UI in 3D space because enabling depthMask, and depth test are coupled through Director::setDepthTest.

In Renderer::visitRenderQueue, if _isDepthTestFor2D is set it will enable both depthTest and depthMask. However when drawing UI you can have several nodes on the same plane overlapping one another. The only way to draw them in order without Z fighting is to have depthTest set to True and depthMask set to False. I can't see a way to do this through current API.

**Comment by walzer** [comment]
Our current render queue can't satisfy the requirement of 3D and 2D rendering very well.
@dabingnn is redesigning the render queue in v3.7, which will probably fix this bug.

**Comment by jdedona** [comment]
Okay sounds good. We've actually made a lot of patches here at TinyCo. We've got 2D UI rendering perfectly in 3D space, and 3D models rendering with perspective perfectly in our 2D UI.
