### ISSUE TITLE
UI Button don't set default fontname 

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#10747]
If I create a button and set only the graphics (normal state, selected, etc) when I compile I get the following:

No file found at Thonburi. Possible missing file.

I've seen in UIButton (and also in UI Text and UI Textfield), that a default _fontname("Thonburi") has been set.

But if I don't want to setTitleFontName("something else") I think I shouldn't get this warning.

**Comment by zilongshanren** [comment]
@DarioDP 
This issue should be fixed in the latest release. 
Could you please check it out?

**Comment by dariodepaolis** [comment]
Ok it's ok now, thank you.
