### ISSUE TITLE
physics objects do not scroll as expected when parent node position is changed

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#10749]
Create a node W. Add a couple visible Sprites to this node W (but without attaching any physics bodies).

If you change node W's position by delta x, the Sprites that are the children of W will actually visually change positions. This is the expected behavior and actually allows for easy scrolling, simply by changing the position of the parent container node.

Now, attach a static physics body (such as a circle shape physics body) to each of those visible Sprites and rerun the test. This time, when you change the position of W, the children of W actually stay stuck in place. 

As a comparison, if you look at cocos2d-swift, it actually handles this case correctly..

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11379
