### ISSUE TITLE
applicationDidEnterBackground not called when low battery popup & title bar interruption

### ISSUE THREAD

**Issue by smitpatel88** [cocos2d/cocos2d-x#10746]
This bug is applicable on both Android & iOS.
Using v3.4 final

Whenever low battery pop-up comes applicationDidEnterBackground() method should called but its not getting called. Due to this user can lost current level easily.
Also for title bar its same, when user drag title bar in Android or iOS, it should call applicationDidEnterBackground().

**Comment by minggo** [comment]
cocos2d-x just forward information from system. iOS doesn't invoke `applicationDidEnterBackground` in these situations.

**Comment by kaplad** [comment]
If you need to pause your game, just handle this event:

```
- (void)applicationWillResignActive:(UIApplication *)application {
    cocos2d::Application::getInstance()->applicationWillEnterForeground();
}
```

**Comment by smitpatel88** [comment]
@kaplad Thanks, That works fine.
What about Android? Which event should i handle? even googling is not helping.

**Comment by kaplad** [comment]
On Android onPause should be invoked. It's already handled by cocos2d-x:

```
JNIEXPORT void JNICALL Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnPause() {
    if (Director::getInstance()->getOpenGLView()) {
            Application::getInstance()->applicationDidEnterBackground();
            cocos2d::EventCustom backgroundEvent(EVENT_COME_TO_BACKGROUND);
            cocos2d::Director::getInstance()->getEventDispatcher()->dispatchEvent(&backgroundEvent);
    }
}
```

**Comment by smitpatel88** [comment]
@kaplad No, for only normal interrupts its working.
Not for low battery pop-up & title bar dragging.

**Comment by kaplad** [comment]
@smitpatel88 Activity has [onWindowFocusChanged (boolean hasFocus)](http://developer.android.com/reference/android/app/Activity.html#onWindowFocusChanged%28boolean%29) Try to handle it

**Comment by smitpatel88** [comment]
@kaplad Thanks.
That works for both battery pop-up & title bar interrupt.

 @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);

```
    if(hasFocus) {
        Cocos2dxHelper.onResume();
        this.mGLSurfaceView.onResume();
    }
    else {
        Cocos2dxHelper.onPause();
        this.mGLSurfaceView.onPause();
    }
}
```
