### ISSUE TITLE
Clipping node doesn't work on Android 5.0:

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#10759]
See this topic:

http://stackoverflow.com/questions/28842039/cocos2d-x-android-5-0-clipping-node-not-working

**Comment by hsienwei** [comment]
i got it too.
It occurred to Nexus 7 with android 5.1.
Some info below.
https://dl.dropboxusercontent.com/u/10581994/cocos2dx_issue/nexus.txt
https://dl.dropboxusercontent.com/u/10581994/cocos2dx_issue/Screenshot_2015-04-16-13-43-24.png
https://dl.dropboxusercontent.com/u/10581994/cocos2dx_issue/Screenshot_2015-04-16-13-41-14.png

if modify Cocos2dxActivity.java like code below, problem  will be fix.
// Switch to supported OpenGL (ARGB888) mode on emulator
if (isAndroidEmulator())
     this.mGLSurfaceView.setEGLConfigChooser(8, 8, 8, 8, 16, 0);
else 
     this.mGLSurfaceView.setEGLConfigChooser(8, 8, 8, 8, 16, 8);

p.s.  using cocos2d-x 3.5

**Comment by hussain-sohaib** [comment]
to fix this issue, in appcontroller.mm change pixelformat and depthFormat to this.

pixelFormat: kEAGLColorFormatRGBA8
depthFormat:  GL_DEPTH24_STENCIL8_OES

thanks!

**Comment by tomhmp** [comment]
I'm also experiencing this issue although neither of the above suggestions worked for me.

My clipping nodes seem to work fine on our Samsung S3 (4.1.2) but not on our S4 (4.2.2) or our Nexus 7 (4.4.3). 

I've also tried changing the #define GL_DEPTH24_STENCIL8 in CCGL-android.h to GL_DEPTH24_STENCIL8_OES but that didn't seem to make a difference. No luck with creating the ClippingNodes in a CallFunc either (which I read as a suggestion elsewhere).

I'm currently using cocos2dx v3.4 if anyone else has any thoughts?

**Comment by lalaloha** [comment]
Hi,

I got the problem described in "Screenshot_2015-04-16-13-41-14.png" too with cocos2d-x 3.5, and using UIScrollView, and it happens in nexus 7.. I tested all the code in many devices, and all is okay.. but in nexus 7 (the first model), it became like the screenshot.. Is there any quick and permanent fix for this? thanks

**Comment by yangws** [comment]
I send a pr for this issue, but i don't have any device to reproduct this issue.
Please test my pr if can reproduct this issue, thanks.
If the pr works correctly, please tell me, thanks.

**Comment by pandamicro** [comment]
@piotrros @hsienwei @tomhmp @lalaloha
Can you help to test our fix #12762 ? Thanks
