### ISSUE TITLE
3.4Final 生成的lua版 通过Name获取ccs节点的问题

### ISSUE THREAD

**Issue by yuyangame** [cocos2d/cocos2d-x#10754]
不会遍历所有子节点，而是只遍历一级子节点，记得之前是能过遍历所有的啊，现在只能自己写方法解决了么

**Comment by chengstory** [comment]
I ask @pipu to answer your question.

**Comment by pipu** [comment]
@yuyangame 
1. Node::getChildByName() 只能查找一级子节点。
2. Helper::seekWidgetByName() 可以递归查找子节点，但是节点类型必须是 Widget 及其子类对象。

**Comment by yuyangame** [comment]
@chengstory  @pipu 谢谢，解决啦
