### ISSUE TITLE
Label setString bug after getLetter function using TTF font

### ISSUE THREAD

**Issue by chenquanjun** [cocos2d/cocos2d-x#10773]
quickx 3.3 final

```
        local label = display.newTTFLabel({
            text = "testlongstring",
            font = "fonts/arial.ttf",
            })
            :addTo(self)
            :pos(display.cx, display.cy)

        local spr = label:getLetter(5)
        label:setString("test2") --assert here
```

It will cause assert in TextureAtlas function removeQuadAtIndex
"CCASSERT( index>=0 && index<_totalQuads, "removeQuadAtIndex: Invalid index");"

if getLetter index larger than setString length, it happens

**Comment by betaShine** [comment]
met same issue.... find a temp solution from:
http://www.cocoachina.com/bbs/read.php?tid=203887
hope fix soon

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11659

**Comment by walzer** [comment]
@WenhaiLin , once your pull request is merged, please close this issue.
