### ISSUE TITLE
PageView should support Vertical scroll

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#10778]
Since many developers are asking me for this feature, we might need to implemented in v3.5 and v4.x.

**Comment by anjandaffo** [comment]
For Now I had modified the PageView.h and PageView.cpp file so the PageView allowing for both direction. if any one need it you can use it with replacing the cocos2d/cocos/ui/PageView.h and cocos2d/cocos/ui/PageView.cpp file with attached file in below link.

http://discuss.cocos2d-x.org/t/will-pageview-support-vertical-direction/13307/3?u=anjanjis

Thanks
Anjan

**Comment by Stephen-Sachson** [comment]
After I rotated a page view by 180°, it turned into a piece of SH**. The scroll direction was totally messed up. What a time-wasting worthless volatile stuff.

**Comment by Stephen-Sachson** [comment]
It's going nuts if I rotate it by 180°. Really a shoddy & cheap piece of work ehhh.

**Comment by anjandaffo** [comment]
@Stephen-Sachson  If you check original PageView with horizontal direction also not worked after rotate . After rotate page change reverse. shame is happen with vertical direction. I did't worked for rotate I just make modification to support Vertical direction. I required Vertical PageView in my one of our project. I made these changes and working fine. Here I just share If any one need he can take it. If it not fulfill your requirement you can escape it.

**Comment by cxfshelter** [comment]
this should be done early
