### ISSUE TITLE
CCParticleSystemQuad crash when cleanup on win32

### ISSUE THREAD

**Issue by maxwzg** [cocos2d/cocos2d-x#1078]
CCParticleSystemQuad cleanup crash on win32,,  include removeFromParentAndCleanup(true) and setAutoRemoveOnFinish(true), tested cocos2d-2.0-rc2-x-2.0.1 and cocos2d-2.0-rc0a-x-2.0  have same issue 

I tested my project and  cocos2d-x->tests->AddAndDeleteParticleSystems example.

i tested IOS platform, it's fine.

**Comment by minggo** [comment]
James has pulled a request to resolve it
https://github.com/cocos2d/cocos2d-x/pull/1077

You can checkout it out.

Thank you for your feed back.
