### ISSUE TITLE
Different declaration on CCLayerColor::setContentSize

### ISSUE THREAD

**Issue by maxwzg** [cocos2d/cocos2d-x#1079]
setContentSize on CCNode is:
void CCNode::setContentSize(CCSize size)

but CCLayerColor is:
void CCLayerColor::setContentSize(const CCSize& size)

so CCLayerColor  can't  override contentSize

**Comment by maxwzg** [comment]
CCLayerColor::setContentSize need change to void CCLayerColor::setContentSize(CCSize size) ?

**Comment by walzer** [comment]
Oh, that's bug. Thanks for you report. I created http://www.cocos2d-x.org/issues/1381 to trace it.
I think change the declaration in CCNode is better.
