### ISSUE TITLE
bug of cocos2d-console/plugins/project_compile/project_compile.py

### ISSUE THREAD

**Issue by phoenixcw** [cocos2d/cocos2d-x#10797]
seems that line 846:
version_pattern = re.compile(r'(\d+).(\d+)')
should be:
version_pattern = re.compile(r'(\d+).(\d+)$')
because sometimes there are some alpha-chars after the last digit.

**Comment by minggo** [comment]
I think you should create issues in [plugin-x repo](https://github.com/cocos2d-x/plugin-x).

**Comment by darkdukey** [comment]
This is cocos console bug I think.

**Comment by minggo** [comment]
@natural-law 
Could you please take a look?

**Comment by natural-law** [comment]
@phoenixcw 
Could you please show me the problem you encountered? For example:
1. What's your register looks like?
2. What's the problem when you are using `cocos compile`?

Because there isn't anyone else feedback similar problem. I think I should find the real reason of your problem. Maybe I should adjust the implementation of `cocos compile`.

Thanks for your feedback! Looking forward to your reply!

**Comment by phoenixcw** [comment]
@natural-law 

Thanks for you response!
If I run the default `project_compile.py`, it raise an error like:
`
  File "D:\Projects\02_GameDevelop\01_cocos\02_cocos2d-x-3.4\tools\cocos2d-console\plugins\project_compile\project_compile.py", line 877, in _get_vs_path
    ver_float = float(version)
ValueError: invalid literal for float(): 7.0Exp
`
I think the reason is that I have too many visual studio versions in my PC. It seems that the version number of VS2005 is 7.0Exp, so if I fixed it by changing the pattern string in `project_compile.py` while some of my friends changed the value in `regedit` directly.
Therefore I don't think there's something to do with `cocos compile`.
Thank you!

**Comment by natural-law** [comment]
@phoenixcw 
Thanks for your information. I think I should adjust the logic of `cocos compile` to be compatible with your situation.
I will solve it later. Thanks for your feedback!

**Comment by natural-law** [comment]
@phoenixcw 
I think this commit will solve your problem:https://github.com/natural-law/cocos2d-console/commit/9159a36ca69720d1447bc17d72dced352a700c2f

I'll send it to the v3 & v4-develop branches of cocos2d-x later.

**Comment by phoenixcw** [comment]
@natural-law
It seems to work:)
Thanks very much!
