### ISSUE TITLE
PhysicsBody don't follow the action of it's parent layer.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10804]
`version:` 3.4Final
`issue:` Add a PhysicalBody to a layer, if move the layer, the PhysicalBody is still resting.
`reproduce:` modify the following code to TestCpp - PhysicsTest.cpp, then click the toggle debug menu.

``` cpp
void PhysicsDemo::toggleDebugCallback(Ref* sender)
{
    if (_scene != nullptr)
    {
        _scene->toggleDebug();
        this->runAction(MoveBy::create(3, Vec2(-500,0)));
    }
}
```

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11379

**Comment by minggo** [comment]
@fusijie 
Could you please test the PR?
Thanks.

**Comment by fusijie** [comment]
@minggo @WenhaiLin 

It's fixed. Thanks!
