### ISSUE TITLE
Help PhysicsBody animation create by CocoStudio v2.1.5

### ISSUE THREAD

**Issue by huynhlam1991** [cocos2d/cocos2d-x#10818]
pleae help me add physicBody to animation create by cocostudio.Please give me tutorial. I use cocos2dx V3.4 and cocostudio v2.1.5. I need tutorial used animation create by cocosStudio
Node\* node = CSLoader::getInstance()->createNode("Node.csb");
    cocostudio::timeline::ActionTimeline\* action = CSLoader::createTimeline("Node.csb");
    action->gotoFrameAndPlay(0,true);
    node->setPosition(300,300);
    node->runAction(action);
    auto paddleNode = PhysicsBody::createBox(node->getContentSize(),PHYSICSBODY_MATERIAL_DEFAULT);
    node->setPhysicsBody(paddleNode);

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
