### ISSUE TITLE
Bug of Node::getParentToNodeTransform()

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#10824]
Engine version: 3.3
More detail information please refer to [this ticket](http://www.cocoachina.com/bbs/read.php?tid-287885.html)

**Comment by litefeel** [comment]
TextBMFont ?

**Comment by wantnon2** [comment]
minggo，连接好像给错了。

**Comment by minggo** [comment]
Thanks guys.
Corrected the url.

**Comment by dabingnn** [comment]
@pandamicro @andyque 
Bug has been fixed in version 3.7. please close it.
