### ISSUE TITLE
Unsupported Platform error on Linux

### ISSUE THREAD

**Issue by kenanb** [cocos2d/cocos2d-x#10826]
I'm testing on on Arch Linux x86-64 with commit https://github.com/cocos2d/cocos2d-x/commit/b02293d012ca9cb3177c79a4d79184384cd34f16 on v4-develop.

When I normally build repo with cmake tests run perfectly. When I try to build a repo using `cocos new foo -l lua` and then `cocos run -p linux` I get `CMake Error at CMakeLists.txt:73 (message): Unsupported platform, CMake will exit` error.

It seems to be broken as of this commit: https://github.com/cocos2d/cocos2d-x/commit/4810a8314775efd37b6e05d3ff3e6f390768a6b1

**Comment by kenanb** [comment]
It seems all `CMakeLists.txt` files including the ones in `tests` folder are changed in commit https://github.com/cocos2d/cocos2d-x/commit/4810a8314775efd37b6e05d3ff3e6f390768a6b1 but the `CMakeLists.txt` files in `templates` folder has stayed exactly the same. Is it possible that some needed revisions to those are forgotten? Because Cocos builds perfectly, tests build perfectly too. Only the projects that are based on templates fail to build. Also there are Thread related changes in that commit. And the error is threads related. So it seems to be the root of the problem.

I want to help more to solve the issue but I don't know enough about Cocos internals to fix it myself. Let me know if I can help any other way.

And thank you, in advance.

**Comment by kenanb** [comment]
Ok, it turns out some definitions are removed from `CMakeBuildHelpers` and some are modified. But those modifications are not reflected to `CMakeLists.txt` files in `templates` folder.

The problems I could find are:

`pre_build` macro is removed from CMakeBuildHelpers, but it is still used in templates.
Variables like `LINUX`, `WINDOWS` are replaced with `COCOS_TARGET_SYSTEM` but templates still use the old versions.

**Comment by kenanb** [comment]
So removal of cocosstudio, cocosbuilder and spine related code from `templates/lua-template-default/frameworks/runtime-src/Classes/lua_module_register.h` and some modifications to `templates/lua-template-default/frameworks/CMakeLists.txt` made it work again. These two revisions did the job for me: https://gist.github.com/kenanb/2e324862e69c28e940ab

I don't think putting back `pre_build` macro inside CMakeLists.txt file is something you would want. There was probably a reason for its removal from CMakeBuildHelpers. So I won't make a pull request for that. I hope these code snippets makes it easy to see the problem.

Thank you.

**Comment by yangws** [comment]
Recently, cmake config has been adjusted for support multi-platform, new project templete out of sync with this modification, we'll fix this problem as soon as possiable.

**Comment by kenanb** [comment]
@yangws thank you very much. Good luck. :)

**Comment by kenanb** [comment]
This issue seems to be fixed now. Thank you.
