### ISSUE TITLE
TransitionTurnOffTiles bug

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10834]
`version:` 3.4Final
`issue:` While the scene is transiting by `TransitionTurnOffTiles` mode, close the app will crash.
the error is

``` cpp
CCASSERT(!_running, "Node still marked as running on node destruction! Was base class onExit() called in derived class onExit() implementations?");
```

`reproduce:`the bug can be reproduced in the TestCpp.

**Comment by drelaptop** [comment]
https://github.com/cocos2d/cocos2d-x/issues/17819#issuecomment-302991126 answer this issues
