### ISSUE TITLE
Adding and removing tiles from a TMXLayer messes up atlas index

### ISSUE THREAD

**Issue by fleshgolem** [cocos2d/cocos2d-x#1083]
See http://www.cocos2d-x.org/boards/6/topics/4336

**Comment by sburavtsov** [comment]
I confirm issue exists and fix as by link above.
Please pull this fix to master.

**Comment by godyZ** [comment]
@fleshgolem  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2685
