### ISSUE TITLE
generate pre-built libraries fails

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#10830]
xcodebuild: error: The project '/Users/chukongus/Chukong-Inc/cocos2d-x/tools/gen-prebuilt/../../cocos/scripting/lua-bindings/proj.ios_mac/cocos2d_lua_bindings.xcodeproj' does not contain a target named 'build all lualibs iOS'.
Traceback (most recent call last):
  File "./gen_prebuilt_libs.py", line 358, in <module>
    gen_obj.do_generate()
  File "./gen_prebuilt_libs.py", line 344, in do_generate
    self.build_all_libs()
  File "./gen_prebuilt_libs.py", line 331, in build_all_libs
    self.build_ios_mac()
  File "./gen_prebuilt_libs.py", line 300, in build_ios_mac
    run_shell(build_cmd, self.tool_dir)
  File "./gen_prebuilt_libs.py", line 42, in run_shell
    raise subprocess.CalledProcessError(returncode=p.returncode, cmd=cmd)
subprocess.CalledProcessError: Command 'xcodebuild -project "/Users/chukongus/Chukong-Inc/cocos2d-x/tools/gen-prebuilt/../../cocos/scripting/lua-bindings/proj.ios_mac/cocos2d_lua_bindings.xcodeproj" -configuration Release -target "build all lualibs iOS" -sdk iphonesimulator CONFIGURATION_BUILD_DIR=/Users/chukongus/Chukong-Inc/cocos2d-x/tools/gen-prebuilt/prebuilt/ios/simulator' returned non-zero exit status 65

**Comment by walzer** [comment]
Thanks for feedback. But next time please add your engine version.
I would close this issue, and leave it to QA team to test carefully on current version.
