### ISSUE TITLE
EaseRateAction::create()

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#10835]
`version:` 3.3Final
`issue:`

in `v2.x` Cocos2d-x have the API: 

``` cpp
static CCEaseRateAction* create(CCActionInterval* pAction, float fRate);
```

but in `v3.x` the `create` method is removed, and what is the substitute？

**Comment by minggo** [comment]
Yep.
It is a problem.

I think it is because construction becomes protected but forgot to add corresponding create method.
