### ISSUE TITLE
NSLog in HttpAsynConnection

### ISSUE THREAD

**Issue by Mazyod** [cocos2d/cocos2d-x#10858]
In general, `NSLog` statements used for debugging should never make it to production code, however, there are a bunch of `NSLog` statements in `HttpAsynConnection` class.

I was wondering if they should be removed completely, or converted into `DLog`? `DLog` will be a new ObjC macro that will only print in DEBUG mode.

**Comment by Mazyod** [comment]
Any thoughts on this?

**Comment by walzer** [comment]
Scheduled into current version.
Thanks for your feedback!

**Comment by fusijie** [comment]
@Mazyod As following picture, you can uncheck **Debug executable** item to turn off `NSLog` output in RELEASE mode.
![schemes](https://cloud.githubusercontent.com/assets/5085300/8665935/734ffe84-2a1c-11e5-82cd-cf0f7334f84d.png)

**Comment by Mazyod** [comment]
@fusijie thanks, but I don't think that will solve the issue. What you are proposing is not attaching the debugger to the app, so the NSLog is still working, but you don't see it. It's like sweeping the dirt under the rug :)

**Comment by fusijie** [comment]
@Mazyod Thanks so much, I have fixed it in https://github.com/cocos2d/cocos2d-x/pull/12875.

**Comment by Mazyod** [comment]
🌹 thank you
