### ISSUE TITLE
WebView Android not support file upload

### ISSUE THREAD

**Issue by 0xJimmyBeh** [cocos2d/cocos2d-x#10862]
There is no openFileChooser in WebView Android which allow user to choose file for upload in WebView.

WebView iOS is working properly for photo select and take photo with camera.

Tested with webpage :
http://www.anyimg.org/

**Comment by walzer** [comment]
I'm not sure if we can fix it. `ui::WebView` just simply invoke `webkit.webview` from android sdk. If android sdk don't support this feature, then we have nothing to do.

**Comment by 0xJimmyBeh** [comment]
The button in the website is working on mobile browser, Google Chrome.
It show "choose an action" after click the button.

I do found people reported some issues on the Android openFileChooser.

So can we check how the mobile Google Chrome make it work and implement in Cocos2d-x WebView?

Here are some examples, hope it help solving the problem.
http://androidexample.com/Open_File_Chooser_With_Camera_Option_In_Webview_File_Option/index.php?view=article_discription&aid=128&aaid=148
http://stackoverflow.com/questions/28600165/cant-open-file-chooser-in-webview-android-4-4-2-using-webchromeclient

**Comment by zilongshanren** [comment]
@Zinitter  If we want to add upload feature to WebView, then the iOS platform should also support it.
We don't have any plan for this.
