### ISSUE TITLE
Render to RenderTexture with User Camera not working

### ISSUE THREAD

**Issue by zilluss** [cocos2d/cocos2d-x#10877]
When I render to a RenderTexture, the camera for the visited nodes is ignored. For example if I try to do something like this:

```
auto camera = Camera::createPerspective(60, (GLfloat)screenSize.width/screenSize.height, 1, 10000);
camera->setCameraFlag(CameraFlag::USER8);

auto someSprite = Sprite::create("test.png");
someSprite->setCameraMask((unsigned short)CameraFlag::USER8);

auto renderTexture = RenderTexture::create(screenSize.width, screenSize.height);
renderTexture->beginWithClear(0, 0, 0, 0);
someSprite->visit();
renderTexture->end();
```

The camera is ignored.

**Comment by tangziwen** [comment]
because the Camera::_visitingCamera is not set yet , there are two solutions to solve it 
(1) hack the CCCamera.cpp file add a method like setVisitingCamera,then invoke it before you visit your sprite
(2) the Camera::_visitingCamera is set in the Scene::render , you can add your sprite into an scene ,say that S , then invoke S->render(Director::getInstance()->getRenderer()).

**Comment by super626** [comment]
@zilluss 
Thanks

Please read the comment above.

**Comment by markovitch57** [comment]
cocos2dx ccUtils captureScreen works fine with 3D and, I assume, anything.

**Comment by markovitch57** [comment]
and here is a working example of (cut down) captureScreen which derives texture and returns sprite instead of saving image to file:

Sprite \*  CcGlobal::getScreenAsSprite(void) {
    Size screenSize = Director::getInstance()->getWinSize();
    int width = screenSize.width;
    int height = screenSize.height;

```
std::shared_ptr<GLubyte> buffer(new GLubyte[width * height * 4], [](GLubyte* p) { CC_SAFE_DELETE_ARRAY(p); });
glPixelStorei(GL_PACK_ALIGNMENT, 1);
glReadPixels(0, 0, width, height, GL_RGBA, GL_UNSIGNED_BYTE, buffer.get());

Image* image = new (std::nothrow) Image;
image->initWithRawData(buffer.get(), width * height * 4, width, height, 8);

Texture2D *texture = new (std::nothrow) Texture2D();
texture->initWithImage(image);
SpriteFrame *spriteFrame = SpriteFrame::createWithTexture(texture, Rect(Vec2(0, 0), screenSize));
Sprite *sprite = Sprite::createWithSpriteFrame(spriteFrame);
sprite->setFlippedY(true);
delete image;
return sprite;
```

}
