### ISSUE TITLE
bug in Lua manual binding

### ISSUE THREAD

**Issue by lzubiaur** [cocos2d/cocos2d-x#10875]
Hi, cc.GLProgram:setUniformLocationF32 only takes up to 4 parameters but it should be possible to pass up to 5 parameters.

Line 3815 in lua_cocos2dx_manual.cpp there's a typo that prevent to pass up to 5 parameters. 

```
if (4 == argc)
```

should be 

```
if (5 == argc)
```

Thanks.

**Comment by samuele3hu** [comment]
Yes, it's a low-level error,i would fix it.Thanks to @lzubiaur.
