### ISSUE TITLE
feature request: add ability to track current number of live nodes

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#10874]
This is a feature request. In debugging, I've personally found it helpful to see how many live Node's currently exist. Usually, if this number increases significantly over time, that's an indication that I have some kind of object leakage going on somewhere. 

```

+static int s_liveNodesCount = 0;
+
+
 bool nodeComparisonLess(Node* n1, Node* n2)
 {
     return( n1->getLocalZOrder() < n2->getLocalZOrder() ||


@@ -150,6 +154,8 @@ Node::Node(void)
     _scriptType = engine != nullptr ? engine->getScriptType() : kScriptTypeNone;
 #endif
     _transform = _inverse = _additionalTransform = Mat4::IDENTITY;
+
+    ++s_liveNodesCount;
 }

 Node * Node::create()
@@ -166,10 +172,20 @@ Node * Node::create()
     return ret;
 }

+
+int Node::getLiveNodesCount()
+{
+    return s_liveNodesCount;
+}
+
+
+
 Node::~Node()
 {
     CCLOGINFO( "deallocing Node: %p - tag: %i", this, _tag );

+    --s_liveNodesCount;
+
 #if CC_ENABLE_SCRIPT_BINDING
```

**Comment by walzer** [comment]
Sorry I would deny your request.
This is a good feature, and I would like to implement it inside Code IDE, instead of write it in cocos2d-x.

**Comment by ginobean** [comment]
I am curious how you would implement in the Code IDE ? 

The advantage of tracking it in CCNode.cpp is that you can just maintain a static integer counter that just tracks each time a Node is constructed or destructed.  Overhead should be negligible yet provide what I have found to be a fairly useful way to quickly ascertain if something has run amuck.

Here's how I modified the code in my local version of cocos2d-x:

```
[near the top of CCNode.cpp]
static int s_liveNodesCount = 0;

[near the end of Node::Node (void) ]
  ++s_liveNodesCount;

[near the beginning of Node::~Node()]
  --s_liveNodesCount;


and add a method to access the current live nodes count:
int Node::getLiveNodesCount()
{
    return s_liveNodesCount;
}

```
