### ISSUE TITLE
Test automation

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#10882]
Corresponding discussion ticket: http://discuss.cocos2d-x.org/t/tests-automation/20272

**Comment by walzer** [comment]
Related to:
#11362
#11357 
#11351 
#11309 
#11272 
#11256

**Comment by WenhaiLin** [comment]
Put back the test cases of performance: https://github.com/cocos2d/cocos2d-x/pull/11778

**Comment by WenhaiLin** [comment]
That's the first stage done:the unit testing framework done and all test cases can run on the testing framework.

 The next stage:make test cases return the unit  test result,etc.
