### ISSUE TITLE
Synchronize 3rd party libraries

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#10885]
3rd party libraries in [3rd party src repo](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src) and [3rd party bin repo](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin) are not sync. They have different versions.

**Comment by walzer** [comment]
Close this issue because we're not using src repo to update bin repo in v3.x
