### ISSUE TITLE
move cocos2d_libs.xcodeproj and cocos2d_tests.xcodeproj to a different path

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#10906]
Currently, they are located under `cocos2d/build`

The problem with this is that the build directory is typically used to house artifacts. I believe this is a fairly standard and common industry practice. And I think most experienced developers would also expect a build directory to only house artifacts as well.

For example, gradle uses a build directory to house artifacts. Android Studio uses a build directory to house artifacts. etc.

So I've instructed git (version control) to ignore any directories that are named 'build'. 

Now, because cocos2d_libs.xcodeproj is currently located under cocos2d/build, git will no longer version control it.

I suggest maybe moving cocos2d_ibs.xcodeproj from `cocos2d/build` to something like: `cocos2d/cocos-lib`

**Comment by walzer** [comment]
Sounds reasonable. But I still have the fear to modify file names and folder name after v3.0. Too much developers complained the huge modification from v2 to v3.

So, I prefer to deny your request because it maybe better but will break the consistency.
