### ISSUE TITLE
io.open(filepath) would failed on the android platform because of the the file is in the package

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#10914]

**Comment by minggo** [comment]
What's io.open()?

**Comment by samuele3hu** [comment]
io module is a standard module of Lua. `open` is a function of io module.

**Comment by minggo** [comment]
Got it.
Is it an issue?
May be we should use FileUtils to open a file.

**Comment by walzer** [comment]
Deny. Use `FileUtils` as standard API of cocos. Otherwise CocosPlayClient can't be notified.
