### ISSUE TITLE
strange behavior of Node::setRotation3D with different anchor points

### ISSUE THREAD

**Issue by woc2006** [cocos2d/cocos2d-x#10928]
1. Add a sprite to scene, set anchor point to center, and position to center sceen, and rotate the sprite by it's x axis, like below:

``` cpp
    auto sprite = Sprite::create("HelloWorld.png");

    // position the sprite on the center of the screen
    sprite->setPosition(Vec2(visibleSize.width / 2, visibleSize.height / 2));
    sprite->setAnchorPoint(Vec2(0.5, 0.5));

    // add the sprite as a child to this layer
    this->addChild(sprite);

    sprite->setRotation3D(Vec3(-45,0,0));
```

Result looks correct.

![0](https://cloud.githubusercontent.com/assets/1716430/6685331/e1d343bc-ccd3-11e4-8d6e-c5a111034c56.png)
1. Change anchor point to bottom left, and position to zero, like below:

``` cpp
    sprite->setPosition(Vec2::ZERO);
    sprite->setAnchorPoint(Vec2::ZERO);
```

Result 

![1](https://cloud.githubusercontent.com/assets/1716430/6685379/3f3e6450-ccd4-11e4-9b98-d5ae6b322c55.png)

The sprite is cropped.

Tested with latest commit of cocos branch v3.
Platform: win7 64bit.

**Comment by woc2006** [comment]
Is this bug or i missed something?

**Comment by super626** [comment]
@woc2006 
@walzer 
It is cropped by the camera.

Take a look at the default camera.

``` c++
bool Camera::initDefault()
{
//
case Director::Projection::_3D:
        {
            float zeye = Director::getInstance()->getZEye();
            initPerspective(60, (GLfloat)size.width / size.height, 10, zeye + size.height / 2.0f);
            Vec3 eye(size.width/2, size.height/2.0f, zeye), center(size.width/2, size.height/2, 0.0f), up(0.0f, 1.0f, 0.0f);
            setPosition3D(eye);
            lookAt(center, up);
            break;
        }
//
}
```

The camera's near plane is 10, and far plane is zeye + size.height/ 2.0f;
Only the scene between the near plane and far plane can be seen.
