### ISSUE TITLE
OpenGL error 0x0502 in CCTextureAtlas.cpp drawNumberOfQuads 689

### ISSUE THREAD

**Issue by twolight** [cocos2d/cocos2d-x#10925]
I use a sdk.
In java code
if (_glSurfaceView != null) {
            _glSurfaceView.queueEvent(new Runnable() {
                @Override
                public void run() {
                    nCompletedVideo();
                }
            });
}
in nCompletedVideo method,I post a notify event.
And in the reception method,I add a view to the window.
but the BMFont in the view can not be displayed.

**Comment by woc2006** [comment]
try runInGLThread

**Comment by twolight** [comment]
i solved that call the view in delay.
may be, Android need more time to exchange the thread.
so strange!

**Comment by walzer** [comment]
Solved by issue owner.
