### ISSUE TITLE
Proper singleton pattern for CCApplication::sharedApplication()

### ISSUE THREAD

**Issue by mfellner** [cocos2d/cocos2d-x#1093]
I was wondering why [CCApplication](https://github.com/cocos2d/cocos2d-x/blob/gles20/cocos2dx/platform/ios/CCApplication.mm) doesn't follow the traditional singleton pattern. Currently `CCApplication::sharedApplication()` will result in an error if no instance exists and `CCApplication()` will too if an instance already exists. Is there are reason this is not implemented like the following?

``` c++
static CCApplication& sharedApplication() {
    static CCApplication instance;
    return instance;
}
```

This would be useful when deviating from the default project setup, e.g. when integrating a cocos2d-x application into an existing Android or iOS app.

**Comment by minggo2** [comment]
Because this class is a abstract class, it should be inherited.

**Comment by donaldalanmorrison** [comment]
@minggo This issue can be closed as "not an issue".  The referenced code uses a Class Variable (static member variable) rather than an instance variable.  Note also that the assert statement enforces the singleton pattern in DEBUG builds.
