### ISSUE TITLE
Incorrect windows behavior: applicationWillEnterForeground

### ISSUE THREAD

**Issue by MFHSchoonbrood** [cocos2d/cocos2d-x#10933]
Hi guys,

Minimizing and maximizing a window on windows will correctly trigger applicationDidEnterBackground and applicationWillEnterForeground.
But if you don't minimize the cocos2d-x game, but activate something else, and then activate the cocos game again, you will recieve 2 applicationWillEnterForeground events.

Is this done on purpose, or is this a bug?

Because naming wise, this is illogical. If I deactivate my app (by activating something else), my app has entered the background, even if it's still visible. It is also inconsistent with how, for example, the google billing dialog is handled on Android.

Imo, glfwSetWindowFocusCallback should be used instead of glfwSetWindowIconifyCallback.
That is assuming that the window focus callback is also called when an app is iconified.

Kind regards,
Michaël

**Comment by minggo** [comment]
Windows platform is just to be convenient for developing mobile games, so close this issue.
