### ISSUE TITLE
Listview pushbackdefaultitem ignore Text setTextColor

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#11006]
This is what I have noticed, following wiki example on Listview: (omitting cosmetic rows)

auto lv = ListView::create();
for (int i = 1; i <= 5; i++) {
  auto lvItem = Layout::create();
  auto lvText = Text::create("Test");
  lvText->setTextColor(Color4B::BLACK);
  lvItem->addChild(lvText);
  lv->setItemModel(lvItem);
  lv->pushBackDefaultItem();
}

The setTextColor doesn't work, the Text is default white.

But if I use
   lv->pushBackCustomItem(lvItem);

It works.

My fault or bug?

**Comment by zilongshanren** [comment]
it should be resolved in the latest develop branch.
