### ISSUE TITLE
[Possible bug?]v3.4 Label memory leak in mac but not in iOS?

### ISSUE THREAD

**Issue by amuseamuse** [cocos2d/cocos2d-x#11019]
also posted in:
http://discuss.cocos2d-x.org/t/possible-bug-label-memory-leak-in-mac-but-not-in-ios/20555

cocos2d-x version:3.4 (download from cocos2d-x.org)
platform: macbook pro/10.10.2

I created a scene which has a function to create and destroy Label continuously:

HelloWorldScene.h

```
#include "cocos2d.h"
class HelloWorld : public cocos2d::Layer{
public:
    static cocos2d::Scene* createScene();
protected:
    virtual bool init();
    CREATE_FUNC(HelloWorld);
};
```

HelloWorldScene.cpp

```
#include "HelloWorldScene.h"
USING_NS_CC;
Scene* HelloWorld::createScene(){
    auto scene = Scene::create();
    auto layer = HelloWorld::create();
    scene->addChild(layer);
    return scene;
}
bool HelloWorld::init(){
    if ( !Layer::init() ){
        return false;
    }
    Vector<FiniteTimeAction*> actionList;
    for(int i=0;i<1000;i++){
        CallFunc *f=CallFunc::create(
            [=]{
                removeAllChildren();
                Label* label=Label::create();
                addChild(label);
                label->setPosition(Director::getInstance()->getVisibleSize()/2);
                label->setString(std::to_string(i));
                label->setSystemFontSize(60);
                label->setTextColor(Color4B::WHITE);
                //Sprite* s=Sprite::create("HelloWorld.png");
                //jumpNumberNode->addChild(s);
            }
        );
        actionList.pushBack(f);
        actionList.pushBack(DelayTime::create(0.033));
    }
    runAction(Sequence::create(actionList));
    return true;
}
```

when run,I found in iOS simulator the memory usage seems remains unchanged.
But in mac the memory seems grow continuously.
(at http://discuss.cocos2d-x.org/t/possible-bug-label-memory-leak-in-mac-but-not-in-ios/20555 there is running video post)
I found both Label::create and Label::createWithTTF have similar problem

I also changed Label to Sprite:

Sprite\* s=Sprite::create("HelloWorld.png");
jumpNumberNode->addChild(s);
but this time the memory usage seems remains unchanged in both platform.

Is Label have memory leak in mac?

**Comment by qiululu** [comment]
using xcode profile <img width="819" alt="pf" src="https://cloud.githubusercontent.com/assets/5564318/8773478/249e2a50-2f07-11e5-972f-416995723654.png">and testing tools on mac to run your code
<img width="960" alt="memlk" src="https://cloud.githubusercontent.com/assets/5564318/8773484/2f883ec4-2f07-11e5-9d53-14760fb4c8dc.png">,there seem no problem

**Comment by qiululu** [comment]
<img width="955" alt="memlk2" src="https://cloud.githubusercontent.com/assets/5564318/8773595/e6bad304-2f07-11e5-94cb-1696a5b2f0dd.png">

**Comment by pandamicro** [comment]
@amuseamuse Please check out our research. I will close this issue for now, if there is any other way to reproduce the memory leak, please reopen this issue

**Comment by seivan** [comment]
@pandamicro This doesn't seem to be fixed. 
I just encountered it myself actually. It's quite a jump in memory.

Related
http://discuss.cocos2d-x.org/t/possible-bug-label-memory-leak-in-mac-but-not-in-ios/20555
http://cocos2d-x.org/issues/4918
