### ISSUE TITLE
CCBReader does not load CCSprite with no SpriteFrame defined

### ISSUE THREAD

**Issue by kagakuninja** [cocos2d/cocos2d-x#1101]
Create a CCSprite, and leave the Sprite Frame property at its default value (blank).  When you load the .ccbi file, there will be a null pointer error.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2684
