### ISSUE TITLE
UIImageView exported from cocostudio with scale9 enabled has wrong position

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#11022]
Exporting image from cocostudio with enabled scale9 through atlas causes wrong positioning

![scale9bug4](https://cloud.githubusercontent.com/assets/4668006/6747849/a4e46b8c-cee7-11e4-8550-81eb356b58b8.png)

sample project here
http://discuss.cocos2d-x.org/t/uiimageview-exported-from-cocostudio-with-scale9-bug/20544

**Comment by zilongshanren** [comment]
@sbrednikhin Which Engine version do you use?
Could your try the latest v3.8beta version and see if this issue is still exists?
Thanks.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
