### ISSUE TITLE
CCTextFieldTTF do not use UTF string for ANDROID

### ISSUE THREAD

**Issue by Yria** [cocos2d/cocos2d-x#1104]
CCTextFieldTTF\* ttf = CCTextFieldTTF::textFieldWithPlaceHolder("", "American Typewrite", 30);
ttf->setString("Eng한글");

const char\* txt = CCIMEDispatcher::sharedDispatcher()->getContentText();

txt is not NULL, but nativeGetContentText() return "";

how i fix that?

**Comment by Yria** [comment]
I'm sorry. setString must locate above attachWithIME.

**Comment by minggo** [comment]
I think you should record strings in a xml file, which format is utf-8.
Then read the strings from the xml file.
Don't write the string in codes.
