### ISSUE TITLE
Set Camera Flag on newly added children

### ISSUE THREAD

**Issue by milos1290** [cocos2d/cocos2d-x#11064]
I've noticed that that when you set a camera flag on parent node, only the current children that are already added to that node will have same camera flag. Newly added children will have default camera flag.

This is a snippet from Node

``` cpp
// MARK: Camera
void Node::setCameraMask(unsigned short mask, bool applyChildren)
{
    _cameraMask = mask;
    if (applyChildren)
    {
        for (const auto& child : _children)
        {
            child->setCameraMask(mask, applyChildren);
        }
    }
}
```

**Comment by walzer** [comment]
Designed as this.
