### ISSUE TITLE
cannot find -lCocosDenshion (Blackberry)

### ISSUE THREAD

**Issue by kslam** [cocos2d/cocos2d-x#1106]
Hi,
I found a problem that after I compile I got an error of "cannot find -lCocosDenshion" as below.

/Developer/SDKs/bbndk-2.1.0-beta1/host/macosx/x86/usr/bin/ntox86-ld: cannot find -lCocosDenshion
cc: /Developer/SDKs/bbndk-2.1.0-beta1/host/macosx/x86/usr/bin/ntox86-ld error 1
Build error occurred, build is stopped

I using bbndk-2.1.0-beta1.

Thank you.

Lam

**Comment by ghost** [comment]
You need to build the CocosDenshion library object (.a file) by importing it into Momentics and building it. Just do Import->Existing projects and specify the cocos2d-x root folder, you should see a list of all possible projects to import. Pick the one for BlackBerry. 

Once you've built that successfully add the CodeDenshion library path to your linker settings as follows: 

![image](https://f.cloud.github.com/assets/2378847/201351/48f1a06c-80ef-11e2-9829-74358ec84e92.png)

Note that {ConfigName} is resolved to your current build configuration e.g. Device-Debug
