### ISSUE TITLE
mutiTouch trigger touches always only one size

### ISSUE THREAD

**Issue by jianglong0156** [cocos2d/cocos2d-x#11073]
cpp-tests mutitouchTest sample. 
I add the test code 
![image](https://cloud.githubusercontent.com/assets/3940568/6775612/b4f85f54-d16e-11e4-9cc8-c4a8e43d7a66.png)

But the touches' size always one.

engine version:Cocos2d-x 3.4
platform:android4.0 
device:xt885

the test codes in onTouchesBegan:

```
char strTemp[1024] = "";
sprintf(strTemp, "%s\ntouch length:%d", this->_label->getString().c_str(), touches.size());
this->_label->setString(strTemp);
```

**Comment by walzer** [comment]
engine version? target platform and its version?
You should work like this!

**Comment by pandamicro** [comment]
When @dumganhar originally designed the event system, he wrapped events with our high level APIs, but he didn't change any behavior of targeted platforms. On android, mutiTouch `onTouchesBegan` did always trigger once for every touch (event contains only one touch), so the behavior is different than iOS.

There is no optimal solution for this problem, the solution proposed by @yangws solve the different behavior, but it cause a slight delay at `onTouchesBegan` event.

@ricardoquesada and @zilongshanren both think the delay is not acceptable for certain type of games, so we won't merge this solution. If anyone really need it and don't care about the side effect, please refer to the pull request and apply it by yourself.

If anyone have other thoughts on this issue, please comment or propose another PR, I will close this issue for now
