### ISSUE TITLE
CMakeLists.txt in Templates/lua-template-default looks for ide-support in v4-develop

### ISSUE THREAD

**Issue by kenanb** [cocos2d/cocos2d-x#11098]
There is a bug in `v4-develop` branch `templates/lua-template-default/frameworks/CMakeLists.txt`:

```
cocos_target_sources(${app_name} GROUP "Classes\\ide-support" FILES
"runtime-src/Classes/ide-support/CodeIDESupport.h"
"runtime-src/Classes/ide-support/SimpleConfigParser.cpp"
"runtime-src/Classes/ide-support/SimpleConfigParser.h"
)
```

There is no `ide-support` folder in `v4-develop`. It is only in v3. So these lines cause cmake error.

**Comment by zilongshanren** [comment]
@kenanb 
Thanks, could you make a PR to resolve this issue?

**Comment by walzer** [comment]
I would like to deny this request, because:
1. we suspend v4 plan, and will focus on v3 in at least 6 months. 
2. lua-template-default is for empty project without neither IDE nor studio support, while lua-template-runtime is for IDE.

**Comment by kenanb** [comment]
that was not a feature request, it is a bug :D the solution was to remove the the extra target source code from the folder, not adding IDE support to template.
