### ISSUE TITLE
update 3rd party libraries

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#11107]

**Comment by minggo** [comment]
- update libcurl to v7.4
- update chipmunk to v6.2.2
- update openssl to v1.0.11
- update png to v1.6.16
- update freetype to v2.5.5

**Comment by felixjingga** [comment]
Hi, can't you update the openssl to latest version? 1.0.2a?

**Comment by zilongshanren** [comment]
@felixjingga 
What's the benefit for updating openssl to 1.0.2.a?
