### ISSUE TITLE
Create toggle fullscreen at runtime for Mac and Win32.

### ISSUE THREAD

**Issue by PinchukAlexey** [cocos2d/cocos2d-x#11127]
Cocos2d-x 3.4 use glfw 3.0. And it hasn't this feature.
http://discuss.cocos2d-x.org/t/cocos2dx-3-4-how-to-create-toggle-fullscreen-at-runtime-mac-win32/20640/3

**Comment by stevetranby** [comment]
Please include this feature in cocos2d-x 3.x as well as 4.x

**Comment by walzer** [comment]
Duplicated with #8321. Let's keep on tracking that issue, and close this one.

**Comment by digitalhoax** [comment]
Only partially duplicated, win32 isn't explicitly mentioned in #8321
