### ISSUE TITLE
Performance improvement in UI system

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#11145]
Batch draw call as much as possible.

**Comment by man2** [comment]
is this done in 3.6?

**Comment by zilongshanren** [comment]
@man2  The performance of UI doesn't improve much in v3.6.   We planed to use manual batch to improve the performance, but it fails in the end. 
Currently only QuardCommand and TriangleCommand could be batched.  UI elements with different Z order can't be batched.

But we could improve the performance of ui::ListView by reusing the cell. This could be done in v3.7.

**Comment by man2** [comment]
ok, sad to hear, because it's a really important issues i'm having right now. hope to see this feature really soon
