### ISSUE TITLE
add ability to add a post step callback to PhysicsWorld

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#11154]
please add the ability to add a post step callback to the PhysicsWorld.

For example, this is useful when you want to perform an operation that occurs outside of a physics step, such as removing physics objects that are no longer valid or updating the gravity vector on the fly:

```
 _physicsWorld->setPostStepCallback([this] {
            this->removeZombieObjectsFromWorld();
            this->updateGravityVector();
        });
```

something like this:

```
-- a/cocos2d/cocos/physics/CCPhysicsWorld.h
+++ b/cocos2d/cocos/physics/CCPhysicsWorld.h
@@ -171,6 +171,8 @@ public:
      */
     void step(float delta);

+    void setPostStepCallback (std::function<void (void)> func);
+
 protected:
     static PhysicsWorld* construct(Scene& scene);
     bool init(Scene& scene);
@@ -213,6 +215,7 @@ protected:
     PhysicsDebugDraw* _debugDraw;
     int _debugDrawMask;

+    std::function<void (void)> _postStepCallback;

     Vector<PhysicsBody*> _delayAddBodies;
     Vector<PhysicsBody*> _delayRemoveBodies;

--- a/cocos2d/cocos/physics/CCPhysicsWorld.cpp
+++ b/cocos2d/cocos/physics/CCPhysicsWorld.cpp
@@ -816,6 +816,14 @@ void PhysicsWorld::step(float delta)
     }
 }

+
+void
+PhysicsWorld::setPostStepCallback(std::function<void ()> func)
+{
+    _postStepCallback = func;
+}
+
+
 void PhysicsWorld::update(float delta, bool userCall/* = false*/)
 {
     if (delta < FLT_EPSILON)
@@ -870,6 +878,9 @@ void PhysicsWorld::update(float delta, bool userCall/* = false*/)
     {
         debugDraw();
     }
+
+    if (_postStepCallback)
+        _postStepCallback();
 }

 PhysicsWorld::PhysicsWorld()
```

**Comment by WenhaiLin** [comment]
@ginobean You should register a collision listener by event dispatcher.
You can get access to contacts by implementing a contact listener. The contact listener supports several events: begin, pre-solve, post-solve and separate.

For more information: http://cocos2d-x.org/programmersguide/12/index.html#collision

**Comment by WenhaiLin** [comment]
@pandamicro @andyque This issue should be close.

**Comment by ginobean** [comment]
The reason why a separate post step callback is useful is that typically during a collision, as I understand it, it's not a good idea to destroy physics objects during the collision callback. 
So, typically, what I tend to do is, during the collision callback, set a flag on the object to indicate that the object should be removed/destroyed at the end of the current physics step. 
Then, in the post step callback, I can easily iterate through all objects that have this destroy flag set, and destroy them without adversely affecting the physics world. 
Has this changed lately so that this is no longer necessary ?

**Comment by WenhaiLin** [comment]
@ginobean OK, i get it.
