### ISSUE TITLE
The RichText Bug

### ISSUE THREAD

**Issue by SuYaoHui** [cocos2d/cocos2d-x#11163]
`version:`3.4Final
`issue:` The function of getVirtualRendererSize() No Effect in current frame.But you can get the value    in next frame.
`code:`

``` CPP```
bool HelloWorld::init()
{
    if ( !Layer::init() )
    {
        return false;
    }

    Size visibleSize = Director::getInstance()->getVisibleSize();
    Vec2 origin = Director::getInstance()->getVisibleOrigin();

    auto closeItem = MenuItemImage::create(
                                           "CloseNormal.png",
                                           "CloseSelected.png",
                                           CC_CALLBACK_1(HelloWorld::menuCloseCallback, this));

    closeItem->setPosition(Vec2(origin.x + visibleSize.width - closeItem->getContentSize().width/2 ,
                                origin.y + closeItem->getContentSize().height/2));

    auto menu = Menu::create(closeItem, NULL);
    menu->setPosition(Vec2::ZERO);
    this->addChild(menu, 1);

    auto richtext = ui::RichText::create();
    richtext->setContentSize(Size(40,40));
    richtext->ignoreContentAdaptWithSize(false);
    richtext->setPosition(visibleSize/2);
    richtext->setName("hello");
    for (int i =0; i <5; i++) {
        auto re1 = ui::RichElementText::create(1, Color3B::WHITE, 255, "aaaaaa", "Fonts/Marker Felt.ttf", 20);
        richtext->pushBackElement(re1);
    }
    richtext->setLocalZOrder(10);
    log("%f",richtext->getContentSize().width);
    log("%f",richtext->getVirtualRendererSize().width);
    this->addChild(richtext);

    return true;
}

void HelloWorld::menuCloseCallback(Ref* pSender)
{
    ui::RichText *node = (ui::RichText*)this->getChildByName("hello");
    log("%f",node->getVirtualRendererSize().width);
}
```

**Comment by minggo** [comment]
RichText is refactored, so close this issue.
