### ISSUE TITLE
a issue about the method replaceScene()

### ISSUE THREAD

**Issue by twolight** [cocos2d/cocos2d-x#11171]
I used to doing SpriteFrameCache::getInstance()->addSpriteFramesWithFile in construction method and creating ui view in init method.
if clicking the button fast to replace scene,and the layer of the scene do some thing waste time in  construction or init method,i found that will cause CREATE method  running some times.

so,do the waste time thing like addSpriteFramesWithFile and called init method  in onEnter method? 

And on the  way, I think:
bool Menu::onTouchBegan(Touch\* touch, Event\* event)
{
    if (_state != Menu::State::WAITING || ! _visible || !_enabled ||  !_running)
    {
        return false;
}
should add !_running in the if().
if the scene will be replaced but still is visible,shoud not  be called the onTouchBegan method.

**Comment by twolight** [comment]
replaceScene method does not really replace scene right now but next loop.
so the old scene is still can receive touch event and button callback is still triggered.

**Comment by walzer** [comment]
Sadly, the mechanism is designed as this. You can invoke `setTouchEnabled(false)` before `replaceScene()`
