### ISSUE TITLE
cocos2dx3.3  GLProgramState:setUniformVec2 to_lua Error

### ISSUE THREAD

**Issue by InfResearch** [cocos2d/cocos2d-x#11206]
The following error when I run lua-tests on windows7 :

error:
     cc.GLProgramState:setUniformVec2 argument #2 is 'string'; 'number' expected.

error:
     cc.GLProgramState:setUniformVec2 argument #2 is 'string'; 'number' expected.

**Comment by samuele3hu** [comment]
@ChenRenault, In the current mechanism of the Lua binding,all overload functions like setUniformVec2 of GLProgramState are integrated in a binding function.When we call the `cc.GLProgramState:setUniformVec2` in the Lua,it would find the adaptive function in the corresponding c++ binding method according to parameter type and the number of parameters. In the process of finding, it would output these error message as long as it meets the unadapted parameter type.It will not affect the final call.

**Comment by InfResearch** [comment]
@samuele3hu 
I see(Don't get it but feel cool :P),thanks.
