### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by scari** [cocos2d/cocos2d-x#11210]
Hello, I'm new here.
It looks like you're using python widely but only version 2, not python3.
Any plans? I would gladly lend a hand for that.

**Comment by minggo** [comment]
There is not plan right now.

**Comment by guoyingtao** [comment]
Any plan for supporting python 3 now?

**Comment by minggo** [comment]
No.

**Comment by itcoding-audatex** [comment]
What about now?

**Comment by vperilla** [comment]
At this time Python 2.7 will retire in 3 months, I think you should consider migrate to python 3

**Comment by minggo** [comment]
Python 2.7 is enough to cocos2d-x since it doesn't use a lot of python code.

**Comment by minggo** [comment]
The default python shift with macOS is also python 2.7.

**Comment by Heceldi** [comment]
From https://www.python.org/doc/sunset-python-2/ ... As of January 1st, 2020 no new bug reports, fixes, or changes will be made to Python 2, and Python 2 is no longer supported. ... Since we're past a year on from end of life, any support planned?

**Comment by MrBenGriffin** [comment]
The default python shift with macOS is **no longer Python2.7**

**Comment by PawelPajor** [comment]
What about now?

**Comment by vdoom** [comment]
It's really time to migrate Cocos2D-x to Python3.

**Comment by Vibhor-Kedia** [comment]
yeah a lot of people are having trouble

**Comment by Vibhor-Kedia** [comment]
what about now?

**Comment by MrBenGriffin** [comment]
> what about now?

I moved on. It is clear that the library is not committed to Python support.
