### ISSUE TITLE
[3.5 Cocos Framework + lua] Android prebuilt has errors?

### ISSUE THREAD

**Issue by hamburml** [cocos2d/cocos2d-x#11239]
Hi!

In 3.4 we were able to use cc.ParticleSystem to manipulate particles. The setTotalParticles ect were working. Not with 3.5 it's only working in cocos simulator on windows but not on android. I've made a thread here. http://discuss.cocos2d-x.org/t/3-5-lua-bindings-removed-from-particlesystem-android-prebuilt-has-error/20799 Any advice is appreciated.

Thanks!

**Comment by minggo** [comment]
@Michael-Hamburger 
Did you use cocos or cocos2d-x?

**Comment by hamburml** [comment]
Cocos framework. Prebuilt files are only delivered with cocos and not with cocos2d-x. Cocos2d-x also doesn't have the lua runtimes (which are now in cocos framework).

**Comment by hamburml** [comment]
Sorry, the setTotalParticles-Bindings are working (sadly the android apk simulator isn't working with them o.O). Should I leave this open or not?

**Comment by walzer** [comment]
Well, I close it. From my experience, debug your game on real devices, instead of simulator **as early as you can**
