### ISSUE TITLE
3.4 PhysicsJointMotor setRate and getRate Bad Access Crash

### ISSUE THREAD

**Issue by jimrange** [cocos2d/cocos2d-x#11240]
If setRate(50) or getRate are called on a PhysicsJointMotor after it is created (in the same code block that it was created in), then a bad access crash occurs on the iPhone 6 simulator and iPhone 5 device running iOS 8.2. 

If getRate or setRate are called later in an update / tick method, then no crash occurs.

This code below can be added to the case 10 in the PhysicsTest.cpp class to 

// This is existing code in the PhysicsTest.cpp test class.
` PhysicsJointMotor\* joint = PhysicsJointMotor::construct(sp1->getPhysicsBody(), sp2->getPhysicsBody(), (float)M_PI_2 \* 5); 
 _scene->getPhysicsWorld()->addJoint(joint); 

// This is new code to reproduce the crash, added below the above code in PhysicsTest.cpp
 auto rate = joint->getRate(); // getRate() will cause a bad access crash
 rate = rate + 1;
 joint->setRate(rate); // setRate(rate) will cause a bad access crash
`

**Comment by jimrange** [comment]
Please consider adding tests for the setters and getters of the physics constraints.
This issue exists in the PhysicsJointDistance, PhysicsJointLimit, PhysicsJointSpring, PhysicsJointGroove and might exist in other joints too.
Maybe the same pattern that causes the issue exists in other joints?

**Comment by jimrange** [comment]
PhysicsTest.cpp Version 3.6 

Line 697:
    PhysicsJointDistance\* joint = PhysicsJointDistance::construct(sp1->getPhysicsBody(), sp2->getPhysicsBody(), Point::ZERO, Point::ZERO);
    getPhysicsWorld()->addJoint(joint);
    **joint->setDistance(100); // This will cause a crash.**

Line 710:
    PhysicsJointLimit\* joint = PhysicsJointLimit::construct(sp1->getPhysicsBody(), sp2->getPhysicsBody(), Point::ZERO, Point::ZERO, 30.0f, 60.0f);
    getPhysicsWorld()->addJoint(joint);
    **joint->setMax(100); // This will cause a crash.**

Line 724: 
    PhysicsJointSpring\* joint = PhysicsJointSpring::construct(sp1->getPhysicsBody(), sp2->getPhysicsBody(), Point::ZERO, Point::ZERO, 500.0f, 0.3f);
    getPhysicsWorld()->addJoint(joint);
    **joint->setStiffness(100); // This will cause a crash.**

Line 738:
    PhysicsJointGroove\* joint = PhysicsJointGroove::construct(sp1->getPhysicsBody(), sp2->getPhysicsBody(), Vec2(30, 15), Vec2(30, -15), Vec2(-30, 0));
    getPhysicsWorld()->addJoint(joint);
    **joint->setAnchr2(Vec2(30,-15)); // This will cause a crash.**

**Comment by thinkong** [comment]
for this not to crash you could call initJoints manually.. but that only makes it not crash.. don't have the functionality i think

**Comment by jimrange** [comment]
Adding another similar issue. These crashes are all likely caused by the same pattern that occurs when using any of the setters and getters of joints immediately after the joint is created. 

orientSpring = PhysicsJointRotarySpring::construct(this->rotationObject->getPhysicsBody(), this->getPhysicsBody(), 0, 1500000);
Director::getInstance()->getRunningScene()->getPhysicsWorld()->addJoint(orientSpring);
**orientSpring->setRestAngle(0); // This will crash.**
