### ISSUE TITLE
3D Sprite Not Visible in Cocos2dx 3.4 and 3.5

### ISSUE THREAD

**Issue by hussain-sohaib** [cocos2d/cocos2d-x#11251]
This Problem occurred on iOS, I am not sure about android since I didn't tried it. 

We are trying to use 3D sprite in our game but it is not getting shown on the screen. Here is the code snippet that I use to bring on 3d sprite on screen .

auto sprite3d = Sprite3D::create("zhujue.c3b");

```
auto animation3d = Animation3D::create("zhujue.c3b");
auto animate3d = Animate3D::create(animation3d);
sprite3d->runAction(RepeatForever::create(animate3d));
sprite3d->setPosition(320, 480);
this->addChild(sprite3d, 100);
sprite3d->setScale(5.0f);
```

I used the zhujue.c3b file from programming guide sample even then its not being shown on the screen (I also added the zhujue_jian.png and zhujue.png files ). Could anyone please help me to understand what the problem is. I also used my own c3b file that I created after converting it from .fbx to .c3b file. C3t files are also not visible.

Thanks!

**Comment by masterhou** [comment]
Can you use testcpp's c3b file for a test.

**Comment by hussain-sohaib** [comment]
Hi,

So I just figured out, the issue is not that the c3b files are not visible
but they get hidden behind the 2d Sprites, no matter what you set the Z
value 3d sprite always gets hidden behind the 2d sprite. even if you add 3d
sprite as a child to 2d sprite 3d sprite appears behind the 2d sprite. I am
also sharing a pictures here. sprite1 is where tortoise is added to scene
with z value 100, sprite 2 is where tortoise is added to sprite helloworld
as a child .I used version 3.5 cocos2dx.

```
// position the sprite on the center of the screen
sprite->setPosition(Vec2(visibleSize.width/2 + origin.x,
```

visibleSize.height/2 + origin.y));

```
// add the sprite as a child to this layer
this->addChild(sprite, 0);
auto sprite3d = Sprite3D::create("tortoise.c3b");
// addChild(sprite3d);

auto animation3d = Animation3D::create("tortoise.c3b");
auto animate3d = Animate3D::create(animation3d);
sprite3d->runAction(RepeatForever::create(animate3d));
sprite3d->setPosition(320, 480);
sprite->addChild(sprite3d, 100);
sprite3d->setScale(.80f);
```

On Wed, Apr 1, 2015 at 7:10 PM, Thomas notifications@github.com wrote:

> Can you use testcpp's c3b file for a test.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cocos2d/cocos2d-x/issues/11251#issuecomment-88499352.

## 

Best Regards
Sohaib Hussain

**Comment by lvlonggame** [comment]
Three methods to deal this problem:
1. set 2d sprite global-z = -1, let the 2D sprite draw first.
2. use the camera's depth to control draw order, low depth will draw Priority.
3. create a empty 3D Sprite as the parent node, use the depth-test by set position3D.

**Comment by super626** [comment]
@hussain-sohaib

**Comment by walzer** [comment]
Solved by issue's owner.
