### ISSUE TITLE
There's no way to get the real height of Text Widget

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#11259]
Read this: http://discuss.cocos2d-x.org/t/new-ui-scrollview-with-text-widget-how-to-set-dynamic-height/20793

Please give us a function to determine dynamic height.

auto textWidget = Text::create("multiline text, blah blab blah", "mybeautyfont.ttf", 50);

There's no way to specify a fixed width, with a variable height.
The only workaround is described here:
http://discuss.cocos2d-x.org/t/ui-text-widget-does-not-wrapp-lines-solved/17877

**Comment by zilongshanren** [comment]
possible workaround:

comment out     `_labelRenderer->setDimensions(0,0);`

```
void Text::labelScaleChangedWithSize()
{
    if (_ignoreSize)
    {
    //    _labelRenderer->setDimensions(0,0);
        _labelRenderer->setScale(1.0f);
        _normalScaleValueX = _normalScaleValueY = 1.0f;
    }
```

And call `setTextAreaSize` to Size(450,0) to allow fixed width and variable height.
Now the content size of text widget is only used for layouting and positioning.

**Comment by pandamicro** [comment]
So what's the plan

**Comment by zilongshanren** [comment]
@pandamicro  I should apply my patch here.
I will do it tomorrow.
