### ISSUE TITLE
performance optimization,ask for help. too many arithmetic.

### ISSUE THREAD

**Issue by 1085075003** [cocos2d/cocos2d-x#11262]
there is 500+ sprite in screen, and 100+ sprite do the action like move, callback , rotate.
those action is cost cpu too much. how do i optimize ？reduce action?
![test](https://cloud.githubusercontent.com/assets/7587389/6965494/7e9408d2-d984-11e4-9b53-e87d306e3869.jpg)

**Comment by perminovVS** [comment]
You need analyze performance, find bottleneck and fix it.
You use sprite sheet ?

**Comment by 1085075003** [comment]
yes, I use sprite sheet,but the 500+ sprite call the function of setPosition every frame cost too much cpu.how can i optimize?

**Comment by 1085075003** [comment]
@perminovVS  yes, I use sprite sheet,but the 500+ sprite call the function of setPosition every frame cost too much cpu.how can i optimize?

**Comment by perminovVS** [comment]
Write fps call setPosition every frame and no set position

**Comment by walzer** [comment]
@1085075003 
1. Please discuss in the forum instead of this issue tracker
2. Have you used BatchNode?

**Comment by 1085075003** [comment]
@walzer I have solved the problem,thanks to everyone.
And, I asked this issue in the forum first, but no one answer me.You have to admit the forum is not a good place to ask question. A little problems have salved in the forum in two years.

**Comment by 1085075003** [comment]
@walzer I will not ask a question which is not a bug of cocos2d in git. thanks.

**Comment by walzer** [comment]
:+1:
