### ISSUE TITLE
Cocos 3.5 c++ In Windows 7 32 bit cocos script console output error 

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#11279]
i executed python setup.py and it executed succefuly 
then i closed the CMD and reopen it tryed to excute this command (what i do always ):
 `cocos new help`

and i get this error 

```
D:\dev\cpp\2d\cocos2d-x-3.5\cocos2d-x-3.5>cocos new help
Traceback (most recent call last):
  File "D:\dev\cpp\2d\cocos2d-x-3.5\cocos2d-x-3.5\tools\cocos2d-console\bin\/cocos.py", line 22, in <module>
    import cocos_project
  File "D:\dev\cpp\2d\cocos2d-x-3.5\cocos2d-x-3.5\tools\cocos2d-console\bin\cocos_project.py", line 4, in <module>
    import cocos
  File "D:\dev\cpp\2d\cocos2d-x-3.5\cocos2d-x-3.5\tools\cocos2d-console\bin\cocos.py", line 26, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict
D:\dev\cpp\2d\cocos2d-x-3.5\cocos2d-x-3.5>
```

**Comment by natural-law** [comment]
@meiry, I think the version of your python is lower than 2.7.
Because `OrderedDict` is a new class in python version 2.7. Take a look at the document of python here : https://docs.python.org/2/library/collections.html?highlight=ordereddict

The `cocos` command require python 2.7 (My python version is 2.7.5). Please update your python.
Thanks for your feedback.

**Comment by meiry** [comment]
yes my version is Python 2.6.6 , consider to do python check when the script is executed and print more informative error massage to the stdout

**Comment by natural-law** [comment]
There are codes for checking the python major version. But the minor version is not checked. I will add it later. Thanks for your suggestion.

**Comment by natural-law** [comment]
@meiry 
I have solve the problem in this PR: 
https://github.com/cocos2d/cocos2d-x/pull/11355

Related PRs in cocos2d-console:
https://github.com/cocos2d/cocos2d-console/pull/245
https://github.com/cocos2d/cocos2d-console/pull/246

**Comment by walzer** [comment]
Solved.
