### ISSUE TITLE
Mac OS retina mode not working

### ISSUE THREAD

**Issue by iSevenDays** [cocos2d/cocos2d-x#11298]
``` C++
if( !glview ){
        glview = GLViewImpl::createWithFullScreen("beat me");
        ((GLViewImpl *)glview)->enableRetina(true);
        director->setOpenGLView(glview);
    }
```

After I enabled retina mode, nothing changed. I still at 1440 \* 900 mode.

It's a known bug: glfwGetFramebufferSize returns size in screen coordinates.
Solution: update glfw( your version is 3.0, bug was fixed in 3.0.1 )
http://www.glfw.org/changelog.html

From the link above:
Version 3.0.1
[Cocoa] Bugfix: glfwGetFramebufferSize return the size in screen coordinates

**Comment by minggo** [comment]
@iSevenDays 
Thanks for the information.

**Comment by zilongshanren** [comment]
@minggo 
So we should upgrade glfw?  In the next release?

**Comment by minggo** [comment]
Yep, i think we need to update it in v3.7.

**Comment by walzer** [comment]
Duplicate to #11748. So that's focus on upgrading the GLFW version.
