### ISSUE TITLE
multiple camera case utils::captureScreen bug.

### ISSUE THREAD

**Issue by lvlonggame** [cocos2d/cocos2d-x#11310]
If i have two or more cameras, the first camera draws nothing(use camera flag control this), but it is visited first in the scene, under this condition use utils::captureScreen function will get nothing, just a black image.

**Comment by minggo** [comment]
Could you give some codes to describe it?
How did you invoke `utils::captureScreen`?

**Comment by lvlonggame** [comment]
You can use utils::captureScreen in the sample of "CameraCullingDemo",  i copy the code from CaptureScreenTest.

**Comment by minggo** [comment]
Put `utils::captureScreen` to where?
Could you please add more detail information?
It is better if you can create a new branch in your own repo to describe it.
Thanks.

**Comment by lvlonggame** [comment]
https://github.com/lvlonggame/cocos2d-x/tree/captureScreen
run cpp-tests->Node:Camera 3D Test->Camera Frustum Clipping, press the button of "capture all"
