### ISSUE TITLE
[3.5 Cocos Framework + lua + win32 Simulator] print not working (lua_print removed in CCLuaStack.cpp

### ISSUE THREAD

**Issue by hamburml** [cocos2d/cocos2d-x#11312]
Again me.

As you might know we are using: 3.5 framework + lua
We also use: cocos code ide 1.2.0 and now we have build our own win32 simulator with cocos code ide build win32 simulator.

Works like expected but now the print("...") method in lua isn't printing something to the console. I was searching for the print-bindings and found out that in cocos2d-x-3.4 in cocos/scripting/lua-bindings/manuel there was the CCLuaStack.cpp which has lua_print and lua_release_print() method.  FYI: We manipulated the appdelegate.cpp.

**Comment by hamburml** [comment]
Please, come on. You can't expect someone to use cocos framework and advertise all the new stuff, when there are problems which exists through versions....
Here is the solution.
http://discuss.cocos2d-x.org/t/why-the-lua-function-print-cant-output-message-in-cocos2d-x3-3rc0-at-windows-cocos-ide/18150
I don't want to build liblua again with debug-flag = 1 so I will just map release_print to print in lua ....

_rant over_ I think it would be a really really really big improvement, if you provide debug _and_ release builds and these will be used for either debug or release builds in your ide.

**Comment by walzer** [comment]
Scheduled in v3.7

**Comment by pandamicro** [comment]
Hi, you should use 
`release_print("any string")`
