### ISSUE TITLE
Write a documentation for creating auto batch friendly GUI 

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#11367]

**Comment by walzer** [comment]
Any update on this?

**Comment by zilongshanren** [comment]
@walzer  I have writen a document and send PR to programing guide but it need to be refined. 
You could click the link above to jump to it.

**Comment by minggo** [comment]
What's the status?
When can it be finished?

**Comment by zilongshanren** [comment]
@minggo  I have refined the document, please check it here  https://github.com/andyque/programmers-guide/blob/add-gui-auto-batch/drafts/14.md
