### ISSUE TITLE
Add cell reuse mechanism to ListView

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#11368]

**Comment by eonghk** [comment]
Is cell reusing working in 3.7? A listview with 10 complicated items is very slow on 2k android phones.(Nexus 6, Galaxy S6).  cocos2d-x 3.6
@zilongshanren

**Comment by Shulepov** [comment]
Hi, i have written simple CollectionView last year with support of cells reusing (it also can be used as ListView). May be somebody find it useful - https://bitbucket.org/Shulepov/cccollectionview/overview.
If somebody will be interested i can provide more comments or rewrite it with compatibility of new UI system.

**Comment by eonghk** [comment]
@Shulepov 
Thank you for the information. I'm interested in it.
What's the difference between your collectionview and tableview?

**Comment by Shulepov** [comment]
@eonghk
If i understood correctly, TableView - much more like ListView (one dimensional array), while CollectionView - two dimensional. Also, i added slightly more configuration properties - like edge insets, inter items spacing, ability to have items with different width, selection and highlight animations managed by subclasses of the cell class, multiple reusable cell types (though it not very useful in most cases).

But i mainly configured it for my own use cases, so it have few restrictions - support only vertical scrolling, doesn't support multiple sections and headers.

**Comment by zilongshanren** [comment]
Add this feature will cause some back compatibility issue, and I also added a cell reuse tests in cpp-tests and js-tests. So just close this issue now.

**Comment by JoHuang** [comment]
@Shulepov 

Hi, I’m interested in your work. Do you have examples to let us figure out how to use your 
collectionview.

Thanks

**Comment by Shulepov** [comment]
@JoHuang hello, I haven't developed anything for cocos2d-x for a while, so I'm not sure if it is still compatible with current cocos2d-x version (though it shouldn't be too hard to fix possible issues). It should work like UICollectionView on iOS, but with less functionality.
