### ISSUE TITLE
touch问题

### ISSUE THREAD

**Issue by mooncode163** [cocos2d/cocos2d-x#11372]
请教大家个问题  3.0 将一个layer setVisible(false)后还会收到touch事件 怎么在系统里修改让隐藏的layer不收到touch事件呢，这个好像是一个bug

**Comment by lbfamous** [comment]
setTouchEnabled(false) 试试看

**Comment by minggo** [comment]
@Jaykie 
Have you resolved your issue?

**Comment by walzer** [comment]
`visible` and `touch enabled`是两个不同的属性，所以还是要分开的。@lbfamous 的解答是正确的。
