### ISSUE TITLE
Cosod2dx 3.5 load csb and the Pacticle had added is gone!!!!

### ISSUE THREAD

**Issue by semgilo** [cocos2d/cocos2d-x#11395]
mac
Cosod2dx 3.5  -l lua 
Cocostudio 2

**Comment by semgilo** [comment]
I try new  particle addTo the resourceNode , the particle doesn't show

**Comment by pipu** [comment]
@semgilo 
I load csb which contain particle can be correctly loaded.
Could you give us your code and csb file?
