### ISSUE TITLE
Should we have iOS Default Multi-Touch Enabled?

### ISSUE THREAD

**Issue by jimrange** [cocos2d/cocos2d-x#11392]
Is there a reason why multi-touch is not enabled by default on iOS?
Is there any benefit to having it disabled by default on iOS?
I think it would make sense to enable it by default.

It seems that there are inconsistencies in the **CCGLViewImpl-ios.mm**. Some parts contain setMultipleTouchEnabled:YES and some do not.

e.g.
In the CCGLViewImpl-ios.mm file:

Multi-touch is **enabled** if the **initWithRect** method is used. That method contains the code [eaglview setMultipleTouchEnabled:YES];

But currently, **initWithEAGLView** is used by default and [_eaglview setMultipleTouchEnabled:YES];  is not called. So the default is multi-touch on iOS is disabled.

The method **initWithFullScreen** in CCGLViewImpl-ios.mm also does not call setMultipleTouchEnabled:YES.

**Comment by minggo** [comment]
Please don't use issue system for discussing.
Please discuss it here: http://discuss.cocos2d-x.org/c/cocos2d-x-dev-discussion.

**Comment by jimrange** [comment]
I didn't intend to discuss it.
I think it is a bug that multi-touch has inconsistent implementations between Android, iOS and WP8.1.
