### ISSUE TITLE
Cocos2d-x 3.5 Resources are not updated unless project is rebuilt

### ISSUE THREAD

**Issue by StudioHo** [cocos2d/cocos2d-x#11391]
I noticed that now the Resources are copied to outdir before run with the prelinkevent

`<PreLinkEvent>
      <Command>if not exist "$(OutDir)" mkdir "$(OutDir)"
xcopy /Y /Q "$(EngineRoot)external\websockets\prebuilt\win32\*.*" "$(OutDir)"
xcopy "$(ProjectDir)..\Resources" "$(OutDir)" /D /E /I /F /Y</Command>
    </PreLinkEvent>`

But shouldn't there be a way to trigger this without rebuilding the project?

**Comment by minggo** [comment]
@StudioHo 
I am not sure if there is a way or not.

**Comment by StudioHo** [comment]
@minggo 
Too bad... Sometimes I make small changes to the sprites, and then, when I hit "Run“ in visual studio, the event is not called since I didn't change the code. So it still uses the old sprites 囧rz

**Comment by walzer** [comment]
Trigger xcopy each time we link "run" in visual studio seems very expensive, especially for programmers who just modify few lines of code in large game projects.

I guess you can fix it by modify the configuration in your vs project. There's no a common way out to satisfy both artists and programmers :)

**Comment by StudioHo** [comment]
@walzer  
Well, if the programmer just changes a few lines of code and build the project, I guess the PreLinkEvent will be called anyway @@
In my case I solved by creating a project called "Resources" that automatically copies only the modified files to $(OutDir)
