### ISSUE TITLE
cocos new allows projects with dots

### ISSUE THREAD

**Issue by hamburml** [cocos2d/cocos2d-x#11390]
cocos new -l cpp Test3.5framework

created a project which name is Test3.5framework
This can't be build for android because the dot is used as a separator for java packages.

![image](https://cloud.githubusercontent.com/assets/7239350/7089165/23cdeae6-df9a-11e4-9878-c7578db1c7b0.png)
![image](https://cloud.githubusercontent.com/assets/7239350/7089175/38242262-df9a-11e4-9441-a724059e7538.png)

**Comment by minggo** [comment]
It is the limitation of Android, not cocos2d-x.

**Comment by hamburml** [comment]
Yes, I know. But you can avoid this if you do not allow projects with dots..... More or less it's the engines work to ensure that a project, which was created, is fully working.... It's sloppy to ignore it.
