### ISSUE TITLE
Label does not work fine on WP8.0.

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#11424]
![label-wp8](https://cloud.githubusercontent.com/assets/5234286/7129879/dfcd79a4-e298-11e4-8dc1-1f4f856e735f.png)

@stammen It look like cause by glTexSubImage2D not work fine on WP8.0

**Comment by minggo** [comment]
@stammen
Could you please take a look?

**Comment by walzer** [comment]
Well, since we're removing wp8 support.  Does this bug still there in wp8.1?

**Comment by WenhaiLin** [comment]
This issue not exhibit on WP8.1.
