### ISSUE TITLE
Cocos2D-X 3.5 utils::captureScreen gets black screenshot when using Camera.

### ISSUE THREAD

**Issue by bryanwong** [cocos2d/cocos2d-x#11447]
I use 3 cameras in my game, and all children of the scene have their own camera set.

I get black screenshot when using utils::captureScreen to catch screen and share.

Please fix.

Thanks,
Bryan

**Comment by walzer** [comment]
Duplicated with issue #11310

**Comment by fusijie** [comment]
It fixed with https://github.com/cocos2d/cocos2d-x/pull/12810.
