### ISSUE TITLE
CCScale9Sprite does not support rotated spriteframe

### ISSUE THREAD

**Issue by chuckzhang** [cocos2d/cocos2d-x#1145]
As described, using rotated sprite frame for CCScale9Sprite does not render correctly.

**Comment by ghost** [comment]
It's not ported from Cocos2d to the Cocos2d-x version. The Cocos2d version does it.

Check

https://github.com/YannickL/CCControlExtension/commit/a920b8e5ba7e2b387d0a97880232a63d004f2d4e

**Comment by chuckzhang** [comment]
I've noticed, but is there any plan to support this feature in the near future?

**Comment by ghost** [comment]
If you update the code? Yes!

**Comment by walzer** [comment]
issue created http://www.cocos2d-x.org/issues/1473 
I will sync your code to c++, thanks!

**Comment by minggo** [comment]
It is fixed in this issue: http://www.cocos2d-x.org/issues/1473

**Comment by lava-hammer** [comment]
I found this bug at release version "cocos2d-2.1rc0-x-2.1.3" May 1st 2013.  And checked my CCScale9Sprite.cpp with latest github version. I didn't see enough changes to fix the bug. Keep watching it.

**Comment by smilingpoplar** [comment]
@minggo, @walzer CCScale9Sprite does not work for rotated spriteframe in cocos2dx v2.1.4 too.
