### ISSUE TITLE
AudioEngine::play2d() cause black screen on Android,  cocos2dx 3.5  

### ISSUE THREAD

**Issue by zdccool** [cocos2d/cocos2d-x#11466]
play2d  screen black and log is frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread 0x65011548 (tid 21923)

**Comment by kumsook** [comment]
hi, AudioEngine::stopAll() use Screen Hangs log is 
frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread 0x7236e630 (tid 15646) sees object 0x70de6ab0 was locked by pthread 0x61f4ffc0 (tid 15049) at frameworks/wilhelm/src/itf/IObject.c:411

**Comment by WenhaiLin** [comment]
@kumsook Please try this solution https://github.com/cocos2d/cocos2d-x/pull/11762

**Comment by kumsook** [comment]
Thank you. :)

**Comment by WenhaiLin** [comment]
@kumsook Tell me if this solution is feasible for your application.

**Comment by kumsook** [comment]
@WenhaiLin  It has been resolved. Good solution. Thanks. :)

**Comment by nicolechen819** [comment]
Still freeze on Android
