### ISSUE TITLE
SSL in Android v3.5

### ISSUE THREAD

**Issue by ivanrumo** [cocos2d/cocos2d-x#11473]
Hi!

When i try to meke a Http request, I get this error log:

E/cocos2d-x debug info(15533): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

This is an example of the request

``` c
    cocos2d::network::HttpRequest* request = new HttpRequest();
    request->setUrl("https://www.atriviate.com");
    request->setRequestType(HttpRequest::Type::POST);

    request->setResponseCallback(pSelector);

    request->setRequestData(data.c_str(), data.size());
    HttpClient::getInstance()->send(request);
    request->release();
```

Thank you and sorry for my english

**Comment by dumganhar** [comment]
I could not reproduce this issue in `v3.15.1`.
Closed this issue temporarily. If you still get this issue, feel free to open it again. Thanks.
