### ISSUE TITLE
upgrade rapidjson to latest version.

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#11474]
The rapidjson version in v3 repository is outdated, we have upgrade it in v4.

**Comment by miloyip** [comment]
Please note that, RapidJSON just released [v1.0.0](https://github.com/miloyip/rapidjson/releases/tag/v1.0.0).
If there is issue with upgrading RapidJSON, feel free to discuss with me.

**Comment by walzer** [comment]
wow, thanks! I'm super amazed that author of rapidjson is watching our repo!
I just added this upgrade into our next version :)
