### ISSUE TITLE
Can not play video on Android 2.3 with VideoPlayer

### ISSUE THREAD

**Issue by aababy** [cocos2d/cocos2d-x#11516]
version: 3.5Final
issue: can not play video on Android 2.3  with VideoPlayer, it will say, "can not play this video". It works well on Android 4.x.
reproduce: 
1. open cocos2d-x sample(cpp-tests)
2. Node:UI -> GUI Dynamic Create Test -> Video..
3. tap play resource video

**Comment by babcca** [comment]
Maybe there is unsupported file format in test scene. Try to check
http://developer.android.com/guide/appendix/media-formats.html

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11651

**Comment by minggo** [comment]
Duplicated with #8511.
