### ISSUE TITLE
Button->setBright(bool) makes memory go up.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#11511]
`version:` 3.5Final
`issue:` Every time creates a button and setBright(false), GLProgramStateCache will cache the program state makes memory go up.
`reproduce:` add following code to HelloWorld project, then pay attention to memory.

``` cpp
    this->schedule([](float){
        ui::Button* btn = ui::Button::create("CloseNormal.png","","",ui::Widget::TextureResType::LOCAL);
        btn->setBright(false);
    }, 0.05, "lambda");
```

**Comment by zilongshanren** [comment]
@fusijie 
Please check whether this issue is resolved or not in the upstream of cocos2d-x.
Thanks.

**Comment by fusijie** [comment]
@andyque Thanks, it's fixed.
