### ISSUE TITLE
sizeXPercentEnable is always false when CSLoader load .csb file exported from Cocos Studio 2.2.1

### ISSUE THREAD

**Issue by matsujun** [cocos2d/cocos2d-x#11548]
Even if I use percent sizes, sizeXPercentEnable
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/editor-support/cocostudio/CSParseBinary_generated.h#L472
is always false.

I'm using Cocos Studio 2.2.1 for mac, and export type is .csb
If I export to .json, it looks correct, but .json is not available now.(Issue #11547)

**Comment by minggo** [comment]
Since cocos studio is canceled, so close this issue.
