### ISSUE TITLE
Add push notification support for iOS/Android/Mac/WinPhone

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#11541]

**Comment by pandamicro** [comment]
Reported here: http://discuss.cocos2d-x.org/t/push-notifications-for-the-web/21146/2
Related article for web implementation: http://updates.html5rocks.com/2015/03/push-notificatons-on-the-open-web

**Comment by walzer** [comment]
There're lots of push service provider on Android.
AnySDK already has this feature and wrapper.
