### ISSUE TITLE
Particle system issue

### ISSUE THREAD

**Issue by hussain-sohaib** [cocos2d/cocos2d-x#11555]
so I am adding particles to my scene, after adding I had to call a schedule function, but if call the schedule function, particle stops moving. Here is the code snippet  that I am using, with cocos2dx 3.5.

  _smokeParticle = ParticleSystemQuad::create("logoParticles.plist");

```
_smokeParticle->setPosition(Vec2(_logo->getContentSize().width/2, _logo->getContentSize().height/2));
_smokeParticle->setAnchorPoint(Vec2:: ANCHOR_MIDDLE);
_smokeParticle->retain();
_logo->addChild(_smokeParticle,100);
```

this->scheduleOnce(schedule_selector(GameStart::loadLand), .05f);

Could anyone please help me understand whats the issue is, or if I am doing any mistake please correct me.

**Comment by walzer** [comment]
It doesn't look like a bug, but a usage mistake, it depends on your context.
I would close this issue. Please ask the usage question in the forum :)
