### ISSUE TITLE
Particle system bug

### ISSUE THREAD

**Issue by VisualSJ** [cocos2d/cocos2d-x#11551]
auto particle2 = ParticleSystemQuad::create("dstalpha-dstcolor1.plist");
auto particle1 = ParticleSystemQuad::create("One-one1.plist");
and
auto particle1 = ParticleSystemQuad::create("One-one1.plist");
auto particle2 = ParticleSystemQuad::create("dstalpha-dstcolor1.plist");
Effect of different....

Resources:
https://github.com/VisualSJ/tools/tree/master/res

issue:
http://punchbox.info:3000/issues/17795

**Comment by walzer** [comment]
Close this issue because "designed as this".
To avoid this problem, please use different texture names in different plist files for 2D particle.
