### ISSUE TITLE
AudioEngine should support the rest of our target platforms

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#11563]
So finally, `AudioEngine` can support all our target platforms.
My idea is that, after v3.7, we can refactor `SimpleAudioEngine` as a wrapper of `AudioEngine` for backward compatibility.

From users feedback, most users are very satisfied with `AudioEngine` with its performance and useful callbacks.

**Comment by stammen** [comment]
We have scheduled the Windows 8.1/10 Universal App AudioEngine work for v3.7.

**Comment by minggo** [comment]
@stammen
You are appreciated if you can help to implement audio engine on these platforms.

**Comment by stammen** [comment]
@minggo We are starting the work next week.

**Comment by minggo** [comment]
Thanks @stammen .

**Comment by cesarpachon** [comment]
hello I am interested in the implementation for linux.. it is someone working on that, or there are some guidelines to have a look at it?

**Comment by pandamicro** [comment]
Current status: AudioEngine is only absent on Linux, Win 8.1 universal support have been done in : 

https://github.com/cocos2d/cocos2d-x/pull/11893
https://github.com/cocos2d/cocos2d-x/pull/12068
https://github.com/cocos2d/cocos2d-x/pull/12234
https://github.com/cocos2d/cocos2d-x/pull/12472
https://github.com/cocos2d/cocos2d-x/pull/12547

Now considering our tasks priority, I think Linux support can be delayed to future versions, so I removed highlight flag and removed this issue from v3.8.

**Comment by pandamicro** [comment]
@cesarpachon If you are willing to support it on Linux, we will really appreciate any kind of contributions. If you have any question, you can ask @WenhaiLin . He is the designer of new AudioEngine

**Comment by cesarpachon** [comment]
sure @WenhaiLin, I would like to contribute. posted request for guidelines here: http://discuss.cocos2d-x.org/t/implementation-of-audioengine-for-linux/22684

**Comment by cesarpachon** [comment]
guys I already begun a simple implementation, added CC_PLATFORM_LINUX to all the places where AudioEngine was restricted in Linux (audio folder and tests) and the implementation right now uses the existing FmodAudioPlayer. the existing test can play and stop a sound. My idea is to check if the general approach is good and then remove FmodAudioPlayer dep from my AudioEngine-linux.cpp file and reimplement with Fmod from scratch, maybe reusing snippets from FmodAudioPlayer.  code here: https://github.com/cesarpachon/cocos2d-x

**Comment by jimrange** [comment]
The open bug https://github.com/cocos2d/cocos2d-x/issues/10527 in AudioEngine regarding a gap in looping on Android should probably be fixed before wrapping AudioEngine with the SimpleAudioEngine interface.

Audio looping works good in SimpleAudioEngine.  But in AuidoEngine there is a noticeable gap in playback when the track loops back to the start of the audio.

So removing SimpleAudioEngine's implementation would result in a loss of the properly working looping feature on all Android other than API 21 (it is already broken on API 21 due to this fix https://github.com/cocos2d/cocos2d-x/pull/12098).

I tried to fix this issue in AudioEngine, but I was unsuccessful. I added notes to issue #10527.

**Comment by cesarpachon** [comment]
hello, I am doing a new PR to both cocos2d-x (https://github.com/cocos2d/cocos2d-x/pull/14476) and third-party-libs-bin (https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/190) projects. both PR's implement the AudioEngine for Linux, refactor SimpleAudioEngine to be a wrapper of the former and upgrades the binaries of FMOD to latest version.

**Comment by minggo** [comment]
All platforms are supported, so close this issue.
