### ISSUE TITLE
Add Android Studio support

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#11565]

**Comment by hamburml** [comment]
Does this also mean that gradle-support could be added?

**Comment by minggo** [comment]
@Michael-Hamburger 
Yep, if it is needed.

**Comment by WenhaiLin** [comment]
Related to:
    https://github.com/cocos2d/cocos2d-x/pull/11856 
    https://github.com/cocos2d/cocos2d-x/pull/11905
    https://github.com/cocos2d/cocos2d-x/pull/11924
    https://github.com/cocos2d/cocos2d-x/pull/12013
