### ISSUE TITLE
Label(ttf) collapse with getLetter and modify some feature(e.g. setOpacity) & setString.

### ISSUE THREAD

**Issue by AknEp** [cocos2d/cocos2d-x#11576]
I found this bug in my private project.

reproduction code is in below repository.

https://github.com/AknEp/GetLetterBugRep

the code is essentially...

```
    auto label = Label::createWithTTF("When I'm drivin' in my car. And the man comes on the radio. He's tellin' me more and more. About some useless information. Supposed to drive my imagination.", "fonts/Marker Felt.ttf", 32);
    label->setPosition(Vec2(origin.x + visibleSize.width/2,
                            origin.y + visibleSize.height - label->getContentSize().height));
    label->setContentSize(visibleSize/2);
    this->addChild(label, 2);

    // wait until draw
    this->runAction(CallFunc::create([label](){
        for( int i=0; i<(label->getStringLength() + label->getStringNumLines()); i++ ){
            auto letterSprite = label->getLetter(i);
            // setOpacity or setColor , FadeInOut-Action etc...
            // such makes collapse characters after setString...
            if( letterSprite ){
                letterSprite->setOpacity(200);
            }
        }
    }));
```

makes below.

![ios simulator screen shot 2015 04 24 10 37 11](https://cloud.githubusercontent.com/assets/743292/7310844/182310d4-ea6e-11e4-943b-9b3fd0216b28.png)

then,

```
    this->runAction(Sequence::create(DelayTime::create(3),
                                     CallFunc::create([label]()
                                                      {
                                                          // it renders collapsed.
                                                          label->setString("I was born in a cross-fire hurricane. And I howled at my ma in the drivin' rain. But it's alright now. In fact it's a gas , but it's alright. I'm Jumping Jack Flash. It's a gas , gas , gas");
                                                      }
                                                      ),
                                     NULL)
                    );
```

![ios simulator screen shot 2015 04 24 10 37 14](https://cloud.githubusercontent.com/assets/743292/7310845/1c09e54c-ea6e-11e4-8bd7-bdc138abab04.png)

As you can see, some letters are located strange.
## work in progress (my fight)

I succeeded to suppress this bug monkey-patching & wrapping below.
### CCLabel patching

I found some child has `-1` tag when collapsed.

In `CCLabel.cpp` line 863
I removed `if(child->getTag() >= 0)` broking. (= all children called updateTransform  )
### re-create Label

I creating Label when string changed.
### patching #10773

apply #10773

It's good enough on my private product.
...but, I couldn't detect fundamental element of the bug.

**Comment by WenhaiLin** [comment]
Fixed crash at:https://github.com/cocos2d/cocos2d-x/pull/11659
Fixed collapse at : https://github.com/cocos2d/cocos2d-x/pull/11683 and https://github.com/cocos2d/cocos2d-x/pull/11728

**Comment by AknEp** [comment]
great!!!
thank you for your quick response :+1:
