### ISSUE TITLE
Anyway to get array bytes/base64 of image from CCSprite/CCImage/CCTexture2d?

### ISSUE THREAD

**Issue by 0xJimmyBeh** [cocos2d/cocos2d-x#11584]
As title,
I need the array bytes/base64 of image to upload it to server, but i can't find any solution yet.
I tried CCImage.getData() in JSB but return null.

I'm using this custom Image Picker to get the image from photo album.
It successfully created CCSprite with the return texture.
https://github.com/cocos2d/cocos2d-x/pull/11344

After get the array bytes/base64 of image, i need to use it in JSB with Cocos2d-JS.

Thanks.

**Comment by zilongshanren** [comment]
@Zinitter 
You might need to maintain a key-value map of texture file name and texture.
Every time you want to get the Image of Texture, you could use this map to query the texture file name and create CCImage with this name.

**Comment by walzer** [comment]
Duplicated with #11349 
Let's track that issue and close this one.

**Comment by 0xJimmyBeh** [comment]
@andyque 

Are you suggesting me to maintain a key-value map of texture so i can recreate the CCImage?
Then does the CCImage.getData() can return the image array bytes?

I have tried modified the ImagePicker to return CCImage instead of texture and tested it with the JSB in Cocos2d-JS

```
var texture = new cc.Texture2D();
texture.initWithImage(returnCCImage);

var sprite = new cc.Sprite(texture);
cc.log("data : " + returnCCImage.getData());<-- this show null on log
```

The sprite can be created and show properly on Mac and iOS with the return CCImage.
The Android show a black sprite but size of sprite it correct, not sure my modification is correct or not.

returnCCImage.getData() on Mac and iOS showing null and Android will crashed.

Am i doing something wrong or is the bug on the CCImage.getData()?

Updated :
Can you have a look on this ImagePicker implementation
https://github.com/qiankanglai/ImagePicker

Is it possible to modify the code to return
cocos2d::Texture2D and array bytes of image in ImagePicker::finishImage included JSB?

I'm not very understand about the array bytes and not sure what type/class should be use.

This become more complicated when on JSB, i have no idea how to modify the JSB.
Does array bytes should be a uint32_t or uint8_t?

Thanks.
