### ISSUE TITLE
Add web runtime (html5) project to jenkins-ci

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#11582]
I remember that we still have no continuous integration for cocos2d-html5 yet.
To guarantee the quality, we need that, e.g., `glup` or something else.

**Comment by pandamicro** [comment]
It's not a problem of tools, it's a problem of continuous integration test, there is no compilation for web platform, the quality need to be guaranteed by unit tests. I also think unit tests are very important.

Though we can only plan it for long term, it's not a day or two work, it probably need several persons a month or even more

**Comment by drelaptop** [comment]
I think it's a out-dated feature request for cocos2d-x now, so close it. @walzer @pandamicro
