### ISSUE TITLE
UI::Widget::Clone() get error if widget has a sprite or scale9sprite

### ISSUE THREAD

**Issue by enhhh** [cocos2d/cocos2d-x#11597]
`version:` cocos2d-x 3.2
`issue:` If `UI::Widget` and  derived class has a render image,`Sprite` or `Scale9Sprite`, if I clone widget will get an error after I call `SpriteFrameCache::getInstance()->removeUnusedSpriteFrames()` or `Director::getInstance()->purgeCachedData()`,TextureCache still has the textures of cloned,but `SpriteFrameCahe` had remove spriteFrames, while `clone()` called, cocos2dx couldn't found the SpriteFrame from SpriteFrameCache.

I think that we should add a `retain()` while we get SpriteFrame from the cache, and call `release()` while widget with spriteFrame destruct.

By the way:
Why `Sprite` has method `getSpriteFrame()` and `Scale9Sprite` has not ?  And why not store all SpriteFrame in the cache but call method `getSpriteFrame()` which create SpriteFrame from `Sprite's` properties.

**Comment by zilongshanren** [comment]
I close this issue here. Because the target engine version is v3.2.
If it still exists in v3.9, feel free to reopen it.
