### ISSUE TITLE
[v3.6-universal-wp8.1-cpptests]Node: Clipping-->Scroll View Demo:Crash

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#11606]
Device:Nokia Lumia 625
OS: Window Phone 8.1

**Comment by minggo** [comment]
@andyque 
@stammen
Could you please take a look?

**Comment by stammen** [comment]
@WenhaiLin  @minggo I am not able to reproduce this issue on my phones or in the emulator. I do not have a Lumia 625. Would you please send me more information.

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/11652
