### ISSUE TITLE
[v3.6-universal-win8.1-cpptests]Node: UI-->GUI Dynamic Create Test-->UISliderTest

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#11605]
Program  is lagging so much when dragging the slider.

console log:
0x74A94DBD 处(位于 cpp-tests.Windows.exe 中)最可能的异常: Microsoft C++ 异常: IOException，位于内存位置 0x06F7E584 处。
0x74A94DBD 处(位于 cpp-tests.Windows.exe 中)最可能的异常: Microsoft C++ 异常: [rethrow]，位于内存位置 0x00000000 处。
...

**Comment by minggo** [comment]
@stammen
Could you please fix this issue ASAP?
We planned to release v3.6 on Apr.29.

Thanks.

**Comment by minggo** [comment]
And please send pull request to v3.6 branch.

**Comment by minggo** [comment]
Fixed in #11622.

@WenhaiLin 
Could you please check it?

**Comment by WenhaiLin** [comment]
It's OK now.
