### ISSUE TITLE
Bug in CCArray::randomObject()?

### ISSUE THREAD

**Issue by maxwzg** [cocos2d/cocos2d-x#1161]
CCObject\* CCArray::randomObject()
{
    if(data->num==0) return NULL;

```
return data->arr[(int)(data->num*CCRANDOM_0_1())];
```

}

if CCRANDOM_0_1() return 1, 
data->num*CCRANDOM_0_1()  = data->num;

index out of range?

**Comment by minggo** [comment]
Yeap, it is a bug.
Is it a acceptable method that when CCRANDOM_0_1() returns 1, we set it to 0?

**Comment by maxwzg** [comment]
CCObject\* CCArray::randomObject()
{
    if(data->num == 0) return NULL;
    float r = CCRANDOM_0_1();
    if (r == 1)
        r = 0;
    return data->arr[(int)(data->num \* r)];
}

**Comment by dumganhar** [comment]
Hi, maxwzg:
Could you send us a pull request to fix this issue ?

**Comment by walzer** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/1172. Thanks to maxwzg
