### ISSUE TITLE
PhysicsBody does not respect Node position

### ISSUE THREAD

**Issue by ElliotMebane** [cocos2d/cocos2d-x#11618]
When a physicsBody is applied to a Node, the position of the Node is disregarded. All physics objects cluster at one coordinate then expand outwards as collisions are resolved. Issue appears in v.3.4 and v.3.5

Please see this discussion:
http://discuss.cocos2d-x.org/t/parent-child-physics-body-position-in-cocos-3-4/20090

**Comment by YadneshCitrus** [comment]
Still facing the same issue....moving back to 3.3

**Comment by pandamicro** [comment]
This should have been solved in this PR: https://github.com/cocos2d/cocos2d-x/pull/12239
we will merged it in v3.8
