### ISSUE TITLE
Remove platform related code from coccos/2d

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#11629]
Microsoft guys added too much platform related code into cocos/2d/ folder, including:
- cocos/2d/libcocos2d_8_1
- cocos/2d/winrt_8.1_props
- cocos/2d/winrt_props
- cocos/2d/wp_8.1_props
  I find there are only project files for visual studio. Could we move these to cocos/build folder?

**Comment by minggo** [comment]
I think we should not modify it in v3, but can consider it in future, so close it.
