### ISSUE TITLE
Scrolling Background in Portrait Mode from up to down

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#11649]
I am new in  cocos2d-x c++ and i want to scroll my background in portrait mode from up to down. Currentally I am using cocos2d-x-3.4 c++ on Eclipse .
Please provide me some idea or source code for solving this problem

**Comment by walzer** [comment]
Please ask questions in the forum, instead of in this issue tracker :)
http://discuss.cocos2d-x.org
