### ISSUE TITLE
 Listview / Scrollview bounciness adjusting

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#11666]
I think this is a request.

Is it possible to change the way the bounce works in listview?
The scroll is fluid but the bounce it's not like other native app, it's too elastic with small retention.
It's possible to customize in some way?

**Comment by walzer** [comment]
I suggest that you look into the source code of ListView and ScrollView, hack the code in it. This request is different from different game designers, unless we have the custom curve.
This requirement is similar to #11665, so I close this issue, and let's track on #11665

**Comment by dariodepaolis** [comment]
Ok thank you.
