### ISSUE TITLE
UI Text and setFontSize doesn't update in realtime

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#11664]
I'm trying to make the Text inside a scrollview zoomable with pinching.

I've a problem on updating, let me explain:

```
if (touches.size() >= 2) {
  Touch *touch1 = (Touch *) touches.at(0);
  Touch *touch2 = (Touch *) touches.at(1);

  Vec2 curPosTouch1 = touch1->getLocationInView();
  Vec2 curPosTouch2 = touch2->getLocationInView();
  Vec2 prevPosTouch1 = touch1->getPreviousLocationInView();
  Vec2 prevPosTouch2 = touch2->getPreviousLocationInView();

  auto zoomFactor = curPosTouch1.distance(curPosTouch2) / prevPosTouch1.distance(prevPosTouch2);

      textWidget->setFontSize(round(textWidget->getFontSize() * zoomFactor));
//      textWidget->setScale(textWidget->getScale() * zoomFactor);

}
```

textWidget is a UI Text, I've a problem when using setFontSize in a listener OnTouchMoved, it updates the font size only when I release the touch not in realtime.
Instead using setScale it updates in realtime, but obviously with a pixelation effect.

Is there any way to force the update?
Or it is a normal behaviour because I'm using TTF font and need to wait for recalculating the new font size?

**Comment by zilongshanren** [comment]
@DarioDP 
ui::Text uses cocos2d::Label inside, many operations happen to cocos2d::Label will be delayed to next frame. It is designed for improving rendering performance.  We can't update the label when any attributes of the label is changed.

If you do want to update the label in realtime, you can do this:

```
auto label = (Label*)textWidget->getVirtualRenderer();
label->updateContent();
```

**Comment by dariodepaolis** [comment]
Tried but with no luck.
If I use setFontSize it doesn't update even if calling updateContent on virtualrenderer.
If I use setScale it works, but with bitmap scaling.

**Comment by zilongshanren** [comment]
@WenhaiLin  Please check this?

**Comment by zilongshanren** [comment]
@DarioDP 
Hi, sorry for the late reply. Is the issue still exists in v3.8?
