### ISSUE TITLE
ClippingNode inside ScrollView doesn't get clipped

### ISSUE THREAD

**Issue by man2** [cocos2d/cocos2d-x#11674]
![screen shot 2015-05-01 at 11 49 22 pm](https://cloud.githubusercontent.com/assets/167375/7432759/84b7f83c-f05d-11e4-8c12-4044de05399a.png)

The rectangle with blue line is the ScrollView, inside the ScrollView is a LabelBMFont and a ClippingNode with circle stencil.

From the image attached , the label gets clipped, while the cliipingNode does not. 

I'm using cocos2d-x 3.5

Is it a bug?

**Comment by man2** [comment]
if I add the clippingNode first then label to ScrollView, here is the result

![screen shot 2015-05-02 at 12 01 58 pm](https://cloud.githubusercontent.com/assets/167375/7440381/af7c0168-f0e3-11e4-9dc4-eb56ecc90f1d.png)

result : the text is clipped inside the ClippingNode, and they are both not get clipped by ScrollView

**Comment by zilongshanren** [comment]
@man2 This should considered to be a bug.
I will check it later.

**Comment by fusijie** [comment]
Maybe the engine do not support nested clipping. How to fix it?

**Comment by zilongshanren** [comment]
@fusijie 
I should change the implementation of ui::Layout, the ClippingNode does support nested clipping, but ui::Layout use plain OpenGL to implement the Clipping feature.

**Comment by man2** [comment]
@zilongshanren
Will this be fixed in 3.8?

**Comment by zilongshanren** [comment]
@man2  no... my priority will put on the cell reuse of ListView and PageView.
If you could help to fix the issue, I will appreciate it.
thanks.

**Comment by yagjak** [comment]
@zilongshanren , the cell reuse of PageView can reduce  the memory usage ?

**Comment by zilongshanren** [comment]
@yagjak  yes, it will not only reduce memory usage , but also improve runtime performance.

**Comment by yagjak** [comment]
Thanks @zilongshanren, this is interesting for me, beacause i'm using it in my application,
 so i'm waiting ...

**Comment by yagjak** [comment]
@zilongshanren, please is there any date about the release of  cocos2d-x V3.8?

**Comment by zilongshanren** [comment]
@yagjak sorry, I can't promise the exactly date. It was scheduled at the end of this month.

**Comment by man2** [comment]
Ok, i will try to fix it, later after i got the time.

**Comment by larsven** [comment]
I am seeing this problem in our game too and I have not yet figured out any workaround.

Any news on when it will be fixed?

**Comment by larsven** [comment]
ClippingNode inside a ScrollView does not work in any of the cocos2d-x versions we have tested.

In v3.6, ClippingRectangleNode did the job correctly inside a ScrollView, but after upgrade to v3.8 it does no longer work.

**Comment by larsven** [comment]
For ClippingRectangleNode and cocos2d-x 3.8, apply the patch posted here: https://github.com/cocos2d/cocos2d-x/issues/13876

**Comment by larsven** [comment]
We are using a temporary workaround until this bug is fixed:

ClippingNode seems to be working correctly inside a ScrollView when first placed on a ClippingRectangleNode.

We have the following hierarchy, from parent to child:
1. ScrollView
2. ClippingRectangleNode
3. ClippingNode
4. Sprite to be clipped

Everything gets clipped and displayed correctly now.

Note: In cocos2d-x 3.8, the ClippingRectangleNode needs the patch posted here: https://github.com/cocos2d/cocos2d-x/issues/13876

**Comment by pandamicro** [comment]
Fixed by #13913

**Comment by larsven** [comment]
With https://github.com/cocos2d/cocos2d-x/pull/13913, it is still required to use a ClippingRectangleNode as wrapper for a ClippingNode to work in a ScrollView. This should be fixed or at least documented.

**Comment by stnguyen** [comment]
what about cocos2d-js?

**Comment by man2** [comment]
it should be affected also, just compile the c++ codes with jsb build tool

**Comment by stnguyen** [comment]
@man2 there's no `ClippingRectangleNode` in js
I'm talking about html5 version
