### ISSUE TITLE
A problem while installing Cocos 2d-x 3.4 install is success but...  problem in create project. 

### ISSUE THREAD

**Issue by AdaGuo760000** [cocos2d/cocos2d-x#11678]
My friend has a problem while installing cocos2dx 3.4  install is success but...  problem in create project.  I send to you image what cmd screen.  How to do for solving this problem?
![park](https://cloud.githubusercontent.com/assets/10951329/7449684/fd961cea-f26d-11e4-99f0-5c28d38336c2.jpg)

**Comment by zilongshanren** [comment]
@natural-law  please take a look at this issue.

**Comment by natural-law** [comment]
@AdaGuo760000 
The reason is the path you are using has non-ASCII characters.
`cocos` command is not support that now. Thanks for your feedback.

**Comment by AdaGuo760000** [comment]
@natural-law Thank you!
