### ISSUE TITLE
Problem occurs when set outline to Chinese character

### ISSUE THREAD

**Issue by doomsdayer** [cocos2d/cocos2d-x#11699]
see code, when I set outline to some Chinese characters, the outline doesn't match with the chacacters exactly:

![image](https://cloud.githubusercontent.com/assets/3272795/7472765/63713c3e-f368-11e4-9846-74c5c32a4506.png)

the code is:

```
    auto uitext = ui::Text::create("等级", "zhuanyuan.ttf", 200);
    uitext->setPosition(Vec2(200, 300));
    uitext->setColor(ccc3(255, 255, 255));
    uitext->enableOutline(ccc4(255, 0, 0, 255), 1);

    scene->addChild(uitext);
```

and here is [the font used](http://pan.baidu.com/s/1eQpisgy)

**Comment by walzer** [comment]
Hi @doomsdayer , could you please give more infos to us:
- Which version of cocos2d-x are you using? v3.6?
- Which platform you meet this bug, iOS or Android? and which platform version?

I'm checking if system fonts will have this bug, or only `zhuanyuan.ttf` has this bug.

**Comment by WenhaiLin** [comment]
This issue is associated with the specific font file and platform independent.

**Comment by doomsdayer** [comment]
hi @walzer, this is only happened on v3.6, only this version have the font outline feature.
I met this bug on windows 8 x64, when I test it on cpp-empty-test.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11720 and https://github.com/cocos2d/cocos2d-x/pull/11782

**Comment by walzer** [comment]
@doomsdayer Could you please check the code in #11720 , can this code fix your bug?

**Comment by mirth** [comment]
Problem occurs with cyrillic "Ы" and "Й" letters in ttf font. Is it problem of my ttf or is it cocos bug? (cocos2d-js 3.6)
![bug](https://cloud.githubusercontent.com/assets/1296970/9955201/cf68c0d4-5df7-11e5-9c93-bcfd6ce9dd85.png)
