### ISSUE TITLE
setDesignResolution and TTF

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#11698]
TTF rescale to fit all the resolutions, but... the problem is that they SCALE... not resize like TTF do... 
So I have the pixelation effect like a bitmap font.

I have tried both with ui Text create and with Label createWithTTF, they do the same.

Is there another way to achieve this? 
How do you make your TTF rescale with resolutions?

I think that using setDesignResolution all TTF fontsize needs to be adjusted accordingly and to bitmap rescaled.

**Comment by dariodepaolis** [comment]
An user on cocos2dx forum gave me a workaround:

```
The best value to use for not losing quality and have no problem with anti-aliasing is how much you are re-scaling your images. You can calculate in this way:

auto screenSize = Director::getInstance()->getOpenGLView()->getFrameSize();
auto visibleSize = Director::getInstance()->getVisibleSize();

float scaleFactor = screenSize.width / visibleSize.width;

label = Label::createWithTTF("", "fonts/Arial.ttf", 24 * scaleFactor );
label->setScale( 1.0 / scaleFactor );
```

Anyway I think you should improve the setDesignResolution
Thank you.

**Comment by walzer** [comment]
The solution looks pretty brilliant!
Currently `setDesignResolution` is based on glViewPort, this will not make things complicated. Actually I'm thinking about wether I should refactor design resolution mechanism, not for the TTF labels, but for 3D mode, or even 3D + 2D mixed mode.
