### ISSUE TITLE
new AudioEngine get lag on stopAllEffects()

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#11697]
A bug report from 骏梦：
- engine version: v2.x with the AudioEngine patch by @WenhaiLin 
- target platform: android v5.0, any devices
- description: if `AudioEngine::stopAllEffects()` is invoked frequently, it will significantly show down the game.

**Comment by walzer** [comment]
The same bug was reported at http://www.cocoachina.com/bbs/read.php?tid-293752-fpage-7.html one more time.

**Comment by walzer** [comment]
And it probably caused by http://grokbase.com/t/gg/android-ndk/127kvtkj45/opensles-deadlock

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11762
