### ISSUE TITLE
Migrate project from Mac to Ubuntu

### ISSUE THREAD

**Issue by d3QUone** [cocos2d/cocos2d-x#11717]
I'm developing a game on C++ using Cocos2d-x v3.5. I use latest Xcode and have no problems with make & run. But my friend who wishes help me can't run my project on his Ubuntu. We guess something is wrong with Cocos2d make-files (we've found 2 named `CMakeLists.txt` ). Are there any ideas how to fix our makefiles and run project on Ubuntu?

Screenshot with compile errors:

![cvtyx0pmjgu](https://cloud.githubusercontent.com/assets/4642885/7488664/111164d2-f3d6-11e4-82e7-c7f9a057565e.jpg)

What shall we do? 

Thank you in advance!

[my question on Stackoverflow](http://stackoverflow.com/questions/30063735/migrate-cocos2d-x-project-from-mac-to-ubuntu)

**Comment by walzer** [comment]
Please discuss in the cocos2d-x forum: http://discuss.cocos2d-x.org

The error you met is `Player.h:12:1: error: 'USING_NS_CC' does not name a type`
I think you haven't include `platform/CCPlatformMacros.h` where `USING_NS_CC` is defined. An alternative way is to write `using namespace cocos2d` directly in your Player.h

Well, my suggestion is that: never `using namespace` in c++ header files, it will pollute all your other cpp/h files which include `Player.h`. 
- in header files: namespace xxx { }
- in c++ files: using namespace
