### ISSUE TITLE
[2dx 3.6] SpriteReader causes wrong image output with webp texture.

### ISSUE THREAD

**Issue by volzhs** [cocos2d/cocos2d-x#11723]
latest cocos studio 2.2.5 and cocos2d-x 3.6 has an option for setting `blendFunc`.

```
void SpriteReader::setPropsWithFlatBuffers(cocos2d::Node *node, const flatbuffers::Table* spriteOptions)
{
.....
    auto f_blendFunc = options->blendFunc();
    if (f_blendFunc)
    {
        cocos2d::BlendFunc blendFunc = cocos2d::BlendFunc::ALPHA_PREMULTIPLIED;
        blendFunc.src = f_blendFunc->src();
        blendFunc.dst = f_blendFunc->dst();
        sprite->setBlendFunc(blendFunc);
    }
.....
}
```

this causes wrong image rendering when using webp texture.

**Comment by xiaofeng11** [comment]
Hi, volzhs
Cocostudio only support PNG & JPG format image file, It won't support webp format

**Comment by volzhs** [comment]
I replaced png with webp manually, with finally published files.

**Comment by xiaofeng11** [comment]
Yes I know, some others has report same problem before, but these format not officially supported by cocostudio now.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
