### ISSUE TITLE
Lua api references not complete

### ISSUE THREAD

**Issue by jie-meng** [cocos2d/cocos2d-x#11726]
I found lua api references in path: cocos2d-x-3.6\cocos\scripting\lua-bindings\auto\api.

All the Action.lua, Node.lua, ... give well documented lua api interfaces.

I use these references to build my auto-completion tips. 

But while I was coding, I found some api lost.

e.g.
- I couldn't find function getTileGIDAt in TMXLayer.lua, but it actually has this function, I can use it.
- I couldn't find function setAnchorPoint in Node.lua, but actually I can use cc.Node:setAnchorPoint(point)

I think there would be more lost I haven't found.

So would you please make the api references completely match all the lua functions. Thank you!

**Comment by walzer** [comment]
Some lua API are redesigned in `cocos/scripting/lua-bindings/manual`, to have better user experience for script coders. The same as JavaScript API.
Close this issue because design as this.

**Comment by jie-meng** [comment]
Ok, thanks. But there aren't any document for the manual apis. That is not good, just suggestion.
