### ISSUE TITLE
[cocos2dx-2.2.6]Texture format somehow loaded as 16bit instead of 32bit in Lollipop

### ISSUE THREAD

**Issue by birdkingz** [cocos2d/cocos2d-x#11737]
Hi I'm having this issue when I try to load the texture and I noticed the texture seems to be converted to RGBA4444 instead of RGBA8888. Does anyone encountered this issue?

**Comment by birdkingz** [comment]
Any update on this issue?

**Comment by minggo** [comment]
v2 branch is into maintain mode, will only fix critical bugs, so close this issue.
