### ISSUE TITLE
Cocostudio 2.2.x frame event bug

### ISSUE THREAD

**Issue by Flame-haze** [cocos2d/cocos2d-x#11730]
the frame event callback function will be called every frame after the event frame.

**Comment by chengstory** [comment]
Thanks @Flame-haze, @walzer. 
Please @geron-cn to take a look.

**Comment by geron-cn** [comment]
@Flame-haze , could you please take a look at this [floor 6 in this post](http://www.cocoachina.com/bbs/read.php?tid=237349&page=e&#a), thanks, and contact me if you have any questions.

**Comment by geron-cn** [comment]
@minggo 
this issue has nothing to do with  issue#11786,
and i did some tests for this issue, nothing happed, i have replied him in the forum.

**Comment by Flame-haze** [comment]
https://github.com/cocos2d/cocos2d-x/commit/5b0e2f0304d48e3936a25d3099455755ccb25573
this commit has fixed this bug. My version is too low. sorry
