### ISSUE TITLE
Save Long via UserDefault

### ISSUE THREAD

**Issue by hamburml** [cocos2d/cocos2d-x#11733]
There is no setLongForKey or getLongForKey() method.

**Comment by walzer** [comment]
Why not use `int` or even `double` instead? I don't want to add dozens of types into `UserDefault`.

**Comment by hamburml** [comment]
Because it looks really bad if the simple primitive types aren't supported. Someone could get the idea that cocos2d-x isn't well thought.

**Comment by thienhaxgame** [comment]
> Why not use int or even double instead? I don't want to add dozens of types into UserDefault.
     
Weirdest answer I've heard, why do you think C++ have `long`? why don't they just use `int` and `double` as you suggested?
