### ISSUE TITLE
Newer GLFW version

### ISSUE THREAD

**Issue by sridenour** [cocos2d/cocos2d-x#11748]
Even Cocos2D-X 3.6 is still using GLFW 3.0.4, which was released in 2013 and does not have good support for things like Fullscreen App mode introduced in OS X 10.7. Really wish Cocos2D-X had as good of Desktop support as Cocos2D-Swift/ObjectiveC.

Please start using the latest version of GLFW. Currently that's 3.1.1, but GLFW 3.2 will be out "soon".

**Comment by RustyMoyher** [comment]
GLFW 3.1.1 has been the current version since March 19, 2015. But cocos2d-x is still using the older GLFW from 2013. Can we expect cocos2d-x to be updated with the latest GLFW soon?

**Comment by zilongshanren** [comment]
@RustyMoyher  @sridenour 
I will upgrade GLFW to 3.1.2 in the next release cycle.

**Comment by RustyMoyher** [comment]
Any update on this issue? I've been manually updating to GLFW 3.1.2 with each new project, but I'd love to have the new version already updated.

**Comment by ricardoquesada** [comment]
@RustyMoyher I can work on this... how difficult was to upgrade to v3.1.2? Did you have to patch the code? if so, where? could you send me the patch? thanks.

**Comment by RustyMoyher** [comment]
@ricardoquesada No, I don't make any code changes to cocos2d-x. Just compile GLFW for each desktop platform and replace the GLFW header files with the new ones.

**Comment by ricardoquesada** [comment]
@RustyMoyher thanks. it seems that v3.2 was released a few weeks ago. I'll use that one instead.

**Comment by ricardoquesada** [comment]
fixed. Using GLFW v3.2
