### ISSUE TITLE
NewLabel will Crash when setString() after getLetter()

### ISSUE THREAD

**Issue by huangzhentao** [cocos2d/cocos2d-x#11759]
Tor example code ： 

```
    TTFConfig ttfConfig("fonts/arial.ttf", 14);
auto label = Label::createWithTTF(ttfConfig, "abcdefv", TextHAlignment::CENTER);

auto char = (Sprite*) label->getLetter(5);

    label->setString("k");
```

The program will crash.  Cause in Label:alignText(), it will call

```
  for (const auto& batchNode:_batchNodes)
{
    batchNode->getTextureAtlas()->removeAllQuads();
}
```

but then it will call  SpriteBatchNode::removeChild(child, true);

**Comment by huangzhentao** [comment]
I think " SpriteBatchNode::removeChild(child, true);  "  in Label::alignText  modified to 

    for(const auto &child : _children) {
        int tag = child->getTag();
        if(tag >= 0)
        {
            hNode::removeChild(child, true);
        }
    }

**Comment by WenhaiLin** [comment]
Fixed crash at:https://github.com/cocos2d/cocos2d-x/pull/11659
Fixed collapse at : https://github.com/cocos2d/cocos2d-x/pull/11683 and https://github.com/cocos2d/cocos2d-x/pull/11728

**Comment by huangzhentao** [comment]
thank you for your quick response :100:
