### ISSUE TITLE
[cocos2dx 3.6] OpenGL error 0x0502 in CCTextureAtlas.cpp drawNumberOfQuads 691

### ISSUE THREAD

**Issue by jyoxun** [cocos2d/cocos2d-x#11755]
The project is normal in cocos2dx 3.4.
After we updated cocos folder to cocos2dx 3.6, the console always output:
OpenGL error 0x0502 in CCTextureAtlas.cpp drawNumberOfQuads 691

**Comment by dariodepaolis** [comment]
Already discussed here and fixed: https://github.com/cocos2d/cocos2d-x/issues/11742

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@jyoxun @dariodepaolis
