### ISSUE TITLE
Docs Required: how to bind c/c++ to JS & lua?

### ISSUE THREAD

**Issue by andersonmadeira** [cocos2d/cocos2d-x#11765]
I have a multiplayer game written in Cocosd2x and I'm willing to add support for scripting language (Lua). So I've been reading the source, docs and wiki but I found no information (not enough) about the Lua Binbings, more presisely, how to call user defined lua functions (inside a script file, say user.lua) inside my game to enable scripting. Do you know any manual, link or tutorial?
Sorry if this is not the proper place for this question.

**Comment by walzer** [comment]
We're using bindings-generator to create lua / js bindings automatically.
The tool: https://github.com/cocos2d/bindings-generator, and please learn from its readme.
Sorry that we still have no `how to bind c++ functions and classes to lua` documentation after cocos2d-x v3.0. I change the title and put it in v3.8 roadmap.

**Comment by andersonmadeira** [comment]
Thanks, walzer.
