### ISSUE TITLE
Upgrade Physics to Chipmunk v7.0

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#11766]
Is it planned or not?

Today I'm trying to build using MSYS2 with mingw and QT, and I've found errors on CCPhysicsBody.obj using the last chipmunk 7.0
Downgrading to 6.2.2 it's ok, but maybe all the physics could gain some advantage using the latest version, from the changelog they have included all the pro features inside this version.

**Comment by walzer** [comment]
Yes, it's necessary. But I'm extremely unconfident that if we have enough human resources to do this before v3.8 release.

**Comment by TheCodez** [comment]
@pandamicro @WenhaiLin @minggo Are you upgrading to Chipmunk 7.0 in Cocos v3.10?

**Comment by KawabataLemon** [comment]
Did you checked PR #10838?
I copied this PR to 3.9.
Almost looks good.
But sometimes ,when two bodies contact,  cpBodyGetRotation/cpBodyPosition value becomes NaN.
then, Node disapears from the screen.

**Comment by ricardoquesada** [comment]
fixed. chipmunk v7.0 was added in v3.9 or v3.10...
