### ISSUE TITLE
Label:the characters  with outline location error

### ISSUE THREAD

**Issue by huangzhentao** [cocos2d/cocos2d-x#11774]
Label:Fixed outline doesn't match with the characters exactly.
 v3 (#11720)

I find the latest version code. But it's still wrong.  Every letter Not on the same line.

I think 

if(_outlineSize > 0)
{
    .....
       // it miss this code to fix origin postion
       outRect.origin.x = bbox.xMin >> 6;
       outRect.origin.y = - (bbox.yMax >> 6);
   .....
}

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11782
