### ISSUE TITLE
The GL calls  and GL verts  continue to rise

### ISSUE THREAD

**Issue by SuYaoHui** [cocos2d/cocos2d-x#11775]
`Version:`Cocos2d-x 3.6
`Issue:`Create a new project and comments the `auto scene = HelloWorld::createScene();`
and `director->runWithScene(scene);`Then  run the project, the GL calls  and 
GL verts  value continue to rise.
`Solve:`Move `_runningScene->render(_renderer);` above to the `if (_runningScene)` in
`Director::drawScene()`

**Comment by walzer** [comment]
I haven't reproduce this case, but the solution is completely wrong.
