### ISSUE TITLE
scrollToPage function bug in PageView

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#11780]
> auto root = CSLoader::createNode("SelectScene.csb");
> addChild(root);
> 
> auto pageVew = dynamic_castui::PageView*(root->getChildByName("PageView"));
> pageVew->scrollToPage(1);  // 1->2

Code above is expected to move to page 2, as a result, moved to page 3

**Comment by zilongshanren** [comment]
Thanks @folgerhu 
I will fix it in the next release.

**Comment by zilongshanren** [comment]
@folgerhu please change the Title to "in PageView"... not "scrollView"
