### ISSUE TITLE
CCFileUtils::getResourceDirectory() mac impl. missing.

### ISSUE THREAD

**Issue by sundhage** [cocos2d/cocos2d-x#1178]
cocos2dx/platform/mac/CCFileUtils.mm does not implement CCFileUtils::getResourceDirectory (causing compiler errors when invoked).

Fix:

const char\* CCFileUtils::getResourceDirectory() {
    return m_obDirectory.c_str();
}

**Comment by minggo** [comment]
Thank you for your feedback.

**Comment by minggo** [comment]
I fixed this issue in this pull request:
https://github.com/cocos2d/cocos2d-x/pull/1180

**Comment by donaldalanmorrison** [comment]
@minggo That pull request fixed platform/ios not platform/mac.  What about a default virtual implementation in platform/CCFileUtils.h instead?

**Comment by godyZ** [comment]
@sundhage Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2683
