### ISSUE TITLE
Checkbox inside Scrollview bug

### ISSUE THREAD

**Issue by lalaloha** [cocos2d/cocos2d-x#11784]
If you have checkbox inside a scrollview, and the content is scrolled, and the checkbox is out of the scrollview view-port, you can still tap-through the checkbox...

**Comment by zilongshanren** [comment]
@lalaloha How to reproduce this issue?

**Comment by zilongshanren** [comment]
@lalaloha 
I can't reproduce in v3.8. If you could give a step by step instructions to reproduce this issue, feel free to reopen this issue.
Thanks.
