### ISSUE TITLE
v3: Test Action Timeline AnimationList test crashes

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#11786]
v3: Test Action Timeline AnimationList test crashes in Win32 and Windows 8.1 Universal App builds

Assert failed:  cannot set aniamtioname when enter frame with index. setEnterWithName true firstly!
Assertion failed!

Program: ... - Copy\build\Debug.win32\cpp-tests\libcocos2d.dll
File: ..\editor-support\cocostudio\ActionTimeline\CCFrame.cpp
Line: 622

**Comment by chengstory** [comment]
Please @xiaofeng11 to take a look.

**Comment by minggo** [comment]
It seems there is a pull request for it #11785.
@chengstory 
Please check it.

And this issue seems duplicated with #11730?

**Comment by chengstory** [comment]
Please @gero-cn check it.

**Comment by geron-cn** [comment]
@minggo ,yes, this issue has been fixed in pr #11785,  
but it is not duplicated with #11730.

**Comment by minggo** [comment]
@geron-cn 
Thanks.

**Comment by minggo** [comment]
@chengstory 
Any update?
