### ISSUE TITLE
Cocos2d - x2.2.6 CCLabelTTF compatibility in android5.0

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#11799]
``` cpp
    CCLabelTTF* pLabel1 = CCLabelTTF::create("123456", "fonts/Munster Bash.ttf", TITLE_FONT_SIZE);
    // position the label on the center of the screen
    pLabel1->setPosition(ccp(100, 100));
    // add the label as a child to this layer
    this->addChild(pLabel1, 1);
```

android2.3:
![image](https://cloud.githubusercontent.com/assets/3455415/7582813/b6235a56-f8c3-11e4-9e15-b24d0e6191cf.png)

android5.0:
![image](https://cloud.githubusercontent.com/assets/3455415/7582832/cdb8816e-f8c3-11e4-8320-1fe1d1f3ee63.png)

**Comment by walzer** [comment]
WTF, I hate android 5.0.

**Comment by WenhaiLin** [comment]
Found out that is not cocos2dx problem is Android 5.0 problem
https://code.google.com/p/android-developer-preview/issues/detail?id=608

**Comment by WenhaiLin** [comment]
@zilongshanren Please close this issue.
