### ISSUE TITLE
A new created project can't build under Android.

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#11796]
I use the HEAD version ( cdfce7fcaeb5b081da588614bd7a8d921fa50e19 ) of code:
1. cocos new ....
2. cocos compile -p android

Got error:

> Android NDK: frameworks\runtime-src\proj.android../../cocos2d-x/external/Box2D/Android.mk: Cannot find module with tag 'bullet' in import path

**Comment by walzer** [comment]
You need to run `./download-deps.py`, that will download and unzip `external/bullet` folder.
We're adding 3D physics into this version.
