### ISSUE TITLE
CCDirector::setNotificationNode should be bound manually

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#11817]
Sets `null` should disable the notification node, which is not the current case.

TODO:

Skip it from auto bindings
Bind it in manual bindings

@samuele3hu please check Lua

**Comment by samuele3hu** [comment]
I have checked this api in the Lua, it wouldn't trigger the assert, and i found the tips should be optimized, i will do it as soon as possible.

**Comment by pandamicro** [comment]
After looking into the problem, Jianglong and I think we should modify the bindings generator to make this fixed in auto bindings.

So Jianglong will change the auto conversions for object

**Comment by pandamicro** [comment]
Fixed at https://github.com/cocos2d/bindings-generator/pull/162
