### ISSUE TITLE
Trying to reset setup.py environment variables.

### ISSUE THREAD

**Issue by edufresne** [cocos2d/cocos2d-x#11824]
Hi,
Ive been using cocos2d-x v3.4 for iOS but I can not seem to get the android project working. At first I downloaded NDK version 10 but realized I needed version 9 to run build_native.py. Is there a way where I can reset all of the environment variables and put them in again using setup.py? I tried running an android project without running build_native.py but it crashed on launch with an error:

> libcocos2dx.apk not found

Any help would be greatly appreciated,
Thanks, Eric

**Comment by natural-law** [comment]
@edufresne 
In the version v3.4. The `build_native.py` is a deprecated way to run the project on android.

You'd better compile/run the project by `cocos2d-console`. It's in path `[cocos2d-x path]/tools/cocos2d-console/bin`. Here is a document for the usage: http://www.cocos2d-x.org/wiki/Cocos2d-console

BTW, if you have any question or suggestion when using the engine, please post to the [forum](http://discuss.cocos2d-x.org/). The issue system is using for collecting bugs, it's not a appropriate way for discussion. Thank you!
