### ISSUE TITLE
[V3]A Surplus Code In LabelTextFormatter::createStringSprites

### ISSUE THREAD

**Issue by huangzhentao** [cocos2d/cocos2d-x#11822]
In LabelTextFormatter.cpp  the function LabelTextFormatter::createStringSprites()

 if (theLabel->_labelHeight > 0)
 {
       ......
        auto labelHeightPixel = theLabel->_labelHeight \* contentScaleFactor;
        if (totalHeight > labelHeightPixel)
        {
            int numLines = labelHeightPixel / theLabel->_commonLineHeight;
            totalHeight = numLines \* theLabel->_commonLineHeight;
        }
      ......
   }

Why : 
     int numLines = labelHeightPixel / theLabel->_commonLineHeight;
     totalHeight = numLines \* theLabel->_commonLineHeight;

Instead of   " totalHeight = labelHeightPixel; "

I think it is surplus.   Is it a mistake？

**Comment by walzer** [comment]
I agree. It looks like a legacy code from a bug fix. We should fix it.

**Comment by WenhaiLin** [comment]
@huangzhentao It's not surplus, `numLines  * theLabel->_commonLineHeight`  is not necessarily equal to `labelHeightPixel`.
In the latest version, the code has changed.

@pandamicro Please close this issue.

**Comment by huangzhentao** [comment]
@WenhaiLin My mistake,Sorry.
