### ISSUE TITLE
utils::captureScreen requires optimization

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#11846]
Use this function will pause for about 1 second, it is necessary to optimize.

**Comment by perminovVS** [comment]
Check https://github.com/perminovVS/cocos2d-x/commit/d2b58dd39be862951e43244e6aa598639dafe329 (CaptureScreen save file in thread)

If all ok, it will create pull request.

**Comment by walzer** [comment]
I know that `glReadPixels` is very slow.
Thanks @perminovVS 's solution.

**Comment by perminovVS** [comment]
@walzer now very slow Image::saveToFile

**Comment by fusijie** [comment]
@walzer The bottleneck of screen capture is Image IO. My test data as following:
![captureperformancetestdata](https://cloud.githubusercontent.com/assets/5085300/8612846/0636ec00-270a-11e5-914c-666b863eda27.png)
The Image IO execute time account for more than 90% in the mobile platform.

@perminovVS  Thanks your solution.

**Comment by folgerhu** [comment]
@fusijie @pandamicro    I test in android 2.3.6, it's ok! thanks.
