### ISSUE TITLE
cocos2d::Console crashed at the first time when it received the command 'debugmsg on' in iOS simulator/device.

### ISSUE THREAD

**Issue by calfjohn** [cocos2d/cocos2d-x#11855]
Develop environment:
CocosIDE 2.0beta with Cocos2d-js-v3.3 and js-v3.6
Xcode 6.3.1 with iOS8.3

We created an new project using IDE with cocos2d-js-v3.6 and ran the application on iOS simulator, then clicked the debug button in IDE and received a crash in iOS simulator.

So we checked all the IDE codes and found that if we sent 'debugmsg on' to cocos2d::Console, we got crash, if we don't , everything is going well.

Notice: this problem only occurs in an new created project, i don't know why.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11898

**Comment by WenhaiLin** [comment]
Update:
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11950
