### ISSUE TITLE
OpenGL 0x0502 WP8.1 cocos2d-x 3.6 download zip

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#11862]
In debug deploy on device (Lumia 930) I'm getting this error with what I believe are from Labels in my main menus. I just upgrade from 3.5 to 3.6 using the download from the main website.

```
OpenGL error 0x0502 in .\cocos2d\cocos\2d\libcocos2d_8_1\libcocos2d_8_1\libcocos2d_8_1.Shared\..\..\..\..\renderer\CCTextureAtlas.cpp cocos2d::TextureAtlas::drawNumberOfQuads 691
```

**Comment by WenhaiLin** [comment]
@zilongshanren I think this issue is duplicated with https://github.com/cocos2d/cocos2d-x/issues/12343 and has been fixed.
