### ISSUE TITLE
SimpleAudioEngine::getInstance()->setBackgroundMusicVolume is not implemented

### ISSUE THREAD

**Issue by Seryusjj** [cocos2d/cocos2d-x#11867]
SimpleAudioEngine::getInstance()->setBackgroundMusicVolume was not working for me so whe a take a look at the source code this is what I get ....

float SimpleAudioEngine::getBackgroundMusicVolume()
{
    return 1.0;
}

void SimpleAudioEngine::setBackgroundMusicVolume(float volume)
{
}

float SimpleAudioEngine::getEffectsVolume()
{
    return 1.0;
}

void SimpleAudioEngine::setEffectsVolume(float volume)
{
}

**Comment by walzer** [comment]
Yes, we haven't implemented this feature on win32 platform. But this function works well on ios, android, winrt and the rest platforms.

Alternatively, please use `AudioEngine` instead of `SimpleAudioEngine`, which has implemented `AudioEngine::setVolume(int audioID, float volume)`.

**Comment by Seryusjj** [comment]
thanks :)

**Comment by jptester** [comment]
Hey guys, can you tell me how to use AudioEngine and SimpleAudioEngine in JS? (using 3.10 right now)  The only class I see is: cc.audioEngine, but no cc.simpleAudioEngine, or cc.experimentalAudioEngine or something
