### ISSUE TITLE
Need to replace thread unsafe code from TextureCache::addImageAsync

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#11887]
TextureCache::loadImage will be runnedin parallel thread by TextureCache::addImageAsync, but _textures.find() and _textures.end() used inside aren't thread-safe and there is no lock.

http://discuss.cocos2d-x.org/t/looks-like-texturecache-loadimage-is-not-thread-safe/21414

**Comment by walzer** [comment]
Yes, this is a critical bug!

**Comment by 0xJimmyBeh** [comment]
@walzer 
There is a long existing issue with TextureCache.addImageAsync in Cocos2d-JS too.

https://github.com/cocos2d/cocos2d-js/issues/1658

Please solve them together since all engine going to merge soon.

Thanks.
