### ISSUE TITLE
Cocos2d-x 3.4rc0 to v3 head - lua slow on android

### ISSUE THREAD

**Issue by SecondDegree** [cocos2d/cocos2d-x#11894]
I've been running tests for the past few days to try and figure out what is slowing down a game I'm working on so much on android devices and have discovered that it sped up when I jumped back to b5f8666 and slowed down again at 865ae56.

My test goes from taking 0.017222 seconds (b5f8666) to taking 138.304155 seconds (865ae56) to run  which is about 800,000% slower. This slowness still occurs currently at e3e78b0.
The test itself is simply timing an empty for loop doing 400,000 iterations in a function which is called 50 times (to average out the results). This is all in Lua and I'm running it in main.lua:main() before anything else.
I got these results running on a OnePlus One on android 5.0.2 building in debug.
I have run the same test on an iPhone 4 and get close to the same times regardless of what version of cocos its running on, indicating that this is an android only issue.
I have also tried running the test on other android devices and they show similar results to varying degrees (seemingly dependent on their cpu power).

**Comment by samuele3hu** [comment]
Can you give me test case,thanks.

**Comment by SecondDegree** [comment]
Here's a link to the test lua file on dropbox: https://www.dropbox.com/s/0vdmkptxat84btm/loopTest.lua?dl=0

**Comment by SecondDegree** [comment]
After looking into it some more, I can confirm that the commit which caused the slow down is 4bdd3f0. This commit simply updated the dependencies from 30 to 31. I can also confirm that the change within the dependencies was updating the version of LuaJIT to 2.0.3, as reverting LuaJIT back to the previous version shows no slow down.

**Comment by samuele3hu** [comment]
@SecondDegree ,I have check the performance by your script, the LuaJIT 2.0.1 performance better indeed, we update LuaJIT to the 2.0.3 because it fixed some bugs and it have been used on the other branch for half a year without happening the big problem.I have feedback this problem to the author of LuaJIT, and i will check the compile flags used to compile LuaJIT library.

**Comment by pandamicro** [comment]
@samuele3hu If there is no further informations for now, I will move this issue to v3.8

**Comment by SecondDegree** [comment]
I have no additional information at this point, thanks.

**Comment by dualface** [comment]
add to main.lua

```
jit.off()
```

**Comment by dualface** [comment]
@pandamicro please close thie issue, thanks.
