### ISSUE TITLE
Mouse doesn't support Previous Location

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#11919]
Can we add the ability for mouse events to store the previous point?

**Comment by walzer** [comment]
I would deny your request. For 2 reasons:
1. We can do this in our mouse event callback
2. Even the mouse events send from and Windows and OS X, they don't have the data of previous location.

**Comment by walzer** [comment]
Please also refer to android's touch event: http://developer.android.com/training/graphics/opengl/touch.html

Developers need to restore previous location in their code, not from system callback.

**Comment by stevetranby** [comment]
So you should get rid of the previous touch then, no? Either all movement input methods should have a previous state, or not. Doesn't matter if the OS supports it. Right now the Touch provides previous, Mouse does not. I'm fine with removing previous from touches as well if you want the developer to handle it themselves. Right now it seems to be a conflicting API.
