### ISSUE TITLE
Refine performance for Cocos Studio JSON parser for 2.x

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#11913]
User reported the parsing process is extremely long in 2.x.

Engine version : Cocos2d-JS v3.3

| Editor version | Time spent | API used |
| --- | --- | --- |
| Cocos Studio 2.2.6 | 2096ms | `ccs.load` |
| Cocos Studio 1.6 | 77ms | `ccs.uiReader.widgetFromJsonFile` |

Reported by IDIS工作室 (QQ: 147040804)

**Comment by pandamicro** [comment]
Backup plan: Use Emscripten to compile C++ csb parser to JS and maintain only one version of parser for C++/Lua/JS

**Comment by pandamicro** [comment]
We have do some test based on v3.7

Web version performance test:
![wechat_1437536659](https://cloud.githubusercontent.com/assets/632460/8817562/2fe4a05e-3067-11e5-8539-4cc0c4ed866b.jpeg)

iOS performance test:
![wechat_1437536627](https://cloud.githubusercontent.com/assets/632460/8817566/3cd7901e-3067-11e5-8a35-0ad4e4632ee4.jpeg)
![wechat_1437536622](https://cloud.githubusercontent.com/assets/632460/8817569/4150f892-3067-11e5-9ef2-4b8f2657899b.jpeg)

Android performance is similar to iOS

**Comment by pandamicro** [comment]
Basically, the strange time consumption is in SimpleAudio and TextBMFont parser, they could be improved.

@VisualSJ Can you state the meaning of each column ?

**Comment by VisualSJ** [comment]
5: Parse all of the properties
1: Don't do anything, only to return empty CCNode
2: Not parsing anything, returns the correct object
3: Not parsing generic properties(LayoutComponent, position, anchor...)
4: Not parsing LayoutComponent

**Comment by pandamicro** [comment]
Removing Audio play is effectively speed up the parse performance: https://github.com/cocos2d/cocos2d-x/pull/13002

**Comment by pandamicro** [comment]
Further research about this issue will be scheduled to future versions
