### ISSUE TITLE
TileMap may crash if a layer containers nothing

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#11912]
- engine version: every engine version including latest code
- how to reproduce
  uses this resource in hellocpp:  http://pan.baidu.com/s/1gdD31tx

Corresponding pull request: #11910

**Comment by minggo** [comment]
@WenhaiLin 
Please help to verify it.

**Comment by kerrisong** [comment]
hi，minggo~：such as these issues，please inform me，too，I need to update the schedule，thanks~

**Comment by minggo** [comment]
@kerrisong
Ok.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11969
