### ISSUE TITLE
TTF Label, drop shadow, retina screens

### ISSUE THREAD

**Issue by dakikifr** [cocos2d/cocos2d-x#11927]
Hi,

I've only noticed now a bug in the TTF Label class when using a drop shadow on retina screens.

This is the code used to create a label:

```
Label* labelSprite = Label::createWithTTF(label, fontPath, desiredFontSize);
labelSprite->setTextColor(Color4B(255, 156, 0, 255));
labelSprite->enableShadow(Color4B::BLACK, Size(2, -2), 1);
labelSprite->enableOutline(Color4B::WHITE, 2);
```

When used on a non-retina device, the outline and the shadow are correctly drawn with 2 points (2 pixels).
But when used on a retina device, the outline is still correctly using 2 points (4 pixels), but the drop shadow is now using 4 points (8 pixels)!
This causes a different render on a retina and non retina screen.

I've tested this code in cocos2d-x 3.2 and 3.6, but I guess the bug has always been there.

See following screenshots, the first is on a non-retina device, the second on a retina device:
![0d5510243ae26613](https://cloud.githubusercontent.com/assets/4882169/7728381/390f68fa-ff0f-11e4-84ed-e4bf73986f1c.png)
![10b7bc52ed3eb08c](https://cloud.githubusercontent.com/assets/4882169/7728393/4310586e-ff0f-11e4-95bd-0f582e6fae6e.png)

Am I wrong, or is there really a bug?
Thanks!
Kiki

**Comment by dakikifr** [comment]
If I force contentScaleFactor variable to 1.0f (instead of CC_CONTENT_SCALE_FACTOR()) in the Label::enableShadow method (CCLabel.cpp), then the result is the same on retina and non-retina devices.

Maybe the content scale is already taken into account inside the shadow shader, and there is no need to use the scale here, or maybe it should be used here but not in the shader??

**Comment by walzer** [comment]
So there're different requirements.
@ricardoquesada what's your suggestion? Should we apply `contextScaleFactor` to label shadows?

**Comment by ricardoquesada** [comment]
@walzer I'm not familiar with that part of the code, but yes, it seems to be a bug in our code.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/14107

**Comment by ricardoquesada** [comment]
closing it since it is fixed.

**Comment by dakikifr** [comment]
Sorry I totally forgot to close it :)
Thanks!
