### ISSUE TITLE
allow both direction vertical and horizontal for ui::PageView

### ISSUE THREAD

**Issue by anjandaffo** [cocos2d/cocos2d-x#11926]
Please allow user to setDirection in ui::PageView like ui::ScrollView and ui::ListView.So PageView either use for vertical or horizontal direction.

**Comment by anjandaffo** [comment]
I modified the PageView.h and PageView.cpp file to setDirection for PageView like Scrollview and ListView. Now I can call setDirection method and vertical pageview is working.

There are no option to attach file, so I can't post modified file. I had post the modified file on Cocos2d-x forum.

http://discuss.cocos2d-x.org/t/will-pageview-support-vertical-direction/13307/3?u=anjanjis

Thanks
Anjan Kumar

**Comment by zilongshanren** [comment]
@anjandaffo  duplicated with https://github.com/cocos2d/cocos2d-x/issues/10778
