### ISSUE TITLE
Cocos2d-x 3.6 possible Crash in CCFrame.cpp

### ISSUE THREAD

**Issue by kybird** [cocos2d/cocos2d-x#11923]
In CCFrame.cpp

there is many if condition like below

`if (nullptr != _node && _betweenScaleX != 0 || _betweenScaleY != 0)`

should be

`if (nullptr != _node && (_betweenScaleX != 0 || _betweenScaleY != 0) )`

I have problem when i use UI Animation by Cocos Studio

thanks for reading

**Comment by pandamicro** [comment]
Checked, this have been fixed in https://github.com/cocos2d/cocos2d-x/pull/11680
