### ISSUE TITLE
Sprite can move out to black border in autoscale = "FIXED_HEIGHT"

### ISSUE THREAD

**Issue by jie-meng** [cocos2d/cocos2d-x#11974]
Environment: cocos2dx 3.5, lua-project, android device

I use CC_DESIGN_RESOLUTION.autoscale = "FIXED_HEIGHT" at first,

Game tested ok on windows and linux. 

But when I deploy apk to android device, there are two black borders at each side horizon. 

When I try move sprite to the border, it moves out of the map to the border area!

I modified the CC_DESIGN_RESOLUTION.autoscale to SHOW_ALL, then the Sprite cannot move out of the map.

Here are the screenshots.

![fixed_height](https://cloud.githubusercontent.com/assets/7405315/7765406/2881b38a-0090-11e5-8143-4a3fcb6aa54b.png)

![show_all](https://cloud.githubusercontent.com/assets/7405315/7765409/308b57d4-0090-11e5-8ae1-754be163fda9.png)

**Comment by jie-meng** [comment]
The first image shows FIXED_HEIGHT, the second one shows SHOW_ALL.

**Comment by jie-meng** [comment]
I found the real position of map move left to the border of the screen, Sprite cannot move to then right area of map.

Same problem also existed in condition of FIXED_WIDTH, vertical direction has the same dislocation problem.

**Comment by walzer** [comment]
Designed as this.
When moving your spider, you should use `VisibleRect::left().x` instead of x coordinate `0` to calculate.
