### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by yiquanshui** [cocos2d/cocos2d-x#11970]
All version have the problem.
GLProgram::parseVertexAttribs nad GLProgram::parseUniforms(CCGLProgram.cpp), alloca the attribName but never free it.

**Comment by walzer** [comment]
Thanks for your feedback. It do looks like a bug here.

**Comment by fusijie** [comment]
@yiquanshui 

`_alloca` allocates size bytes from the program stack. The allocated space is `automatically freed` when the calling function exits (not when the allocation merely passes out of scope). Therefore, `do not pass` the pointer value returned by _alloca as an argument to free.

We often do this:

``` cpp
#define alloca(size)    __alloca(size)
```

You can refer to [Linux man-pages](http://linux.die.net/man/3/alloca) or [MSDN](https://msdn.microsoft.com/en-us/library/wb1s57t5.aspx).
