### ISSUE TITLE
There are some Jaggies on ClippingNode

### ISSUE THREAD

**Issue by aababy** [cocos2d/cocos2d-x#11981]
version: 
C++ 3.6
step:
1. create a HelloWorld Project
2. modify HelloWorldScene.cpp
auto stencil = Sprite::create("ui02_picture.png");
    stencil->setScale(0.4);
    auto _underContent = Sprite::create("HelloWorld.png");
    auto _underClipper = ClippingNode::create(stencil);
    _underClipper->setAlphaThreshold(0.8f);
    _underClipper->setInverted(false);
    _underClipper->setAnchorPoint(Vec2(0.5, 0.5));
    _underClipper->addChild(_underContent);
    _underClipper->setPosition(getContentSize() / 2);
    addChild(_underClipper);
1. use ipad 2 as simulator.
2. you will see there are some jaggies in the edges, but ui02_picture (the picture below) has no jaggies.

![ui02_picture](https://cloud.githubusercontent.com/assets/8336452/7765913/3c9bfcd0-0096-11e5-9d0c-561d0cefa145.png)

Thank you for your great work.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@aababy
