### ISSUE TITLE
Setting UserDefault key with spaces breaks the entire xml

### ISSUE THREAD

**Issue by tankorsmash** [cocos2d/cocos2d-x#11996]
```
UserDefault* ud = UserDefault::getInstance();
ud->setBoolForKey("this has a space");
```

Spits out 

```
read root node error
```

and then the `UserDefault.xml` has only the following in it

   <?xml version="1.0" encoding="UTF-8"?>

Right now, I'm fixing this locally by writing a simple validation function and throwing it in before each call to set data in `cocos/base/CCUserDefault.cpp`:

```
void validate_key(std::string key)
{
    auto pos = key.find(" ");
    bool valid_string = pos == std::string::npos;
    if (!valid_string)
    {
        cocos2d::log("found a space in the key \"%s\"", key.c_str());
        assert(valid_string && "Cant have spaces in userdefault keys");
    }
}
```

and something like `validate_key("this has a space");` would throw the exception. I didn't want to make the pull request because I'm not confident that it's fast enough, and I'm sure you guys have a specific string you'd rather use.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@tankorsmash
