### ISSUE TITLE
UserDefault should (un)escape XML characters on all platforms.

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#11997]
UserDefault silently fails when trying to add key or data that includes an XML parse character such as the "less than" character on a platform that rely's on cocos2d's internal XML parser. On iOS/Mac it uses Apple's PLIST parser and it handles the escaping internally.

Sample Valid PLIST

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Test</key>
    <string>&lt;b&gt;One &amp; Two&lt;/b&gt;</string>
    <key>Key&lt;Int&gt;</key>
    <string>my value</string>
</dict>
</plist>
```

Key=Values:
`Test` = `<b>One & Two</b>`
`Key<Int>` = `my value`

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@stevetranby
