### ISSUE TITLE
Provide a generic asynchronous resource loading process

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12021]
We have an asynchronous loading function for TextureCache, `addImageAsync`:

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/renderer/CCTextureCache.h#L123

But can we have a common asynchronous loading process for all type of resources ? Otherwise, while loading some resources, especially some heavy resources like animation, cocos studio big scenes, the game will suffer a period of frozen time.

The theoretic solution can be open a thread, runs the loading task, and invoke a callback while the loading function returns.

Reference: http://blog.csdn.net/chenhaobright/article/details/44619633

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@pandamicro

**Comment by tankorsmash** [comment]
I don't necessarily want to reopen, but it would be cool if there was a generic solution for animations and spriteframes
