### ISSUE TITLE
Add Spine Skeleton Animation Cache

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12020]
The current Spine animation are often created by `createWithFile` API: https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/editor-support/spine/SkeletonAnimation.h#L51

However, there isn't an AnimationCache / SpriteFrameCache like class to cache spine animation data. It's an important feature, because `createWithFile` need to read and parse file every time and it's very long. If we cache the spine animation data, we can support preload and use the data to create animations instantly.

Proposed solution:

Use `spSkeletonJson_create` and `spSkeletonJson_readSkeletonDataFile` to get the `spSkeletonData` and cache it into a SpineAnimationCache with a key (file name by default)

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/editor-support/spine/SkeletonJson.h#L51

Important APIs needed:
1. SpineAnimationCache::getInstance()
2. SpineAnimationCache::addAnimation(const std::string& skeletonDataFile, const std::string& atlasFile)
3. SpineAnimationCache::getAnimation(const std::string& key)

We can add other needed APIs similar to CCAnimationCache

Reference: http://blog.csdn.net/chenhaobright/article/details/44619633

**Comment by tangyiyang** [comment]
I think "CCFileDataCache" is a better solution, sometimes you also need to cache other files, such as json configuration file, localization file.

**Comment by pandamicro** [comment]
But they don't have the same data type, can you propose some solution for handling the difference between different data types ?

**Comment by tangyiyang** [comment]
There's no need to care about the file type(extensions), all we need is just the 'FileData' pointer and the length of the file.
All we need is only 2 interfaces. The user should care about NOT to use the same file path.

// when we load some file into the memory, we add the file to the cache, the cache saves the pointer to the file which been read with CCFileUtil::getFileData()

void FileDataCache::addFile(const char\* fileName);

// the length is an output parameter, stores the length of the fileName.
unsigned char\* FileDataCache::getFile(const char\* fileName, int\* length);

**Comment by pandamicro** [comment]
Oh, I see, what you are proposing is a File level resource cache, this can avoid time of loading data from file system. It's not really relevant to this issue. This issue want to discuss a cache for Spine's SkeletonAnimation.

The file data cache can be a low level cache.
On top of it, there are SpriteFrameCache, TextureCache, AnimationCache, SpineAnimationCache etc...

It's based on the fact that we need to load file data, then parse it or read it to the memory and construct a high level object which propose high level APIs, like Texture2D, SkeletonAnimation, etc

**Comment by tangyiyang** [comment]
I got your point.
Actually, It's slow to read the json file data and the atlas file created by Spine. But it's really fast to parse them.
I've tested that you can create 30 spine animations in only 1sec as long as you have preload the json and atlas file into memory.

**Comment by pandamicro** [comment]
I created a new issue for your request: https://github.com/cocos2d/cocos2d-x/issues/12177

**Comment by linhbanhmi** [comment]
I create a spine boy,and add it to current scene, its never shown up, but shown when run scene again.
Value "renderMode" in project.json is 0.
When i change   "renderMode" in project.json to 1. its shown all the time.
Here's my code:
spineBoy = new sp.SkeletonAnimation('res/skeletons/choingay.json', 'res/skeletons/choingay.atlas');
        this.addChild(spineBoy, 99);
        spineBoy.setAnimation(0, 'animation', true);
        spineBoy.setVisible(true);
        spineBoy.setPosition(cc.p(1280, 543));
        spineBoy.setAnchorPoint(cc.p(0.5, 0.5));
I think i need to cache .json and .atlas file first, but I didn't find any things SpineAnimationCache in cocos2dx js. Can you guild me, please.
Sorry for my Bad English.
@pandamicro

**Comment by minggo** [comment]
already update spine runtime
