### ISSUE TITLE
Label TTF problem with TextureAtlas resizing (android)

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#12029]
I have a long text, created with Label:createWithTTF and then inserted in a scrollview.
With normal text, all is ok.

When the text is long I got this in android debug.

```
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [30] to [41].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [41] to [56].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [56] to [76].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [76] to [102].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [102] to [137].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [137] to [184].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [184] to [246].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [246] to [329].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [329] to [440].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [440] to [588].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [588] to [785].
cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [785] to [1048].
cocos2d: fullPathForFilename: No file found at Helvetica. Possible missing file.
```

Not only I got the error that Helvetica font is missing (I have selected another TTF), but when I scroll in scrollview sometimes the font disappear, I don't know why.
When the TextureAtlas remains around 400-600 the error of "no file found at Helvetica" doesn't appear, so it seems a weird bug occurring when the capacity goes up 1000 or so.

Debugging on win32 I got no problem.

**Comment by dariodepaolis** [comment]
Is it a bug or not?

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@dariodepaolis
