### ISSUE TITLE
Image::initWithImageFileThreadSafe is not thread safe

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#12035]
It uses singleton FileUtils inside
So if FileUtils instance will be destroyed in main thread it will crush.
http://discuss.cocos2d-x.org/t/initwithimagefilethreadsafe-in-ccimage-is-not-thread-safe/21706/1

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@sbrednikhin
