### ISSUE TITLE
ui::TextField doesn't support cursor 

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#12044]
If we provide cursor feature to ui::TextField, the users could delete at any given index.

http://discuss.cocos2d-x.org/t/is-there-any-way-to-change-the-input-character-index-for-the-textfield-widget/21714

**Comment by felixjingga** [comment]
is there any quick fix or can you make this issue more urgent to solve?

Thanks,

**Comment by 0xJimmyBeh** [comment]
+1 for this feature.

It is very problematic when we just need to modify a grammar mistake at earlier index in a long text.
We have no choice but to retype whole text. 

Moreover, it is good to have a cursor to indicate clearly which TextField is being using and the position we are typing.

**Comment by zilongshanren** [comment]
@felixjingga  @Zinitter  Support cursor and other fancy editbox feature on top of OpenGL is tricky.
So we decide to drop TextField and put all of our effort into improving the EditBox control.

**Comment by xpol** [comment]
I was planing to implement a multiline text editing control with cursor support on top OpenGL (based on TextField). 

Then I saw [this discuss](http://discuss.cocos2d-x.org/t/what-do-you-hate-most-in-terms-of-editbox-and-textfield/22436).

So I tested the latest 3.9 code find no cursor at all.

The solution is to roll my own.

PS: @zilongshanren Would please add update to that discuss maybe ~~strikethrough~~ would help.
PPS: I will not trust you @zilongshanren any more. :sob:

**Comment by 0xJimmyBeh** [comment]
@xpol 

Check this if you interesting on textfield cursor support
https://github.com/cocos2d/cocos2d-x/pull/13903

**Comment by xpol** [comment]
@Zinitter Thank you for you information.

**Comment by zilongshanren** [comment]
@xpol 

The TextField cursor support is not finished. And the PR is still pending due to merge conflicts.
If someone could continue the work with #13903, I will merge the code.

**Comment by xpol** [comment]
@zilongshanren Thank you.

**Comment by cellininicholas** [comment]
So a Textfield cursor was never implemented?...
I was using EditBox, but found that it had no text alignment properties (am I wrong?)
So I decided to use Textfield, but it has no Cursor.
Is it possible to center align the EditBox?

**Comment by zilongshanren** [comment]
@cellininicholas  EditBox TextAlignment will be implemented in the future.
Here is a implementation only for iOS and Android.

https://github.com/cocos2d/cocos2d-x/pull/14459

**Comment by cellininicholas** [comment]
Thanks @zilongshanren! Found it a little tricky to merge into v3.12, so I've given up for now :\
