### ISSUE TITLE
download-deps.py version 56 corrupts the tools/framework-compile folder

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#12067]
download-deps.py version 56 corrupts the /framework-compile folder.. Since tools/framework-compile already exists, copying external/framework-compile to tools/framework-compile causes a change in git status since the tools/framework-compile files are changed. Why are we copying these files? Do we need to delete the files in the existing tools/framework-compile folder from the cocos2d-x repo? since download-deps.py is now copying these files over to the tools/framework-compile folder.

This problem was caused by pull request https://github.com/cocos2d/cocos2d-x/commit/a65d7ea49a591343a16edb813c352681a263a0f9

How to reproduce

git clone https://github.com/cocos2d/cocos2d-x.git
cd cocos2d-x
git checkout v3
git status (everything is fine)
python download-deps.py (version 56)
git status

modified:   tools/framework-compile/bin-templates/cpp-template-default/Classes/AppDelegate.cpp
modified:   tools/framework-compile/bin-templates/cpp-template-default/Classes/HelloWorldScene.cpp
modified:   tools/framework-compile/bin-templates/cpp-template-default/Classes/HelloWorldScene.h
modified:   tools/framework-compile/bin-templates/cpp-template-default/cocos-project-template.json
modified:   tools/framework-compile/bin-templates/cpp-template-default/proj.android/jni/Android.mk
modified:   tools/framework-compile/bin-templates/cpp-template-default/proj.win32/HelloCpp.sln
modified:   tools/framework-compile/bin-templates/cpp-template-default/proj.win32/main.cpp
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-landscape/HelloCpp.ccs
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-landscape/HelloCpp.cfg
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-landscape/HelloCpp.udf
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-landscape/cocosstudio/MainScene.csd
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-portrait/HelloCpp.ccs
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-portrait/HelloCpp.cfg
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-portrait/HelloCpp.udf
modified:   tools/framework-compile/bin-templates/cpp-template-default/res-portrait/cocosstudio/MainScene.csd
modified:   tools/framework-compile/bin-templates/js-template-runtime/.project
modified:   tools/framework-compile/bin-templates/js-template-runtime/cocos-project-template.json
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.android/build-cfg.json
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.android/jni/Android.mk
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.win32/HelloJavascript.sln
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.win32/build-cfg.json
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.win32/main.cpp
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.win32/stdafx.cpp
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.win32/stdafx.h
modified:   tools/framework-compile/bin-templates/js-template-runtime/frameworks/runtime-src/proj.win32/targetver.h
modified:   tools/framework-compile/bin-templates/js-template-runtime/index.html
modified:   tools/framework-compile/bin-templates/js-template-runtime/main.js
modified:   tools/framework-compile/bin-templates/js-template-runtime/project.json
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-landscape/HelloJavascript.ccs
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-landscape/HelloJavascript.cfg
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-landscape/HelloJavascript.udf
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-landscape/cocosstudio/MainScene.csd
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-landscape/res/MainScene.json
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-portrait/HelloJavascript.ccs
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-portrait/HelloJavascript.udf
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-portrait/cocosstudio/MainScene.csd
modified:   tools/framework-compile/bin-templates/js-template-runtime/res-portrait/res/MainScene.json
modified:   tools/framework-compile/bin-templates/js-template-runtime/src/app.js
modified:   tools/framework-compile/bin-templates/js-template-runtime/src/resource.js
modified:   tools/framework-compile/bin-templates/lua-template-runtime/cocos-project-template.json
modified:   tools/framework-compile/bin-templates/lua-template-runtime/frameworks/runtime-src/proj.android/jni/Android.mk
modified:   tools/framework-compile/bin-templates/lua-template-runtime/frameworks/runtime-src/proj.win32/HelloLua.sln
modified:   tools/framework-compile/bin-templates/lua-template-runtime/frameworks/runtime-src/proj.win32/main.cpp
modified:   tools/framework-compile/bin-templates/lua-template-runtime/res-landscape/HelloLua.ccs
modified:   tools/framework-compile/bin-templates/lua-template-runtime/res-landscape/HelloLua.cfg
modified:   tools/framework-compile/bin-templates/lua-template-runtime/res-landscape/HelloLua.udf
modified:   tools/framework-compile/bin-templates/lua-template-runtime/res-landscape/cocosstudio/MainScene.csd
modified:   tools/framework-compile/bin-templates/lua-template-runtime/res-portrait/HelloLua.ccs
modified:   tools/framework-compile/bin-templates/lua-template-runtime/res-portrait/HelloLua.udf
modified:   tools/framework-compile/bin-templates/lua-template-runtime/res-portrait/cocosstudio/MainScene.csd
modified:   tools/framework-compile/bin-templates/lua-template-runtime/src/app/MyApp.lua
modified:   tools/framework-compile/bin-templates/lua-template-runtime/src/app/views/MainScene.lua
modified:   tools/framework-compile/bin-templates/lua-template-runtime/src/config.lua
deleted:    tools/framework-compile/gen_cocos_libs.sh
modified:   tools/framework-compile/x-modified/cocos/audio/android/prebuilt-mk/Android.mk
modified:   tools/framework-compile/x-modified/cocos/prebuilt-mk/Android.mk
modified:   tools/framework-compile/x-modified/cocos/scripting/js-bindings/proj.android/prebuilt-mk/Android.mk
modified:   tools/framework-compile/x-modified/cocos/scripting/lua-bindings/proj.android/prebuilt-mk/Androi

**Comment by zilongshanren** [comment]
hi @stammen  do you try it on your Windows machine?

**Comment by stammen** [comment]
@andyque  Yes. I tried it on a windows machine. Since git on Windows checks out files with CRLF, it shows all the files that are being overwritten by download-deps.py since the files in the download have only LF endings. We should not be replacing files that are checked into the cocos2d-x repo. Please decide which files are correct and delete the extra copies.

**Comment by zilongshanren** [comment]
@stammen  Yes, I have told the guy who made this mistake. He is handling this issue.
Thanks.

**Comment by stammen** [comment]
@andyque  Thanks for the update.

**Comment by zilongshanren** [comment]
@stammen  Fixed at https://github.com/cocos2d/cocos2d-x/pull/12069

**Comment by stammen** [comment]
@andyque How does one add or modify an app template now?

**Comment by zilongshanren** [comment]
The template is used for Cocos Framework, it will be added in the cocos2d-x-3rd-bin repository.
