### ISSUE TITLE
VideoPlayer on Android ignores search paths

### ISSUE THREAD

**Issue by stari4ek** [cocos2d/cocos2d-x#12097]
iOS works well, cause search path is resolved in  `UIVideoViewWrapperIos::setURL:videoSource` with help of `UIVideoViewWrapperIos::fullPathFromRelativePath`

**Comment by stari4ek** [comment]
can anyone review it? there is PR for it

**Comment by pandamicro** [comment]
Thanks @stari4ek It's merged
