### ISSUE TITLE
cpp-tests set macros CC_ENABLE_BOX2D_INTEGRATION=1 then compile error

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12104]
cocos 2d-x 3.6
cpp-tests set macros CC_ENABLE_BOX2D_INTEGRATION=1 then compile error

![image](https://cloud.githubusercontent.com/assets/3455415/7880456/1f89fe30-062c-11e5-8f2c-5c1e10fe1687.png)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12236
