### ISSUE TITLE
Plese bind CCFastTMXTiledMap to js

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12121]
Plese bind CCFastTMXTiledMap to js，and merge https://github.com/cocos2d/cocos2d-x/pull/11910 to CCFastTMXTiledMap implementation

**Comment by pandamicro** [comment]
- [ ] Merge https://github.com/cocos2d/cocos2d-x/pull/11910 to CCFastTMXTiledMap implementation
- [ ] Bind CCFastTMXTiledMap

**Comment by yue19870813** [comment]
What's the status of the issues?

**Comment by drelaptop** [comment]
out-of-data JS bind issues, reopen it if someone care it now and later.
