### ISSUE TITLE
GLProgram memory do not release.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#12138]
`version:` v3.5
`issue:` Create a GLProgram object and release it, the memory of it do not release.
`reproduce:` GLProgram is an autorelease object. Notice the memory.

``` cpp
for (int i=0; i<500; i++) {
            auto glProgram = cocos2d::GLProgram::createWithByteArrays(cocos2d::ccPositionTextureColor_noMVP_vert, cocos2d::ccPositionTextureColor_frag);
        }
```

**Comment by dabingnn** [comment]
Memory leak does not exists. Tested on IOS by using profile tools.
However, the program would crash if there are two many glprograms create in a short while because the release of the memory is delayed.

Please close it.

**Comment by dabingnn** [comment]
@fusijie @pandamicro @andyque
