### ISSUE TITLE
formarRenderers in RichText doesn’t update container size

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#12145]
need to update container size in RichText

http://discuss.cocos2d-x.org/t/formarrenderers-in-richtext-doesnt-update-container-size/21710

**Comment by pandamicro** [comment]
Related PR: https://github.com/cocos2d/cocos2d-x/pull/12806

**Comment by pekayatt** [comment]
This has been solved for JS as well? Having the same problem here in the HTML5...
