### ISSUE TITLE
One cannot pause an action of a node before first onEnter() call

### ISSUE THREAD

**Issue by jphw** [cocos2d/cocos2d-x#12143]
Basically, if i want to create a number of actions for a node during its initialization (in overrided init() function), and then pause them right after it, in order to just unpause them when time comes instead of creating an actions - i cannot pause an action right after the runAction() call, and i need to call ActionManager::pauseTarget in onEnter() function, because otherwise it will have no effect. 

so, code like this below will not work

class MySprite : public Sprite
{
    virtual bool init() override
    {
        . . .
        runAction( someAction );
        Director::getInstance()->getActionManager()->pauseTarget( this );
        . . .
    }
}

**Comment by pandamicro** [comment]
The action manager is designed in this way, actions are not managed unless their target node is running. So please put such logic into `onEnter` `onExit` functions
