### ISSUE TITLE
Some basic transitions do not animate on Android 5.x

### ISSUE THREAD

**Issue by hawkwood** [cocos2d/cocos2d-x#12146]
Built Cpp-Tests from Cocos 3.6 and installed on Nexus 7 running Android 5.0.2, and some scene transitions do not animate, they just immediately (or after a delay) switch to the next scene.  Specifically:
TransitionCrossFade
TransitionProgressRadialCCW
TransitionProgressRadialCW
TransitionProgressHorizontal
TransitionProgressVertical
TransitionProgressInOut
TransitionProgressOutIn

**Comment by fusijie** [comment]
In my Nexus9, Android 5.0.1, All of the transitions you mentioned are correct. I'll find a 5.0.2 device to test it.

**Comment by hawkwood** [comment]
Which NDK are you using? I used r10d.

**Comment by fusijie** [comment]
r10c.

**Comment by fusijie** [comment]
@hawkwood NDK version should not the reason of this issue, but could you please help to test ndkr10c for 5.0.2. My nexus9 encounter problem(GFW...%>_<%) when upgrade to 5.0.2

**Comment by hawkwood** [comment]
I only have the a 2012 Nexus 7 which is upgraded to Android 5, specifically 5.1.1 now. I rebuilt and tested with NDK r10c and am still seeing the issue.

**Comment by hawkwood** [comment]
As an additional test, I installed TestCpp from Cocos 2.2.6 and the transitions are working correctly there.  in fact, the page curl transitions look better on 2.2.6 than on 3.7.

**Comment by 42stones** [comment]
Any progress on that?

**Comment by hawkwood** [comment]
Looks like this is fixed in 3.11 using NDK r10e.  I tested on 5 devices, ranging from Android 4.1 to 6.
