### ISSUE TITLE
The Button in the clipped area of scrollview still can be clicked.

### ISSUE THREAD

**Issue by jyoxun** [cocos2d/cocos2d-x#12141]
We add a button to the scrollview, and set the position to outside of the visible view. But the button still can be clicked.

**Comment by jyoxun** [comment]
Below is my resolution, FYI.

bool Widget::isClippingParentContainsPoint(const Vec2 &pt) 
{ 
_affectByClipping = false; 
#if 0 
    Widget\* parent = getWidgetParent(); 
#esle
    Node\* parent = getParent(); 
#endif
    Widget\* clippingParent = nullptr; 
    while (parent) 
    { 
        Layout\* layoutParent = dynamic_cast<Layout*>(parent); 
        if (layoutParent) 
        { 
            if (layoutParent->isClippingEnabled()) 
            { 
                _affectByClipping = true; 
                clippingParent = layoutParent; 
                break; 
            } 
        } 
#if 0
        parent = parent->getWidgetParent(); 
#else 
        parent = getParent(); 
#endif
    }

**Comment by zilongshanren** [comment]
This issue can't be reproduced.
