### ISSUE TITLE
Cocos2dxSound.java have thread safety problem

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#12156]
`preloadEffect` will release the mSemaphore also, so if you call `preloadEffect` first, and then call `playEffect` to play some unloaded sound, the mSemaphore's acquire will return immediately, and gain a wrong streamID.

**Comment by pandamicro** [comment]
Originally reported: https://github.com/cocos2d/cocos2d-js/issues/1766

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12256
