### ISSUE TITLE
cocos2dx 3.6版本 Label 显示问题

### ISSUE THREAD

**Issue by jasonzhangxx** [cocos2d/cocos2d-x#12154]
如图：
![img_0072](https://cloud.githubusercontent.com/assets/2697724/7953688/69c4b31a-09fa-11e5-9634-9d0116dac941.PNG)
很明显字符的边缘被截掉了部分像素。下方和右侧较为明显。

凑合的解决方法，设置2像素透明色的outline。

附上代码：

``` c++
Label* label = Label::createWithTTF("aaaaaa:8888", "fonts/arial.ttf", 34);`
label->setPosition(Vec2(480,320));`
label->setColor(Color3B(0,0,0));`
this->addChild(label); 
```

**Comment by jminht** [comment]
请问解决了么？

**Comment by qiululu** [comment]
using the test code, there seems no problems. only in some very small sized ones it will have some slightly edge cuts. here's the picture:
<img width="231" alt="cutprob" src="https://cloud.githubusercontent.com/assets/5564318/8716338/8ad4931a-2bc2-11e5-8eff-82c2acf8b3d1.png">
<img width="230" alt="cutprob2" src="https://cloud.githubusercontent.com/assets/5564318/8716341/92f36116-2bc2-11e5-8a2c-52a8f6e216cf.png">

**Comment by pandamicro** [comment]
Duplicated with https://github.com/cocos2d/cocos2d-x/issues/9333
