### ISSUE TITLE
Text isn't drawn in version 3.6

### ISSUE THREAD

**Issue by TheCodez** [cocos2d/cocos2d-x#12166]
Labels are not drawn on 3.6 because of  jni not finding method createTextBitmapShadowStroke in Cocos2dxBitmap.java. The output is :
JniHelper: Failed to find static method id of createTextBitmapShadowStroke

It worked before this pr https://github.com/cocos2d/cocos2d-x/pull/11451
The error happened on a Samsung Galaxy S3.

**Comment by tizbecool** [comment]
I've got the same Error and checking that libcocos2djs.so and libcocos2dx.jar was well rebuild fixed the thing.

**Comment by TheCodez** [comment]
Indeed, it works. Thank you :+1:
