### ISSUE TITLE
RichTest in tableView no display

### ISSUE THREAD

**Issue by davewang** [cocos2d/cocos2d-x#12170]
RichTest in tableView no display
RichTest in tableView no display
RichTest in tableView no display
RichTest in tableView no display

**Comment by pandamicro** [comment]
Please give the exact way or sample code to reproduce the issue, the engine version, screen shot, otherwise we can't help to fix it

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@davewang
