### ISSUE TITLE
cocos2d-x js jsb getValueMapFromFile fails to load plist

### ISSUE THREAD

**Issue by araker** [cocos2d/cocos2d-x#12208]
Hello,

I'm trying to read a .plist file in the jsb version of cocos2d-x js, but I get a empty array back instead. I load the plist with

var test = jsb.fileUtils.getValueMapFromFile(res.ani_plist);
I've tried this on xcode with the simulator and on a device with the same result. When debugging I see that in CCFileUtilsApple.mm the dictionary in

ValueMap FileUtilsApple::getValueMapFromFile(const std::string& filename)
gets the correct values from the plist. The dictionary is then converted into a valueMap and send back to js. In the debugger I can't see if this valueMap is correctly filled, so either the valueMap gets filled incorrectly or something goes wrong when the sending the valueMap back to js. Either way, when using the remote debugger in firefox I see that a empty array is returned.

The plist itself has a correct syntax, it gets accepted when loading the plist and png into the spriteframeCache and the sprite frames are correctly saved in the cache as well. The plist was created in texture packer.

I've created a test project to demonstrate this behaviour. In the test project, press the button and look in the log.

You can download it here .. https://www.wetransfer.com/downloads/62db27dfb5c4befda4ee5f108e9d864620150604182240/93d936.

My environment is 
cocos2d-x js 3.6 
Xcode 6.3.2 
OS X 10.10.2 
Texture packer 3.7.1

**Comment by pandamicro** [comment]
I have tested it, it's in fact correctly loaded, but as the result is big, when you try to print it, it won't give you anything. But you can try to print:

```
var test = jsb.fileUtils.getValueMapFromFile("lvl_01_03_0_ani.plist");
cc.log("Result: " + test.frames["lvl_01_01_2_0_1_normal_talking_00.png"].frame);
```

You will see the result.

Oh, by the way, there is no value map in JS, we transform it to a JS object.

**Comment by araker** [comment]
Thanks for looking into this. Painful that I didn't log a few more values.

**Comment by pandamicro** [comment]
No problem
