### ISSUE TITLE
Enhance GameService crash in lolipop for targetSdk 21+

### ISSUE THREAD

**Issue by felixjingga** [cocos2d/cocos2d-x#12200]
one of the latest commit was an enhance gameservice.. if we're building against targetSdk 22 (lolipop), game will crash because of 

"Service Intent must be explicit: Intent { act=com.enhance.gameservice.IGameTuningService }"

**Comment by zilongshanren** [comment]
@felixjingga  Could you provide more info of this issue?  For example, the crash log and so on.
Thanks.

**Comment by felixjingga** [comment]
@andyque build using gradle, set the "targetSdkVersion" to 22, and then compile assembleRelease, and install the apk to the device.. It should be crash..

there are many reference to this crash,
http://stackoverflow.com/questions/26530565/android-5-0-l-service-intent-must-be-explicit
http://stackoverflow.com/questions/27842430/service-intent-must-be-explicit-intent
https://code.google.com/p/android-developer-preview/issues/detail?id=1247
https://commonsware.com/blog/2014/06/29/dealing-deprecations-bindservice.html

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12261
