### ISSUE TITLE
Wrong label spacing with outline enabled

### ISSUE THREAD

**Issue by AIGRIND-LLC** [cocos2d/cocos2d-x#12217]
If outline is enabled for the Label than spacing between the letters becomes expanded!
This bug noesn't actually allow to use outline feature because of big space overrun.
![outline-bug](https://cloud.githubusercontent.com/assets/6168693/8010772/6afb7d76-0bb3-11e5-9ddb-3e98403041b2.png)

**Comment by pandamicro** [comment]
@WenhaiLin Please explain the behavior and how to adjust

**Comment by stari4ek** [comment]
we have this "issue" (let's call it specific behavior) also.
currently, if outline is enabled, it changes letters spacing:

```
xAdvance += 2 * _outlineSize;
```

I'd expect, that it shouldn't happened by default. or it should be configurable
We've moved advance correction to `FontAtlas::prepareLetterDefinitions`

```
tempDef.xAdvance += fontTTf->getOutlineSize() * OutlineAdvanceMiltiplier;
```

Please note, that if advance is 0, letters will overlap each other, and probably this isn't good eighther

**Comment by AIGRIND-LLC** [comment]
@pandamicro You can reproduce it using Cocos Studio.
Just drop Label widget to the scene, assign any TTF font to it and adjust Outline Size property:
![outline-bug1](https://cloud.githubusercontent.com/assets/6168693/8036388/c7628bae-0df7-11e5-9e30-bd8b93d233a2.png)

**Comment by AIGRIND-LLC** [comment]
Probably the appropriate bechavior could be achieved by editing the following code in `FontFreeType::getGlyphBitmap()`

```
// xAdvance += 2 * _outlineSize;
xAdvance += _outlineSize; // fixed
```

**Comment by stari4ek** [comment]
minimizing influence of outline on letters spacing isn't a fix.
any extra value we add here, it _extra_ spacing, comparing to label without outline.

btw, here is an example of font rendering with disabled `xAdvance` correction (from another PR):
![image](https://cloud.githubusercontent.com/assets/327778/8038242/02d8760e-0e0b-11e5-862f-1fc8857af007.png)
compare "loading" with outline disabled:
![no_outline_loading](https://cloud.githubusercontent.com/assets/327778/8038296/4f56dff2-0e0b-11e5-9f2c-a3a98539f179.png)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12386

**Comment by stari4ek** [comment]
Works great. Thank You.
Checked on 3.5

**Comment by AIGRIND-LLC** [comment]
The problem is solved.
Thanks!
