### ISSUE TITLE
bug in CCDirector::runWithScene?

### ISSUE THREAD

**Issue by zhshuai1** [cocos2d/cocos2d-x#12229]
I'm a new hand in Cocos2dx, and I'm using the Cocos2dx-v2.2.6. When I call CCDirector::popScene or CCDirector::replaceScene, I got an runtime error, which says: "Assertion failed! in popScene or replaceScene m_pRunningScene!=0". And I go to runWithScene function, and found that the m_pRunningScene is not assigned, so I trie to add the expression: "m_pRunningScene=pScene;", and it works. So I just wonder whether it's a bug here, and if so, please fix it.
I'm using Visual Studio 2010 in windows 32 xp OS, and my code is as following:

```
CCScene *pScene = HelloWorld::scene();
CCScene *pTest=Test::scene();

pDirector->runWithScene(pTest);
pDirector->replaceScene(pScene);
pDirector->pushScene(Test::scene());
pDirector->pushScene(HelloWorld::scene());
pDirector->popScene();
```

**Comment by pandamicro** [comment]
If you are new to Cocos, please try our v3.x version, v2 is no longer in active maintenance. I believe there won't be such problem in v3.
