### ISSUE TITLE
cmake `option(BUILD_SHARED_LIBS ON)`

### ISSUE THREAD

**Issue by c0ffeeartc** [cocos2d/cocos2d-x#12227]
`libcocos2d.a` builds well, but building `libcocos2d.so` brings errors.

Is it possible to add branch to jenkins with `option(BUILD_SHARED_LIBS ON)`, or some other way to ensure it's built correctly?

**Comment by zilongshanren** [comment]
It could be possible to add `option(BUILD_SHARED_LIBS ON)` in Jenkins build, but we don't have the plan to support building shared cocos2d-x libs. If you could provide a PR, it will be welcome.

**Comment by minggo** [comment]
Yep, there is not plan to use shared library, so close this issue
