### ISSUE TITLE
Add music search path  not work in wp8.1

### ISSUE THREAD

**Issue by letzgame** [cocos2d/cocos2d-x#12228]
1.) put a music file name "test.wav" file to 'music' folder
2.) add  'music' folder to search path
3.) use SimpleAudioEngine to call playBackgroundMusic("test.wav"), the app crash.
3.1) call playBackgroundMusic("music/test.wav") , it works.

**Comment by stammen** [comment]
Which version of cocos2d-x are you using?

**Comment by letzgame** [comment]
cocos v3.6 c++

**Comment by stammen** [comment]
The v3 branch has the fix

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/audio/winrt/SimpleAudioEngine.cpp
