### ISSUE TITLE
CREATE_FUNC across the board

### ISSUE THREAD

**Issue by martell** [cocos2d/cocos2d-x#1223]
Hey guys Im' using cocos in a large game project atm.
I like how you changed everything to create.
but I have one issue with this
there are different #defines for different create funcs
eg. LAYER_CREATE_FUNC and SCENE_CREATE_FUNC

why not just have a CREATE_FUNC define because I looked at the headers and they are the same,

**Comment by minggo** [comment]
You are right.
I have created an issue for it: http://www.cocos2d-x.org/issues/1442.

Thank you.

**Comment by wandermyz** [comment]
I am curious why there is no NODE_CREATE_FUNC. 
I try to create some subclasses of CCNode. When I implement their "create" functions, I realize the code is exactly the same as LAYER_CREATE_FUNC and SCENE_CREATE_FUNC. So I wonder why there is no NODE_CREATE_FUNC, or just CREATE_FUNC for all CCObject. Did I miss some important considerations in memory management?

**Comment by martell** [comment]
Hey wandermyz,
That's pretty much why I created the issue. :)
I agree that CCObject would be a good place to have the CREATE_FUNC.

On another note using CREATE_FUNC takes away our ability to have arguments in the constructor so its not a one fit all solution and should only be used where necessary.

**Comment by jacklin1011** [comment]
may be this question is stupid, but i really don't understand what is create_func?is it equals to the singleton mode to create a instance?

**Comment by martell** [comment]
hi jacklin,

I basically gives you the option to avoid using the default constructor, with it you can put your startup code in the init function created.It makes your code look more like the rest of cocos giving you the create style constructor.

I dont quite understand what your trying to say in the second sentence but
It does not make the class a singleton.

Look in the cocos source if you want to know more

You dont really need it to be honest
Its only a #define

Hope that helps?

Martell

**Comment by jacklin1011** [comment]
thank you very much! i did some research and i found  CREATE_FUNC is the marco for the create function.it encapsulates the constructor and init and autorelease in it.so when i want to create the instance of my object i just need to write object::create(). the second setence about singleton is that when i want to port my project from cocos2d to cocos2d-x, i create a class like this:
.h:
@interface GameScreen : CCLayer {

}
- (GameScreen *) instance;

.m:
static GameScreen \* _instance = nil;
- (GameScreen *) instance {
  return _instance;
  }
  and i want to create this class in cpp. i'm kind of new to cpp,is there any simple example for doing this?

**Comment by martell** [comment]
a singleton is created by using a function that always returns the same instance of an object, usually a pointer to that instance in c++. eg CCApplication::sharedApplication();

I've never seen @interface in a header before. I know what an interface is just that must be objective c specific

**Comment by jacklin1011** [comment]
haha ,you are right. that's my objective-c code. thank you

**Comment by umesheklavyasharma** [comment]
Hello every1..... I want to create a game like nobwars on agame.com...... i however dont know how to use CCObject and how to use it's reference in gamelayer. If anybody can help me and give me some reference project it would be a great help.

Thanks in advance
