### ISSUE TITLE
Question regarding parsing an object in TMXXMLParser::startElement

### ISSUE THREAD

**Issue by Pouja** [cocos2d/cocos2d-x#12231]
While I was reading how a tmx file gets parsed, I came across this: [CCTMXXLParser.cpp](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCTMXXMLParser.cpp#L457).

I have 2 questions about that specific line of code:
- ~~Why are you taking the mapsize.y in the equation for calculating the y coordinate?~~ Already figured it out: It is because the y-zero is different for tiledmap and opengl.
- Shouldn't it be: `_mapSize.height * _tileSize.height - y  - objectGroup->getPositionOffset().y - attributeDict["height"].asInt()` instead of `_mapSize.height * _tileSize.height - y  - objectGroup->getPositionOffset().x - attributeDict["height"].asInt()`. So: taking the offset in y direction instead of the x direction, which makes more sense if I'm not mistaken.

**Comment by stevetranby** [comment]
Part 2 has been fixed in latest. Didn't check when it was fixed. Can probably close this ...
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCTMXXMLParser.cpp#L462

**Comment by Pouja** [comment]
Yup closing it
