### ISSUE TITLE
conversion problem in ActionTimeline::step

### ISSUE THREAD

**Issue by jicaixin** [cocos2d/cocos2d-x#12244]
My cocos2d-x version is 3.6, and CocosStudio version is 2.2.9

I have two different monster plist files, one works well but another was wrong.  I checked code in ActionTimeline.cpp and found my frame event was not triggered because you calculate a double value and then cast it to integer, my endFrame will be never triggered at all.

``` cpp
if(!_playing)
        {
            _time = _endFrame * _frameInternal;
            _currentFrame = (int)(_time / _frameInternal);
            stepToFrame(_currentFrame);
        }
```

My  _endFrame is 220 here, but after  code `(int)(_time / _frameInternal)`,  the result is 219.

And I think you make an unnecessary process, the result of `_endFrame * _frameInternal / _frameInternal` is `_endFrame`, why don't you write code like this `_currentFrame = _endFrame;`

I really feel 蛋疼.

**Comment by pandamicro** [comment]
@jicaixin Sorry for the issue, we have already a fix here: https://github.com/cocos2d/cocos2d-x/pull/12040/files
We will review it as soon as possible to make it right in the next version

**Comment by jicaixin** [comment]
Good job guys. 么么哒
