### ISSUE TITLE
[cocos new] fail to create a portrait project

### ISSUE THREAD

**Issue by letzgame** [cocos2d/cocos2d-x#12252]
steps:
1.) cocos new -p com.test.test -l cpp -d ~/Desktop/ --portrait  test
2.) logs from cocos console:
"> Copying cocos2d-x files...

> Rename project name from 'HelloCpp' to 'test'
> Replace the project name from 'HelloCpp' to 'test'
> Replace the project package name from 'org.cocos2dx.hellocpp' to 'com.test.test'
> Replace the mac bundle id from 'org.cocos2dx.hellocpp' to 'com.test.test'
> Replace the ios bundle id from 'org.cocos2dx.hellocpp' to 'com.test.test'
> WARNING: Can't find step change_orientation.
> "

**Comment by ppawlak** [comment]
Same problem here, using cocos2d js v3.6.1 and -l js option.
When I run the game on an iOS device it appears landscape.

**Comment by pandamicro** [comment]
The template project will be modified to support creating portrait project
