### ISSUE TITLE
js-tests about the animation API sample is too old, please update it

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12274]
I search the sample about play animation, only found:
src/CocoStudioTest/SceneTest/SceneEditorTest.js

``` js
ccs.actionManager.playActionByName();
```

It's too old, the new API is like this:

``` js
var node = ccs.load("res/Node.json");
this.addChild(node.node);
node.action.play("animation0", true);
node.node.runAction(node.action);
```

please update it.
cocos2d-x v3.6

**Comment by VisualSJ** [comment]
Hi @folgerhu 
The new interface only used to parsing that the new file.
Analytical old scene files, can not return to action objects.
So you must use ccs.actionManager.playActionByName

We do not recommend using this old version to export json files.
You can try to use the new version of Studio

SJ

**Comment by folgerhu** [comment]
@VisualSJ 
I understand what you mean, but i can't find out about the new API DEMO in js-tests, user can't study the new API in js-tests.
