### ISSUE TITLE
CppTests's textures disappeared after app push to/ pop from background on android.

### ISSUE THREAD

**Issue by yangws** [cocos2d/cocos2d-x#12279]
Env:
   Nexus 5 with andorid 4.4.4
Repreduct step:
1. enable "don't keep activity" in developer configrations
2. launch app, enter test case
3. push app to background
4. pop from background

bug1 is main menu, bug2 is "Player walk around in terrain" test case.
![bug1](https://cloud.githubusercontent.com/assets/488183/8078520/dfc41128-0f90-11e5-91d8-04bdfbb9d63e.png)
![bug2](https://cloud.githubusercontent.com/assets/488183/8078521/dff4a1d0-0f90-11e5-89d0-a7fe98711775.png)

**Comment by pandamicro** [comment]
I think @WenhaiLin is investigating this issue, please give some update about it, thank you

**Comment by yangws** [comment]
This bug isn't in v3 branch, report by mistake.
