### ISSUE TITLE
Bind utils::captureScreen to JSB and add web implementation

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12295]
- Review captureScreen API
- Bind in JSB
- Add web implementation

**Comment by IgorMats** [comment]
Can this be an async operation?

**Comment by pandamicro** [comment]
This is indeed a-synchronized, it will wait for the end of rendering during the current frame, then create the screen caption and invoke a callback.

**Comment by drelaptop** [comment]
JS bind issues years ago, close it.

> reopen if cocos2d-x(JS) developer concern this
