### ISSUE TITLE
spine动画修改着色器错位

### ISSUE THREAD

**Issue by fangjianh** [cocos2d/cocos2d-x#12317]
spine骨骼动画添加轮廓着色器后，显示图像错位

**Comment by pandamicro** [comment]
Please describe the following informations:
1. Exact steps to reproduce the issue.
2. Engine version.
3. Test environment, system, version, etc.
4. Correct behavior, observed behavior and screen captions of incorrect effect if possible.
5. Error message if there is any.
6. Call stack if there is a crash.
