### ISSUE TITLE
ListView in user Camera can't visible

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12311]
cocos2d-js v3.6

ListView in user Camera can't visible, if setClippingEnabled(false) then listview can visible. I suspect the problem in ui::Layout::visit.

Test code:

``` js
        //add a test sprite
        var testSprite = new cc.Sprite("res/Images/green_edit.png");
        testSprite.setPosition(300, 0)
        layer3D.addChild(testSprite);

        //add a listview
        var listView = ccui.ScrollView.create();
        listView.setDirection(ccui.ScrollView.DIR_VERTICAL);
        listView.setBounceEnabled(true);
        listView.setBackGroundImage("res/HelloWorld.png");
        listView.setBackGroundImageScale9Enabled(true);
        listView.setContentSize(240, 180);
        listView.setAnchorPoint(0.5, 0.5);
        listView.setPosition(480, 320);
        listView.setPosition3D(cc.math.vec3(0, 0, 0));
        layer3D.addChild(listView);

        for (var i=1; i<6; i++)
        {
            var testSprite = new cc.Sprite("res/Images/backtotoppressed.png");
            testSprite.setAnchorPoint(0, 0)
            testSprite.setPosition(20,40 * i);
            listView.addChild(testSprite);
        }

        //if setClippingEnabled(false) then listview can visible
        //listView.setClippingEnabled(false);

        var camera = cc.Camera.createPerspective(60, cc.winSize.width/cc.winSize.height, 1, 1000);
        camera.setCameraFlag(cc.CameraFlag.USER1);
        camera.setPosition3D(cc.math.vec3(0, 0, 550));
        layer3D.addChild(camera);

        layer3D.setCameraMask(cc.CameraFlag.USER1);
```

![screen shot 2015-06-12 at 2 32 47 pm](https://cloud.githubusercontent.com/assets/3455415/8124609/0abb5b22-1110-11e5-8ece-ed297d113d53.png)

**Comment by zilongshanren** [comment]
@super626  Could you have a look at this issue?

**Comment by super626** [comment]
@andyque 
Ok

**Comment by eonghk** [comment]
Same bug here, upgrade from 3.3 and it just happens. Working fine in 3.3. It's really annoying.

**Comment by eonghk** [comment]
@folgerhu Try this below, you may need to modify the header file yourself.

diff ui/UILayout.cpp ../../cocos2d-x-3.6-orig/cocos2d-x-3.6/cocos/ui/UILayout.cpp
1939,1946c1939
< 
< void Layout::setCameraMask(unsigned short mask, bool applyChildren){
<   Widget::setCameraMask(mask, applyChildren);
<   if (_clippingStencil){
<       _clippingStencil->setCameraMask(mask, applyChildren);
<   }
< }

## <

**Comment by super626** [comment]
@eonghk 
@folgerhu 
Thanks.

@eonghk  's  method does work.
