### ISSUE TITLE
NotificationNode with CCLabel with TTF,  Can let the program crashes!

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12315]
Using CCLabel with third party label font, if added to the NotificationNode, when program exits will crash!

Because the Director at the time of release calls to reset () method,  and there is no reset NotificationNode in this method, but it cleared all the freetype cache!

So when NotificationNode clean up itself, the label will clean up the font cache, but this time the font cache is empty pointer!

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12349
