### ISSUE TITLE
call glfwCreateWindow method failed ,return null

### ISSUE THREAD

**Issue by chenleijava** [cocos2d/cocos2d-x#12323]
on mac os, GLFWError #65544 Happen, NSGL: Failed to create OpenGL pixel format, the glfwCreateWindow return null. not found any Solutions in google !
cocos2dx version 3.6

**Comment by pandamicro** [comment]
@chenleijava Please tell us how to reproduce the issue ?

**Comment by chenleijava** [comment]
The strange thing is working well now! opengl version 4.1 .. ..   may next time ,i'll take it and offer to more detail . thanks @pandamicro

**Comment by pandamicro** [comment]
OK, thanks for the update
