### ISSUE TITLE
HttpRequest.h inline function uses deprecated API.

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#12335]
In HttpRequest.h:
function: [void HttpRequest::setResponseCallback(Ref\* pTarget, SEL_CallFuncND pSelector)](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/HttpRequest.h#L245) uses deprecated function [void HttpRequest::setResponseCallback(Ref\* pTarget, SEL_HttpResponse pSelector)](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/HttpRequest.h#L2550). This cause any cpp file includes "HttpRequest.h" will raise a deprecation warning.

To avoid this:
- Move `void HttpRequest::setResponseCallback(Ref* pTarget, SEL_CallFuncND pSelector)` implementation in to cpp file, 
- Or implements `void HttpRequest::setResponseCallback(Ref* pTarget, SEL_CallFuncND pSelector)` inline with non-deprecated API.

BTW, I suggest to check other headers.

**Comment by xpol** [comment]
@pandamicro 

This is very boring, just move these function body to cpp would fixes this.
Do it please!

Orz

**Comment by zilongshanren** [comment]
@xpol 
I think it's the best time for you to contribute :smile:

**Comment by xpol** [comment]
Here we go #14423

**Comment by minggo** [comment]
close it since #14423 is merged.
