### ISSUE TITLE
CocoStudio using TTFLabe  and enableShadow return opengl 0x0502 errors in cocos2dx 3.6 

### ISSUE THREAD

**Issue by wulei** [cocos2d/cocos2d-x#12343]
CocoStudio using TTFLabe  and enableShadow return errors in cocos2dx 3.6 

Error Log:
OpenGL error 0x0502 drawNumberOfQuads

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11696

**Comment by pandamicro** [comment]
Duplicated with: https://github.com/cocos2d/cocos2d-x/issues/11374
