### ISSUE TITLE
cocos2d-x 3.5 tizen not working

### ISSUE THREAD

**Issue by Seryusjj** [cocos2d/cocos2d-x#12347]
The cpp-tes project runs following the instrunctions but when creating a new project, libcocos2d compiles with out problems but where our Classes are sais the following when trying to compile:
Description Resource    Path    Location    Type
cannot find -lwebsockets    CocosProject            C/C++ Problem
make: **\* [hellocpp] Error 1    CocosProject            C/C++ Problem
recipe for target 'hellocpp' failed makefile    /CocosProject/Emulator  line 49 C/C++ Problem
skipping incompatible C:~\CocosProject\cocos2d\external\websockets\prebuilt\tizen\arm\libwebsockets.a when searching for -lwebsockets  CocosProject            C/C++ Problem

**Comment by WenhaiLin** [comment]
@sukwonsuh @QingliWang

**Comment by QingliWang** [comment]
/CocosProject/Emulator
Because you are building on "Emulator" mode,
please change the Platform Architecture to "X86".
Project->properties->C/C++ Build->Tizen Settings->Platform->Architecture
Thanks a lot.

**Comment by Seryusjj** [comment]
I'm already running both projects with architecture x86 
Platform Tizen 2.3
Architecture x86
Tolchain GCC -4.8
Thanks to you :+1:

**Comment by Seryusjj** [comment]
If setting active debug or release, with architecture ARMv7-a it compile (don't know if works because I dont have a fisical device), the problem just happend when trying to use the emulator. Thanks

**Comment by kompjoefriek** [comment]
@Seryusjj `Emulator` should be able to build for newly created `C++` and `Lua`projects.

**Comment by minggo** [comment]
Tizen implementation is updated  and merged into v3 branch, it will be included in v3.12. So close this issue.
