### ISSUE TITLE
CCTextureCache and ArmatureDataManager have race condition in async loading

### ISSUE THREAD

**Issue by jokerlee** [cocos2d/cocos2d-x#12370]
We capture some crash stacks of TextureCache and ArmatureDataManager from our ios game by Crashlytics. 
#### CCTextureCache

![qq20150617-1 2x](https://cloud.githubusercontent.com/assets/1501465/8201749/49a25f4e-1506-11e5-8dca-b15a7524af0b.png)

CCTextureCache's _textures member can be access by the async loading worker thread and be modified by the main thread concurrently which will cause race condition. I remove the existence checking in worker thread loadImage to work around this problem.
#### CCArmatureDataManager

![image](https://cloud.githubusercontent.com/assets/1501465/8185894/8810d126-1479-11e5-98fb-b1cc124712e3.png)

CCArmatureDataManager's _relativeDatas member (a unordered map) can be modified by the main thread (by ArmatureDataManager::addArmatureFileInfo) and the DataReaderHelper's worker thread (by DataReaderHelper::loadData) concurrently without locking which will cause the crash.

CCArmatureDataManager::addRelativeData, getRelativeData and removeArmatureFileInfo should acquire a mutex lock to avoid this problem.

```
void CCArmatureDataManager::addRelativeData(const std::string& configFilePath)
{
    _relativeDatasMutex.lock();
    if (_relativeDatas.find(configFilePath) == _relativeDatas.end())
    {
        _relativeDatas[configFilePath] = RelativeData();
    }
    _relativeDatasMutex.unlock();
}

RelativeData *CCArmatureDataManager::getRelativeData(const std::string&  configFilePath)
{
    _relativeDatasMutex.lock();
    RelativeData * ret = &_relativeDatas[configFilePath];
    _relativeDatasMutex.unlock();
    return ret;
}

void ArmatureDataManager::removeArmatureFileInfo(const std::string& configFilePath)
{
        ...
        _relativeDatasMutex.lock();
        _relativeDatas.erase(configFilePath);
        _relativeDatasMutex.unlock();
        DataReaderHelper::getInstance()->removeConfigFile(configFilePath);
}
```

**Comment by WenhaiLin** [comment]
@jokerlee The TextureCache::addImageAsync has been reimplemented by @yangws https://github.com/cocos2d/cocos2d-x/pull/12735

**Comment by pkxpp** [comment]
ex, ArmatureDataManager bug is also fixed?

**Comment by minggo** [comment]
Since cocos studio is canceled, so close this issue.
