### ISSUE TITLE
Android layout and cocos2dx layout

### ISSUE THREAD

**Issue by csaken** [cocos2d/cocos2d-x#124]
Hello,

I have tried to play a bit with cocos2d-x on Android platform, looks / works great. However, seems like there is something wrong with the layout on Android.
I have tried to add an android component over the cocos2 view, but seems like cocos2 is rotated from the Android layout, and because of this the text displayed in Android control is perpendicular to text displayed by cocos2dx.

I tracked down the code until CCDirector_mobile.cpp, where there are some rotations applied (in CCDirector::applyOrientation) depending on device orientation, and I'm wondering why they are applied.
Also, in CCDirector::getWinSize(void) seems like x,y is swapped in landscape mode.

I'm trying to figure out what is going on but I'm not sure why these transformations are applied.

I'd like to have the cocos2d in Portrait when Android layout is portrait, and in Landscape when layout is Landscape, and I'm not sure why those applied changes are there for.

**Comment by Macarse** [comment]
Can you provide some code to reproduce so it's easier to fix?
Thanks!

**Comment by walzer** [comment]
Well, this issue is hang too long. If you has any questions, please ask on http://forum.cocos2d-x.org

**Comment by csaken** [comment]
Sorry I was kind of busy with some other projects lately so I had no time to prepare a simple  code to reproduce the issue, although simulating it is kind of easy, just change in the java /xml code and the corresponding C++ code the layout at init code and you'll see the layout breaks between java and cocos2dx (can be best observed if you have something over or next to the opengl view itself - a place for advertising, some text, etc which is not rendered by cocos2dx but instead comes from the java side. I did not check if latest commits changed this behaviour
