### ISSUE TITLE
Use generational gc in SpiderMonkey

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12405]
The background of this feature: http://blogs.msdn.com/b/abhinaba/archive/2009/03/02/back-to-basics-generational-garbage-collection.aspx

This requires to adopt the new GC coding style in all JSB code.

The new GC coding style can be verified with this tool: https://github.com/joshuastray/RootAnalysis

**Comment by ricardoquesada** [comment]
Yes, we need to update the manual bindings.
The manual bindings are manually rooting many objects, from callbacks, to events... to everything.
So, if we want to get rid of the "retain/release" model, we have to review all the manual bindings as well.

**Comment by pandamicro** [comment]
One discussion to make JS::Rooted, JS::PersistentRooted and JS::Heap much more clear (especially what Boris Zbarsky said): 

https://groups.google.com/d/msg/mozilla.dev.tech.js-engine/2fmV2Y-eBuk/8wAKYs-gAm8J

I will complete the work in this issue.

Another useful demonstration here: http://trac.wildfiregames.com/wiki/JSRootingGuide

**Comment by ricardoquesada** [comment]
good info. thanks.

**Comment by minggo** [comment]
@pandamicro told me it is fixed, so close the issue.
