### ISSUE TITLE
Clone function of stroke and the shadow is invalid

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12406]
Cocos 2d-x v3.6

![11](https://cloud.githubusercontent.com/assets/3455415/8204832/2c865c4a-151e-11e5-879e-7a172e0d9d4b.png)

**Comment by WenhaiLin** [comment]
@pandamicro I think you'd better assign this issue to @andyque . thanks.

**Comment by AIGRIND-LLC** [comment]
Confirmed on v3.7
![clone](https://cloud.githubusercontent.com/assets/6168693/9087055/a2cf921e-3b88-11e5-9d80-8fa1764b9362.png)

**Comment by AIGRIND-LLC** [comment]
@pandamicro @zilongshanren what about this bug guys?
In v3.9 ui::Text can't still be completelly cloned.

**Comment by zilongshanren** [comment]
@AIGRIND-LLC 
It's fixed at v3.10

**Comment by zilongshanren** [comment]
https://github.com/cocos2d/cocos2d-x/pull/14639

**Comment by AIGRIND-LLC** [comment]
Great!
