### ISSUE TITLE
cpp-tests[ Lumia 830--WP8.1]:Material System-->Sprites with multiple meshes:Crash

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#12416]
error log：D3D11: Removing Device.

**Comment by WenhaiLin** [comment]
The response from MS Open Tech:

```
All of these tests are using the orc.c3b file. On some Windows Phones like the 830, the
rendering of the orc character crashes in Angle (the OpenGL to DirectX lib). The problem
is specifically with the Skin shader used by the character.
```

**Comment by fusijie** [comment]
It's a angel issue. @stammen Could you please take a look?

**Comment by stammen** [comment]
I am working with the Angle team on this issue. It won't be fixed for several weeks.

**Comment by stammen** [comment]
Update: The Angle team has fixed 2 of the 4 issues that were causing crashes. They are still working on fixing the problem. We should have a fix soon.

**Comment by drelaptop** [comment]
out-of-date windows phone issues, we didn't support this platform on newer release.
