### ISSUE TITLE
Particle Demo test crashes cpp-tests

### ISSUE THREAD

**Issue by SvDyer** [cocos2d/cocos2d-x#12413]
1. Run cpp-tests (reproduced on Win32 build and universal app)
   2, From the main menu go to Node: Particles
2. Tap on the left arrow to get to the Particle Demo test (you should see two Particle Emitters using different texture).
   4.Tap left/right arrow to move to another text - the app crashes

**Comment by stammen** [comment]
Please open an issue on the main cocos2d-x repo.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12473
