### ISSUE TITLE
Director::setClearColor(const Color4F& clearColor) have no effect.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#12426]
`version:` 3.7alpha
`issue:` Director::setClearColor(const Color4F& clearColor) have no effect. v3.6 is OK.
`reproduce:` add following code to HelloWorld project, init function.

``` cpp
    Director::getInstance()->setClearColor(Color4F::RED);
```

**Comment by zilongshanren** [comment]
@pandamicro  I think you'd better assign this issue to some other guys. thanks.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12507
