### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by zawasp** [cocos2d/cocos2d-x#12436]
With this commit 67d008810377a3cbad63f9af73beb02e8a1af297 I get a lot of IllegalArgumentExceptions for Android 2.3.3 - 2.3.7

`Caused by: java.lang.IllegalArgumentException: ALIGN_LEFT is not a constant in class android.text.Layout$Alignment
at java.lang.Enum.valueOf(Enum.java:176)
at android.text.Layout$Alignment.valueOf(Layout.java:1947)
at org.cocos2dx.lib.Cocos2dxBitmap.createTextBitmapShadowStroke(Cocos2dxBitmap.java:101)
... 5 more`

ALIGN_LEFT and ALIGN_RIGHT are not values of this enum (and never were, it seems):
http://developer.android.com/reference/android/text/Layout.Alignment.html

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12478
