### ISSUE TITLE
Suggest the log information in detail as far as possible

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12430]
Cocos2d-x v3.6

![](http://support.cocos.com//uploads/feedback/470346/a178d5c73933a3ad85b0ab7530a0b5a2.png)
This log information let me unable to know the specific path to the file.

UIScale9Sprite.cpp line 734, initWithSpriteFrameName of assert, suggest print spriteFrameName parameters.

**Comment by minggo** [comment]
fixed in #16191
