### ISSUE TITLE
Cpp-tests app crashes after opening Socket IO

### ISSUE THREAD

**Issue by SvDyer** [cocos2d/cocos2d-x#12439]
1. Build and run cpp-tests from v3 
2. From the main menu go to Extensions > Socket IO Test
3. Click on the Open SocketIO Client  and wait for a after a few seconds
4. Click Back and select another test - cpp-tests app crashes after about a second or two

(reproduced on Windows 10, and Windows 8.1 and Win32 platforms)

**Comment by man2** [comment]
maybe the socket.io callback has not been cleared when exiting the scene?

**Comment by himynameschris** [comment]
you need to disconnect any sockets opened during the test, otherwise you are correct, callbacks will happen on pointers that have been released. the test could easily be changed to force this to happen upon exiting the scene, but at the moment it relies on users to manually disconnect endpoints.

**Comment by minggo** [comment]
We haven't met the issue in the cpp-tests, so close this issue.
