### ISSUE TITLE
cpp-tests[ win8.1-universal--window 8.1]:Audio - CocosDenshion:Crash

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#12448]
@stammen Could you please take a look?

**Comment by stammen** [comment]
@WenhaiLin I will take a look

**Comment by WenhaiLin** [comment]
Crash cause by CreateMasteringVoice returns ERROR_NOT_FOUND. It's mean no default audio device exists and NULL is passed in as the szDeviceId parameter.

https://msdn.microsoft.com/en-us/library/windows/desktop/hh405048(v=vs.85).aspx

**Comment by stammen** [comment]
@WenhaiLin I tested CocosDenshion this morning on commit e0ea8a460a87c68e71adf133afee8fd3fe374a22 and it was working fine on the Windows Phone. Do you still have this issue with the latest code?

Also please restart the phone and see it that fixes the issue.

**Comment by WenhaiLin** [comment]
@stammen This issue only applies to window 8.1,not Window Phone.

**Comment by stammen** [comment]
@WenhaiLin What device are you testing on?

**Comment by WenhaiLin** [comment]
@stammen It's cause by the PC(desktop) not have any audio device.

**Comment by stammen** [comment]
@WenhaiLin So the crash occurs when there is no audio device installed on the PC?

**Comment by WenhaiLin** [comment]
@stammen Yes

**Comment by stammen** [comment]
@WenhaiLin Thanks for the update .I can reproduce the issue. We will fix this.

**Comment by stammen** [comment]
Opened issue https://github.com/MSOpenTech/cocos2d-x/issues/168

**Comment by stammen** [comment]
@WenhaiLin This is fixed in PR https://github.com/cocos2d/cocos2d-x/pull/12472
