### ISSUE TITLE
Capured image with RenderTexture loses quality

### ISSUE THREAD

**Issue by naghekyan** [cocos2d/cocos2d-x#12459]
I use this code to capture the screen and then I put the image a bit shifted down:

```
  const Size visibleSize = Director::getInstance()->getVisibleSize();
    Size screenSize = Director::getInstance()->getWinSize();

    auto rt = RenderTexture::create(screenSize.width, screenSize.height, Texture2D::PixelFormat::RGBA8888);
    rt->retain();
    rt->begin();
    m_ingameLayer->visit();
    rt->end();


    Sprite* normal2 = Sprite::createWithTexture(rt->getSprite()->getTexture());
    normal2->setAnchorPoint(Vec2::ANCHOR_MIDDLE);
    normal2->setPosition(Vec2(visibleSize.width * 0.5f, visibleSize.height* 0.45f));
    normal2->setFlippedY(true);
    removeAllChildren();
    addChild(normal2);
```

Here is the result of distortion: 
![capture](https://cloud.githubusercontent.com/assets/7469377/8254606/1020b526-16ab-11e5-853b-da6f088683c8.PNG)

Here is the related link: http://discuss.cocos2d-x.org/t/3-0-beta-2-rendertexture-stretching/11618/18

**Comment by semgilo** [comment]
@pandamicro how about the issue now?
@zilongshanren

**Comment by ricardoquesada** [comment]
strange... you are already using `Texture2D::PixelFormat::RGBA8888`... weird.

**Comment by IgorMats** [comment]
Same issue with my project!

**Comment by ShuraLiu** [comment]
I got the same problem with my project and I find this issue. Fortunately I found this page http://discuss.cocos2d-x.org/t/problem-with-ccrendertexture-and-image-quality/3916/3,  it gives the solution.
The I looked into the file CCRenderTexture.cpp, I think you can change _texture->setAliasTexParameters() to _texture->setAntiAliasTexParameters() in default. @minggo @ricardoquesada

**Comment by minggo** [comment]
@ShuraLiu sounds reasonable. Have you fixed it by changing it?

**Comment by ShuraLiu** [comment]
@minggo Yes, it works right now.

**Comment by minggo** [comment]
Why not send a PR?

**Comment by ShuraLiu** [comment]
here it is. It's my first pr, I'm not sure is it right, please help me checking it, thanks!

**Comment by minggo** [comment]
it looks good, thanks
