### ISSUE TITLE
cant generate js binding

### ISSUE THREAD

**Issue by man2** [cocos2d/cocos2d-x#12451]
when I run genbindings.py I got this error

can't open file '/Users/Documents/cocos/TestJS/frameworks/cocos2d-x/tools/bindings-generator/generator.py': [Errno 2] No such file or directory

**Comment by man2** [comment]
solved, I have to copy bindings-generator folder to tools. But it should be done automatically with the cocos tool

**Comment by pandamicro** [comment]
You should update the submodules, and run `download-deps.py`
