### ISSUE TITLE
Transition in the process of closing the simulator can lead to crush

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12483]
Cocos2d-x v3.6

``` cpp
void HelloWorld::onEnterTransitionDidFinish()
{
    Director::getInstance()->replaceScene( TransitionFade::create(2.0f, TestScene::scene()) );
}
```

If TestScene is in the transition, click the simulator close button, app can lead to crush:

> Assert failed: Node still marked as running on node destruction! Was base class onExit() called in derived class onExit() implementations?
> Assertion failed: (!_running), function ~Node, file /Users/chukong/Developer/mac-workspace/x36-test/cocos2d/cocos/2d/CCNode.cpp, line 212.

**Comment by pandamicro** [comment]
Duplicated with https://github.com/cocos2d/cocos2d-x/issues/10834
