### ISSUE TITLE
void PhysicsWorld::debugDraw() 当body都删除后body的绘制还在

### ISSUE THREAD

**Issue by xzben** [cocos2d/cocos2d-x#12486]
问题描述：
    在一个场景中增加开启DebugDraw 增加 PhysicsBody 后，删除全部 PhysicsBody 则绘制的所有 DebugDraw 会一直存在。
问题代码：
在 void PhysicsWorld::debugDraw() 中当在下次绘制前将全部body都删除后会导致 下么判断失败，则直接跳过了所有操作，这是时候应该把 debugDraw 中的 DrawNode 都clear 才对。 
    if (_debugDraw && !_bodies.empty())

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@xzben
