### ISSUE TITLE
Parse Touch/Click callback in JS Studio parser

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12489]

**Comment by pandamicro** [comment]
![screen shot 2015-06-23 at 5 20 17 pm](https://cloud.githubusercontent.com/assets/632460/8302981/1fdd838e-19cd-11e5-834f-e4721d10038b.png)

**Comment by zj8487** [comment]
is there any example to indicate how to use callback in js？
@pandamicro 
@VisualSJ

**Comment by pandamicro** [comment]
@VisualSJ Please add a test case for the callbacks

**Comment by zj8487** [comment]
when will the 3.7.1 be released?

**Comment by pandamicro** [comment]
About 8.11

**Comment by zj8487** [comment]
@VisualSJ is the testcase added? i don't find it! i really want to know how to use it!

**Comment by pandamicro** [comment]
@VisualSJ Please tell @zj8487 where the test case is and link related PR to this issue

**Comment by zj8487** [comment]
ping

**Comment by VisualSJ** [comment]
@zj8487 

![image](https://cloud.githubusercontent.com/assets/7113508/9266376/cfe6c286-4272-11e5-9b99-86b691081974.png)

![image](https://cloud.githubusercontent.com/assets/7113508/9266380/e7e47806-4272-11e5-902d-5c35fe5704af.png)

http://www.cocoachina.com/bbs/read.php?tid-318856.html

I'm so sorry for the long time to reply this.
