### ISSUE TITLE
ScrollView _childFocusCancelOffset should consider DPI

### ISSUE THREAD

**Issue by eonghk** [cocos2d/cocos2d-x#12493]
It's difficult to click a item in a listview in 2k screen phones.
The _childFocusCancelOffset should based on screen dpi like this:

bool ScrollView::init()
{
    if (Layout::init())
    {
        //mod,scale with dpi.
        int dpi = Device::getDPI();
        _childFocusCancelOffset = _childFocusCancelOffset \* dpi / 160;
        //end mod
        setClippingEnabled(true);
        _innerContainer->setTouchEnabled(false);
        return true;
    }
    return false;
}

**Comment by zilongshanren** [comment]
@eonghk  Yes, This issue will be fixed in v3.8.
you could hack the engine with https://github.com/cocos2d/cocos2d-x/pull/8948

**Comment by eonghk** [comment]
I have no problem with hacking. I know this problem since 3.3 and you guys say you fix it in 3.8. Is it tooooo long? Not everyone knows this place and knows how to locate the problem. I think you guys should really consider about a bug fix branch like the linux kernel. If there is a open bug fix branch 3.6.1, we can commit the fix and work around. No one need to wait until 3.8. It will be much easier for developer to use it. That's why we love open source.

**Comment by zilongshanren** [comment]
@eonghk Yep, I should fix it soon, I mean in v3.7, but the branching and release cycle is not determined by me. @walzer Toughts?

**Comment by zilongshanren** [comment]
@eonghk  fixed at https://github.com/cocos2d/cocos2d-x/pull/12537
