### ISSUE TITLE
Resources/Shaders/example_Blur.fsh is not OpenGL ES 2.0 compliant

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#12505]
The for loop in Resources/Shaders/example_Blur.fsh is not OpenGL ES 2.0 compliant and will not compile on some platforms that enforce the requirement that control flow be limited to forward branching and to loops where the maximum number of iterations can easily be determined at compile time. 

The use of the calculated value r from a uniform value means the maximum number of loop iterations cannot be known by the shader compiler. Angle for Windows 8.1 and 10 enforces this requirement. Other platforms may skip the for loop entirely without the compiler reporting an error.

The blur shader does the following:

uniform float blurRadius;
...
float r = blurRadius;
...
for(float x = -r; x < r; x += sampleStep) // error! compiler cannot unroll this loop 

The blur shader is not a correct GLSL shader.

See Appendix A section 4: Flow Control of the GLSL spec.

https://www.khronos.org/registry/gles/specs/2.0/GLSL_ES_Specification_1.0.17.pdf

**Comment by fusijie** [comment]
@stammen As we have tested, Win/Mac/iOS/Android is OK. I know the GLSL spec, but we need the blur effect controlled dynamically.

Is the shader compile requirement need by all windows 8.1 universal devices or angle? And will win10 support this feature?
