### ISSUE TITLE
Benefit from parallel project builds by decoupling framework into multiple libraries

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#12506]
Issue reported from zhihu

> 2.X已经觉得图形部分和基础部分写成一个工程已经很大了.到了3.X, 居然直接把所有东西都整合到一个工程里了. 这是懒吗? 殊不知, 包括VC在内的很多编译器都是以工程为并发编译的最小元素. 这么做完全不能利用CPU并发节约时间. 本来引擎bug多, 偶尔需要改下引擎, 动辄编译就很久. 这是要杀人的节奏啊...

Visual Studio supports `parallel project builds`, we can have a try and estimate how faster it can be.

**Comment by stammen** [comment]
Before you create a lot of new projects simply enable Multi-processor Compilation in the C++/General properties. When using msbuild add the /m option to the command line. We do this in the Windows 8.1 Universal App project and it builds may times faster than the Win32 project. Also, make sure the Win32 projects are using precompiled headers especially libcocos2d and cpp-tests.
