### ISSUE TITLE
iOS: ARC support

### ISSUE THREAD

**Issue by Shulepov** [cocos2d/cocos2d-x#12518]
Is it possible to add ARC support for generated project? I'm not asking for adding ARC support for cocos2d-x itself, just for game project. Many libraries require ARC support and i don't see any reason why it can't be added, at least as an additional option when starting new project.

It won't bring any performance issues as usually there are no any performance sensitive iOS code in the generated projects, just some bindings to libraries.

**Comment by Shulepov** [comment]
How would be better to implement this feature? 
- add new project folder, something like proj.ios_mac_arc
- use preprocessor definitions to check if ARC enabled:
  #if __has_feature(objc_arc)
  ...
  #else
  ...
  #endif

But with second approach it belongs to user to enable/disable ARC in project settings.

**Comment by minggo** [comment]
It is fixed.
