### ISSUE TITLE
Support Android Studio 1.3 for compilation and debugging C++

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12512]

**Comment by zilongshanren** [comment]
here is a few links:
- http://kvurd.com/blog/compiling-a-cpp-library-for-android-with-android-studio/
- http://arstechnica.com/gadgets/2015/05/good-news-for-game-devs-android-studio-1-3-supports-androids-cc-ndk/

**Comment by minggo** [comment]
We are adding support this feature in #15676, so close this issue.
