### ISSUE TITLE
A bug of editBox

### ISSUE THREAD

**Issue by RaoZiJian** [cocos2d/cocos2d-x#12519]
Cocos2d-x 3.3 with Lua
The `setMaxLength` is not available sometimes. It's not easy to describe and I would talk this to QuGuanghui.
And The way to fix it is modify the `UIEditBoxImpl-ios.mm` on `Line 236`
-     return newLength <= getEditBoxImplIOS()->getMaxLength();  // delete this line
-    return (newLength<=oldLength) || (newLength <= getEditBoxImplIOS()->getMaxLength());  //add this line

**Comment by zilongshanren** [comment]
http://blog.csdn.net/jasonblog/article/details/23771117
