### ISSUE TITLE
Downloader should use native HttpClient implementations

### ISSUE THREAD

**Issue by pandemosth** [cocos2d/cocos2d-x#12524]
We have native implementations of HttpClient now, which is great. But, AssetManager and Downloader still have a separate implementation that is dependant on libcurl, and this comes with its own ongoing bugs and issues.

Its confusing when scripting that `cc.loader.getXMLHttpRequest()` will use the native HttpClient and yet `cc.loader.loadImg(url, ...)` will not (since it is internally implemented using Downloader).

**Comment by pandamicro** [comment]
An issue have been created for removing libcurl dependency in Downloader: https://github.com/cocos2d/cocos2d-x/issues/10382
