### ISSUE TITLE
Merge JSB test project into cocos2d-x

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#12530]
This would reduce jenkins compile time dramatically.

**Comment by pandamicro** [comment]
@andyque Please help @jianglong0156 for platforms that he is not very familiar with.

**Comment by zilongshanren** [comment]
@pandamicro  ok , @jianglong0156  you could ask me anytime. But please finish this issue ASAP.
We need it to improve Jenkins build performance.
Thanks.

**Comment by jianglong0156** [comment]
ok. I will take this job as a first priority

**Comment by pandamicro** [comment]
Fixed via https://github.com/cocos2d/cocos2d-x/issues/12530
