### ISSUE TITLE
Label with outline crash on winRT

### ISSUE THREAD

**Issue by dakikifr** [cocos2d/cocos2d-x#12549]
I've found a bug playing with Labels, it only occurs on winRT (fine in iOS/Mac/Win32/Android).
It's only for specific glyphs, and specific fonts, and always when outline is enabled.

An example of such a crash can be make easily.
Create a new project using the cocos console (from cocos 3.3 up to current v4-develop version), and change the Label creation from HelloWorldScene.cpp to this:

auto label = Label::createWithTTF("e", std::string("fonts/intuitive.ttf"), 70);
label->enableOutline(Color4B::BLACK, 2);

Get the intuitive.ttf font here: https://drive.google.com/open?id=0B1_hJ_Q8mPOBcUVRTVRXUk96ZlE

Compile and run on a windows 8.1 computer using the win32-debug target of the win8.1-universal project.
As soon as the label is rendered, it crashs.
Not sure if it has an effect, but my desktop screen resolution is 1920*1080.

Thanks

**Comment by stammen** [comment]
It worked for me using cocos2d-x v3.7. Make sure you put the intuitive.ttf font in the Resources/fonts folder. Screen resolution is 1920 x 1080.

![image](https://cloud.githubusercontent.com/assets/1226490/8367541/221f653a-1b54-11e5-8308-c115a85785d4.png)

**Comment by dakikifr** [comment]
It works if I comment the outline command (the glyph is obviously not drawn with outline in this case), but does crash with the line.
In fact I extracted this sample from my whole game that I'm porting to windows phone, everything works fine on all platforms except all the 'e' glyphs for this font that crash.
If nobody produces this error on their computer, I'll give a call stack of the crash.
I managed to run the sample at the same time using win32 and win8.1 builds to compare, I'll give the crash line after a good night of sleep :)

**Comment by dakikifr** [comment]
I should add that I did only try v3.3 and v4.0, haven't try 3.7 yet but will do tomorrow

**Comment by dakikifr** [comment]
I've done some more tests:
3.3: Crash
3.5: Crash
3.6: OK
3.7-beta: OK
4.0-beta: Crash

So it seems the bug is fixed in current stable branch, but not in dev? Weird.
I didn't test 3.7 since I tested 3.3 and 4.0 (I thought that if the bug was fixed, it would be in devel branch too).

I'll investigate a little more, see if I can find anything

**Comment by dakikifr** [comment]
Also, it should be noted that the render is absolutly not the same between v3.7 and v3.6 (the 2 that works):

This is 3.6
![cap-3 6](https://cloud.githubusercontent.com/assets/4882169/8375272/136f8530-1bfc-11e5-8795-e885e8039d85.png)

and this is 3.7
![capt-3 7](https://cloud.githubusercontent.com/assets/4882169/8375280/231081ce-1bfc-11e5-9507-f8bfd520e192.png)

**Comment by dakikifr** [comment]
I just saw the 3.6 changelog and noticed freetype lib was upgraded to v2.5.5.
I guess it's the reason it's now working fine.

So my question is now:
Is there an easy way to upgrade freetype for my v3.3 project (not easy for me to upgrade to 3.6)??

And you might have a new issue in 3.7 like I described in my previous reply (glyph size changed btw 3.6 and 3.7beta)

(The only weird thing is that it perfectly works on pure win32 build)

**Comment by stammen** [comment]
You should be able to copy the freetype libs and include files from v3.6 to your v3.3 external folder and then rebuild. Please let me know if this works for you.

**Comment by dakikifr** [comment]
It worked (only tried Windows, not WindowsPhone), but I had to change the filename (freetype250.lib vs freetype.lib).
Not very convenient but better than nothing, and not straightforward for managing multiple projects.

I'll consider upgrading to 3.6 but I fear new bugs might arise (like the font size one with 3.7)

**Comment by dakikifr** [comment]
@stammen Should I close this issue now it has some answers for other ppl (and I got it fixed on my side by upgrading cocos version.. I lost some time but it was not that hard)?
Should I then open a new issue for the label size bug in 3.7 then?

**Comment by stammen** [comment]
Yes. Go ahead and close the issue and open a new one for the the label size.

**Comment by dakikifr** [comment]
As a reference, the label size bug: https://github.com/cocos2d/cocos2d-x/issues/12572
