### ISSUE TITLE
Request: add 'enable cascade color' option in CocosStudio

### ISSUE THREAD

**Issue by AIGRIND-LLC** [cocos2d/cocos2d-x#12548]
There is no any option available in CocosStudio which is equivalent of `Node::setCascadeColorEnabled(bool cascadeColorEnabled)` method in runtime.

![image](https://cloud.githubusercontent.com/assets/6168693/8366179/662083da-1b9b-11e5-8cf9-69bae1a2210b.png)

**Comment by man2** [comment]
+1 for this.. really important feature

**Comment by AIGRIND-LLC** [comment]
@pandamicro @chengstory 
So guys what about this feature? 
It looks like quite simple for implementation.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
