### ISSUE TITLE
WinRT: PreloadSoundEffect search path error

### ISSUE THREAD

**Issue by dakikifr** [cocos2d/cocos2d-x#12544]
Hi,

on winRT (checked from cocos3.3 to 3.6), there is a bug in the PreloadSoundEffect function that prevent it from find the sound resource if using FileUtils searchPaths.

My resources folder looks like this:
Resources/common
Resources/lowres
Resources/highres

In common, I store all resolution-independant files, and lowres/highres speaks for themselves.
During game init, I setup my search paths using FileUtils::getInstance()->setSearchPaths(searchPath);
I always add "common", then add either lowres or highres.

Problem is (winRT only, works fine on iOS/MacOS/Android/Win32), the PreloadSoundEffect function of winRT does not use the FileUtils searchpaths, it's only looking inside the base "Resources" folder.
(I try to load "sfx/effect.wav", on other platforms it correctly find it in "Resources/common/sfx/effect.wav" but on winRT it only search in "Resources/sfx/effect.wav").

**Comment by zilongshanren** [comment]
@daiki1003  Have you tried v3.7? I think it should be fixed now.

**Comment by dakikifr** [comment]
Like I said, I tried up to 3.6, but I'm currently stuck at 3.3 (too much work to upgrade).
I checked 3.7 quickly but the diff was quite big (new sound engine?). I was looking for a quick fix to cherry-pick :)

**Comment by zilongshanren** [comment]
@dakikifr  The PR is here: https://github.com/cocos2d/cocos2d-x/pull/10388

**Comment by zilongshanren** [comment]
@daiki1003  And also https://github.com/cocos2d/cocos2d-x/pull/10426
I forget to add `cocos2d` namespace in that PR.

**Comment by dakikifr** [comment]
Well thanks.
I used the search tool but couldn't find a matching issue on github.

**Comment by daiki1003** [comment]
@andyque Was it wrong mention to me? :)
