### ISSUE TITLE
Sprite3D::getAABBRecursively does not get AABB of Nodes with Sprite3d children

### ISSUE THREAD

**Issue by gykapur** [cocos2d/cocos2d-x#12551]
I needed to the bounding box of a sprite3d that I created that has children that are nodes, with Sprite3d children to those nodes (don't know why as I'm using someone else's fbx-conv converted .obj file and not a 3d whizz by any means). The current Sprite3d does not allow this use case (it assumes the Sprite3D only has Sprite3d objects with Sprite3d children.)

The following ugly modification (which adds a helper function to search node children) suffices for my use case to solve the issue, though it could obviously be cleaned up:

bool getAABBNodeChild(Node\* node, AABB& aabb) {
    bool retVal = false;
    const Vector<Node*>& children = node->getChildren();
    for (const auto& iter : children)
    {
        Sprite3D\* child = dynamic_cast<Sprite3D*>(iter);
        if (child)
        {
            aabb.merge(child->getAABBRecursively());
            retVal = true;
        }
        else {
            AABB childAABB;
            if (getAABBNodeChild(iter, childAABB)) {
                aabb.merge(childAABB);
                retVal = true;
            }
        }
    }
    return retVal;
}
AABB Sprite3D::getAABBRecursively()
{
    AABB aabb;
    const Vector<Node*>& children = getChildren();
    for (const auto& iter : children)
    {
        Sprite3D\* child = dynamic_cast<Sprite3D*>(iter);
        if(child)
        {
            aabb.merge(child->getAABBRecursively());
        }
        else {
            AABB childAABB;
            if (getAABBNodeChild(iter, childAABB)) {
                aabb.merge(childAABB);
            }
        }
    }
    aabb.merge(getAABB());
    return aabb;
}

**Comment by gykapur** [comment]
A sample obj file that generates this issue is located at: http://tf3dm.com/3d-model/hn48-flying-car-10381.html which will needed to be converted to a c3t file (and then persuant to bug https://github.com/cocos2d/cocos2d-x/issues/12546 will have to be reassigned clamping) This also might be an issue with fbx-conv as the original .obj file does not have this issue but the c3t does.

I can also send the c3t file, etc. via email if this helps.

**Comment by songchengjiang** [comment]
The issue has been fixed, your code is correct, or you can use the following code:

AABB Sprite3D::getAABBRecursivelyImp(Node *node)
{
    AABB aabb;
    for (auto iter : node->getChildren()){
        aabb.merge(getAABBRecursivelyImp(iter));
    }

```
Sprite3D *sprite3d = dynamic_cast<Sprite3D*>(node);
if (sprite3d)
    aabb.merge(sprite3d->getAABB());

return aabb;
```

}

AABB Sprite3D::getAABBRecursively()
{
    return getAABBRecursivelyImp(this);
}
