### ISSUE TITLE
Camera::project(const Vec3& src) method return the wrong Vec2::y value

### ISSUE THREAD

**Issue by yixiaoqingyuz** [cocos2d/cocos2d-x#12554]
cocos2d-x version is 3.6.
When i set the xoz as the ground,i found that the Camera::project(const Vec3& src) method returned a reverse Vec2::y value.

For example the Camera::LookAt(Vec3(0,0,0)) and the postion of the 3D node in the 3D world is (0,0,-400)(display on the top of the screen),so, the Camera::project(const Vec3& src) should return a Vec2::y that on the top of the screen( for example 800),but in fact,this method return a value that on the bottom of the screen( for example 50).

**Comment by fusijie** [comment]
@yixiaoqingyuz 

It's the camera created by yourself or the default one?

And what's the detail args of the camera if the camera is created by yourself?

**Comment by yixiaoqingyuz** [comment]
@fusijie 
I created the camera by myself,and the gound base on the xoz plane.
    Size vs = Director::getInstance()->getVisibleSize();
    mCamera3D = Camera::createPerspective(60, vs.width/vs.height, 0.1, 2600);
    mCamera3D->setCameraFlag(CameraFlag::USER1);
    mCamera3D->setPosition3D(Vec3(0, 978, 482));
    mCamera3D->lookAt(Vec3(0, 0, 50),Vec3(0, 0, -1));
    addChild(mCamera3D);

**Comment by fusijie** [comment]
please use this method: `Vec2 projectGL(const Vec3& src) const;`

`Vec2 project(const Vec3& src) const;`: Origin point at left top corner in screen-space.
`Vec2 projectGL(const Vec3& src) const;`: Origin point at left bottom corner in GL-screen-space.

so you get a reverse Vec2::y value...

**Comment by yixiaoqingyuz** [comment]
Thanks for your help!
Maybe change the name of these method to Consistent with the name of Touch::getLocationInView() and Touch::getLocation() will be better.

**Comment by fusijie** [comment]
ok, please close this issue.
thanks for your suggestion. @super626
