### ISSUE TITLE
Physics-enabled nodes are teleported during a scene transition.

### ISSUE THREAD

**Issue by trojanfoe** [cocos2d/cocos2d-x#12567]
When a scene transition is used to replace a scene, any physics-enabled nodes in the new scene are sometimes teleported to offscreen positions.  This is caused by `Node::updateTransformFromPhysics()`.

I worked around the issue by not loading sprites in `init` or `onEnter`, but did it in `onEnterTransitionDidFinish()` instead.

This is using v3.7 beta 0 (v3 branch).

See this article of the forum for more details: http://discuss.cocos2d-x.org/t/probable-teleport-physics-bug-related-to-scene-transitions/22333

**Comment by trojanfoe** [comment]
A possible detail that I missed from my initial report is that I had the main menu scene, that is performing the transition to the game scene, "auto start" as I was developing the game scene and didn't want to keep pressing the "Start Game" button.  This means that the transition is kicked off from the very first `update()` of the main menu scene, which might have some bearing on the issue, perhaps starting the transition before the first physics tick (I am guessing quite a bit here).

**Comment by jimrange** [comment]
I was able to reproduce this bug.
Code to do so found here: https://github.com/jimrange/cocos2dxPhysicsBug/tree/teleport
To reproduce:
**1)** Clone the above repo and checkout the branch teleport.
**2)** Run the project in Xcode with Cocos2d-x 3.7 rc0. 
**3)** Press the button in the bottom right corner of the MainMenuScene to transiton to the HelloWorldScene. 
**4)** In MainMenuScene.cpp, you can enable/disable USE_SCENE_TRANSITION to see the bug come and go.
**5)** in HelloWorldScene.cpp you can set/disable CALL_SETUP_IN_ON_ENTER_TRANSITION_DID_FINISH to see the workaround trojanfoe described.

Youtube video of the bug: http://youtu.be/52PAT8yYauA

When running the HelloWorldScene in the simulator, you can press the button in the lower right corner to reload the HelloWorldScene.

**Comment by trojanfoe** [comment]
Nice work Jim

**Comment by jimrange** [comment]
Hopefully this bug can be confirmed and added to 3.8. 
I think this is a critical bug since it results in strange and unexpected behavior, essentially making the physics wrapper unusable if scene transitions are used.

This bug might be related to https://github.com/cocos2d/cocos2d-x/issues/12691.

**Comment by jimrange** [comment]
@pandamicro Do you think this bug is a critical issue?

**Comment by pandamicro** [comment]
@jimrange @trojanfoe We are not focusing on Physics now, the plan to fix this issue will be scheduled to the next version. Sorry for the delay and inconvenient.

**Comment by rainfallljs** [comment]
I had the same problem.I tried "onEnterTransitionDidFinish" but did not work.

I'm using v3.8.1.
There is another problem,All the sprites with physics disappear if you call setAutoStep(false).
It words well when I use v3.6.

**Comment by rainfallljs** [comment]
@pandamicro Is this problem on schedule?

**Comment by TheCodez** [comment]
Another workaround for this bug is to add those lines at the end of your init function :

``` cpp
_physicsWorld->setAutoStep(false);
_physicsWorld->step(0.0f);
_physicsWorld->setAutoStep(true);
```

**Comment by pandamicro** [comment]
@jimrange I just tested v3.9 with the combination of physics objects and transition scene, I think this issue should have been fixed. Your test project also runs correctly with v3.9.

Should be related to https://github.com/cocos2d/cocos2d-x/pull/13923
