### ISSUE TITLE
CC_PLATFORM_WINDOWS in CCClippingNode.cpp for v2

### ISSUE THREAD

**Issue by litefeel** [cocos2d/cocos2d-x#12563]

**Comment by litefeel** [comment]
`CC_PLATFORM_WINDOWS`
at 
https://github.com/cocos2d/cocos2d-x/blob/v2/cocos2dx/misc_nodes/CCClippingNode.cpp#L275
https://github.com/cocos2d/cocos2d-x/blob/v2/cocos2dx/misc_nodes/CCClippingNode.cpp#L281
https://github.com/cocos2d/cocos2d-x/blob/v2/cocos2dx/misc_nodes/CCClippingNode.cpp#L317

it's `CC_PLATFORM_WIN32` ?

**Comment by pandamicro** [comment]
You are right, I think they are missed when refactoring the macros
https://github.com/cocos2d/cocos2d-x/blob/v2/cocos2dx/platform/CCPlatformConfig.h#L41

**Comment by minggo** [comment]
fixed in #16015
