### ISSUE TITLE
v3.7-beta createWithTTF label size bug

### ISSUE THREAD

**Issue by dakikifr** [cocos2d/cocos2d-x#12572]
Hi,

it looks like v3.7 introduced a bug in the label size for TTF **Label**, compared to all previous cocos versions, as seen on this screenshot showing side-by-side an empty project (tested on win32 and win8.1 desktop), left is cocos3.6, right is cocos3.7 beta up-to-date at commitID 9f32db91549e25581f8c14f5dd95e84216106ca7 )
![labelbug-3 7](https://cloud.githubusercontent.com/assets/4882169/8392043/227167f2-1cdc-11e5-8e9d-7cd81d000cf1.PNG)

As you can see, the size is not correct, breaking all current games using TTF fonts.

**Comment by zilongshanren** [comment]
@WenhaiLin please check this issue.

**Comment by WenhaiLin** [comment]
@dakikifr Hi,I can't reproduce this issue.
![20150629111319](https://cloud.githubusercontent.com/assets/5234286/8400437/f08e68d6-1e50-11e5-869d-1a14bb950f3b.png)
![_20150629112038](https://cloud.githubusercontent.com/assets/5234286/8400441/fa56cc0a-1e50-11e5-941b-04b4a1bb2374.png)

**Comment by dakikifr** [comment]
That's weird.
I simply checked out tag cocos2d-x-3.6, updated submodules and deps, then created a new project that I compiled.
Next I checked out latest v3 (commit iD provided in my original post), updated submodules and deps, created a new project and compiled.
I tried both win32 and win8.1 and got the issue.
If I find some time in the next couple hours I'll try to dual debug this, but I'd like to finish my windows port for the contest... Not sure I'll be able to finish it :(

**Comment by WenhaiLin** [comment]
This issue cause by https://github.com/cocos2d/cocos2d-x/pull/12201. It is not a bug.

**Comment by dakikifr** [comment]
Hum, I'll than make a new test and use the same appdelegate and helloworld Files, if it's ok I'll close this thanks

**Comment by dakikifr** [comment]
Ok good, I didn't notice a scaleFactor was applied. I expected the sprite to be scale too, since there is only one version of it (not a double sized, or half sized one).
Everything looks ok. I'll try my game using 3.7 then.
