### ISSUE TITLE
Missing RelativeBox Tests

### ISSUE THREAD

**Issue by Mazyod** [cocos2d/cocos2d-x#12573]
I can't seem to find any tests that implement `RelativeBox` convenience class.

**Comment by zilongshanren** [comment]
@Mazyod  It's missing in cpp-tests, I'll add them back in v3.8. Thanks.

**Comment by Mazyod** [comment]
Thanks, what do you mean "missing in cpp-tests"? Can I find them elsewhere? I am trying to learn about them.

**Comment by zilongshanren** [comment]
@Mazyod  `UILayoutTest_Layout_Relative_Location`  is a test for testing relative layout.
And `RelativeBox` is just a wrapper class for `Layout` with relative alignment.

There are currently no `RelativeBox` tests as you mentioned above. 

I mean I should add `RelativeBox` tests in cpp-tests in the future.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@Mazyod
