### ISSUE TITLE
v3.7-beta Label issue with shadow&outline

### ISSUE THREAD

**Issue by dakikifr** [cocos2d/cocos2d-x#12589]
Hi,

Labels (TTF) have an issue using v3.7 beta (v3 being at commit 85af18f6341d55a1e22f46cf0754fb167af22f49).
If you enable either shadow or outline, characters are not correctly displayed as see on this screenshot comparing v3.6 (top) and v3.7 (bottom) :
![buglabel](https://cloud.githubusercontent.com/assets/4882169/8406114/a02ce18e-1e59-11e5-8190-e48bd8ce23e1.PNG)

Some pixels are tunctated at the top, and chars are too tighly packed (see how 'r' is overlapping inside the outline of 'l').

You can simply reproduce by modifying the template project, replacing the label by this:
    auto label = Label::createWithTTF("Hello World", "fonts/Marker Felt.ttf", 70);
    label->setTextColor(Color4B(50, 50, 0, 255));
    label->enableShadow(Color4B::RED, Size(3, -3), 3);
    label->enableOutline(Color4B::WHITE, 3);

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12619

**Comment by dakikifr** [comment]
Is your commit fixing the char spacing too, or only the top being truncated?

**Comment by WenhaiLin** [comment]
@dakikifr The letter spacing should not be expanded with outline enabled.For more information : https://github.com/cocos2d/cocos2d-x/issues/12217

**Comment by WenhaiLin** [comment]
@dakikifr You can still change the space between characters by `Label::setAdditionalKerning`.

**Comment by dakikifr** [comment]
Thanks for the function, but my concern was about the default behaviour. Same code (if not deprecated) should not behave differently when changing cocos version.
In my bug report, we can see 2 bugs (or at least 1 visual bug and 1 change of behaviour):
- Glyphs truncated at the top (bug) which you seemed to have fixed (thanks)
- Glyphs spacing shorter and overlapping (bug or change of default behaviour)

**Comment by dakikifr** [comment]
Or maybe kerning was not correctly supported in previous cocos version for TTF fonts, I don't have this answer (and if it's the case, then the chars are now properly using kerning and so more tighly packed, and thus it's my job to change my code to behave like it pleases me).
But I don't think it's "normal" for glyphs to overlap their outlines

**Comment by dakikifr** [comment]
Oh I didn't see your answer with the link to the issue 12217. So it explains what I replied just above :)
So it's a change in the default behaviour and I'll now have to play with setAdditionalKerning. Thanks!

Please notify (and close) this issue when it's merged in v3.7, thanks!

**Comment by WenhaiLin** [comment]
@dakikifr Sorry to be slow replying. The letter spacing should not be expanded with outline enabled(References to Android,etc..). We need to change it today or in the future.

**Comment by dakikifr** [comment]
Isn't this already changed by commit from issue 12217, in v3.7 branch?
If so, then it has already been changed :D (and my screenshots show it has)
Anyway, I'll try with the setAdditionalKerning method, as soon as your  fix for top of glyphs being cropped is pushed in v3.7 (if not already)

**Comment by WenhaiLin** [comment]
@dakikifr The behavior of letter spacing is changed in v3.7 branch. The cropped issue have been fixed in v3.7 branch.

**Comment by dakikifr** [comment]
Thanks, I'll take a look and try to see how I can achieve my previous spacing using Label::setAdditionalKerning (maybe it's just outlineSize*2)
