### ISSUE TITLE
win8.1 crash when loading specific png file

### ISSUE THREAD

**Issue by dakikifr** [cocos2d/cocos2d-x#12592]
Using this png file: https://drive.google.com/open?id=0B1_hJ_Q8mPOBWWtzV3ZKUFhBNHc&authuser=0

and replacing the "HelloWorld.png" by "flare.png" in the template project
v3.5 and before: OK
v3.6 and 3.7 : crash

Only crashing on Win8.1-universal build.
Win32/ios/android/mac are all OK

Crash is in CCTexture2D.cpp, inside bool Texture2D::initWithImage(Image *image, PixelFormat format):
Line PixelFormat      renderFormat = image->getRenderFormat();
returns PixelFormat::NONE on win8.1, PixelFormat::RGB888 on other platforms.

This time it's sure, I won't make it for the contest :(

**Comment by stammen** [comment]
@andyque @pandamicro This is fixed in PR https://github.com/cocos2d/cocos2d-x/pull/12593

**Comment by dakikifr** [comment]
Does it mean I have to change the format of my PNG file, or your PR will fix the loading of my png?
If the former, to what (and how) should I convert the file?

**Comment by stammen** [comment]
The pull request fixes cocos2d-x to work with your png which appears to be in 64 bpp format.

**Comment by dakikifr** [comment]
hum ok thanks. I don't know why it's in 64bpp, I'll try to convert it to 32bbp instead and see if it's visually correct, so I don't have to wait for the PR.

Edit: I know why is was in 64bpp, because I can see some artefacts in only 32bpp (It's not that big of a deal for a windows phone, but I can clearly see it on a win desktop)
