### ISSUE TITLE
Label: outline color is affected by main label's color

### ISSUE THREAD

**Issue by stari4ek** [cocos2d/cocos2d-x#12590]
Main color of label affect's outline color: 
![outline_issue](https://cloud.githubusercontent.com/assets/327778/8407411/ffbaf982-1e6e-11e5-86fb-70c6205de8bd.png)
Expected:
![outline_issue_fixed](https://cloud.githubusercontent.com/assets/327778/8407396/e0d618e4-1e6e-11e5-93d5-12e1589d05f3.png)

**Comment by WenhaiLin** [comment]
@stari4ek Because to me,you are confusing the two color:the color of node and the text color of label.

**Comment by WenhaiLin** [comment]
@stari4ek Node:setColor: the color should affect to text color,outline color,shadow color.
Label:setTextColor: the text color of label and the color of node are not the same.

**Comment by stari4ek** [comment]
hm.
You're right. color of node messes with outline color.
Currently I'm checking it with LWF. When it's label is rendered:
- color of text is bypassed with node's color (come with vertex data)
- "u_textColor" uniform is WHITE (ffffffff)
- "u_effectColor" uniform is outline color

I was going to create PR, but probably It's more about LWF than cocos. But can You check next commit: https://github.com/stari4ek/cocos2d-x/commit/5e96e1834b706679d02677771ea4a4a4e3155645 please?

**Comment by stari4ek** [comment]
Checked LWF. You're right, It performs setColor. Will go deep with LWF.
Thank You
