### ISSUE TITLE
ADT Support is Ending

### ISSUE THREAD

**Issue by almostasleep** [cocos2d/cocos2d-x#12596]
Google is ending support for eclipse. What are your plans about this? http://www.androidpolice.com/2015/06/26/google-officially-ends-support-for-adt-with-eclipse-urges-android-developers-to-migrate-projects-to-android-studio/

**Comment by WenhaiLin** [comment]
Cocos2d-x has supported Android Studio.

**Comment by cy-zhang-lei** [comment]
If we are using Cocos2d-x V3.2, do we necessarily need to upgrade to a later version in order to migrating to Android studio ? Thank you.

**Comment by WenhaiLin** [comment]
@cy-zhang-lei I think you do not need to upgrade before the official launch of Android Studio 1.3 final  version. Android Studio 1.3 is a new version of the IDE with built-in support for the NDK.

**Comment by WenhaiLin** [comment]
@almostasleep Please close this issue.

**Comment by cy-zhang-lei** [comment]
Thank you very much :)
