### ISSUE TITLE
Add Vietnamese as an official supported language in cocos2d-x

### ISSUE THREAD

**Issue by tony-hoang999** [cocos2d/cocos2d-x#12605]
Dear cocos2d-x team,

I am writing to ask for an officially support from cocos2d-x for Vietnamese language.
I'm really appreciated

Thank you very much!

**Comment by zilongshanren** [comment]
Could you send a patch?

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@tony-hoang999
