### ISSUE TITLE
Engine support composite 2D/3D scene by moving UI and camera far away.

### ISSUE THREAD

**Issue by yangws** [cocos2d/cocos2d-x#12626]
Forum thread: http://discuss.cocos2d-x.org/t/found-bugs-when-composite-3d-2d-mixed-scene-by-moving-ui-and-the-camera-which-look-at-far-away/21907

@pandamicro 

This function seperated to several PRs, list below:
- [x] https://github.com/cocos2d/cocos2d-x/pull/12419
- [x] https://github.com/cocos2d/cocos2d-x/pull/12602 :bugfix https://github.com/cocos2d/cocos2d-x/pull/12711 , https://github.com/cocos2d/cocos2d-x/pull/13000
- [x] https://github.com/cocos2d/cocos2d-x/pull/12620
- [x] https://github.com/cocos2d/cocos2d-x/pull/12635

**Comment by yangws** [comment]
All PRs are done. 
@pandamicro

**Comment by pandamicro** [comment]
Thanks
