### ISSUE TITLE
Unable to get correct path from FileUtilsWin32::getWritablePath if it has Unicode symbols

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#12621]
FileUtilsWin32::getWritablePath uses SHGetFolderPathA, SHCreateDirectoryExA, GetModuleFileNameA, it looks like SHGetFolderPathW, SHCreateDirectoryExW, GetModuleFileNameW must be used instead.

**Comment by perminovVS** [comment]
Use this #11866
