### ISSUE TITLE
Add cc.director.setClearColor for the web engine

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12628]
Already done in Cpp: https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/CCDirector.cpp#L691
1. This feature should be supported by WebGL and Canvas renderer
2. Transparent color should be supported

WebGL sample code provided by @jwu 

```
this._contextOptions = {
        alpha: this.transparent,
        antialias: options.antialias,
        premultipliedAlpha: this.transparent && this.transparent !== 'notMultiplied',
        stencil: true,
        preserveDrawingBuffer: options.preserveDrawingBuffer
    };
var gl = this.view.getContext('webgl', this._contextOptions) || this.view.getContext('experimental-webgl', this._contextOptions);
```

**Comment by jareguo** [comment]
It seems like you should also change the hardcoded background color in `cc.Director.setGLDefaultValues`.

from

```
_p.setGLDefaultValues = function () {
    // ...
    cc._renderContext.clearColor(0.0, 0.0, 0.0, 1.0);
};
```

to

```
_p.setGLDefaultValues = function () {
    // ...
    cc._renderContext.clearColor(0.0, 0.0, 0.0, 0.0);
};
```

**Comment by pandamicro** [comment]
@jareguo Thanks !

**Comment by pandamicro** [comment]
@ZhangMenghe Please try to fix this issue

**Comment by ZhangMenghe** [comment]
2015/7/8
The issue was completed the and pulled request, waiting to be merged.
The PR links as below: 
https://github.com/cocos2d/cocos2d-html5/pull/2975#issuecomment-119526872
