### ISSUE TITLE
v3 branch jsb_cocos2dx_ui_auto.cpp breaks Win32. Windows 8.1 and Windows 10 builds

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#12632]
v3 branch

jsb_cocos2dx_ui_auto.cpp breaks Win32. Windows 8.1 and Windows 10 builds. hitTest is incorrect.

..\auto\jsb_cocos2dx_ui_auto.cpp(1691): error C2660: 'cocos2d::ui::Widget::hitTest' : function does not take 1 arguments

**Comment by pandamicro** [comment]
Hi, Dale, I confirmed, Widget's hitTest api do accept only one argument, the autobindings code shouldn't have any problem

**Comment by venetanji** [comment]
This breaks android too. I think this commit may be causing it:

https://github.com/cocos2d/cocos2d-x/commit/f8a5b1e18c071bb1bcc37c4dd273f93ee4d730ad#diff-b4f082f82b3fd911e648b8966b8353b0

**Comment by pandamicro** [comment]
It was because the auto bindings haven't been updated automatically for v3 branch, it have been fixed.
