### ISSUE TITLE
iOS: depth/stencil buffers attributes are ignored

### ISSUE THREAD

**Issue by stari4ek** [cocos2d/cocos2d-x#12645]
1. disable depth and stencil buffers: `GLView::setGLContextAttrs({8, 8, 8, 0, 0});` usually from `AppDelegate::initGLContextAttrs` 
2. `GLViewImpl::convertAttrs` checks for RGBA8888 and 24+8(depth+stencil) only
3. otherwise default will be used `kEAGLColorFormatRGB565`/`GL_DEPTH_COMPONENT16`

**Comment by minggo** [comment]
It is already fixed.
