### ISSUE TITLE
IndexBuffer::recreateVBO() generated buffer object is bound to GL_ARRAY_BUFFER

### ISSUE THREAD

**Issue by Jumes** [cocos2d/cocos2d-x#12655]
Hello, I found the code below in cocos2d-x-3.6, GL_ARRAY_BUFFER should be replaced with GL_ELEMENT_ARRAY_BUFFER

void IndexBuffer::recreateVBO() const
{
    CCLOG("come to foreground of IndexBuffer");
    glGenBuffers(1, &_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, _vbo);
    const void\* buffer = nullptr;
    if(isShadowCopyEnabled())
    {
        buffer = &_shadowCopy[0];
    }
    CCLOG("recreate IndexBuffer with size %d %d ", getSizePerIndex(), _indexNumber);
    glBufferData(GL_ARRAY_BUFFER, getSize(), buffer, _usage);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    if(!glIsBuffer(_vbo))
    {
        CCLOGERROR("recreate IndexBuffer Error");
    }
}

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@Jumes
