### ISSUE TITLE
LabelTTF:the letters slightly cut

### ISSUE THREAD

**Issue by jminht** [cocos2d/cocos2d-x#12666]
i'm using the cocos2dx v3.1.1.
i found the labelttf may slightly cut with some letters, especially "069".
as you may see, the upper one is from v3.6 and the performance is right.
the one below is from my project.
for some reason, i can't update the project to v3.6 immediately, i can only slowly compare the code and update my project.
So, which part of the code in the engine should i compare to solve the problem?
thanks a lot.
![labelfft](https://cloud.githubusercontent.com/assets/4132186/8494270/d909d4aa-2195-11e5-991d-6eb2cad67d85.png)

**Comment by WenhaiLin** [comment]
This issue may be fixed at https://github.com/cocos2d/cocos2d-x/pull/7770/files. I'm not sure 
I suggest you synchronize the following files from https://github.com/cocos2d/cocos2d-x:
CCFontAtlas.h and CCFontAtlas.cpp
CCFontFreeType.h and CCFontFreeType.cpp
CCLabel.h and CCLabel.cpp
CCLabelTextFormatter.h and CCLabelTextFormatter.cpp

**Comment by jminht** [comment]
@WenhaiLin 
thanks.
i've synchronized those files as you said, but the problem is still there.
with v3.1.1, the node draw and visit are:

```
virtual void draw(Renderer *renderer, const Mat4& transform, bool transformUpdated);
virtual void visit(Renderer *renderer, const Mat4& parentTransform, bool parentTransformUpdated);
```

but v3.6, it's turns to be:

```
virtual void draw(Renderer *renderer, const Mat4& transform, uint32_t flags);
virtual void visit(Renderer *renderer, const Mat4& parentTransform, uint32_t parentFlags);
```

i don't know whether the different params matters.

**Comment by jminht** [comment]
![diff](https://cloud.githubusercontent.com/assets/4132186/8496794/8eb4d606-21aa-11e5-8e0a-43211f1b8cfa.png)

@WenhaiLin 
the left is from v3.6 and the right is from my project.
i compare the screenshots in beyond compare.
the result seems that font in my project is a little bigger than the font in v3.6, so that the font in my proj appears to be slightly cut at the edge.
where can i check to track this issue?

**Comment by pandamicro** [comment]
Duplicated with https://github.com/cocos2d/cocos2d-x/issues/9333
