### ISSUE TITLE
v3.7rc0 Label setOpacity(0)

### ISSUE THREAD

**Issue by milos1290** [cocos2d/cocos2d-x#12687]
Label setOpacity(0) with enableShadow just removes color from characters leaving it black without hiding it.

**Comment by pandamicro** [comment]
You mean the shadow ?

**Comment by milos1290** [comment]
I'm not sure but letters are still visible only in black color.

**Comment by WenhaiLin** [comment]
@milos1290 Could you provide sample code for reproduce this issue?

**Comment by milos1290** [comment]
```
_distanceLabel = Label::createWithBMFont("font_bm.fnt", "0 m");
_distanceLabel->setPosition(_origin.x + _visibleSize.width / 2, _origin.y + _visibleSize.height / 2);
_distanceLabel->setAnchorPoint(Vec2::ANCHOR_MIDDLE_RIGHT);
_distanceLabel->setOpacity(0);
_distanceLabel->enableShadow(Color4B::BLACK, Size(1,-1),1);
addChild(_distanceLabel);
```

**Comment by WenhaiLin** [comment]
@milos1290 I can't reproduced this issue in v3.7rc0. This issue should be cause by https://github.com/cocos2d/cocos2d-x/pull/12718, not in version 3.7rc0.

**Comment by wefiends** [comment]
This is caused by `_isOpacityModifyRGB` not being set correctly, now that Label is not subclassing SpriteBatchNode (since #12718) . PNG textures need this set to true, otherwise the display color and alpha will not be set correctly.

This is a quick fix:

``` C++
void Label::alignText() {
/*** omitted ***/
_blendFunc = batchNode->getBlendFunc();
/** SET WHEN CREATING BATCHNODE **/
_isOpacityModifyRGB = batchNode->getTexture()->hasPremultipliedAlpha();       
batchNode->setAnchorPoint(Vec2::ANCHOR_TOP_LEFT);
batchNode->setPosition(Vec2::ZERO);
_batchNodes.pushBack(batchNode);
/*** omitted ***/
```

This will break if the font atlas has more than one texture and they don't all have the same premult value.

**Comment by WenhaiLin** [comment]
@wefiends Thank you. You needn't worry about "the font atlas has more than one texture and they don't all have the same premult value". 
Label with TTF may have more than one texture,but they have the same premult value.
Label with bitmap font only have one texture.
Label with char map only have one texture.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12914
