### ISSUE TITLE
segfault isFileExist on Mac

### ISSUE THREAD

**Issue by jonyrock** [cocos2d/cocos2d-x#12686]
Hi!

A simple call `FileUtils::getInstance()->isFileExist("cool/path.txt")` leads to a segfault on Mac OS X

I gonna investigate it by myself soon.

**Comment by folgerhu** [comment]
I test is in OSX with xcode6.4, Cocos2d-x v3.6：

``` cpp
   auto a = FileUtils::getInstance()->isFileExist("cool/path.txt"); //no file exist
    auto b = FileUtils::getInstance()->isFileExist("fonts/arial.ttf"); //exist file
```

Program is running normally,  console out put:

```
cocos2d: fullPathForFilename: No file found at cool/path.txt. Possible missing file.
```

**Comment by jonyrock** [comment]
Sorry guys, I gonna close it. 
I will reopen it if find it in the last version.
