### ISSUE TITLE
UILayout viewing area cutting position calculation error

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12692]
Cocos2d-x v3.6

![2a1b630de0d747e8111bce23810dccce](https://cloud.githubusercontent.com/assets/3455415/8518237/c44e7a9a-23fa-11e5-9a69-0dfbefbd8dbc.png)

If UIListView setClippingType for the SCISSOR, and it has a listview item also set the SCISSOR, listview display will go wrong.

**Comment by semgilo** [comment]
I try to fix bug by the way, but it doesnt work?why ?whien i set the scrollview clippingtype 1
![image](https://cloud.githubusercontent.com/assets/7121873/9713305/2fb526e4-5583-11e5-95e9-4a619f55af6b.png)

**Comment by semgilo** [comment]
Cocos2dx 3.6   window 7

**Comment by zilongshanren** [comment]
@yangws  please take a look at this.

**Comment by semgilo** [comment]
normal state
![image](https://cloud.githubusercontent.com/assets/7121873/9713436/ec418bcc-5583-11e5-922f-c3269487bf3f.png)
