### ISSUE TITLE
ClippingNode does not support Scale9Sprite in some platform

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12753]
Cocos2d-x v3.6

``` cpp
    auto win_size = Director::getInstance()->getWinSize();
    auto stencil = cocos2d::ui::Scale9Sprite::create("CloseNormal.png");
    stencil->ignoreAnchorPointForPosition(false);
    stencil->setAnchorPoint(Vec2::ANCHOR_MIDDLE);
    stencil->setScale(2.0f);
    stencil->setPosition(Vec2::ZERO);


    auto clipping = ClippingNode::create();
    clipping->setStencil(stencil);
    clipping->setInverted(true);
    clipping->setAlphaThreshold(0.5f);
    clipping->setPosition(win_size/2);
    addChild(clipping);

    auto content = Sprite::create("HelloWorld.png");
    content->setPosition(Vec2::ZERO);

    clipping->addChild(content);
```

Display the results on Linux is ok,  on android, ios is wrong:

![img_0357](https://cloud.githubusercontent.com/assets/3455415/8587067/b3411218-2629-11e5-93c9-9716af4483ae.jpg)

**Comment by zilongshanren** [comment]
I think this issue wrongly reported.
I just close it here. Feel free to reopen.

**Comment by Shulepov** [comment]
Actually this issue appeared again after rewriting Scale9Sprite with 1 inner sprite.
The reason of this issue is when we set scale9sprite->setGLProgram - it actually do nothing. Inner renderer not added as child as well, so recursive setting of glprogram also do nothing (approach of CCClippingNode).

Should be done:

```
   void Scale9Sprite::setGLProgram(GLProgram *glprogram) {
        if (_scale9Image) {
            _scale9Image->setGLProgram(glprogram);
        }
    }
```

**Comment by zilongshanren** [comment]
@Shulepov 
Thanks, I will fix it later.
