### ISSUE TITLE
Node::scheduleUpdate() is missing in lua-binding

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#12771]

**Comment by pandamicro** [comment]
Lua have an API : scheduleUpdateWithPriorityLua

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/lua-bindings/manual/cocos2d/lua_cocos2dx_manual.cpp#L5062

maybe this is what you are looking for

**Comment by minggo** [comment]
It is not the same.
`Node::scheduleUpdatePriorityLua()`: 
1. make `Node::update()` in enabled
2. it will invoke a lua function passed to `scheduleUpdatePriorityLua()`

And `Node::scheduleUpdate()` is just do step 1.

**Comment by minggo** [comment]
This function is not important for pure lua games. But it is needed when mixing use lua and c++, for example:
- create a Node in lua
- want to Node::update be enabled then all its components will be looped

**Comment by lisikuangxiangqu** [comment]
11

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@minggo @lisikuangxiangqu @pandamicro
