### ISSUE TITLE
Set Label with text definition then setSystemFontSize won't have effect

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12784]
Code to reproduce the issue.

```
    Color3B tintColorRed(  255, 0, 0   );
    Size shadowOffset(12.0, 12.0);

    FontDefinition shadowTextDef;
    shadowTextDef._fontSize = 10;
    shadowTextDef._fontName = std::string("Marker Felt");

    shadowTextDef._shadow._shadowEnabled = true;
    shadowTextDef._shadow._shadowOffset  = shadowOffset;
    shadowTextDef._shadow._shadowOpacity = 1.0;
    shadowTextDef._shadow._shadowBlur    = 1.0;
    shadowTextDef._fontFillColor   = tintColorRed;

    // shadow only label
    auto fontShadow = cocos2d::Label::create();
    fontShadow->setString("Shadow Only Red Text");
    fontShadow->setFontDefinition(shadowTextDef);

    fontShadow->setSystemFontSize(70);
```

Correct effect, the label should be very large in size 70.
But the label will be shown in size 10

**Comment by WenhaiLin** [comment]
@qiululu This issue should be fixed at https://github.com/cocos2d/cocos2d-x/pull/12828. Please verify that.

**Comment by qiululu** [comment]
maybe the bug has already been fixed?  now it works correct

**Comment by qiululu** [comment]
checking out the latest version of the code , it appears no problems. see the picture:
<img width="695" alt="98217b07-1eae-40ad-8bc6-d5373ef5fb11" src="https://cloud.githubusercontent.com/assets/5564318/8769552/33c76c6a-2ed2-11e5-8c91-139d7b6b7354.png">
