### ISSUE TITLE
Canvas transform calculation issue

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12787]
Originally reported: https://github.com/cocos2d/cocos2d-js/issues/1781 by @Dolaham

@ZhangMenghe Please confirm this issue.

> For example:
> If you have 3 sprites: a, b, c.
> a is b's parent. b is c's parent.
> set b's scaleX to -1. then set a's rotation to some value nonzero.
> The visual layout is fine in WebGL mode, but totally wrong in canvas.
> I have to run my game in IE.
> Please help to fix this problem. I will be appreciative。

**Comment by ZhangMenghe** [comment]
I wrote a test case based on the newest version but haven't yet found any difference effect between canvas and WebGL,could you please give more information?

**Comment by ZhangMenghe** [comment]
I wrote a test case based on the newest version but haven't yet found any difference effect between canvas and WebGL,could you please give more information? @Dolaham

**Comment by pandamicro** [comment]
@Dolaham can you confirm it ? How to reproduce this issue

**Comment by pandamicro** [comment]
I will close this issue for now, @Dolaham if you have any further information, you can tell us and reopen it .
