### ISSUE TITLE
moving SpritePolygon::triangulate / calculateUV to DrawNode

### ISSUE THREAD

**Issue by dionysiusmarquis** [cocos2d/cocos2d-x#12795]
I would like to know if its possible to move/add the triangulate and calculateUV functions of SpritePolygon to the DrawNode. I'd like to use this functions for a SVG parsed Polygon. The polygon needs to get tessellated and UVs would be handy for custom FragmentShader.

**Comment by fusijie** [comment]
@dionysiusmarquis We remove SpritePolygon and add a helper class `AutoPolygon` to integrate to Sprite. I don't have any idea about why to `move/add the triangulate and calculateUV functions of SpritePolygon to the DrawNode`...

**Comment by dionysiusmarquis** [comment]
@fusijie Helper class sounds great. My intention was to be able to use the `triangulate` and `UV creation` functionality outside `SpritePolygon`. I just realized that `PolygonSprite` don't extend `DrawNode` so it's indeed not practical to move it there.

**Comment by fusijie** [comment]
@dionysiusmarquis er... Although it is a helper class, I think it would not meets your needs. The purpose of AutoPolygon is to serve the polygon sprite. But you can do any thing you like, It's a free engine, happy hacking. If you have any problems, please contact with me. lol

**Comment by dionysiusmarquis** [comment]
@fusijie Mhm... ok I'm extending `PolySprite` right now. It's maybe not that bad because it would provide a way to support svg image fills as well. Will the `PolySprite` class functions survive and remain accessible in any kind?

**Comment by fusijie** [comment]
Let me show you some code. The usage of polygon sprite:

``` cpp
    auto pinfo = AutoPolygon::generatePolygon("filename.png");
    auto spp = Sprite::create(pinfo);
```

**Comment by dionysiusmarquis** [comment]
Ok, I'll see. Thank you so far!
