### ISSUE TITLE
Are you killing the support for Box2d Physics engine?

### ISSUE THREAD

**Issue by minemilk** [cocos2d/cocos2d-x#12803]
I am making a game for linux , windows and  mac, but my main aim was linux for the upcoming steam os. I don't see a good tutorial on setting up the project in linux and compiling for linux platform so I used clion, everything works fine but not on windows which I had to use visual studio which is so slow when building. my project compile fine, as I am about to start my journey in Physics game, and tried using Box2d but failed to integrate it.

Are you killing the support for Box2d as physics engine in the future? its seems that the default enabled physics engine for the engine is chipmunk, and currently you have this Physics engine which is based on chipmunk also, which also has a good documentation. 

I can't enable box2d since it would cause so many compile error.  I thought Box2d was enable already and just ready for me to include since in your documentation it was not stated. Please help me on this one.

I using clion on ubuntu for editing and compiling for linux
and visual studio for windows. currently can't do mac. to expensive

**Comment by kompjoefriek** [comment]
This seems to be related to issue #12724.

I have no experience with Box2d myself, but maybe these forum posts can help you out:
- [Box2d on Linux](http://discuss.cocos2d-x.org/t/cocos2d-v-3-how-to-enable-box2d/15597/5)
- [Box2d on Windows](http://discuss.cocos2d-x.org/t/box2d-questions-and-set-cc-enable-box2d-integration-1-in-testcpp/18489/2)

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@minemilk
