### ISSUE TITLE
cocostudios/CocoStudio.h Too many include problems

### ISSUE THREAD

**Issue by jorovipe97** [cocos2d/cocos2d-x#12820]
I did a scene with Cocos Studio later I export it as **.csb** file, all right for now. The problem appear when I try to use the **.csb** file into the code, I am use the following code for import the scene.

``` c++
#include "editor-support/cocostudio/CocoStudio.h"

// put where you want add your cocos studio project
Node *rootNode = CSLoader::createNode( "Filepath to .csb file" );
this->addChild( rootNode );
```

...But when I try this on the terminal:

``` bash
cocos run -p linux
```

I see that in: **CocoStudio.h** not can include the **"cocostudio/CCActionFrame.h"** and all the others includes that have it the **cocostudio/** prefix, and this prevent the game to be compiled :rage: 
### Notes:
- I am on Ubuntu 14.04
- I am using cocos2d-x-3.6
- I am using c++ as language
- Sorry for my english :expressionless:
- This not work for me: #8163

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
