### ISSUE TITLE
[android]Cocos2dxBitmap.java divideStringWithMaxWidth() has a missing leading text bug

### ISSUE THREAD

**Issue by smilingpoplar** [cocos2d/cocos2d-x#1283]
I use cocos2d-x 2.0.x on android, the multiline CCLabelTTF missing a first letter whenever it start a new line.  
Test code:

```
CCLabelTTF* pLabel = CCLabelTTF::create("12345678901234567890", "Arial", 15, CCSizeMake(50, 0),
                                        kCCTextAlignmentLeft, kCCVerticalTextAlignmentCenter);
```

I examine Cocos2dxBitmap:: divideStringWithMaxWidth, and change 

```
while(content.indexOf(i++) == ' ') {
}
```

to

```
while(i < charLength && content.charAt(i) == ' ') {
    i++;
}
```

It should works.

**Comment by xeroo** [comment]
I've got this too, already posted here http://www.cocos2d-x.org/boards/6/topics/18347?r=18432
