### ISSUE TITLE
cc.textureCache.addImageAsync is not fully asynchronous

### ISSUE THREAD

**Issue by 0xJimmyBeh** [cocos2d/cocos2d-x#12857]
Currently we have cc.textureCache.addImageAsync to load online image with url which is async.

But after downloaded image, it will invoke Image::initWithImageData to create the texture which will blocking the main thread and cause freeze.

Thus, the whole process is not fully asynchronous as Image::initWithImageData is synchronous.

In this case, i would like to request implementation of Image::initWithImageDataAsync to make the loading image process fully asynchronous.

The original issue cc.textureCache.addImageAsync is at here :
https://github.com/cocos2d/cocos2d-js/issues/1217

From @pandamicro 

> Do we must invoke Image::initWithImageData after the image data downloaded to buffer?

For image data downloaded to buffer, yes.
For image downloaded to file, no, we can use other APIs.

> Why the frozen issue is not happen on Mac but only Android and iOS?

CCImage implementation is in the platform folder, so it's platform related and its performance may vary between different platforms

Thanks.

**Comment by man2** [comment]
any updates on this?

**Comment by pandamicro** [comment]
Hi, in the current implementation, initWithImageData is already in the download thread and asynchronous.

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/manual/extension/jsb_cocos2dx_extension_manual.cpp#L971

**Comment by 0xJimmyBeh** [comment]
@pandamicro 
If it is asynchronous, why it still freeze the app when the image downloaded on iOS and Android?
I created a sprite on the `cc.textureCache.addImageAsync` callback.

The app will freeze awhile before the sprite shown.

> cc.textureCache.addImageAsync(imageUrl, this.imageDownloaded, this);
> 
> imageDownloaded : function(texture)
> var image = new cc.Sprite(texture);

I remember you told me that CCImage is in the platform folder. So different platform might have different performance.

But if it run asynchronous which is on another thread, it shouldn't block the main thread which caused the app freeze.

Thanks.

**Comment by pandamicro** [comment]
Indeed it shouldn't, are you sure it's freezing ? or just nothing is changing ?

Besides, we refactored the native implementation of `cc.textureCache.addImageAsync` to improve the multithread logic, can you try out the latest version on github ?

**Comment by 0xJimmyBeh** [comment]
Do you mean this fix? I already applied this fixed into v3.7.
https://github.com/cocos2d/cocos2d-x/pull/12735

The freeze is in the callback of `cc.textureCache.addImageAsync`

I'm creating a cc.Sprite with the return texture2D in the callback.
Suppose the function should create the cc.Sprite async but it do have minor freeze in iOS and Android.

The freeze become noticeable when calling `cc.textureCache.addImageAsync` multiple time to download different image.

In this case, it can't considered fully async unless we don't use the return texture2D. But that should not the purpose to use `cc.textureCache.addImageAsync` if we don't want the image.

There are some issues on iOS.
The app will crash when `cc.textureCache.addImageAsync` downloading image and we change scene or received low memory.

I suspect the textured2D is released because sometime the cc.Sprite would be a black sprite.

Then i think to create the image in device local storage in order to avoid download the same image with `cc.RenderTexture` but sometime it will caused crash too when changing scene and it freeze the app. The crash happen on iOS only. But the image created by `cc.RenderTexture` is far larger than the original image in size, 50KB image can become 300-500KB for a jpeg image in iOS and Android but not Mac.
https://github.com/cocos2d/cocos2d-x/issues/13054

I would like to request the implementation of caching the image in device local storage as `cc.textureCache.addImageAsyncAndCache`.

The process flow would be : 
1. Download the image
2. Create the image after downloaded
3. Load the image and return texture2D

Then user don't have to keep download the same image and save disk space on the image caching.

Thanks for your time and effort.

**Comment by pandamicro** [comment]
> The freeze is in the callback of cc.textureCache.addImageAsync

If the freeze is happening in your callback, you need to investigate into its implementation.］

> I would like to request the implementation of caching the image in device local storage as cc.textureCache.addImageAsyncAndCache.

About this, we will probably refine Downloader API to support your need: https://github.com/cocos2d/cocos2d-x/issues/10382, user can do the following:
1. User can download a file (sync or async) with Downloader
2. Use `cc.textureCache.addImageAsync` to add a texture

What do you think ?

**Comment by 0xJimmyBeh** [comment]
> For the freeze in callback, i tested by keep scrolling the layer with
1. Do nothing in the callback, very slightly freeze < 1s
2. Create a `cc.Sprite` with the texture, slightly freeze when the image shown in the layer. 
   Freeze become longer like 1-2s when downloading multiple image together, for example, 10 images.
3. Create a `cc.Sprite` and cache the image with `cc.RenderTexture`, freeze > 2s. I think write to disk take long time and block the main thread.

When at the freeze moment or just before freeze moment, if i click a button which trigger a moveTo action, the moveTo position will become abnormal.

Node original position cc.p(leftBorderOfScreen, 0);
`cc.moveTo(1.0, cc.p(centerOfScreen, 0));` moveTo position
`cc.moveTo(1.0, cc.p(rightBorderOfScreen, 0));` abnormal position

`cc.textureCache.addImageAsync` should not freeze at all to avoid interrupt user using the app while waiting the image to load.

> About the crash of cc.textureCache.addImageAsync when changing scene

The crash is only happen in iOS device but not simulator, Mac or Android.

I try to use `cc.sys.isObjectValid(texture)` to check the texture before creating the `cc.Sprite`.
It do reduce the chance of crash but do not completely avoid the crash.

The crash should caused by the memory management of the engine.
If waiting all the cc.textureCache.addImageAsync to completed the download and create the `cc.Sprite`,
changing scene would not crash the app.

Do you have any idea to avoid the crash?

> refine Downloader API

I do agree on your suggestion to unified the download function.

It can avoid multiple functions doing the same thing and easier for maintenance and update.
Too many functions would confuse developer.

> 1. User can download a file (sync or async) with Downloader
> 2. Use cc.textureCache.addImageAsync to add a texture

Does the flow work as
1. Downloader download the image
2. Downloader invoke cc.textureCache.addImageAsync in the callback when complete downloaded.
3. cc.textureCache.addImageAsync return `texture2D` so we can create cc.Sprite as current implementation

Thanks.

**Comment by pandamicro** [comment]
> Create a cc.Sprite and cache the image with cc.RenderTexture, freeze > 2s. I think write to disk take long time and block the main thread.

RenderTexture will freeze a little for writing file to disk, but I assume once Downloader can occupy the download process, you don't need to do so anymore.

> Do you have any idea to avoid the crash?

I will take a look later, we can discuss it in another issue, it's not relevant with this one.

> 1. Downloader download the image
> 2. Downloader invoke cc.textureCache.addImageAsync in the callback when complete downloaded.
> 3. cc.textureCache.addImageAsync return texture2D so we can create cc.Sprite as current 

Not exactly, when Downloader API is ready, what you should do is like the following:

```
cc.Downloader.downloadFileAsync(url, function (succeed) {
    if (succeed) {
        cc.textureCache.addImageAsync(url, function(succeed, texture) {
            // Do your work
        });
    }
});
```

**Comment by 0xJimmyBeh** [comment]
> RenderTexture will freeze a little for writing file to disk, but I assume once Downloader can occupy the download process, you don't need to do so anymore.

When you expect the Downloader will be refined?
I read the post from your link, v3.8 will only have minimal changes, does this count as minimal changes?

> I will take a look later, we can discuss it in another issue, it's not relevant with this one.

Do i need to create another issue or wait you verify the issue first?
Friendly remind, you should test it with iOS device.

> when Downloader API is ready

`cc.textureCache.addImageAsync(url, function(succeed, texture)` would load the image from local file as current implementation? If so, thats great with the caching feature.

**Comment by pandamicro** [comment]
> When you expect the Downloader will be refined?
> I read the post from your link, v3.8 will only have minimal changes, does this count as minimal changes?

It's possible to bind these APIs in JS in v3.8.

> Do i need to create another issue or wait you verify the issue first?

It's not the same as #13054 ? If not, you can create a new one

> cc.textureCache.addImageAsync(url, function(succeed, texture) would load the image from local file as current implementation? If so, thats great with the caching feature.

Yes, addImageAsync remains the same as current

**Comment by 0xJimmyBeh** [comment]
> It's possible to bind these APIs in JS in v3.8.
> That's great to see the improvement in v3.8

This issue https://github.com/cocos2d/cocos2d-x/issues/13054 is about `cc.RenderTexture`
It use the texture2d return by `cc.textureCache.addImageAsync` to create the image.

Both should have related problem on the texture.

So i add "cc.textureCache.addImageAsync" to the issue because both having crash when changing scene or received low memory warning on iOS device.
