### ISSUE TITLE
function name ‘“pToAngleSelf” in cocos2d.lua is easy to be misunderstood.

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12876]
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/lua-bindings/script/cocos2d/Cocos2d.lua

``` lua
function cc.pToAngleSelf(self)   --The atan2 returns radians, not angle
    return math.atan2(self.y, self.x)
end

function cc.pForAngle(a)    --Here the parameters with Angle
    return { x = math.cos(a), y = math.sin(a) }
End
```

The function name let a person is difficult to understand.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@folgerhu
