### ISSUE TITLE
touch event pass to another layer?

### ISSUE THREAD

**Issue by rangercyh** [cocos2d/cocos2d-x#12895]
```
local _scene = cc.Scene:create()
local layer1 = ccs.GUIReader:getInstance():widgetFromJsonFile('res/CustomUI_25.json');

local function fun_1(sender, event)
    if event == ccui.TouchEventType.ended then
        sender:removeFromParent(true)
    end
end

local btn_1 = layer1:getChildByName("Button_1")
btn_1:addTouchEventListener(fun_1)

_scene:addChild(layer1);
cc.Director:getInstance():runWithScene(_scene)

local layer2 = cc.Layer:create()
local function onTouchesEnded(touches, event)
    print("onTouchesEnded")
end

local listener = cc.EventListenerTouchAllAtOnce:create()
listener:registerScriptHandler(onTouchesEnded,cc.Handler.EVENT_TOUCHES_ENDED )

local eventDispatcher = layer2:getEventDispatcher()
eventDispatcher:addEventListenerWithSceneGraphPriority(listener, layer2)
_scene:addChild(layer2)
```

I create a scene, and two layer added to it.
layer1 is a cocos studio layer, and have a button, I bind a touch event to it, in the function, I remove the button from the layer, it's ok! But the touch event passed to layer2, that's strange.
layer2 is a normal layer, and I create a AllAtOnce listener, and bind a function.
anybody can help me to figure it out? If button1's function not call removefromeparent, just do some print, it will swollow the event, layer2 is not trggle the listener.
I doubt that is this normal?

**Comment by pandamicro** [comment]
Swallow touch is supported for TOUCH_ONE_BY_ONE
