### ISSUE TITLE
quick 3.3 or 3.5 trans to cocos2d-x 3.7 rc1

### ISSUE THREAD

**Issue by wade0317** [cocos2d/cocos2d-x#12905]
I create a lua HelloWorld project by running "cocos new MyLuaGame -p com.yourcompany.mygame -l lua -d MyLuaGame" with the newest cocos2d-x . I copy framework of quick 3.5 to my HelloWorld Project, and replace app directory , main.lua, config.lua with the sample code in mvc, when i run the project, it said : [LUA ERROR] [string "src/framework/cocos2dx/NodeEx.lua"]:278: attempt to call a nil value. I do not known why.  Is that the newest cocos2d-x was not adapted to quick ? How can i  fixed it ?

this is my project:
localhost:MyLuaGame Wade$ ls
config.json frameworks  res     runtime     src
localhost:MyLuaGame Wade$ cd frameworks/
localhost:frameworks Wade$ ls
CMakeLists.txt  cocos2d-x   runtime-src
localhost:frameworks Wade$ cd ..
localhost:MyLuaGame Wade$ cd src
localhost:src Wade$ ls
app     cocos       config.lua  framework   main.lua
localhost:src Wade$ cd cocos/
localhost:cocos Wade$ ls
3d      cocosdenshion   extension   network     ui
cocos2d     cocostudio  framework   physics3d
cocosbuilder    controller  init.lua    spine
localhost:cocos Wade$ cd ..
localhost:src Wade$ cd framework/
localhost:framework Wade$ ls
anysdkConst.lua cocos2dx.lua    device.lua  global.lua  luaoc.lua   shortcodes.lua
audio.lua   crypto.lua  display.lua init.lua    network.lua toluaEx.lua
cc      debug.lua   filter.lua  json.lua    platform    transition.lua
cocos2dx    deprecated  functions.lua   luaj.lua    scheduler.lua

**Comment by pandamicro** [comment]
@dualface Can you take a look at this issue

**Comment by dualface** [comment]
You can upgrade your project to Quick 3.6 (3.7 coming soon), without modify many codes.

New Quick repo: https://github.com/dualface/quick-ng

**Comment by wade0317** [comment]
OK, I will have a try。 Thanks!

**Comment by wade0317** [comment]
OK, I will have a try。 Thanks!

**Comment by wade0317** [comment]
OK, I will have a try.  Thanks!
