### ISSUE TITLE
[cocos2d-js] Cc.EditBox incorrect positioning on Android and ALWAYS in CAPS

### ISSUE THREAD

**Issue by pepeek** [cocos2d/cocos2d-x#12902]
On Android is the normal9SpriteBg placed on expected position but the corresponding native edit control is ALWAYS placed on fixed top position regardless the required/set node position.

Also, the input text is always in CAPS with no option to switch is to lower case.
Regardless what mode/flag is set.
I've tried:

n = new cc.EditBox(cc.size(size.width*0.8, 50), new cc.Scale9Sprite("editbox_bg.png"));
n.setString(this.text);
n.setFontColor(cc.color(251, 250, 250));
n.setDelegate(this);
n.setInputMode(cc.KEYBOARD_RETURNTYPE_DEFAULT);
n.setInputFlag(cc.EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE);

Env: Cocos 3.5, Samsung Galaxy tablet.

Appreciate your help!

**Comment by pandamicro** [comment]
@zilongshanren Can this issue be fixed with your new implmentation?

**Comment by zilongshanren** [comment]
@pepeek @pandamicro 
The new EditBox implementation doesn't have this issue.
https://github.com/cocos2d/cocos2d-x/pull/13146

**Comment by zilongshanren** [comment]
Since the EditBox on Android platform is reimplemented. So I just close the issue here.
