### ISSUE TITLE
[cocos2d-js] Cc.EditBox show virtual keyboard automatically

### ISSUE THREAD

**Issue by pepeek** [cocos2d/cocos2d-x#12903]
Implement a method on cc.EditBox to show the virtual keyboard. Similar to ccui.TextField.attachWithIME().

First I thought that I can use this:

```
 cc.director.getOpenGLView().setIMEKeyboardState(true);
```

it does open the keyboard but the focus is not in the EditBox

so I've ended up with this DIRTY trick:

```
 void MyHelpCppClass::showVirtualKeyboard (bool open, EditBox* editBox) const
 {
      editBox->touchDownAction(NULL, Widget::TouchEventType::ENDED);
 }
```

which is called from JS using JSB. Sad, but working... at least for now.

Any proper solution would still be appreciated, thanks.

**Comment by zilongshanren** [comment]
@pepeek 
thanks for reporting this issue.
EditBox optimization has a higher priority in v3.8 roadmap.

**Comment by zilongshanren** [comment]
@pepeek 
Since EditBox is multi platform control, it's a bit tricky to add this API.
It's not a universal API valid for all platforms.
So sorry for the request.
