### ISSUE TITLE
cocosui folder not found on ubuntu when running test

### ISSUE THREAD

**Issue by cesarpachon** [cocos2d/cocos2d-x#12904]
working on implementation of AudioEngine for linux. when running the test NewAudioEngine on Ubuntu, I got this error and some UI sprites are not shown: 
 cocos2d: fullPathForFilename: No file found at cocosui/sliderTrack.png. Possible missing file.
cocos2d: fullPathForFilename: No file found at cocosui/sliderThumb.png. Possible missing file.
cocos2d: fullPathForFilename: No file found at cocosui/sliderThumb.png. Possible missing file.
cocos2d: fullPathForFilename: No file found at cocosui/sliderProgress.png. Possible missing file.
I solved it by creating a symbolic link named cocosui pointing to "extensions", but wonder what is the right approach.

**Comment by zilongshanren** [comment]
Did you run the command `git submodule update --init`?

**Comment by cesarpachon** [comment]
nope. I miss that step. thanks!
