### ISSUE TITLE
TMXXMLParser.cpp -- In the function getRectForGID have small errors

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12918]
cocos2d-x v3.6

![33333](https://cloud.githubusercontent.com/assets/3455415/8772025/a3b7ea40-2efa-11e5-9083-a0d6b6e120e8.png)
_imageSize.width = 256, _margin = 1, _spacing = 1, _tileSize.width = 31

Can see in the Tiled editor tilesets is 8 columns,
<img width="368" alt="screen shot 2015-07-20 at 4 17 49 pm" src="https://cloud.githubusercontent.com/assets/3455415/8772049/fef603ba-2efa-11e5-98a2-bcd4baf3cee0.png">

But in cocos2dx display abnormal.

``` cpp
Rect TMXTilesetInfo::getRectForGID(uint32_t gid)
{
    Rect rect;
    rect.size = _tileSize;
    gid &= kTMXFlippedMask;
    gid = gid - _firstGid;

    //The reason is that _margin don't * 2
    int max_x = (int)((_imageSize.width - _margin*2 + _spacing) / (_tileSize.width + _spacing));  

    //    int max_y = (imageSize.height - margin*2 + spacing) / (tileSize.height + spacing);
    rect.origin.x = (gid % max_x) * (_tileSize.width + _spacing) + _margin;
    rect.origin.y = (gid / max_x) * (_tileSize.height + _spacing) + _margin;
    return rect;
}
```

**Comment by pandamicro** [comment]
I can't see any problems here

**Comment by folgerhu** [comment]
```
int max_x = (int)((_imageSize.width - _margin*2 + _spacing) / (_tileSize.width + _spacing));
```

if _imageSize.width = 256, _margin = 1, _spacing = 1, _tileSize.width = 31, then:

```
max_x = (256-1*2+1)/(31+1) = 255 / 32 = 7
```

But see in the Tiled editor tilesets is 8 columns...

**Comment by yangws** [comment]
max_x = 7 is correct, the tile has 8 columns, values in [0, 8), means [0, 7].
