### ISSUE TITLE
[LUA ERROR] function refid '8182' does not reference a Lua function

### ISSUE THREAD

**Issue by pkxpp** [cocos2d/cocos2d-x#12913]
description: when I want my spine eventcallback don't work any more, I unregister the callback(as: :unregisterSpineEventHandler(sp.EventType.ANIMATION_EVENT)). But, after I do this, this problem come, why? And, How can I do? Thank you

**Comment by zilongshanren** [comment]
@dualface 
Could you take a look at this issue?

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@pkxpp
