### ISSUE TITLE
Spine: issue with scheduleUpdate

### ISSUE THREAD

**Issue by IgorMats** [cocos2d/cocos2d-x#12925]
Hi everyone.
I found a problem with latest version of **CCSkeleton.cpp**.

When you create a new Spine instance it calling **scheduleUpdate** method on **onEner** event.
It's okay, but when you using **javascript bindings** and wants to control update method from **javascript** there are some issue because **update** method in **javascript** is never calling because scheduleUpdate was called from c++.

Any way when you trying to call **scheduleUpdate** from javascript **it calling TWICE (once from c++ and once from javascript)**, so even the spine animation running two times faster.

This issue related to the https://github.com/cocos2d/cocos2d-js/issues/1732, but today I know why it happens. I don't know exactly what I shoud do with it so I trying to find the solution with community.

Thank you!

**Comment by pandamicro** [comment]
Temporarily, you can remove `this._super()` in JS update function, then the spine animation's speed should be normal.

The final solution should fix the default update in skeleton, if it found the call is invoked from script, then ignore it

**Comment by IgorMats** [comment]
I tried it but then it ignores my changes for class properties, so now I commented scheduleUpdate and unscheduleUpdate in c++, but it is not very convenient.

**Comment by pandamicro** [comment]
Can you post the code in your update function ?

**Comment by IgorMats** [comment]
@pandamicro there are nothing special, just `this.x += 1;`.

**Comment by IgorMats** [comment]
Closed due to Spine update in **3.8**.
