### ISSUE TITLE
How to load remote texture?

### ISSUE THREAD

**Issue by man2** [cocos2d/cocos2d-x#12920]
Tried with 
Director::getInstance()->getTextureCache()->addImageAsync("http://discuss.cocos2d-x.org/images/logo-vertical.png",[&](Texture2D *tex){});

I got this
cocos2d: fullPathForFilename: No file found at http://discuss.cocos2d-x.org/images/logo-vertical.png. Possible missing file.

It used to be working. I'm using github codes.

**Comment by pandamicro** [comment]
This is not supported in CPP, only supported in JS

**Comment by fusijie** [comment]
@man2 I have forked a repo which may be helpful to you. It's base on Cocos2d-x cpp branch.

https://github.com/fusijie/WebSprite

**Comment by man2** [comment]
Thanks, I also found this implementation 
https://developerhuddle.wordpress.com/2015/02/22/remotesprite-sprite-extension-to-support-server-hosted-graphics-cocos2d-x-c/

I think this feature is important to include in main repo

**Comment by minggo** [comment]
There is not plan to add this feature currently, may be in future.
