### ISSUE TITLE
some member functions of CCNode is not virtual.

### ISSUE THREAD

**Issue by maxwzg** [cocos2d/cocos2d-x#1293]
CCNode::getScale();
CCNode::setScale(float scale);
CCNode::getPositionLua(void);
CCNode::getPosition(float\* x, float\* y);
CCNode::getPositionX(void);
CCNode::getPositionY(void);
CCNode::setPositionX(float x);
CCNode::setPositionY(float y);
CCNode::setPosition(float x, float y);

No declared as virtual, is bug?

**Comment by ghost** [comment]
+1 Very true.

**Comment by donaldalanmorrison** [comment]
@maxwzg Do you need to override any of those functions for some reason?  If not, then not an issue yet. :-)

**Comment by godyZ** [comment]
@maxwzg Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August
