### ISSUE TITLE
Is v3.7 using a difference size system? 

### ISSUE THREAD

**Issue by hackthehackerman** [cocos2d/cocos2d-x#12939]
Hello, I am trying to migrate my project from 3.6 to 3.7 and notice that all my Labels are huge! It turns out that v3.7 has changed the size system from pixels to a "universal dimension"? 

With the following codes:

```
Size visibleSize = Director::getInstance()->getVisibleSize();
cout << visibleSize.width << endl;
cout << visibleSize.height << endl;
```

It used to print out the pixel dimension of the display, so 750 and 1334 for iphone 6. But it's now giving me 179.91,320 for iphone 6 and 180,320 for iphone 6+.

Here is a screenshot running on iphone 6.
<img width="725" alt="screen shot 2015-07-21 at 4 45 54 pm" src="https://cloud.githubusercontent.com/assets/1932380/8796609/802c513c-2fc8-11e5-8858-9d2d73c5aba8.png">

I couldn't find any reference to this in the change logs. Could anyone clear up the confusion? Thanks!

**Comment by WenhaiLin** [comment]
@yansuck That size system has not changed in cocos2d-x 3.7 version. Please check the design resolution within AppDelegate::applicationDidFinishLaunching.

**Comment by WenhaiLin** [comment]
@pandamicro I think this issue should be close.

**Comment by hackthehackerman** [comment]
I was running my codes inside HelloWorld:init() from a fresh application template generated by cocos. HelloWorld:init() is "inside" AppDelegate::applicationDidFinishLaunching. 

I ran the following codes again on iphone 6, iphone 6+ and ipad simulator.

<img width="1202" alt="screen shot 2015-07-22 at 8 48 49 pm" src="https://cloud.githubusercontent.com/assets/1932380/8825662/588d01bc-30b3-11e5-9735-ff9ab8e87bb4.png">

The output from my consoles are:

```
#iphone6: 
Inside applicationDidFinishLaunching.
1334
750
Inside Hello World.
480
269.865

#iphone6+:
Inside applicationDidFinishLaunching.
2208
1242
Inside Hello World.
480
270

#ipad:
Inside applicationDidFinishLaunching.
2048
1536
Inside Hello World.
426.667
320

```

@WenhaiLin Are you sure this is intended? Thanks.

**Comment by WenhaiLin** [comment]
@yansuck 
The value is equal to `Director::getWinSize()` if don't invoke `GLView::setDesignResolutionSize()`.
Do you invoke `GLView::setDesignResolutionSize()` within AppDelegate::applicationDidFinishLaunching

**Comment by hackthehackerman** [comment]
You are right. I didn't see the newly added design resolution routine in the default AppDelegate.cpp. Thank you for helping!
