### ISSUE TITLE
非线程安全的容器操作

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#12965]
1. 在CCRef里面通过CC_REF_LEAK_DETECTION跟踪Ref对象生命周期，由于现在Image是继承自Ref，在TextureCache里面通过线程加载时就有可能导致__refAllocationList数据污染。
2. FileUtils的fullPathForFilename也是一样在TextureCache的loadImage线程里面操作_fullPathCache这个容器。
3. TextureCache的loadImage里面_textures.find(asyncStruct->filename);操作也是不安全的

问题1,确认过是会crash的

**Comment by c3076802** [comment]
我们的游戏是有大量图片异步加载的，基本上和页游一个处理办法都是边下边玩的，才会出现上面的问题。毕竟cocos也就一个加载线程在跑，还有一点，现在取消异步加载实际上它还是会读取的，只不过读取完不回调而已，但是这样就意义不大了。

**Comment by yangws** [comment]
此问题已在 pr https://github.com/cocos2d/cocos2d-x/pull/12735 中修复。
在新的实现中：
－在CCRef里面通过CC_REF_LEAK_DETECTION跟踪Ref对象生命周期，由于现在Image是继承自Ref，在TextureCache里面通过线程加载时就有可能导致__refAllocationList数据污染。
-\* Image在这线程中被创建。
- FileUtils的fullPathForFilename也是一样在TextureCache的loadImage线程里面操作_fullPathCache这个容器。
  -\* fullPathForFilename 全部在主线程中执行。
- TextureCache的loadImage里面_textures.find(asyncStruct->filename);操作也是不安全的
  -\* 在load 线程中不再执行 _textures.find 操作。
  @pandamicro

**Comment by pandamicro** [comment]
Thanks
