### ISSUE TITLE
gen_prebuildlibs no longer works correctly on windows, Remove it

### ISSUE THREAD

**Issue by kompjoefriek** [cocos2d/cocos2d-x#12963]
The script `gen_prebuild_libs.py` goes into an endless loop on Windows 7 (64bit) and Windows 8.1 (64bit).
This can be fixed by changing `continue` to `break` on line 199. Not sure if that is the correct thing to do.

The configuration in `build_config.json` is outdated:
- `build/cocos2d-win32.vc2013.sln` was renamed to `build/cocos2d-win32.sln`
- `libcocosdenshion`, `libchipmunk` and `libcocosbuilder` are prebuild now and are no longer present in `cocos2d-win32.sln` (i probably missed a couple)
- `libbullet` and `librecast` have been added to `cocos2d-win32.sln`

If this script is still meant to be used (and supported), please fix the script.

**Comment by pandamicro** [comment]
It's no longer used by Cocos workflow and no longer maintained, we will remove it in v3.8

**Comment by kompjoefriek** [comment]
ok, thank you.
