### ISSUE TITLE
cmake now supports windows store apps

### ISSUE THREAD

**Issue by martell** [cocos2d/cocos2d-x#12960]
I don't know if you guys are aware or not but MS have sponsored some work on cmake

https://github.com/Microsoft/CMake

cmake can now generate projects using xaml files and can target windows phone winRT universal app etc.

All the more reason to move to a full cmake build system for cocos2d-x

**Comment by pandamicro** [comment]
This is a good news, @yangws

**Comment by drelaptop** [comment]
Cocos2d-x is moving to a full cmake build system. and now the CMake build of Cocos2d-x have supported VS2017. Welcome to use and feedback.

> no plan to support windows store apps
