### ISSUE TITLE
cocos' -p option won't change the package name of the generated android project.

### ISSUE THREAD

**Issue by dreamlover** [cocos2d/cocos2d-x#12970]
cocos new -p com.xx.xxx -l lua
When I create a new project with the command line above, the package name of the generated android project is still org.cocos2dx.lua.

**Comment by natural-law** [comment]
@dreamlover 
I just test the `cocos new` command. I haven't found the error.
The command I tested & the output:

```
$ ./cocos new -l lua -p com.xx.xxx
Running command: new
> Copy template into /Users/cocos2d-x/MyWork/cocos2d-x/tools/cocos2d-console/bin/MyLuaGame
> Replace the project name from 'HelloLua' to 'MyLuaGame'
> Copying directory from cocos root directory...
> Copying files from template directory...
> Copying cocos2d-x files...
> Copying directory from cocos root directory...
> Rename project name from 'HelloLua' to 'MyLuaGame'
> Replace the project name from 'HelloLua' to 'MyLuaGame'
> Replace the project package name from 'org.cocos2dx.hellolua' to 'com.xx.xxx'
> Replace the Mac bundle id from 'org.cocos2dx.hellolua' to 'com.xx.xxx'
> Replace the iOS bundle id from 'org.cocos2dx.hellolua' to 'com.xx.xxx'
> Modify files by re.sub()
```

Then take a look at the package name in AndroidManifest.xml:
![image](https://cloud.githubusercontent.com/assets/488169/8925680/4cd75150-353c-11e5-96e3-76f53fdeb076.png)

The package name has been replaced with `com.xx.xxx`.

**Comment by dreamlover** [comment]
Which version do you use? I use cocos2d-x 3.6 downloaded from your official website. It's OK if this error has been fixed, however. :)
