### ISSUE TITLE
RenderQueue:sort 在android机器上有可能出现错乱问题，std::sort is not always stable on every platform

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#13008]
这个是我同事提交给我的bug，经实测是有问题的，需要具体测试环境和bug描述，请联系我。

```
void RenderQueue::sort()
{
    //std::sort就在windows下边是稳定排序，g++是不稳定排序
    //如果序列里面有某个子序列系自己排好序再插入去的话，然后这个序列经过std::sort就会将你个子序列反转
    // Don't sort _queue0, it already comes sorted
    std::stable_sort(std::begin(_commands[QUEUE_GROUP::TRANSPARENT_3D]), std::end(_commands[QUEUE_GROUP::TRANSPARENT_3D]), compare3DCommand);
    std::stable_sort(std::begin(_commands[QUEUE_GROUP::GLOBALZ_NEG]), std::end(_commands[QUEUE_GROUP::GLOBALZ_NEG]), compareRenderCommand);
}
```

**Comment by fusijie** [comment]
请提供一个测试例（代码片段），以及测试的环境需求（平台？设备？）感谢~

Could you please provide some pieces of code and the environment requirement? Thanks.

**Comment by HoseaJiang** [comment]
发现这个问题的代码片段是JS写的，大概如下：
        var root=new jsb.Sprite3D();
        this.addChild(root);
        var bill0 = new jsb.BillBoard();
        root.addChild(bill0);

```
    var role= new baseArmature(res.j_master,"Master");
    role.playWithIndex(0,true);
    bill0.x=230;
    bill0.y=150;
    bill0.addChild(role);

    var bill = new jsb.BillBoard();
    bill.y=120;
    root.addChild(bill);
    var par=new cc.ParticleSystem(res.particle);
    bill.addChild(par);

    this.schedule(function(){

        this.cnt+=0.03;
        bill.setPosition3D(cc.math.vec3(Math.sin(this.cnt)*180+100,Math.cos(this.cnt)*50+80,Math.cos(this.cnt)*150+20));
    }, 0.05);
```

大概意思是建立一个Sprite3D的root，并且把一个Armature的骨骼对象（bill0）和粒子火焰对象（bill1）挂在root下，bill1围绕bill0旋转（挂在Sprite3D是为了两个对象之间的透视感）。在windows上是没问题的，发布到android包上就可以看到骨骼排序全部反转了（火球没问题）。实际上不需要bill1，只要把一个Armature的骨骼对象加入到sprite3D结点下面，骨骼各个部件之间有重叠覆盖部分，就可以看到骨骼的各个部件上下顺序是反的。

原因是，在c++标准中，std::sort是不稳定排序，对于同一个骨骼下面的部件，z相同，根据标准，排序会反转。但是在windows下，估计微软是为了怕麻烦，直接按照稳定排序来做了，所以在windows下一切正常。实际应用中主要影响TRANSPARENT_3D模式的渲染对象，把一些比如avata（骨骼或者序列帧）的billboard挂在3DSprite下就会出现这个bug。

**Comment by fusijie** [comment]
@jiang35 也就是说Sprite3D->BillBoard->Armature这样的结果会出现反序渲染，需要转动吗？一定要BillBoard吗？Armature是studio的还是spine？

**Comment by HoseaJiang** [comment]
@fusijie 一个2D骨骼对象挂到3D结点下面就是要用billboard了吧，还有没有别的挂法我不太清楚，这个歌demo也是我同事写的。Armature是studio的，那个例子下面的场合使用spine的话会有别的问题，不过不是这个的重点我这里先不说了。怎么挂不是问题主要是挂到3D场景下面的半透明对象都是要排序的，这个骨骼有没有动作是否转动都不重要，问题发生在排序上。就是RenderQueue::sort里面对QUEUE_GROUP::TRANSPARENT_3D也就是3D场景下半透明类型的对象进行排序，当Z相同的时候会发生反转，这对于一般的广告板无所谓，谁先谁后都是对的，但是如果是一个上层逻辑进行排过序的比如2D avata对象，各个部件的Z肯定是相等的，渲染的顺序要严格按照原来顺序。

上面贴的代码有写，std::sort严格按照c++标准来说是不稳定排序，改成std::stable_sort稳定排序
就可以正确显示了（在windows和安卓上测试过）。

**Comment by fusijie** [comment]
@jiang35 2D骨骼对象可以直接挂在3D节点下，至于挂在billboard下应该是有其他需求（面向camera之类的）。

我的主要疑问点是`但是如果是一个上层逻辑进行排过序的比如2D avata对象，各个部件的Z（这个是什么Z？）肯定是相等的`。这个Z不应该相等，Armature的各个bone(skin)，会有一个_orderOfArrival，这个值是各个部件是不一样的，而且参与排序，所以使用std::sort不会有问题。
能否直接给我一个测试例工程（代码+资源）。我刚用TestCase中的cowBoy骨骼按照你的方式测试没试出bug。我需要一个可以重现问题的测试例。
另外请告知您的Cocos2d-x版本。
感谢！

**Comment by HoseaJiang** [comment]
@fusijie cocos2d的版本是3.6，你是发布了安卓包测试的么？完整的资源我找一下。

**Comment by fusijie** [comment]
@jiang35 是的，安卓Nexus 7 v5.0.1. Cocos2d-x v3.8

**Comment by HoseaJiang** [comment]
@fusijie 我这边试了用官方的资源确实没问题，我们自己制作的资源在windows上没问题，在安卓上是全反了，然后std::sort改成std::stable_sort之后解决了问题，我把资源的源文件发给你吧。

**Comment by fusijie** [comment]
@jiang35 感谢~ fusijie@vip.qq.com

**Comment by HoseaJiang** [comment]
@fusijie 那个Z就是QuadCommand里面的_depth，好像跟_orderOfArrival没关系吧？_orderOfArrival是属于node的，是上层逻辑用的把本渲染对象构造成一种RenderCommand送进渲染器时候的顺序，然后对于其中的几种RenderCommand队列，渲染器会对它重新排序的。

**Comment by fusijie** [comment]
@jiang35 没有关系。因为有2次排序，一次是Node内部，一次是渲染队列。两次都使用的不稳定排序，而Node内部理论上不会有相等的Z（localZ + _orderOfArrival），所以没什么问题。而渲染队列无法保证Z一定都不相等，所以可能会出现不稳定排序。这个bug在v3.9会处理，主要是考虑到还得做一次性能测试确认下影响。请见#13482.
