### ISSUE TITLE
Problem with Socket.io emit

### ISSUE THREAD

**Issue by mmathews92** [cocos2d/cocos2d-x#13023]
I have a problem trying to use "emit" for send data to my server.
Connect, disconnect and On functions are working well, but when i trying to send some data to server, nothing is happend, no error log and server do nothing.

I use Socket.io 1.3.6

Sorry for my bad english.

**Comment by pandamicro** [comment]
Socket 1.x will be supported since v3.8, until then, you can only use Socket.io < 0.9
Please refer to this PR: https://github.com/cocos2d/cocos2d-x/pull/11583
