### ISSUE TITLE
Basic question: how to create scenes

### ISSUE THREAD

**Issue by jonnyijapan** [cocos2d/cocos2d-x#13035]
I'm on cocos2d-x v3.6. What is the recommended/supported way to create scenes - specifically when using replaceScene()? 

I used to use the `director->replaceScene(Myscene::createScene())` way from the template, but later when switching to RapidGame (you can find here on Github) it seems that the create() method was incompatible (it crashed in onExit for me) so I changed to the recommended way in RapidGame which is to use `director->replaceScene(new Myscene)` - now I'm worrying about memory issues here because I guess that cocos2d-x has no way of knowing if the dev used new, so it cannot release that memory on its own... (and in fact I am seeing that the destructor is not actually called on my scenes which currently uses this method)

Well looking at the cpp HelloWorld template in 3.6/3.7 it still looks like `director->replaceScene(Myscene::createScene())` **is** the correct way... and that Myscene should have a `static cocos2d::Scene* createScene();` as well as `CREATE_FUNC(Myscene);` defined. Can someone please confirm?

**Comment by pandamicro** [comment]
For Cocos2d-x with CPP, using create functions are suggested, and it's also a suggested way for implementing your own sub classes of `Ref`.

But well, it's also an open choice, you can of course do the following:

```
MyScene *scene = new Myscene();
scene->autorelease();
director->replaceScene(scene);
```

Once you call autorelease, it will be put into the autorelease pool.

**Comment by pandamicro** [comment]
About usages, you'd better open a topic on our forum: http://discuss.cocos2d-x.org/c/cocos2d-x

**Comment by jonnyijapan** [comment]
Thanks, got it! For some reason the create functions didn't work with RapidGame - I never found the reason for that and as I have to move on I stopped using RapidGame and will now go back to plain cocos2d-x.
