### ISSUE TITLE
HttpClient crash on App Quit （windows)

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#13045]
```
HttpClient::~HttpClient()
{
    CC_SAFE_DELETE(_requestSentinel);
    CCLOG("HttpClient destructor");
}
```

_requestSentinel might have ref > 1 when _responseQueue is not empty,
CC_SAFE_RELEASE_NULL should be called instead.

**Comment by WenhaiLin** [comment]
@c3076802  I can't reproduce this issue. How to reproduce this issue easier?

**Comment by zilongshanren** [comment]
can't reproduce, so I just close it here. If anyone have this issue again, feel free to reopen it .
