### ISSUE TITLE
3.7版本的CC_ENABLE_BULLET_INTEGRATION宏的继承问题

### ISSUE THREAD

**Issue by acros** [cocos2d/cocos2d-x#13046]
CC_ENABLE_BULLET_INTEGRATION=1在cocos2d-x DLL中启用，但是继承项目中并没有添加这个宏，导致主项目引用DLL时，实际编译头文件忽略了 Physics3DWorld\* 和 Camera*两个指针，DLL外进行Scene类内寻址_Physics3DWorld成员之后的变量全部出错。

另外，Scene还重定义覆盖了Node中的 PhysicsWorld\* _physicsWorld成员。

**Comment by zhaijialong** [comment]
是的，win32有问题，他们的宏玩脱了(逃

**Comment by yangws** [comment]
这个问题和 https://github.com/cocos2d/cocos2d-x/issues/12962 是同一个问题，已被修复
