### ISSUE TITLE
Callback gets called no matter where I touch!

### ISSUE THREAD

**Issue by andersonmadeira** [cocos2d/cocos2d-x#13047]
I think this may not be the right place to ask questions, but I've searched all over the internet to no avail. I just want to check for touch events on Sprites or DrawNodes, but when I bind the listener and run the application, the function gets called no matter where I click. This is the last place i'm looking for a solution to this problem, It's driving me crazy! -_-'

auto sprite = Sprite::create("sprite.png");
    sprite->setPosition(Vec2(100, 100));

```
auto listener2 = EventListenerTouchOneByOne::create();
listener2->setSwallowTouches(true);

// trigger when you push down
listener2->onTouchBegan = [](Touch* touch, Event* event){
    // your code
    log("2-Touch started: %s", event->getCurrentTarget()->getName().c_str());
    return true; // if you are consuming it
};

// trigger when moving touch
listener2->onTouchMoved = [](Touch* touch, Event* event){
    log("2-Touch moved: %s", event->getCurrentTarget()->getName().c_str());
    // your code
};

// trigger when you let up
listener2->onTouchEnded = [=](Touch* touch, Event* event){
    log("2-Touch end: %s", event->getCurrentTarget()->getName().c_str());
    // your code
};

// Add listener
sprite->getEventDispatcher()->addEventListenerWithSceneGraphPriority(listener2, sprite);

addChild(sprite);
```

No matter where I touch/click on the screen, I always get a bunch of ""2-Touch ...." on the console. What is wrong with my code?! 
Thanks.

BTW, I'm using version 3.6

**EDIT**: It looks like I have to check if `touch->getLocation()` belongs to `event->getCurrentTarget()->getBoundingBox()`. I thought that the function would be called only once and for the corresponding node (touched one). It looks like this callback is called for every node and I have to filter to match the node that was clicked. Correct me if I'm wrong. Thanks anyways.

**Comment by pandamicro** [comment]
Yes, you are right. The event dispatcher doesn't occupy the detection of responding regions for performance and complicated user needs reasons. You need to detect whether your listener should respond yourself

**Comment by andersonmadeira** [comment]
Ok, now I get it. Thanks.
Em 28/07/2015 00:11, "pandamicro" notifications@github.com escreveu:
