### ISSUE TITLE
C++ template project style differs from JS template project

### ISSUE THREAD

**Issue by simondel** [cocos2d/cocos2d-x#13070]
When creating a new JS project, a sample HelloWorldScene is created and that scene creates a HelloWorldLayer. From a hierarchical standpoint this makes a lot of sense: the layer is a child of the scene so the scene creates the layer.

In the C++ project this is not the case. The layer creates the scene which puts an odd dependency on the layer which should not be there in my opinion.

Could the C++ sample project be changed so it looks more like the JS sample project? I personally find the JS version a lot easier to build apps upon.

**Comment by zilongshanren** [comment]
@simondel 
For keeping consistency, it's better to unify all the template projects.
:+1:  Good catch.
Could you send us a PR?
Thanks.

**Comment by simondel** [comment]
@zilongshanren I think the best way way would be to change the C++ template so the Scene's overriden init method is used to create and add all layers. This way, the template will look like the JS template.
However, when using `createWithPhysics ()` the init method is not called because initwithphysics is called. You cannot override this method. How do you suggest fixing this little problem?
