### ISSUE TITLE
Transition popScene

### ISSUE THREAD

**Issue by sniperbat** [cocos2d/cocos2d-x#1307]
We can use pushScene with TransitionScene, let fade in and out to scene,but can not use popScene with TransitionScene, fade back to pre scene.
So, if the popScene method can return the m_pNextScene, we can use this code to implement it:

```
CCScene * nextScene = CCDirector::sharedDirector()->popScene();
CCScene * fadeScene = CCTransitionFade::create( 1.0f,  nextScene,ccc3( 255, 255, 255 ) );
CCDirector::sharedDirector()->replaceScene(  fadeScene );
```

The popScene code is

```
CCScene * CCDirector::popScene(void)
{
    CCAssert(m_pRunningScene != NULL, "running scene should not null");

    m_pobScenesStack->removeLastObject();
    unsigned int c = m_pobScenesStack->count();

    if (c == 0)
    {
        end();
    }
    else
    {
        m_bSendCleanupToScene = true;
        m_pNextScene = (CCScene*)m_pobScenesStack->objectAtIndex(c - 1);
    }
    return m_pNextScene;
}

```

Please consider this change

**Comment by donaldalanmorrison** [comment]
@sniperbat It is easier to quickly understand code suggestions in the form of a Pull Request.  Forks, commits, pushes, and pulls are all very cheap for git.

**Comment by godyZ** [comment]
@sniperbat Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August

**Comment by sniperbat** [comment]
@godyZ I got it, I will open it in redmine later.
@ttencate actually, the code has problem(missing some init or finish works), but idea should be work.
