### ISSUE TITLE
3.x 通过tolua自动导出到lua的C++函数异常检查的问题（原谅我无法reopen，很重要所以再次提出）

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#13072]
``` C++
    int lua_cocos2dx_Node_setCascadeOpacityEnabled(lua_State* tolua_S)
    {
        int argc = 0;
        cocos2d::Node* cobj = nullptr;
        bool ok  = true;

    #if COCOS2D_DEBUG >= 1
        tolua_Error tolua_err;
    #endif


    #if COCOS2D_DEBUG >= 1
        if (!tolua_isusertype(tolua_S,1,"cc.Node",0,&tolua_err)) goto tolua_lerror;
    #endif

        cobj = (cocos2d::Node*)tolua_tousertype(tolua_S,1,0);

    #if COCOS2D_DEBUG >= 1
        if (!cobj) 
        {
            tolua_error(tolua_S,"invalid 'cobj' in function 'lua_cocos2dx_Node_setCascadeOpacityEnabled'", nullptr);
            return 0;
        }
    #endif

        argc = lua_gettop(tolua_S)-1;
        if (argc == 1) 
        {
            bool arg0;

            ok &= luaval_to_boolean(tolua_S, 2,&arg0, "cc.Node:setCascadeOpacityEnabled");
            if(!ok)
            {
                tolua_error(tolua_S,"invalid arguments in function 'lua_cocos2dx_Node_setCascadeOpacityEnabled'", nullptr);
                return 0;
            }
            cobj->setCascadeOpacityEnabled(arg0);
            lua_settop(tolua_S, 1);
            return 1;
        }
        luaL_error(tolua_S, "%s has wrong number of arguments: %d, was expecting %d \n", "cc.Node:setCascadeOpacityEnabled",argc, 1);
        return 0;

    #if COCOS2D_DEBUG >= 1
        tolua_lerror:
        tolua_error(tolua_S,"#ferror in function 'lua_cocos2dx_Node_setCascadeOpacityEnabled'.",&tolua_err);
    #endif

        return 0;
    }
```

比如以上代码，如果COCOS2D_DEBUG 不是>=1的话，if (!cobj) 这句就不会执行，在运行中是会有cobj == null的情况的，比如说
1. 脚本使用了一个Node，将其放在一个callback里面执行（并没有retain）
2. callback还没执行之前，其他脚本代码删除了Node
3. 在lua的注册表就删除了该Node的关联
4. callback调用，cobj = (cocos2d::Ref*)tolua_tousertype(tolua_S,1,0); cobj返回null
5. 崩溃
这个脚本程序员很常见的错误，如果一个不小心，release版本就不明不白的就挂了。
我宁愿要一个slow and safe的运行环境，所以我才请求，在lua自动导出的文件(auto)里面，关于lua异常检查的开关宏不要用COCOS2D_DEBUG来处理，
因为COCOS2D_DEBUG关联了整个COCOS的DEBUG模式，我需要的是可开关是否做lua C++函数的异常检查的宏，甚至完全启用lua C++函数异常检查也可以。
@pandamicro

**Comment by zilongshanren** [comment]
@c3076802  Why not catch the bug in DEBUG mode?

**Comment by c3076802** [comment]
这是在开发中很常见的问题，说白了很多脚本程序员基础本来就不太好，我知道如果retain和release都弄好，其实是不会有以上的问题，但是现实就是根本上无法控制，记得retain又忘了release，造成内存泄露。

之前我们做过端游，就直接导出智能指针，这样就没有这种问题了，比如BigWorld, 用得是python
但是lua 5.1 table的没有gc事件（5.2有），这样就没办法精确控制C++对象的生命周期，而且就会导致内存消耗变大，这个在手游是不允许的。

在开发大型游戏时多人合作，在有限的开发时间里，对象生命周期及其难以维护，之前我们用cocos做的几个项目都是手改的，真心不想再弄一次了，蛋疼。

**Comment by c3076802** [comment]
@zilongshanren It is nearly impossible to catch the bug in DEBUG mode when you developing a large project.
1. some script programmer just don‘t have the capacity to handle the obj life-cycle well when developing module with others ( specially involving timer, callback and events push from the server)；
   and as you know we just not be able to hire good script programmer always; due to the budget and release deadlines. It is a practical problem.
2. We would like to have a safe and slow mode as Unity(C#) can be provided; 
   script exception is acceptable , crash is not.

**Comment by zilongshanren** [comment]
@c3076802  有什么办法可以减少这种错误 么？ 现在 Lua 是没办法控件C++对象的生命周期的。@dualface 这个问题你怎么看？

**Comment by c3076802** [comment]
我的意思就是，让所有这些自动导出的C++文件里面的lua API调用检查都通过其他宏来控制，根据项目需要来开关，比如我做一个大型项目，测试时间也不够，那么我就打开这个宏，进入safe and slow 模式，如果是个小游戏或者效率要求很高，那么大可关闭这个宏，现在的问题是，使用了COCOS2D_DEBUG 这个宏，弄起来麻烦而已。 @zilongshanren 我上面的评论也编辑了一下，BigWorld是用了智能指针（python），GameByro是handle + 智能指针（python or lua），其实都不太适合手游，原因上面也有说了，lua 5.1的局限和内存堆积。cocos本来就处理得不错，其实就是个宏的问题。

**Comment by zilongshanren** [comment]
@c3076802  恩，这样改要去论坛投票一下，毕竟是个破坏兼容性的修改。

**Comment by c3076802** [comment]
@zilongshanren 
恩，好的。
其实cocos 2.x的时候这个lua-binding的异常检查是通过独立的宏 TOLUA_RELEASE 来控制的，这样其实就足够灵活了。

``` C++
    /* method: getDuration of class  CCParticleSystem */
    #ifndef TOLUA_DISABLE_tolua_Cocos2d_CCParticleSystem_getDuration00
    static int tolua_Cocos2d_CCParticleSystem_getDuration00(lua_State* tolua_S)
    {
    #ifndef TOLUA_RELEASE
     tolua_Error tolua_err;
     if (
         !tolua_isusertype(tolua_S,1,"CCParticleSystem",0,&tolua_err) ||
         !tolua_isnoobj(tolua_S,2,&tolua_err)
     )
      goto tolua_lerror;
     else
    #endif
     {
      CCParticleSystem* self = (CCParticleSystem*)  tolua_tousertype(tolua_S,1,0);
    #ifndef TOLUA_RELEASE
      if (!self) tolua_error(tolua_S,"invalid 'self' in function 'getDuration'", NULL);
    #endif
      {
       float tolua_ret = (float)  self->getDuration();
       tolua_pushnumber(tolua_S,(lua_Number)tolua_ret);
      }
     }
     return 1;
    #ifndef TOLUA_RELEASE
     tolua_lerror:
     tolua_error(tolua_S,"#ferror in function 'getDuration'.",&tolua_err);
     return 0;
    #endif
    }
    #endif //#ifndef TOLUA_DISABLE
```

使用时只要将TOLUA_RELEASE 定义一下，就是safe and slow的模式了。

**Comment by c3076802** [comment]
BTW
我们现在的改法是在tolua_fix.h加上

```
//COCOS2D_CUSTOM_FIX Begin
// let COCOS2D_DEBUG always be 1 when in luabinding cpp src
#ifndef COCOS2D_DEBUG
#define COCOS2D_DEBUG 1
#else
#if COCOS2D_DEBUG <= 0
#undef COCOS2D_DEBUG
#define COCOS2D_DEBUG 1
#endif
#endif
//COCOS2D_CUSTOM_FIX End
```

**Comment by dualface** [comment]
是的。在 2.x 里是通过独立宏来开关的。

我个人认为应该一直打开这些参数检查，对性能的影响极小，却能明显帮助脚本开发者。

**Comment by zilongshanren** [comment]
@c3076802 Could you send a PR?
Thanks.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@c3076802 @zilongshanren @dualface
