### ISSUE TITLE
Can't find 3.7 min.js

### ISSUE THREAD

**Issue by darkoverlordofdata** [cocos2d/cocos2d-x#13075]
Hi, I just downloaded 3.7, and I can't find a prebuilt min.js anywhere.
cocos2d-js v3.6.1 had a cocos2d-js-v3.6-min.js located in frameworks/cocos2d-html5/lib

Will you be adding this back in for future releases?

Bruce

**Comment by pandamicro** [comment]
Oh, sorry, that was my mistake, I will build it in v3.7.1.
You can build it yourself by running `ant` command under `web/tools`
