### ISSUE TITLE
ccui.AbstractCheckButton没有注册到脚本，导致ccui.CheckBox继承链也断了无法使用Widget相关函数

### ISSUE THREAD

**Issue by fatfatson** [cocos2d/cocos2d-x#13080]
同时像setSelected这些本属于CheckBox的函数因为移到AbstractCheckButton上去了，现在也没法从脚本调用。非常大的问题啊！！！

**Comment by zilongshanren** [comment]
@fatfatson  Thanks for reporting, we need to resolve it before v3.8 release.

**Comment by zilongshanren** [comment]
already fixed.
