### ISSUE TITLE
Sprite doesn't show after setting its Physics Body

### ISSUE THREAD

**Issue by eliodecolli** [cocos2d/cocos2d-x#13090]
Here's my piece of code:
http://pastebin.com/tD1PnzNM

The "enemy" sprite doesn't appear if I set its PhysicsBody, the strange thing is that it happens only with that specific sprite.

**Comment by ItsElioBaby** [comment]
Really? No answers? So it's like the engine simply doesn't want me to have that sprite inside the game.

**Comment by SniderThanYou** [comment]
I've seen the same thing happen. Did you find a solution?

**Comment by eliodecolli** [comment]
No actually I've simply dropped Cocos.

**Comment by rynkowsg** [comment]
I have the same.

**Comment by SniderThanYou** [comment]
@rynkowsg (and anyone else looking at this)

I've been trying to follow this tutorial: http://www.sonarlearning.co.uk/coursepage.php?topic=game&course=cocos2d-x-flappy-bird-cplusplus

It's basically a Flappy Bird clone. The pipes, with their physics bodies, appear just fine. It's the bird that won't show up. The only real difference is that the bird is added in the GameScene's 'init' method, but the pipes are added later, in a timer-based callback. Sure enough, if I move the bird creation into that callback, it draws just fine.

To further muddy the waters, this problem only presents when I build the project on Windows using Visual Studio. Both the ball and the pipes appear just fine when I build on Ubuntu with CMake and gcc.

1) Does anyone know why I can't add sprites with physics bodies during a scene's init method?
2) Does anyone know why I would experience this problem on Windows but now Ubuntu?

**Comment by eliodecolli** [comment]
@SniderThanYou Well, try to use a different compiler, I would recommend Intel Parallel Studio.
I will try to build the game from my laptop with both visual c++ compiler and intel's one. Will post back results asap.

**Comment by TheCodez** [comment]
I think I also had this problem. Try adding those lines at the end of your init method:

``` cpp
_physicsWorld->setAutoStep(false);
_physicsWorld->step(0.0f);
_physicsWorld->setAutoStep(true);
```

**Comment by eliodecolli** [comment]
@TheCodez Is that like a "kickstart" for the physics wold ?

**Comment by TheCodez** [comment]
It might be, as it updates your bodies once. Removing those lines causes all my phyisical sprites to dissappear.

**Comment by rynkowsg** [comment]
@TheCodez: Your workaround causes a crash on Android platform (on Linux is ok).

Until now I use @SniderThanYou 's workaround. To apply it I used `scheduleOnce` in the GameScene's `init()` method:

```
scheduleOnce(schedule_selector(GameScene::createPlayer), 1.0f);
```

In the above line I put `1.0f` seconds as a delay. In my case 0.6s works fine too, but 0.5s is to low - the player doesn't appear. I didn't check why is it so. Apparently something needs to initialize before binding sprites and physical bodies.

@ItsElioBaby: I think that this issue is worth to re-open. It would be great to get the attention of cocos2d-x' contributors.

**Comment by TheCodez** [comment]
@rynkowsg @SniderThanYou  Are you using scene transitions? If you are using them its this issue causing the problem. https://github.com/cocos2d/cocos2d-x/issues/12567

**Comment by rynkowsg** [comment]
@TheCodez Thanks, I'll check it later. For now I'll stay with @SniderThanYou's workaround.

**Comment by TheCodez** [comment]
@rynkowsg you could also try to init your player in the `onEnterTransitionDidFinish` function. Im guessing the 0.6s in your `scheduleOnce` is your transition duration, that's why it isn't working with values below that.

**Comment by rynkowsg** [comment]
@TheCodez You almost guessed, I use 0.5s for transition duration. I read #12567 also and like you I think it could be cause of this problem. I will check the initialization of the player in the `onEnterTransitionDidFinish` when I switch to Windows. For now I leave it aside.
Thanks anyway.

**Comment by SniderThanYou** [comment]
Thanks for all of the workaround suggestions, and for referring me to that bug ticket. I'm glad to know I'm not the only one running up against this problem. Hopefully the bug is fixed soon!

**Comment by tqwewe** [comment]
Nearly 2018, any updates on this? I'm currently having this issue.
