### ISSUE TITLE
Tiledmap display usually not correct

### ISSUE THREAD

**Issue by jie-meng** [cocos2d/cocos2d-x#13096]
This is tiledmap:
![tiled](https://cloud.githubusercontent.com/assets/7405315/8973613/5432b8c8-3699-11e5-8483-07d87320409a.PNG)

This is how cocos2d-x-3.6 displayed:
![cocos](https://cloud.githubusercontent.com/assets/7405315/8973617/68b184be-3699-11e5-994a-ffd51013c7eb.PNG)

cocos2dx 3.5, 3.6 both have this bug.

**Comment by jie-meng** [comment]
I tried on windows, linux and Android, all of the 3 platforms display not correct.

**Comment by pandamicro** [comment]
Please check whether this PR fix your problem: https://github.com/cocos2d/cocos2d-x/pull/12971

**Comment by jie-meng** [comment]
It does not work with PR #12971  commit 3c3a5a6.

**Comment by jie-meng** [comment]
This bug is really easy to appear when you create a tiledmap with 3 or more tiled layers, some map graphics in different pngs.

**Comment by jie-meng** [comment]
1-layer-tiled
![background](https://cloud.githubusercontent.com/assets/7405315/9026119/60b89d42-3955-11e5-8c6f-858c9c1c9c55.png)
 2-layers-tiled
![objects](https://cloud.githubusercontent.com/assets/7405315/9026129/dd021d7e-3955-11e5-8a6c-72ebb9b4ad3e.png)

@pandamicro It seems if I draw all tiles in one background layer, it is ok. but when I put objects to another layer above background, it would meet this bug.

**Comment by jie-meng** [comment]
I got the point, one TMXLayer can only use one tiledset.
