### ISSUE TITLE
CCBI file version 3 not supported

### ISSUE THREAD

**Issue by meroon-zz** [cocos2d/cocos2d-x#1309]
The latest CocosBuilder appears to only export version 3 CCBI files. Right now cocos2d-x supports up to version 2. Is there currently an effort to update cocos2d-x support?

**Comment by minggo** [comment]
Yep, i am doing the work.

**Comment by meroon-zz** [comment]
Oh awesome! Any kind of ETA on the fix? I don't mean to be pushy, just wondering for my own planning. Can I help in any way?

**Comment by walzer** [comment]
Minggo has finished coding, I saw he's debugging on the last Friday.

**Comment by minggo** [comment]
@meroon 

I will create a branch for it, then i will push the codes.
I will paster the url here when i finish it.

There are still some bugs.
You are appreciated if you can help me to resolve the bugs.

**Comment by minggo** [comment]
@meroon 

I have push my codes here https://github.com/minggo/cocos2d-x/tree/iss1470_cocosbuilder.

There are some bugs:
1. It seems that CCLayerGradient doesn't take effect, so the background is black.
2. It will crash when click the button in TestButtons.ccbi.
3. I have not implemented Animations when click "Animations".

You are appreciated to help to resolve these issues.
Thank you.

**Comment by minggo** [comment]
I fix the crash.

**Comment by meroon-zz** [comment]
Oh awesome! Thanks man! I'll bring the changes in tomorrow and test them out. 

Cheers!

**Comment by minggo** [comment]
I fix all errors.
Now there is only one thing i have to do.
I have to re-publish CCB file, now it uses "Flatter paths", i will not use it like this.
Because it is not convenient on other platforms.

**Comment by donaldalanmorrison** [comment]
☆彡 ☆ミ ☆彡 ☆ミ ☆彡 ☆ミ ☆彡 ☆ミ ☆彡 ☆ミ   

＼(◎o◎)／

**Comment by godyZ** [comment]
@meroon  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August
