### ISSUE TITLE
cocos 3.1无法使用NDK r10c，有解决方案吗？

### ISSUE THREAD

**Issue by xiaoqiangkx** [cocos2d/cocos2d-x#13099]
使用NDK r10c编译cocos 3.1时会报错，看上去是NDK r10c去除了一部分方法。
cocos2d-x/external/lua/lua/prebuilt/android/liblua.a(lauxlib.o):lauxlib.c:function luaL_loadfile: error: undefined reference to '__srget'

大家有同时使用cocos 3.1 + NDK 10c的解决方案吗？

**Comment by zilongshanren** [comment]
可以自己重新用 NDK r10c 去编译 liblua.a
