### ISSUE TITLE
Auto-Culling issue

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#13109]
relate issue: #10487 
relate pr: #13105 

**Temporary solution:**
#13105 is a temporary remedy. we wanna to get a balance between bug and performance. so we choose  to check model view matrix dirty for default camera preferentially and ignore user's cameras.

**Now the result is:**
- For default camera, bug is fixed, performance almost the same with before.
- For user's cameras, bug is fixed, but get performance loss.

**What we need to do?**
- Check model view dirty for all nodes and cameras.
- Multiple cameras for a node, the difficulty is:
  - How to manage cameras' dirty? 
  - How to update cameras' dirty?
  - How to optimize search algorithm to reduce performance loss?

**Suggestion**
If you get confuse with auto-culling function, here are something you need to know. (for Sprite & Label)
- CC_USE_CULLING is a precompiled macro instead of hard coding, means that it's not a 100% optimization. The right way is enable/disable it in the appropriate environment.
- If ensure all of the Sprite/Label inside of the screen, disable auto-culling function.
- If a lot of Sprite/Label outside of screen, enable auto-culling function.
- If ensure camera is a static object, no needs to apply #13105.
- Detailed performance comparision can be found via #10487.

**Comment by zilongshanren** [comment]
@ricardoquesada 
Thoughts?

**Comment by minggo** [comment]
enable/disable culling in runtime is time consuming, so close it
