### ISSUE TITLE
HTML5 -- Armature render bug in CANVAS mode

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#13103]
`Engine version: Cocos 2d-x v3.7`
`Language: JS`
`Test env:  Chrome for mac Version 41.0.2272.101 (64-bit)`

`Reproduce steps:`
1. create JS project and set "renderMode" : 2
2. create a Armature object
3. add some display object into this Armature object
4. run moveTo action with this Armature object
5. run in web browser with canvas mode, then some display object position is incorrect:
<img width="609" alt="screen shot 2015-07-30 at 11 03 10 am" src="https://cloud.githubusercontent.com/assets/3455415/8975344/b5d1e5de-36af-11e5-86e2-952436af50e3.png">

Here is my test code: http://vdisk.weibo.com/s/u2pFxSLc_tXN

**Comment by minggo** [comment]
Since cocos studio is canceled, so close this issue
