### ISSUE TITLE
TypeError: ccui.CheckBox.getSelectedState = UICheckBoxDeprecated.setSelectedState

### ISSUE THREAD

**Issue by dreamlover** [cocos2d/cocos2d-x#13136]
cocos/ui/DeprecatedUIFunc.lua:121:
--- source ---
function UICheckBoxDeprecated.getSelectedState(self)
   deprecatedTip("ccui.CheckBox:getSelectedState", "ccui.CheckBox:getSelected")
   return self:getSelected()
end
ccui.CheckBox.getSelectedState = UICheckBoxDeprecated.setSelectedState
--- end ---

Maybe that is derived from here: cocos/ui/UICheckBox.h:191:
--- source --- 
/**
     \* Change Checkbox state to selected.
     *
     \* @deprecated use `isSelected()` instead
     \* @param selected   True means the Checkbox will be selected, false means unselected.
     */
    CC_DEPRECATED_ATTRIBUTE void setSelectedState(bool selected){this->setSelected(selected);}

```
/**
 * Query whether the CheckBox is selected or not.
 *
 * @deprecated use `setSelected(bool)` instead.
 * @return selected    true that checkbox is selected, false otherwise.
 */
CC_DEPRECATED_ATTRIBUTE bool getSelectedState()const{return this->isSelected();}
```

--- end ---

**Comment by zilongshanren** [comment]
@dreamlover 
Hi, What's the problem here?
