### ISSUE TITLE
win32無法編譯，experimental::Viewport建構式錯誤

### ISSUE THREAD

**Issue by sianzain** [cocos2d/cocos2d-x#13134]
cocos\platform\CCGLView.cpp
line:230
應該改為
    experimental::Viewport vp((float)(x \* _scaleX + _viewPortRect.origin.x),
        (float)(y \* _scaleY + _viewPortRect.origin.y),
        (float)(w \* _scaleX),
        (float)(h \* _scaleY));
//--------------------------------------------------------------------------------------------
cocos\platform\desktop\CCGLViewImpl-desktop.cpp
line:554
應該改為  
experimental::Viewport vp((float)(x \* _scaleX \* _retinaFactor \* _frameZoomFactor + _viewPortRect.origin.x \* _retinaFactor \* _frameZoomFactor),
        (float)(y \* _scaleY \* _retinaFactor  \* _frameZoomFactor + _viewPortRect.origin.y \* _retinaFactor \* _frameZoomFactor),
        (float)(w \* _scaleX \* _retinaFactor \* _frameZoomFactor),
        (float)(h \* _scaleY \* _retinaFactor \* _frameZoomFactor));

**Comment by zilongshanren** [comment]
@sianzain
What's the problem with the original `GLView` settings?
@dabingnn  Could you please take a look at this issue?

**Comment by dabingnn** [comment]
@sianzain Which version of visual studio are you using? It seems that old version of visual studio does not support this. Anyway, I like your proposal, it is more compiler friendly.
Thanks.

**Comment by sianzain** [comment]
vs 2012
