### ISSUE TITLE
CCLuaEngine Does Not Compile In GNU++11/libc++ Mode On Xcode/iOS

### ISSUE THREAD

**Issue by nolsen** [cocos2d/cocos2d-x#1313]
If I try to build a cocos2dx application for iOS using Xcode with C++ Language Dialect set to GNU++11 and C++ Standard Library set to libc++ (the LLVM standard library with C++11 support) I get errors trying to resolve the templates in CCLuaEngine.h. The problem is with CCScriptValue being forward declared, and then used in the declaration of CCScriptValueField, which is then used in the actual definition of CCScriptValue.

This seems to be a bit of an edge case for the C++ language and I'm not sure why LLVM will compile it in default C++ mode but not 11 mode. Seems like a possible solution would be to make the various CCScriptValue containers store pointers to CCScriptValues instead, possibly using smart pointers like unique_ptr to minimize memory management hassle.

For some context, the reason I ran into this is because I wanted to use the new std::unordered_map, so I enabled C++11 support, rebuilt and had the errors. I also found if I enable C++11 mode in the compiler but continue to use the default GNU C++ standard library, the code will compile and link if I use the std::tr1::unordered_map instead.

This is hardly a critical issue as I have alternative choices of containers as well as a workaround via TR1, but figure I might as well report it. In general the sooner you find out what breaks because of a new language revision, the better.

**Comment by minggo** [comment]
I think C++11 is too new to use.
cocos2d-x is a cross-platform engine, so it can not use so new C++11 feature.
Even this issue can be resolved in Xcode, can it work in Android, windows, linux and blackberry?

**Comment by nolsen** [comment]
Well I wasn't so much advocating using C++11 features in the cocos2dx codebase, as making sure it compiles with a C++11 compiler. Someone may want to use C++11 features in their game code and if cocos2dx won't compile that's the end of that.

**Comment by Aludirk** [comment]
I'm totally agree with nolsen, the cocos2dx needs not to use C++11 features,
by as least it should not stop the engine user to use the C++11 features.

start from 2.0.3, our project cannot build anymore in iOS
and is that mean we should not use cocos2dx engine if we are going to use C++11 features ?

**Comment by nolsen** [comment]
Another consideration, and I am nowhere near a standards lawyer, but it may be the case that the code that fails to compile is not a C++11 issue per se, it may be that the code is not legal C++ and never has been legal C++, but that current-generation compilers are lax and allow it to compile anyway. If future compiler versions are more strict, irrespective of C++11 support, it may only be a matter of time before this results in cocos2dx becoming broken with a compiler update. This is probably likely to happen on Xcode first as Apple is pretty aggressive about iterating tools and doesn't care so much about breaking changes, but it could happen on any platform at any time, especially as all the players are getting their updates together as we transition to compilers with progressively more support for the new standard.

**Comment by godyZ** [comment]
@nolsen  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August
