### ISSUE TITLE
Can't use proj.android-studio for compiling

### ISSUE THREAD

**Issue by mikementos** [cocos2d/cocos2d-x#13142]
I can't make it run the android project for android studio. because of this error 

java.lang.UnsatisfiedLinkError: Couldn't load cocos2dcpp: findLibrary returned null

http://stackoverflow.com/questions/31737384/android-studio-1-3-java-lang-unsatisfiedlinkerror-couldnt-load-cocos2dcpp-fin

**Comment by WenhaiLin** [comment]
Cocos console now supports compilation and package with Android Studio 1.2+, use it with a --android-studio flag

```
cocos run/compile -p android --android-studio
```
