### ISSUE TITLE
Editbox setInputFlag as "password", enter key can't complete input.

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#13140]
`Engine version: Cocos 2d-x v3.7`
`Test environment:  XiaoMi2 / Samsung GT-I8552`

Editbox setInputFlag as "password", click the "enter" on the soft keyboard, the input have not completed, but the "enter" as a character.

**Comment by zilongshanren** [comment]
@folgerhu
The EditBox has been reimplemented. So please test it after v3.8 released.
Thanks.

**Comment by semgilo** [comment]
@zilongshanren 3.9 problem has exist

**Comment by zilongshanren** [comment]
@semgilo 
Do you mean this issue is still exists on v3.9?

**Comment by zilongshanren** [comment]
@semgilo 
I have tested it with HuaWei P8 and it doesn't have this issue.
What Android device do you use and what's your Android version?

**Comment by semgilo** [comment]
@zilongshanren i used iphone5 ios 9.1

**Comment by semgilo** [comment]
when i setInputFlag as "password", i can't input and text is null

**Comment by semgilo** [comment]
@zilongshanren sorry it my problem

**Comment by zilongshanren** [comment]
@semgilo  
It's all right.
