### ISSUE TITLE
iPhone5  fixes

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#1315]
Can't talk about iOS6 features because of NDA, but this fix should be considered :-)

iOS/AppController.mm at line 44:

```
// set the Navigation Controller as the root view controller for iOS >=4
[window setRootViewController: viewController];
```

Check http://www.cocos2d-x.org/boards/6/topics/15447?r=15526

**Comment by donaldalanmorrison** [comment]
Looks fixed in https://github.com/cocos2d/cocos2d-x/commit/b64f007fbbe7b65e974c5ab310d04a0e2509775a

**Comment by ghost** [comment]
Closing now
