### ISSUE TITLE
Fix the physics timestamp with smooth interpolation

### ISSUE THREAD

**Issue by Dredok** [cocos2d/cocos2d-x#13156]
Hi,
In order to avoid stuttering and other graphical artifacts, I have to set the autoUpdate(false) and manually fix the timestep for physics.

After using a fixed timestep for physics, I have to manually interpolate all graphical nodes which depend on  physic bodies.

See this:
http://gafferongames.com/game-physics/fix-your-timestep/

Ideally this should be performed by the engine out of the box: I think it is a must to have a fixed timestep for physics2d engine

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@Dredok
