### ISSUE TITLE
[Spine] SkeletonRenderer::initialize cause memory leak

### ISSUE THREAD

**Issue by shkertt** [cocos2d/cocos2d-x#13150]
SkeletonRenderer::_atlas 初始化后 被SkeletonRenderer::initialize 置空

导致内存在析构是无法释放

**Comment by pandamicro** [comment]
Fix PR proposed to SpineRuntime: https://github.com/EsotericSoftware/spine-runtimes/pull/461

**Comment by minggo** [comment]
The codes is merged in #13335.
