### ISSUE TITLE
bug for hello world project 

### ISSUE THREAD

**Issue by wade0317** [cocos2d/cocos2d-x#13155]
I create a hello world project by runing  "cocos new MyLuaGame -p com.jellykitgames.MyLuaGame -l lua --portrait -d /Users/Wade/Documents/workspace/ ",  It seems to be a bug there.  It's upside down
![ios simulator screen shot 2015 8 2 1 28 29](https://cloud.githubusercontent.com/assets/3960813/9024878/59a8d600-391b-11e5-9bb8-ab3f7c33d889.png)

**Comment by natural-law** [comment]
@wade0317 
I have reproduced the problem with Xcode 6.4.
I'm using Xcode 6.1 before, it was worked well on Xcode 6.1.

The related PR : https://github.com/cocos2d/cocos2d-x/pull/13377
You can test the latest code again. Thanks for your feedback.
