### ISSUE TITLE
couldn't build latest gl20 branch on Ubuntu 12.04 x86_64

### ISSUE THREAD

**Issue by GavinBIC** [cocos2d/cocos2d-x#1317]
I got the latest snapshot of the gl20 branch, and built it on Ubuntu 12.04 x86_64.
the build broke while building samples/testCPP.

here is the build error-log.
https://gist.github.com/3725395

**Comment by walzer** [comment]
I think there may be something wrong in the search header path, many basic classes are undefined. As you can see, we are using 2 machines 7x24 compiling the edge version, but we have no enough machine to run linux now. Maybe next week :)

My suggestion is 1. check the header path is correct.  2. compile on x86_32. AFAIK, core team haven't tested it on 64bit system.

**Comment by GavinBIC** [comment]
I used make-all-linux-project.sh , so path should be correct.
I think it's DSO's symbol problem. reading http://gcc.gnu.org/wiki/Visibility , I think cocos2dx/platform/linux/CCPlatformDefine.h need very little fix which is this https://gist.github.com/3733228 .  
With above fix , SampleCpp and HelloCpp are working fine in Ubuntu 12.04 x86_64
