### ISSUE TITLE
may be no unref

### ISSUE THREAD

**Issue by ywxzm** [cocos2d/cocos2d-x#13195]
in file lua_cocos2dx_manual.cpp Line 1817    , function tolua_cocos2d_CallFunc_create 
            lua_pushvalue(tolua_S, 3);
            ref = luaL_ref(tolua_S, LUA_REGISTRYINDEX);

```
       if this action no execute, no unref it
```

**Comment by zilongshanren** [comment]
@dualface  
please take a look at this issue, thanks.

**Comment by dumganhar** [comment]
@zilongshanren , it's actually a bug. We need to fix it.

**Comment by minggo** [comment]
it is fixed
