### ISSUE TITLE
ProtectedNode中通过addProtectedChild()添加的子节点，触摸事件，不受节点树控制。

### ISSUE THREAD

**Issue by hai4925** [cocos2d/cocos2d-x#13207]
在EventDispatcher中，对事件排序时，是根据事件所在节点，在节点树上的深度进行排序，但是ProtectedNode的派生类中，_protectedChildren中的直接点没有参与排序运算。

**Comment by zilongshanren** [comment]
@hai4925
please use English here Thanks.

The `addProtectedNode` API is designed like this. If you want the child node receive touch event, you should use `addChild` instead.

**Comment by hai4925** [comment]
但是UIRichText中的渲染根节点，是通过addProtectedChild添加到UIRichText上的，如果UIRichText有元素有触摸事件，行为就不一定正常了。我这边把一个Button添加到UIRichText中，结果触摸事件在最后面，如果事件队列中任意事件吞没事件，Button就响应不到事件。@zilongshanren

**Comment by minggo** [comment]
It is better to ask these question in forum:
- Chinese forum: http://forum.cocos.com/
- English forum: http://discuss.cocos2d-x.org/

**Comment by Areaper** [comment]
@zilongshanren Cocos use addProtectedChild in UIRichText. Is there any way to get these child node?
