### ISSUE TITLE
Menu must receive touch ended event

### ISSUE THREAD

**Issue by udirub** [cocos2d/cocos2d-x#13204]
I have a simple menu with a menu item and I've placed a node that recognizes gestures in front of it. If my gesture recognizer detects a gesture it stops the touch ended event propagation so it won't trigger a button click on the button behind it. The problem is that once the touch ended event doesn't reach the menu the menu is no longer usable and it doesn't respond to any more touches.
From a quick look at the code it seems to be a problem with the _state member variable that is only reset in the touch ended method and if this function is not called even once the _state doesn't return to WAITING.

**Comment by zilongshanren** [comment]
@udirub 
Thanks.  Could you send a PR to resolve this issue? 
Since Menu is very ooooooold widget and we have no plan to continue the improvement over it.
You could try ui::Layout and ui::Buttons instead. Thanks.

**Comment by udirub** [comment]
@zilongshanren , What do you mean by PR?

**Comment by zilongshanren** [comment]
@udirub  I mean "Pull Request".

**Comment by udirub** [comment]
@zilongshanren , currently I did a dirty fix in my own code, if I'll have a chance to make a real fix I'll let you know.
