### ISSUE TITLE
FontAtlasCache::purgeCachedData might cause crash

### ISSUE THREAD

**Issue by weibobo** [cocos2d/cocos2d-x#13202]
I got a crash stack on android, it pointed to method FontAtlasCache::purgeCachedData, but i can not create a test case to always create this bug. I checked the code , find the bug might cause by that:
In FontAtlasCache::purgeCachedData, 
    for (auto & atlas:_atlasMap)
    {
        atlas.second->purgeTexturesAtlas();
    }
It invoke FontAtlas::purgeTexturesAtlas, which invoke cclabel's purgeTextureListener, which call FontAtlasCache::releaseFontAtlas. FontAtlasCache::releaseFontAtlas change the _atlasMap. 

The loop process of _atlasMap might be affected in the process, and cause crash.

**Comment by zilongshanren** [comment]
@WenhaiLin 
Could you please take a look at this issue?

**Comment by weibobo** [comment]
Found a test case to recreate the crash. Solution is:
void FontAtlasCache::purgeCachedData()
{
    std::vector<FontAtlas*> v;
    for(auto &atlas: _atlasMap)
    {
        v.push_back(atlas.second);
    }
    for (auto & atlas:v)
    {
        atlas->purgeTexturesAtlas();
    }
}

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/13210
