### ISSUE TITLE
Very Low Frame Rate on Samsung Galaxy Tab 4

### ISSUE THREAD

**Issue by ermanhaskan** [cocos2d/cocos2d-x#13205]
Hello

We tested our cocos2d-x v3.7 game on 20-25 different Android devices. It hardly passes 30 fps on Tab 4 while every other device (including Tab2 & Tab3) ran the game near 60fps. We tried everything from lowering resolutions of textures to changing pixel format but at the end we have found out that it's not really about our code because the game performs great even on slowest Android devices. 

Is there a special condition for Tab 4's GPU to prevent running Cocos2d-x engine at good performance? Can anything be done about this issue? Does anyone have further information on this matter?

Thanks.

**Comment by zilongshanren** [comment]
@ermanhaskan  Could you try the Samsung EnhancedAPI?
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/CCEnhanceAPI-android.h

**Comment by ermanhaskan** [comment]
It says: "Note: The minimum required Android version is 5.0." 

Tab 4 is 4.x

**Comment by VivekFitkariwala** [comment]
I am using cocos2dx 3.8.1 build which has Samsung EnhancedAPI but still getting 30fps on Samsung Note 4 with android version 5.0.1

**Comment by minggo** [comment]
I think it is fixed in latest codes, please refer to #15652 for detail information.
