### ISSUE TITLE
Physics issues when scene is moved/scaled (v3.7)

### ISSUE THREAD

**Issue by gstolarov** [cocos2d/cocos2d-x#13226]
When scene is moved/scaled physics node positioning is broken. To replicate in 
cocos2d-x-3.7\tests\cpp-tests\classes\physicstest\physicstest.cpp function PhysicsDemo::init() add 
this->setPosition(Vec2(-24.0f, -24.0f)) before return. Navigate to Node: Physics and then to Physics Test - multitouch to add grossini. Click Toggle debug to turn debug draw on. Observe how the debug draw is full width of image (48px rather then 24px) off. At some point moving and scaling scene may change relative position of objects, and in extreme cases actually position images outside of the edge node and completely break physics.
Works correctly in v3.3
Might be related to https://github.com/cocos2d/cocos2d-x/issues/12943 (but adjusted for position)

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@gstolarov
