### ISSUE TITLE
Support hexagonal tile maps

### ISSUE THREAD

**Issue by JustVic** [cocos2d/cocos2d-x#13237]
I'm trying to make game with hexagonal tile map, but I found hex maps in cocos2d-x not working so good.

1)First time i create map in TiledMapEditor(0.12.3):
in Tiled: https://i.imgur.com/bBuGnPq.png3
But cocos2d-x drawing it not exactly.

How it looks in cocos2d-x:
In Cocos2d-x: https://i.imgur.com/GlYe3II.jpg3

2)Another map with Stagger Axis Y and Drawing Offset Y
in Tiled: https://i.imgur.com/bpaqqEk.png3

In Cocos2d-x: https://i.imgur.com/juJpzx2.jpg4

Are there any plans to do full support hexagonal maps in cocos2d-x?

I'am trying to fix this in my branch:
https://github.com/JustVic/cocos2d-x/tree/jv_cocos2d-x
can send a “pull request”.

I solve second case, and Stagger Axis Y and X and Drawing Offset is working. but not solve first because it needs to rewrite rendering order. And Hex map in cocos test need to be updated Tile Side Lenght(Hex);
Working examples screenshots:
1 - https://i.imgur.com/Xo2wzkr.jpg
2 - https://i.imgur.com/mRWZdxd.jpg

**Comment by dehlen** [comment]
Any news on this one ? I also ran into this problem and would love to see a fix here.

**Comment by JustVic** [comment]
I sent commit with partial fix to this #13288

**Comment by ricardoquesada** [comment]
thanks. I'll work on this one.

**Comment by ricardoquesada** [comment]
@JustVic your PR seems to work ok with the hex example that comes with Tiled.

But you mentioned that it fails with other cases? could you describe where it fails? thanks.

**Comment by ricardoquesada** [comment]
thanks. fixed in #16019

**Comment by shadel** [comment]
this bug still appeard in js build. Please check it again
