### ISSUE TITLE
VideoPlayer runAction with scaleto, run on android appear black

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#13244]
`Engine version: Cocos 2d-js v3.7`

`Reproduce steps:`
1. run this code on android;
2. click button play video for more

Here is test code: http://vdisk.weibo.com/s/u2pFxSLcI5yv

**Comment by folgerhu** [comment]
@WenhaiLin

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@folgerhu
