### ISSUE TITLE
SimpleAudioEngine pauseBackgroundMusic() different behavior on windows

### ISSUE THREAD

**Issue by lfmn83** [cocos2d/cocos2d-x#13254]
Steps:
- Pause music: CocosDenshion::SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
- Check if music is playing: if(CocosDenshion::SimpleAudioEngine::getInstance()->isBackgroundMusicPlaying()) 

Result: On Windows Phone isBackgroundMusicPlaying return true. Android and iOS return false.

Tested on windows phone project (proj.win8.1-universal) with cocos2d-x v3.7.

**Comment by minggo** [comment]
close it since it is fixed in #13518
