### ISSUE TITLE
Collision filtering (physics2d) should be cleaned and improved

### ISSUE THREAD

**Issue by Dredok** [cocos2d/cocos2d-x#13278]
From what I see on the code, right now there are no collision filtering performed by chipmunk. If you look here:
https://chipmunk-physics.net/release/ChipmunkLatest-Docs/#cpShape-Filtering

You will see the recommended way to perform filtering is to tell chipmunk the CategoryMask via cpShapeFilter. 
Right now the collision filtering is performed after chipmunk has done the physics calculations, and it is expensive.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@Dredok
