### ISSUE TITLE
cocostudio memory leak

### ISSUE THREAD

**Issue by pkxpp** [cocos2d/cocos2d-x#13282]
cocos2cx version: 3.2
cocostudio version: 1.6
desc:
(1) make a empty ui(just a panel with green color) with studio
(2) add this layout to a scene, and set touchevent.when touch this panel , add the same ui to this layout
(3) when touch the second layout, removeself
(4) result is: when add the second layout, the memory is increasing, but when i move it. the memory doesn't decrease

**Comment by pkxpp** [comment]
I use vld check, the result is: \cocos2d-x\cocos\base\objectfactory.cpp (104): demo.exe!cocos2d::ObjectFactory::registerType + 0x37 bytes

**Comment by pandamicro** [comment]
Hi, the 1.6 version is no longer in active maintenance, can you upgrade your project to v2.x ?

**Comment by pkxpp** [comment]
= =
