### ISSUE TITLE
lua mode ERROR

### ISSUE THREAD

**Issue by colamax** [cocos2d/cocos2d-x#1330]
create a lua mode 
libs/extensions/netowrk/HttpClinet.cpp  :36  #include "curl/curl.h"  file not found 

^-^ ??

**Comment by nikhildhamsaniya** [comment]
hey did you find anything?? it seems in basic template as well for xcode 4

**Comment by colamax** [comment]
libs/extensions/netowrk/HttpClinet.cpp 
line:36 

#include "curl/curl.h" file not found
