### ISSUE TITLE
v3.7 win32 Node::visit() causes crash if called before Scene is rendered for the first time

### ISSUE THREAD

**Issue by kingchimp** [cocos2d/cocos2d-x#13322]
Hi,

I've found that calling visit() on a Sprite (or node I guess) before the associated scene is rendered for the first time causes a crash. This appears to be because visit() attempts to use _visitingCamera which is not initialised before render() is called on the scene for the first time. This is a problem because you now cannot draw to a rendertexture using visit() when initializing a layer for your scene, before the scene actually starts rendering. This affects win32 but may affect other platforms also. In v3.6 my code did not cause an error when using visit() to draw to a rendertexture before the scene starts.

To reproduce, add the following to HelloWorld::init() in the standard project created by cocos:

```
auto testSprite = Sprite::create("CloseNormal.png");
testSprite->visit();
```

In the debugger you can see the following at CCRenderer.cpp line 1043:

```
Vec2 v2p = Camera::getVisitingCamera()->projectGL(v3p);
```

getVisitingCamera returns NULL.

As a workaround the following can be used to initialise _visitingCamera when the scene is created. Add this after scene->create():

```
scene->getDefaultCamera()->initDefault();
scene->getDefaultCamera()->onEnter();
scene->initCamera();
```

Implementation of initCamera() in CCScene.cpp:

```
void Scene::initCamera()
{
    auto director = Director::getInstance();
    Camera* defaultCamera = nullptr;
    const auto& transform = getNodeToParentTransform();
    if (_cameraOrderDirty)
    {
        stable_sort(_cameras.begin(), _cameras.end(), camera_cmp);
        _cameraOrderDirty = false;
    }

    for (const auto& camera : _cameras)
    {
        if (!camera->isVisible())
            continue;

        Camera::_visitingCamera = camera;
        if (Camera::_visitingCamera->getCameraFlag() == CameraFlag::DEFAULT)
        {
            defaultCamera = Camera::_visitingCamera;
        }

        director->pushMatrix(MATRIX_STACK_TYPE::MATRIX_STACK_PROJECTION);
        director->loadMatrix(MATRIX_STACK_TYPE::MATRIX_STACK_PROJECTION, Camera::_visitingCamera->getViewProjectionMatrix());
        camera->apply();
        //clear background with max depth
        camera->clearBackground(1.0);

        director->popMatrix(MATRIX_STACK_TYPE::MATRIX_STACK_PROJECTION);
    }

#if CC_USE_3D_PHYSICS && CC_ENABLE_BULLET_INTEGRATION
    if (_physics3DWorld && _physics3DWorld->isDebugDrawEnabled())
    {
        director->pushMatrix(MATRIX_STACK_TYPE::MATRIX_STACK_PROJECTION);
        director->loadMatrix(MATRIX_STACK_TYPE::MATRIX_STACK_PROJECTION, _physics3dDebugCamera != nullptr ? _physics3dDebugCamera->getViewProjectionMatrix() : defaultCamera->getViewProjectionMatrix());
        director->popMatrix(MATRIX_STACK_TYPE::MATRIX_STACK_PROJECTION);
    }
#endif

    //Camera::_visitingCamera = nullptr;
    //experimental::FrameBuffer::applyDefaultFBO();
}
```

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@kingchimp
