### ISSUE TITLE
CCControl touch priority bug

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#1332]
This is still not fixed in the repo.

Pls check http://cocos2d-x.org/boards/6/topics/12092

Fix Summary:

```
//In the init method
m_nDefaultTouchPriority = 1;
this->setDefaultTouchPriority(m_nDefaultTouchPriority);

//And in the overrided registerWithTouchDispatcher method
CCDirector::sharedDirector()->getTouchDispatcher()->addTargetedDelegate(this, m_nDefaultTouchPriority , true);
```

**Comment by godyZ** [comment]
@hermanjakobi Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2681
