### ISSUE TITLE
cocos2d-x getNumberOfRunningActions does not decrement when pause() is used ?

### ISSUE THREAD

**Issue by algenepulido** [cocos2d/cocos2d-x#13341]
I think there is a problem here. If getNumberOfRunningActions does not decrement when we use pause(), the method name should be getNumberOfActions(). I'm a bit afraid if it will change later, that it will decrement the number of running actions when pause() is used.. 

It's misleading I think...

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@ginealgames
