### ISSUE TITLE
Cannot use --advanced to publish web with certain library such as socketio and underscore

### ISSUE THREAD

**Issue by 0xJimmyBeh** [cocos2d/cocos2d-x#13350]
Hi,

There is problem when using command below to publish web version.
`cocos compile -p web -m release --advanced`

The website is working without using `--advanced`

When include socketio module, website will return error `Uncaught TypeError: Cannot read property 'push' of undefined`

> "modules": ["cocos2d","socketio"],

The error point to this code `push("websocket")` in game.min.js

There is errors when using underscore.js library too with `--advanced`

In the Closure Compiler FAQ
https://github.com/google/closure-compiler/wiki/FAQ#i-want-to-use-advanced-optimizations-but--jquery-yui-underscore-prototype-js-library-foo--does-not-work-with-them-what-do-i-do

It suggest to use externs file which i found here but i don't know how to pass in.
https://raw.githubusercontent.com/google/closure-compiler/master/contrib/externs/underscore-1.4.4.js

How can we pass externs files to the compiler command with `--advanced`?
`cocos compile -p web -m release --advanced`

Thanks.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@Zinitter
