### ISSUE TITLE
热更新中断，继续更新挂掉

### ISSUE THREAD

**Issue by wishes2018** [cocos2d/cocos2d-x#13362]
断线续传的时候
AssetsManagerEx::startUpdate
->
_tempManifest->genResumeAssetsList(&_downloadUnits);
由于未标记下载完成状态，导致整个列表全部下载。
并且由于目录未创建，导致出错.

好奇的是，既然有把其他未更新资源设置下载完成：
_tempManifest->setAssetDownloadState(key, Manifest::DownloadState::SUCCESSED);
为什么不把它写回文件？

**Comment by zilongshanren** [comment]
@pandamicro  please take a look at it.

**Comment by lovekankan** [comment]
我这AssetsManagerEx一直都不支持断点续传，if (_supportResuming && unit.resumeDownload) {...}  _supportResuming值都是false。

**Comment by jianglong0156** [comment]
already fix:https://github.com/cocos2d/cocos2d-x/pull/13717
