### ISSUE TITLE
ProgressTimer setPercentage时描绘错误

### ISSUE THREAD

**Issue by jigelang** [cocos2d/cocos2d-x#13389]
在创建一个ProgressTimer之后 类型为 RADIAL   setPercentage(100.f) 再setReverseDirection(true); 然后每隔一秒更新一次ProgressTimer的percentage，总共更新30次，在前4秒中描绘会出问题，但是如果将setReverseDirection(true); 放到setPercentage(100.f)之前  描绘时不会出错

**Comment by zilongshanren** [comment]
What's the error message?
