### ISSUE TITLE
Cc.sys.localStorage App crash Cocos2d-js 3.6 in iOS 7.1.1 version

### ISSUE THREAD

**Issue by GurudathTS** [cocos2d/cocos2d-x#13384]
When we use Cc.sys.localStorage method in a game, App getting crash when game is running on device iOS 7.1.1 version. We have used Cocos2d-js 3.6. 

Error: 
TypeError: 'undefined' is not a function (evaluating 'cc.sys.localStorage.setItem(JSON.stringify("isAppLauchFirstTime"), JSON.stringify(value1))')

**Comment by zilongshanren** [comment]
@pandamicro  please take a look at this.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@GurudathTS
