### ISSUE TITLE
Xcode 7 beta 3 when compiling new project for iOS 7.3 on iphone 4 error: -fembed-bitcode is not supported on versions of iOS prior to 6.0

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#13390]
when creating new project with cocos console , loading it to xcode 7 beat 3 for iOS 7.3 on iphone 4  and trying to compile it im getting the link error:

```
clang: error: -fembed-bitcode is not supported on versions of iOS prior to 6.0
```

**Solution is :**
in xcode go to Build Options -> Enable Bitcode = No

**Comment by zilongshanren** [comment]
thanks. but I don't have a iPhone 4 at hand..

**Comment by meiry** [comment]
I have , also allot around me , it's still something that needs to be supported

**Comment by justbilt** [comment]
It helped me, thanks! @meiry

**Comment by meiry** [comment]
@justbilt  
You are welcome

**Comment by minggo** [comment]
i think bitcode is asked by apple, and cocos2d-x supports iOS 6.0+, so close it.
