### ISSUE TITLE
LuaJIT 2.0.4 lua iOS 64 load error

### ISSUE THREAD

**Issue by wulei** [cocos2d/cocos2d-x#13392]
android iphone4s is ok

iphone 5s,iphone 6 use lua code:
[LUA ERROR] load "/private/var/mobile/Containers/Bundle/Application/C2FD6099-14B6-4DF4-84BC-4F80139CE6E8/thunderGirl-mobile.app/src/main.lua", error: syntax error during pre-compilation.

**Comment by zilongshanren** [comment]
@dualface  please take a look at this issue.

**Comment by ZhaoTianze** [comment]
same error.
Version: cocos2d-x 3.6
When read a pre-compilation zip file on android, Mac is OK,
but " error: syntax error during pre-compilation" on iOS
Please fix it

**Comment by wulei** [comment]
@zilongshanren tech support is basic error, tsk
@ZhaoTianze i'm search a solution use luajit 2.1,but i'm not try it.

**Comment by ZhaoTianze** [comment]
When I use the cocos luacompile, I get this information.
"By using luacompile, you could precompile the Lua script files to the bytecode files and encrypt the Lua script files or the bytecode files by XXTEA.The mechanism of generating the bytecode files is based on the LuaJIT v2.0.3, so the generated bytecode files cann't be used on the 64-bit iOS devices."
The cocos2d-x 3.6 is not support 64-bit iOS devices?

**Comment by ZhaoTianze** [comment]
On the quick-x 2.2.6, I use lua-5.1.5 to compile my lua file. The compiled file could be used on the 64-bit iOS devices.
Is there a method to switch to lua-5.1.5 compile on Cocos2d-x 3.6?
@zilongshanren 
@dualface

**Comment by minggo** [comment]
now uses luajit 2.1.0-beta2, so close this issue
