### ISSUE TITLE
Xcode 7 beta 5: override function not marked override

### ISSUE THREAD

**Issue by seraphpl** [cocos2d/cocos2d-x#13395]
While building, many functions have this problem:

`override function not marked override`

**Comment by zilongshanren** [comment]
@seraphpl  What's your engine version?

**Comment by seraphpl** [comment]
@zilongshanren: It is `cocos2d-x-3.7.1`.

**Comment by zilongshanren** [comment]
@seraphpl  3.7.1 doesn't support XCode 7 well, we don't even put any effort to it.
You could try v3.8 with XCode 7.
If there are any issues, please ping me, thanks.

**Comment by seraphpl** [comment]
@zilongshanren Thanks for suggesting. I will try it.

**Comment by seraphpl** [comment]
@zilongshanren I have downloaded v3.8beta0, execute `setup.py`, `download-deps.py`.
The directory `tools/cocos2d-console` is empty. Cannot use `cocos` command.

**Comment by mogemimi** [comment]
This issue has already been fixed in #14062 and in #14162, so I think we can close it.
