### ISSUE TITLE
AutoPolygon's copy contructor

### ISSUE THREAD

**Issue by lucbloom** [cocos2d/cocos2d-x#13405]
In PolygonInfo::PolygonInfo(const PolygonInfo& other),
isVertsOwner = other.isVertsOwner;

Shouldn't that be
isVertsOwner = true;

Because it allocates new memory, which should be released in
PolygonInfo::releaseVertsAndIndices

**Comment by zilongshanren** [comment]
@fusijie please take a look at this issue.

**Comment by fusijie** [comment]
@lucbloom Thanks, I have fixed it.
