### ISSUE TITLE
CC_SYNTHESIZE giving syntax error

### ISSUE THREAD

**Issue by afrazizid** [cocos2d/cocos2d-x#1340]
I am using cocos2dx for android and I have added the following line above 
# include "cocos2d.h"

using namespace cocos2d;

now i am getting syntax error on using using CC_SYNTHESIZE macros the following line is giving syntax error

CC_SYNTHESIZE(bool, isWish,IsSWish);

CCARRAY_FOREACH and CCDICT_FOREACH also give error.

where are in the same file all other macros work perfectly fine such as 

CC_SAFE_DELETE(pElement); //where pElement is a CCDictElement 

please let me know if i am missing something. thanks in advance :)

**Comment by ivzave** [comment]
Please show how do you use them.

**Comment by afrazizid** [comment]
i use CC_SYNTHESIZE as following 

CC_SYNTHESIZE(bool, isWish,IsSWish);

the project compiles successfully but yellow question mark appear in eclipse showing "syntax error"

for now please help me resolve this. we can

**Comment by afrazizid** [comment]
i am using CCDICT_FOREACH as following 

```
CCDictElement* pElement = NULL;


CCDICT_FOREACH(dictionary, pElement)
{
    CCSprite* pSubClassObj = (CCSprite*)pElement->getObject();

    std::string oneStrKey = pElement->getStrKey(); // if the key type is string.

    CCSprite * sprite  = (CCSprite*)dictionary->objectForKey(oneStrKey);
    sprite->setVisible(false);
}
```

but it does not recognise the CCDICT_FOREACH macro. further more if i run the same code in XCode project of cocos2dx. This code give no error. It appears to me that there is some linking issue. While in Eclipse in the same  file when i use CCStringMake it works perfectly fine this means that i have latest cocos2dx version. I can't figure out why CCDICT_FOREACH is not working. Please help. Thanks in advance :)

**Comment by ivzave** [comment]
Make sure you include "cocos2d.h" before any macro usage (and before including your headers that probably use that macro).

Since your project compiles successfully it's not cocos2d-x issue, but eclipse one. Probably index gone obsolete. You can turn it off and on in c++ indexer settings to rebuild.

**Comment by afrazizid** [comment]
thanks for quick response. This is really helpful. Actually developing the android version of existing iOS code base. At the same time I am using the latest version of cocos2d for android version. 

I need help regarding open gl code as well. The following code is giving error because it is not recognizing gl APIs I have added the error ine by line

```
glPushMatrix(); //ERROR: 'glPopMatrix' was not declared in this scope
glTranslatef(x, y, 0.0); //ERROR: 'glPopMatrix' was not declared in this scope

float angle = 360.0 / sparkleNum;

int idx, opacity;
idx = index % FIREWORK_TYPE_NUM;

opacity = (1.0 - step) * 255;

for(int i = 0; i < sparkleNum; ++i)
{
    glPushMatrix();
    glRotatef(i * angle, 0.0, 0.0, 1.0); //ERROR: 'glPopMatrix' was not declared in this scope
    glTranslatef(0.0, dist, 0.0);
    glScalef(scalar, scalar, scalar);//ERROR: 'glPopMatrix' was not declared in this scope

    firework[idx]->setOpacity(opacity);
    firework[idx]->draw();

    glPopMatrix(); //ERROR: 'glPopMatrix' was not declared in this scope
}

glPopMatrix(); //ERROR: 'glPopMatrix' was not declared in this scope
```

P.S. the above code runs perfectly fine in XCode project and obvious I have included #include "cocos2d.h" and using namespace cocos2d; on the top. Thanks

**Comment by minggo** [comment]
Gles2.0 doesn't have these functions, try to use kazmath instead.

**Comment by afrazizid** [comment]
minggo thank you very much for you help. I really appreciate that. Adding kazmath libraray resolve most of the gl issue except following three GL Appis. 

glColorPointer(4, GL_UNSIGNED_BYTE, 0, colors);
glVertexPointer(2, GL_FLOAT, 0, vertices);
glTexCoordPointer(2, GL_FLOAT, 0, spotTexcoord);

these three APIs still give error. If i resolved this I think i will be good to go. Thanks in advance :)

**Comment by afrazizid** [comment]
sorry my bad i did'nt include the gl.h file. Thanks you all it was great help. \m/

**Comment by donaldalanmorrison** [comment]
@afraz-confiz Is this issue resolved?

**Comment by afrazizid** [comment]
thanks the issue has been resolved. cheers! :)

**Comment by donaldalanmorrison** [comment]
@afraz-confiz You can click the Close Button. :)

**Comment by afrazizid** [comment]
oh sorry!
