### ISSUE TITLE
CC_SPRITE_DEBUG_DRAW does nothing in Cocos2d-x 3.7

### ISSUE THREAD

**Issue by grimtastic** [cocos2d/cocos2d-x#13454]
I set CC_SPRITE_DEBUG_DRAW to 1 and to 2 and it does nothing. Not sure if there is something else I have to do but this looks like a bug.

From what I can tell, in 3.6 the DrawNode used to draw the outline of sprites is refreshed during each draw call, so it always uses the latest vertex data when drawing the outline. In 3.7, the DrawNode is created and set once. Unfortunately this is done in the constructor of the Sprite before texture data is set, so the triangle count is always 0 and no outline is drawn.

Calling `debugDraw(true);` immediately after `_polyInfo.setQuad(&_quad);` works for me, surrounded by `#if CC_SPRITE_DEBUG_DRAW` of course.

**Comment by fusijie** [comment]
Yes, It has already broke the compatibility. I'll fix it in next version(v3.9). Thanks for your feedback.

**Comment by fusijie** [comment]
My opinion is **remove debugDraw method**, and restore to the status of v3.6.
v3.7 introduced debugDraw method, debugDraw just draw the sprite frame once no matter how the sprite     transform after that, and break the compatibility, it is not a good idea, 
@zilongshanren @pandamicro Any thoughts?
