### ISSUE TITLE
Optimize the bindings-generator tool

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#13468]
- [ ] Should support lambda in Lua bindings (@dualface can you take a look) 
- [ ] The return value is Object value, it would trigger the compile error.
- [ ] If the functions of class are limited by the macro, the binding function have get the macro limit.
- [ ] Make tools search the dependent library path automatically
- [ ] Make the enum class be generated automatically (Configurable)
- [ ] Add record of deprecated functions
- [ ] Record the binding function that have parse error
- [ ] Should support the include conversional heads files of different module by configure

Migrated from: https://github.com/cocos2d/cocos2d-x/issues/9958

**Comment by wulei** [comment]
@pandamicro @dualface 
please see lua iOS 64-bit load error #13392 
tks
