### ISSUE TITLE
[3.8] ListView has wrong behaviour by default 

### ISSUE THREAD

**Issue by TheCodez** [cocos2d/cocos2d-x#13472]
In cpp-tests the listview shows the last items by default , so the user has to scroll up everytime to see the top items. The behaviour should be the other way around and should show the top items first.

This is shown when opening the UIListViewTest:
![wrong](https://cloud.githubusercontent.com/assets/4009589/9358991/29876848-468f-11e5-8ac2-77263531746f.PNG)

This should be shown instead:
![right](https://cloud.githubusercontent.com/assets/4009589/9359011/402c6f26-468f-11e5-92de-c6267d7df4e5.PNG)

**Comment by zilongshanren** [comment]
@TheCodez 
Thanks for reporting, I will fix it.

**Comment by zilongshanren** [comment]
fixed at  https://github.com/cocos2d/cocos2d-x/pull/13499

**Comment by neokim** [comment]
This was on the top of my action item list. Thanks!
