### ISSUE TITLE
Some #define incorrect in CCControlButtonLoader.cpp?

### ISSUE THREAD

**Issue by maxwzg** [cocos2d/cocos2d-x#1349]
In the CCControl.h ,   CCControlStateDisabled   is    CCControlStateDisabled     = 1 << 2 ,
so CCControlStateDisabled  equals 4,

but in CCControlButtonLoader.cpp, Some define is:
# define PROPERTY_TITLE_DISABLED "title|3"
# define PROPERTY_TITLECOLOR_DISABLED "titleColor|3"
# define PROPERTY_TITLETTF_DISABLED "titleTTF|3"
# define PROPERTY_TITLETTFSIZE_DISABLED "titleTTFSize|3"
# define PROPERTY_BACKGROUNDSPRITEFRAME_DISABLED "backgroundSpriteFrame|3"

Perhaps should be:
# define PROPERTY_TITLE_DISABLED "title|4"
# define PROPERTY_TITLECOLOR_DISABLED "titleColor|4"
# define PROPERTY_TITLETTF_DISABLED "titleTTF|4"
# define PROPERTY_TITLETTFSIZE_DISABLED "titleTTFSize|4"
# define PROPERTY_BACKGROUNDSPRITEFRAME_DISABLED "backgroundSpriteFrame|4"

**Comment by maxwzg** [comment]
I was wrong,
Please Ignore this issue.

**Comment by donaldalanmorrison** [comment]
@maxwzg  You can click the Close Button down at the bottom. :-)
