### ISSUE TITLE
TMX, vertical camera cull not working properly

### ISSUE THREAD

**Issue by Cybertwip** [cocos2d/cocos2d-x#13503]
Only horizontal parallax seems to be working properly, and it seems that it takes in consideration only design size from the origin. 

The first map works fine but after scrolling down the camera culls everything but sprites, the second map starts a bit down from the origin and it simply does not render at all. If we move forward only sprites are rendered.

First map:
![parallax1](https://cloud.githubusercontent.com/assets/8097385/9401562/95a7c306-478e-11e5-84ff-7f9f85e403c7.PNG)
![parallax2](https://cloud.githubusercontent.com/assets/8097385/9401555/953a4268-478e-11e5-88e6-da9d4eac417c.PNG)
![parallax3](https://cloud.githubusercontent.com/assets/8097385/9401557/9545d966-478e-11e5-9a15-0a1d9d59edbb.PNG)
![tmx](https://cloud.githubusercontent.com/assets/8097385/9401556/953f8a98-478e-11e5-8ec1-d822eb7aadcd.PNG)

Second map:
![night1](https://cloud.githubusercontent.com/assets/8097385/9401559/9556715e-478e-11e5-8584-5b0da2efb090.PNG)
![night2](https://cloud.githubusercontent.com/assets/8097385/9401558/954f44b0-478e-11e5-81b1-ecf8fb6a9a1e.PNG)
![night3](https://cloud.githubusercontent.com/assets/8097385/9401560/9572bed6-478e-11e5-8a16-91fcadf9295b.PNG)

**Comment by fusijie** [comment]
What's your Cocos2d-x version?
Could you please test this pr: https://github.com/cocos2d/cocos2d-x/pull/13105?

**Comment by Cybertwip** [comment]
I cloned directly from the v3 branch, yesterday. I believe the pr is already merged.  I'm setting the anchor point for the TMXTiledMap to be 0, 1 and initial position display.left_top, no further movement done to the map, only to the camera.

**Comment by fusijie** [comment]
Could you change following code to NewRendererTest -> BugAutoCulling::BugAutoCulling()

``` cpp
BugAutoCulling::BugAutoCulling()
{
    Size s = Director::getInstance()->getWinSize();
    auto fastmap = cocos2d::experimental::TMXTiledMap::create("TileMaps/orthogonal-test2.tmx");
    this->addChild(fastmap);
    for (int i = 0; i < 30; i++) {
        auto sprite = Sprite::create("Images/grossini.png");
        sprite->setPosition(s.width/2 + s.width/10 * i, s.height/2);
        this->addChild(sprite);
        auto label = Label::createWithTTF(TTFConfig("fonts/arial.ttf"), "Label");
        label->setPosition(s.width/2 + s.width/10 * i, s.height/2);
        this->addChild(label);
    }

    this->scheduleOnce([=](float){
        auto camera = Director::getInstance()->getRunningScene()->getCameras().front();
        camera->setPosition(camera->getPosition() + Vec2(0, s.height));
        auto move  = MoveBy::create(2.0, Vec2(0, -s.height));
        camera->runAction(RepeatForever::create(Sequence::create(move, move->reverse(),nullptr)));
    }, 1.0f, "lambda-autoculling-bug");
}
```

Is the effect you wanted? Or could you reproduce the bug through this test case?

**Comment by Cybertwip** [comment]
I did, but what it seems is that the map is not rendering at all. Scrolling works and also perfectly with the built-in test map used by BugAutoCulling, but when loading a larger tileset this is what happens.

I've done an horizontal MoveBy to see how many tiles got rendered and when moving there is only a thin line of them.

![bugauto](https://cloud.githubusercontent.com/assets/8097385/9420999/44bfc27c-4829-11e5-9193-e279e5d7cf1c.PNG)

![bugauto2](https://cloud.githubusercontent.com/assets/8097385/9421025/9546556c-4829-11e5-8217-b057b9023dc4.PNG)

``` c++
BugAutoCulling::BugAutoCulling()
{
    Size s = Director::getInstance()->getWinSize();
    auto fastmap = cocos2d::experimental::TMXTiledMap::create("TileMaps/orthogonal-test2.tmx");

    fastmap->setAnchorPoint(cocos2d::Vec2(0, 1));
    fastmap->setPosition(0, s.height);

    this->addChild(fastmap);

    this->scheduleOnce([=](float){
        auto camera = Director::getInstance()->getRunningScene()->getCameras().front();
        camera->setPosition(Vec2(s.width * 0.5, s.height * 0.5));
        auto move = MoveBy::create(8.0, Vec2(s.width * 4, 0));
        camera->runAction(RepeatForever::create(Sequence::create(move, move->reverse(),nullptr)));
    }, 1.0f, "lambda-autoculling-bug");
}

```

These are the data assets I'm using for the test:

![level_vineman_bank](https://cloud.githubusercontent.com/assets/8097385/9421096/ac8dc678-482a-11e5-88ce-9539e1cc312d.png)

https://gist.github.com/VictorJL/908cef96ecef92e50dfb

**Comment by Cybertwip** [comment]
The tiled map used does not have any    

```
<tile gid="0"/>
```

instead it has a reference to a tile in the texture 

```
<tile gid="29"/>
```

Which has an alpha value of 0. 

I believe that with this code:

``` c++
    for (int y =  yBegin; y < yEnd; ++y)
    {
        for (int x = xBegin; x < xEnd; ++x)
        {
            int tileIndex = getTileIndexByPos(x, y);
            if(_tiles[tileIndex] == 0) continue; // needs to verify alpha value first.

            int vertexZ = getVertexZForPos(Vec2(x,y));
            auto iter = _indicesVertexZNumber.find(vertexZ);
            int offset = iter->second;
            iter->second++;

            int quadIndex = _tileToQuadIndex[tileIndex];
            CC_ASSERT(-1 != quadIndex);
            _indices[6 * offset + 0] = quadIndex * 4 + 0;
            _indices[6 * offset + 1] = quadIndex * 4 + 1;
            _indices[6 * offset + 2] = quadIndex * 4 + 2;
            _indices[6 * offset + 3] = quadIndex * 4 + 3;
            _indices[6 * offset + 4] = quadIndex * 4 + 2;
            _indices[6 * offset + 5] = quadIndex * 4 + 1;

        } // for x
    } // for y
```

We shall verify alpha values of 0 used by empty tiles before rendering or setting up tiles from the TMX map. Does the TMX loader have any size limitation on the number of tiles to be drawn? After changing the transparent tile from 

```
   <tile gid="29"/>
```

to

```
   <tile gid="0"/>
```

The map loads perfectly.

![renderer](https://cloud.githubusercontent.com/assets/8097385/9422570/a38a7a86-4856-11e5-8a49-05be683d3f92.PNG)

The map is being created with ShoeBox, which extracts tiles from pictures automatically, third party but maybe this could be fixed in a future in the renderhjs tool, identified by software or automated by any TMX editing tool.
