### ISSUE TITLE
Strange behaviour of Scene in Cocos2d-x 3.6

### ISSUE THREAD

**Issue by rekrutik** [cocos2d/cocos2d-x#13517]
I see a strange thing when working with Scenes in Cocos2d-x. Any transformation of this container (e.g. moving, scaling, etc) shows that it's rendered twice: without transformations and with them as well.
Here's a simple graph of my example application:
globalScene (Scene) -> levelScene (a subclass of Scene) -> rootScene (a Scene to which my nodes are added)
And here's the code:

```
bool LevelScene::init() {
        if (!Scene::init()) {
            return false;
        }

        this->rootScene = Scene::create();

        auto square = Sprite::create("dirt.jpg");
        square->setPosition(Vec2(100, 100));

        this->rootScene->addChild(square);


        // some code from tutorials
        auto eventListener = EventListenerKeyboard::create();

        eventListener->onKeyPressed = [](EventKeyboard::KeyCode keyCode, Event* event){

        Vec2 loc = event->getCurrentTarget()->getPosition();
        switch (keyCode) {
        case EventKeyboard::KeyCode::KEY_LEFT_ARROW:
        case EventKeyboard::KeyCode::KEY_A:
            event->getCurrentTarget()->setPosition(--loc.x, loc.y);
            break;
        case EventKeyboard::KeyCode::KEY_RIGHT_ARROW:
        case EventKeyboard::KeyCode::KEY_D:
            event->getCurrentTarget()->setPosition(++loc.x, loc.y);
            break;
        case EventKeyboard::KeyCode::KEY_UP_ARROW:
        case EventKeyboard::KeyCode::KEY_W:
            event->getCurrentTarget()->setPosition(loc.x, ++loc.y);
            break;
        case EventKeyboard::KeyCode::KEY_DOWN_ARROW:
        case EventKeyboard::KeyCode::KEY_S:
            event->getCurrentTarget()->setPosition(loc.x, --loc.y);
            break;
        }
    };

    _eventDispatcher->addEventListenerWithSceneGraphPriority(eventListener, this->rootScene);

    this->addChild(rootScene);

    return true;
}
```

And here's the result:
When the scene hasn't been moved yet (everything is fine):
![cc1](https://cloud.githubusercontent.com/assets/6683515/9410424/cba360ba-4828-11e5-9204-08a7c41c8b74.png)
...and when it has:
![cc2](https://cloud.githubusercontent.com/assets/6683515/9410436/dd4eac84-4828-11e5-9223-dd5b35b191c6.png)
Also, everything works as it should do when I use Layers/Nodes instead of Scenes, but I need using Scenes because of physics support.
I hope I'm not the only one having troubles with it, and this problem is already solved (I can't test it with 3.7 by now).

**Comment by TheCodez** [comment]
@rekrutik You can also use layers with physics.

**Comment by rekrutik** [comment]
@TheCodez But I have to update the position of all layer's child nodes by myself then, don't I?

**Comment by TheCodez** [comment]
No not really. You just create a scene with physics `Scene::createWithPhysics()` and attach your layer to that, which has for example sprites with physicsbodies as children.

**Comment by rekrutik** [comment]
@TheCodez Wow, thanks a lot! Now I finally got it working.

**Comment by TheCodez** [comment]
No problem ;)
