### ISSUE TITLE
thumb display wrong in CCControlSwitch

### ISSUE THREAD

**Issue by Nicholas-Shen** [cocos2d/cocos2d-x#1351]
if two or more CCControlSwitch in one page, the thumbSprite will not display "extensions/switch-thumb.png".

**Comment by Nicholas-Shen** [comment]
for more additional information, see the picture : http://xiangce.baidu.com/picture/detail/b511c7f6471a899e59d307d283bfe95c77084ded

**Comment by ghost** [comment]
That's right. Looks like if you rename the PNG to another name - it works ! Strange. TextureCache bug?

**Comment by godyZ** [comment]
@Nicholas-Shen Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2680
