### ISSUE TITLE
[3.8] ListView has rendering bug when calling setScrollBarAutoHideEnabled(false)

### ISSUE THREAD

**Issue by TheCodez** [cocos2d/cocos2d-x#13516]
When calling `setScrollBarAutoHideEnabled(false)`, ListView doesnt shows the scrollbar right away, instead its showing the scrollbars circle in the bottom left corner. This goes away when scrolling because then the real scrollbar becomes visible on the right side.

![artifact](https://cloud.githubusercontent.com/assets/4009589/9406244/f44a7104-47fe-11e5-9386-db4b1096306b.PNG)
![res](https://cloud.githubusercontent.com/assets/4009589/9412878/b66acf02-482e-11e5-94f2-f861c2f3ccfc.PNG)

**Comment by neokim** [comment]
Fixed at #13537.

@zilongshanren Please don't hesitate to mention me on any ScrollView related issues. I'll try to handle them.

**Comment by zilongshanren** [comment]
@neokim  :+1: 
Great

**Comment by TheCodez** [comment]
@neokim
I also noticed that the scrollbars circle gets really blurry the larger the width is

**Comment by zilongshanren** [comment]
Hi, @TheCodez
Does the fixes work for you?

**Comment by TheCodez** [comment]
@zilongshanren Yes, it works without a problem :+1:

**Comment by neokim** [comment]
@TheCodez The circle is not intended for big scroll bar. The diameter is only 12 pixel. How big do you use it?

**Comment by TheCodez** [comment]
Ok good to know, I set it to 16, but also at 12 pixel width it's still a bit pixelated.
