### ISSUE TITLE
[3.0] Clang (3.8) Build fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by DanielBelow** [cocos2d/cocos2d-x#13526]
Using clang3.8 on Ubuntu 15.04 a clean build fails with the following error:

In file included from [...]/cocos2d-x/cocos/base/allocator/CCAllocatorGlobal.h:31:
[...]/cocos2d-x/cocos/base/allocator/CCAllocatorStrategyDefault.h:45:16: error: use of undeclared identifier 'malloc'
        return malloc(size);
               ^
[...]/cocos2d-x/cocos/base/allocator/CCAllocatorStrategyDefault.h:51:13: error: use of undeclared identifier 'free'
            free(address);
            ^
2 errors generated.

I did install all dependencies and updated submodules. 

Including cstdlib in the CCAllocatorStrategyDefault.h file did fix the problem for me.

**Comment by zilongshanren** [comment]
@Tehlyria  
The minimal GCC version is 4.9, please give it a try.

**Comment by DanielBelow** [comment]
@zilongshanren 

gcc -v 
-- gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) 

I'm building with clang though.
clang -v
-- clang version 3.8.0 (trunk 242676)

**Comment by zilongshanren** [comment]
@Tehlyria 
Clang is not tested on the Linux platform. So you should switch to GCC.

**Comment by man2** [comment]
I too have problem with clang on linux. I think it should be supported, because the compile time is so much faster with clang compared to gcc

**Comment by pandamicro** [comment]
Hi, @man2 Linux is not our focusing platform, so we can't spend too much time on it, we have a small group size and we must focus on what is important for most of our users. So I'm sorry we can't improve it recently, I'm closing it.
