### ISSUE TITLE
need to rename AVAudioPlayer to avoid conflicting with system framework: AVFoundation.framework

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#13522]
cocos2d-x team,

Please rename your version of AVAudioPlayer to CCAVAudioPlayer, to avoid conflicting with the version of AVAudioPlayer in the system framework : AVFoundation.framework . This is easily reproducible by doing a Mac build.

After a successful Mac build, when you run the newly built Mac app, the following warning message appears:
Class AVAudioPlayer is implemented in both /System/Library/Frameworks/AVFoundation.framework/Versions/A/Resources/libAVFAudio.dylib and [the newly built desktop app].. One of the two will be used. Which one is undefined.

From looking at the cocos2d-x source code, it's implementing the class AVAudioPlayer. The conflict must be occurring because AVFoundation.framework must also be definining it's _own_ AVAudioPlayer\* class. 

```
cocos/audio/mac/CDXMacOSXSupport.h
26: A set of proxy classes to allow iOS audio code to run on MacOS X. AVAudioPlayer is implemented using NSSound.
30: AVAudioPlayer numberOfLoops not correctly supported.  Looping is either on or off, can not specify a specific number of loops.
31: AVAudioPlayer panning not supported.
32: AVAudioPlayer metering not supported.
57: Based on AVAudioPlayer.h header in AVFoundation headers
60:@protocol AVAudioPlayerDelegate;
63:@interface AVAudioPlayer : NSObject <NSSoundDelegate> {
```

**Comment by pandamicro** [comment]
@WenhaiLin Please fix it

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/13698
