### ISSUE TITLE
ISO C++ violation

### ISSUE THREAD

**Issue by GavinBIC** [cocos2d/cocos2d-x#1356]
In file included from ../../extensions/CCBReader/CCNodeLoader.h:6:0,
                 from ../../extensions/CCBReader/CCBFileLoader.h:4,
                 from ../../extensions/CCBReader/CCBFileLoader.cpp:1:
../../extensions/CCBReader/CCBReader.h: At global scope:
../../extensions/CCBReader/CCBReader.h:238:30: error: ISO C++ forbids initialization of member ‘hasScriptingOwner’ [-fpermissive]
../../extensions/CCBReader/CCBReader.h:238:30: error: making ‘hasScriptingOwner’ static [-fpermissive]
../../extensions/CCBReader/CCBReader.h:238:30: error: ISO C++ forbids in-class initialization of non-const static member ‘hasScriptingOwner’
make: **\* [../../extensions/CCBReader/CCBFileLoader.o] Error 1

**Comment by minggo** [comment]
I think i fixed this issue.
You can get latest codes and have a try.

Thank you.

**Comment by GavinBIC** [comment]
great! thanks.
