### ISSUE TITLE
Scale9Sprite draw extra 1 pixel when creating from spritesheet

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#13564]
This issue was reported by developers from Chinese forum.
He found that when creating Scale9Sprite from spritesheet and the resulting Scale9Sprite will draw extra 1 pixel from other spriteframe.  

He also proposed a solution:

```
Vec2 offsetPosition(ceil(_offset.x + (_originalSize.width - _spriteRect.size.width) / 2),
                            ceil(_offset.y + (_originalSize.height - _spriteRect.size.height) / 2));
```

should be changed to 

```
Vec2 offsetPosition(floor(_offset.x + (_originalSize.width - _spriteRect.size.width) / 2),
                            floor(_offset.y + (_originalSize.height - _spriteRect.size.height) / 2));
```

Chinese forum:

http://www.cocoachina.com/bbs/read.php?tid=320932&page=1&toread=1#1376926

and 

his blog:

http://www.cnblogs.com/songcf/p/4755193.html

**Comment by zilongshanren** [comment]
@newnon  
I remember that the `ceil` function was added by you.
Thoughts?  How about changing ceil to floor?

Thanks.

**Comment by newnon** [comment]
I'm not sure it was long time ago. may be it is correct fix may be it will give some other artifacts

**Comment by zilongshanren** [comment]
@newnon
I agree with you. The offset and originalSize read from plist files will be divided by ContentScaleFactor which will cause some precision lose.

I still can't make sure the fix is correct but at least it resolve the developer's issue and all the tests are good now.

I will keep a an eye with it.

Thanks for reply.
