### ISSUE TITLE
TransitionPageTurn effect issue with contentScaleFactor.

### ISSUE THREAD

**Issue by anjandaffo** [cocos2d/cocos2d-x#13562]
I am using cocos2d-x version 3.7

I am setting the content scale factor from AppDelegate.cpp to support for all screen size. I used all resources of 2048*1536 size.

director->setContentScaleFactor(1536 / director->getWinSize().height);

design is perfect for all screen sizes.Issue with TransitionPageTurn,  if contentScaleFactor < 1.0 then out scene is cut from the top. For contentScaleFactor >=1.0 work fine.

For Example In Android Tablet 10 inch size of screen is 2560\* 1600 that for contentScaleFactor is 0.96. Here Issue is come that the out scene is cut from the top and InScene is correct. 

PFA attached file.
![screenshot_2015-08-25-17-53-03](https://cloud.githubusercontent.com/assets/12529102/9466684/48b4cef8-4b54-11e5-9d97-3964f0dfb869.png)

**Comment by pandamicro** [comment]
@fusijie  have improved page turn in v3.8, maybe your problem is fixed

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@anjandaffo
