### ISSUE TITLE
cocos2d::ui::Slider does not tak TextureResType into consideration

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-x#13575]
In UISlider.cpp, line 99

widget->loadBarTexture(barTextureName);
widget->loadSlidBallTextureNormal(normalBallTextureName);

should be changed to

widget->loadBarTexture(barTextureName, resType);
widget->loadSlidBallTextureNormal(normalBallTextureName, resType);

**Comment by zilongshanren** [comment]
@Birkemose  Good catch, thanks.
