### ISSUE TITLE
v3.8 Bug in scheduleOnce with delay parameter being 0.0

### ISSUE THREAD

**Issue by felixjingga** [cocos2d/cocos2d-x#13582]
When we use scheduleOnce with delay parameter being 0.0, the code inside the function is executed multiple times. this not happens in previous version.

**Comment by zilongshanren** [comment]
@yangws  @WenhaiLin 
Please take a look at this issue.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/13585

**Comment by man2** [comment]
nice!! :)
