### ISSUE TITLE
Make csb can use sprite from plist

### ISSUE THREAD

**Issue by felixjingga** [cocos2d/cocos2d-x#13583]
When we are using CSLoader and load a csb file. If the all the sprite inside the *.csb is added as a texture with cocos2d::SpriteFrameCache::getInstance()->addSpriteFramesWithFile(), the csb will fail to load and render the sprite.

**Comment by pandamicro** [comment]
You can actually create merged texture in Cocos Studio and generate the plist and png file, then it support loading it from CSLoader.

**Comment by felixjingga** [comment]
@pandamicro But currently cocos studio can't support passworded pvr.ccz. so I can't add the plist + pvr.ccz to the cocos studio, and freely use the sprite defined there. Is there in any way this will be implemented soon?

Thanks,

**Comment by pandamicro** [comment]
@chengstory Please take a look at this request

**Comment by felixjingga** [comment]
Hi, how about this one? temporary solution I use right now involves in editing some of the cocos2d-x source which is not pretty, because I use passworded pvr.ccz

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
