### ISSUE TITLE
Adding a namespace for actions and maybe UI nodes

### ISSUE THREAD

**Issue by seivan** [cocos2d/cocos2d-x#13597]
Maybe I'm doing it wrong, but it would it would be great to have either a namespace or some sort of a prefix for actions.
On Sprite-Kit, Apple solved it by adding all the actions on a single class as a static method. 

Obviously, that's to work around the fact that Obj-C is missing Namespaces, but I feel like C++ could solve that better.
At least making it easier to explore available node types, UI and Actions.

**Comment by pandamicro** [comment]
I don't really understand what's the benefit

**Comment by seivan** [comment]
The benefit would make the API cleaner and easier to find available actions. 
Right now there is no naming conventions of all the different types of actions, making it hard to find them.

With SpriteKit, every action falls under SKAction.
With Cocos2d (Obj-C) every action falls under CCAction
Obviously Obj-C doesn't have namespaces, so that's how they solve it.

In order to find and use all the actions, you either just glance at the header file or use autocomplete to find them all.

WIth Cocos2d-x this is much harder as they are all named differently and in separate files.

Sequence, DelayTimer, CallFunc.. there is no common ground between them other than inheritance. 

You see my point here? Cocos2d-x has an incredibly messy discoverability and even messier header files.

**Comment by pandamicro** [comment]
I see your point, @ricardoquesada what's your opinion ?

**Comment by milos1290** [comment]
I vote for this. It would be much easier to see what actions are available.

**Comment by ricardoquesada** [comment]
having a action factory-pattern could work (like in SK) ... but the old API must work.
I'm not neither against or for this option... I know that we can improve many parts of our API... but of these fixes either means:
- break backwards compatibility (we don't want this)
- or duplicates functionality (and there should only be one way of doing things in cocos2d).

**Comment by seivan** [comment]
I'm not a C++ expert, but I would guess there is a way to wrap the actions inside a namespace and still expose them outside?

So you could keep backwards compatibility 

``` c++
cocos2d::Sequence::create()
```

while still allowing a namespace for actions to make it easier to find actions. 

``` c++
cocos2d::Actions::Sequence::create()
```

Is that a possibility?

**Comment by ricardoquesada** [comment]
yes, it is possible to either put all actions in a namespace, or in a factory class. Both options have more or less the same pros and cons.

**Comment by seivan** [comment]
I don't see the cons here? That way backward compatibility still works, while you can get a list of all actions by checking under Actions namespace. 

That is, if it's possible at all to do what I suggested with c++ :)

**Comment by ricardoquesada** [comment]
the cons is that there should be only way way to do things, not three, not two, just one.
Imagine an API where there are multiple ways to do things... it would be confusing (which API should I use, A or B), more difficult to maintain (more documentation, more code to write)...
As the Zen of Python says:
`There should be one-- and preferably only one --obvious way to do it.`

**Comment by seivan** [comment]
I agree with that sentiment, I guess you're right.
Out of curiosity, what is the easiest/fastest/less typing way off adding my own namespace on top of all the available cocos2d-x actions?

**Comment by stevetranby** [comment]
I would think as set of `#define`s or possibly `typedef` or `using` would be the quickest way to do this for only yourself. I may be wrong, but I think the following would work for you in your precompiled header or a header you include wherever you need it.

```
namespace cocos2d {
    namespace actions {
        using CallFunc = cocos2d::CallFunc;
        using DelayTime = cocos2d::DelayTime;
    };
};
// I believe this will allow you to use them:
cocos2d::actions::DelayTime::create(0.5f);
// or
using namespace cocos2d;
actions::DelayTime::create(0.5f);
```
