### ISSUE TITLE
When the program exits, it may be possible to get a crash.

### ISSUE THREAD

**Issue by YangFeiFly** [cocos2d/cocos2d-x#13609]
Our games are developed using Lua. cocos version is 3.2.
Engine source code
virtual ~ApplicationProtocol(){
# if CC_ENABLE_SCRIPT_BINDING

```
    ScriptEngineManager::destroyInstance();
```
# endif

```
    /** clean auto release pool. */
    PoolManager::destroyInstance();
}
```

Modified code
virtual ~ApplicationProtocol(){
        // clean auto release pool
        PoolManager::destroyInstance();
# if CC_ENABLE_SCRIPT_BINDING

```
    ScriptEngineManager::destroyInstance();
```
# endif

```
}
```

**Comment by pandamicro** [comment]
Thanks, it's a known issue, but we haven't planned to solve it yet, it's low priority

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@YangFeiFly
