### ISSUE TITLE
why not run the simulation of physics3D by a new thread

### ISSUE THREAD

**Issue by xifengxi** [cocos2d/cocos2d-x#13606]
Cocos2d-x put too many tasks in the mainloop, like update, render and callback....

**Comment by pandamicro** [comment]
For now we don't have a multi thread design for Cocos, but it is a very important direction to improve our engine. And physics is the most suitable case to be put in another thread than the GL thread, I personally agree with you. We are now completing our 3D functionalities, so this kind of improvement is delayed to future plans.

@ricardoquesada @minggo @super626 @dabingnn thoughts?

**Comment by xifengxi** [comment]
yeah, Almost all of our phone haves a lot of core ,such as four-core, eight-core or even ten-core. And the performance of a core is getting lower and lower. thanks for your answer.~~~

**Comment by ricardoquesada** [comment]
@pandamicro 
Yes, what I think is that we should move to an Entity Component System, and have more Systems in cocos2d-x.
And physics should be one of those systems, and that system should run on its own thread.
