### ISSUE TITLE
why not AssetsManagerEx  class breakpoint continuingly function doesn't work

### ISSUE THREAD

**Issue by lovekankan** [cocos2d/cocos2d-x#13611]
When I use AssetsManagerEx class to update the resource, the breakpoint continuingly functions didn't effect。 The following code has been enforced。（unit.resumeDownload ----> this variable value is true）
           .....
           // Resuming download support
            if (_supportResuming && unit.resumeDownload)
            {
                // Check already downloaded size for current download unit
                long size = _fileUtils->getFileSize(storagePath + TEMP_EXT);
                if (size != -1)
                {
                    curl_easy_setopt(curl, CURLOPT_RESUME_FROM_LARGE, size);
                }
            }

**Comment by pandamicro** [comment]
In this case it did take effect, but we also find that the calculation of progression is taking account of the size already downloaded, so it shows always from 0 - 100.

Please watch this issue: https://github.com/cocos2d/cocos2d-x/issues/13729
