### ISSUE TITLE
Android EditText multiline issue.

### ISSUE THREAD

**Issue by anjandaffo** [cocos2d/cocos2d-x#13616]
When edittext is focussed then text is showing correct with scrolling. After focus loses If the no of line crossed the height of edittext then label of edittext going outside of edittext region. Attached screenshot describe you better.

![device-2015-08-28-155822](https://cloud.githubusercontent.com/assets/12529102/9544367/cb4fd0b0-4d9d-11e5-8334-968ab32b95db.png)

**Comment by anjandaffo** [comment]
I fixed issue by modify few line in setInactiveText(const char\* pText) method of UIEditBoxImpl-android.cpp and UIEditBoxImpl-ios.mm file.

old code:

float fMaxWidth = _editBox->getContentSize().width - CC_EDIT_BOX_PADDING \* 2;
Size labelSize = _label->getContentSize();
 if(labelSize.width > fMaxWidth) {
                        _label->setDimensions(fMaxWidth,labelSize.height);
}

changed it to:

float fMaxWidth = _editBox->getContentSize().width - CC_EDIT_BOX_PADDING \* 2;
float fMaxHeight = _editBox->getContentSize().height - CC_EDIT_BOX_PADDING \* 2;
Size labelSize = _label->getContentSize();
 if(labelSize.width > fMaxWidth || labelSize.height > fMaxHeight) {
            _label->setDimensions(fMaxWidth,fMaxHeight);
}

**Comment by WenhaiLin** [comment]
@zilongshanren

**Comment by zilongshanren** [comment]
@anjandaffo @WenhaiLin  
Thanks, I will fix the issue.

**Comment by zilongshanren** [comment]
@anjandaffo  please test it on v3.8 branch.
It is already fixed.
