### ISSUE TITLE
v3.8beta0 EventListenerTouchAllAtOnce events triggered for each camera (performance issue) 

### ISSUE THREAD

**Issue by jimrange** [cocos2d/cocos2d-x#13620]
There does not seem to be a practical reason to cycle through all cameras to dispatch EventDispatcher::dispatchTouchEventToListeners events.

Calling it once per camera seems to be unnecessary and inefficient.

Is there a reason for sending the event once per camera that I am missing?

EventDispatcher::dispatchTouchEventToListeners is cycling through all cameras on line 834 of CCEventDispatcher.cpp of Cocos2d-x 3.8 beta 0.

If you move a camera around or move/scale a node that is masked to a camera, there is no touch coordinate space translation or scale. The touch coordinates are always scaled and cropped per the design resolution settings and can be defined as VisibleRect.

```
Size visibleSize = Director::getInstance()->getVisibleSize();
Vec2 origin = Director::getInstance()->getVisibleOrigin();
_visibleRect = Rect(origin, visibleSize);
```

Example code to see this can be found here: https://github.com/jimrange/cocos2d-x-bugs/tree/designRes

e.g. on an iPhone 5, the touch space with the default no border policy in the HelloWorld results in a touch rect of: visibleRect:0.00,25.07,480.00,269.87.

So if I add 2 cameras to my game, e.g. parallax camera, game world camera, and use the default camera for the HUD, then I get three calls to the HUD's EventDispatcher::dispatchTouchEventToListeners  listener for each event.
e.g. Start a touch by pressing the screen and you will get three calls to onTouchesBegan, all with the identical coordinates.
onTouchesBegan
onTouchesBegan
onTouchesBegan

**Comment by milos1290** [comment]
https://github.com/cocos2d/cocos2d-x/commit/f8a5b
This commit introduce this bug and now touches are called like crazy. I have to revert now to 3.7.1 because of this.

Edit:
Temporary solution in my case is to add event->stopPropagation();

**Comment by pandamicro** [comment]
The reason of this change is for fixing this issue: http://discuss.cocos2d-x.org/t/found-bugs-when-composite-3d-2d-mixed-scene-by-moving-ui-and-the-camera-which-look-at-far-away/21907

The related github issue: https://github.com/cocos2d/cocos2d-x/issues/12626

I think the correct way is to stop propagation once you catch the event, because the system can tell the content in which camera should respond to the event.
@yangws
