### ISSUE TITLE
Canceling HttpRequest transfer

### ISSUE THREAD

**Issue by man2** [cocos2d/cocos2d-x#13621]
Is there a way to cancel/stop HttpRequest Transfer? Not just releasing the variable, but stopping the ongoing transfer. Like the stop button in the browser.

**Comment by dakabang** [comment]
Base on the source file HttpClient.cpp, there is no function to cancel a http request, but you can add a function to remove the quest from task queue

**Comment by man2** [comment]
do you have any more clues on how to do that? I also found this stackoverflow links
http://stackoverflow.com/questions/8415976/example-how-to-cancel-a-libcurl-request
http://stackoverflow.com/questions/4456180/how-can-i-immediately-cancel-a-curl-operation

From this documentation
http://curl.haxx.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html
we need to add CURLOPT_XFERINFOFUNCTION and return non zero integer to abort transfer process. Does it need to replace the current CURLOPT_WRITEFUNCTION? Or it can be just added to current options?

**Comment by dakabang** [comment]
you can stop the non-immediate request by removing the request from queue(already put  on the pull request), but your question is about the immediate send, it is a new thread which is start immediately, kill the thread can cause certain issues. I'll work on that

**Comment by man2** [comment]
I think it's enough to stop non-immediate request for me. I'll check your PR later today, thanks :)

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@man2 @dakabang
