### ISSUE TITLE
Suggest 3D model swaping

### ISSUE THREAD

**Issue by kybird** [cocos2d/cocos2d-x#13633]
is the cocos2d 3d functionality support the real reskin or remapping?
swap some part of model with another part

setVisible(true),(false) is not enough

**Comment by pandamicro** [comment]
@super626

**Comment by super626** [comment]
Thanks @kybird 
I can not understand what is real reskin or remapping in your mind.
In the PC game, we often split the player into many parts, head, body, and equipments. And then assemble them together. Do you mean this?
Cocos does not support this right now. But you can achieve this by exporting multiple fbx and assemble them together using attach node(see cpp-tests for detail). You can switch any parts during the game.
