### ISSUE TITLE
why my png represent different from the source file ?

### ISSUE THREAD

**Issue by jminht** [cocos2d/cocos2d-x#13638]
![diff](https://cloud.githubusercontent.com/assets/4132186/9578604/14fe4994-501e-11e5-93f1-e63e361cf0b7.PNG)

i open my file on the windows and add it in my game.
as you may see, they represent the different result.
is this normal ?

**Comment by RMariowski** [comment]
Yes, it is. You need to turn off anti-aliasing, if you want the same result. Check this: [setAliasTexParameters()](http://www.cocos2d-x.org/reference/native-cpp/V3.6/d0/d6a/classcocos2d_1_1_texture2_d.html#ada0eedff71e551f089727923a8c23513)

**Comment by jminht** [comment]
@Xandev 
Got it.
Does this only appear on windows?

**Comment by RMariowski** [comment]
It appears on every platform.
