### ISSUE TITLE
In CSLoader.cpp, change log level of a couple log messages or remove them altogether

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#13641]
Change log level of the messages below to CCLOGINFO or take them out altogether. These log messages clutter up the console output with information that is generally irrelevant to the end developer.

```
(near lines 990-998 of CSLoader.cpp:):
        CCLOG("size = %d", size);
            CCLOG("child = %p", child);
```

**Comment by horace-velmont** [comment]
Please eraze these logs....

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
