### ISSUE TITLE
v3.8:JS: ListView cannot insertCustomItem when item is layOut created cocostudio 2.3!

### ISSUE THREAD

**Issue by tungnt11** [cocos2d/cocos2d-x#13648]
I have some code: 
var jsonPath1 = '....';
var layOut1 = ccs.load(jsonPath);
var listView = ccui.helper.seekWidgetByName(this.layOut1 .node, 'listView');

var jsonPath2 = '....';
var layOut2 = ccs.load(jsonPath2);
<b>And error in line code:
listView.insertCustomItem(layOut2.node ,0);</b>
In cocos2dx C++ , it run well.

**Comment by pandamicro** [comment]
For web engine or native JSB engine ?

**Comment by tungnt11** [comment]
@pandamicro : For native JSB engine !

**Comment by ZhangMenghe** [comment]
@dimaria11 
Hi, I've tested your code and found it works proper.For the testcase you could refer to `UIlistViewTest`, in which we setup a new a layout and attach it to listView.
I think the reason why your code refuse to run is something abnormal in `jsonPath2` file. Check the resource and find if mistakes in loaded layout. 
Or else please offer me more specific  error message.

**Comment by pandamicro** [comment]
If your jsonPath2 is created with Cocos Studio and nothing have been modified, then please give us a link to download the file and related resources (all related cocos studio output) so that we can investigate

**Comment by dimaria11** [comment]
Sorry, i can't public file and resource because some reasons.

**Comment by dimaria11** [comment]
Sorry, i can't public file and resource because some reasons.

**Comment by tungnt11** [comment]
Sorry, i can't public file and resource because some reasons. I will describe as: If I add 
1.    var layOutJson = ccs.load(res.BarHonors_Json);
2.      this._listView.pushBackCustomItem(layOutJson.node);
When i run, app is crashes in line 2.
But if I create new Layout as:
3.  var layoutItem = new ccui.Layout();
4.  layoutItem.setContentSize(layOutJson.node.getContentSize());
5.  layoutItem.addChild(layOutJson.node);
6.  this._listView.pushBackCustomItem(layoutItem);
It run well. But listView cannot scroll and touch. I sure file cocos studio not error.

**Comment by minggo** [comment]
close this issue since cocos studio is canceled
