### ISSUE TITLE
Culling causes partial clipping of ui::Button if part is outside screen

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#13645]
With Culling enabled there is an issue with some Buttons after a change in margin. It appears that if margin is set to -10 just after button create we get partial Button "clipping" if we later update the margin to >= 0. 

While we could change how we position the buttons and which widgets we use the issue arises when we have a VBox with Button as children and we change the margins from -20 to 0 in order to make the buttons only partially visible.

Notes:
- I have no idea yet if clipping is the culprit, but the issue goes away when we disable CULLING
- unsure if it's clipping, Scale9Sprite draw path, or something else?
## Example

This is a screen shot after we have moved the two top buttons setting initially with -20 Left Margin and later updating the Left Margin to 0. We have also tried to add a call to `updateSizeAndPosition();` with no change. (sorry, the screen shots have 10 pixels of the xcode window behind the game)

Culling OFF (Desired/Good)
<img width="48" alt="screenshot 2015-08-31 19 42 43" src="https://cloud.githubusercontent.com/assets/225665/9594468/84c7f438-5018-11e5-87b6-0abbb34b274b.png">

Culling ON (Wrong/Bad)
<img width="47" alt="screenshot 2015-08-31 19 57 41" src="https://cloud.githubusercontent.com/assets/225665/9594661/fca7a578-501a-11e5-921f-96ff10f3a20d.png">

**Comment by stevetranby** [comment]
This does not occur if I set the margins to be positive (>= 0) so it's likely how the VBox (Layout/Widget) is handling its updateSizeAndPosition method with respect to its children.

**Comment by zilongshanren** [comment]
@stevetranby 
So I could simply close this issue?

**Comment by stevetranby** [comment]
Well it's a bug from my perspective since with clipping off the button image should be rendered in full, but if you want to close it that's fine as I have moved on to not use Layout for this purpose.

**Comment by stevetranby** [comment]
You can close this. While it may be a bug, we've worked around it in our game and I'm sure its either been fixed indirectly (with Layout/Widget commits) or it's something that could just be left as "undefined behavior" or "unsupported".
