### ISSUE TITLE
cocos2d::Map may cause Dangling Pointers when inserting Ref Object which already exist in the Map

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#13656]
cocos2d::Map may cause Dangling Pointers when inserting Ref Object which already exist
CCMap  line 274

``` C++
    void insert(const K& key, V object)
    {
        CCASSERT(object != nullptr, "Object is nullptr!");
        erase(key);
        _data.insert(std::make_pair(key, object));
        object->retain();
    }
```

For example
Object A already exist in Map B, and Map B has the very last reference of Object A. The code above will release Object A and Object A will be deleted, then Map B holds a Dangling Pointer.

How about retain the input object first, or check if the input object exist?

**Comment by seivan** [comment]
But from what I gather, the actual deletion happens in an autoreleasepool and might not trigger during the execution of insert().

You are actually accurate that the retain happens _after_ a release and that's bad.
Always retain what you work with, and release once you're done. So it should def be fixed :)

**Comment by c3076802** [comment]
@seivan 
I think you mis-understand the problem. For a newly created object surely the code above won't crash, because autorelease pool holds the +1 ref count that increased by the constructor. That Is not the case I mentioned ,  "Object A already exist in Map B, and Map B has the very last reference of Object A". 
Of course I could retain the object  then insert then release or check if the object already inserted, but shouldn't be the container at least generates a assert in DEBUG MODE for that ? 
if we insert a already existed item into std::map it will fail, which might cause memory leak but it certainly won't crash, cocos2d::Map is a wrapper of std::map but it behave differently at some point, It is a bit confusing for me, overall cocos2d::Map works fine.

**Comment by c3076802** [comment]
void insert(const K& key, V object)
	{
		CCASSERT(object != nullptr, "Object is nullptr!");
		object->retain();		// retain first might fix the problem
		erase(key);
		_data.insert(std::make_pair(key, object));
		//object->retain();
	}

**Comment by seivan** [comment]
No dude, I understood you correctly. 
You erase it before you retain it, it might trigger a delete.

**Comment by c3076802** [comment]
@seivan 
What I am trying to state is How the problem should be handled, not what the problem is. 
I think this kind of error should be and can be handled by the lib. If we need to retain every object before we pass to any function we don't we just use smart-pointer ? This problem similar to self-assign. It should be and can be handled by the container, like what I commented before at least should raise assert in DEBUG MODE.

**Comment by seivan** [comment]
@c3076802 
I am guessing, release doesn't mean deallocation, it means it's added on the autorelease pool and will eventually be deallocated (deleted)
If you release and retain in the same tick, nothing actually happens (a dangerous guess though)

What I am agreeing on here, is that the notion of calling release without knowing if the object is inside the vector.

``` c++
void insert(const K& key, V object)
    {
        CCASSERT(object != nullptr, "Object is nullptr!");
        if( erase(key, object) ) {
         _data.insert(std::make_pair(key, object));
         object->retain();
        }
    }

 size_t erase(const K& k,  V object = nil)
    {
        auto iter = _data.find(k);
        if (iter != _data.end() && iter->second != object)
        {
            iter->second->release();
            _data.erase(iter);
            return 1;
        }

        return 0;
    }
```

my c++ is pretty weak, but this at least doesn't fuck with the rest of the code base. erase() is being used at some other place as well.

**Comment by c3076802** [comment]
In Cocos in order to add an object into autorelease-pool, the method autorelease() is needed to be called. release will delete the object then the ref-count == 1

``` C++
void Ref::release()
{
    CCASSERT(_referenceCount > 0, "reference count should be greater than 0");
    --_referenceCount;

    if (_referenceCount == 0)
    {
#if defined(COCOS2D_DEBUG) && (COCOS2D_DEBUG > 0)
        auto poolManager = PoolManager::getInstance();
        if (!poolManager->getCurrentPool()->isClearing() && poolManager->isObjectInPools(this))
        {
            // Trigger an assert if the reference count is 0 but the Ref is still in autorelease pool.
            // This happens when 'autorelease/release' were not used in pairs with 'new/retain'.
            //
            // Wrong usage (1):
            //
            // auto obj = Node::create();   // Ref = 1, but it's an autorelease Ref which means it was in the autorelease pool.
            // obj->autorelease();   // Wrong: If you wish to invoke autorelease several times, you should retain `obj` first.
            //
            // Wrong usage (2):
            //
            // auto obj = Node::create();
            // obj->release();   // Wrong: obj is an autorelease Ref, it will be released when clearing current pool.
            //
            // Correct usage (1):
            //
            // auto obj = Node::create();
            //                     |-   new Node();     // `new` is the pair of the `autorelease` of next line
            //                     |-   autorelease();  // The pair of `new Node`.
            //
            // obj->retain();
            // obj->autorelease();  // This `autorelease` is the pair of `retain` of previous line.
            //
            // Correct usage (2):
            //
            // auto obj = Node::create();
            // obj->retain();
            // obj->release();   // This `release` is the pair of `retain` of previous line.
            CCASSERT(false, "The reference shouldn't be 0 because it is still in autorelease pool.");
        }
#endif

#if CC_REF_LEAK_DETECTION
        untrackRef(this);
#endif
        delete this;
    }
}
```

``` C++
Ref* Ref::autorelease()
{
    PoolManager::getInstance()->getCurrentPool()->addObject(this);
    return this;
}
```

I coded similar fix as you commented above. 

``` C++
void insert(const K& key, V object)
{
    CCASSERT(object != nullptr, "Object is nullptr!");
    auto iter = _data.find(key);
    if (iter != _data.end())
    {
        if (iter->second == object)
            return;
        else
            erase(iter);
    }
    _data.insert(std::make_pair(key, object));
    object->retain();
}
```

Thx for your rely, have a nice day.

**Comment by seivan** [comment]
@c3076802 That just proves my point, that it's wrong to call release before retain. I think there is a language barrier here.

Regardless, you fix will add a penalty as you're doing _two_ `find(key)`
One in insert() and one in erase()

Also, append append your first ``` with c++ when doing markdown for code, it will give us some syntax highlight.

**Comment by c3076802** [comment]
@seivan 
1. There won't be duplicate find called, since the overload method insert doesn't call find.

``` C++
void insert(const K& key, V object)
{
    CCASSERT(object != nullptr, "Object is nullptr!");
    auto iter = _data.find(key); //<-- Is an iterator
    if (iter != _data.end())
    {
        if (iter->second == object)
            return;
        else
            erase(iter);
    }
    _data.insert(std::make_pair(key, object));
    object->retain();
}
```

erase that take const_iterator as param

``` C++
iterator erase(const_iterator position)
{
    CCASSERT(position != _data.cend(), "Invalid iterator!");
    position->second->release();
    return _data.erase(position);
} 
```

2..  I don't see how I call release before retain, It won't happen on a very same object.  :-)

**Comment by stevetranby** [comment]
Why not just call retain first?

``` cpp
void insert(const K& key, V object)
{
  CCASSERT(object != nullptr, "Object is nullptr!");
  object->retain();
  erase(key);
  _data.insert(std::make_pair(key, object));
}
```

**Comment by WenhaiLin** [comment]
@seivan @c3076802 I think @stevetranby presented a better solution.

**Comment by seivan** [comment]
Haha that is a much better solution!

**Comment by c3076802** [comment]
@seivan @c3076802 @stevetranby @WenhaiLin
I suggested before "Of course I could retain the object then insert then release or check if the object already inserted". 
I had coded fix similar to @stevetranby 's, but I changed my mind later, here are the reasons. 
1. The problem is actually self-assigning, it should be solved by comparing self with input ( to make the problem clear).
2.  @stevetranby 's fix might need more function calls  one extra insert() when the input object already exist in the Map than mine fix; mine fix is actually an inline version of erase with extra comparison.

Original erase with keyname As below 

``` C++
    size_t erase(const K& k)
    {
        auto iter = _data.find(k);
        if (iter != _data.end())
        {
            iter->second->release();
            _data.erase(iter);
            return 1;
        }

        return 0;
    }
```

Here is mine fix, added an inline version of erase with extra comparison

``` C++
    void insert(const K& key, V object)
    {
        CCASSERT(object != nullptr, "Object is nullptr!");
        auto iter = _data.find(key);
        if (iter != _data.end())
        {
            if (iter->second == object)
                return;
            else
                erase(iter);
        }
        _data.insert(std::make_pair(key, object));
        object->retain();
    }
```

**Comment by c3076802** [comment]
I think again I might be wrong, because most of time, the situation "input object already inside Map" is pretty rare I assume.   @stevetranby 's fix is right Thanks.

**Comment by stevetranby** [comment]
The compiler may inline erase automatically. Also, in your method if it finds the object you don't insert it? I'm not sure what the correct behavior is, but I think I'd rather that anytime I call insert that the object I pass in should be the value that exists in the map after that point.

**Comment by c3076802** [comment]
Hmm
The behavior of CCMap::insert is really depends on how you look into the problem, there is no right or wrong; or we should ask the class designer what he/she was thinking.

But As a wrapper of std::map CCMap works in a different way.
std::map:insert,  In this case should fail silently. 

> Because element keys in a map are unique, the insertion operation checks whether each inserted element has a key equivalent to the one of an element already in the container, and if so, the element is not inserted, returning an iterator to this existing element (if the function returns a value).

CCMap::insert is actually similar std::map::operator[]

> If k does not match the key of any element in the container, the function inserts a new element with that key and returns a reference to its mapped value. Notice that this always increases the container size by one, even if no mapped value is assigned to the element (the element is constructed using its default constructor).

``` C++
//A call to this function is equivalent to:
(*((this->insert(make_pair(k,mapped_type()))).first)).second
```

And @stevetranby I think you misunderstand my fix, 

> if it finds the object you don't insert it? 

It only fails when the inserted element has a key equivalent to the one of an element already in the container and the inserted element's value is == the existing element's value. 

``` C++
        auto iter = _data.find(key);
        if (iter != _data.end())
        {
            if (iter->second == object)
                return;
            else
                erase(iter);
        }
```

I think this case is pretty rare, so that I agree your fix is better.

**Comment by stevetranby** [comment]
Oops, didn't read your fix closely enough, sorry about that. Thanks for the clarification. Maybe I'll go submit a PR tomorrow.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/13701
