### ISSUE TITLE
simulator.exe corrupted

### ISSUE THREAD

**Issue by fztcjjl** [cocos2d/cocos2d-x#13657]
I use the following command to build simulator
"cocos gen-simulator -p win32 --vs 2013 -m debug"
and use the simulator to run a simple lua program containing the following code:
local addr = io.open("res/addressbook.pb","rb")
local buffer = addr:read "_a"
simulator.exe corrupted at line: local buffer = addr:read "_a"

**Comment by fztcjjl** [comment]
but if i use "release" mode to build,there is no such problem

**Comment by chengstory** [comment]
what's visual studio version used for building simulator "release"?

**Comment by fztcjjl** [comment]
VS 2013

**Comment by fztcjjl** [comment]
发现问题了，是因为debug版链接的lua51.lib库冲突的问题

**Comment by minggo** [comment]
close it since cocos studio is canceled
