### ISSUE TITLE
I touched once, but Camera3DTestDemo::onTouchesBegan be triggered two times

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#13669]
`Cocos 2d-x v3.8rc0`

```
void Camera3DTestDemo::onTouchesBegan(const std::vector<Touch*>& touches, cocos2d::Event  *event)
{
    for ( auto &item: touches )
    {
        auto touch = item;
        auto location = touch->getLocation();
    }
}
```

I touched once, but Camera3DTestDemo::onTouchesBegan be triggered two times,
Cocos2d-x v3.6 and 3.7 have no this problem.

**Comment by TheCodez** [comment]
This is because this issue https://github.com/cocos2d/cocos2d-x/issues/13620 , the event is triggered for every camera in the scene
