### ISSUE TITLE
cocos2d-x APK Expansion Files Support

### ISSUE THREAD

**Issue by felixjingga** [cocos2d/cocos2d-x#13667]
This is useful for developers which has APK more than 50MB because of the assets. The documentation for this is here:
http://developer.android.com/google/play/expansion-files.html

a lot of people is needing this support from posts on the forum.. stevetranby is providing his codes for this support here:
https://gist.github.com/stevetranby/3151c541a7ce17cbd9bc

I think this should be a great features to have in cocos2dx

**Comment by stevetranby** [comment]
Please note that my code is probably convoluted, verbose, and most importantly for 2.x. We're likely going to be pushing a 3.x update in the next month so I'll post an update with our code or references to others if we use other people's information or code.

**Comment by felixjingga** [comment]
@stevetranby, It'd be a delight if you can contribute the 3.x codes update directly to cocos2d-x via PR.. It will save the cocos2d-x developers times..

**Comment by minggo** [comment]
it is fixed in v3.12 which will be released in a few days
