### ISSUE TITLE
TMX artifacts.

### ISSUE THREAD

**Issue by Cybertwip** [cocos2d/cocos2d-x#13679]
When loading a TMX map file this is what happens: 

![artifact_a](https://cloud.githubusercontent.com/assets/8097385/9667922/ecac798c-523b-11e5-9dd2-529e67eb68dd.PNG)
![artifacts_b](https://cloud.githubusercontent.com/assets/8097385/9667923/ecaf9928-523b-11e5-91ca-68b069505da6.PNG)
![artifacts_c](https://cloud.githubusercontent.com/assets/8097385/9667924/eceee042-523b-11e5-9287-fd0bde205cda.PNG)

The tileset has padding and margin:

![level_sheriffman_bank](https://cloud.githubusercontent.com/assets/8097385/9667958/1326ef20-523c-11e5-87f2-4b78e477467e.png)

This is the tmx map file: 
https://gist.github.com/VictorJL/d6652c55d6eeb6ca1e79

**Comment by Dredok** [comment]
Try to extrude your tiles by 2 pixels. This is an issue with OpenGL when tries to render a floating point position which must be interpolated, picking half of next pixel which is black transparent in your sprite sheet. If you extrude your tiles by 1 or 2 pixels the issue should go. Or you could try to enforce integer positions in screen space for all the tiles

**Comment by Cybertwip** [comment]
Thanks @Dredok we solved it like that that by adding a gutter between tiles like you indicate and it worked.
