### ISSUE TITLE
CocosStudio failed when running c++ project 

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#13675]
Im not sure where to open this bug but it related to Cocos Studio 
1. if i download the cocos3.7.1 framework from Cocos Store and install it , the CocosStudio doesn't detect it 
you must change the name of the directory from cocos2d-x-3.7.1 to cocos2d-x-3.7

when creating c++ project via CocosStudio and try to run it im getting error

![cpp_error](https://cloud.githubusercontent.com/assets/1107316/9657520/8577ae76-524a-11e5-9e0e-3750a9cf28e9.png)

**Comment by chengstory** [comment]
Hi meiry, If you want to create game project based on cocos2d-x 3.7.1, you need to upgrade Cocos Studio to 2.3.1 at least, check your cocos studio version and upgrade it to 2.3.1 or higher verison. Thanks.

**Comment by ricardoquesada** [comment]
we are not supporting cocos studio anymore. won't fix. sorry.
