### ISSUE TITLE
Remote debug using Firefox 40.0.3 doesn't work on windows using JSB project.

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#13674]
Remote debug using Firefox 40.0.3 doesn't work. on windows using JSB project ( js + native runtime ) 
following your old documentation : http://www.cocos2d-x.org/docs/manual/framework/native/v3/js-remote-debugger/en

today in the new Firefox there is no WebDeveloper -> debug , there is tool cold WebIDE 
The WebIDE manage to connect to the cocos2d-x server as you can see in the picture (2) but doesn't continue to the debug session and gets timeout ( 1)
as you can see in the image:
![remote_debug](https://cloud.githubusercontent.com/assets/1107316/9657506/6087eb4e-524a-11e5-9bc7-a9e99e5e9540.png)

**Comment by minggo** [comment]
It is fixed in #14890

**Comment by ricardoquesada** [comment]
closing it since, as @minggo said, it is fixed in #14890
