### ISSUE TITLE
ControlColorPicker issue with setContentScaleFactor.

### ISSUE THREAD

**Issue by anjandaffo** [cocos2d/cocos2d-x#13676]
If I set Director::getInstance()->setContentScalefactor() to support multiple screen size then color picker is wrongly placed.

PFA.
![ios simulator screen shot sep 3 2015 6 27 40 pm](https://cloud.githubusercontent.com/assets/12529102/9659382/d9a3d1d2-526d-11e5-909b-3497581333d7.png)

**Comment by pandamicro** [comment]
Sorry, the maintenance of GUI module is not active for now.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@anjandaffo
