### ISSUE TITLE
Issue with CCTMXXMLParser.cpp , Wrong object y calculation , and diffrent coordinate system at object position and tile position

### ISSUE THREAD

**Issue by mrsaleh** [cocos2d/cocos2d-x#13680]
![untitled](https://cloud.githubusercontent.com/assets/3070126/9671285/1cce6d6c-52a7-11e5-8f38-077e9aff79aa.png)

-attributeDict["height"].asInt() is not neccessory. I created a tilemap and add someobjects , the x property is  OK but Y is invalid as long as -attributeDict["height"].asInt() is there.
The anchor point for all map objecs are (0,0) .The position returned from bottom,left. But something is wrong and that is the tile position returned from left,top. so you need to fix object position calculation in the file from top,left or fix the tile returned from getTileGIDAt or getTileAt which return from bottom,left.

for example I had to use this piece of code:

``` c++
        bool canGoRight, canGoLeft, isOnFloor;
    float maxRight, maxLeft, floorY;
    //check floor1
    tmp.set(player->getPositionX(), player->getPositionY());
    int tileX = floor( tmp.x / mapTileSize.width);
    int tileY = ceil(tmp.y / mapTileSize.height);
    tmp.x = tileX;
    tmp.y = map->getMapSize().height- tileY;

    auto gid = tilesLayer->getTileGIDAt(tmp);   
    auto tileProperties = map->getPropertiesForGID(gid).asValueMap();

    if (tileProperties.find("blank") == tileProperties.end()){
        isOnFloor = true;
        floorY = tileY * mapTileSize.height;
    }
    else{
        isOnFloor = false;
        floorY = 0;
    }
```

sorry for bad english ;)

**Comment by dakabang** [comment]
version 3.7.1 don't have this problem, it's y where you marked.
![image](https://cloud.githubusercontent.com/assets/12713535/9688282/c9da49ea-5360-11e5-92da-4321b7f7910a.png)

**Comment by dakabang** [comment]
and the v3 branch show the same code as v3.7.1

**Comment by pandamicro** [comment]
Yes, we have solved it, please upgrade to latest version
