### ISSUE TITLE
android:sharedUserId on Manifest Causes Crash on Galaxy Edge+ and Note 5

### ISSUE THREAD

**Issue by ermanhaskan** [cocos2d/cocos2d-x#13681]
Hello

After very long hours of struggle I found out that Cocos2d-x Applications crash on Galaxy Edge+ and Note 5 if they have a android:sharedUserId value on the manifest and the value is same with the package name. I tried everything and I am desperate to find a solution. This issue doesn't occur with regular Android applications.

Recreating the issue is very simple. Create a new game with the latest version of cocos. And add a android:sharedUserId parameter to the <manifest> tag with a value same as the package game. Game will crash on Galaxy Edge+ or Note 5 at launch with this error: 

E/AndroidRuntime(31539): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.test/org.cocos2dx.cpp.AppActivity}: android.content.res.Resources$NotFoundException: File res/drawable/edit_text.xml from drawable resource ID #0x1080016
E/AndroidRuntime(31539):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3149)
E/AndroidRuntime(31539):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
E/AndroidRuntime(31539):    at android.app.ActivityThread.access$1000(ActivityThread.java:197)
E/AndroidRuntime(31539):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
E/AndroidRuntime(31539):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31539):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(31539):    at android.app.ActivityThread.main(ActivityThread.java:6891)
E/AndroidRuntime(31539):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31539):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31539):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(31539):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(31539): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/edit_text.xml from drawable resource ID #0x1080016
E/AndroidRuntime(31539):    at android.content.res.Resources.loadDrawableForCookie(Resources.java:3984)
E/AndroidRuntime(31539):    at android.content.res.Resources.loadDrawable(Resources.java:3852)
E/AndroidRuntime(31539):    at android.content.res.TypedArray.getDrawable(TypedArray.java:776)
E/AndroidRuntime(31539):    at android.view.View.<init>(View.java:4009)
E/AndroidRuntime(31539):    at android.widget.TextView.<init>(TextView.java:1026)
E/AndroidRuntime(31539):    at android.widget.EditText.<init>(EditText.java:88)
E/AndroidRuntime(31539):    at android.widget.EditText.<init>(EditText.java:84)
E/AndroidRuntime(31539):    at android.widget.EditText.<init>(EditText.java:80)
E/AndroidRuntime(31539):    at android.widget.EditText.<init>(EditText.java:76)
E/AndroidRuntime(31539):    at org.cocos2dx.lib.Cocos2dxEditBox.<init>(Cocos2dxEditBox.java:110)
E/AndroidRuntime(31539):    at org.cocos2dx.lib.Cocos2dxActivity.init(Cocos2dxActivity.java:409)
E/AndroidRuntime(31539):    at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:310)
E/AndroidRuntime(31539):    at org.cocos2dx.cpp.BaseGameActivity.onCreate(BaseGameActivity.java:103)
E/AndroidRuntime(31539):    at org.cocos2dx.cpp.AppActivity.onCreate(AppActivity.java:346)
E/AndroidRuntime(31539):    at android.app.Activity.performCreate(Activity.java:6550)
E/AndroidRuntime(31539):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
E/AndroidRuntime(31539):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
E/AndroidRuntime(31539):    ... 10 more
E/AndroidRuntime(31539): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/textfield_default.9.png from drawable resource ID #0x108082f
E/AndroidRuntime(31539):    at android.content.res.Resources.loadDrawableForCookie(Resources.java:3984)
E/AndroidRuntime(31539):    at android.content.res.Resources.loadDrawable(Resources.java:3852)
E/AndroidRuntime(31539):    at android.content.res.TypedArray.getDrawable(TypedArray.java:776)
E/AndroidRuntime(31539):    at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:182)
E/AndroidRuntime(31539):    at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:127)
E/AndroidRuntime(31539):    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1192)
E/AndroidRuntime(31539):    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1086)
E/AndroidRuntime(31539):    at android.content.res.Resources.loadDrawableForCookie(Resources.java:3968)
E/AndroidRuntime(31539):    ... 26 more
E/AndroidRuntime(31539): Caused by: java.lang.IllegalArgumentException: bitmap size exceeds 32 bits
E/AndroidRuntime(31539):    at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
E/AndroidRuntime(31539):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:837)
E/AndroidRuntime(31539):    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:656)
E/AndroidRuntime(31539):    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1037)
E/AndroidRuntime(31539):    at android.content.res.Resources.loadDrawableForCookie(Resources.java:3979)
E/AndroidRuntime(31539):    ... 33 more

**Comment by ermanhaskan** [comment]
Disabling the error causing lines on Cocos2dxActivity.java doesn't fix the problem, further errors occur.

**Comment by ermanhaskan** [comment]
Any ideas guys?

**Comment by ermanhaskan** [comment]
?

**Comment by ermanhaskan** [comment]
Finally found the solution to this problem :) Just remove com.enhance.gameservice.IGameTuningService library from the cocos library and any code related to it.

**Comment by eduhub123** [comment]
Thanks @ermanhaskan 
Provided that the application must be removed first and then reset the device
