### ISSUE TITLE
why the label effect in cocos2dx can't be so clear ?

### ISSUE THREAD

**Issue by jminht** [cocos2d/cocos2d-x#13699]
I played a game called "梦幻西游" made by netease, and the effect of its label shocked me.
why its label can be so clear, while the effect in my game is so blurred ?

**Comment by jminht** [comment]
![label](https://cloud.githubusercontent.com/assets/4132186/9704347/816abcfe-54d6-11e5-9143-d443f40c688c.png)

**Comment by WenhaiLin** [comment]
@jminht blurred? Which version of cocos2d-x are you using? Any source code to reproduce this issue?

**Comment by jminht** [comment]
@WenhaiLin 
I'm using v3.1.1. 
I synchronize part of code from the issue []https://github.com/cocos2d/cocos2d-x/issues/12666.

I simply create the label by these code

```
local tx = cc.Label:createWithTTF("战胜了妖王，妖王留下一个定魂珠后一溜烟的跑了", "fonts/test.ttf", 24)
```

here is the result pic
![difflabel](https://cloud.githubusercontent.com/assets/4132186/9709267/3dba3b80-555b-11e5-9ef4-e201d78956b7.PNG)

it's more obvious when running on the ipad.

**Comment by jminht** [comment]
the font blow isn't only brighter.
it looks like his font is vectorgraph, while mine is normal font.

**Comment by jminht** [comment]
@WenhaiLin 
you can check the screenshot from the game.

![shot](https://cloud.githubusercontent.com/assets/4132186/9709339/755cfc98-555c-11e5-8770-21b9b7d56bf0.png)

**Comment by felixjingga** [comment]
how could we duplicate their label? they have emoticon, and different color on the same line, etc.. This is what cocos2d-x label lack of. I saw richlabel, and tested it but it was still inconsistent and difficult to used. Is there any way we can emulate this using bmfont? is there in any way we can do ":P" to translate to one emoticon character in bmfont?

**Comment by WenhaiLin** [comment]
@jminht Could you provide related font resources for test?

**Comment by jminht** [comment]
@WenhaiLin 
how can i upload my font resources here?
i tried but failed, said "only PNG, GIF, JPG supported"

**Comment by jminht** [comment]
@WenhaiLin 
i uploaded my file to Pan.baidu.com.
Please check it.
[http://pan.baidu.com/s/1i3AiDrJ](http://pan.baidu.com/s/1i3AiDrJ)

2s8h

**Comment by Cybertwip** [comment]
We're having the same experience with the issue [#13677](https://github.com/cocos2d/cocos2d-x/issues/13677)

What we did was setting aliasing for the texture but after 3.8 there seems not to exist any method to apply aliasing to the TTF font.

**Comment by WenhaiLin** [comment]
@VirtualSJ  I got it. I will add `setAntiAliasTexParameters/setAliasTexParameters` to Label later.

**Comment by jminht** [comment]
@VictorJL 
hi, my label seems don't have the function "getTexture()".
Did you export it yourself ?

**Comment by zjsxcm** [comment]
@jminht the label is inherit from SpriteBatchNode,  it has the getTexture() method.

**Comment by stevetranby** [comment]
`label->getFontAtlas()->setAliasTexParameters()` from here:
http://discuss.cocos2d-x.org/t/release-cocos2d-x-3-8-final-please-enjoy/23479/94?u=stevetranby
