### ISSUE TITLE
mac模拟器console窗口文字区不响应  鼠标选中等事件

### ISSUE THREAD

**Issue by Cola-Zhang** [cocos2d/cocos2d-x#13695]
mac模拟器console窗口文字区不响应  鼠标选中等事件

**Comment by pandamicro** [comment]
Please be more specific.

Issue reports should follow issue description rules, an issue report should include the following informations:
1. Exact steps to reproduce the issue.
2. Engine version.
3. Programming language. (C++/Lua/JS)
4. Test environment:
   - Development platform and IDE version (VS, Xcode, NDK, Cocos)
   - Deployment mode: release or debug
   - Test device and its os version
   - Browser and its version (for html5 bugs)
5. [Optional] Sample code or test case that can reproduce the issue if possible.
6. [Optional] Correct behavior, observed behavior and screen captions of incorrect effect if possible.
7. [Optional] Error message if there is any.
8. [Optional] Call stack if there is a crash.

Important: Invalid reports won't be occupied before given necessary informations, but once the informations are complete, they will be transferred to other milestones.
