### ISSUE TITLE
There is bug when run command line "cocos new" 

### ISSUE THREAD

**Issue by wade0317** [cocos2d/cocos2d-x#13700]
Just because i add "--no-native" when run cocos new, such as:

Shuangquan:cocos2d-x shuangquan$ source /Users/shuangquan/.bash_profile
Shuangquan:cocos2d-x shuangquan$ cocos new MyDemoGame --portrait --no-native -p com.demoproject.mydemogames -l lua -d /Users/shuangquan/Documents/workspace/
执行命令：new

> 拷贝模板到 /Users/shuangquan/Documents/workspace/MyDemoGame
> 替换文件中的工程名称，'HelloLua' 替换为 'MyDemoGame'。
> 拷贝引擎中的文件夹...
> 使用 re.sub() 修改文件内容。
> /Users/shuangquan/Documents/workspace/MyDemoGame/frameworks/runtime-src/proj.ios_mac/ios/Info.plist 不是有效的文件。
> /Users/shuangquan/Documents/workspace/MyDemoGame/frameworks/runtime-src/proj.ios_mac/ios/Info.plist 不是有效的文件。
> /Users/shuangquan/Documents/workspace/MyDemoGame/frameworks/runtime-src/proj.android/AndroidManifest.xml 不是有效的文件。
> /Users/shuangquan/Documents/workspace/MyDemoGame/frameworks/runtime-src/proj.android-studio/app/AndroidManifest.xml 不是有效的文件。

**Comment by pandamicro** [comment]
Lua doesn't support --no-native tag, this is for creating pure web game.
