### ISSUE TITLE
There is problem when use Label::createWithCharMap

### ISSUE THREAD

**Issue by start530** [cocos2d/cocos2d-x#13705]
Sometimes it can be used, sometimes not used。
it is so ungelivable.
code:
auto label = Label::createWithCharMap("costFont.png",30,45,47);
label->setString("100");
label->setPosition(Point(400,250)); 
this->addChild(label,10);

console print:WARNING: can't find letter definition in font file for letter: 1

the picture just like “/ 1 2 3 4 5 6 7 8 9"

**Comment by WenhaiLin** [comment]
@start530 Which version of cocos2d-x are you using? Could you provide related resources for test?

**Comment by start530** [comment]
cocos2d-x 3.3
http://yunpan.cn/cm84sDAnb3GXw  访问密码 e1d8

**Comment by WenhaiLin** [comment]
@start530  Your image height is 44,not 45. It’s not a bug.

**Comment by WenhaiLin** [comment]
@zilongshanren Please close this issue

**Comment by start530** [comment]
sorry,it copy by cocos2dx 2.1.4 ,CCLabelAtlas,and it could be used successfully，so when I use  createWithCharMap, just modify startCharMap 。=。=
