### ISSUE TITLE
If replacing scene with Transition, built-in physics initialized at the beginning of the scene disappear

### ISSUE THREAD

**Issue by nbtthief** [cocos2d/cocos2d-x#13713]
Like the title said, if i create a scene with a physics Edgebox that i called it AScene, then if i replace the AScene with transition effect, the edge box disappear.

This bug wont happen if i replace AScene without any transition effect, or the older version(version 3.4 to be specific)

**Comment by pandamicro** [comment]
Duplicated with https://github.com/cocos2d/cocos2d-x/issues/12567
Please discuss in that thread
