### ISSUE TITLE
Bug reporting about removing joint from physics world(chipmunk)

### ISSUE THREAD

**Issue by foxhu17** [cocos2d/cocos2d-x#13712]
Hi,
I create a lot of nodes width physics body bound with joints  in my game, and remove the nodes when their hp=0. A random bug happen when removing the node.It stops at this code:
        cpSpaceRemoveConstraint(_cpSpace, constraint);
in CCPhysicsWorld.cpp line.729 with message "EXC_BAD_ACCESS"

I searched this problem on google and find this article:http://chipmunk-physics.net/forum/viewtopic.php?f=1&t=1780

It seamed that code like this will cause my bug:
cpSpaceRemoveBody(space, body);
cpBodyFree(body);
cpSpaceConstraintRemove(space, constraintAttachedToTheSameBody); // CRASH!

And I saw these code in CCPhysicsWorld.cpp:

```
if(_updateBodyTransform || !_delayAddBodies.empty())
{
    _scene->updatePhysicsBodyTransform(_scene->getNodeToParentTransform(), 0, 1.0f, 1.0f);
    updateBodies();
    _updateBodyTransform = false;
}
else if (!_delayRemoveBodies.empty())
{
    updateBodies();
}

if (!_delayAddJoints.empty() || !_delayRemoveJoints.empty() || !_delayRemoveBodies.empty())
{
    updateJoints();
}
```

It seems that cocos2dx will remove body earlier than joints. Maybe this is the problem.
I moved codes about body removing in updateBodies() into updateJoints(), after codes of joints removing, and my game works without bug since then.

Maybe I just use cocos2dx in the wrong way.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@foxhu17
