### ISSUE TITLE
Add native localization support

### ISSUE THREAD

**Issue by zeyangl** [cocos2d/cocos2d-x#13739]
Localization should be an integrated part of the game engine and provides ease to use interface. Right now common hacks are employed, like reading key strings from an external spreadsheet, replacing UI widget text by hand. It's inconvenient and hard to maintain. A locale setting should be allowed with hooks embedded in common widget classes.

**Comment by felixjingga** [comment]
:+1:  to this

**Comment by jgod** [comment]
Standardizing this sounds like a good idea :+1:

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@zeyangl @felixjingga @jgod
