### ISSUE TITLE
in sweep.cc, nested for loops using same variable name (ambiguous coding style)

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#13758]
XCode compiler warning is: "Declaration shadows a local variable." If you look at the two for-loops, you'll see that the inner for-loop is using the _same_ variable name as the outer for loop. Ambiguous coding style.. Suggest rewrite to use two different iter variable names.

```
void Sweep::SweepPoints(SweepContext& tcx)
{
  for (size_t i = 1; i < tcx.point_count(); i++) {
    Point& point = *tcx.GetPoint(i);
    Node* node = &PointEvent(tcx, point);
    for (unsigned int i = 0; i < point.edge_list.size(); i++) {
      EdgeEvent(tcx, point.edge_list[i], node);
   }
  }
```

}

**Comment by ginobean** [comment]
Actually, I hadn't really noticed this before but there seem about a couple hundred warning messages from the compiler regarding issues such as these: e.g. "declaration shadows a local variable". "implicit conversion loses integer precision", "register storage class specifier is deprecated". 

Not a big deal, but you guys could probably resolve the vast majority of these issues pretty easily/quickly with just a couple days of work.. And it would be nice to see a low number of compiler warnings from the cocos2d-x layer..

**Comment by jgod** [comment]
:+1: 
I've been thinking about this for a while. It's likely a bunch of little changes like this, improving the code itself and the user experience.

**Comment by minggo** [comment]
It is a 3rd party library, we don't want to modify it or it will be hard to update to new version.
