### ISSUE TITLE
ClippingNode is not perfect and does not work in some cases

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#13759]
Here are some issues found with clipping node:
1. ClippingNode fails to work if you have a nested ClippingNodes e.g. masked sprite in a scrollview, nested sprite masks
2. ClippingNode and label does not seem to work together. e.g. using label to mask a sprite does not work
3. ClippingNode does not seem to have a smooth output. Does it support alpha?

**Comment by webcrawler** [comment]
the first  issue, if you use UIScrollview, you can try to use the "setClippingType" to change the clipping type

**Comment by zilongshanren** [comment]
@StrikerScoleriWilliams  @webcrawler 
It should be fixed at https://github.com/cocos2d/cocos2d-x/pull/14470

**Comment by zilongshanren** [comment]
@StrikerScoleriWilliams 

> ClippingNode fails to work if you have a nested ClippingNodes e.g. masked sprite in a scrollview, nested sprite masks

It should be fixed at #14470

> ClippingNode and label does not seem to work together. e.g. using label to mask a sprite does not work

This issue I should verify.

> ClippingNode does not seem to have a smooth output. Does it support alpha?

ClippingNode does support alpha, please check.

Thanks.

**Comment by zilongshanren** [comment]
@StrikerScoleriWilliams 
For 

> ClippingNode and label does not seem to work together. e.g. using label to mask a sprite does not work

I have tested it, it's OK for clippingNode work with label. But you should pay attention to the system font label, it's rendered as a whole texture, so if you use a system font as stencil, it may not work the same as other label types.

**Comment by ghost** [comment]
Yup this issue is fixed. Tested and OK.
