### ISSUE TITLE
ImageView使用shader问题

### ISSUE THREAD

**Issue by crystal891002** [cocos2d/cocos2d-x#13763]
同样的shader使用，sprite正常，imageview不支持
这是怎么回事？

**Comment by woc2006** [comment]
((Sprite*)imageView->getVirtualRender())->setGLProgram(program)

**Comment by crystal891002** [comment]
这样也是不行的，ImageView的getVirtualRender()是个Scale9Sprite，直接对其设置和直接对ImageView也是一样的

**Comment by woc2006** [comment]
S9S 内部是9个Sprite, 要分别设置shader

**Comment by ZhangMenghe** [comment]
目前只能对Sprite(及其子类)设置shaderprogram.UI部分的node，包括button,imageView,s9Sprite等暂无此功能。
有的节点，比如imageview，可以通过设置Sprite类型子节点_imageRenderer的shaderProgram实现

**Comment by drelaptop** [comment]
问题已经 2 年没得到开发者回应，直接关闭，后续有问题建议在中文论坛讨论 @crystal891002
