### ISSUE TITLE
Not able to set physics body for any sprite

### ISSUE THREAD

**Issue by abhisheksahay** [cocos2d/cocos2d-x#13762]
Hi ,
I am trying to set physics body for a sprite. Here is my code:
`auto physicsBody = PhysicsBody::createBox(Size(65.0f, 75.0f), PhysicsMaterial(0.1f, 1.0f, 0.0f));
 testSprite1->setPhysicsBody(physicsBody);`

I even followed the tutorial (http://jslim.net/blog/2014/10/10/cocos2d-x-v3-accurate-physics-body-shape-with-physicseditor/) and tried with physics editor but in both the ways my application is crashing in `void Node::updateTransformFromPhysics(const Mat4& parentTransform, uint32_t parentFlags)` at this line 
 `auto updateBodyTransform = _physicsWorld->_updateBodyTransform;`

**Comment by Davarg** [comment]
Hi, what exactly exception you see? Do you debbuged your code, I mean is everything fine with variable '_physicsWorld' ?

**Comment by abhisheksahay** [comment]
_physicsWorld is NULL

please find the log below:

`this   cocos2d::Sprite *   0x7ff28085c600  0x00007ff28085c600
cocos2d::Node   cocos2d::Node       
_textureAtlas   cocos2d::TextureAtlas * NULL    0x0000000000000000
_atlasIndex ssize_t -1  -1
_batchNode  cocos2d::SpriteBatchNode *  NULL    0x0000000000000000
_dirty  bool    true    true
_recursiveDirty bool    true    true
_shouldBeHidden bool    false   false
_transformToBatch   cocos2d::Mat4       
_blendFunc  cocos2d::BlendFunc      
_texture    cocos2d::Texture2D *    0x7ff2804634b0  0x00007ff2804634b0
_spriteFrame    cocos2d::SpriteFrame *  NULL    0x0000000000000000
_quadCommand    cocos2d::QuadCommand        
_rect   cocos2d::Rect       
_rectRotated    bool    false   false
_offsetPosition cocos2d::Vec2       
_unflippedOffsetPositionFromCenter  cocos2d::Vec2       
_quad   cocos2d::V3F_C4B_T2F_Quad       
_opacityModifyRGB   bool    true    true
_flippedX   bool    false   false
_flippedY   bool    false   false
_insideBounds   bool    true    true
parentTransform const cocos2d::Mat4 &   0x00007ff28045a560  0x00007ff28045a560
    cocos2d::Mat4::(anonymous union)        
col __m128 [4]      
m   float [16]      
parentFlags uint32_t    3   3
recordedPosition    cocos2d::Vec2 & 0x00007ff2804639c4  0x00007ff2804639c4
x   float   0   0
y   float   0   0
newPosition const cocos2d::Vec2 &   0x00007ff2804639cc  0x00007ff2804639cc
x   float   0   0
y   float   0   0
updateBodyTransform bool    false   false`

**Comment by Davarg** [comment]
Ok, now we know that your variable _physicsWorld  is NULL,  maybe you just forget to initialize it? Where variable _physicsWorld  is created?

**Comment by abhisheksahay** [comment]
Do I need to initialize the _physicsWorld?
Its crashing in CCNode.cpp
I just followed the tutorial.

**Comment by zilongshanren** [comment]
@minggo  
maybe it's related to the new physics component?

**Comment by abhisheksahay** [comment]
Yes thanks for your help, I got it I had to create the scene using physics.

Thanks
