### ISSUE TITLE
Disable TIFF support causes Camera 3D Test to ASSERT

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#13791]
(low-priority crash in Cpp-Tests)

The reason for the ASSERT when running the test is that I'm guessing the imageTextureData stored inside SmallSun.plist is of the format TIFF? 

camera3dtest.cpp (line 90)

``` cpp
    auto p1 = ParticleSystemQuad::create("Particles/SmallSun.plist");
    p1->setPosition(30,80);
    bill1->addChild(p1);
```

Debug Log

```
tiff is not enabled, please enable it in ccConfig.h
Assert failed: CCParticleSystem: error init image with Data
Assertion failed: (isOK), function initWithDictionary, 
file /Users/stevetranby/dev/projects/cocos2d-x/cocos/2d/CCParticleSystem.cpp, line 404.
```

**Comment by fusijie** [comment]
Yes, the image data is `TIFF` format, so you can't disable TIFF support for cpp-tests.

**Comment by stevetranby** [comment]
Alright, I guess it's a test specific project issue. I guess I should always use pre-processor macros instead of changing the core cocos2d_libs ccConfig.h file. Makes sense.
