### ISSUE TITLE
3D Sprite Not Visible on top of another 3D Sprite

### ISSUE THREAD

**Issue by abhisheksahay** [cocos2d/cocos2d-x#13803]
Hi,
I am trying to add a 3D sprite on top of another 3D Sprite but only the first sprite is visible on the screen.
Here is my code:
`ground = Sprite3D::create("fieldwithgp.c3t");`
`ground->setScale(0.01f);`
 `addChild(ground);`
 `auto testSprite = Sprite3D::create("orange.c3t");`
  `testSprite->setScale(0.4f);`
  `testSprite->setPosition(Vec2(visibleSize.width/4 + origin.x, visibleSize.height/4 + origin.y));`
   `ground->addChild(testSprite);`

I wanted to show testSprite at center of ground sprite but its showing at a corner and if I change the position of test sprite to bring in center of the ground it is hiding behind the ground.

**Comment by fusijie** [comment]
You can `setGlobalZOrder/setPositionZ` for testSprite.

**Comment by abhisheksahay** [comment]
I did setPositionZ. Now my screen looks like
![screenshot](https://cloud.githubusercontent.com/assets/1061148/9867370/68e9766a-5b8a-11e5-9fea-3d6d6d8175b5.png)

I wanted to show the ball on center of the field.

**Comment by fusijie** [comment]
You can refer to [Cocos2d-x Program Guide: 3D](http://www.cocos2d-x.org/programmersguide/9/index.html) and [Depth Test](http://learnopengl.com/#!Advanced-OpenGL/Depth-testing).
