### ISSUE TITLE
CocosStudio的.csd檔案放在資料夾下，輸出json到loadTexture沒辦法自動預載plist

### ISSUE THREAD

**Issue by sianzain** [cocos2d/cocos2d-x#13805]
CocosStudio的.csd檔案放在資料夾下
輸出json到使用
使用JSB或Html5，ccs.load()
到loadTexture沒辦法自動預載plist
似乎是路徑組合有問題
JSB：

![image](https://cloud.githubusercontent.com/assets/11533618/9845516/0f84d24a-5afe-11e5-8a1d-25291566fe8c.png)

Html5：

![image](https://cloud.githubusercontent.com/assets/11533618/9845552/5e4f5706-5afe-11e5-96ce-84890b15cefb.png)

CocosStudio：
![image](https://cloud.githubusercontent.com/assets/11533618/9845648/1ad756ee-5aff-11e5-8db7-9cebe182dbf5.png)

cocos2d 3.7
script\studio\parsers\timelineParser-2.x.js：Line:1261:
![image](https://cloud.githubusercontent.com/assets/11533618/9845724/b445a92a-5aff-11e5-81f6-0820debe4d0c.png)

**Comment by sianzain** [comment]
似乎不是程式的問題
是CocoStudio導出json的plist路徑有問題

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
