### ISSUE TITLE
 Bitcode 导致编译失败

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#13829]
问题：Xcode 7 编译 3.8 ios模拟器 编译失败
详细描述：libcocos2d iOS.a(ftbase.ios8_x86_64.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64
我创建了个新的3.8版本的项目直接编译6s模拟器然后出现这个错误，用的是Xcode7 GM Seed版本
我把项目的target Enable Bitcode 设置为No之后 真机上可以编译成功

**Comment by fqamic** [comment]
主要是模拟器编译不过，真机可以在自己关闭target Enable Bitcode后编译通过

**Comment by dpclove** [comment]
我也碰到了这个问题，昨天更新了xcode7之后就这样了~~

**Comment by xpol** [comment]
我觉得应该支持Enable Bitcode。
（似乎要从新编译预编译的.a？）

**Comment by fqamic** [comment]
3.8.1可以编译模拟器了，但是Enable Bitcode还是得关闭才行

**Comment by minggo** [comment]
I haven't met the issue, i use Xcode7.3 for a long time.
