### ISSUE TITLE
Getting bounding box of CocoStudio skeleton is broken for JS in 3.8

### ISSUE THREAD

**Issue by wassil** [cocos2d/cocos2d-x#13831]
I tried creating a skeleton based animation in cocostudio and then importing it in JS.
It loads fine, but when trying to get bounding box, it crashes in CCBoneNode.js line 286
I did a quick fix by changing 
    displayRect.setRect(minx, miny, maxx - minx, maxy - miny);
into
    displayRect = type.rect(minx, miny, maxx - minx, maxy - miny);
It works fine now, but I don't understand the engine deep enough to tell if this is a correct fix

**Comment by minggo** [comment]
since cocos studio is canceled, so close the issue
