### ISSUE TITLE
MoveBy action doesn't work when applied to CCBoneNode in Browser

### ISSUE THREAD

**Issue by wassil** [cocos2d/cocos2d-x#13834]
I'm using cocos2d-x 3.8, I have added animation from cocostudio using ccs.load, it displays without issues and plays animation
when I try to use cc.moveBy action, the object doesn't move when I'm running the game in browser, but moves on iOS

**Comment by AlexKamaev** [comment]
same issue

**Comment by minggo** [comment]
since cocos studio is canceled, so close the issue
