### ISSUE TITLE
CCLabel not rendered with culling enabled

### ISSUE THREAD

**Issue by milos1290** [cocos2d/cocos2d-x#13838]
So i've came across this issue several times, if i remember well CCSprite with same setup will also show same problem.

If you set for example Label out of screen initially with CC_CULLING_ENABLED, and using action like MoveTo/MoveBy to move label to visible part of the screen, it won't render any letter.

```
auto label = Label::createWithBMFont("font.fnt", "Testing label visibility");
label->setPosition(_origin.x + _visibleSize.width / 2, _origin.y - 50.0f);
addChild(label);
```

and later

```
auto action = EaseBackOut::create(MoveBy::create(0.4f, Vec2(0, 100)));
label->runAction(action);
```

To solve this issue, i usually have to call 

```
label->visit();   
```

**Comment by minggo** [comment]
I can not reproduce it with latest codes. May be it is fixed, so close this issue.
