### ISSUE TITLE
ActionTimeline triggers multiple lastFrameEvent when its FPS is lower then application FPS

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#13844]
1. create an animation in cocos-studio with fps **30**
2. run cocos-application in fps **60**
3. set **CCActionTimeline::setLastFrameCallFunc** with a print 
4. receive multiple lastFrameEvents

``` C++
void ActionTimeline::step(float delta)
{
    if (!_playing || _timelineMap.size() == 0 || _duration == 0)
    {
        return;
    }

    _time += delta * _timeSpeed;
    const float endtoffset = _time - _endFrame * _frameInternal;

    if (endtoffset < _frameInternal)
    {
        _currentFrame = (int)(_time / _frameInternal);
        stepToFrame(_currentFrame);
        if (endtoffset >= 0 && _lastFrameListener != nullptr) // last frame 
            _lastFrameListener();
    }
    else
    {
        _playing = _loop;
        if (!_playing)
        {
            _time = _endFrame * _frameInternal;
            if (_currentFrame != _endFrame)
            {
                _currentFrame = _endFrame;
                stepToFrame(_currentFrame);
                if (_lastFrameListener != nullptr)  // last frame 
                    _lastFrameListener();
            }
        }
        else
            gotoFrameAndPlay(_startFrame, _endFrame, _loop);
    }
}
```

Say we set the **ActionTimeLine's** FPS to **30**, then **_timeSpeed** will be **0.5**

``` C++
    _time += delta * _timeSpeed;
    const float endtoffset = _time - _endFrame * _frameInternal;

    if (endtoffset < _frameInternal)
    {
        _currentFrame = (int)(_time / _frameInternal);
        stepToFrame(_currentFrame);
        if (endtoffset >= 0 && _lastFrameListener != nullptr) // last frame 
            _lastFrameListener();
    }
```

So that_time increase slower than real time. 
After **the first "last frame event"** is triggered,  since the member **_playing** is not set to false, **ActionTimeline::step** is able to call again; And because **_time** increase with **0.5**  **_timeSpeed**, then **endtoffset** will be able to stay **> 0**, then **the second  "last frame event"** is triggered.

note: **_frameInternal** is set to **1/60** by default.

I think the member _playing should be set right after.

``` C++
        if (endtoffset >= 0 && _lastFrameListener != nullptr) // last frame 
            _lastFrameListener();
```

**Comment by pandamicro** [comment]
@chengstory @xiaofeng11 @geron-cn Please take a look at this issue

**Comment by chengstory** [comment]
@geron-cn Please take a look. Thanks.

**Comment by geron-cn** [comment]
@c3076802 
the key note is reentry a same frameindex after scale actiontime's speed, it fixed in this pr: https://github.com/cocos2d/cocos2d-x/pull/13859/files   .

thank you very much.
@chengstory @pandamicro .

**Comment by c3076802** [comment]
I tried to fix it myself How about setting the _playing flag to false to prevent it revisit ?
I think the animation is end, _playing should be false when not in a loop. 

``` C++
    if (endtoffset < _frameInternal)
    {
        _currentFrame = (int)(_time / _frameInternal);
        stepToFrame(_currentFrame);
#ifdef COCOS2D_CUSTOM_FIX
        if (endtoffset >= 0 && _lastFrameListener != nullptr) // last frame 
        {
            _playing = _loop;
            if (!_playing)
                _lastFrameListener();
        }
#endif // COCOS2D_CUSTOM_FIX
    }
```

Thank you.

**Comment by geron-cn** [comment]
no , it can not resolve the problem from the root: `ReEntery the same frameindex`, and it will cause new issue: 
- may not emit the _lastFrameListener while loop play and fps <60
  if you fix like that.

the correct way to set _playing has been set in `endtooffset >= _fraemInternal`

**Comment by c3076802** [comment]
OK thanks for your explanation :+1:

**Comment by c3076802** [comment]
Hi 
@geron-cn We apply your patch, it works on Window but halts animation on android, we are trying to find out what happen , report later.

**Comment by geron-cn** [comment]
@c3076802   may be some multithreading reasons?

**Comment by c3076802** [comment]
I am guessing the problem might be the function **abs** on Linux works only with **integer**, then when we pass a double as param cause something unexpected.

**http://linux.die.net/man/3/abs**

``` C++
Synopsis

#include <stdlib.h>

int abs(int j);
long int labs(long int j);
long long int llabs(long long int j);

#include <inttypes.h>

intmax_t imaxabs(intmax_t j);
```

we should use **fabs** or **std::abs** for instead. I will do some tests next Monday.

**Comment by geron-cn** [comment]
yes, that is a problem , than you very much.

**Comment by pandamicro** [comment]
abs usage have been fixed in https://github.com/cocos2d/cocos2d-x/pull/13954
