### ISSUE TITLE
[Spine] memory leak

### ISSUE THREAD

**Issue by Neo1975** [cocos2d/cocos2d-x#13871]
Engine Version: 3.6

To reproduce: create a spine animation, free textureCache from spine texture and make run another time the animation. This scenario is tipical for animation that required a big atlas. In a scene you show an animation, for memory reson you free textureCache but no memory will be free and the second time you run the animation another texture was loaded.

Motivation:
I notice that then used spine from js, but I'm sure the same problem is present also in c++ enviroment, texture of atlas cannot be released never.
This is due to initialize() method, where it is called and what it is do.

The void SkeletonRenderer::initXXXX method call initialize and the end where initXXX allocate _atlas and initialize put it at NULL.

**Comment by pandamicro** [comment]
It have been fixed in v3.8 https://github.com/cocos2d/cocos2d-x/pull/13335
