### ISSUE TITLE
glsl在iphone6(a8 gpu) 下提示错误 OpenGL error 0x0502 但在其他 iphone和ipad设备上没有错误

### ISSUE THREAD

**Issue by xkf815** [cocos2d/cocos2d-x#13898]
错误提示:penGL error 0x0502 in /cocos2d-x/cocos/renderer/CCRenderer.cpp restoreRenderState 182
以下是glsl代码:
vsh:
attribute vec4 a_position;
attribute vec2 a_texCoord;
attribute vec4 a_color;

varying vec4 v_fragmentColor;
varying vec2 v_texCoord;

void main()
{
    gl_Position = CC_PMatrix \* a_position;
    v_fragmentColor = a_color;
    v_texCoord = a_texCoord;
}
fsh:
varying vec2 v_texCoord;
varying vec4 v_fragmentColor;

uniform vec2 custompos;
uniform vec2 resolution;
uniform float customtime;

void main(void)
{
    vec4 v_orColor = v_fragmentColor \* texture2D(CC_Texture0, v_texCoord);
    if(v_orColor.w <= 0.0){
        gl_FragColor = v_orColor;
        return;
    }
    vec2 p = vec2(gl_FragCoord.x-custompos.x, gl_FragCoord.y-custompos.y);
    float height = floor(resolution.y/3.0);
    float pecentTim = customtime/0.16;
    float maxRow = floor(resolution.y/height);
    float curRow = maxRow-floor(p.y/height);
    bool isShow = false;
    if( (curRow_resolution.x + (mod(curRow,2.0) == 1.0? p.x:resolution.x-p.x))/(maxRow_resolution.x) < pecentTim ){
        isShow = true;
    }
    gl_FragColor = vec4(
        isShow ? 0.12:0.0,
        isShow ? 0.12:0.0,
        isShow ? 0.12:0.0,
        isShow ? 0.54:0.0);
}

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@xkf815
