### ISSUE TITLE
v3.8 compatibility issue with json file exported by cocostudio v1.6

### ISSUE THREAD

**Issue by yaoyinbear** [cocos2d/cocos2d-x#13894]
In function SpriteFrameCacheHelper::retainSpriteFrames we can see :
 ValueMap& framesDict = dict["frames"].asValueMap();
Once there is no tag with name of "frames", the ASSERT will occured in Value::asValueMap
Unfortunately, if you added a particle in the cocostudio v1.6, then you would got a exported json file
with a particle plist file in it. And, the particle plist file had no tag names "frames".

**Comment by minggo** [comment]
since cocos studio is canceled, so close this issue
