### ISSUE TITLE
[Web Engine] Draw labels directly on Screen instead of creating new canvas

### ISSUE THREAD

**Issue by ZhangMenghe** [cocos2d/cocos2d-x#13908]
This is a modification for labelTTF under Canvas Mode
- Avoid drawing creating new _labelCanvas to temporarily store labels.
- In this mode, `use fillText()` instead of `drawImage()`
- use function `setDrawMode` to switch between draw on cached Canvas and Screen.

**Comment by pandamicro** [comment]
Please add a test case to test this feature
