### ISSUE TITLE
Can not link cocos2d-x in just released XCode 7.0

### ISSUE THREAD

**Issue by stoshb** [cocos2d/cocos2d-x#13904]
Because I like to live dangerously (and please don't flame me for this stupidity), I usually just download all updates from Apple as they occur.

Yesterday, I saw the release version of XCode 7 and put it on my system, replacing previous release.  Now my XCode project fails to link when loading xcode.  So, I went and downloaded cocos2d-x v3.8 and tried to load this and failed again.  

Now I am getting failed to link messages in the lua test portion of cpp-tests command.

While I consider myself a pretty good programmer, I only know cocos as a casual user and not a developer.  I am also an apps developer from a whole bunch of different environments, but not any sort of expert for debugging linking issues on Mac's.

Would appreciate a straight forward set of directions to use cocos2d-x in the release version of XCode 7.0.  It would even be nice to just know that there is a vanilla install process to use cocos2d and the released XCode 7.

Thanks in advance for any help with this issue.  It is a real pain to have to debug system software, when my own code provides its own set of interesting bugs.

Stan

**Comment by stoshb** [comment]
For specificity sake here is last error:

ld: in /Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Products/Debug-iphonesimulator/libcocos2d iOS.a(ftbase.ios8_x86_64.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and here is the xcode generated command when this happened

Ld /Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Products/Debug-iphonesimulator/lua-empty-test\ iOS.app/lua-empty-test\ iOS normal x86_64
    cd /Users/Stan/Downloads/cocos2d-x-3.8/build
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Products/Debug-iphonesimulator -L/Users/Stan/Downloads/cocos2d-x-3.8/build/../external/curl/prebuilt/ios -F/Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Products/Debug-iphonesimulator -filelist /Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Intermediates/cocos2d_tests.build/Debug-iphonesimulator/lua-empty-test\ iOS.build/Objects-normal/x86_64/lua-empty-test\ iOS.LinkFileList -mios-simulator-version-min=6.0 -Xlinker -objc_abi_version -Xlinker 2 -pagezero_size 10000 -image_base 100000000 -stdlib=libc++ -fobjc-link-runtime -liconv /Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Products/Debug-iphonesimulator/libcocos2d\ iOS.a /Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Products/Debug-iphonesimulator/libluacocos2d\ iOS.a -framework MediaPlayer -lz -framework CoreMotion -framework AudioToolbox -framework OpenAL -framework QuartzCore -framework CoreGraphics -framework OpenGLES -framework UIKit -framework AVFoundation -framework Foundation -Xlinker -dependency_info -Xlinker /Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Intermediates/cocos2d_tests.build/Debug-iphonesimulator/lua-empty-test\ iOS.build/Objects-normal/x86_64/lua-empty-test\ iOS_dependency_info.dat -o /Users/Stan/Library/Developer/Xcode/DerivedData/cocos2d_tests-bqsluxlnuocyzxbuuzkxhaelcseb/Build/Products/Debug-iphonesimulator/lua-empty-test\ iOS.app/lua-empty-test\ iOS

**Comment by pandamicro** [comment]
Duplicated with https://github.com/cocos2d/cocos2d-x/issues/13820
And fixed in #13880 

Please try to download v3.8.1 which supports Xcode 7: http://cocos2d-x.org/download
