### ISSUE TITLE
shander叠加

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#13915]
Cocos2d-x 的 shader 不能叠加，这样要做复杂点的功能就要全部写成一个shader， 调试起来很麻烦热情容易出错啊，也不利于做成模块化
希望shader可以叠加，谢谢。

**Comment by c3076802** [comment]
简单的话可以参考gamebyro的标准材质的做法，
根据渲染体所绑定的纹理（是否有法线图，漫反射图等），是否接受光照，是否有阴影，uniform输入等参数，运行时生成shader，相对还是比较灵活的，不过如果定制shader的话还是得自己写。

**Comment by 1078559858** [comment]
多谢回答，我尝试一下！
