### ISSUE TITLE
skybox各个面贴图左右颠倒

### ISSUE THREAD

**Issue by Curtis-ly** [cocos2d/cocos2d-x#13916]
skybox各个面贴图和Pano2VR/Unity3D对比发现图像左右颠倒

**Comment by super626** [comment]
@Curtis-ly 
unity用的是左手坐标系，cocos用是右手坐标系，设置的天空盒的贴图是以坐标系为准的，所以左右是反的。

**Comment by drelaptop** [comment]
@super626 已经解答了问题，Issue 关闭，如果有异议请重新打开 @Curtis-ly
