### ISSUE TITLE
problem with CCHTTPRequest

### ISSUE THREAD

**Issue by afrazizid** [cocos2d/cocos2d-x#1391]
I am trying to get response from the url by using CCHTTPRequest, the url is made perfectly fine and I have also tested on browser, the server is giving desired response. 

The problem i am facing using CCHTTPRequest is that the desired result is successfully coming in response data but only some portion of it is visible (i.e. the response string is truncated from the beginning and from the end). There mite be some limitation due to with the response string is truncated. The code I am writing is as following:

int statusCode = response->getResponseCode();
    char statusString[64] = {};
    sprintf(statusString, "HTTP Status Code: %d, tag = %s", statusCode, response->getHttpRequest()->getTag());
    CCLog("Zuluu:: response code: %d", statusCode);

    if (!response->isSucceed())
    {
        CCLog("Zuluu:: response failed");
        CCLog("Zuluu:: error buffer: %s", response->getErrorBuffer());
        return;
    }

    // dump data
    std::vector<char> _buffer = response->getResponseData();
    CCLog("Zuluu:: Http Test, dump data: ");
    std::string responseText = std::string((_buffer).begin(),(*buffer).end());

    CCLog("Zuluu:: Response is: %s",responseText); /// ONLY SOME PORTION OF THE RESPONSE STRING IS LOGGED (i.e. RESPONSE STRING IS TRUNCATED FROM START AND END)

I will really appreciate the help. Thanks in advance.

**Comment by sburavtsov** [comment]
Most possible it is result of issue in writeData of HttpClient
It was in stable version, then it was fixed in current. Sorry, don't remember commit on this.

Here is right piece of code:

size_t writeData(void _ptr, size_t size, size_t nmemb, void *stream)
{
    std::vector<char> *recvBuffer = (std::vector<char>_)stream;
    size_t sizes = size \* nmemb;

```
recvBuffer->insert(recvBuffer->end(), (char *)ptr, (char *)ptr + sizes);
return sizes;
```

}

Just compare it with what you have in HttpClient.cpp

**Comment by walzer** [comment]
This bug has been fixed in the gles20 branch 16 days ago, please take a look at https://github.com/cocos2d/cocos2d-x/pull/1300
The next stable version release in this week will involve this fix.

**Comment by afrazizid** [comment]
Thanks waizer and sburavtsov, I updated the cocos2d code and managed to resolve the issue. I really appreciate your help. :)
