### ISSUE TITLE
Event can't be received when calling addEventListener and dispatchEvent inside dispatchEvent.

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#13924]
I have just received a interesting bug report from my colleague.
I modified NewEventDispatcherTest.cpp to reproduce the bug. 

``` C++
    _listener = EventListenerCustom::create("game_custom_event1", [=](EventCustom* event){
        std::string str("Custom event 1 received, ");
        char* buf = static_cast<char*>(event->getUserData());
        str += buf;
        str += " times";
        statusLabel->setString(str.c_str());

        // test call EventDispatcher::addEventListener and EventDispatcher::dispatchEvent when receiving event. begin
        // create a listener when receiving event 
        auto l = EventListenerCustom::create(buf, [](EventCustom* ee){ 
            char* buf = static_cast<char*>(ee->getUserData()); 
            log(buf); 
        });
        _eventDispatcher->addEventListenerWithFixedPriority(l, 1);
        EventCustom e(buf);
        e.setUserData(buf);
        // dispatch event
        _eventDispatcher->dispatchEvent(&e);
        // test call EventDispatcher::addEventListener and EventDispatcher::dispatchEvent when receiving event. end
    });
```

(1). when dispatchEvent "game_custom_event1" （_inDispatch+1 = 1）

``` C++
void EventDispatcher::dispatchEvent(Event* event)
{
    ...
    DispatchGuard guard(_inDispatch);
    ...
```

(2). Inside "game_custom_event1" receiver function, call addEventListener "1", since 
（_inDispatch > 1) _toAddedListeners.push_back(listener);

``` C++
void EventDispatcher::addEventListener(EventListener* listener)
{
    if (_inDispatch == 0)
        forceAddEventListener(listener);
    else
        _toAddedListeners.push_back(listener);
}
```

(3). call dispatchEvent "1", because event "1" is not added to _listenerMap,  so event "1" can not be dispatched nor received.

This can be solve by dispatching the event with some delay.
I think it would be nice we could raise some warning for such case; by checking when calling function EventDispatcher::dispatchEvent whether any listener inside _toAddedListeners with an event id  == dispatching event if so print out some warning.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@c3076802
