### ISSUE TITLE
audio crash (version cocos2d3.8)

### ISSUE THREAD

**Issue by joewan** [cocos2d/cocos2d-x#13926]
http://bugly.qq.com/share/IRli00

0   libsystem_platform.dylib    0x3b20c1cc  __platform_memmove$VARIANT$CortexA9 + 160
1   OpenAL  0x31fff2be  OALSource::DoRender(AudioBufferList_, unsigned long) + 2050
2   OpenAL  0x31ffea5c  OALSource::SourceInputProc(void_, unsigned long_, AudioTimeStamp const_, unsigned long, unsigned long, AudioBufferList_) + 28
3   AudioToolbox    0x301627a0  AU3DMixerEmbeddedInputElement::PullSharedInput(unsigned long, unsigned long&, AudioTimeStamp const&, unsigned long) + 156
4   AudioToolbox    0x301650b2  AU3DMixerEmbedded::Render(unsigned long&, AudioTimeStamp const&, unsigned long) + 1210
5   AudioToolbox    0x300a299c  AUBase::DoRenderBus(unsigned long&, AudioTimeStamp const&, unsigned long, AUOutputElement_, unsigned long, AudioBufferList&) + 148
6   AudioToolbox    0x300a27ee  AUBase::DoRender(unsigned long&, AudioTimeStamp const&, unsigned long, unsigned long, AudioBufferList&) + 530
7   AudioToolbox    0x300a25d2  AUMethodRender(void_, unsigned long_, AudioTimeStamp const_, unsigned long, unsigned long, AudioBufferList_) + 46
8   AudioToolbox    0x30171116  AUInputElement::PullInput(unsigned long&, AudioTimeStamp const&, unsigned long, unsigned long) + 102
9   AudioToolbox    0x3016e4d6  AUInputFormatConverter2::InputProc(OpaqueAudioConverter_, unsigned long_, AudioBufferList_, AudioStreamPacketDescription__, void_) + 210
10  AudioToolbox    0x300a0ed0  AudioConverterChain::CallInputProc(unsigned long) 340
11  AudioToolbox    0x300a0c30  AudioConverterChain::FillBufferFromInputProc(unsigned long_, CABufferList_) + 92
12  AudioToolbox    0x300a0bca  BufferedAudioConverter::GetInputBytes(unsigned long, unsigned long&, CABufferList const_&) + 118
13  AudioToolbox    0x300a0ad0  CBRConverter::RenderOutput(CABufferList_, unsigned long, unsigned long&, AudioStreamPacketDescription_) + 72
14  AudioToolbox    0x300a0972  BufferedAudioConverter::FillBuffer(unsigned long&, AudioBufferList&, AudioStreamPacketDescription_) + 294
15  AudioToolbox    0x300a0bae  BufferedAudioConverter::GetInputBytes(unsigned long, unsigned long&, CABufferList const_&) + 90
16  AudioToolbox    0x300afc30  Resampler2Wrapper::RenderOutput(CABufferList_, unsigned long, unsigned long&) + 128
14  AudioToolbox    0x300a0972  BufferedAudioConverter::FillBuffer(unsigned long&, AudioBufferList&, AudioStreamPacketDescription_) + 294
18  AudioToolbox    0x300a0a48  AudioConverterChain::RenderOutput(CABufferList_, unsigned long, unsigned long&, AudioStreamPacketDescription_) + 92
14  AudioToolbox    0x300a0972  BufferedAudioConverter::FillBuffer(unsigned long&, AudioBufferList&, AudioStreamPacketDescription_) + 294
20  AudioToolbox    0x300af2b0  AudioConverterFillComplexBuffer + 355
21  AudioToolbox    0x3016e3b8  AUInputFormatConverter2::PullAndConvertInput(AudioTimeStamp const&, unsigned long&, AudioBufferList&, AudioStreamPacketDescription_, bool&) + 100
22  AudioToolbox    0x3016df68  AUConverterBase::RenderBus(unsigned long&, AudioTimeStamp const&, unsigned long, unsigned long) + 216
5   AudioToolbox    0x300a299c  AUBase::DoRenderBus(unsigned long&, AudioTimeStamp const&, unsigned long, AUOutputElement_, unsigned long, AudioBufferList&) + 148
6   AudioToolbox    0x300a27ee  AUBase::DoRender(unsigned long&, AudioTimeStamp const&, unsigned long, unsigned long, AudioBufferList&) + 530
25  AudioToolbox    0x3015deaa  AURemoteIO::PerformIO(unsigned long, unsigned int, unsigned int, AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const_, AudioBufferList_, int&) + 482
26  AudioToolbox    0x3015eede  _AURIOCallbackReceiver_PerformIO + 366
27  AudioToolbox    0x3015590e  __XPerformIO + 178
28  AudioToolbox    0x300c37a4  _mshMIGPerform + 124
29  AudioToolbox    0x301326fc  _MSHMIGDispatchMessage + 32
30  AudioToolbox    0x3015e128  AURemoteIO::IOThread::Run() + 120
31  AudioToolbox    0x3016134c  AURemoteIO::IOThread::Entry(void_) + 8
32  AudioToolbox    0x3009ebaa  CAPThread::Entry(CAPThread_) + 210
7   libsystem_pthread.dylib 0x3b210c1c  __pthread_body + 140
8   libsystem_pthread.dylib 0x3b210b8e  _pthread_start + 95
9   libsystem_pthread.dylib 0x3b20ec90  thread_start + 8

**Comment by joewan** [comment]
@WenhaiLin.      can you give us some advice?

**Comment by hawkwood** [comment]
I see this is a year old and no movement.  I just released an app build using Xcode 7 and Cocos 3.8.1 and am getting a lot of reports of this, but I and my team have not seen it.  Interestingly, I have a different app using 3.8.1 that is not seeing it, but I don't know what version of Xcode was used to compile/build that.    

Did you find a solution?  Does using a newer version of Cocos help (seeing as how 3.13 just came out)?

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/17500 and https://github.com/cocos2d/cocos2d-x/pull/17518 .
