### ISSUE TITLE
[Request] 2d CCLightNode

### ISSUE THREAD

**Issue by seivan** [cocos2d/cocos2d-x#13952]
Would be cool to have a CCLightNode for 2d similar to SKLightNode on SpriteKit
with the following attributes (getter/setters)
- `categoryBitMask`
- `ambientColor`
- `lightColor`
- `falloff`

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@seivan
