### ISSUE TITLE
cocosstudio的诡异问题：直接在csb写入文字会崩溃

### ISSUE THREAD

**Issue by loveyanbei** [cocos2d/cocos2d-x#13955]
崩溃的时候dvm打印了这样的log:
09-20 19:43:57.580    6121-6185/org.cocos2dx.heretictrainer W/dalvikvm﹕ Invalid indirect reference 0x41ffbb58 in decodeIndirectRef       //这里是关键
09-20 19:43:57.580    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ "GLThread 2514" prio=5 tid=13 RUNNABLE
09-20 19:43:57.580    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x42017798 self=0x72db8998
09-20 19:43:57.580    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ | sysTid=6185 nice=0 sched=0/0 cgrp=apps handle=1927062224
09-20 19:43:57.585    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ | state=R schedstat=( 747650783 190291302 1127 ) utm=41 stm=33 core=2
09-20 19:43:57.585    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ at org.cocos2dx.lib.Cocos2dxRenderer.nativeInit(Native Method)
09-20 19:43:57.585    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ at org.cocos2dx.lib.Cocos2dxRenderer.onSurfaceCreated(Cocos2dxRenderer.java:72)
09-20 19:43:57.585    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1510)
09-20 19:43:57.585    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)
09-20 19:43:57.585    6121-6185/org.cocos2dx.heretictrainer I/dalvikvm﹕ [ 09-20 19:43:57.585  6121: 6185 E/dalvikvm ]
    VM aborting
09-20 19:43:57.585    6121-6185/org.cocos2dx.heretictrainer A/libc﹕ Fatal signal 6 (SIGABRT) at 0x000017e9 (code=-6), thread 6185 (Thread-2514)

ndk-stack排查的时候发现CCDevice-Android.cpp出现了问题，看起来是渲染文字的时候出了问题

********* Crash dump: **********
Build fingerprint: 'samsung/klimtltetdzc/klimtlte:4.4.2/KOT49H/T705CZCU1AOC1:user/release-keys'
pid: 21407, tid: 21437, name: Thread-2310  >>> org.cocos2dx.heretictrainer <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Stack frame #00  pc 000222d0  /system/lib/libc.so (tgkill+12)
Stack frame #01  pc 000130dd  /system/lib/libc.so (pthread_kill+48)
Stack frame #02  pc 000132f1  /system/lib/libc.so (raise+10)
Stack frame #03  pc 00012027  /system/lib/libc.so
Stack frame #04  pc 00021b84  /system/lib/libc.so (abort+4)
Stack frame #05  pc 00046c33  /system/lib/libdvm.so (dvmAbort+78)
Stack frame #06  pc 0004b543  /system/lib/libdvm.so (dvmDecodeIndirectRef(Thread*, _jobject*)+146)
Stack frame #07  pc 0004c609  /system/lib/libdvm.so
Stack frame #08  pc 00756fb4  /data/app-lib/org.cocos2dx.heretictrainer-2/libcocos2dcpp.so (_JNIEnv::GetStaticMethodID(_jclass*, char const*, char const*)+56): Routine _JNIEnv::GetStaticMethodID(_jclass*, char const*, char const*) at D:/work/android-ndk-r10d/platforms/android-19/arch-arm/usr/include/jni.h:760
Stack frame #09  pc 00757630  /data/app-lib/org.cocos2dx.heretictrainer-2/libcocos2dcpp.so (cocos2d::JniHelper::getStaticMethodInfo(cocos2d::JniMethodInfo_&, char const*, char const*, char const*)+224): Routine cocos2d::JniHelper::getStaticMethodInfo(cocos2d::JniMethodInfo_&, char const*, char const*, char const*) at D:\work\workspace\LLPractice_cocos\heretictrainer\proj.android/jni/../../cocos2d/cocos/platform/android/jni/JniHelper.cpp:178
Stack frame #10  pc 00751208  /data/app-lib/org.cocos2dx.heretictrainer-2/libcocos2dcpp.so (cocos2d::BitmapDC::getBitmapFromJavaShadowStroke(char const*, int, int, cocos2d::Device::TextAlign, cocos2d::FontDefinition const&)+68): Routine cocos2d::BitmapDC::getBitmapFromJavaShadowStroke(char const*, int, int, cocos2d::Device::TextAlign, cocos2d::FontDefinition const&) at D:\work\workspace\LLPractice_cocos\heretictrainer\proj.android/jni/../../cocos2d/cocos/platform/android/CCDevice-android.cpp:91
Stack frame #11  pc 00751658  /data/app-lib/org.cocos2dx.heretictrainer-2/libcocos2dcpp.so (cocos2d::Device::getTextureDataForText(char const*, cocos2d::FontDefinition const&, cocos2d::Device::TextAlign, int&, int&, bool&)+104): Routine cocos2d::Device::getTextureDataForText(char const*, cocos2d::FontDefinition const&, cocos2d::Device::TextAlign, int&, int&, bool&) at D:\work\workspace\LLPractice_cocos\heretictrainer\proj.android/jni/../../cocos2d/cocos/platform/android/CCDevice-android.cpp:160
Stack frame #12  pc 00de610c  /data/app-lib/org.cocos2dx.heretictrainer-2/libcocos2dcpp.so (cocos2d::Texture2D::initWithString(char const*, cocos2d::FontDefinition const&)+672): Routine cocos2d::Texture2D::initWithString(char const*, cocos2d::FontDefinition const&) at D:\work\workspace\LLPractice_cocos\heretictrainer\proj.android/jni/../../cocos2d/cocos/./renderer/CCTexture2D.cpp:1120

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
