### ISSUE TITLE
_defaultFBO释放问题

### ISSUE THREAD

**Issue by winneryong** [cocos2d/cocos2d-x#13951]
我使用cocos2d-x的场景和其他人可能不太一样，需要将cocos2d-x集成到我们的app中，可以在不同的页面中来回切换，由于cocos2d-x不支持多导演，所以使用的时候流程为，每个页面打开运行一个新的场景和导演，当用户切换页面时将当前页面中的场景和导演都要销毁（Director::getInstance()->end();），每次进到一个新的页面到重新运行一个全新的导演和场景。但是我发现当切换到第2个页面的时候就会显示不出来，黑屏，控制台一直打印OpenGL的错误，于是我跟踪了一下当Director::getInstance()->end();后为什么没有销毁所有对象，发现_defaultFBO有些问题，我觉得是问题，本人c++刚学没几天，所以不能断定到底是不是bug，下面我把说一下我分析的过程：

环境： iOS Xcode  UIKit和cocos2d-x集成
我的测试程序有2个Tab导航页面，每个界面都显示cocos场景，第一次记入第一个Tab页面没有问题，当切换到第2个就有问题，页面黑屏，控制台输出OpenGL 错误信息。
当切换页面后程序会调用Director::getInstance()->end();结束当前场景，通过debug发现进入第2个tab页面时：
FrameBuffer\* FrameBuffer::getOrCreateDefaultFBO(GLView\* view)
{
    if(nullptr == _defaultFBO)
    {
        auto result = new (std::nothrow) FrameBuffer();

```
    if(result && result->initWithGLView(view))
    {
        result->autorelease();
        result->_isDefault = true;
    }
    else
    {
        CC_SAFE_DELETE(result);
    }

    _defaultFBO = result;
}

return _defaultFBO;
```

}

if代码块未进入，且_defaultFBO的内存地址与第一次进入tab页面时的地址一致。

还有一个奇怪的现象就是_defaultFBO的_referenceCount在第2次后的值为非常大的数字，有6，7位长。

这个bug我觉得和#13816 bug 一致，请明查！

**Comment by super626** [comment]
@winneryong 
多谢，是同一个问题。
可以按他的方法修复。我稍后发个修复的PR

**Comment by super626** [comment]
@winneryong 
这种修改应该也可以，能不能帮忙确认一下。
https://github.com/cocos2d/cocos2d-x/pull/14471

**Comment by winneryong** [comment]
试过了，可以使用，没有问题。辛苦！

**Comment by super626** [comment]
@winneryong 
多谢哈

**Comment by sunyuping** [comment]
你好我也是 iOS Xcode UIKit和cocos2d-x集成，第一次进入游戏没有问题，但是第二次进入后改了你说的这个崩溃的问题解决了，但是页面显示有问题，音乐有，点击效果也有，但是就是图片绘制有问题不知道你是否有此问题？或者能告诉我一下你在退出游戏的时候要执行那些释放动作？

**Comment by winneryong** [comment]
我这个图片绘制没有问题，退出执行：
cocos2d::Director::getInstance()->end();
_eaglView = nil;

其中_eaglView为CCEAGLView实例

**Comment by sunyuping** [comment]
@winneryong 多谢我再试试。。
