### ISSUE TITLE
[Web] Merge some transformation logic

### ISSUE THREAD

**Issue by VisualSJ** [cocos2d/cocos2d-x#13964]
There are two sets of all the transform in logic
WebGL / Canvas

In fact, the inside of the logic can be merged

**Comment by VisualSJ** [comment]
https://github.com/cocos2d/cocos2d-html5/pull/3106

**Comment by 1scaR1** [comment]
After merge #3106 on scene wit a lot of sprites(about 600-700 sprites) and a lot of ccui elements animations related to all ccui elements doesn't work. Also settings positions of ccui elements with moving mouse(by "onTouchMoved") not works. 
With animations of simple nodes and sprites everything is ok.(but moving with mouse not)
Frame rate is 60.0.
