### ISSUE TITLE
关于Cocos Studio2.3.2的帧事件回调触发不正确的Bug

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#13963]
HTML5版本的cocos2d-js, 在播放带有帧事件回调的动画时， 帧事件回调触发会在不正确的帧中触发， 经过与参考对比C++版本实现，有用户 发现并解决了此问题，我替他上传到GIT中。
这是代码链接：http://yunpan.cn/cHj9Q57Qf3v46 （提取码：f51d）

**Comment by maxwzg** [comment]
我是提交代码的用户， 补充一下， cocos2d-js版本是3.8.1

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
