### ISSUE TITLE
libcurl with https support

### ISSUE THREAD

**Issue by sburavtsov** [cocos2d/cocos2d-x#1399]
For now (at least in latest stable) iOS version of libcurl built without ssl, neither darwin native nor OpenSSL.
So all https:// urls are not working.
I built libcurl using this scripts: https://github.com/brunodecarvalho/curl-ios-build-scripts and it works now.
But it would be better either provide curl build configuration options or prebuilt libraries with different feature sets if size matters

**Comment by frranck** [comment]
I think it's still the case for the android version.
https is not working

**Comment by minggo** [comment]
It supports ssl on android now.
You can try AssetsManagerTest in samples/Cpp.
It uses url that starts with "https".

**Comment by godyZ** [comment]
@sburavtsov  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2679
