### ISSUE TITLE
It’s recommended that developers should add md5/sha1 sum in releases

### ISSUE THREAD

**Issue by loveyanbei** [cocos2d/cocos2d-x#13993]
It proves that unity and cocos2d-x are in danger of being infected by xcodeghost.
http://www.digi-wo.com/thread-34634-1-1.html

**Comment by pandamicro** [comment]
We are verifying our official packages, I believe there won't be any problem. But it's indeed possible to repackage cocos2d-x and redistribute it to some unofficial channel.

So please download Cocos packages from our website and Cocos Store

http://cocos2d-x.org/download
http://www.cocos.com/download/
http://store.cocos.com/

**Comment by loveyanbei** [comment]
thanks

**Comment by drelaptop** [comment]
@loveyanbei this issues have been replied by @pandamicro ,and not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
