### ISSUE TITLE
iOS Splash Screens and iOS Icons Not Configured Properly

### ISSUE THREAD

**Issue by jimrange** [cocos2d/cocos2d-x#14002]
It looks like the Cocos2d-x 3.8.1 iOS template (and previous 3.x versions) uses a configuration for iOS splash screens and a few icons that was not configured properly. 

To fix the issue, I deleted the UILaunchImages array of dictionaries in the Info.plist and ensure the following files are added as resources to the iOS project.

Default-568h@2x.png
Default-667h@2x.png
Default-736h@3x.png
Default.png
Default@2x.png
Default-Landscape~ipad.png

Another issue is that the orientation of the Default-736h@3x.png image is supposed to be portrait, but it is landscape in the helloWorld template. This might mislead developers to create the image with the wrong orientation.

I also had issues when using the icons defined in the template to submit the app with a missing icon or misconfigured Info.plist. The app failed validation due to an icon issue. I forget exactly what the issue was. But I updated the icons to more explicitly show the sizes in the file names and updated the Info.plist as describe in this blogpost in the section titled Icons and Splash Screens: http://heyalda.com/18-things-every-cocos2d-x-c-game-developer-should-know-about-xcode/

I am not certain this is the "correct" way to configure the assets. Could not get the asset catalog approach to work, but the approach descried in the blog post seems to show the splash screens and icons properly when using iOS and I tested it on 6plus, 6, 4s, 4, 5, iPad mini, and iPad 3 and it all looked correct.

I also just tested this in the simulator using base SDK iOS 9 and Xcode 7 and it looks correct on each device.

**Comment by zilongshanren** [comment]
@jimrange 
nice fix. :+1: 
Could you send a PR for this issue?

Thanks.

**Comment by jimrange** [comment]
Sorry for the delay. I have been very busy lately. 
Here is the pull request: https://github.com/cocos2d/cocos2d-x/pull/14130
