### ISSUE TITLE
EditBox PlaceHolder hint before start enter text

### ISSUE THREAD

**Issue by corcimaria** [cocos2d/cocos2d-x#14000]
![img](https://cloud.githubusercontent.com/assets/12607219/10019870/7a6885fc-6148-11e5-93fe-f8b2076aa996.png)
v 3.8.1, IOS
1. i user black background color for EditBox
2. focus the EditBox (apair Keyboard, but not start tape text, pointer its blinking on start of the text field)
3. !!! place holder hint color it's any time black transparent, and invisible on black background !!!

how to set color for placeholder hint

**Comment by zilongshanren** [comment]
@raduev 
Currently the EditBox doesn't support settings placeholder color.
It's a missing feature. And it is also tricky to implement it across all the supported platforms.

**Comment by zilongshanren** [comment]
@raduev 
It's not easy to support placeholder color across all the platform.
So, this request has no plan yet.
