### ISSUE TITLE
[Web Engine] Abnormal display when contains' positions change

### ISSUE THREAD

**Issue by ZhangMenghe** [cocos2d/cocos2d-x#14019]
For example, in the third testcase in scrollView Test. 
If `setInnerContainerSize` before `setPosition` for the widget inside, there could exist a wrong judgement about whether the widget should be draw.
The reason is that we ever determined the existence of widgets in `_moveChildren`, after which the reference could get changed.

**Comment by pandamicro** [comment]
Please add a test case for this issue

**Comment by ZhangMenghe** [comment]
The third testcase in scrollView is already a typical one for this issue.
