### ISSUE TITLE
BUG：Layout裁剪

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14013]
环境：3.8
描述：
创建Layout
{
    创建Layout1
    {
        Layout1->setClippingEnabled(true);//面板1开启裁切
        创建Layout2
        {
            创建Layout2->setClippingEnabled（true）;//面板2开启裁切  
            创建Btn
            Btn->setTouchEnabled(true); 
            }
    }
}

当一个面板含有这种结构的时候，点击里面的按钮响应消息就需要点击两次
问题分析：
bool Widget::isClippingParentContainsPoint(const Vec2 &pt)函数中的
if (layoutParent->isClippingEnabled())
            {
                _affectByClipping = true;
                clippingParent = layoutParent;
                break;
            }
和
 if (clippingParent)
    {
        bool bRet = false;
        if (clippingParent->hitTest(pt, _hittedByCamera, nullptr))
        {
            bRet = true;
        }
        if (bRet)
        {
            return clippingParent->isClippingParentContainsPoint(pt);
        }
        return false;
    }
递归出错，导致第二次遍历_hittedByCamera为null。

解决办法：
      bool bRet = false;
        auto carmera = Camera::getVisitingCamera();
        if (clippingParent->hitTest(pt, carmera, nullptr))

（ps：这是网友提供，我负责上传到git上。）

**Comment by pandamicro** [comment]
Hi, this issue have been fixed, thanks for your report : 

https://github.com/cocos2d/cocos2d-x/pull/13884
