### ISSUE TITLE
Cocos2d-x build failed on linux due to cocostudio headers

### ISSUE THREAD

**Issue by loveyanbei** [cocos2d/cocos2d-x#14010]
Looks like developers have forgotten to put those headers into cmakefiles.

Terminal Says:

Scanning dependencies of target MyGame
[100%] [100%] [100%] Building CXX object CMakeFiles/MyGame.dir/Classes/HelloWorldScene.cpp.o
Building CXX object CMakeFiles/MyGame.dir/Classes/AppDelegate.cpp.o
Building CXX object CMakeFiles/MyGame.dir/proj.linux/main.cpp.o
/home/lyt/Desktop/LLPractice_cocos/heretictrainer/Classes/HelloWorldScene.cpp:2:35: fatal error: cocostudio/CocoStudio.h: No such file or directory
 #include "cocostudio/CocoStudio.h"
                                   ^
compilation terminated.
CMakeFiles/MyGame.dir/build.make:77: recipe for target 'CMakeFiles/MyGame.dir/Classes/HelloWorldScene.cpp.o' failed
make[2]: *** [CMakeFiles/MyGame.dir/Classes/HelloWorldScene.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:66: recipe for target 'CMakeFiles/MyGame.dir/all' failed
make[1]: *** [CMakeFiles/MyGame.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zilongshanren** [comment]
@loveyanbei 
What's the engine version?

The CI is passed.

**Comment by loveyanbei** [comment]
3.8.1. I manually added editor-support files,and files under Classes folder
to cmakelists and solve the problem.

子龙山人 <notifications@github.com>于2015年10月9日星期五 08:33写道：

**Comment by ricardoquesada** [comment]
I confirm that v3.12 compiles Ok on Linux. fixed.
