### ISSUE TITLE
FPS (frames per second) display is incorrect when actual framerate is low

### ISSUE THREAD

**Issue by ginobean** [cocos2d/cocos2d-x#14025]
To reproduce: 
   write a test driver to display 700 Sprite3D objects (for example, you can use cubes that are 1 unit on a side) in a three dimension grid structure, with a PointLight and ambient light enabled. To make it easier to see the FPS inconsistency, set up a simple animation, like a cube that moves a short distance in every frame. (set up an Action).

  set the animation interval to 30 fps:
    director->setAnimationInterval(1.0 / 30.0f);

On an Ipod Touch 4, it shows an fps that is obviously incorrect. The actual framerate is actually closer to 4-6 frames per second, but the fps display is showing 40+ fps. 

If you want to reproduce this issue on a faster device, keep double the 700 Sprite3D instances until you get obviously incorrect FPS numbers..

You'll see that, at a certain point, even though the fps display seems to show a high frames per second, the animation cube is moving like molasses, which indicates that the FPS display must be incorrect.

**Comment by Leandros** [comment]
:+1:

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@ginobean @Leandros
