### ISSUE TITLE
Can't get writable path on android in AppDelegate constructor

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#14020]
```
AppDelegate::AppDelegate() {
    std::string wpath = FileUtils::getInstance()->getWritablePath();
}
```

wpath will be empty string

**Comment by FrankStain** [comment]
@ricardoquesada I had found this behaviour uncommon too.
Why it not fixed yet?

**Comment by ricardoquesada** [comment]
@FrankStain I guess nobody reported it before. Please, feel free to send a patch. Thanks.

**Comment by FrankStain** [comment]
@ricardoquesada , i can make a fix, but i had never pull into cocos repo and don't know code style. Thinking it will be long and hard way for me. So it would much better if somewho more qualified make such fix.

Actually, for fixing this bug, i suggest to make next things:
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/javaactivity-android.cpp#L56

Frankly it's bad idea placing main startup routine into `JNI_OnLoad()`. It must be done by another way. Stackoverflow is full of proves why main function should not be invoked inside `JNI_OnLoad()`.
`cocos_android_app_init()` needs to be invoked by another way, through new JNI function of JniHelper class.

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxActivity.java#L308

Here, after `Cocos2dxHelper.init(this)` main native function should be invoked via another jni request. Smth like:

``` .java
Cocos2dxHelper.init(this);
Cocos2dxHelper.invokeEngineMain();
```

It's crucial that jni helper must be ready at moment main function invoked cuz `AppDelegate` is created inside main function.
https://github.com/cocos2d/cocos2d-x/blob/v3/templates/cpp-template-default/proj.android/jni/hellocpp/main.cpp#L14
`AppDelegate` object may contain initialization routines that requires data from java side. Such data, like `FileUtils::getInstance()->getWritablePath()`, may be given only via jni helper.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@sbrednikhin @FrankStain
