### ISSUE TITLE
socket.io sending and getting data (acknowledgements)

### ISSUE THREAD

**Issue by man2** [cocos2d/cocos2d-x#14031]
@himynameschris 
Is there a way to do ack with current socket.io client implementation?
This is the documentation for this : http://socket.io/docs/#sending-and-getting-data-(acknowledgements)

From socket.io js client implementation, It's just adding callback on emit function. I need this, because on slow connection, I get lost data so many times when emitting from server to client. And socket.io doesn't retry sending the lost data.

**Comment by man2** [comment]
I got loss data on emit from server to client so many times even on localhost server. So I'm guessing there is a bug somewhere in the socket.io c++ code

**Comment by himynameschris** [comment]
can you provide a sample of the client and server code you are using so we can try and replicate the lost data?

**Comment by man2** [comment]
there is nothing special with my code. I just tried to send request to socket.io server, then the server emit back data to connected socket in a namespace with json data. Currently there is only 2 clients connected to namespace. So this is the schema

There is a namespace called test-namespace. 
Client A and B connect to test-namespace.
Client A send emit to server.
Server emit data back to all clients connected to namespace. 
(This is where loss data happens almost all the time)
Client A gets the data. Client B doesn't receive anything. Or Client B gets the data, Client A receives nothing.

 I will make a simple sample, but mostly it's just the same with sample code in cocos2d-x test-cpp.  Anyway here it is

``` cpp
// Client code
_socketIOClient = SocketIO::connect("http://localhost:3000/test-namespace", *this);
_socketIOClient->emit("fetchData", "message");
```

``` js
// server code
var nsp = io.of('/test-namespace');
nsp.on('connection', socketIOEventHandler);
function socketIOEventHandler(socket)
{
    console.log("socketio challenge created");
    socket.on("message", function(msg)
    {
        console.log("receives message");
    });

    socket.on('disconnect', function () {
        console.log(socket.id + " disconnected");
    });

    socket.on("fetchData", function(data)
    {
        nsp.emit( "message", JSON.stringify({"hello":"world"}))
    }
}
```

**Comment by ZeroHackeR** [comment]
```
 socket.on("fetchData", function(data)
   {
       nsp.emit( "message", JSON.stringify({"hello":"world"}))
    }
```

Try socket.emit instead of nsp

**Comment by man2** [comment]
@ZeroHackeR 
Tried that already, same result.. I iterate over all connected socket with nsp.connected then do socket.emit for each of them. 

There is always big probability that one of the socket will not receive message emitted from server

**Comment by ZeroHackeR** [comment]
Have you patch your socketio.cpp? There were a few errors in v 3.8

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@man2 @himynameschris @ZeroHackeR
