### ISSUE TITLE
Wrong line height in FontAtlas

### ISSUE THREAD

**Issue by ondesly** [cocos2d/cocos2d-x#14037]
There is function prepareLetterDefinitions in CCFontAtlas.cpp.
Each time bitmapHeight is compared with _currLineHeight and new value for _currLineHeight is set if it's needed. If char is rendered on next row, _currLineHeight is set to 0. 
But this first symbol is not compared with _currLineHeight. So if the first symbol in row is the biggest one, it will overlay with another row.
And we will get font artefacts.

if (bitmapHeight > _currLineHeight)
            {
                _currLineHeight = static_cast<int>(bitmapHeight) + _letterPadding + _letterEdgeExtend + 1;
            }
            if (_currentPageOrigX + tempDef.width > CacheTextureWidth)
            {
                _currentPageOrigY += _currLineHeight;
                _currLineHeight = 0;
                _currentPageOrigX = 0;
...

**Comment by minggo** [comment]
The logic is changed, so close this issue. Please create a new one if it also has issue. Thanks.
