### ISSUE TITLE
Android builds don't work with NDK r10 when running on Android 4.x devices

### ISSUE THREAD

**Issue by denisk20** [cocos2d/cocos2d-x#14034]
Using cocos2d-x 3.8.1 on OSX 10.10.5.

I use android NDK `r10e` to run a Hello World autogenerated project. After I compile the project

```
cocos compile -pandroid --android-studio --no-apk
```

I and run it from android studio on Android API 17 device. The app crashes on startup. From logcat:

```
    java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "srand" referenced by "libcocos2dcpp.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:365)
        at java.lang.System.loadLibrary(System.java:514)
        at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:288)
        at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:303)
        at android.app.Activity.performCreate(Activity.java:5135)
```

This thread provides some detail
http://discuss.cocos2d-x.org/t/android-debug-mode-works-but-release-dont-crashes-at-launch/20247

In particular:

> This relates to an issue where some functions, including atof() and srand(), were static inline before android-21 but have been moved into the library .so file since then. If you compile your app against the android-21 and run it on a pre-android-21 device you will get this error.

Any way to fix this without downgrading the NDK?
Thanks.

**Comment by denisk20** [comment]
Just found this post where it's suggested to use NDK 9 but the reasons for that seem to be different.
http://www.cocos2d-x.org/news/307

**Comment by denisk20** [comment]
The issue appears on Ubuntu 14.04 64-bit too.

**Comment by denisk20** [comment]
Based on
http://stackoverflow.com/questions/27091001/how-to-use-mkfifo-using-androids-ndk
https://code.google.com/p/android-developer-preview/issues/detail?id=888
the workaround is to set
`APP_PLATFORM=android-20`
in `Application.mk`. Not sure if it will work for APIs < 16 though.

**Comment by Leandros** [comment]
Doesn't fix your issue, but you shouldn't use `srand()`/`rand()` anyway. [rand() considered harmful](https://channel9.msdn.com/Events/GoingNative/2013/rand-Considered-Harmful).

**Comment by denisk20** [comment]
@Leandros Thanks for the link. I don't use it, it is used in Cocos, for example, in `CCConsole.cpp`, `CCActionTiledGrid.cpp`.

**Comment by Guy-kun** [comment]
According to a post in http://discuss.cocos2d-x.org/t/cant-find-ndk-r9d-download-anymore/15719/7 a (now dead link) new post on the main site said

"We suggest you use NDK r10c or upper version, because it fixed some bugs that exist on Android 5.0." which means not using NDK 9 anymore.
This issue is still relevant.

**Comment by Narvikz** [comment]
Apparently the issue has been fixed with r12 beta release: https://code.google.com/p/android/issues/detail?id=73907#c10

**Comment by daniaDlbani** [comment]
Did you try it?

**Comment by daniaDlbani** [comment]
@Narvikz trying the new ndk but it failed to build the project and here my error log:

[armeabi] SharedLibrary : libcocos2dcpp.so
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(libwebsockets.c.o):libwebsockets.c:function libwebsocket_create_context: error: undefined reference to 'getdtablesize'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(libwebsockets.c.o):libwebsockets.c:function libwebsocket_create_context: error: undefined reference to 'bsd_signal'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(daemonize.c.o):daemonize.c:function lws_daemonize: error: undefined reference to 'bsd_signal'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(daemonize.c.o):daemonize.c:function lws_daemonize: error: undefined reference to 'bsd_signal'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(daemonize.c.o):daemonize.c:function lws_daemonize: error: undefined reference to 'bsd_signal'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi/libcocos2dcpp.so] Error 1

**Comment by daniaDlbani** [comment]
I have fix this problem by setting up the application make correctly as shown [here](http://stackoverflow.com/questions/31516952/cocos2d-x-java-lang-unsatisfiedlinkerror-app-crash-on-startup?noredirect=1#comment50995473_31516952)

**Comment by Guy-kun** [comment]
Targeting an old android version is NOT a solution unless you want all dialogue boxes to be themed like a 5-year old app or to lock yourself out of new APIs.
I wish these issues would stop being closed while there is no real solution except 'use old API'

**Comment by minggo** [comment]
I don't met this issue. I used NDK r10c for a long time, now changed to use NDK r11c.

**Comment by Guy-kun** [comment]
@minggo What APP_PLATFORM and min_sdk do you target when doing so

**Comment by minggo** [comment]
I don't modify it, just the same as the engine shift.

**Comment by shinigami1992** [comment]
Facing same issue.

SDK  -> 22
NDK -> 12.1

Building my app using:
cocos compile -pandroid --android-studio --no-apk --target android-22 --ap android-22 --ndk-mode debug  --app-abi armeabi

Adding "APP_PLATFORM=android-19" to "Application.mk" fixed my issue.

**Comment by minggo** [comment]
@mmobini In android-19, `srand` is defined in `usr/include/stdlib/h` as

``` c++
static __inline__ void srand(unsigned int __s) {
    srand48(__s);
}
static __inline__ long random(void)
{
    return lrand48();
}
static __inline__ void srandom(unsigned int __s)
{
    srand48(__s);
}
```

`srand` is defined as static inline function, as what i know, it will invoke `srand48`, so i don't know why you changed to Android 19 can resolve the issue.

**Comment by minggo** [comment]
I think i got the idea, it is caused because compiling Android version and running Android version is different and Android break compatibility. For example:
- if i use Android 19 to compile the codes that invoke `srand()`, because `srand()` is a static inline function, so it will invoke `srand48` instead, which means cocos2d-x depends on `srand48` instead of `srand`. `srand48` is defined in all Android versions, so there is not problem.
- i using Android 21+ to compiling the codes, `srand()` is defined like `void srand(unsigned int);`, so cocos2d-x depends on `srand`. Because `srand` is not defined below Android 21, so it will have problem if running on Android version below 21.

I think we should not use `srand`, should use `std::srand` instead in cocos2d-x. But `srand` may be used in 3rd party libraries, such as bullet, then i have not idea how to fix it.

**Comment by minggo** [comment]
I sent #16079 to fix it. I did't modify bullet since it is 3rd party libs, and it is a 3d physics engine.

**Comment by minggo** [comment]
@all please let me know if it fixes your issue, thanks.
