### ISSUE TITLE
Cocos Framework 3.8.1 - no windows phone solution created

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#14036]
When using the Framework, a Windows phone project is not created. When using source, a Windows phone project is created. 

Forum discussion: http://discuss.cocos2d-x.org/t/cocos-framework-3-8-1-no-windows-phone-solution-created/23997

**Comment by pandamicro** [comment]
Windows phone haven't been supported by Cocos Framework yet

**Comment by slackmoehrle** [comment]
Alright, that explains it. Is there a plan for support in the frameworks or not for a while yet?
The user can always is `cocos new` to create a Windows phone project, then decide to add in the pre-built libraries if they choose..

Edit: I see you posted a reply on the forums, no need to answer me here now.

**Comment by minggo** [comment]
since there is not plan to support it, so close this issue
