### ISSUE TITLE
"cocos run -p metro" fails for cocos2d-js project

### ISSUE THREAD

**Issue by saeedakhter** [cocos2d/cocos2d-x#14059]
Failure is below.  Opening \MyTestProject\frameworks\runtime-src\proj.win8.1-universal\MyTestProject.sln shows all modules as (unavailable).

Potentially I'm interested in contributing/fixing problems with the windows build process for cocos2d-js, but I am looking for background on what is the current status.  Has it ever worked?  Is there any effort underway to make cocos2d-js compile as a Win10 universal app?

---

C:\Users\saeed\Projects\MyTestProject>cocos run -p metro
Running command: compile
Building mode: debug
Building...
Required VS version : 12.0
Finding VS in registry : 64bit
Finding VS in registry : 32bit
Find VS path : C:\Program Files (x86)\Microsoft Visual Studio 14.0\
running: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.com" "C:\Users\saeed\Projects\MyTestProject\frameworks\runtime-src\proj.win8.1
-universal\MyTestProject.sln" /Upgrade'

Microsoft Visual Studio 2015 Version 14.0.23107.0.
Copyright (C) Microsoft Corp. All rights reserved.

Migration completed successfully, but some warnings were detected during migration.
For more information, see the migration report:
C:\Users\saeed\Projects\MyTestProject\frameworks\runtime-src\proj.win8.1-universal\UpgradeLog.htm

Information:
This project/solution does not require migration. It will open without modification.
running: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.com" "C:\Users\saeed\Projects\MyTestProject\frameworks\runtime-src\proj.win8.1
-universal\MyTestProject.sln" /Build "Debug" /Project "MyTestProject.Windows"'

Microsoft Visual Studio 2015 Version 14.0.23107.0.
Copyright (C) Microsoft Corp. All rights reserved.

The operation could not be completed. The parameter is incorrect.

Use:
devenv  [solutionfile | projectfile | anyfile.ext]  [switches]

The first argument for devenv is usually a solution file or project file.
You can also use any other file as the first argument if you want to have the
file open automatically in an editor. When you enter a project file, the IDE
looks for an .sln file with the same base name as the project file in the
parent directory for the project file. If no such .sln file exists, then the
IDE looks for a single .sln file that references the project. If no such single
.sln file exists, then the IDE creates an unsaved solution with a default .sln
file name that has the same base name as the project file.

Command line builds:
devenv solutionfile.sln /build [ solutionconfig ] [ /project projectnameorfile [ /projectconfig name ] ]
Available command line switches:

/Build          Builds the solution or project with the specified solution
                configuration. For example "Debug". If multiple platforms
                are possible, the configuration name must be enclosed in quotes
                and contain platform name. For example: "Debug|Win32".
/Clean          Deletes build outputs.
/Command        Starts the IDE and executes the command.
/Deploy         Builds and then deploys the specified build configuration.
/Edit           Opens the specified files in a running instance of this
                application. If there are no running instances, it will
                start a new instance with a simplified window layout.
/LCID           Sets the default language in the IDE for the UI.
/Log            Logs IDE activity to the specified file for troubleshooting.
/NoVSIP         Disables the VSIP developer's license key for VSIP testing.
/Out            Appends the build log to a specified file.
/Project        Specifies the project to build, clean, or deploy.
                Must be used with /Build, /Rebuild, /Clean, or /Deploy.
/ProjectConfig  Overrides the project configuration specified in the solution
                configuration. For example "Debug". If multiple platforms are
                possible, the configuration name must be enclosed in quotes
                and contain platform name. For example: "Debug|Win32".
                Must be used with /Project.
/Rebuild        Cleans and then builds the solution or project with the
                specified configuration.
Error running command, return code: 1.

**Comment by zilongshanren** [comment]
@pandamicro  @stammen  thoughts?

**Comment by ideath4** [comment]
Hello, i have a same problem, do u find any solution?

**Comment by saeedakhter** [comment]
Not much progress to report.  There is a blog post here about how to get cocos2d-x working on Win10 (but it does not mention cocos2d-JS)

https://blogs.windows.com/buildingapps/2015/06/15/running-cocos2d-x-on-windows-10/

I did manage to get the example C++ cocos2d-x project to build and run following the instructions in that blog post.  However, I have not investigated what it would take to get a cocos game written in JavaScript to run on Win10.

@stammen any input or guidance here?

**Comment by stammen** [comment]
We have not added support for JavaScript for Windows 10 UWP. The work is currently not scheduled at Microsoft.

The following libs need to be ported to Windows 10 UWP
1) SpiderMonkey (Windows 8.1 source is at https://github.com/MSOpenTech/Spidermonkey)
2) libjscocos2d
3) JavaScript app templates for Windows 10 UWP
