### ISSUE TITLE
cocos2d-x v3.X  -> FlipY3D does not flip at Y center position

### ISSUE THREAD

**Issue by stefan80** [cocos2d/cocos2d-x#14057]
Hi!

When I tryo to FlipY3D the layer of the default hello world template, the conent will flip but also move to upper corner.

So, it is not flipped at Y-Center position anymore. It worked with v2.2.6

Here is my code which I added to the end of the HelloWorldScene.init() method:

// add "HelloWorld" splash screen"
auto sprite = Sprite::create("HelloWorld.png");

// position the sprite on the center of the screen
sprite->setPosition(Vec2(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y));

NodeGrid\* lNodeGrid = NodeGrid::create();
this->addChild(lNodeGrid);

// add the sprite as a child to this layer
lNodeGrid->addChild(sprite, 0);

CCFlipY3D\* mFlipScreenY3D = CCFlipY3D::create(1);
lNodeGrid->runAction(mFlipScreenY3D);

I have checked the test-cpp project of 2.2.6 and 3.8 and the FlipX3D and FlipY3D effects are not correct for 3.8.

Can you please check this or give a workaround?

v2.2.6:
![flipy3d_cocos2dxv2_2_6](https://cloud.githubusercontent.com/assets/14909272/10197754/660a129a-6799-11e5-8a79-bc1cb7765cba.PNG)

v3.8
![flipy3d_cocos2dxv3_8](https://cloud.githubusercontent.com/assets/14909272/10197753/6609c04c-6799-11e5-96e9-140d06324d1e.PNG)

**Comment by zilongshanren** [comment]
@super626  please take a look at this.

**Comment by stefan80** [comment]
Someone taking care of it? We need this asap for our commercial game

**Comment by stefan80** [comment]
Any update? Please have a look into this issue...

**Comment by slackmoehrle** [comment]
@super626 is there an update on this?

**Comment by stefan80** [comment]
@slackmoehrle @super626 @zilongshanren 
I have checked v3.10 and the issue still exists. Can you please check this? We really need a solution for that issue.

**Comment by stefan80** [comment]
add

auto origin = Director::getInstance()->getVisibleOrigin();
Size visibleSize = Director::getInstance()->getVisibleSize();
_gridNodeTarget = NodeGrid::create({origin, visibleSize });

at Line 345 of EffectsTest.cpp (cocos2d-x v310 tests application) and the flipping will be correct for y and x axes.

**Comment by perfectdeveloper53** [comment]
Hello. Is there any solution for Javascript(cocos2d-x 3.16)  with above problem?
