### ISSUE TITLE
Is there a wp8.1 project template  in cocos2dx  lua ?

### ISSUE THREAD

**Issue by dannyjiajia** [cocos2d/cocos2d-x#14067]
I didn't find a project template with  wp8.1 in  cocos2dx  lua project. not support?

**Comment by PeqNP** [comment]
There currently is not. I plan on working on this integration as soon as I am able. You can reference issue [13761](https://github.com/cocos2d/cocos2d-x/issues/13761) to track the progress.

**Comment by zilongshanren** [comment]
@dannyjiajia  
please move to #13761 to continue discussion.
