### ISSUE TITLE
CMake does not check for sqlite3 dependency

### ISSUE THREAD

**Issue by firefly2442** [cocos2d/cocos2d-x#14070]
It seems that it's possible to run CMake and generate a solution without having the sqlite dependency (libsqlite3-dev on Linux) installed.  This results in the code not being able to compile because it's missing the appropriate include headers.

tested version hash: b38eec4d470d3ed7cf3062c4cad5f821ebc352d5
OS: Linux

**Comment by zilongshanren** [comment]
@firefly2442  
Could you send a PR to resolve it?
Thanks.

**Comment by firefly2442** [comment]
Please test, I haven't worked with CMake in some time.

**Comment by zilongshanren** [comment]
@firefly2442 
How could I test your code?

What kind of Linux distribution should I have?
I have Ubuntu, but it doesn't complain about the sqlite3 dependency.

**Comment by firefly2442** [comment]
@zilongshanren try this:

On Ubuntu, uninstall the `libsqlite3-dev` package.  This package contains the header file for sqlite.  Delete the CMake cache to clear out any old settings (or just delete your build folder contents).  By not having this sqlite dependency, CMake should fail and give an error but it doesn't.  CMake completes successfully and generates a solution.  Then, when you try to build Cocos2d-x, it will fail saying it's missing the sqlite header file.

I believe CMake should recognize if sqlite is missing and provide an appropriate warning/error message to prevent the solution from being generated.

**Comment by ricardoquesada** [comment]
thanks. fixed.
