### ISSUE TITLE
SocketIO - Connect failed after Disconnected

### ISSUE THREAD

**Issue by ZeroHackeR** [cocos2d/cocos2d-x#14077]
Setup:
- Platform: Android
- Framework: 3.8 (JS) (with SocketIO patch for incorrect packet format)
- Create a button to Connect to any working SocektIO (v1+) server
- Create on SocketIO's connect and disconnect event handlers

Test Flow:
- Connect to server
- You should receive connect event
- Disable your Wifi/Mobile Data
- You should receive disconnect event
- Now, enable your Wifi/Mobile Data
- Try to connect again
- No event fire

**Comment by ZeroHackeR** [comment]
Update:

As per catlog,
JSB SocketIO.connect method was called
But, JSB SocketIO::SIODelegate->fireEventToScript method was NOT called

**Comment by man2** [comment]
I think it's because cocos2d-x socket.io implementation haven't implemented reconnect even. I don't know how to do it also. I tried adding on "reconnect" event with no success

**Comment by ZeroHackeR** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/3157700/10301985/f1b0abe0-6c2d-11e5-8f88-200d03d62ba6.png)

Update: https://github.com/ZeroHackeR/cocos2d-x/commit/4cfe13999115970613151e407889910fc718a5d4

**Comment by ZeroHackeR** [comment]
@man2 Yes.. there is no reconnect methods. We got to manually monitor and connect again if it gets disconnected. And there was a bug as above when tried to connect again.

**Comment by man2** [comment]
thanks for the fix.. awesome..

**Comment by ZeroHackeR** [comment]
@pandamicro  Please check and merge

**Comment by pandamicro** [comment]
Thanks for the fix, it have been reviewed and merged

**Comment by ZeroHackeR** [comment]
Glad to be a part of this awesome engine ;)

**Comment by pandamicro** [comment]
The pleasure is ours ～

**Comment by pbes0707** [comment]
Hi, I'm having the same issues. I tried to reconnect via my current code, but Heap Memory leak occurred . I think Memory leak is caused by "c->disconnect". That might be "socket->disconnect". please check this code~ ㅜ^ㅜ

**Comment by Super-Man** [comment]
When the server disconnects 。 the client response disconnect function. Re-connect Crash。
How to reconnect socket ? please give an example 。

sioManager.init = function(){
   sioManager._clientSio = SocketIO.connect("www.xxx.ur",{"force new connection": true });
   sioManager._clientSio.on("connect",function(){
   });
  sioManager._clientSio.on("disconnect",sioManager.disconnect);
};

sioManager.disconnect = function(){
    sioManager._clientSio.disconnect();
    sioManager._clientSio = null;
    sioManager.init();
}

this is my code , i don't find where problem>...

**Comment by ZeroHackeR** [comment]
@Super-Man what is your cocos version? make sure your socketio.cpp has the fixes as above...

and try to add some delay before calling init...

**Comment by Super-Man** [comment]
@ZeroHackeR  I try to disconnect the response received when a record label, indicating disconnected. Then call disconnect (); time to get in the timer status is disconnected, go to init () but the connection again, unsuccessful.
And call disconnect (),the project will be crash.

this is my code

var sioManager = sioManager || {};
sioManager._sioClient = null;
sioManager.connectState = 1; // 0: connect success ，1: connecting  2: disconnect
sioManager.sendReconnectTime = 0 ;  // reconnect time 

// sio init
sioManager.init = function(){
  sioManager.connectState = 1;
  sioManager._sioClient = SocketIO.connect(" 192.168.10.11",{"force new connection" : true});
  sioManager._sioClient.on("connect",function(){ 
    sioManager.connectState = 0;
  }); 

 sioManager._sioClient.on("disconnect",sioManager.disconnection);
 sioManager._sioClient.on("error",sioManager.onerror);
};

sioManager.disconnection = function(){
  if(sioManager.connectState == 0){
    sioManager.connectState = 2;
    sioManager._sioClient.disconnect();   // there response application will crash . on SocketImple.onColse  
   sioManager._sioClient = null;
 } ;  
};

In the main scene. schedule function, 

this.schedule(this.reconnectSio,1);

reconnectSio :function(dt){
   if(sioManager.connectState == 2  && (G_severTime - sioManager.sendReconnectTime) >= 5000){
      sioManager.init(); 
   }
},

**Comment by ZeroHackeR** [comment]
@Super-Man  I think, you don't need to call sioManager._sioClient.disconnect() as socket must be already disconnected to reach to "disconnect" event handler. 

All the best and I'm already using Socket.IO in two of my games and they are working fine. 

Good Luck Bro!

**Comment by Super-Man** [comment]
@ZeroHackeR  
thank you!
I'll try, but found again in the timer init (), the connection is unsuccessful. SocketIO and no reconnection mechanism ..
I want to reconnect it, how?   Can you give me some advice?

**Comment by ZeroHackeR** [comment]
Here're my codes (not full version) using Cocos 3.8 (with custom socketio.cpp fix as above)

```

    ctor:function () {
        this._super();
        var self = this;
        setInterval(self.isConnected, 10 * 1000);
        return true;
    }, 

    isConnected: function(){
        if(_DataLayer._socket == null || !_DataLayer._socket.connected){
            _DataLayer.setup();
            //cc.game.restart(); // you may restart the game if your server have handler/logic for reconnected users
        }
    },

    setup: function(){
        var self = this;
        cc.log("opening socket connection");
        var sio = SocketIO.connect(SOCKET_URL, {"force new connection" : true, reconnection: false});
        sio.on("connect", self.sioConnect);     
        sio.on("disconnect", self.sioDisconnect);       
        sio.on("error", self.sioError);     
        sio.on("hello", self.sioHello);

        self._socket = sio;
},
```

**Comment by Super-Man** [comment]
@ZeroHackeR  OK , i'll check my codes。 thank you !

**Comment by Super-Man** [comment]
@ZeroHackeR   Very helpless！
I try to reconnect delay also checked cocos version, and socketIO.cpp, .h file. With the 3.8 version of the same. But recall init (), or cause the application to crash, and the connection is unsuccessful.

**Comment by linxuanwei** [comment]
function linxuanwei_sio(_uri){
    this._socket = null;
    this._uri = _uri;
    this._isConnected = false;
}

linxuanwei_sio.prototype.connect = function(){
    var self = this;
    var theSock = SocketIO.connect(self._uri,{"force new connection":true,"reconnection": false});
    theSock.on('connect',function(){
        console.log('>>>> connect Server success');
        self._isConnected = true;
        if(self._timer) clearInterval(self._timer);
    });
    theSock.on('disconnect',function(){
        console.log('>>>> disconnect !');
        if(self._timer) clearInterval(self._timer);
        self._isConnected = false;
        self.reconnect();
    });
    theSock.on('error',function(data){
        console.log('>>>> error：'+JSON.stringify(data));
        if(self._timer) clearInterval(self._timer);
        self._isConnected = false;
        self.reconnect();
    });
    self._socket = theSock;
};

linxuanwei_sio.prototype.reconnect= function(){
    var self = this;
   // self._socket = null;
    self._timer = setInterval(function(){
    if(!self._isConnected){
        console.log('>>>>> reconnecting....');
        self.connect();
    }

After server restarted,  cocos crashed too.

**Comment by linxuanwei** [comment]
function linxuanwei_sio(_uri){
    this._socket = null;
    this._uri = _uri;
    this._isConnected = false;
}

linxuanwei_sio.prototype.connect = function(){
    var self = this;
    var theSock = SocketIO.connect(self._uri,{"force new connection":true,"reconnection": false});
    theSock.on('connect',function(){
        console.log('>>>> connect Server success');
        self._isConnected = true;
        if(self._timer) clearInterval(self._timer);
    });
    theSock.on('disconnect',function(){
        console.log('>>>> disconnect !');
        if(self._timer) clearInterval(self._timer);
        self._isConnected = false;
        self.reconnect();
    });
    theSock.on('error',function(data){
        console.log('>>>> error：'+JSON.stringify(data));
        if(self._timer) clearInterval(self._timer);
        self._isConnected = false;
        self.reconnect();
    });
    self._socket = theSock;
};

linxuanwei_sio.prototype.reconnect= function(){
    var self = this;
   // self._socket = null;
    self._timer = setInterval(function(){
    if(!self._isConnected){
        console.log('>>>>> reconnecting....');
        self.connect();
    }

@ZeroHackeR   server restarted , crashed!   I wrong?

**Comment by linxuanwei** [comment]
![image](https://cloud.githubusercontent.com/assets/10094722/14007639/85e70808-f1b3-11e5-90c6-ae6ef3d8b313.png)

**Comment by ZeroHackeR** [comment]
@linxuanwei @Super-Man  

Thanks for reporting guys... 
I will check and try to fix them when I got time...

For time being, please try to restart the game if you got disconnected.
`cc.game.restart();`

**Comment by linxuanwei** [comment]
@ZeroHackeR  @Super-Man @pandamicro 

**I found the reason of crash, after the server rebooted.**

when the server stopped, cocos would call method "SIOClientImpl::onClose()", and 
method "SIOClientImpl::onClose" would call method "SIOClient::socketClosed()",

then, cocos would call method "connect", but method "connect" called method "SIOClient::disconnect()".

so bug came ,  method "SIOClient::socketClosed()"  and method "SIOClient::disconnect()" both called method "this->release()"

free twice memory.

I added a method  

void SIOClient::disconnectNotRelease(){

```
_connected = false;

_socket->disconnectFromEndpoint(_path);
```

}

edited method "connect"

```
    //check if already connected to endpoint, handle
    c = socket->getClient(path);

    if(c == nullptr)
    {
        c = new (std::nothrow) SIOClient(host, port, path, socket, delegate);

        socket->addClient(path, c);

        socket->connectToEndpoint(path);
    }else{
    CCLOG("SocketIO: disconnect previous client");
```

**_        //c->disconnect();
         c->disconnectNotRelease();_**
