### ISSUE TITLE
Wild pointer in CCControlButton::setBackgroundSpriteForState

### ISSUE THREAD

**Issue by maxwzg** [cocos2d/cocos2d-x#1407]
CCControlButton::setBackgroundSpriteForState maybe need add a line:

```
if (getState() == state)
{
    m_backgroundSprite = sprite; // if current state == state,  m_backgroundSpriteDispatchTable have updated to new sprite, but m_backgroundSprite still equal old sprite
    needsLayout();
}
```

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2678
