### ISSUE TITLE
Sprite3D with light will become black on IOS9 Device, not on simulator, not on IOS8

### ISSUE THREAD

**Issue by lwwhb** [cocos2d/cocos2d-x#14081]
It's OK, when not use light on sprite3d object , but use any light in scene will make the sprite3d black on ios9 device.
That's must be a light bug,

**Comment by lwwhb** [comment]
fixed!

before:
s_spotLightUniformInnerAngleCosValues.assign(maxSpotLight, 0.0f);
s_spotLightUniformOuterAngleCosValues.assign(maxSpotLight, 0.0f);

affter
s_spotLightUniformInnerAngleCosValues.assign(maxSpotLight, 0.0f);
s_spotLightUniformOuterAngleCosValues.assign(maxSpotLight, 1.0f);

**Comment by zilongshanren** [comment]
@super626 
Could you please take a look at this issue?

**Comment by super626** [comment]
It is fixed. Thanks @lwwhb 
#14085

**Comment by super626** [comment]
@zilongshanren It can be closed.
