### ISSUE TITLE
crash when 'ScriptingCore::cleanup'

### ISSUE THREAD

**Issue by SongCF** [cocos2d/cocos2d-x#14092]
platform: ios
engine: v3.7 js-binding

when I exit the game, call the following code (same as the demo of cpp-helloworld click close menu item)

```
    Director::getInstance()->end();
#if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
    exit(0);
#endif
```

allways crash at ScriptingCore::cleanup:

```
    for (auto iter = _js_global_type_map.begin(); iter != _js_global_type_map.end(); ++iter)
    {
        CCLOG("typeName = %s", iter->first.c_str());
        free(iter->second->jsclass);  //  EXC_BAD_ACCESS
        free(iter->second);
    }
```

I try to find where freed `iter->second->jsclass` before `ScriptingCore::cleanup`, but not found.
why crash at this code, please tell me if you known, thanks.

**Comment by pandemosth** [comment]
+1

This has been an issue for a while and causes lots of unnecessary crash reports.

**Comment by ANUBIS-V** [comment]
+1
ios9 cocos2d-x 3.9

**Comment by minggo** [comment]
Could somebody provide a test case for it to reproduce it?

**Comment by minggo** [comment]
oh, i got it, i will test it

**Comment by minggo** [comment]
> when I exit the game, call the following code (same as the demo of cpp-helloworld click close menu item)
> 
> ``` c++
>     Director::getInstance()->end();
> #if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
>     exit(0);
> #endif
> ```

How did you do it like this? Did you invoke c++ codes from javascript? Could you please provide a test case?

**Comment by wijanarko-sukma** [comment]
+1
I was wondering if this issue is fixed or not because it happened to me every time I restarted the game using restart method from the Director
`cocos2d::Director::getInstance()->restart();`
FYI, I mainly used C++ on the game with JSB so I frequently invoke C++ codes from javascript and vice versa

**Comment by SongCF** [comment]
I'm sorry I forgot how to solved it. i no longer develop games

**Comment by Dimon4eg** [comment]
Why the issue is closed?
It still reproduces on cocos2d-x 3.17 with js binding.

js code to reproduce:

`close();`

**Comment by Dimon4eg** [comment]
I did following fix (commented destroys):

```C++
AppDelegate::~AppDelegate()
{
#if USE_AUDIO_ENGINE
    AudioEngine::end();
#elif USE_SIMPLE_AUDIO_ENGINE
    SimpleAudioEngine::end();
#endif
    //ScriptEngineManager::destroyInstance();
}

virtual ~ApplicationProtocol(){
#if CC_ENABLE_SCRIPT_BINDING
    //ScriptEngineManager::destroyInstance();
#endif
    /** clean auto release pool. */
    //PoolManager::destroyInstance();
}
```

Now app exits fine, no leaks in any case because app is closed and all resources and memory will be freed.
But I think that destroys are needed to catch app memory leaks.

**Comment by drelaptop** [comment]
double free crash, please check https://github.com/cocos2d/cocos2d-x/pull/19236 @Dimon4eg
