### ISSUE TITLE
UIAccelerometerDelegate Deprecated in iOS 5.0; Core Motion is the new API

### ISSUE THREAD

**Issue by donaldalanmorrison** [cocos2d/cocos2d-x#1409]
<pre><code>
$ find . -exec grep UIAccelerometerDelegate {} \; -print
@interface AccelerometerDispatcher : NSObject<UIAccelerometerDelegate>
./cocos2dx/platform/ios/AccelerometerDelegateWrapper.h
    id<UIAccelerometerDelegate> accelDelegate;
@property(nonatomic, assign) id<UIAccelerometerDelegate> delegate;
./cocos2dx/platform/ios/Simulation/AccelerometerSimulation.h
- (void)setDelegate:(id<UIAccelerometerDelegate>)delegate
- (id<UIAccelerometerDelegate>)delegate
./cocos2dx/platform/ios/Simulation/AccelerometerSimulation.m
@interface SkUIView : UIView <UIAccelerometerDelegate> {
./cocos2dx/platform/third_party/blackberry/include/grskia/SkUIView.h
@interface AppController : NSObject <UIAccelerometerDelegate, UIAlertViewDelegate, UITextFieldDelegate,UIApplicationDelegate> {
./samples/HelloCpp/proj.ios/AppController.h
@interface AppController : NSObject <UIAccelerometerDelegate, UIAlertViewDelegate, UITextFieldDelegate,UIApplicationDelegate> {
./samples/HelloLua/proj.ios/AppController.h
@interface AppController : NSObject <UIAccelerometerDelegate, UIAlertViewDelegate, UITextFieldDelegate,UIApplicationDelegate> {
./samples/SimpleGame/proj.ios/AppController.h
@interface AppController : NSObject <UIAccelerometerDelegate, UIAlertViewDelegate, UITextFieldDelegate,UIApplicationDelegate> {
./samples/TestJavascript/proj.ios/AppController.h
@interface AppController : NSObject <UIAccelerometerDelegate, UIAlertViewDelegate, UITextFieldDelegate,UIApplicationDelegate> {
./samples/TestLua/proj.ios/AppController.h
@interface AppController : NSObject <UIAccelerometerDelegate, UIAlertViewDelegate, UITextFieldDelegate,UIApplicationDelegate> {
./template/xcode4/base_ios.xctemplate/ios/AppController.h
@interface AppController : NSObject <UIAccelerometerDelegate, UIAlertViewDelegate, UITextFieldDelegate,UIApplicationDelegate> {
./tools/lua_project_generator/template/ios/AppController.h
</code></pre>

**Comment by godyZ** [comment]
@donaldalanmorrison Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2677
