### ISSUE TITLE
Any way to get class name for tolua C++ class?

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#14101]
I want to call the follow wrap function like: `local w1 = wrap(cc.Node)` `local w1 = wrap(cc.Sprite)` etc...

``` Lua
function wrap(toluaclass)
  local meta = getmetatable(toluaclass)
  -- use meta here...
  return function(instacne)
    if iskindof(instacne, toluaclass) then -- Error here, needs 2nd arg to be a string.
       -- ...
    end
  end
end
```

`iskindof()` requires 2nd arg as a string.
I  can't find way to get class name for tolua C++ class (eg cc.Node, cc.Sprite ...).

**Comment by xpol** [comment]
I have add a pull request cocos2d/cocos2d-x-3rd-party-libs-bin#179 should add support for this.

I can't write `iskindof(instacne, toluaclass['.name'])` then.

**Comment by zilongshanren** [comment]
@xpol  This PR seems good, but I'm not sure whether we really need this feature and it will add a .classname field to every meta table created by toulua c++, I think it's not a good idea..

Someone might not want to have this feature..

**Comment by minggo** [comment]
close it since it is not a common requirement
