### ISSUE TITLE
AppDelegate deconstructor is not called on Android

### ISSUE THREAD

**Issue by rynkowsg** [cocos2d/cocos2d-x#14110]
I used at `AppDelegate`'s deconstructor a log, and it was not printed.
I was looking and I found that `AppDelegate` object is created on the heap and probably it is not released.
Please look on the Android's `main.cpp`:

```
void cocos_android_app_init (JNIEnv* env) {
    LOGD("cocos_android_app_init");
    AppDelegate *pAppDelegate = new AppDelegate();
}
```

Does it should be like this?

**Comment by FrankStain** [comment]
@rynkowsg , all it's totally true.
It's an cocos2d-x design issue, and it's very hard to fix it. Jni and Java design must be changed to fix this issue.
Currently there is no place in java code, where `Application` could be safely finalized.

**Comment by rynkowsg** [comment]
@FrankStain 
Thanks for the clarification.

**Comment by rynkowsg** [comment]
@FrankStain,
I reopened the issue because I prepared a solution for it:
https://github.com/cocos2d/cocos2d-x/pull/16333
https://github.com/cocos2d-x/plugin-x/pull/174

In my organisation I applied this fix couple months ago and it works perfectly.

**Comment by FrankStain** [comment]
@rynkowsg ,
Wow, nice solution!

Frankly, i had never thought in such direction. Also `JNI_OnUnload` may be used for such purposes.
And, yep, i can confirm, this solution is safe. `AppDelegate` will be created only one time per library load and removed just before unloading of library (and after invocation of `JNI_OnUnload`).

**Comment by rynkowsg** [comment]
My changes have been merged. I'm going to close the issue.
