### ISSUE TITLE
support getDataFromFile in lua 

### ISSUE THREAD

**Issue by jminht** [cocos2d/cocos2d-x#14112]
Is there any way for me to use getDataFromFile in lua ?
And how is the export going ?
https://github.com/cocos2d/cocos2d-x/issues/9621

**Comment by jminht** [comment]
@pandamicro @WenhaiLin @zilongshanren 
please check my issue.

**Comment by zilongshanren** [comment]
@pandamicro  Any plans?

**Comment by linguofeng** [comment]
``` lua
local fileUtils = cc.FileUtils:getInstance()
local fullpath = fileUtils:fullPathForFilename("file.txt")
local file = io.open(fullpath, "r")
print(file:read("*a"))
file:close()
```

**Comment by jminht** [comment]
@linguofeng thanks.

**Comment by minggo** [comment]
lua has its own `io` module to do the thing, so close it
