### ISSUE TITLE
BUG: 新建helloworld项目android会调用applicationWillEnterForeground，而ios不会

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14125]
问题描述：
1.新建helloworld项目android会调用applicationWillEnterForeground，而ios不会
2.3.4和3.5版本的android也不会调用，但是3.8和3.8.1会调用

这样导致接SDK时会发送两次数据

**Comment by jimrange** [comment]
Same as this bug. 
https://github.com/cocos2d/cocos2d-x/issues/14206

It is unclear which is the "correct" way. 
Option 1: all platforms call applicationWillEnterForeground on first launch and all successive launches.
Option 2: all platforms call applicationWillEnterForeground not on the first launch but on all successive launches (this is the iOS default).

Cocos2d-x should be updated to make the calling of applicationWillEnterForeground consistent across platforms (or at least the most popular mobile platforms).

**Comment by minggo** [comment]
close it since it is duplicated with #14206
