### ISSUE TITLE
使用spriteFrameCache时重复加载image，效率很低

### ISSUE THREAD

**Issue by iNeverSleeeeep** [cocos2d/cocos2d-x#14121]
```
    Texture2D *texture = Director::getInstance()->getTextureCache()->addImage(texturePath.c_str(), image);

    if (texture)
    {
        addSpriteFramesWithDictionary(dict, texture, image.get());
        _loadedFileNames->insert(plist);
    }
    else
    {
        CCLOG("cocos2d: SpriteFrameCache: Couldn't load texture");
    }
```

以上代码，在addImage中根据fileName产生了一个临时image，在addSpriteFramesWithDictionary中，也产生了一个临时image，虽然结构较为合理，但是产生image耗时很长（我这一个图片用时0.24s)，建议addImage可以返回一个share_ptr<Image>。

**Comment by iNeverSleeeeep** [comment]
但是如果texture已经存在的情况，还是不能返回image。上面的建议只解决一点点问题。

**Comment by iNeverSleeeeep** [comment]
不好意思，应该是将
 image = new Image();
image->initWithImageFile(textureFileName);
移动到下面函数内，可以提高很多效率(因为只在下面函数中使用)
        bool flag = NinePatchImageParser::isNinePatchImage(spriteFrameName);
        if(flag)
        {
            parser.setSpriteFrameInfo(image, spriteFrame->getRectInPixels(), spriteFrame->isRotated());
            texture->addSpriteFrameCapInset(spriteFrame, parser.parseCapInset());
        }
我使用的版本是3.8.1。

**Comment by WenhaiLin** [comment]
Duplicated with https://github.com/cocos2d/cocos2d-x/issues/13666
