### ISSUE TITLE
Cocos2d-x 3.8.1 cpp template compile error

### ISSUE THREAD

**Issue by yecaokinux** [cocos2d/cocos2d-x#14133]
版本: cocos2d-x 3.8.1 
操作:
1. cocos new -p com.x.xAct -l cpp -d . xAct 
2. 然后在 HelloWorldScene.h里面添加 
# include "cocos-ext.h"

USING_NS_CC;
USING_NS_CC_EXT; 
这样几行；
3.编译工程

failed msg:
\cocos2d\extensions\gui\cccontrolextension\cccontrolutils.h(39): fatal error C1083: Cannot open include file: 'extensions/ExtensionExport.h': No such file or directory (..\Classes\HelloWorldScene.cpp)
# \cocos2d\extensions\gui\cccontrolextension\cccontrolutils.h(39): fatal error C1083: Cannot open include file: 'extensions/ExtensionExport.h': No such file or directory (..\Classes\AppDelegate.cpp)

**Comment by zilongshanren** [comment]
@yecaokinux 
which platform do you use ?

**Comment by minggo** [comment]
there is not problem in latest codes, so close this issue
