### ISSUE TITLE
New project:Undefined symbols for architecture arm64:   "_iconv_open" error!

### ISSUE THREAD

**Issue by yixiaoqingyuz** [cocos2d/cocos2d-x#14131]
Creat a new project by cocos new commond,then run this project's ios target on ios9 you can see this error.

**Comment by yixiaoqingyuz** [comment]
I know how to fix it.but, it should be fixed from the source.

**Comment by pandamicro** [comment]
Can you send us a patch via github ?

**Comment by yixiaoqingyuz** [comment]
@pandamicro Sorry,i don't no how to send a patch to your via github.
In cocos2d-x 3.8 your added the 'libiconv.dylib' library,but in iOS9 sdk this library was changed to 'libiconv.tbd'

**Comment by minggo** [comment]
there is not problem in latest codes, i think it is fixed, so close this issue

**Comment by yixiaoqingyuz** [comment]
close
