### ISSUE TITLE
can not play audio if not playing any effect and come back from background on iOS

### ISSUE THREAD

**Issue by ANUBIS-V** [cocos2d/cocos2d-x#14148]
15:47:15.912 ERROR:    [0x19e5fa000] >aurioc> 807: failed: '!pla' (enable 2, outf< 2 ch,  44100 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Float32, non-inter>)

IOS9 xcode7 cocos2d-x3.8.1

进入游戏后如果没有播放任何音效就切出游戏会报以上错误, 之后无法再播放任何音效
如果在进入游戏后播放过一次音效, 之后切出游戏不会再报错误

**Comment by pandamicro** [comment]
@xiaofeng11 Please confirm this issue
@WenhaiLin may provide some help

**Comment by 0xJimmyBeh** [comment]
@pandamicro 

I have this issue on the version iOS9 Xcode 7 cocos2d-JS v3.8.1 too.

How to reproduce this issue : 
1.Open app, then open a link with `cc.sys.openURL("http://www.cocos2d-x.org/");` which open the link with browser, Xcode will log the error 

```
15:47:15.912 ERROR: [0x19e5fa000] >aurioc> 807: failed: '!pla' (enable 2, outf< 2 ch, 44100 Hz, Float32, non-inter> inf< 2 ch, 0 Hz, Float32, non-inter>)
```

2.Play sound effect with cc.audioEngine.playEffect, no sound coming out from speaker.

Thanks.

**Comment by 0xJimmyBeh** [comment]
@pandamicro 

Found easier way to reproduce this issue with iOS 9, cocos2d-JS v3.8.1

When app at splash screen, press home button to make app go into background, the issue will happen.
The audio engine can't initialise when app in background mode.

When comment out `SimpleAudioEngine code` in AppDelegate.cpp, the issue won't happen.

```
void AppDelegate::applicationDidEnterBackground()
{
    auto director = Director::getInstance();
    director->stopAnimation();
    director->getEventDispatcher()->dispatchCustomEvent("game_on_hide");

    //SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
    //SimpleAudioEngine::getInstance()->pauseAllEffects();
}
```

I found a suggestion is to initialise audio engine until after the UIApplicationDidBecomeActiveNotification notification is received int this case.

But i don't know how to modify Cocos2d-x engine to to so.
https://github.com/kstenerud/ObjectAL-for-iPhone/issues/69

Please provide solution to fix this issue, thanks!

**Comment by 0xJimmyBeh** [comment]
@kongyuan @pandamicro @xiaofeng11 @WenhaiLin 

I found the solution and tested with 2 issues which would trigger the error on iOS only, Android don't have the issue.

Issue 1 :
Once open app and while app at splash screen, press home button to cause app go into background mode.

Issue 2 : 
Open app as usual, while not using any play sound effect function, switch out app with home button or open url function.

Just add a boolean variable to check did the app become active once before enter background.
It is as stated, the audio engine can't be initialise for the first time in background mode.

The pause function for audio engine will cause the error.

```
SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
SimpleAudioEngine::getInstance()->pauseAllEffects();
```

Temporarily solution

```
AppDelegate.h
private:
    bool applicationDidActive;

AppDelegate.cpp

AppDelegate::AppDelegate()
{
    applicationDidActive = false;
}

void AppDelegate::applicationDidEnterBackground()
{
    auto director = Director::getInstance();
    director->stopAnimation();
    director->getEventDispatcher()->dispatchCustomEvent("game_on_hide");

    if(applicationDidActive == true)
    {
        SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
        SimpleAudioEngine::getInstance()->pauseAllEffects();
    }
}

void AppDelegate::applicationWillEnterForeground()
{
    applicationDidActive = true;
    auto director = Director::getInstance();
    director->startAnimation();
    director->getEventDispatcher()->dispatchCustomEvent("game_on_show");
    SimpleAudioEngine::getInstance()->resumeBackgroundMusic();
    SimpleAudioEngine::getInstance()->resumeAllEffects();
}
```

Hope to see official solution.

Thanks.

**Comment by minggo** [comment]
@dumganhar please take a look since you are fixing Audio issues.

**Comment by dumganhar** [comment]
Did you play audio by `SimpleAudioEngine` or `cocos2d::experimental::AudioEngine`?

**Comment by dumganhar** [comment]
It seems that the output error log is from `alcOpenDevice`. I will continue to investigate.

**Comment by dumganhar** [comment]
UPDATED: New AudioEngine will not trigger this error.

**Comment by minggo** [comment]
@dumganhar could you paste the link of the PR that fixed this issue, then developers can take a try. Thanks.

**Comment by dumganhar** [comment]
@minggo, my fix isn't for this issue.
The issue here is related to `SimpleAudioEngine`.

**Comment by dumganhar** [comment]
Developers also report this issue at http://www.cocoachina.com/bbs/read.php?tid-281971.html
It seems that this issue exists for a long time. :(

**Comment by dumganhar** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/16228
