### ISSUE TITLE
Editbox multiline text should be verticle top.

### ISSUE THREAD

**Issue by anjandaffo** [cocos2d/cocos2d-x#14165]
In multiline Editbox the text should be vertically top align. Better to provide Api so user can set alignment of text as per requirement. But obviously in multiline textfield typing should start from top and after typing label should also start from top.

**Comment by zilongshanren** [comment]
Yeah, We should add alignment API for EditBox.
Could you make one?
Thanks.

**Comment by anjandaffo** [comment]
@zilongshanren  Yes I can, Can you give me the short details to how I create pull request.

**Comment by zilongshanren** [comment]
@anjandaffo 
This link might be helpful:
https://help.github.com/articles/creating-a-pull-request/

**Comment by anjandaffo** [comment]
@zilongshanren 

#14459 for text alignment and Inner padding.

**Comment by zilongshanren** [comment]
@anjandaffo 
Thanks, I will review the PR.

**Comment by zilongshanren** [comment]
this issue should be  resolve in the latest v3 branch.
