### ISSUE TITLE
EventListener will cause leak while deleting nodes during event dispatching

### ISSUE THREAD

**Issue by fuyifan** [cocos2d/cocos2d-x#14160]
这两天在检查内存漏洞的时候发现有大量的EventListenerCustom没有释放的问题, 我的多个朋友在开发的过程中也和我遇到相同的问题, 后网上搜索发现确实有不少开发人员也碰到相同问题, 这个问题是非常非常严重的, 具体内容可以根据这篇帖子. http://www.cocoachina.com/bbs/read.php?tid=202831

**Comment by pandamicro** [comment]
@xiaofeng11 Please take a look at this, it should be solved in this version

**Comment by xiaofeng11** [comment]
CCEventDispatcher里存在逻辑bug，如果label实在按钮点击之类的事件中被释放，removeEventListener发现当前在事件分发处理过程中，不会release掉listener，只是标记为registered false，事件分发完成后updateListener清理Listener时，只是针对当前事件的listener进行清理。而label注册的事件正常情况下基本不会发生，所以label的事件永远不会释放。修改了一下代码，如果当前是点击事件，清理整个监听列表，不再根据事件进行清理。
https://github.com/cocos2d/cocos2d-x/pull/14177
