### ISSUE TITLE
mac模拟器console窗口无法响应鼠标选中log事件

### ISSUE THREAD

**Issue by Cola-Zhang** [cocos2d/cocos2d-x#14179]
版本： cocos3.8.1
模拟器：  mac模拟器
现象：运行mac模拟器  会有两个window,  一个是游戏的window,  一个是日志的window(这里成为consoleWindow)
经调查代码consoleWindow是调用 openConsoleWindow 产生的，   生成后由于游戏window 一直调用mainLoop一直循环，  而consoleWindow无法响应鼠标选中log中的任何一行（注释掉mainLoop后consoleWindow能响应鼠标选中log）
对于mac模拟器 调试有很大影响

**Comment by minggo** [comment]
since cocos studio is canceled, so close this issue
