### ISSUE TITLE
选择支持x86 cpu在编译apk时出错了

### ISSUE THREAD

**Issue by kawais** [cocos2d/cocos2d-x#14176]
windows10下在cocos中创建项目时如果选择了支持x86 cpu和gcc优化，编译apk时提示错误

E:\test\clientproject\ZYRS>cocos compile -p android
执行命令：compile
编译模式：debug
使用 Eclipse 工程：E:\test\clientproject\ZYRS\frameworks\runtime-src\p
roj.android
未指定 Android 目标平台版本，自动查找一个可用版本...
正在执行：'"E:\cocos\androidsdk\sdk\tools\android" update project -t android-10
-p E:\test\clientproject\ZYRS\frameworks\runtime-src\proj.android'

Updated project.properties
Updated local.properties
Updated file E:\test\clientproject\ZYRS\frameworks\runtime-src\proj.an
droid\proguard-project.txt
正在执行 ndk-build...
NDK 编译模式：debug
NDK_TOOLCHAIN_VERSION: 4.9
正在执行：'"E:\cocos\androidndk\ndk-build" -C E:\test\clientproject\ZY
RS\frameworks\runtime-src\proj.android -j4 NDK_MODULE_PATH=C:\Cocos\frameworks/c
ocos2d-x-3.8;C:\Cocos\frameworks/cocos2d-x-3.8/cocos;C:\Cocos\frameworks/cocos2d
-x-3.8/external NDK_TOOLCHAIN_VERSION=4.9 NDK_DEBUG=1'

make.exe: Entering directory `E:/test/clientproject/ZYRS/frameworks/ru
ntime-src/proj.android'
[armeabi] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi/gdbserver
[armeabi] Gdbsetup       : libs/armeabi/gdb.setup
[x86] Gdbserver      : [x86-4.9] libs/x86/gdbserver
[x86] Gdbsetup       : libs/x86/gdb.setup
[armeabi] Compile++ arm  : cocos2djs_shared <= AppDelegate.cpp
arm-linux-andr
oideabi-g++: error: unrecognized argument in option '-mtune=atom'
arm-linux-androideabi-g++: note: valid arguments to '-mtune=' are: arm1020e arm1
020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s ar
m1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 ar
m620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm
740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm
8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm9
68e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a5 cortex
-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a8 cortex-a9 cortex-m0 co
rtex-m0plus cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 cortex-
r7 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmm
xt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 s
trongarm1110 xscale
arm-linux-androideabi-g++: error: unrecognized command line option '-msse3'
arm-linux-androideabi-g++: error: unrecognized command line option '-mfpmath=sse
'
[armeabi] Compile++ arm  : cocos2djs_shared <= SimpleConfigParser.cpp
make.exe: *** [obj/local/armeabi/objs/cocos2djs_shared/__/__/Classes/AppDelegate
.o] Error 1
make.exe: *** Waiting for unfinished jobs....
arm-linux-androideabi-g++: error: unrecognized argument in option '-mtune=atom'
arm-linux-androideabi-g++: note: valid arguments to '-mtune=' are: arm1020e arm1
020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s ar
m1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 ar
m620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm
740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm
8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm9
68e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a5 cortex
-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a8 cortex-a9 cortex-m0 co
rtex-m0plus cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 cortex-
r7 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmm
xt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 s
trongarm1110 xscale
arm-linux-androideabi-g++: error: unrecognized command line option '-msse3'
arm-linux-androideabi-g++: error: unrecognized command line option '-mfpmath=sse
'
make.exe: *** [obj/local/armeabi/objs/cocos2djs_shared/__/__/Classes/ide-support
/SimpleConfigParser.o] Error 1
make.exe: Leaving directory`E:/test/clientproject/ZYRS/frameworks/run
time-src/proj.android'
执行命令出错，返回值：2。

是需要安装什么东西吗？还是别的原因？

**Comment by UkiyoESoragoto** [comment]
是用cocos studio创建的项目吗？
建议先用cocos console创建新项目然后尝试编译，通过则表示cocos环境没有问题
参考这里：
http://www.cocos2d-x.org/wiki/Cocos_new

**Comment by minggo** [comment]
since cocos studio is canceled, so close this issue
