### ISSUE TITLE
Inconsistent calling of AppDelegate::applicationWillEnterForeground() on iOS vs Android

### ISSUE THREAD

**Issue by jimrange** [cocos2d/cocos2d-x#14206]
On iOS and Mac, the method AppDelegate::applicationWillEnterForeground() is only called after a game resumes. Not on first launch.

But on Android, AppDelegate::applicationWillEnterForeground() is called after resuming AND on first launch.

This result in inconsistent behavior of games on different platforms, where the behavior can and should be consistent.

More info: http://discuss.cocos2d-x.org/t/applicationwillenterforeground-always-call/24418

**Comment by fmo080308** [comment]
Yup!
No problem on IOS but Android.
AppDelegate::applicationWillEnterForeground() will be called on first launch continuously (like an update method)

**Comment by jimrange** [comment]
Same as this bug: https://github.com/cocos2d/cocos2d-x/issues/14125

**Comment by minggo** [comment]
fixed in #16201
