### ISSUE TITLE
Sprite3D AABB bug report

### ISSUE THREAD

**Issue by Seonghyun-Lee** [cocos2d/cocos2d-x#14202]
http://discuss.cocos2d-x.org/t/sprite3d--meshes-size-always-0/24462

Sprite3d::_meshes.size() = 0

always.

It drives Sprite3D::getAABB() dumb.

And, it incapacitate Ray.intersact() function from any processes.

**Comment by pandamicro** [comment]
@super626 Please take a look

**Comment by super626** [comment]
Sprite3D::create returns the root of nodes when the Sprite3D is complex. That is why your 3D Sprite has no meshes. You can find the meshes in the offsprings.

Sprite3D::getAABB only returns the AABB its own. You can use getAABBRecursively instead. This function returns the AABB combined from its own and its offsprings.

**Comment by super626** [comment]
@pandamicro We had discussed on the forum. This issue can be closed.
