### ISSUE TITLE
Physics: ContactListener Collision ordering bug

### ISSUE THREAD

**Issue by TheCodez** [cocos2d/cocos2d-x#14201]
I have a platform which has a PhysicsBody(Box). This platform has a child node with a PhysicsBody(EdgeBody) acting as a trigger. 

The problem is even though the player landed inside the trigger first, the collision of the platforms body is detected first. 

For example the player lands in the middle hitting the top trigger but still dies, because the collision is somehow detected in the platform body first 

This never happened in 3.4 and started happening when upgrading to 3.7-3.8.

Here is a picture showing the body setup :
![bug](https://cloud.githubusercontent.com/assets/4009589/10614466/c3eb88c8-775a-11e5-8087-1ee6e6a43b1c.PNG)

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree. @TheCodez
