### ISSUE TITLE
mac模拟器尺寸错误

### ISSUE THREAD

**Issue by Cola-Zhang** [cocos2d/cocos2d-x#14208]
mac显示器分辨率： 2560X1600
mac模拟器设置尺寸： 960X640
cocos2dx版本：3.8.1
实际模拟器启动显示 明显偏大  大概显示分辨率在1920X1280左右（2倍）

**Comment by drelaptop** [comment]
问题已经 2 年没得到开发者回应，直接关闭，后续有问题建议在中文论坛讨论
