### ISSUE TITLE
AudioEngine::setFinishCallback error

### ISSUE THREAD

**Issue by dongtaohan** [cocos2d/cocos2d-x#14212]
当使用 AudioEngine 播放比较长的音乐时， 接收不到 setFinishCallback 回调， 且在update里面一直检测到它的状态为 PLAYING。
Windows 上 cocos2d-x 3.6 版本可用， 3.8，3.8.1 均不可用。
Mac OSX 上 3.8.1 可用。
使用测试用例 cpp-tests 中的 AudioControlTest，把 background.mp3 换成一个长点的音乐即可再现。

**Comment by dumganhar** [comment]
@dongtaohan ,  does this issue exist in Cocos2d-x v3.12?
I tested with a large mp3 file and I could get the finished callback while play ended.

**Comment by dumganhar** [comment]
Closed it since I could not reproduce this issue.
If you this issue still exists in the latest release, feel free to open it again.
