### ISSUE TITLE
__system_property_get is deprecated in 64 bit android NDK

### ISSUE THREAD

**Issue by krishan711** [cocos2d/cocos2d-x#14221]
As discussed here https://code.google.com/p/android/issues/detail?id=143627, the __system_property_get method has been removed from the 64 bit NDK. It is used in cocos/audio/android/jni/cddandroidAndroidJavaEngine.cpp:59 and should be replaced.

**Comment by zilongshanren** [comment]
@krishan711 
thanks. Does it affect the compilation?

**Comment by minggo** [comment]
yep, i think we should fix it since we will support `armeabi-v8a` in 3.13.

**Comment by minggo** [comment]
fixed in #16205
