### ISSUE TITLE
Crash loading CCBI file with animations on Mac

### ISSUE THREAD

**Issue by kagakuninja** [cocos2d/cocos2d-x#1423]
I am using the new CocosBuilder 2.1 RC1 animations; the game runs fine in the iOS simulator, crashes when loading the CCBI file on the Mac.  The animation has auto play, and is started in CCBReader::readNodeGraphFromData

**Comment by kagakuninja** [comment]
I've discovered that the CCB tests are all compiled in 32 bit mode, and my problem has gone away by switching from 64 to 32 bit mode.  Why isn't 64 bit mode supported?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2676
