### ISSUE TITLE
使用了std命名空间下的string类与函数，编译通过，却在android平台上跳出

### ISSUE THREAD

**Issue by MaryJaneInChain** [cocos2d/cocos2d-x#14234]
在win32平台上运行正常，cocos2d-x版本为v3.4

**Comment by UkiyoESoragoto** [comment]
安卓平台需要重写你需要的函数
这里给个 std::to_string() 的做参考吧

```
#if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
namespace std
{
    template < typename T > std::string to_string( const T& n )
    {

        std::ostringstream os;
        os << n;
        return os.str();

    }
}
#endif
```

**Comment by minggo** [comment]
Sorry, what's the issue? How did you use the functions? cocos2d-x also uses std::string too, and doesn't meet any problem.

PS: please use english in future, then developers all over the world will help you. You can use Chinese together with english like this:

```
你好
hello
```
