### ISSUE TITLE
3.9 PhysicsBody update() is called twice

### ISSUE THREAD

**Issue by TheCodez** [cocos2d/cocos2d-x#14231]
It's called in PhysicsWorld and ComponentContainer
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/physics/CCPhysicsWorld.cpp#L845
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCComponentContainer.cpp#L129

Before the integration of Script Components it was only called in PhysicsWorld, as script components added `scheduleUpdate()` to node's `addComponent()` method

**Comment by pandamicro** [comment]
@WenhaiLin  Can you confirm this issue ?
