### ISSUE TITLE
Can't use "Custom Class" in CCBReader 

### ISSUE THREAD

**Issue by young40** [cocos2d/cocos2d-x#1424]
I have a sample class "Welcome" here

Welcome.h
# ifndef **Tank__Welcome**
# define **Tank__Welcome**
# include "cocos2d.h"

USING_NS_CC;

class Welcome : public CCLayer
{
public:
    void pressedStart();
};
# endif /\* defined(**Tank__Welcome**) */

Welcome.cpp:
# include "Welcome.h"

void Welcome::pressedStart()
{
    CCLog("welcome");
}

after set "Custom Class" to welcome.ccb in Cocosbuilder v2.1beta0,
I try to run the project in xCode, stopped at:
CCNodeLoader \* CCNodeLoaderLibrary::getCCNodeLoader(CCString \* pClassName) {
    CCNodeLoaderMap::iterator ccNodeLoadersIterator = this->mCCNodeLoaders.find(pClassName);
    assert(ccNodeLoadersIterator != this->mCCNodeLoaders.end());
    return ccNodeLoadersIterator->second;
}

is there something wrong? or there is a bug of cocos2d-x?

and is there a full demo of CocosBuilder in Cocos2d-x?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2675

**Comment by young40** [comment]
@godyZ there is no issue about this now.

**Comment by godyZ** [comment]
@young40  ok i will close it in redmine, thx
