### ISSUE TITLE
UIHelper 不能找到Sprite底下的子節點

### ISSUE THREAD

**Issue by sianzain** [cocos2d/cocos2d-x#14250]
Widget\* child = dynamic_cast<Widget*>(subWidget);
Sprite不能被轉成Widget
所以child 為 NULL

![image](https://cloud.githubusercontent.com/assets/11533618/10782940/19f96818-7d8f-11e5-9fa5-db67036dc6bb.png)

**Comment by pandamicro** [comment]
It's designed this way, you can't find a normal node with UIHelper's API, please use Node::enumerateChildren API
