### ISSUE TITLE
SimulatorApp.mm 224-225行

### ISSUE THREAD

**Issue by wetiontop** [cocos2d/cocos2d-x#14259]
```
    if (nPos > 0)
        solutionDir = solutionDir.substr(0, nPos + 1);
```

模拟器加载config.json文件路径会截取多一层文件夹如
cocos/test/config.json 通过上面的代码会输出 cocos/config.json 导致无法加载配置文件

**Comment by pandamicro** [comment]
It should have been fixed @xiaofeng11 ?

**Comment by xiaofeng11** [comment]
按照我们当前编辑器创建项目的路径结构是 : "项目目录/cocosstudio/MainScene.csd"，config.json保存在“项目目录”文件夹下，solutionDir是指包含csd文件的目录，也就是"cocosstudio"一层，所以目录必须多截取一层才能让模拟器正确加载"项目目录"下的config.json。
@pandamicro 上一次提交的修改是修正少截取了一层目录，去读取"项目目录/cocosstudio"目录下的config.json导致文件找不到。

**Comment by minggo** [comment]
since cocos studio is canceled, so close the issue
