### ISSUE TITLE
Cocos2d-x 3.8.1 Win 10 Universal Build crash

### ISSUE THREAD

**Issue by ghua78** [cocos2d/cocos2d-x#14258]
I am trying to have different xaml files on mobile and desktop. 
If I add DeviceFamily-Mobile directory to the project and inside it create another OpenGLESPage.xaml (this one is without .cpp as in theory it should reuse original cpp code) then there is crash on mobile emulator when I try to click/touch anywhere on the screen:

Catastrophic failure 0x8000ffff in cocos2d::GLViewImpl::OnPointerPressed line 251
called from cocos2d::PointerEvent::execute() line 58

Any ideas how to fix it?

**Comment by stammen** [comment]
There is bug in the current win 10 mobile emulator that crashes on pointer press events. You will need to run your app on a windows phone upgraded to windows 10 for now. Keep working on the store app until the emulator is fixed.
