### ISSUE TITLE
iOS上cc.director.end()与安卓表现不同

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14267]
cocos-js v3.6.1
安卓调用cc.director.end()会直接结束进程，而iOS上调用后屏幕会一直黑掉，进程实际还未结束，
PS：在frameworks\js-bindings\cocos2d-x\cocos\platform\ios\CCGLViewImpl-ios.mm文件第195行void GLViewImpl::end()方法中，方法最后添加exit(0)，然后可以结束进程。

**Comment by SongCF** [comment]
请问一下 这样exit时，在`ScriptingCode::cleanup`中会crash吗？
因为我们在`Director::end`中调用exit时会因野指针导致crash
https://github.com/cocos2d/cocos2d-x/issues/14092
https://github.com/cocos2d/cocos2d-x/issues/14279

**Comment by pengsheng998** [comment]
@SongCF exit(0)应该是结束进程了啊，你是不是连着Xcode点了退出。

**Comment by ppzflpp** [comment]
安卓如何不结束进程，但是引擎本身占用的资源都能释放掉？尤其是c++，还有js那块所有内存释放掉，java 层surfaceview不释放掉

**Comment by pengsheng998** [comment]
@ppzflpp replaceScene应该会做释放资源动作的吧，不过对于泄露的资源就没办法了

**Comment by ppzflpp** [comment]
我现在的做法就是当js里面触发某个动作，我直接调用js里面的director.end函数,c+这边，我在GLViewImpl里面没有并没有杀进程，而是调用delete appdelegate,这个类的的析构函数会调用scriptingCore.cleanup函数，这样做可以达到我的预期，可以重复开启关闭引擎（不用杀死进程），但是每次关闭开启会泄露大概2M  native相关的内存，这个你有什么好的建议没

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@1078559858 @SongCF @pengsheng998 @ppzflpp 

or you can discuss this at Chinese forum http://forum.cocos.com/c/cocos2d-x
