### ISSUE TITLE
Unknown CMake command "cocos_find_package".

### ISSUE THREAD

**Issue by solodon4** [cocos2d/cocos2d-x#14278]
F:\OpenSource\cocos2d-x\tests\cpp-tests\build>cmake ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23419.0
-- The CXX compiler identification is MSVC 19.0.23419.0
-- Check for working C compiler using: Visual Studio 14 2015
-- Check for working C compiler using: Visual Studio 14 2015 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 14 2015
-- Check for working CXX compiler using: Visual Studio 14 2015 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (cocos_find_package):
  Unknown CMake command "cocos_find_package".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

```
cmake_minimum_required(VERSION 3.3)
```

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "F:/OpenSource/cocos2d-x/tests/cpp-tests/build/CMakeFiles/CMakeOutput.log".

**Comment by minggo** [comment]
I think it is fixed, i have met the issue. Please reopen it if it still exists.
