### ISSUE TITLE
gl.readPixels:Can not got transparent color, alpha always got 255 as its value. 

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#14284]
```
        var _self=this;  //this is extend from cc.Sprite
        var spriteSize = _self.getContentSize();
        var renderTexture = new cc.RenderTexture(spriteSize.width, spriteSize.height, cc.PIXEL_FORMAT_RGBA8888, gl.DEPTH24_STENCIL8_OES);
        renderTexture.beginWithClear(0, 0, 0, 0);
        //renderTexture.begin();
        _self.visit();
        var colors=new Uint8Array(4);
        gl.readPixels(pos.x, pos.y, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE,colors );
        console.log(colors);   //Can not got transparent color, alpha always got 255 as its value. And found when click on the transparent place in this Sprite, got the color of background of current Scene.
        renderTexture.end();


      Can anybody tell me how to fix this? Or this is a bug of cocos2dx-js? Because somebody said the same code can got transparent color in pre-version cocos2d-js. 
    谁可以告诉我上面的代码应该如何修改才可以获得正确的值吗？也许这是一个cocos2d-js的bug？
```

**Comment by pandamicro** [comment]
@xiaofeng11 Can you take a look at this issue？

**Comment by xiaofeng11** [comment]
I'm not familiar on OpenGL related functions.
@super626 Could you take a look on this issue.

**Comment by liuyi** [comment]
I found a article said that the reason maybe is render queue cased this problem. just cached it in queue but not execute at once.  
A code clip at below:

```
var _self=this;  //this is extend from cc.Sprite
    var spriteSize = _self.getContentSize();
    var renderTexture = new cc.RenderTexture(spriteSize.width, spriteSize.height, cc.PIXEL_FORMAT_RGBA8888, gl.DEPTH24_STENCIL8_OES);
    renderTexture.beginWithClear(0, 0, 0, 0);
    //renderTexture.begin();
    _self.visit();
    var colors=new Uint8Array(4);
    gl.readPixels(pos.x, pos.y, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE,colors );
    console.log(colors);   //Can not got transparent color, 
```

//alpha always got 255 as its value. 
//And found when click on the transparent place in this Sprite, 
//got the color of background of current Scene.
        renderTexture.end();

```
      cc.director.forceRenderer();    
       var img=renderTexture.newImage();
       var imgData= img.getData(); //got null ...
```

ref link:http://blog.csdn.net/super_level/article/details/41707687  

I  translated it in Javascript but   image data is null.

c++ added a custom method:
void Director::forceRendere()
{
    _renderer->render();
}

**Comment by liuyi** [comment]
I just wan get the pixel on the texture... help you guys can give some advices. THANKS!

**Comment by liuyi** [comment]
OKEY.. I use cpp resolved this issue. Added a new method in Sprite, do all the action in cpp side.

**Comment by liuyi** [comment]
中国人做项目就是这个样子，谁谁谁去看下 然后就没有然后 也没有任何回复 真是搞笑。。。

**Comment by cheerayhuang** [comment]
@liuyi， completely agree with you.  what a pity!  :dart:

**Comment by js305492881** [comment]
醉了、

**Comment by minggo** [comment]
@liuyi you are right, render texture just sends commands to renderer, and will take effect after `Renderer::render()` is invoked. If you want to get the result immediately, i think you can invoke `Director::getInstance()->getRenderer()->render()` yourself before getting the result.
