### ISSUE TITLE
featureRequest:make Node can be added to the listview!

### ISSUE THREAD

**Issue by zj8487** [cocos2d/cocos2d-x#14281]
@pandamicro

**Comment by zilongshanren** [comment]
@zj8487  Node doesn't support layout in Widget system. So it can't be added into the listview.

**Comment by zj8487** [comment]
@zilongshanren 
but i think it is necessary, for example, we create a node in the cocostudio. and want the node can be shared, and want make it be added into the listview in the runtime.

**Comment by pandamicro** [comment]
Sorry, it's not the purpose of ListView, it can only accept Widget type node in its children. If you want to reuse a node, maybe you need to manually control it in the scene graph, for example:
- parent
  - node
  - ListView
