### ISSUE TITLE
UIText的copySpecialProperties方法拷贝属性不全

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14288]
CocosV3.8    c++
UIText的这个copySpecialProperties这个方法里没有对阴影和描边等属性进行拷贝

**Comment by pandamicro** [comment]
@xiaofeng11 please check whether it have been fixed

**Comment by zilongshanren** [comment]
@1078559858 
This issue exists mainly because Label doesn't support deep copy.

**Comment by xiaofeng11** [comment]
@1078559858 https://github.com/cocos2d/cocos2d-x/pull/14639 this pr have fix the issue, please check. It will come with cocos2dx v3.10
