### ISSUE TITLE
Button with setEnabled(false) always visible

### ISSUE THREAD

**Issue by milos1290** [cocos2d/cocos2d-x#14286]
Button with setEnabled(false) and setOpacity(0) will always stay visible, because of this FadeIn action wont work.

**Comment by zilongshanren** [comment]
@milos1290 
Could you provide an example to reproduce this issue?

**Comment by milos1290** [comment]
``` cpp
        auto button = Button::create("button_image.png");
        button->setEnabled(false);
        button->setOpacity(0);
```

**Comment by minggo** [comment]
@milos1290 i tested with the codes with latest codes, button is not visible, so i think the bug is fixed.

And Button::setEnabled() doesn't control the visibility of button, so i think the title is not correctly.

**Comment by milos1290** [comment]
If i remember well, the issue was when you call Button::SetEnabled() it will use different shader for disabled state which will not be influenced with opacity, and resulting in button visible

**Comment by minggo** [comment]
@milos1290 i am not sure, i think the codes changed. What i can make sure is that it is fixed now.
