### ISSUE TITLE
Scale9Sprite custom shader support

### ISSUE THREAD

**Issue by sianzain** [cocos2d/cocos2d-x#14289]
I first came across this when trying to use a Scale9Sprite as the stencil for ClippingNode. On mobile devices ClippingNode recursively calls setGLProgram on it's stencil renderer and it's children, however Scale9Sprite's subsprites are stored as protected children and are not effected by this process.

My current solution is to implement setGLProgram for Scale9Sprite as such:

void Scale9Sprite::setGLProgram(GLProgram *glprogram)
{
    Node::setGLProgram(glprogram);
    if(_scale9Image)
    {
        _scale9Image->setGLProgram(glprogram);
    }
    if(_scale9Enabled)
    {
        for( const auto &child: _protectedChildren )
        {
            child->setGLProgram(glprogram);
        }
    }
}
A similar issue was reported here(https://github.com/cocos2d/cocos2d-x/issues/9977) but was due to the test case being incorrectly positioned. However it's not clear if this was confirmed fixed on mobile.

Not to mention it would be useful to be able to set a custom shader for Scale9Sprite in general.

Does anyone know if this problem was solved in a more general case that I've overlooked in versions above 3.3RC0, and if not what the best approach to solving this might be?

http://discuss.cocos2d-x.org/t/scale9sprite-custom-shader-support/19824

**Comment by zilongshanren** [comment]
@sianzain 
Could you give the latest v3 code a try?
I have rewrite the whole scale9sprite, now it doesn't use 9 separate sprite any more.

**Comment by sianzain** [comment]
![image](https://cloud.githubusercontent.com/assets/11533618/11334024/330b2fe8-920d-11e5-94c3-d5499765cbd0.png)
![image](https://cloud.githubusercontent.com/assets/11533618/11334045/5be07c52-920d-11e5-8ee6-a3a904583f9f.png)
![image](https://cloud.githubusercontent.com/assets/11533618/11334052/6812fbd0-920d-11e5-8e96-f3d755bf28b7.png)

**Comment by Shulepov** [comment]
I think it will be fixed by PR #15039
