### ISSUE TITLE
How to send Cocos2d object from javascript to c++ ?

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#14291]
See an example first:
JS: var sp=new cc.Sprite("res.hello");//a picture

then send it to c++:

var result=custom_jsb_utils.pixelHitCheck(sp,cc.p(10,10));
# 

So how can we send a Sprite instance or a native object identifier  to cpp,  and then send back the result to JS side?

**Comment by ricardoquesada** [comment]
The JS bindings are doing that. It is not trivial, but my suggestion is that you take a look at our JS binding code.
In particular take a look at our manual bindings:
https://github.com/cocos2d/cocos2d-x/tree/v3/cocos/scripting/js-bindings/manual

After reading the our code, most probably you will further questions about this. If so, please, use the forum for that. thanks.
