### ISSUE TITLE
cocos2dx support to download and unzip resouces

### ISSUE THREAD

**Issue by afrazizid** [cocos2d/cocos2d-x#1429]
Hello, I am working on android platform and trying to download resources from server and need to unzip the file and save resources in sd card. What help can i get from cocos2dx framework. 

Thanking you in advance.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2674
