### ISSUE TITLE
AssetsManager can not work with https protocol on v3.9 beta0

### ISSUE THREAD

**Issue by letzgame** [cocos2d/cocos2d-x#14309]
1.)DESC:
While downloading resources using https, It gives no any callbacks.
2.)HOW TO TEST
You guys could try to test to download this file to local:
https://github.com/cocos2d/cocos2d-x/blob/v3/extensions/assets-manager/AssetsManager.cpp

**Comment by xiaofeng11** [comment]
@letzgame Does this issue is platform related or it will appear on all platform? 3.9beta0 have refactor
 the downloader implementation, on some platform it use platform library, but not libCurl as before.

**Comment by letzgame** [comment]
@xiaofeng11 
I just tested it on ios 9.
To repeat this issue, you guys could try to download a file from github.

I figured out that the callback function should be called while version is downloaded. but actually it's not.

**Comment by xiaofeng11** [comment]
@letzgame Thank you very much. I'll check it some later.

**Comment by letzgame** [comment]
@xiaofeng11 
Just now test it on UWP windows10 project, It can not work either.

**Comment by cpascal** [comment]
@letzgame Can you test with the https://github.com/cocos2d/cocos2d-x/pull/14446 code? Some of your cases are caused by that.

**Comment by letzgame** [comment]
@cpascal 
Yes I tested it just now.
It still can not work on iOS.

**Comment by letzgame** [comment]
@cpascal 
Any updates about issue?

EDIT:
I think this PR #14542  has already fixed this issue
