### ISSUE TITLE
Wrong behaviour of the UserDefault class

### ISSUE THREAD

**Issue by teestudio** [cocos2d/cocos2d-x#14307]
Egnine version: Cocos2d-x 3.8
The issue is, when any data with the key, which is not correct as name of an XML tag, is being put into the UserDefault class on Windows (and on ony other platform which is using the default tinyxml2 data backend), the XML file gets corrupted (the root "userDefault" node gets removed from the document). It makes impossible to continue working with that UserDefault file. I think that there should be some assertions/exceptions/etc which wouldn't let using those keys, or at least this thing should be somehow documented.

```
UserDefault::getInstance()->setIntegerForKey("here/is/a/wrong/key", 1917);
assert(UserDefault::getInstance()->getIntegerForKey("here/is/a/wrong/key"), 1917); // false, the program exits
```

Well, I would also recommend to use arrtibute value for keys, so there wouldn't be such troubles.

**Comment by minggo** [comment]
@teestudio sorry, what's the issue?

**Comment by teestudio** [comment]
We can't use slashes ("/" symbols) in the names of the XML tags, so the UserDefault class won't work right in this case on Windows, where the UserDefault keys are mapped as tag names because a slash can't appear in a tag name.
Since that, 
> I think that there should be some assertions/exceptions/etc which wouldn't let using those keys [keys with slashes and other prohibited symbols], or at least this thing should be somehow documented.

**Comment by minggo** [comment]
Yep, i think document is needed. Different platforms have different implementations, we should mentioned that.

**Comment by minggo** [comment]
Yep, i think document is needed. Different platforms have different implementations, we should mentioned that.

**Comment by minggo** [comment]
I added some comments https://github.com/cocos2d/cocos2d-x/pull/17122

**Comment by teestudio** [comment]
Great! I think that the ticket can be closed.
