### ISSUE TITLE
tiledmap 半透明图 变黑   

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14306]
环境：2dx 3.8.1 c++
代码修改如下：
fasttmxlayer改draw方法，blendfunc部分
int index = 0;
    for(const auto& iter : _primitives)
    {
        if(iter.second->getCount() > 0)
        {
            auto& cmd = _renderCommands[index++];
            auto blendfunc = _texture->hasPremultipliedAlpha() ? BlendFunc::ALPHA_PREMULTIPLIED : BlendFunc::ALPHA_NON_PREMULTIPLIED;
            cmd.init(iter.first, _texture->getName(), getGLProgramState(), blendfunc, iter.second, _modelViewTransform, flags);

```
        renderer->addCommand(&cmd);
    }
} 
```

原因：发现用fast时，如果在map中添加了一个使用亮色blend的动画，他的上层就会一起用这个亮色的blend，而代码中并没设置，所以添加了一句：auto blendfunc = _texture->hasPremultipliedAlpha() ? BlendFunc::ALPHA_PREMULTIPLIED : BlendFunc::ALPHA_NON_PREMULTIPLIED;
    GL::blendFunc(blendfunc.src, blendfunc.dst);

**Comment by pandamicro** [comment]
@xiaofeng11 Please take a look at this issue for the next version

**Comment by xiaofeng11** [comment]
@super626 Please confirm this render issue.

**Comment by super626** [comment]
thanks @1078559858
