### ISSUE TITLE
Touch event lost when IME popup

### ISSUE THREAD

**Issue by kennir** [cocos2d/cocos2d-x#1432]
Hi dear, I have upgrade to 2.0.3 and found a problem, the layer can't receive touch event when IME popup, Test touch sample has same problem, How can I resolve it ?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2673
