### ISSUE TITLE
fbx-conv bug? changed bone name

### ISSUE THREAD

**Issue by rosone** [cocos2d/cocos2d-x#14329]
I have a fbx file, and I use 3d tools to see its bone name is Bip001, but after I convert to c3b, its name changed to Bip0011, what should I do?

**Comment by super626** [comment]
@rosone 
Do you have bones or nodes with the same name?
We will not modify the name unless you have nodes with the same name. 
You can send me a email with your fbx attached. tony.yang@chukong-inc.com
Thanks

**Comment by rosone** [comment]
seems ok now, I don't know what happened.

**Comment by super626** [comment]
ok. You can contact with me if there is something wrong.
