### ISSUE TITLE
UILayout clipping issue

### ISSUE THREAD

**Issue by shkertt** [cocos2d/cocos2d-x#14323]
```
        float bottomOffset = worldPos.y - parentClippingRect.origin.y;
        if (bottomOffset < 0.0f)
        {
            finalY = parentClippingRect.origin.x; //这里！
            finalHeight += bottomOffset;
        }
```

**Comment by zilongshanren** [comment]
@serhtt 
What's the problem here?

**Comment by shkertt** [comment]
finalY = parentClippingRect.origin.y

**Comment by zilongshanren** [comment]
So what's the problem does this line cause?
Could you provide a more concise example?
It seems the code is wired, but I still don't know what happens.

**Comment by shkertt** [comment]
嵌套的layout，开启剪切时子layout剪切区域的原点y在父layout剪切区域下面时间要调整到和父layout的y一样 。这里写成x了。

**Comment by zilongshanren** [comment]
@serhtt  why close the issue...
