### ISSUE TITLE
AudioEngine:  Never `FinishCallback` in Windows (But Android works)

### ISSUE THREAD

**Issue by emadpres** [cocos2d/cocos2d-x#14339]
Hi
I simply play a .mp3 file ( ~ 3min)  like this:

```
_id = PlayMusic("bg.mp3");
AudioEngine::setFinishCallback(_id, [&](int _audioId, const std::string &_audioPath)
    {
            // Why I Don't reach here in windows !!!
    });
```

**Problem:**
In `windows`, my `finishCallback` (above lambda function) doesn't trigger after play finished, but the same code works fine in `Android`. therefore I have to test my every change in Android !

**PS:** I test multiple mp3 files and problem for most of them (except one short ~10 sec mp3) exists always .

_Cocos2dx version: 3.7_

**Comment by pandamicro** [comment]
@WenhaiLin Have this been fixed yet?

**Comment by fuyifan** [comment]
@pandamicro  and @WenhaiLin  Yes, I get this bug and have found some clue. First, this problem only occurs in Windows and mp3 size should larger than PCMDATA_CACHEMAXSIZE so the _queBufferFrames not is equal to 0. In this situation, AudioPlayer's rotateBufferThread _readForRemove is set to true. When the music stopped, in AudioEngionImpl's update function it = _audioPlayers.erase(it); is called, but player._finishCallback is not invoked. Actually, callback function is not invoked is not the only one bug in Windows environment, I also found AudioPlayer::play2d::alSourcePlay error code:a001 occurs frequently, when play a lot of mp3s randomly for several minutes. I think you guys should re-construct the audio engine implementation in windows system. Preload makes too many bugs.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/14414
