### ISSUE TITLE
Can not get binary data from file in a lua project?

### ISSUE THREAD

**Issue by qqjckimo** [cocos2d/cocos2d-x#14341]
I'm using Cocos2d-x v3.8 and create a lua project.
When trying to reading a binary file , *.mo file actually, I found that there are no binding of `getDataFromFile` nor `getFileData` via

``` lua
getmetatable( cc.FileUtils:getInstance() )
```

The call of `cc.Helper` and `cc.HelperFunc` also return `nil`.
I've also tried to use native `io.open` and wrapped `io.readfile` , but no way to get full path of a file from relative path in cocos, because `cc.FileUtils:getInstance():fullPathFromRelativeFilename(file_name)` only returns path which only relative to project, not 'full' path actually.

So, is there any way to read binary file in a lua project?

**Comment by xpol** [comment]
I find this problem today.
I can't believe that cocos don't have binary file reading interface for Lua.

We have 2 options:
1. let `cc.FileUtils:getInstance():getStringFromFile()` return all data from string, as we in Lua string are binary. This is more Lua way.
2. add `cc.FileUtils:getInstance():getStringFromFile()`, you may follow steps [here (Chinese)](http://xpol.logdown.com/posts/316157-how-to-elegantly-add-or-modify-lua-bindings-for-cocos2d-x).

Here is my hot fixes:

``` c++
static int fs_getDataFromFile(lua_State * L)
{
    size_t len;
    const char* cfilename = luaL_checklstring(L, 2, &len); // arg 1 is FileUtils itself.
    std::string filename(cfilename, len);
    auto fs = cocos2d::FileUtils::getInstance()->getInstance();

    if (!fs->isFileExist(filename))
    {
        lua_pushnil(L);
        lua_pushliteral(L, "file not exists");
        return 2;
    }

    auto data = fs->getDataFromFile(filename);
    lua_pushlstring(L, reinterpret_cast<const char*>(data.getBytes()), static_cast<size_t>(data.getSize()));
    return 1;
}

int patch_cc_modules(lua_State* L)
{
    tolua_open(L);
    tolua_module(L, "cc", 0);
    tolua_beginmodule(L, "cc");
        tolua_beginmodule(L,"FileUtils");
            tolua_function(L,"getDataFromFile",fs_getDataFromFile);
        tolua_endmodule(L);
    tolua_endmodule(L);

    return 0;
}
```

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17182
