### ISSUE TITLE
SimpleAudioEngine CocosDension playSound bug and possible fix

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#14349]
Hi, I've experienced a bug with playSound function. 
How to reproduce problem:
1) play a sound in a loop at startup
2) add button which plays other sound
3) click button 32 times and boom.. sound played at startup will stop.

That's because this function seems working wrong:

```
    int sourceIndex = [self _getSourceIndexForSourceGroup:sourceGroupId];
```

I don't understand how exactly _getSourceIndexForSourceGroup:sourceGroupId works so I've added simple fix after this line:

```
    for(int i = 0; i < sourceTotal_; i++){
        ALint state;
        ALuint source = _sources[i].sourceId;
        alGetSourcei(source, AL_SOURCE_STATE, &state);
        if (state != AL_PLAYING && state != AL_PAUSED) {
            sourceIndex = i;
            break;
        }
    }
```

as I've found out sourceGroupId is always 0 anyway.
My loop is simply checking first non-playing/non-paused sound.

**Comment by dumganhar** [comment]
The same issue as https://github.com/cocos2d/cocos2d-x/issues/14335.
Please refer to my post in that issue.

**Comment by minggo** [comment]
Close it since it is a duplicate issue.
