### ISSUE TITLE
cocos2d-x-3.8.1 js can not debug on Firefox 40 and above

### ISSUE THREAD

**Issue by war3gu** [cocos2d/cocos2d-x#14347]
按照官方教程，使用firefox，进行到需要点击Hello Cocos2d-X JSb，就继续不下去了。

**Comment by nil1511** [comment]
for jsb debugging try with firefox version 39 or below. JSB Debugging is not working from firefox version 40 onwards.

**Comment by pandamicro** [comment]
Please do as @nil1511 suggested.

Thanks, @nil1511

**Comment by minggo** [comment]
It is fixed.
