### ISSUE TITLE
ios9 cceditbox键盘适配问题

### ISSUE THREAD

**Issue by jasonz1987** [cocos2d/cocos2d-x#14370]
在iOS9的设备上，点击cceditbox会出现游戏屏幕尺寸异常，键盘隐藏后还是无法恢复（这个问题曾经在ios8上出现过，我按照官方的代码修复了）
后来，我在 `onUIKeyboardNotification` 方法后添加了以下代码：
<pre><code>if(originalRect_.size.height > originalRect_.size.width) {
      CGFloat tempValue = originalRect_.size.height;
       originalRect_.size.height = originalRect_.size.width;
       originalRect_.size.width = tempValue;
}</pre></code>
游戏的屏幕可以被正常推到上面，但是键盘的弹出方向会出现问题
1. 手机横屏状态且屏幕方向不锁定，键盘横屏弹出
2. 手机竖屏无论屏幕方向锁不锁定，键盘竖屏弹出
3. 手机横屏且屏幕方向锁定，键盘竖屏弹出。

请给位帮忙解答？

**Comment by jasonz1987** [comment]
最重发现是某个sdk不适配导致的，但是上面那几句代码还是需要的～

**Comment by zilongshanren** [comment]
@jasonz1987 
I think it's not needed.  But anyway, if you still have issue with EditBox keyboard animation, feel free to reopen.

**Comment by rablwupei** [comment]
这句确实需要.....多谢....iphone6s, ios10.2
