### ISSUE TITLE
crash js::jit::AutoFlushICache

### ISSUE THREAD

**Issue by SongCF** [cocos2d/cocos2d-x#14374]
When my game enters the background, there is a probability that it will crash.

```
SIGSEGV(SEGV_MAPERR)
#00 pc 00d28718 libgame.so js::jit::AutoFlushICache::AutoFlushICache(char const*, bool)
```

I did not find this function in SpiderMonkey, I can't understand why it's here to crash.
Who knows, could you tell me, or give me some advice.
thank you.

**Comment by SongCF** [comment]
resolved: 
my bad, java call native method not in the GL thread.

**Comment by sanchguy** [comment]
could you tell me more detail?! I have this problem now ?

**Comment by sanchguy** [comment]
could you tell me more detail?! I have this problem now ~~~~~~！thank you
