### ISSUE TITLE
Scale9Sprite opacity cant change when I setState gray

### ISSUE THREAD

**Issue by semgilo** [cocos2d/cocos2d-x#14378]
cocos2dx 3.6
for example:
local img = ccui.ImageView:create()  
img:loadTexture("test.png")
img:setState(1)
img:setOpacity(50)

the img opacity is 255 
50 expected

**Comment by zilongshanren** [comment]
@semgilo 
Does this issue still exists in the latest v3.9 version?

**Comment by semgilo** [comment]
@zilongshanren i dont try,i  had used shader instead

**Comment by semgilo** [comment]
@zilongshanren i try3.9 the issue exist

**Comment by stevetranby** [comment]
SHADER_NAME_POSITION_GRAYSCALE
Update `ccPositionTexture_GrayScale_frag` to multiply v_fragmentColor.a possibly not multiplying by 0.5 and setting CCScale9Sprite's opacity by default to 128 (0.5) instead.

```
    gl_FragColor.xyz = vec3(0.2126*c.r + 0.7152*c.g + 0.0722*c.b);
    gl_FragColor.a = v_fragmentColor.a * 0.5; 
```

**Comment by zilongshanren** [comment]
@stevetranby  @semgilo

Fixed at #14854

**Comment by semgilo** [comment]
@zilongshanren 3q

**Comment by semgilo** [comment]
@stevetranby 3q
