### ISSUE TITLE
UI::PageView::scrollPages中除了判断_touchMoveDirection外还需要处理_autoScrollDirection

### ISSUE THREAD

**Issue by 120910383** [cocos2d/cocos2d-x#14389]
重现方法，设置PageView滚动方向为垂直滚动，创建后不要触发touch事件，那么_touchMoveDirection将一直为初始值，此时调用scrollToPage，最终会进入scrollPages函数，而其内部仅仅对_touchMoveDirection进行判断，而没有处理_autoScrollDirection，导致滚动方向bug
版本为官网3.8.1正式版

**Comment by zilongshanren** [comment]
Could you try the latest code in the v3 branch.
The new PageView implementation is totally changed. Now it inherit from ListView and it also adds PageView indicator which I think is very useful.

**Comment by zilongshanren** [comment]
@120910383 
please next time use English here. 
If the issue is still exists on the v3 branch, feel free to reopen this issue.
Thanks.
