### ISSUE TITLE
AssetsManagerEx has memory leak.

### ISSUE THREAD

**Issue by pengbn** [cocos2d/cocos2d-x#14386]
We should release _downloader object int AssetsManagerEx::~AssetsManagerEx().

**Comment by pengbn** [comment]
We should release _downloader object int AssetsManagerEx::~AssetsManagerEx().

**Comment by pandamicro** [comment]
_downloader是一个shared_ptr，会随着AssetsManagerEx的销毁而被销毁，自动释放_downloader的内存
