### ISSUE TITLE
Version 3.8.1 is a branch and not a tag

### ISSUE THREAD

**Issue by michaelcontento** [cocos2d/cocos2d-x#14387]
I'm a bit confused as `3.8.1` is only a branch in git an not a tag -- is this on purpose or by accident?

**Comment by michaelcontento** [comment]
Oh, and it seems that `3.9beta0` is released[1] but the tag is missing aswell. It would be nice if this could be sorted out, as it would allow to diff around and see what happend in details :)

[1] http://discuss.cocos2d-x.org/t/cocos2d-x-3-9-beta0-released/24507

**Comment by slackmoehrle** [comment]
Thanks. We shall check into this. @pandamicro can you create these tags? What is Eddy's GitHub ID?

**Comment by michaelcontento** [comment]
Tags are now present - thanks a lot!
