### ISSUE TITLE
[Web] UITextField not working in iOS9 QZone browser

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#14380]
In iOS 9 QZone browser, UITextField can't prompt input keyboard

**Comment by zeamais** [comment]
EditBox 我在使用过程中遇到一个问题， 在UC浏览器上，如果添加了事件监听，则在上面无法输入数字。如果没添加事件监听，则可以输入数字。

**Comment by pandamicro** [comment]
Solved by overwrite back the prompt function to original one
