### ISSUE TITLE
[WEB] Cross origin image was ok in v3.6, but not working in v3.8 +

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#14398]
Should compare `cc.loader.loadImg` implementation between these two version and test.

**Comment by fuchao9625** [comment]
Hi guys, when will you have time to fix this bug?

**Comment by drelaptop** [comment]
@pandamicro @fuchao9625 

This issues have been ignored for more than 2 years, and no one care it, so just close. Please reopen if disagree.
