### ISSUE TITLE
cc.RotateTo arg 2

### ISSUE THREAD

**Issue by sianzain** [cocos2d/cocos2d-x#14407]
![image](https://cloud.githubusercontent.com/assets/11533618/11202307/ada6c2ee-8d21-11e5-84bc-ba97e9cc3a44.png)

**Comment by sianzain** [comment]
jsb_create_apis.js

**Comment by minggo** [comment]
I don't think it is an issue. If there is not `deltaAngleY`, then use `deltaAngleX`.
