### ISSUE TITLE
android 退出activity后，下次如何进行cocos2dx AppDelegate的重新初始化

### ISSUE THREAD

**Issue by fangshuai0119** [cocos2d/cocos2d-x#14400]
我现在进入Cocos2dxActivity后进行了一次初始化，然后就结束了当前的activity，当我再次进入activity的时候，还是上次我进行的操作，我现在应该如何进行初始化呢

**Comment by minggo** [comment]
Sorry, don't quite understand the issue. And please use english in future, then developers all over the world can help you. Thanks.
