### ISSUE TITLE
MAC - CocosDenshion Crash

### ISSUE THREAD

**Issue by edbartley** [cocos2d/cocos2d-x#1440]
When running the CocosDenshion test in the TestCPP project there is a crash during init. Here is the stack trace:
#1  0x0010c688 in -[SimpleAudioEngine init] at /Users/ed/dev/cocos2d-x-master/samples/TestCpp/proj.mac/../../../CocosDenshion/mac/SimpleAudioEngine_objc.m:57
#2  0x0010c4a2 in +[SimpleAudioEngine sharedEngine] at /Users/ed/dev/cocos2d-x-master/samples/TestCpp/proj.mac/../../../CocosDenshion/mac/SimpleAudioEngine_objc.m:39
#3  0x0010bd06 in static_preloadBackgroundMusic [inlined] at /Users/ed/dev/cocos2d-x-master/samples/TestCpp/proj.mac/../../../CocosDenshion/mac/SimpleAudioEngine.mm:35
#4  0x0010bce3 in CocosDenshion::SimpleAudioEngine::preloadBackgroundMusic(char const*) at /Users/ed/dev/cocos2d-x-master/samples/TestCpp/proj.mac/../../../CocosDenshion/mac/SimpleAudioEngine.mm:177
#5  0x0003b729 in CocosDenshionTest::CocosDenshionTest() at /Users/ed/dev/cocos2d-x-master/samples/TestCpp/proj.mac/../classes/CocosDenshionTest/CocosDenshionTest.cpp:79
#6  0x0003c2be in CocosDenshionTestScene::runThisTest() at /Users/ed/dev/cocos2d-x-master/samples/TestCpp/proj.mac/../classes/CocosDenshionTest/CocosDenshionTest.cpp:226
#7  0x0003c8b6 in TestController::menuCallback(cocos2d::CCObject*) at /Users/ed/dev/cocos2d-x-master/samples/TestCpp/proj.mac/../classes/controller.cpp:182
#8  0x001f0183 in cocos2d::CCMenuItem::activate() at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../menu_nodes/CCMenuItem.cpp:119
#9  0x001f09f1 in cocos2d::CCMenuItemLabel::activate() at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../menu_nodes/CCMenuItem.cpp:242
#10 0x001ec05c in cocos2d::CCMenu::ccTouchEnded(cocos2d::CCTouch_, cocos2d::CCEvent_) at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../menu_nodes/CCMenu.cpp:258
#11 0x001ec0b6 in non-virtual thunk to cocos2d::CCMenu::ccTouchEnded(cocos2d::CCTouch_, cocos2d::CCEvent_) at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../menu_nodes/CCMenu.cpp:261
#12 0x0025671f in cocos2d::CCTouchDispatcher::touches(cocos2d::CCSet_, cocos2d::CCEvent_, unsigned int) at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../touch_dispatcher/CCTouchDispatcher.cpp:377
#13 0x00256da2 in cocos2d::CCTouchDispatcher::touchesEnded(cocos2d::CCSet_, cocos2d::CCEvent_) at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../touch_dispatcher/CCTouchDispatcher.cpp:507
#14 0x00256de6 in non-virtual thunk to cocos2d::CCTouchDispatcher::touchesEnded(cocos2d::CCSet_, cocos2d::CCEvent_) at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../touch_dispatcher/CCTouchDispatcher.cpp:509
#15 0x0020e698 in cocos2d::CCEGLViewProtocol::handleTouchesEnd(int, int_, float_, float*) at /Users/ed/dev/cocos2d-x-master/cocos2dx/proj.mac/../platform/CCEGLViewProtocol.cpp:336

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to  http://www.cocos2d-x.org/issues/2672
