### ISSUE TITLE
android上游戏从后台切换回到前台或者从第三方应用切回来,ttf字体有时候出现纹理丢失

### ISSUE THREAD

**Issue by zxzAndyMAC** [cocos2d/cocos2d-x#14406]
引擎版本：3.7
使用ui组件：UIText
ccs：1.6

android上游戏从后台切换回到前台或者从第三方应用切回来,ttf字体有时候出现纹理丢失导致部分字体无法显示，非必现，但出现概率还是挺高，求解决方案，魅族4，三星s6都出现这样问题，概率高, 原生系统也会出现

**Comment by zxzAndyMAC** [comment]
fixed in v3.8

**Comment by TwoEggDu** [comment]
我遇到了相同的问题，请问除了升级引擎还有别的方法吗？我现在使用的是3.6
