### ISSUE TITLE
about spidermonkey's source code

### ISSUE THREAD

**Issue by SongCF** [cocos2d/cocos2d-x#14418]
For some reason, we need spidermonkey's source code which version in cocos2d-x.
When we search at repo 'cocos2d-x-3rd-party-libs-src', but not found. And download at  [Ricardo Quesada's Spidermonkey fork](https://github.com/ricardoquesada/Spidermonkey), found so much different from cocos2d-x release.
![qq 20151118114924](https://cloud.githubusercontent.com/assets/3910887/11232133/9d40d59c-8dea-11e5-9647-99834193c36f.png)
so, could you please tell me where can get spidermonkey's source code which version in cocos2d-x ?
thanks.

**Comment by pandamicro** [comment]
The source code is in Riq's repo. The header files was generated from it.

The current version we are using for Cocos2d-x is SpiderMonkey v33:

https://github.com/pandamicro/Spidermonkey/tree/v33
