### ISSUE TITLE
Crash on Android when reopen Cocos2dxActivity

### ISSUE THREAD

**Issue by sdelaysam** [cocos2d/cocos2d-x#14422]
I'm using cocos2dx for single game activity inside Android app.
When activity is created, it starts director with single scene.
When activity is about to close, it ends director.
When terminateProcessJNI() is called by android GLView implementation, I finish activity instead of shutting down the whole android process.
But when I start that game activity again, it crashes.
I'm using logcat + ndk-stack and it shows SIGSEGV in CCFrameBuffer.cpp, FrameBuffer::applyFBO() method.

Using latest version of cocos2dx, build with ndk-build.

**Comment by sdelaysam** [comment]
Looks like a leak in CCFrameBuffer.
This pointer never get released.

```
static FrameBuffer* _defaultFBO;
```

Also, it cached here

```
static std::set<FrameBuffer*> _frameBuffers;
```

I changed DTOR like

```
FrameBuffer::~FrameBuffer()
{
    _frameBuffers.erase(this);

    if(!isDefaultFBO())
    {
        CC_SAFE_RELEASE_NULL(_rt);
        CC_SAFE_RELEASE_NULL(_rtDepthStencil);
        glDeleteFramebuffers(1, &_fbo);
        _fbo = 0;
#if CC_ENABLE_CACHE_TEXTURE_DATA
        Director::getInstance()->getEventDispatcher()->removeEventListener(_dirtyFBOListener);
#endif
    }
    else
    {
        _defaultFBO = nullptr;
    }
}

```

and it finally works.

And i made changes in Director DTOR.

```
Director::~Director(void)
{
   //CC_SAFE_DELETE(_defaultFBO);
    CC_SAFE_RELEASE_NULL(_defaultFBO);
}
```

Could you guys review that?

**Comment by sepperousseau** [comment]
Got same issue, I have a game that I start in a native application. When I start the game it runs correctly. When I call director->end() it never comes in appdelegate destructor. 
When I start the activity again, the app restarts =/

OpenGL error 0x0501 in purgeDirector 992

**Comment by minggo** [comment]
currently, cocos2d-x doesn't support restart like this, we may consider how to add it in future, but it will be in v4
