### ISSUE TITLE
Scale9Sprite opacity broken

### ISSUE THREAD

**Issue by 1scaR1** [cocos2d/cocos2d-x#14436]
If set opacity of scale9sprite just after it's creation, it would't be set.
This bug reproduces after #14263.
Test code is simple:

``` c++
auto sprite = new Scale9Sprite("some_image.png");
sprite.setOpacity(0); // not updated opacity os sprite.
```

P.S.
It seems to me that after moving logic of creating slices to visit function, opacity of scale9sprite is not updated.

**Comment by zilongshanren** [comment]
@1scaR1 
Thanks, I will check this issue.

**Comment by zilongshanren** [comment]
@1scaR1 
The fix is here:  https://github.com/cocos2d/cocos2d-x/pull/14443
please check whether it resolve your problem or not.
Thanks.

**Comment by 1scaR1** [comment]
Yes, it resolves my problem.
Thanks!
