### ISSUE TITLE
llvm::convertUTF16ToUTF8String() should not assert(Out.empty())

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#14431]
As in here:

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/v3/ConvertUTF/ConvertUTFWrapper.cpp#L102

The first line of llvm::convertUTF16ToUTF8String() body:

``` C++
bool convertUTF16ToUTF8String(const std::u16string& utf16, std::string &Out) {
  assert(Out.empty());

  // Avoid OOB by returning early on empty input.
  if (utf16.empty())
    return true;
```

Should removed and modify to:

``` C++
bool convertUTF16ToUTF8String(const std::u16string& utf16, std::string &Out) {
  // Avoid OOB by returning early on empty input.
  if (utf16.empty())
  {
    Out.clear();
    return true;
  }
```

The function does not require the Out string to be empty as it resize the Out string later.

**Comment by xpol** [comment]
@minggo

**Comment by minggo** [comment]
@zilongshanren 
Will you please take a look?

**Comment by zilongshanren** [comment]
@xpol 
This library is grabbed from llvm. I think it's better to discuss this problem with llvm team...

**Comment by xpol** [comment]
I'd rather clean my out string before calling.
子龙山人 notifications@github.com于2015年11月20日 周五10:51写道：
