### ISSUE TITLE
New label features (spacing, leading, kernings, line height) are strongly needed in Cocos Studio editor.

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#14437]
In cocos2d-x version 3.9 there are lots of features that not supported by CocosStudio editor.
Label line spacnig/leading, kernings, and line height are strongly needed by GUI designers.
Also, it would be great to see enabling/disabling of cascade coloring and opacity.

**Comment by ghost** [comment]
Option to set texture of scroll in scrollview is needed too.

**Comment by AIGRIND-LLC** [comment]
+1 for this request!

**Comment by vitalyrovny** [comment]
Line spacing, scroll customization +1

**Comment by FrankStain** [comment]
Pretty useful features!
+1 for all!

**Comment by RMariowski** [comment]
+1 for all

**Comment by mumreg** [comment]
+1 for all

**Comment by minggo** [comment]
close this issue since cocos studio is canceled

**Comment by AIGRIND-LLC** [comment]
- CocosCreator does not support C++ and estimates are unknown
- CocosCreator can't import CocosStudio projects without errors
- CocosCreator can't be used as just stand-alone UI editor
- CocosStudio is cancelled
  What a great news! :D

**Comment by minggo** [comment]
@AIGRIND-LLC i don't know the plan of CocosCreator. If you have any question, you are appreciated reported in cocos forum. Thanks.

**Comment by ryancheung** [comment]
+1 for line height!
