### ISSUE TITLE
cocos2d-js 3.6.1 can not  play two effects at the same time on android device.

### ISSUE THREAD

**Issue by lovekankan** [cocos2d/cocos2d-x#14442]

**Comment by lovekankan** [comment]
no one can solve this issue??

**Comment by liuyi** [comment]
Please upgrade your code to 3.8+

**Comment by liuyi** [comment]
a new audio api is there: jsb.AudioEngine

**Comment by dumganhar** [comment]
Basically, we need to deprecate SimpleAudioEngine and use `AudioEngine` to implement it.
I'm gonna achieve this. It's probably in cocos2d-x 3.14.

**Comment by dumganhar** [comment]
@lovekankan , any update of this issue?

**Comment by dumganhar** [comment]
I guess this issue was fixed in the latest release v3.14.1.
I closed this issue. If you still find any problems, feel free to open it again.
