### ISSUE TITLE
A serious bug in new UIPageView

### ISSUE THREAD

**Issue by xiaofeng11** [cocos2d/cocos2d-x#14440]
In new UIPageView, getPages function has been deprecated, and add a ASSERT in entrance of the function, when it been called, the program will crash. But in LayoutComponent::refreshLayout() function, getPages() is still been using, this make program can never run.

@neokim @zilongshanren Please check & fix this issue

**Comment by zilongshanren** [comment]
@xiaofeng11  
please check the latest code to verify it, thanks.

**Comment by xiaofeng11** [comment]
@neokim @zilongshanren Great works!
