### ISSUE TITLE
3.9 Problem with setTexture and PhysicsBody

### ISSUE THREAD

**Issue by TheCodez** [cocos2d/cocos2d-x#14449]
I have a player, im applying a force to him and change his texture to a flying one(which is wider). Then after 1 second im resetting the forces on that player and change his texture back to an idle one.

Before 3.9 this worked as expected, but now in 3.9 the player is pushed forward after 1 second because the flying texture is wider.

Apparently, this has something to do with the new way components update positions.

**Comment by TheCodez** [comment]
@WenhaiLin any news on this? This is holding our development back.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@TheCodez
