### ISSUE TITLE
Any reason of using SharedPreferences.commit() in Android?

### ISSUE THREAD

**Issue by teestudio** [cocos2d/cocos2d-x#14450]
There's an `apply()` method which lets save data with `SharedPreferences` asynchronously, so I can't understand why `commit()` is still being used in `Cocos2dxHelper` class, a game may be freezed when using it.
[SharedPreferences.apply() docs](http://developer.android.com/intl/ru/reference/android/content/SharedPreferences.Editor.html#apply%28%29)

**Comment by minggo** [comment]
@teestudio you are right, we should use `apply` instead.

**Comment by minggo** [comment]
fixed in #16632
