### ISSUE TITLE
Different behavior between pvr.ccz and png for BlendFunc dest GL_ONE

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#14452]
When set BlendFunc dest with GL_ONE in Cocos Studio, the behavior of pvr.ccz and png texture varies. It may be related to premultiple alpha settings.

Originally reported in the comment of http://weibo.com/1702027805/CzrhTdu3a?type=comment

Please contact the author to know how to reproduce and more details.

He mentioned other problems too in the comment

**Comment by young40** [comment]
Thank you, pandamicro

Sorry for this inconvenient.

truly is, I made a mistake while export png to pvr.ccz. I missed the premultiply alpha.

you can close this issue now. 

Thanks a lot, again.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
