### ISSUE TITLE
A lot of hardcoded constants in ScrollView

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#14461]
There a lot of hardcoded constants inside of ScrollView source code.

```
static const int NUMBER_OF_GATHERED_TOUCHES_FOR_MOVE_SPEED = 5;
static const float OUT_OF_BOUNDARY_BREAKING_FACTOR = 0.05f;
static const float BOUNCE_BACK_DURATION = 1.0f;

#define MOVE_INCH            7.0f/160.0f
```

```
Vec2 ScrollView::calculateTouchMoveVelocity() const
{
    float totalTime = 0;
    for(auto &timeDelta : _touchMoveTimeDeltas)
    {
        totalTime += timeDelta;
    }
    if(totalTime == 0 || totalTime >= 0.1f)
    {
        return Vec2::ZERO;
    }
```

If you don't want to give a chance to change it, at least you could give a way to use them from the outside, by moving it's declarations to header.

**Comment by zilongshanren** [comment]
@neokim 
What do you think about these hardcoded values?

**Comment by sbrednikhin** [comment]
Possibility of changing this values through class interface would be ideal. As an example: In PageView scrolling parameters can be changed from outside of class. 
If you don't want to allow parameter changing - it would be useful to declare them as static constants in public area of the class, so user could use this values to configure his code.

My widgets have custom touch behavior and this behavior is critical for functionality, but breaks scrolling. So now I have 2 variants:
1. Make some workaround to fix scrolling. In this case I need to use this hardcoded values in my code, but I cant - values are declared in source file.
2. Change hardcoded values in cocos sources, and get portion of headache with merging after new version of cocos will be released.

**Comment by neokim** [comment]
Those constants are internal properties for elastic scroll pattern. Any changes on them will be spoiling scrolling pattern. They are not supposed to be exposed to outside and to be modified without careful concern about user experiences for scroll UI.

If your changes on touch behavior breaks scrolling and so you need to refer to these values, it looks to me that there may be some design flaw in your implementation. Touch and scrolling pattern should be considered as independent parts. Even though scrolling is triggered and driven by touch event, it doesn't mean that its scroll pattern is dependent to touch feature.

If you have custom touch implementation, it can be separated from scrolling pattern in some ways.

**Comment by sbrednikhin** [comment]
You are absolutely right, about independence of scrolling and touching, until you would need to implement dragging started from scrolling panel (it is common feature). I believe that if you would implement "native" dragging mechanics in cocos, you would have similar problems.

I need custom touch processing because of dragging mechanics, but I really don't want to code my own scrolling. Simpy changing

```
if(totalTime == 0 || totalTime >= 0.1f)
```

to 

```
if(totalTime == 0 || totalTime >= 0.2f)
```

would solve all my problems without catastrophic consequences to ui functionality, but I don't have such interface. 
I can make some workaround, but I need at least to know that values.

**Comment by neokim** [comment]
The `totalTime` is used here to depress auto scrolling after touch released when user had held touch more than specific time. I agree that this value can be configurable.

BTW, can you explain more about dragging started from scrolling panel?
If a user starts dragging action in scroll panel, it means user's intention of to move the internal canvas of scroll panel. It is appropriate that scroll panel processes it by itself.

It looks that you are trying to do different action not scrolling in some case of dragging. If you try to catch another type of user's intention when user drags, it should not be a part of scroll panel.

Isn't it possibly that your case needs a customized scroll panel class derived from `UIScrollView` and overriding `calculateTouchMoveVelocity()`?
I'm not sure that providing a way to configure values can be a proper solution for your case.

**Comment by sbrednikhin** [comment]
About dragging: 
Dragging started from scroll panel is common for different mobile GUI's. There are some ways to separate dragging action from scrolling. Most common is to use long tap as indicator of dragging start (android interface) so we need to count time of tap without movement. Thus we need some minimal movement distance ( like your `#define MOVE_INCH            7.0f/160.0f` interval ) to avoid false dragging because of finger shaking or devise touch peculiar properties.
To implement dragging above your scroll, "move" touches must be processed in dragged widget that placed on scroll panel without propagation, at the same time "start" touch must be propagated. If dragging was started everything is good. But if dragging wasn't started (for example because of small time of touch, or small finger shift ), touches must be propagated to scroll panel. I can't just start propagating move touches, because a lot of time passed from touch start and auto scrolling will be suppressed (by totalTime comparison).
I could try to emulate touches swallowed by dragged widget, but in that case i need to know internal constants of scrolling mechanics.

Custom class derived from UIScrollView would be a good solution, but I need to use cocos classes because of using CocosStudio. And CocosStudio doesn't have mechanism of custom widgets usage now.

**Comment by neokim** [comment]
Sorry for late response.

First, I was under the impression that your dragging means just user's touch movement, but it seems that you mean dragging a widget placed in a scroll panel. In the previous comment, I was talking about just touch movement as drag.
Now I got the reason why you need it. I will add a setter for `totalTime` threshold.

So, you are adding a functionality for dragging items in scroll view? I really look forward it! :smiley:

**Comment by sbrednikhin** [comment]
Yes. In our project we need dragging (and from scrolls too). This feature must be useful in mobile applications. There are samples of user interfaces that uses dragging widget from scrolling panels (first in mind is main screen in android). As I said before, they use long tap as indicator of dragging start.

Thanks for adding functionality. It will make life easier.
