### ISSUE TITLE
cc.ActionInterval.extend is not a Function

### ISSUE THREAD

**Issue by sianzain** [cocos2d/cocos2d-x#14464]
How can one extends the action interval class for Cocos2d-x Android/JS project?
Because in android Debug error gives:

DEBUG/cocos2d-x debug info(24129): JS: assets/progressBar.js:127:TypeError: cc.ActionInterval.extend is not a function

**Comment by gaoshaoliang** [comment]
I also get this issue; I added this code "cc.ActionInterval.extend = cc.Class.extend;" before extending the action interval class,but I got an error "cc.ActionInterval.prototype.ctor is undefined".And how did you solve this issue?

error:
JS: F:/workspaces/cocos2d-js/GameDemo/GenZhePao/Demo_4_2_IDEA/runtime/win32/../../src/Utils/ShapeCollision.js:440:TypeError: cc.ActionInterval.prototype.ctor is undefined

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree. @sianzain @gaoshaoliang

**Comment by NanZii** [comment]
I also get this issue, i wanna custom action interval but when i run my project on Android devices i catch a error: cc.ActionInterval.extend is not a function
