### ISSUE TITLE
Can't import custom class/widget ctype into cocos2d-x reader.

### ISSUE THREAD

**Issue by Cybertwip** [cocos2d/cocos2d-x#14462]
See https://github.com/darkdukey/Cocos-Studio/issues/75

This is about the node parsing segment that loads flat buffers. As it seems, when loading custom widgets this is always equal to NULL: 

![nulled](https://cloud.githubusercontent.com/assets/8097385/11354597/e94752ea-9209-11e5-9edf-6c5c658fe5b0.PNG)

It doesn't happen with Custom Class nodes, only with custom widgets loaded via the C#/lua method.

**Comment by minggo** [comment]
close it since cocos studio is canceled
