### ISSUE TITLE
Radial progress widget in UI and CocosStudio editor is needed.

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#14473]
Actually, i'ts no a big deal to implement it by myself, using cocos2d::ProgressTimer and make a pull request, but cocos2d::ui::LoadingBar doesn't uses cocos2d::ProgressTimer as renderer, and I think there is a reason - why, although I don't understand it.

Besides that, I need to use this widget in CocosStudio editor, but I don't see a way of doing it. There was some mechanism of making plugins for editor in old versions of CocosStudio, but it seems to be unsupported or removed now. Even if it works, I can't find valid documentation about i'ts usage.

**Comment by AIGRIND-LLC** [comment]
Agree. It's pretty common case when we need to create some widgets like this:
![01](https://cloud.githubusercontent.com/assets/6168693/11496725/ad8e3962-981c-11e5-8c79-241f842b6b67.png) ![02](https://cloud.githubusercontent.com/assets/6168693/11496724/ad8c8fd6-981c-11e5-8dff-64493224d2b6.gif)
Every time we need the widget of such type we have to manually combine ProgressTimer and ClippingNode to achieve the result.
The dedicated widget in CocosStudio is really necessary.

**Comment by AIGRIND-LLC** [comment]
@zilongshanren, @pandamicro, Is CocosStudio development closed?
Actually at this moment CocosStudio is the only UI editor for cocos2d-x and it supports only 50% of UI API from the engine itself. Moreover there are a lot of opened issues related to CocosStudio which were opened long time ago and had no any result.
It would be more effective if it was opensource so we could make a lot of improvements much faster.

**Comment by zilongshanren** [comment]
@AIGRIND-LLC  No, CocoStudio is still under development.
I will forward your request to the CocoStudio team.
Thanks.

**Comment by minggo** [comment]
close it since cocos studio is canceled
