### ISSUE TITLE
Download load zip file from url and save it on writable directory. and unzip file which is folder.

### ISSUE THREAD

**Issue by afrazizid** [cocos2d/cocos2d-x#1448]
Hello, I am working on android game using cocos2dx. I want to download a zip file from server and store it on writeable directory in may case it is data/data/com.fun.game/ . Here is what if want
1. download zip file from server and store it locally at data/data/com.fun.game/20068.zip
2. unzip the zip file content (zip file contains folder that contains images .png files) to directory data/data/com.fun.game/20068/

Problem I am facing is as following:
1. I am using CCHttpRequest to get file data from server. I have have tested the zip file url it works fine in terminal using CURL call, it returns raw file data string having starting 2 charactors  "PK" . I sucessfully get response of my CCHttpRequest in CCHttpResponse. I extract raw file data in response by the following code:

std::vector<char> _buffer = response->getResponseData();
std::string responseText = std::string((_buffer).begin(),(*buffer).end());

when i CCLog in responseText.c_str() the log say its value is "PK"
1. I write const char\* data into a file using the following code:
   asume that "data" is  const char\* containing 

std::string filePath = CCFileUtils::sharedFileUtils()->getWriteablePath()+"20068..zip";
FILE *fp = fopen(filePath.c_str(), "w");
fwrite(data,1,sizeof(data),fp);
fclose(fp);

the above code generates zip file at privded path sucessfully. When i copy that zip file form android device to my computer it does not extracts the data and when i open the file in TextEdit.app. it contians the text "PK".

I am struggling from very long time and can't acheive my target. Please help me how should i download zip file and extract its content in my writabel directory of andorid. Please help. Thanks in advance.

**Comment by sburavtsov** [comment]
Hi,

sizeof(data) returns just size of pointer, not actual block length.

You can do something like that:

``` C++
vector<char> *responseData = response->getResponseData();

FILE *fp = fopen(fullFilename.c_str(), "w");

if (! fp) {
    CCLOG("can not create file %s", fullFilename.c_str());
    return;
}

fwrite(responseData->data(), 1, responseData->size(), fp);

fclose(fp);
```

Also it can be good to use "wb" mode to specify binary write mode.

**Comment by afrazizid** [comment]
Thanks for the quick response. Opening file in binary write mode by "w" with "wb" did'nt work either. Please sugguest me any help i can get form cocos2dx librariies of some other. to complete the functionality. Download and save zip file and how to extract it in directory.

**Comment by sburavtsov** [comment]
did you try piece of code from comment above?

**Comment by sburavtsov** [comment]
Also do you have HttpClient with fixed write data callback?

**Comment by afrazizid** [comment]
No it did'nt work for me. i have updated to above mentioned version. and using "wb" mode of writing file. please help find me the appropriate way or library to achieve the functionality.

**Comment by afrazizid** [comment]
ops it was my bad Thanks sburavtsov for your help. Its worked. I appreciate!
