### ISSUE TITLE
Js ccs.load low efficiency.

### ISSUE THREAD

**Issue by yue19870813** [cocos2d/cocos2d-x#14492]
ccs.load = function(file, path){
    var object = {
        node: null,
        action: null
    };
    object.node = ccs._load(file, null, path);    //load and prase once.
    object.action = ccs._load(file, "action", path);    //load and prase twice.
    if(object.action && object.action.tag === -1 && object.node)
        object.action.tag = object.node.tag;
    return object;
};

**Comment by yue19870813** [comment]
var json = ccs.load("res/Jason/jiecendonghua.json");
var node = json.node;

And the above method is not able to do caching. I must to load many times when I want to create many nodes. It's a problem or how can I do?

**Comment by weibobo** [comment]
you can try to use the new nodes, like uiimageview, uilayout, and cache the node, next time you can use node.clone

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
