### ISSUE TITLE
如何将库文件编译为arm64-x86

### ISSUE THREAD

**Issue by fangshuai0119** [cocos2d/cocos2d-x#14501]
如题，开发平台：android，CPU_ABI=arm64-x86
我应该如何将库文件编译为arm64-x86，
出错详细信息：
Android NDK: ERROR:C:\Cocos\frameworks/cocos2d-x-3.7.1/external/freetype2/prebuilt/android/Android.mk:cocos_freetype2_static: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that C:/Cocos/frameworks/cocos2d-x-3.7.1/external/freetype2/prebuilt/android/arm64-v8a/libfreetype.a exists  or that its path is correct

**Comment by zilongshanren** [comment]
@fangshuai0119 
You should first compile all the 3rd party libs to arm64 or x86-64 with https://github.com/zilongshanren/cocos2d-x-3rd-party-libs-src/tree/add-android-x86-64-support

Then you could change the APP_ABI to arm64-x86 and compile the engine to arm64 or x86-64.

**Comment by zilongshanren** [comment]
@fangshuai0119  
It's not a easy job, good luck.

**Comment by fangshuai0119** [comment]
Thank you for your answer.

**Comment by EXKulo** [comment]
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin
