### ISSUE TITLE
3d model,fbx convert to c3b

### ISSUE THREAD

**Issue by DustYang** [cocos2d/cocos2d-x#14500]
i have two problems
first: fbx convert to c3b,in 3dmax,the z axis is up, in cocos2dx, the y axis is up,but,it is cocos2dx 3.5 before, convert to c3b is normal, it is cocos2dx 3.5 after, i have to rotate 90 around the x axis. cocos2dx 3.5 after,3dmax convert to fbx, We should pay attention to what?
second: If I use skin skeleton, the model I had to scale, it is appropriate

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@DustYang
