### ISSUE TITLE
Nothing is calling CCNode::onExitTransitionDidStart

### ISSUE THREAD

**Issue by darbotron** [cocos2d/cocos2d-x#1450]
Hi,

I discovered that nothing was calling the virtual function CCNode::onExitTransitionDidStart().

By my reckoning it should be getting called in CCTransitionScene::onEnter(), I've made the change locally, I've done some relatively thorough testing, and it works as anticipated.

This is the fix, the function starts on line 168 of CCTransition.cpp:

```
// custom onEnter
void CCTransitionScene::onEnter()
{
    CCScene::onEnter();
    m_pInScene->onEnter();
    // call onExitTransitionDidStart on m_pOutScene
    // to inform it that the transition has started
    m_pOutScene->onExitTransitionDidStart();
}
```

To be honest I can't believe that no-one has noticed this before!

Hope this helps,

Alex

**Comment by vedi** [comment]
Hi,

Related forum topic is http://www.cocos2d-x.org/boards/6/topics/12822?r=24686 .
It's a really high-priority bug. Please, have a look.

Thanks.

Best regards,
Fedor

**Comment by minggo** [comment]
It is fixed in the latest code in github.
Thank you.
