### ISSUE TITLE
[3.9] Wrong assert in ComponentContainer

### ISSUE THREAD

**Issue by pmaloman** [cocos2d/cocos2d-x#14506]
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCComponentContainer.cpp#L65

**Comment by xiaofeng11** [comment]
@pmaloman Yes, this is a bug, Could you submit a PR to fix it? Thanks a lot.

**Comment by xiaofeng11** [comment]
@pmaloman Thanks for help us improve cocos2dx.
