### ISSUE TITLE
ClippingNode inside a ScrollView does not work properly...

### ISSUE THREAD

**Issue by willmoon** [cocos2d/cocos2d-x#14522]
I have some ClippingNodes in TableView which inherit from Scrollview...But the ClippingNode does not work properly...When first created,it show the ClippingNode,after that it is at a random state

**Comment by liamcindy** [comment]
@willmoon Could you show us some code with that problem?

**Comment by willmoon** [comment]
Ok,I have an ImageView which will be clipped,and the ImageView is in a json file made by the CocoStutio.I put the ImageView into a tableviewcell  and get it cliiped.Here is some code: 

if ( !pImageView )
	{
		return;
	}
	m_StencilPosition = stencilPosition;
	if ( !_imageRenderer )
	{
		ClippingNode* clipNode = ClippingNode::create();
		m_pStencil = Sprite::create(path);
		m_pStencil->setPosition(stencilPosition);
		if (newSize > 0)
		{
			float fStencilScale = newSize / m_pStencil->getContentSize().width;
			m_pStencil->setScale(fStencilScale);
		}
		clipNode->setStencil(m_pStencil);
		//设置要计算裁减alpha值
		clipNode->setAlphaThreshold(0.05f);
		clipNode->setAnchorPoint(Point(0.5,0.5));

		m_pClipNode = clipNode;
		
		this->copyProperties(pImageView);
		m_pContent = pImageView->getVirtualRenderer();
		if ( m_pContent == nullptr )
		{
			m_pContent = Scale9Sprite::create();
		}
		if ( m_pContent )
		{
		if ( m_pContent->getParent() != nullptr )
				{
					pImageView->removeProtectedChild(m_pContent);
				}
				m_pClipNode->addChild(m_pContent);
				addProtectedChild(m_pClipNode, IMAGE_RENDERER_Z, -1);
				m_pClipNode->setPosition( pImageView->getPosition().x,pImageView->getPosition().y );

				Node* pParent = pImageView->getParent();
				pParent->addChild(this);
				pImageView->removeFromParent();
			}
		
	}

**Comment by willmoon** [comment]
ok,if it is reused ,just not clip it again
