### ISSUE TITLE
arm64-v8a还是不能进行编译成功

### ISSUE THREAD

**Issue by fangshuai0119** [cocos2d/cocos2d-x#14531]
我按https://github.com/zilongshanren/cocos2d-x-3rd-party-libs-src/tree/add-android-x86-64-support这个上边说的，将除了rapidjson的第三方库全部进行了编译，之后分别将lib*.a加入到对应包下的prebuild/arm64-v8a下，初步怀疑libwebp.a编译有问题，编译过程中出现的错误如下：
./obj/local/arm64-v8a/libcocos2dandroid.a(CCEnhanceAPI-android.o): In function `__ctype_get_mb_cur_max':
C:/Cocos/frameworks/cocos2d-x-3.9/cocos/platform/android/CCEnhanceAPI-android.cpp:34: multiple definition of`__ctype_get_mb_cur_max'
./obj/local/arm64-v8a/libcocos2dandroid.a(CCApplication-android.o):C:/Cocos/frameworks/cocos2d-x-3.9/cocos/platform/android/CCApplication-android.cpp:44: first defined here
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPInitDecBuffer':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:193: undefined reference to`WebPInitDecBufferInternal'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPIDecGetYUV':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:322: undefined reference to`WebPIDecGetYUVA'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPGetFeatures':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:394: undefined reference to`WebPGetFeaturesInternal'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPInitDecoderConfig':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:429: undefined reference to`WebPInitDecoderConfigInternal'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `cocos2d::Image::initWithWebpData(unsigned char const*, long)':
C:/Cocos/frameworks/cocos2d-x-3.9/cocos/./platform/CCImage.cpp:2140: undefined reference to`WebPDecode'
./obj/local/arm64-v8a/libcocos2dandroid.a(CCEnhanceAPI-android.o): In function `__ctype_get_mb_cur_max':
C:/Cocos/frameworks/cocos2d-x-3.9/cocos/platform/android/CCEnhanceAPI-android.cpp:34: multiple definition of`__ctype_get_mb_cur_max'
./obj/local/arm64-v8a/libcocos2dandroid.a(CCApplication-android.o):C:/Cocos/frameworks/cocos2d-x-3.9/cocos/platform/android/CCApplication-android.cpp:44: first defined here
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPInitDecBuffer':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:193: undefined reference to`WebPInitDecBufferInternal'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPIDecGetYUV':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:322: undefined reference to`WebPIDecGetYUVA'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPGetFeatures':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:394: undefined reference to`WebPGetFeaturesInternal'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `WebPInitDecoderConfig':
C:/Cocos/frameworks/cocos2d-x-3.9/external/webp/prebuilt/android/../../include/android/decode.h:429: undefined reference to`WebPInitDecoderConfigInternal'
./obj/local/arm64-v8a/libcocos2dxinternal.a(CCImage.o): In function `cocos2d::Image::initWithWebpData(unsigned char const*, long)':
C:/Cocos/frameworks/cocos2d-x-3.9/cocos/./platform/CCImage.cpp:2140: undefined reference to`WebPDecode'
collect2.exe: error: ld returned 1 exit status
make.exe: **\* [obj/local/arm64-v8a/libcocos2dcpp.so] Error 1
make.exe: Leaving directory `D:/tmp/chat/easyndk/proj.android'
执行命令出错，返回值：2。
Traceback (most recent call last):
  File "build_native.py", line 43, in <module>
    build(opts.build_mode)
  File "build_native.py", line 28, in build
    raise Exception("Build dynamic library for project [ " + app_android_root + " ] fails!")
Exception: Build dynamic library for project [ D:\tmp\chat\easyndk\proj.android../ ] fails!

**Comment by littleboss** [comment]
我项目中没有用到webp，吧这个webp的第三方没有编译进去就ok

**Comment by zilongshanren** [comment]
please move to the forum or stackoverflow, thanks.
