### ISSUE TITLE
CCDownloader on iOS is broken in v3.9

### ISSUE THREAD

**Issue by pandemosth** [cocos2d/cocos2d-x#14539]
The `onDataTaskSuccess` callback is never called for a data download task. You can reproduce this in the Downloader Test, Top Left test in cocos2d-x v3.9 cpp-tests project.

Inside CCDownloader-apple.mm it just looks like `onTaskFinish` callback is never called for a data task.

Related issue #14533

**Comment by cezheng** [comment]
DataTask is only used when no storage path is specified, but why use it? If you do want to get the callback, try doing it in this delegate method: https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/CCDownloader-apple.mm#L388

**Comment by pandemosth** [comment]
I'm not using it directly, its being called here - https://github.com/cocos2d/cocos2d-x/blob/V3.9/cocos/scripting/js-bindings/manual/extension/jsb_cocos2dx_extension_manual.cpp#L933

I assume the intention is to avoid the overhead of writing an image to file and then reading from that file to add to the texture cache.

**Comment by pandemosth** [comment]
Also, its being used this way in the Downloader Test as stated in the issue description above, so clearly its an intended use case.

**Comment by pandamicro** [comment]
I see the problem here, sorry for the bug, we will investigate into it in this version

**Comment by cezheng** [comment]
@pandamicro I have fixed another bug related to the new Downloader implementations in 3.9. https://github.com/cocos2d/cocos2d-x/pull/14530

**Comment by cezheng** [comment]
@pandemosth  from the source code of CCDownloader-apple.mm it is definitely not called, so I guess that NSURLDataDelegate method should be implemented for your case

**Comment by pandamicro** [comment]
@cezheng Thanks !

**Comment by pandemosth** [comment]
@cezheng Thanks but fyi that delegate method is not called when the request completes.
From the Apple docs: "Tells the delegate that the data task received the initial reply (headers) from the server."

**Comment by pandamicro** [comment]
@pandemosth  Thanks for solving this problem !

**Comment by pandemosth** [comment]
@pandamicro No problem!

Can I get your opinion on this related bit of code though:

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/manual/extension/jsb_cocos2dx_extension_manual.cpp#L875

Shouldn't this Image object be allocated on heap with 'new'..?
