### ISSUE TITLE
Scale9Sprite does not work correct with cropped sprite frames

### ISSUE THREAD

**Issue by newnon** [cocos2d/cocos2d-x#14549]
after last changes cocos 3.10 Scale9Sprite draws cropped sprite not correct you can see it in tests images must be cropped but not scaled

**Comment by zilongshanren** [comment]
@newnon  
Do you have any ideas to resolve this issue? The new Scale9Sprite in 3.10 is made by me.
Currently I can't fully understand how to draw cropped images with scale9 feature.
I hope you could explain it to me.
thanks.

**Comment by newnon** [comment]
I will look into code in next few days and try to send pool request

**Comment by zilongshanren** [comment]
@newnon 
Thanks.

**Comment by newnon** [comment]
done in https://github.com/cocos2d/cocos2d-x/pull/14729
