### ISSUE TITLE
TMXTiledMap's bug

### ISSUE THREAD

**Issue by feijing566** [cocos2d/cocos2d-x#14577]
TMXTiledMap unable to correct display when the tile setFlippedX and setFlippedY both true

The first one is correct but the others is wrong

Verstion : 3.9

By the way it's Ok in v3.6
# In Editer:

![In Editer](https://cloud.githubusercontent.com/assets/7393582/11583170/e302e454-9a91-11e5-9312-bbfc1489b5ee.png)
# In Project:

![In Project](https://cloud.githubusercontent.com/assets/7393582/11583169/e3022dc0-9a91-11e5-95f4-cfb7fcb9cac1.png)
# The tile png

![3](https://cloud.githubusercontent.com/assets/7393582/11583294/0c7e6956-9a93-11e5-9f8e-83c076d2f062.png)

@zilongshanren

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree. @feijing566
