### ISSUE TITLE
Button widget with 9-slice enabled cloning problem

### ISSUE THREAD

**Issue by vasyaPP** [cocos2d/cocos2d-x#14596]
I have just upgraded my project from cocos2d-x v3.7 up to v3.9 release and discovered problem with Button widget. I have button with 9-slice enabled created with cocostudio. And after cloning button it displayed with wrong size - width and height of button are equal to texture size, not the original button size.

Without these lines of code everything working perfect:

```
UIButton.cpp
void Button::setupNormalTexture() {
    ...
    // force update _customSize, fixed issue:
    // https://github.com/cocos2d/cocos2d-x/issues/12249
    _customSize = _normalTextureSize;
    ... 
}
```

It can be reproduced with cocos2d-x v3.9, cocostudio 2.3.3 (mac os). If it's important texture was packed in atlas with TexturePacker.

```
auto rootNode = cocos2d::CSLoader::createNode("Layers/UILayer.csb");
addChild(rootNode);

auto btn = rootNode->getChildByName<cocos2d::ui::Button*>("btn");
auto btn2 = btn->clone();
addChild(btn2);
btn2->setPositionY(btn->getPositionY() + 100);
```

<img width="228" alt="screen shot 2015-12-05 at 16 17 26" src="https://cloud.githubusercontent.com/assets/2494560/11607986/e71566d4-9b6d-11e5-90c3-20899730da07.png">

**Comment by zilongshanren** [comment]
@yangws  please take a look at this issue.

**Comment by zilongshanren** [comment]
@vasyaPP 
please check the latest v3 branch.

**Comment by zilongshanren** [comment]
@vasyaPP 
It is already fixed in upstream v3.

**Comment by vasyaPP** [comment]
@zilongshanren yes, I checked latest v3 branch (2251b529290be72c05938c25b363cb0986ed2257). I can confirm that there are no problems with cloning Button widget with 9-scale enabled option on current development branch.
