### ISSUE TITLE
Build failed on OS X using GCC 4.9.3

### ISSUE THREAD

**Issue by apocarteres** [cocos2d/cocos2d-x#14606]
I'm trying to build v3.9 in OS X using <code>cmake</code> and GCC 4.9.3 (installed using <code>brew</code> with <code>--with-all-languages</code> flag) but seems that there are some problems with Cocos code here.

At first attemtion to get project built i got this:
1. cd cocos3.9
2. mkdir <code>macbuild</code> && <code>cd macbuild</code>
3. Exec <code>cmake</code> like that:

<pre>
cmake -G Unix Makefiles
 -DBUILD_CPP_TESTS=OFF
 -DBUILD_LUA_LIBS=OFF 
 -DBUILD_JS_LIBS=FALSE 
 -DCMAKE_CXX_COMPILER=/usr/local/gcc-4.9.3/bin/g++ 
 -DCMAKE_C_COMPILER=/usr/local/gcc-4.9.3/bin/gcc 
 -DCMAKE_CXX_FLAGS=-w -std=c++11 
 -DCMAKE_C_FLAGS=-std=gnu99 ..
</pre>
1. <code>make</code>
2. First compilation fail was related to issue that children classes of <code>cocos/2d/CCNode.h</code> were not able to resolve <code>isnan</code> function, so i hacked it like this:
   file: <code>cocos/2d/CCNode.h</code>
   <pre>
   using std::isnan;
   </pre>
3. Next problem which i _currently stuck on_:

<pre>
[ 23%] Built target bullet
[ 26%] Built target recast
[ 27%] Built target tinyxml2
[ 27%] Built target unzip
[ 28%] Built target flatbuffers
[ 29%] Built target xxhash
[ 29%] Building CXX object cocos/CMakeFiles/cocos2d.dir/platform/mac/CCApplication-mac.mm.o
In file included from /usr/include/os/object.h:75:0,
                 from /usr/include/dispatch/dispatch.h:48,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                 from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12,
                 from /Users/sandro/cocos2d-x/cocos/platform/mac/CCApplication-mac.mm:29:
/usr/include/objc/NSObject.h:22:4: error: 'instancetype' does not name a type
 - (instancetype)self;
    ^
/usr/include/objc/NSObject.h:36:4: error: 'instancetype' does not name a type
 - (instancetype)retain OBJC_ARC_UNAVAILABLE;
    ^
/usr/include/objc/NSObject.h:38:4: error: 'instancetype' does not name a type
 - (instancetype)autorelease OBJC_ARC_UNAVAILABLE;
    ^
/usr/include/objc/NSObject.h:60:4: error: 'instancetype' does not name a type
 - (instancetype)init
    ^
/usr/include/objc/NSObject.h:66:4: error: 'instancetype' does not name a type
 + (instancetype)new OBJC_SWIFT_UNAVAILABLE("use object initializers instead");
    ^
/usr/include/objc/NSObject.h:67:4: error: 'instancetype' does not name a type
 + (instancetype)allocWithZone:(struct _NSZone *)zone OBJC_SWIFT_UNAVAILABLE("use object initializers instead");
    ^
/usr/include/objc/NSObject.h:68:4: error: 'instancetype' does not name a type
 + (instancetype)alloc OBJC_SWIFT_UNAVAILABLE("use object initializers instead");
    ^
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:0,
                 from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12,
                 from /Users/sandro/cocos2d-x/cocos/platform/mac/CCApplication-mac.mm:29:
/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: error: 'nullable' does not name a type
 - (id)copyWithZone:(nullable NSZone *)zone;
                     ^
/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:25:28: error: 'nullable' does not name a type
 - (id)mutableCopyWithZone:(nullable NSZone *)zone;
                            ^
/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:32:4: error: 'nullable' does not name a type
 - (nullable instancetype)initWithCoder:(NSCoder *)aDecoder; // NS_DESIGNATED_INITIALIZER
    ^
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:0,
                 from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12,
                 from /Users/sandro/cocos2d-x/cocos/platform/mac/CCApplication-mac.mm:29:
</pre>

Having investigated it already two days i haven't came to any useful conclusion yet. 

Guys, could you please suggest where i can go next at this point?

P.S I really need to build project with <code>GCC 4.9+</code> since my team uses <code>GCC 4.9+</code>. When i try to you use <code>clang</code> project is built successful, however rest of the team facing a lot of issues when they try to compile my code with <code>GCC</code>

P.S.S I'm _not_ going to use XCode, since it worst IDE in the world it's completely not possible to use it. I prefer vim.

**Comment by PeqNP** [comment]
I'm not sure `nullable` and `instancetype` are supported `GCC` attributes. I can't seem to find any indication that they are. This is the list of common function attributes for `GCC` https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes. I hope this helps in your search.

**Comment by apocarteres** [comment]
Unfortunately, you are right. I already noticed that there are complains on that https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63651
And i assume it's connected to that issue that gcc doesn't support "blocks extension" (http://opensource.apple.com/source/libclosure/libclosure-65/BlockImplementation.txt)

**Comment by apocarteres** [comment]
but i'm still wondering is there any chance to use gcc with osx to get Cocos built well...

**Comment by PeqNP** [comment]
I am very sorry. I don't know enough about Mac OS X to say one way or the other. I also don't know anyone in Mac OS X land who may be able to help.

FYI: I'm not part of the Cocos team. Hopefully someone who has more experience in this area can help answer your question.

**Comment by ricardoquesada** [comment]
thanks for the bug report.
unfortunately we don't have the bandwidth to take a look a this bug. we are only going to support clang/llvm for Mac OS X.

but we do support gcc in Linux... and we compile Linux using cmake, so should work ok.

closing this bug as "won't fix", but thanks again for reporting it.

**Comment by apocarteres** [comment]
/(º_º)\
