### ISSUE TITLE
SocketIO: Automatically reconnect

### ISSUE THREAD

**Issue by michaelcontento** [cocos2d/cocos2d-x#14618]
As [described here](http://socket.io/docs/client-api/#manager%28url:string,-opts:object%29), the official JS client of SocketIO comes with a quite simple solution to reconnect on connection lost. 

It would be awesome if the cocos2dx native implementation of SocketIO would do the same and we could get a comparable behaviour between native and JS.

**Comment by minggo** [comment]
@michaelcontento did you mean current Socket.IO doesn't do auto reconnection?

**Comment by michaelcontento** [comment]
Yes, at least was that the case a few months ago.

**Comment by michaelcontento** [comment]
Closed as outdated and change no longer required
