### ISSUE TITLE
Cannot find file path with capitalize letters in file name and folders

### ISSUE THREAD

**Issue by thuydx55** [cocos2d/cocos2d-x#14627]
## Android

Uncomment this line and found some logs but file is existed
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/CCFileUtils-android.cpp#L175

> 12-09 23:19:40.038 28636-28737/com.hub102.tsog D/cocos2d-x debug info: [AssetManager] ... in APK assets/res/SD/Adidog/ConCho.json, found = false!
> 12-09 23:19:40.038 28636-28737/com.hub102.tsog D/cocos2d-x debug info: [AssetManager] ... in APK assets/Adidog/ConCho.json, found = false!
> 12-09 23:19:40.038 28636-28737/com.hub102.tsog D/cocos2d-x debug info: [AssetManager] ... in APK assets/Adidog/ConCho.json, found = false!
> 12-09 23:19:40.038 28636-28737/com.hub102.tsog D/cocos2d-x debug info: [AssetManager] ... in APK assets/res/SD/Adidog/ConCho.json, found = false!
> 12-09 23:19:40.038 28636-28737/com.hub102.tsog D/cocos2d-x debug info: [AssetManager] ... in APK assets/res/Adidog/ConCho.json, found = false!

**Comment by minggo** [comment]
`cpp-tests` uses many resources that contain capital characters and haven't met issue. So close it. Feel free to reopen it if you find it is still has problem.
