### ISSUE TITLE
Is there any way that Box2d will bind to Lua?

### ISSUE THREAD

**Issue by iWoz** [cocos2d/cocos2d-x#14646]
Currently, I used LiquidFun which based on Box2d to simulate liquid effect in my game. 

It seems Box2d isn't bind to Lua yet.

And I tried to make a new gen binding ini configure file for LiquidFun, which gives me an error: `The namespace (b2Shape::Type) conversion wasn't set in 'ns_map' section of the conversions.yaml`

How do I solve this error? And is there any quick and easy way that could I bind LiquidFun to Lua?

Thanks in advance!

**Comment by minggo** [comment]
You can try tolua++ to bind it or use [binding-generator](https://github.com/cocos2d/bindings-generator) that is used by cocos2d-x.

**Comment by iWoz** [comment]
For the sake of successors, I made a tolua binding [repository](https://github.com/iWoz/LiquidFun_toLua) for LiquidFun, and successfully used in [my game](http://wuzhiwei.net/liquidfun_in_soda_world/).
