### ISSUE TITLE
NewAudioEngine bug after incoming call still exist (ios)

### ISSUE THREAD

**Issue by fuyifan** [cocos2d/cocos2d-x#14664]
After the incoming call, if you refuse the call, the audio can resume normally. However, if you ANSWER the call and after several seconds finish the call, the audio will not resume any longer.

**Comment by fuyifan** [comment]
@pandamicro @WenhaiLin Please make your test.

**Comment by fuyifan** [comment]
I am sorry for this bug. Actually, the audio will not resume any longer no matter you answer or not answer the call. The problem with my issue is caused by some code that invokes the SimpleAudioEngine and this makes the system notifcation to NewAudioEngine stop working. So I recommand cocos should use some mechanism to prevent programmer use both two AudioEngine at the same time. @pandamicro

**Comment by dumganhar** [comment]
Yes, basically, we need to deprecate `SimpleAudioEngine`, and implement `SimpleAudioEngine` with `AudioEngine`.
