### ISSUE TITLE
What is the difference between ProgressTimer::setReverseProgress and ProgressTimer::setReverseDirection

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#14678]
Methods looks to do same thing by bit little different ways. Shouldn't one of than be deprecated or something?

**Comment by minggo** [comment]
Yep, it seems similar and the implementation is a little different. I don't know it too. @ricardoquesada have idea?

**Comment by ricardoquesada** [comment]
it seems that they are doing exactly the same thing.
yes, one should be deprecated... I can fix it. Which one should I deprecate?
I'll take a look at the history of the file a deprecate the oldest one.

**Comment by ricardoquesada** [comment]
I found this:
the code was copied from cocos2d-iphone v2. or v1.
but cocos2d-iphone doesn't have the `reverseProgress` function... it only has the `reverseDirection`. So I'll deprecate the `reverseProgress` one.
