### ISSUE TITLE
[Question] Totally confused with GlobalZOrder

### ISSUE THREAD

**Issue by vladpazych** [cocos2d/cocos2d-x#14675]
Hello.

I have nested tree:

``` javascript
self.addChild(red);
self.addChild(green);
green.addChild(blue);
```

I get this: 
![Screenshot](http://s7.postimg.org/75r1xmb3r/Screenshot_2015_12_14_14_21_19.png)

How can I put blue square behind others, without changing my tree to make it look like this:
![Screenshot](http://s12.postimg.org/6kz2bqnjt/Screenshot_2015_12_14_14_25_06.png)

I can't understand how to use `setGlobalZOrder()`, because this does nothing:

``` javascript
red.setGlobalZOrder(2);
green.setGlobalZOrder(3);
blue.setGlobalZOrder(1);
```

**Comment by zilongshanren** [comment]
@vladpazych  image broken?

**Comment by vladpazych** [comment]
@zilongshanren weird, I saw it. Anyway - image is updated.

**Comment by madlexus** [comment]
The global z order is affecting only for Sprite objects.

**Comment by vladpazych** [comment]
Ok, thank's. Make sense.
