### ISSUE TITLE
Issues with new Label on Nexus 6P - Huge FPS drop & Lag

### ISSUE THREAD

**Issue by kiranb47** [cocos2d/cocos2d-x#14685]
The problem is with new label system. No issue with old LabelTTF. Getting 60fps

We tested new Label with TTF & BMFont. Both have FPS issue.

ui::TextBMFont, ui::Text & LabelBMFont also have the same fps issue.

http://discuss.cocos2d-x.org/t/serious-lag-fps-issue-on-nexus-6p-marshmallow/25622

**Comment by zilongshanren** [comment]
@WenhaiLin please take a look at this issue.

**Comment by kiranb47** [comment]
Just tested on Motorolla Nexus 6 & Samsung S6 edge.

Motorolla Nexus 6 has same issue exist.

No issue on S6 edge.

**Comment by WenhaiLin** [comment]
I can't recreate the problem on Nexus 6 with Android 5.1. @kiranb47  Which os version you meet this bug?

**Comment by kiranb47** [comment]
Android 6.0.1 Marshmallow

**Comment by kiranb47** [comment]
@WenhaiLin Any update on this?

**Comment by piotrros** [comment]
This is a serious bug! I know 6.0 is still on < 0.5% devices, but some day it will be on most of devices.
