### ISSUE TITLE
AutoPolygen should support reading sprites from spriteFrameCache

### ISSUE THREAD

**Issue by TheSachin** [cocos2d/cocos2d-x#14705]
So far `AutoPolygon` supports creating from sprites,but since in most production games sprites are loaded from plist,It is only logical that we also have option of creating Polygon Sprites using `SpriteFrameCache`

**Comment by ghost** [comment]
Maybe https://github.com/cocos2d/cocos2d-x/pull/14049

**Comment by stevetranby** [comment]
That PR is a different workflow from the OP I think. However, does calling setSpriteFrame on a sprite  allow the AutoPolygon to run after it has been updated? If so then that would solve it albeit with a slightly less easy API.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree. @TheSachin @yinjimmy @stevetranby
