### ISSUE TITLE
ios上3d模型加光照与listview冲突，死机

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14711]
场景包含3d模型和一个pannel，pannel里面有两个listview，listview都有clip属性，有studio生成。还有光照和相机，应用一打开没有3d模型，这时应用正常。当添加一个3d模型时，系统死机。出错位置在：UIlayout.cpp

原因：在ios上对opengl检查比较严，其他平台没有这么严格的，glBindbuffer必须配对。

CCVertexAttribBinding.cpp里面

``` c++
bool VertexAttribBinding::init(MeshIndexData* meshIndexData, GLProgramState* glProgramState)
{

    // VAO hardware
    if (Configuration::getInstance()->supportsShareableVAO())
    {
        glBindBuffer(GL_ARRAY_BUFFER, 0);
        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);

        glGenVertexArrays(1, &_handle);
        GL::bindVAO(_handle);
        glBindBuffer(GL_ARRAY_BUFFER, meshVertexData->getVertexBuffer()->getVBO());

        auto flags = _vertexAttribsFlags;
        for (int i = 0; flags > 0; i++) {
            int flag = 1 << i;
            if (flag & flags)
                glEnableVertexAttribArray(i);
            flags &= ~flag;
        }

        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, meshIndexData->getIndexBuffer()->getVBO());

        for(auto &attribute : _attributes)
        {
            attribute.second.apply();
        }

        GL::bindVAO(0);
         //增加下面两行
     glBindBuffer(GL_ARRAY_BUFFER, 0);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
    }
```

**Comment by 1078559858** [comment]
@xiaofeng11

**Comment by xiaofeng11** [comment]
@liamcindy @super626 Please take a look on this issue

**Comment by fatfatson** [comment]
看标题好搞笑。。。

**Comment by minggo** [comment]
@1078559858 i think you are right. 
@ricardoquesada i think  [these two lines](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/renderer/CCVertexAttribBinding.cpp#L147) should be moved to the end of `if` block:

``` c++
 // VAO hardware
    if (Configuration::getInstance()->supportsShareableVAO())
    {
        // these two lines are not needed
        glBindBuffer(GL_ARRAY_BUFFER, 0);
        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);

        glGenVertexArrays(1, &_handle);
        GL::bindVAO(_handle);
        glBindBuffer(GL_ARRAY_BUFFER, meshVertexData->getVertexBuffer()->getVBO());

        auto flags = _vertexAttribsFlags;
        for (int i = 0; flags > 0; i++) {
            int flag = 1 << i;
            if (flag & flags)
                glEnableVertexAttribArray(i);
            flags &= ~flag;
        }

        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, meshIndexData->getIndexBuffer()->getVBO());

        for(auto &attribute : _attributes)
        {
            attribute.second.apply();
        }

        GL::bindVAO(0);

        // should add here
        glBindBuffer(GL_ARRAY_BUFFER, 0);
        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
    }
```

PS: please use english in future, then developers all over the world can join the discussion. Thanks.

**Comment by ricardoquesada** [comment]
@minggo you might be right... but problem are those two lines causing? What is the bug? thanks.

**Comment by minggo** [comment]
Oh, i can translate the error message:

The scene includes a 3d model and a panel. The panel is created in cocos studio, and it has two listview, every listview has a clip attribute. The app also uses camera and lights, and it works correctly if not using 3d model, but it will crash when 3d model is added. It crashed in `UILayout.cpp`.

And the developer said the reason is because `glBindBuffer` is unmatched.

**Comment by ricardoquesada** [comment]
@minggo yes, your suggestions looks good. Sent PR.

of course, a test case for this would be great.
@1078559858 could you send us the code to reproduce the crash? thanks

**Comment by ricardoquesada** [comment]
fixed. thanks.
