### ISSUE TITLE
SpriteBatchNode crash if CC_SPRITE_DEBUG_DRAW enabled

### ISSUE THREAD

**Issue by newnon** [cocos2d/cocos2d-x#14730]
enable CC_SPRITE_DEBUG_DRAW will crash test with SpriteBatchNode nodes

**Comment by ricardoquesada** [comment]
at least in v3.11 it doesn't crash anymore but it doesn't render the sprites... just the frames.

**UPDATE**: it didn't crash for me... but only by pure chance.

**Comment by ricardoquesada** [comment]
fixed.
