### ISSUE TITLE
Assert attempting to play background music for 2nd time (win8.1-universal project)

### ISSUE THREAD

**Issue by StreakyGames** [cocos2d/cocos2d-x#14737]
Using Cocos2d-x v3.9

Run my game...music plays smile
(quit game)
Run my game again...assert!!!!!!!!!!!!

The game will NOT play music until I rename the audio file or rename the folder it's in (eg. Resources/Audio/music.wav to Resources/WTF/music.wav), obviously I rename the filename/path within the code to reflect this change.

After renaming, it'll run once, then everytime after....assert!!!!

This is the assert that triggers:
long FileUtils::getFileSize(const std::string &filepath)
{
    CCASSERT(false, "getFileSize should be override by platform FileUtils");
    return 0;
}

Apparently occurs on an actual Windows Phone too, and the mp3 from cpp-tests works fine.

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/14848

**Comment by minggo** [comment]
@stammen i found you closed #14848. So what's the status of this issue?

**Comment by stammen** [comment]
@minggo It was fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/14848

**Comment by minggo** [comment]
Oh, it is fixed in #14915
