### ISSUE TITLE
When i used Scale9Sprite by spriteframe  will got a gap

### ISSUE THREAD

**Issue by semgilo** [cocos2d/cocos2d-x#14731]
cocos2dx 3.6 
when i didnt use spriteframe it was right
The gap will vary with movement
like this :
![image](https://cloud.githubusercontent.com/assets/7121873/11887339/30dc717c-a56e-11e5-9eb2-607ed46aad63.png)
![image](https://cloud.githubusercontent.com/assets/7121873/11887346/471cf722-a56e-11e5-94bf-e876ae264692.png)

And I 've seen a pixel BUG, this is not the same

**Comment by zilongshanren** [comment]
@semgilo 
you could try

```
sprite->getTexture()->setAntiAliasTexParameters()
```

**Comment by minggo** [comment]
@semgilo have you fixed your issue as @zilongshanren 's suggestion?

**Comment by semgilo** [comment]
@minggo may be spriteframe args was wrong, i had used single png, final

**Comment by minggo** [comment]
@semgilo should i close this issue or you will help us to reproduce it?

**Comment by semgilo** [comment]
@minggo close it
