### ISSUE TITLE
Migrating to chipmunk 7.x

### ISSUE THREAD

**Issue by newnon** [cocos2d/cocos2d-x#14754]
what about to migrate to chipmunk 7.x it is a bit faster & give some additional features, i have already use it with cocos in https://github.com/cocos2d/cocos2d-x/pull/10838 i can make new request to only v3 with chipmunk 7.0 support

**Comment by zilongshanren** [comment]
I'm fine with upgrading to chipmunk 7.x.
What's your opinion? @ricardoquesada

**Comment by ricardoquesada** [comment]
+1 for that. thanks.

**Comment by newnon** [comment]
first version preview quality https://github.com/cocos2d/cocos2d-x/pull/14949

**Comment by ricardoquesada** [comment]
fixed in v3.11 (or v3.10)
