### ISSUE TITLE
Update WebP to 0.5.0

### ISSUE THREAD

**Issue by newnon** [cocos2d/cocos2d-x#14756]
New versions is much faster than old ones.

**Comment by zilongshanren** [comment]
@newnon 
Thanks, We will consider to upgrade in the next release.

**Comment by minggo** [comment]
all platforms except Tizen is update to 0.5.0 in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/226

**Comment by minggo** [comment]
@zilongshanren it's your turn now

**Comment by zilongshanren** [comment]
@minggo  https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/229  PR has been created, please review, thanks.

**Comment by minggo** [comment]
I generate a new version of 3rd party libs and update to cocos2d-x in #15840
