### ISSUE TITLE
[3.9]win10 uwp x64 compile error

### ISSUE THREAD

**Issue by dannyjiajia** [cocos2d/cocos2d-x#14762]
C2664   “void cocos2d::GLView::handleTouchesBegin(int,intptr_t [],float [],float [])”
convert "int *" to “intptr_t []” in "CCGLViewImpl-winrt.cpp"

**Comment by stammen** [comment]
There currently is no support for x64 on WIndows 10 UWP builds. Only arm and win32.

**Comment by dannyjiajia** [comment]
@stammen thanks :)

**Comment by yuangu** [comment]
soga, no support for x64

**Comment by stammen** [comment]
@dannyjiajia @yuangu  x64 support for WIndows 10 UWP starts with v3.11.
