### ISSUE TITLE
Support of press action is strongly needed in cocosstudio.

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#14771]
_pressedActionEnabled field in ui::Button doesn't supported in cocosstudio editor and runtime.
This feature can be very helpful when you need to do resources as small as possible. Each button needs at least 2 images without using of press action. Using pressed action can reduce it to one.

**Comment by zilongshanren** [comment]
@xiaofeng11  
please check.

**Comment by xiaofeng11** [comment]
@chengstory @liamcindy Please take a look on this requirement.

**Comment by vitalyrovny** [comment]
+1 to press action support

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
