### ISSUE TITLE
File Dialog

### ISSUE THREAD

**Issue by hgokturk** [cocos2d/cocos2d-x#14774]
For some games, we may want to let players choose avatar from their gallery and then upload it. And as far as i know, no such functionality exists in Cocos2d-x yet. I guess it would be handy.

**Comment by 0xJimmyBeh** [comment]
@hgokturk 

Here is the Image Picker you need which working with Cocos2d-X.
I'm using it with Cocos2d-JS v3.6 and v3.8.1.

https://github.com/qiankanglai/ImagePicker

Unfortunately, Cocos team don't want to add this functionality into their engine long time ago as not much people request this function.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@hgokturk
