### ISSUE TITLE
Problem with build cocos2d on windows 10

### ISSUE THREAD

**Issue by david899** [cocos2d/cocos2d-x#14772]
I followed this tutorial:
https://blogs.windows.com/buildingapps/2015/06/15/running-cocos2d-x-on-windows-10/
but as you can expecte did not successfully ends... Here is screenshot(http://prntscr.com/9gw5c7) after about 2 - 3 minute build (I think it might download some file). And here is full report: 
http://pastebin.com/n9gdhtef
Anyone could help?

**Comment by stammen** [comment]
x64 builds are currently not supported. Please try win32 or arm.

**Comment by david899** [comment]
I cannot beleve it was so easy! Thank  you very much!
