### ISSUE TITLE
cocos studio 导出的lua文件无法使用

### ISSUE THREAD

**Issue by shinexia** [cocos2d/cocos2d-x#14812]
cocos stutio: 2.3.3
framework: 3.9

官方论坛给的方法只针对老版本，3.9无论怎么试都运行不了

Decoda 调试信息信息如下
src/main.lua
![DEBUG](http://www.technote.io/images/debug.jpg)

res/ 下有如下文件
HelloWorld.png
LuaExtend.lua
MainScene.lua

**Comment by dongtaohan** [comment]
上面的代码段是不正确的，ret['root'] 是个 cc.Node 不是 cc.Scene. 可以新建一个 Scene 去承载它。
可以试试把 display.*\* 这一行替换为：
local scene = cc.Scene:create()
scene:addChild(ret['root'])
cc.Director:getInstance():runWithScene(scene)
不推荐直接这么加载。
推荐 http://www.cocos.com/doc/article/index?type=Cocos%20Studio&url=/doc/cocos-docs-master//manual/studio/v4/chapter3/HowToCode/LoadExportData/zh.md 中的 加载lua 段 中的加载方式。

**Comment by shinexia** [comment]
原来如此，导出的代码用是用Scene命名的，就没注意，非常感谢！
