### ISSUE TITLE
rapidJson crash in iphone4s  when CCDictionary change string

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14824]
cocos2d-x v3.9 c++ 

rapidjson::StringBuffer buffer;
    rapidjson::Writerrapidjson::StringBuffer writer(buffer);
    value->Accept(writer);

when CCDictionary  change string  it will be crash in real-phone ,For example,iPhone4s，ipad min2.
it crash in "value->Accept(writer);"
but the crash don't happen in simulator.

从CCDictonary转string，在模拟器中能够正常的运行；但是在真机中会Crash在    value->Accept(writer);
@xiaofeng11

**Comment by xiaofeng11** [comment]
请提供一个测试例进行调试，谢谢。

**Comment by LongJDoing** [comment]
https://github.com/LongJDoing/Question_Demo 里面创建字典；我的数据类似它提供的；通过KSCCJsonRapid类，实现转化的过程，模拟器中可以实现；真机中不可以

**Comment by xiaofeng11** [comment]
@LongJDoing 这个是你的转换代码里面的问题，和2dx引擎无关。下面这个函数
CCString\* KSCCJsonRapid::jsonStringFromDictionary(CCDictionary *dic)
{
    rapidjson::Value *value = KSCCJsonRapid::jsonValueFromDictionary(dic);
    rapidjson::StringBuffer buffer;
    rapidjson::Writerrapidjson::StringBuffer writer(buffer);
    value->Accept(writer);
    std::string jsonString = buffer.GetString();
    delete value;
    return CCString::create(jsonString);
}
第一行获取rapidjson::Value并没有传入第二个参数document，你可以看看jsonValueFromDictionary函数里面的实现。它创建了一个document用来生成Value，然后在函数退出之前删除了这个document，在pc上内存充足，释放后并不会马上被重新分配使用，但是设备上的内存比较少，释放后马上被回收，导致返回的value已经无效，再访问的时候就会产生非法访问。只要在上面这个函数调用KSCCJsonRapid::jsonValueFromDictionary之前自己创建一个document对象，传入函数。生成字符串后再释放就可以解决崩溃问题。

**Comment by LongJDoing** [comment]
@xiaofeng11 谢谢你，是我自己大意了；经过修改OK

**Comment by xiaofeng11** [comment]
@LongJDoing 不客气，问题解决这个讨论我就先关闭了

**Comment by xiaofeng11** [comment]
Not cocos2dx issue.
