### ISSUE TITLE
[Android] It is silly when set EditBox::setVisible() will also toggles keyboard.

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#14827]
in function `public static void setVisible(final int index, final boolean visible)`

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxEditBoxHelper.java#L311-L317

``` java
                    if (visible) {
                        editBox.requestFocus();
                        Cocos2dxEditBoxHelper.openKeyboard(index);
                    }else{
                        mCocos2dxActivity.getGLSurfaceView().requestFocus();
                        Cocos2dxEditBoxHelper.closeKeyboard(index);
                    }
```

Set visibility of EditBox will also toggles keyboard. We should not do this, see the follow scenario:
- I have a EditSettingsDialog with 2 EditBox: `a` (single line edit) and `b` (multiple line edit).
- When i open EditSettingsDialog I my specify which EditBox to be visible.

``` Lua
function EditSettingsDialog:openSingleLine()
    a:setVisible(true) 
    b:setVisible(false)
end

function EditSettingsDialog:openMultipleLine()
    a:setVisible(false)
    b:setVisible(true)
end
```
- `EditSettingsDialog:openSingleLine()` will opens keyboard and then close keyboard, final status will **have no keyboard**.
- `EditSettingsDialog:openMultipleLine()` will close keyboard and then open keyboard, final status will **have keyboard**.

**Comment by zilongshanren** [comment]
@xpol 
So what's your solution here?

**Comment by xpol** [comment]
My solution would break compatibility. 

Move focus/keyboard code into 2 new method named `EditBox::setFocus()` `EditBox::resignFocus()`

**Comment by zilongshanren** [comment]
@xpol 
Thanks, I will try to fix it.

**Comment by zilongshanren** [comment]
A few issues with Editbox:

1.现在Editbox 不能支持连续输入模式，我在尝试用any多行模式通过判断换行符实现，还没开始尝试

2.Editbox现在editBoxEditingDidEnd和editBoxReturn的触发机制完全一样，根本没法判断用户到底是点击的虚拟键盘的send按钮还是因为控件失去焦点，安卓可以利用EventListenerKeyboard 来实现键盘的监听，但是iOS 貌似不行。
