### ISSUE TITLE
HelloCpp crashes in Linux

### ISSUE THREAD

**Issue by vonj** [cocos2d/cocos2d-x#1484]
When I start samples/HelloCpp/proj.linux/bin/debug/HelloCpp,
the screen flickers, then the program crashes:

cocos2d-x debug info [Not totally ready :( 
]
cocos2d-x debug info [OpenGL 2.0 not supported
]
Segmentation fault

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2671
