### ISSUE TITLE
RenderTexture newImage() is empty

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#14861]
I'm using cocos2d v3.9, Mac OS 10.10.5 Xcode 7.2

```
Sprite *someSprite = Sprite::create("1.png"); //any image with some graphics
RenderTexture *render = RenderTexture::create(someSprite->getTexture()->getPixelsWide(), someSprite->getTexture()->getPixelsHigh());
render->beginWithClear(1, 1, 1, 1);
someSprite->setAnchorPoint(Vec2(0, 0));
someSprite->visit();
render->end();

auto sprite = Sprite::create();
sprite->initWithTexture(render->getSprite()->getTexture());
sprite->setAnchorPoint(Vec2(0.5, 0.5));
sprite->setFlippedY(true);
sprite->setPosition(320, 480);
//addChild(sprite); /// ------------------- //works well, I got sprite image 
```

However, when I call:

```
Image *testImage = render->newImage();
unsigned char *data = testImage->getData(); // it's 0 always
```

I don't need to save image to disk, I just need it data.

**Comment by ricardoquesada** [comment]
thank. I'll take a look at it.

**Comment by sachingarg05** [comment]
I think this might be because all actual rendering happens when the frame ends (the commands are only queued). Sprite code works because that also gets executed only during next frame's rendering. If you want the newImage, try executing it after the next frame using a scheduler.

@ricardoquesada It will be good if RenderTexture provided a API like renderNow().

**Comment by iSuneast** [comment]
> I also ran into this issue. Any solution yet? Thanks!

I found a bug in my code. In fact, newImage() works for me. Sorry for that. :>

**Comment by stevetranby** [comment]
I suppose renderNow() might be useful, but wouldn't that require stalling until it can force OpenGL to write to the frame buffer backing storage and then calling readPixels or some other shared memory functionality. 

Maybe the API could just offer a similar callback like the Screen Shot functionality. 

``` cpp
// optionally method name: getImageData_FromNextRender or whatever
render->getImageData([](Image* image) { 
  unsigned char* data = image->getData();
}); 
```

**Comment by Dimon4eg** [comment]
Solution which works for me [on forum](http://discuss.cocos2d-x.org/t/problem-when-use-rendertexture-newimage-the-image-is-black-empty/13636/10)

call
`Director::getInstance()->getRenderer()->render();`
before
`render->newImage();`

**Comment by Seryusjj** [comment]
Thank you so much @Dimon4eg it's working for me too.

**Comment by ricardoquesada** [comment]
yes, you should force flushing the renderer. I'm closing this issue then. Reopen if you still think it is a bug. thanks.
