### ISSUE TITLE
Refactor CocosPlay JNI code with EasyJNI

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#14879]
Ref: https://github.com/cocos2d/cocos2d-x/pull/14340

**Comment by zilongshanren** [comment]
@WenhaiLin  please take a look.

**Comment by WenhaiLin** [comment]
The CocosPlay-related code should be remove from cocos engine now.

**Comment by zilongshanren** [comment]
ok @WenhaiLin  show me the PR :smile:

**Comment by WenhaiLin** [comment]
@zilongshanren Remove CocosPlayClient ：https://github.com/cocos2d/cocos2d-x/pull/14905
