### ISSUE TITLE
EditBox crashs when input Chinese in iOS 7.1.2

### ISSUE THREAD

**Issue by weiwest** [cocos2d/cocos2d-x#14884]
Error Details:

Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray replaceObjectsInRange:withObject:length:: Out of bounds'

Test Environment：
iPhone5c 
ios7.1.2
xcode7.2

**Comment by zilongshanren** [comment]
@westsuper2 
What's the engine version?

**Comment by weiwest** [comment]
cocos2d-x3.9 @zilongshanren

**Comment by zilongshanren** [comment]
@westsuper2 
I can reproduce this issue, thanks. I will fix it soon.

**Comment by zilongshanren** [comment]
@webcrawler 

``` cpp
- (void)textChanged:(UITextField *)textField
{
    int maxLength = getEditBoxImplIOS()->getMaxLength();
    if (textField.markedTextRange == nil) {
        if (textField.text.length > maxLength) {
            textField.text = [textField.text substringToIndex:maxLength];
        }

        const char* inputText = [textField.text UTF8String];
        getEditBoxImplIOS()->editBoxEditingChanged(inputText);
    }
}
```

```
- (void)textViewDidChange:(UITextView *)textView
{
    int maxLength = getEditBoxImplIOS()->getMaxLength();
    if (textView.markedTextRange == nil) {
        if (textView.text.length > maxLength) {
            textView.text = [textView.text substringToIndex:maxLength];
        }

        const char* inputText = [textView.text UTF8String];
        getEditBoxImplIOS()->editBoxEditingChanged(inputText);
    }
}

```

Pay attention to the following statement I added:

```
    if (textView.markedTextRange == nil) {
```

I think it's a bug in iOS 7.12...
Anyway, I will send the patch later.

**Comment by zilongshanren** [comment]
@westsuper2 
You could update `ui/widgets/UIEditBox/iOS/CCUIEditBoxIOS.mm` file by yourself.
If it solves your problem, please let me know.

**Comment by weiwest** [comment]
Yes,this method solves my problem,thank you. @zilongshanren
