### ISSUE TITLE
Compile 3rd pre-build libs get missing librapidjson.a error

### ISSUE THREAD

**Issue by xiaofeng11** [cocos2d/cocos2d-x#14897]
Use command  ./build.sh -p=ios under MacOSX to start build all pre-build library, the building process will broken after websocket compiled with follow info :

......
create fat library libssl for ios/ssl/prebuilt/arm64/libssl.a
ios/ssl/prebuilt/armv7/libssl.a
ios/ssl/prebuilt/i386/libssl.a
ios/ssl/prebuilt/x86_64/libssl.a
Architectures in the fat file: ios/ssl/prebuilt/libssl.a are: armv7 i386 x86_64 arm64 
create fat library for dependent archives...
removing old fat library...
create fat library libcrypto for ios/crypto/prebuilt/arm64/libcrypto.a
ios/crypto/prebuilt/armv7/libcrypto.a
ios/crypto/prebuilt/i386/libcrypto.a
ios/crypto/prebuilt/x86_64/libcrypto.a
Architectures in the fat file: ios/crypto/prebuilt/libcrypto.a are: armv7 i386 x86_64 arm64 

build armv7 for rapidjson in ios
toolchain path is 
Creating configuration file... config.mak
The host is apple-darwin
SDKROOT not specified, assuming /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk
Bootstrap completed.

Run "make" to start compilation.

Other targets:
- make install      same as "make"
- make list         list packages
- make fetch        fetch required source tarballs
- make fetch-all    fetch all source tarballs
- make distclean    clean everything and undo bootstrap
- make mostlyclean  clean everything except source tarballs
- make clean        clean everything
  make: Nothing to be done for `all'.
  /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build
  cp: /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build/../contrib/install-ios/armv7/lib/librapidjson.a: No such file or directory
  Copying needed heder files
  cleaning up

build i386 for rapidjson in ios
toolchain path is 
Creating configuration file... config.mak
The host is apple-darwin
SDKROOT not specified, assuming /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk
Bootstrap completed.

Run "make" to start compilation.

Other targets:
- make install      same as "make"
- make list         list packages
- make fetch        fetch required source tarballs
- make fetch-all    fetch all source tarballs
- make distclean    clean everything and undo bootstrap
- make mostlyclean  clean everything except source tarballs
- make clean        clean everything
  make: Nothing to be done for `all'.
  /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build
  cp: /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build/../contrib/install-ios/i386/lib/librapidjson.a: No such file or directory
  Copying needed heder files
  cleaning up

build arm64 for rapidjson in ios
toolchain path is 
Creating configuration file... config.mak
The host is apple-darwin
SDKROOT not specified, assuming /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk
Bootstrap completed.

Run "make" to start compilation.

Other targets:
- make install      same as "make"
- make list         list packages
- make fetch        fetch required source tarballs
- make fetch-all    fetch all source tarballs
- make distclean    clean everything and undo bootstrap
- make mostlyclean  clean everything except source tarballs
- make clean        clean everything
  make: Nothing to be done for `all'.
  /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build
  cp: /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build/../contrib/install-ios/arm64/lib/librapidjson.a: No such file or directory
  Copying needed heder files
  cleaning up

build x86_64 for rapidjson in ios
toolchain path is 
Creating configuration file... config.mak
The host is apple-darwin
SDKROOT not specified, assuming /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk
Bootstrap completed.

Run "make" to start compilation.

Other targets:
- make install      same as "make"
- make list         list packages
- make fetch        fetch required source tarballs
- make fetch-all    fetch all source tarballs
- make distclean    clean everything and undo bootstrap
- make mostlyclean  clean everything except source tarballs
- make clean        clean everything
  make: Nothing to be done for `all'.
  /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build
  cp: /Users/Norman/Projects/cocos2d-x-3rd-party-libs-src/build/../contrib/install-ios/x86_64/lib/librapidjson.a: No such file or directory
  Copying needed heder files
  cleaning up
  yes
  create fat library librapidjson for 
  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified
  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...
  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: ios/rapidjson/prebuilt/librapidjson.a (No such file or directory)

**Comment by xiaofeng11** [comment]
@zilongshanren Please take a look on it

**Comment by zilongshanren** [comment]
@xiaofeng11  this is not a problem, I will fix it.

**Comment by zilongshanren** [comment]
@xiaofeng11  
you should switch to v4 for compiling rapidjson
