### ISSUE TITLE
PageView::addEventListener() is invalid in v3.10

### ISSUE THREAD

**Issue by otake--masayoshi** [cocos2d/cocos2d-x#14909]
m_PageView->addEventListener(TestScene::callbackFunc, this);
TestScene::callbackFunc don't called when m_PageView turning.
sorry my English is poor.

**Comment by lifzgreat** [comment]
I'm sorry if I just duplicated this with #15325. That's for web vs Android but it's the same issue. I see this was just removed from the 3.11 milestone last week. Why is that? The PageView is not currently usable.

Thank you for all you guys do!

**Comment by zilongshanren** [comment]
@lifzgreat  it has been fixed in the latest v3 branch, please check...

**Comment by zilongshanren** [comment]
this issue is already fixed in upstream
