### ISSUE TITLE
RenderTexture 截屏后质量会有所下降

### ISSUE THREAD

**Issue by semgilo** [cocos2d/cocos2d-x#14910]
cococs2dx 3.9 lua

测试代码片段
local pRenderTexture = cc.RenderTexture:create(display.width, display.height,cc.TEXTURE2_D_PIXEL_FORMAT_RGB_A8888)
pRenderTexture:beginWithClear(0, 0, 0, 0)
self:visit()
pRenderTexture:endToLua()
pRenderTexture:addTo(self, 999)
pRenderTexture:getSprite():getTexture():setAntiAliasTexParameters() 
pRenderTexture:align(cc.p(0.5, 0.5), cc.pAdd(center(display.size),cc.p(0, 250)) )

效果示意：主要是文字变化比较明显
![image](https://cloud.githubusercontent.com/assets/7121873/12418139/2f5395f4-bee8-11e5-8095-729209c2acc3.png)

**Comment by playscforever** [comment]
@semgilo 问题解决了？

**Comment by semgilo** [comment]
@playscforever 后面使用cocos里面的截图 保存成Sprite
