### ISSUE TITLE
integrate new renderer

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/cocos2d-x#14913]
From here:
http://discuss.cocos2d-x.org/t/flaws-with-renderer-glprogram-and-gl-state-management/26239

**Comment by minggo** [comment]
Hi Riq, what's the status of this issue?

**Comment by ricardoquesada** [comment]
@minggo  some of the improvements mentioned on that thread were added into the renderer. the others shouldn't be part of v3.x. closing it implemented.
