### ISSUE TITLE
ControlSwitch::create(Sprite *maskSprite, Sprite * onSprite, Sprite * offSprite, Sprite * thumbSprite) crashes

### ISSUE THREAD

**Issue by ingtellect** [cocos2d/cocos2d-x#14946]
ControlSwitch::create(Sprite _maskSprite, Sprite \* onSprite, Sprite \* offSprite, Sprite \* thumbSprite) crashe. It calls initWithMaskSprite(maskSprite, onSprite, offSprite, thumbSprite, nullptr, nullptr) and eventually crashes when calling clipper->addChild(onLabel) and clipper->addChild(offLabel) in ControlSwitchSprite::initWithMaskSprite(
    Sprite *maskSprite, 
    Sprite *onSprite, 
    Sprite *offSprite,
    Sprite *thumbSprite,
    Label_ onLabel, 
    Label\* offLabel)
because onLabel and OffLabel is nullptr.

**Comment by minggo** [comment]
close this issue since the PR is merged. And please reopen it if it is not fixed.
