### ISSUE TITLE
Skip CCActionCamera:: startWithTarget?

### ISSUE THREAD

**Issue by codetypess** [cocos2d/cocos2d-x#1495]
void CCOrbitCamera::startWithTarget(CCNode *pTarget)
{
    CCActionInterval::startWithTarget(pTarget); //?CCActionCamera:: startWithTarget(pTarget)
    float r, zenith, azimuth;
    this->sphericalRadius(&r, &zenith, &azimuth);
    if( isnan(m_fRadius) )
        m_fRadius = r;
    if( isnan(m_fAngleZ) )
        m_fAngleZ = (float)CC_RADIANS_TO_DEGREES(zenith);
    if( isnan(m_fAngleX) )
        m_fAngleX = (float)CC_RADIANS_TO_DEGREES(azimuth);

```
m_fRadZ = (float)CC_DEGREES_TO_RADIANS(m_fAngleZ);
m_fRadX = (float)CC_DEGREES_TO_RADIANS(m_fAngleX);
```

}

the same code in cocos2d-iphone:

-(void) startWithTarget:(id)aTarget
{
    [super startWithTarget:aTarget];
    float r, zenith, azimuth;

```
[self sphericalRadius: &r zenith:&zenith azimuth:&azimuth];
```
# if 0 // isnan() is not supported on the simulator, and isnan() always returns false.

```
if( isnan(radius_) )
    radius_ = r;

if( isnan( angleZ_) )
    angleZ_ = (CGFloat)CC_RADIANS_TO_DEGREES(zenith);

if( isnan( angleX_ ) )
    angleX_ = (CGFloat)CC_RADIANS_TO_DEGREES(azimuth);
```
# endif

```
radZ_ = (CGFloat)CC_DEGREES_TO_RADIANS(angleZ_);
radX_ = (CGFloat)CC_DEGREES_TO_RADIANS(angleX_);
```

}

**Comment by godyZ** [comment]
@zhongfq  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2669
