### ISSUE TITLE
anchorPoint position delimiters parsing in CocosStudio works wrong (MacOS X)

### ISSUE THREAD

**Issue by mumreg** [cocos2d/cocos2d-x#14968]
Reproduce steps: (on MacOS X)
1. Set system language to Russian (or any other with delimiters - "," of fractional part of digit )
2. Open CocosStudio and create node with sprite and publish project.
Your sprite properties should look like that:
![2016-01-25 16 08 34](https://cloud.githubusercontent.com/assets/1148009/12551812/45e7b9cc-c37e-11e5-9452-38f4e351b772.png)
3. Look at size of csb-file/csd-file.
4. Set system language to English (or any other with delimiters - "." of fractional part of digit)
5. Open CocosStudio and publish project
Your sprite properties should look like that:
![screen shot 2016-01-25 at 16 11 58](https://cloud.githubusercontent.com/assets/1148009/12551875/ca6b5064-c37e-11e5-89e3-94e1c9d8147d.png)
6. Compare sizes of published csd and csb files for "," delimiters and "."

Size should be different. And when you'll try to load that nodes into your game anchorPoints of sprite will be (0.f 0.f) for ","-version and (0.5f, 0.5f) for "."-version.

**Comment by zilongshanren** [comment]
@chengstory  @xiaofeng11

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
