### ISSUE TITLE
Generated Prelibs for all platforms, rather than selective ones?

### ISSUE THREAD

**Issue by TheSachin** [cocos2d/cocos2d-x#14960]
Hi,
I fail to understand why we are not shipping prebuilt version of Windows platform, is absence mere cause of less Windows platform devices, or is there something else as well?
Edit : Windows 10 Store

**Comment by minggo** [comment]
What did you mean prebuilt windows version?

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree. @TheSachin @minggo
