### ISSUE TITLE
3.10 Install fmod for new AudioEngine on Linux with install-deps-linux.

### ISSUE THREAD

**Issue by madebymozart** [cocos2d/cocos2d-x#14961]
**Link** - http://discuss.cocos2d-x.org/t/error-while-building-for-linux-libfmod-so-6/26553/4 

**Description** - When you have a fresh download of cocos2d-x 3.10 and you do all the normal step (ex. `./download-deps.sh` and `./install-deps-linux.sh`) the build will still crash with this error:

`/bin/debug/linux/MyGame: error while loading shared libraries: libfmod.so.6: cannot open shared object file: No such file or directory`

The way to fix this is to copy the `libfmod.so` and `libfmodL.so` to `/usr/local/lib/` and the `fmod.h` files to `/usr/local/include/`. I was wondering if we could add this to the `install-deps-linux.sh` script.

The commands:
`sudo cp <*COCOS FOLDER LOCATION*>/external/linux-specific/fmod/prebuilt/64-bit/libfmod.so /usr/local/lib/`

`sudo cp  <*COCOS FOLDER LOCATION*>/external/linux-specific/fmod/prebuilt/64-bit/libfmodL.so /usr/local/lib/`

`sudo cp <*COCOS FOLDER LOCATION*>/external/linux-specific/fmod/include/*.h /usr/local/include/`

Then Run the script  install-deps-linux again

**Comment by cesarpachon** [comment]
hello @mozartalouis, I just checked the issue and I think there is no need to copy to /usr/local/lib, what I did was just to create a symbolic link in the same folder of the libfmod.so: 
ln -s libfmod.so libfmod.so.6
I am not used to the install-deps-linux.sh internals, but I will try this approach there to see if it solves the issue.

**Comment by Dimon4eg** [comment]
Hi, I also had this issue on Linux Mint.

My total solution:
1. copy
   sudo cp <COCOS FOLDER LOCATION>/external/linux-specific/fmod/prebuilt/64-bit/libfmod.so /usr/local/lib/
   sudo cp <COCOS FOLDER LOCATION>/external/linux-specific/fmod/prebuilt/64-bit/libfmodL.so /usr/local/lib/
2. create symbolic link in /usr/local/lib/
   ln -s libfmod.so libfmod.so.6
3. run ./install-deps-linux again (in cosos2d/build)

**Comment by rmuratov** [comment]
@Dimon4eg Also helped me on Linux Mint 17.1, thanks

**Comment by RequiemSouls** [comment]
hello @mozartalouis 
how did you fix this bug?
I did cp libfmod.so /usr/local/lib/ and ln -s libfmod.so libfmod.so.6
but it's still doesn't work.

**Comment by Dimon4eg** [comment]
Hi @RequiemSouls 
Did you try my solution described above?

@mozartalouis Why did you close the bug? Is it fixed?

**Comment by RequiemSouls** [comment]
@Dimon4eg 
I try your solution. but it's still error.
How according to the print message to check the operating is success.
I never get error when execute install-deps-linux.sh

**Comment by RequiemSouls** [comment]
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found
I found this error when I execute`install-deps-linux` 
this is the cause of the error?

**Comment by bretsko** [comment]
Why is this bug closed? By the way @Dimon4eg solution is working perfectly fine on my Debian machine.

**Comment by teosbpl** [comment]
Hi everybody. Another solution is to use the ldconfig machinery:
sudo cat > /etc/ld.so.conf.d/cocos.conf
Enter a line /<MYCOCOS2DXDIR/external/linux-specific/fmod/prebuilt/64-bit
or /<MYCOCOS2DXDIR/external/linux-specific/fmod/prebuilt/32-bit
Run sudo ldconfig
Enjoy cpp_tests - without any compilation 

If you have nothing in /<MYCOCOS2DXDIR/external/linux-specific/fmod/prebuilt/64-bit - then you need install-deps-linux.sh

**Comment by uxdxdev** [comment]
@teosbpl Thank you.

**Comment by raydelto** [comment]
It worked for me copying libfmodL.so  and libfmod.so to **/usr/lib** , then creating a link to libfmod.so  named libfmod.so.6 .

I'm using Ubuntu 14.04

**Comment by reneolivo** [comment]
@raydelto answer worked for me. I'm using Ubuntu 16.04

**Comment by malleyne** [comment]
I'm running into the same error but the first solution mentioned hasn't worked for me :( I'm stuck as to how to resolve it. 

I have a raspberry pi model b with debian

My scenario:

**~/fmodstudioapi10813linux/api/lowlevel/examples/make $** make --file play_stream.makefile CONFIG=Debug CPU=arm

**~/fmodstudioapi10813linux/api/lowlevel/examples/make $** ./play_stream 

`./play_stream: error while loading shared libraries: libfmodL.so.8: cannot open shared object file: No such file or directory`

**~/fmodstudioapi10813linux/api/lowlevel/lib/arm $** ls /usr/local/lib/

`libfmodL.so  libfmodL.so.8  libfmodL.so.8.13  libfmod.so  libfmod.so.8  libfmod.so.8.13`

**~ $** ls /usr/local/include/

`fmod_codec.h  fmod_common.h  fmod_dsp_effects.h  fmod_dsp.h  fmod_errors.h  fmod.h  fmod.hpp  fmod_output.h  node`

**~ $** env | grep '^LD_LIBRARY_PATH'

LD_LIBRARY_PATH=:/usr/local/lib:/home/pi/fmodstudioapi10813linux/api/lowlevel/lib/arm

**Comment by banjocat** [comment]
I only ran into this issue if I was using lua or javascript.

My solution was to just create a link within the project. I did no copying into /usr/lib

Below is an example.. as I linked via full path.
```
ln -s /home/banjocat/code/games/test/frameworks/cocos2d-x/external/linux-specific/fmod/prebuilt/64-bit/libfmod.so /home/banjocat/code/games/test/frameworks/cocos2d-x/external/linux-specific/fmod/prebuilt/64-bit/libfmod.so.6
```
