### ISSUE TITLE
BUG:setInputMode(ui::EditBox::InputMode::SINGLE_LINE) 

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14981]
edit box 在android上设置了setInputMode(ui::EditBox::InputMode::SINGLE_LINE) 
输入文字过长是会多行显示

android 
测试是会出现文字多行显示的，输入内容后点击键盘外面关闭按钮会出现多行显示，如果是点击键盘上的关闭按钮关闭键盘是正常的，但在点击屏幕则会出现多行显示
![11](https://cloud.githubusercontent.com/assets/7157980/12611355/214d9992-c527-11e5-9308-614cf3087d50.png)
@xiaofeng11

**Comment by xiaofeng11** [comment]
@zilongshanren Please take a look on this issue

**Comment by zilongshanren** [comment]
@1078559858 
那不是多行显示，而是换行了。如果不换行，难道要截断么？单行最好限定最大长度。

**Comment by ThirteenZhou** [comment]
最好能做成跟ios一样的效果吧，ios上是截断处理的
