### ISSUE TITLE
CSLoader 执行 ActionTimeline后，多个动画节点被移除时卡顿时间非常长

### ISSUE THREAD

**Issue by kibernet** [cocos2d/cocos2d-x#14987]
当有10个ActionTimeline时 ，界面被移除时，游戏卡顿3到5秒之久
延迟一帧移除执行ActionTimeline的节点是可以解决卡顿的问题，延迟一帧移除完全没有卡顿了

**Comment by xiaofeng11** [comment]
@geron-cn Please take a look on this issue.

**Comment by geron-cn** [comment]
@kibernet Js Version?

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
