### ISSUE TITLE
键盘弹起后，触摸区域并没有随着键盘的弹起而变化

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#14984]
cocos3.10 + ios
当输入的时候，打开软键盘，游戏画面会上移。此时点击上移的游戏画面，会触发之前游戏画面没有上移时候的区域，进而会触发对应的逻辑。

**Comment by zilongshanren** [comment]
@1078559858 
What's your code look like?

If you use node.convertTouchToNodeSpace, it shouldn't have problems.
