### ISSUE TITLE
游戏切换到后台，再切换回来动画累积的问题

### ISSUE THREAD

**Issue by tooolkit** [cocos2d/cocos2d-x#14991]
cocos2d-js 写的h5 游戏切换到后台的时候服务器发了很多消息  等切换回来了 所有响应消息的动画都累积到一起显示了  这样应该怎么处理啊

**Comment by Zzzen** [comment]
按照逻辑要求，要显示哪个就显示哪个，要停哪个就停哪个

**Comment by zilongshanren** [comment]
@tooolkit
I suggest you guys move this topic into Chinese forum. thanks.
