### ISSUE TITLE
Scale9Sprite a problem

### ISSUE THREAD

**Issue by sianzain** [cocos2d/cocos2d-x#15008]
in VS2012 can't build.

//--------------------------------------------------------------------------------------------------
uvCoordinates = {Vec2(u0,v3), Vec2(u3,v0)};

Should be modified as

Vec2 uvCoordinatesArr[] = {Vec2(u0,v3), Vec2(u3,v0)};
uvCoordinates = std::vector<Vec2>(uvCoordinatesArr, uvCoordinatesArr + sizeof(uvCoordinatesArr) / sizeof(Vec2) );
//--------------------------------------------------------------------------------------------------
uvCoordinates = {Vec2(u0,v3), Vec2(u1,v2), Vec2(u2,v1), Vec2(u3,v0)};

Should be modified as

Vec2 uvCoordinatesArr[] = {Vec2(u0,v3), Vec2(u1,v2), Vec2(u2,v1), Vec2(u3,v0)};
uvCoordinates = std::vector<Vec2>(uvCoordinatesArr, uvCoordinatesArr + sizeof(uvCoordinatesArr) / sizeof(Vec2) );
//--------------------------------------------------------------------------------------------------
vertices = {Vec2(offsetLeft \* hScale, offsetBottom \* vScale),
                  Vec2(_preferredSize.width - offsetRight \* hScale, _preferredSize.height - offsetTop \* vScale)};

Should be modified as

Vec2 verticesArr[] = {Vec2(offsetLeft \* hScale, offsetBottom \* vScale),
                 　　　　　Vec2(_preferredSize.width - offsetRight \* hScale, _preferredSize.height - offsetTop \* vScale)};
vertices = std::vector<Vec2>(verticesArr, verticesArr + sizeof(verticesArr) / sizeof(Vec2) );
//--------------------------------------------------------------------------------------------------
vertices = {Vec2(x0,y0), Vec2(x1,y1), Vec2(x2,y2), Vec2(x3,y3)};

Should be modified as

Vec2 verticesArr[] = {Vec2(x0,y0), Vec2(x1,y1), Vec2(x2,y2), Vec2(x3,y3)};
vertices = std::vector<Vec2>(verticesArr, verticesArr + sizeof(verticesArr) / sizeof(Vec2) );
//--------------------------------------------------------------------------------------------------

**Comment by zilongshanren** [comment]
@sianzain 
we don't support vs2012 now. Please use vs2013 +  instead.
