### ISSUE TITLE
cocos2d-x-v3.10 fails linking lua project when building debug on linux(deepin and ubuntu)

### ISSUE THREAD

**Issue by Andyscream** [cocos2d/cocos2d-x#15017]
[ 21%] Built target bullet
[ 21%] Built target HelloLua_PRE_BUILD
[ 87%] Built target cocos2d
[100%] Built target luacocos2d
[100%] Linking CXX executable bin/HelloLua
lib/libluacocos2d.a(loslib.c.o)：in function‘os_tmpname’：
/home/x/workspace/testlua/frameworks/cocos2d-x/external/lua/lua/loslib.c:60: warnings：the use of `tmpnam' is dangerous, better use`mkstemp'
CMakeFiles/HelloLua.dir/runtime-src/Classes/AppDelegate.cpp.o：in function ‘AppDelegate::applicationDidFinishLaunching()’：
/home/x/workspace/testlua/frameworks/runtime-src/Classes/AppDelegate.cpp:63：
‘lua_module_register(lua_State_)’ undefined reference
collect2: error: ld returned 1 exit status
CMakeFiles/HelloLua.dir/build.make:143: recipe for target 'bin/HelloLua' failed
make[2]: *_\* [bin/HelloLua] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/HelloLua.dir/all' failed
make[1]: **\* [CMakeFiles/HelloLua.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2
Execute command error, return value：2。

**Comment by Andyscream** [comment]
我试过了，用v3.9创建lua工程，编译是通过的，但是v3.10创建lua工程，就是最后一步linking executable时出错，linux系统，我用deepin和ubuntu都试过了，出错，没人遇到和我一样的问题吗？

**Comment by zilongshanren** [comment]
@Andyscream 
我回头修一下，貌似是有问题。

**Comment by jingtaow** [comment]
I also met exactly the same problem. My environment is Ubuntu Desktop 14.04 64 bit + Cocos2dx-3.10. Is there a fix now?

**Comment by Andyscream** [comment]
No，it didn't fix yet !

**Comment by zilongshanren** [comment]
@Andyscream 
Be patient, man...

**Comment by AllanDaemon** [comment]
I gotta the same error here. I'm using a Debian Sid (Unstable) AMD64.

**Comment by minggo** [comment]
the latest version doesn't have the issue, so close it
