### ISSUE TITLE
Cannot edit decimal value in CocosStudio 3.10 on Windows with decimal separator other than dot.

### ISSUE THREAD

**Issue by adesentenac** [cocos2d/cocos2d-x#15020]
If the decimal separator is not the dot (.), like in French where it's the comma (,), edition of decimal values in Cocos Studio (like anchor point, position, size...) is not possible.
The only thing possible is to clear the current value and set an integer value.

The only way to work around it is to go in Windows regional options and change the decimal separator.

In previous versions of Cocos Studio, typing the decimal separator was not possible, but editing values was working.

**Comment by xiaofeng11** [comment]
Hi adesentenac,
Please refer discus in http://discuss.cocos2d-x.org/t/cocos-studio-2-2-6-very-buggy-on-mac-os/21598/20, there's a temporary solution. This issue will be fix in next version.

**Comment by AIGRIND-LLC** [comment]
@xiaofeng11 It seems the link you provided has no solution for this issue.
Waiting for the fix.

**Comment by AIGRIND-LLC** [comment]
In Windows 8.1 Pro it could be fixed in that way:

![untitled](https://cloud.githubusercontent.com/assets/6168693/13183199/5a175faa-d73e-11e5-9275-17b1fd4b5eb5.png)

**Comment by vitalyrovny** [comment]
+1

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
