### ISSUE TITLE
iOS Simulator Build Linking Issues

### ISSUE THREAD

**Issue by aardvarkk** [cocos2d/cocos2d-x#15049]
It appears that the libcocos2d iOS build has only the following valid architectures for Debug and Release:

`VALID_ARCHS = "arm64 armv7";`

This caused me linking headaches in XCode 7.2 as it refused to link against the Cocos libraries when doing a simulator build. This makes sense, because the simulator build is for an x86_64 architecture, not an ARM architecture like the actual device build. By removing the manually listed "valid architectures" and specifying not to only build the active architecture only the linker issues disappeared. I am submitting a pull request to correct this.

**Comment by minggo** [comment]
I don't have any problem with Xcode 7.3

**Comment by minggo** [comment]
> This caused me linking headaches in XCode 7.2 as it refused to link against the Cocos libraries when doing a simulator build. 

@aardvarkk What did you mean `doing a simulator build`?

**Comment by aardvarkk** [comment]
@minggo Trying to run a project that executes on a simulator instead of an actual device.

**Comment by minggo** [comment]
As i said, i have not problem with XCode 7.3, and i didn't meet problem in previous Xcode versions.

**Comment by aardvarkk** [comment]
Could have been an issue in a previous version of Cocos at this point. Perhaps it’s safe to close.
