### ISSUE TITLE
CCFontFNT missing _fontSize on binary fonts.

### ISSUE THREAD

**Issue by WarlockD** [cocos2d/cocos2d-x#15042]
Was trying to use some binary fonts when, for some reason, the fonts came out with no fontSize.  I noticed in BMFontConfiguration::parseConfigFile that it would read the fontSize from the text version but it would never set it from the binary version.

I just added these lines to BMFontConfiguration::parseBinaryConfigFile.

``` C
uint16_t fontSize = 0; memcpy(&fontSize, pData, 2);  // add
_fontSize = fontSize;  // add
 _padding.top = (unsigned char)pData[7];
_padding.right = (unsigned char)pData[8];
_padding.bottom = (unsigned char)pData[9];
_padding.left = (unsigned char)pData[10];
```

I don't have access right now to Git any time soon, so thought I post it to see if someone else can confrere.

**Comment by aardvarkk** [comment]
Ugh!

I can confirm the following:
1. I have been trying to figure out why none of my previously-working bitmap fonts were showing up at all. No errors, just a black screen.
2. I spent the last day and a half wandering through the Cocos internal code trying to figure out why the text wasn't showing up.
3. Your fix solves the issue! Thank you so much for finding this!

I have altered your code slightly to remove the creation of a temporary variable, and I will submit a pull request to fix it.

**Comment by WarlockD** [comment]
Honestly I think the entire code should be refactored.  You take a look at the AngelCode Font program source, you see that it just writes the raw c structure to file.  But in cocos2d it reads the individual numbers in multiple memory statements.  If your not going to care about endianness in this format, why not just read the entire 20 byte structure at once instead of having 9 separate temp variables for it as well as 9 separate memcpy commands?

Heck, even the text .fnt reader should have a redo, atleast with some error checking.  I know we want speed, but figure the parts that load the file into the cache should have that atleast.

Actually, when I look at this, does this even work on an Android or IOS device?  Its reading shorts/ints without caring about how the raw data is stored.
