### ISSUE TITLE
master version cpp-tests runtime crash on ubuntu debug mode

### ISSUE THREAD

**Issue by cesarpachon** [cocos2d/cocos2d-x#15056]
hi, just after building the latest commit: 3177f3431ecbedd5756317b72afc12a6ade45585 in ubuntu, I tested both my project and the cpp-tests in linux-debug mode, in both cases there is a segmentation fault: 

Program received signal SIGSEGV, Segmentation fault.
0x000000000185f1c2 in cocos2d::Node::insertChild (this=0x2f70540, child=0x2f708c0, z=0)
    at /home/cesar/Projects/cocos2d-x/cocos/2d/CCNode.cpp:1125
1125        ScriptEngineManager::getInstance()->getScriptEngine()->retainScriptObject(this, child);

I will try to collect more info on this, but would like to know if someone else has the same issue.

**Comment by zilongshanren** [comment]
@cesarpachon 
I think this is a critical bug, @pandamicro  please take a look at this.

**Comment by zilongshanren** [comment]
@cesarpachon 
Wired, I have just tested the cpp-tests project on my ubuntu 14.04 machine and it works well.

**Comment by zilongshanren** [comment]
@cesarpachon 
I can reproduce this issue on my mac.

**Comment by zilongshanren** [comment]
@cesarpachon  I think it has been fixed now. please check the latest upstream.

**Comment by cesarpachon** [comment]
@zilongshanren It is working now, thanks!
