### ISSUE TITLE
TextAlignment in conjunction with kerning

### ISSUE THREAD

**Issue by Leandros** [cocos2d/cocos2d-x#15077]
Setting a TextAlignment via cocostudio, and after that changing the kerning of that label via code, results in wrong alignment.
It looks like the alignment is applied before the kerning, and the actual (freetype bitmap) font is centered in the center of the label.

See the attached image:

![err](https://cloud.githubusercontent.com/assets/396475/13107140/7e93de5e-d56c-11e5-9046-89657385f745.png)

All labels were left aligned.

**Comment by lolaloli** [comment]
The optimization introduces a bug where the priority and Touch Mode will not get changed if the list is locked.
The most straight forward fix is to merge the pHandlersToAdd and pHandlersToRemove into a queue and process through all of them in the order they are received

[Agen Bola Euro 2016](http://idcash78.com/idcash78-com-agen-bola-resmi-terpercaya-euro-2016/)

**Comment by Leandros** [comment]
lol

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
