### ISSUE TITLE
[CocosStudio v3.10] Crashes when open file csd on CocosStudio 3.10, Win10 !

### ISSUE THREAD

**Issue by tungnt11** [cocos2d/cocos2d-x#15075]
I am using Win10 after updated from Win 8.1. 
For CocosStudio 2.3.3 , i use normal. But when i update to v3.10, i cann't open file csd by CocosStudio. It's crashes.

**Comment by xiaofeng11** [comment]
Hi dimaria11, CocosStudio need hardware acceleration, please confirm your video card driver have been update to the latest version and works fine. And we found some user running CocosStudio in VM, please get to know that VMWare won't support hardware acceleration to Win10 running in VM now.

**Comment by tungnt11** [comment]
I'm not running in VM, but my laptop have problem about ATI Card. Now, I only use Intel HD Graphics.
Is it reason???

**Comment by tungnt11** [comment]
For CocosStudio 2.3.3, i use normal. What's the new in CocosStudio 3.10 ?

**Comment by xiaofeng11** [comment]
Please update your ATI Card driver and try again, I've just talk with studio group members they find most user reported crash issue is this reason. And there hasn't any change about openGL init between 2.3.3 & 3.10, they can not sure why CocosStudio 2.3.3 run well but CocosStudio 3.10 crash. When cocos2dx init, it will call some function of libglfw, maybe this lib runs different between Win8.1 and Win10.

**Comment by tungnt11** [comment]
But my ATI Card was broken. I only use Intel HD Graphics and don't use driver for ATI Card. Maybe, I'll use CocosStudio 2.3.3. :(. Thanks a lot xiaofeng11!

**Comment by xiaofeng11** [comment]
You are welcome dimaria11, Does you have any crash log? it can help us find what's wrong on your PC.

**Comment by tungnt11** [comment]
[https://drive.google.com/open?id=0B3PtFU6P-CnkWDJxOFNqTlJYb28](url)
I debug with visual Studio. I'm not sure it can help you. :)

**Comment by xiaofeng11** [comment]
I won't have right to access the page, could you send it to me by email? My email is xiaofeng@chukong-inc.com

**Comment by tungnt11** [comment]
i just send you. Please check your mail.

**Comment by Michinin** [comment]
I have the same issue - crashes when open file csd on CocosStudio 3.10, Win10
I tried re-install but nothing changes

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
