### ISSUE TITLE
Preload not support on Anroid  

### ISSUE THREAD

**Issue by zhbd-bobi** [cocos2d/cocos2d-x#15086]
experimental::AudioEngine::preload(path, [musicID](bool isSuccess) 
    { 
        CCLOG("IS IN PRELOAD"); 
        if(isSuccess) 
        { 
            XXXX; //can't arrive
        } 
    }); 

When I run this code on android,'XXXX' can't be arrived!!

The log is shown as below in Logcat;
02-11 18:57:33.978: D/cocos2d-x debug info(29899): Preload not support on Anroid

**Comment by minggo** [comment]
Yep, Android doesn't support preload now.

**Comment by dumganhar** [comment]
It's gonna be supported in cocos2d-x 3.13.
Rather, preload for android is supported in the v3 branch.
