### ISSUE TITLE
BUG:帧动画仅0帧有帧事件，则只会触发一次帧事件。

### ISSUE THREAD

**Issue by 1078559858** [cocos2d/cocos2d-x#15084]
cocos 3.10 c++
原因：
在cctimeline.cpp文件中，
void Timeline::binarySearchKeyFrame(unsigned int frameIndex)
函数中进入do语句中的ifelse语句break后，
if(needEnterFrame || _currentKeyFrame != from）判断句没有进入，
导致eventframe的enter没有调用。

解决办法：
void Timeline::binarySearchKeyFrame(unsigned int frameIndex)
{
Frame *from = nullptr;
…………
 bool needEnterFrame = false;

//添加bool变量
bool needEnterFrameEvent = false;

…………
…………
…………
  from = to = _frames.at(length - 1); 
            _currentKeyFrameIndex = _frames.at(length - 1)->getFrameIndex();
            _betweenDuration = 0;

//添加判断句
if (_currentKeyFrame == from && frameIndex == 0)
{
needEnterFrameEvent = true;
}
……
……
……
} while (0);

//修改if语句
if(needEnterFrame || _currentKeyFrame != from || needEnterFrameEvent)
…………
…………
}

@xiaofeng11

**Comment by xiaofeng11** [comment]
@geron-cn Please take a look on this issue

**Comment by 1078559858** [comment]
my solution only work on this bug, Please pay more attention to it.
thx

**Comment by wulei** [comment]
@xiaofeng11  这里是不是会引起 #15230 问题？

**Comment by xiaofeng11** [comment]
@wulei #15230 是另外一个问题，返回的Action没有进行clone导致的，已经在其它pr里修复。你可以参考garon-cn在那个issue里面的回复。
如果可以的话请帮忙确认一下合并这两个修复之后是不是相关问题已经解决了，谢谢！

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
