### ISSUE TITLE
A class template 'CreateHelper'. Just A feature.

### ISSUE THREAD

**Issue by halx99** [cocos2d/cocos2d-x#15082]
usage:
 CreateHelper::create(&MySprite::initWithFile, "test.png");
[CCCreateHelper.zip](https://github.com/cocos2d/cocos2d-x/files/135570/CCCreateHelper.zip)
implement source code:
# ifndef _CCCREATE_HELPER_H_
# define _CCCREATE_HELPER_H_

/*
*\* CreateHelper for cocos2d's autorelease objects
*/
namespace cocos2d {

template<typename _Ty>
class CreateHelper
{
    typedef CreateHelper<_Ty> _Myt;
public:
    template<typename ..._Args>
    static _Ty\* create(const _Args&...args)
    {
        auto ccobj = new(std::nothrow) _Ty();

```
    if (ccobj != nullptr && CreateHelper<_Ty>::delayed_init(ccobj, args...))
    {
        ccobj->autorelease();
        return ccobj;
    }

    CC_SAFE_RELEASE_NULL(ccobj);

    return ccobj;
}

template<typename _Arg1, typename..._Args>
static bool delayed_init(_Ty* ccobj, const _Arg1& memf, const _Args&...args)
{
    return traits_init<std::is_member_function_pointer<_Arg1>::value>::delayed_init(ccobj, memf, args...);
}

static bool delayed_init(_Ty* ccobj)
{ // init use 'init' member func without arg
    return ccobj->init();
}

template<bool>
struct traits_init{};

template<>
struct traits_init<false>
{
    template<typename..._Args>
    static bool delayed_init(_Ty* ccobj, const _Args&...args)
    { // init use 'init' member func with more than 1 args
        return ccobj->init(args...);
    }
};

template<>
struct traits_init<true>
{
    template<typename _Fty, typename..._Args>
    static bool delayed_init(_Ty* ccobj, const _Fty& memf, const _Args&...args)
    { // init use specific member func with more than 1 args
        return std::mem_fn(memf)(ccobj, args...);
    }

    template<typename _Fty>
    static bool delayed_init(_Ty* ccobj, const _Fty& memf)
    { // init use specific member func without arg
        return std::mem_fun(memf)(ccobj);
    }
};
```

};

};
# endif

**Comment by halx99** [comment]
implement source code:

#ifndef _CCCREATE_HELPER_H_
#define _CCCREATE_HELPER_H_

/*
** CreateHelper for cocos2d's autorelease objects
*/
namespace cocos2d {

template<typename _Ty>
class CreateHelper
{
    typedef CreateHelper<_Ty> _Myt;
public:
    template<typename ..._Args>
    static _Ty* create(const _Args&...args)
    {
        auto ccobj = new(std::nothrow) _Ty();

        if (ccobj != nullptr && CreateHelper<_Ty>::delayed_init(ccobj, args...))
        {
            ccobj->autorelease();
            return ccobj;
        }

        CC_SAFE_RELEASE_NULL(ccobj);

        return ccobj;
    }

    template<typename _Arg1, typename..._Args>
    static bool delayed_init(_Ty* ccobj, const _Arg1& memf, const _Args&...args)
    {
        return traits_init<std::is_member_function_pointer<_Arg1>::value>::delayed_init(ccobj, memf, args...);
    }

    static bool delayed_init(_Ty* ccobj)
    { // init use 'init' member func without arg
        return ccobj->init();
    }

    template<bool>
    struct traits_init{};

    template<>
    struct traits_init<false>
    {
        template<typename..._Args>
        static bool delayed_init(_Ty* ccobj, const _Args&...args)
        { // init use 'init' member func with more than 1 args
            return ccobj->init(args...);
        }
    };

    template<>
    struct traits_init<true>
    {
        template<typename _Fty, typename..._Args>
        static bool delayed_init(_Ty* ccobj, const _Fty& memf, const _Args&...args)
        { // init use specific member func with more than 1 args
            return std::mem_fn(memf)(ccobj, args...);
        }

        template<typename _Fty>
        static bool delayed_init(_Ty* ccobj, const _Fty& memf)
        { // init use specific member func without arg
            return std::mem_fun(memf)(ccobj);
        }
    };
};

};

#endif

**Comment by lolaloli** [comment]
The optimization introduces a bug where the priority and Touch Mode will not get changed if the list is locked.
The most straight forward fix is to merge the pHandlersToAdd and pHandlersToRemove into a queue and process through all of them in the order they are received

[Agen Bola Euro 2016](http://idcash78.com/idcash78-com-agen-bola-resmi-terpercaya-euro-2016/) | [Agen Judi Online](http://idcash78.net/)

**Comment by minggo** [comment]
Thanks. But please don't use issue system for sharing codes.
