### ISSUE TITLE
Cannot load sound resources in android

### ISSUE THREAD

**Issue by PhucDuy** [cocos2d/cocos2d-x#15090]
I use SimpleAudioEngine to play sound for my game. It's work in iOs. But in Android, It get errors such as " cocos2d: fullPathForFilename: No file found at winner_sound.mp3. Possible missing file." 
I use cocos2dx version 3.10 and  sound file is already existed in file apk.
Anyone can help me?

**Comment by pwang08** [comment]
I have fixed this issue, check this:   #15193 .
