### ISSUE TITLE
[libwebsockets] not compiled

### ISSUE THREAD

**Issue by pixmaster** [cocos2d/cocos2d-x#15106]
related to https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/issues/89
What is that?

> tar (child): xz: Cannot exec: No such file or directory
> tar (child): Error is not recoverable: exiting now
> make: **\* [../../contrib/tarballs/libwebsockets-git.tar.xz] Error 141
> make: **\* Deleting file `../../contrib/tarballs/libwebsockets-git.tar.xz'

**Comment by pixmaster** [comment]
Solution: need install lzma tool.
Maybe need specify dependencies?

**Comment by minggo** [comment]
It is better not report 3rd party libs issue here.
