### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by crobertsbmw** [cocos2d/cocos2d-x#15107]
The link in the readme for the "Temporary Cocos2d-JS documents" to http://cocos2d-x.org/docs/manual/framework/html5/en is dead. It throws an nginx error.

**Comment by slackmoehrle** [comment]
This is being fixed.

**Comment by geometrydash** [comment]
Useful information.I am actual blessed to read this article.thanks for giving us this advantageous information.I acknowledge this post.and I would like bookmark this post.Thanks [five nights at freddy's 3](http://fivenightsatfreddysaz.com/five-nights-at-freddys-3)  [five nights at freddy's 4](http://fivenightsatfreddysaz.com/five-nights-at-freddys-4)  [five nights at freddy's 2](http://fivenightsatfreddysaz.com/five-nights-at-freddys-2)
