### ISSUE TITLE
lots of methods not exists in api reference

### ISSUE THREAD

**Issue by Skywalker-gamefu** [cocos2d/cocos2d-x#15100]
hi

im using visual studio and i see lots of (sprite / node) method if i serch for it in the online api reference dosent exists like

setOpacity and setColor

and more i hope to fix it

**Comment by zilongshanren** [comment]
@Skywalker-gamefu 
Thanks, I will fix it later... but I can't update the online api ref right now...
I will ask someone else to do the job...
