### ISSUE TITLE
EditBox crash on  iOS7  V3.10

### ISSUE THREAD

**Issue by robslove** [cocos2d/cocos2d-x#15110]
test-cpp=》extensionsTest=>EditBoxTest

=>name

=>input chinese, when exceed the length limit

=>crash

only on ios7, ios9 is is OK

该问题只会在ios7出现,搜了可能的类似问题
http://www.cocoachina.com/bbs/read.php?tid-460148.html
http://www.bubuko.com/infodetail-1414853.html
http://www.jianshu.com/p/2d1c06f2dfa4

**Comment by zilongshanren** [comment]
@robslove 
duplicated with https://github.com/cocos2d/cocos2d-x/issues/14884

**Comment by zilongshanren** [comment]
@robslove  I have fixed in v3.11, please tell me after apply the fix, thanks.
