### ISSUE TITLE
Support loading .psd file

### ISSUE THREAD

**Issue by iSuneast** [cocos2d/cocos2d-x#15115]
I wonder why cocos2d doesn't support .psd file now?

I have checked the code, and noticed that when I create a sprite by calling `Sprite::create(const std::string& filename)`. This function would finally call `Director::getInstance()->getTextureCache()->addImage()` to load the texture file.

However, the comment said, `* Supported image extensions: .png, .bmp, .tiff, .jpeg, .pvr.`. There is no ".psd". :(

I wonder are you going to support loading psd file in the future?

Please let me know if I have missed anything. Thank you so much.

**Comment by RizkiePratama** [comment]
I'm not sure, PSD not just storing image/color data, it also store other data needed by Adobe software suite. and As far as i know cocos directly load the asset and process it on runtime. If it's going to have a psd support i think it best to have / create some custom asset database and pack it into something cocos2d can read when compiling.

unless you think you'll getting benefit from using psd file (eg: Layering) i guess it's good to have a psd support. Of couse it would not hurt on develoment but i think it would be bad for production, especially on mobile / web based.

Well i'm not really familiar with cocos yet and not a fan of PSD format. so correct me if i wrong.

**Comment by iSuneast** [comment]
Hi Rizkie,

Thank you so much for your reply. :>

As you may know, most of the designers use photoshop to create the sprite. It would simply be more convenient if cocos does support loading psd, since we don't want to export png for every psd. Moreover, we don't want to maintain multiple copies of a sprite (psd version and png version).

You said, "it would be bad for the production". Do you mean psd would affect the performance or size of you game? If so, in fact, the engine could provide some import options and do some packing on the image.

Thanks.

**Comment by RizkiePratama** [comment]
Well, indeed it will be much easier for the designer comparing to export it to other format each time you create new asset. but just like i said, cocos load asset diretly as the developer give, ex: if you have the texture as a png, the you will be easily get that png file on final version on the asset folder. The same goes for other format, including psd file. Unless you don't mind to expose the your raw asset to the public.

Of course this won't be much a problem if you're realeasing on mobile platform without have the game data seperated with the main program(apk).

In some case psd file can have a bigger size compared to other file format(especialy if you working with complex one), aside from storing other data than image/color, psd format was not compressed. So this gonna waste some space when it's not actually need.

Incase of other engine, eg: unity, they have their own asset database. So it's just take the needed image data from psd's and compile it to unity assets file.

im not against for adding this psd support, but cocos need a method to store only need data on final release. Maybe same method on their 3d model converter, .fbx to .c3b (cocos 3d binary)

**Comment by minggo** [comment]
There is not plan to support psd file. Please use png or jpeg instead.
