### ISSUE TITLE
Provide flatbuffer schemes for custom edit?

### ISSUE THREAD

**Issue by eranzhao** [cocos2d/cocos2d-x#15124]
There's a lots of generated code in cocos2dx for serialization, such as CSParseBinary_generated.h. The generated protocol is not full and complete, and we need to update them for making advanced prefabs. But I can not find the flatbuffer schemes, should cocos2dx provide these schemes?

**Comment by xiaofeng11** [comment]
Sorry, these files are belong to CocosStudio project, and CocosStudio is not an open source project.

**Comment by geometrydash** [comment]
Very interesting blog. Alot of blogs I see these days don't really provide anything that I'm interested in, but I'm most definately interested in this one. Just thought that I would post and let you know. [geometry dash lite](http://geometrydash.co/)| [sniper games](http://snipergamesaz.com) |[happy wheels](http://happywheels10.com) | [happy wheels 2](http://happywheels2.co/) |[agario](http://agario0.com)| [fnaf](http://fivenightsatfreddysaz.com)

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
