### ISSUE TITLE
Fails on linking android application.

### ISSUE THREAD

**Issue by chmyaf** [cocos2d/cocos2d-x#15129]
In 3 version from git repository build and run for linux and win32 platforms is correct.

But, build for android:

$ cocos new FirstApp -p com.my.cocos.firstapp -l cpp -d projects
$ cd projects/FirstApp
$ cocos run -p android -j 4
. . .
[armeabi] SharedLibrary  : libcocos2dcpp.so
/home/opt/cocos2d-x/projects/FirstApp/proj.android/../cocos2d/cocos/./base/CCDirector.cpp:981: error: undefined reference to 'cocos2d::network::WebSocket::closeAllConnections()'
collect2: error: ld returned 1 exit status
make: **\* [obj/local/armeabi/libcocos2dcpp.so] Error 1
make: Leaving directory `/home/opt/cocos2d-x/projects/FirstApp/proj.android'

**Comment by perminovVS** [comment]
It method added https://github.com/cocos2d/cocos2d-x/commit/d122784ad4cb997feae8875723983da61bd49fe4

Check cocos\network\Android.mk WebSocket.cpp

**Comment by Obg1** [comment]
I'm having the same issue, the fix is not working

**Comment by perminovVS** [comment]
@Obg1 WebSocket.cpp have closeAllConnections?

**Comment by xiaofeng11** [comment]
The pr https://github.com/cocos2d/cocos2d-x/pull/15135 will fix this issue

**Comment by minggo** [comment]
Can i close this issue?

**Comment by chmyaf** [comment]
@minggo Yes. Thanks!
