### ISSUE TITLE
Request for createWithXML() of RichText

### ISSUE THREAD

**Issue by m-yukio** [cocos2d/cocos2d-x#15131]
- I want to set the default value.
  - color
  - font size
  - font face
- I want to set values (color, size, face, etc) of the font in the A tag.
- I want to extend the hyperlink. For example, the callback can be registered.
  - For example, I want to go to the scene.
- I want to add own tags.

**Comment by zilongshanren** [comment]
@m-yukio 
It's already there in the latest v3 branch, please check... @ricardoquesada  did this, cheers :smile:

**Comment by m-yukio** [comment]
@zilongshanren
sorry, this request is for the latest v3 branch.

**Comment by zilongshanren** [comment]
@ricardoquesada  Thoughts?

**Comment by ricardoquesada** [comment]
yep, we already implemented something like that. Please, take a look at this test case:
https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-tests/Classes/UITest/CocoStudioGUITest/UIRichTextTest/UIRichTextTest.cpp#L438

Search for "createWithXML" in that file. It supports the `<a href>` tag as well.
Closing this issue. Please, reopen it if you think a particular feature is missing. thanks.
