### ISSUE TITLE
error while loading shared libraries: libfmod.so.6 in Debian

### ISSUE THREAD

**Issue by RequiemSouls** [cocos2d/cocos2d-x#15137]
OS: Debian 8
version: cocos2d-x-3.10

> $: unzip cocos2d-x-3.10
> $ : ./build/install-deps-linux.sh
> $:  ./steup.py
> $: source ~/.bashrc
> $: cocos run -s ./tests/ccp-tests/ -p linux

when I build over I got this error:

> /home/zhe/Documents/PoolGame/simulator/linux/MyGame: error while loading shared libraries: libfmod.so.6: cannot open shared object file: No such file or directory
> Error running command, return code: 127.

I did anything I can. 

> cp ./external/linux-specific/fmod/prebuilt/64-bit/libfmodL.so /usr/local/lib/
> cp ./external/linux-specific/fmod/prebuilt/64-bit/libfmod.so /usr/local/lib/
> 
> ln -s /usr/local/lib/libfmod.so /usr/local/lib/libfmod.so.6
> ln -s /usr/local/lib/libfmodL.so /usr/local/lib/libfmod.soL.6

execute install-deps-linux.sh again and again.
but it still error. somebady can help me?

**Comment by madebymozart** [comment]
http://discuss.cocos2d-x.org/t/error-while-building-for-linux-libfmod-so-6/26553/12

Make sure after you copy the files you run ./install-deps-linux.sh again

**Comment by geometrydash** [comment]
Very interesting blog. Alot of blogs I see these days don't really provide anything that I'm interested in, but I'm most definately interested in this one. Just thought that I would post and let you know. [geometry dash](http://geometrydash.co/)| [sniper games](http://snipergamesaz.com) |[happy wheels demo](http://happywheels10.com) | [happy wheels 2](http://happywheels2.co/) |[agario](http://agario0.com)| [five nights at freddy's](http://fivenightsatfreddysaz.com)

**Comment by minggo** [comment]
Can i close this issue?

**Comment by minggo** [comment]
I have the same issue on ubuntu. It is strange why it links to `libfmod.so.6`, coocs2d-x indeed need to link `libfmod.so`, not `libfmod.so.6`. And i searched in my computer, there is not a symbol file named `libfmod.so` links to `libfmod.so.6`. That's what it confused me.

**Comment by damorton** [comment]
Whats the status on this issue? I'm getting 

```
error while loading shared libraries: libfmod.so.6: cannot open shared object file: No such file or directory
```

**Comment by minggo** [comment]
@RequiemSouls i did as you said, and fix the link issue in Ubuntu 16.04. Do you still have problem?

**Comment by alkhimey** [comment]
Another problem, my system does not have ```fmod``` installed at all but ```build/install-deps-linux.sh``` did not even alert me about it. (cocos version 3.13.1)

**Comment by Kingurus** [comment]
hi all,

  I have the same problem as RequiemSouls. On aarch64. I did the same things. it says libfmod.so: error adding symbols: file wrong format

  Please help.

**Comment by f4th4n** [comment]
I fix them by running this command

`sudo ldconfig -v`

**Comment by cirosantilli** [comment]
I needed:

```
cd external/linux-specific/fmod/prebuilt/64-bit
ln -s libfmod.so libfmod.so.6
```

Note that `readelf -a cpp-tests` tells us that the full path to that folder is hard coded in the binary:

     0x000000000000001d (RUNPATH)            Library runpath: [/path/to/git/cocos2d-x/external/linux-specific/fmod/prebuilt

so we need to put `libfmod.so.6` there.

@minggo the file `libfmod.so.6` is still not present inthe prebuilts: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/tree/15149f454f6cf30652ee3df35b3b7fac26c4da28/linux-specific/fmod/prebuilt/64-bit

**Comment by minggo** [comment]
libfmod is downloaded directly by running `build/install-deps-linux.sh`.

**Comment by cirosantilli** [comment]
@minggo I understood why the libmod.so.6 symlink is required: it is because of the SONAME field of the ELF libmod.so file.

Please consider: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/304 to restore it.

**Comment by minggo** [comment]
good to know, thanks

**Comment by drelaptop** [comment]
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/304 have restored libmod.so.6 symlink

since issue have been fixed at latest code. this should be closed.
