### ISSUE TITLE
[cocos2d-x 2.0.3] CCGrabber/CCEGLView issue for Win32

### ISSUE THREAD

**Issue by burutofoz** [cocos2d/cocos2d-x#1517]
Hi...

I'm experiencing issue with my Win32 build when trying to compile the game using Cocos2d-x 2.0.3.

The build process is experiencing exception when:

``` c++
CCGrabber::CCGrabber(void)
    : m_fbo(0)
    , m_oldFBO(0)
{
    memset(m_oldClearColor, 0, sizeof(m_oldClearColor));

    // generate FBO
    glGenFramebuffers(1, &m_fbo); // <-- stops here
}
```

So I looked for a solution in cocos2d-x, I did the following:

> updating my video driver to use Intel's provided driver. My laptop is using Mobile Intel(4) express chipset family
> changing the CCEGLView.cpp for platform/win32 to http://www.cocos2d-x.org/attachments/1220/CCEGLView.cpp

I made it to a successfully build and run process.

**Comment by dumganhar** [comment]
These codes were merged into our latest codes. Thanks.

**Comment by dumganhar** [comment]
Closed since it was fixed.
