### ISSUE TITLE
Windows 10 http request not working

### ISSUE THREAD

**Issue by uxdxdev** [cocos2d/cocos2d-x#15173]
There is an issue with 'HttpRequest' on Windows 10. To get it working I have added a custom header setting `Content-Type: application/x-www-form-urlencoded\r\n` but this does not work with Win32. Removing the custom header works for Win32, Android, Windows8.1 & 8.1 Phone.

> cocos2d::network::HttpRequest\* remoteRequest = new (std::nothrow) cocos2d::network::HttpRequest();
> 
> remoteRequest->setUrl("http://urltowebsite.net/update.php/");
> 
> // Request type is POST
> std::vectorstd::string headers;
> headers.push_back("Content-Type: application/x-www-form-urlencoded\r\n");
> remoteRequest->setHeaders(headers);
> remoteRequest->setRequestType(cocos2d::network::HttpRequest::Type::POST);
> remoteRequest->setResponseCallback(CC_CALLBACK_2(Dao::Read, this));
> remoteRequest->setRequestData(requestString.c_str(), requestString.length());
> 
> cocos2d::network::HttpClient::getInstance()->send(remoteRequest);
> remoteRequest->release();

**Comment by perminovVS** [comment]
try to remove \r\n

**Comment by uxdxdev** [comment]
So the content-type needs to be set explicitly?

**Comment by perminovVS** [comment]
@damorton winrt parse headers string on key and value.
potentially remove \r\n can help you

**Comment by uxdxdev** [comment]
@perminovVS Thanks that did the trick.
