### ISSUE TITLE
Why is there a DEBUG_MODE option wrapping around CMAKE_BUILD_TYPE?

### ISSUE THREAD

**Issue by chaoren** [cocos2d/cocos2d-x#15172]
See here: https://github.com/cocos2d/cocos2d-x/blob/v3/CMakeLists.txt#L98

This is a bit problematic for systems that expect a standard way to configure a CMake project. I.e., `-DCMAKE_BUILD_TYPE=Debug` or `-DCMAKE_BUILD_TYPE=Release`. Is setting `CMAKE_BUILD_TYPE` directly insufficient for this project?

**Comment by chaoren** [comment]
Since the option is already out there, I think wrapping it around `if(NOT CMAKE_BUILD_TYPE)` would be a good idea to maintain backwards compatibility while preventing a manually specified `CMAKE_BUILD_TYPE` from getting overwritten.

**Comment by ricardoquesada** [comment]
fixed https://github.com/cocos2d/cocos2d-x/pull/15186
