### ISSUE TITLE
Load sprites in XCode 7.3 Beta

### ISSUE THREAD

**Issue by zartako** [cocos2d/cocos2d-x#15199]
If I try to load a sprite it fails with this error on the console: 

libpng error: CgBI: unhandled critical chunk. 

Everything works fine when I run it on simulator, only happens when running in device. If it might help, I am using Xcode 7.3 beta and iOS 9.3 beta. Downgrading to Xcode 7.2 solve the problem.

**Comment by slackmoehrle** [comment]
I don't have Xcode 7.3 yet, but I can snag it and try to reproduce this.

**Comment by slackmoehrle** [comment]
XCode 7.3 final comes out today. I will try with this version. Beta 5 seemed to work.

**Comment by rws08** [comment]
I have this problem too. using Xcode 7.3(7D175) and iOS 9.3.

> libpng error: CgBI: unhandled critical chunk
> cocos2d: SpriteFrameCache: couldn't load texture file.

 CCImage.cpp

```
bool Image::initWithPngData(const unsigned char * data, ssize_t dataLen){
...
 png_read_info(png_ptr, info_ptr); // problem code
...
}
```

**Comment by secredut** [comment]
I also have same problem with Xcode 7.3 and iOS 9.3.

**Comment by slackmoehrle** [comment]
Thanks. I am downloading the latest XCode 7.3 build. Takes me quite some time.

**Comment by slackmoehrle** [comment]
set:
Remove Text Metadata From PNG Files = NO.

**Comment by secredut** [comment]
Thanks! It works fine :)

**Comment by rws08** [comment]
Thanks!

**Comment by wengxianxun** [comment]
i set:
Remove Text Metadata From PNG Files = NO.

but position is wrong

**Comment by vellozo** [comment]
The position is wrong only in my iPhone (5C). In the simulator is fine. How to fix that? I'm using XCode 7.3.1 and before it works in both "devices".

**Comment by rws08** [comment]
![png](https://cloud.githubusercontent.com/assets/7792240/15449114/8836ffa8-1faf-11e6-844c-2b63cc56d495.png)

**Comment by slackmoehrle** [comment]
@vellozo This was answered above by myself and below by @rws08

**Comment by ghost** [comment]
IT DOESN'T WORK

**Comment by slackmoehrle** [comment]
It does work, there are so many documented questions about it. Can you show your build settings and errors?

**Comment by xbw12138** [comment]
thanks ！ it's very cool

**Comment by onlycxue** [comment]
thanks !
