### ISSUE TITLE
help for add cocos2dx framework source to vs2015 project

### ISSUE THREAD

**Issue by rosone** [cocos2d/cocos2d-x#15212]
I'm new to c++.

I need change some of the cocos's code, so I want to rebuilt win32 sln in my vs2015 on windows 2008 server, however I built coco's sln successfully after my code updated,

but when I run my project, there is a lot of problem,

so I want to include cocos2dx source code to my project, what should I do?

I've tried add libcocos2d libSpine libbox2d and other 2 proejects that the libcocos2d refered, but the problem is same.

**Comment by slackmoehrle** [comment]
Have you been through this: http://cocos2d-x.org/docs/installation/G/index.html

**Comment by rosone** [comment]
yes, completely follow above url. but after I run my projects there are a lot of small things wrong, it worked correct before, like: setViewName(view), I can't read view string.

**Comment by rosone** [comment]
after 2 weeks struggle, I realized that, I created the coco project with PREBUILD library, then after I change source project it won't affect the library, so I get various funny errors, I download the latest coco studio again, when I create new project, it shows the option: prebuilt or source code, so I create with source code projects, then I can run it successfully.

**Comment by rosone** [comment]
after 2 weeks struggle, I realized that, I created the coco project with PREBUILD library, then after I change source project it won't affect the library, so I get various funny errors, I download the latest coco studio again, when I create new project, it shows the option: prebuilt or source code, so I create with source code projects, then I can run it successfully.
