### ISSUE TITLE
Error when having a class named Game in Win32

### ISSUE THREAD

**Issue by pyrosphere** [cocos2d/cocos2d-x#15221]
I have a class named `Game`in my project. It has worked on all platforms but now added a win32 project which throws the error: "Game is ambiguous".

It seems to be caused by the line 162 `friend class Game;` in [CCProperties.h](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/CCProperties.h#L162) which, as far as I can tell, doesn't do anything at all. I've commented this line and now it works.

Should this line be removed from cocos2d-x or am I failing to see something?

**Comment by minggo** [comment]
I am not familiar with CCProperties.h, @ricardoquesada do you know it?

**Comment by ricardoquesada** [comment]
bug.
