### ISSUE TITLE
cocosstudio一个场景中，多个相同节点，使用不同的嵌套动画，无法完全播放

### ISSUE THREAD

**Issue by wulei** [cocos2d/cocos2d-x#15230]
如题，我在cocosstudio中，创建了多个相同的node节点，绑定了相同的csd文件，但是在动画中嵌套播放了不同的嵌套动画（NoLoopAction）

播放出现了问题

**Comment by wulei** [comment]
补充一下，原来使用下面版本，是没问题的：
cocos2dx：3.6
cocosstudio：2.3.1.2

有问题的使用版本如下：
cocos2dx：3.10
cocosstudio：3.10

**Comment by wulei** [comment]
@xiaofeng11 
我跟了一下代码，貌似问题出在
相同的
第一个node innerActiontimeline 返回的是nullptr，就没有走完onEnter
如果是多个，为什么只有最后一个能获取？
所以相同的多个只有最后一个能播放出嵌套动画

void InnerActionFrame::onEnter(Frame *nextFrame, int currentFrameIndex)
{
    if (_node == nullptr)
    {
        return;
    }

```
auto innerActiontimeline = static_cast<ActionTimeline*>(_node->getActionByTag(_node->getTag()));
```

**Comment by geron-cn** [comment]
@wulei 这个问题已经修复， 参考这个pr：
https://github.com/cocos2d/cocos2d-x/pull/14888

**Comment by wulei** [comment]
@geron-cn fixed it！谢谢~
