### ISSUE TITLE
cocos run -p android fails with dlopen failed: cannot locate symbol "atof" referenced by "libcocos2djs.so"

### ISSUE THREAD

**Issue by guivanrv** [cocos2d/cocos2d-x#15234]
All fresh clean project created with 'cocos create' fails after 
'cocos run -p android'. adb logcat returned log similar to 
[https://github.com/cocos2d/cocos2d-js/issues/1288](https://github.com/cocos2d/cocos2d-js/issues/1288)

```
E/AndroidRuntime(29440): FATAL EXCEPTION: main
E/AndroidRuntime(29440): Process: com.symplestudios.penguinwars, PID: 29440
E/AndroidRuntime(29440): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "atof" referenced by "libcocos2djs.so"...
E/AndroidRuntime(29440): at java.lang.Runtime.loadLibrary(Runtime.java:364)
E/AndroidRuntime(29440): at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(29440): at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:85)
E/AndroidRuntime(29440): at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:99)
E/AndroidRuntime(29440): at android.app.Activity.performCreate(Activity.java:5600)
```

Using help from [http://discuss.cocos2d-x.org/t/need-help-android-app-crash-on-launch/18908](http://discuss.cocos2d-x.org/t/need-help-android-app-crash-on-launch/18908) I've added the implementations of missing methods (atoi, rand and srand) to my AppDelegate.cpp and now the empty project runs as it should (shows cocos logo on device)

I've used JS as language for generation, ndk r10 and latest sdk. In case someone else will need it, here's the code that helped

```
static u_long myNextRandom = 1;
double atof(const char *nptr)
{
    return (strtod(nptr, NULL));
}

int rand(void)
{
    return (int)((myNextRandom = (1103515245 * myNextRandom) + 12345) % ((u_long)RAND_MAX + 1));
}

void srand(u_int seed)
{
    myNextRandom = seed;
}
```

Device is Xiaomi mi3, android version is 4.4.4, cocos version 3.10. This nasty workaround seems to be a wrong way to solve the problem. Can someone look into it, please? Definitely I'm not the only one experiencing this kind of issues

**Comment by zilongshanren** [comment]
@guivanrv 
I will check this issue tomorrow, thanks for reporting.

**Comment by 4ian** [comment]
@zilongshanren Any news on that issue? :)
Note that an alternative solution is to add:

```
APP_PLATFORM := android-9
```

inside `frameworks/runtime-src/proj.android/jni/Application.mk`. This also dismiss a warning, displayed when calling `cocos run -p android`, telling that APP_PLATFORM is too high:

```
Android NDK: WARNING: APP_PLATFORM android-21 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml
```

**Comment by minggo** [comment]
@guivanrv Did you mean `cocos run -p android` will failed with JS?

**Comment by tungnt11** [comment]
@minggo and @zilongshanren : Hi, I also crashes when I run app with error : 
E/AndroidRuntime(11959): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libcocos2djs.so"...
E/AndroidRuntime(11959):    at java.lang.Runtime.loadLibrary(Runtime.java:361)
 E/AndroidRuntime(11959):   at java.lang.System.loadLibrary(System.java:525)

I'm using cocos 3.9, NDK R10e and target SDK is 23 (Android 6.0). I want use Android 6.0 because I use android-support-v7-appcompat for new api of Google SignIn .
Can you help me fix this issue? 
Thank you!

**Comment by minggo** [comment]
@dimaria11 I will have a try with latest codes.

**Comment by minggo** [comment]
@dimaria11 did you use jsb too?

**Comment by tungnt11** [comment]
@minggo : Yes, I used jsb. I just change target Android down to 5.1.1. It still crashes. :(.

**Comment by minggo** [comment]
> I just change target Android down to 5.1.1. It still crashes. :(.

How did you change target?

**Comment by tungnt11** [comment]
I use Eclipse: Android -> change Project Build Target to: Android 5.1.1. I use SDKBox.

**Comment by minggo** [comment]
I can run js-tests with Android 5.0(21), i will try Android 6.0

**Comment by tungnt11** [comment]
Before I integrate SDKBox, my app run fine. Then, I integrate SDKBox with: JSBinding, Jni: Android.mk + sdkJni. I recompile to generate new libcocos2djs.so and run -> app crashes. This app run with CocosJS v 3.9.
With other app run with CocosJS v3.8.1, I still integrate SDKBox normal with Android 6.0.

**Comment by minggo** [comment]
@dimaria11  I can run with Android 6.0 too. I use latest codes. I don't use SDKBox. I think you should ask SDKBox guys to take a look.
