### ISSUE TITLE
release application in vs2015 to win7 msvcr110.dll is missing dll

### ISSUE THREAD

**Issue by rosone** [cocos2d/cocos2d-x#15243]
for debug version, missing MSVCP140D.DLL

for relase verson, missing MSVCR110.DLL

could any body tell me how to release coco app in vs 2015?

I've set all build settings to MTd for debug, and MT for release, and use of MFC: use static MFC.

and tried c++ redistributable for vs 2015/2012/2010/2008, no any luck.

**Comment by minggo** [comment]
May be @stammen have some idea.

**Comment by stammen** [comment]
@rosone Did you try installing https://www.microsoft.com/en-us/download/details.aspx?id=30679#?

**Comment by minggo** [comment]
@rosone Have you resolved your problem? If so please close this issue. Thanks.

**Comment by larsven** [comment]
Check which VS2015 Update version you have compiled with (for example VS2015 Update 2) and use the corresponding redistributable file.

**Comment by rh101** [comment]
@minggo This issue should be closed because it's not related to Cocos2d-x, but a matter of installing the Microsoft Visual C++ Redistributable. For the sake of anyone else who needs it, it can be found [here](https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads)
