### ISSUE TITLE
规范头文件

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#15250]
目前 cocos2d-x 的头文件有这些问题：
## 1 搜索路径太多

以 Windows 为例，根据 cocos2d-x/cocos/2d/cocos2d_headers.props 需要搜索的路径有（不包含外部依赖）：

> $(EngineRoot)cocos
> $(EngineRoot)cocos\editor-support
> $(EngineRoot)cocos\platform
> $(EngineRoot)cocos\platform\desktop

虽然这样内部使用没有问题，但是影响其他项目中使用 cocos 头文件。

完全可以 **只搜索 `$(EngineRoot)cocos** 嘛。其他的就在这个路径上的相对路径进行包含就好了。
单一搜索路径的好处是便于设置编译：比如我要弄一个 Lua 模块，依赖 cocos 的 C++ 代码。我只要设置一个搜索路径就好了。
## 2 没有区分内部和公开头文件

目前没有独立的 include 目录，在代码变迁过程中难免出现有人不小心直接 `#include "abc.h"` 而不是用 `#include "relative/path/to/abc.h"`。

比如 `cocos/scripting/lua-bindings/manual/CCLuaBridge.h` 中就直接这样包含的： `#include "CCLuaEngine.h"` 这样导致第三方工程需要引用 `#include "scripting/lua-bindings/manual/CCLuaBridge.h"` 的时候，不得不把 `cocos/scripting/lua-bindings/manual` 添加到搜索路径里面。这样有加重了前面第1点。

这里的问题就是，没有区分内部头文件和导出的外部头文件。

如果`scripting/lua-bindings/manual/CCLuaEngine.h` 是公开 API，那么就应`scripting/lua-bindings/manual/CCLuaBridge.h`该使用`#include "scripting/lua-bindings/manual/CCLuaEngine.h"`。
如果 CCLuaEngine.h 不是公开的，那么就不该在头文件中引用它，而应该在 cpp 文件中引用。当然如果`CCLuaBridge.h` 也不是公开的，那么可以另当别论。

问题是，现在没有办法通过路径知道到底一个头文件是不是公开的 API。

所以需要 **专门建一个 include 目录放公开的 API 的头文件**。
## 3  cocos2d-x 内部一股脑地 #include "cocos2d.h"

现在 cocos2d-x 内部，只要动一下头文件，几乎是导致整个 cocos 重新编译。元凶就是 `#include "cocos2d.h"`。

解决办法就是 **用啥包含啥，不用别包含** 。

`cocos2d.h` 存在的意义就是提供给外部使用，帮助那些不太熟悉 cocos 的开发者，因为他们可能不太清楚，比如要用 Node 该使用哪个头文件。但是严谨的开发者在使用 cocos2d 的时候，不应该使用 `#incude "cocos2d.h"` 这样的方式。更不要说 cocos2d 内部代码了。

更糟糕的是，由于前面讲到的 第一二点 的关系，目前 cocos2d-x 的的头文件是在逼开发者在游戏项目中使用 `#incude "cocos2d.h"` 。
## 4 一个头文件里面包含太多内容

比如我想只使用 `platform/CCFileUtils.h` 结果：

> In file included from cocos/platform/CCFileUtils.h:33:
> In file included from cocos/base/ccTypes.h:36:
> In file included from cocos/platform/CCGL.h:33:
> cocos/platform/mac/CCGL-mac.h:32:9: fatal error: 'OpenGL/gl.h' file not found

原因就是 ccTypes.h 定义的和 OpenGL 相关的类型，而这些类型又依赖于 CCGL.h ，进一步要求依赖于 'OpenGL/gl.h'。 于是乎 一个 CCFileUtils 就依赖与 OpenGL 了。

**Comment by zilongshanren** [comment]
头文件的规范确实很有必要，不过这个修改影响也很大。只能慢慢一点点来完善。楼主可以先提PR，不过尽量不要修改目录结构。

**Comment by xpol** [comment]
不改目录的话，1 和 3 可以实现，4 的话需要将 ccTypes.h 这样的头文件分成多个小文件，然后把引用的地方改成引用那些小的头文件。

**Comment by xpol** [comment]
随便吐槽一下：

PR 到是没问题，就是不知道猴年马月能处理或者合并啊，这样很影响提 PR 的积极性啊。

去年的 cocos2d-x 相关的 PR 有将近20个没有处理：

https://github.com/cocos2d/cocos2d-x/pulls/xpol
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pulls/xpol
https://github.com/cocos2d/cocos2d-console/pulls/xpol
https://github.com/cocos2d/bindings-generator/pulls/xpol

有些连零回复都没有消灭。倒不是要求每个都能合并，不合适的 close 就行啊。

**Comment by zilongshanren** [comment]
@xpol 唉。。。 一个人处理不过来呀。。。

**Comment by xpol** [comment]
雇佣我嘛，远程 :smile: 。

**Comment by zilongshanren** [comment]
@xpol  我不是老板。。 我给你合了bindings的PR，还有一个生成lua ctags的，你回复一下吧。怎么用你那个patch来生成tags?

**Comment by xpol** [comment]
#15435 removes include of `cocos2d.h`.
