### ISSUE TITLE
getRandomObject() issue in Vector

### ISSUE THREAD

**Issue by wkdtjsgur100** [cocos2d/cocos2d-x#15270]
My develop environment is consist of eclipse, cocos2d-x 3.10, windows 10 64bit and
my android build target is Android 6.0

I want to use getRandomObject() in cocos2d::Vector class.
It works well on win32-platform, but the same code doesn't work in android-platform.
so I track my class's member methods. And figure out rand() function cause this problem.

getRandomObject function in CCVector is:

T getRandomObject() const
    {
        if (!_data.empty())
        {
            ssize_t randIdx = rand() % _data.size();
            return *(_data.begin() + randIdx);
        }
        return nullptr;
    }

In addition, it can be caused that it would be non-complete random object.

so I recommend to change a function with using a RandomHelper class in cocos2d-x

or using a uniform_real_distribution in std namespace.

like this:

T getRandomObject() const
    {
        if (!_data.empty())
        {
            ssize_t randIdx = RandomHelper:: random_int(0,_data.size());
            return *(_data.begin() + randIdx);
        }
        return nullptr;
    }

**Comment by dumganhar** [comment]
Good point, could you please send a Pull Request for this? Thanks.

**Comment by wkdtjsgur100** [comment]
I sent a pull request.. please check :)

**Comment by gestern** [comment]
Here is better to use a more elegant solution `random(0,_data.size());` than `RandomHelper:: random_int(0,_data.size());` Because random is:

``` cpp
template<typename T>
inline T random(T min, T max) {
    return RandomHelper::random_int<T>(min, max);
}

template<>
inline float random(float min, float max) {
    return RandomHelper::random_real(min, max);
}
...
```
