### ISSUE TITLE
How to clear or delete UserDefault

### ISSUE THREAD

**Issue by pulidoEuge** [cocos2d/cocos2d-x#15280]
I simulate my app in both IOS and MAC. I can easily delete saved UserDefault data on IOS but i dont know how to do it in MAC simulator. I can't also find the UserDefault.xml in /Library/Caches or in /Documents..

I also tried clean then building the app but no avail.. Pls help

**Comment by slackmoehrle** [comment]
UserDefault.xml lives where `getWriteablePath()` returns. Take a look where this is using the debugger and then navigate to it on your file system.

**Comment by minggo** [comment]
@juuj Have you resolved you issue? I will  close this issue if it is resolved.

**Comment by pulidoEuge** [comment]
Not yet. But ive made a remedy. You can close it already. Thanks
