### ISSUE TITLE
Older Coco Studio binaries are crashing in v3.10

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#15288]
v3.10. Tried using source and also creating a new project using Cocos Launcher.

This repo: https://github.com/chukong/CocosStudioSamples

clone it and try and build the iOS project. It will run and you will crash at the first `.csb` it tries to load.

Users are complaining about this and also starting to experience this in their own projects. Older Cocos Studio files are not working in newer Cocos2d-x projects. 

Some users are reporting this starts in v3.4 and some users are reporting going back to v3.7 and things work as expected again.

@pandamicro @linshun

**Comment by slackmoehrle** [comment]
@xiaofeng11 has had a thread here: https://github.com/cocos2d/cocos2d-x/issues/15075 and there is no resolution. He is recommending updating drivers for an ATI card, which OS X users cannot do (under normal use circumstances and assuming their Mac has an ATI card even), as Cocos Studio needs hardware acceleration.

I'd say this is a known issue and we need to look into a proper fix as user complaints are coming in.

**Comment by pabitrapadhy** [comment]
It crashes in Android as well.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
