### ISSUE TITLE
cocos2dx-js v3.6 scrollview 里面加了一个 sclippingnode 裁剪的node，滑出显示区域还是显示。

### ISSUE THREAD

**Issue by Super-Man** [cocos2d/cocos2d-x#15308]
项目是cocos2dx-js v3.6版本， 在scrollview 里面 addchild 一个 clippingNode裁剪出得node，滑动scrollview的时候 这个裁剪的node显示有问题..！ 我知道最新版本的cocos 是解决的这个问题，但是我们项目不能换新引擎。 我想问 主要修改了哪些地方... @zilongshanren

**Comment by zilongshanren** [comment]
@Super-Man  https://github.com/cocos2d/cocos2d-x/pull/14470
主要是修改了clipping node.cpp里面的两个静态变量，UILayout需要和clippingNode共用那两个变量。
