### ISSUE TITLE
Compile errors with APP_CPPFLAGS := -std=c++14 and APP_STL := c++_static on Android

### ISSUE THREAD

**Issue by ryukbk** [cocos2d/cocos2d-x#15310]
With APP_CPPFLAGS := -std=c++14 with APP_STL := c++_static in Application.mk for x86 Android build, I got the following errors.

`Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libcxx/include/tuple:290:102: error: invalid initialization of reference of type 'cocos2d::AsyncTaskPool::ThreadTasks::ThreadTasks()::<lambda()>&' from expression of type 'const cocos2d::AsyncTaskPool::ThreadTasks::ThreadTasks()::<lambda()>'
     _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_AFTER_CXX11       _Hp& get()       _NOEXCEPT {return value;}
                                                                                                      ^`

With -std=c++11, c++_static seems just fine.

**Comment by minggo** [comment]
We haven't decided to use c++14.
