### ISSUE TITLE
cocos compile -p mac fails with #include "SimpleAudioEngine.h"  

### ISSUE THREAD

**Issue by anagorko** [cocos2d/cocos2d-x#15323]
I needed to add

```
                "$(SRCROOT)/../cocos2d/cocos/audio/include/"
```

to HEADER_SEARCH_PATHS in proj.ios_mac/*.xcodeproj/project.pbxproj to get it working.

I see that this path is included in CMakeLists.txt in the project root directory.

**Comment by zilongshanren** [comment]
@anagorko  thanks. I will fix this issue later.

**Comment by xpol** [comment]
@anagorko 
Can you attach full error log please?

**Comment by zilongshanren** [comment]
@anagorko 

We have cleaned up our header file search path, now all the include should relative to `$engineRoot/cocos` .

~~So please change `#include "SimpleAudioEngine.h" to`#include "audio/include/SimpleAudioEngine.h" "--``~~

I will fix the back compatibility issue.

Thanks.

**Comment by zilongshanren** [comment]
@anagorko  please check the latest V3 head, it should be fixed now.
