### ISSUE TITLE
出了个问题,请帮忙看一下

### ISSUE THREAD

**Issue by songwentong** [cocos2d/cocos2d-x#15324]
详情请看图片

 raise ValueError, 'unknown locale: %s' % locale name
![screen shot 2016-03-28 at 9 52 34 am](https://cloud.githubusercontent.com/assets/561644/14069322/d50acb3a-f4ca-11e5-9bdd-f91c70e5e416.png)

**Comment by zilongshanren** [comment]
@swtlovewtt  你的.bash_profile或者.zshrc文件里面的locale不正确, 改成en_US.UTF-8试试？

**Comment by zilongshanren** [comment]
这种问题希望去论坛提问，谢谢。
