### ISSUE TITLE
Compiling for android with ndk-r11b fails

### ISSUE THREAD

**Issue by anagorko** [cocos2d/cocos2d-x#15320]
It fails with empty cpp  project. The NDK_TOOLCHAIN_VERSION should be 4.9. Here is the relevant error log:

Building native...
NDK build mode: debug
Parse NDK version from file /Users/Monika/Library/Android/ndk-r11b/RELEASE.TXT failed.
NDK_TOOLCHAIN_VERSION: 4.8
running: '/Users/Monika/Library/Android/ndk-r11b/ndk-build -C /Users/Monika/kinf/Cocos/TestGame/proj.android -j4 NDK_MODULE_PATH=/Users/Monika/kinf/Cocos/TestGame/proj.android/../cocos2d:/Users/Monika/kinf/Cocos/TestGame/proj.android/../cocos2d/cocos:/Users/Monika/kinf/Cocos/TestGame/proj.android/../cocos2d/external NDK_TOOLCHAIN_VERSION=4.8 NDK_DEBUG=1'

Android NDK: WARNING: APP_PLATFORM android-23 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml  
[armeabi] Compile++      : cocostudio_static <= WidgetReader.cpp
make: /Users/Monika/Library/Android/ndk-r11b/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++: No such file or directory
make: **\* [obj/local/armeabi/objs-debug/cocostudio_static/WidgetReader/WidgetReader.o] Error 1
make: **\* Waiting for unfinished jobs....
Error running command, return code: 2.

**Comment by dimbonix** [comment]
As an adhoc, in the root directory of ndk you can create file RELEASE.TXT and write to it text(without quotes): "r11b (64-bit)" or "r11b (32-bit)" depends on what version you are using. It works for me, but i dont know why ndk requires that file. I have found RELEASE.TXT file in previous ndk versions, but ndk11b doesnt contains it.

**Comment by anagorko** [comment]
I downgraded to r10e, which also solves the problem.

I confirm that your workaround fixes the problem for me with ndk-r11b. Thanks!

**Comment by zilongshanren** [comment]
@anagorko  maybe it's a bug related NDK...

**Comment by minggo** [comment]
@anagorko Did you use `cocos` to compile the android project?

**Comment by anagorko** [comment]
I compiled it from command line with "cocos compile"

**Comment by minggo** [comment]
I think it is fixed in latest code, could you please have a try?

**Comment by anagorko** [comment]
I confirm that it is indeed fixed. Good work!

**Comment by klodha** [comment]
I downloaded cocos2d-x 3.10 today. After that spent hours trying to setup it and each time faced error with NDK. Earlier I was using NDK r8c, but then downloaded the current version from Android website. Version which I got was r11c. I was looking for the version mentioned on cocos2d-x setup guide, but couldn't find. 

Then cpp-tests step kept giving strange errors related to missing files etc in NDK and I was about to give for the day, when I found this thread. 

I found @dibondi's suggestion of creating a README.TXT file in NDK root folder works!  Not sure why NDK needs a read me file to compile (not an seasonal android / c++ developer) but overall creating this file in root with string `rc11 (64-bit)` without any quote worked like a charm and compilation is working now.

@dibondi thanks for sharing this useful workaround! Not sure if fix is already included in stable download from cocos2d-x website, but if it is, then at least for me it didn't work.

**Comment by vkumar79** [comment]
@dibondi :+1: thanks man

**Comment by elecstudent** [comment]
Hi there,
I am trying to run ndk for tess-two but I am getting following error  regardless of my ndk version. Any idea how can I fix that?
"
C:\Users\Mcodes\tess-two-master\tess-two>ndk-build
[armeabi] Compile thumb : jpgt <= jaricom.c
error: error opening './obj/local/armeabi/objs/jpgt/jaricom.o.d': Error opening
output file './obj/local/armeabi/objs/jpgt/jaricom.o.d': No such file or
directory
1 error generated.
make.exe: *** [obj/local/armeabi/objs/jpgt/jaricom.o] Error 1
"
