### ISSUE TITLE
怪不得 -x 发展这么多年了，每个公司都有一套的版本，但就是不回馈给社区

### ISSUE THREAD

**Issue by jareguo** [cocos2d/cocos2d-x#15327]
因为太难 clone 了，我从来就没成功过，这个项目如果还重视**墙内**用户，请把 clone 好的版本放到**墙内**网盘里让大家下载，否则想提 PR 都没办法。

**Comment by litefeel** [comment]
使用代理会好很多

**Comment by leejuen** [comment]
...这都能吐槽啊

**Comment by zilongshanren** [comment]
@jareguo  这个问题还是关了吧。。 可以去论坛吐槽。。

**Comment by jareguo** [comment]
> 这个问题还是关了吧。。 可以去论坛吐槽。。

嗯，我去论坛发发牢骚，希望 -x 越发展越好。
