### ISSUE TITLE
PageView addEventListener() doesn't work in Android

### ISSUE THREAD

**Issue by lifzgreat** [cocos2d/cocos2d-x#15325]
This works in web but not in Android (posted [here](https://github.com/cocos2d/cocos2d-js/issues/1827) but realized that was deprecated). It's possible that it's not necessarily web vs Android but mouse vs touch.

``` javascript
ctor: function () {
    var pageView = new ccui.PageView();

    for (var i = 0; i < 3; ++i) {
        var layout = new ccui.Layout();
        pageView.addPage(layout);
    }

    pageView.addEventListener(this.pageViewScrolled, this);
},

pageViewScrolled: function(sender, type) {
    cc.log("pageView scrolled.");
}
```

**Comment by zilongshanren** [comment]
@lifzgreat  The latest v3 has already fixed this issue.

**Comment by lifzgreat** [comment]
Is it available on cocos2d-x.org? I had the latest as of not long ago! Or do I need to clone the repo?

**Comment by zilongshanren** [comment]
@lifzgreat  no, it's not on cocos2d-x.org, you should clone the repo if you want to test it now.

**Comment by lifzgreat** [comment]
Ok, I will test it. I will respond with findings here. Thanks for the quick response!

When does the main site get updated with the latest v3 branch?

**Comment by zilongshanren** [comment]
@lifzgreat  It will happen in the early April, but I can't promise the exactly release date, lots tests need to be done before we officially announce the release to the public.

**Comment by lifzgreat** [comment]
Thanks so much! I am cloning now...wish me luck :)

**Comment by lifzgreat** [comment]
Ok, I just cloned the newest v3 branch and ran `coocs run -p android` against the existing project. The PageView's event listener didn't fire. I'm using a PageView from Cocos Studio's UI elements and it works great on web but just not in Android. I can try manually creating the PageView in code again like the code in the initial bug report above.

**Comment by zilongshanren** [comment]
@lifzgreat  Which project do you test? I have tested js-tests and it works fine.

**Comment by lifzgreat** [comment]
I ran it against my personal project. I will test js-tests on Android again to see if it works.

Do I _have_ to create the PageView in code or can I use Cocos Studio?

**Comment by zilongshanren** [comment]
@lifzgreat  I think both ways should be working... either in code or with CocoStudio.

**Comment by lifzgreat** [comment]
Yes sir, it works perfectly in js-tests. I did notice a couple differences:

``` javascript
var root = this._parseUIFile("ccs-res/cocosui/UIEditorTest/UIPageView/pageview_1.json");
var pageView =ccui.helper.seekWidgetByName(root, "PageView_1269");
```

I've always done:

``` javascript
var root = ccs.load(res.Scene_json);
pageView = root.node.getChildByName("PageView");
```

Also, js-test has a pageview.json file that looks vastly different than the one that was exported from Cocos Studio for me.

**Comment by zilongshanren** [comment]
@lifzgreat 
The search method you used should working, the code in js-tests might be more time efficient.
I think the core reason doesn't in here, nor does the pageview.json file..

Maybe you should pay attention to the page turn event callback.

**Comment by lifzgreat** [comment]
The callback is incredibly simple so this can't be it, right?

``` javascript
ctor: function() {
    pageView.addEventListener(this.pageScrolled, this);
},
pageScrolled: function(sender, type) {
    cc.log("PageView scrolled.");
}
```

I'm going to remove the /frameworks/runtime-src/proj.android folder and let it compile everything fresh. Maybe the new v3 I cloned isn't compiling certain pieces because they already existed from an old compile.

**Comment by zilongshanren** [comment]
@lifzgreat 
I suggest you create a new project with `cocos new -l js` and add your code to the newly created project.

I don't quite understand how you are using the v3 branch code to do the test...

**Comment by lifzgreat** [comment]
Ok, I will do that if this doesn't work. Just for the sake of information, I moved my old cocos2d-x-3.10 folder to cocos2d-x-3.10_OLD and cloned the v3 branch into cocos2d-x-3.10. So it's using all of the new branch to compile. But I will do what you suggested if this next compile doesn't work :)

**Comment by lifzgreat** [comment]
As you suggested, I created a new project and imported my code into the newly created project and it worked perfectly.

Thanks so much for the quick responses! I can't wait for the new cocos to come out to the public. What a fantastic framework.

**Comment by zilongshanren** [comment]
@lifzgreat  :smile:  Should I close this issue now?

**Comment by lifzgreat** [comment]
Yes sir! Thanks again :)
