### ISSUE TITLE
ConnectWaitLayer 导致crash 的bug

### ISSUE THREAD

**Issue by xzben** [cocos2d/cocos2d-x#15329]
在ConnectWaitLayer 中
`_imageShine = new Image();
    _imageShine->initWithImageData(__shinePngData, sizeof(__shinePngData));
    Texture2D* textureShine = Director::getInstance()->getTextureCache()->addImage(_imageShine, "shine");
`
这里new 的Image 在 
`void VolatileTextureMgr::addImage(Texture2D *tt, Image *image)
{
    VolatileTexture *vt = findVolotileTexture(tt);
    image->retain();
    vt->_uiImage = image;
    vt->_cashedImageType = VolatileTexture::kImage;
}
`
中Image 可能被retain，然后在ConnectWaitLayer 里面却没有走  release 的流程直接走的是
`ConnectWaitLayer::~ConnectWaitLayer()
{
    CC_SAFE_DELETE(_imagebg);
    CC_SAFE_DELETE(_imageplay);
    CC_SAFE_DELETE(_imageShine);
}
`
这样之后后面 release 到了这写Image 就直接crash了，解决方案
`
ConnectWaitLayer::~ConnectWaitLayer()
{
    CC_SAFE_RELEASE(_imagebg);
    CC_SAFE_RELEASE(_imageplay);
    CC_SAFE_RELEASE(_imageShine);
}
`

**Comment by minggo** [comment]
Yep, cocos2d-x use reference count to control object life cycle. Image is a special case, may be we should add `Image::create()`?

**Comment by xzben** [comment]
Only need to replace CC_SAFE_DELETE to CC_SAFE_RELEASE can solve

**Comment by minggo** [comment]
ConnectWaitLayer is your own class, so engine can not do anything helpful, right?
