### ISSUE TITLE
Node:Physics crashed on first test case

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15331]
`cpp-tests` crashed on iPad4 iOS 9.0.1 and worked ok on:
- Mac OS X
- iPhone4 iOS 6.1.2

`lua-tests` crashed on Windows 10.

**Comment by ricardoquesada** [comment]
which project did you try? win32 or universal?

When I tested it, it worked ok.  mmmm... perhaps the new libraries broke it?

**Comment by minggo** [comment]
The QA team reported the bug. I will ask them to give more detail information.

**Comment by chengshan1** [comment]
cpp-tests project crashed on iPad4 iOS 9.0.1
lua-tests project crashed on Windows10(win32)

**Comment by ricardoquesada** [comment]
@chengshan1 could you tell me which test? The more information you add, the easier it is going to reproduce it and fix it. Thanks!

**Comment by minggo** [comment]
@ricardoquesada I think the tile tells which test case

**Comment by chengshan1** [comment]
cpp-tests  Node:Physics test case
lua-tests   PhysicsTest   test case

**Comment by ricardoquesada** [comment]
everything seems to be working on for me on iPhone... (cpp-tests and lua-tests).
 I'll try it on iPad Air

**Comment by chengshan1** [comment]
You can try it on Windows。

**Comment by ricardoquesada** [comment]
@chengshan1 yes, sure. ill do that

**Comment by ricardoquesada** [comment]
More tests that I did:

iPhone 6S with iOS 9.3: Everything worked Ok
iPad Air with iOS 8.3: Everything worked Ok.
Testing windows now...

**Comment by ricardoquesada** [comment]
I confirm that it crashes on win32.
It could be something else, but it seems that the version pushed by @xiaofeng11 broke it :-(
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/commits/v3/chipmunk/prebuilt/win32/release-lib/libchipmunk-2015.lib

**Comment by minggo** [comment]
@xiaofeng11 Could you please take a look?

**Comment by xiaofeng11** [comment]
OK, I'll check it.

**Comment by xiaofeng11** [comment]
@ricardoquesada Studio project is canceled, so export won't need any more, I will rollback chipmunk to old version to solve this issue, I see Win10 & WindowsPhone version have been update after I commit export change to src lib, shall I rollback these 2 lib either?

**Comment by ricardoquesada** [comment]
@xiaofeng11 
I wouldn't know what to say because I don't know why they are crashing.
If the new win10 & winphone libs don't crash, then I think it is safe to use them. No need to roll them back

**Comment by xiaofeng11** [comment]
@ricardoquesada  The crash is because in follow function, Assert will be triggered. Seems it has nothing related with export function, but I can not find the reason, maybe compile param related. I'll check does win10 project crash now.

cpVect cpCircleShapeGetOffset(const cpShape *shape)
{
    cpAssertHard(shape->klass == &cpCircleShapeClass, "Shape is not a circle shape.");
    return ((cpCircleShape *)shape)->c;
}

**Comment by xiaofeng11** [comment]
Win10 pass the test, I'll rollback src and win32 libs

**Comment by ricardoquesada** [comment]
ok. great. thanks

**Comment by minggo** [comment]
The lib is reverted.
