### ISSUE TITLE
Quake like console

### ISSUE THREAD

**Issue by if1live** [cocos2d/cocos2d-x#1534]
Hello. I am a devolper who use cocos2d-x as hobby.
I make a devel console like quake console.

I use GLConsole(http://www.robots.ox.ac.uk/~gsibley/GLConsole/). It is LGPL lincese. and GLConsole include tinyxml(zlib). I also use a font png file from google image search(but I can't find original link)

If third-party license is clear and you want dev console feature, I will modify and give code. (Current code is not cocos2d-x coding style and some comment is not english)

current code link : https://github.com/if1live/cocos2d-x/tree/sora
## Sample release build

https://docs.google.com/open?id=0B5whqvrskT5eWU5xTXlSRmJCZzA
1. execute
2. press `, (~)
3. input "echo_cmd XXX XXX XXXX". I make only echo_cmd function

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2668
