### ISSUE TITLE
Update OpenSSL for libcurl

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15359]
Some developers met the issue on Android: http://discuss.cocos2d-x.org/t/openssl-problem-again/28270. I think we should update it in v3.11, and it seems there is pull request in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/80.

**Comment by abhinavpachauri** [comment]
Can you please let us know when is the scheduled date of release of 3.11 with the above fix?

**Comment by minggo** [comment]
We planned to release v3.11 on Apr.26.

**Comment by minggo** [comment]
@zilongshanren What's the progress of this issue?

**Comment by zilongshanren** [comment]
@minggo  it's done
