### ISSUE TITLE
[JSB]Physics demos have different effects as before

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15350]
I will ask QA team to give more detail information.

**Comment by ricardoquesada** [comment]
as far as I know, the only one that works differently is the buoyancy test.

**Comment by minggo** [comment]
@chengshan1 please add more detail information about this issue. Pictures are better to describe the issue. Thanks.

**Comment by chengshan1** [comment]
Is there any difference in the two versions of the buoyancy?

**Comment by ricardoquesada** [comment]
@chengshan1 I'll fix the buoyancy, but is there any other example with issues? thanks.

**Comment by TheCodez** [comment]
@ricardoquesada i think `applyImpulse` is also not the same as before.

**Comment by ricardoquesada** [comment]
@TheCodez good tip. I'll take a look at it.

**Comment by pandamicro** [comment]
@ricardoquesada  Also, how should we deal with the API changes ? Do we have a change List to let user know how to upgrade ?

**Comment by ricardoquesada** [comment]
@pandamicro I haven't changed our physics API, the `CCPhysics` stuff. Users who are using our API directly won't need to change anything.
Not sure if you are referring to the chipmunk API, or our API.

**UPDATE**:
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/physics/cpCompat62.h

It is not complete, but will work for >80% of the games based on chipmunk 6.2.

**Comment by minggo** [comment]
@ricardoquesada Any progress of this issue? We plan to ask QA team to test on next Monday.

**Comment by minggo** [comment]
`buoyancy` is fixed via #15373
