### ISSUE TITLE
ccui::TextInput changes password style symbol

### ISSUE THREAD

**Issue by 1scaR1** [cocos2d/cocos2d-x#15354]
If ui TextField is in focus then password style text is like '*****', but after loosing focus it changes to '● ● ● ● ●'.

Works with HEAD of v3.

**Comment by zilongshanren** [comment]
@1scaR1  Got it :+1:  I will fix it later, thanks

**Comment by zilongshanren** [comment]
@1scaR1  I have fixed it in v3 HEAD, please give it a try.

**Comment by 1scaR1** [comment]
@zilongshanren now all is ok. Thanks!
