### ISSUE TITLE
VSync and Inconsistent Performance Issues on Windows

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#15368]
Posting this issue to help get it looked at and hopefully a PR once a fix is determined.
http://discuss.cocos2d-x.org/t/cocos2d-x-windows-performance-issues-examined/27915/
https://randomascii.wordpress.com/2013/04/02/sleep-variation-investigated/

This PR fixed the busy waiting, but introduces sleep(1) which potentially waits for 15ms instead of 1ms.
https://github.com/cocos2d/cocos2d-x/pull/9368

**Comment by minggo** [comment]
@stammen Could you please take a look?

**Comment by Bilalmirza** [comment]
@minggo these fixes has already been applied to win32 version. You can close this issue.
Also there is an issue where vsync is not applied to to some pcs (I'm not sure what differs).

add this  at the start of Application::run() in CCApplication-win32.cpp will fix the vsync issue. (glfwSwapInterval(1) doesn't work).

#ifdef _WIN32
    // Turn on vertical screen sync under Windows.
    // (I.e. it uses the WGL_EXT_swap_control extension)
    typedef BOOL (WINAPI *PFNWGLSWAPINTERVALEXTPROC)(int interval);
    PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT = NULL;
    wglSwapIntervalEXT = (PFNWGLSWAPINTERVALEXTPROC)wglGetProcAddress("wglSwapIntervalEXT");
    if(wglSwapIntervalEXT)
        wglSwapIntervalEXT(1);
#endif

**Comment by minggo** [comment]
@Bilalmirza thanks. Could you please create a new issue and send a PR for it?
