### ISSUE TITLE
MenuItemSprite requires 2 parameters or fails silently

### ISSUE THREAD

**Issue by ntrrgc** [cocos2d/cocos2d-x#15365]
If you are working with `MenuItemImage` you can add a button with a single image like this:

```
var playButton = new cc.MenuItemImage('res/playButton.png');
```

You can pass a second parameter to specify a different image for the _selected_ status, but that's not necessary.

You would expect the same behavior with MenuItemSprite, but unfortunately, something like this...

```
var playButton = new cc.MenuItemSprite(sprite);
```

will do nothing. No sprites will be actually added to the menu item.

**Comment by pandamicro** [comment]
Thanks for your contribution !
