### ISSUE TITLE
launchimage of iphone5/5s on ios7.x/ios8.x?

### ISSUE THREAD

**Issue by jasonz1987** [cocos2d/cocos2d-x#15370]
my game is landscape,this is my info.plist for iphone5/iphone5s

<dict>
            <key>UILaunchImageMinimumOSVersion</key>
            <string>6.0</string>
            <key>UILaunchImageName</key>
            <string>Default-568h</string>
            <key>UILaunchImageOrientation</key>
            <string>Portrait</string>
            <key>UILaunchImageSize</key>
            <string>{320, 568}</string>
        </dict>

 it's just worked for  iphone5/5s on ios9.x ios6.x, but not on  ios7.x ios8.x,it doese not show launchimages on these os versions.

my cocos2dx-lua version is v3.3.

**Comment by slackmoehrle** [comment]
this is long, but go towards the bottom for a current explanation. https://github.com/cocos2d/cocos2d-x/issues/8545

**Comment by slackmoehrle** [comment]
You either use an info.plist of just name your launch images correctly and it works also
