### ISSUE TITLE
Label with TTF font error

### ISSUE THREAD

**Issue by haanhman** [cocos2d/cocos2d-x#15378]
I am using Cocos2d-x-3.9 and have tried to use Cocos2d-x-3.10 and still experienced the following issue with **Label::createWithTTF**.
As you can see from the pictures, the words just have some random marks around them. If I use **getLetter(int index)**, then the errors happen even more often, sometimes the letters just get overlapped with each other.
Here is our code
https://github.com/haanhman/Label/blob/master/Classes/HelloWorldScene.cpp

My Project: https://www.dropbox.com/s/0cuud1vzhq69jnq/v10.zip?dl=0
On github: https://github.com/haanhman/Label

![e1](https://cloud.githubusercontent.com/assets/7600709/14335772/1cb78710-fc88-11e5-8d4d-48733debe605.png)
![e2](https://cloud.githubusercontent.com/assets/7600709/14335771/1cb4f798-fc88-11e5-946f-b2439e9008c6.png)
![e3](https://cloud.githubusercontent.com/assets/7600709/14335774/1cba3e74-fc88-11e5-96d5-738ead70b819.png)
![e4](https://cloud.githubusercontent.com/assets/7600709/14335773/1cb847b8-fc88-11e5-86c2-f3e6a1f09344.jpg)
![e5](https://cloud.githubusercontent.com/assets/7600709/14337632/f93600a2-fc99-11e5-8fa5-9f4a7933d75e.png)
![e6](https://cloud.githubusercontent.com/assets/6611502/14338250/a2adeb9a-fc9f-11e5-9e5b-3f67af59f638.png)

**Comment by eduhub123** [comment]
@minggo @zilongshanren 
Hi Minggo and Zilongshanren
Has my error been solved yet?

**Comment by slackmoehrle** [comment]
Have you tried a different TTF font to see if the issue persists? I use Arial and Marker Felt a lot and I don't see this happening, at least on iOS.

**Comment by eduhub123** [comment]
@slackmoehrle 
Our project includes multipule languages of various fonts. Please download our trouble code/ project and run it on Simulator Iphone 5, you will see the results as attached.
My Project: https://www.dropbox.com/s/0cuud1vzhq69jnq/v10.zip?dl=0
![aaaa](https://cloud.githubusercontent.com/assets/7600709/14484953/229343e0-017e-11e6-92ea-035c00fde357.png)

**Comment by larsven** [comment]
This looks like the same issue discussed here: http://discuss.cocos2d-x.org/t/random-font-artifacts/27486/5. And yes, it only occurs with some fonts. But those fonts are perfectly rendered everywhere else.

**Comment by larsven** [comment]
This is fixed in 3.11

**Comment by eduhub123** [comment]
I updated it to version 3.11, which has solved my problem. 
Thanks @larsven.

**Comment by ricardoquesada** [comment]
closing as fixed.
