### ISSUE TITLE
v3.11 #if not is not a legal C++ preprocessor directive.

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#15372]
# if not  is not a legal C++ preprocessor directive and it causes an "unexpected tokens following preprocessor directive" warning in Visual Studio.

For example:
# if not CC_ENABLE_GC_FOR_NATIVE_OBJECTS is not a legal C++ preprocessor directive.

Here are all of the incorrect preprocessor directives:

 D:\GitHub\cocos2d-x-v3\cocos\scripting\js-bindings\manual\cocos2d_specifics.cpp(2221):#if not CC_ENABLE_GC_FOR_NATIVE_OBJECTS
  D:\GitHub\cocos2d-x-v3\cocos\scripting\js-bindings\manual\cocos2d_specifics.cpp(2236):#if not CC_ENABLE_GC_FOR_NATIVE_OBJECTS
  D:\GitHub\cocos2d-x-v3\cocos\scripting\js-bindings\manual\ScriptingCore.cpp(219):#if not CC_ENABLE_GC_FOR_NATIVE_OBJECTS
  D:\GitHub\cocos2d-x-v3\cocos\scripting\js-bindings\manual\ScriptingCore.cpp(2195):#if not CC_ENABLE_GC_FOR_NATIVE_OBJECTS
  D:\GitHub\cocos2d-x-v3\cocos\scripting\js-bindings\manual\ScriptingCore.cpp(2265):#if not CC_ENABLE_GC_FOR_NATIVE_OBJECTS

**Comment by slackmoehrle** [comment]
Thanks @stammen. I think @ricardoquesada is working on the bindings.

**Comment by ricardoquesada** [comment]
thanks. I guess it should be replaced with `#if !`, correct?

**Comment by slackmoehrle** [comment]
@ricardoquesada I believe you are correct: https://msdn.microsoft.com/en-us/library/ew2hz0yd.aspx

**Comment by minggo** [comment]
@ricardoquesada Could you please add milestone in future, it will be convenient when writing release note.

**Comment by ricardoquesada** [comment]
@minggo sure!
it says "milestone = next" now... shouldn't it say "3.11" instead?

**Comment by minggo** [comment]
I have created v3.11 branch, then we can continue merging pull request in master branch. If you think it is an important issue, then could you please send to v3.11 branch too?

**Comment by stammen** [comment]
@minggo  @ricardoquesada  This is still an issue in the v3.11 branch

7>..\manual\ScriptingCore.cpp(219): warning C4067: unexpected tokens following preprocessor directive - expected a newline
7>..\manual\ScriptingCore.cpp(2195): warning C4067: unexpected tokens following preprocessor directive - expected a newline
7>..\manual\ScriptingCore.cpp(2265): warning C4067: unexpected tokens following preprocessor directive - expected a newline

**Comment by minggo** [comment]
Ok, i send a pull request to synchronize the modification #15429
