### ISSUE TITLE
sqlite localStorageSetItem error

### ISSUE THREAD

**Issue by iNeverSleeeeep** [cocos2d/cocos2d-x#15382]
`
/*\* sets an item in the LS */
void localStorageSetItem( const std::string& key, const std::string& value)
{
    assert( _initialized );

```
int ok = sqlite3_bind_text(_stmt_update, 1, key.c_str(), -1, SQLITE_TRANSIENT);
ok |= sqlite3_bind_text(_stmt_update, 2, value.c_str(), -1, SQLITE_TRANSIENT);

ok |= sqlite3_step(_stmt_update);

ok |= sqlite3_reset(_stmt_update);

if( ok != SQLITE_OK && ok != SQLITE_DONE)
    printf("Error in localStorage.setItem()\n");
```

}
`
_ok_ is SQLITE_BUSY         5   /\* The database file is locked */
I don't know why this happened.

**Comment by minggo** [comment]
It seems it is your own codes, right?

**Comment by iNeverSleeeeep** [comment]
I think it because i launched the game twice at same time.
