### ISSUE TITLE
New AudioEngine not pause when enterbackground

### ISSUE THREAD

**Issue by Lostmonkey** [cocos2d/cocos2d-x#15403]
On Android platform, our apps still play bgm after the user press "home" button.

**Comment by minggo** [comment]
Did you pause it in `AppDelegate::applicationDidEnterBackground()`?

**Comment by dumganhar** [comment]
@Lostmonkey , any update? You probably need to invoke `AudioEngine::pauseAll` in `AppDelegate::applicationDidEnterBackground()` and invoke `AudioEngine::resumeAll` in `AppDelegate::applicationWillEnterForeground`.

I closed this issue, if you still get the problem, feel free to re-open it.
