### ISSUE TITLE
[3.10] HttpClient Content-Type limitation on iOS only

### ISSUE THREAD

**Issue by klemsFR** [cocos2d/cocos2d-x#15413]
Hi ,

The HttpClient for iOS always set a content-type (in the http headers) to "application/x-www-form-urlencoded" for PUT request.
I think that's an issue because all put requests are not limited to this content type!

For example i need to use "application/json" to be compliant with my REST webservices...

The android version of HttpClient is not affected.

Issue can be fixed by removing the following lines from HttpClient-apple.mm:

```
if ([requestType isEqual: @"PUT"])
{
    [nsrequest setValue: @"application/x-www-form-urlencoded" forHTTPHeaderField: @"Content-Type"];
}
```

Thank you!

**Comment by minggo** [comment]
fixed in #15607
