### ISSUE TITLE
Fix warnings as possible

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15426]

**Comment by xpol** [comment]
I have done some of it: #15443

**Comment by xpol** [comment]
Here is more fixes: #15446 #15447 #15448 #15451 and a related issue #15449 .

**Comment by minggo** [comment]
Thanks @xpol .

**Comment by minggo** [comment]
#15480

**Comment by minggo** [comment]
#15472

**Comment by minggo** [comment]
#15460

**Comment by minggo** [comment]
#15453

**Comment by mogemimi** [comment]
I've just submitted #15490

**Comment by mogemimi** [comment]
I just made a pull request #15492

**Comment by mogemimi** [comment]
I created a pull request #15500

**Comment by xpol** [comment]
#15510 and #15508

**Comment by mogemimi** [comment]
I've submitted #15514

**Comment by xpol** [comment]
Lets eliminate them all: #15511

**Comment by mogemimi** [comment]
I've just created a new PR #15543

**Comment by mogemimi** [comment]
I've just submitted a new PR #15578

**Comment by mogemimi** [comment]
I've submitted a new PR #15633

**Comment by mogemimi** [comment]
I've submitted #15685

**Comment by mogemimi** [comment]
I just made a new PR: #15744

**Comment by mogemimi** [comment]
I've submitted #15747

**Comment by mogemimi** [comment]
I've submitted a new PR #15766

**Comment by mogemimi** [comment]
I submitted #15775 and #15784

**Comment by mogemimi** [comment]
I've submitted #15795

**Comment by mogemimi** [comment]
These are the PRs specific to Android NDK/Clang: #15807 #15737

**Comment by mogemimi** [comment]
I submitted #15861
