### ISSUE TITLE
No exit from EditBox with InputMode::PHONE_NUMBER

### ISSUE THREAD

**Issue by rynkowsg** [cocos2d/cocos2d-x#15468]
Tested on iPhone 5 and iPhone Touch 5G.
Using Cocos2d-x 3.9

Using modes DECIMAL, NUMERIC and PHONE_NUMBER there is no exit from edit box. Touching the background doesn't work.

![noexitfromageeditbox](https://cloud.githubusercontent.com/assets/5878299/14668436/27c4180e-06dc-11e6-9a5b-b4aa193b3f44.png)

**Comment by zilongshanren** [comment]
@rynkowsg what's your engine version? it should be OK in the latest branch.

**Comment by zilongshanren** [comment]
@rynkowsg  please try 3.10, it should be fixed.

**Comment by rynkowsg** [comment]
Thanks @zilongshanren,
Because of our fixed development process I can't update cocos2d-x now. I'll check this out when we update cocos2d-x and I'll let you know here.

**Comment by rynkowsg** [comment]
Hi @zilongshanren,

I haven't updated cocos2d-x to v3.10, but I fixed the issue. I've just cherry-picked commits from #14505 and #14514 and the problem is gone.

I consider that this issue could be closed.
