### ISSUE TITLE
Replace libxml2 with tinyxml2

### ISSUE THREAD

**Issue by martell** [cocos2d/cocos2d-x#1546]
Hi guys,

My cmake solution for cocos2dx is almost ready, just a few more days.
It can download all required external libs and build them from source along with cocos2dx
It can generate nmake files visual studio solutions eclipse solutions etc

I was wondering if you were replacing libxml with tinyxml2 because it is in the windows 8 branch.
It seems a lot smaller and more robust and I was wondering if I should create cmake support for it?

**Comment by dumganhar** [comment]
Hi martell
That's great!
How about on android? Users don't need to write Android.mk if using cmake?
Does your cmake solution create .xcodeproject for ios and mac?

Yep, tinyxml2 is more faster, we will try to use it if we have enough time. Thanks.

**Comment by martell** [comment]
Hi dumganhar,
I've created a custom cmake file so that you don't need android.mk files or even apache-ant for that matter.
You can use the latest jdk version 7 with it also.

It can generate .xcode projects but I haven't tested it for mac or ios yet.
Also it can do windows 64bit also ;)

Creating a cmake file for libxml2 is a pain. :/

PS. using ninja build I can build cocos2dx in roughly 10 seconds.
Might be handy for you guys for development speed?

**Comment by dumganhar** [comment]
Hey martell,
I looked at your repo(https://github.com/martell/cocos2dx.cmake). It looks cool.
Could you write a document about how to make it works?

**Comment by martell** [comment]
Hi dumgnhar that is not the full code,

For the repo you have linked it keeps cocos in a submodule.
You will need the other cmake file which i havent uploaded to github to build it.

Basically I would like to pull the external libraries into a 3rdparty directory outside of the cocos dir.
I will have a cmake file in that directory for building the libs and dll's to replace older ones if the user wants to build from source.

Then a cmake file will be placed in the cocos dir to build cocos. ( the one you have looked at with a few tweaks)

A final cmake file will be at the root directory that has all the options for building.
ie. building things static/ shared.
This cmake file invokes the other two into running and controls their options

On my specific version right now it downloads the 3rd party libs and cocos from source using git through cmake and then builds it.

What we might have to agree on is a structure for the folder layout etc, and if git submodules can be used?

**Comment by martell** [comment]
Ill submit a merge request tomorrow along with a tutorial and we will work from there.
Kind regards Martell

**Comment by martell** [comment]
https://github.com/cocos2d/cocos2d-x/pull/1894

For the tinyxml2 start :)
