### ISSUE TITLE
Why not rename all cocos file name by remove CC prefix

### ISSUE THREAD

**Issue by aozhimin** [cocos2d/cocos2d-x#15494]
I know cocos2d-x which is based on cocos2d-iphone, was implement by c++ . in objective-c, there is no namespace, so we always name a class with a namespace, in 2.x, we use this style, however, in 3.x, all class prefix was removed, but, the file name still named by CC prefix

**Comment by stevetranby** [comment]
I think there's benefit to keeping it this way for code/file navigation in larger project and amongst other STL and platform methods during autocomplete/search, but I guess I would be fine if the prefix was dropped going forward (probably a v4+ thing).

**Comment by aozhimin** [comment]
Got it, thank you for answer me!

**Comment by minggo** [comment]
Yep, it is a history issue. We hope we can remove it in future.
