### ISSUE TITLE
Windows Universal 8.1 Build Machine  error code '23'  

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#15506]
The Windows Universal 8.1 Jenkins Build Machine  is having an issue with error code '23'  

fatal error C1090: PDB API call failed, error code '23'

**Comment by stammen** [comment]
@minggo What version of Visual Studio are you using on the Windows Universal 8.1 Jenkins build machine? Visual Studio 20XX Update X?

**Comment by minggo** [comment]
@zilongshanren Do you know?

**Comment by zilongshanren** [comment]
@minggo  Sometimes Jenkins Windows Universal 8.1 Build machine got this issue, But I don't know why, somebody says the PDB process broken when it reaches the limits.. I'm also quite confused by this error message...

**Comment by minggo** [comment]
@zilongshanren Do you know the answer of @stammen question `What version of Visual Studio are you using on the Windows Universal 8.1 Jenkins build machine?`

**Comment by zilongshanren** [comment]
@stammen  

We use VS 2013 on the Windows Universal 8.1 Jenkins build machine?

**Comment by stammen** [comment]
@zilongshanren Which update of VS 2013? There are updates 1 to 5.
