### ISSUE TITLE
.cocos-project.json file not found.

### ISSUE THREAD

**Issue by PeqNP** [cocos2d/cocos2d-x#15524]
I upgraded from 3.8.1 to 3.10.0 yesterday. I ran the `cocos` command only to find that it couldn't find the `.cocos-project.json` file. Typically I have this in the `<Cocos2d-x-path>/frameworks/runtime-src`. After some investigation I saw that the `cocos` script invokes bash with `#!/bin/bash -l` (it runs the script as if it was ran in a new terminal). In my case, this will always change the directory into the home directory. So it attempts to find the file at `~/.cocos-project.json`. Sure enough, after removing the `-l`, it worked.

Is this the intended behavior of this script? Is there a specific reason the `cocos` script needs to be opened as if it was opened in a new terminal? I'm assuming the idea is to prevent path pollution from the environment. I find "polluting" the path useful, especially when testing different configurations, or changing environment variables before I run certain scripts which require a certain configuration.

So, is this a bug? Feature?

Thank you!

**Comment by PeqNP** [comment]
A separate issue: By default, the .cocos-project.json is not created. I end up having to copy the one I used in an older version to `frameworks/runtime-src`. Is there a reason for this? Because not having it, and building for Android, will always fail.

**Comment by slackmoehrle** [comment]
I just ran `cocos new...` and `.cocos-project.json` was created for me.

**Comment by PeqNP** [comment]
Huh. Sometimes I wonder if my machine is configured so much more different from others that it's causing issues.

That is good to know.

Were you using the zip download for v3.8.1? Was it on a Mac? Was it a Lua project?

Thank you!

**Comment by minggo** [comment]
I am not sure if it has problem in v3.8.1 or not, but i don't have problem with github latest code.

``` sh
A03101308207:test minggo$ cocos new -l lua
> Copy template into /Users/minggo/SourceCode/test/MyLuaGame
> Replace the project name from 'HelloLua' to 'MyLuaGame'
> Copying directory from cocos root directory...
> Copying files from template directory...
> Copying cocos2d-x files...
> Copying directory from cocos root directory...
> Rename project name from 'HelloLua' to 'MyLuaGame'
> Replace the project name from 'HelloLua' to 'MyLuaGame'
> Replace the project package name from 'org.cocos2dx.hellolua' to 'org.cocos2dx.MyLuaGame'
> Replace the Mac bundle id from 'org.cocos2dx.hellolua' to 'org.cocos2dx.MyLuaGame'
> Replace the iOS bundle id from 'org.cocos2dx.hellolua' to 'org.cocos2dx.MyLuaGame'
> Modify files by re.sub()
A03101308207:test minggo$ cd ./MyLuaGame/
A03101308207:MyLuaGame minggo$ ls -a | grep '.cocos-project.json'
.cocos-project.json
A03101308207:MyLuaGame minggo$ 
```

PS: i use MBP, Mac OS X version is 10.11.4.
