### ISSUE TITLE
Getting different values stored with scientific notation in a plist.

### ISSUE THREAD

**Issue by bolino** [cocos2d/cocos2d-x#15525]
I'm reading the plist using`FileUtils::getInstance()->getValueMapFromFile(path)` and then reading the value using `asFloat()`.

For example: if you save the number 1.52587890625E-05 in a plist and then try to read it, the correct decimal number (0.0000152587890625) will be returned in iOS, however in android it will return the number 1.52587890625.

Xcode will automatically convert numbers to scientific notation. If you write the number 0.0000152587890625 using Xcode it will actually be actually stored as 1.52587890625E-05.

I'm using v3.9 by the way.

**Comment by minggo** [comment]
It is interesting, i will take a look.

**Comment by minggo** [comment]
K, i know what causes this issue. On Android, it uses [utils::atof()](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/CCFileUtils.cpp#L286) to convert string to float. And `utils::atof()` is to fix [`std::atof` issue](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/ccUtils.h#L86) on Android.  So `1.52587890625E-05` is converted to `1.5258789`  on Android.

I can fix it by appending `E-05` to the end of string if it exits, but i can not fix the issue on Android. Which means `1.52587890625E-05` will be converted to `1.5258789E-05`, i am not sure if it is acceptable.

**Comment by minggo** [comment]
`utils::atof` is added in #7440, it is almost two years ago, may be the bug is fixed by new NDK. So i will try to use `std::atof`.

**Comment by minggo** [comment]
It worked as expected with `std::atof()`, my environment is:
- Device: Nexus 5
- Android version: 5.1
- NDK version: r10c
- cocos2d-x codes: latest codes in v3 with the commit hash: `fba4bead704497f7c111746f703fbef56c35bec2`
- PC: Mac OS X 10.11.4

**Comment by minggo** [comment]
fixed in #15549

@bolino Please have a try.
