### ISSUE TITLE
cocos2dx 3.9引擎，ios越狱i5, 纹理渲染出现严重马赛克

### ISSUE THREAD

**Issue by zeguRepository** [cocos2d/cocos2d-x#15536]
平台：ios，越狱版本，iphone6不会出现该问题；
引擎：3.9部分升级到3.10

**Comment by zilongshanren** [comment]
@xiaoyudoudou  

show me some screenshot and code？

**Comment by xiaoyudoudou** [comment]
我上传不了图片哦~~~

**Comment by xiaoyudoudou** [comment]
![Uploading eg.png…]()

**Comment by gdgoldlion** [comment]
![d17_ rwv5ro9xw3 hc2](https://cloud.githubusercontent.com/assets/1749001/14907571/54484ce2-0dfd-11e6-865b-4956eb8e4219.jpg)
代传图片

**Comment by zeguRepository** [comment]
@zilongshanren

**Comment by zeguRepository** [comment]
@zilongshanren 
i5 7.1.2
i5 8.2
i5c 8.3 都有问题

i5s 9.3
ipad mini 3  9.2
ipad air2  9.1  
i6 9.1+    都没问题

现在确定的情况是A6芯片的时候 就问题了～～

**Comment by zilongshanren** [comment]
@xiaoyudoudou  回头我测试一下，现在我手上没设备。。。

**Comment by zeguRepository** [comment]
问题解决了，原因是frag着色器里面使用的低精度浮点书导致的问题，可能是iphone5等设备的GPU支持问题导致的；代码如下
![aee22cd7-eed4-4d08-9ca1-eac357e3290b](https://cloud.githubusercontent.com/assets/6153203/14973868/2a8ac468-1120-11e6-8775-beafa8879d43.jpg)

我后来加了etc1的支持，导致frag里面又额外的计算。
但是我还有一个疑问呢，假如我注释掉自定义的纹理采样部分的代码也能解决这个问题，问题是逻辑上不应该走u_hasAlpha后面的代码呢。

**Comment by zeguRepository** [comment]
@zilongshanren  能不能解答一下我额外的疑问呢，感激不尽呢！

**Comment by zilongshanren** [comment]
@xiaoyudoudou 
你的自定义纹理采样的代码是什么样子的？

**Comment by zeguRepository** [comment]
我的意思是采样第二张纹理的颜色；
![image](https://cloud.githubusercontent.com/assets/6153203/14974093/0b754ece-1123-11e6-886e-53bca9c9e678.png)

**Comment by zilongshanren** [comment]
@xiaoyudoudou 
你指的注释掉的代码，是上图中if 语句里面的代码，还是只注释掉 采样 alpha channel 的代码啊？

**Comment by zeguRepository** [comment]
我现在是把原来的低精度浮点数改为了中精度，可解决锯齿问题；或者把原来的低精度设置去掉也可以；还有一种就是把我alpha channel这些代码去掉。但是不应该走到alpha channel这边的逻辑啊～

**Comment by zilongshanren** [comment]
@xiaoyudoudou  会不会是 uniform 的初始值有问题，你是直接没有给 uniform 传值对么？
我还是不是很理解你说的不应该走 alpha channel 的逻辑。。 如果 u_hasAlpha > 0 就会走啊。。

**Comment by zeguRepository** [comment]
![image](https://cloud.githubusercontent.com/assets/6153203/14974219/a6dafa70-1124-11e6-9a62-2cadf4b65558.png)

**Comment by zeguRepository** [comment]
只有在逻辑判断有alpha通道时，才会设置为1，才会走u_hasAlpha虾面的逻辑

**Comment by zilongshanren** [comment]
@xiaoyudoudou 
我的建议是你直接在 u_hasAlpha if 语句里面人为添加一些设置，比如把 color 手动设置为一个值，然后确定在没有 alpha 的情况下面也进入了 alpha 采样的 shader。

此时，说明 u_hasAlpha 这个 Uniform 的值确实是大于 0 的，再在 C++层打个断点看看，先定位一下问题，然后再找原因。

**Comment by zeguRepository** [comment]
嗯嗯，好的～主要是对shader不是太熟悉，有点疑惑，谢谢你的建议～ 我先去试试

**Comment by zilongshanren** [comment]
@xiaoyudoudou 
继续讨论可以移步 http://forum.cocos.com/

**Comment by zeguRepository** [comment]
测试了，并没有走到那边的逻辑里面，问题现在就确定了：浮点数精度问题
