### ISSUE TITLE
Add a callback in FileUtils

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15537]
Some developers suggesting add a callback in FileUtils, then can use the callback to decrypt data read by FileUtils. If you understand Chinese, can refer to [this thread](http://forum.cocos.com/t/cocos2d-x/36192/15).

**Comment by minggo** [comment]
@xpol Do you have any suggestion about this feature?

**Comment by xpol** [comment]
My solution in my current project, have a CryptFileUtils like this:

``` C++
if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
#include "platform/android/CCFileUtils-android.h"
typedef cocos2d::FileUtilsAndroid FlatformFileUtils;

#elif (CC_TARGET_PLATFORM == CC_PLATFORM_IOS) || (CC_TARGET_PLATFORM == CC_PLATFORM_MAC)
#include "platform/apple/CCFileUtils-apple.h"
typedef cocos2d::FileUtilsApple FlatformFileUtils;

#elif (CC_TARGET_PLATFORM == CC_PLATFORM_WIN32)
#include "platform/win32/CCFileUtils-win32.h"
typedef cocos2d::FileUtilsWin32 FlatformFileUtils;

#elif (CC_TARGET_PLATFORM == CC_PLATFORM_WINRT)
#include "platform/winrt/CCFileUtilsWinRT.h"
typedef cocos2d::CCFileUtilsWinRT FlatformFileUtils;


#elif (CC_TARGET_PLATFORM == CC_PLATFORM_LINUX)
#include "platform/linux/CCFileUtils-linux.h"
typedef cocos2d::FileUtilsLinux FlatformFileUtils;

#else
#error "Filesystem not supported on this platform"
#endif


#include "Crypt.hpp"
#include "Locator.hpp"

class CryptFileUtils: public FlatformFileUtils {
    Crypt* crypt_;
    Locator* locator_;
public:
    CryptFileUtils(Crypt* crypt, Locator* locator);
    virtual ~CryptFileUtils() { delete crypt_; delete locator_; }
protected:
    virtual cocos2d::Data getDataFromFile(const std::string& filename) override {
        return decrypt(FlatformFileUtils::getDataFromFile(filename));
    }
    virtual void purgeCachedEntries() override;
private:
    cocos2d::Data encrypt(const cocos2d::Data& data);
    cocos2d::Data decrypt(const cocos2d::Data& data);
};
```

And in `frameworks/runtime-src/Classes/AppDelegate.cpp`:

``` C++

bool AppDelegate::applicationDidFinishLaunching()
{
    auto crypt = new XXTeaCrypt("key", "sign");
    auto locate = new HashLocator(FileUtils::getInstance()->getWritablePath() + "up", "index");
    FileUtils::setDelegate(new CryptFileUtils(crypt, locate));

// ...
}

```

**Comment by xpol** [comment]
I think the abstract class of `Crypt` is nessary.

If need, I can port CryptFileUtils into FileUtils with Crypt support.

**Comment by minggo** [comment]
Why need `Crypt` class? A callback is not enough?

**Comment by xpol** [comment]
Abstract `Crypt` class make it more flexible can support both encrypt and decrypt:

``` C++
class Crypt {
public:
    virtual ~Crypt() {}
    virtual bool isEncrypted(const cocos2d::Data& buffer) const = 0;
    virtual void decrypt(const cocos2d::Data& in, cocos2d::Data* out) const = 0;
    virtual void encrypt(const cocos2d::Data& in, cocos2d::Data* out) const = 0;
};


cocos2d::Data CryptFileUtils::decrypt(const cocos2d::Data& data)
{
    if (!crypt_->isEncrypted(data))
        return cocos2d::Data(data);

    cocos2d::Data rv;
    crypt_->decrypt(data, &rv);
    return rv;
}
```

These can't be done in one simple callback function.

**Comment by xpol** [comment]
```C++
cocos2d::Data CryptFileUtils::decrypt(const cocos2d::Data& data)
{
    if (!crypt_->isEncrypted(data))
        return cocos2d::Data(data);

    cocos2d::Data rv;
    crypt_->decrypt(data, &rv);
    return rv;
}
```

**Comment by xpol** [comment]
BTW, I can't login/register http://forum.cocos.com/t/cocos2d-x/36192/4.

For packing all resource as a package, there is [LÖVE](https://love2d.org) which [does it very well](https://love2d.org/wiki/love.filesystem).

**Comment by minggo** [comment]
@xpol Thanks.
But i think add a callback is more simple and flexible, because you can just pass an lambda. And you can do what you want in the callback.

About the callback parameter, i think return unsigned char\* is more common, the prototype looks as 

``` c++
void callback(unsigned char* buffer, size_t length);
```

**Comment by halx99** [comment]
Yes, I think, we just need add a callback, but should be:
void callback(const std::string& filename/_a relative path key_/, unsigned char\* buffer, size_t length);

**Comment by minggo** [comment]
@halx99 Yep, needs to pass filename too, then developers know how to do based on filename. But i think should pass full path of filename because many files may have the same name. And i think FileUtils needs to know the final size after callback, such as:

``` c++
void callback(const std::string fullPathOfFileName, unsigned char* buffer, const size_t originSize, size_t *finalSize);
```

**Comment by halx99** [comment]
@minggo Actually, the developers should avoid use same relative path which will lead ambiguity texture load, so I think, the follow callback should be ok:
std::function<void(const std::string& filename, unsigned char\* buffer, ssize_t& size)> decryptFunc;

**Comment by minggo** [comment]
Yep, relative path(relative to Resources) should be ok.

**Comment by xpol** [comment]
for `void callback(const std::string fullPathOfFileName, unsigned char* buffer, const size_t originSize, size_t *finalSize);`:
1. It makes us go back to use raw buffer like `FileUtils::getFileData()`
2. It don't support some decryption which don't allow work on original buffer.

How about:

``` C++
void callback(const std::string& fullPathOfFileName, ResizableBuffer * inBuffer, ResizableBuffer * outBuffer);
```

**Comment by halx99** [comment]
For performance, I think use overlapped encrypt/decrypt algorithm is a better choice, such as AES. Certainly we need test that.

**Comment by minggo** [comment]
@xpol looks good to me. Yep, it may be better not use raw data.

> For performance, I think use overlapped encrypt/decrypt algorithm is a better choice, such as AES. Certainly we need test that.

@halx99 what did you mean `overlapped encrypt/decrypt algorithm`? Engine will not provide encryption algorithm by default.

**Comment by halx99** [comment]
@minggo It means reuse inputbuffer: inputbuffer == outputbuffer, No unnecessary memory alloc & copy.
And many block encrypt algorithm suppurt the feature.

**Comment by halx99** [comment]
@minggo The openssl support AES, https://en.wikipedia.org/wiki/Advanced_Encryption_Standard, so Engine already privide it.

**Comment by minggo** [comment]
> @minggo It means reuse inputbuffer: inputbuffer == outputbuffer, No unnecessary memory alloc & copy.
> And many block encrypt algorithm suppurt the feature.

@halx99 so did you mean we don't need outputbuffer parameter? Could you please write the prototype and the usage? About OpenSSL support AES, i don't know if it is something related with this issue.

@xpol the prototype has a problem 

``` c++
void callback(const std::string& fullPathOfFileName, ResizableBuffer * inBuffer, ResizableBuffer * outBuffer);
```

`ResizableBuffer` doesn't contain size information, and the size information for `inBuffer` is important.

**Comment by halx99** [comment]
@minggo  Yes, I mean no need outputbuffer parameter. The follow usage is from My project: 

``` c++
        auto fileUtils = FileUtils::getInstance();
    fileUtils->decryptFunc = [this](unsigned char* buffer, ssize_t& size){
        if (decryption)
        {
            const unsigned char cipherkey[] = DATA_ENCRYPT_KEY;
            crypto::aes::privacy::mode_spec<>::decrypt((char*)buffer, size, (char*)buffer, (size_t&)size, (const char*)cipherkey);
        }
    };
```

And the engine FileUtils implement should add some code support it like follow:
![qq 20160429172747](https://cloud.githubusercontent.com/assets/6977319/14912571/c10e982c-0e2f-11e6-8c89-38db2c0f6c74.png)

**Comment by minggo** [comment]
@halx99 but we can't make sure that inBuffer and outBuffer will be the same all the time. And if they are the same, just do `outBuffer = inBuffer`, right?

**Comment by minggo** [comment]
outBuffer and inBuffer may not be `unsigned char*`, may be can use Data or other types, but they support `std::move`, so not alloc and copy is needed.

**Comment by halx99** [comment]
@minggo  Yes, Data should be ok, but when you want use it to std::string parameter interface, you must copy the data. It goback std::string maybe more common useful than Data.

**Comment by xpol** [comment]
string can not cover every needs. An abstract buffer is certainly needed.

**Comment by halx99** [comment]
Yes, I agree.

**Comment by xpol** [comment]
I thought it again, the abstract of `Crypt` is necessary.
Because a single callback is not enough, see follow usage:

``` C++
FileUtils::Status FileUtils::getContents(const std::string& filename, ResizableBuffer* buffer)
{
    std::string signature;

    HANDLE* fp = fopen(filename);
    size_t size = getSizeFormHandle(fp);

    if (crypt->signatureSize() >= size) { // no longer than signature, must be a unencrypted file.
        buffer->resize(size);
        fread(buffer->buffer(), 1, size, fp);
        return Status::OK;
    }

    signature.reisze(crypt->signatureSize());
    fread(&signature.front(), 1, 16, pf);
    fseek(fp, 0, SEEK_SET);

    switch (crypt->getEncrytionType(signature))
    {
    case NO_ENCRYTION:
        buffer->reisze(size);
        fread(buffer->buffer(), 1, size, fp);
        return Status::OK;
    case INPLACE_ENCRYTION:
        fread(buffer->buffer(), 1, size, fp);
        crypt->decrypt(buffer);
        return Status::OK;
    case COPY_ENCRYTION:
        std::string s;
        s.resize(size);
        fread(&s.front(), 1, size, fp);
        crypt->decrypt(s, buffer);
        return Status::OK;
    }
}
```

The crypt interface would be:

``` C++
class Crypt {
public:
    virtual ~Crypt() {}
    virtual size_t signatureSize() const = 0;
    virtual bool isEncrypted(const std::string& signatureBytes) const = 0;
    virtual void decrypt(ResizableBuffer* inout) const = 0; // inplace decrypt
    virtual void decrypt(const std::string& in, ResizableBuffer* out) const = 0; // copy decrypt

    // needs encrypt interface maybe...
};
```

**Comment by halx99** [comment]
I  think, fixed use a  temporary buffer 's' not good, the developer chould't select reusable algorithm.
case COPY_ENCRYTION:
        std::string s;
        s.resize(size);
        fread(&s.front(), 1, size, fp);
        crypt->decrypt(s, buffer);
        return Status::OK;
    }

Leave the implement for developer, engine just privide a hook maybe a better solution.

**Comment by xpol** [comment]
why user must choose reusable algorithm？it's so limited.
i want compress + encryption, and this can be a reusable algorithm.

halx99 notifications@github.com于2016年4月29日周五 下午11:53写道：

**Comment by xpol** [comment]
And a abstract class doing this can support them all: plan file, inplace
encrypted and copy encrypted.

Xpol Wan xpolife@gmail.com于2016年4月30日周六 上午8:21写道：

**Comment by halx99** [comment]
Not must be, such as, I want reuse the input buffer, that's after I decrypt the inputbuffer, the inputbuffer become plaintext, and  I can use it to init a Image directly when it's a texture file. My mean is, the temp variable 's' is unnecessary in this case.

**Comment by minggo** [comment]
@xpol the callback is not just for encrypt, it can be used for everything. I think the most flexible way is the same mechanism as unix pipe. In the callback function, it passed input and accept output, looks like

``` c++
void callbcak(XXX input, XXX output);
```

**Comment by xpol** [comment]
how to optimize when no copy is required?

**Comment by minggo** [comment]
XXX can be `cocos2d::Data`, and you can just use `Data::takeBuffer()` you added a few days ago.

**Comment by Shulepov** [comment]
Absolutely agree with @xpol. Interface classes is much more verbose and extendable than just lambda function. @xpol already shows some possible future modifications. Interface `Crypt` requires only one additional file for implementation but gives much more abilities and makes code more verbose and readable. Also `Crypt` can contain both `ecnrypt` for saving files and `decrypt` for reading them (i like that functionality) - i think related things should go together.

**Comment by halx99** [comment]
Hi @minggo,  I agree with @xpol, If somebody interest about this, you can see: https://github.com/halx99/cocos2d-x/blob/v3/tests/cpp-empty-test/Classes/EncryptManager.cpp
And this issue could be closed.

**Comment by halx99** [comment]
@drelaptop @minggo
this issue should be close.
 It's a flexiable encrypt solution, the repo is changed to be: https://github.com/halx99/x-studio365/blob/master/encrypt-demo/cpp-empty-test/Classes/EncryptManager.cpp

**Comment by drelaptop** [comment]
@halx99 thanks for this feedback.
