### ISSUE TITLE
Unicode characters not displaying correctly in CCLabel [Windows only]

### ISSUE THREAD

**Issue by joshbodily** [cocos2d/cocos2d-x#15532]
See:
https://github.com/cocos2d/cocos2d-x/pull/15473#issuecomment-213562896

Steps to reproduce:
1) Create a CCLabel
2) label->setText("👐👊💝"); // See https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-tests/Classes/UITest/CocoStudioGUITest/UIEditBoxTest.cpp#L67 if the Unicode chars aren't showing up.

Expected:
Same glyphs show up

Actual:
Box glyphs show up

@stammen @minggo Feel free to assign to me.  I should have bandwidth next week to look into this.

**Comment by minggo** [comment]
@joshbodily Thanks. But i can not assign to you because you are not in assignee. But i will leave it to you :)

**Comment by drelaptop** [comment]
this feature have been improved at next milestones, you can test it using latest code. so close this out-dated issues, please reopen if disagree. @joshbodily
