### ISSUE TITLE
Support alpha channel for ETC1

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15538]

**Comment by minggo** [comment]
If you understand Chinese, can refer to [this thread](http://forum.cocos.com/t/cocos2d-x/36192) for detail information.

I am not sure if there is a simple way to support alpha channel with ETC format easily.

**Comment by UKDeveloper99** [comment]
@minggo I put ETC1 with alpha in to my game a long time ago. It was a really time consuming and frustrating process. Firstly ETC1 format by default can only accept RGB channels. So there is no way to have a single ETC1 texture with alpha. That means you have to supply the alpha channel in a separate texture.
Using the Mali GPU Texture Compression tool made by the arm developers they allow you to do this in a number of ways. The usual method is to embed the alpha channel of PNG or something like that in to either the R G or B channel of a separate ETC1 texture of equal dimensions to the ETC1 texture that contains the RGB channels. Then it is a simple case of providing both textures to a shader that combines these values in the color value for a pixel to make the final color. 

In my project I made a subclass of sprite called  SpriteETC and it had 2 textures one for the alpha and one for the rgb. If cocos2d-x was to support it like this. You would probably need to add a shader like above that does this to the default shaders. Also make a sprite class or something that needs to be initialized with 2 textures. There are other ways you can supply the alpha texture, e.g. (RAW) format and also attached to the RGB texture (below for example). The sampler in the shader will then take the values from the normal coords for rgb. And for the alpha it will be coords.y plus textureheight.

Hope that helps.

**Comment by minggo** [comment]
@UKDeveloper99 thanks, it is fixed in v3.13.
