### ISSUE TITLE
Make error in function ‘luaH_set’:

### ISSUE THREAD

**Issue by ehthxC7x9D** [cocos2d/cocos2d-x#15544]
Build: Ubuntu 16.04

```
In file included from /home/eht/tools/cocos2d-x-3.10/external/lua/lua/lua.h:16:0,
                 from /home/eht/tools/cocos2d-x-3.10/external/lua/lua/ltable.c:27:
/home/eht/tools/cocos2d-x-3.10/external/lua/lua/luaconf.h:543:20: warning: ISO C99 requires whitespace after the macro name
 #define luai_numstd::isnan(a) (!luai_numeq((a), (a)))
                    ^
/home/eht/tools/cocos2d-x-3.10/external/lua/lua/ltable.c: In function ‘luaH_set’:
/home/eht/tools/cocos2d-x-3.10/external/lua/lua/luaconf.h:543:20: error: expected expression before ‘:’ token
 #define luai_numstd::isnan(a) (!luai_numeq((a), (a)))
                    ^
/home/eht/tools/cocos2d-x-3.10/external/lua/lua/ltable.c:501:33: note: in expansion of macro ‘luai_numstd’
     else if (ttisnumber(key) && luai_numstd::isnan(nvalue(key)))
                                 ^
cocos/scripting/lua-bindings/CMakeFiles/luacocos2d.dir/build.make:302: recipe for target 'cocos/scripting/lua-bindings/CMakeFiles/luacocos2d.dir/__/__/__/external/lua/lua/ltable.c.o' failed
make[2]: *** [cocos/scripting/lua-bindings/CMakeFiles/luacocos2d.dir/__/__/__/external/lua/lua/ltable.c.o] Error 1
CMakeFiles/Makefile2:672: recipe for target 'cocos/scripting/lua-bindings/CMakeFiles/luacocos2d.dir/all' failed
make[1]: *** [cocos/scripting/lua-bindings/CMakeFiles/luacocos2d.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by minggo** [comment]
I will install the ubuntu version to have a try.

**Comment by ManidakisM** [comment]
I actually came across the same problem. I run the sed command again
to fix the issue with colons since the compiler responds with error at ":".

```
sed -i 's/luai_numstd::isnan/luai_numisnan/g' `grep "isnan" -rl`
```

Im not sure if that will fix the problem since the `make` has not yet completed on my end. Still running.

Update:
`make` finished without any errors. That's a fix maybe?

**Comment by minggo** [comment]
there is #15522 for it

**Comment by ehthxC7x9D** [comment]
Any update on this?

**Comment by minggo** [comment]
@e-ht haven't seen my comments?

**Comment by ehthxC7x9D** [comment]
@minggo I see your comments on #15522. Was that fix also for this?

**Comment by minggo** [comment]
Yep, i think so. Because i succeed building in Ubuntu 16.04 after applying the PR i sent though i met error when run the app because of .so missing issue.

**Comment by ehthxC7x9D** [comment]
It seems to get past those issues at this point but now I am hung up on #15624. I am using fresh installs of 16.04, so I am not sure where I am going wrong. In the cocos forums, user slackmoehrle seems to have been able to install just fine on 16.04 (see [here](http://discuss.cocos2d-x.org/t/building-on-ubuntu-16-04-issues/29051/2?u=eht)), despite earlier issues. At any rate, thanks for your attention.
