### ISSUE TITLE
Mac下编译Android目标失败

### ISSUE THREAD

**Issue by OneSecure** [cocos2d/cocos2d-x#15557]
我从 Github 取下的最后的 cocos2d-x 代码。然后编译 android 目标。编译 一直失败。

首先，在 Android Studio 里编译成功后。运行失败。说找不到 .so 文件。

然后，用命令行  cocos compile -p android  编译，就遇到下面的错误。
Android NDK: ERROR:/Users/xxx/proj.android/../cocos2d/external/freetype2/prebuilt/android/Android.mk:cocos_freetype2_static: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that /Users/xxxx/proj.android/../cocos2d/external/freetype2/prebuilt/android/arm64-v8a/libfreetype.a exists  or that its path is correct  
/Users/xxxx/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: **\* Android NDK: Aborting    .  Stop.
Error running command, return code: 2.

我的开发环境是 Mac OS X 10.11  
Android Studio 是最近两天(2016.05.03)下载的最新版。
SDK、NDK 和 cocos2d－x 也是最新的。

拜托修复。 拜托拜托。🙏。

**Comment by minggo** [comment]
You should use `cocos compile -p android --android-studio` to compile for android-studio.

**Comment by OneSecure** [comment]
改用 “ cocos compile -p android --android-studio ” 命令后。错误信息还是一样的。
反正就是缺 /prebuilt/android/arm64-v8a/libfreetype.a  文件。

**Comment by minggo** [comment]
Have you run `cocos2dx-root/download-deps.py` to download external libraries needed by cocos2d-x?

**Comment by OneSecure** [comment]
已经运行过了 说明文档的第二步。
 $ cd cocos2d-x
 cocos2d-x $ python download-deps.py

**Comment by minggo** [comment]
Oh, there is not prebuilt libs for arm64-v8a, why it will find the architecture? Did you modify `Android.mk` to specify special architecture?

**Comment by OneSecure** [comment]
用 cocos new yyyyy -p com.xxxxx.yyyy -l cpp  生成的工程直接编译的。没做任何改动。

**Comment by minggo** [comment]
what's your NDK version?

**Comment by OneSecure** [comment]
android-ndk-r12-beta1-darwin-x86_64.zip

**Comment by minggo** [comment]
I suggest you using NDK r10c now, and i will try r12.

**Comment by OneSecure** [comment]
好的。我马上用回 r10C 谢谢。

**Comment by OneSecure** [comment]
我的 ndk 是 Android Studio 的 SDK manager 自己替我做主安装的，版本号也是它替我选的。
我手工改回 r10c 去。

**Comment by OneSecure** [comment]
建议啊，你们发布安装包时，注明一下需要的 NDK 的版本号。您以为如何？

**Comment by minggo** [comment]
It is [here](https://github.com/cocos2d/cocos2d-x#build-requirements) but not all developers will notice it.

**Comment by minggo** [comment]
I found the latest version is r11c [here](http://developer.android.com/ndk/downloads/index.html), where did you download r12?

**Comment by OneSecure** [comment]
我的 ndk 是 Android Studio 的 SDK manager 自己替我做主安装的，版本号也是它替我选的。
我发现它的自动安装很不靠谱，不稳定。 然后我把这个 URL 复制下来专门下载了一份。
https://dl.google.com/android/repository/android-ndk-r12-beta1-darwin-x86_64.zip

安装路径默认是 /Users/xxxxxx/Library/Android/sdk/ndk-bundle

与手工安装的习惯路径不一样。

**Comment by minggo** [comment]
r12beta1 is not released in google doc, so i think you'd better not use it.

**Comment by tiancode** [comment]
-p android --app-abi armeabi

**Comment by mquaker** [comment]
i have same problem on released ndk-r12.
maby ndk-r12 not supported on cocos2d-x.
so, i tried ndk-r11e..
works perfect!

**Comment by minggo** [comment]
@mquaker you should use latest codes as i fixed an issue with r12 a few days ago.

**Comment by mquaker** [comment]
@minggo yep.. i downloaded cocos2d-x v3.12 and ndk-r12 when yesterday.
compile visual studio 2015 community... ok!
compile xcode... ok!
but, only cocos console compile appear ndk error.
so i replace only ndk revision r11 or revision r10.. worked fine.

**Comment by minggo** [comment]
@mquaker what i mean latest codes is the codes in github, not v3.12.

**Comment by Arman11** [comment]
I get latest version cocos2d-x v3 from github. Download latest NDK r12b. Create new project and try to compile for android.

cocos compile -p android

Android NDK: WARNING: APP_PLATFORM android-22 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml  
Android NDK: ERROR:/Users/.../proj.android/../cocos2d/external/freetype2/prebuilt/android/Android.mk:cocos_freetype2_static: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that /Users/.../proj.android/../cocos2d/external/freetype2/prebuilt/android/x86_64/libfreetype.a exists  or that its path is correct  
/Users/.../Library/Android/ndk/build/core/prebuilt-library.mk:45: **\* Android NDK: Aborting    .  Stop.
Error running command, return code: 2.

**Comment by minggo** [comment]
@Arman11 have you run `./downloade_deps.sh` to get corresponding 3rd party libraries?

**Comment by Arman11** [comment]
Yes of course
 $ cd cocos2d-x
 cocos2d-x $ python download-deps.py
and
cocos2d-x $ git submodule update --init

**Comment by minggo** [comment]
Oh, yep, i found the issue. cocos2d-x doesn't support x86_64. You can use `cocos compile -p android --app-abi armeabi` to compile it. I will fix it in template.

**Comment by minggo** [comment]
fixed in #16223

**Comment by SnowflakeTQ** [comment]
This conversation is sooooo funy 😄

**Comment by yhhwatl** [comment]
When to support the latest NDK version?

**Comment by dumganhar** [comment]
@yhhwatl, I have already tried to build cocos2d-x with the latest ndk version (android-ndk-r13b) and it works well.

**Comment by AgoraBeck** [comment]
In Application.mk, do some modification, as following: 

 APP_ABI := armeabi-v7a  \
              x86        \
              #arm64-v8a

That will be helpful.
