### ISSUE TITLE
提审的google商店的安装包被拒绝了

### ISSUE THREAD

**Issue by nanmuyao** [cocos2d/cocos2d-x#15564]
![nvomn ml fa 16b c atk](https://cloud.githubusercontent.com/assets/7760063/15012174/2e1116dc-1229-11e6-9e07-fdef3d3cb6fc.png)
上面是提示，我想在github cocos2dx 目录下的external目录中找到openssl编译后的类似libcrypto.a 这杨的文件但是没有找到@zilongshanren

**Comment by minggo** [comment]
Please refer to [this ticket](http://discuss.cocos2d-x.org/t/openssl-problem-again/28270/)

**Comment by minggo** [comment]
And there is a [blog](http://blog.cocos2d-x.org/2016/04/openssl-update/).

**Comment by nanmuyao** [comment]
@minggo I have done like the blog ，and then i need to Recompile ？？

**Comment by minggo** [comment]
yep, you need to recompile.

**Comment by nanmuyao** [comment]
oh my gold, i refused by googleplay again, this time it tips me  this [https://support.google.com/faqs/answer/6376725?hl=zh-Hant](google play tips) ,  first i use cocos version is v2.x,  i have done like the [http://blog.cocos2d-x.org/2016/04/openssl-update/](blog) , i guess the proplem is caused by  recompile . but i don't know how to do next
this  is my android.mk, and i have deleted my game class file ,i guess is the android.mk not include sopenssl libs. but i am not sure, thank you very much@minggo
`LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE:=libtersafe
LOCAL_SRC_FILES:=libtersafe.so
include $(PREBUILT_SHARED_LIBRARY)
include $(CLEAR_VARS)
LOCAL_MODULE := game_shared
LOCAL_MODULE_FILENAME := libgame
LOCAL_SRC_FILES := hellocpp/main.cpp \
                GameSdk.cpp \

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes \
$(LOCAL_PATH)/../../../cocos2dx/platform/android/jni \
LOCAL_WHOLE_STATIC_LIBRARIES := cocos2dx_static cocosdenshion_static cocos_extension_static cocos2dx-talkingdata cryptopp_static
LOCAL_SHARED_LIBRARIES:=libtersafe
include $(BUILD_SHARED_LIBRARY)

$(call import-add-path,$(LOCAL_PATH)/../../../)

$(call import-module,CocosDenshion/android) \
$(call import-module,cocos2dx) \
$(call import-module,extensions) \
$(call import-module,TalkingData/proj.android/jni)
$(call import-module,cryptopp562)
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE:=libtersafe
LOCAL_SRC_FILES:=libtersafe.so
include $(PREBUILT_SHARED_LIBRARY)
include $(CLEAR_VARS)
LOCAL_MODULE := game_shared
LOCAL_MODULE_FILENAME := libgame
LOCAL_SRC_FILES := hellocpp/main.cpp \
                GameSdk.cpp \

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes \
$(LOCAL_PATH)/../../../cocos2dx/platform/android/jni \ 
LOCAL_WHOLE_STATIC_LIBRARIES := cocos2dx_static cocosdenshion_static cocos_extension_static cocos2dx-talkingdata cryptopp_static
LOCAL_SHARED_LIBRARIES:=libtersafe
include $(BUILD_SHARED_LIBRARY)

$(call import-add-path,$(LOCAL_PATH)/../../../)

$(call import-module,CocosDenshion/android) \
$(call import-module,cocos2dx) \
$(call import-module,extensions) \
$(call import-module,TalkingData/proj.android/jni)
$(call import-module,cryptopp562)`

**Comment by minggo** [comment]
Does your own 3rd-party-library, such as `cocos2dx-talkingdata`, has OpenSSL codes that causes the issue?

**Comment by nanmuyao** [comment]
yes i used 3rd sdk and i use talkingdata for report some data in my game。

**Comment by minggo** [comment]
So you should check if it uses older version of OpenSSL that cause the problem.

**Comment by nanmuyao** [comment]
You mean the problem with the OpenSSL version is too older of the talkingdata used ，caused i was refused by google play

**Comment by minggo** [comment]
I just a guess. Because cocos2d-x itself only CURL uses OpenSSL, and it is not problem if you updated them because so many developers resolve the issue.

**Comment by nanmuyao** [comment]
![1](https://cloud.githubusercontent.com/assets/7760063/15061699/d3fbb01a-136a-11e6-9629-714309576b43.png)
thank you veru much, i'll check the 3rd sdk.

**Comment by minggo** [comment]
You should modify the deps version in [external/config.json](https://github.com/cocos2d/cocos2d-x/blob/v2/external/config.json) first as the blog said.

`"version":"v2-deps-5"`
