### ISSUE TITLE
utils::captureScreen memory leak

### ISSUE THREAD

**Issue by davidejones88** [cocos2d/cocos2d-x#15572]
Hi there!

I've been using the captureScreen command lately like this

```
utils::captureScreen(CC_CALLBACK_2(MenuGameLayer::afterCaptured, this), "capturescreen.png");
```

but I constantly have a memory leak which can increase the memory usage quite heavily if I take too many screenshots. (using xCode, iOS 9)

If I go into onCaptureScreen in ccUtils.cpp and return immediately like this

```
void onCaptureScreen(const std::function<void(bool, const std::string&)>& afterCaptured, const std::string& filename)
{
    return;
    ...
}
```

the leak does not occur. 

Any help? 

Davide

**Comment by davidejones88** [comment]
It looks like if I comment this line

`// succeedSaveToFile = image->saveToFile(outputFile);`

like this

```
            AsyncTaskPool::getInstance()->enqueue(AsyncTaskPool::TaskType::TASK_IO, mainThread, (void*)NULL, [image, outputFile]()
            {
                // succeedSaveToFile = image->saveToFile(outputFile);
                delete image;
            });
```

the leak does not occur.

Davide

**Comment by stevetranby** [comment]
Submitted a PR for this.
https://github.com/cocos2d/cocos2d-x/pull/15575
