### ISSUE TITLE
Quality low on iOS but Android (v. 3.10)

### ISSUE THREAD

**Issue by alankevin2** [cocos2d/cocos2d-x#15573]
Recently we found that the same app run on **iOS** and Android can result slight difference in quality.
The quality(images, labels) is better on **Android**.
For what comes to my mind in the first time, I thought of **retina** may not enabled on **iOS**, but with some time of research on the internet, it looked like **Cocos2d-x** now automatically enable **retina** for **iOS** now. 
Furthermore, it seems that labels is more blurred if run on **iOS**, this make me think that it is definitely not the "-hd" resources missing for **retina-use**.
Is there any config or setting to adjust something quality-related? I've tried _CEAGLView_ pixel format but with no luck.

Hope to see your response and support soon! 
Thanks in advance!

---

btw, if **Cocos2d-x** now turn on retina automatically, why the main.js still exist a code like :

> ```
> cc.view.enableRetina(true);
> ```

**Comment by cwasp** [comment]
I recently ran into this problem, and after some time found the cause of blurred images.
Antialias is enabled by default, so all images and text labels are blurred, if some transform with not integer coordinates are applied.

After I changed default antialiasEnabled to false, all images become clear.
Texture2D::Texture2D()
...
, _antialiasEnabled(false)//true)

FontAtlas::FontAtlas(Font &theFont) 
...
, _antialiasEnabled(false)//true)

I think that this is not quite right solution, but how to set antialiasing when you start the game, I haven't found.

If someone tells us a more flexible solution, I'll be happy to test it.

**Comment by alankevin2** [comment]
@cwasp Weird, I turn anti-alias to false and the quality became much worse.  
I think anti-alias is to make the quality better isn't it? 
Anyway, thanks for the reply!
I will keep looking for some answer on the internet.

**Comment by minggo** [comment]
@alankevin2 You can add search path based on resolution, please refer to [the sample](https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-empty-test/Classes/AppDelegate.cpp#L54) for detail information.

**Comment by cwasp** [comment]
@alankevin2  Then apparently you just not load proper HD graphics, and the @minggo advice should help.

**Comment by minggo** [comment]
@alankevin2 have you fixed the issue?

**Comment by redclock** [comment]
Do you have the launching images with the correct resolution? We solved a similar problem several days ago. At that time, we only prepared a iphone 5 launching image (640x1136) but no iphone 6 one (750x1334). So the quality was low because we only got a 640x1136 GL frame buffer in iPhone 6 and iPhone 6 Plus! After the proper launching images were prepared in the project, the quality became correct.

**Comment by alankevin2** [comment]
Hi, thanks for the reply.
I will pick up some time to try those solutions!
But I still wondering why the text in the labels are blurred? That's what I mentioned in the original post.
If the images are the case, why the label is somehow effected too?

> Furthermore, it seems that labels is more blurred if run on iOS, this make me think that it is definitely not the "-hd" resources missing for retina-use.

**Comment by minggo** [comment]
As i know the launching image size will affect resolution on iOS.

**Comment by alankevin2** [comment]
@minggo You saved our day**S**!!! The launching image **DOES** effect!
After I modify the launching image(I did not make a new picture, instead, just new a Launch Screen in storyboard and let the size class do the rest), the text in the label did become clearer 👍 
Much obliged !
But still wondering if this only effect on Cocos2d-x

**Comment by minggo** [comment]
I think it is the feature of iOS. The window size returned from iOS changed based on launching image size.

Can i close this issue?

**Comment by minggo** [comment]
ping @alankevin2

**Comment by alankevin2** [comment]
Yes, this actually solved the issue!

**Comment by semgilo** [comment]
> I recently ran into this problem, and after some time found the cause of blurred images.
> Antialias is enabled by default, so all images and text labels are blurred, if some transform with not integer coordinates are applied.

After I changed default antialiasEnabled to false, all images become clear.
Texture2D::Texture2D()
...
, _antialiasEnabled(false)//true)

FontAtlas::FontAtlas(Font &theFont) 
...
, _antialiasEnabled(false)//true)

I think that this is not quite right solution, but how to set antialiasing when you start the game, I haven't found.

If someone tells us a more flexible solution, I'll be happy to test it.


`@cwasp` @minggo  any flexible solution had found?

**Comment by minggo** [comment]
@semgilo i think it is another issue, could you please create a new one? Thanks.
