### ISSUE TITLE
Use clang toolchain for Android

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15577]
From http://developer.android.com/ndk/downloads/revision_history.html (history of r11)

> Clang
> Important announcements
> We strongly recommend switching to Clang.
> 
> GCC
> Important announcements
> GCC in the NDK is now deprecated in favor of Clang.

Works to do:
- choose `clang` toolchain in `cocos console`, refer to [this PR](https://github.com/cocos2d/cocos2d-console/pull/342)
- use `clang toolchain` to build 3rd party libraries of Android platform: #15781

**Comment by cezheng** [comment]
https://github.com/cocos2d/cocos2d-console/pull/342/files
I believe this PR is setting gcc 4.9 rather than clang as the toolchain, so we are still not able to use clang by cocos compile

**Comment by minggo** [comment]
@cezheng Thanks. I mentioned in the work to do above.

**Comment by crazyhappygame** [comment]
Please upgrade also NDK to latest version r11c. 
Currently for example:
`cocos gen-libs -p android` 
fails with android-ndk-r11c

**Comment by minggo** [comment]
change cocos console to clang: https://github.com/cocos2d/cocos2d-console/pull/350
