### ISSUE TITLE
These codes cause trouble:

### ISSUE THREAD

**Issue by gekailin** [cocos2d/cocos2d-x#15593]
In cocos/network/HttpClient-apple.mm line 174-177:

```
    if ([requestType isEqual: @"PUT"])
    {
        [nsrequest setValue: @"application/x-www-form-urlencoded" forHTTPHeaderField: @"Content-Type"];
    }
```

These codes set "Content-Type" for all "PUT" request, and I can't even override it. Maybe these code should test whether the headers set by user contains custom "Content-Type" first.

**Comment by minggo** [comment]
@gekailin I am not familiar with it, do you have any idea of it?

**Comment by minggo** [comment]
ok, it is duplicated with #15413
