### ISSUE TITLE
cocos2d-x 3.10 can't use png file to create sprite

### ISSUE THREAD

**Issue by UkiyoESoragoto** [cocos2d/cocos2d-x#15608]
engine: cocos2d-x
language: cpp
version: 3.10
work platform: mac osx
target platform: ios 9.3.1

error info: "libpng error: CgBI: unhandled critical chunk"

I cerate a new project and it can't use png to create sprite.
But jpg file is ok.
The HelloWorld.png is fine, but when I import myself png file, it can't be use.

FileUtils::getInstance()->isFileExist() 
show is the file is exist

FileUtils::getInstance()->fullPathForFilename()
can get file path too

Debug shows it interrupt at file 
cocos2d/cocos/platform/CCImage.cpp with line 1042
the function is png_read_info()
![image](https://cloud.githubusercontent.com/assets/7730737/15143621/3bde6572-16dd-11e6-9e9c-cf7cd40e727f.png)

I try it with iPhone6s, iPhone 5s, iPad mini 4, but every device is same error.

So where is wrong?

---

引擎: cocos2d-x
语言: cpp
版本: 3.10
工作平台: mac osx
目标平台: ios 9.3.1

报错：“libpng error: CgBI: unhandled critical chunk”

在下创建了一个新的项目，然后发现不能用png文件创造新的精灵，jpg倒是可以，然而并没有什么卵用。
项目自带的HelloWorld.png可以使用，但是任何我自己导入的png文件都不行。

我尝试用这个方法
FileUtils::getInstance()->isFileExist() 
但是它表示文件是存在的

FileUtils::getInstance()->fullPathForFilename()
也能找到文件路径

在Debug的时候我跟到
cocos2d/cocos/platform/CCImage.cpp 的第 1042 行就中断了，没有返回任何信息
上面有图这里就不重发了

另外在6s 5s iPad mini 4上我都有试过 全都GG

所以问题在哪儿呢？

求有关专家解释

**Comment by UkiyoESoragoto** [comment]
libpng error: CgBI: unhandled critical chunk

![image](https://cloud.githubusercontent.com/assets/7730737/15144112/e8c3d8ce-16df-11e6-9bc3-2f0ab252227d.png)

OK
It is not a error about cocos2d-x,  I'm so soory.

**Comment by YYXuelangwang** [comment]
I get this issue today, even i set the Build settings
![2017-05-12 11 09 29](https://cloud.githubusercontent.com/assets/16287226/25980799/9f9e81a4-3703-11e7-92ad-713a2d5347f8.png)
![2017-05-12 11 09 51](https://cloud.githubusercontent.com/assets/16287226/25980803/a406861a-3703-11e7-9423-d2f23107169c.png)
engine: cocos2d-x
language: cpp
version: 3.14.1
work platform: mac osx
xcode: 8.2.1
i have no ideal with this issue, anyone can help?
