### ISSUE TITLE
EGL_BAD_ALLOC crash on some android devices

### ISSUE THREAD

**Issue by dannyjiajia** [cocos2d/cocos2d-x#15602]
Hi guys, i found crashs on some android devices:

```
java.lang.RuntimeException
createWindowSurface failed EGL_BAD_ALLOC
android.view.HardwareRenderer$GlRenderer.createSurface(HardwareRenderer.java:1058)
android.view.HardwareRenderer$GlRenderer.createEglSurface(HardwareRenderer.java:946)
android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:780)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1696)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4607)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
android.view.Choreographer.doCallbacks(Choreographer.java:567)
android.view.Choreographer.doFrame(Choreographer.java:536)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:733)
android.os.Handler.handleCallback(Handler.java:615)
android.os.Handler.dispatchMessage(Handler.java:92)
android.os.Looper.loop(Looper.java:153)
android.app.ActivityThread.main(ActivityThread.java:5108)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
dalvik.system.NativeStart.main(Native Method)
```

[http://bugly.qq.com/share/IZnsQb](http://bugly.qq.com/share/IZnsQb)

I have use the cocos2dx 3.5,i have upgrade the `Cocos2dxActivity.java` file with the lastest version. But it's not working...

**Comment by minggo** [comment]
From the call stack, not cocos2d-x codes are invoked. Could you please try to run NDK gl related samples to check if it has problem or not.

I am not sure if i can find `Lenovo S890` to test. Does it has problem on other devices? Does the error happened all the time if it has problem on a devices or it just happens sometimes.

**Comment by dannyjiajia** [comment]
hi @minggo, thanks your reports.
I am not sure if the error happens sometimes,it's from bugly, and i have search the similar reports on google.  I think the bug maybe caused by the life cycle of SurfaceView or hardware acceleration.
[http://stackoverflow.com/questions/6039107/android-glsurfaceview-egl-bad-alloc](http://stackoverflow.com/questions/6039107/android-glsurfaceview-egl-bad-alloc)
[http://blog.csdn.net/yaphetzhao/article/details/48240073](http://blog.csdn.net/yaphetzhao/article/details/48240073)
[http://stackoverflow.com/questions/20152890/bug-createwindowsurface-failed-egl-bad-alloc](http://stackoverflow.com/questions/20152890/bug-createwindowsurface-failed-egl-bad-alloc)
Should i send this bug to the forum of cocos2dx?

**Comment by minggo** [comment]
@dannyjiajia it may be better to ask it in cocos2d-x forum, there are many developers there. And please add a link here after you crate a ticket in forum. Thanks.

**Comment by dannyjiajia** [comment]
thanks @minggo I have create a ticket:[http://discuss.cocos2d-x.org/t/egl-bad-alloc-crash-on-some-android-devices/29234](http://discuss.cocos2d-x.org/t/egl-bad-alloc-crash-on-some-android-devices/29234)
