### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found: 

### ISSUE THREAD

**Issue by daniaDlbani** [cocos2d/cocos2d-x#15616]
My cocos2dx app crash on the startup giving me unsatisfied link error:
I am using cocos2dx 2.2.6
compiling android project with android API 21
My ndk version is NDKr10c
this error occurs on android device with 4.4.2 os and the app is working on android5 and above

I was using NDK9 to avoid this [issue](https://github.com/cocos2d/cocos2d-x/issues/14034) and it was working on android 4+
but few weeks ago we get the Open SSL warning at the play store
solving it by update my curlLib as mention [here](http://discuss.cocos2d-x.org/t/openssl-problem-again/28270)
then I can't build it so I upgrade my NDK to the latest version found on android developer website which was NDKr11c then I failed to build my project and face the issue reported [here](https://github.com/cocos2d/cocos2d-x/issues/15417)
they advice to use NDKr10c and I am stuck at this loop and here the error log
any help will be appreciated

05-08 10:29:56.581: E/AndroidRuntime(11183): FATAL EXCEPTION: main
05-08 10:29:56.581: E/AndroidRuntime(11183): Process: ae.test.test, PID: 11183
05-08 10:29:56.581: E/AndroidRuntime(11183): java.lang.UnsatisfiedLinkError: Native method not found: org.cocos2dx.lib.Cocos2dxHelper.nativeSetApkPath:(Ljava/lang/String;)V
05-08 10:29:56.581: E/AndroidRuntime(11183): at org.cocos2dx.lib.Cocos2dxHelper.nativeSetApkPath(Native Method)
05-08 10:29:56.581: E/AndroidRuntime(11183): at org.cocos2dx.lib.Cocos2dxHelper.init(Cocos2dxHelper.java:71)
05-08 10:29:56.581: E/AndroidRuntime(11183): at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:69)
05-08 10:29:56.581: E/AndroidRuntime(11183): at ae.test.test.testapp.onCreate(testapp.java:62)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.app.Activity.performCreate(Activity.java:5322)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2303)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.app.ActivityThread.access$900(ActivityThread.java:166)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.os.Handler.dispatchMessage(Handler.java:102)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.os.Looper.loop(Looper.java:146)
05-08 10:29:56.581: E/AndroidRuntime(11183): at android.app.ActivityThread.main(ActivityThread.java:5511)
05-08 10:29:56.581: E/AndroidRuntime(11183): at java.lang.reflect.Method.invokeNative(Native Method)
05-08 10:29:56.581: E/AndroidRuntime(11183): at java.lang.reflect.Method.invoke(Method.java:515)
05-08 10:29:56.581: E/AndroidRuntime(11183): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
05-08 10:29:56.581: E/AndroidRuntime(11183): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
05-08 10:29:56.581: E/AndroidRuntime(11183): at dalvik.system.NativeStart.main(Native Method)

**Comment by minggo** [comment]
It is strange, it related with NDK version and Android OS version. I think it is a problem of NDK though i don't have any clue.

**Comment by daniaDlbani** [comment]
I found that there is someone at cocos team reported similar  [issue](https://code.google.com/p/android/issues/detail?id=73907)
 and they announce that it is fixed at the new NDK12beta1
but trying it I am getting new build errors something like this:

[armeabi] SharedLibrary  : libcocos2dcpp.so
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(libwebsockets.c.o):libwebsockets.c:function libwebsocket_create_context: error: undefined reference to 'getdtablesize'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(libwebsockets.c.o):libwebsockets.c:function libwebsocket_create_context: error: undefined reference to 'bsd_signal'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(daemonize.c.o):daemonize.c:function lws_daemonize: error: undefined reference to 'bsd_signal'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(daemonize.c.o):daemonize.c:function lws_daemonize: error: undefined reference to 'bsd_signal'
./MyProject/cocos2d-x-2.2.6/external/libwebsockets/android/./lib/armeabi/libwebsockets.a(daemonize.c.o):daemonize.c:function lws_daemonize: error: undefined reference to 'bsd_signal'
collect2: error: ld returned 1 exit status
make: **\* [obj/local/armeabi/libcocos2dcpp.so] Error 1

any suggestions or work around!

**Comment by daniaDlbani** [comment]
finally I manage to solve it and [here](http://stackoverflow.com/questions/31516952/cocos2d-x-java-lang-unsatisfiedlinkerror-app-crash-on-startup?noredirect=1#comment50995473_31516952) what I did

**Comment by minggo** [comment]
the issue is fixed in #16267
