### ISSUE TITLE
ui::EditBox random crash on iOS

### ISSUE THREAD

**Issue by robslove** [cocos2d/cocos2d-x#15613]
random crash or black screen  on 

textFieldShouldEndEditing...

**\* Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 512]'

**Comment by liuyi** [comment]
I think you should check your code, because we can find the reason is that:"NaN".

Maybe you code generate an NaN value, and set it to layer's position.

**Comment by zilongshanren** [comment]
@robslove  
I agree with @liuyi   please check your code.
If you still have this issue, feel free to reopen this issue again.
