### ISSUE TITLE
Make error @ jscocos target

### ISSUE THREAD

**Issue by ehthxC7x9D** [cocos2d/cocos2d-x#15624]
Ubuntu 16.04

While running make in /linux-build:

```
cocos/scripting/js-bindings/CMakeFiles/jscocos2d.dir/build.make:62: recipe for target 'cocos/scripting/js-bindings/CMakeFiles/jscocos2d.dir/auto/jsb_cocos2dx_auto.cpp.o' failed
make[2]: *** [cocos/scripting/js-bindings/CMakeFiles/jscocos2d.dir/auto/jsb_cocos2dx_auto.cpp.o] Error 1
CMakeFiles/Makefile2:1044: recipe for target 'cocos/scripting/js-bindings/CMakeFiles/jscocos2d.dir/all' failed
make[1]: *** [cocos/scripting/js-bindings/CMakeFiles/jscocos2d.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by teosbpl** [comment]
Clone of of PR #15522

**Comment by teosbpl** [comment]
It may be related with compilation using many jobs (as make -j4 in my case). Running 'make -j4' several times fixed the problem. There apparently is a problem with precedence of build targets, which I'm unable to solve.

**Comment by minggo** [comment]
@e-ht i don't have the problem, i used ubuntu 16.04 too.

**Comment by ghost** [comment]
Still getting this error. Any workaround? I tried 'make -j4' quite a times, but no luck.
Using Ubuntu 16.04

EDIT: Got it working. Command 'make -j4' did not work for me though. Instead, replacing 'isnan' with 'std::isnan' in few other cpp files [the one's that caused the error (Eg. file `jsb_cocos2dx_auto.cpp` according to error posted above)] did the trick.

**Comment by e-ht** [comment]
I've given up and happily moved forward with LibGDX. Cocos2d has proven dysfunctional and inconsistent on Linux and even a messy hassle installing on OSX.  At this point, unless you use Windows (which I only assume works) I suggest you move on.

**Comment by ghost** [comment]
It's working now :)
