### ISSUE TITLE
some compiling errors in js-bindings*

### ISSUE THREAD

**Issue by Joilnen** [cocos2d/cocos2d-x#15621]
Linux
gcc 5.3 glibc 2.23
## I fixed including cmath  and using namespace std;, c includes like math.h seems doesn't works, anyway reporting.

 /home/joilnen/cocos2d-x_devel/my/cocos2d-x_HEAD_09_05_2016/cocos/scripting/js-bindings/manual/js_manual_conversions.cpp:1660:13: error: 'isnan' was not declared in this scope
     !isnan(x) && !isnan(y);
             ^
/home/joilnen/cocos2d-x_devel/my/cocos2d-x_HEAD_09_05_2016/cocos/scripting/js-bindings/manual/js_manual_conversions.cpp:1660:13: note: suggested alternative:
In file included from /home/joilnen/cocos2d-x_devel/my/cocos2d-x_HEAD_09_05_2016/cocos/scripting/js-bindings/../../../external/spidermonkey/include/linux/mozilla/MathAlgorithms.h:15:0,
                 from /home/joilnen/cocos2d-x_devel/my/cocos2d-x_HEAD_09_05_2016/cocos/scripting/js-bindings/../../../external/spidermonkey/include/linux/mozilla/FloatingPoint.h:15,
                 from /home/joilnen/cocos2d-x_devel/my/cocos2d-x_HEAD_09_05_2016/cocos/scripting/js-bindings/../../../external/spidermonkey/include/linux/jsapi.h:12,
                 from /home/joilnen/cocos2d-x_devel/my/cocos2d-x_HEAD_09_05_2016/cocos/scripting/js-bindings/manual/js_manual_conversions.h:28,
                 from /home/joilnen/cocos2d-x_devel/my/cocos2d-x_HEAD_09_05_2016/cocos/scripting/js-bindings/manual/js_manual_conversions.cpp:25:
/usr/include/c++/5.3.0/cmath:641:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
#

**Comment by minggo** [comment]
did you use latest codes? i think it is fixed

**Comment by minggo** [comment]
Fixed in this #15687
