### ISSUE TITLE
Supporting IPv6-only Networks

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15629]
As [apple required to support IPv6-only Networks](https://developer.apple.com/news/?id=05042016a) since June 1, 2016. So we need to make sure cocos2d-x can work on IPv6-only Networks.

I think we should check
- 3rd party libraries supports IPv6-only networks
  - [x]  CURL
  - [x]   websocket
  
  any other?
- cocos2d-x provided network modules support IPv6-only networks
  - [x] HttpClient
  - [x] AssetsManagerEx
  - [x] SocketIO
  - [x] WebSocket
  - [x] Console
  - [x] ScriptingCore
  
  any else?

Found module that use IPV4 specific API:
- [serverEntryPoint in ScriptingCore](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/manual/ScriptingCore.cpp#L1883)

**Comment by minggo** [comment]
[this doc](https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1)  is a good material about how to support IPv4/v6 together and test IPv6 compatibility.

**Comment by minggo** [comment]
@zilongshanren Please help to check the 3rd party libraries supports IPv6.

**Comment by cezheng** [comment]
is cURL still used in iOS? I guess since 3.9 it has been removed from the xcodeproj's link options

**Comment by minggo** [comment]
@cezheng CURL is not used in cocos2d-x itself, but it is shift with cocos2d-x, so we should make sure it supports IPv6 too.

**Comment by yafen** [comment]
Hi, just test my cocos2d-x project  for IPv6 DNS64/NAT64 Compatibility by following Apple Doc. It fails to communicate with the server. We use HttpClient in our case. Any update at your side?

**Comment by minggo** [comment]
@yafen thanks for testing. I will test it today.

**Comment by minggo** [comment]
@yafen I just tested with `cpp-tests/Extensions/HttpClientTest` by following Apple Doc, the it works great. What's your cocos2d-x version? And other developer also said v3.11 works as expected in [this ticket](http://discuss.cocos2d-x.org/t/supporting-ipv6-only-networks/29266).

**Comment by minggo** [comment]
libwebsocket supports IPv6 is fixed in this PR: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/219. Other platforms supporting will be added soon.

Edit: linux platform supports IPv6: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/220

**Comment by minggo** [comment]
Console and ScriptingCore add ipv6 compatibility support is fixed in #15654.

**Comment by minggo** [comment]
SocketIO depends on libwebsocket, so there is not problem.

**Comment by yafen** [comment]
Thx for updating. We use cocos2dx 2.2.6. So have to update to version 3.11?

**Comment by minggo** [comment]
No, you just need to update libwebsocket and libcurl, becuase libcurl supports IPv6 in v3.10.

**Comment by yafen** [comment]
ok. will try. thx.

**Comment by minggo** [comment]
You are welcome.

**Comment by minggo** [comment]
v2 branch is fixed in #15666 , windows and wp8 has not been updated, waiting @stammen 's  update.
@yafen you can refer to the PR, it also needs to modify some cpp codes to use new version of libwebsockets.

@yafen to be more clear, should refer to [this commit](https://github.com/cocos2d/cocos2d-x/pull/15666/commits/43dd696750014efa9b0419a59f72ba1c4cdaba50) to fix compiling error.

**Comment by jamjamcat** [comment]
Hi zhangxm

Thank you, but I'm using cocos2dx v2.2.2.

Cocos2d-x root/external/config.json and download-deps.py scripts don't exist in v2.2.2.
Please tell me what to do, to update libwebsockets and CURL in cocos2dx v2.2.2.

Thank you.

**Comment by minggo** [comment]
@jamjamcat you can down load the libraries [here](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/releases).

**Comment by minggo** [comment]
To be more clearly, it is [here](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/releases/tag/v2-deps-6)

**Comment by minggo** [comment]
libwebsocket for windows is updated by this PR: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/224, it is included in v2-deps-v7. And the corresponding PR for cocos2d-x is #15704

**Comment by cezheng** [comment]
After gradle support and this IPv6 support update, will there be a new release?

**Comment by minggo** [comment]
About IPv6 support, i think you just need to update 3rd party libs. And gradle support is not ready, there is bug about apk size.

There is not plan to release a new version currently. I think we can release it if we find and fix Android performance issue.

**Comment by luckyouch** [comment]
@minggo  I found a strange status:
My project is developed with cocos2d-x 2.2.2, I update the libcurl.a from cocos2d-x 3.10, then build successful, and when tested success for ipv6 in simulator on iOS, But failed when I burned it to any ios device. All http requests failed with Timeout error.
So I don't know how to fix it.

**Comment by minggo** [comment]
Did you test on IPv6-only network? And does your device network is good?

**Comment by luckyouch** [comment]
Yes, I test it on ipv6-only network as the doc above. and my network is good because I test some other apps, some test well.

**Comment by minggo** [comment]
Would you please use latest CURL? I tested with it, i don't test on v3.10.

**Comment by luckyouch** [comment]
If I use latest libcurl.a and libssl.a in v3.11, my project will occurs some link error about ssl. So I use them in v3.10 as you say above.

**Comment by minggo** [comment]
The latest is not v3.11, it is the link: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/releases/tag/v3-deps-95

**Comment by luckyouch** [comment]
OK, thanks, I will try it.

**Comment by luckyouch** [comment]
@minggo  fortunatly, it works, but I don't know does the version supply 64-bits?

**Comment by minggo** [comment]
@youchlucky This version is the same as before except supporting IPv6.

**Comment by jasonz1987** [comment]
is luasocket support ipv6?i cant not connect server in my game?

**Comment by minggo** [comment]
@jasonz1987 I am not sure. I din't test luasocket. It is missed. But we use source code of luasocket, so i think if it doesn't support IPv6-only, then we can do nothing.

**Comment by zhoujianghai** [comment]
My project was developed with cocos2d-x 2.1.5, I updated the libcurl.a from v2-deps-v7, but build error with arm64, the version of libcurl.a not supporting 64-bits?
the error log info:
Undefined symbols for architecture arm64:
  "_MD4_Init", referenced from:
      _Curl_ntlm_core_mk_nt_hash in libcurl.a(libcurl_la-curl_ntlm_core.o)
  "_MD4_Update", referenced from:
      _Curl_ntlm_core_mk_nt_hash in libcurl.a(libcurl_la-curl_ntlm_core.o)
  "_MD4_Final", referenced from:
      _Curl_ntlm_core_mk_nt_hash in libcurl.a(libcurl_la-curl_ntlm_core.o)
  "_UI_get_string_type", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
      _ssl_ui_writer in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_get_reader", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
  "_UI_set_result", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
  "_SSL_write", referenced from:
      _ossl_send in libcurl.a(libcurl_la-openssl.o)
  "_SHA256_Init", referenced from:
      _Curl_ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_SHA256_Final", referenced from:
      _Curl_ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_MD5_Update", referenced from:
      _Curl_ossl_md5sum in libcurl.a(libcurl_la-openssl.o)
      _Curl_md5it in libcurl.a(libcurl_la-md5.o)
      _Curl_HMAC_MD5 in libcurl.a(libcurl_la-md5.o)
      _Curl_DIGEST_MD5 in libcurl.a(libcurl_la-md5.o)
  "_MD5_Final", referenced from:
      _Curl_ossl_md5sum in libcurl.a(libcurl_la-openssl.o)
      _Curl_md5it in libcurl.a(libcurl_la-md5.o)
      _Curl_HMAC_MD5 in libcurl.a(libcurl_la-md5.o)
      _Curl_DIGEST_MD5 in libcurl.a(libcurl_la-md5.o)
  "_RAND_load_file", referenced from:
      _Curl_ossl_seed in libcurl.a(libcurl_la-openssl.o)
  "_RAND_status", referenced from:
      _Curl_ossl_seed in libcurl.a(libcurl_la-openssl.o)
  "_SSLeay", referenced from:
      _Curl_ossl_version in libcurl.a(libcurl_la-openssl.o)
     (maybe you meant: __ZN4NGcp11RAND_SSLeayEv, __ZN4NGcp16RSA_PKCS1_SSLeayEv )
  "_SSL_pending", referenced from:
      _Curl_ossl_data_pending in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_alpn_protos", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_default_passwd_cb_userdata", referenced from:

**Comment by jasonz1987** [comment]
@zhoujianghai you must also include `libcrypto.a` `libssl.a` in your project,then your question will be fixed~

**Comment by zhoujianghai** [comment]
@jasonz1987 thanks, build success!
