### ISSUE TITLE
Cocos2d-x 3.11: PageView::setCurrentPageIndex does not trigger event "PageView::EventType::TURNING"

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#15631]
I don't know if this is a bug or a design choice, but when it is called setCurrentPageIndex() on a PageView object the event PageView::EventType::TURNING does not trigger!
PageView::scrollToPage() does trigger the event PageView::EventType::TURNING correctly, but only when scroll ends.
Sometimes can be useful to jump immediately to a page triggering the turning event!

**Comment by davidchai-6waves** [comment]
I think it should be fixed in v3.11, you can check the latest CHANGE_LOG here.
I am so sure, because that is the one of the reason i upgraded to 3.11

**Comment by minggo** [comment]
@zilongshanren please take a look

**Comment by zilongshanren** [comment]
@Drakon-Cocos 
I think you could emit a custom event when you call `setCurrentPageIndex`.
I'm not sure whether the PageView event will be triggered on other platforms. For example, does iOS and Android also behavior this way? If so, please show me the docs and I will consider to change the current implementation.

Thanks.

**Comment by alfogrillo** [comment]
@zilongshanren 
The PageView event is triggered both on iOS and Android when scroll to destination page ends.
For now in my project I inherited PageView class adding the following member function

```
void PageViewCustom::setCurrentPageIndex(ssize_t index)
 {
     PageView::setCurrentPageIndex(index);
     pageTurningEvent();
}
```

This solution works well both on iOS and Android (I also use buttons to scroll PageView and I need PageView::EventType::TURNING to update contents).
Anyway if things does not chanced recently, `PageView::setCurrentPageIndex` is not `virtual`, then this solution is not ideal!

**Comment by xschool2010** [comment]
it still doesn't work on iOS... @Drakon-Cocos

**Comment by alfogrillo** [comment]
@xschool2010 
What does not work?
I use my custom `PageViewCustom` both on iOS (8.4) and Android and work properly!
Anyway as I said before this solution is not ideal because `PageView::setCurrentPageIndex` is not `virtual`!
If you do something like that, the event  PageView::EventType::TURNING will not be triggered:

```
PageView* pageView = PageViewCustom::create();
/* add pages */
pageView->setCurrentPageIndex(0); // called PageView implementation, not PageViewCustom!
```

**Comment by alfogrillo** [comment]
My proposal to fix this:
https://github.com/cocos2d/cocos2d-x/pull/16002
