### ISSUE TITLE
Cocos2d-x 3.11: PhysicsBody damping does not work [WITH SOLUTION]

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#15630]
In cocos2d-x 3.11 the damping does not work.
I figure out the lines 776:781 in file CCPhysicsBody.cpp were left commented!
Un-commenting these lines damping seems to work fine!

**Comment by minggo** [comment]
@ricardoquesada could you please take a look?

**Comment by minggo** [comment]
@ricardoquesada i found you comment these codes, is there any reason?

**Comment by ricardoquesada** [comment]
@minggo bug I guess
