### ISSUE TITLE
Minimizing window on desktop causes drop of _designResolutionSize

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#15636]
Version: cocos 3.11, OS: Windows 10.

onGLFWWindowSizeFunCallback was changed so that it's calling setFrameSize on window minimizing/maximizing. 
It causes drop of _designResolutionSize value (initial value not restored). Should I restore it manually now after minimize/maximize, or it's a bug?

(Looks like it finally fired : 
http://discuss.cocos2d-x.org/t/potential-bug-in-cceglviewprotocol-setframesize/10796)

**Comment by AIGRIND-LLC** [comment]
Bug is confirmed with CPP-Test on Windows 10.

Before the window is minimized:
![cpp-test1](https://cloud.githubusercontent.com/assets/6168693/15245302/f8a32ee8-1905-11e6-882b-85982faaefa8.png)

After the window is restored:
![cpp-test2](https://cloud.githubusercontent.com/assets/6168693/15245318/0bb9d9be-1906-11e6-8dcd-1ff64d5c3e10.png)

**Comment by larsven** [comment]
It seems setting design resolution manually after restore does not work.

**Comment by larsven** [comment]
There is an attempt to fix it here: https://github.com/cocos2d/cocos2d-x/commit/061fc2f28773447d817e6152a0f2b857295a0305, but it does not fully solve the problem

**Comment by larsven** [comment]
There is a fix here that solves the problem: https://github.com/cocos2d/cocos2d-x/commit/061fc2f28773447d817e6152a0f2b857295a0305

**Comment by minggo** [comment]
Yep, it is fixed in latest code.
