### ISSUE TITLE
[BUG] version3.11 pro.android/build_native.py  has error path.

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#15642]
LINE 139 

 resources_dir = os.path.join(app_android_root, "../../../frameworks/cocos2d-x/cocos/js-bindings/bindings/script")

SHOULD BE:
resources_dir = os.path.join(app_android_root, "../../../frameworks/cocos2d-x/cocos/scripting/js-bindings/script")

error info:

No such file or directory: '/Volumes/data/work/temp/test/frameworks/runtime-src/proj.android/../../../frameworks/cocos2d-x/cocos/js-bindings/bindings/script'

**Comment by minggo** [comment]
Please use cocos command instead.

**Comment by minggo** [comment]
build_native.sh will be removed.
