### ISSUE TITLE
Experimental::AudioPlayer stopped playing sounds after 10 min of game play

### ISSUE THREAD

**Issue by Kotaiba** [cocos2d/cocos2d-x#15661]
After around 10 min of playing on my game the AudioPlayer stopped playing the audio and start giving me this message on play2d .

cocos2d::experimental::AudioPlayer::play2d(cocos2d::experimental::AudioCache *):alGenBuffers error code:a003
I tried to clear the cash and re cash on replacing the scenes and it did't fix it . 
i tried to

experimental::AudioEngine::end();
But the game crash .

**Comment by minggo** [comment]
What's the engine version?
How can i reproduce it?
What's the Android OS version?
What's the device?

**Comment by Kotaiba** [comment]
1-Cocos2d-x 3.10 C++ .
2- My game run around 10 to 24 sounds at the same time( 5 running all the time and 19 on and off)  so you can say 24 max at the same time . after playing for like 10 to 15 min .60% of the sounds will stop working and this error message show every time it try to play sound effect (Will Show On Log).
`cocos2d::experimental::AudioPlayer::play2d(cocos2d::experimental::AudioCache *):alGenBuffers error code:a003`
removing the cashed and re-cash them will not solve it .
3-for now i only test it on real device iPhone 6 and iPhone 6+ .and both have this bug.

**Comment by minggo** [comment]
Could you please give a sample code to reproduce it?
Thanks.

**Comment by Kotaiba** [comment]
i think the bug related to 
`void AudioEngine::stop(int audioID)`
i've got it fixed after making sure that the audio `state == AudioState::PLAYING `before calling any `AudioEngine::stop`

**Comment by Kotaiba** [comment]
i think its related to `experimental::AudioEngine::stop` i will keep testing to find out what reproduce it.

**Comment by Kotaiba** [comment]
So far i have no idea how this exactly reproduce. 
Is there any way i can restart the AudioEngine . i tried `experimental::AudioEngine::end` but the game always crash . if you could help me with that so i can test it .

**Comment by minggo** [comment]
There is not other way to restart AudioEngine.

**Comment by joewan** [comment]
I have also met the same problem, I think the audio bug is a serious bug. I feel very disappointed with cocos, this bug has existed a century. Everytime you ask us to reproduce  this bug, obviously it is very difficult to reproduce. and why you do not provide a restartAudioEngine interface? 
http://forum.cocos.com/t/cocos2d-js-3-6-mp3/36614
http://forum.cocos.com/t/cocos2dx3-10-bug/36710
http://forum.cocos.com/t/cocos2dx-3-x-audioengine-bug/35920

there are so many audio bugs, can you make some more pressure testings for audio engine?
can you provide restartAudioEngine interface?

@walzer @minggo @WenhaiLin

**Comment by minggo** [comment]
@joewan it is because android has so many devices and so OS version, the issue doesn't happen on all devices. As you know, sometimes it happened on some devices with some specific OS version. So we need a way to reproduce it, then we can verify if it is fixed or not.

> there are so many audio bugs, can you make some more pressure testings for audio engine?
> can you provide restartAudioEngine interface?

Yep, i think we need to do more testing. And restartAudioEngine, i am not sure it it can help or not. AudioEngine uses OpenSL ES on Android, if the state of OpenSL ES is affected, i am not sure if it can be reset or not. I will do more test.

**Comment by joewan** [comment]
this bug almost happens on on all devices,  at least iPhone 6s (os version 9.3.2).
thanks very much for immediate response.

**Comment by minggo** [comment]
@joewan Do you have codes to reproduce easily? This issue is about on iOS, but your link above is about on Android. Audio engine implementation is different in these two platforms.

**Comment by Kotaiba** [comment]
This is the code that coz the Bug.(I have trains running on the map i need the audio to play when it get closer to my hero and stop if it gets far ) ,Hope it will help .  

```
//Update Function 
int i=0;

    for ( auto &train: trainsArray )
    {
        float value=train->getPosition().distance(car->getPosition());
        if (value<1500) {
            if (  experimental::AudioEngine::getState( trainsAudio[i])!=experimental::AudioEngine::AudioState::PLAYING) {
                trainsAudio[i] =  KJAudioEngine::getInstance()->playEffect("sounds/Train.mp3", true,0);
                if ( trainsAudio[i] ==-1) {
                    //Audio Stopped
                }
            }
            if (value<200) {

                KJAudioEngine::getInstance()->setVolume(trainsAudio[i], 1);
            }else{
                value=(value/200);
                KJAudioEngine::getInstance()->setVolume(trainsAudio[i], 1/value);
            }

        }else{
            if (trainsAudio[i]!=0&&  experimental::AudioEngine::getState( trainsAudio[i])==experimental::AudioEngine::AudioState::PLAYING) {
                experimental::AudioEngine::stop(trainsAudio[i]);

                trainsAudio[i]=0;
            }

        }
        i++;
    }

//Destructor
 int i=0;
for ( auto &train: trainsArray )
    {
        if (trainsAudio[i]!=0&&(experimental::AudioEngine::getState( trainsAudio[i])==experimental::AudioEngine::AudioState::PLAYING)) {
            experimental::AudioEngine::stop(trainsAudio[i]);
            trainsAudio[i]=0;
        }

        i++;
    }
```

**Comment by minggo** [comment]
@Kotaiba Sorry, what did you modify? I am doing testing, playing 13 sound/effect all the time, and haven't found the issue.

**Comment by Kotaiba** [comment]
i test that too ,playing sounds is not the issue , after testing on my project found that the code above coz the bug to happen .

**Comment by Kotaiba** [comment]
ive modifed the error code : cocos2d::experimental::AudioPlayer::play2d(cocos2d::experimental::AudioCache *):alGenBuffers error code:a003

**Comment by Kotaiba** [comment]
One more thing , the audio will play normally but when ever i play `Train.mp3` again the audio will stop ,So if `Train.mp3` is not running the audio will play perfectly.

**Comment by minggo** [comment]
@Kotaiba I added log in [this commit](https://github.com/minggo/cocos2d-x/commit/0e6b4116a54cea66019869737d8808b3b8d3dd42), will you apply the modification of `cocos/audio/apple/AudioPlayer.mm`, then it will print which line caused the error.

And you can take a look of [this doc](http://forum.sparrow-framework.org/topic/spsound-error-could-not-allocate-openal-buffer-a003). It seems need to check `_sourceId` before invoking `alSourceStop()`. Would you please have a try?

**Comment by minggo** [comment]
> One more thing , the audio will play normally but when ever i play Train.mp3 again the audio will stop ,So if Train.mp3 is not running the audio will play perfectly.

Did you mean can not play the same audio more than one time?

**Comment by Kotaiba** [comment]
I mean After the bug happen ,It happen on 1 audio but it will effect all the running audios cozing them to stop also ,so if that bugged audio play again the other audios will stop also .and if its stopped the audio will work again.

**Comment by Kotaiba** [comment]
Will test the code now .

**Comment by minggo** [comment]
Thanks.

**Comment by Kotaiba** [comment]
`openal error code: 0 line: 232`

**Comment by Kotaiba** [comment]
Let me know if you need me to test anything else.

**Comment by minggo** [comment]
@Kotaiba Thanks. I have to analyze it, then make a new patch to ask your help.

**Comment by minggo** [comment]
Oh, sorry, could you please modify the macro of `ERROR_CHECK()` to

``` c++
#define ERROR_CHECK() \
if (int errorcode = alGetError() != GL_NO_ERROR) \
{ \
    printf("openal error code: %d line: %d", errorcode, __LINE__); \
}

```

and test again? The previous version lost error code.
Thanks.

**Comment by Kotaiba** [comment]
`openal error code: 1 line: 232`

**Comment by minggo** [comment]
@Kotaiba sorry, i reviewed the codes, and can not find the bug. Does `openal error code: 1 line: 232` happened immediately or it is about 10 minutes later after playing as before?

**Comment by Kotaiba** [comment]
It happen after 5-10 min of playing .

**Comment by Kotaiba** [comment]
line: 232 ,is on play2d or on stop ?

**Comment by minggo** [comment]
It is the line number of `AudioPlayer.mm`.

**Comment by Kotaiba** [comment]
i know i mean is the error related to AudioEngine::stop or AudioEngine::play2d ?

**Comment by minggo** [comment]
I think it is related with AudioEngine::play2d(). But you can try to check the value before stop and have a try.

**Comment by Kotaiba** [comment]
I've tried to check the value ,it did't solve it .

**Comment by minggo** [comment]
Some comments about your codes:

``` c++
//Update Function 
int i=0;

    for ( auto &train: trainsArray )
    {
        float value=train->getPosition().distance(car->getPosition());
        if (value<1500) {
            if (  experimental::AudioEngine::getState( trainsAudio[i])!=experimental::AudioEngine::AudioState::PLAYING) {
                trainsAudio[i] =  KJAudioEngine::getInstance()->playEffect("sounds/Train.mp3", true,0);
                if ( trainsAudio[i] ==-1) {
                    //Audio Stopped
                }
            }
            if (value<200) {

                KJAudioEngine::getInstance()->setVolume(trainsAudio[i], 1);
            }else{
                value=(value/200);
                KJAudioEngine::getInstance()->setVolume(trainsAudio[i], 1/value);
            }

        }else{
            if (trainsAudio[i]!=0&&  experimental::AudioEngine::getState( trainsAudio[i])==experimental::AudioEngine::AudioState::PLAYING) {
                experimental::AudioEngine::stop(trainsAudio[i]);

                trainsAudio[i]=0; // i think it is better to set to -1, since -1 is not valid
            }

        }
        i++;
    }

//Destructor
 int i=0;
for ( auto &train: trainsArray )
    {
        if (trainsAudio[i]!=0&&(experimental::AudioEngine::getState( trainsAudio[i])==experimental::AudioEngine::AudioState::PLAYING)) {
            experimental::AudioEngine::stop(trainsAudio[i]);
            trainsAudio[i]=0; // i think it is better to set to -1, since -1 is not valid
        }

        i++;
    }
```

**Comment by joewan** [comment]
audio engine always goes wrong on ios device in our game，can you add some key logs and we can reproduce this problem easily，then we give you the log information.

**Comment by Kotaiba** [comment]
Hi, you guys doing great job on cocos2d-x but why the bugs on audio, i have big game and the game is bug free except the audio engines bugs the bug above and another bug is the game crash on
 (
AudioCache.mm file ios random crash happen around every 20 to 100 lunch it crashes 1 time on iphone 6 cocos2d-x 3.10 

`void AudioCache::readDataTask()`
line 160
        `alGenBuffers(1, &_alBufferId);`
)

**Comment by joewan** [comment]
I have met the same problem, our game is also bug free except the audio engines bugs. @Kotaiba

**Comment by minggo** [comment]
Hi guys, i need your help to reproduce the bug. Now i can not reproduce it.

**Comment by Kotaiba** [comment]
@minggo  please let me know if you need me to do anything for you I'm all yours

**Comment by minggo** [comment]
@Kotaiba Thanks. You are appreciated if you can give me an example to reproduce the issue easily.

**Comment by Kotaiba** [comment]
@minggo i Emailed you a project the project is crashing and showing `cocos2d::experimental::AudioPlayer::play2d(cocos2d::experimental::AudioCache *):alGenBuffers error code:a003` message randomly

**Comment by minggo** [comment]
@Kotaiba Thanks, i received it.

**Comment by dumganhar** [comment]
@Kotaiba , thanks for your feedback. I'll dig into the issue. :)

**Comment by joewan** [comment]
。。。。。。。。

**Comment by dumganhar** [comment]
Don't worry, guys, I'm checking this issue. :)

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/16147.
Could you test it and give me the feedback? Thanks.

**Comment by dumganhar** [comment]
@Kotaiba @joewan

**Comment by dumganhar** [comment]
Duang~~

**Comment by minggo** [comment]
@Kotaiba will you please take a try and give the feedback, thanks.

**Comment by Kotaiba** [comment]
@dumganhar @minggo I've test it ,so far so good ,No bugs ,will keep testing to make sure . did the bug with random crashes at the start fixed too ?

**Comment by dumganhar** [comment]
@Kotaiba , good to know that it works now.

> did the bug with random crashes at the start fixed too ?

Where did this issue reported?

**Comment by Kotaiba** [comment]
i reported the bug as comment look above u can fine it .

```
 another bug is the game crash on
(
AudioCache.mm file ios random crash happen around every 20 to 100 lunch it crashes 1 time on iphone 6 cocos2d-x 3.10

void AudioCache::readDataTask()
line 160
alGenBuffers(1, &_alBufferId);
)
```

**Comment by dumganhar** [comment]
@Kotaiba 
I didn't reproduce the startup crash problem.
Anyway, I create a new issue at https://github.com/cocos2d/cocos2d-x/issues/16170 .
Is there an easier way for being reproduced?

**Comment by Kotaiba** [comment]
I think there is no easier way .since its on the start of the game only.
please see our new game its ready for ios but i was waiting for the bugs to be fixed, we will lunch it first on steam let me know if you like it . http://steamcommunity.com/sharedfiles/filedetails/?id=714856182

**Comment by dumganhar** [comment]
@Kotaiba , it's cool. I'll play it.

> please see our new game its ready for ios but i was waiting for the bugs to be fixed

Do you mean that if `10 minutes` issue was fixed, you will publish your game to App Store?
Or do you mean you wanna wait until `glGenBuffers` is fixed?

**Comment by Kotaiba** [comment]
i will wait for the glGenBuffers ,so let me know when its fixed .

**Comment by dumganhar** [comment]
@Kotaiba, I fixed 'glGenBuffers' issue here:
https://github.com/cocos2d/cocos2d-x/pull/16182
Could you please check again?
