### ISSUE TITLE
Programmer's Guide is corrupted

### ISSUE THREAD

**Issue by ip** [cocos2d/cocos2d-x#15665]
For example, this page is 404:
http://www.cocos2d-x.org/docs/programmers-guide/4/index.html

**Comment by klemsFR** [comment]
API reference is also concerned!

**Comment by slackmoehrle** [comment]
Weird, let me look into this. It was working earlier today as I was reading content to update.

**Comment by slackmoehrle** [comment]
Fixed. I apologize for the inconvenience.
