### ISSUE TITLE
Memory leak when setting Texture2D to Sprite

### ISSUE THREAD

**Issue by Seryusjj** [cocos2d/cocos2d-x#15679]
I have the following code:
Texture2D \* texture = new Texture2D();  //referece count = 1
texture->initWithData(..)
sprite->setTexture(texture); // reference count = 2

Later on i change the texture
sprite->setTexture(texture2); //reference count of texture  = 1
and the first texture is not going to be released, is this correct? 
Do i have to release it? or the sprite should do it automatically?

**Comment by felixjingga** [comment]
@Seryusjj use Texture2D::create() interface.. don't new it.. if u new it, it will result in memleak...

**Comment by minggo** [comment]
Yep, if you use new, then you should release it too. Sprite::setTexture() will retain it internally. As @felixjingga said, use `create` instead, create function will return an autoreleased object.

**Comment by Seryusjj** [comment]
Texture2D and Image do not have that interface, you just can have an instance of them by calling new

**Comment by minggo** [comment]
Oh, yep. Sorry about that. So you need to invoke release when you don't need it.
