### ISSUE TITLE
Remove the Spine library as it has a personal only license

### ISSUE THREAD

**Issue by obushnell** [cocos2d/cocos2d-x#15678]
The Spine library's license is for personal use only. Which means it cannot be used in commercial software. This was mentioned and agreed to here [https://github.com/cocos2d/cocos2d-x/issues/15036#issuecomment-217066236](url).

Remove the Spine library from cocos2d-x.

**Comment by minggo** [comment]
Why have to remove it? You can ignore it if you don't use it, it will not hurt you.
