### ISSUE TITLE
libpng error: CgBI: unhandled critical chunk

### ISSUE THREAD

**Issue by ryukbk** [cocos2d/cocos2d-x#15698]
Originally discussed in this thread, https://github.com/cocos2d/cocos2d-x/issues/15199
The error happens at Texture2D::initWithImage (Cocos2d-x 3.10) only with an actual iOS device, not on an iOS simulator, and the solution is we had to disable both "Compress PNG Files" and "Remove Text Metadata From PNG files" on Xcode 7.2. It seems this issue persists for years. Is it possible to remedy it at the side of Cocos2d-x?

**Comment by slackmoehrle** [comment]
I am not sure, @minggo? @ricardoquesada?

We have a few other issues with this same subject and yes the fix was what you mentioned.

**Comment by minggo** [comment]
@ryukbk I think we can set `Remove Text Metadata From PNG files` to false by default.

**Comment by minggo** [comment]
Fixe it in #15702.
The issue is caused because Xcode 7.3 enable it by default.

**Comment by clevertension** [comment]
yes, in the [TARGETS ->  xxx-mobile], not PROJECTS
