### ISSUE TITLE
RenderTexture -> newImage() not working

### ISSUE THREAD

**Issue by Seryusjj** [cocos2d/cocos2d-x#15694]
Hello I have the following code that actually works v3.11 on windows (I have an sprite that executes a custom shader and want to get the raw output so I just try that):

```
    auto _rend = RenderTexture::create(sp->getTexture()->getPixelsWide(),          
    sp->getTexture()->getPixelsHigh(), Texture2D::PixelFormat::RGBA8888);
_rend->retain();
_rend->setKeepMatrix(true);

_rend->setVirtualViewport(Point(sp->getPosition().x, sp->getPosition().y),
                                               Rect(0, 0, windowSize.width, windowSize.height),
                                           Rect(0, 0, pixelSize.width, pixelSize.height));
_rend->beginWithClear(1, 0,0, 0);
sp->visit();
_rend->end();
_rend->getSprite()->getTexture()->setAntiAliasTexParameters();

//sprite from render target
auto _spriteDraw = Sprite::createWithTexture(_rend->getSprite()->getTexture());
_spriteDraw->setPosition(sp->getPosition());
addChild(_spriteDraw);
```

But if initializing the sprite in that way (to get the image data that is what i want):

```
   auto image = _rend->newImage();
auto texture = new Texture2D();
texture->initWithImage(image);

auto _spriteDraw = Sprite::createWithTexture(texture/*_rend->getSprite()->getTexture()*/);
_spriteDraw->setPosition(sp->getPosition());
addChild(_spriteDraw);
```

It does not print anything on screen, when debugging seems like the buffer that it's copiying is empty.
Correct size, but empty. Is there any other way to achieve what i want? . Than you in advance.

**Comment by Dimon4eg** [comment]
Hi @Seryusjj, looks like the same issue [#14861](https://github.com/cocos2d/cocos2d-x/issues/14861#issuecomment-223346963).

try to call
`Director::getInstance()->getRenderer()->render();`
before
`render->newImage();`

**Comment by Seryusjj** [comment]
Thank you so much @Dimon4eg it's working for me too.

**Comment by Seryusjj** [comment]
@ricardoquesada you can close this issue too.

**Comment by ricardoquesada** [comment]
closed. thanks.
