### ISSUE TITLE
[Cocos2d-x 3.11, Linux]: SimpleAudioEngine::playEffect() doesn't work correctly on Linux

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#15708]
After invoking 32 times the function "playEffect()" on a SimpleAudioEngine instance you get the message:

`"Fail to play <wav sound name> cause by limited max instance of AudioEngine"`

A test case can be made scheduling this function on the HelloWorld cocos project:

```
void HelloWorld::playSound(float dt) 
{
    auto engine = CocosDenshion::SimpleAudioEngine::getInstance();
    engine->playEffect("yourSound.wav");
}
```

**Comment by minggo** [comment]
Does #15735 fixed it?

**Comment by alfogrillo** [comment]
https://github.com/cocos2d/cocos2d-x/pull/15735 seems to work! :-)

**Comment by minggo** [comment]
@Drakon-Cocos Thanks.
