### ISSUE TITLE
CocosBuilder Issue: Application keep on crashing randomly upon calling CCB_MEMBERVARIABLEASSIGNER_GLUE

### ISSUE THREAD

**Issue by CodeSnooker** [cocos2d/cocos2d-x#1571]
Application keeps on crashing if you try to load the member variable using CCB_MEMBERVARIABLEASSIGNER_GLUE definition from a CCBI file.

The issue is reproducible in both Cocos2D-x v2.0.3 and v2.0.4

Possible reason: 

The definition is trying to release an autorelease object. If you go to the definition and comment out the object release call then application works fine. Though not sure about the memory leakage in this case.

eg:
# define CCB_MEMBERVARIABLEASSIGNER_GLUE(TARGET, MEMBERVARIABLENAME, MEMBERVARIABLETYPE, MEMBERVARIABLE) \

```
if (pTarget == TARGET && pMemberVariableName->compare(MEMBERVARIABLENAME) == 0) { \
    MEMBERVARIABLETYPE pOldVar = MEMBERVARIABLE; \
    MEMBERVARIABLE = dynamic_cast<MEMBERVARIABLETYPE>(pNode); \
    CC_ASSERT(MEMBERVARIABLE); \
    if (pOldVar != MEMBERVARIABLE) { \
        std::cout << "pOldVar = " << pOldVar << "\n"; \
        if (pOldVar == NULL) \
        { \
            std::cout<<"pOldVar is NULL \n"; \
        } \
        else \
        { \
            std::cout<<"pOldVar is NOT NULL.\n"; \
        } \
        /*CC_SAFE_RELEASE(pOldVar); // Application works fine now */ \
        MEMBERVARIABLE->retain(); \
    } \
    return true; \
}
```

**Comment by CodeSnooker** [comment]
Let me know if you need working sample to reproduce this issue.

**Comment by CodeSnooker** [comment]
Hey Guys,

I further investigated this issue. In CocosBuilder if you define any animation and you uncheck the autoplay in the Edit Timeline for any animation then chances are high the application will crash. 

If you check all the animations as autoplay in Edit Timeline then application is not crashing at all.

Let me know if this help.

Thanks,
Paras Mendiratta

**Comment by Kafeen** [comment]
This issue still occurs in the latest version from GITHUB but isn't reproduced 100% of the time.

**Comment by CodeSnooker** [comment]
@dumganhar @walzer 

Hi Guys,

This issue still occurs with cocos2d-2.1beta3-x-2.1.0 
Quite annoying. I wasted almost 2 hours in debugging the application. I have already given the solution. Not sure if those are the right steps but it certainly fixed the issue. 

Can you please verify and update the same?

Thanks,
Paras Mendiratta

**Comment by minggo** [comment]
@CodeSnooker 
pOldVar is retained in the macro, so we should release it when changing its value.
Could you give me a simple sample to reproduce it?

**Comment by CodeSnooker** [comment]
@minggo It's very simple to reproduce.

Step 1: Create a C++ (not javascript) project in Cocos2D-x using CocosBuilder.
Step 2: Add a variable in CocosBuilder for any element. Let's say in a scene, add a sprite and give it variable name: testSprite in the code connection and change the value from "Don't assign" to "Doc root var".

Step 3: In Cocos2D-x project try GLUE this variable using CCB_MEMBERVARIABLEASSIGNER_GLUE. 

Run the application and you will find 95% of time application will crash while loading the scene.

I tried to debug and tried to print the value in the macro. Most of the time it is coming NULL. Looks like it is already released. Is there is any other safe method to release the variable?

Thanks,
Paras Mendiratta

**Comment by CodeSnooker** [comment]
Just to be sure, this is how, I am using the method: onAssignCCBMemberVariable

bool MainMenuScene::onAssignCCBMemberVariable(cocos2d::CCObject \* pTarget, const char \* pMemberVariableName, cocos2d::CCNode \* pNode)
{
    CCB_MEMBERVARIABLEASSIGNER_GLUE(this, "musicOffSprite", CCSprite *, this->_musicOffSprite);
    CCB_MEMBERVARIABLEASSIGNER_GLUE(this, "soundOffSprite", CCSprite *, this->_soundOffSprite);
    return false;
}

**Comment by minggo** [comment]
But CocosBuilderTest use this way to assign member variable, it works ok.
Did you initialize "_musicOffSprite" and "_soundOffSprite" to NULL in MainMenuScene's constructor?

**Comment by CodeSnooker** [comment]
@minggo 

No, I didn't initialize the variable as NULL in the constructor. I did now and seems application is not crashing. I tried couple of time.

Thanks a lot for helping me out here.

**Comment by rockingdice** [comment]
It is caused by not initializing variable.

**Comment by yaowei1188** [comment]
i have came cross this issue, and have resolved by using initialize to NULL in constructor
but i just don't understand why !

**Comment by harikrishnar** [comment]
hi,
its because when the value is not initialized, it might be pointing to some garbage value, and we will try to release it in the setter, which will cause the crash as the release method is only present in CCObject and its derivatives, the garbage value will not have it.
