### ISSUE TITLE
CocosBuilder Issue: CustomProperty is not supported

### ISSUE THREAD

**Issue by CodeSnooker** [cocos2d/cocos2d-x#1573]
Application does not support custom property. For more details please read along: http://www.cocos2d-x.org/boards/18/topics/17554

**Comment by CodeSnooker** [comment]
@dumganhar 

Hi there,

Any idea by when it will be fixed for non-JS version?

Thanks,
Paras Mendiratta

**Comment by dumganhar** [comment]
Hey, did you write you own loader? 
And did your gamelayer inherit CCBMemberVariableAssigner protocol ?
Since c++ has no reflection, you need to override <code>onAssignCCBMemberVariable</code> and use strcmp to check which custom property you are using.
For more details, you should refer to TestCpp/ExtenstionsTest/CocosBuilderTest, thanks.

**Comment by denranx** [comment]
Hi, 
CCBMemberVariableAssigner is used to link cocosbuilder's objects to class member variables in the code and not custom properties.

Unfortunately there is no example in the cocos2dx tests that show how to handle custom properties.

**Comment by CodeSnooker** [comment]
@dumganhar 

Please see @lzubix comment. I agreed with him. Will custom properties officially supported?

**Comment by dumganhar** [comment]
So are there some examples in cocos2d-iphone?
ÔÚ 2013-1-3 ÉÏÎç1:12£¬"lzubix" notifications@github.comÐ´µÀ£º

**Comment by CodeSnooker** [comment]
@dumganhar 

Yes there is. Check Viktor's tutorial: http://code.zynga.com/2012/10/creating-a-game-with-cocosbuilder/

He is using custom property for Coin (Green Coin)

**Comment by dumganhar** [comment]
@CodeSnooker 
Thank you, it will test it and let u know the result.

**Comment by dumganhar** [comment]
@CodeSnooker 
If your loader override the function _onHandlePropTypeInteger_, you will be able to get the custom property.
Have a try and let me know whether it works. Thanks.

**Comment by CodeSnooker** [comment]
@dumganhar 

That requires to pass CCBReader reference. 

virtual void onHandlePropTypeInteger(CCNode \* pNode, CCNode \* pParent, const char\* pPropertyName, int pInteger, CCBReader \* pCCBReader);

IMO, this is not the right way to do. It should be something similar to 

virtual bool onAssignCCBMemberVariable(cocos2d::CCObject \* pTarget, const char \* pMemberVariableName, cocos2d::CCNode \* pNode);

but the last parameter should not restrict to CCNode type. It should allow to read Integer, float, String etc. as supported by custom property.

**Comment by dumganhar** [comment]
Make sense. Maybe i need to look inside the CCBReader of cocos2d-iphone to see how it works.

**Comment by denranx** [comment]
Hi,

Just to let you know that I was able to get custom properties working by overwriting onHandlePropTypeString in my node loader class (should also work for integer, float...).

class MyCustomClassLoader : public CCMenuItemImageLoader {

...

void onHandlePropTypeString(CCNode \* pNode, CCNode \* pParent, CCString \* pPropertyName, CCString \* pString, CCBReader \* pCCBReader) {
        if( strcmp(pPropertyName->getCString(), "myPropertyName") == 0 ) {
            static_cast<MyCustomClass*>(pNode)->setPropertyString(pString);
        }
}

}

But as CodeSnooker said, it's might not be the best way to handle custom properties and a onAssignCCBMemberVariable method should be implemented.

**Comment by dumganhar** [comment]
Hello @CodeSnooker @lzubix 
I reviewed the CCBReader codes in cocos2d-iphone and found that in `objc`, it's pretty easy to achieve that by 
`[node setValue:[NSNumber numberWithInt:d] forKey:name];`
But in c++, it's impossible to do that. 
What's more, I couldn't find `customProperty` section in `.ccbi` file. It isn't needed in cocos2d-iphone since `[node setValue` can set the properties dynamically.
But it's painful in c++.
To achieve that, it should be a `customProperty` section in `.ccbi` file.

Any thoughts?

**Comment by dumganhar** [comment]
I think i have fixed this issue. I will send a pull request and let u know soon.

**Comment by denranx** [comment]
Hi  dumganhar,
Thanks for the feedback!

**Comment by dumganhar** [comment]
I have sent the PR here(https://github.com/cocos2d/cocos2d-x/pull/1876).
Could you test it? If no problem, i will merge it. Thanks.
You could find the example at `HelloCocosBuilder.ccb`

<pre>
bool HelloCocosBuilderLayer::onAssignCCBCustomProperty(CCObject* pTarget, const char* pMemberVariableName, cocos2d::extension::CCBValue* pCCBValue)
{
    bool bRet = false;
    if (pTarget == this)
    {
        if (0 == strcmp(pMemberVariableName, "mCustomPropertyInt"))
        {
            this->mCustomPropertyInt = pCCBValue->getIntValue();
            CCLog("mCustomPropertyInt = %d", mCustomPropertyInt);
            bRet = true;
        }
        else if ( 0 == strcmp(pMemberVariableName, "mCustomPropertyFloat"))
        {
            this->mCustomPropertyFloat = pCCBValue->getFloatValue();
            CCLog("mCustomPropertyFloat = %f", mCustomPropertyFloat);
            bRet = true;
        }
        else if ( 0 == strcmp(pMemberVariableName, "mCustomPropertyBoolean"))
        {
            this->mCustomPropertyBoolean = pCCBValue->getBoolValue();
            CCLog("mCustomPropertyBoolean = %d", mCustomPropertyBoolean);
            bRet = true;
        }
        else if ( 0 == strcmp(pMemberVariableName, "mCustomPropertyString"))
        {
            this->mCustomPropertyString = pCCBValue->getStringValue();
            CCLog("mCustomPropertyString = %s", mCustomPropertyString.c_str());
            bRet = true;
        }
        
    }
    return bRet;
}
</pre>

**Comment by denranx** [comment]
Hi dumganhar,

I will test asap and give you some feedback... thanks!!!

**Comment by Andargor** [comment]
I have tested this with a custom CCParticleSystemQuad and it seems to work.

**Comment by godyZ** [comment]
@CodeSnooker Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August
