### ISSUE TITLE
CocosBuilder Issue: Sometime all game objects does not load in the Scene

### ISSUE THREAD

**Issue by CodeSnooker** [cocos2d/cocos2d-x#1574]
For example, while porting CocosDragon in Cocos2D-X (http://code.zynga.com/2012/10/creating-a-game-with-cocosbuilder/) if I try to load the GameScene, sometimes the Dragon does not appear in the game at all.

**Comment by minggo** [comment]
Is this issue the same as https://github.com/cocos2d/cocos2d-x/issues/1575?

**Comment by CodeSnooker** [comment]
@minggo  No. Both issues are totally different. 

1575 - Reproducible only on Android platform

Whereas this issue is reproducible at both Android and iOS platform.
