### ISSUE TITLE
AssetsManagerEx zip decompression unrecoverable error

### ISSUE THREAD

**Issue by alk-aries** [cocos2d/cocos2d-x#15750]
There's a bug in AssetsManagerEx that can cause invalid state of assets update. In any circumstances where decompressDownloadedZip failed, there's no way for the game to recover from this error. The only solution is to uninstall and reinstall the game.

```
void AssetsManagerEx::onDownloadUnitsFinished()
{
    // Finished with error check
    if (_failedUnits.size() > 0)
    {
        // Save current download manifest information for resuming
        _tempManifest->saveToFile(_tempManifestPath);

        decompressDownloadedZip();

        _updateState = State::FAIL_TO_UPDATE;
        dispatchUpdateEvent(EventAssetsManagerEx::EventCode::UPDATE_FAILED);
    }
    else
    {
        updateSucceed();
    }
}
```

The problem might be caused after writing the temp manifest, AssetsManager won't be able to retry on files that fails in decompression. To reproduce the bug:
1. Start update with AssetsManagerEx
2. Trigger download failure
3. Just after temp manifest has been saved and decompression started, kill the game
4. AssetsManagerEx won't be able to detect the failure and resuming the update without previous assets

This problem might also occurs in updateSucceed.

**Comment by dumganhar** [comment]
@pandamicro, please check whether this issue was fixed in v3 branch. Thanks.

**Comment by pandamicro** [comment]
My refactor to AssetsManagerEx haven't been submitted yet, but it can solve this problem, because I put decompression before file load succeed, only when file successfully decompressed, it can be marked as complete. Any break during decompress process will cause the file incomplete, so it could be finished in the next try

**Comment by dumganhar** [comment]
@pandamicro , could you submit that patch to cocos2d-x repo? Thank you.

**Comment by pandamicro** [comment]
My PR have been merged https://github.com/cocos2d/cocos2d-x/pull/17115

The new AssetsManagerEx behavior is more secured, a zip file is only succeed after successfully decompressed
