### ISSUE TITLE
[Cocos2d-x 3.11, Android]: SimpleAudioEngine::playEffect() stops previous playing effects! 

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#15758]
When a relatively long (3-4 seconds) sound effect is playing while a burst of little sounds are playing, the long sound likely will stop its execution. This happens on Android (5.1.1) and does NOT happens on iOS.

The bug can be reproduced with this code to add to Hello World proejct:

```
bool HelloWorld::init()
{
    if ( !Layer::init() )
        return false;

    schedule(schedule_selector(HelloWorld::playLongSound), 2.0f);
    schedule(schedule_selector(HelloWorld::playShortSound), 0.25f);
    return true;
}

void HelloWorld::playLongSound(float dt) 
{
    auto engine = CocosDenshion::SimpleAudioEngine::getInstance();
    engine->playEffect("long.wav"); // 3-4 seconds
}

void HelloWorld::playShortrSound(float dt) 
{
    auto engine = CocosDenshion::SimpleAudioEngine::getInstance();
    engine->playEffect("short.wav"); // < 1 second
}
```

**Comment by Shulepov** [comment]
As i know currently `SimpleAudioEngine` internally implemented on android using `SoundPool`. And cocos-team allowed it to play `5` sounds simultaneously (`3` on GT-I9100). Possibly it has some issues on some devices so them can play less sounds (just assumption).

You can try to use `experimental::AudioEngine` instead. It works nice on android for me.

**Comment by alfogrillo** [comment]
Thanks Shulepov
Probably the interruption is due to the sound threshold!
I will do some other test! :-)

I chose `SimpleAudioEngine` (instead of `AudioEngine`) because I needed to manipulate the "pitch" property of the sounds effects (to simulate time slow down).
If I remember well `AudioEngine` does not support sound pitch! :-(

**Comment by minggo** [comment]
No matter SimpleAudioEngine or Audio Engine, there is limitation of sound instance limitation.
