### ISSUE TITLE
CocosBuilder Issue: On Android platform, all game objects do not load in the GameScene

### ISSUE THREAD

**Issue by CodeSnooker** [cocos2d/cocos2d-x#1575]
For example, 

While porting CocosDragon (http://code.zynga.com/2012/10/creating-a-game-with-cocosbuilder/) in Cocos2D-X platform and while testing the game in Android, in the gameScene all objects do no load in the game scene.

In iOS it load 68 objects in GameScene whereas in Android it loads only 38 objects. Sometime it load even less then 38 objects. 

The issue is 100% reproducible on Android device. Tested issue on Samsung Galaxy Ace.

**Comment by minggo** [comment]
Did you publish the CocosBuilder project without "flatter mode"?

**Comment by CodeSnooker** [comment]
@minggo No. Issue #1574 is reproducible at iOS platform also. In Issue, #1574, only Dragon is not appearing in the scene, rest seems to be fine. 

@walzer  Not sure what is "flatter mode". Any link to search for the same.

**Comment by minggo** [comment]
You can refer to the document released with CocosBuilder for the information of "flatter mode".

**Comment by CodeSnooker** [comment]
@minggo  and @walzer  Yes I did publish files using flatter mode. Let me give more information about the issue.

The GameScene consists of GameObjects: Coins, Dragon, and Bombs.

On Android platform, top coins and bombs are not loading at all whereas on iOS platform, all objects are loading properly except sometimes Dragon doesn't appear.

**Comment by minggo** [comment]
Publishing with flatter mode like adding files as blue color in Xcode. You can open a corresponding CCB file, and checkout the path of the resources.

**Comment by CodeSnooker** [comment]
@minggo Thanks! Already checked and files are published in flatter mode only. I checked via project settings.
