### ISSUE TITLE
3.11.1 xcode 新建工程 #include "cocostudio/CocoStudio.h" 出错

### ISSUE THREAD

**Issue by ruifly2012** [cocos2d/cocos2d-x#15770]
提示找不到文件，怎么解决

**Comment by VizXu** [comment]
不是#include<cocostudio/CocoStudio.h>吗？

**Comment by ruifly2012** [comment]
@VizXu #include "cocostudio/CocoStudio.h"在vs工程上引入每问题，在xcode上就报错，不清楚xcode哪里要配置下

**Comment by VizXu** [comment]
这个你去stackoverflow上问问

**Comment by cmzx3444** [comment]
#include "editor-support/cocostudio/CocoStudio.h"

**Comment by zilongshanren** [comment]
@ruifly2012  楼上正解，所有引擎的包含目录都要从 `cocos` 目录算起。
