### ISSUE TITLE
AudioEngine接完电话出问题

### ISSUE THREAD

**Issue by yunmin97** [cocos2d/cocos2d-x#15789]
使用AudioEngine播放音乐，接完电话回到游戏就没有声音了，调试发现调用play2d播放能返回一个有效ID（非-1），但是就是播放不出声音来！！！

cocos2dx版本：cocos2dx3.8.1版本
ios：8.x到9.x都有测出来

**Comment by zilongshanren** [comment]
please upgrade  your engine to 3.10 or later.
It is fixed in https://github.com/cocos2d/cocos2d-x/pull/13706
