### ISSUE TITLE
Android project.properties file may have typo

### ISSUE THREAD

**Issue by traviswimer** [cocos2d/cocos2d-x#15785]
In the templates for the android `project.properties` files, I think the comments may contain an incorrect statement. It says:

```
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
```

I'm guessing this was meant to have the same comment as in `local.properties`:

```
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
```

I'll gladly make a pull request if someone can verify that this is a mistake.

Example file:
`cocos2d-x/templates/cpp-template-default/proj.android-studio/app/project.properties`

It also looks like `project.properties` is included in the `.gitignore` file, but is still being tracked by git. I'm guessing this file should not be tracked?

**Comment by minggo** [comment]
About the comment, it is generated by Eclipse. And we need this file to make sure `cocos2d/cocos/platform/android/java` is depended on correctly, so that's why it is traced by git.

**Comment by ricardoquesada** [comment]
closing it. Please reopen it if you think this is still a bug.
