### ISSUE TITLE
[Cocos2d-x 3.11] NodeGrid actions don't work correctly with content scale factor < 1

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#15783]
NodeGrid actions don't work correctly with content scale factor (csf) < 1 
(maybe also with csf > 1, I haven't tested this case).
The children of the NodeGrid are partially clipped or, worse, not correctly drawn.
Here the core code snippet ("Liquid" action is only an example, the problem remain with other actions):

```
void HelloWorld::addGridNode() 
{
    auto visibleSize = Director::getInstance()->getVisibleSize();
    auto gridNode = NodeGrid::create();
    gridNode->setPosition(visibleSize * 0.5f);

    auto sprite = Sprite::create("HelloWorld.png");
    gridNode->addChild(sprite);
    addChild(gridNode);

    auto liquid = Liquid::create(5.0, {32, 24}, 5, 8);
    gridNode->runAction(liquid);
}

bool AppDelegate::applicationDidFinishLaunching() {
   ...
    auto director = Director::getInstance();
    director->setContentScaleFactor(0.66f); // or 0.5f, or 1.0f
   ...
}
```

Content Scale Factor = 0.5f (artifacts!)
![csf-0 5](https://cloud.githubusercontent.com/assets/19324622/15790858/25ebbe54-29d4-11e6-8d57-de5a8ae8a941.png)

Content Scale Factor = 0.66f (sprite partially clipped)
![csf-0 66](https://cloud.githubusercontent.com/assets/19324622/15790867/31f982da-29d4-11e6-99cb-35d674604cad.png)

Content Scale Factor = 1.0f (ok)
![csf-1 0](https://cloud.githubusercontent.com/assets/19324622/15790872/35aca5ec-29d4-11e6-8368-8e5f63654ad6.png)

**Comment by alfogrillo** [comment]
A similar wrong behavior happens when it is called:

`Director::getInstance()->getOpenGLView->setFrameZoomFactor(0.7f);`
inside `AppDelegate::applicationDidFinishLaunching`

this independently by the content scale factor!

**Comment by JoHuang** [comment]
I think #2994 might be also related.

**Comment by unix2dos** [comment]
how to slove this problem

**Comment by alfogrillo** [comment]
@unix2dos 
In my case the solution was not using NodeGrid actions!
Did you try with the last cocos2d-x version?

**Comment by unix2dos** [comment]
@drakon-ag  
Inside CCGrid.cpp  i find Class GridBase
 I replace all `director->getWinSizeInPixels()` to `director->getWinSize()`
It's ok, thanks
