### ISSUE TITLE
pointer is not initialized !!!!

### ISSUE THREAD

**Issue by zero1234567** [cocos2d/cocos2d-x#15798]
class TextureFrame
{
    cocos2d::Sprite\* _sprite;
}
TextureFrame::TextureFrame()
    : _textureName("")
{
     // _sprite is not initialized !!!!
}

**Comment by ricardoquesada** [comment]
Please, add more info. Why do you think Sprite should be initialized if you don't initialize it?

Closing it as invalid... please reopen it with more data. thanks.
