### ISSUE TITLE
Serious Memory Leak in CCLabel

### ISSUE THREAD

**Issue by joewan** [cocos2d/cocos2d-x#15793]
now we found a serious memory leak in CCLabel. if we create a cocos2d::Label, it will create two custom listeners: _purgeTextureListener && _resetTextureListener. and the two listener will always in memory, it will cause serious memory leak when we create many labels. @minggo pls help us.
now.  and it is very easy to reproduce this problem.

**Comment by joewan** [comment]
our cocos is 3.8.1. maybe you have solve this problem. and i will check the latest modification of CCLabel.cpp or
 EventDispatcher.cpp

**Comment by joewan** [comment]
https://github.com/cocos2d/cocos2d-x/commit/ffb2cfa9e0349c05853a55f74120b6b494fab756  we have fixed this bug.

**Comment by joewan** [comment]
![image](https://cloud.githubusercontent.com/assets/1213438/15843460/e03ae6c8-2c94-11e6-8900-11891d129cca.png)
`void FontAtlas::purgeTexturesAtlas()
{
    if (_fontFreeType && _atlasTextures.size() > 1)
    {
        auto eventDispatcher = Director::getInstance()->getEventDispatcher();
        eventDispatcher->dispatchCustomEvent(CMD_PURGE_FONTATLAS,this);
        eventDispatcher->dispatchCustomEvent(CMD_RESET_FONTATLAS,this);
    }
}`
"_atlasTextures.size() > 1", what does "1" mean here? @minggo ,for left-down stats label?

**Comment by minggo** [comment]
Sorry, i have not idea.
@zilongshanren do you know it?

**Comment by joewan** [comment]
and I also think it is a bad design to destroy resource in destructor function.
![image](https://cloud.githubusercontent.com/assets/1213438/15843627/36a6ee16-2c96-11e6-8ef7-6e7056e87597.png),these two function calls are very dangerous,

**Comment by vkreal** [comment]
@joewan can you please share why you think it's a bad design to destroy resource in destructor function?
