### ISSUE TITLE
setup.py doesn't check ndk_root correctly on windows

### ISSUE THREAD

**Issue by cryptozion** [cocos2d/cocos2d-x#15806]
There is only sdk/ndk-bundle/ndk-build.cmd on windows platform when I download the NDK from the  The Android Studio 2.12. When running setup.py,cocos2d-x-3.11.1 only check for "ndk-build".

The correct code should be like this:

```
        ndk_build_path = os.path.join(ndk_root, 'ndk-build')
        if os.path.isfile(ndk_build_path) or os.path.isfile(os.path.join(ndk_root, 'ndk-build.cmd')):
            return True
        else:
            return False
```

**Comment by minggo** [comment]
@natural-law Could you please take a look.

**Comment by natural-law** [comment]
> when I download the NDK from the The Android Studio 2.12

I don't know what's this mean. As I see on the formal website of Android Studio. There isn't NDK in Android Studio bundle package.

After all, it's a problem of setup.py. Thanks for your feedback, I will solve it later.
