### ISSUE TITLE
ipv6 cocos2d-x(v3.11.1) ERR: lws_rx_sm: doing draining flow

### ISSUE THREAD

**Issue by frankwun** [cocos2d/cocos2d-x#15813]
My iOS app to adapt to IPV6-only, so we upgrade the cocos2d-x to the v3.11.1+ version. Now it work in the IPV6 environment, but encountered another problem:
When SocketIO (websocket) receives the data more than 1024 bytes. Even now (10 times will appear 1-2 times) reported the following wrong, the return of the data is garbled or incomplete.

Data:index:104 len=1023, Receiving
Lws_rx_sm: doing draining flow ERR:

Have you encountered such a problem, how to solve the problem? thank you！

**Comment by springrider** [comment]
same issue here: #15829

**Comment by wulei** [comment]
same issue +1 here: #15742

**Comment by ricardoquesada** [comment]
closing it since it is a duplicate.
