### ISSUE TITLE
The Sprite Anchor Point Bug and PhysicsBody Removing Bug 

### ISSUE THREAD

**Issue by eray-z** [cocos2d/cocos2d-x#15812]
Hi there. 

1- The sprite object anchor point is Vec2(0.5,0.5) as a default.(according to helper documents) Sprite objects doesn't respect anchor point like node objects when I add a new child. The child object must be added center of the sprite object.

I don't have that problem with node objects.Only sprite.

You may try the example helloworldscene.cpp file; http://codepaste.net/9d8rjj
I tried: v3.11.1

2- Another bug, I can't remove PhysicsBody component from any node-node based object. I get "EXC_BAD_ACCESS" error. 

You may try the example helloworldscene.cpp file; http://codepaste.net/sfyyy2
I tried: v3.11.1

I had opened this [issue](http://discuss.cocos2d-x.org/t/cocos2d-x-node-sprite-anchor-points-and-removing-physicsbody-bugs/29875) in cocos2d-x community.

**Comment by ricardoquesada** [comment]
Links don't work. Could you post the code to reproduce the bug? thanks.

**Comment by ricardoquesada** [comment]
> The child object must be added center of the sprite object.

this is not correct. the child will always be added to 0,0, regardless of the parent's anchor point.
this is a design feature.

**Comment by eray-z** [comment]
Ok, I tried set parent sprite object anchor point (0.5,0.5)  and it's still not working.

**Comment by eray-z** [comment]
And parentSprite->getPosition() always give the center point . But If I add child sprite always add bottom-left point of parentSprite. : (

**Comment by ricardoquesada** [comment]
that's correct, that's the expected behavior.
children will always be added relative to the bottom/left (0,0) corner of its parent. I added more info in the forum thread: http://discuss.cocos2d-x.org/t/cocos2d-x-node-sprite-anchor-points-and-removing-physicsbody-bugs/29875
