### ISSUE TITLE
ClippingNode::setStencil() does not clean up _stencil correctly

### ISSUE THREAD

**Issue by Almax27** [cocos2d/cocos2d-x#15815]
When ClippingNode::setStencil() is called, _stencil may have had it's onEnter() function called, setting _running = true. However it is released without onExit() being called resulting in CCASSERT(!_running) triggering in Node::~Node().

PR: https://github.com/cocos2d/cocos2d-x/pull/15814

**Comment by minggo** [comment]
How to reproduce it?

**Comment by Almax27** [comment]
Call setStencil() twice with different nodes after ClippingNode has been added to a running scene.

**Comment by minggo** [comment]
To simplify my life, would you please write some demo codes to reproduce it? Thanks.

**Comment by Almax27** [comment]
Test case: 
- "cocos new -d ./test -l cpp"
- Replace HelloWorldScene.h and HelloWorldScene.cpp with:

**HelloWorldScene.h**

```
#pragma once

#include "cocos2d.h"

class HelloWorld : public cocos2d::Layer
{
public:
    static cocos2d::Scene* createScene();

    virtual bool init() override;
    virtual void onEnter() override;

    CREATE_FUNC(HelloWorld);

private:
    cocos2d::ClippingNode* m_clippingNode;
};
```

**HelloWorldScene.cpp**

```
#include "HelloWorldScene.h"

USING_NS_CC;

Scene* HelloWorld::createScene()
{
    auto scene = Scene::create();
    auto layer = HelloWorld::create();
    scene->addChild(layer);
    return scene;
}

bool HelloWorld::init()
{
    if ( !Layer::init() )
    {
        return false;
    }

    m_clippingNode = ClippingNode::create(Node::create());
    this->addChild(m_clippingNode);

    return true;
}

void HelloWorld::onEnter()
{
    Layer::onEnter();

    //BUG: this crashes the application in Node::~Node()
    m_clippingNode->setStencil(Node::create());
}

```

**Comment by Almax27** [comment]
I have also updated the pull request to add correct initialisation of the new stencil

**Comment by minggo** [comment]
Thanks @Almax27 . I merged the PR.
