### ISSUE TITLE
sometimes websocket.cpp broke the gzip message

### ISSUE THREAD

**Issue by springrider** [cocos2d/cocos2d-x#15829]
I just updated my web socket wrapper to the latest, commit: 264bf87c87ded7e1ed0c3f86ca0b51622d2af11e

and got some wired issue, I am using server side gzip to optimize  the data traffic,  it went well on older version web socket wrapper(commit: 507f221).

but after update to the latest wrapper, I occasionally encounter error like this:

[LUA-print] [ERROR] InvalidInput: input string does not conform to zlib format or checksum failed at lua_extensions/zlib/lua_zlib.c line 165

it seems the packet got chunked??  
I am not familiar with the wrapper, is there anyway around this?  thanks!

**Comment by springrider** [comment]
and after disabled gzip, I got this error:

eceiving data:index:3, len=1023
```
ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow
```

what does it mean?

**Comment by springrider** [comment]
I just noticed issue: #15742, please allow me to post the new findings here:

>  I am pretty sure my msg got chunked, I printed my msg in lua like this:
> print("msg:"..msg.."#end")
> 
> and what I got is:
> msg:(some reasonable data and length=1023) ~z\363\216\342~\215\252\221\233l\206NG#end
> 
> I am not sure: " ~z\363\216\342~\215\252\221\233l\206NG" is , but it definitely not right.

**Comment by springrider** [comment]
and the entire log is like this:

```

Receiving data:index:3, len=1023
data:]u\277\\3207\312*"\323V\227b\360l\253o$\273\274\227Rs;d\346\200_&\277h\336\333w\352I\273"GN,\222\266,\273sb\333>\350s\343\226s
\341yf\232~\213\340v\230.H>\213\274\360c\272\215,Dnb>\3327\255\342\211\207\324W\366A\367\235IK\350\223\235\354E}w>\326OtK\304&J5\347\347"q\345LKU\350wX\236d\271\306"\213F曗=<\212k\2242\346\333\360\373:%\303
q\310o^i\222\314N\247%}\330Z\256\347{^\211\365)<\332k~)\233\315\304\300\350A\233\341\213\236\236%%bʫ\233\227\3718މ6q\315\320:iW\265)\356\362\200\317Яה\372V\234\301\347Q\265d\334ta_LQ\302InI\206\305\364b, 3\223O%\273\242\260\321p\262\204\216\312%Un\324ivр,(X\306лqf\252\327ncJBERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

ERR: lws_rx_sm: doing draining flow

Receiving data:index:4, len=15
data:]u\271T\337n\204oe\225\230~wNotify data len 1038 to Cocos thread.
[LUA-print] msg:(some reasonable data and length=1023) ~z\363\216\342~\215\252\221\233l\206NG�#end
[LUA-print] decode msg error
```

**Comment by springrider** [comment]
not sure if it's the right way to debug, but I printed the receivedData before and after like this:

``````
```
LOGD("before receiveddata:%s #end, len:%lu", (char*)_receivedData.data(), _receivedData.size());
    _receivedData.insert(_receivedData.end(), inData, inData + len);
    LOGD("receiveddata:%s #end, len:%lu", (char*)_receivedData.data(), _receivedData.size());
``````

```

and for the packet that caused the problem, the value of _receivedData before and after insert are the same.
```

**Comment by springrider** [comment]
I have managed to get through once, the total length of the "problem packet" should be about: "17625.(frame size) ".

but in most cases,  after the the frame size reached 1038,  the final fragment mark change to 1: 
isFinalFragment: 1

not sure how this woks.... does it because my server send some special character? like space or "\n" or "\0" something like that?    is there anyway to force binary transfer?

**Comment by springrider** [comment]
just found out the error is caused by encryption(I disabled gzip to test and forgot somehow the encrypted data can't be transferred via websocket).  after gzip the encrypted data.  the problem goes away.  

but I still encounter the problem I mentioned in the first post :
`[LUA-print] [ERROR] InvalidInput: input string does not conform to zlib format or checksum failed at lua_extensions/zlib/lua_zlib.c line 165`

sometimes the data get transferred seems wrong, but I have no way to reproduce it, it just happens randomly. 

I noticed the extension changed to ""permessage-deflate",  in the new wrapper, will this cause the issue? because in the earlier version,  its another extension(can't recall the name), is that why the old version works fine?

**Comment by frankwun** [comment]
@springrider ，How to disable gzip?

**Comment by springrider** [comment]
I gzipped the msg by myself, so just disabled gzip in my code...
I am not sure if libwebsockets also do gzip...

**Comment by frankwun** [comment]
@springrider ，thank you

**Comment by minggo** [comment]
> I am not sure if libwebsockets also do gzip...

@dumganhar do you know?

**Comment by dumganhar** [comment]
> I noticed the extension changed to ""permessage-deflate", in the new wrapper, will this cause the issue? because in the earlier version, its another extension(can't recall the name), is that why the old version works fine?

Yep, libwebsockets is using `permessage-deflate` for gzip compression. Probably, you should update websocket protocol for your service to support this feature.

BTW, `permessage-deflate` is probably not perfectly supported in libwebsockets since there were some test case could not pass the AutoBahn Test. You could refer to http://182.254.241.97/runtime-test/websocket-report/index.html for the test result.

**Comment by minggo** [comment]
close this issue since it is a limitation of websockets
