### ISSUE TITLE
Compiling error with Android 6.0(API 23)

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#15823]
`Cocos2dxDownloader.java` uses [Apache HTTP Client](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client) which is removed in Android 6.0, should use `HttpURLConnection` instead.

There is corresponding [ticket](http://discuss.cocos2d-x.org/t/cant-compile-to-android/26874) in the forum.

**Comment by minggo** [comment]
@cezheng How do you think this issue? Have you fixed the issue? If so, could you please send a PR? If not, then i will implement it, and please help to review it. Thanks.

**Comment by cezheng** [comment]
android-async-http uses apache http, the way to work around it is to add the legacy class path to it. I don't think it is really necessary to remove it yet, since google's volley also uses apache

**Comment by minggo** [comment]
yep, it is easy to add class path in Android Studio, but how about ADT?

**Comment by cezheng** [comment]
I will take a look then. I guess the modification might take place in the cocos-console project.

We have a legacy internal android library that has nothing to do with cocos2d-x. It is still on ADT.

 We build it in this way

``` bash
if [ `echo "$ANDROID_TARGET" | cut -d "-" -f 2` -ge 23 ]; then
  APACHE_HTTP_LIB=$(dirname `which android`)/../platforms/${ANDROID_TARGET}/optional/org.apache.http.legacy.jar
  cp $APACHE_HTTP_LIB $PROJECT_ROOT/libs
fi
```

**Comment by cezheng** [comment]
I realized that they have a new release for this, so maybe the correct approach is:
1. Update android-async-http to 1.4.9, resolve any compile errors if exists
2. Since only the range header for download resuming explicitly uses apache.http, rewrite that part

https://github.com/loopj/android-async-http/blob/1.4.9/CHANGELOG.md#149-released-19-9-2015

The current version used is 1.4.8

**Comment by minggo** [comment]
@cezheng Thanks for the information.

> Since only the range header for download resuming explicitly uses apache.http, rewrite that part

I think we don't have to rewrite since the library updates it. I am not sure.

**Comment by cezheng** [comment]
@minggo `That part` means that part in Cocos2dxDownloader, more specifically, this part

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxDownloader.java#L255-L259

**Comment by cezheng** [comment]
If you want a fast fix, maybe modifying `cocos compile` to copy the legacy jar is an easier approach

**Comment by minggo** [comment]
No, i think we should fix it in correct way. `Head` is needed by the parameter of the library. I think we can change it since the library remove the dependence of legacy jar.

**Comment by Dauch** [comment]
hey, since doing hot update I meat [https://github.com/loopj/android-async-http/issues/990](url), Then I downward ```android-async-http`` version to 1.4.8, revert to this patch [https://github.com/cocos2d/cocos2d-x/commit/84db1ac294a9829cfc3d7a8aa0de18d292208e63](url),  and ervrything wroks ok, any thought about this?

**Comment by Dauch** [comment]
More about hot update couldn't work detail, It's when I start update ```AssetsManagerEx:update()``` after minutes past, I got those err, It's rarely happen, not everytimes.
```
13002-20 14:59:41.698 19065 19474 W System.err: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 80) after 45000ms: isConnected failed: ECONNREFUSED (Connection refused)
13102-20 14:59:41.698 19065 19474 W System.err: at libcore.io.IoBridge.isConnected(IoBridge.java:238)
13202-20 14:59:41.698 19065 19474 W System.err: at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
13302-20 14:59:41.698 19065 19474 W System.err: at libcore.io.IoBridge.connect(IoBridge.java:122)
13402-20 14:59:41.698 19065 19474 W System.err: at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
13502-20 14:59:41.698 19065 19474 W System.err: at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
13602-20 14:59:41.698 19065 19474 W System.err: at java.net.Socket.connect(Socket.java:882)
13702-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java)
13802-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java)
13902-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java)
14002-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java)
14102-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java)
14202-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java)
14302-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java)
14402-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
14502-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java)
14602-20 14:59:41.698 19065 19474 W System.err: at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java)
14702-20 14:59:41.698 19065 19474 W System.err: at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java)
14802-20 14:59:41.698 19065 19474 W System.err: at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java)
14902-20 14:59:41.698 19065 19474 W System.err: at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java)
15002-20 14:59:41.698 19065 19474 W System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
15102-20 14:59:41.698 19065 19474 W System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
15202-20 14:59:41.698 19065 19474 W System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
15302-20 14:59:41.698 19065 19474 W System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
15402-20 14:59:41.698 19065 19474 W System.err: at java.lang.Thread.run(Thread.java:818)
15502-20 14:59:41.698 19065 19474 W System.err: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
15602-20 14:59:41.698 19065 19474 W System.err: at libcore.io.IoBridge.isConnected(IoBridge.java:223)
15702-20 14:59:41.698 19065 19474 W System.err: ... 23 more
15802-20 14:59:41.698 19065 19065 D Cocos2dxDownloader: onFailure(i:0 headers:null throwable:java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 80) after 45000ms: isConnected failed: ECONNREFUSED (Connection refused) file:/data/data/com.xxxxxxx.xxxx.xx/files/version.manifest.tmp
```
