### ISSUE TITLE
Help me! Problem with: make Linux, #include<new> 'new ' file not found

### ISSUE THREAD

**Issue by tuantuannd** [cocos2d/cocos2d-x#15820]
After cmake../.. success, i type: make and it appear error:
/root/Desktop/cocos2d-x/external/bullet/LinearMath/btAlignedObjectArray.h:39:10: fatal error: 
      'new' file not found
# #include<new> //for placement new
# ^

1 error generated.
external/bullet/CMakeFiles/bullet.dir/build.make:62: recipe for target 'external/bullet/CMakeFiles/bullet.dir/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp.o' failed

Please help me..

**Comment by ricardoquesada** [comment]
try editing "btAlignedObjectArray.h" and comment line 29, like this:

``` c++
/* #define BT_USE_PLACEMENT_NEW 1 */
```

Also, please also mention which linux distro you have and what gcc version you are using

**Comment by minggo** [comment]
@tuantuannd have you fixed the issue?

**Comment by JesseTG** [comment]
I have this problem as well.  Ubuntu 16.04, with clang 3.8.0.  I do NOT get this issue with gcc 5.3.1.

**Comment by rikapo** [comment]
make sure your g++ symbolic link works fine.
try this command : `file /usr/bin/g++`
and if symlink is broked, this commands will help you.

```
sudo apt-get purge g++ 
sudo apt-get install build-essential g++
```
