### ISSUE TITLE
Crash (JSB) when action sequence contains an action with easing

### ISSUE THREAD

**Issue by pandemosth** [cocos2d/cocos2d-x#15851]
Seen in versions: cocos2d-x v3.11.1, and latest from v3 branch.

The crash is shown in the attached XCode screenshot.

<img width="789" alt="crash" src="https://cloud.githubusercontent.com/assets/1736144/16079419/dcb8767e-3346-11e6-97a2-16e35599dd3d.png">

The access violation happens if garbage collection take place. To reproduce, create a new js project using cocos command line, and in app.js, add the following before the end of the HelloWorldLayer constructor:

```
        this.sprite.runAction(
            cc.sequence(
                cc.rotateBy(2, 90).easing(cc.easeElasticInOut(0.5)),
                cc.rotateBy(0.5, 90)
            ).repeatForever()
        );

        cc.sys.garbageCollect();
```

This crashes if easing function called, otherwise it does not.

Note, this is a trivial example to show the issue. This is causing crashes all over our game which is being upgraded from v3.9 to v3.11 (works fine on v3.9). For example, garbage collection is requested whenever a scene transition finishes, so any actions with easing that are created within the incoming scene will cause this crash.

**Comment by zilongshanren** [comment]
@pandamicro  please take a look at this issue.

**Comment by arloistale** [comment]
This issue also exists in 3.11. Every version before that is fine. Please help this issue is breaking us :(

**Comment by slackmoehrle** [comment]
@zilongshanren @pandamicro @linshun this issue is becoming a bigger deal on the forums. It seems that a number of folks are now getting hit by it. v3.11.1 and v3.12 from GitHub are also affected.

**Comment by pandemosth** [comment]
I've tracked down the issue to jsb_ref_rebind function in ScriptingCore.cpp, where a new js obj (for easing, repeat, etc) is being bound to the new action, but is not being rooted so eligible for garbage collection.
Thats my primitive understanding of it at least, would appreciate comment from @pandamicro / @ricardoquesada who wrote the function. Cheers.

This fix seems to work for me, if anyone else wants to test it too:
https://github.com/pandemosth/cocos2d-x/commit/405d6f833c0b6d8dca832f50a82981093fc34a40

**Comment by minggo** [comment]
@pandemosth thanks for your sharing, i have asked @pandamicro to take a look. He added these codes.

**Comment by pandamicro** [comment]
Thanks for reporting this, I will dig into it this week, sorry for the inconvenience. @pandemosth  I think your hypothesis is valid, ~~I will try to fix it using another way because `AddNamedObjectRoot` may cause memory leak.~~

By the way, have you activated `CC_ENABLE_GC_FOR_NATIVE_OBJECTS` in ccConfig.h ？

**Comment by pandemosth** [comment]
Hey @pandamicro in my case CC_ENABLE_GC_FOR_NATIVE_OBJECTS is not activated.
Thanks

**Comment by pandamicro** [comment]
@pandemosth I reproduced the issue, and sorry about what I said earlier, your solution is the correct one, when `CC_ENABLE_GC_FOR_NATIVE_OBJECTS` is disabled, we need to manually root JS object to prevent them from being garbage collected, and in jsb_ref_rebind, it's missing.
