### ISSUE TITLE
`tinyxml2` missing when building `libsimulator`

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#15879]
I tried to build the prebuilt libraries and they failed citing errors in **libsimulator**

```
The following build commands failed:
    CompileC build/libsimulator.build/Release-iphonesimulator/libsimulator\ iOS.build/Objects-normal/i386/RuntimeCCSImpl.o /Volumes/GitHub/cocos2d-x/tools/simulator/libsimulator/lib/runtime/RuntimeCCSImpl.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/libsimulator.build/Release-iphonesimulator/libsimulator\ iOS.build/Objects-normal/x86_64/RuntimeCCSImpl.o /Volumes/GitHub/cocos2d-x/tools/simulator/libsimulator/lib/runtime/RuntimeCCSImpl.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    Libtool build/libsimulator.build/Release-iphonesimulator/libsimulator\ iOS.build/Objects-normal/i386/libsimulator\ iOS.a normal i386
    Libtool build/libsimulator.build/Release-iphonesimulator/libsimulator\ iOS.build/Objects-normal/x86_64/libsimulator\ iOS.a normal x86_64
    CreateUniversalBinary /Volumes/GitHub/cocos2d-x/prebuilt/ios/simulator/libsimulator\ iOS.a normal i386\ x86_64
(5 failures)
Error running command, return code: 65.
```

I tried to build **tools/simulator/libsimulator/proj.ios/libsimulator.xcodeproj**, it fails

![screen shot 2016-06-17 at 4 03 45 pm](https://cloud.githubusercontent.com/assets/7491758/16163267/5db7e038-34a6-11e6-81f6-835a5e2e30f2.png)

I opened **tools/simulator/libsimulator/proj.ios/libsimulator.xcodeproj** and indeed **tinyxml2** is missing and there are no **tinyxml2** files anywhere in **tools/simulator/libsimulator/lib**.

As a quick test, I downloaded **tinyxml2** and added `tinyxml2.c` and `tinyxml2.h` to **tools/simulator/libsimulator/lib** then added to Xcode project and everything builds again.

**Comment by minggo** [comment]
Will you change

``` c++
include "tinyxml2.h"
```

to 

``` c++
include "tinyxml2/tinyxml2.h"
```

to have a try?

**Comment by slackmoehrle** [comment]
Ah, yes, I see all of the **Header Search Paths** in build settings. Indeed it does work. I can build the Xcode project and also `cocos gen-libs` succeeds as well.

**Comment by ricardoquesada** [comment]
can we close this bug? or should we fix `RuntimeCCimpl`? BTW, what is the `RuntimeCCImpl` file for?

**Comment by slackmoehrle** [comment]
@ricardoquesada `RuntimeCCimpl` does indeed require a fix. Replacing: `include "tinyxml2.h"` with `include "tinyxml2/tinyxml2.h"`

**Comment by adesentenac** [comment]
I've submitted https://github.com/cocos2d/cocos2d-x/pull/15900 to fix the include paths.
Replacing tinyxml2/tinyxml2.h by tinyxml2.h was a change I made in https://github.com/cocos2d/cocos2d-x/pull/15837 because the headers in the external folder where conflicting with the system one when not using prebuilts.
