### ISSUE TITLE
Linking with pre-built libraries fails for iOS.

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#15889]
I tested this in `v3.11.1` and everything works as expected. This bug occurs in branch `v3` and `v3.12`.
I generated the pre-built libraries using `cocos gen-libs -c -p ios` and they compile successfully.

When I try to drop them into a project, I get the following linker errors:

<img width="760" alt="screen shot 2016-06-20 at 9 41 38 am" src="https://cloud.githubusercontent.com/assets/7491758/16201038/bdd3f2e8-36dd-11e6-9d8d-4f43f3008aab.png">

**Comment by ricardoquesada** [comment]
@minggo @linshun what about removing the "gen-libs" functionality from "cocos" and put it in a different script.

**Comment by slackmoehrle** [comment]
@zilongshanren said this requires **CoreText.framework** and this indeed does fix the problem. I will send in a PR to document this in README and RELEASENOTES.

**Comment by zilongshanren** [comment]
@slackmoehrle  Thanks.

**Comment by minggo** [comment]
@ricardoquesada Why need to use another script?

**Comment by ricardoquesada** [comment]
@minggo because the script `cocos` was created to help users manage its games: compile their game, run it, create new games, create spritesheets, etc...

but building cocos2d libs with `cocos` it outside the scope of the `cocos` tool. I think it was added only because some there was no better place to put it... but it shouldn't be there.
less is more

**Comment by minggo** [comment]
I think cocos can be used more than just for compile and run. I think gen-lib is part of game, because developers may want to use binary version. And there are `gen-simulator`, `gen-template`, these command is needed for some developers when developing a game.

Because cocos uses plugin, so different command don't effect other command. Though these commands are not needed for all developers, but they are needed from some developers and our own tools, such as creator. 

If we change to put it into other places, then we need to add a new environment variable, break compatibility, and may be write duplicated codes. So i think it is better to keep these commands here. And I there is not develop say it is not good to use `cocos gen-libs`.

**Comment by ricardoquesada** [comment]
no need to add new env. variables. 
I think this is minor issue, but I think it is an issue to add that kind of functionality to `cocos`.

**Comment by minggo** [comment]
yep, we can discuss what functions can be added into cocos. Then we can avoid it in future.

**Comment by ricardoquesada** [comment]
sure. my point is this... we tell users to use `cocos` to create and run new games... so the type `cocos` and they see this:

```
Available commands:
    run              Compiles, deploy and run project on the target.
    gen-libs         Generate prebuilt libs of engine. The libs will be placed in 'prebuilt' folder of the engine root path.
    luacompile       Encrypt and/or compile lua files.
    gui              shows the GUI
    deploy           Compile and deploy a project to a device/simulator.
    package          Manage package for cocos.
    compile          Compile projects to binary.
    framework        Manage frameworks for the project.
    gen-simulator    Generate Cocos Simulator.
    new              Creates a new project.
    jscompile        Compile and/or compress js files.
    gen-templates    Generate templates for Cocos Framework.
```

"what are those commands for?" will ask most of the users

**Comment by minggo** [comment]
So should we ask it in forum?

**Comment by ricardoquesada** [comment]
could be... since we have other more important things to do, I wouldn't make this change right now. Instead I would keep it in our minds so when the next opportunity to make a big change in `cocos` arrives, we also move the extra functionality somewhere else.

**Comment by slackmoehrle** [comment]
I cover some of these options in the `cocos command-line` chapter in docs/ However, I don't cover them all. I am happy to cover more if I get clarification on what they do.

**Comment by minggo** [comment]
@slackmoehrle so you don't know the commands too?

**Comment by minggo** [comment]
@slackmoehrle I think we need a PR for cocos2d-x too.

**Comment by slackmoehrle** [comment]
@minggo I know some of them and some of them are covered in the **cocos command-line chapter** I want to cover all of them in the chapter.

```
Available commands:
    run              Compiles, deploy and run project on the target.
    gen-libs         Generate prebuilt libs of engine. The libs will be placed in 'prebuilt' folder of the engine root path.
    luacompile       Encrypt and/or compile lua files.
    gui              shows the GUI
    deploy           Compile and deploy a project to a device/simulator.
    package          Manage package for cocos.
    compile          Compile projects to binary.
    framework        Manage frameworks for the project.
    gen-simulator    Generate Cocos Simulator.
    new              Creates a new project.
    jscompile        Compile and/or compress js files.
    gen-templates    Generate templates for Cocos Framework.
```

 From this list:

**`luacompile`** - is this different from `compile`? If you have a `lua` project, do you use `cocos compile` or `cocos luacompile`? Meaning Lua users would _never_ use `cocos compile`?

**`gui`** - what gui? Cocos Launcher? That is in **/Applications** on OS X by a default install but `cocos gui --help` return: `FSPathMakeRef(cocos2d-x/tools/cocos2d-console/bin/Cocos2d-Console-GUI.app) failed with error -43.` so it seems it is being looked for in **cocos2d-x/tools/cocos2d-console/bin/Cocos2d-Console-GUI.app** I have no idea what `Cocos2d-Console-GUI.app` is even. If this is a real thing, @ricardoquesada  and I should look at it.

**`framework`** - What is this used for and why would a user use it? To change from 3.10 to 3.11, as an example? To change locations to a different set of frameworks on the system to swap back and forth for testing? `cocos framework --help` seems to be invalid for me:

``` sh
$ cocos framework
usage: cocos framework [-h] COMMAND arg [arg ...]
cocos framework: error: too few arguments

$ cocos framework -h
Fatal: invalid command 'cocos framework -h'

$ cocos framework --help
Fatal: invalid command 'cocos framework --help'
```

**`gen-simulator`** - under what circumstances would a user want to do this? Does this build the `libsimulator` project?

**`jscompile`** - same questions as `luacompile` above.

**`gen-templates`** - I know what this does and it seems to me a user would only run this if they update Cocos2d-x version to ensure templates are up to date, i.e if they start a new project they might run this one time, before running `cocos new`

**Comment by minggo** [comment]
@natural-law could you please take a look and describe the commands to @slackmoehrle , then @slackmoehrle can complete the the documentation.

**Comment by natural-law** [comment]
http://www.cocos2d-x.org/wiki/Cocos2d-console
@slackmoehrle 
Here is a document in English I write before. You can see most of the commands usage.

For more details of the commands:
- Commands `gen-simulator`, `gen-libs` & `gen-templates` are added for Cocos Bundle Package (I mean the bundle with Cocos Studio).
- In my mind, command `framework` is added by @dualface team. And when the `package` command is added, the `framework` is duplicated. I think you can ask @darkdukey for more details about `framework` & `package`
- Command `gui` is added by @ricardoquesada.
- Command `luacompile` & `jscompile` are tools for compiling scripts. They are used in `compile` command in some cases.

**Comment by ricardoquesada** [comment]
we can safely remove `cocos gui` since it was supposed to call "cocos-console-gui", the GUI frontend for `cocos`, but the GUI was cancelled.

In fact, I don't recall merging the `cocos gui` PR... probably someone else merge my PR about `cocos gui`. In any case, we can safely remove it.

**Comment by slackmoehrle** [comment]
@natural-law I'm sorry, but your explanation isn't good enough for me to work with.

Example:
- Commands `gen-simulator`, `gen-libs` & `gen-templates` are added for Cocos Bundle Package (I mean the bundle with Cocos Studio).

But Cocos Studio is EOL'd, so do we still need these commands? I know we do `gen-libs`. But what does `gen-simulator` and `gen-templates` actually do? According to: http://www.cocos2d-x.org/wiki/Cocos_gen-simulator all it says is **Generate Cocos Simulator.**! What does this mean? What is the simulator? Why would a user need to do this? We need to explain to our users. A simple, non-descriptive sentence is not good enough. Same with `gen-templates` all it says is: **Generate templates for Cocos Framework.**.
- In my mind, command `framework` is added by @jinyuliao team. And when the `package` command is added, the `framework` is duplicated. I think you can ask @darkdukey for more details about `framework` & `package`

But @darkdukey is not a member of our team anymore. I can surely reach out, but if he is the only one that has answers, we should do a knowledge transfer so we don't have to bother him in the future (unless he chooses to participate).
- Command `gui` is added by @ricardoquesada.

I don't think @ricardoquesada GUI tool was every officially added. Perhaps we should remove the -gui option for now. This prevents users running it, seeing errors and then asking questions.
- Command `luacompile` & `jscompile` are tools for compiling scripts. They are used in `compile` command in some cases.

Sorry, I need more here. The Wiki page just says: **Compile the .js files to .jsc.**. This isn't helpful. Why do users run `cocos jscompile ...`? Does `cocos jscompile ...` replace the need to run `cocos compile ...`? Doesn't `cocos compile ...` do everything if a user is developing with JavaScript? I have written code for the PG Samples and never needed to touch `cocos jscompile ...`. Same thoughts for `cocos luacompile ...` as well..

**Comment by natural-law** [comment]
@slackmoehrle Sorry for my simple reply.
- `gen-simulator` is used for generating simulator. The simulator is for preview function in Cocos Studio at first. But now Cocos Creator is using it for preview the project too.
- `gen-templates` is used for generating [**binary templates**<sup>1</sup>](#binary-template). Binary templates are required by **Cocos Bundle Package**. Also they are required by Cocos Creator now.

The reason of `gen-libs`, `gen-simulator` & `gen-templates` are added into `cocos console` is: Once developers modified the code of engine. They can use these commands re-generate libs, simlator & tempates for the Cocos Bundle & Cocos Creator.
- About the `framework` & `package`, maybe you can try to connect with @hugohuang1111 , I found that most code of the two commands are wrote by him. But I'm not sure whether he is also left our team or not.
- About `luacompile` & `jscompile`. They are tool commands for encrypting the lua & js scrips in the game. They are invoked once `cocos compile` is invoked with `-m release` argument. Also developers can invoke them manually for encrypting their scripts.

[1. **binary templates**: Templates using cocos2d-x as pre-built library, but not source code.](id:binary-template)

**Comment by slackmoehrle** [comment]
@natural-law this is helpful. I will use it to update the Cocos command-line chapter.

**Comment by minggo** [comment]
@slackmoehrle can i close the issue?
