### ISSUE TITLE
typo on video play code

### ISSUE THREAD

**Issue by mallun** [cocos2d/cocos2d-x#15887]
in Cocos2dxVideoView.java
public void fixSize() {
if (mFullScreenEnabled) {
fixSize(0, 0, mFullScreenWidth, mFullScreenHeight);
} else {
fixSize(mViewLeft, mViewTop, mViewWidth, mVideoHeight);
}
}
mVideoHeight should be mViewHeight
This typo still exists on 3.11
Hope it can be fix in next release

**Comment by ricardoquesada** [comment]
are you sure it is not fixed in v3.11?
seems to be fixed in v3.11: https://github.com/cocos2d/cocos2d-x/blob/cocos2d-x-3.11/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxVideoView.java#L336

please, double check your version. reopen if you think the bug is still there.
