### ISSUE TITLE
Cocos command-line tool -> --list-templates returns {}

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#15890]
Latest from Github, try running: `cocos new --list-templates` and you will get:

```
$ cocos new --list-templates
{}
$
```

To be sure, I tried to run `cocos gen-templates` and then `cocos new --list-templates` again and same thing, just `{}`

**Comment by minggo** [comment]
@natural-law Will you take a look?

**Comment by natural-law** [comment]
@minggo Argument `--list-templates` is added by Riq in [this commit](https://github.com/cocos2d/cocos2d-console/commit/e79bdbf375ff814c12938ab0fcbaffaefc89ff71#diff-619073a9bc56c28519d2307f332c494bR135)

I've just took a look at the logic code. It's finding a file `template_metadata/config.json` in each template folder. But I don't know when this file is added/removed. So, I've no idea how to solve the problem.

I think it's better to discuss this problem with Riq.

**Comment by minggo** [comment]
@ricardoquesada would you please take a look?

**Comment by ricardoquesada** [comment]
yes, `--list-templates` was supposed to be part of the big refactoring a did for the cocos console, including a GUI frontend. but unfortunately that project was cancelled.
They can be removed safely.

I'll remove them.

**Comment by ricardoquesada** [comment]
fixed here: https://github.com/cocos2d/cocos2d-console/pull/352
and in v3.

let me know if you think it should be fixed in v3.12

**Comment by minggo** [comment]
Thanks @ricardoquesada , keep 3.12 as it is now is ok to me since it is not a critical bug.

**Comment by ricardoquesada** [comment]
ok. thanks.
