### ISSUE TITLE
Please Attention: simplify file raw data read APIs.

### ISSUE THREAD

**Issue by halx99** [cocos2d/cocos2d-x#15896]
@minggo 
I suggest only leave one API for read raw data, such as:

```
std::string FileUtils::getFileData(const std::string& filename)
{
    std::string s;
    getContents(filename, &s);
    return s;
}
```

Remark: The 'std::string' is not just string, Actual it can handle binary or null-terminated-string.
So, at least, for engine, We can replace every raw read APIs with this API.

**Comment by minggo** [comment]
We can deprecated other API, but can not remove them.

**Comment by halx99** [comment]
OK, I argree. 
By the way: I relaize that The getStringFromFile API always truncate, does this needed? 
It think, for performance, do not truncate is better.

**Comment by minggo** [comment]
>  I relaize that The getStringFromFile API always truncate, does this needed? 

What did you mean?

**Comment by halx99** [comment]
See follow: 

```
std::string FileUtils::getStringFromFile(const std::string& filename)
{
    std::string s;
    getContents(filename, &s);

    // truncated
    s.resize(strlen(s.data())); // I think this statement can be removed.

    return s;
}
```

**Comment by halx99** [comment]
对于多数文本文件，s.resize(strlen(s.data()))会导致不必要的循环. 多数都是最坏的情况，遍历一边整个文件字节数据

**Comment by minggo** [comment]
I have not idea why it needs to be truncated.

**Comment by halx99** [comment]
I create a PR to remove it.

**Comment by xpol** [comment]
The old implementation of `FileUtils::getStringFromFile()` was doing the truncated.
I just keep the behavior of it when I refactor `FileUtils`.

I think we should not change the behavior.

**Comment by halx99** [comment]
I have no idea for the explicit reson to reserve this behavior.

**Comment by halx99** [comment]
PR:  #15939
