### ISSUE TITLE
cpp-tests Scene3D -> description buttons don't work

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/cocos2d-x#15909]
- cd cpp-tests
- click Node::Scene3D
- click Description
- click `hair` or `glass`

The hair or glass are not changed.

In v3.11, it works as expected. I don’t remember if there is any codes except your VR PR changed the logic.

**Comment by minggo** [comment]
`27:Node:Camera 3D Test->5:Camera ArcBall Moving` can not move the scene and click the `Switch Operation` and `Switch Target` doesn't have effect.

**Comment by ricardoquesada** [comment]
Patch for v3.12: https://github.com/cocos2d/cocos2d-x/pull/15931

Patch for v3: https://github.com/cocos2d/cocos2d-x/pull/15930

**Comment by ricardoquesada** [comment]
merged for v3.
v3.12 patch still open. @minggo I've not merged the v3.12 patch since you own that branch. let me know if you have any question about it. thanks.

**Comment by minggo** [comment]
@ricardoquesada Thanks, i will have a try.

**Comment by minggo** [comment]
Thanks, it is fixed.

**Comment by ricardoquesada** [comment]
With this PR I found a few bugs in VR now :(... I'll send a new PR tomorrow.

**Comment by minggo** [comment]
Ok.
