### ISSUE TITLE
UITextField crash when text exceeds content with enabled cursor

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#15926]
Repeating:
In UITextFieldTest_LineWrap::init

add 
'''textField->setCursorEnabled( true );'''
after
''' TextField\* textField = TextField::create("input words here","fonts/Marker Felt.ttf",30);'''

then run test and in test tape some letters till test will crash.

**Comment by minggo** [comment]
Sorry, i don't quite understand the issue? Could you please describe it in more detail?

**Comment by sbrednikhin** [comment]
Sorry for misunderstanding.

If you will enter symbols (a lots of symbols) into text field that have some content size and enabled cursor - it will crash when cursor walks outside of content area.

**Comment by minggo** [comment]
Will you provide a test case? @zilongshanren could you please take a look?

**Comment by AIGRIND-LLC** [comment]
Confirmed that bug in cocos2dx v3.12.
To reproduce the crash a TextField must have fixed content size that is not enough to display all text content.
**Cursor must be enabled** also for this TextField.

![text_fielad_1](https://cloud.githubusercontent.com/assets/6168693/19072447/8350f52a-8a35-11e6-8ae8-8a4f04f2ed7a.png)

If you click on the TextField the app will crash on assert.

![text_field_2](https://cloud.githubusercontent.com/assets/6168693/19072586/54ddd0b8-8a36-11e6-9cf1-85e23ec02423.png)

**Comment by AIGRIND-LLC** [comment]
There is pull request containing fix for this issue:
https://github.com/cocos2d/cocos2d-x/pull/17786

**Comment by zilongshanren** [comment]
@AIGRIND-LLC 
I have tested this issue on IOS, and it didn't crash.

 I have tested this issue with the latest v3 branch code.

Does this issue happen only on Win32 or cocos2d-x v3.12?

thanks.

**Comment by sbrednikhin** [comment]
All versions of cocos between 3.12 and 3.14. On Win32 and Android.
More: It's not fully stable crush. It may crush after 3 symbols or after 20. It depends on cursor "pahse".
Please look into pull request.

**Comment by AIGRIND-LLC** [comment]
@zilongshanren
This bug can be reproduced in the latest version of framework (incl. 3.15)
Did you **enable cursor** for the text field? Also a **fixed content size** must be set for it.

**Comment by zilongshanren** [comment]
@AIGRIND-LLC  I do follow your instructions and add `''textField->setCursorEnabled( true );` in cpp-tests/UITextFieldTest_LineWrap, anything missing here?

**Comment by sbrednikhin** [comment]
Add 
`textField->setCursorEnabled( true );
textField->setCursorChar( '@' );`.
Looks like font used in UITextFieldTest_LineWrap has no default symbol for cursor.

You may also change 
` textField->setContentSize(Size(240, 170));` to  ` textField->setContentSize(Size(240, 30));` it will require less typing until crash.

**Comment by zilongshanren** [comment]
@sbrednikhin 
Thanks, I will give it a try.

**Comment by zilongshanren** [comment]
@sbrednikhin 
the PR is merged, thanks for the testing method.

@AIGRIND-LLC 
thanks for the patch.

**Comment by dumganhar** [comment]
After merging this Pull Request, it breaks ShaderTest/ShaderRetroEffect.
Because `Label::getLetter(i)` will return `nullptr` if the letter is a `space`.
