### ISSUE TITLE
FPS could not be shown on iOS

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#15934]
After this Pull Request (https://github.com/cocos2d/cocos2d-x/pull/15853) was merged, FPS would not be shown on iOS while it works ok on Android.
I reverted the changes in this PR and FPS was shown correctly on iOS too.

@ricardoquesada , please help to check what's going wrong. Thanks.

**Comment by ricardoquesada** [comment]
sent PR to v3.12. awaiting @minggo approval.
I'll merge the PR sent to v3.
