### ISSUE TITLE
Node:Particles Test will cause huge lag

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#15937]
@ricardoquesada   This PR https://github.com/cocos2d/cocos2d-x/pull/15646 will alloc indices memory on the fly and it will cause particles play laggy... please refer to cpp-tests -> Node: Particles for example.

Here is the logging message.

```
cocos2d: QuadCommand: resizing index size from [90] to [534]
cocos2d: QuadCommand: resizing index size from [534] to [564]
cocos2d: QuadCommand: resizing index size from [564] to [708]
cocos2d: QuadCommand: resizing index size from [708] to [852]
cocos2d: QuadCommand: resizing index size from [852] to [1002]
cocos2d: QuadCommand: resizing index size from [1002] to [1110]
cocos2d: QuadCommand: resizing index size from [1110] to [1122]
cocos2d: QuadCommand: resizing index size from [1122] to [1248]
cocos2d: QuadCommand: resizing index size from [1248] to [1272]
cocos2d: QuadCommand: resizing index size from [1272] to [1362]
cocos2d: QuadCommand: resizing index size from [1362] to [1410]
cocos2d: QuadCommand: resizing index size from [1410] to [1446]
cocos2d: QuadCommand: resizing index size from [1446] to [1464]
cocos2d: QuadCommand: resizing index size from [1464] to [1518]
cocos2d: QuadCommand: resizing index size from [1518] to [1560]
cocos2d: QuadCommand: resizing index size from [1560] to [1668]
cocos2d: QuadCommand: resizing index size from [1668] to [1776]
cocos2d: QuadCommand: resizing index size from [1776] to [1782]
cocos2d: QuadCommand: resizing index size from [1782] to [1884]
cocos2d: QuadCommand: resizing index size from [1884] to [1908]
cocos2d: QuadCommand: resizing index size from [1908] to [1956]
cocos2d: QuadCommand: resizing index size from [1956] to [1992]
cocos2d: QuadCommand: resizing index size from [1992] to [2046]
cocos2d: QuadCommand: resizing index size from [2046] to [2058]
cocos2d: QuadCommand: resizing index size from [2058] to [2124]
cocos2d: QuadCommand: resizing index size from [2124] to [2142]
cocos2d: QuadCommand: resizing index size from [2142] to [2166]
cocos2d: QuadCommand: resizing index size from [2166] to [2268]
cocos2d: QuadCommand: resizing index size from [2268] to [2292]
cocos2d: QuadCommand: resizing index size from [2292] to [2364]
cocos2d: QuadCommand: resizing index size from [2364] to [2382]
cocos2d: QuadCommand: resizing index size from [2382] to [2466]
cocos2d: QuadCommand: resizing index size from [2466] to [2496]
cocos2d: QuadCommand: resizing index size from [2496] to [2556]
cocos2d: QuadCommand: resizing index size from [2556] to [2592]
cocos2d: QuadCommand: resizing index size from [2592] to [2610]
cocos2d: QuadCommand: resizing index size from [2610] to [2664]
cocos2d: QuadCommand: resizing index size from [2664] to [2724]
cocos2d: QuadCommand: resizing index size from [2724] to [2784]
cocos2d: QuadCommand: resizing index size from [2784] to [2832]
cocos2d: QuadCommand: resizing index size from [2832] to [2844]
cocos2d: QuadCommand: resizing index size from [2844] to [2910]
cocos2d: QuadCommand: resizing index size from [2910] to [2940]
cocos2d: QuadCommand: resizing index size from [2940] to [2952]
```

**Comment by ricardoquesada** [comment]
Sent PR both to v3 and v3.12.
I'll merge it in v3. @minggo please, take a look at the PR for v3.12:  https://github.com/cocos2d/cocos2d-x/pull/15946 Thanks.

**Comment by minggo** [comment]
@ricardoquesada thanks, i have merged it into v3.12.
@zilongshanren could you please test it or ask developer to do testing, thanks.

**Comment by ricardoquesada** [comment]
thanks. closing this issue. we should reopen it in case the developer finds more bugs.

**Comment by mori1234** [comment]
the last  __indices new is not inserted _ownedIndices when is delete ?
void QuadCommand::reIndex(int indicesCount)
{
    // first time init: create a decent buffer size for indices to prevent too much resizing
    if (__indexCapacity == -1)
    {
        indicesCount = std::max(indicesCount, 2048);
    }

    if (indicesCount > __indexCapacity)
    {
        // if resizing is needed, get needed size plus 25%, but not bigger that max size
        indicesCount *= 1.25;
        indicesCount = std::min(indicesCount, 65536);

        CCLOG("cocos2d: QuadCommand: resizing index size from [%d] to [%d]", __indexCapacity, indicesCount);

         **
          // the last  __indices new is not inserted _ownedIndices
          // when is delete ?
          **

          _ownedIndices.push_back(__indices);
          __indices =  new (std::nothrow) GLushort[indicesCount]; 

      
        __indexCapacity = indicesCount


    }

    for( int i=0; i < __indexCapacity/6; i++)
    {
        __indices[i*6+0] = (GLushort) (i*4+0);
        __indices[i*6+1] = (GLushort) (i*4+1);
        __indices[i*6+2] = (GLushort) (i*4+2);
        __indices[i*6+3] = (GLushort) (i*4+3);
        __indices[i*6+4] = (GLushort) (i*4+2);
        __indices[i*6+5] = (GLushort) (i*4+1);
    }

    _indexSize = indicesCount;
}

memory leak?
