### ISSUE TITLE
Xcode 7.3 编译 libcocos2d(mac) error

### ISSUE THREAD

**Issue by tiancode** [cocos2d/cocos2d-x#15944]
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib/libsqlite3.dylib (No such file or directory)

solution http://discuss.cocos2d-x.org/t/how-to-compile-with-xcode-7/22677

**Comment by ricardoquesada** [comment]
what cocos2d-x version are you using? I think this has been fixed long ago.

**Comment by minggo** [comment]
Yep, i just compile cpp-tests too, there is not problem.
Could you please describe your problem step by step?

**Comment by minggo** [comment]
I don't met the issue and i am using Xcode 7.3 for a long time. So close this issue.
