### ISSUE TITLE
getTimeInMilliseconds

### ISSUE THREAD

**Issue by LeeMyoungYeol** [cocos2d/cocos2d-x#15968]
Wrong time on android  -> utils::getTimeInMilliseconds()
- add  (long long)

long long getTimeInMilliseconds()
{
    struct timeval tv;
    gettimeofday (&tv, nullptr);
    return (long long)tv.tv_sec \* 1000 + tv.tv_usec / 1000;
}

**Comment by minggo** [comment]
@LeeMyoungYeol What's the error? How can i reproduce it?

**Comment by jasonwan2016** [comment]
I found a long long value will be wrong in android, but currect in win32.
For example: store 1467282355000 in a long long variable, it will be correct in win32, but become negative in android (A samsung device (pad)).

**Comment by minggo** [comment]
@jasonwan2016 did you mean Android doesn't support `long long`? And have you met problem in cocos2d-x with this issue? Do you have any suggestion with this issue? Use `long` instead?

**Comment by LeeMyoungYeol** [comment]
My device android samsung s4  bad result, The iPhone is a good result.

'return tv.tv_sec \* 1000 + tv.tv_usec / 1000;'  
The result comes across as negative.
So I added the (long long).

**Comment by minggo** [comment]
@LeeMyoungYeol Got it, will you send a PR to fix it?

**Comment by minggo** [comment]
#16016

**Comment by minggo** [comment]
@LeeMyoungYeol How did you print the result?
