### ISSUE TITLE
git clone failed on Mac OS X 10.11.5

### ISSUE THREAD

**Issue by qinhanlei** [cocos2d/cocos2d-x#15969]
```
...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

git version 2.7.4 (Apple Git-66)
curl 7.43.0 (x86_64-apple-darwin15.0)
OpenSSL 0.9.8zh 14 Jan 2016

**Comment by ricardoquesada** [comment]
could you try again? perhaps it was your internet conneciton

**Comment by slackmoehrle** [comment]
Hi @qinhanlei This has happened to me when my Internet connection gets interrupted. I am running **git 2.8.0** and I cloned the repo this morning without an issue.

**Comment by qinhanlei** [comment]
@ricardoquesada 
That was very strange in recent days. 
I tried clone this repo several times and failed on my new mac book pro which in my office.
The Internet connection is well.
Perhaps I need a proxy? I'll try again next time.
Thanks for your reply.

**Comment by qinhanlei** [comment]
Hi @slackmoehrle , 
Thanks for your reply, 
I'll try proxy this day, perhaps some WALL improved cause some G19, G21 thing was going on in my city...

**Comment by minggo** [comment]
@qinhanlei Are you in China? I have not problem to access github these days, and i am in China too.

**Comment by qinhanlei** [comment]
Hi @minggo , 
Yeah, I'm in Hangzhou now.
Recently I access github also fine but cocos2d-x repo.
I tried VPN which in California, still got failed:

```
Cloning into 'cocos2d-x'...
remote: Counting objects: 418164, done.
remote: Compressing objects: 100% (169/169), done.
error: RPC failed; curl 56 SSLRead() return error -3626.00 KiB/s    
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

But I clone other repos all well like below:

```
Cloning into 'Urho3D'...
remote: Counting objects: 104586, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 104586 (delta 29), reused 5 (delta 5), pack-reused 104512
Receiving objects: 100% (104586/104586), 95.71 MiB | 3.48 MiB/s, done.
Resolving deltas: 100% (82587/82587), done.
Checking connectivity... done.
```

It seems the Internet connection is well.
Is that something wrong with my git configuration or else?

**Comment by slackmoehrle** [comment]
I just tried myself

``` sh
$ git clone git@github.com:cocos2d/cocos2d-x.git
Cloning into 'cocos2d-x'...
remote: Counting objects: 418179, done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 418179 (delta 24), reused 0 (delta 0), pack-reused 417999
Receiving objects: 100% (418179/418179), 866.84 MiB | 29.00 KiB/s, done.
Resolving deltas: 100% (279324/279324), done.
Checking connectivity... done.
```

**Comment by ricardoquesada** [comment]
I guess it is related to the cocos2d-x repo size which might be bigger than Urtho3d.

**Comment by minggo** [comment]
@qinhanlei I think it is nothing about git configuration. I am cloning cocos2d-x v2 branch, and there is ok until now.

```
A03101308207:SourceCode minggo$ git clone git@github.com:cocos2d/cocos2d-x.git -b v2 cocos2d-x-v2
Cloning into 'cocos2d-x-v2'...
remote: Counting objects: 418302, done.
remote: Compressing objects: 100% (6/6), done.
Receiving objects:  38% (158955/418302), 211.32 MiB | 132.00 KiB/s 
```

I am cloning v2 branch just for convenient, because it is not easy to switch from v3 to v2.

**Comment by minggo** [comment]
And i don't use VPN. I am in Xiamen.

**Comment by minggo** [comment]
I can clone cocos2d-x in China. I think it is nothing about cocos2d-x. The only thing is that, cocos2d-x repo is too big but it is another issue. So close this issue.

**Comment by qinhanlei** [comment]
Hi, thanks for all your help.
I will try in other day else.

**Comment by mohshin-shah** [comment]
Please open the terminal and execute this 
git config --global user.email "youremail@xxx.xxx"
then try git clone

**Comment by geeksupport1** [comment]
http://stackoverflow.com/questions/30385939/git-clone-fails-with-sslread-error-on-os-x-yosemite

Here is a simple way to connect with your WIFI -

Click on Edit from the menu section
Virtual Network Editor
Change Settings
Add Network
Select a network name
Select Bridged option in VMnet Information -> Bridge to : Automatic
Apply
That's it. You might be asked password to connect. Add it and you would be able to connect to the network.
