### ISSUE TITLE
websocket doesn't support SSL

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#15972]

**Comment by ricardoquesada** [comment]
what is wss? and what is its use case? thanks.

**Comment by huangapple** [comment]
@ricardoquesada  
sorry, I didn't say that clearly. 
ws  is websocket, wss is websocket safe, like  http  and https  protocol ??
like https://github.com/cocos2d/cocos2d-x/blob/v3/tests/js-tests/src/ExtensionsTest/NetworkTest/SocketIOTest.js  line162, ws link.  
i can't  use wss protocol ,  even though my service support wss protocol .

**Comment by roed** [comment]
You have to compile libwebsockets with ssl support. The precompiled libraries that come with cocos do not have ssl support yet.

**Comment by minggo** [comment]
Yep, as the [compiling flags](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/blob/v3/contrib/src/websockets/rules.mak#L29) shows, SSL is disabled. I think we should enable it.

**Comment by huangapple** [comment]
what time to support ssl?

**Comment by Dimon4eg** [comment]
Here is PR [https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/61](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/61)

**Comment by minggo** [comment]
After enable ssl support and update lws to v2.1.0, it will crash if creating more than one WebSocket instance. The reason is discussed [here](https://github.com/warmcat/libwebsockets/issues/468). 

It seems we should only create one lws context, which means should refactor the implementation of WebSockets. Currently, WebSockets will create a new thread and create a new lws instance. We should use only one thread, and share the lws context across all WebSocket instances.

As [apple delate the requirements of ATS support](https://developer.apple.com/news/?id=12212016b) and it is a big refactor, so i think we should fix it in next version to have more testing time.

If you don't use WebSocket, use the library directly, then you can take a look of [this pr](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/261). Currently, iOS, mac and android are supported.

WebSocket: means cocos2d::WebSocket
lws: means libwebsockets

**Comment by dumganhar** [comment]
wss support was finished at https://github.com/cocos2d/cocos2d-x/pull/17172
Please help to test. 
Known issues:

1. Although libwebsockets source code has ignore `SIGPIPE` signal, xcode will still catch this kind of signal and pause at the breakpoint while debugging. But this will not cause any problems if you're not debugging.
2. Developers who is using linux system should update `binutils` (contain `ld` linker command line) to 2.27  & cmake to `3.7.2`.  If linux package manager (apt-get, yum) doesn't have an update version, you could install it from source code like the following command:

```sh
    # install new version cmake
    CMAKE_VERSION="3.7.2"
    CMAKE_DOWNLOAD_URL="https://cmake.org/files/v3.7/cmake-${CMAKE_VERSION}.tar.gz"
    echo "Download ${CMAKE_DOWNLOAD_URL}"
    curl -O ${CMAKE_DOWNLOAD_URL}
    tar -zxf "cmake-${CMAKE_VERSION}.tar.gz"
    cd "cmake-${CMAKE_VERSION}"
    ./configure > /dev/null
    make -j2 > /dev/null
    sudo make install > /dev/null
    echo "CMake Version: `cmake --version`"
    cd ..

    # install new version binutils
    BINUTILS_VERSION="2.27"
    BINUTILS_URL="http://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.gz"
    echo "Download ${BINUTILS_URL}"
    curl -O ${BINUTILS_URL}
    tar -zxf "binutils-${BINUTILS_VERSION}.tar.gz"
    cd "binutils-${BINUTILS_VERSION}"
    ./configure > /dev/null
    make -j2 > /dev/null
    sudo make install > /dev/null
    echo "ld Version: `ld --version`"
    echo "which ld: `which ld`"
    sudo rm /usr/bin/ld

```

**Comment by minggo** [comment]
About 2, i think we should install new binutils in `build/install-deps-linux.sh`.

**Comment by huangapple** [comment]
3.15 can't support ssl with public key is rsa2048, sha2 signature?
@minggo

**Comment by dumganhar** [comment]
> 3.15 can't support ssl with public key is rsa2048, sha2 signature?

@huangapple , I'm not sure about this.
We uses `libwebsockets-2.1.1` for websocket connection. Probably, you need to check it out in libwebsockets official (https://github.com/warmcat/libwebsockets).

**Comment by dumganhar** [comment]
@huangapple , I tested with the certificate which was got from `qcloud`, and I could make sure that it uses ras2048 and sha2 signature and it works.

![sig](https://cloud.githubusercontent.com/assets/493372/25160001/f1546f02-24e5-11e7-950e-74b076f63ddf.png)

**Comment by huangapple** [comment]
@dumganhar 
额，我那边是阿里云那边系统生成的， 可以开启https服务， 浏览器也能正常访问， 绿色的。
应该不会错的。

我把证书发给你， 你测试下吧？

**Comment by huangapple** [comment]
@dumganhar  
把证书发到你  jianhua.chen@cocos2d-x.org 这个邮件了
