### ISSUE TITLE
Glfw 3 support on Linux

### ISSUE THREAD

**Issue by azmeuk** [cocos2d/cocos2d-x#1598]
Hi,
Glfw 3 is not supported by cocos2d-x on linux, as explained here : http://www.cocos2d-x.org/boards/6/topics/18530 . However it is the default version in Fedora 17 for instance.

Maybe this could help : http://wiki.glfw.org/wiki/Moving_from_GLFW_2_to_3

Éloi

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2666
