### ISSUE TITLE
socketio  fireEvent 'message' event repeat?

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#15981]
at https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/SocketIO.cpp line 945, 946, fireEvent repeat？
Consider this situation, I invoke SIOClient::on("message").

**Comment by minggo** [comment]
I think they are for different purposes. `fireEvent` can send event to every listing object, it doesn't have to be a delegate of SocketIO, and `onMessage` just invoke delete's corresponding method.

**Comment by huangapple** [comment]
@minggo 
but i will receive ‘message’  message twice.

**Comment by minggo** [comment]
then i think you don't have to listen the event, just use delegate instead
