### ISSUE TITLE
在安卓下 ， 按电源键， 就再入游戏， 很经常崩掉。

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#16020]
在安卓下 ， 按电源键， 就再入游戏， 崩掉。
点击按钮切到其它应用，再回来， 也崩掉。
按home键， 在桌面上一小段时间（30秒）出来， 也很经常崩掉。
是因为  某些缓存的精灵帧被释放了， 导致加载不到？？
或者 部分 着色器被释放了， 没有重新加载？？

这是bug吗？ cocos引擎能帮处理吗？或有没有什么解决思路？

**Comment by minggo** [comment]
What's your engine version?
Did you use your own shader or create textures by yourself?

PS: please use english in later then developers all over the world can help you. You can paste english with Chinese like:

```
hello，how can i resolve it?
你好，请问该怎么解决呢？
```

**Comment by huangapple** [comment]
@minggo 
engine version 3.11.1
no use own shader, and no create textures by myself.

**Comment by minggo** [comment]
Could you paste the error stack or provide a test case to reproduce it?

**Comment by huangapple** [comment]
@minggo 
![image](https://cloud.githubusercontent.com/assets/10572028/16549752/12cb09ce-41d5-11e6-98b0-3a8111974f3a.png)

07-04 10:51:55.414: A/libc(14462): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 14969 (GLThread 2144)

**Comment by minggo** [comment]
@huangapple I think you should use `ndk-trace` to print human readable stack trace.

**Comment by liuyi** [comment]
在我的项目前期也遇到过这样的问题，花了大概两个星期去做各种测试优化才解决掉这一系列的问题。
这些问题主要是由于几个方面造成的。
1，js调用的c++对象被释放掉了，自己在js这边要判断好。
2，js在一帧里连续执行了比较重，消耗cpu时间的代码，导致程序假死或者被Android manager 自动杀死。
3，声音。 频繁的杀死所有声音或uncache声音。或杀死所有声音的一帧里，去播放了声音。
4、比较小的图片，在场景里的缩放比例比较大。会导致降帧非常多。但是不会挂，但是如果这个时候干了别的事情也耗cpu，也会死。

可能还有些没有提到，漏掉了。总之，要想优化好一个jsb的项目是要非常小心，非常有经验才行。

ps:这些问题在js里（除了4），在ios上表现得不明显。ios的代码优化得比较好，用起来比较舒服。。。安卓代码还有很大优化空间。

**Comment by huangapple** [comment]
@liuyi think you!!!!!!

@minggo can your team help me to fix it? i think it should be fixed in engine。

**Comment by liuyi** [comment]
@huangapple   引擎层面修复那是不太现实，至少现在。我尝试过了。这是jsb的特点，可以从js端优化从而屏蔽这些问题。。。

**Comment by minggo** [comment]
@huangapple if you can provide a test case then it will help to fix the issue. @pandamicro do you have any suggestion?

**Comment by huangapple** [comment]
androidManifest.xml  里面的  <uses-sdk android:minSdkVersion="8" />  一定要是8, 要不按电源， 或 切到其它应用， 横竖屏切换就崩。 （小米4c， andorid 5.1)

@minggo  这是为什么？  8感觉很少了， 如果要用到一些新的api， 那不是会麻烦一点？ 而且为什么填14或16， 会这样子？  是因为用到的一些库是 按 8来编译的吗？

**Comment by dumganhar** [comment]
Which api version did you use for compiling java code?
If you used high version (>10), you probably need to add `screenSize` to `android:configChanges` in the AndroidManifest.xml.

**Comment by huangapple** [comment]
android 19, 20, 21, 22, 23  都试过， 如果 uses-sdk android:minSdkVersion="8"   这个配置的不是8， 而是14或16， 切到其它应用就会崩。

**Comment by dumganhar** [comment]
minSdkVersion是指你的app要能跑在最小的android版本。我问的是你用来编译java代码的sdk版本。
如果是用Android Studio, 在build.gradle中有compileSdkVersion，如果是用ant/eclipse, 在project.properties中配置。还有，有尝试加上screenSize的配置么？

**Comment by huangapple** [comment]
我说的就是  编译用的sdk版本， 试过 android 19， 20， 21， 22， 23， 只要 android:minSdkVersion 不是8， 切到外部就会崩。  androidManifest.xml 里面除了改  android:minSdkVersion 这个， 没有改其它的。screenSize是配在 androidManifest.xml 里面？？那就没有， cocos 默认怎么样就怎么样的。

**Comment by dumganhar** [comment]
能尝试修改
android:configChanges="orientation|screenSize"试试么？

**Comment by huangapple** [comment]
好的， 我正在测试

**Comment by huangapple** [comment]
@dumganhar  测试了 ， 把  android:configChanges="orientation"  改成 android:configChanges="orientation|screenSize" 的话， 不管  android:minSdkVersion 是8， 还是14， 都不会崩了。
cocos要不要考虑在 xml里面 直接把 android:configChanges="orientation" 换成 android:configChanges="orientation|screenSize"？  还是有其它考虑？

**Comment by huangapple** [comment]
谢谢各位大大们的解答

**Comment by dumganhar** [comment]
@huangapple , screenSize是在高版本的api中才加入的，目前cocos2d-x已经回退到使用api level 10来编译java代码了，所以在3.13版本中不需要加入screenSize。
