### ISSUE TITLE
[Cocos2d-x 3.11, iOS] : AudioEngine does not play correctly some .wav files

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#16026]
On iOS `experimental::AudioEngine` does not play correctly some .wav files.
When this happens the sound play is interrupted by multiple small intervals of silence.
The issue could be sound frequency related.
The same sound converted in .mp3 play correctly.

Here a sound that does not play correctly on iOS 8.4 (iPhone 6).
[sound.wav.zip](https://github.com/cocos2d/cocos2d-x/files/345141/sound.wav.zip)

and here the test line:
`experimental::AudioEngine::play2d("sound.wav");`

**Comment by minggo** [comment]
It is better use platform specific audios. iOS supports .caf best, Android supports .ogg best.

**Comment by alfogrillo** [comment]
@minggo 
Is the .mp3 format safe for both Android and iOS?
On a Cocos2d-x book I found this table:
![table](https://cloud.githubusercontent.com/assets/19324622/16553152/c90075bc-41c6-11e6-8c8e-3ca3e83bf3db.png)

**Comment by minggo** [comment]
Yep, i think .mp3 is safer. What i mean is the best supported.

**Comment by alfogrillo** [comment]
Thanks for the info! :-)

**Comment by minggo** [comment]
It's my pleasure. Can i close the issue?

**Comment by alfogrillo** [comment]
Yes, you can!
I just suggest to extend the `AudioEngine` documentation such that the cocos2d-x user can be aware of the well supported audio formats for each platform.
Otherwise the `AudioEngine` is perceived as buggy!

**Comment by minggo** [comment]
@slackmoehrle will you add it into docs?
