### ISSUE TITLE
cocos2d-js iOS平台下socketIO重连会闪蹦

### ISSUE THREAD

**Issue by BiteLu** [cocos2d/cocos2d-x#16037]
cocos2d-js 3.11.1版本，iOS平台下，按了电源键锁屏，再解锁回游戏，socketIO会自动关闭，再次调用connect连接时，游戏就闪蹦。报错行：
![image](https://cloud.githubusercontent.com/assets/9947182/16578300/51aafaee-42cc-11e6-924f-cd527f1a3e7d.png)

报错如下：
`malloc: *** error for object 0x17017f13f: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug`。

**Comment by huangapple** [comment]
@dumganhar can you help fix it ?

**Comment by dumganhar** [comment]
@huangapple , I will check it.

**Comment by dumganhar** [comment]
I couldn't reproduce the issue you said. No crash occurred on my iphone6 with iOS9.3.3

**Comment by dumganhar** [comment]
The same issue as https://github.com/cocos2d/cocos2d-x/issues/16829
