### ISSUE TITLE
Using chrono::steady_clock() instead of gettimeofday for FPS calculation

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16046]
Hackers could modify system time to speed up game.
Game running should not depend on system time, it should depend on CPU clock time which could not be modified.

BTW, some articles said that the invocation of `clock_gettime` is faster and more precise than `gettimeofday`.

@minggo , any ideas?

**Comment by minggo** [comment]
Yep, sounds good.

> BTW, some articles said that clock_gettime is faster and more precise than gettimeofday.

Do you have any link of the doc?

**Comment by dumganhar** [comment]
I found a Chinese article here: http://www.cnblogs.com/leaven/archive/2011/03/21/1989946.html

You could google the function information to see whether we should use it. :)

**Comment by minggo** [comment]
`clock_gettime()` is not cross platform, may be we can use [std::clock()](http://en.cppreference.com/w/cpp/chrono/c/clock).

**Comment by Guy-kun** [comment]
To switch away from system time and time synchronization shifts in my game I changed ccUtils::getTimeInMilliseconds() to 

`long long getTimeInMilliseconds()
{
    return std::chrono::time_point_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()).time_since_epoch().count();
}`

This works on android, osx/ios and windows without any issues to me.
clock_gettime is not available on OSX

Maybe someone could review and use this in both gettime and getTimeInMilliseconds since the gettimeofday implementation shifts on android devices time to time during gameplay

**Comment by dumganhar** [comment]
@Guy-kun, thanks for reminding that we can use `std::chrono::steady_clock`. I will try that.

**Comment by dumganhar** [comment]
Documentation updated: 
- 1

http://en.cppreference.com/w/cpp/chrono/steady_clock

> Class std::chrono::steady_clock represents a monotonic clock. The time points of this clock cannot decrease as physical time moves forward. This clock is not related to wall clock time (for example, it can be time since last reboot), and is most suitable for measuring intervals.
> std::chrono::steady_clock meets the requirements of TrivialClock.
- 2

http://stackoverflow.com/questions/16177295/get-time-since-epoch-in-milliseconds-preferably-using-c11-chrono

> unsigned long milliseconds_since_epoch =
>     std::chrono::system_clock::now().time_since_epoch() / 
>     std::chrono::milliseconds(1);
> although, especially since you want platform independence, it might be better to replace unsigned long with a type that's more likely to be large enough:
> 
> (unsigned) long long
> std::(u)int64_t
> std::chrono::milliseconds::rep
> auto 
> 
> To me, this clearly states both that you're risking loss of precision (by analogy with integer division) and that you're leaving the safety of the type system (by dividing by a typed time to give a unitless number). However, as demonstrated in the comments, some people would say that any attempt to move away from type-safety should be accompanied by a deliberate attempt to make the code look dangerous. If you need to deal with people who hold that belief, it might be simpler to use duration_cast rather than enter into an argument about irrelevant stylistic choices:
> 
> unsigned long milliseconds_since_epoch = 
>     std::chrono::duration_caststd::chrono::milliseconds
>         (std::chrono::system_clock::now().time_since_epoch()).count();

**Comment by dumganhar** [comment]
I reviewed the source code of std::chrono of Mac platform.
It seems that `streay_clock` will not be defined if the macro `_LIBCPP_HAS_NO_MONOTONIC_CLOCK` is defined.
And `high_resolution_clock` is a typedef stuff to `steady_clock`.
Currently, we're using `std::chrono::high_resolution_clock` for calcurating the duration in performance test. So my question is `Is it better to use std::chrono::high_resolution_clock?`

std::chrono code snippet:

``` c++
//////////////////////////////////////////////////////////
/////////////////////// clocks ///////////////////////////
//////////////////////////////////////////////////////////

class _LIBCPP_TYPE_VIS system_clock
{
public:
    typedef microseconds                     duration;
    typedef duration::rep                    rep;
    typedef duration::period                 period;
    typedef chrono::time_point<system_clock> time_point;
    static _LIBCPP_CONSTEXPR_AFTER_CXX11 const bool is_steady = false;

    static time_point now() _NOEXCEPT;
    static time_t     to_time_t  (const time_point& __t) _NOEXCEPT;
    static time_point from_time_t(time_t __t) _NOEXCEPT;
};

#ifndef _LIBCPP_HAS_NO_MONOTONIC_CLOCK
class _LIBCPP_TYPE_VIS steady_clock
{
public:
    typedef nanoseconds                                   duration;
    typedef duration::rep                                 rep;
    typedef duration::period                              period;
    typedef chrono::time_point<steady_clock, duration>    time_point;
    static _LIBCPP_CONSTEXPR_AFTER_CXX11 const bool is_steady = true;

    static time_point now() _NOEXCEPT;
};

typedef steady_clock high_resolution_clock;
#else
typedef system_clock high_resolution_clock;
#endif

} // chrono
```

**Comment by dumganhar** [comment]
It seems that we should not use `high_resolution_clock`. Different stl library has different implementations. 
In the `gnu-libstdc++` on android, it's typedef as `system_clock` directly.
So let's keep using `std::chrono::steady_clock`.

@Guy-kun , is there any reason you use `time_since_epoch`?
Is it need in our engine? I think it's enough to just calculate the duration between tow timepoint.
Something like:

``` c++
        auto old = std::chrono::steady_clock::now();
        ......
        auto now = std::chrono::steady_clock::now();
        auto sec = std::chrono::duration_cast<std::chrono::microseconds>(now-old).count() / 1000000.0f;
       // sec is the `dt` used in cocos2d.
```

Do we need the exact time which starts from device bootup?
Is duration between two timepoint enough for delta time (dt) ?

**Comment by Guy-kun** [comment]
You're right, I don't think `time_since_epoch()` is needed, just a comparison of now() should be okay
