### ISSUE TITLE
WebSocket couldn't receive large data

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16045]
Reported at http://forum.cocos.com/t/pc-websocket/37859

**Comment by huangapple** [comment]
@dumganhar 
try comments  https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/WebSocket.cpp line598
// info.extensions = exts;

**Comment by DineshKachhot** [comment]
Working now, Thanks.....

**Comment by dumganhar** [comment]
So it seems a `permessage-deflate` related issue?
Does your websocket server support `permessage-deflate` and did you enable it?

**Comment by dumganhar** [comment]
Sorry, I could not reproduce this issue on iPhone6.
I used https://github.com/crossbario/autobahn-python to create a websocket server.
Is there some step to reproduce this issue?

**Comment by dumganhar** [comment]
@DineshKachhot , does this issue occur on all platforms? Did I miss something?

**Comment by dumganhar** [comment]
@DineshKachhot, @huangapple 
What kind of WebSocket server did you use?

**Comment by huangapple** [comment]
@dumganhar  socket-io  
"url": "git://github.com/Automattic/socket.io.git"

**Comment by dumganhar** [comment]
@huangapple , So did you use `cocos2d::network::SocketIO` class to connect to server? Or just use `WebSocket` class directly?

**Comment by huangapple** [comment]
@dumganhar  
use cocos2d::network::SocketIO

**Comment by dumganhar** [comment]
@huangapple,
With SocketIO, I still couldn't reproduce this problem.
Every thing works fine.
Could you send me a simple demo including both server & client source code?

**Comment by dumganhar** [comment]
Reported to the official libwebsockets: https://github.com/warmcat/libwebsockets/issues/593
Please disable `permessage-deflate` extension until the problem is resolved.

**Comment by dumganhar** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/16350.
But it seems that we have to upgrade libwebsockets library since `lws_set_extension_option` isn't supported in libwebsockets which cocos2d-x is using now.

**Comment by dumganhar** [comment]
UPDATED：#16350 didn't actually fix the issue. We re-opened this issue.
For a workaround, we commented `info.extension` line to disable `permessage-deflate` temporarily.

**Comment by yunmin97** [comment]
@dabingnn cocosdx-3.13版本的什么时候能在官网下载？？

**Comment by huangapple** [comment]
刚上了

**Comment by flyingkisser** [comment]
这个问题看样子在移动端一直无解啊
