### ISSUE TITLE
upgrade CURL to 7.50.0

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#16063]
CURL has a bug about connect to ipv4 numerical IP address in NAT64 environment, which caused cocos2d-x rejected by Apple: https://github.com/curl/curl/issues/863

**Comment by minggo** [comment]
iOS, Mac and Android upgraded in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/241

**Comment by stammen** [comment]
@minggo https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src has not been updated to curl version 7.50.0.

**Comment by minggo** [comment]
Sorry, i forgot to update the source repo. Could you please try again, i just updated it.

**Comment by minggo** [comment]
@stammen is https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src useful for you? It can not build Windows Phone architectutre.

**Comment by minggo** [comment]
windows 10 and 8.1 is updated in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/242

**Comment by stammen** [comment]
@minggo I will make a pull request to https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src with the updated build scripts for windows 10 and 8.1.

**Comment by minggo** [comment]
tahnks

**Comment by fuyifan** [comment]
@minggo The file curlbuild.h you sent in iOS include directory in cocos2d-x-3rd-party-libs-bin, can not be compiled. Pls fix it.

**Comment by minggo** [comment]
@fuyifan could you please use latest version? I think i fixed it.

**Comment by fuyifan** [comment]
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/v3/curl/include/ios/curl/curlbuild.h
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/v3/curl/include/android/curl/curlbuild.h
shows like this
#if defined(**LP64**) && **LP64**
#include "curlbuild-64.h"
#else
#include "curlbuild-32.h"

**Comment by minggo** [comment]
It is

``` c++
#if defined(__LP64__) && __LP64__
#include "curlbuild-64.h"
#else
#include "curlbuild-32.h"
```

Yep, is there any problem? The original version also use the same logical to include correct header file.

**Comment by fuyifan** [comment]
No #endif at the end of the file?

**Comment by minggo** [comment]
@fuyifan thanks, i fixed it.
