### ISSUE TITLE
[Cocos2d-x 3.12] Scene Transitions don't work correctly with a ListView child

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#16109]
Some (most) Transitions aren't rendered correctly in the 'from' `Scene` there is a `ListView`.

How to test the provided code:
1) Replace the two files in the 'HelloWorld' project (Classes folder).
2) Bulid and run
3) Click on the power button to generate a scene transition

The transition seems to work fine only if the clipping is disabled on the`ListView`.

[Test.zip](https://github.com/cocos2d/cocos2d-x/files/361007/Test.zip)

**Comment by alfogrillo** [comment]
Here a screenshot of the artifacts
![transition](https://cloud.githubusercontent.com/assets/19324622/16835832/d28b448a-49ba-11e6-87c4-e25cc8378c0c.png)

**Comment by ricardoquesada** [comment]
thanks. you mentioned that are you using v3.12... is this something that only fails in v3.12 and works in previous versions?

**Comment by alfogrillo** [comment]
Hi @ricardoquesada 
The issue is present also in v3.11.
If you are in charge of rendering stuff I suggest to take a look to another, I think serious, rendering issue: #15783
