### ISSUE TITLE
[3.12] cocos gen-libs (android) failed to generate ndk r10, r11, r12 

### ISSUE THREAD

**Issue by androidLaLa** [cocos2d/cocos2d-x#16103]
**Windows 10. and using NDK r12b.**

C:\MyFolder>set NDK_ROOT=D:\Tools\android\android-ndk-r12b

C:\MyFolder>cocos gen-libs -p android -m release
running: 'C:\MyFolder\Downloads\cocos2d-x-3.12\tools/cocos2d-console/bin\cocos.bat compile -s C:\MyFolder\Downloads\cocos2d-x-3.12\tools/simulator -p android --ndk-mode release --app-abi armeabi'

Building mode: debug
Using Eclipse project : C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android
Android platform not specified, searching a default one...
running: '"D:\Tools\android\android-sdk-windows\tools\android" update project -t android-16 -p C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android'

Updated project.properties
Updated local.properties
Updated file C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android\proguard-project.txt
Android platform not specified, searching a default one...
running: '"D:\Tools\android\android-sdk-windows\tools\android" update lib-project -p C:\MyFolder\Downloads\cocos2d-x-3.12\cocos\platform\android\java -t android-22'

Updated project.properties
Updated local.properties
Updated file C:\MyFolder\Downloads\cocos2d-x-3.12\cocos\platform\android\java\proguard-project.txt
Building native...
NDK build mode: release
running: '"D:\Tools\android\android-ndk-r12b\ndk-build" -C C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android -j4 APP_ABI="armeabi" NDK_MODULE_PATH=C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android../../../../../;C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android../../../../../cocos/;C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android../../../../../external;C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android../../../../../cocos/scripting NDK_TOOLCHAIN_VERSION=clang'

Android NDK: WARNING: APP_PLATFORM android-16 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml
Android NDK: WARNING: Unsupported source file extensions in C:\MyFolder\Downloads\cocos2d-x-3.12\tools\simulator\frameworks\runtime-src\proj.android../../../../../cocos//scripting/js-bindings/proj.android/Android.mk for module cocos2d_js_static
Android NDK:   \
make: Entering directory `C:/Users/LaLa/Downloads/cocos2d-x-3.12/tools/simulator/frameworks/runtime-src/proj.android'
[armeabi] Compile++ arm  : cocos2dlua_shared <= RuntimeJsImpl.cpp
[armeabi] Compile++ arm  :[armeabi] Compile++ arm  : cocos2d_lua_static <= lua_cocos2dx_network_manual.cpp cocos2d_lua_static <= lua_cocos2dx_cocosdenshion_manual.cpp

[armeabi] Compile++ arm  : cocos2d_lua_static <= Lua_web_socket.cpp
[armeabi] Compile++ arm  : cocos2d_lua_static <= lua_xml_http_request.cpp
[armeabi] Compile++ arm  : cocos2d_lua_static <= lua_cocos2dx_cocosbuilder_manual.cpp
[armeabi] Compile++ arm  : cocos2d_lua_static <= CCBProxy.cpp
jni/../../Classes/ide-support/RuntimeJsImpl.cpp:222:52: error: no viable conversion from 'unordered_map<[...],
      JS::PersistentRootedScript _>' to 'unordered_map<[...], JSScript *>'
        std::unordered_map<std::string, JSScript_> filenameScript = ScriptingCore::getInstance()->getFileScript();
                                                   ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/Tools/android/android-ndk-r12b/build//../sources/cxx-stl/gnu-libstdc++/4.9/include\bits/unordered_map.h:169:7: note: 
      candidate constructor not viable: no known conversion from 'std::unordered_map<std::string,
      JS::PersistentRootedScript *>' (aka 'unordered_map<basic_string<char>, PersistentRooted<JSScript *> _>') to 'const
      std::unordered_mapstd::basic_string<char, JSScript *, std::hash<string>, std::equal_tostd::basic_string<char
      >, std::allocator<std::pair<const std::basic_string<char>, JSScript *> > > &' for 1st argument
      unordered_map(const unordered_map&) = default;
      ^
D:/Tools/android/android-ndk-r12b/build//../sources/cxx-stl/gnu-libstdc++/4.9/include\bits/unordered_map.h:172:7: note: 
      candidate constructor not viable: no known conversion from 'std::unordered_map<std::string,
      JS::PersistentRootedScript *>' (aka 'unordered_map<basic_string<char>, PersistentRooted<JSScript *> *>') to
      'std::unordered_mapstd::basic_string<char, JSScript *, std::hash<string>, std::equal_tostd::basic_string<char
      >, std::allocator<std::pair<const std::basic_string<char>, JSScript *> > > &&' for 1st argument
      unordered_map(unordered_map&&) = default;
      ^
D:/Tools/android/android-ndk-r12b/build//../sources/cxx-stl/gnu-libstdc++/4.9/include\bits/unordered_map.h:214:7: note: 
      candidate constructor not viable: no known conversion from 'std::unordered_map<std::string,
      JS::PersistentRootedScript *>' (aka 'unordered_map<basic_string<char>, PersistentRooted<JSScript *> *>') to
      'initializer_list<value_type>' (aka 'initializer_list<std::pair<const std::basic_string<char>, JSScript *> >') for
      1st argument
      unordered_map(initializer_list<value_type> __l,
      ^
1 error generated.
make: *_\* [obj/local/armeabi/objs/cocos2dlua_shared/**/**/Classes/ide-support/RuntimeJsImpl.o] Error 1
make: **\* Waiting for unfinished jobs....
make: Leaving directory `C:/Users/LaLa/Downloads/cocos2d-x-3.12/tools/simulator/frameworks/runtime-src/proj.android'
Error running command, return code: 2.
Error running command, return code: 14.

**I also compile with r11c and r10e but error occured.**

**Comment by minggo** [comment]
duplicated with #16068, and it is fixed
