### ISSUE TITLE
Upgrade to Spine 3.4

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/cocos2d-x#16115]
http://esotericsoftware.com/blog/Spine-3-4-released

**Comment by gestern** [comment]
Great! I can not wait when cocos2d-x would be able to handle a mash in Spine. 💯

**Comment by Bilalmirza** [comment]
@ricardoquesada when you upgrade to v3.4. You might get a few crashes. Let me know if you do. I also have tests prepared for this since i upgraded to v3.4 myself.

**Comment by ricardoquesada** [comment]
@Bilalmirza thanks. I started the upgrade. Everything that you can share would be great.
So far I was able to test it on Mac without major problems. I just needed to update the .json files...  Apparently v3.4 requires to to re-export certain animations

**Comment by Bilalmirza** [comment]
yes... most of the animations require a re-export. I had a few problems earlier but it seems like spine has fixed those problems :)
cheers

**Comment by ricardoquesada** [comment]
fixed.

**Comment by badlogic** [comment]
Hi, Mario from Spine here. I wonder, would it be possible to include the official Spine runtime as Git submodules? That way we'd be in charge of keeping things in sync, and there'd be a single source of truth.

**Comment by ricardoquesada** [comment]
@badlogic yes, makes sense.
