### ISSUE TITLE
do research about how to make jenkins work together with Travis or other CI

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#16116]
Travis is good, but it doesn't support windows, that's why we use jenkins currently. But our genkins is not stable, the slaves are easy to be disconnected. We need to find a way to switch to use free CI step by step.

**Comment by minggo** [comment]
@stammen do you have any suggestion?

**Comment by zilongshanren** [comment]
I have one possible solution:

Setup a web service which does the following things:
1.  When a Github PR opened, call one hook of the web service,  it will trigger multiple CI 
2. Wait for the results of multiple CI and send the _merged_ results back to Github PR commit.
3. When click the status button of the PR, it will direct to the web page we maintained and show the merged build results here.

**Comment by zilongshanren** [comment]
I think we can't use travis CI or other CI as jenkins Slaves.(Am I wrong here?)

 If Jenkins slaves are not state, the cloud host could save us. But is need dollars..

**Comment by minggo** [comment]
> I think we can't use travis CI or other CI as jenkins Slaves.(Am I wrong here?)

Make jenkins work together with other CI doesn't mean make other CI as jenkins slave. And it is better if we can remove jenkins, just use one CI or multiple CI work together.

> If Jenkins slaves are not state, the cloud host could save us. But is need dollars..

Yep, money can resolve it. It is better if we can find free CI as cocos2d-x is open source.

**Comment by minggo** [comment]
> I have one possible solution:
> 
> Setup a web service which does the following things:
> 
> 1.When a Github PR opened, call one hook of the web service, it will trigger multiple CI
> 
> 2.Wait for the results of multiple CI and send the merged results back to Github PR commit.
> 
> 3.When click the status button of the PR, it will direct to the web page we maintained and show the merged build results here.

It sounds good.

**Comment by cezheng** [comment]
As far as I know, you can trigger multiple ci builds for one PR and show all of these build status in github: https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

![](https://cloud.githubusercontent.com/assets/483/5332863/0f58f9b6-7e1a-11e4-9884-e362ec566f2b.png)

So you can setup travis ci for iOS, macOS & Linux, while using another ci like [AppVeyor](https://www.appveyor.com/) to run windows builds. And there shall be no need to setup a web service for this.

**Comment by minggo** [comment]
@cezheng looks good, thanks

**Comment by minggo** [comment]
I am working on travis CI these days, and found it will exceed the time-limit when building our tests on all platforms except linux. And it will take about 42 minutes on linux. I build all tests (include `cpp-empty-test`, `cpp-tests`, `lua-empty-test`, `lua-tests` and `js-tests`). So we should optimize the compiling time.

**Comment by minggo** [comment]
It will take about 18 minutes to setup environments on Mac:
- download engine, deps
- set up environments to generate binding codes
- generate binding codes

On linux it is more quickly, and the linux job is started first(about 5 minutes first compared to Mac job).

Edit: it seems mac os performance is slower than linux os in travis.

**Comment by minggo** [comment]
From the [doc](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), we can find the Mac virtual machine is lower performance. It only has 3G memory and only one core. Linux virtual machine has 7.5G memory and 2 cores.

**Comment by minggo** [comment]
I added two jobs on Mac platform, only building `cpp-empty-test` and `cpp-tests` also met timeout issue: https://travis-ci.org/minggo/cocos2d-x/builds/156724132. So should make some modules into binary mode first, such as
- box2d
- bullet
- studio reader
- builder reader
- spine reader

**Comment by minggo** [comment]
I send #16494 for new travis script.

**Comment by minggo** [comment]
windows ci is added too: https://github.com/cocos2d/cocos2d-x/pull/18077
