### ISSUE TITLE
Cocos console on MAC getting error (again) :ValueError: unknown locale: UTF-8  

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#16138]
downloaded the latest version 3.12 
this used to be in some of the previous  versions   , 
i executed :  cocos new help
Got this error : 

```
meirs-Mac-mini:cocos2d-x-3.12 meiryanovich$ cocos new help
Traceback (most recent call last):
  File "/Users/meiryanovich/Documents/cocos2d-x/cocos2d-x-3.12/tools/cocos2d-console/bin/cocos.py", line 22, in <module>
    import cocos_project
  File "/Users/meiryanovich/Documents/cocos2d-x/cocos2d-x-3.12/tools/cocos2d-console/bin/cocos_project.py", line 4, in <module>
    import cocos
  File "/Users/meiryanovich/Documents/cocos2d-x/cocos2d-x-3.12/tools/cocos2d-console/bin/cocos.py", line 936, in <module>
    language, encoding = locale.getlocale()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

```

i was able  to fix this problem executing those commands in the shell :

```
meirs-Mac-mini:cocos2d-x-3.12 meiryanovich$ export LC_ALL=en_US.UTF-8
meirs-Mac-mini:cocos2d-x-3.12 meiryanovich$ export LANG=en_US.UTF-8
```

can it be combined in the setup.py or something ? 
Thanks

**Comment by minggo** [comment]
@natural-law could you please take a look?

**Comment by natural-law** [comment]
@meiry @minggo I don't think it should be added in `setup.py`. Because maybe it will be conflict with existing environment settings on user's machine.

But I think we can add the solution into FAQ or Documents. Then once user encountered the problem, they can find the solution.

@meiry After all, thanks for your feedback!

**Comment by meiry** [comment]
@minggo @natural-law  
The realty ( my also ) is that i don't always go to search in FAQ or documents .
And i saw more then 4-5 users complain in the forums . 
for new user it can be pain . it is basic . 
What is the cause of this problem ? in previous versions it worked out of the box . 
Also you can check with simple if/then  if the LANG or LC_ALL are already set .

**Comment by natural-law** [comment]
On my machine, the value of LANG & LC_ALL like this:

```
Bill:~ cocos2d-x$ echo $LC_ALL

Bill:~ cocos2d-x$ echo $LANG
zh_CN.UTF-8
```

It works well with the latest code of v3 branch.

And I found this in python issue system : https://bugs.python.org/issue18378
Maybe the problem only occurred on machines with special language or terminal settings. I'm sorry that I've no idea what's the right way to solve it.

**Comment by meiry** [comment]
looks like python + MAC problem . 
try to catch the exception in python and print to STD out the suggested solution

**Comment by minggo** [comment]
@meiry can i close the issue since it is not a cocos2-x issue?

**Comment by natural-law** [comment]
@minggo I've just checked the logic, I think it's necessary that catch the exception to solve the crash problem. I will do it later.
@meiry Thanks for your suggestion!

**Comment by meiry** [comment]
Sure , happy to help

**Comment by fd5788** [comment]
just，export LC_CTYPE=en_US.UTF-8
