### ISSUE TITLE
FPS disappeared

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#16139]
steps to reproduce it:
- run `cpp-empty-test` for Mac target
- then you will find the FPS is disappeared

I think all platforms has the issue.  @ricardoquesada could you please take a look. Thanks.

**Comment by ricardoquesada** [comment]
fixed.

**Comment by minggo** [comment]
@ricardoquesada android still has the issue, and iOS is ok. So i reopen this issue.

**Comment by ricardoquesada** [comment]
f@ck! :-( thanks.

**Comment by ricardoquesada** [comment]
well, I guess I fixed this for real.

Besides this bug, the thing is that our GLView setup code is super fragile.
Desktops are using GLFW, iOS its own code, Android its own code, Windows its own code...
We need to unify them.
Our code is error-prone, difficult to make changes without breaking other stuff.

Tested on Mac, iOS and Android.

**Comment by minggo** [comment]
yep, it is better if GLFW can support all these platforms.

**Comment by minggo** [comment]
And i add `use GLFW on all platforms` in v4 plan.
