### ISSUE TITLE
AudioEngine 在android上播放循环音效不能完美循环播放，连接处有断裂

### ISSUE THREAD

**Issue by yunmin97** [cocos2d/cocos2d-x#16144]
cocos2dx版本：v3.12版本
运行平台：android（sdk 4.x和N都试过）
问题：audioEngine在android上播放循环音效无法完美循环，音效播放结束重新回到到音头时，中间出现卡顿（空白），之前ios上播放mp3时也无法循环，后来我们发现是音频本身的问题，修改过后能够循环了（最后使用.m4a格式的音频），但是andriod上我们使用过.ogg、.flac、.m4a、.mp3的都无法循环播放（音频确定已经去掉压缩的头，用audition能循环起来），最后我们找来很多类型android机，发现部分机型能循环，有的又不能循环（三星G6 Edge就无法循环，但G Note Edge又能循环）！有木有人遇到这个问题？

**Comment by liuyi** [comment]
循环有特殊的处理方法：
不要设置循环，而是自己处理循环。当声音快要播放完成的时候，将声音的播放进度重置到开始 就可以完美循环了。

**Comment by dumganhar** [comment]
@duuyia, @iuyi 
谢谢反馈，请问循环播放音效有100ms的延时，具体是怎么测试出来的（使用什么工具？）？

Android上的声音播放以及重构了一次，支持preload，提高了效率和稳定性。

https://github.com/cocos2d/cocos2d-x/pull/15875

是否可以同步下这个PR中的修改并且再次测试？

或者提供给我一个重现问题的demo，我分析一下原因。非常感谢。

**Comment by liuyi** [comment]
@dumganhar  我遇到这个问题的时候 是听出来的。。。

**Comment by dumganhar** [comment]
@liuyi , 耳力真是好。 👍

**Comment by yunmin97** [comment]
@dumganhar 
我上传了一个Demo，ios完美循环但android无法完美循环的工程
地址： http://git.oschina.net/duuyia/AudioLoopTest_Cocos2dx

**Comment by yunmin97** [comment]
@liuyi 
请问怎么知道音频即将播放完毕？？AudioEngine里面有个getCurrentTime的函数，但那也得另外再每帧监听所有循环的音频当前播放的进度和音频总时间做对比（这样开销有点大，感觉不怎么合理），程序要把所有循环的音频的时间播放长度都记录下来（因为貌似AudioEngine还无法获取到音频的长度）..我是这么理解的，不知道阁下有什么高招<___>，请指教？？

**Comment by dumganhar** [comment]
@duuyia , 谢谢，我稍后测试一下你的demo。
目前没有音频即将播放完毕的接口，即将如何定位呢？
有已经播放结束的接口：AudioEngine::setFinishCallback

**Comment by dumganhar** [comment]
@duuyia ,请问你的demo如何测试？
Android上有bug的表现情况是怎么样的？期望是如何的？

**Comment by yunmin97** [comment]
@dumganhar 
编译项目安装到android或者ios上面
ios完美循环，但是android不行！win32就不用测了
打开后是cocos2dx的hello原封不动的界面，界面上我加了有四个按钮
左边两个分别是播放两个音频的开关，右边是分别关闭左边对应音频的开关

**Comment by yunmin97** [comment]
@dumganhar 
bug的表现在android上就能感觉到，对比ios的或者直接用audition等音频播放器播放的效果完全不一样！
android播放快结束跳转到音频开始处时能明显听到断隙！

**Comment by dumganhar** [comment]
@duuyia , 谢谢。我马上验证一下。

**Comment by yunmin97** [comment]
@dumganhar 
好的，谢谢

**Comment by dumganhar** [comment]
@duuyia , 貌似Android的直接播放filePath的OpenSLES实现有问题。
最新v3分支已经支持在android上的preload逻辑了，经过测试，无此问题。
但是请注意AudioPlayerProvider.cpp中的

``` c++
static AudioFileIndicator __audioFileIndicator[] = {
        {"default", 128000}, // If we could not handle the audio format, return default value, the position should be first.
        {".wav",    1024000},
        {".ogg",    128000},  // 只针对小于128K的文件，使用新的方式(PcmAudioPlayer)播放
        {".mp3",    160000}
};
```

字段需要改大点，否则还会使用旧的方式（UrlAudioPlayer, 不支持preload）播放音频。

Android的音频实现实在是问题太多了。。。

**Comment by yunmin97** [comment]
好的，谢谢，明天我按照你说的方式再测测，有没问题我都给你个回复。
Cocos2dx我要重新下载最新的吗？我直接是从官网下载的，没有从github这里下载！

**Comment by dumganhar** [comment]
最新的改动还没有正式发布，需要用git同步一份代码来测试。
对应的改动在这个Pull Request中：#15875

**Comment by yunmin97** [comment]
@dumganhar 
好的，我git下来测测，稍后反馈

**Comment by yunmin97** [comment]
@dumganhar 
给力，下了几个循环音乐已经完美循环了，谢谢

**Comment by dumganhar** [comment]
@duuyia, 太好了。但是目前这个特性只有在4.1及以上的设备上才支持。
如果是2.3的机器，还是会继续使用原来的方式播放而导致循环的时候卡顿。这属于系统的问题了。
而且2.3的设备已经非常少了，基本能够忽略不计. :)

**Comment by yunmin97** [comment]
@dumganhar 
16年没人会用4.1一下系统玩游戏了：)

**Comment by yunmin97** [comment]
@dumganhar 
目前遇到的问题就是，项目之前用v3.8.1开发的，现在移植新版本后各种错误，特别是关于shader和tmx部分，新版本改动有点大，像tmx有的接口直接被删除了！
最后我想干脆就直接把最新版本的audio模块移植到v3.8.1里头，新版的audio模块有移植到v3.8.1版本的可能性吗？

**Comment by dumganhar** [comment]
可以的，新的audio实现是非常独立的一个模块，移植到3.8.1的步骤为：
- 拷贝新版本的cocos/audio/android替换到3.8.1对应的目录
- 参考新版本中cocos/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxHelper.h/.cpp, 新版本添加了两个新函数( getDeviceSampleRate, getDeviceAudioBufferSizeInFrames )
- 参考新版本中cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxHelper.java的修改，主要在init函数中
- 注释掉cocos/audio/android/AudioEngine-inl.cpp中fdGetter函数中关于getObbFile的分支

**Comment by dumganhar** [comment]
@duuyia, 那请关闭这个issue吧，谢谢。

**Comment by yunmin97** [comment]
@dumganhar OK
