### ISSUE TITLE
Sprite3D can't release its texture

### ISSUE THREAD

**Issue by sdspageprotein** [cocos2d/cocos2d-x#16155]
Create a sprite3d object, and then add it to one layer. After a while remove it from parent, then the texture it refred can't be released after calling the function removeUnusedTextures!
This is a very serious issue, because it can consume much memory when there are many 3d sprites on one scene.
The version of engine we are using is 3.8.1

**Comment by minggo** [comment]
`removeUnusedTextures` just remove textures that the reference count is 1. Please make sure it is not used other places.

**Comment by sdspageprotein** [comment]
This is definitely a bug, I test many times by only adding one Sprite3D object on one scene.

**Comment by minggo** [comment]
@sdspageprotein could you paste some code snipper to show how you use it?

**Comment by sdspageprotein** [comment]
This is one simple example:

```
local sp = cc.Sprite3D:create("plane3D/A-5.c3b")
self._core:addChild(sp)

self._core:runAction( cc.Sequence:create(
    cc.DelayTime:create(1),
    cc.CallFunc:create(function (  )
        sp:removeFromParent()
        cc.Director:getInstance():getTextureCache():removeUnusedTextures()
    end),
    cc.CallFunc:create(function (  )
        print(cc.Director:getInstance():getTextureCache():getCachedTextureInfo())
    end) ) )
```

And we may find the reason of this issue.
We change RenderState's finalization from:
RenderState::~RenderState()
{
    CC_SAFE_RELEASE(_state);
}
to 
RenderState::~RenderState()
{
    CC_SAFE_RELEASE(_texture);
    CC_SAFE_RELEASE(_state);
}

And then Sprite3D works fine. I do not know will this change cause some other issues.

**Comment by dumganhar** [comment]
@minggo , for a glance, I think @sdspageprotein 's change is reasonable, if _texture isn't released, it may cause memory leak.

**Comment by cwq** [comment]
can test in Sprite3DBasicTest

```
addChild( sprite );
removeChild(sprite);
```

the reference count of texture is 2, because RenderState did not release _texture

**Comment by minggo** [comment]
@cwq i think you are right. @ricardoquesada could you please take a look? `_texture` is retained in `RenderState::setTexture()` but it is not released.

**Comment by ricardoquesada** [comment]
fixed. thanks.
