### ISSUE TITLE
Uikt using cocos2dx 3.11, how to do?

### ISSUE THREAD

**Issue by ChillLight** [cocos2d/cocos2d-x#16179]
Recently needed to implement a 3D model display in IOS originally project, using the OpenGL and scenekit found some 3D model format does not support to show, so cocos2dx to achieve and now want to do them a binding but did not check the integrity of data and hope someone can give me the help, help!

**Comment by Shulepov** [comment]
Currently cocos2d-x is embedded in RootViewController (though also lifecycle events is propagated from AppController). So you can just add this RootViewController as child view controller whenever you want. But don't forget to adjust CCEAGLView size if necessary, currently it configured to fill the whole screen.

Anyway, look at RootViewController - it contains all you need to use cocos2d-x from anywhere.
