### ISSUE TITLE
sdkbox imports should be implemented at Cocos2dxActivity

### ISSUE THREAD

**Issue by AlexanderBykin** [cocos2d/cocos2d-x#16197]
I'm tired to modify Activity sdkbox to use it, so i want to do ease usage of it by adding simple flag of enable.

i will provide PR.

**Comment by minggo** [comment]
@AlexanderShniperson i don't quite understand what's your need, could you please paste some codes to explain it?

**Comment by AlexanderBykin** [comment]
@minggo sure i will provide Java class that initialize SDKBOX from Cocos2dxActivity

**Comment by AlexanderShniperson** [comment]
#16203
