### ISSUE TITLE
cocs2d-x v. [3.12] - 

### ISSUE THREAD

**Issue by rahb3rt** [cocos2d/cocos2d-x#16198]
cocos2d/external/json/document.h

When using an unsigned long variable for buffer size and using the NetworkWrapper function sendData() and recieveData() the crash occurs on recieving and interpreting the buffer. 

Assertion failed: (IsNumber()), function GetDouble, file ~/cocos2d/external/json/document.h, line 1402.

Possible problem that interpreter does not handle unsigned long

**Comment by Rubonnek** [comment]
Have you tried updating the rapidjson library directly from the master tree to see if that fixes the issue? 

You can just copy the contents form: https://github.com/miloyip/rapidjson/tree/master/include/rapidjson
and drop them into that json folder.

**Comment by rahb3rt** [comment]
I will give that a go and post back.

**Comment by minggo** [comment]
does it mean we should update rapidjson?
