### ISSUE TITLE
Crash while decoding small MP3 file on Android

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16192]
Reported by @ryanxia2016

> When call playEffect with same SMALL mp3 files, game crashed.
> Crash Device : ASUS ZENPHONE2 (Android 5.0 x86)
> 
> COCOS Version 3.3 with this PR merged.
> 
> The game worked right at most time, but if it hits the specified mp3 files, then crash occur.
> 
> attachment is the mp3 file, which will cause crash.
> [crash_voice.mp3.zip](https://github.com/cocos2d/cocos2d-x/files/377483/crash_voice.mp3.zip)

**Comment by ryanxia2016** [comment]
If need more error Info or Device Test, let me know. :-)

**Comment by ryanxia2016** [comment]
Another problem found.
At android 2.3.6, Game Running OK, but after several minutes, all sound effects disappear(background music is playing and game is still working). 

BTW:

I had modified cddandroidAndroidJavaEngine to use AudioEngine on all Android Versions(Comment out the if (sdk_ver == 21) statement)

and add new preload and unload Method as:

void AndroidJavaEngine::preloadEffect(const char\* filePath)
{
    **if (_implementBaseOnAudioEngine)
    {
        AudioEngine::preload(filePath, nullptr);
    }**
    else
    {
        std::string fullPath = CocosDenshion::android::getFullPathWithoutAssetsPrefix(filePath);
        JniHelper::callStaticVoidMethod(helperClassName, "preloadEffect", fullPath);
    }
}

void AndroidJavaEngine::unloadEffect(const char\* filePath)
{
    **if (_implementBaseOnAudioEngine)
    {
        AudioEngine::uncache(filePath);
    }
    else**
    {
        std::string fullPath = CocosDenshion::android::getFullPathWithoutAssetsPrefix(filePath);
        JniHelper::callStaticVoidMethod(helperClassName, "unloadEffect", fullPath);
    }
}

**Comment by ryanxia2016** [comment]
@dumganhar 
Is there anything found?

**Comment by dumganhar** [comment]
No yet,  i'm busy handling https://github.com/cocos2d/cocos2d-x/issues/16169, I'll check this problem right after issue #16169 is resolved.

**Comment by dumganhar** [comment]
@ryanxia2016, it was fixed at https://github.com/cocos2d/cocos2d-x/pull/16226.

**Comment by ryanxia2016** [comment]
@dumganhar 
Thanks a lot!
