### ISSUE TITLE
iconv uses the LGPL License (conflicts with the MIT License)

### ISSUE THREAD

**Issue by jasonchin** [cocos2d/cocos2d-x#16225]
Specifically CCFontAtlas uses the iconv library, which is under the LGPL License:
https://www.gnu.org/software/libiconv/

This conflicts with the MIT License, as well as meaning it shouldn't be publishable on an Appstore etc.

Seems like iconv needs to be replaced?

**Comment by nsnsns** [comment]
No - it is not in conflict.
With lgpl a compiled component can be linked as a library and you don't
need to give source code of all software unless you have significantly
changed compiled component

**Comment by jasonchin** [comment]
From the cocos2dx coding style page:
http://www.cocos2d-x.org/wiki/Cocos2d-x_Coding_Style_C++

> The license must be compatible for the different App Stores, so GPL and LGPL code cannot be used in cocos2d-x.

Another similar problem which was resolved:
http://www.cocos2d-x.org/issues/4782

The LGPL license is a grey area with iOS in particular, but it seems like the general consensus seems that  it shouldn't be used? It also requires to make object files of your app to be accessible to the public.

**Comment by minggo** [comment]
@jasonchin i don't remember cocos2d-x uses icon on iOS, could you please point out the url? Thanks.

**Comment by jasonchin** [comment]
@minggo 

> cocos2d-x uses icon on iOS

Sorry, not sure what you mean. Is it some reference image?

**Comment by minggo** [comment]
Sorry, i mean iconv.

**Comment by jasonchin** [comment]
@minggo ah sorry, yes of course.
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCLabelAtlas.cpp

**Comment by minggo** [comment]
Sorry, does CCLabelAtlas.cpp uses iconv?

**Comment by jasonchin** [comment]
@minggo I'm an idiot sorry, wrong file
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCFontAtlas.cpp

**Comment by ricardoquesada** [comment]
@jasonchin as far as I know, we are using the built-in iconv library that is part of iOS. So, this shouldn't be an issue.

If so, we can safely close this issue.

**Comment by jasonchin** [comment]
@ricardoquesada Ahh, so this means Apple has some unwritten free license agreement I guess? Yeah if so then apologies, feel free to close.

**Comment by ricardoquesada** [comment]
ok. closing it. Apple can use iconv as a dynamic library I guess. No need for an unwritten free license.

**Comment by mrexodia** [comment]
I think this issue should be reopened. The Apple headers say iconv is a LGPL library and since the functionality provided by iconv is super narrow (UTF-32 -> GB2312) it would be easy to replace.

This project can be used (it has the right license): https://github.com/lyaohe/UTF-8toGB2312/blob/master/UTF-8toGB2312.c. I volunteer to provide a clean reimplementation in modern C++ if you accept it.

Weirdly enough iconv (called `icon`) is also part of the external dependencies for Windows, not entirely sure why that is...
