### ISSUE TITLE
CocosBuilder Issue: Scale Property gives an error while compilation

### ISSUE THREAD

**Issue by CodeSnooker** [cocos2d/cocos2d-x#1622]
If you try to scale any sprite from CocosBuilder and try to read it via Cocos2D-X then it gives compile time error.

``` Objective-C
Assertion failed: (m_fScaleX == m_fScaleY), function getScale
```

For example,
1. Create a CCNode in CocosBuilder and add the sprite.
2. ScaleX the sprite in CocosBuilder (remember the value of ScaleX and ScaleY for sprite should be different).
3. Try to read the CCB file via Cocos2D-X, you will find the error.

**Comment by CodeSnooker** [comment]
The issue can be easily solved by modifying the following lines in CCBReader.cpp in the method 

``` javascript
CCNode * CCBReader::readNodeGraph(CCNode * pParent) {
```

``` javascript
embeddedNode->setScaleX(ccbFileNode->getScaleX());  // Newly added line
embeddedNode->setScaleY(ccbFileNode->getScaleY());  // Newly added line
//embeddedNode->setScale(ccbFileNode->getScale());     // Line commented to avoid crash.
```

**Comment by kohashi** [comment]
excuse me, it seems no resolve commit.
i think, you dumganhar have wrote a wrong issue number.

**Comment by dumganhar** [comment]
Oh, sorry for that. The issue id of `fixed #1622` means that on the redmine. http://www.cocos2d-x.org/projects/cocos2d-x/issues

**Comment by dumganhar** [comment]
http://www.cocos2d-x.org/issues/2040 was created. Thanks.

**Comment by dumganhar** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/2368. Thanks.
