### ISSUE TITLE
GLProgram::link() check result only debug or WinRT

### ISSUE THREAD

**Issue by perminovVS** [cocos2d/cocos2d-x#16231]
Why GLProgram::link correct check status result only DEBUG build or CC_TARGET_PLATFORM == CC_PLATFORM_WINRT ?

``` c++
bool GLProgram::link()
{
    CCASSERT(_program != 0, "Cannot link invalid program");

    GLint status = GL_TRUE;

    bindPredefinedVertexAttribs();

    glLinkProgram(_program);

    parseVertexAttribs();
    parseUniforms();

    clearShader();

//// Why this condition ?
#if DEBUG || (CC_TARGET_PLATFORM == CC_PLATFORM_WINRT)
    glGetProgramiv(_program, GL_LINK_STATUS, &status);

    if (status == GL_FALSE)
    {
        CCLOG("cocos2d: ERROR: Failed to link program: %i", _program);
        GL::deleteProgram(_program);
        _program = 0;
    }
#endif

    return (status == GL_TRUE);
}
```

Faced with the problem of the players, as it turned out the program will not be linked.
Compiling and linking your programs tested, but Results linking was not true, I spent a lot of time did not find this error.
If you check the linking properly, you can display a message to the player, with a description of the error.

**Comment by ricardoquesada** [comment]
My guess is that it was added only on debug for performance reasons, but I think that is legacy code. `glGetProgramiv()` shouldn't be an issue.
And it should be added in release mode as well since some users might download shaders on hot-updates, or via DLC.

**Comment by ricardoquesada** [comment]
thanks. merged your PR.
