### ISSUE TITLE
Accelerometer values flipped on Kindle Fire HD

### ISSUE THREAD

**Issue by pyrosphere** [cocos2d/cocos2d-x#1623]
On the Kindle Fire HD (and possibly on other devices) the values of the accelerometer values are flipped. I believe this is because the default rotation on landscape is Surface.ROTATION_270 instead of the usual Surface.ROTATION_90. I don't own any of these devices so I can't provide a fix, but it might be possible to use the device rotation instead of the orientation configuration to swap around the values of x/y on onSensorChanged.

**Comment by minggo** [comment]
Any idea to use device rotation?

**Comment by pyrosphere** [comment]
I haven't tested this properly but it might be possible to deal with this by getting the rotation instead of mNaturalOrientation:

``` java
final Display display = ((WindowManager) this.mContext.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();
this.mRotation = display.getRotation();
```

and then in onSensorChanged invert and flip the axis as needed:

``` java
switch (mRotation) { 
    case Surface.ROTATION_0:
    break;

    case Surface.ROTATION_90:
    break;

    case Surface.ROTATION_180:
    break;

    case Surface.ROTATION_270:
    break;
}
```
