### ISSUE TITLE
Tilemap Bug

### ISSUE THREAD

**Issue by MinhHTML5** [cocos2d/cocos2d-x#16289]
- cocos2d-x version: 3.12
- devices test on: Browser
- developing environments
  - NDK version: 10e
  - Xcode version:
  - VS version:
  - brower type and version: Chrome newest

Steps to Reproduce:
1. Load a tmx tilemap, and tileset texture file.
2. Error at: CCTMXLayer.js, line 115.
3. How to fix: at line 117, change "tex" to "texID".

**Comment by pandamicro** [comment]
Thanks for reporting, this is fixed in v3.13
