### ISSUE TITLE
Inefficient batch capacity resizing

### ISSUE THREAD

**Issue by Almax27** [cocos2d/cocos2d-x#16293]
cocos2d-x version: 3.12
### Steps to Reproduce:
1. Create a label with string of 90 characters
2. Observe SpriteBatchNode increasing it's capacity 4 times. Each time memory is reseated, indices reinitialised and the GL buffers remapped.  
   29 -> 40  
   40 -> 54  
   54 -> 73  
   73 -> 98  
### Proposed solution:

Follow behaviour of std::vector:
When assigned initial content it's capacity will equal it's size. When new content is subsequently added std::vector doubles it's existing capacity. If new content would exceed the doubled capacity, match capacity exactly to fit.
e.g.

```
std::vector<int> vec = {1,2,3}; 
//initial: vec.capacity() == 3

vec.push_back(4); 
//double: vec.capacity() == 6

vec.insert(vec.end(), {5,6,7,8,9,10,11,12,13});
//double capacity would be 12, but as new content exceeds this we use content size instead
//content: vec.capacity() == 13
```

Furthermore we should expose ability to manually set capacity to allow developers to 'warm' labels they expect to be displaying large amounts of content in the future.
### References:

[Origin forum thread](http://discuss.cocos2d-x.org/t/cocos2d-x-version-3-xx-is-resize-textureatlast-capacity-a-problem/16408/9)

**Comment by ricardoquesada** [comment]
SpriteBatchNode is rather conservative when increasing the buffer size. It just does a 4/3 of the previous size.
But the bug is that it should allocate the needed size if we already know it. If a label contains 90 chars, then it should do the resizing just once, not four times.

**Comment by ricardoquesada** [comment]
fixed.
