### ISSUE TITLE
Test cases Bug15776Layer Crash

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#16302]
- cocos2d-x version: 3.13
- devices test on: Mac

Steps to Reproduce:
1. compile and run cpp-tests
2. select "Bugs -> Bug15776Layer"

@minggo 

![image](https://cloud.githubusercontent.com/assets/785541/17359084/a6571230-5997-11e6-9930-c56250ed8e0c.png)

The code snippet:

``` cpp
bool Bug15776Layer::init()
{
    if (BugsTestBase::init())
    {
        cocos2d::Image *cocos2dxImage = new cocos2d::Image();
        cocos2dxImage->initWithImageData(nullptr, 0);
        // should not crash. invalid cocos2dImage
        auto texture2d = Director::getInstance()->getTextureCache()->addImage(cocos2dxImage, "unused");
        return texture2d;
    }

    return false;
}
```

**Comment by minggo** [comment]
it is designed as it is, please refer to #15880
