### ISSUE TITLE
Use VSCode to debug cocos2d-x jsb with cocos2d-x 3.12 version, got timeout

### ISSUE THREAD

**Issue by ttdjong** [cocos2d/cocos2d-x#16304]
- cocos2d-x version: 3.12
- devices test on: win7
- developing environments
  - VS version: 2013, debug model

Steps to Reproduce:
1. Download the cocos2d-x 3.12 from [Cocos2d-x site](http://www.cocos.com/download/cocos2d-x/)
2. Execute the setup.py.
3. Open the cocos2d-win32.sln solution and run the js-test project.
4. Open the js-test folder with VSCode and debug the project.
5. The VSCode console will show "retry socket.connet" until timeout.
6. I test the cocos2d-x version 3.11.1, it don't have this problem.
[Here is screenshot](http://discuss.cocos2d-x.org/t/use-vscode-to-debug-cocos2d-x-jsb-programs/27588/81?u=djong)

**Comment by minggo** [comment]
Will you please replace `localhost` to `::1` to have a test. As i know, Windows 7 uses IPV6 format address. But i am curious why 3.11.1 doesn't have issue.

**Comment by ttdjong** [comment]
I test the 3.12 with `::1`, yes, it runs well. Sorry for my poor knowledge and Thank you for your patience guidance.

**Comment by minggo** [comment]
@djwind it is ok. I will update the plugin to try `::1` when `localhost` can not work.

**Comment by minggo** [comment]
Can i close the issue?

**Comment by ttdjong** [comment]
Ok, i close it.
