### ISSUE TITLE
Cameras don't work anymore.

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#16322]
I pulled the latest cocos2dx from github(v3.13).

I'm not sure what the problem is. Either the all cameras stopped working or the function
sprite->setCameraMask()  doesnt do anything anymore.

here is my game running on v3.12
https://www.dropbox.com/s/f5c21h05uhc53b4/forMusic.mp4?dl=0

running on v3.13
https://www.dropbox.com/s/8nglvua4mxrhl1x/cameraBug.mov?dl=0

cameras dont seem to follow the player any more... same with the backgrounds.
This has the same effect when i remove all the cameras.

I know i should only use the released version. But i had to do some tests for @dumganhar on android phones

if you need more tests please let me know.

Thanks

**Comment by minggo** [comment]
I think it is related to #13203.

**Comment by UKDeveloper99** [comment]
Unrelated but @Bilalmirza have you got an e-mail I can contact you on?

**Comment by Bilalmirza** [comment]
@UKDeveloper99 
Bilalmirza@msn.com

skype: bilalmirza13

**Comment by Bilalmirza** [comment]
i actually think its related to #13203 
when you set camera mask of its parent what happens is eventually when it reaches the first parent which doesn't have a camera mask or it is default, and in my case there is not camera set to default. which may be causing the problem.
