### ISSUE TITLE
There is no OpenGL ES extensions called GL_IMG_texture_format_BGRA8888

### ISSUE THREAD

**Issue by id-0x76adf1** [cocos2d/cocos2d-x#16336]
There are extensions GL_EXT_texture_format_BGRA8888 and GL_APPLE_texture_format_BGRA8888.

**Comment by id-0x76adf1** [comment]
_supportsBGRA8888 = checkForGLExtension("GL_IMG_texture_format_BGRA888");
_supportsBGRA8888 is always false

**Comment by ricardoquesada** [comment]
@identifer well, yes, actually we have a typo:

It checks for: `GL_IMG_texture_format_BGRA888`... only three 8s.. and it should have four 8s. eg: `GL_IMG_texture_format_BGRA8888`

Searching on google it seems that it does exist... at least with four 8s.

**Comment by ricardoquesada** [comment]
fixed.
