### ISSUE TITLE
Started getting strange error on upgrade to cocos2d-x 3.10 from 3.8

### ISSUE THREAD

**Issue by vpadmnabh** [cocos2d/cocos2d-x#16349]
- cocos2d-x version: 3.10
- devices test on: iPad
- developing environments
  - NDK version:
  - Xcode version: 7.3.1
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. Upgrade project created from cocos2d-x 3.8 to cocos2d-x 3.10
2. Started getting strange warning on compile and crash on cocos2d::CSLoader::createNode

Following for warnings
1)  Direct access in cocos2d::CSLoader::createNodeWithFlatBuffersFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (cocos2d::Ref*)> const&) to global weak symbol typeinfo for cocostudio::WidgetCallBackHandlerProtocol means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

2)  Direct access in cocos2d::CSLoader::createNode(cocos2d::Data, std::__1::function<void (cocos2d::Ref*)> const&) to global weak symbol typeinfo for cocostudio::WidgetCallBackHandlerProtocol means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

3) Direct access in cocos2d::CSLoader::nodeWithFlatBuffers(flatbuffers::NodeTree const_, std::__1::function<void (cocos2d::Ref_)> const&) to global weak symbol typeinfo for cocostudio::WidgetCallBackHandlerProtocol means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

4) Direct access in cocos2d::CSLoader::bindCallback(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cocos2d::ui::Widget_, cocos2d::Node_) to global weak symbol typeinfo for cocostudio::WidgetCallBackHandlerProtocol means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

Crash comes after repeatedly using createNode(FIlePath)

**Comment by minggo** [comment]
close it since cocos studio is canceled, but you are appreciated if you can send PR to fix it
