### ISSUE TITLE
in JS project, import SDKBOX share do not set Appdelegate.cpp and Classes folder

### ISSUE THREAD

**Issue by jphutter** [cocos2d/cocos2d-x#16364]
- cocos2d-x version: cocos2d-x-3.12 Jul 06 2016
- devices test on: Xcode simulator set as iPhone 6S Plus
- developing environments
  - NDK version: --
  - Xcode version: 7.3.1 El Capitan
  - VS version: --
  - brower type and version: --

Steps to Reproduce:
1. cocos new MyGame -l js -d Path
2. sdkbox import share
3. missing PluginShareJS(Helper) in Appdelegate.cpp and PluginShareJS\* in Classes
4. sdkbox import facebook
5. all normal

**Comment by minggo** [comment]
@jphutter you should report it to SDKBOX guys.
