### ISSUE TITLE
The latest Label calculate Size seems not correct with some .ttf font

### ISSUE THREAD

**Issue by halx99** [cocos2d/cocos2d-x#16399]
- cocos2d-x version: github latest
- devices test on: Windows  10 14393.82 win32 program
- developing environments
  - NDK version:
  - Xcode version:
  - VS version: 2013 or 2015
  - brower type and version:

Steps to Reproduce:
1. Use latest cocosstudio to edit a demo UI with Label
2. publish to .csb and load it, then the postion not correct because the contetSize of Label not be calculated correct.
3. test cocosstudio project: http://halx99.oschina.io/releases/LabelBugTest.zip

CocosStudio Effect:
![cocosstudioeffect](https://cloud.githubusercontent.com/assets/6977319/17798009/4a9498e4-6600-11e6-8b84-fb51b9055166.png)

The latest Label render effect:
![gameeffect](https://cloud.githubusercontent.com/assets/6977319/17798017/5ee0e51e-6600-11e6-99aa-278b4b4ac631.png)

**Comment by halx99** [comment]
@minggo please take a look, does this is a bug?

**Comment by minggo** [comment]
@halx99 sorry, cocos studio is canceled, we don't have resource to support it.

**Comment by halx99** [comment]
@minggo Well, I think it's not cocosstudio problem, you also can reproduce this issue draw the border of the label, the render text will surpass right edge.

**Comment by minggo** [comment]
@halx99 could you please provide a test case? Thanks.

**Comment by halx99** [comment]
ok, I will.

**Comment by halx99** [comment]
@minggo The test case: https://github.com/halx99/cocos2d-x/tree/labelsizebugtest

My test result:
![a _mrg6co5oa tkv 2n89 w](https://cloud.githubusercontent.com/assets/6977319/17798940/b8586f06-6608-11e6-940b-a6b435bd1589.png)

**Comment by minggo** [comment]
@halx99 i can not find the error from your pasted image. What does the red rectangle mean?

**Comment by halx99** [comment]
@minggo The red rectangle is border of the label, normally all letters shoud at inner of the rectangle, you can see the last letter is surpassed a little.

**Comment by minggo** [comment]
Yep.

**Comment by dumganhar** [comment]
@halx99, I tested your demo and I could reproduced it.

@newnon has submitted a Pull Request https://github.com/cocos2d/cocos2d-x/pull/16689

After I applied @newnon's patch, this issue was fixed.

@halx99, could you try to apply that patch and test again? Thanks.

**Comment by halx99** [comment]
@dumganhar ok, I will test it
