### ISSUE TITLE
CCDownloader-apple DownloadFile Error

### ISSUE THREAD

**Issue by puckery** [cocos2d/cocos2d-x#16407]
- cocos2d-x version:3.10
- devices test on:iphone6
- developing environments
  - NDK version:
  - Xcode version:7.3.1
  - VS version:
  - brower type and version:

Steps to Reproduce:
1.  download and save file error:
   The file “CFNetworkDownload_ERkw5r.tmp” doesn’t exist.

error in this line:
if ([fileManager copyItemAtURL:location toURL:destURL error:&error])

**Comment by minggo** [comment]
How to reproduce it?

**Comment by puckery** [comment]
I haved resovled, it's must be create directory beforce copyItemFromUrl.
