### ISSUE TITLE
vs2013编译cocos2d-x2.2.2报错？怎么没人解答啊？

### ISSUE THREAD

**Issue by zhenqicai** [cocos2d/cocos2d-x#16408]
1>e:\cocos2dx\cocos2d-x-2.2.2\cocos2dx\platform\win32\cceglview.cpp(250): error C2065: “GLEW_OK”: 未声明的标识符
1>e:\cocos2dx\cocos2d-x-2.2.2\cocos2dx\platform\win32\cceglview.cpp(252): error C3861: “glewGetErrorString”:  找不到标识符
1>e:\cocos2dx\cocos2d-x-2.2.2\cocos2dx\platform\win32\cceglview.cpp(256): error C2065: “GLEW_ARB_vertex_shader”: 未声明的标识符
1>e:\cocos2dx\cocos2d-x-2.2.2\cocos2dx\platform\win32\cceglview.cpp(256): error C2065: “GLEW_ARB_fragment_shader”: 未声明的标识符
1>e:\cocos2dx\cocos2d-x-2.2.2\cocos2dx\platform\ccimagecommon_cpp.h(34): fatal error C1083: 无法打开包括文件: “png.h”: No such file or directory

**Comment by minggo** [comment]
This is a too old version, we don't have enough source to fix it. I'd better to upgrade to v2.2.6 or latest codes in github v2 branch. 

And please use english. Thanks.
