### ISSUE TITLE
Camera::_viewProjectionUpdated not initialised

### ISSUE THREAD

**Issue by Almax27** [cocos2d/cocos2d-x#16404]
cocos2d-x version: 3.12

Camera::_viewProjectionUpdated is not initialised in constructor. Should be initialised to false.
This can lead to redundant visibility checks if _viewProjectionUpdated happens to resolve true.

Furthermore as Camera::visit() is never called, _viewProjectionUpdated is never actually updated, resulting in no visibility tests when the camera transform changes.

I propose we add 
`_viewProjectionUpdated = _transformUpdated;`
to Camera::apply() as well.

**Comment by minggo** [comment]
@Almax27 i think you are right, thanks. @ricardoquesada could you please take a look?

**Comment by ricardoquesada** [comment]
@minggo looks good to me. I'll merge it once the build is green.
