### ISSUE TITLE
Cannot set position for CCProgressTimer 

### ISSUE THREAD

**Issue by peerobo** [cocos2d/cocos2d-x#16441]
- cocos2d-x version: 3.12 (obtained from github)
- devices test on: GT-P7300 (android os 4.0.4)
- developing environments
  - NDK version: 12b (64bit)
  - Application.mk: 

```
APP_STL := gnustl_static
NDK_TOOLCHAIN_VERSION := clang
APP_PLATFORM := android-19
APP_CPPFLAGS := -frtti -std=c++11 -fsigned-char -fexceptions -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS
APP_LDFLAGS := -latomic
APP_ABI := armeabi
```

Steps to Reproduce:
1. Create new cocos C++ project
2. Modified HelloWorldScene.cpp:

```
// add "HelloWorld" splash screen"
auto sprite = Sprite::create("HelloWorld.png");

// position the sprite on the center of the screen
// sprite->setPosition(Vec2(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y));

auto progress = ProgressTimer::create(sprite);
progress->setPosition(Vec2(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y));
progress->setType(cocos2d::ProgressTimer::Type::BAR);
progress->setPercentage(50.0f);

// add the sprite as a child to this layer
// this->addChild(sprite, 0);
this->addChild(progress);
```

![scr](https://cloud.githubusercontent.com/assets/4023681/17959401/57eedcc4-6aca-11e6-8529-c332dab0ea03.png)

The logo must be in the center of screen.
Then I copied old CCProgressTimer.cpp/h from cocos2d-x3.10 and everything was fine:

![scr1](https://cloud.githubusercontent.com/assets/4023681/17959538/3512bcba-6acb-11e6-96c7-a07512af546c.png)

**Comment by minggo** [comment]
Duplicated with #16400? How about change clang to gcc to have a try?

**Comment by peerobo** [comment]
After update to the latest cocos2d-x on github, everything is ok (still using clang).
