### ISSUE TITLE
"this.initWithString is not a function" when new cc.TextFieldTTF with params

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#16448]
cocos2dx 3.10 JSB  run on  ipad3

code:

issue 1:
var snTxt=new cc.TextFieldTTF("","arial",24);   //echo : this.initWithString is not a function 

issue 2:
var snTxt=new cc.TextFieldTTF();
snTxt.setFontSize(36);  //echo  setFontSize is not a function 

issude 3:
var snTxt=new cc.TextFieldTTF();
snTxt.fontSize=36 //Nothing happened.....

How to set the size of  cc.TextFieldTTF?

**Comment by liuyi** [comment]
Is Cocos2dx(JSB) is so important that you guys don't care fix these issues?
Or
You guys want all the cocos2d-js user move to CREATOR, so don't want fix these little bugs in cocos2d(JSB)?

**Comment by dumganhar** [comment]
cc.TextFieldTTF is so old and out of maintaining for a long time.
How about switching to `cc.EditBox`?

**Comment by liuyi** [comment]
OK, Thanks!
Because there are too much api & components such as  ccui.TextField, cc.TextFieldTTF ,cc.EditBox 
I'm confused to choose which one ...
