### ISSUE TITLE
upgrade OpenSSL to v1.1.0

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#16446]

**Comment by heyikun** [comment]
Whould u please tell me when can it be fninished , cause our apk  had been rejected by google play.

**Comment by minggo** [comment]
I think you can refer to [this topic](http://discuss.cocos2d-x.org/t/openssl-problem-again/28270). OpenSSL issue is resolved a few months ago, this issue is just upgrade it to latest version in advance.

**Comment by minggo** [comment]
@zilongshanren after i updated OpenSSL to 1.1.0, i can not build it for android. Please help to fix the compiling issue.

**Comment by zilongshanren** [comment]
[prebuilt.tar.gz](https://github.com/cocos2d/cocos2d-x/files/535621/prebuilt.tar.gz)

@heyikun  

I have successfully built the openssl 1.1.0b  static library, could you help to test it ?

Thanks.

**Comment by minggo** [comment]
it is updated to 1.1.0c
