### ISSUE TITLE
crash in void Renderer::fillVerticesAndIndices(const TrianglesCommand* cmd)

### ISSUE THREAD

**Issue by zloop1982** [cocos2d/cocos2d-x#16453]
- cocos2d-x version:3.13(branch v3)
- devices test on:iphone 6plus  ios 9.3.3
- developing environments
  - NDK version:
  - Xcode version: 7.3.1 (7D1014)
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. upgrade spine to newest (spine-c ,spine-cocos2dx)
2. try example in spine-cocos2dx.

will crash when you run BatchingExample or run RaptorExample and tap screen enter the batching scene.
xcode report :EXC_BAD_ACCESS  in this line (function : fillVerticesAndIndices in CCRender)
memcpy(&_verts[_filledVertex], cmd->getVertices(), sizeof(V3F_C4B_T2F) \* cmd->getVertexCount());

for memcpy to _verts is bad access.
_verts not null, _filledVertex less than 65536, in most of the time, _filledVertex is 512.
but it's not happened in iOS simulator.
@minggo

**Comment by minggo** [comment]
@zloop1982 v3.13 already update to spine-3.4, you can just try v3.13. We haven't updated to newest spine-cocos2dx.

**Comment by zloop1982** [comment]
@minggo you are right, newest  spine-c have supported all Spine features, include support loading the binary format[not supported by spine-cocos2dx yet].
but I think this is an issue in fillVerticesAndIndices, BatchingExample is just an test case which can reproduce the crash.
It seems like memory manage about _verts have some problem. 
there is some different between iOS simulator  and iphone device.

I will try the spine-3.4 which in v3.13 late, to figure out  if it will crash in BatchingExample.

**Comment by zloop1982** [comment]
bad news, it still crash in the same line when I use the old spine .
so the reproduce step is:

test the BatchingExample[commit 3af5290e23108d409c9dc5754b4adbfedf2e814d] from {https://github.com/EsotericSoftware/spine-runtimes} with the cocos2d-x 3.13 [commit 6c9a05f8319553bb7c3fd81fcca32c6d767903b6]

don't need to upgrade spine.

{
    gl.supports_OES_map_buffer: true
    gl.supports_vertex_array_object: true
    cocos2d.x.version: cocos2d-x-3.13
    gl.vendor: Apple Inc.
    gl.supports_PVRTC: true
    gl.renderer: Apple A8 GPU
    cocos2d.x.compiled_with_profiler: false
    gl.supports_S3TC: false
    gl.version: OpenGL ES 2.0 Apple A8 GPU - 77.14
    cocos2d.x.build_type: DEBUG
    gl.max_texture_size: 4096
    gl.supports_ETC1: false
    gl.supports_BGRA8888: false
    gl.max_texture_units: 8
    gl.max_samples_allowed: 4
    gl.supports_OES_packed_depth_stencil: true
    gl.supports_ATITC: false
    gl.supports_NPOT: true
    gl.supports_discard_framebuffer: true
    cocos2d.x.compiled_with_gl_state_cache: true
    gl.supports_OES_depth24: true
}

IOS version is 9.3.5

**Comment by zloop1982** [comment]
my bad.
EXC_BAD_ACCESS is on cmd->getVertices();  not  _verts.
getVertices() return _triangles.verts, address is 0x000000010783c810.

**Comment by zloop1982** [comment]
finally, the crash is because for 50 spine boys , SkeletonBatch::setBufferSize(512)
is not enugh.
create 50 spine boys on device must use SkeletonBatch::setBufferSize(3600).
seems like the size of SkeletonBatch can not auto increase on iphone.

**Comment by minggo** [comment]
@zloop1982 there is not `SkeletonBatch` test in cocos2d-x, is it a new test case?

**Comment by zloop1982** [comment]
no,cocos2d-x already have SkeletonBatch.
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/editor-support/spine/SkeletonBatch.h

**Comment by zloop1982** [comment]
BatchingExample set SkeletonBatch::setBufferSize(512) at start.
It's ok for simulator. but crash in device.
on device should set enough size at beginning.

**Comment by zloop1982** [comment]
oh, you mean SkeletonBatch test case. yes.
this test case is from EsotericSoftware/spine-runtimes/spine-cocos2dx.

**Comment by minggo** [comment]
yep, i mean the test case. So it is an issue of spine-runtime itself?

**Comment by zloop1982** [comment]
I don't know. need more deep debug. 75% is SkeletonBatch's issue.

**Comment by zloop1982** [comment]
I read the code, this is SkeletonBatch's issue. 100%

**Comment by minggo** [comment]
so please report it to spine-runtime repo.

**Comment by zloop1982** [comment]
already reported.

**Comment by minggo** [comment]
can i close the issue?

**Comment by zloop1982** [comment]
yes

**Comment by FastGitHub** [comment]
@minggo zloop1982 Can you solve the issue?  How to fix it? Thanks!

**Comment by FastGitHub** [comment]
@zloop1982  Can you solve the issue? How to fix it? Thanks!
