### ISSUE TITLE
How to replace the simpleaudioengine with the new audio engin?

### ISSUE THREAD

**Issue by jminht** [cocos2d/cocos2d-x#16450]
i'm using cocos2dx v3.1.1.
and i got the problem "audio lagged in nexus 4".
i want to try the new audio engine and found that the cocos i used is so different from the lastest cocos2dx v3.12.
how can i replace the old audio engine without modify files which are not related to the audio engine?

**Comment by liuyi** [comment]
You can write a wrapper to avoid change audio api when audio engine API changed.

**Comment by minggo** [comment]
yep, you can do as @liuyi 's suggestion.
