### ISSUE TITLE
cocos3.13   jsval_to_std_string 

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#16459]
- cocos2d-x version:  3.13

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/manual/js_manual_conversions.cpp  line:604

原本是 if(v.isString() || v.isNumber())

现在变成  if(v.isString() || v.isBoolean())

这真的好吗？  在js代码中， 经常 setString(123), 很少setString(true)吧？

**Comment by dumganhar** [comment]
@pandamicro , please take a look.

**Comment by pandamicro** [comment]
Sorry, it should be 

```
if(v.isString() || v.isNumber() || v.isBoolean())
```

I suppose it's caused during code merging, sorry for the inconvenient, @huangapple

**Comment by huangapple** [comment]
Thank you!

**Comment by huangapple** [comment]
@pandamicro  
fix it on github?

**Comment by dumganhar** [comment]
@pandamicro , could send a PR for that?

**Comment by dumganhar** [comment]
fixed it at https://github.com/cocos2d/cocos2d-x/pull/16504, closed this issue.

**Comment by minggo** [comment]
v3.13.1 fixed in #16515.
