### ISSUE TITLE
Don't build New Project in cross platform IDE's on OS X

### ISSUE THREAD

**Issue by yuriilychak** [cocos2d/cocos2d-x#16467]
- cocos2d-x version: 3.13 && 3.12
- devices test on: mac Mini
- developing environments
  - NDK version:
  - Xcode version: 7.3.1
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. Create project from console.
2. Build project in QTCreator, CLion, NetBeans, CodeBlocks etc on OS X. 
3. Get "Undifinded symbol for architecture x86-64".

In cocos2d-x v3.11 all works fine. Seems like some librarys in "CMakeList.txt" files are not linked well. I'm using Ubuntu and OS X, and for me is impotent to use one IDE for development.

**Comment by liuyi** [comment]
I suggest InteliJ IDEA OR PHP Storm and XCODE

**Comment by yuriilychak** [comment]
Sorry, but I'm using C++ version of engine. Intelij IDE and PHP Storm don't support  C++. In JetBrains CLion it don't builds (under OS X). I use XCode for building for IPhone, but it not cross platform, I can't use it on Ubuntu or Windows.

**Comment by minggo** [comment]
We don't make sure the engine can work on all IDE, but we accept PR if it will not too complex.
