### ISSUE TITLE
Support for Game Controllers on Mac

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/cocos2d-x#16460]
iOS and Mac share the same API for game controllers.
Adding support for Mac is almost free and it makes more sense to play game on Mac with game controllers than on iOS

**Comment by ricardoquesada** [comment]
merged.

**Comment by Bilalmirza** [comment]
@ricardoquesada hey, Ive test both xbox controller and playstation controller they don't work. Previously i had tried for android controller that worked fine.

Test was done on a mac with a v3.13.1 Test project. Should i be downloading specific drivers?

Any help would be greatly appreciated :D

Thanks

**Comment by ricardoquesada** [comment]
@Bilalmirza it only supports MFi devices (same controllers as in iOS)... anyone from this list:
https://afterpad.com/mficontrollers/
