### ISSUE TITLE
Ref's reference counting is using non-atomic ints, while allowing reference count mutation across multiple threads

### ISSUE THREAD

**Issue by DavidDeSimone** [cocos2d/cocos2d-x#16465]
- cocos2d-x version: 3.11
- devices test on: iPad Air 2
- developing environments
  - NDK version: 
  - Xcode version:
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. This is a rare race condition that is most common in networking code. A common usage pattern of HTTP requests looks like the following:

```
HttpRequest* request = new (std::nothrow) HttpRequest();
request->setUrl(url);
 request->setRequestType(HttpRequest::Type::GET);
 HttpClient::getInstance()->send(request);
 request->release();
```

Calling send will send the request into an input queue, which it will be picked up on a working thread, executing the following code:

```
  while (true) 
    {
        HttpRequest *request;

        // step 1: send http request if the requestQueue isn't empty
        {
            std::lock_guard<std::mutex> lock(_requestQueueMutex);
            while (_requestQueue.empty())
            {
                _sleepCondition.wait(_requestQueueMutex);
            }
            request = _requestQueue.at(0);
            _requestQueue.erase(0);
        }

        if (request == _requestSentinel) {
            break;
        }

        // step 2: libcurl sync access

        // Create a HttpResponse object, the default setting is http access failed
        HttpResponse *response = new (std::nothrow) HttpResponse(request);
//...
```

The issue here is that creating an HttpResponse will mutate the reference count of the request. Depending on the thread scheduler, the following two lines of code can be run on two different threads at the same time

```
>>>> THREAD 1
request->release();
-----
HttpResponse *response = new (std::nothrow) HttpResponse(request);
<<<<<  THREAD 2
```

Both of these calls will mutate the ref count, which is a non-atomic integer with no thread guarding. This can potentially cause some very bad behavior, and in the worse case a crash, or mis reference count. 

I have a few different solutions I am prepared to contribute, based on the opinion of the contributors (if they believe this is a problem worth acting on). 

Potential Solution 1: Making Ref uses atomic in all cases is wasteful, and will waste time when refs will not be shared across threads. However, certain Refs are known to be shared across threads. We could use templating to create two versions of Ref, one that uses atomics, and one that does not use atomics. Things like HttpRequests will use the atomic version. 

Potential Solution 2: Attempt to make Refs that are known to be shared across threads use std::shared_ptr, which is safe against this problem.

**Comment by minggo** [comment]
Yep, it is design like this. Make it thread-safe will slow down the performance.
