### ISSUE TITLE
3.13 android OpenSLES error while play background music in writablepath or sdcard

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#16473]
![0gssc8wzu5 4as56k e2r j](https://cloud.githubusercontent.com/assets/10572028/18089676/ad61cdd8-6ef3-11e6-925a-7d5ef08b3d36.png)

this is bug?

**Comment by minggo** [comment]
how to reproduce it? And please use english in future, then all developers can join the discussion. Thanks.

**Comment by minggo** [comment]
@dumganhar please take a look.

**Comment by huangapple** [comment]
wait, i',m trying make a demo package

**Comment by dumganhar** [comment]
@huangapple , I reproduced it. Don't worry, I will submit a Pull Request to fix.

**Comment by dumganhar** [comment]
@huangapple , fixed it at https://github.com/cocos2d/cocos2d-x/pull/16475

Please try to apply that patch and test it again.

BTW, `FileUtils` doesn't provide a API to copy a file to /sdcard or writable path. It's hard for me to add a test case. :(

**Comment by huangapple** [comment]
now it can play background music in writablepath or sdcard, but can't stop music in writablepath or sdcard??  
maybe is my problem,  I'm will try again.
@dumganhar

**Comment by dumganhar** [comment]
How did you stop music? cpp-tests -> NewAudioEngineTest could stop background music.
Did you pass a correct `audioId` to `AudioEngine::stop(int id)`?
Or did you use `AudioEngine::stopAll()`?

**Comment by huangapple** [comment]
jsb.AudioEngine.stop(id).  
That seems to be accidental.
maybe is my problem

**Comment by huangapple** [comment]
i try again, but no reproduced

**Comment by huangapple** [comment]
var id = jsb.AudioEngine.play2d("xxx.mp3", true)
in other scene, i use jsb.AudioEngine.stop(id)  and  play other background music.
maybe  in xxx.mp3 in loop clearance,  jsb.AudioEngine.stop(id) can't to stop it??
May this be the case???
I  reproduced twice, that seems to be accidental.

**Comment by dumganhar** [comment]
@Please send an email to me(jianhua.chen@cocos2d-x.org) and leave your QQ account.
I will help to find out the issue. Thanks.

**Comment by Valiancer** [comment]
I have the same problem，play downloaded music，It is not valid，fixed it at #16475， apply that patch，then it works，but when i stop it  by AudioEngine::stop(_audioID), it crashed,

**Comment by dumganhar** [comment]
@Valiancer, could you paste some code snippets and upload the logcat output?

**Comment by Valiancer** [comment]
@huangapple sorry，yesterday's question is my fault. but i found when i stop the music，it will call the callback，AudioEngine::setFinishCallback(_audioID, std::bind(&MusicPlayer::callbackMusicFinish, this, std::placeholders::_1, std::placeholders::_2));    in Android

**Comment by Valiancer** [comment]
@dumganhar sorry，yesterday's question is my fault. but i found when i stop the music，it will call the callback，AudioEngine::setFinishCallback(_audioID, std::bind(&MusicPlayer::callbackMusicFinish, this, std::placeholders::_1, std::placeholders::_2)); in Android

**Comment by dumganhar** [comment]
@Valiancer , good to know it works for you now.

**Comment by Valiancer** [comment]
@dumganhar  i found when i stop the music，it will call the callback，AudioEngine::setFinishCallback(_audioID, std::bind(&MusicPlayer::callbackMusicFinish, this, std::placeholders::_1, std::placeholders::_2)); in Android

**Comment by dumganhar** [comment]
@Valiancer , I'll check it.

**Comment by dumganhar** [comment]
@Valiancer , I checked the code and found that it should not happen, could you please upload logcat output for me to analyze?

**Comment by Valiancer** [comment]
@dumganhar [http://forum.cocos.com/t/cocos2d-x-3-13-android-audioengine-stop/39432](url)

**Comment by minggo** [comment]
synchronize to v3.13.1 in #16521, @dumganhar , please take a look.

**Comment by dumganhar** [comment]
@minggo , I have reviewed it and it's great.
