### ISSUE TITLE
couldn't open release mode in vs 2015 used by cocos2d-x 3.13

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#16472]
- cocos2d-x version: 3.13
- devices test on:
- developing environments
  - NDK version:
  - Xcode version:
  - VS version: 2015
  - brower type and version:

Steps to Reproduce:
1. cocos new TD -p org.cocos2dx.test -l lua -d D:\client\test
2. open it with vs 2015, the debug model is fine. but release model crash with error.
   ![image](https://cloud.githubusercontent.com/assets/5201160/18089623/73ef5610-6ef3-11e6-9d96-26fda11290ee.png)

**Comment by dumganhar** [comment]
@Dauch , did you build it in debug mode and then build it in release mode ?

**Comment by dumganhar** [comment]
@Dauch ,please check this https://github.com/cocos2d/cocos2d-x/pull/16501

**Comment by Dauch** [comment]
yes, ok, I will try :)

**Comment by Dauch** [comment]
Thanks, It works. @dumganhar ,pls close this issue.

**Comment by dumganhar** [comment]
Good to know it works for you now. I closed this issue.
