### ISSUE TITLE
Does it normal the empty "hello world" project consume cpu 40% around is fine?

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#16474]
- cocos2d-x version: 3.13 
- devices test on:
- developing environments
  - NDK version:
  - Xcode version:
  - VS version: 2015 
  - brower type and version:

Steps to Reproduce:

use debug model, it is highly cpu consume.
![image](https://cloud.githubusercontent.com/assets/5201160/18089827/65beb12a-6ef4-11e6-857d-f1accea777fe.png)

**Comment by huangapple** [comment]
This is normal.

**Comment by Dauch** [comment]
@huangapple  what? (black man ???)

**Comment by huangapple** [comment]
再空的项目， cocos也要一秒60帧的刷啊。他又不是应用程序的引擎， 是游戏的引擎， 大部分游戏界面是一直动的， 所以无条件刷是比较合适的。如果有大量不动的ui时， cocos 好像也有脏矩阵 策略。但要手动开， 并不适合大部分游戏。

**Comment by PengboGai** [comment]
that's the problem 60 fps

**Comment by minggo** [comment]
yep, it is normal. Game engine is different from app, it will re-draw everything in a frame.
