### ISSUE TITLE
Text color lose in  cocos2d-x 3.13

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#16471]
- cocos2d-x version: 3.13
- devices test on: win32
- developing environments
  - NDK version:
  - Xcode version:
  - VS version: 2015
  - brower type and version:
- cocostudio 3.10

Steps to Reproduce:

open csb, is Text type's color is lose, it won't set
origin:
![image](https://cloud.githubusercontent.com/assets/5201160/18089332/07eac9c8-6ef2-11e6-8f64-8c3464093945.png)
output:
![image](https://cloud.githubusercontent.com/assets/5201160/18089395/5f7f7882-6ef2-11e6-921c-e20bde7dee72.png)

i didn't do anything in code change it's color, it should be expected like in cocostudio(is ok with cocos2d-x 3.12)

**Comment by zhaozhantao** [comment]
Me too.

**Comment by Dauch** [comment]
pls give some help @minggo

**Comment by minggo** [comment]
sorry, cocostudio is canceled, we don't have resource to handle corresponding issues.

**Comment by Dauch** [comment]
@minggo  any suggestion for this bugifx?

**Comment by minggo** [comment]
I am sorry, i are not familiar with cocostudio and we don't make sure v3.13 can work with cocos studio.

**Comment by zhaozhantao** [comment]
this is min code:

```
local node = cc.Node:create()
self:addChild(node, 100)
-- 此处设置为false则testLabel:setTextColor有效
-- 设置为true则testLabel:setTextColor无效
-- if set false then  testLabel:setTextColor is useful
node:setCascadeColorEnabled(true) 
local testLabel = ccui.Text:create()
testLabel:setFontSize(72)
testLabel:setString("test setCascadeColorEnabled")
testLabel:setTextColor({r = 0, g = 0, b = 0})
node:addChild(testLabel)
```

**Comment by Dauch** [comment]
In CCLabel.cpp line 1893, I comment line 1893&1894 it work fine. changging those has any bad influence?
@minggo
`
void Label::updateDisplayedColor(const Color3B& parentColor)
{
    Node::updateDisplayedColor(parentColor);

```
//if (_currentLabelType == LabelType::TTF || _currentLabelType == LabelType::STRING_TEXTURE)
//    setTextColor(Color4B(_displayedColor));
```

`

**Comment by zhaozhantao** [comment]
@Dauch I delete the two line code. It work fine.
I compare cocos2d-x 3.12 and 3.13 , this two line is 3.13 added. same a bugfix.
Who know the two line should delete or save.

**Comment by zhaozhantao** [comment]
in this commit https://github.com/cocos2d/cocos2d-x/commit/35008702bfe7a33f75b9ad823d64b6c4773ca45b

**Comment by Dauch** [comment]
just delete it if you don't use underline @zhaozhantao

**Comment by dumganhar** [comment]
@minggo ,it seems to be an issue which isn't related to CocosStudio. I re-opened this.

@ricardoquesada , could you please take a look this issue since https://github.com/cocos2d/cocos2d-x/commit/35008702bfe7a33f75b9ad823d64b6c4773ca45b was updated by you.

**Comment by ricardoquesada** [comment]
I can reproduce and also happens on `Label()`. This is not related to Cocos Studio.

**Comment by ricardoquesada** [comment]
thanks. fixed.

**Comment by minggo** [comment]
#16516 for v3.13.1 branch, @ricardoquesada please check it.

**Comment by ricardoquesada** [comment]
@minggo looks good to me

**Comment by minggo** [comment]
@ricardoquesada thanks.
