### ISSUE TITLE
怎么才能正确生成mips、mips64、arm64-v8a、x86_64对应的libcocos2dcpp.so？

### ISSUE THREAD

**Issue by yunmin97** [cocos2d/cocos2d-x#16479]
cocos2dx版本：3.8.1
1、生成armeabi、armeabi-v7a、x86下面的libcocos2dcpp.so没有问题，但是生成其他的mips、mips64、arm64-v8a、x86_64就报各种错！
2、看了一下貌似cocos库里面的external扩展库中没有mips、mips64、arm64-v8a、x86_64对应的xxx.a文件，但是armeabi、armeabi-v7a、x86这三个是有的（比如：chipmunk、png的都没有）！
3、请问这个要怎么解决？cocos官方可以提供其他cpu架构（mips、mips64、arm64-v8a、x86_64）的xxx.a吗？？

**Comment by yunmin97** [comment]
平台：andriod

**Comment by dumganhar** [comment]
3.13之前支持 armeabi, armeabi-v7a, x86，其他架构不支持。
3.13支持 armeabi, armeabi-v7a, arm64-v8a, x86，其他架构不支持。

**Comment by yunmin97** [comment]
Get了，目前接腾讯的MSdk和米大师支付sdk多了mips、mips64、arm64-v8a、x86_64的cpu架构，如果cocos2dx没有对应的cpu架构的xxx.a，估计在这些cpu架构的机器上无法完成登陆或者支付！

**Comment by dumganhar** [comment]
Forget those archs. They have really small users.

**Comment by yunmin97** [comment]
ok，got it!!
