### ISSUE TITLE
How to use joystick in cocos2d-x?

### ISSUE THREAD

**Issue by ZeroObject** [cocos2d/cocos2d-x#16481]
cocos2d-x used GLFW and GLFW support joystick function. I tried to use it. it does not work on windows, but osx and linux is no problem.

```
cocos2d-x 3.12 and 3.13 (GLFW 3.2)
windows 10
osx 10.11
ubuntu 16.04
```

```
static int joysticks[GLFW_JOYSTICK_LAST + 1];
static int joystick_count = 0;

static void joystick_callback(int joy, int event)
{
    if (event == GLFW_CONNECTED)
    {
        int axis_count, button_count;

        glfwGetJoystickAxes(joy, &axis_count);
        glfwGetJoystickButtons(joy, &button_count);

        printf("Found joystick %i named \'%s\' with %i axes, %i buttons\n",
               joy + 1,
               glfwGetJoystickName(joy),
               axis_count,
               button_count);

        joysticks[joystick_count++] = joy;
    }
    else if (event == GLFW_DISCONNECTED)
    {
        int i;

        for (i = 0;  i < joystick_count;  i++)
        {
            if (joysticks[i] == joy)
                break;
        }

        for (i = i + 1;  i < joystick_count;  i++)
            joysticks[i - 1] = joysticks[i];

        printf("Lost joystick %i\n", joy + 1);
        joystick_count--;
    }
}

static void find_joysticks(void)
{
    int joy;

    for (joy = GLFW_JOYSTICK_1;  joy <= GLFW_JOYSTICK_LAST;  joy++)
    {
        if (glfwJoystickPresent(joy))
            joystick_callback(joy, GLFW_CONNECTED);
    }
}

bool GamepadTestScene::init() {
    if (!Layer::init())
    {
        return false;
    }

    memset(joysticks, 0, sizeof(joysticks));
    find_joysticks();
    glfwSetJoystickCallback(joystick_callback);

    return true;
}
```

**Comment by ZeroObject** [comment]
http://gamedev.stackexchange.com/questions/129225/how-to-use-joystick-in-cocos2d-x

**Comment by dumganhar** [comment]
> it does not work on windows

What was the error?

**Comment by ZeroObject** [comment]
It was not any error. GLFWEventHandler::onGLFWError was not called.

>  vs2015 output. xbox 360 Controller was connection on wire.

```
Ready for GLSL
Ready for OpenGL 2.0

{
    gl.version: 4.5.0 NVIDIA 358.91
    gl.supports_NPOT: true
    cocos2d.x.version: cocos2d-x-3.13
    cocos2d.x.compiled_with_profiler: false
    cocos2d.x.build_type: DEBUG
    cocos2d.x.compiled_with_gl_state_cache: true
    gl.max_texture_size: 16384
    gl.supports_OES_packed_depth_stencil: false
    gl.vendor: NVIDIA Corporation
    gl.renderer: GeForce GTX 750 Ti/PCIe/SSE2
    gl.max_texture_units: 192
    gl.supports_ETC1: false
    gl.supports_S3TC: true
    gl.supports_ATITC: false
    gl.supports_PVRTC: false
    gl.supports_BGRA8888: false
    gl.supports_discard_framebuffer: false
    gl.supports_vertex_array_object: true
    gl.supports_OES_map_buffer: false
    gl.supports_OES_depth24: false
}


cocos2d: warning, Director::setProjection() failed because size is 0
cocos2d: fullPathForFilename: No file found at /cc_2x2_white_image. Possible missing file.
cocos2d: QuadCommand: resizing index size from [-1] to [2560]
```

> xcode output. Playstation 4 controller was connection on bluetooth.

```

{
    gl.supports_OES_map_buffer: false
    gl.supports_vertex_array_object: true
    cocos2d.x.version: cocos2d-x-3.13
    gl.vendor: NVIDIA Corporation
    gl.supports_PVRTC: false
    gl.renderer: NVIDIA GeForce GT 750M OpenGL Engine
    cocos2d.x.compiled_with_profiler: false
    cocos2d.x.build_type: DEBUG
    cocos2d.x.compiled_with_gl_state_cache: true
    gl.max_texture_size: 16384
    gl.supports_ETC1: false
    gl.supports_BGRA8888: false
    gl.max_texture_units: 16
    gl.supports_OES_packed_depth_stencil: false
    gl.supports_ATITC: false
    gl.supports_discard_framebuffer: false
    gl.supports_NPOT: true
    gl.version: 2.1 NVIDIA-10.10.13 310.42.25f01
    gl.supports_S3TC: true
    gl.supports_OES_depth24: false
}


cocos2d: warning, Director::setProjection() failed because size is 0
Found joystick 1 named 'Wireless Controller' with 6 axes, 18 buttons
cocos2d: QuadCommand: resizing index size from [-1] to [2560]

```

> ubuntu output. xbox 360 and PS4 controller was connection on wire.

```
Ready for GLSL
Ready for OpenGL 2.0
Found joystick 1 named 'Microsoft X-Box 360 pad' with 8 axes, 11 buttons
Found joystick 2 named 'Sony Computer Entertainment Wireless Controller' with 12 axes, 14 buttons

```

**Comment by dumganhar** [comment]
So it's probably an issue of glfw on windows. Could you check whether there is a new version of GLFW released? If this issue exits in the latest version of GLFW, you probably need to submit this issue to GLFW official. Thanks.

**Comment by ZeroObject** [comment]
I build and run GLFW 3.2 source code build-in joystick test. It was perfect worked anywhere except for PS4 Controller with bluetooth on ubuntu, but use USB cable is right. I have tested GLFW 3.1, 3.2, 3.2.1 and cocos2d-x 3.11, 3.12, 3.13. The results are the same.

**Comment by dumganhar** [comment]
Currently, cocos2d-x is using GLFW 3.2.0, so according to what you experiment, it should work on Windows. Did you try put the GLFW 3.2.0 source code to cocos2d-x VS projects and check that why joystick devices could not be found?

**Comment by ZeroObject** [comment]
I known it can use Xinput, but I really would not like to call the local API.

**Comment by ZeroObject** [comment]
I do not know how to build it after put it in. Finally, I tried to do that, but always build failing. Would you help me with this problem? I known it can use Xinput, but I really would not like to call the local API. Thanks.

**Comment by Rubonnek** [comment]
I was able to reproduce the same issue as @ZeroObject. I didn't pinpoint the exact issue, but it seems to lie on how the GLFW library is being compiled since I was able to get an Xbox 360 controller working on my build by using the official prebuilt GLFW library. Here's what I did on a step by step basis:
1. I downloaded the [GLFW library](https://github.com/glfw/glfw/releases/download/3.2/glfw-3.2.bin.WIN32.zip) from the official [github release page](https://github.com/glfw/glfw/releases).
2. Extracted the prebuilt libraries, from the downloaded zipped file, at `glfw-3.2.bin.WIN32\lib-vc2015` to `%PROJECT_ROOT%\cocos2d\external\glfw3\prebuilt\win32`
3. Deleted `%PROJECT_ROOT%\cocos2d\external\glfw3\prebuilt\win32\glfw3-2015.lib`
4. Renamed `%PROJECT_ROOT%\cocos2d\external\glfw3\prebuilt\win32\glfw3dll.lib` to `%PROJECT_ROOT%\cocos2d\external\glfw3\prebuilt\win32\glfw3-2015.lib`
5. Built the project again and done -- the Xbox 360 controller was detected. Here's the output I got: `Found joystick 1 named 'Wireless Xbox 360 Controller' with 6 axes, 14 buttons`. Everything else seems to be working fine. 

I think we should also update to GLFW 3.2.1. Some bugs were found that affected all the GLFW supported platforms.

**Comment by dumganhar** [comment]
@Rubonnek , did you check that GLFW 3.2.1 fixed this issue?

**Comment by Rubonnek** [comment]
@dumganhar Yes. You can follow the same steps as above with [GLFW 3.2.1](https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN32.zip) instead while also replacing the headers at `%PROJECT_ROOT%\cocos2d\external\glfw3\include\win32` with the headers from the official prebuilt release at `glfw-3.2.1.bin.WIN32.zip\glfw-3.2.1.bin.WIN32\include\GLFW` and you will get the same results.

I also tested this on Linux, but not on Mac.

**Comment by ZeroObject** [comment]
I used @Rubonnek method to update to GLFW 3.2.1. Everything looks fine! 
Think you!!😆

**Comment by bsy6766** [comment]
Will there be an update for GLFW on Cocos2d-x? Latest GLFW (on github not released version) added awesome feature for desktop platform window settings and would love to PR new features.

**Comment by Bilalmirza** [comment]
updating to 3.2.1 works :) thanks guys

**Comment by Bilalmirza** [comment]
@minggo @dumganhar Guys could you please update glfw to 3.2.1 for v3.15? it doesn't take long.

**Comment by dumganhar** [comment]
@Bilalmirza , the upgrade will not be in v3.15 since it's in RC now.
I create an issue https://github.com/cocos2d/cocos2d-x/issues/17700 here.
It will probably be in v3.16.
