### ISSUE TITLE
v3.13 -> apps crashing if they don't specify a design resolution

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#16485]
Apps are crashing if not using a Design resolution:
http://discuss.cocos2d-x.org/t/cocos2d-x-3-13-crashes-when-not-using-design-resolution/31756/6

user posted a work around of: 

```
Director::getInstance()->getOpenGLView()->setContentScaleFactor(1.0f);
Director::getInstance()->getOpenGLView()->setDesignResolutionSize(Director::getInstance()->getOpenGLView()->getFrameSize().width, Director::getInstance()->getOpenGLView()->getFrameSize().height, ResolutionPolicy::EXACT_FIT);
```

**Comment by ermanhaskan** [comment]
Experienced this issue yesterday, did the same thing to fix it. Only occurs on Android.

**Comment by dumganhar** [comment]
@ricardoquesada , could you please take a look at this issue?
It does crash in Camera::projectGL. Thanks.

**Comment by stevetranby** [comment]
Also, while this is probably an improvement, our game broke on upgrade as well because we were setting the projection type before setting our design resolution, which worked fine using 3.7 to 3.12. 

Maybe setProjection throw an assertion instead of just a warning? With a note that says to make sure design resolution is set before changing state in the Director?

**Comment by sachingarg05** [comment]
Our code failed because Director::getInstance()->getVisibleSize(); would return zero.

Using the above workaround fixed it for us too.

**Comment by ricardoquesada** [comment]
**UPDATE 1:** it is crashing here:
09-06 18:00:31.946 25830-25855/org.cocos2dx.cpp_empty_test E/cocos2d-x assert: /Users/riq/progs/cocos2d-x/tests/cpp-empty-test/proj.android/../../../cocos/./2d/CCCamera.cpp function:projectGL line:281

**UPDATE 2:** Why did it work in the first place without a design resolution. I guess the default one should be the one posted above as the workaround.

**UPDATE 3:** Crashes at least on Mac, Android and iOS

**UPDATE 4:** I confirm that it works on v3.12. I thought it was related to the VR code, but apparently it is not.

**UPDATE 5:**: Found the culprit: https://github.com/cocos2d/cocos2d-x/commit/0e64c2a07174701d7dcc26f75112d3061b455124
