### ISSUE TITLE
[android, audio] AudioEngine::stop() triggers 'finished' callback

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16490]
Reported at http://forum.cocos.com/t/cocos2d-x-3-13-android-audioengine-stop/39432
- cocos2d-x version: 3.13
- devices test on: Android
- developing environments
  - NDK version: r10e

Steps to Reproduce:
1. NewAudioEngineTest -> ControlTest
2. Click play, then click stop button
3. finished callback will be triggered

**Comment by minggo** [comment]
synchronized to v3.13.1 in #16524
