### ISSUE TITLE
websocket (JSB) cause lag when recieve msg

### ISSUE THREAD

**Issue by zmox** [cocos2d/cocos2d-x#16505]
- cocos2d-x version: 3.11 (JSB)
- devices test on: iOS/Android

Steps to Reproduce:
1. use websocket recieve msg, cause obvious lag,  (seem block ui thread???)

**Comment by dumganhar** [comment]
How did you test it? And how did you measure the lag.

**Comment by zmox** [comment]
sorry, it seem its my logic problem... already fix it
