### ISSUE TITLE
v3.13 -> SPINE color bug.

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#16502]
SPINE will display objects as black, when color is at all modified in the editor. Comparing color code with previous SPINE versions fixed it. Since I am not sure if this is a correct fix, I will not make a PR.

![screen shot 2016-09-02 at 08 14 11](https://cloud.githubusercontent.com/assets/21215757/18193340/45331200-70e5-11e6-8d81-f85bbb5a2ae1.png)

**Comment by dumganhar** [comment]
It's a bug, I will check whether it was fixed at https://github.com/EsotericSoftware/spine-runtimes.

**Comment by dumganhar** [comment]
It seems to be fixed at https://github.com/EsotericSoftware/spine-runtimes/commit/c8b72e382f10d555187ef74e38306893972bd489

Could you apply that patch and test again?
But I think your patch should also work. 👍

**Comment by ghost** [comment]
Yes, the fix you posted also works fine.

**Comment by dumganhar** [comment]
I submitted a PR for this: https://github.com/cocos2d/cocos2d-x/pull/16503
