### ISSUE TITLE
outlined LabelTTF  sometimes rendered dirty with artifacts

### ISSUE THREAD

**Issue by rockingdice** [cocos2d/cocos2d-x#16518]
- cocos2d-x version: 3.8
- devices test on: iPhone 6+
- developing environments
  - NDK version: --
  - Xcode version: 7.3.1
  - VS version: --
  - brower type and version: --

Steps to Reproduce:
1. Use Chinese Language TTF to create some LabelTTF with outline enabled.
2. Not always reproducible. I think those artifacts are used to be former characters. since our game needs to display lots of Chinese characters, these textures in atlas may be removed frequently when they are not used anymore.

I also found someone had same issue in v3.2:
[Click Here](http://www.cocoachina.com/bbs/read.php?tid=238214)

Is this something related to texture bleeding or not cleaning carefully? I'm just guessing.

Some pictures to help understand:
<img width="172" alt="111" src="https://cloud.githubusercontent.com/assets/3458134/18240270/444a2b68-737d-11e6-9dd8-b6bfa231049b.png">
<img width="369" alt="222" src="https://cloud.githubusercontent.com/assets/3458134/18240271/44a4e17a-737d-11e6-905a-8e66d59a85c9.png">

**Comment by rockingdice** [comment]
By the way, I also checked the change history of CCFreeTypeFont.cpp till v3.13, and I don't find anything helpful to this issue. Hopefully this will be fixed in latest version or just give a patch to fix it, thank you.

**Comment by shenwei0415** [comment]
This bug has been fixed in v3.13, you can merge from cocos/2d/CCFontAtlas.cpp

**Comment by rockingdice** [comment]
@shenwei0415 Thank you, I'll try it.
