### ISSUE TITLE
while playing music in background, preload it make this music stop.

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#16526]
- cocos2d-x version:3.13
- devices test on:Samsunm I9300
- developing environments
  - NDK version:r10b
  - Xcode version:
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. play the background music:
   `cc.SimpleAudioEngine:getInstance():playMusic("a.mp3")`
2. preload this background music:
   `cc.SimpleAudioEngine:getInstance():preloadMusic("a.mp3")`

then it stop.

and another thing, while i play the sound, it keep throwing those err but is running is ok

09-06 15:07:39.369 1911-14744/? E/AudioPolicyService: getOutput() tid 14744 ++
09-06 15:07:39.369 1911-14744/? E/AudioPolicyService: getOutput() tid 14744 --
09-06 15:07:39.369 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 ++
09-06 15:07:39.369 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 --
09-06 15:07:39.369 1911-2181/? E/AudioPolicyService: getOutput() tid 2181 ++
09-06 15:07:39.369 1911-2181/? E/AudioPolicyService: getOutput() tid 2181 --
09-06 15:07:39.394 1911-2217/? E/AudioMixer: MOON > checkSEC_PCM ++ 1
09-06 15:07:40.079 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 ++
09-06 15:07:40.079 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 --
09-06 15:07:40.079 1911-2181/? E/AudioPolicyService: getOutput() tid 2181 ++
09-06 15:07:40.079 1911-2181/? E/AudioPolicyService: getOutput() tid 2181 --
09-06 15:07:40.079 1911-2260/? E/AudioPolicyService: getOutput() tid 2260 ++
09-06 15:07:40.079 1911-2260/? E/AudioPolicyService: getOutput() tid 2260 --
09-06 15:07:40.089 1911-2217/? E/AudioMixer: MOON > checkSEC_PCM ++ 1
09-06 15:07:40.849 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 ++
09-06 15:07:40.849 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 --
09-06 15:07:40.849 1911-2181/? E/AudioPolicyService: getOutput() tid 2181 ++
09-06 15:07:40.849 1911-2181/? E/AudioPolicyService: getOutput() tid 2181 --
09-06 15:07:40.849 1911-2260/? E/AudioPolicyService: getOutput() tid 2260 ++
09-06 15:07:40.849 1911-2260/? E/AudioPolicyService: getOutput() tid 2260 --
09-06 15:07:40.859 1911-2217/? E/AudioMixer: MOON > checkSEC_PCM ++ 1

**Comment by dumganhar** [comment]
It seems that some system errors appeared.
Could you provide more informations? 
e.g.
- The Android Version of your device?
- The logcat output

> then it stop.

What do you mean `stop`, is it freezing?

**Comment by Dauch** [comment]
The Android Version of my device:
![image](https://cloud.githubusercontent.com/assets/5201160/18265573/f7c4364a-7448-11e6-8017-3825c567a936.png)

[log.txt](https://github.com/cocos2d/cocos2d-x/files/456168/log.txt)
and stop just stop playing. music stop.

**Comment by dumganhar** [comment]
Are you sure that you're using v3.13?
I could not find any keywords of v3.13.
And did you use `SimpleAudioEngine` to play audio? If so, how about trying to use `AudioEngine` instead and test again?

**Comment by Dauch** [comment]
Yes, of cource I using 3.13, I use `SimpleAudioEngine` as beyong
ok, I will try to use `AudioEngine`.

**Comment by Dauch** [comment]
I used `AudioEngine`, it didn't cause stop playing problem. But it still keep throwing those err but is running is ok, do you know what's going on? @dumganhar 

09-06 21:40:40.905 31770-31770/? W/native_eup: empty
09-06 21:40:40.945 2314-2411/? E/NotificationService: Ignoring notification with icon==0: Notification(pri=0 contentView=com.kingroot.kinguser/0x10900aa vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null]) tickerText=null contactCharSeq=null when=1473169240938 threadId=0
09-06 21:40:41.260 1911-2260/? W/AwesomePlayer: couldn't get userdata - Weather
09-06 21:40:41.260 1911-2260/? W/AwesomePlayer: couldn't get userdata - Authorization 
09-06 21:40:41.260 1911-2260/? W/AwesomePlayer: couldn't get userdata - SnapShot 
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 ++
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 --
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 ++
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 --
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 ++
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 --
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 ++
09-06 21:40:41.270 1911-1856/? E/AudioPolicyService: getOutput() tid 1856 --
09-06 21:40:41.295 1911-2217/? E/AudioMixer: MOON > checkSEC_PCM ++ 1
09-06 21:40:41.365 1911-31787/? E/OMXCodec: [OMX.google.vorbis.decoder] err = -1011
09-06 21:40:41.830 1911-31818/? E/OMXCodec: [OMX.google.vorbis.decoder] err = -1011
09-06 21:40:41.855 1911-31677/? E/OMXCodec: [OMX.google.vorbis.decoder] err = -1011
09-06 21:40:43.905 2314-2472/? W/PowerManagerService: Timer 0x3->0x3|0x1
09-06 21:40:50.325 1911-26781/? E/OMXCodec: [OMX.google.vorbis.decoder] err = -1011
09-06 21:40:51.565 32389-32389/? E/ActivityThread: Failed to find provider info for com.seven.provider.email
09-06 21:40:58.955 2314-2651/? E/Watchdog: !@Sync 7197
09-06 21:41:36.385 25632-25632/? E/MtpService: In MTPAPP onReceive:android.intent.action.BATTERY_CHANGED
09-06 21:41:36.385 25632-25632/? E/MtpService: battPlugged Type : 2
09-06 21:41:58.955 2314-2651/? E/Watchdog: !@Sync 7199
09-06 21:41:59.995 2314-2402/? W/AlarmManager: FACTORY_ON= 0
09-06 21:42:00.850 2314-2686/? W/AlarmManager: FACTORY_ON= 0
09-06 21:42:02.865 1911-26781/? E/OMXCodec: [OMX.google.vorbis.decoder] err = -1011
09-06 21:42:03.975 2314-2792/? W/AlarmManager: FACTORY_ON= 0
09-06 21:42:21.550 5963-5963/? E/dalvikvm: Could not find class 'android.app.Notification$Action$Builder', referenced from method android.support.v4.app.a.a
09-06 21:42:21.550 5963-5963/? W/dalvikvm: VFY: unable to resolve new-instance 55 (Landroid/app/Notification$Action$Builder;) in Landroid/support/v4/app/a;
09-06 21:42:21.550 5963-5963/? W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/j; (52)
09-06 21:42:21.550 5963-5963/? W/dalvikvm: Link of class 'Landroid/support/v4/app/j;' failed
09-06 21:42:21.550 5963-5963/? E/dalvikvm: Could not find class 'android.support.v4.app.j', referenced from method android.support.v4.app.a.a
09-06 21:42:21.550 5963-5963/? W/dalvikvm: VFY: unable to resolve new-instance 354 (Landroid/support/v4/app/j;) in Landroid/support/v4/app/a;
09-06 21:42:21.550 5963-5963/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/app/SharedElementCallback;)
09-06 21:42:21.555 5963-5963/? E/dalvikvm: Could not find class 'android.app.RemoteInput$Builder', referenced from method android.support.v4.app.a.a
09-06 21:42:21.555 5963-5963/? W/dalvikvm: VFY: unable to resolve new-instance 63 (Landroid/app/RemoteInput$Builder;) in Landroid/support/v4/app/a;
09-06 21:42:21.555 5963-5963/? W/dalvikvm: VFY: unable to resolve virtual method 837: Landroid/os/Bundle;.getBinder (Ljava/lang/String;)Landroid/os/IBinder;
09-06 21:42:21.555 5963-5963/? W/dalvikvm: DexOpt: resolve class illegal access: Landroid/support/v4/app/a; -> Landroid/app/Notification$Action;
09-06 21:42:21.555 5963-5963/? W/dalvikvm: VFY: unable to resolve virtual method 187: Landroid/app/Notification$Action;.getRemoteInputs ()[Landroid/app/RemoteInput;
09-06 21:42:21.555 5963-5963/? W/dalvikvm: VFY: unable to resolve instance field 16
09-06 21:42:21.575 5963-5963/? E/dalvikvm: Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.a.a
09-06 21:42:21.575 5963-5963/? W/dalvikvm: VFY: unable to resolve check-cast 621 (Landroid/transition/Transition;) in Landroid/support/v4/app/a;
09-06 21:42:21.575 5963-5963/? E/dalvikvm: Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.a.a
09-06 21:42:21.575 5963-5963/? W/dalvikvm: VFY: unable to resolve check-cast 621 (Landroid/transition/Transition;) in Landroid/support/v4/app/a;
09-06 21:42:21.590 5963-5963/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/app/SharedElementCallback;)
09-06 21:42:21.590 5963-5963/? W/dalvikvm: VFY: unable to resolve virtual method 82: Landroid/app/Activity;.setEnterSharedElementCallback (Landroid/app/SharedElementCallback;)V
09-06 21:42:21.590 5963-5963/? E/dalvikvm: Could not find class 'android.app.Notification$Action$Builder', referenced from method android.support.v4.app.a.a
09-06 21:42:21.590 5963-5963/? W/dalvikvm: VFY: unable to resolve new-instance 55 (Landroid/app/Notification$Action$Builder;) in Landroid/support/v4/app/a;
09-06 21:42:21.600 5963-5963/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/transition/Transition;)
09-06 21:42:21.600 5963-5963/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/transition/Transition;)
09-06 21:42:21.600 5963-5963/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/transition/Transition;)
09-06 21:42:21.600 5963-5963/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/transition/Transition;)
09-06 21:42:21.610 5963-5963/? E/dalvikvm: Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.a.a
09-06 21:42:21.610 5963-5963/? W/dalvikvm: VFY: unable to resolve check-cast 621 (Landroid/transition/Transition;) in Landroid/support/v4/app/a;
09-06 21:42:21.610 5963-5963/? E/dalvikvm: Could not find class 'android.transition.TransitionSet', referenced from method android.support.v4.app.a.a
09-06 21:42:21.610 5963-5963/? W/dalvikvm: VFY: unable to resolve check-cast 623 (Landroid/transition/TransitionSet;) in Landroid/support/v4/app/a;
09-06 21:42:21.610 5963-5963/? E/dalvikvm: Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.a.a
09-06 21:42:21.610 5963-5963/? W/dalvikvm: VFY: unable to resolve check-cast 621 (Landroid/transition/Transition;) in Landroid/support/v4/app/a;
09-06 21:42:21.615 5963-5963/? E/dalvikvm: Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.a.a
09-06 21:42:21.620 5963-5963/? W/dalvikvm: VFY: unable to resolve check-cast 621 (Landroid/transition/Transition;) in Landroid/support/v4/app/a;
09-06 21:42:21.620 5963-5963/? E/dalvikvm: Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.a.a
09-06 21:42:21.620 5963-5963/? W/dalvikvm: VFY: unable to resolve check-cast 621 (Landroid/transition/Transition;) in Landroid/support/v4/app/a;
09-06 21:42:21.620 5963-5963/? E/dalvikvm: Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.a.a

09-06 21:42:25.020 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 ++
09-06 21:42:25.020 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 --
09-06 21:42:25.020 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 ++
09-06 21:42:25.020 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 --
09-06 21:42:25.025 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 ++
09-06 21:42:25.025 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 --
09-06 21:42:25.025 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 ++
09-06 21:42:25.025 1911-8031/? E/AudioPolicyService: getOutput() tid 8031 --
09-06 21:42:25.040 1911-2217/? E/AudioMixer: MOON > checkSEC_PCM ++ 1
09-06 21:42:25.135 1911-6267/? E/OMXCodec: [OMX.google.vorbis.decoder] err = -1011
01-01 00:00:00.000 0-0/? E/Internal: device '4df187fd01e0afaf' not found

**Comment by dumganhar** [comment]
I don't know why the system output this logs. We just use the standard `OpenSLES` API Android provides. So if there're no side-effects, just keep on.

**Comment by Dauch** [comment]
sorry for delay, pls close it. @dumganhar
