### ISSUE TITLE
migrate sprite used in cocos2d-x-lite to cocos2d-x

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#16535]
The requirement is from cocos creator lua support, sprite used in cocos2d-x-lite need to be migrated into cocos2d-x repo. The files is https://github.com/cocos-creator/cocos2d-x-lite/blob/develop/cocos/editor-support/creator/CCScale9Sprite.h and https://github.com/cocos-creator/cocos2d-x-lite/blob/develop/cocos/editor-support/creator/CCScale9Sprite.cpp.
@ricardoquesada @dualface @minggo Which name should be used in cocos2d-x repo.

**Comment by minggo** [comment]
@dabingnn i think Sprite already support scale9 feature. Why need this class? @zilongshanren am i  wrong?

**Comment by zilongshanren** [comment]
@minggo  Sprite class doesn't support Slice-9 feature ATM, but `ui::Scale9Sprite` does support this feature. Maybe we could enhance the existing `ui::Scale9Sprite` class and keep back compatibility.

**Comment by minggo** [comment]
@zilongshanren sounds good to me. @dabingnn what's your opinion.

**Comment by dabingnn** [comment]
It is impossible to achieve the goal as @zilongshanren suggested. To keep backward compatibility and fulfill creator lua support. In creator, simple/sliced 9/tiled/filled are all sprites. Since we have paid much time to achieve the same goal in cocos2d-x-lite several month ago, but failed as last, I am opposed to do it again.

**Comment by ricardoquesada** [comment]
What is cocos2d-x-lite?

Adding sprite-9-slice in sprite sounds good to me.
Adding something similar to SpriteKit's `centerRect` could be a nice feature:
https://developer.apple.com/library/ios/documentation/GraphicsAnimation/Conceptual/SpriteKit_PG/Sprites/Sprites.html

**Comment by minggo** [comment]
cocos2d-x-lite is the custom cocos2d-x version of cocos2d-x used in cocos creator, it remove many components, such as 3d, cocos studio reader and so on, and it also adds some features needed by cocos creator.

> Adding sprite-9-slice in sprite sounds good to me.

Yep, it is good if @dabingnn wants to do it like this. But i think it just wants to add a file into cocos2d-x.

**Comment by ricardoquesada** [comment]
> But i think it just wants to add a file into cocos2d-x.

we should avoid doing that. it adds "bloat-ness" to the engine

**Comment by minggo** [comment]
@dabingnn please move it to `cocos/scripting/lua-bindings/cocos-creator`. You should create the `cocos-creator` folder.

**Comment by dabingnn** [comment]
https://github.com/cocos2d/cocos2d-x/pull/16600

**Comment by minggo** [comment]
@ricardoquesada as creator cpp support is starting, and these files are needed for cpp too, so i think it is ok to move the file to `cocos/editor-support/cocos-creator`. Please take a look, thanks.

**Comment by ricardoquesada** [comment]
@minggo thanks. I'll take a look. For the moment I don't need them, but most probably because I haven't added support for those features yet.
