### ISSUE TITLE
Memory leak in AudioPlayer.mm

### ISSUE THREAD

**Issue by nicolechen819** [cocos2d/cocos2d-x#16547]
- cocos2d-x version:3.13

If set _isDestroyed = true in rotateBufferThread function, then AudioPlayer::destroy() will return at the beginning. Which will cause memory leak.

**Comment by dumganhar** [comment]
Which object would be leaked? How did you test it?

**Comment by nicolechen819** [comment]
I use xcode Instruments to find the leak. Instruments does not point out what is leaked clearly. I found out by tracing code.

**Comment by dumganhar** [comment]
So you find the leak by reviewing the code?
Which object do you think is leaked?

**Comment by nicolechen819** [comment]
So I think memory need to release in AudioPlayer::destroy() will cause leak, i.e. _rotateBufferThread. Because AudioPlayer::destroy() return at the beginning.

**Comment by dumganhar** [comment]
@nicolechen819 , you should be right.
Marked it to be resolved at v3.14. Thank you.

**Comment by dumganhar** [comment]
@nicolechen819 , fixed it at https://github.com/cocos2d/cocos2d-x/pull/16556.
Please check again. I could not write a test case for this patch since AudioPlayer is an internal class.

**Comment by nicolechen819** [comment]
Thanks, leaks is gone.
