### ISSUE TITLE
how to prevent frame half drop (60 -> 30)

### ISSUE THREAD

**Issue by cinakyn** [cocos2d/cocos2d-x#16550]
- cocos2d-x version: 3.12
- devices test on: iPhone6, iPhone4, iPhone4s, etc...
- developing environments
  - NDK version: none
  - Xcode version: 7.3.1
  - VS version: none
  - brower type and version: none

Steps to Reproduce:
1. make high cpu load
2. frame drops to 30 during about 5 seconds.

---

Hi, when I test my game, There's some section which uses 90% ~ 100% of cpu because of loading process. after that peak, fps drops from 60 into 30 and last during about 5 seconds. but there's no cpu load after loading process. how to prevent this drop?

**Comment by ricardoquesada** [comment]
not sure... could you please post the code to reproduce it?
It could be a bug in cocos2d-x or in your code... or something else.

**Comment by cinakyn** [comment]
@ricardoquesada 
I typed simple codes like this, but can't reproduce issue.
So I need to inspect more precisely and will open issue again.

```
    if (_duration < 30)
    {
        // make high cpu load.
        auto start = std::chrono::system_clock::now();
        auto end = std::chrono::system_clock::now();
        while (std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() < 100)
        {
            end = std::chrono::system_clock::now();
        }

        _duration += dt;
    }
    else if (_duration > 31)
    {
       // small cpu load
        auto start = std::chrono::system_clock::now();
        auto end = std::chrono::system_clock::now();
        while (std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() < 10)
        {
            end = std::chrono::system_clock::now();
        }
        if (dt > 0.03)
        {
            CCLOG("fps drop!!");
        }
    }
```
