### ISSUE TITLE
cocos2dx 3.12 and 3.13.1 device orientation

### ISSUE THREAD

**Issue by dirtyshadowss** [cocos2d/cocos2d-x#16565]
Hello,
when i create New Project with version 3.12, 3.13 and 3.13.1 i have this:

Landscape:
![06993cd2707c4c6d55b6774f7e4622618716550e](https://cloud.githubusercontent.com/assets/22153658/18443537/09746840-791e-11e6-8156-1bb89908eccb.PNG)
and Portrait:
![0f4502b69ccc2d7b8dc6d9226c79ef2cb0976edb](https://cloud.githubusercontent.com/assets/22153658/18443570/1a437ef4-791e-11e6-9a5e-a54ab4177e03.PNG)
My appdelegate.cpp is standart creating, only change 
designResolutionSize = cocos2d::Size(960, 640);
and
ResolutionPolicy::EXACT_FIT;

This issue is not fix the problem

[https://github.com/cocos2d/cocos2d-x/issues/16485]
- cocos2d-x version: 3.13.1
- devices test on:Iphone 4S IOS 7.0.4
- developing environments
  - NDK version: iOS 9.2
  - Xcode version: 7.2.1

**Comment by ricardoquesada** [comment]
Either it is already fixed, or something is wrong with your example. I tried with v3 branch (HEAD) and this is the result after using EXACT_FIT AND 960x640 as designed resolution.

<img width="480" alt="screen shot 2016-09-14 at 5 13 49 pm" src="https://cloud.githubusercontent.com/assets/232330/18534333/c6167304-7a9e-11e6-9d4a-506b46194886.png">

**Comment by dirtyshadowss** [comment]
Hello ricardo,
i don't have problem with iphone simulator with IOS 9.2 toо, the problem is IOS 7.0.3 on real device (iphone 4S). For me is no problem to upgrade my device to IOS 9.3 but when going time to production deployment whats should be minimum IOS system requirement (7.1, 8.0, 8.1).   Is  Cocos2d-x Runtime Requirements for IOS 7.0+ is right or must be highter?

**Comment by ricardoquesada** [comment]
yep. I tested also on a real device: iPhone 4S + iOS 8.3 and it worked Ok.
As of Xcode 8, the minimum deployment target is iOS 8.

**Comment by dirtyshadowss** [comment]
Thanks man,
install unsigned versions of iOS is hard, maybe try to install iOS 8 or stay on 3.11.1. It is better to change  Cocos2d-x Runtime Requirements on official github page. Thanks for solve the problem.

**Comment by MrCapone** [comment]
https://github.com/cocos2d/cocos2d-x/pull/15792 this pull request caused the problem.

**Comment by bouc0277** [comment]
Is this still being fixed in 3.14?

**Comment by minggo** [comment]
it is fixed

**Comment by bouc0277** [comment]
on 3.14? I am still seeing this on 3.13.1

**Comment by minggo** [comment]
Yep, i will be in v3.14 as the `Milestone` is marked as v3.14. And you can refer to the above PR that you can apply to your engine.
