### ISSUE TITLE
[js-bindings] unconfirmed undefined behavior

### ISSUE THREAD

**Issue by bryonglodencissp** [cocos2d/cocos2d-x#16583]
- cocos2d-x version: v3

Steps to Reproduce:
1. On line number [792](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/manual/ScriptingCore.cpp#L792) & [800](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/manual/ScriptingCore.cpp#L800) of [ScriptingCore.cpp](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/manual/ScriptingCore.cpp) the memory pointed to by `second` may be deleted twice. After calling `delete it->second;` the first time, if (by any chance), `delete it->second;` is called again, it's undefined behavior.
2. Can somebody else confirm or rebut it? 
3. If this is confirmed, the patch may be to set `it->second= NULL;` after the first `delete`.

**Comment by ricardoquesada** [comment]
I don't think it is possible to occur, since after the first delete, it will call `filename_script.erase()`
