### ISSUE TITLE
 ImageView used  loadtexture() with etc, the alpha is wrong!

### ISSUE THREAD

**Issue by huangzhentao** [cocos2d/cocos2d-x#16603]
- cocos2d-x version:3.13.1
- devices test on:all
- developing environments
  - NDK version:
  - Xcode version:
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. ImageView used png file first
2. then loadtexture() with etc support alpha

**Comment by huangzhentao** [comment]
I think  after loadTexture() ,it must call "_imageRenderer->setState(_imageRenderer->getState());"
to update GLProgramState

**Comment by huangzhentao** [comment]
![image](https://cloud.githubusercontent.com/assets/5028674/18779058/e34c9432-81a9-11e6-8147-ae7f0c6ef17b.png)
in UIScale9Sprite.cpp
maybe use "this->setState(_brightState);"   more better.  And fix all Scale9Sprite problem about alpha.
Thinks @halx99

**Comment by halx99** [comment]
@huangzhentao  Thanks for your feedback, I post a PR to fix this issue.

**Comment by minggo** [comment]
Thanks @halx99
