### ISSUE TITLE
crash --->xcode report :EXC_BAD_ACCESS in this line (function : fillVerticesAndIndices in CCRender) memcpy(&_verts[_filledVertex], cmd->getVertices(), sizeof(V3F_C4B_T2F) * cmd->getVertexCount());

### ISSUE THREAD

**Issue by FastGitHub** [cocos2d/cocos2d-x#16602]
- cocos2d-x version: 3.13.1
- devices test on: iOS 9.3.5
- developing environments
  - NDK version:
  - Xcode version:7.3
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. 
2.

**Comment by minggo** [comment]
how to reproduce it？

**Comment by FastGitHub** [comment]
Sorry,This is question of Spine.  Fix the crash already!

**Comment by FastGitHub** [comment]
@minggo Sorry,This is question of Spine. Fix the crash already!
