### ISSUE TITLE
The App crashes when using HttpClient

### ISSUE THREAD

**Issue by LouisChen79** [cocos2d/cocos2d-x#16618]
- cocos2d-x version: cocos2d-x-3.13
- devices test on: hTC Desire 600
- developing environments
  - NDK version: android-ndk-r10d
  - Xcode version:
  - VS version:
  - brower type and version:

Steps to Reproduce:
1.  The app crashes at at line 716 of HttpClient-android.cpp, the app runs on hTC Desire600 and gets the data from a tomcat server. The root cause is that system got a nullptr of messageInfo when executing "strcpy(responseMessage, messageInfo);" 
2. It is better to check the pointer's address before executing strcpy.
   if (nullptr != messageInfo)
   {// To avoid crash in some mobile phone.
       strcpy(responseMessage, messageInfo);
       free(messageInfo);
   }

**Comment by markchou** [comment]
Thanks!

**Comment by dumganhar** [comment]
The latest code has checked the `messageInfo`.
Please refer to https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/HttpClient-android.cpp#L706
So I closed this issue. Thanks for your feedback.

**Comment by LouisChen79** [comment]
Hi Markchou and Dumganhar,
    Thank you for your effort. 
Louis
