### ISSUE TITLE
Defining CC_USE_PHYSICS to 1 by default is wrong

### ISSUE THREAD

**Issue by antidotcb** [cocos2d/cocos2d-x#16628]
- cocos2d-x version: 3.13.1

I use cocos2dx with **only** Box2D.

So I disabled default use of `chipmunk, bullet, recast` via adding following configuration options to my project `CMakeLists.txt`:

```
SET( USE_SOURCES_EXTERNAL ON CACHE BOOL "Use some libraries from cocos2dx externals" )
SET( USE_CHIPMUNK OFF CACHE BOOL "Turn off default ChipMunk (2D physics)" )
SET( USE_BULLET OFF CACHE BOOL "Turn off Bullet (3d physics)" )
SET( USE_RECAST OFF CACHE BOOL "Turn off Recast (3d pathfinding)" )
SET( USE_BOX2D ON CACHE BOOL "Turn on Box2D for 2D physics" )

```

cocos2dx library compiling is OK.
my project compiling is OK.

But, when I try to use default camera object from any scene, I got SEGFAULT.

```
auto camera = cocos2d::Director::getInstance()->getRunningScene()->getDefaultCamera();
auto position = camera->getPosition();
```

My "small" investigation (8 hrs) lead me to `cocos2d::Node` (parent class of`cocos2d::Scene`).

I found out that there is a block of code, covered with `#ifdef CC_USE_PHYSICS`:

```
#if CC_USE_PHYSICS
    PhysicsBody* _physicsBody; 
    ...
#endif
```

Because `USE_CHIPMUNK` is set to `OFF` in my configuration, cocos2dx cmake module defines `CC_USE_PHYSICS` to `0`, **add_definitions(-DCC_USE_PHYSICS=0)** (see `cmake\Modules\SetCompilerOptions.cmake`):

```
    # definitions for chipmunk
    if (USE_CHIPMUNK)
        add_definitions(-DCC_ENABLE_CHIPMUNK_INTEGRATION=1)
        if (IOS OR MACOSX)
            # without this chipmunk will try to use apple defined geometry types, that conflicts with cocos
            add_definitions(-DCP_USE_CGPOINTS=0)
        endif()
    else()
        add_definitions(-DCC_USE_PHYSICS=0)
    endif()
```

So cocos2d library is compiled with `CC_USE_PHYSICS=0` and with absent field `_physicsBody` in `cocos2d::Node` class definition. 

My project compiles with undefined CC_USE_PHYSICS.
(BTW I don't think it's good practice to add any library related definitions to my project.)

Let's look into `cocos/base/ccConfig.h`: 

```
/*\* Use physics integration API. */
# ifndef CC_USE_PHYSICS
# define CC_USE_PHYSICS 1
# endif
```
So in my project cocos2d config defines `CC_USE_PHYSICS` to `1`.

That's why my declaration of class is different from declaration of class cocos2d library was compiled with.
That leads to `sizeof(PhysicsBody*)` offset for **all** member fields in **all** classes that are inherited from `cocos2d::Node`, resulting in accessing wrong memory.

**I would be glad if you could change the way CC_USE_PHYSICS is defined, or in best get rid of it.** 
I didn't come up with any good idea, it's up to you of course to figure out best possibilities.
At least you can add a comment to cocos2d cmake about _the need_ to define CC_USE_PHYSICS at project, when user disables Chipmunk usage.
It can save a lot of time to many folks around.
It's wasn't that easy to understand what was going on in first place. And newbie developers can stuck at all.

P.S. As for me, you can provide users with some variable (i.e. `CC_CXX_FLAGS`), so users project can update theirs `CMAKE_CXX_FLAGS`.

**Comment by drelaptop** [comment]
define `USE_* ` in cmake will case conflict with ccConfig.h, https://github.com/cocos2d/cocos2d-x/pull/19139 have improved this

**Comment by drelaptop** [comment]
the issue is same with https://github.com/cocos2d/cocos2d-x/issues/18914

```C++
#if CC_USE_PHYSICS
    PhysicsBody* _physicsBody; 
    ...
#endif
```
