### ISSUE TITLE
FMOD issues in linux

### ISSUE THREAD

**Issue by Joilnen** [cocos2d/cocos2d-x#16627]
- cocos2d-x version: 3.13.1
- devices test on:  computer (running slackware linux)
- developing environments
  - gcc 5.3.0, cmake 3.5.0

Steps to Reproduce:
1. Try to execute audio examples of cpp-tests 
Error output error:
Ready for GLSL
Ready for OpenGL 2.0
Console: listening on  0.0.0.0 : 5678
FMOD: SystemI::init                  : FMOD Ex Version: 00042817
FMOD: SystemI::init                  : maxchannels = 32, flags = 00000000, extradriverdata = (nil)
FMOD: SystemI::close                 : 
FMOD: SystemI::close                 : Stop all sounds
FMOD: SystemI::close                 : Remove miscllaneous DSP stuff.
FMOD: SystemI::close                 : done.

FMOD: OutputOSS::init                : Initializing.
FMOD: OutputOSS::init                : Initialized.
FMOD: SystemI::init                  : Set up software engine
FMOD: OutputOSS::setDeviceParams     : bits = 16 channels = 2 speed = 48000 bufferlen = 4096
FMOD: OutputOSS::setDeviceParams     : Buffersize = 00001000
FMOD: OutputOSS::setDeviceParams     : Fragment setting = 08x
FMOD: Thread::initThread             : Initializing OSS Mixer.  priority 1
FMOD: Thread::initThread             : - Stacksize 0.  Stack pointer (nil) : usesemaphore = 0 : sleeptime = 0
FMOD: Thread::callback               : \* OSS Mixer started
FMOD: Thread::initThread             : done.
FMOD: SystemI::init                  : Set up emulated output
FMOD: SystemI::init                  : create the channel pool
FMOD: SystemI::init                  : Set up streamer
FMOD: Thread::initThread             : Initializing FMOD stream thread.  priority 2
FMOD: Thread::initThread             : - Stacksize 49152.  Stack pointer (nil) : usesemaphore = 0 : sleeptime = 10
FMOD: Thread::callback               : \* FMOD stream thread started
FMOD: Thread::initThread             : done.
FMOD: SystemI::init                  : done

FMOD: SystemI::createSoundInternal   : filename = /home/joilnen/cocos2d-x_devel/my/build/bin/cpp-tests/Resources/background.ogg : mode 00000001
FMOD: SystemI::createSoundInternal   : 18 codecs found.  Scan all until one succeeds
FMOD: CodecTag::openInternal         : attempting to open ID3 or ASF tags..
FMOD: Codec::release                 : 
FMOD: Plugin::release                : (0x359e780)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecCDDA::openInternal        : attempting to open as CDDA..
FMOD: Codec::release                 : 
FMOD: Plugin::release                : (0x359e780)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecFSB::openInternal         : attempting to open as FSB..
FMOD: CodecFSB::openInternal         : Header check failed.  Not an FSB
FMOD: Codec::release                 : 
FMOD: CodecFSB::closeInternal        : 
FMOD: CodecFSB::closeInternal        : done
FMOD: Plugin::release                : (0x359e780)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecVAG::openInternal         : attempting to open as VAG..
FMOD: CodecVAG::openInternal         : 'VAG' ID check failed [Ogg]
FMOD: Codec::release                 : 
FMOD: Plugin::release                : (0x359e780)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecWav::openInternal         : attempting to open as WAV..
FMOD: Codec::release                 : 
FMOD: Plugin::release                : (0x359e780)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecOggVorbis::openInternal   : attempting to open as OGG..
FMOD: SystemI::createSoundInternal   : Format has 0 subsounds.
FMOD: SystemI::createSoundInternal   : Create as FMOD_CREATESAMPLE
FMOD: SystemI::createSoundInternal   : creating subsound 0/0
FMOD: SystemI::createSample          : mode 00000041 length 353664 samples, lengthbytes 89234
FMOD: SystemI::createSample          : subsamples = 1, channels = 1
FMOD: SystemI::createSample          : subsample 0.  output = 0x3545830
FMOD: SystemI::createSample          : mSoftware = 0x3545830
FMOD: OutputSoftware::createSample   : lengthpcm 353664, lengthbytes 89234, channels 1, format 2, mode 00000049
FMOD: OutputSoftware::createSample   : done
FMOD: SystemI::createSample          : done
FMOD: SystemI::createSoundInternal   : No name found in file, use filename.
FMOD: SystemI::createSoundInternal   : done.  OpenState now = FMOD_OPENSTATE_READY.

FMOD: SystemI::createSoundInternal   : filename = /home/joilnen/cocos2d-x_devel/my/build/bin/cpp-tests/Resources/effect1.wav : mode 00000001
FMOD: SystemI::createSoundInternal   : 18 codecs found.  Scan all until one succeeds
FMOD: CodecTag::openInternal         : attempting to open ID3 or ASF tags..
FMOD: Codec::release                 : 
FMOD: Plugin::release                : (0x35d5a50)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecCDDA::openInternal        : attempting to open as CDDA..
FMOD: Codec::release                 : 
FMOD: Plugin::release                : (0x35d5a50)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecFSB::openInternal         : attempting to open as FSB..
FMOD: CodecFSB::openInternal         : Header check failed.  Not an FSB
FMOD: Codec::release                 : 
FMOD: CodecFSB::closeInternal        : 
FMOD: CodecFSB::closeInternal        : done
FMOD: Plugin::release                : (0x35d5a50)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecVAG::openInternal         : attempting to open as VAG..
FMOD: CodecVAG::openInternal         : 'VAG' ID check failed [RIF]
FMOD: Codec::release                 : 
FMOD: Plugin::release                : (0x35d5a50)
FMOD: Plugin::release                : done
FMOD: Codec::release                 : done
FMOD: CodecWav::openInternal         : attempting to open as WAV..
FMOD: CodecWav::parseRIFF            : chunk : id fmt  size 16
FMOD: CodecWav::parseRIFF            : offset = 28 / 10018
FMOD: CodecWav::parseRIFF            : chunk : id data size 9981
FMOD: CodecWav::parseRIFF            : offset = 10018 / 10018
FMOD: CodecWav::openInternal         : mSrcFormat->wFormatTag = 1
FMOD: CodecWav::openInternal         : mSrcFormat->nChannels = 1
FMOD: CodecWav::openInternal         : mSrcFormat->nSamplesPerSec = 11025
FMOD: CodecWav::openInternal         : mSrcFormat->nAvgBytesPerSec = 11025
FMOD: CodecWav::openInternal         : mSrcFormat->nBlockAlign = 1
FMOD: CodecWav::openInternal         : mSrcFormat->wBitsPerSample = 8
FMOD: CodecWav::openInternal         : mSrcFormat->cbSize = 0
FMOD: SystemI::createSoundInternal   : Format has 0 subsounds.
FMOD: SystemI::createSoundInternal   : Create as FMOD_CREATESAMPLE
FMOD: SystemI::createSoundInternal   : creating subsound 0/0
FMOD: SystemI::createSample          : mode 00000041 length 9981 samples, lengthbytes 9981
FMOD: SystemI::createSample          : subsamples = 1, channels = 1
FMOD: SystemI::createSample          : subsample 0.  output = 0x3545830
FMOD: SystemI::createSample          : mSoftware = 0x3545830
FMOD: OutputSoftware::createSample   : lengthpcm 9981, lengthbytes 9981, channels 1, format 1, mode 00000049
FMOD: OutputSoftware::createSample   : done
FMOD: SystemI::createSample          : done
FMOD: SystemI::createSoundInternal   : No name found in file, use filename.
FMOD: SystemI::createSoundInternal   : done.  OpenState now = FMOD_OPENSTATE_READY.

./cpp-tests: symbol lookup error: ./cpp-tests: undefined symbol: _ZN4FMOD14ChannelControl9setPausedEb

**Comment by Rubonnek** [comment]
Have you tried using the included prebuilt library at: ${COCOS_ROOT}/external/linux-specific/fmod/prebuilt/${ARCH}/libfmod.so? ARCH is either "32-bit" or "64-bit" depending on your system.

That's the library I'm currently using in Arch Linux and it works.

**Comment by Joilnen** [comment]
Yes, i figured out that because I was using local lib, but even with cocos2d dependencies I can't run sounds now Im getting different error messages:
./cpp-tests 
Ready for GLSL
Ready for OpenGL 2.0
Console: listening on  0.0.0.0 : 5678
shm_open() failed: Permission denied
FMOD error! (51) Error initializing output device.
FMOD error! (67) This command failed because System::init or System::setDriver was not called.
sound effect in background.ogg could not be preload
FMOD error! (67) This command failed because System::init or System::setDriver was not called

**Comment by Rubonnek** [comment]
You are missing `pulseaudio`. I had that exact error some time back when I tried to play sounds without pulseaudio installed.

**Comment by slackmoehrle** [comment]
We have had some issues where users have had to make a few symlinks to get everything working but that was for compiling. I think you need `pulseaudio` as @Rubonnek has stated. You are running Slackware and it is very minimal. Distros like Ubuntu have this already installed.

**Comment by ocrest** [comment]
> I think you need pulseaudio as @Rubonnek has stated.

I think it would be better to simply change [this line](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/audio/linux/AudioEngine-linux.cpp#L66) in AudioEngine-linux.cpp:

``` diff
diff --git a/cocos/audio/linux/AudioEngine-linux.cpp b/cocos/audio/linux/AudioEngine-linux.cpp
index 40ed2f0..4d7a3a6 100644
--- a/cocos/audio/linux/AudioEngine-linux.cpp
+++ b/cocos/audio/linux/AudioEngine-linux.cpp
@@ -63,7 +63,7 @@ bool AudioEngineImpl::init()
     result = FMOD::System_Create(&pSystem);
     ERRCHECKWITHEXIT(result);

-    result = pSystem->setOutput(FMOD_OUTPUTTYPE_PULSEAUDIO);
+    result = pSystem->setOutput(FMOD_OUTPUTTYPE_AUTODETECT);
     ERRCHECKWITHEXIT(result);

     result = pSystem->init(32, FMOD_INIT_NORMAL, 0);
```

instead of installing PulseAudio. In my case (Debian with ALSA) this fixed the problem.

**Comment by minggo** [comment]
The PR looks good to me, thanks.
