### ISSUE TITLE
Upgrade Box2D to latest version

### ISSUE THREAD

**Issue by mogemimi** [cocos2d/cocos2d-x#16644]
- cocos2d-x version: v3.13.1
- developing environments
  - Xcode version: Xcode 8.0

Steps to Reproduce:
1. Build libcocos2d project with Xcode, then the following warnings are generated.

```
external/Box2D/Common/b2Math.h:59:17: declaration shadows a field of 'b2Vec2' [-Wshadow]
external/Box2D/Common/b2Math.h:59:28: declaration shadows a field of 'b2Vec2' [-Wshadow]
external/Box2D/Common/b2Math.h:150:17: declaration shadows a field of 'b2Vec3' [-Wshadow]
external/Box2D/Common/b2Math.h:150:28: declaration shadows a field of 'b2Vec3' [-Wshadow]
external/Box2D/Common/b2Math.h:150:39: declaration shadows a field of 'b2Vec3' [-Wshadow]
external/Box2D/Common/b2Draw.h:28:18: declaration shadows a field of 'b2Color' [-Wshadow]
external/Box2D/Common/b2Draw.h:28:29: declaration shadows a field of 'b2Color' [-Wshadow]
external/Box2D/Common/b2Draw.h:28:40: declaration shadows a field of 'b2Color' [-Wshadow]
external/Box2D/Collision/b2CollideCircle.cpp:141:11: declaration shadows a local variable [-Wshadow]
external/Box2D/Dynamics/b2Island.cpp:315:14: declaration shadows a local variable [-Wshadow]
external/Box2D/Dynamics/Joints/b2WheelJoint.cpp:144:12: declaration shadows a local variable [-Wshadow]
```

These warnings seem to have already been fixed in the latest Box2D that is hosted on github at https://github.com/erincatto/Box2D. I also tried to replace the old files with new ones which are downloaded from github into `external/Box2D`, and it works fine without any compiler warnings.

So could you please update Box2D to the latest master version?
Kindly consider.

**Comment by dumganhar** [comment]
Is there a release tag for Box2D? Or does it mean `master` branch of https://github.com/erincatto/Box2D is stable enough?

**Comment by mogemimi** [comment]
At the moment, Box2D v2.3.2 not yet officially released. So if you will attempt to update now, we can use latest HEAD on master branch in progress (not stable), or waiting for stable release.

**Comment by dumganhar** [comment]
@mogemimi , thanks. 
It's better to wait the stable box2d version (2.3.2) to be released, then we could update it. :)

**Comment by mogemimi** [comment]
@dumganhar Thank you for considering my request! :heart:

**Comment by minggo** [comment]
it is updated to latest version: 2.3.1, and use prebuilt version: https://github.com/cocos2d/cocos2d-x/pull/18422

**Comment by mogemimi** [comment]
Thank you for updating! :+1:
