### ISSUE TITLE
Generation of scripting/lua/cocos2dx_support/LuaCocos2d.cpp is unclear

### ISSUE THREAD

**Issue by 9re** [cocos2d/cocos2d-x#1666]
I have read the description in https://github.com/cocos2d/cocos2d-x/blob/gles20/tools/tolua%2B%2B/README

and by using tolua++-1.0.92(which is the same version as in the line 3 of https://raw.github.com/cocos2d/cocos2d-x/gles20/scripting/lua/cocos2dx_support/LuaCocos2d.cpp)

I cannot make the same LuaCocos2d.cpp by

$ ant -buildfile build_macosx.xml

instead it generates LuaCocos2d.cpp with many diffs like

 static int tolua_collect_CCAnimationFrame (lua_State\* tolua_S)
 {
  CCAnimationFrame\* self = (CCAnimationFrame*) tolua_tousertype(tolua_S,1,0);
-    Mtolua_delete(self);
-    return 0;
+       delete self;
+       return 0;
 }

---

@@ -5609,9 +5534,7 @@ static int tolua_Cocos2d_CCArray_createWithObject00(lua_State\* tolua_S)
   CCObject\* pObject = ((CCObject_)  tolua_tousertype(tolua_S,2,0));
   {
    CCArray_ tolua_ret = (CCArray_)  CCArray::createWithObject(pObject);
-    int nID = (tolua_ret) ? (int)tolua_ret->m_uID : -1;
-    int_ pLuaID = (tolua_ret) ? &tolua_ret->m_nLuaID : NULL;
-    toluafix_pushusertype_ccobject(tolua_S, nID, pLuaID, (void_)tolua_ret,"CCArray");
+   tolua_pushusertype(tolua_S,(void_)tolua_ret,"CCArray");
   }
  }

I made some modification on ccLanguageType for supporting japanese(https://github.com/cocos2d/cocos2d-x/pull/1665) and generated LuaCocos2d.cpp but most of diffs are unintended so I have to git add --patch and select the changes that I really wanted.

I want to know the proper way to do it.

**Comment by dualface** [comment]
For mac, please use tolua++.Mac.zip.
For windows, use tolua++.zip.

Use build.php generate valid LuaCocos2d.cpp

```
$ cd tools/tolua++
$ php build.php
```

**Comment by 9re** [comment]
Thanks!

Isn't there linux version or source code version for tolua++?

**Comment by godyZ** [comment]
@9re  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2665
