### ISSUE TITLE
there is a problem for the method addCustomHandler of ScriptHandlerMgr

### ISSUE THREAD

**Issue by toreinkun** [cocos2d/cocos2d-x#16674]
- cocos2d-x version:3.13.1

If i use method addObjectHandler first , the vecHandlers for the object is not empty. Then i use addCustomHandler, the handleType just  increment one , it will not bigger than HandlerType::EVENT_CUSTOM_BEGAN.

this is some code of addCustomHandler.

```
  if (_mapObjectHandlers.end() != iter)
    {
        vecHandlers = iter->second;
        handlerType = static_cast<HandlerType>((int)vecHandlers.back().first + 1);
    }
```

**Comment by minggo** [comment]
Sorry, what's the issue?

**Comment by toreinkun** [comment]
The handlerType in ScriptHandlerMgr::addObjectHandler will be in conflict with ScriptHandlerMgr::addCustomHandler.
In some case, they will replace each other, but it is not our hope.

**Comment by minggo** [comment]
Could you please provide a test case to reproduce it? Thanks.

**Comment by toreinkun** [comment]
There is no wrong in the engine code, but there is a hidden rule to use ScriptHandlerMgr.
I can't do this in my custom spine object, such as:

``` c++
LUA_FUNCTION handler1 = (  toluafix_ref_function(L,2,0));

ScriptHandlerMgr::getInstance()->addObjectHandler((void*)self, handler1, ScriptHandlerMgr::HandlerType::EVENT_SPINE_ANIMATION_START);

LUA_FUNCTION handler2 = (  toluafix_ref_function(L,3,0));

ScriptHandlerMgr::getInstance()->addCustomHandler((void*)self, handler2);

LUA_FUNCTION handler3 = (  toluafix_ref_function(L,4,0));

ScriptHandlerMgr::getInstance()->addObjectHandler((void*)self, handler3, 
ScriptHandlerMgr::HandlerType::EVENT_SPINE_ANIMATION_END);
```

Actually, by modifying ScriptHandlerMgr::HandlerType  to avoid use ScriptHandlerMgr::addCustomHandler.

**Comment by minggo** [comment]
Yep, it is designed like this. All well known event type should use addObjectHandler, if you have some  custom event, then you should all use addCustomHandler.

**Comment by panzhihao** [comment]
i can't all use addCustomHandler, because CCNode has used addObjectHandler.

**Comment by toreinkun** [comment]
I can't all use addCustomHandler, because some node like extension::ScrollView has used addObjectHandler. If i want to extend extension::ScrollView about script handler, i must add a new ScriptHandlerMgr::HandlerType for it. I don't think it is a nice designed, because i should not change the engine code, it will be harder to update engine.
