### ISSUE TITLE
code duplication in cocos2d-x / tools / tolua++

### ISSUE THREAD

**Issue by 9re** [cocos2d/cocos2d-x#1669]
ccLanguageType is defined twice.
one appears in
https://github.com/cocos2d/cocos2d-x/blob/gles20/tools/tolua%2B%2B/CCApplication.pkg

the other appears in
https://github.com/cocos2d/cocos2d-x/blob/gles20/tools/tolua%2B%2B/CCCommon.pkg

as a result,

the member of enum ccLanguageType such as kLanguageEnglish is exported for lua twice:

as you can find

tolua_constant(tolua_S,"kLanguageEnglish",kLanguageEnglish);

twice in
https://raw.github.com/cocos2d/cocos2d-x/gles20/scripting/lua/cocos2dx_support/LuaCocos2d.cpp

This is not a problem itself but it makes maintenance for the list of supported language a little bit bothering :(

**Comment by dualface** [comment]
thanks, fixed.

https://github.com/cocos2d/cocos2d-x/pull/1694

**Comment by 9re** [comment]
thanks!!
