### ISSUE TITLE
source code lipng issues ??

### ISSUE THREAD

**Issue by abdel3** [cocos2d/cocos2d-x#16715]
Hello i have a source code (see the attach files) i want to reskin it and im wonderring if it include libpng error please if somone have an idea about it let me know 
![issuse](https://cloud.githubusercontent.com/assets/22892605/19446656/16a72664-949a-11e6-9e28-ad3e1204a0b3.PNG)

thank you :)

**Comment by slackmoehrle** [comment]
Your question is inappropriate here. Please ask on our forums.
