### ISSUE TITLE
android-build.py doesn't work if Android API level 13 is not installed

### ISSUE THREAD

**Issue by apoluektov** [cocos2d/cocos2d-x#16729]
cocos2d-x/build$ ./android-build.py cpp-empty-test
cocos compile -p android -s /Users/poluektov/devel/playground/cocos2d/cocos2d-x/build/../tests/cpp-empty-test --ndk-mode debug --app-abi armeabi-v7a
Building mode: debug
Using Eclipse project : /Users/poluektov/devel/playground/cocos2d/cocos2d-x/tests/cpp-empty-test/proj.android
**The directory 'android-13' can't be found in ANDROID_SDK_ROOT/platforms, please use --ap to set needed API level**
Build dynamic library for project [ /Users/poluektov/devel/playground/cocos2d/cocos2d-x/build/../tests/cpp-empty-test ] fails!

I addressed this issue in this PR: https://github.com/cocos2d/cocos2d-x/pull/16727

(I also changed a bunch of other things in the script, like replacing deprecated OptionParser with ArgumentParser, PEP8-zing the code, and some other small improvements).

**Comment by dumganhar** [comment]
> The directory 'android-13' can't be found in ANDROID_SDK_ROOT/platforms, please use --ap to set needed API level

But we suggest developers to use the API level same as which `Cocos` targets (currently, api 13).
It's because our QA team will do a lot of testing on that api level. If you use other api level, it may cause some strange compatibility issues.

**Comment by apoluektov** [comment]
@dumganhar,

1) According to android-build.py documentation, "This script is mainy used for building tests built-in with cocos2d-x."
In my view, allowing to build and run _tests_ on another API level is the first step to finding any compatibility issues.

2) Please take a look at my PR: https://github.com/cocos2d/cocos2d-x/pull/16727
It doesn't _change_ default API level (it is still 13), it merely _allows_ to override one.

**Comment by apoluektov** [comment]
Besides, if API level 13 is recommended, perhaps we should mention it somewhere in the documentation? I haven't found any mentions of on cocos2d-x.org website.

**Comment by dumganhar** [comment]
Yes, we need to make a documentation for this.
@minggo , where shall we put this to?

**Comment by apoluektov** [comment]
@dumganhar @minggo As the PR has been merged, I created a separate issue to address the documentation of the recommended Android API Level: https://github.com/cocos2d/cocos2d-x/issues/16752
