### ISSUE TITLE
GlobalZOrder with same values change order .

### ISSUE THREAD

**Issue by Kotaiba** [cocos2d/cocos2d-x#16726]
- cocos2d-x version:3.13.1
- devices test on: ios 9, ios 10 , iphone 6 , iphone 7 . (more frequent on ios 9)
- developing environments
  - Xcode version:8.0

Steps to Reproduce:
1. Set same globalzorder to 2 sprites .
2. The order of the sprites keep changing with movement or on heavy load .

please see the attached video it will show how the ground and other sprites changes order ..
[Untitled.zip](https://github.com/cocos2d/cocos2d-x/files/541531/Untitled.zip)

**Comment by minggo** [comment]
I think you can change to the codes
```c++
void RenderQueue::sort()
{
    // Don't sort _queue0, it already comes sorted
    std::sort(std::begin(_commands[QUEUE_GROUP::TRANSPARENT_3D]), std::end(_commands[QUEUE_GROUP::TRANSPARENT_3D]), compare3DCommand);
    std::sort(std::begin(_commands[QUEUE_GROUP::GLOBALZ_NEG]), std::end(_commands[QUEUE_GROUP::GLOBALZ_NEG]), compareRenderCommand);
    std::sort(std::begin(_commands[QUEUE_GROUP::GLOBALZ_POS]), std::end(_commands[QUEUE_GROUP::GLOBALZ_POS]), compareRenderCommand);
}
```
to
```c++
void RenderQueue::sort()
{
    // Don't sort _queue0, it already comes sorted
    std::stable_sort(std::begin(_commands[QUEUE_GROUP::TRANSPARENT_3D]), std::end(_commands[QUEUE_GROUP::TRANSPARENT_3D]), compare3DCommand);
    std::stable_sort(std::begin(_commands[QUEUE_GROUP::GLOBALZ_NEG]), std::end(_commands[QUEUE_GROUP::GLOBALZ_NEG]), compareRenderCommand);
    std::stable_sort(std::begin(_commands[QUEUE_GROUP::GLOBALZ_POS]), std::end(_commands[QUEUE_GROUP::GLOBALZ_POS]), compareRenderCommand);
}
```
Because std::sort can not guarantee that the order of equal elements is to be preserved.

Edit: The codes is in `CCRenderer.cpp`

**Comment by minggo** [comment]
@Kotaiba have you fixed the issue?

**Comment by Kotaiba** [comment]
@minggo  yes the issue seems to be fixed .Thank you

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17156
