### ISSUE TITLE
(SimpleAudioEngine) Effects could not be resumed after entering foreground

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16733]
- cocos2d-x version: 3.13.1
- devices test on: iphone 6
- developing environments
  - NDK version: N/A
  - Xcode version: 8.0
  - VS version: N/A
  - browser type and version: N/A

Steps to Reproduce:
1. Play a looping background music & a looping effect in HelloWorldLayer

``` C++
    SimpleAudioEngine::getInstance()->playBackgroundMusic("fonts/background.mp3", true);
    SimpleAudioEngine::getInstance()->playEffect("fonts/effect1.wav", true);
```
1. Press `home` button
2. Go back to foreground by double click `home` button and select the game.
3. The effect may not be resumed.

**Comment by pablorealini** [comment]
Hi @dumganhar any comments on how to fix this issue? We are experimenting this. Also if there is an incoming message or call the background music don’t resume.

**Comment by pablorealini** [comment]
I realize our problem is with AudioEngine and not with SimpleAudioEngine.

**Comment by minggo** [comment]
Please use AudioEngine instead.
