### ISSUE TITLE
ADDED SAMPLE CODE:Added SceneA to a SceneB, would got twice touch events 

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#16738]
- cocos2d-x version:3.10
- devices test on:ios
- developing environments
  - NDK version:r10c
  - Xcode version:
  - VS version:
  - browser type and version:

Steps to Reproduce:
1. 
2.

**Comment by dumganhar** [comment]
Any reproduce step or demo?

**Comment by liuyi** [comment]
@dumganhar 
Tested in latest cocos2dx(JSB), the bug still occured.

[app.js.txt](https://github.com/cocos2d/cocos2d-x/files/557582/app.js.txt)
1\ JUST Create a empty project: cocos new sampleTest.
2\ REPLACE "src/app.js" with my file:app.js 
3\Compile and run it, click the screen in anywhere.

Here is bug  code:

Create and add a cc.Scene to current scene,
    Click the screen,onTouchBegan would fired twice.
    You can test it in the latest cocos2dx(3.13.1)

```
twiceEventBug: function() {
    var _self = this;
    var scene = new cc.Scene();
    var layer = new HelloWorldLayer();
    scene.addChild(layer);
    _self.addChild(scene); //BUG FIRED POINT

    _self._touchListenr = cc.eventManager.addListener({
        event: cc.EventListener.TOUCH_ONE_BY_ONE,
        swallowTouches: false, //BUG FIRED POINT
        onTouchBegan: function(touch, event) {
            console.log("twiceEventBug: touched!!!"); //fired twice.
        }

    }, _self);
}
```

**Comment by dumganhar** [comment]
Don't add a scene to another scene.
Game should only have one scene in current scene-graph.
If you wish to change to another scene, please use `cc.director.runScene(anotherScene);`.
