### ISSUE TITLE
Fix bug   It does not work properly Rect (float x, float y, float width, float height )

### ISSUE THREAD

**Issue by Sluysarev** [cocos2d/cocos2d-x#16744]
Rect (float x, float y, float width, float height )

cocos2d-x version: 3.11 worked fine
cocos2d-x version: 3.13.1 is not working properly

---

```
cocos2d-x version: Cocos2d-x 3.13.1 
VS version: 2013
```

**Comment by dumganhar** [comment]
What's the problem in 3.13.1?

**Comment by Sluysarev** [comment]
```
auto s = Director::getInstance()->getWinSize();
auto gameSprite = Sprite::create("image.png", Rect(0, 0, 80, 110));
gameSprite->setPosition(Vec2(s.width / 2, s.height / 2));
this->addChild(gameSprite);

```

cocos2d-x version: 3.13.1  shows a picture more than    80, 110

**Comment by dumganhar** [comment]
Thanks. Could you upload the image.png you used?

**Comment by Sluysarev** [comment]
![image](https://cloud.githubusercontent.com/assets/23049273/19681680/116370d0-9ab3-11e6-8c9c-a23cce505396.png)

**Comment by dumganhar** [comment]
@Sluysarev, 

> cocos2d-x version: 3.13.1 shows a picture more than 80, 110

Could you upload correct and incorrect screenshots?

**Comment by dumganhar** [comment]
I guess you wanna show the first image in the atlas, you need to pass a `point coordinate` base on design resolution rather than pixel coordinate to Sprite::create.
If you only know the pixel size of picture in the atlas, you could use `CC_RECT_PIXELS_TO_POINTS` to change it to points.

So 

``` c++
auto gameSprite = Sprite::create("fonts/image.png", CC_RECT_PIXELS_TO_POINTS(Rect(0, 0, 80, 110)));
```

will work for you.

**Comment by Sluysarev** [comment]
Thanks for the help, it worked as I wanted
