### ISSUE TITLE
"builing" typo

### ISSUE THREAD

**Issue by sean-mcmanus** [cocos2d/cocos2d-x#16743]
cmake/Modules/CocosBuildHelpers.cmake
set(BUILDING_STRING "It appears you are builing natively for ${SYSTEM_STRING} with ${COMPILER_STRING}")

There's a typo: "builing" should be "building". It's not immediately obvious that the typo comes from Cocos itself so users of Visual Studio may believe the typo comes from Visual Studio's CMake system.

**Comment by minggo** [comment]
fixed in #16813
