### ISSUE TITLE
lua中的data 经过 HttpClient-android.cpp中 sendRequest传递的bytearray到JAVA层中是乱码

### ISSUE THREAD

**Issue by yhhwatl** [cocos2d/cocos2d-x#16767]
- cocos2d-x version:3.6
- devices test on:RedMi-note3
- developing environments
  - NDK version:r10c
  - Android studio version:2.2.2

Steps to Reproduce:
lua中的data 经过 HttpClient-android.cpp中 sendRequest传递的bytearray到JAVA层中是乱码

**Comment by minggo** [comment]
@yhhwatl could you please provide some code to reproduce it? And please use english instead, then developers all over the world can join the discussion. Thanks.

**Comment by liuyi** [comment]
maybe got an high bit or low bit problem when send byte from one language to another one?
