### ISSUE TITLE
"The system cannot find the path specified" error when running cocos from a relative path

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#16761]
- cocos2d-x version: latest git code, v3 branch
- devices test on: Windows 10
- developing environments: Python 2.7.11

Steps to Reproduce:
1. Run `cocos` using a relative path when creating a new project. For example:
   
   ```
   cd %COCOS_GIT_ROOT%\tests\cpp-tests
   ..\..\tools\cocos2d-console\bin\cocos new -l cpp %HOMEPATH%\Desktop\latest_git_hello_world
   ```

You'll get the error:

```
    [Error 3] The system cannot find the path specified
```

**Comment by Rubonnek** [comment]
I'm not sure if running cocos from a relative path like above is supported.

**Comment by minggo** [comment]
You should run `setup.py` in cocos2d-x root to set up environment variables. Then you can just invoke `cocos` everywhere
