### ISSUE TITLE
EditBox doesn't show text when editing in Mac version (but no problem in iOS)

### ISSUE THREAD

**Issue by amuseamuse** [cocos2d/cocos2d-x#16779]
- cocos2d-x version: 3.13 , 3.13.1
- devices test on: MacBook Pro 13 inch 2010 and iMac 27 inch 2010 (Mac OS Sierra)
    (Note: this issue doesn't appear before the Mac OS Sierra I upgraded from former os, and the issue appears after I completely reinstall Mac OS Sierra)
- developing environments
    Mac (but not ios) in Mac OS Sierra

Steps to Reproduce:
1 .  create a EditBox

    bool HelloWorld::init(){
    EditBox* gameIdEditBox=EditBox::create(Size(480,180),Scale9Sprite::create());
    this->addChild(gameIdEditBox);
    gameIdEditBox->setInputMode(ui::EditBox::InputMode::SINGLE_LINE);
    gameIdEditBox->setReturnType(ui::EditBox::KeyboardReturnType::SEND);
    gameIdEditBox->setAnchorPoint(Vec2::ZERO);
    gameIdEditBox->setText("abc");
    return true;
    }

![e01](https://cloud.githubusercontent.com/assets/11567495/19843023/a7fa6c24-9f59-11e6-93f5-0ab3817ba562.png)

it can show the text when it is not editing

2 . when click the edit box and start to edit, the EditBox doesn't show the editing text:

![e02](https://cloud.githubusercontent.com/assets/11567495/19843059/e5a1c586-9f59-11e6-801c-65e65902e359.png)

3 . when edit finished, the text appear again, and it seems the text can change normally:

![e03](https://cloud.githubusercontent.com/assets/11567495/19843076/0ab73f40-9f5a-11e6-9bc1-e738358de392.png)

Note 1: I tried to solve the problem by setNeedsLayer in CCApplication-mac.mm

    int Application::run()
    {
        initGLContextAttrs();
        if(!applicationDidFinishLaunching())
        {
            return 1;
        }
    
        long lastTime = 0L;
        long curTime = 0L;
    
        auto director = Director::getInstance();
        auto glview = director->getOpenGLView();
        NSWindow* window = glview->getCocoaWindow();
        [[window contentView] setWantsLayer:YES];
        .
        .
        .

This time the EditBox can show normally but it contains a lot of OpenGL errors:

Before Editing:
![e04](https://cloud.githubusercontent.com/assets/11567495/19843169/c4631ef0-9f5a-11e6-95ae-d3d2ad449d80.png)

During Editing:
![e05](https://cloud.githubusercontent.com/assets/11567495/19843178/cb4d772e-9f5a-11e6-8088-b86c70471a18.png)

,and error logs after adding

        NSWindow* window = glview->getCocoaWindow();
        [[window contentView] setWantsLayer:YES];

in CCApplication-mac.mm:

2016-10-31 10:43:58.347564 TestEditBox-desktop[861:159412] [General] ERROR: Setting <GLFWContentView: 0x608000140160> as the first responder for window <GLFWWindow: 0x6000001e0200>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fffcf48e9a4 -[NSWindow _validateFirstResponder:] + 566
	1   AppKit                              0x00007fffcec7f9eb -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fffced2766a -[NSWindow _realMakeFirstResponder:] + 406
	3   AppKit                              0x00007fffced27480 -[NSWindow makeFirstResponder:] + 123
	4   TestEditBox-desktop                 0x00000001006a7720 _glfwPlatformCreateWindow + 656
	5   TestEditBox-desktop                 0x00000001006a238a glfwCreateWindow + 474
	6   TestEditBox-desktop                 0x00000001005fd8ad _ZN7cocos2d10GLViewImpl12initWithRectERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_4RectEfb + 685
	7   TestEditBox-desktop                 0x00000001005fe272 _ZN7cocos2d10GLViewImpl14createWithRectERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_4RectEfb + 258
	8   TestEditBox-desktop                 0x0000000100001912 _ZN11AppDelegate29applicationDidFinishLaunchingEv + 242
	9   TestEditBox-desktop                 0x0000000100656069 _ZN7cocos2d11Application3runEv + 57
	10  TestEditBox-desktop                 0x0000000100001f06 main + 54
	11  TestEditBox-desktop                 0x00000001000016a4 start + 52
)

{
	gl.supports_OES_map_buffer: false
	gl.supports_vertex_array_object: true
	cocos2d.x.version: cocos2d-x-3.13.1
	gl.vendor: ATI Technologies Inc.
	gl.supports_PVRTC: false
	gl.renderer: ATI Radeon HD 5670 OpenGL Engine
	cocos2d.x.compiled_with_profiler: false
	cocos2d.x.build_type: DEBUG
	cocos2d.x.compiled_with_gl_state_cache: true
	gl.max_texture_size: 16384
	gl.supports_ETC1: false
	gl.supports_BGRA8888: false
	gl.max_texture_units: 16
	gl.supports_OES_packed_depth_stencil: false
	gl.supports_ATITC: false
	gl.supports_discard_framebuffer: false
	gl.supports_NPOT: true
	gl.version: 2.1 ATI-1.46.22
	gl.supports_S3TC: true
	gl.supports_OES_depth24: false
}

setReturnType not implemented
[Edit text] content size = (480.000000, 180.000000)
[Edit text] content size = (480.000000, 180.000000)
setReturnType not implemented
setReturnType not implemented
OpenGL error 0x0506 in xxx/TestEditBox/cocos2d/cocos/renderer/CCFrameBuffer.cpp applyFBO 448

FrameBuffer Status Error 33305
[Edit text] content size = (480.000000, 180.000000)
OpenGL error 0x0506 in xxx/TestEditBox/cocos2d/cocos/renderer/CCRenderer.cpp saveRenderState 158

.
.
.
(many other similar statements)

Note 2: This issue seems appear in a newly restored Mac OS Sierra only, not the Mac OS Sierra that upgraded from previous OS X (if the EditBox works before)

**Comment by zilongshanren** [comment]
@amuseamuse 
I also noticed this issue and I have no idea why it behaviors like this.
In the previous version of MacOS X, the Editbox works well.

I'm trying to fix it these days, I will post my new findings here.

Thanks for reporting.

**Comment by zilongshanren** [comment]
It is a bug with glfw:  https://github.com/glfw/glfw/commit/967e837c73f0e0d7f9f27c7f6bb1aaa1d55dae54

I will consider to upgrade the GLFW extension

**Comment by zilongshanren** [comment]
@amuseamuse 
Weird... I have patched the mac os 10.12 fix of glfw, I could get ride of the error message, but EditBox still can't display cursor...

**Comment by zilongshanren** [comment]
@amuseamuse  
I have created a issue in GLFW:  https://github.com/glfw/glfw/issues/892

Still don't know how to find a workaround...

**Comment by zilongshanren** [comment]
@amuseamuse 

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/126

I have made a patch to resolve this issue.

could you help to test it ?

If you move the GLFW window from one monitor to another, you might also need try this PR:

https://github.com/cocos2d/cocos2d-x/pull/16785

**Comment by Monisha123Ramesh** [comment]
hello @zilongshanren , @dumganhar , @minggo 
I am doing a game for Mac store using cocos2d-js. I am in need of help with edit box issue.
Edit box works weird in Mac. When the window size is changed (i.e.,maximised or minimised) the edit box position changes and it comes back to its original position until its been clicked. I am sharing the screenshots. Can you please have a check on it and provide me a solution as I'm stuck on this issue for long..

Mac version is 10.13.2

Initial:

<img width="1374" alt="screen shot 2017-12-28 at 3 07 51 pm" src="https://user-images.githubusercontent.com/28771417/34407163-eb49ca20-ebe2-11e7-9064-0fb7edf86b81.png">



After maximising

<img width="1774" alt="screen shot 2017-12-28 at 3 08 18 pm" src="https://user-images.githubusercontent.com/28771417/34407165-ee359d7c-ebe2-11e7-9c50-e267cd8f80e1.png">



Thank you.
