### ISSUE TITLE
Crash when call Director::getInstance()->restart()

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#16782]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. call Director::getInstance()->restart();

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/CCDirector.cpp#L1137

```
    auto script = ScriptEngineManager::getInstance()->getScriptEngine();
    if (script) {
        script->sendEvent(&scriptEvent);
    }
```

**Comment by minggo** [comment]
How can you invoke this function? It is protected, and is to be used for JSB.

**Comment by ghost** [comment]
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/CCDirector.h#L339

It's public api.
