### ISSUE TITLE
gles20 branch crashes when using particles

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/cocos2d-x#1678]
For some reason, cocos2d-x is crashing when using particles on Android.
Seems to work OK on iOS.

How to reproduce it:
- download gles20 branch from cocos2d-x (as of today)
- Update the submodule
- Run the Particle Test
- Crash

**Comment by minggo** [comment]
Did you run TestCpp?
I have just tested, but no problem.

My device is G10.

Best Regards
Minggo

**Comment by ricardoquesada** [comment]
Yes, I run TestCpp con a Samsung III

**Comment by ricardoquesada** [comment]
@minggo , surith sent you a PR for it:
https://github.com/cocos2d/cocos2d-x/pull/1686

**Comment by minggo** [comment]
Yep, i will test it.

Best Regards
Minggo
