### ISSUE TITLE
Difference in Spine default blend function behavior between native and webGL.

### ISSUE THREAD

**Issue by DavidDeSimone** [cocos2d/cocos2d-x#16786]
There is a difference in the logic that handles blend functions for spine skeletons between native and WebGL.

We can see in https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/editor-support/spine/SkeletonRenderer.cpp#L238 that we have 3 options, ADDITIVE, MULTIPLY, and SCREEN. If none of these are chosen, we will either get GL_ONE/GL_ONE_MINUS_SRC_ALPHA, or GL_SRC_ALPHA/GL_ONE_MINUS_SRC_ALPHA depending on if we have premultiplied alpha. However, if we  examine https://github.com/cocos2d/cocos2d-html5/blob/e10208255f9eae2c25db5e04e395f4258406dbcd/extensions/spine/CCSkeletonWebGLRenderCmd.js#L96, we see that the default behavior is to use the underlying node's blend func. 

This can cause visual difference between cocos2d-js and cocos2d-x on native. It seems to me that native should match web's functionality, and if we hit the default case, we use the node's current blend func. 

Since SkeletonRenderer is under the spine licence, I wanted to bring this issue to the cocos2d-x team and get their blessing before I submit a PR to spine.

**Comment by DavidDeSimone** [comment]
@ricardoquesada do you have an opinion on this?

**Comment by ricardoquesada** [comment]
@DavidDeSimone I'm not sure about this. I think both implementations were developed by the Spine guys. I wouldn't know which one is the correct blending mode for spine, but it should be the same in both implementations.

**Comment by pandamicro** [comment]
We shouldn't use the underlying node's blend func by default, the default one should be additive, so should be the same as additive, cpp implementation is correct

**Comment by DavidDeSimone** [comment]
@pandamicro @ricardoquesada Makes sense to me. I will close this issue as @pandamicro has merged in https://github.com/cocos2d/cocos2d-html5/pull/3402
