### ISSUE TITLE
What's the logic of 'if( sizeof(Vec2) == sizeof(Vec2) ) '?

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16787]
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCDrawingPrimitives.cpp#L141

I can't understand this code, could some one explain this? Thanks.

**Comment by pyrosphere** [comment]
I checked the history for that line and it was originally a 32-bit/64-bit check that was lost over time with refactorings.

```
if( sizeof(Point) == sizeof(Vertex2F) )
if( sizeof(Point) == sizeof(Vector2) )
if( sizeof(Vector2) == sizeof(Vector2) )
if( sizeof(Vec2) == sizeof(Vec2) )
```

**Comment by dumganhar** [comment]
Thank you, @pyrosphere . I will check that why we used `if( sizeof(Point) == sizeof(Vertex2F) )` to detect 32bit or 64bit devices.

**Comment by dumganhar** [comment]
@pyrosphere 

I checked the code, found that that line was came from `cocos2d-iphone` (https://github.com/cocos2d/cocos2d-iphone-classic/blob/develop-v2/cocos2d/CCDrawingPrimitives.m#L126)

``` objective-c
#if defined(__LP64__) && __LP64__
# define CGFLOAT_TYPE double
# define CGFLOAT_IS_DOUBLE 1
# define CGFLOAT_MIN DBL_MIN
# define CGFLOAT_MAX DBL_MAX
#else
# define CGFLOAT_TYPE float
# define CGFLOAT_IS_DOUBLE 0
# define CGFLOAT_MIN FLT_MIN
# define CGFLOAT_MAX FLT_MAX
#endif

/* Definition of the `CGFloat' type and `CGFLOAT_DEFINED'. */

typedef CGFLOAT_TYPE CGFloat;

/* Points. */

struct CGPoint {
    CGFloat x;
    CGFloat y;
};
typedef struct CGPoint CGPoint;
```

On 64bit iOS devices, `CGPoint.x/y` is `double` (8 bytes).
It's `float` on 32bit iOS devices. So we need to check the 32/64 bit in cocos2d-iphone.

But in cocos2d-x, we don't use the system type (CGPoint) and we use `float` both for Vertex2F/Point/Vec2, therefore it's safe to remove this confused code.

**Comment by dumganhar** [comment]
@pyrosphere , I submitted a Pull Request here https://github.com/cocos2d/cocos2d-x/pull/16791

Please check it out.
