### ISSUE TITLE
cocos permission denied

### ISSUE THREAD

**Issue by ryojishimura** [cocos2d/cocos2d-x#16795]
- cocos2d-x version:
cocos2d-x-3.13.1
Cocos Console 2.1
- devices test on:
None
- developing environments
   - NDK version: r13
   - Xcode version: 8
   - VS version:
   - browser type and version: Chrome

Steps to Reproduce:

1. python setup.py
2. cocos -v

fixed by changing the permissions files.

chmod +x ~/.cocos2d-x-3.13.1/tools/cocos2d-console/bin/cocos

**Comment by minggo** [comment]
but i found it has correct permission

```
-rwxr-xr-x  1 minggo  staff    189 Oct 22 16:45 cocos
```

**Comment by nangsan** [comment]
Hi, minggo
same issue happened to me also I'm installing coco2d-x in Ubuntu.
cocos.py file has only [ -rw-rw-r-- Jul 20 14:27 ~/cocos2d-x-3.13.1/tools/cocos2d-console/bin/cocos] permission.
As @ryojishimura suggested I added execution permission, and it solved the issue.

**Comment by minggo** [comment]
It is strange, i reopen this issue.

**Comment by nangsan** [comment]
Thanks for the response,
And one more thing, when I tried to run a new project using _cocos run_ for android [ Android Studio ],
ndk-build was successful but while starting Gradle build I got permission denied.
Then I added the execute permission to the _gradlew_ file in proj.android-studio.
Again I started _cocos run_ this time all was fine and APK generated successfully.

**Comment by minggo** [comment]
close this one as there is nothing happen even i added permission for it.
