### ISSUE TITLE
 jsb.fileUtils.getStringFromFile cause crash when read big file.

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#16811]
- cocos2d-x version:3.10
- devices test on:android redmi note3
- developing environments
   - NDK version:r10e
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. some base code, such as hotupdate, create base folder etc. 
2. jsb.fileUtils.isFileExist("path to big json file") then crash

The crash not happen every time, but  occurred about  30%-50% .

Can we have a callback when read file?

**Comment by DavidDeSimone** [comment]
How big is the big JSON file here? 1MB? 1GB? 

It sounds like it may be an out of memory issue. Do you have a stack trace of the crash?

**Comment by liuyi** [comment]
Sorry , I confirmed  my crash come from encode AES string in javascript side. 
Maybe the file is too big, about 27KB. spent about 300MS.
So it crashed on some android devices.

But I really want a callback when read text file, because sometimes will read   json file more than 500KB-1M.

**Comment by dumganhar** [comment]
`jsb.fileUtils.isFileExist` should not cause crash and this function will not `read` the file indeed.
Therefore, I guess it's not an issue about big file. @liuyi Could you upload your json file and the crash stack? I will be glad to check it out.

**Comment by liuyi** [comment]
@dumganhar  
YES you are right! 
 This crash is come from my code which decode a text file that encrypt (AES encrypt) in javascript. It cost too much time in a frame(about 300MS).

This is another feature request:
I mean maybe jsb.fileUtils.getStringFromFile need a callback, type so fast, sorry!

**Comment by dumganhar** [comment]
@liuyi, that's another issue, please create another issue.
If this issue appears in your code, could you close this issue now? Thanks.
