### ISSUE TITLE
is it a bug on socket.io when client reconnect crash on android?

### ISSUE THREAD

**Issue by cnogo** [cocos2d/cocos2d-x#16829]
- cocos2d-x version: .13.1
- devices test on:   android (小米5)  only android 
- developing environments
   - NDK version: ndk-r11c
   - SDK API Level: android-19

Steps to Reproduce:
1. first let client connect server,   then server quit,  wait some times, android client crash
先让客户端连上服务器， 然后服务端退出，客户端启动重连过了一段时间就崩溃了

### the exception info as below:
11-10 18:01:18.421: E/URLConnection exception(8895): java.net.SocketTimeoutException: failed to connect to /192.168.1.245 (port 1234) after 30000ms
11-10 18:01:18.423: E/URLConnection exception(8895): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
11-10 18:01:18.423: E/URLConnection exception(8895): java.net.SocketTimeoutException: failed to connect to /192.168.1.245 (port 1234) after 30000ms
11-10 18:01:18.427: A/libc(8895): Fatal signal 6 (SIGABRT), code -6 in tid 8937 (GLThread 8842)

### the server demo:
```javascript
var io = require("socket.io");

var port = 1234;
var socket = io.listen(port);

socket.on('connection', newSock => {

    console.log("a new socket connection");

    newSock.on('disconnect', ()=> {
        console.log("socket disconnect");
    });
});

console.log("server start");
```

### The client Demo code:

```javascript
var SocketIO = SocketIO || window.io 

var HelloWorldLayer = cc.Layer.extend({

    sock: null,

    ctor:function () {
        this._super();
        var size = cc.winSize;
        var helloLabel = new cc.LabelTTF("Hello World", "Arial", 38);
        // position the label on the center of the screen
        helloLabel.x = size.width / 2;
        helloLabel.y = size.height / 2 + 200;
        // add the label as a child to this layer
        this.addChild(helloLabel, 5);

        this.initEx();

        return true;
    },

    initEx: function () {
        this.connect();
    },

    connect: function () {
        var uri = "ws://192.168.1.245:1234";

        this.sock = SocketIO.connect(uri);

        var self = this;

        cc.log("链接开始");

        this.sock.on("connect", function () {
            cc.log("链接成功：" + uri);
        });

        this.sock.on("disconnect", function () {
            cc.log("链接断开 3s 后重连");
            self.reconnect();
        });

        this.sock.on("error", function () {
            cc.log("链接错误 3s 后重连");
            self.reconnect();
        });
    },

    reconnect: function () {
        var self = this;
        setTimeout(function () {
            self.connect();
        }, 3000);
    }
});
```

**Comment by dumganhar** [comment]
Should refactor SocketIO implementation and add more test case for SocketIO.
Therefore, mark this issue to `next` milestone.
Relative issue: https://github.com/cocos2d/cocos2d-x/issues/17070

**Comment by tbwind** [comment]
发现这种情况下，cocos2dx的SIOClientImpl收到的握手http回复有问题。这应该是失败的请求，在安卓下isSucceed返回的是true
```
//if (!response->isSucceed())
if (!response->isSucceed() || statusCode != 200)//这里我改了
    {
        CCLOGERROR("SIOClientImpl::handshake() failed");
        CCLOGERROR("error buffer: %s", response->getErrorBuffer());

        for (auto& client : _clients)
        {
            client.second->getDelegate()->onError(client.second, response->getErrorBuffer());
        }
       //另外这里我觉得应该加句this->release();，不过不确定。这个this没有被添加到SocketIO的map里，也没有谁控制它重新握手，理论上已经是飞地了。
        return;
    }

```

**Comment by plutoo** [comment]
Reconnection does not cause a crash on the current version, @minggo
