### ISSUE TITLE
How do I use android studio 2.2 (cmake) compile and edit cocos2dx files  like xcode

### ISSUE THREAD

**Issue by abc20899** [cocos2d/cocos2d-x#16836]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by minggo** [comment]
Please refer to this PR https://github.com/cocos2d/cocos2d-x/pull/15676. We want Android Studio to support ndk-build ad before and currently Android Studio doesn't support it very well.

**Comment by abc20899** [comment]
https://github.com/chaoren/cocos2d-x/tree/cmake       does it not work？

**Comment by minggo** [comment]
please read the comments in the PR.

**Comment by abc20899** [comment]
thanks
