### ISSUE TITLE
highschool math mistake in radian2angle

### ISSUE THREAD

**Issue by samsonchen1989** [cocos2d/cocos2d-x#16837]
math mistake in [*cocos/scripting/lua-bindings/script/cocos2d/functions.lua*](https://github.com/cocos2d/cocos2d-x/blob/92af2b2b6f8acfd51226631cb54deb5813519e5d/cocos/scripting/lua-bindings/script/cocos2d/functions.lua)

```lua
local pi_div_180 = math.pi / 180
function math.angle2radian(angle)
    return angle * pi_div_180
end

local pi_mul_180 = math.pi * 180
function math.radian2angle(radian)
    return radian / pi_mul_180
end
```

**radian2angle** should be ```radian * 180 / math.pi``` but not ```radian / (math.pi * 180)```

**Comment by minggo** [comment]
Good catch, could you please send a PR?

**Comment by slackmoehrle** [comment]
I was in communication with this user via Twitter. They have said they might be able to submit a PR at a later date. Perhaps we should fix this ourselves. Thank you @samsonchen1989 for submitting this.
