### ISSUE TITLE
How to set lineHeight of labelTTF

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#16841]
- cocos2d-x version:3.10+
 
Can not find any api to set lineHeight or letter spacing etc.

Is there any method? I use cocos2d-js.
I found some code like below:

    /** Sets the line height of the Label.
     * @warning Not support system font.
     * @since v3.2.0
     */
    void setLineHeight(float height);

Thanks!

**Comment by dumganhar** [comment]
`setLineHeight` is defined in `cocos2d::Label` class but it's not in the `cocos2d::LabelTTF` which is a deprecated class. You could simply add that function and run `tools/tojs/genbindings.py` again to generate `setLineHeight` for `cocos2d::LabelTTF`.

@zilongshanren , is there any reason we don't export this function for LabelTTF?
I guess it's probably this function doesn't exist from v2.x and setLineHeight is a feature in Label class.

**Comment by zilongshanren** [comment]
@dumganhar 
Yes, I think so.

**Comment by liuyi** [comment]
Thanks your reply @zilongshanren  @dumganhar

 If cocos2d::LabelTTF is deprecated. Which Class I should choice? I need use system fonts to display user's content.

PS: I checked source code and found this method in CCDevice-ios.mm:

Data Device::getTextureDataForText(const char \* text, const FontDefinition& textDefinition, TextAlign align, int &width, int &height, bool& hasPremultipliedAlpha)

and 
static bool _initWithString(const char \* text, cocos2d::Device::TextAlign align, const char \* fontName, int size, tImageInfo\* info)

Maybe I need modify these files, But If I am wrong, Which Class I should use?

**Comment by zilongshanren** [comment]
@liuyi 
The method `setLineHeight` is indeed existed in cpp side, you might need to expose the cpp API to js layer, I will check this issue later and send a PR to resolve this issue.

**Comment by liuyi** [comment]
@zilongshanren
There is a setLineHeight in labelTTF, but it can not support system font as texture.
see this source code:
void Label::setLineHeight(float height)
{
    CCASSERT(_currentLabelType != LabelType::STRING_TEXTURE, "Not supported system font!");

```
if (_lineHeight != height)
{
    _lineHeight = height;
    _contentDirty = true;
}
```

}

I tracked source and found that cocos2dx just send the string to IOS API:NSStringDrawingContext 
 in  CCDevice-ios.mm.
you can check this method to get more infomation:

static CGSize _calculateStringSize(NSString *str, id font, CGSize *constrainSize)
{
    CGSize textRect = CGSizeZero;
    textRect.width = constrainSize->width > 0 ? constrainSize->width
    : 0x7fffffff;
    textRect.height = constrainSize->height > 0 ? constrainSize->height
    : 0x7fffffff;

```
CGSize dim;
if(s_isIOS7OrHigher){
    NSDictionary *attibutes = @{NSFontAttributeName:font};
    dim = [str boundingRectWithSize:textRect options:(NSStringDrawingOptions)
```

//send an empty value as context
(NSStringDrawingUsesLineFragmentOrigin) attributes:attibutes context:nil].size; 
    }
    else {
        dim = [str sizeWithFont:font constrainedToSize:textRect];
    }

```
dim.width = ceilf(dim.width);
dim.height = ceilf(dim.height);

return dim;
```

}

**Comment by zilongshanren** [comment]
@liuyi 
System font currently doesn't support lineHeight and it might be hard to implement this feature for all the supported platforms.

**Comment by liuyi** [comment]
@zilongshanren  
Yes, I tried modified code for IOS device, But hope we can add this feature to engine, at least IOS and Android. It's really useful.

**Comment by zilongshanren** [comment]
@liuyi 
Currently the label implementation is messy, we are planing to refactor the code and this feature request will be considered, thanks for your suggestions.
