### ISSUE TITLE
Black screen android

### ISSUE THREAD

**Issue by purepure** [cocos2d/cocos2d-x#16840]
- cocos2d-x version: v3
- devices test on: samsung s4
- developing environments
   - NDK version: android-ndk-r10e
   - Xcode version: 8.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

I use that version of cocos2dx:
branch: v3
commit b5de8ba
Merge: 9943c83 9c35ded
Author: minggo xiaoming.zhang@chukong-inc.com
Date: Mon Jul 18 15:01:10 2016 +0800

Simply I created a project of c++ then build. When I put this flag APP_ABI:= armeabi armeabi-v7a x86 in Application.mk file then build -> the game seem work normally, include sound effect, but black screen
I also tried to build only for armeabi-v7a architect, it work!, but build for all, it failed

**Comment by purepure** [comment]
Sorry for the delay!
I tried to rebuild my project with that version but i cannot reproduce that issue. There are too many error when i switch back to that version (after building failed, I tried to update, modified my environment) so I am so sorry for deliver nothing to you guy about that issue. 
The only thing is, I was build succeed with that version, but until this project, it fail me. The log of adb is only about AssetManager cannot load asset in asset path. (even I checked the apk, every asset is in there). 

That is the best I can do, hope this help

If you need any further information, dont hesitate to contact me

BR

**Comment by minggo** [comment]
Sorry, i can not catch your idea? So what's the issue, could you please help to reproduce the issue?

**Comment by purepure** [comment]
It mean, I cannot provide apk, log about that issue. The step to reproduce is create new project with above cocos version, then make build for android with flag: APP_ABI:= armeabi armeabi-v7a x86 in Application.mk

BR

**Comment by minggo** [comment]
I can not reproduce it on Nexus 5x(Android 6.0) with the commit(latest github codes)

```
commit 23b6d3b45b08469600f75dcf64d03903d81e9b2a
Merge: 5e6c30e 65f8c60
Author: 子龙山人 <guanghui8827@126.com>
Date:   Mon Nov 14 01:20:12 2016 -0800

    Merge pull request #258 from zilongshanren/upgrade-glfw

    upgrade glfw
```

**Comment by minggo** [comment]
Sorry, the commit is this one

```
commit 88f6825c4840beea4f18ac7a9c80ac403137f48c
Author: minggo <xiaoming.zhang@chukong-inc.com>
Date:   Fri Nov 18 09:28:01 2016 +0800

    reset stencil program when alpha threshold is set to 1 (#16858)
```
