### ISSUE TITLE
Add async file utils to cocos2d-x

### ISSUE THREAD

**Issue by DavidDeSimone** [cocos2d/cocos2d-x#16846]
Currently in cocos2d-x and cocos2d-js, we have functions like FileUtils::getStringFromFile, and jsb.fileUtils.getStringFromFile for interacting with the file system. These functions are synchronous, and performed on the main thread. This can be detrimental to performance. It can cause hitching and frame drops while loading data from the filesystem.

I suggest that we create asynchronous versions of these functions, that each take a callback. The operation will be completed off thread, and then call the callback on the main thread once complete. 

I think the best mechanism for managing the threading is to iterate on CCThreadPool, and pull that feature out of experimental, and bring it into the engine proper. 

I have been iterating on CCThreadPool, and have an iteration I would like to share for consideration. It can be found here: https://github.com/DavidDeSimone/cocos2d-x/blob/async-file-utils/cocos/platform/CCThreadPool.cpp. I have made major changes to this file that I would be happy to discuss/iterate on with other developers involved. 

I'd be curious what @dumganhar thinks of all of this.

**Comment by liuyi** [comment]
good job! I indeed need this feature.

**Comment by DavidDeSimone** [comment]
Update on this:

I have written async versions of each of the basic file operations in CCFileUtils, each taking a callback, and each done off thread. I am currently in the process of writing tests for all of this. I also need to make sure that the auto binding generator works properly for the new functions I've created. I hope to have a PR open next week for this feature.

**Comment by DavidDeSimone** [comment]
Closing this issue as the corresponding PR was merged.
