### ISSUE TITLE
Duplicate if-else branch in CCAutoPolygon.cpp

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#16854]
Running `cppcheck` against CCAutoPolygon.cpp shows the following:

```
[cocos/2d/CCAutoPolygon.cpp:425] -> [cocos/2d/CCAutoPolygon.cpp:419]: (style, inconclusive) Found duplicate branches for 'if' and 'else'.
```

Lines [423](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCAutoPolygon.cpp#L423) and [426](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCAutoPolygon.cpp#L426) are the same.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/16860
