### ISSUE TITLE
CURL have error compile for APP_PLATFORM := android-15

### ISSUE THREAD

**Issue by Limetris** [cocos2d/cocos2d-x#16863]
Hello!
I'm sorry for my bad english.

- cocos2d-x version: 3.13.1
- devices test on: Android 4.4.2
- developing environments
   - NDK version: r13b
   - VS version: 2015
   - Android API: 24

Steps to Reproduce:

1.  add variable in file **Application.mk** variable: `APP_PLATFORM := android-15`
2.  compile for android

I get error compile:

```
[armeabi] SharedLibrary  : libcocos2dcpp.so
<proj_dir>/proj.android-studio/../cocos2d/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'signal'
<proj_dir>/proj.android-studio/../cocos2d/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
<proj_dir>/proj.android-studio/../cocos2d/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
<proj_dir>/proj.android-studio/../cocos2d/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'tcgetattr'
collect2.exe: error: ld returned 1 exit status
```

**My solution:**

1. I get old commit in project `https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/`

```
d025d1f97e215b735cb319bedc7f877cd8f0b7d6
Author: zilongshanren <guanghui8827@126.com>
Date:   Wed Apr 6 11:42:33 2016 +0800

    upgrade libcurl to 7.48 and openssl to 1.02g
```

2. Then i replace folder **curl** for my project

Check please last version library curl in project cocos2d.
Thanks You!

**Comment by dumganhar** [comment]
I tried to build `cpp-empty-test` with cocos2d-x 3.13.1 + android-15 + android-ndk-r13b, it was compiled successfully.
I used `cocos compile -p android --ap=android-15` to compile.

**Comment by Limetris** [comment]
I'm sorry that did not specify.
I used `cocos run -p android --ap android-24 --android-studio` to compile.

**Comment by dumganhar** [comment]
@Limetris , I also used `cocos run -p android --ap android-24` to build an apk without any errors.
But i did it on macOS. What's your host OS?

**Comment by Limetris** [comment]
My OS Win10.
Perhaps this is a problem with the engine upgrade in our project.
Previous engine v3.9

**Comment by coolexp** [comment]
I got the same error,if use libcurl in the project.And i read the sample code, the samples in the cpp-test not use  curl in android platform,only in win32 platform.

use --ap=android-21 is ok,use --ap==android-19,get the error

Version details:
Cocos2d-x 3.13.1
Win10 64Bit 

Error info as below:
`C:/cocos/CocosGameLua/frameworks/runtime-src/proj.android/../../cocos2d-x/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'signal'
C:/cocos/CocosGameLua/frameworks/runtime-src/proj.android/../../cocos2d-x/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
C:/cocos/CocosGameLua/frameworks/runtime-src/proj.android/../../cocos2d-x/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
C:/cocos/CocosGameLua/frameworks/runtime-src/proj.android/../../cocos2d-x/external/curl/prebuilt/android/armeabi/libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'tcgetattr'
collect2.exe: error: ld returned 1 exit status
make: *** [obj/local/armeabi/libcocos2dlua.so] Error 1`

**Comment by dumganhar** [comment]
@coolexp, thanks for your feedback.
So I guess it's probably an issue of target sdk version.

@Limetris , could you figure out that how many api level you have installed? Could you make sure that you have installed `android-24`?

**Comment by dumganhar** [comment]
@coolexp , I also tried with android-19, but it was compiled successfully. :(
Anyway, I will try it on Windows and update the result here.

**Comment by coolapi** [comment]
@dumganhar did you enable curl in the project? Mabye you should enable libcurl in the project and write some function code to compile

My Project android.mk file as below:
.......
LOCAL_STATIC_LIBRARIES := cocos2d_lua_static
LOCAL_STATIC_LIBRARIES += cocos_curl_static


include $(BUILD_SHARED_LIBRARY)

$(call import-module,curl/prebuilt/android)
$(call import-module,scripting/lua-bindings/proj.android)

...
and my cpp code as below:
`#include "NetHelper.h"

#include "cocos2d.h"
#include <curl/curl.h>

using namespace cocos2d;

size_t NetHelper::writehtml(uint8_t* ptr, size_t size, size_t number, void *stream)
{

	CCLOG("%s", ptr);
	return size*number;
}
void NetHelper::get() {
	CURL *curl;
	curl = curl_easy_init();
}`

**Comment by dumganhar** [comment]
@coolapi, I used `tests/cpp-tests` for testing. `tests/cpp-tests` definitely uses all modules in cocos2d-x.

**Comment by coolapi** [comment]
@dumganhar i just read the sample code,found tests/cpp-tests disable libcurl at android platform

**Comment by dumganhar** [comment]
@coolapi, Oops, it's my fault. I didn't notice that `CurlTest` in `cpp-tests` was disabled.
Okay, I will try to use the way you provided to test it. Thanks.

**Comment by dumganhar** [comment]
@coolexp ,

I reproduced this issue with `android-19`, but `android-21` works fine.

@minggo , I remember that it's a bug of `android-19` target platform in ndk. Right?

**Comment by minggo** [comment]
I sent a PR to fix it https://github.com/cocos2d/cocos2d-x/pull/16882

**Comment by Limetris** [comment]
If it is still required

My `Application.mk`

```
APP_STL := gnustl_static

APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
APP_LDFLAGS := -latomic

APP_ABI := armeabi

ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif
APP_PLATFORM := android-15
```

My `project.properties`
```
target=android-24
```

I used `cocos run -p android --ap android-24 --android-studio` to compile.

**Comment by minggo** [comment]
> If it is still required

@Limetris what did you mean? Have you tried my PR?

**Comment by Limetris** [comment]
@minggo 
Thank you, I will check it, when i will have time.

**Comment by HHvarni** [comment]
generate apk file in android studio show error------>Error:error: ld returned 1 exit status
