### ISSUE TITLE
Hardcoded `compileSdkVersion` and `buildToolsVersion` at 'build.gradle'.

### ISSUE THREAD

**Issue by FrankStain** [cocos2d/cocos2d-x#16865]
Currently just wanted to test some code, but had stuck with incompatible versions of android build tools.
```
> A problem occurred configuring project ':libcocos2dx'.
  > The SDK Build Tools revision (22.0.1) is too low for project ':libcocos2dx'. Minimum required is 25.0.0
```
So that's how i found hardcoded values at 'build.gradle' of libcocos2dx:
https://github.com/cocos2d/cocos2d-x/blob/7e2fe05050c6fe88ea6cef5e39344d9a7546fc92/cocos/platform/android/libcocos2dx/build.gradle#L5
It happened cuz i always prefer to use most recent version of gradle and android build tools. But now i have to rollback the gradle and build tools versions what may affect the results of my tests.

So, the good practice in this case is using the extended variables of root project. Smth like this.
```
apply plugin: 'com.android.application'

android {
	if( project.ext.hasProperty( 'compileSdkVersion' ) ) {
		compileSdkVersion project.ext['compileSdkVersion']
	} else {
		compileSdkVersion 23
		// whine to user that the default value is set.
	}
	
	...
```
This code is guarded by checking the corresponded property exists, so it's safe.
I think, it would be great if this values will be configurable from root project.

**Comment by minggo** [comment]
Sound reasonable. How to modify it? I am not an expert of Android Studio.

**Comment by FrankStain** [comment]
So, i had tested it on my current version of cocos2d-x. I can make a PR if necessary, but only if it will take small time for me.

Real working code is (file - .../cocos/platform/android/libcocos2dx/build.gradle):
```
android {
    if(project.hasProperty('compileSdkVersion')) {
        compileSdkVersion project.compileSdkVersion
    } else {
        compileSdkVersion 22
    }

    if(project.hasProperty('buildToolsVersion')) {
        buildToolsVersion project.buildToolsVersion
    } else {
        buildToolsVersion '22.0.1'
    }
    ...
```

**Comment by FrankStain** [comment]
In addition.

Next code, which must be placed at `build.gradle` of root project, will cause the suggested feature to work.
```
...
allprojects {
    repositories {
        jcenter()
    }
	
    project.ext {
        compileSdkVersion	= 23
        buildToolsVersion	= "25.0.0"
        targetSdkVersion	= 23
        ...
```

**Comment by mars3142** [comment]
**buildToolsVersion** can now be removed from gradle file. As far as I know it's obsolete and the gradle build tools will find the right one.

**Comment by drelaptop** [comment]
Any official docs to describe it? 

and __buildToolsVersion__ isn't Hardcoded since 3.17 release, so I think it's a out-dated issue, this should be closed, what do you think @mars3142

**Comment by formatCvt** [comment]
@drelaptop official doc https://developer.android.com/studio/releases/gradle-plugin
`Build Tools 27.0.3 or higher. Keep in mind, you no longer need to specify a version for the build tools using the android.buildToolsVersion property—the plugin uses the minimum required version by default.`

**Comment by drelaptop** [comment]
finally, solved at https://github.com/cocos2d/cocos2d-x/pull/18952
