### ISSUE TITLE
editbox doesn't show cursor and input text in android

### ISSUE THREAD

**Issue by flyingkisser** [cocos2d/cocos2d-x#16864]
- cocos2d-x version:3.13.1
- devices test on: 乐视手机1
- developing environments
   - NDK version: r10e
   - Xcode version:
   - VS version:
   - browser type and version:
-android:5.0.2
Steps to Reproduce:

1. git clone https://github.com/cocos2d/cocos2d-x.git
./download-deps.py 
cd tests/js-tests
cocos run -p android

2. goto Extensions Test->EditBoxTest

3. click the fourth EditBox, 7 times in 10 I won't see the input cursor and inputed text.
![wechatimg1](https://cloud.githubusercontent.com/assets/8563538/20387706/6599458e-acfc-11e6-98e0-39834696bf18.png)

4.when click the down button in the soft keyboard, you will see the inputed text.
![wechatimg2](https://cloud.githubusercontent.com/assets/8563538/20387940/90017a20-acfd-11e6-84bc-8c5ae9d04f59.png)

**Comment by dumganhar** [comment]
@zilongshanren, could you please check this issue? Thanks.

**Comment by flyingkisser** [comment]
It's not easy to see this issue in Xiaomi's phone, but 1 in 20 times you still can see it. Very easy to show in LeTV's phone.

**Comment by zilongshanren** [comment]
@flyingkisser 
I can't find a LeTV's phone at the moment... Do you see any error message when click the EditBox?

**Comment by dumganhar** [comment]
What's the input method installed in your phone?

**Comment by flyingkisser** [comment]
I tried 10 times in my xiaomi 5 , this issues appears again. By logcat nothing  occurs.
my input app in xiaomi5 is sogo, in LeTV phone1 that is xunfei.

![1](https://cloud.githubusercontent.com/assets/8563538/20419914/9e0eb6f4-ad94-11e6-91c2-410a16782c7c.png)
![2](https://cloud.githubusercontent.com/assets/8563538/20419917/a5fa9e82-ad94-11e6-8f30-60e06775c62e.png)
![3](https://cloud.githubusercontent.com/assets/8563538/20419923/ac4a05e8-ad94-11e6-817a-ea2c03a4b883.png)

**Comment by flyingkisser** [comment]
any ideas about this issue?

**Comment by zilongshanren** [comment]
@flyingkisser 
I have fixed it, could you please give it a test?

**Comment by flyingkisser** [comment]
@zilongshanren sure, maybe I'll test it on this weekend.

**Comment by zilongshanren** [comment]
@flyingkisser thanks
