### ISSUE TITLE
为什么 一帧执行两次renderer->render();

### ISSUE THREAD

**Issue by linyouhappy** [cocos2d/cocos2d-x#16887]
- cocos2d-x version:3.8
在CCScene文件 第209行
renderer->render();
在CCDirector文件 第309行
_renderer->render();
这样子，不消耗性能吗？

**Comment by linyouhappy** [comment]
注释掉 CCScene里面的renderer->render();，运行正常。未发现异常

**Comment by minggo** [comment]
the codes in Director::draw() is 
```c++
...
if (_notificationNode)
    {
        _notificationNode->visit(_renderer, Mat4::IDENTITY, 0);
    }

    if (_displayStats)
    {
        showStats();
    }
    _renderer->render();
```
It is used to draw status and notification nodes.
