### ISSUE TITLE
outdated CMakeLists.txt on templates

### ISSUE THREAD

**Issue by MrCapone** [cocos2d/cocos2d-x#16900]
`CMakeLists.txt` in `templates` not been updated for over a year only received minor fixes. But `CMakeLists.txt` from `cpp-empty-test` much better and has more features. I created gist with sample `CMakeLists.txt` based on  `cpp-empty-test/CMakeLists.txt` but modified for use in `templates` 
https://gist.github.com/MrCapone/ccdc1826cb7362086107e8096bfe6f90
It's only for cpp, but it can be used with small changes in js and lua. 
It can:
build and run project on linux/Cmake+gcc
build and run valid .app on macOS/Cmake+clang
generate valid Xcode project for macOS
generate valid Visual Studio project for win32

not yet tested for android studio

also i tried build win32 project on win32/MinGW, but it failed because of precompiled libraries.

**Comment by minggo** [comment]
Don't have to consider Android Studio, Android Studio doesn't support normal cmake files.

**Comment by MrCapone** [comment]
Generated Visual Studio 2015 project crashes on linking because of prebuilt libs. I will try to fix i and then i can make pull request.

**Comment by MrCapone** [comment]
@minggo should i push my [CmakeLists.txt](https://gist.github.com/MrCapone/ccdc1826cb7362086107e8096bfe6f90) as PR? It works good on cpp projects with `linux/gcc`, `macOS+clang`, `Windows+nmake`, also it generates valid projects for `Xcode (only macOS target)` and `Visual Studio 2013/2015/2017 (only win32 target)`. Also i changed macOS output target for generate valid macOS .app bundle.

**Comment by minggo** [comment]
Yep, thanks.

**Comment by MrCapone** [comment]
done https://github.com/cocos2d/cocos2d-x/pull/18167
