### ISSUE TITLE
The display of UISliderTest_scale9_State_Change is wrong

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16928]
- cocos2d-x version: v3.14
- devices test on: macOS
- developing environments
   - NDK version: N/A
   - Xcode version: 8.1
   - VS version:N/A
   - browser type and version:N/A

Steps to Reproduce:

1. cpp-tests -> 52:Node: UI -> 1: GUI Dynamic Create Test -> 7: Slider Test -> UISliderTest_Scale9_State_Change

Current Result (Wrong):

![screen shot 2016-11-30 at 11 46 27](https://cloud.githubusercontent.com/assets/493372/20739133/1ec8b756-b6f3-11e6-96dc-1f26af64276d.png)

Expected Result (in v3.13.1):

<img width="958" alt="screen shot 2016-11-30 at 11 46 19" src="https://cloud.githubusercontent.com/assets/493372/20739142/29f20e34-b6f3-11e6-8005-41f0409dc1e5.png">

**Comment by dumganhar** [comment]
@ricardoquesada , please take a look at this issue.  It's also relative to Scale9Sprite.

**Comment by dumganhar** [comment]
7: UISliderIssue12249Test is also broken.
In 3.13.1, we get:
<img width="960" alt="screen shot 2016-11-30 at 11 54 21" src="https://cloud.githubusercontent.com/assets/493372/20739230/e0ebfe74-b6f3-11e6-8cad-57d34dc863fa.png">

But in current v3.14 branch:

![screen shot 2016-11-30 at 11 54 29](https://cloud.githubusercontent.com/assets/493372/20739234/e9de8920-b6f3-11e6-8080-21f1e24d916f.png)

**Comment by dumganhar** [comment]
Probably, the `LoadingBar issue` (https://github.com/cocos2d/cocos2d-x/issues/16930) is the same as this one.

**Comment by ricardoquesada** [comment]
PR is here: https://github.com/cocos2d/cocos2d-x/pull/16949

**Comment by dumganhar** [comment]
@ricardoquesada ,there are still two issues. I have posted it in your Pull Request.
