### ISSUE TITLE
Widget::clone() is broken

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16924]
- cocos2d-x version: v3.14
- devices test on: macOS, iOS
- developing environments
   - NDK version: N/A
   - Xcode version: 8.1
   - VS version: N/A
   - browser type and version: N/A

Steps to Reproduce:

1. cpp-tests -> 52:Node: UI -> 1:GUI Dynamic Create Test -> 16: PageViewTest -> 5: UIPageViewJumpToPageTest
2. Only `Jump to Page1` could be clicked, `Jump to Page(2,3,4)` buttons isn't clickable.

**Comment by dumganhar** [comment]
@ricardoquesada , this issue is probably the same as `copy` problem in https://github.com/cocos2d/cocos2d-x/pull/16949. 
Please also help to check. Thanks.

**Comment by ricardoquesada** [comment]
@dumganhar part of the same bug. fixed in this PR: https://github.com/ricardoquesada/cocos2d-x/commit/b7a769aac8dbcef4408791c6d29dfb95dd928b62
