### ISSUE TITLE
.9.png file is shown incorrect

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16921]
- cocos2d-x version: 3.14
- devices test on: macOS, iOS
- developing environments
   - NDK version: N/A
   - Xcode version: 8.1
   - VS version: N/A
   - browser type and version: N/A

Steps to Reproduce:

1. Pull the latest code in v3.14 branch
2. build js-tests for Mac or iOS
3. go to js-tests -> UITest -> UIS9NinePatchTest

Result:

![screen shot 2016-11-30 at 10 20 20](https://cloud.githubusercontent.com/assets/493372/20737283/a35550a4-b6e6-11e6-9597-0eb0b7bc5e31.png)

The expected result (in v3.13.1): 

![screen shot 2016-11-30 at 10 21 14](https://cloud.githubusercontent.com/assets/493372/20737411/666d9592-b6e7-11e6-8021-d0708a9ba1b8.png)

Please note that the screenshot in v3.13.1 will not display black lines at top & left side.

I guess it's a `magic number` issue in Scale9Sprite since I noticed this code:
```c++
void Scale9Sprite::setupSlice9(Texture2D* texture, const Rect& capInsets)
{
    if (texture && texture->isContain9PatchInfo()) {
        auto& parsedCapInset = texture->getSpriteFrameCapInset(getSpriteFrame());

        if(!parsedCapInset.equals(Rect::ZERO))
        {
            // adjust texture rect. 1.3f seems to be the magic number  <--- magic number???
            // to avoid artifacts
            auto rect = getTextureRect();
            rect.origin.x += 1.3f; 
            rect.origin.y += 1.3f;
            rect.size.width -= 2.0f;
            rect.size.height -= 2.0f;
            setTextureRect(rect);

            // and after adjusting the texture, set the new cap insets
            _isPatch9 = true;
            setCapInsets(parsedCapInset);
        }
    }

    if (!_isPatch9)
    {
        setCapInsets(capInsets);
    }
}
```

**Comment by dumganhar** [comment]
@ricardoquesada, could you please look at this issue? I guess it's caused after refactoring Scale9Sprite. Thanks.

**Comment by ricardoquesada** [comment]
@dumganhar yep, thanks. I took the "magic" number from v3.13, so I guess there must be something else somewhere

**Comment by ricardoquesada** [comment]
fixed.
