### ISSUE TITLE
UILoadingBarTest is broken

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#16930]
- cocos2d-x version: v3.14
- devices test on: macOS
- developing environments
   - NDK version: N/A
   - Xcode version: 8.1
   - VS version:N/A
   - browser type and version:N/A

Steps to Reproduce:

1. cpp-tests -> 52:Node: UI -> 1: GUI Dynamic Create Test -> 9: LoadingBar Test

2. UILoadingBarTest_Left:

The right direction loading bar is missing:

Current Result (Wrong):

![screen shot 2016-11-30 at 11 59 13](https://cloud.githubusercontent.com/assets/493372/20739323/750e5e76-b6f4-11e6-8582-a45bc5a8bb14.png)

Expected result:

<img width="959" alt="screen shot 2016-11-30 at 11 59 20" src="https://cloud.githubusercontent.com/assets/493372/20739327/82b29e8e-b6f4-11e6-8a6d-976e536f1d7f.png">

3. UILoadingBarTest_Left_Scale9 & UILoadingBarTest_Right is broken

Current Result (Wrong):

![screen shot 2016-11-30 at 12 00 36](https://cloud.githubusercontent.com/assets/493372/20739347/a4190400-b6f4-11e6-88e1-6bfdb8630700.png)

Expected result:
<img width="958" alt="screen shot 2016-11-30 at 12 00 41" src="https://cloud.githubusercontent.com/assets/493372/20739353/a9b94302-b6f4-11e6-8994-eded37d6e1d4.png">

4. UILoadingBarReloadTexture, Clicking `ToggleScale9`
After clicking `ToggleScale9` several times, the display in v3.14 will be wrong. And sometimes the texture is missing after clicking toggle many times.
![screen shot 2016-11-30 at 13 42 03](https://cloud.githubusercontent.com/assets/493372/20741165/6a13f5d0-b703-11e6-9cbd-ea105ae6858b.png)

5. UILoadingBarReloadTexture, Clicking `ChangeTexture`, the animation of progress is wrong:

![screen shot 2016-11-30 at 13 47 59](https://cloud.githubusercontent.com/assets/493372/20741249/f8be87fa-b703-11e6-9fb5-cf38a7ce48c4.png)

6. UILoadingBarIssue 12249: (Left: v3.13.1, Right: v3.14)
![loadingbarissue12249](https://cloud.githubusercontent.com/assets/493372/20741571/21f4860e-b706-11e6-9b14-3d98966f4e07.gif)

7. UILoadingBarTest_Direction:

![screen shot 2016-11-30 at 14 06 47](https://cloud.githubusercontent.com/assets/493372/20741693/dbb03232-b706-11e6-9c50-9de8b4232aad.png)

**Comment by dumganhar** [comment]
@ricardoquesada , please take a look at this issue too. Thanks.

**Comment by ricardoquesada** [comment]
I already fixed these ones, but I'll send a PR with the slider fix as well. they are different bugs

**Comment by ricardoquesada** [comment]
well, this is very strange. Slider + LoadingBar bugs fixed. But there is a parsing bug in CS reader that is feeding Sprite9SCale with the incorrect information...

...I don't know if this is a bug in rapidjson or not... working on this.

**Comment by ricardoquesada** [comment]
PR is here: https://github.com/cocos2d/cocos2d-x/pull/16949
