### ISSUE TITLE
GetFirstWordLen method breaks line on "no-break" space symbol

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#16939]
- cocos2d-x version: 3.13
environmental and platform independent problem

Steps to Reproduce:

1.  Try to enable word wrapping on label and use symbol of "no-break" space 0xA0 
https://unicodelookup.com/# /1
For example line: "This line contains only nonbreak spaces and no spaces at all" shouldn't be broken by word wrapping. Just like in this text field: -------------------------------------------> "This line contains only nonbreak spaces and no spaces at all".
Problem is in function isUnicodeSpace which is used for word wrapping (but probably shouldn't).

**Comment by drelaptop** [comment]
https://github.com/cocos2d/cocos2d-x/pull/18753 fixed this times ago
