### ISSUE TITLE
If Layer is  deprecated please chanage the "HelloWorld" Example that is created with Cocos console

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#16941]
- cocos2d-x version: 
3++
- devices test on:
all
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Create new project in cocos console 
2. The Example is create with Layer , which is deprecated  long time ago ...

please change it to something valid like sprite or node

**Comment by minggo** [comment]
Yep, you are right. We should modify it.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17048
