### ISSUE TITLE
Audio still playing app dead.

### ISSUE THREAD

**Issue by pineoc** [cocos2d/cocos2d-x#16945]
- cocos2d-x version: 3.13.1
- devices test on: Samsung Galaxy S2, API 15
- developing environments
   - NDK version: r12b
   - Xcode version: 8.1

when i test my game to my phone, background music file like ``background.wav``.
Background music still playing even though the app is dead.
This '.wav' file seems to be causing the problem. zombie background music.
Another phone S3, did not occur. just minor issue on android low API?

**Comment by minggo** [comment]
What API level used when building?

**Comment by pineoc** [comment]
In my case,
Android OS API : 15
in `build.gradle` file
compileSdkVersion 23
buildToolVersion "23.0.3"

**Comment by dumganhar** [comment]
@pineoc, which audio module are you using, `SimpleAudioEngine` or `AudioEngine`?

**Comment by pineoc** [comment]
When i used `SimpleAudioEngine`.
This error occur on `.wav` files. not `.mp3` files.

**Comment by dumganhar** [comment]
@pineoc, did you test it on other android devices?
I wanna check whether it's a device specific issue.

**Comment by pineoc** [comment]
@dumganhar other device (galaxy s3, galaxy a5, nexus 5x) not occurred.
I guess .wav file issued on low android version.
