### ISSUE TITLE
EditBox not show any character when type on keyboard

### ISSUE THREAD

**Issue by rbermudez** [cocos2d/cocos2d-x#16959]
- cocos2d-x version:3.13
- devices test on:android 4.4
- developing environments
   - NDK version: 10
   - Xcode version:Eclipse
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Run CppTest
2.Select 52:Node:Ui ->1:GUI:Dynamic Create Test ->3:EditBoxTest.
3.The problem is the component ui EditBox not show any character when type on keyboard, but when  the focus is lost the character appears

**Comment by qiwucwb** [comment]
me too.
android log: Warning! You can't change Android Hint fontName and fontSize.
testing...

**Comment by fnc12** [comment]
probably you pass `Size::ZERO` in `EditBox::create` function as first parameter.

**Comment by minggo** [comment]
@zilongshanren have you resolved it? I can't reproduce it in v3.14.

**Comment by artemtarassov** [comment]
i still see this behavior in v3.14.1 on my mac sierra

**Comment by zilongshanren** [comment]
@artemtarassov 
I have fixed it, could you please give it a test?

**Comment by artemtarassov** [comment]
@zilongshanren , i see you changed some java files but i had this issue with the mac implementation. i'm about to update to 3.15 in few days and will check if the editbox error is still there.

**Comment by zilongshanren** [comment]
@artemtarassov 
thanks.

**Comment by zilongshanren** [comment]
@qiwucwb It's fixed now in the upstream, you could refer to the merged PR to resolve this issue by yourself.
