### ISSUE TITLE
cocos2d-x 3.10 lua project will crash on simulator for XCode 8.2

### ISSUE THREAD

**Issue by knuth** [cocos2d/cocos2d-x#17019]
- cocos2d-x version: 3.10
- devices test on:
- developing environments
   - NDK version:
   - Xcode version: **Version 8.2 (8C38)**
   - VS version:
   - browser type and version:

I just update the Xcode to 8.2
Steps to Reproduce:

1. create a new lua project based on cocos2d-x 3.10 (e.g. cocos new -p cn.test -l lua Test)
2. build and run on iOS simulator [e.g. iPhone 6 (10.2) or (8.1version)]
3. crashed in the std vector. (when call lua_open())

The device works well.
the iPhone 4s simulator works well.

**Comment by zgc0911** [comment]
I also met this problem.
How to fix it.

**Comment by zgc0911** [comment]
build and run on iOS simulator(iPhone 6s(10.2 or 9.3)

**Comment by stnguyen** [comment]
this is urgent, no simulator works for me. anyone has any solution?

**Comment by minggo** [comment]
duplicated with #17043
