### ISSUE TITLE
built faild with json/document-wrapper.h not found.

### ISSUE THREAD

**Issue by liketemple** [cocos2d/cocos2d-x#17017]
- cocos2d-x version: 3.13
- devices test on: mac pro
- developing environments
   - NDK version:
   - Xcode version: 8.2
   - VS version:
   - browser type and version:

just simply create a new project, then use xcode to build it, get:
In file included from /Users/like/gitsrc/cocos2dx/cocos/3d/CCAnimation3D.cpp:26:
/Users/like/gitsrc/cocos2dx/cocos/3d/CCBundle3D.h:31:10: fatal error: 'json/document-wrapper.h' file not found
#include "json/document-wrapper.h"
         ^
1 error generated.

**Comment by minggo** [comment]
I think you didn't update external by running `./download-deps.py`.

**Comment by piotrros** [comment]
Fresh cocos2d-x 3.14 from download page.

./download-deps.py 
=======================================================
==> Prepare to download external libraries!
==> Not need to update!

Still the same error.
Seems like paths are wrong.
I fixed it like this:

`#include "../../../external/json/document-wrapper.h"`

But then more errors are popping up. So you have to remove json from path in each error. 
I wonder why it cannot find it. I have this line:
/Users/piotr/Documents/pierdoly/cocos2d-x-3.14/cocos/external
in header search paths so it should work.

**Comment by minggo** [comment]
Where did you download from? If you downloaded from [here](http://www.cocos2d-x.org/), you don't have to download external libraries yourself. The zip file includes all needed libraries.

**Comment by piotrros** [comment]
Yes - from "here" :) I fixed several path error using relative paths and it worked. Strange.

**Comment by minggo** [comment]
yep, it is always path error. You should make sure what search paths are added, and what paths you used in codes.

**Comment by piotrros** [comment]
Yes, but it should work, I have /Users/piotr/Documents/pierdoly/cocos2d-x-3.14/cocos/external in search paths and there's "json" directory inside. Errors were only related to rapidjson library, if I didn't have this search path added it would have the same errors with other external libraries.
