### ISSUE TITLE
[RFC] Support of non-bottom left coord system,  replacement for ignoreAnchorPointForPosition, 

### ISSUE THREAD

**Issue by DavidDeSimone** [cocos2d/cocos2d-x#17021]
Proposal:

cocos2d-x only currently supports the origin being in the bottom left. The engine has the ability to change the anchor point of a node, and toggle if this anchor point will be used for positioning calculations, however there is no way to change the basis of the coordinate system. It seems that overall there is a desire to support upper-left, and center based coordinate systems. 

This can be accomplished by a project using additional transforms, however this can be complicated when factoring in CCActions, as the CCActions can change the scale and rotation. with updating the users additional transform. This can also be done by adding additional nodes to the hierarchy, but this adds memory and cpu overhead. 

I propose two additional concepts to be added to cocos:

- The ability to change where a node anchor's itself, which is decoupled from where it scales and rotates itself from. Basically an Anchor Point used only for positioning. 
- The ability to change where a node is positioned relative to it's parent. With this, I have the ability to set my coordinate system to 0,0 being either in the center, or the upper left, or the bottom left.

The code may look like this. (Not tested, just a rough idea)
(in Node::getNodeToParentTransform)
```
        if (_isUsingPositionAnchor) // replaces _ignoreAnchorPointForPosition
        {
            auto&& p = getPositionAnchorInPoints();
            x += _anchorPointInPoints.x + p.x;
            y += _anchorPointInPoints.y + p.y;
        }
        
        if (_parent && _parent->isUsingPositionBasis())
        {
            auto&& p = _parent->getPositionBasisInPoints();
            x += p.x;
            y += p.y;
        }
        // rest of code...
```

@minggo @ricardoquesada Is this something you are interested in?

**Comment by minggo** [comment]
> The ability to change where a node anchor's itself

Doesn't `Node::setAnchorPoint()` meets it?

> The ability to change where a node is positioned relative to it's parent

Currently, the position set in child is relative to its parent. So i don't quite understand this requirement.

**Comment by stevetranby** [comment]
@DavidDeSimone what would your client usage API look like? Is this a positioning method you've used elsewhere?

I think I kind of understand your stated desire to move a node along a path while adjusting anchor,scale, and rotation separately without having to write the re-calculate function to use every step of the action.

I believe the simplest solution working within the bounds of the cocos2d-x engine as it currently exists would be to have the scaled and rotated Node/Sprite be a child of a node that's used as the action's target.

**Comment by DavidDeSimone** [comment]
@minggo Thank you for the response, apologies for some miscommunicates. Let me clarify.

Node::setAnchorPoint does meet that requirement, however it also means I must scale and rotate from that point too. The ask is to have the ability to have my anchor point be in the upper left, but scale and rotate around my center (or vice versa). IIRC, Flash is an example of a system like this. The anchor point for positioning can be different then the anchor point for scale and rotation.

The second requirement is if I want 0,0 to be in the upper left hand corner (or the center etc) instead of always being in the bottom left hand corner (as it is currently). The desired behavior would be an API like
```
auto scene = new Scene();
scene.setBasis(Vec2(0, 1)); // 0,0 is now the upper left hand corner of the scene
```

```
auto node = new Node();
node.setPositionAnchor(Vec2(0,1)); // Node will position itself according to the top left
node.setAnchorPoint(Vec2(0.5,0.5));  // node will rotate and scale around the center
```

``` 
auto node = new Node();
node.setAnchorPoint(Vec2(0, 1)); // No call to setPositionAnchor, node will position, scale 
// and rotate to the top left. Backwards compatible. 
```

**Comment by DavidDeSimone** [comment]
@stevetranby Let me give you more background on my teams current situation.

I work in a legacy cocos2d-x codebase, where old team members wanted 0,0 to be in the upper left hand corner of every view. They heavily modified the transform function in a clunky way to accomplish this. 

I have spent the past few days cleaning this up. I have programmed an API for setting 0,0 to be any position you would like (middle, bottom left, top left, etc.) in cocos with minimal code changes, in a backwards compatible way. I am willing to share with functionality, however I want to have a discussion with the community if this is a desired feature for the engine.

**Comment by stevetranby** [comment]
@DavidDeSimone I understand now. I would say as long as it doesn't add any conditionals, change behavior (backward compatible), or otherwise affect performance then it's worth the discussion and I'd post the code as a PR, but you may want to wait for confirmation from the team (ie: @minggo  and company). Otherwise you may also get more discussion over on the forums??
http://discuss.cocos2d-x.org/

**Comment by minggo** [comment]
@DavidDeSimone thanks for explanation. I understand the requirement of the `anchor point requirement`. So you want two different anchor points, one for position, one for rations and scale. But it will break compatibility.

About the second requirements of your implementation showed above, it seems it will affect the performance.

**Comment by DavidDeSimone** [comment]
@stevetranby That's a good callout. I will prepare a post on the forums and let people discuss this matter there.

@minggo I believe this will be backwards compatible. 

I think at this point, it would be best to let the code speak for itself. Here is my current work in progress patch:

[positionBasis.txt](https://github.com/cocos2d/cocos2d-x/files/667774/positionBasis.txt)

**Comment by stevetranby** [comment]
Initial glance:

It does add conditionals, but they look to be limited to the infrequent code paths (in common case), `setContentSize` and `Node::getNodeToParentTransform()`.

You also prevent dirty flag being set (backward incompatibility):
```
_transformUpdated = _transformDirty = _inverseDirty = true;
```
It does appear to be backward compatible, but if you don't use this feature there are 2 extra conditional tests that will run always, but as above usually infrequently.

Assuming it's accepted into the core (instead of you just keeping this in your custom fork of the engine), this could be another use of FEATURE_DEFINE_MACRO in order to by default keep it strictly backward compatible.

Just trying to help. I have no authority in what will be accepted :D

**Comment by DavidDeSimone** [comment]
After discussing with other community members, I think that this RFC would not be a good fit for the cocos2d-x engine. It adds a layer of complexity that most engine users do not need, and will add maintenance overhead. Thank's to @minggo and @stevetranby for the discussion.

If anyone needs this functionality in their own engine fork, feel free to use the patch provided in the issue, and feel free to contact/ping me if you have any questions. Closing this.
