### ISSUE TITLE
LabelIssue4428Test is broken in v3.14

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17022]
- cocos2d-x version: 3.14
- devices test on: macOS 10.12.2
- developing environments
   - NDK version:
   - Xcode version: 8.2
   - VS version:
   - browser type and version:

Steps to Reproduce:

Node: Label - New API -> New Label Bugs Test (LabelIssue4428Test)

Result:

The letter of bitmap font isn't flipped.

![new label bugs test](https://cloud.githubusercontent.com/assets/493372/21250144/e8078b1a-c37d-11e6-82a7-5f9d6a38be37.PNG)

Expected:

Should be flipped.

![screen shot 2016-12-16 at 10 55 09](https://cloud.githubusercontent.com/assets/493372/21250163/25535954-c37e-11e6-8cfa-9f80cd10e6f8.png)

**Comment by dumganhar** [comment]
@ricardoquesada ,

I found that this test case uses getting sprite from bitmap font label and setting flipY for sprite.
It's probably caused by our sprite refactoring.

Could you take a look at this issue? Thanks.

```c++
LabelIssue4428Test::LabelIssue4428Test()
{
    auto size = Director::getInstance()->getWinSize();

    auto label = Label::createWithBMFont( "fonts/bitmapFontTest3.fnt", "123\n456");
    label->setPosition(Vec2(size.width /2.0f, size.height / 2.0f));
    label->setAnchorPoint(Vec2::ANCHOR_BOTTOM_LEFT);
    addChild(label);

    int len = label->getStringLength();
    for (int i = 0; i < len; ++i)
    {
        auto sprite = label->getLetter(i);
        if (sprite != nullptr)
        {
            sprite->setFlippedY(true);  // Set flipY here, but it doesn't work in v3.14.
        }
    }
}
```

**Comment by ricardoquesada** [comment]
@dumganhar thanks. good catch!

fix is here: https://github.com/cocos2d/cocos2d-x/pull/17025

**Comment by dumganhar** [comment]
Thank you. @ricardoquesada . :)
