### ISSUE TITLE
Opencv [SIZE_MAX] error when installing

### ISSUE THREAD

**Issue by Islam94** [cocos2d/cocos2d-x#17031]
Hello,

I am trying to install opencv on a beagleboneblack to use in a school project but this error pops up when running the command line # make

Please help...
![capture2](https://cloud.githubusercontent.com/assets/24612503/21275206/84ca8ae0-c380-11e6-90d9-31aefb5a1745.PNG)

**Comment by minggo** [comment]
i think you should create an issue to opencv issue sytem instead
