### ISSUE TITLE
cocos2d::Menu wrong touch logic

### ISSUE THREAD

**Issue by MrCapone** [cocos2d/cocos2d-x#17036]
- cocos2d-x version: 3.13.1

Steps to Reproduce:

1. create cocos2d::Menu with multiple menu items
2. press one menu item and move finger (cursor) without touch up to another
3. first menu item become unselected and next one become selected

But it wrong touch logic. menu item must respond to moving touches only when it was touched first.

I recorded webms:
how it works now - https://www.dropbox.com/s/uyq95to56nzpq0l/bewfore.webm
how it should works - https://www.dropbox.com/s/2k0ao5srg406z5r/after.webm

**Comment by minggo** [comment]
A menu is the object to accept the touch information. The menu will receive move touch event, and determine which menu item is selected dynamically. So it is not an error, it is designed like this.
