### ISSUE TITLE
  Could NOT find Freetype (missing: FREETYPE_LIBRARIES FREETYPE_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by Sejen27** [cocos2d/cocos2d-x#17034]
- cocos2d-x version:3.13.1
- devices test on:
- developing environments
   - NDK version:android-ndk-r13b

when i compile proj.android-studio with cmake, i encount this error

See also "F:/code/cocos2d-x/Test/proj.android-studio/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
It appears you are cross compiling for  with Clang
CMake Error at cocos2d/cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARIES FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  cocos2d/cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cocos2d/cmake/Modules/FindFreetype.cmake:162 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cocos2d/cmake/Modules/CocosBuildHelpers.cmake:44 (find_package)
  cocos2d/cmake/Modules/BuildModules.cmake:36 (cocos_find_package)
  cocos2d/CMakeLists.txt:98 (BuildModules)
Error:executing external native build for cmake F:\code\cocos2d-x\Test\CMakeLists.txt

below is my build.gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.sejen"
        minSdkVersion 10
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_CPP_FEATURES=rtti exceptions',
                        '-DANDROID_ARM_MODE=arm'
                abiFilters 'armeabi', 'armeabi-v7a'
            }
        }
    }

    sourceSets.main {
        java.srcDir "src"
        res.srcDir "res"
        jniLibs.srcDir "libs"
        manifest.srcFile "AndroidManifest.xml"
        assets.srcDir "assets"
    }

    externalNativeBuild {
        cmake {
            path "../../CMakeLists.txt"
        }
    }

    signingConfigs {

       release {
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                storeFile file(RELEASE_STORE_FILE)
                storePassword RELEASE_STORE_PASSWORD
                keyAlias RELEASE_KEY_ALIAS
                keyPassword RELEASE_KEY_PASSWORD
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':libcocos2dx')
}

task cleanAssets(type: Delete) {
    delete 'assets'
}
task copyAssets(type: Copy) {
    from '../../Resources'
    into 'assets'
}

clean.dependsOn cleanAssets
preBuild.dependsOn copyAssets

**Comment by aqeeliqbal** [comment]
why this is closed?
is it resolved? how?
