### ISSUE TITLE
AudioEngine choppy sound played on MAC

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#17045]
use Audio engine to play sound effects. Sounds aren't played correctly.
File type: wav

**Comment by minggo** [comment]
It is better to provide the wav file.

**Comment by Bilalmirza** [comment]
I've spent hours finding what is wrong.

Sounds work fine in all scene. But when i play the same sounds in my gamescene (where alot of stuff is happening) It is completely distorted. I cant reproduce this in other projects.  I can only make a video and show it to you. I'll post the video in half an hour.

I think ill stick to cocosdenshion for now.

**Comment by Bilalmirza** [comment]
https://www.dropbox.com/s/cuv2bwrz11jp93i/cocosAudioEngine.mov?dl=0

**Comment by minggo** [comment]
@dumganhar please take a look.

**Comment by dumganhar** [comment]
@minggo, OK, I'm downloading the video.

**Comment by dumganhar** [comment]
@Bilalmirza, It's probably an issue which has been resolved already.
For minimum fix in your current engine, you just need to add a line in AudioCache.mm
```c++
_pcmData = (char*)malloc(_dataSize);
memset(_pcmData, 0, _dataSize); // add this line to initialize data.
```
We will release v3.14 in these days. Another way for some audio bug fixes is to pull the latest code in v3.14 branch. Then copy `cocos/audio/apple` folder in v3.14 branch to your engine folder. Don't forget to update xcode project configuration by adding some new files to `cocos/audio/apple`.

**Comment by Bilalmirza** [comment]
@dumganhar Thanks! that fixed it :D

**Comment by dumganhar** [comment]
@Bilalmirza, good to hear that it works. :)
