### ISSUE TITLE
3.14 support ssl?

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#17054]
3.14 support ssl?

**Comment by slackmoehrle** [comment]
of course and we have had SSL support for a long time. We use OpenSSL.

**Comment by huangapple** [comment]
@minggo 
socketio support ssl?

**Comment by minggo** [comment]
yep, socketio uses HttpClient, and HttpClient supports ssl. Did you meet any problem?

**Comment by huangapple** [comment]
@minggo 
https://github.com/cocos2d/cocos2d-x/issues/15972
Has it been solved?

**Comment by minggo** [comment]
No, it is not fixed. We will fix it ASAP.
