### ISSUE TITLE
Add "$(SRCROOT)/../cocos2d/cocos/editor-support" to target in xcode

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#17063]
- cocos2d-x version: v3.13

Steps to Reproduce:

1. #include <spine/spine-cocos2dx.h>
2. All spine files will generate an error because header search files dont have path the editor support.

**Comment by minggo** [comment]
i think you just need to include `#include "spine/spine.h"` to use spine.

**Comment by Bilalmirza** [comment]
@minggo 
It seems like i have to make a video for every issue to prove it :(
there are 2 bugs with a new project

steps to reproduce:
1. pull latest repo
2.cocos new test -l cpp
3. run project
4. will give error of document-wrapper.h 

"let me know if you want me to create a new issue for this"

5. change all document-wrapper.h to document.h 
6. project will run

2nd bug: spine error mentioned above!

I made a 5 min vid. Please watch the full video below.

https://www.dropbox.com/s/k3p34r5jvcqmhs7/SpineCocos2d-x.mov?dl=0


Thanks

**Comment by Bilalmirza** [comment]
@minggo  Due to document-wrapper.h bug... "cocos gen-libs -c" doesn't compile either!

**Comment by minggo** [comment]
You should update the 3rd party library by running `./download-deps.py`

**Comment by Bilalmirza** [comment]
@minggo ./download-deps.py removes the document-wrapper error... but doesn't remove the spine bug

**Comment by Bilalmirza** [comment]
http://discuss.cocos2d-x.org/t/spine-include-spine-spine-cocos2dx-h-file-not-found-solved/30862

heres a 4 month old forum post about it too.

**Comment by minggo** [comment]
But why did you include `<spine/spine-cocos2dx.h>` instead of `spine/spine.h`?

**Comment by Bilalmirza** [comment]
spine/spine.h doesn't work. Is it suppose to or am i missing something?

**Comment by Bilalmirza** [comment]
https://www.dropbox.com/s/86xdvuvtsk2f2j1/Screen%20Shot%202017-01-03%20at%202.32.36%20PM.png?dl=0

**Comment by minggo** [comment]
I added `spine/spine.h` in `cpp-empty-test`, no problem. I will create a new project to have a try.

**Comment by Bilalmirza** [comment]
thanks :)

**Comment by minggo** [comment]
Yep, it has problem in new project.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17137
