### ISSUE TITLE
ui::ListView setGlobalZOrder will Show Green Background .

### ISSUE THREAD

**Issue by Kotaiba** [cocos2d/cocos2d-x#17068]
- cocos2d-x version:3.13
- devices test on:ios

Steps to Reproduce:

1. _listView->setGlobalZOrder(204);
2. will show green background .
<img width="1127" alt="screen shot 2016-12-26 at 1 46 36 pm" src="https://cloud.githubusercontent.com/assets/3635272/21480825/a6e10276-cb69-11e6-9a8b-ce0d196185db.png">

**Comment by minggo** [comment]
global z order is used to sort commands, less global z order will be renderer first. So what's the global z order of the background?

**Comment by Kotaiba** [comment]
@minggo  i don't have background ,this will popup at the top of game scene that have many objects with deferent global z order.
this is how it will look like without global  z order 
<img width="1127" alt="screen shot 2016-12-29 at 12 15 59 pm" src="https://cloud.githubusercontent.com/assets/3635272/21540523/4718ec18-cdb8-11e6-81ab-3a3bf3b80a03.png">

**Comment by minggo** [comment]
> will show green background

I don't quite understand the issue. Did you mean the background changes to green or it is a green background but now it is on the top?

**Comment by minggo** [comment]
Could you please provide a test case to reproduce it?

**Comment by Kotaiba** [comment]
@minggo  I mean if i set global z order for listView a green layer will show from no where

**Comment by Kotaiba** [comment]
@minggo  you can use cocos2d test , bool UIListViewTest_Vertical::init() 
remove this line 
  _listView->setBackGroundImage("cocosui/green_edit.png");
and add  GlobalZOrder you will see the green layer 
    _listView->setGlobalZOrder(200);

<img width="742" alt="screen shot 2016-12-29 at 12 27 05 pm" src="https://cloud.githubusercontent.com/assets/3635272/21540717/dcbd3bb0-cdb9-11e6-974c-f1918d5685e0.png">

**Comment by minggo** [comment]
Yep, after adding `_listView->setGlobalZOrder(200)`, the background becomes green. I will take a look.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17098

**Comment by Kotaiba** [comment]
@minggo  great will test it soon ,can you please take a look at this globalZorder issue .https://github.com/cocos2d/cocos2d-x/issues/16726
