### ISSUE TITLE
The 'disconnect' event could not be triggered while closing SocketIO

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17070]
Just reported by a developer, we need to make a test case to reproduce it.

**Comment by dumganhar** [comment]
It was confirmed, we need to refactor SocketIO module since there are some differents from socket-io-client.

**Comment by dumganhar** [comment]
Refactoring thing should be done in `next` milestone.

**Comment by plutoo** [comment]
The issue does not exist on current version @minggo
