### ISSUE TITLE
Bug in RichText::createWithXML() 

### ISSUE THREAD

**Issue by aseem2625** [cocos2d/cocos2d-x#17077]
using Cocos2d-x 3.11.1, Android.

```cardFooter = ui::RichText::createWithXML("<font color='#545454' face='fonts/Open_Sans/OpenSans-Regular.ttf' size='32'> Here is my  <b>TEXT</b></font>");```

I've to give double space before ``<b>`` to get a single space on my screen.

**Comment by minggo** [comment]
I tested with latest codes in v3.14 branch, it seems it is fixed. You can have a try.
