### ISSUE TITLE
CC_SPRITE_DEBUG_DRAW = 2 is not drawing texture area

### ISSUE THREAD

**Issue by aseem2625** [cocos2d/cocos2d-x#17086]
using Cocos2d-x 3.11.1, Android.

In ``/base/CCConfig.h``
``#define CC_SPRITE_DEBUG_DRAW 2``

Setting it 2 only gives what setting it 1 gives which is outline. I need to draw debug texture area.
AFAIK, it used to work in 3.10.

Please close if it works fine in v3.14.

Thanks

**Comment by minggo** [comment]
I tested in v3.14, there is debug texture area with sprites, so close it.
