### ISSUE TITLE
HelloWorld::init() does not get called when HelloWorld::createWithPhysics() is called.

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#17093]
- cocos2d-x version: latest git repository as of December 31, 2016
- devices test on: Linux, Mac
- developing environments
   - Mac Xcode version: 8.2
   - Linux GCC: 6.2.1

Steps to Reproduce:

1. Create a new CPP sample project:
````shell
cocos new -l cpp inittest
````
2. Change [line 8 from HelloWorldScene.cpp](https://github.com/cocos2d/cocos2d-x/blob/v3/templates/cpp-template-default/Classes/HelloWorldScene.cpp#L8) to:
````cpp
    return HelloWorld::createWithPhysics();
````
3. Compile
````shell
#Linux
cocos run -p linux

#Mac
cocos run -p mac
````
4. Nothing in the scene will show up. HelloWorld::init() is not getting called.

**Comment by Rubonnek** [comment]
Related:
* Issue: #16941 
* Pull Request: #17048

**Comment by Rubonnek** [comment]
The problem lies in [lines 41 through 56 of CCPlatformMacros.h](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/CCPlatformMacros.h#L41-L56). Doing the changes I stated above to HelloWorldScene.cpp avoids running the `create()` function created by the `CREATE_FUNC` macro which also avoids running the `HelloWorld::init()` method.

Changing [line 8 of HelloWorldScene.cpp](https://github.com/cocos2d/cocos2d-x/blob/v3/templates/cpp-template-default/Classes/HelloWorldScene.cpp#L8) to the following:
````cpp
auto scene = HelloWorld::create();
scene->initWithPhysics();
return scene;
````
fixes this issue temporarily.

The only problem I see with doing this is that `Scene::init()` and `Scene::initWithPhysics()` overlap in functionality and incurs in a small unnecessary overhead. There's no need to call both of these functions.

**Comment by Rubonnek** [comment]
Just noticed that the proper way of initiating a scene with physics now is to change [line 16 of HelloWorldScene.cpp](https://github.com/cocos2d/cocos2d-x/blob/v3/templates/cpp-template-default/Classes/HelloWorldScene.cpp#L16) to the following:
````cpp
    if ( !Scene::initWithPhysics() )
````

**Comment by naklow12** [comment]
> Just noticed that the proper way of initiating a scene with physics now is to change [line 16 of HelloWorldScene.cpp](https://github.com/cocos2d/cocos2d-x/blob/v3/templates/cpp-template-default/Classes/HelloWorldScene.cpp#L16) to the following:
> 
> ```c++
>     if ( !Scene::initWithPhysics() )
> ```

Omg you solved my problem thank you.
