### ISSUE TITLE
Video Player always plays video on top, regardless of z-order.

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#17108]
- cocos2d-x version: 3.13.1
- devices test on: iPhone 7P

Video Player always plays a video on top, regardless of z-order. You can test this in cpp-tests.
1. run the default test and play a video.
2. add a Sprite and give it a z-order higher than the video player. Re-run cpp-tests. Notice the Sprite is on top of the video player. Press play. Video then comes to the top.
3. I tried adding a Layer, as a test, to see if it behaves differently. It does not, same result as step 2.

![screen shot 2017-01-04 at 2 09 00 pm](https://cloud.githubusercontent.com/assets/7491758/21656204/2aaa5576-d28b-11e6-924b-2261d4c18aac.png)

![screen shot 2017-01-04 at 2 09 20 pm](https://cloud.githubusercontent.com/assets/7491758/21656223/40b522a6-d28b-11e6-835a-5b6244749075.png)

**Comment by minggo** [comment]
Videoplayer just use system widget, it is not rendered by OpenGL ES, there is not z value concept about it.
