### ISSUE TITLE
Spritesheet created with algorithm polygon now works incorrectly

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#17119]
- cocos2d-x version: v3.14
- devices test on: Mac
- developing environments
   - NDK version:
   - Xcode version: v8.1
   - VS version:

All spritesheets with polygon algorithm now works incorrectly. This worked fine in v3.13.

here is an image of spritesheet
https://www.dropbox.com/s/we5qzb8fqmdd0hx/Screen%20Shot%202017-01-05%20at%205.52.16%20PM.png?dl=0

here is its display in game

https://www.dropbox.com/s/x38nger25z6gsvv/Screen%20Shot%202017-01-05%20at%205.51.22%20PM.png?dl=0

you can see in the background the polygons are created incorrectly as if it is taking whole rects of the image.

**Comment by minggo** [comment]
@ricardoquesada could you please take a look? I think it is something related with Sprite slice9 support modification. Thanks.

**Comment by ricardoquesada** [comment]
@Bilalmirza thanks for the report.

What's the best way to reproduce it. how did you create the spritesheet ? should attach the code/assets to reproduce it? Thanks!

also, from the screenshot I can't tell where is the bug.

**Comment by Bilalmirza** [comment]
@ricardoquesada  Sorry about that ... i figured out what was causing it. It occurs when ->setFlipped is called.

here is the link for spritesheet and images
https://www.dropbox.com/s/aa3zaeezc49oob2/testFolder.zip?dl=0

heres the video to produce it.
https://www.dropbox.com/s/fvslra7ujv0u6aa/setFlip%20Bug.mov?dl=0

Thanks

**Comment by ricardoquesada** [comment]
Thanks for the detailed bug report. I'll work on this this Monday.

**Comment by ricardoquesada** [comment]
PR here: https://github.com/cocos2d/cocos2d-x/pull/17135

**Comment by ryule** [comment]
After I applied this commits and calling setStrechEnabled(false) causes following CCASSERT:
`CCASSERT(_renderMode == RenderMode::QUAD || _renderMode == RenderMode::SLICE9, "centerRect can only be used with SLICE9 or QUAD render modes");`
because of `_renderMode == RenderMode::POLYGON`.

**Comment by ricardoquesada** [comment]
@ryule I'll change the assert to a warning. thanks.
