### ISSUE TITLE
ui::EditBox setPlaceHolderFontColor crash when creating single line EditBox

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#17114]
- cocos2d-x version: cocos2d-x-3.14
- devices test on: iphone 7 with iOS 10.2
- developing environments
   - NDK version: NA
   - Xcode version: 8.2
   - VS version: NA
   - browser type and version: NA

Steps to Reproduce:

1.  create a EditBox with InputMode::SINGLE_LINE
2.  call method `setPlaceholderFontColor`

**Comment by DavidDeSimone** [comment]
@zilongshanren I believe this may have been introduced in https://github.com/cocos2d/cocos2d-x/pull/16821, and I believe is fixed in https://github.com/cocos2d/cocos2d-x/pull/16915

**Comment by zilongshanren** [comment]
@DavidDeSimone 
👍   thanks, I'm considering to fix this issue and you guys had already fixed it.
