### ISSUE TITLE
DUTCH of Language Type does not exists in Lua Code.

### ISSUE THREAD

**Issue by bushimichi** [cocos2d/cocos2d-x#17123]
- cocos2d-x version: 3.14 and less

cocos/scripting/lua-bindings/script/cocos2d/Cocos2dConstants.lua

about line 190
cc.LANGUAGE_ENGLISH    = 0
cc.LANGUAGE_CHINESE    = 1
cc.LANGUAGE_FRENCH     = 2
cc.LANGUAGE_ITALIAN    = 3
cc.LANGUAGE_GERMAN     = 4
cc.LANGUAGE_SPANISH    = 5
cc.LANGUAGE_RUSSIAN    = 6
cc.LANGUAGE_KOREAN     = 7
cc.LANGUAGE_JAPANESE   = 8
cc.LANGUAGE_HUNGARIAN  = 9
cc.LANGUAGE_PORTUGUESE = 10
cc.LANGUAGE_ARABIC     = 11

--------------------------------------------------------------------

cc.LANGUAGE_ENGLISH = 0
cc.LANGUAGE_CHINESE = 1
cc.LANGUAGE_FRENCH = 2
cc.LANGUAGE_ITALIAN = 3
cc.LANGUAGE_GERMAN = 4
cc.LANGUAGE_SPANISH = 5
cc.LANGUAGE_DUTCH = 6    <---   Here
cc.LANGUAGE_RUSSIAN = 7
cc.LANGUAGE_KOREAN = 8
cc.LANGUAGE_JAPANESE = 9
cc.LANGUAGE_HUNGARIAN = 10
cc.LANGUAGE_PORTUGUESE = 11
cc.LANGUAGE_ARABIC = 12

**Comment by minggo** [comment]
We can not add all the languages, you can add it yourself, or you can send a PR to add it. But please don't break compatibility.

**Comment by bushimichi** [comment]
My explanation was bad. 
This issue is Typo in Lua Code. 
Although it is in C ++ code, it is a constant missing in Lua's code.
The constants are different between C ++ and Lua.

**Comment by minggo** [comment]
thanks, fixed in https://github.com/cocos2d/cocos2d-x/pull/17160
