### ISSUE TITLE
Why can't I use evalString

### ISSUE THREAD

**Issue by xifengxi** [cocos2d/cocos2d-x#17124]
- cocos2d-x version: 3.13.1
- devices test on: xiaomi5
- developing environments
   - NDK version: 4.9
   - Xcode version:r10c
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  I use a static method to call Cocos2dxJavascriptJavaBridge.eavlString(), but it does not respond. this is some pic
![image](https://cloud.githubusercontent.com/assets/10802972/21740829/ae8858ee-d500-11e6-8141-63783ce755b7.png)
![image](https://cloud.githubusercontent.com/assets/10802972/21740812/20a2ccda-d500-11e6-838b-562cec23cb34.png)
![image](https://cloud.githubusercontent.com/assets/10802972/21740834/c3be22f2-d500-11e6-85bd-1f5ab8e9cc7b.png)

i already use unOnUiThread and runOnGLThread

where I am wrong

**Comment by DavidDeSimone** [comment]
This was a known issue in 3.13.1 fixed in 3.14 by https://github.com/cocos2d/cocos2d-x/pull/16751

**Comment by xifengxi** [comment]
Oh! thank you. I have seen your pull yesterday. But it was closed.
