### ISSUE TITLE
TextField Black Box on Windows

### ISSUE THREAD

**Issue by Garretthh07** [cocos2d/cocos2d-x#17128]
- cocos2d-x version: 3.14 and less
- devices test on: windows
- developing environments
   - VS version: VS2015

Steps to Reproduce:

1.  Use  `TextField` on Windows, while inputting by Chinese Mode, It always appear a Black Box with Green Arrow. like this [Black Box Sample](http://www.zhangseng.com/id-66061216.html), what can I do to delete this

**Comment by Garretthh07** [comment]
By the way, `EditBox` while pop an input dialog, this is too ugly.

**Comment by minggo** [comment]
Windows is a developing platform, not a publishing platform. We will focus mostly on mobile platforms.

**Comment by Garretthh07** [comment]
thanks a lot
