### ISSUE TITLE
if called setContentSize then the sprite position will have offset!

### ISSUE THREAD

**Issue by QwincyLi** [cocos2d/cocos2d-x#17134]
- cocos2d-x version: 3.13.1
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: VS 2015
   - browser type and version:

Steps to Reproduce:

1.   create a sprite
2.   called setContentSize

test code :
```c++
auto sprite = Sprite::create("HelloWorld.png");
    sprite->setPosition(Vec2(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y));
	sprite->setContentSize(Size(400, 400));
	sprite->setOpacity(100);
    this->addChild(sprite, 0);

	auto sprite2 = Sprite::create("HelloWorld.png");
	sprite2->setPosition(Vec2(visibleSize.width / 2 + origin.x, visibleSize.height / 2 + origin.y));
	sprite2->setContentSize(Size(100, 45));
	sprite2->setOpacity(200);
	this->addChild(sprite2);

	auto sprite3 = Sprite::create("HelloWorld.png");
	sprite3->setPosition(Vec2(visibleSize.width / 2 + origin.x, visibleSize.height / 2 + origin.y));
	this->addChild(sprite3);`
```
        their  position was the same! but in the simulator thier be draw in different position!

**Comment by minggo** [comment]
I tested on Mac with v3 latest codes, can not reproduce it. Could you please try it with latest v3 codes? If it also has the issue, could you please paste a picture to show the error effect?

Thanks.

**Comment by QwincyLi** [comment]
Sorry for my later reply!  Perhaps my test code and description is not correct!

i had tested it on v 3.14.

if parent node called setContentSize! the method setAnchorPoint() was invalid ! The position of the child node is wrong!

      `auto scene = Scene::create();

	auto visibleSize = Director::getInstance()->getVisibleSize();
	Vec2 origin = Director::getInstance()->getVisibleOrigin();

	auto sprite = Sprite::create("HelloWorld.png");
	sprite->setPosition(Vec2(visibleSize.width / 2 + origin.x, visibleSize.height / 2 + origin.y));
	// set AnchorPoint(0.5,0.5)
	sprite->setAnchorPoint(Vec2( 0.5, 0.5));
	sprite->setContentSize(Size(400, 400));
	sprite->setOpacity(100);
	scene->addChild(sprite, 0);

	auto sprite2 = Sprite::create("HelloWorld.png");
	/*
		sprite2 is sprite child, and sprite anchorPoint is Vec(0.5, 0.5) , 
		sprite position should be in sprite mid, But it's on the lower left corner!
		It looks like anchorPoint is Vec(0,0)
	*/
	sprite2->setPosition(Vec2(0, 0));
	sprite2->setAnchorPoint(Vec2(0.5, 0.5));
	sprite2->setOpacity(200);
	sprite->addChild(sprite2);`

the picture of error effect!
![erroreffect](https://cloud.githubusercontent.com/assets/19216999/22724390/ae435f6e-ee00-11e6-85d1-661469292925.png)

[the problem be same as: http://www.cocoachina.com/bbs/read.php?tid=265394](http://www.cocoachina.com/bbs/read.php?tid=265394)

Thanks for you reply!

**Comment by minggo** [comment]
I think the result is correct. sprite1's anchor point only affect sprite1's position, its origin is bottom left. sprite2 is a child of sprite1, so sprite2's position(center of sprite2 as the anchor point is (0.5,0.5)) is relative to sprite1's origin.
