### ISSUE TITLE
Android build freezing when audio file is played Cocos2d-x 3.13.1 and 3.14

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#17148]
[log.txt](https://github.com/cocos2d/cocos2d-x/files/695970/log.txt)

[audiotest.zip](https://github.com/cocos2d/cocos2d-x/files/695975/audiotest.zip)

- cocos2d-x version: 3.13.1 and 3.14
- devices test on: Nexus 6P with Android v7.1.1
- developing environments
   - NDK version: crystax-ndk-10.3.1
   - Xcode version: -
   - VS version: -
   - browser type and version: -

Steps to Reproduce:

1. Play an ogg audio file several times. In the attached project the same file is played 400ms apart 5 times.
Game freezes when experimental::AudioEngine::play2d is called.

OGG audio file is in the attached audiotest.zip project, and the logcat output log.txt is also attached to this post.

Android build command used: cocos compile -p android -m debug --ap android-15

**Comment by dumganhar** [comment]
@rh101, thanks for your feedback.
Does this issue only occur on Nexus 6P with Android v7.1.1? I tested your demo on one of my device with android 5.0.1 and it didn't crash.

**Comment by dumganhar** [comment]
I have reproduced this issue on Nexus 9 with Android 7.0. 
And I found this log output:
![screen shot 2017-01-13 at 10 11 04](https://cloud.githubusercontent.com/assets/493372/21916048/b63a7d66-d978-11e6-8483-a32e6d572969.png)
It seems that OpenSLES decoding stuff didn't work correctly on Android 7+.

**Comment by rh101** [comment]
@dumganhar yes, you are right, I just tested it on a Samsung S6 with Android 5.x and it worked, but it won't work on the Nexus 6P with Android 7.1.1.

Using Cocos2dx v3.12 works fine though on Android 7.1.1, so what exactly has changed between Cocos2dx 3.12 and 3.13.1/3.14?

**Comment by rh101** [comment]
@dumganhar I just tested MP3 and WAV versions of the same audio file, and they worked perfectly fine on the Nexus 6p with Android 7.1.1.  The problem only appears if the OGG format is used.  Does it process the file via a different code path to decode it?

**Comment by dumganhar** [comment]
@rh101, sorry for my late.
I submitted a PR (https://github.com/cocos2d/cocos2d-x/pull/17233) to improve stability and performance.
That PR should resolve this issue. Please have a try.

**Comment by rh101** [comment]
@dumganhar No worries, I did already test your changes, and I did post on the other thread you made regarding the changes. I'm just waiting on the next official Cocos2d-x release with these changes (you mentioned it will be in v3.15).

**Comment by dumganhar** [comment]
PR (https://github.com/cocos2d/cocos2d-x/pull/17233) was merged. I closed this issue.
