### ISSUE TITLE
Font Atlas crashed in function FontAtlas::prepareLetterDefinitions after a memory warning emitted.

### ISSUE THREAD

**Issue by bingle123** [cocos2d/cocos2d-x#17167]
- cocos2d-x version:3.14
- devices test on:iPad
- developing environments
   - NDK version:android-ndk-r10e
   - Xcode version:Version 8.2.1 (8C1002)
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  add a UIButton to scene
2. update the title of the button in a timer scheduler.
3. add many sprites to make system eject a memory warning. 
4.after  a memory warning emitted, the app will crashed on  line 443 of CCFontAtlas.cpp since _atlasTextures[_currentPage] is nullptr after FontAtlasCache::purgeCachedData called.  
![crashed2017-1-12](https://cloud.githubusercontent.com/assets/7941850/21876635/8f3c3a06-d8bf-11e6-90d8-2d54bb8a9fb3.jpg)

fixed:
 edit  CCFontAtlasCache.cpp , about line 45, add 2 lines as follow:
        **if(atlas.second->getReferenceCount()<=0){**
            atlas.second->purgeTexturesAtlas();
        **}**

**Comment by toreinkun** [comment]
if the ReferenceCount <= 0, it means that the object has been released.
So atlas.second->purgeTexturesAtlas() won't be invoked.

**Comment by bingle123** [comment]
Yes，you’re right. May be we should reconstruct the atlasTexture vector(map) as the rendering thread approaches here while the vector(map) is empty.
The text will not be rendered if we just only add a NULL judgement statement before the crashed line, in which case I've tested.

**Comment by toreinkun** [comment]
Which font did you used?  Ttf or system font?

**Comment by bingle123** [comment]
Sniglet-Regular.ttf,DroidSerif.ttf or Arial.ttf ,etc.

**Comment by minggo** [comment]
> _atlasTextures[_currentPage] is nullptr after FontAtlasCache::purgeCachedData called

@bingle123 did you invoke `FontAtlasCache::purgeCachedData` in your game code?

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/18145
