### ISSUE TITLE
Error compiling on Linux (Debian stretch)

### ISSUE THREAD

**Issue by mikejw** [cocos2d/cocos2d-x#17173]
- cocos2d-x version: cocos2d-x-3.14

Steps to Reproduce:

1.  Install 
2.  Create new app
3. run "cocos run -s . -p linux"

Output:

Building mode: debug
running: 'cmake -DCMAKE_BUILD_TYPE=Debug -DDEBUG_MODE=ON ..'

It appears you are building natively for Linux with GCC
-- OpenGL include dirs: /usr/include
-- GLEW include dirs: /usr/include
-- PkgConfig found
-- GLFW3 include dirs: /usr/include/GLFW
-- SQLite3 include dirs: /usr/include
-- FMOD include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/linux-specific/fmod/include
-- Fontconfig include dirs: /usr/include/freetype2
-- GTK3 include dirs: /usr/include/gtk-3.0;/usr/include/at-spi2-atk/2.0;/usr/include/at-spi-2.0;/usr/include/dbus-1.0;/usr/lib/x86_64-linux-gnu/dbus-1.0/include;/usr/include/gtk-3.0;/usr/include/gio-unix-2.0/;/usr/include/cairo;/usr/include/pango-1.0;/usr/include/harfbuzz;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/freetype2;/usr/include/libpng16;/usr/include/gdk-pixbuf-2.0;/usr/include/libpng16;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include
-- Freetype include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/freetype2/include/linux;/home/mike/Desktop/gamename/MyCppGame/cocos2d/external/freetype2/include/linux
-- WebP include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/webp/include/linux
-- Chipmunk include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/chipmunk/include
-- Bullet include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/bullet
-- Recast include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/recast
-- TinyXML2 include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/tinyxml2
-- JPEG include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/jpeg/include/linux
-- ZLIB include dirs: /usr/include
-- MINIZIP include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/unzip;/usr/include
-- PNG include dirs: /usr/include;/usr/include
-- TIFF include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/tiff/include/linux
-- WEBSOCKETS include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/websockets/include/linux
-- CURL include dirs: 
-- Flatbuffers include dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external
-- OPENGL add to include_dirs: /usr/include
-- OPENGL libs added to 'cocos2dInternal': /usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so
-- GLEW add to include_dirs: /usr/include
-- GLEW libs added to 'cocos2dInternal': /usr/lib/x86_64-linux-gnu/libGLEW.so
-- GLFW3 add to include_dirs: /usr/include/GLFW
-- GLFW3 libs added to 'cocos2dInternal': glfw
-- GLFW3 add definitions: -DGLFW_DLL
-- FMOD add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/linux-specific/fmod/include
-- FMOD libs added to 'cocos2dInternal': /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/linux-specific/fmod/prebuilt/64-bit/libfmod.so;/home/mike/Desktop/gamename/MyCppGame/cocos2d/external/linux-specific/fmod/prebuilt/64-bit/libfmod.so
-- FONTCONFIG add to include_dirs: /usr/include/freetype2
-- FONTCONFIG libs added to 'cocos2dInternal': fontconfig;freetype
-- THREADS libs added to 'cocos2dInternal': -lpthread
-- GTK3 add to include_dirs: /usr/include/gtk-3.0;/usr/include/at-spi2-atk/2.0;/usr/include/at-spi-2.0;/usr/include/dbus-1.0;/usr/lib/x86_64-linux-gnu/dbus-1.0/include;/usr/include/gtk-3.0;/usr/include/gio-unix-2.0/;/usr/include/cairo;/usr/include/pango-1.0;/usr/include/harfbuzz;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/freetype2;/usr/include/libpng16;/usr/include/gdk-pixbuf-2.0;/usr/include/libpng16;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include
-- GTK3 libs added to 'cocos2dInternal': gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
-- GTK3 add definitions: -pthread
-- ZLIB add to include_dirs: /usr/include
-- ZLIB libs added to 'cocos2dInternal': /usr/lib/x86_64-linux-gnu/libz.so
-- MINIZIP add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/unzip;/usr/include
-- MINIZIP libs added to 'cocos2dInternal': unzip;/usr/lib/x86_64-linux-gnu/libz.so
-- JPEG add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/jpeg/include/linux
-- JPEG libs added to 'cocos2dInternal': /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/jpeg/prebuilt/linux/64-bit/libjpeg.a
-- PNG add to include_dirs: /usr/include;/usr/include
-- PNG libs added to 'cocos2dInternal': /usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so
-- TIFF add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/tiff/include/linux
-- TIFF libs added to 'cocos2dInternal': /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/tiff/prebuilt/linux/64-bit/libtiff.a
-- TinyXML2 add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/tinyxml2
-- TinyXML2 libs added to 'cocos2dInternal': tinyxml2
-- FREETYPE add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/freetype2/include/linux;/home/mike/Desktop/gamename/MyCppGame/cocos2d/external/freetype2/include/linux
-- FREETYPE libs added to 'cocos2dInternal': /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/freetype2/prebuilt/linux/64-bit/libfreetype.a
-- WEBSOCKETS add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/websockets/include/linux
-- WEBSOCKETS libs added to 'cocos2dInternal': /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/websockets/prebuilt/linux/64-bit/libwebsockets.a
-- CURL libs added to 'cocos2dInternal': curl
-- FLATBUFFERS add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external
-- XXHASH add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/xxhash
-- XXHASH libs added to 'cocos2dInternal': xxhash
-- WEBP add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/webp/include/linux
-- WEBP libs added to 'cocos2dInternal': /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/webp/prebuilt/linux/64-bit/libwebp.a
-- CHIPMUNK add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/chipmunk/include
-- CHIPMUNK libs added to 'cocos2dInternal': /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/chipmunk/prebuilt/linux/64-bit/libchipmunk.a
-- BULLET add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/bullet
-- BULLET libs added to 'cocos2dInternal': bullet
-- RECAST add to include_dirs: /home/mike/Desktop/gamename/MyCppGame/cocos2d/external/recast
-- RECAST libs added to 'cocos2dInternal': recast
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mike/Desktop/gamename/MyCppGame/linux-build
running: 'make -j8'

[  1%] Built target xxhash
[  2%] Built target tinyxml2
[  3%] Built target flatbuffers
[  5%] Built target recast
[  5%] Built target MyGame_CORE_PRE_BUILD
[  5%] Built target unzip
MyGame_PRE_BUILD ...
[  5%] Built target MyGame_PRE_BUILD
[ 25%] Built target bullet
[100%] Built target cocos2dInternal
[100%] Built target cocos2d
[100%] Linking CXX executable bin/MyGame
/usr/bin/ld: lib/libcocos2dInternal.a(CCTextureCache.cpp.o): undefined reference to symbol '_ZNSt18condition_variable10notify_oneEv@@GLIBCXX_3.4.11'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/MyGame.dir/build.make:168: recipe for target 'bin/MyGame' failed
make[2]: *** [bin/MyGame] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/MyGame.dir/all' failed
make[1]: *** [CMakeFiles/MyGame.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Error running command, return code: 2.

**Comment by minggo** [comment]
> /usr/bin/ld: lib/libcocos2dInternal.a(CCTextureCache.cpp.o): undefined reference to symbol '_ZNSt18condition_variable10notify_oneEv@@GLIBCXX_3.4.11'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

It seems there is some problem of c++ library. What's your g++ version? cocos2d-x needed g++ 4.9+.

**Comment by mikejw** [comment]
mike@dwayne:~/Desktop/gamename/MyCppGame$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.2.1-5' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.1 20161124 (Debian 6.2.1-5)

**Comment by dumganhar** [comment]
@mikejw ,
Could you switch to gcc 4.9 to test?

**Comment by v1993** [comment]
I had the same error with another project. Try wiping your build directory to rebuild from scratch.

**Comment by drelaptop** [comment]
out-of-data cmake issues
