### ISSUE TITLE
Enabling depth test and disabling depth mask equals disabling depth test in Android/IOS

### ISSUE THREAD

**Issue by wanjia** [cocos2d/cocos2d-x#17181]
when i draw some translucent objects and opaque objects, i found translucent object in cocos3.13.1 will be drawed after all opaque objects.  And the code in CCRenderer.cpp handle transparent command like this
glEnable(GL_DEPTH_TEST);
glDepthMask(false);

In my opinion,  these codes mean it will do the depth test, if fragments fail the depth test, it will be discarded, otherwise if fragments pass the depth test, the color buffer will be updated but depth buffer will not.

But when i test the actual effect in Android/IOS, I found glDepthMask(false) works almost like glDisable(GL_DEPTH_TEST)， the depth test seemed not working.

So if disabling glDepthMask seems to  disable depth test, the transparent command will be excuted under depth test disabling. it will cause the far translucent objects will be seen above the near opaque objects.

if I want translucent object A to blend with opaque B , and  opaque C(nearer) will overlap with opaque B.

Then i will get the result of object A blending with (B and C), but i just want to A to blend with B.

I don't know whether my understanding of these code are right. So can you guys give me some advice ?

**Comment by minggo** [comment]
@wanjia i think [cocos2d-x forum](http://discuss.cocos2d-x.org/) is more suitable for the topic. But if you found any issue, please create one here. Thanks.
