### ISSUE TITLE
使用--no-native生成的项目无法使用问题

### ISSUE THREAD

**Issue by wulei** [cocos2d/cocos2d-x#17196]
### 我用如下命令生成一个测试项目
```
cocos new -l lua --no-native ~/Documents/Hello
```

### 然后cd到目录下使用：
```
cocos run -p osx 
```

### 报错：
```
没有可用的平台。
```

**Comment by minggo** [comment]
the command is used for cocos studio, as cocos studio is canceled, the command will be removed.
