### ISSUE TITLE
crash on honor 3c android version 4.2.2

### ISSUE THREAD

**Issue by nanmuyao** [cocos2d/cocos2d-x#17193]
- cocos2d-x version: 3.13.1
- devices test on: honor 3c android 4.2.2
- developing environments
   - NDK version: ndk r11
   and i had tried ndk r10c r10b
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. cocos compile -p android then run on honor 3c android 4.2.2 and it crashed
2.code desc when i send http request it will crash like this
xhr:send(json.encode(sendData))
3. logcat flow
01-15 13:16:35.260: D/cocos2d-x debug info(6589): In the constructor of HttpClient!
01-15 13:16:35.296: W/dalvikvm(6589): dvmFindClassByName rejecting 'org/cocos2dx/lib/Cocos2dxHttpURLConnection'
01-15 13:16:35.488: A/libc(6589): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 6
@minggo

**Comment by minggo** [comment]
could you please provide a test case?

**Comment by nanmuyao** [comment]
you mean source code (caused crashed )and android apk ,is this?

**Comment by minggo** [comment]
the codes that i can reproduce the issue, i don't need the apk, i can compile it myself.

**Comment by nanmuyao** [comment]
i'll take this to you as soon as possible, please wait a moment , thanks a lot

**Comment by nanmuyao** [comment]
ndk version is Pkg.Revision = 11.0.2655954 from source.properties file
i had upload the test code file name is MainScene.lua ,sorry waitting for so long time

1. code
```lua
local MainScene = class("MainScene", cc.load("mvc").ViewBase)

function MainScene:onCreate()
--    display.newSprite("HelloWorld.png")
--        :move(display.center)
--        :addTo(self)

--     add HelloWorld label
--    cc.Label:createWithSystemFont("Hello World", "Arial", 40)
--        :move(display.cx, display.cy + 200)
--        :addTo(self)

    --Get
    local function onMenuGetClicked()
        local xhr = cc.XMLHttpRequest:new()
        xhr.responseType = cc.XMLHTTPREQUEST_RESPONSE_STRING
        xhr:open("GET", "http://sdpoker.dzlol.com/test.html")
        local function onReadyStateChanged()
            if xhr.readyState == 4 and (xhr.status >= 200 and xhr.status < 207) then
                print("send success")
                --print(xhr.response)
               
            else
                print("xhr.status is: ",xhr.status)
            end
            xhr:unregisterScriptHandler()
        end

        xhr:registerScriptHandler(onReadyStateChanged)
        xhr:send()
        print("send")
    end

    local function btSecond(tag, sender)
       print("btSecond getOid")
       onMenuGetClicked()
    end

    local item = cc.MenuItemFont:create("test")
    item:setPosition(cc.p(100,100))
    item:registerScriptTapHandler(btSecond)

    local menu = cc.Menu:create()
    menu:addChild(item)
    self:addChild(menu)
end

return MainScene
```
2.  png info

![mainscene](https://cloud.githubusercontent.com/assets/7760063/21979641/ceeece58-dc1a-11e6-9d3b-6221805b2c56.png)

**Comment by nanmuyao** [comment]
thanks a lot @minggo

**Comment by minggo** [comment]
Could you please tell me how to reproduce it step by step? Can i create a new lua project and replace the MainScene.lua, then i will reproduce the issue?

**Comment by nanmuyao** [comment]
1. create lua project with cocos2dx version 3.13.1
2.replace the new project MainScene.lua,with my MainScene.lua 
3.ndk version is Pkg.Revision = 11.0.2655954
4.run the command cocos compile -p android 
5.run the apk to the android version 4.2.2 my case is huawei honor 3c (the system version is 4.2.2)
6.it will crashed
Do not know whether the detailed enough thanks a lot that you had helped me many times on github and forum

**Comment by minggo** [comment]
Thanks for the information, it's my pleasure.

> 3.ndk version is Pkg.Revision = 11.0.2655954

What does it mean? Which file should i modify to use this information?

**Comment by nanmuyao** [comment]
I use the NDK  链接：http://pan.baidu.com/s/1cagT1k 密码：t42g and unzip the file you can see the file source.properties
![ndkinfo](https://cloud.githubusercontent.com/assets/7760063/22005676/34747c0c-dca0-11e6-8c50-68a93febff44.png)

**Comment by minggo** [comment]
Got it, thanks. I will try to reproduce it first.

**Comment by minggo** [comment]
I tested on huawei p9(Android 6.0), can not reproduce it. Does it only happen on huawei hornor 3c? Have you tried other devices or other Android versions?

**Comment by nanmuyao** [comment]
Yes, the Real machine only on huawei hornor 3c crash (android version 4.2.2), other device no chrash, and I have a android Simulator(version is 4.2.2 also crashed),and the simulator download url 链接：http://pan.baidu.com/s/1mh8IdNM 密码：aefw

**Comment by minggo** [comment]
it is strange, i am not sure if i can find huawei hornor 3c

**Comment by nanmuyao** [comment]
I use the cloud phone http://remote.utest.qq.com/ the huawei p6 android verison 4.2, and you could try this, the huawei p6 is free for using, and it crash either,just now
![phone](https://cloud.githubusercontent.com/assets/7760063/22007351/05d036d6-dcad-11e6-8278-24df0c16ace8.png)

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17215, it seems HttpURLConnection.getResponseMessage() returns null if there is no response message on Android 4.2, and will return a empty string on higher Android versions.

**Comment by nanmuyao** [comment]
I don't know what i should say, a big problem solved  ,thanks a lot @minggo

**Comment by minggo** [comment]
It's my pleasure, and thanks for the detail feedback.
