### ISSUE TITLE
AudioEngine does not call finishCallback if audio is removed before it has stopped playing

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#17199]
- cocos2d-x version: 3.14 (but possibly in all previous releases where this code exists)
- devices test on: N/A
- developing environments
   - NDK version: N/A
   - Xcode version: N/A
   - VS version: VS 2015
   - browser type and version: N/A

Steps to Reproduce:

1. Build a test application that plays an unsupported audio file format (such as AAC/MP4 on Windows).
If the player->_removeByAudioEngine is set to **true** at any point, then the AudioEngine will remove the audioID from the list, but it never actually calls _finishCallbak (it should be renamed _finishCallback if this code is ever updated). 

If an audio file is never played (ie, invalid audio format), or there is another issue preventing the sound from being played, the AudioEngine treats it as everything is ok, and simply removes the audio instance without calling _finishCallbak.  For game code that relies on the finishCallbak, it never occurs, so the game will be stuck waiting for something that will never happen.

The following is the code from AudioEngine-win32.cpp where the issue exists (same for Android/iOS etc), AudioEngineImpl::update(float dt).

The "if" and "else if" conditions both do the same thing, which is remove the audio from the _audioPlayers map, but only the "else if" condition calls the finishedCallbak.  If a sound is removed from _audioPlayers, then technically it has stopped, whether it was played or not.  It doesn't make much sense to have the if/else if condition there when the purpose is the same.

```
    for (auto it = _audioPlayers.begin(); it != _audioPlayers.end(); ) {
        audioID = it->first;
        player = it->second;
        alGetSourcei(player->_alSource, AL_SOURCE_STATE, &sourceState);

        if (player->_removeByAudioEngine)
        {
            _alSourceUsed[player->_alSource] = false;

            AudioEngine::remove(audioID);
            _threadMutex.lock();
            it = _audioPlayers.erase(it);
            _threadMutex.unlock();
            delete player;
        }
        else if (player->_ready && sourceState == AL_STOPPED) {

            _alSourceUsed[player->_alSource] = false;
            if (player->_finishCallbak) {
                auto& audioInfo = AudioEngine::_audioIDInfoMap[audioID];
                player->_finishCallbak(audioID, *audioInfo.filePath); //FIXME: callback will delay 50ms
            }

            AudioEngine::remove(audioID);
            delete player;
            _threadMutex.lock();
            it = _audioPlayers.erase(it);
            _threadMutex.unlock();
        }
        else{
            ++it;
        }
    }
```

If there isn't a specific reason why the if/else if is there, then the code should be changed to the following in all implementations (win32/Android/iOS etc):

```
    for (auto it = _audioPlayers.begin(); it != _audioPlayers.end(); ) {
        audioID = it->first;
        player = it->second;
        alGetSourcei(player->_alSource, AL_SOURCE_STATE, &sourceState);

        if (player->_removeByAudioEngine || (player->_ready && sourceState == AL_STOPPED))
        {
            _alSourceUsed[player->_alSource] = false;
            if (player->_finishCallbak) {
                auto& audioInfo = AudioEngine::_audioIDInfoMap[audioID];
                player->_finishCallbak(audioID, *audioInfo.filePath); //FIXME: callback will delay 50ms
            }

            AudioEngine::remove(audioID);
            _threadMutex.lock();
            it = _audioPlayers.erase(it);
            _threadMutex.unlock();
            delete player;
        }
        else{
            ++it;
        }
    }
```

**Comment by rh101** [comment]
The code I suggested in the previous comment would still call _finishedCallbak even if a sound is stopped explicitly by a call to AudioEngine::stop().  

I'm not sure if this is the preferred behavior, but that is up to you guys to decide.

**Comment by minggo** [comment]
It depends how we treat the `finished` state. We treat `finished` as the audio is played from start to end. We can change the behavior, but it will break compatibility, so i think it is better to keep as it is now.

**Comment by rh101** [comment]
Keeping the behavior the same is fine, but is there anything that can be done about the issue where AudioEngine::play2d is called, it always returns a valid ID even if the audio file format is not supported on that platform.  If it instead returned AudioEngine::INVALID_AUDIO_ID, then that would solve the problem completely. 

If a valid ID is always returned, the assumption is that the sound started playing, so game code would be actively waiting for finishedCallbak to be triggered.

**Comment by minggo** [comment]
> it always returns a valid ID even if the audio file format is not supported on that platform

It is an issue. But i think it's better to create a new issue to describe it.

**Comment by rh101** [comment]
Will do, and I'll close this one.
