### ISSUE TITLE
cocos2d: CCSpriteFrameCache: Trying to use file perfectBounce.png as texture, cocos2d: CCSpriteFrameCache: Couldn't load texture

### ISSUE THREAD

**Issue by suroorwijdan** [cocos2d/cocos2d-x#17200]
- cocos2d-x version: cocos2d-x-3.13.1
- devices test on: running build on simulator iphone 6s
- developing environments
   - NDK version: android-ndk-r13b
   - Xcode version: Version 8.1 (8B62)
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Running the build from xcode, getting exception when initializing a new scene which uses sprite frame cache. 
2. Have a spritesheet generated using texture packer, perfectBounce.png and perfectBounce.plist. Both files are present under the Resources directory in xcode. 

Screenshots attached for the debug console.

<img width="594" alt="screen shot 2017-01-16 at 21 57 04" src="https://cloud.githubusercontent.com/assets/1986887/21990970/c47a4ee0-dc36-11e6-8635-7d2ddc0521d6.png">

**Comment by suroorwijdan** [comment]
Some more info: Already tried cleaning in Xcode and deleting the data in Derived Data directory respective to the project. 

Using Cocos2d-js Everything works perfect on browser. But throws the above exception when running the build on iOS Simulator and device too.

**Comment by suroorwijdan** [comment]
Getting the same error when building for Android:

Logcat screenshot:

<img width="1432" alt="screen shot 2017-01-17 at 14 10 21" src="https://cloud.githubusercontent.com/assets/1986887/22013402/d610365a-dcbe-11e6-9fcc-69d41d29a571.png">

**Comment by minggo** [comment]
Could you please upload the plist and png file?

**Comment by suroorwijdan** [comment]
Here is one of the png and plist files which is throwing the same error.


![countdown_num](https://cloud.githubusercontent.com/assets/1986887/22055451/3f6ce6bc-dd81-11e6-9aa2-28ec0beaae56.png)

countdown_num.plist

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>frames</key>
        <dict>
            <key>countdown_num0.png</key>
            <dict>
                <key>aliases</key>
                <array/>
                <key>spriteOffset</key>
                <string>{0,0}</string>
                <key>spriteSize</key>
                <string>{100,92}</string>
                <key>spriteSourceSize</key>
                <string>{100,100}</string>
                <key>textureRect</key>
                <string>{{1,1},{100,92}}</string>
                <key>textureRotated</key>
                <false/>
            </dict>
            <key>countdown_num1.png</key>
            <dict>
                <key>aliases</key>
                <array/>
                <key>spriteOffset</key>
                <string>{0,0}</string>
                <key>spriteSize</key>
                <string>{100,92}</string>
                <key>spriteSourceSize</key>
                <string>{100,100}</string>
                <key>textureRect</key>
                <string>{{1,95},{100,92}}</string>
                <key>textureRotated</key>
                <false/>
            </dict>
            <key>countdown_num2.png</key>
            <dict>
                <key>aliases</key>
                <array/>
                <key>spriteOffset</key>
                <string>{0,0}</string>
                <key>spriteSize</key>
                <string>{60,92}</string>
                <key>spriteSourceSize</key>
                <string>{100,100}</string>
                <key>textureRect</key>
                <string>{{1,189},{60,92}}</string>
                <key>textureRotated</key>
                <true/>
            </dict>
        </dict>
        <key>metadata</key>
        <dict>
            <key>format</key>
            <integer>3</integer>
            <key>pixelFormat</key>
            <string>RGBA8888</string>
            <key>premultiplyAlpha</key>
            <false/>
            <key>realTextureFileName</key>
            <string>countdown_num.png</string>
            <key>size</key>
            <string>{102,250}</string>
            <key>smartupdate</key>
            <string>$TexturePacker:SmartUpdate:2f9fda59ea8f4d66e2cd321257f3501e:0b6b42585434c1923f3e80c19984aa89:ac20f6a099b4a26f12df893df88bf0fd$</string>
            <key>textureFileName</key>
            <string>countdown_num.png</string>
        </dict>
    </dict>
</plist>
```

**Comment by suroorwijdan** [comment]
No worries. I figured it out. Was a very silly issue on my side. The urls had a starting `/` in the resources just for these files that is why they were failing.
