### ISSUE TITLE
Removes linux 32-bit support

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17210]

**Comment by minggo** [comment]
Yep, most 3rd party libraries are installed by `build/install-deps-linux.sh`, and you can build 32bit of some libraries using this repo https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src

**Comment by minggo** [comment]
fixed https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/267
