### ISSUE TITLE
how to use CCFrameBuffer in cocos? For example？

### ISSUE THREAD

**Issue by grrr2828** [cocos2d/cocos2d-x#17214]
how to use CCFrameBuffer in cocos? For example？

**Comment by minggo** [comment]
I think it is designed to be used internally. @ricardoquesada any idea about it?

**Comment by grrr2828** [comment]
I need to implement water ripple screen distortion effect, use glCopyTexImage2D will drop frames.

**Comment by minggo** [comment]
I think you can use shader+rendertexture, or you can take a look test cases in `cpp-tests/Classes/EffectsTest/EffectsTest.cpp`.

**Comment by ricardoquesada** [comment]
take a look at the Effects examples in cpp-tests. The use the `CCGrid` class which uses the IIRC `CCFrameBuffer`

**Comment by grrr2828** [comment]
Can I modify the shape of the Ripple3D?Now is a circle

**Comment by grrr2828** [comment]
I need to distort with A texture. help!!!

**Comment by ricardoquesada** [comment]
@grrr2828 please, use the forum for support. and use github issues to report bugs/enhancements.

please, take a look at the code of Ripple3D. thanks.
