### ISSUE TITLE
applicationDidEnterBackground not called for Android

### ISSUE THREAD

**Issue by rnnbl** [cocos2d/cocos2d-x#17213]
- cocos2d-x version:  3.13.1
- devices test on: android 5.1, 4.4.2
- developing environments
   - NDK version: r10e
   - Xcode version: 8.2.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Run your cocos2d-x app on android
2. Switch to another activity outside the app
3.  applicationDidEnterBackground is not called

Notes:
I found some fixed issues regarding this problem back in 2011 #462 #238 [android]. In Cocos2dxGLSurfaceView.java:
```java
@Override
public void onPause() {
this.queueEvent(new Runnable() {
@Override
public void run() {
Cocos2dxGLSurfaceView.this.mCocos2dxRenderer.handleOnPause();
}
});
this.setRenderMode(RENDERMODE_WHEN_DIRTY);
//super.onPause();
}
```
I was thinking to fix it by uncommmenting the last line super.onPause() but that didn't work unfortunately, the code is different than the change of 2011, it had the super.onPause().

**Comment by minggo** [comment]
comment `super.onPause()` is because it will prevent OpenGL context being destroyed as possible.

**Comment by rnnbl** [comment]
If this is true then cocos2d-x android apps will slow down device and drain the battery of users when going to background. Not to mention bad reviews and possible rejection from play store. So this is a real serious problem or am I the only one having this?

**Comment by rnnbl** [comment]
@minggo Any updates on this?

**Comment by rnnbl** [comment]
This line of code is never called on android:
JNIEXPORT void JNICALL Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnPause() 

However the JNICALL Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnResume() is called.

**Comment by rnnbl** [comment]
@minggo Can you please add  a label 'critical'?

**Comment by dumganhar** [comment]
@rnnbl, added.

**Comment by rnnbl** [comment]
@dumganhar Thank you!

**Comment by rnnbl** [comment]
I fixed it with the following. In cocos2d/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxActivity.java:  
@Override
    protected void onPause() {
          super.onPause();
//Add these 2 lines:
**Cocos2dxHelper.onPause();
this.mGLSurfaceView.onPause();**
          SDKBox.onPause();
    }

**Comment by rnnbl** [comment]
It was the SDKBOX doing this, the automatic installer
