### ISSUE TITLE
Missing search path for SPINE

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#17238]
Reported by users on the forums.

- cocos2d-x version: v3.14.1

it seems we forgot to add header for Spine:

$(SRCROOT)/../cocos2d/cocos/editor-support

**Comment by minggo** [comment]
it is fixed in v3 branch https://github.com/cocos2d/cocos2d-x/pull/17137. Developers can add it to fix the issue, it is not a critical issue so i don't synchronize it to v3.14.1.
