### ISSUE TITLE
A little bug about build_android.py in Cocos2d-x-3.14

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#17234]
- cocos2d-x version: 3.14
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. enter the project directory and run `cocos compile -p android --android-studio -m release`
2. it will produce some outputs like: `ioerror no such file or directory: jni/Application.mk`

I found this bug in `tools/cocos2d-console/plugins/plugin_compile/build_android.py`:

```Python
def _get_build_type(self, param_of_appabi):

        # get build type from parameter
        if param_of_appabi:
            return self._do_get_build_type(param_of_appabi)
        
        # get build type from Application.mk
        applicationmk_path = os.path.join(self.app_android_root, "jni/Application.mk")
        with open(applicationmk_path) as f:
            for line in f:
                if line.find('APP_ABI') == -1:
                    continue
                build_type = self._do_get_build_type(line)
                if build_type != self.LuaBuildType.UNKNOWN:
                    return build_type

        return self.LuaBuildType.UNKNOWN
```

the line `applicationmk_path = os.path.join(self.app_android_root, "jni/Application.mk")` should be replaced by

```Python
        if self.use_studio:
            applicationmk_path = os.path.join(self.app_android_root, "app/jni/Application.mk")
        else:
            applicationmk_path = os.path.join(self.app_android_root, "jni/Application.mk")
```

**Comment by minggo** [comment]
yep, it is fixed in v3.14.1
