### ISSUE TITLE
ccui.Editbox singleline setPlaceholderFontSize error

### ISSUE THREAD

**Issue by uhever** [cocos2d/cocos2d-x#17244]
- cocos2d-x version:3.14.1 - lua
- devices test on:iPhone SE 10.1 (14B72)
- developing environments
   - NDK version:
   - Xcode version:8.1 (8B62)
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. create ccui.EditBox
2. setInputMode with cc.EDITBOX_INPUT_MODE_SINGLELINE
3. setPlaceholderFontSize

-[CCUISingleLineTextField ccui_placeholderLabel]: unrecognized selector sent to instance 0x7f8fdd546640

Test Code:
```
local editBox = ccui.EditBox:create(cc.size(350, 70), "res/Image/common/edit_bg.png")
editBox:setInputMode(cc.EDITBOX_INPUT_MODE_SINGLELINE)
editBox:setPosition(cc.p(display.cx, display.cy))
editBox:setPlaceHolder("password")
editBox:setPlaceholderFontSize(32)
sceneWidget:addChild(editBox)
```

**Comment by DavidDeSimone** [comment]
I believe this should have been fixed in https://github.com/cocos2d/cocos2d-x/pull/17127. I'm not sure if that made it into 3.14.1 or not. If not, can you try applying that patch and seeing if the issue persists?

**Comment by summerinsects** [comment]
I found this issue too, and it is still exists in 3.14.1.

**Comment by zilongshanren** [comment]
@uhever @summerinsects 
please give the latest v3 branch a test or manually apply the patch provided by @DavidDeSimone 
Thanks.

**Comment by sail1024** [comment]
maybe you can see the issue #17608, that's my resolution!
