### ISSUE TITLE
Fatal signal 11 (SIGSEGV) between onStop() and onCreate() caused by Label::setTTFConfig

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#17252]
- cocos2d-x version: 3.13.1
- devices test on: Lenovo TAB S8-50F
- developing environments
   - NDK version: 11c

Steps to Reproduce:

The problem occurs only when the App is stopped (onStop), killed and than created (onCreate) again.
The left side on the [Android Lifecyle](http://www.javatpoint.com/images/androidimages/Android-Activity-Lifecycle.png). 

If these steps are executed depends on the system and the currently available resources. 

This is the message from the logs:
`01-18 13:32:04.733 29461-29640/de.truncad.trunapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x24 in tid 29640 (GLThread 1112)`

Cause: 
The problem is caused by Label::setTTFConfig. I added the following code to the HelloWorld Demo and had the same problems: 
```
    std::string label2Font = "fonts/Marker Felt.ttf";
    TTFConfig label_config;
    label_config.distanceFieldEnabled = false;
    label_config.fontSize = 1; 
    label_config.fontFilePath = label2Font;
    label_config.outlineSize = 0;
    
    auto label2 = Label::createWithTTF("asdf", label2Font, 1, Size(10,10));

    label2->setTTFConfig(label_config);
    this->addChild(label2);
```
If  `label2->setTTFConfig(label_config);` is removed it works.

**Comment by minggo** [comment]
> The problem occurs only when the App is stopped (onStop), killed and than created (onCreate) again.

Could you please describe it step by step?

**Comment by minggo** [comment]
I think it is fixed in https://github.com/cocos2d/cocos2d-x/pull/18145.
