### ISSUE TITLE
Current build gives unresolved __imp____iob_func  and __imp___vsnprintf

### ISSUE THREAD

**Issue by markovitch57** [cocos2d/cocos2d-x#17250]
- cocos2d-x version: bleeding edge 2017_01_23
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: 2015 community
   - browser type and version:

Steps to Reproduce:

1.  download as zip from github
2.  run download-deps.py (fills in external folder)
3.  click on build/cocos2d-win32.sln (brings up VS 2015 community edition)
4.  right-click on Solution and choose 'build'
5.  I get: unresolved __imp____iob_func  and __imp___vsnprintf

**Comment by markovitch57** [comment]
Please note that 3.14.1 builds without problems on the same system.

**Comment by minggo** [comment]
I just used VS2015 to compile the project yesterday. Not problem.
