### ISSUE TITLE
libwebsocket with openssl rejected by apple for using non-public API

### ISSUE THREAD

**Issue by thangenius** [cocos2d/cocos2d-x#17257]
I was trying to upgrade libwebsockets (2.1.0) with ssl supported which I downloaded from cocos 3rd party github and using it in my project which is using cocos2d-x 3.8.1. It built and ran successfully in our development environment, but when submitting to Apple to be reviewed, it was rejected because the following reason:

Non-public API usage:

The app references non-public symbols in <our-project-name>: _getcontext, _makecontext, _setcontext

I had to revert back to libwebsockets (1.6.0) without ssl and submitted again. Everything was fine after that. Please help me check if libwebsocket (2.1.0) or openssl use those non-public api or not.

Thanks!

**Comment by dumganhar** [comment]
@thangenius, thanks for your feedback.
`setcontext` is used in `async_posix.h` and `getcontext, makecontext` is used in `async_posix.c`.
`async_posix.h/c` are both in the `openssl-1.1.0c`. I have no idea about this.

**Comment by dumganhar** [comment]
Similar issue: https://github.com/iCepa/Tor.framework/issues/9

Probably, we need to disable `async` and rebuild `openssl` library.

**Comment by thangenius** [comment]
@dumganhar that sounds great! Please notify me when the rebuilt openssl is available, thanks!

**Comment by dumganhar** [comment]
@thangenius, I will.
I also created an issue in `openssl` repo: https://github.com/openssl/openssl/issues/2545
I'm waiting the reply of openssl official.

**Comment by dumganhar** [comment]
@thangenius , I have updated the prebuilt library for openssl.
Please refer to https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/268
You could download the new `.a` files and update opensslconf-`archname`.h header file, then submit to App Store again now.

**Comment by thangenius** [comment]
@dumganhar thanks a lot!

**Comment by thangenius** [comment]
After update the new lib, I noticed there're following log in the console:

"...
NOTICE:  Compiled with OpenSSL support
NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
..."

Does it mean SSL is disabled by default? If it is, how to enable it?

P/S: I did try to open an wss connection and it failed to open connection

**Comment by dumganhar** [comment]
Did you update `cocos/network/WebSocket.h/.cpp`, `external/openssl`, `external/websockets`?
The new `WebSocket.cpp` will use `LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT`. Therefore I guess you use an old version of `WebSocket.cpp/h`.

**Comment by thangenius** [comment]
oh, that's right, thank you!

**Comment by thangenius** [comment]
@dumganhar I now encounter this assert

CCASSERT(!_caFilePath.empty(), "CA file path is empty!");

I wonder why client-side need to specify the ca file path? The web version of our game creates wss connection without having to specify the ca path.

Please help me justify this assertion, thanks!

**Comment by dumganhar** [comment]
Please refer to http://discuss.cocos2d-x.org/t/websocket-supports-ssl-connections/34611

You need a CA file in native since Websocket implementation in libwebsockets is different from browser, native doesn't know where to find the CA file.

**Comment by thangenius** [comment]
I see, thank you!

**Comment by dumganhar** [comment]
@thangenius, does your application pass AppStore now?

**Comment by thangenius** [comment]
@dumhanhar the previous version of our game which uses libwebsocket 1.6.0 w/o SSL is still in review. I will try to use libwebsocket 2.1.0 in the next version and report the result to you soon.

**Comment by dumganhar** [comment]
@thangenius ,thank you. 👍  :)
