### ISSUE TITLE
cmake error Could NOT find WEBSOCKETS (missing: WEBSOCKETS_LIBRARIES  WEBSOCKETS_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by KarenHuang2016** [cocos2d/cocos2d-x#17251]
- cocos2d-x version: b1f2a05
- devices test on: Windows 10
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:
1. git clone https://github.com/cocos2d/cocos2d-x.git D:\Cocos2dx\src
2. cd cocos2dx
3. mkdir build && cd build
4. cmake –G “Visual Studio 14” ..\src

Note: This issue happens from revision b1f2a05. It is due to the name of external libraries are changed. D:\Cocos2dx\src\external\curl\prebuilt\win32\websockets.lib is changed to websockets_static.lib, D:\Cocos2dx\src\external\curl\prebuilt\win32\libcurl_imp.lib is changed to libcurl_a.lib.

cmake log info:
[executing command] cmake -G "Visual Studio 14" ..\src 
-- The C compiler identification is MSVC 19.10.24923.0
-- The CXX compiler identification is MSVC 19.10.24923.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
It appears you are building natively for Windows Desktop with Visual Studio C++
CMake Warning (dev) in cmake/Modules/CocosUsePrebuiltLibs.cmake:
  A logical block opening on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:8 (if)

  closes on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:12 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in cmake/Modules/CocosUsePrebuiltLibs.cmake:
  A logical block opening on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:28 (if)

  closes on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:32 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in cmake/Modules/CocosUsePrebuiltLibs.cmake:
  A logical block opening on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:39 (if)

  closes on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:43 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in cmake/Modules/CocosUsePrebuiltLibs.cmake:
  A logical block opening on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:50 (if)

  closes on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:54 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in cmake/Modules/CocosUsePrebuiltLibs.cmake:
  A logical block opening on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:70 (if)

  closes on the line

    D:/Cocos2dx/src/cmake/Modules/CocosUsePrebuiltLibs.cmake:74 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: opengl32  
-- OpenGL include dirs: 
-- GLEW include dirs: D:/Cocos2dx/src/external/win32-specific/gles/include/OGLES
-- GLFW3 include dirs: D:/Cocos2dx/src/external/glfw3/include/win32
-- Vorbis include dirs: D:/Cocos2dx/src/external/win32-specific/OggDecoder/include
-- MPG123 include dirs: D:/Cocos2dx/src/external/win32-specific/MP3Decoder/include
-- OpenAL include dirs: D:/Cocos2dx/src/external/win32-specific/OpenalSoft/include/AL
-- Freetype include dirs: D:/Cocos2dx/src/external/freetype2/include/win32/freetype2
-- WebP include dirs: D:/Cocos2dx/src/external/webp/include/win32
-- Chipmunk include dirs: D:/Cocos2dx/src/external/chipmunk/include
-- Bullet include dirs: D:/Cocos2dx/src/external/bullet
-- Recast include dirs: D:/Cocos2dx/src/external/recast
-- TinyXML2 include dirs: D:/Cocos2dx/src/external/tinyxml2
-- JPEG include dirs: D:/Cocos2dx/src/external/jpeg/include/win32
-- ZLIB include dirs: D:/Cocos2dx/src/external/win32-specific/zlib/include
-- MINIZIP include dirs: D:/Cocos2dx/src/external/unzip;D:/Cocos2dx/src/external/win32-specific/zlib/include
-- PNG include dirs: D:/Cocos2dx/src/external/png/include/win32
-- TIFF include dirs: D:/Cocos2dx/src/external/tiff/include/win32
CMake Error at cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find WEBSOCKETS (missing: WEBSOCKETS_LIBRARIES
  WEBSOCKETS_INCLUDE_DIRS)
Call Stack (most recent call first):
  cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindWEBSOCKETS.cmake:46 (find_package_handle_standard_args)
  cmake/Modules/CocosBuildHelpers.cmake:44 (find_package)
  cmake/Modules/BuildModules.cmake:131 (cocos_find_package)
  CMakeLists.txt:98 (BuildModules)

-- Configuring incomplete, errors occurred!
See also "D:/Cocos2dx/build_x86/CMakeFiles/CMakeOutput.log".
[command took 10 seconds]

**Comment by Bilalmirza** [comment]
After cloning the repo, please execute download-deps.py to download and install dependencies.

 $ cd cocos2d-x
 cocos2d-x $ python download-deps.py
After running download-deps.py.

 cocos2d-x $ git submodule update --init

have you ran these?

**Comment by KarenHuang2016** [comment]
Sorry for reponding so late. Yes, I have ran these 2 steps beofore executing cmake command.

**Comment by KarenHuang2016** [comment]
After investigation, I found this error is caused by the changes in external/config.json file (revision b1f2a05). This file is used to configure the downloaded external libraries. It upgraded the version of external libraries to “v3-deps-120”. If we download “v3-deps-117.zip” external libraries, there will be no cmake error reported. If we download “v3-deps-120.zip” external libraries, the cmake error will be reported. 
The differences between v3-deps-117.zip and v3-deps-120.zip:
Version of libraries	WEBSOCKETS	Curl
v3-deps-117	
D:\Cocos2dx\src\external\websockets\prebuilt\win32\websockets.lib	  D:\Cocos2dx\src\external\curl\prebuilt\win32\libcurl_imp.lib
v3-deps-120	
D:\Cocos2dx\src\external\websockets\prebuilt\win32\websockets_static.lib
D:\Cocos2dx\src\external\curl\prebuilt\win32\libcurl_a.lib

**Comment by KarenHuang2016** [comment]
This issue has been fixed in revision 8bf29a4. Close this issue.
