### ISSUE TITLE
Update flatbuffers to v1.5

### ISSUE THREAD

**Issue by whitegfx** [cocos2d/cocos2d-x#17269]
Update flatbuffers to the latest version (1.5) please, now we have initial 1.0 release.

Lots of features added, for anyone big time saver.
- can read, write json, populate c++ generated objects from binary or json, send messages to server and all generated from simple fbs schema
- Object API read & write to generated C++ objects.
- php, java support easy server client message interchange with verification
- mutation support

Thank you

**Comment by njh0602** [comment]
I have a problem that is incompatible with the header file generated by the latest version of flatbuffers and the code of existing flatbuffers. So I replaced it with the latest version of the flatbuffers code and removed the code for cocos-studio, and it works fine.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17349/

**Comment by minggo** [comment]
@whitegfx after updating flatbuffer, cocos studio reader is broken. Though we close cocos studio, and don't promise to keep backward compatibility, but can not make it crash when loading .csb files. So i think i have to revert the PR. If you want to use new version of flatbuffer, may be you should do it yourself.
