### ISSUE TITLE
Sprites with ETC1 with alpha texture loses shader after restore from background.

### ISSUE THREAD

**Issue by SBJoker** [cocos2d/cocos2d-x#17266]
- cocos2d-x version: 3.14.1
- devices test on: Samsung TAB A
- developing environments
   - NDK version: r10e (64-bit)

Steps to Reproduce:

1. Launch game with sprites use etc1 with alpha textures.
2. Game should have button to launch another app, let say open browser.
3. Launch other application using button
4. Restore game from background
 Expected result: all sprites lost shader and transparency as well

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17278

**Comment by SBJoker** [comment]
this fix has an potential issue: it will try reload alpha textures for all color textures, even for textures without alpha couple. And will cause crash on restore.
