### ISSUE TITLE
Cannot agree to Cocos License in an automated fashion

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#17262]
- cocos2d-x version: 3.14.1 (but previous versions as well)

When the usage/data collection is shown you must select Y or N. This is a manual selection. There is not a __flag__ one can pass to accept the license agreement automatically. This is handy for those running build servers.

You can modify __.cocos/local_cfg.json__ and set: __"agreement_shown": true__ but a __flag__ would be nice. Some users running build servers have brought this issue up on social media.

**Comment by stammen** [comment]
On my Jenkins build machine I do the following:

Running download-deps.py:

c:/Python27/python.exe download-deps.py -r yes > NUL

Creating a new game project
rm -rf projects/
set ans="Y"
echo %ans%|.\tools\cocos2d-console\bin\cocos new MyGame -p com.your_company.mygame -l cpp -d projects

**Comment by slackmoehrle** [comment]
@stammen Thanks. This is useful too.

**Comment by minggo** [comment]
I mentioned the issue to @natural-law moths ago, but i don't remember why we don't add a flag for it. It seems only have to do it one time, so @natural-law seems it is not a problem.

**Comment by natural-law** [comment]
> You can modify .cocos/local_cfg.json and set: "agreement_shown": true
> It seems only have to do it one time

Yep, this problem can be solved by modify the config `agreement_shown` one time.
@slackmoehrle @minggo I can add an option to skip the manually select step if necessary!

**Comment by minggo** [comment]
@natural-law i think it is better to add a flag for convenient.

**Comment by dumganhar** [comment]
@natural-law , is this issue fixed?

**Comment by natural-law** [comment]
> is this issue fixed?

I have not implement this feature.

**Comment by natural-law** [comment]
I've add an argument `--agreement` for cocos command. Here is the PR of cocos2d-x: #17407
