### ISSUE TITLE
setIntegerForkeys() doesn't work on win32

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#17263]
- cocos2d-x version: 3.14.1
- devices test on: win32 simulator
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: 2015 enterprise
   - browser type and version:

Steps to Reproduce:
int score = 333;
UserDefault::getInstance()->setIntegerForKey("intKey", score);
log("int score %d", UserDefault::getInstance()->getIntegerForKey("intKey"));

always returns 0;//works fine on mac

**Comment by minggo** [comment]
you need to invoke `UserDefault::getInstance()->flush()` to save all keys.

**Comment by Bilalmirza** [comment]
@minggo yes im using flush()
@dumganhar could you have look please? 
same code works perfectly on mac.

I think the problem is with userdefaults

thanks

**Comment by Bilalmirza** [comment]
ill make a testcase first ... sorry about that

**Comment by Bilalmirza** [comment]
hey!

unlike mac version we cant use a space in the key.

for example
UserDefaults::getInstance->setIntegerForKey("WAR MACHINE",2);
.
.
.

once space is used flush() no longer works.

**Comment by dumganhar** [comment]
I reproduced this issue on Win32 by adding space to `key`.
It's an issue indeed.

**Comment by dumganhar** [comment]
@Bilalmirza , we use TinyXML2 to implement UserDefault for win32.
I checked the documentation about what is a valid XML file and I found this:
```
XML Naming Rules
XML elements must follow these naming rules:

Element names are case-sensitive
Element names must start with a letter or underscore
Element names cannot start with the letters xml (or XML, or Xml, etc)
Element names can contain letters, digits, hyphens, underscores, and periods
Element names cannot contain spaces
Any name can be used, no words are reserved (except xml).
```
You could refer to https://www.w3schools.com/xml/xml_elements.asp .
So I guess `key` with space will not be supported in xml.

**Comment by Bilalmirza** [comment]
thanks @dumganhar  :)
