### ISSUE TITLE
Exclude fps images from library (.so) in release build

### ISSUE THREAD

**Issue by whitegfx** [cocos2d/cocos2d-x#17273]
Android library in release mode contain fps images (array with png fps image).
Add define flag to  cc config to use fps images functionality, if not def strip all functions and array for fps functionality.

nm output the last big one entry (28127 is the size):
05060136 00028127 D cc_fps_images_png

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17934
