### ISSUE TITLE
CCNode::visit - Performance issue for pushMatrix

### ISSUE THREAD

**Issue by osknoes** [cocos2d/cocos2d-x#17272]
- cocos2d-x version: 3.3 and 3.14
- devices test on: Iphone 5
- developing environments
   - Xcode version: 7.3.1

Steps to Reproduce:

1. Create a scene with many many nodes ( about 2000 ).
2. Use instruments to profile the scene.
3. About 3-4% of the cpu is used to do the pushmatrix stack operations, although I could not find why this operation is still required. I noticed because the code has a comment saying that the functionality it's actually deprecated, but the code is still there, running, wasting cpu cycles.

"// IMPORTANT:
    // To ease the migration to v3.0, we still support the Mat4 stack,
    // but it is deprecated and your code should not rely on it"

4. See images below for comparison with this code running or commented.

![screen shot 2017-02-03 at 12 06 22](https://cloud.githubusercontent.com/assets/25527653/22589295/e05d91cc-ea09-11e6-93d1-9c2e06052f8e.png)
![screen shot 2017-01-30 at 11 28 01](https://cloud.githubusercontent.com/assets/25527653/22589299/e478210a-ea09-11e6-8d23-d5b03aa9ae3a.png)
![screen shot 2017-01-30 at 11 32 42](https://cloud.githubusercontent.com/assets/25527653/22589302/e66922ac-ea09-11e6-8dfb-49437f3fd826.png)

**Comment by minggo** [comment]
matrix is needed

**Comment by sp-oscar-noguera** [comment]
@minggo could you elaborate more on your response ?

**Comment by minggo** [comment]
Since OpenGL ES 2.0, the developer should manage the matrix themselves. There is not glPushMatrix/glPopMatrix and other similar functions anymore.
