### ISSUE TITLE
Box2D and Collisions

### ISSUE THREAD

**Issue by Sluysarev** [cocos2d/cocos2d-x#17291]
Box2D and Collisions

There is a code

```
std::vector<b2Body *>toDestroy;
	std::vector<MyContact>::iterator pos;

	for (pos = _contactListener->_contacts.begin();
		pos != _contactListener->_contacts.end(); ++pos) {

	MyContact contact = *pos;

	b2Body *bodyA = contact.fixtureA->GetBody();
	b2Body *bodyB = contact.fixtureB->GetBody();
	if (bodyA->GetUserData() != NULL && bodyB->GetUserData() != NULL) {
		CCSprite *spriteA = (CCSprite *)bodyA->GetUserData();
		CCSprite *spriteB = (CCSprite *)bodyB->GetUserData();

		// Sprite A = ball, Sprite B = Block
		if (spriteA->getTag() == 1 && spriteB->getTag() == 2) {
			if (std::find(toDestroy.begin(), toDestroy.end(), bodyB)
				== toDestroy.end()) {
				toDestroy.push_back(bodyB);
			}
		}
		// Sprite B = block, Sprite A = ball
		else if (spriteA->getTag() == 2 && spriteB->getTag() == 1) {
			if (std::find(toDestroy.begin(), toDestroy.end(), bodyA)
				== toDestroy.end()) {
				toDestroy.push_back(bodyA);
			}
		}
	}

	}


```
In the version cocos 2d-x 3.11  it works

In the version cocos 2d-x 3.14.1    I receive an error   vector

```
iterator begin() _NOEXCEPT
		{	// return iterator for beginning of mutable sequence
		return (iterator(this->_Myfirst, this));
		}
```

how do I do that the code worked in version cocos 2d-x 3.14.1 ?

thanks for the help!

-----------------------------------------------------------
- cocos2d-x version: 3.14.1
 - VS version: 2013

**Comment by minggo** [comment]
What's the error? A runtime error or compiling error?

**Comment by Sluysarev** [comment]
The compilation is successful, run-time error.

![error](https://cloud.githubusercontent.com/assets/23049273/22729382/2d9d45c4-edeb-11e6-9062-64463755a883.jpg)

**Comment by Anywhere-Music-Player** [comment]
I also wanted to add: currently I'm converting my game code from ObjC to C++. My game uses Box2d v2.3.2. But when I converted major parts of code in my game with latest cocos2d-x(that time it was 3.13) - I got a lot exceptions for Box2D functions and as I remember I noticed, that Box2D that was downloaded to external folder for cocos2d-x has a lower version that I'm using. So I updated it by downloading latest from GitHub and replaced all files in external folder. After that all works as expected.  But honestly, it was a long time ago, so I don't remember exactly this situation, but probably cocos2d-x external libs point to old Box2D..

**Comment by drelaptop** [comment]
> Box2D hasn't been updated in quite some time. A new production version has yet to be released so far in 2018. We felt GitHub commit f655c603ba9d83 was stable. You can also now use Box2D as a precompiled library.

Box2d have been updated before 3.17 released, reopen this issue if same issues occurs when using 3.17.
