### ISSUE TITLE
ProgressTimer doesn't show after a Sprite, only on Android

### ISSUE THREAD

**Issue by redclock** [cocos2d/cocos2d-x#17292]
- cocos2d-x version: 3.14
- devices test on: Android Galaxy 4S

Steps to Reproduce:
```
    Scene* pScene = Scene::create();
    Director::getInstance()->runWithScene(pScene);
    Node* pNode = Node::create();
    pNode->setPosition(100, 100);
    pScene->addChild(pNode);
    
    //---- remove this line, the pProgress node will show
    pNode->addChild(Sprite::create("border.png"));

    Sprite* pSprite = Sprite::create("progress.png");
    ProgressTimer* pProgress = ProgressTimer::create(pSprite);
    pProgress->setPercentage(100);
    pProgress->setAnchorPoint(pSprite->getAnchorPoint());
    pProgress->setMidpoint(Vec2(0, 0));
    pProgress->setBarChangeRate(Vec2(1, 0));
    pNode->addChild(pProgress);
```

On Android, the pProgress node will not be displayed, while on iOS it is all correct.
If we remove the line 
    
     pNode->addChild(Sprite::create("native/battery.png"));

The pProgress will show correctly.
I think there are some problems when the ProgressTimer is rendered after a Sprite node on Android.

**Comment by minggo** [comment]
I tested in huawei p9 with latests code, can not reproduce it.

**Comment by tdebock** [comment]
I am having a very similar issue in v3.13.
#18784 

This has caused a complete blocker on my Android build. The ProgressTimer nodes show as expected on any iOS device, but are not there on Android devices, Testing with Samsung S7 on Android 7.

**Comment by slackmoehrle** [comment]
@minggo per our conversation yesterday, I will be happy to work on this and report back to you once I have an answer. I have asked @tdebock to share their repo with me as they have a complex game and would be hard to isolate since my simple examples don't seem to reproduce the problem. @tdebock says they may require an NDA to gain access. I can sign that for Xiamen Yagi.
