### ISSUE TITLE
Change std::sort to std::stable_sort in CCEventDispatcher.cpp

### ISSUE THREAD

**Issue by crazyhappygame** [cocos2d/cocos2d-x#17299]
- cocos2d-x version: 3.14
- devices test on: All
- developing environments
   - NDK version: r13
   - Xcode version:
   - VS version: 2015
   - browser type and version:

Steps to Reproduce:

1. Add few listeners to the same node "node"

`cocos2d::Director::getInstance()->getEventDispatcher()->addEventListenerWithSceneGraphPriority(listener, node);`
2. Issue: order of dispatching is undetermined ( std::sort is unstable ) 

Proposed fix:
Change std::sort to std::stable_sort in CCEventDispatcher.cpp

Changes should be done in below files:
```
CCEventDispatcher.cpp(277):        std::sort(globalZOrders.begin(), globalZOrders.end(), [](const float a, const float b){
CCEventDispatcher.cpp(1331):    std::sort(sceneGraphListeners->begin(), sceneGraphListeners->end(), [this](const EventListener* l1, const EventListener* l2) {
CCEventDispatcher.cpp(1356):    std::sort(fixedListeners->begin(), fixedListeners->end(), [](const EventListener* l1, const EventListener* l2) {
```

**Comment by crazyhappygame** [comment]
@minggo Could you fix it?

**Comment by minggo** [comment]
@crazyhappygame sure. You can send a PR to fix it too, why not?

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17321
