### ISSUE TITLE
CMake Visual studio build failed

### ISSUE THREAD

**Issue by MrCapone** [cocos2d/cocos2d-x#17305]
I use CMake build system for build desktop project. This is the easiest way to include third-party libraries in a multi-platform project.  After this commit be43c4210f1dc648a8e8925398fda4cf1b1245ba build audio engine on win32 fails with CMake. Compile error: `cocos2d\cocos\audio/win32/AudioCache.h(35): fatal error C1083: cannot open include file: AL/al.h: No such file or directory`. Seems it wrong include of AL/al.h header file.

- cocos2d-x version: 3.14.1
- devices test on: Windows 10
- developing environments
   - VS version: 2015
   - CMake version: 3.6.2

Steps to Reproduce:

1. create blank cpp project
2. generate visual studio project by `cmake -G 'Visual Studio 14'`
3. try build generated project

**Comment by ZolnerBen** [comment]
The compiler generates a C1083 error when it can’t find a file. Are you sure the file is in the Compiler search path? It could also be because of a wrong version name.Try looking over the compiled files.It may be because your precompiled headers are not yet precompiled.

**Comment by MrCapone** [comment]
@ZolnerBen 
I already found solution and push it as pull request. Problem was in search path, yes. In default project search path is `.../OpenAL/include` and _FindOpenAL.cmake_ generate `.../OpenAL/include/AL` search path.
