### ISSUE TITLE
Sprite with  cannot be stretched if in polygon mode

### ISSUE THREAD

**Issue by nicolechen819** [cocos2d/cocos2d-x#17303]
- cocos2d-x version: 3.14.1

Hi, I see a snippet of code in CCSprite.cpp Sprite::setContentSize function: 
```
if (_renderMode == RenderMode::QUAD_BATCHNODE || _renderMode == RenderMode::POLYGON)
        CCLOGWARN("Sprite::setContentSize() doesn't strech the sprite when using BATCHNODE or POLYGON render modes");
```
Are there other ways to stretch the sprite in polygon mode?

**Comment by minggo** [comment]
@ricardoquesada any idea of this issue?

**Comment by zilongshanren** [comment]
@nichos1983 
I think you could only scale the sprite with polygon mode.

**Comment by nicolechen819** [comment]
I don't think scale is a good solution for scale9Sprite
