### ISSUE TITLE
android js binding CCJavasciptJavaBridge not calls env->DeleteLocalRef

### ISSUE THREAD

**Issue by alonlevylll** [cocos2d/cocos2d-x#17325]
I got JNI max table=512 exception, after a lot of JS jsb.reflection.callStaticMethod calls.

After some investigations, seems like there is no call to DeleteLocalRef for all argument passed through the JNI call.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17338

**Comment by alonlevylll** [comment]
Thanks
