### ISSUE TITLE
cocos android build fails with SSL enabled in libwebsocket

### ISSUE THREAD

**Issue by div5yesh** [cocos2d/cocos2d-x#17343]
- cocos2d-x version: 3.14.1
- devices test on: android
- developing environments
   - NDK version: android-ndk-r13b
   - Xcode version: NA
   - VS version: NA
   - browser type and version: NA

Steps to Reproduce:

1. create a new js project
2. add pre-compiled libwebscoket with SSL enabled
3. compile for android

### I have created js project using cocos2d-x 3.14.1. I get the following errors when I compile the project for android with libwebsocket with SSL support ON (I have also tried using precompiled binaries mentioned in #https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/61):

Also tried with openssl-1.0.2f and openssl-1.0.2g.

divyeshch@divyeshch:~/projects/test314$ **cocos compile -p android --ap android-21 --ndk-mode debug --android-studio**
Building mode: debug
Using Android Studio project : /home/divyeshch/projects/test314/frameworks/runtime-src/proj.android-studio
running: '/home/divyeshch/Android/Sdk/tools/android update project -t android-21 -p /home/divyeshch/projects/test314/frameworks/runtime-src/proj.android-studio/app'

Updated project.properties
Updated local.properties
Updated file /home/divyeshch/projects/test314/frameworks/runtime-src/proj.android-studio/app/proguard-project.txt
Building native...
NDK build mode: debug
running: '/home/divyeshch/Documents/programs/android-ndk-r13b/ndk-build -C /home/divyeshch/projects/test314/frameworks/runtime-src/proj.android-studio/app -j4 NDK_MODULE_PATH=/home/divyeshch/projects/test314/frameworks/cocos2d-x:/home/divyeshch/projects/test314/frameworks/cocos2d-x/cocos:/home/divyeshch/projects/test314/frameworks/cocos2d-x/external NDK_TOOLCHAIN_VERSION=4.9 NDK_DEBUG=1'

make: Entering directory /home/divyeshch/projects/test314/frameworks/runtime-src/proj.android-studio/app'
[armeabi-v7a] StaticLibrary  : libjscocos2d.a
[armeabi-v7a] StaticLibrary  : libcocos2d.a
[armeabi-v7a] StaticLibrary  : liblocalstorage.a
[armeabi-v7a] StaticLibrary  : libcocostudio.a
[armeabi-v7a] StaticLibrary  : libcocosbuilder.a
[armeabi-v7a] StaticLibrary  : libcocos3d.a
[armeabi-v7a] StaticLibrary  : libspine.a
[armeabi-v7a] StaticLibrary  : libui.a
[armeabi-v7a] StaticLibrary  : libcocosdenshion.a
[armeabi-v7a] StaticLibrary  : flatbuffers.a
[armeabi-v7a] StaticLibrary  : libextension.a
[armeabi-v7a] StaticLibrary  : libaudioengine.a
[armeabi-v7a] StaticLibrary  : libbox2d.a
[armeabi-v7a] StaticLibrary  : libnetwork.a
[armeabi-v7a] StaticLibrary  : libcocos2dxinternal.a
[armeabi-v7a] StaticLibrary  : librecast.a
[armeabi-v7a] StaticLibrary  : libbullet.a
[armeabi-v7a] StaticLibrary  : libjscocos2dandroid.a
[armeabi-v7a] StaticLibrary  : libcocos2dandroid.a
[armeabi-v7a] StaticLibrary  : libcpufeatures.a
[armeabi-v7a] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi-v7a/gdbserver
[armeabi-v7a] Gdbsetup       : libs/armeabi-v7a/gdb.setup
[armeabi-v7a] SharedLibrary  : libcocos2djs.so
**/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:71: error: undefined reference to 'SSL_get_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:132: error: undefined reference to 'ERR_error_string_n'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:131: error: undefined reference to 'ERR_get_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:172: error: undefined reference to 'SSL_CTX_set_default_passwd_cb_userdata'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:173: error: undefined reference to 'SSL_CTX_set_default_passwd_cb'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:217: error: undefined reference to 'OPENSSL_init_ssl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:219: error: undefined reference to 'OPENSSL_init_crypto'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:220: error: undefined reference to 'OPENSSL_init_ssl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:223: error: undefined reference to 'CRYPTO_get_ex_new_index'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:225: error: undefined reference to 'CRYPTO_get_ex_new_index'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:247: error: undefined reference to 'SSL_CTX_free'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:249: error: undefined reference to 'SSL_CTX_free'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:284: error: undefined reference to 'ERR_error_string_n'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:283: error: undefined reference to 'ERR_get_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:333: error: undefined reference to 'SSL_read'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:339: error: undefined reference to 'ERR_error_string'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:351: error: undefined reference to 'ERR_error_string'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:380: error: undefined reference to 'SSL_pending'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:417: error: undefined reference to 'SSL_pending'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:435: error: undefined reference to 'SSL_write'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:447: error: undefined reference to 'ERR_error_string'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:470: error: undefined reference to 'SSL_get_fd'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:471: error: undefined reference to 'SSL_shutdown'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:473: error: undefined reference to 'SSL_free'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:543: error: undefined reference to 'SSL_new'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:545: error: undefined reference to 'ERR_error_string'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:553: error: undefined reference to 'SSL_set_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:556: error: undefined reference to 'SSL_set_fd'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:572: error: undefined reference to 'SSL_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:573: error: undefined reference to 'SSL_get_rbio'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:575: error: undefined reference to 'BIO_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:578: error: undefined reference to 'SSL_get_wbio'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:580: error: undefined reference to 'BIO_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:644: error: undefined reference to 'SSL_shutdown'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:645: error: undefined reference to 'SSL_free'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:679: error: undefined reference to 'SSL_accept'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:741: error: undefined reference to 'SSL_CTX_free'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl.c:751: error: undefined reference to 'SSL_CTX_free'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:42: error: undefined reference to 'SSL_get_ex_data_X509_STORE_CTX_idx'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:42: error: undefined reference to 'X509_STORE_CTX_get_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:49: error: undefined reference to 'SSL_get_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:118: error: undefined reference to 'OBJ_sn2nid'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:124: error: undefined reference to 'EC_KEY_new_by_curve_name'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:129: error: undefined reference to 'SSL_CTX_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:130: error: undefined reference to 'EC_KEY_free'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:132: error: undefined reference to 'SSL_CTX_set_options'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:154: error: undefined reference to 'SSL_get_SSL_CTX'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:153: error: undefined reference to 'SSL_CTX_get_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:164: error: undefined reference to 'SSL_get_SSL_CTX'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:172: error: undefined reference to 'SSL_get_servername'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:179: error: undefined reference to 'SSL_set_SSL_CTX'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:301: error: undefined reference to 'TLS_server_method'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:303: error: undefined reference to 'ERR_get_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:309: error: undefined reference to 'SSL_CTX_new'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:311: error: undefined reference to 'ERR_get_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:321: error: undefined reference to 'SSL_CTX_set_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:325: error: undefined reference to 'SSL_CTX_set_options'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:327: error: undefined reference to 'SSL_CTX_set_options'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:329: error: undefined reference to 'SSL_CTX_set_options'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:332: error: undefined reference to 'SSL_CTX_set_cipher_list'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:345: error: undefined reference to 'SSL_CTX_set_session_id_context'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:350: error: undefined reference to 'SSL_CTX_set_verify'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:355: error: undefined reference to 'SSL_CTX_callback_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:365: error: undefined reference to 'SSL_CTX_load_verify_locations'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:389: error: undefined reference to 'SSL_CTX_clear_options'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:392: error: undefined reference to 'SSL_CTX_get_options'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:399: error: undefined reference to 'SSL_CTX_use_certificate_chain_file'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:414: error: undefined reference to 'SSL_CTX_use_PrivateKey_file'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-server.c:434: error: undefined reference to 'SSL_CTX_check_private_key'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:48: error: undefined reference to 'X509_STORE_CTX_get_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:51: error: undefined reference to 'SSL_get_ex_data_X509_STORE_CTX_idx'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:51: error: undefined reference to 'X509_STORE_CTX_get_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:52: error: undefined reference to 'SSL_get_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:58: error: undefined reference to 'X509_STORE_CTX_set_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:64: error: undefined reference to 'SSL_get_ex_data_X509_STORE_CTX_idx'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:64: error: undefined reference to 'X509_STORE_CTX_get_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:65: error: undefined reference to 'SSL_get_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:74: error: undefined reference to 'X509_STORE_CTX_get_error'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:77: error: undefined reference to 'X509_STORE_CTX_get_error_depth'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:78: error: undefined reference to 'X509_verify_cert_error_string'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:120: error: undefined reference to 'SSL_new'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:133: error: undefined reference to 'SSL_get0_param'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:135: error: undefined reference to 'X509_VERIFY_PARAM_set_hostflags'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:137: error: undefined reference to 'X509_VERIFY_PARAM_set1_host'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:142: error: undefined reference to 'SSL_set_verify'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:145: error: undefined reference to 'SSL_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:163: error: undefined reference to 'SSL_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:184: error: undefined reference to 'BIO_new_socket'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:185: error: undefined reference to 'SSL_set_bio'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:194: error: undefined reference to 'BIO_ctrl'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:197: error: undefined reference to 'SSL_set_ex_data'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:216: error: undefined reference to 'SSL_connect'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:310: error: undefined reference to 'SSL_connect'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:383: error: undefined reference to 'SSL_get_verify_result'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:444: error: undefined reference to 'TLS_client_method'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:453: error: undefined reference to 'SSL_CTX_new'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:468: error: undefined reference to 'SSL_CTX_set_cipher_list'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:474: error: undefined reference to 'SSL_CTX_set_default_verify_paths'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:479: error: undefined reference to 'SSL_CTX_load_verify_locations'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:488: error: undefined reference to 'SSL_CTX_load_verify_locations'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:508: error: undefined reference to 'SSL_CTX_use_certificate_chain_file'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:523: error: undefined reference to 'SSL_CTX_use_PrivateKey_file'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-client.c:534: error: undefined reference to 'SSL_CTX_check_private_key'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-http2.c:80: error: undefined reference to 'SSL_select_next_proto'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-http2.c:96: error: undefined reference to 'SSL_CTX_set_next_protos_advertised_cb'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-http2.c:99: error: undefined reference to 'SSL_CTX_set_alpn_select_cb'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-http2.c:116: error: undefined reference to 'SSL_get0_alpn_selected'
/home/divyeshch/projects/libwebsocket/libwebsockets/contrib/libwebsockets/lib/ssl-http2.c:119: error: undefined reference to 'SSL_get0_next_proto_negotiated'**
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libcocos2djs.so] Error 1
make: Leaving directory `/home/divyeshch/projects/test314/frameworks/runtime-src/proj.android-studio/app'
Error running command, return code: 2.

**Comment by dumganhar** [comment]
Hi, I guess you didn't link with openssl static library.
You probably need to link with `libssl.a` and `libcrypto.a` like which in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/v3/openssl/prebuilt/android/Android.mk

**Comment by div5yesh** [comment]
I have linked the libraries. @dumganhar please take a look. This is my repository [https://github.com/div5yesh/cocositup](https://github.com/div5yesh/cocositup)

**Comment by div5yesh** [comment]
I'm thinking of compiling libwebsocket with wolfssl, instead of openssl as I suspect there are issues in openssl header files, but wolfssl also creates problem as mentioned in https://github.com/warmcat/libwebsockets/issues/741.

**Comment by lws-team** [comment]
There are no issues with lws and openssl afaik.

As @dumganhar said it looks like you failed to link to the ssl libs,

**Comment by div5yesh** [comment]
My Android.mk file is same as [https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/v3/openssl/prebuilt/android/Android.mk](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/v3/openssl/prebuilt/android/Android.mk). @dumganhar am I missing something??

**Comment by dumganhar** [comment]
@div5yesh, 
Where did you include this Android.mk?
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/8dcfc483b62c8b7b7eaf29754ee5ecfa89814ddd/websockets/prebuilt/android/Android.mk#L12

Are your libwebsockets link ssl library like the above Android.mk?

**Comment by div5yesh** [comment]
Yes @dumganhar libwebsockets does link ssl just as you have mentioned. This is my [Android.mk](https://github.com/div5yesh/cocositup/blob/master/frameworks/cocos2d-x/external/websockets/prebuilt/android/Android.mk#L12) file inside **"cocos2d-x/external/websockets/prebuilt/android/"** folder.

**Comment by dumganhar** [comment]
@div5yesh, you have missed something in `cocos/Android.mk`
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/Android.mk#L333

**Comment by div5yesh** [comment]
@dumganhar Added ssl import in cocos/Android.mk. It worked. Thanks a lot.

**Comment by dumganhar** [comment]
@div5yesh , good to know it works for you now. So I closed this issue.
