### ISSUE TITLE
Why does 'EditBoxImplCommon' have the same member variable with 'EditBox'?

### ISSUE THREAD

**Issue by summerinsects** [cocos2d/cocos2d-x#17346]
Why does 'EditBoxImplCommon' have the same member variable with 'EditBox'?
These are

    EditBox::InputMode    _editBoxInputMode;
    EditBox::InputFlag    _editBoxInputFlag;
    EditBox::KeyboardReturnType  _keyboardReturnType;
    cocos2d::TextHAlignment _alignment;
    std::string _text;
    std::string _placeHolder;   
    Color4B _colText;
    Color4B _colPlaceHolder;
    int   _maxLength;

Why not delete them?

**Comment by zilongshanren** [comment]
@summerinsects 
I think it's a design flaw, the member variables could be merged into EditBoxCommon.
If you could do this and send a PR, I'm glad to help and merge.
thanks.

**Comment by summerinsects** [comment]
@zilongshanren  I will have a try
