### ISSUE TITLE
能否提供 libsimulator.xcodeproj 下的Protos.proto protobuf原文件，现在没办法用其他版本的protobuf

### ISSUE THREAD

**Issue by bluce** [cocos2d/cocos2d-x#17355]
- cocos2d-x version:3.13.1
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. cocos2d-x libsimulator.xcodeproj 
2.

**Comment by minggo** [comment]
simulator is used for cocos studio, as cocos studio is canceled, i don't have the files too.

**Comment by pumpkye** [comment]
我反推了Protos.proto
https://github.com/pumpkye/Cocos_Protos
