### ISSUE TITLE
CCBAnimationManager bug fix for CCLabelBMFont color animation

### ISSUE THREAD

**Issue by fgig77** [cocos2d/cocos2d-x#1736]
I fixed a bug caused by animating color on a 'CCLabelBMFont' in CocosBuilder. In CCBAnimationManager::setAnimatedProperty(), the node is being cast into a CCSprite instead of CCRGBAProtocol.

((CCSprite*)pNode)->setColor(color->getColor());

should be:

(dynamic_cast<CCRGBAProtocol*>(pNode))->setColor(color->getColor());

**Comment by minggo** [comment]
Thank you.

**Comment by minggo** [comment]
It is fixed in this commit https://github.com/cocos2d/cocos2d-x/pull/1743
