### ISSUE TITLE
Bug fix for CCLayerColor & CocosBuilder

### ISSUE THREAD

**Issue by fgig77** [cocos2d/cocos2d-x#1737]
So I found that Cocosbuilder assumes a default CCLayerColor opacity of 255, but Cocos2dx defaults to 0. This causes CCLayerColors created in Cocosbuilder to not display if they have a opacity of 255. I fixed this by changing the following:

bool CCLayerColor::init()
{
CCSize s = CCDirector::sharedDirector()->getWinSize();
return initWithColor(ccc4(0,0,0,0), s.width, s.height);
}

To:

bool CCLayerColor::init()
{
CCSize s = CCDirector::sharedDirector()->getWinSize();
return initWithColor(ccc4(0,0,0,255), s.width, s.height);
}

This is similar to what CCLayerGradient already does.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2664
