### ISSUE TITLE
Bug: Memory leak with CCBAnimationManager

### ISSUE THREAD

**Issue by fgig77** [cocos2d/cocos2d-x#1738]
The CocosBuilderTest example will leak layers when going into and out of the AnimationsTestLayer. This is because AnimationsTestLayer keeps a reference to CCBAnimationManager and CCBAnimationManager keeps a reference to AnimationsTestLayer. It's a circular dependency. Neither class will get it's destructor called because the reference count never drops.

For more info:
http://www.cocos2d-x.org/boards/6/topics/18169

**Comment by TimothyZhang** [comment]
we may use weak reference, if pull request(https://github.com/cocos2d/cocos2d-x/pull/2476) would been applied.

**Comment by godyZ** [comment]
@fgig77 Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
