### ISSUE TITLE
SimpleAudioEngine not playing effect after openURL on iOS

### ISSUE THREAD

**Issue by pineoc** [cocos2d/cocos2d-x#17386]
- cocos2d-x version: 3.13.1
- devices test on: iPhone 5s, 6s
- developing environments
   - NDK version: r12b
   - Xcode version: 8.2.1

Steps to Reproduce:

1. i just add this code on button listener function, and click.
```cpp
Application::getInstance()->openURL("fb://page/172875553094691");
```
2. effect sounds works well. but sometimes not working on iOS.

I Think something issues on focusing view or audioEngine file release.
And i test 
```cpp
experimental::AudioEngine::play2d("file.mp3");
```
not working neither.
How can i solve it?

**Comment by pineoc** [comment]
I solve this problem some trick.
Just add this code and reload files.
```cpp
SimpleAudioEngine::getInstance()->end();
```
But This code not good because of loading time.
I guess this problem maximum limit of sound file pool

**Comment by dumganhar** [comment]
Do you use `SimpleAudioEngine` & `AudioEngine` both at your game?
If so ,it will cause this issue.

**Comment by pineoc** [comment]
Nope. I use only ```SimpleAudioEngine``` at first time and error occurred.
I used AudioEngine test this error.

**Comment by dumganhar** [comment]
@pineoc, thanks for your feedback. If you could provide a demo for reproducing this  issue, I will try to check it out. :)

**Comment by pineoc** [comment]
Okay, I will make test project same environment and share it.

**Comment by rainfallljs** [comment]
@dumganhar have you solved this issue?
I have the similar issue: after back to game, SimpleAudioEngine  playEffect not work on iOS

**Comment by dumganhar** [comment]
@rainfallljs , if you could reproduce the issue, could you please test the issue on v3.15 to check out whether it was fixed?

**Comment by shooga** [comment]
how to reproduce:
* just put the app into background when SimpleAudioEngine is not yet initialized, then applicationDidEnterBackground will call SimpleAudioEngine::getInstance()->pauseBackgroundMusic(), and then getInstance() will try to init, finally [CDSoundEngine init] will fail, and funtioning_ flag wil keep NO. This flag will cause the effect not work.

**Comment by mr746866** [comment]
I am facing similar issue for Cocos2D-X 3.14.1 on my iPhone 6s. Whenever the app goes in background and comes to foreground again, sound effects stop working. However, background musics work perfectly.

**Comment by mr746866** [comment]
Solved the problem by excluding the following lines from `AppDelegate::applicationDidEnterBackground()` & `AppDelegate::applicationWillEnterForeground()` respectively. The comments that are present in default are misleading.

`CocosDenshion::SimpleAudioEngine::getInstance()->pauseBackgroundMusic();`

`CocosDenshion::SimpleAudioEngine::getInstance()->resumeBackgroundMusic();`

**Comment by pineoc** [comment]
@mr746866 you solve the problem like this?
remove `//` on pause, resume?
```cpp
// This function will be called when the app is inactive. Note, when receiving a phone call it is invoked.
void AppDelegate::applicationDidEnterBackground() {
    Director::getInstance()->stopAnimation();

    // if you use SimpleAudioEngine, it must be paused
    CocosDenshion::SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
}

// this function will be called when the app is active again
void AppDelegate::applicationWillEnterForeground() {
    Director::getInstance()->startAnimation();

    // if you use SimpleAudioEngine, it must resume here
    CocosDenshion::SimpleAudioEngine::getInstance()->resumeBackgroundMusic();
}
```

**Comment by shooga** [comment]
i think just comment out the pause/resume line might cause crash on some device
----------------------
i solve this problem by:
1. AppDelegate::applicationDidFinishLaunching() add following code
    // init audio engine
    SimpleAudioEngine::getInstance();

2. in file SimpleAudioEngine.mm,  add funtion
static void static_init_engine()
{
    [SimpleAudioEngine sharedEngine];
}

and call it in SimpleAudioEngine::getInstance()
    if (! s_pEngine)
    {
        s_pEngine = new (std::nothrow) SimpleAudioEngine();
        static_init_engine();  // <<<<<<<<<<< add this line
    }
    
    return s_pEngine;
