### ISSUE TITLE
CCBAnimationManager doesn't support kCCBKeyframeEasingInstant

### ISSUE THREAD

**Issue by fgig77** [cocos2d/cocos2d-x#1739]
kCCBKeyframeEasingInstant currently uses the kCCBKeyframeEasingLinear code path.  This causes keyframes flagged as "Instant" easing to still lerp.

See CCBAnimationManager::getEaseAction()

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2663
