### ISSUE TITLE
Performance issue of cocos2d-x

### ISSUE THREAD

**Issue by gestern** [cocos2d/cocos2d-x#17394]
- cocos2d-x version: 3.11, 3.12, 3.13, 3.14, 3.14.1
- devices test on: iPad Air, iPhone 6s
- developing environments
   - Xcode version: 8.2.1

Steps to Reproduce:

1. Create new project from scratch for iOS in console with language type CPP ``./cocos new -p <package> -d <directory> -l cpp Test``
2. Launch just created project inside xCode with real iOS device;
3. Follow to Debug navigator view (see below):

## iPad Air

- Energy Impact: **Very High**, **Utilization in red area** - it is so bad for project from scratch and do nothing, but having high energy impact!
- **CPU**: 12% - for one static sprite and "Hello world" - this is unacceptable.

## iPhone 6s
- Energy Impact: **Low**, **Utilization in green area** - it is good, but
- **CPU**: 13-14%. - very bad

I'm using cocos2d-x for 6 years but I'm never faced the problems with performance like these.

**Comment by dumganhar** [comment]
Did you mean the versions before v3.11 don't have the issue you said?

**Comment by dumganhar** [comment]
Thanks for your reply, I will check this issue.

**Comment by gestern** [comment]
Just finished testing with 3.6, so here is results:
## Pad Air
- Energy Impact: **Very High/High** - Utilization between yellow and red areas (more better than 3.1X )
- **CPU:** 10%-11%

## iPhone 6s
- Energy Impact: **Low**
- **CPU:** 10%

**Comment by gestern** [comment]
I've finished testing with **iPhone 4** device, and several versions of cocos2d-x (including 2.x version). And the problem reproduced everywhere. It is awful - turn over in my mind a bit before when I tried to downgrade xCode from 8.2.1 to 7.3.1. And... **problem is gone**. Wow! Then I'm roll back again to 8.2.1 and checking with simulating environment on swift language - and all devices (except iPhone 4) showed 1-2% payload and low utilization level. 
Looks like the xCode 8 pretends that he hates anything except Swift and telling to developers "let's do your products in bitcode".

The bug has been figured out and it may be closed.

**Comment by dumganhar** [comment]
@gestern , thanks for your detailed tests.
Good to know it's something about Xcode version and programming languages except `swift`.
Therefore, shouldn't we rely on the `Energy Impact` & `time profiling` in Xcode 8.2.1 to find out performance issues?

**Comment by gestern** [comment]
@dumganhar I think we shouldn't do so. Because Xcode 8.2.1 shows incorrect result with cocos2d-x 2.x.
