### ISSUE TITLE
Crash on Android after restore from background in Texture2D::updateWithData

### ISSUE THREAD

**Issue by SBJoker** [cocos2d/cocos2d-x#17390]
- cocos2d-x version: 3.14.1
- devices test on: Samsung Galaxy Tab A
- developing environments
   - NDK version: r10e (64-bit)

Description:
Game crashes if it was restored from background on Android, and game state was restored.
Callstack:
1. Texture2D::updateWithData()
2. FontAtlas::prepareLetterDefinitions()

Steps to Reproduce:

1. Game should use TTF font for labels. 
2. Send game to background, force system to free game's resources to force resources reloading on restore from background. (Best solution with 100% success: button with an "open Application's page on Google Play" action, and use "launch" button on that page to return to game).
3. Restore game from background
4. Game should crash on first attempt to use TTF Fonts.

Key step to reproduce crash - force game reload resources.

**Comment by SBJoker** [comment]
Maybe label's text should be updated to get crash

**Comment by SBJoker** [comment]
Fixed it by myself. Here are attached modifies files.
Also it fix for another issue:
https://github.com/cocos2d/cocos2d-x/issues/17167
[CCFontAtlas.zip](https://github.com/cocos2d/cocos2d-x/files/793061/CCFontAtlas.zip)

**Comment by dumganhar** [comment]
@SBJoker , thanks for investigating the issue.
How about submit a Pull Request? In that case, we could review it on the github.

**Comment by nicolechen819** [comment]
Hi developers, can you review the solution? We also got lots of it. Thanks so much!

**Comment by enrevol** [comment]
Any new updates on this issue?

**Comment by minggo** [comment]
@SBJoker could you please add some comment of the PR: https://github.com/cocos2d/cocos2d-x/pull/18145? @newnon sent a PR based on your modification.

Thanks.
