### ISSUE TITLE
lua范例(cocos3.14.1)运行出错

### ISSUE THREAD

**Issue by Awaken929** [cocos2d/cocos2d-x#17402]
- cocos2d-x version:3.14.1
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:8.2.1
   - VS version:
   - browser type and version:

Steps to Reproduce:
运行lua范例时出现个错误，不知道怎么解决
1. 报错地方 string(类)->__zero()(函数)->__a[__i] = 0;(函数具体地方)
![b](https://cloud.githubusercontent.com/assets/5218377/23245993/90ece076-f9cb-11e6-8884-21e2f2d1f866.png)
![a](https://cloud.githubusercontent.com/assets/5218377/23245994/90f6bd94-f9cb-11e6-9869-b6d67da375de.png)

**Comment by dumganhar** [comment]
It's a known issue while running lua project in ios simulator using xcode 8.2.
There isn't an available solution for this, therefore, please debug your game on real ios device.

**Comment by dumganhar** [comment]
You could refer to https://github.com/cocos2d/cocos2d-x/issues/17043,
It's similar issue, so I closed this one. Please discuss in that thread.
