### ISSUE TITLE
macOS FileUtils::getWritablePath() uses Ducuments directory

### ISSUE THREAD

**Issue by MrCapone** [cocos2d/cocos2d-x#17417]
When you call `cocos2d::FileUtils::getInstance()->getWritablePath()` on macOS it returns `NSDocumentDirectory` [code link](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/apple/CCFileUtils-apple.mm#L239). I think its not good idea use User's Documents directory to store game data and files. I, as a mac user, do not want to fill my Documents folder with service data.
On windows cocos uses AppData dirrectory, on macOS analog of this directory is Application Support folder. Maybe you should change code for macOS target like this:
`[NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);`
also i think it's good idea append game name to end of path, to create folder with game name.

**Comment by dumganhar** [comment]
I was confused about this too.
I remember when I debugged `AssetsManagerEx` somedays ago, I passed in `getWritablePath` as the storage path, `AssetsManagerEx` will delete all files and directories in the storage path, then my all documents were gone. :(

**Comment by dumganhar** [comment]
I wanna know is there a place only owned by current application?

**Comment by 1scaR1** [comment]
If you enable App Sandbox in capabilities for application it will use special sandboxed directory(returned by `cocos2d::FileUtils::getInstance()->getWritablePath()`) like:
/Users/your_user/Library/Containers/com.yourcompany.app/Data/Documents/

**Comment by MrCapone** [comment]
@dumganhar go to `~/Library/Application Support` folder on your mac. You will see that all apps create their folder there and use it to store service data.

**Comment by MrCapone** [comment]
Example:
```
std::string FileUtilsApple::getWritablePath() const
{
    if (_writablePath.length())
    {
        return _writablePath;
    }

    // save to application support folder
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
    NSString *applicationSupportDirectory = [NSString stringWithFormat:@"%@/%@/",[paths objectAtIndex:0], [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"]];
    
    std::string strRet = [applicationSupportDirectory UTF8String];
    return strRet;
}
```

`getWritablePath()` will return /Users/_your_user_name_/Library/Application Support/_your_app_name_/

**Comment by dumganhar** [comment]
@MrCapone , thanks for the code, this change will break the compatibility on macOS.
Old game will lost its data if upgrading to the latest engine.

@1scaR1 , 
> If you enable App Sandbox in capabilities for application it will use special sandboxed directory(returned by cocos2d::FileUtils::getInstance()->getWritablePath()) like:
/Users/your_user/Library/Containers/com.yourcompany.app/Data/Documents/

Do you mean current implementation could not be changed, just enable App Sandbox is enough? If so, is there any documentation which describes this feature?

**Comment by MrCapone** [comment]
@dumganhar i just tested my example, it's not works. Seems app does not have write access to Application Support folder. 
I also tested solution with App Sandbox. It works fine, but it will break the compatibility with old versions of engine too.
[Official apple documentation about App Sandbox](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html)
Maybe it's not better solution. I will try search in official apple guidelines.

**Comment by Bilalmirza** [comment]
@MrCapone how do you fill in /your_user/ ?

**Comment by MrCapone** [comment]
@Bilalmirza 

`NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);`
`[paths objectAtIndex:0]` will return full path to _Application Support_ folder for current user. But it seems you cant just write to this folder.

**Comment by MrCapone** [comment]
I found why my code does not working. On mac you need create folder and then use it as writable path. Updated version of code:
```
std::string FileUtilsApple::getWritablePath() const
{
    if (_writablePath.length())
    {
        return _writablePath;
    }
    
    // save to application support folder
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
    NSString *applicationSupportDirectory = [NSString stringWithFormat:@"%@/%@/",[paths objectAtIndex:0], [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"]];
    
    NSError * error = nil;
    [[NSFileManager defaultManager] createDirectoryAtPath:applicationSupportDirectory withIntermediateDirectories:YES attributes:nil error:&error];
    
    if (error != nil) {
        NSLog(@"error creating directory: %@", error);
    }
    
    std::string strRet = [applicationSupportDirectory UTF8String];
    return strRet;
}
```
maybe it will be helpful for someone.

**Comment by minggo** [comment]
Yep, for Mac OS, it is not a good idea to write file in documents folder. But as @dumganhar said it will break compatibility though there are not many developers release game on Mac. So i will close this issue.

**Comment by yangyp-yes** [comment]
When I tested the download, my documents folder was cleared!
