### ISSUE TITLE
Does win10 platform support Lua and JS?

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17418]
A developer reported that he didn't know how to create a win10 project with Lua support.

Currently, I only find `proj.win10` folder in `cpp` tests and `cpp` template.
It seems it is missing in `lua` & `js` testcase and template projects.

@stammen , could you please take some time to answer this question?

**Comment by stammen** [comment]
@dumganhar win10 platform currently only supports c++.

**Comment by stammen** [comment]
@dumganhar It might be possible to create a  Windows Store cocos2d-x lua or js app by using the Win32 lua or js project templates and then converting the Win32 app to a Windows 10 Store app with the [Desktop App Converter](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter)

**Comment by dumganhar** [comment]
Got it. Thank you
