### ISSUE TITLE
websocket cant connected in android

### ISSUE THREAD

**Issue by Usopp-Code** [cocos2d/cocos2d-x#17419]
- cocos2d-x version:3.4 
- devices test on: samsung sm-c5000
- developing environments
   - NDK version: r10d
   - Xcode version:
   - VS version:
   - browser type and version:

hi
i upgrade my code by https://github.com/cocos2d/cocos2d-x/pull/17172
then compile well in windows and ios, and connected well
in android, i can't connect to my server
i got this log

02-28 12:26:09.912 10213 10464 D WebSocket.cpp: NOTICE: Initial logging level 911
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: NOTICE: Libwebsockets version: 2.1.0 james@James-Chen.local-v3.4-139-gbdcf7f8
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: NOTICE: IPV6 compiled in and enabled
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: NOTICE: libev support not compiled in
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: NOTICE: libuv support not compiled in
02-28 12:26:09.912 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: NOTICE:  Threads: 1 each 1024 fds
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: NOTICE:  mem: platform fd map:  4096 bytes
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: NOTICE:  Compiled with OpenSSL support
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: NOTICE:  mem: per-conn:          376 bytes + protocol rx buf
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: protocol: ws, host: 123.207.10.90, port: 21000, path: ?sign=MaybeYouHaveGotThisSignWithWireSharkOrIDA
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 on
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: NOTICE: lws_protocol_init
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: 
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) Unhandled websocket event: 32
02-28 12:26:09.922 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) Unhandled websocket event: 29
02-28 12:26:09.942 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) Unhandled websocket event: 24
02-28 12:26:09.952 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) onConnectionError, state: 0 ...
02-28 12:26:09.952 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) onConnectionClosed, state: 2 ...
02-28 12:26:09.952 10213 10464 D WebSocket.cpp: onConnectionClosed, WebSocket (0x934c83e4) is closing by server.
02-28 12:26:09.952 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) onConnectionClosed DONE!
02-28 12:26:09.952 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) Unhandled websocket event: 45
02-28 12:26:09.952 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) Unhandled websocket event: 33
02-28 12:26:09.952 10213 10464 D WebSocket.cpp: WebSocket (0x934c83e4) onConnectionClosed, state: 3 ...
02-28 12:26:09.972 10213 10240 D cocos2d-x debug info: [LUA-print] server﹎error    1

is something wrong?

**Comment by Usopp-Code** [comment]
reason is  “HS: URI missing”

**Comment by dumganhar** [comment]
What's the URL did you connect to ?

**Comment by lee2doge** [comment]
i found the problem.
my URL is ws://xx.xx.xx.xx:xxxx?sign=xxxxxxxxx
in android the URI resolved to sign=xxxxxxxxx
but, in other platform is ok

**Comment by Usopp-Code** [comment]
i found the problem.
my URL is ws://xx.xx.xx.xx:xxxx//?sign=xxxxxxxxx
in android the URI resolved to ?sign=xxxxxxxxx
but, in other platform is /?sign=xxxxxxxxx

**Comment by dumganhar** [comment]
Hi, please try to use WebSocket.h/.cpp in v3 branch.
I have modified some code after the refactoring pull request.

https://github.com/cocos2d/cocos2d-x/pull/17342
https://github.com/cocos2d/cocos2d-x/pull/17381
https://github.com/cocos2d/cocos2d-x/pull/17379

**Comment by Usopp-Code** [comment]
thank you very much

**Comment by dumganhar** [comment]
It's basically because this https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/WebSocket.cpp#L870

`lws_parse_uri` will modify the input parameter `url`.

**Comment by Usopp-Code** [comment]
yep,  it is running well after i fix my URL.
thx

**Comment by dumganhar** [comment]
OK. So I closed this issue since it was fixed in the upstream.

**Comment by qcwgithub** [comment]
这 BUG 我 TM 都能碰上……
