### ISSUE TITLE
runAction is not executed under setonEnterTransitionDidFinishCallback when returning a TransitionFade* on HelloWorld::createScene()

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#17428]
- cocos2d-x version: v3.14
- devices test on: LG G3 Stylus (Android), Lenovo x220T (Linux)
- developing environments
   - NDK version: r13
   - GCC version: 6.3.1

Steps to Reproduce:

1. Create a new C++ project and replace  `Classes/HelloWorldScene.cpp` template with the attached code: [HelloWorldScene.cpp.txt](https://github.com/cocos2d/cocos2d-x/files/811773/HelloWorldScene.cpp.txt)
2. After setting the `setonEnterTransitionDidFinishCallback` callback on HelloWorld::create(), the runAction method will not be executed for the created scene under the previously mentioned callback after Director::getRunningScene gets called if we return a TransitionFade* object created from that scene. (See the code and messages).

**Workaround**
I'm not quite sure if the above is considered a bug, but creating a TransitionFade object first and then setting the callbacks and node tags works well.

**Comment by minggo** [comment]
> I'm not quite sure if the above is considered a bug, but creating a TransitionFade object first and then setting the callbacks and node tags works well.

Could you please describe it in more detail? Paste some codes is better.

**Comment by minggo** [comment]
the reason is that `TransitionFade` is destroyed after `setonEnterTransitionDidFinishCallback` is invoked.

**Comment by Rubonnek** [comment]
Thanks a lot -- this had been bugging me for a while.
