### ISSUE TITLE
functions.lua "iskindof" returns wrong result

### ISSUE THREAD

**Issue by qingwabote** [cocos2d/cocos2d-x#17421]
- cocos2d-x version: 3.13.1
- devices test on: mac desktop

Steps to Reproduce:

1. define class A = class("A", cc.Node) and its sub class B = class("B", A)
2. instance b = B.new()
3. iskindof(b, "A") return false

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17785
