### ISSUE TITLE
websocket connected bug

### ISSUE THREAD

**Issue by NathanLi** [cocos2d/cocos2d-x#17427]
- cocos2d-x version: 3.14
In JSB the webSocet connect was failed.

ws://domain.com/abc/d

It will parse the path is: abc/d

The correct path is: /abc/d

**Comment by dumganhar** [comment]
Did you use the version on v3 branch rather than v3.14?

**Comment by NathanLi** [comment]
It's no problem in v3.13

**Comment by dumganhar** [comment]
I confirm that this issue doesn't exist in v3.14.1 and it's a bug in v3 branch.
So I guess you're using v3 branch to reproduce this issue, right?

**Comment by NathanLi** [comment]
Maybe you are right. I revert my code to v3.13.

**Comment by dumganhar** [comment]
fixed it at https://github.com/cocos2d/cocos2d-x/pull/17455
