### ISSUE TITLE
Android build freezing when ogg audio file is played in latest audioEngine

### ISSUE THREAD

**Issue by Usopp-Code** [cocos2d/cocos2d-x#17426]
cocos2d-x version:3.4
devices test on: 华为麦芒5（MLA-AL10) and 乐视x620
developing environments
NDK version: r10d
Xcode version:
VS version:
browser type and version:

i use the latest version audioEngine in github branch v3, and i use ogg file in android.
it is random freezing when i call the play2d/stopall.
i dont know how to Reproduce it.
because never happen again when i dump log.
it is happen three times with in two hours in two device. 
i will keep follow this question.
if i got the crash log, i will notity ASAP.

**Comment by Usopp-Code** [comment]
i try to use mp3 file in android.
but in sm-c5000, it is stuck main thread when i call preload.

**Comment by Usopp-Code** [comment]
vivo X7 also freezing

**Comment by dumganhar** [comment]
Please attach the log of freezing.

**Comment by Usopp-Code** [comment]
i ’m trying

**Comment by dumganhar** [comment]
@lee2doge , any update?

**Comment by dumganhar** [comment]
Bump !!!

**Comment by pablorealini** [comment]
Hi @dumganhar , 
I don't know if we are currently having this same issue.

But we are testing our game on a Samsung Galaxy S7 with Android 7.0 and no sound is being played and each time try to play a sound effect the game freeze for 2 seconds.

Could this be the same issue? we are currently using v3.14 but we will do some tests with v3.15

**Comment by pablorealini** [comment]
My mistake! We are testing this in v3.13.1

This is the console log:

`
05-17 13:55:15.670  9261  9286 V cocos2d-x debug info: play2d, _audioPlayers.size=1
05-17 13:55:15.670  9261  9286 V AudioPlayerProvider: (assets/KR4_Android/Sounds/Fx/Commons/kr4_selection.ogg) file size: 5787
05-17 13:55:15.670  9261  9286 V AudioPlayerProvider: audio (assets/KR4_Android/Sounds/Fx/Commons/kr4_selection.ogg) is being preloaded, add to callback vector!
05-17 13:55:15.670  9261  9286 V AudioPlayerProvider: FileInfo (0xc99df960), Waiting preload (assets/KR4_Android/Sounds/Fx/Commons/kr4_selection.ogg) to finish ...
05-17 13:55:17.670  9261  9286 V AudioPlayerProvider: FileInfo (0xc99df960), Waitup preload (assets/KR4_Android/Sounds/Fx/Commons/kr4_selection.ogg) ...
05-17 13:55:17.670  9261  9286 E AudioPlayerProvider: FileInfo (0xc99df960), preloadEffect (assets/KR4_Android/Sounds/Fx/Commons/kr4_selection.ogg) failed
`

**Comment by pablorealini** [comment]
Hi, we tested this on version 3.15 and it seems to be working.

**Comment by drelaptop** [comment]
As @pablorealini said , `tested this on version 3.15 and it seems to be working.` and what your feedback occurs on 3.4. so I think it's a out-dated issue, just close this. 

please reopen it if you found same issue on latest code @lee2doge
