### ISSUE TITLE
runWithScene(TransitionSlideInT) and onEnterTransitionDidFinish trouble

### ISSUE THREAD

**Issue by aldoshkind** [cocos2d/cocos2d-x#17442]
- cocos2d-x version: github v3 branch commit c69d14c32ecd5f23b071f091e66ba1f4d4ed235a
- devices test on: Xubuntu GNU/Linux 16.04.2
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. inherit `Scene` (I just modified HelloWorld);
2. overload `onEnterTransitionDidFinish()`;
3. do `director->runWithScene(TransitionSlideInT::create(1.0, HelloWorld::createScene()));`;
4. wait forever for `onEnterTransitionDidFinish()` being called;

TransitionFade works fine.

reason is here:
CCTransition.cpp:549:
```
	ActionInterval* inAction = easeActionWithAction(in);
	ActionInterval* outAction = Sequence::create
	(
		easeActionWithAction(out),
		CallFunc::create(CC_CALLBACK_0(TransitionScene::finish,this)),
		nullptr
	);
    _inScene->runAction(inAction);
    _outScene->runAction(outAction);
```

`_inScene` is created in `TransitionScene::initWithDuration` and somehow destructed (???) before `CC_CALLBACK_0(TransitionScene::finish,this)` gets called, thus it is never called.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17466
