### ISSUE TITLE
windows android studio compile with lua error(path too long)

### ISSUE THREAD

**Issue by owen200008** [cocos2d/cocos2d-x#17444]
lua compile for android studio error

E:\project\testapp_stable\client\frameworks\cocos2d-x\cocos\scripting\lua-bindings\manual\platform\android\jni\Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp

change to 1.cpp and change android.mk is ok. it no long 260 but fail create .o and .o.d
add 
LOCAL_SHORT_COMMANDS := true
APP_SHORT_COMMANDS := true
is not valid for this

**Comment by minggo** [comment]
yep, it file name is a little long, but i is not 260 longer.

**Comment by owen200008** [comment]
but it will fail create the .o and .o.d

**Comment by owen200008** [comment]
change to short name will success

**Comment by minggo** [comment]
what's the error message?

**Comment by owen200008** [comment]
link the file, the file no exist.
the file no create.

**Comment by owen200008** [comment]
just windows

**Comment by owen200008** [comment]
mac is ok

**Comment by minggo** [comment]
We can just make the file name as short as possible, but can not fix the issue. It is the limitation of windows. And you'd better put cocos2d-x into a path that its length is as short as possible.

**Comment by owen200008** [comment]
ok

**Comment by summerinsects** [comment]
#17586 
I met the issue and fixed it via removing `$(LOCAL_PATH)/` in `Android.mk`
