### ISSUE TITLE
mac android studio compile with 2.3 ndk 14 always error

### ISSUE THREAD

**Issue by owen200008** [cocos2d/cocos2d-x#17443]
Error:(686, 0) Android NDK: Module MyGame_shared depends on undefined modules: log    
<a href="openFile:/Volumes/data/sdk/ndk-bundle/build/core/build-binary.mk">Open File</a>

Error:(699, 0) *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.
<a href="openFile:/Volumes/data/sdk/ndk-bundle/build/core/build-binary.mk">Open File</a>

should set it to true to miss? i think log is very important

**Comment by owen200008** [comment]
success with ndk r10d version

**Comment by dumganhar** [comment]
I got this issue too. It seems google breaks the compatibility again.

**Comment by minggo** [comment]
@owen200008 What's the engine version? How did you compile the codes?

**Comment by dumganhar** [comment]
@minggo , the latest code on v3 branch will be able to reproduce this issue.

**Comment by owen200008** [comment]
lldb also have the crash problem when debug。 I can't commit the report using the shadowsocks also。
the lastest version also have this problem。It is lldb's bug.

**Comment by minggo** [comment]
Yep, i can reproduce the issue. From the [changelog](https://github.com/android-ndk/ndk/wiki/Changelog-r14) it seems should add `APP_ALLOW_MISSING_DEPS=true` to keep compatible, but i don't know why `log` is missing.

**Comment by minggo** [comment]
fixed here: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/283.
