### ISSUE TITLE
since 3.14.1 load csb file with flatbuffer will crash

### ISSUE THREAD

**Issue by owen200008** [cocos2d/cocos2d-x#17464]
since 3.14.1 load csb file with flatbuffer will crash
it is no good test!!!

- cocos2d-x version:
3.14.1 and the github version. 
3.13.1 is run well
- devices test on:
windows

**Comment by owen200008** [comment]
i have find the issue CSLoader.cpp:1069 
node = reader->createNodeWithFlatBuffers(tableOptions); is wrong
must be tableOptions->data()

**Comment by owen200008** [comment]
i think it is no test!!!

**Comment by minggo** [comment]
there is not resource to support cocos studio reader.
