### ISSUE TITLE
Remote debug using Firefox 51.0.1 doesn't work on windows using JSB project with cocos 3.14

### ISSUE THREAD

**Issue by fuyifan** [cocos2d/cocos2d-x#17463]
- cocos2d-x version: 3.14
- Firefox: 51.0.1 (32bit)
- devices test on: windows
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:
I do it by some web tutorial, but it doesn't work. I made the test on not only my project but also the js-tests one, and both of them. Why? Any buddy has the same experience with me?

**Comment by minggo** [comment]
cocos2d-x port firefox debug server, but it strongly depends on firefix client codes. It is not easy to port the debug server, so we can not follow closely with its update. Please use VSCode or lower firefox version to debug the codes.

**Comment by fuyifan** [comment]
@minggo I use the latest VSCode and your plugin. However, the plugin does not work. Please check and I will very appreciate your kindly help. Thanks

**Comment by minggo** [comment]
Ok, i will update to latest VSCode to have a try. Where did you get the plugin? Use creator?

**Comment by fuyifan** [comment]
http://discuss.cocos2d-x.org/t/use-vscode-to-debug-cocos2d-x-jsb-programs/27588 Here is the URL @minggo

**Comment by minggo** [comment]
I just tried it, can work. What's your error message?

**Comment by fuyifan** [comment]
I just copy the compiled path to the %USERPROFILE%\.vscode\extensions and restart the vscode. For options in debugger window, i can not find anything about cocosXXX.
Would you please leave me your QQ or wechat and it's more convenient.

**Comment by minggo** [comment]
please send a mail to xiaoming.zhang@chukong-inc.com
