### ISSUE TITLE
Create OpenGL ES 3.0 context on devices that support it - significant performance boost with no known compatibility issues.

### ISSUE THREAD

**Issue by sachingarg05** [cocos2d/cocos2d-x#17478]
Only changing opengl es context from 2.0 to 3.0 significantly improves performance of some of our shaders, without needing any changes in app or cocos2dx code. 

For example, on iPhone6, simply changing context to opengl es 3.0 gives shaders access to 15 varying vectors instead of 8 available when using opengl es 2.0 context (Max Varying Vectors).

On iOS, code change is also very simple, including the fallback to opengl es 2.0 for devices which don't support 3.0. Change this:

cocos/platform/ios/CCES2Renderer-ios.m
```
        if( ! sharegroup )
            context_ = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2];
        else
            context_ = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2 sharegroup:sharegroup];
```
To:
```
        if ( ! sharegroup ) {
            context_ = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
            if (context_ == nil) {
                context_ = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2];
            }
        }
        else {
            context_ = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3 sharegroup:sharegroup];
            if (context_ == nil) {
                context_ = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2 sharegroup:sharegroup];
            }
        }
```

On Android also, code change to start using opengl es 3.0 is simply changing this:
cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxGLSurfaceView.java
`            this.setEGLContextClientVersion(2);
`
To:
`            this.setEGLContextClientVersion(3);
`

But this (obviously) causes app to crash on devices which don't support 3.0. And I couldn't figure out how to change Cocos2dxGLSurfaceView to fallback to opengl es 2.0 in this case. Android documentation provides some hints for detecting 3.0 support but not for apps using GLSurfaceView, only for apps managing their own EGL context. I hope someone can help with this.
From https://developer.android.com/guide/topics/graphics/opengl.html#version-check
```
private static double glVersion = 3.0;

private static class ContextFactory implements GLSurfaceView.EGLContextFactory {

  private static int EGL_CONTEXT_CLIENT_VERSION = 0x3098;

  public EGLContext createContext(
          EGL10 egl, EGLDisplay display, EGLConfig eglConfig) {

      Log.w(TAG, "creating OpenGL ES " + glVersion + " context");
      int[] attrib_list = {EGL_CONTEXT_CLIENT_VERSION, (int) glVersion,
              EGL10.EGL_NONE };
      // attempt to create a OpenGL ES 3.0 context
      EGLContext context = egl.eglCreateContext(
              display, eglConfig, EGL10.EGL_NO_CONTEXT, attrib_list);
      return context; // returns null if 3.0 is not supported;
  }
}
```

But overall this seems to be a very safe change which will give immediate performance boost to many apps without any code changes, and let them start using new 3.0 features if they want to.

You can check Apple's opengl es 3.0 compatibility checklist to make sure it won't effect cocos2dx engine, but I haven't seen anything failing until now:
https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/AdoptingOpenGLES3/AdoptingOpenGLES3.html

90% iOS devices (iPhone5s and newer) and more than 60% Android devices already support opengl es 3.0 (https://developer.android.com/about/dashboards/index.html#OpenGL).

**Comment by minggo** [comment]
On android, i think we can just use the codes to check if supporting 3.0 without using the context.

Edit: should use the result.

**Comment by minggo** [comment]
https://github.com/cocos2d/cocos2d-x/pull/17537 for this issue. On Android, we should use custom EGLConfigureChooser and EGLContextFactory:

* In the custom EGLConfigureChooser, we should use GLES3 configure first, if failed then use GLES2 configure.
* In EGLContextFactory, will create GLES3 context first, if failed, then create GLES2 context.

**Comment by minggo** [comment]
Find a conflict issue:

* multi sample conflict on iOS, can refer to https://github.com/cocos2d/cocos2d-x/issues/17767

**Comment by minggo** [comment]
It seems it has issue on some Android enumlator https://github.com/cocos2d/cocos2d-x/issues/17850. I may revert the modification on Android if can not find a good way to fix it. In China, some emulators are important Android markets channel, many players play Android games on emulators.

**Comment by minggo** [comment]
A developer reported [issue](http://discuss.cocos2d-x.org/t/bug-v3-15-opengl-transformer-tf101-cant-work/37157) on TF101 too.

**Comment by minggo** [comment]
After using GLES3 context, `Configuration::supportsShareableVAO()` will return false, it is bad performance.

**Comment by minggo** [comment]
i reverted gles3 context for iOS in https://github.com/cocos2d/cocos2d-x/pull/18066

**Comment by lost-guadelenn** [comment]
Hi

VAO is a built-in feature of GL ES 3.0
https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glBindVertexArray.xhtml
You probably don't need to check for extension to use it.

Removing ES 3.0 support breaks another feature: iPhone devices stop reporting ASTC support, which is important in my project.

**Comment by minggo** [comment]
Yep, VAO checking can be removed if using GL ES 3.0, but as i mentioned above, currently we can not move to support GL ES 3, you can do it in your project.

**Comment by lost-guadelenn** [comment]
Yes, we will fix this in our project.

But I want to say that cocos engine knows exactly GL context version it uses. (Because is explicitly binds a specific version).
And in a case of GL ES 3 function supportsShareableVAO() may return true without any checks.

Here is a pseudocode illustration to my idea:
```
bool Configuration::supportsShareableVAO()
{
    if (GetOpenGLESVersion() >= 3)
    {
        return true;
    }
    else
    {  
        return _supportsShareableVAO;
    }
}
```
This will allow you to bind GL ES 3 to gain more performance and also use VAO on devices where it is available.

**Comment by Kevinlwg** [comment]
2.0.10版本参考此方法修改后，iOS上运行后图片未显示出来，报错：无法调用JSB_glTexImage2D：build / jsb-default / frameworks / cocos2d -x / cocos / scripting / js-bindings / manual / jsb_opengl_manual。 CPP：2177，请问是哪里配置不对吗如何解决？

**Comment by goodleon** [comment]
2.1.1版本参考此方法修改后，iOS上运行后图片未显示出来，报错：无法调用JSB_glTexImage2D：build / jsb-default / frameworks / cocos2d -x / cocos / scripting / js-bindings / manual / jsb_opengl_manual。 CPP：2177，请问是哪里配置不对吗如何解决？
