### ISSUE TITLE
[feature] SocketIO supports to transfer binary data

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17475]

**Comment by yayawoo** [comment]
请问这个问题有更新吗？

**Comment by PatriceJiang** [comment]
Since the callback `SocketIOClient#on()` only support single `string` parameter, I think it is not necessary to alter `emit/send` and that will make interfaces more complex. @minggo

**Comment by minggo** [comment]
@PatriceJiang can we add a new method for it?

**Comment by PatriceJiang** [comment]
Introducing `#sendBinary()` make little difference. Binary data can easily be serialized to string. If we add `binary` output then the `binary` input will be expected. `#onBinary() & #on()` would be quite confusing to call on a specific event, and it is resolved by the server. I think it is the lack of JSON type make SIO APIs inconvenient.

**Comment by minggo** [comment]
Sounds reasonable, so close it until we have a good reason to support it.
