### ISSUE TITLE
Remove methods forbid by Apple

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#17471]
These functions are forbid by Apple:

* respondsToSelector:
* performSelector:
* dlopen()
* dlsym() 
* method_exchangeImplementations

I am not sure if we can remove the usage of them, but i seems we have to do so.

**Comment by DavidDeSimone** [comment]
Some key notes on respondsToSelector and performSelector: Apple cares about using these to execute arbitrary selectors, say by getting a string from an HTTP request and then executing that. Apple seems to be fine if you use them in a "static" way where you explicitly declare the selector you are testing against. 

One call out is the JS to Obj C bridge. That seems like the kind of reflection that Apple seems to be cracking down on.

**Comment by minggo** [comment]
> Apple seems to be fine if you use them in a "static" way where you explicitly declare the selector you are testing against.

Yep, i think so. But i am not sure about it. Apple doesn't make it clear.

**Comment by minggo** [comment]
i sent https://github.com/cocos2d/cocos2d-x/pull/17477 to remove some usage of `respondsToSelector:` and `performSelector:`. I didn't remove it in `CDAudioEngine.m` because i can not remove it. But i will remove it if these two functions are really forbid by Apple because this file is used to implement SimpleAudioEngine, and SimpleAudioEngine doesn't use these features though developers may use it.

I haven't removed JS/Lua to Objective-c bridge, may be should can just define a macro to control the logic,  and the default behavior is not compiling these codes. Developers can enable it by modifying the macro value.

Edit: i removed js/lua to objective-c bridge in the PR.

**Comment by loyalwind** [comment]
so can i use the following method ?
    objc_msgSend(BridgeObjc , sel_reigsterName("someMethod"));
Will Apple reject my app ?

**Comment by minggo** [comment]
I am not sure about it. That's why i don't send the PR.

**Comment by loyalwind** [comment]
i use clang -rewrite-objc .m , find [BridgeObjc   someMethod] is equal to objc_msgSend(BridgeObjc , sel_reigsterName("someMethod")); i'm not sure whether can i user rumtime method?

**Comment by minggo** [comment]
It seems it is not a problem, so close this issue.
