### ISSUE TITLE
[Android] Downloader doesn't support SSL connection

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17473]
Reported at http://forum.cocos.com/t/creator1-4-5s-https-certificate-for-cdn-qiyimofang-com-doesnt-match-any-of-the-subject-alternative-names-ucd1-pp-uc-cn/44489/3

- cocos2d-x version: v3.14
- devices test on: Android
- developing environments
   - NDK version: r10e
   - Xcode version: N/A
   - VS version: N/A
   - browser type and version: N/A

Steps to Reproduce:

1. Just download a file with `https://` prefix url

**Comment by dumganhar** [comment]
I replaced the link in `DownloaderTest` to https://cct.ccsize.com/1.tar.gz .
And it could download the file through https connection successfully.

**Comment by dumganhar** [comment]
Need to check with the bug reporter again. Mark this issue to `next` version.

**Comment by kienvn** [comment]
CCDownloader-curl doesn't support https connection too.

**Comment by owen200008** [comment]
test on windows no curl_multi_add_handle use sync is ok
if use curl_multi_add_handle must be timeout

**Comment by plutoo** [comment]
It seems `Downloader` works fine with `https` links on the current version. @minggo

**Comment by minggo** [comment]
@PatriceJiang please check

**Comment by PatriceJiang** [comment]
Downloading `https` links are OK.  Checked.

**Comment by imtrobin** [comment]
I'm facing this problem on some Android devices. Most of them work but my Xiaomi (Redmi) https will fail.
