### ISSUE TITLE
AudioEngine ios does not play sound

### ISSUE THREAD

**Issue by hussain-sohaib** [cocos2d/cocos2d-x#17488]
- cocos2d-x version: 3.10
- devices test on: iPhone 6s+  iOS 10.2

AudioEngine does not play sound because AudioEngine::lazyInit()  always returns false. 

In  AudioEngineImpl::init()

s_ALDevice = alcOpenDevice(nullptr);

s_ALDevice is not created and is always nullptr, so if(s_ALDevice) { ... }  fails and ret is always false.

**Comment by dumganhar** [comment]
Hey, how did you reproduce this issue? Could cpp-test, lua-test reproduce it?

**Comment by hussain-sohaib** [comment]
Hello,

So the issue is we cant play sounds at same time using SimpleEngine and AudioEngine, What ever engine is used to play sound or background music first will take the lead, meaning only sounds related to them will play. Please see attached classes file and resources file to reproduce the issue. this issue appears to on iOS only, because on android I am using both simple and audio engine in same scene.

any Idea how to resolve this?
thanks

  



[Classes.zip](https://github.com/cocos2d/cocos2d-x/files/837506/Classes.zip)
[Resources.zip](https://github.com/cocos2d/cocos2d-x/files/837507/Resources.zip)

**Comment by dumganhar** [comment]
Don't use `SimpleAudioEngine` and `AudioEngine` in a game, please just choose one, don't mix them.
