### ISSUE TITLE
cc.audioEngine.playEffect();   Not have play end callback?

### ISSUE THREAD

**Issue by sevenChilde** [cocos2d/cocos2d-x#17482]
I need now get cc.audioEngine.playEffect(); play end callback
but.
I find it seems not  to exits

**Comment by dumganhar** [comment]
cc.audioEngine is implemented by `CocosDenshion::SimpleAudioEngine` which doesn't support play ended callback.
Try to use `jsb.AudioEngine` which supports this feature.
You could refer to js-tests/src/NativeTest/AudioEngineTest.js

**Comment by sevenChilde** [comment]
oh,Ok.  I gonna go see AudioEngineTest.
Thank you
