### ISSUE TITLE
how to pause PhysicsWorld? use cc.Director:getInstance():pause() is no valid

### ISSUE THREAD

**Issue by owen200008** [cocos2d/cocos2d-x#17486]
- cocos2d-x version:
github version
- devices test on:
windows
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
vs 2013
   - browser type and version:

how to pause PhysicsWorld? use cc.Director:getInstance():pause() is no valid

**Comment by minggo** [comment]
I think you can use `PhysicsWorld::setAutoStep(false)` to pause it.
