### ISSUE TITLE
[jsb] SocketIO client receives message twice

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17490]
Reported at https://github.com/cocos-creator/cocos2d-x-lite/issues/563

- cocos2d-x version: v3.14.1
- devices test on: all
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by PatriceJiang** [comment]
bug has been fixed before jul 10, 2017 
`cocos/scripting/js-bindings/manul/jsb_socketio.cpp`
```diff
-    virtual void onMessage(SIOClient* client, const std::string& data)
+    virtual void onMessage(SIOClient* client, const std::string& data) override
     {
-        CCLOG("JSB SocketIO::SIODelegate->onMessage method called from native with data: %s", data.c_str());
-        this->fireEventToScript(client, "message", data);
     }
 
```
it is no longer exists in newer version. this issue should be closed, @minggo
