### ISSUE TITLE
Win32 performance is bad.

### ISSUE THREAD

**Issue by Kotaiba** [cocos2d/cocos2d-x#17497]
- cocos2d-x version:14.1
- devices test on:Win32
- developing environments
   - VS version: vs community 2015 14.0.25431.01

Steps to Reproduce:
print the fps.
 if (dt>0.0167f){
cclog("dt=%f",dt);
}

Our game is running with steady 0.0166667f on all devices ,but on win32 the game is lagging 
i tried to print the fps since i noticed that the update function is not steady like other platforms.
  if you can see the fps go up to 0.0200f.

![capture](https://cloud.githubusercontent.com/assets/3635272/23903803/6d9cd47a-08ce-11e7-8530-6a3510012c2b.PNG)

on the next image the game on mac is running without any issue and the fps perfect.

<img width="154" alt="screen shot 2017-03-14 at 4 56 25 pm" src="https://cloud.githubusercontent.com/assets/3635272/23903945/f1dbb17a-08ce-11e7-8581-224b263a7076.png">

**Comment by bsy6766** [comment]
Are you running on release mode or debug mode?

**Comment by Kotaiba** [comment]
@bsy6766  on both release and debug .
@dumganhar i will try to stop all the audio to see if this issue audio relevant .

**Comment by Kotaiba** [comment]
@dumganhar i think this not audio issue ,i stoped all the audio and the issue remain. 
please note the fps go down too so the range will be  0.013 ->0.02  on win32 only ,on other platform same game running perfectly .

**Comment by dumganhar** [comment]
@kobake , thanks. I will have a check. Could the simplest cpp-empty-test or the new project created by `cocos new` reproduce this issue?

**Comment by Bilalmirza** [comment]
@dumganhar win32 performance is really pathetic... there are some fixes mentioned in this post

http://discuss.cocos2d-x.org/t/cocos2d-x-windows-performance-issues-examined/27915

i have to go through these every time i update cocos2dx version.

Even after all the changes, Performance on a mac beats windows... Even though my windows laptop is much more faster and has a much better graphics card.

**Comment by Bilalmirza** [comment]
atleast merge these changes in v3.15 
http://discuss.cocos2d-x.org/t/cocos2d-x-windows-performance-issues-examined/27915

Thanks :)

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/17556
The patch is based on the post in the form but makes a little change.
@Kotaiba  @Bilalmirza , could you test my patch? Thanks.

**Comment by Bilalmirza** [comment]
@dumganhar After applying the #17556 fps is more stable at 60 on a empty project.

**Comment by dumganhar** [comment]
@Bilalmirza, thanks for testing. :)

**Comment by Bilalmirza** [comment]
@dumganhar what could be other reasons that mac build is much faster than win32 build (even with having  a hardware advantage for win32).

**Comment by perminovVS** [comment]
@dumganhar you solution, on some device, create each time to work less 2 ms, 100% load processor core.
`else
    Sleep(1);
`
Solves it, but likely return problem issue.

You solves up precision fps, but degraded performance.
