### ISSUE TITLE
求助：新建lua项目，iOS运行出错

### ISSUE THREAD

**Issue by sunweiliang** [cocos2d/cocos2d-x#17508]
cocos2d-x-3.14.1
Cocos Console 2.2
Xcode8.2

创建项目：
cocos new luagame -p com.testbe.game -l lua -d /Users/ystx_mbp/Documents/cocos2dx/project 

运行iOS，出错了

![image](https://cloud.githubusercontent.com/assets/4755841/23940377/a009cb3a-099f-11e7-8fa1-4f9fc66360e7.png)

js 和 c++ 是正常的，lua报错，求助，谢谢各位

**Comment by dumganhar** [comment]
Duplicated issue: https://github.com/cocos2d/cocos2d-x/issues/17043
Closed this one.
