### ISSUE TITLE
Changing a test case header file forces a recompile of all tests

### ISSUE THREAD

**Issue by ntrrgc** [cocos2d/cocos2d-x#17514]
- cocos2d-x version: latest `v3` from this repo (8c542d711d1d341b59c4905827a2b7bde23da19b)
- developing environments
   - CMake: 3.7.2

Steps to Reproduce:

1. Compile the Cocos2D-x test suite.
2. Make a cosmetic change in any header file in the `tests/cpp-tests/Classes` directory.
3. Run `cmake --build` to recompile.

Expected behavior:

The test case is recompiled in a short time span.

Actual behavior:

Every test case within `tests/cpp-tests` is recompiled, which can take several minutes. Is there any reason it has to be this way?

**Comment by minggo** [comment]
Why need to use cmake every time? I think you can just use `make` instead if not adding new cpp files.

**Comment by ntrrgc** [comment]
Note `cmake --build` is just a generic way to invoke make, ninja or whatever task runner you use, it does not build the project from scratch, nor is a noticeable time difference compared to executing raw commands.

Anyway, I no longer can reproduce the issue, so I'm closing this. 😕 I'll reopen if it happens again.
