### ISSUE TITLE
Cocos documentation should be corrected after #17424

### ISSUE THREAD

**Issue by samodadela** [cocos2d/cocos2d-x#17515]
Hi, 

Win10/Cocos2d-x 3.14.1

Was just following the cocos documentation on http://cocos2d-x.org/docs/static-pages/installation.html in order to try out Android Studio Setup. I've downloaded the latest/greatest(?) Android Studio and related sdk, ndk, ant (added to path, etc) When following the steps I had first to complete the prerequisite: http://cocos2d-x.org/docs/installation/Android-terminal/index.html

Problems started at:  
python android-build.py -p 21 cpp-tests

The reason was https://github.com/cocos2d/cocos2d-x/issues/17424

I've patched the scripts natural-law fixed and tried again only to get the message that the command line build is not supported with Android SDK Tools 25.3.x.

I guess this obsoletes the all the instruction on:
http://cocos2d-x.org/docs/installation/Android-terminal/index.html

Can you please fix the documentations? Do we even need command line build for android?

I don't know if this is related to the above (I guess it is since I could not complete the step): 
I then skipped this step opened Android Studio and opened cpp-tests. After some updating, rebuilding, updating again, rebuilding... the project was built without errors, but when I start it (either on device or simulator) I get:

```
03-15 14:58:39.216 2611-2611/org.cocos2dx.cpp_tests E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.cocos2dx.cpp_tests, PID: 2611
                                                                      java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.cocos2dx.cpp_tests-1/base.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.cocos2dx.cpp_tests-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.cocos2dx.cpp_tests-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libcpp_tests.so"
                                                                          at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                                          at java.lang.System.loadLibrary(System.java:1530)
                                                                          at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:248)
                                                                          at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:264)
                                                                          at android.app.Activity.performCreate(Activity.java:6679)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

One more thing... from the documentation it is not clear from where to get the sdk/ndk. The latest android studio downloads the sdk/ndk automatically from withing Tools/Android/sdkmanager. Are those ok, do I need other ones? 

It's my first attempt at running the android build so please excuse my ignorance.

**Comment by samodadela** [comment]
The exact error I get when trying to follow the instructions at:
http://cocos2d-x.org/docs/installation/Android-terminal/index.html

```
C:\Cocos2d-x\3.14.1\build>python android-build.py -p 21 cpp-tests
cocos compile -p android -s C:\Cocos2d-x\3.14.1\build\..\tests\cpp-tests --ndk-mode debug --app-abi armeabi-v7a --ap android-21
Building mode: debug
Using Eclipse project : C:\Cocos2d-x\3.14.1\tests\cpp-tests\proj.android
Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0.
Build dynamic library for project [ C:\Cocos2d-x\3.14.1\build\..\tests\cpp-tests ] failed!
```

**Comment by samodadela** [comment]
I guess that android-build.py should be updated to build proj.android-studio?

I then went to build it manually:
`C:\Cocos2d-x\3.14.1\tests\cpp-tests\proj.android-studio>cocos compile -p android -s C:\Cocos2d-x\3.14.1\build\..\tests\cpp-tests --ndk-mode debug --app-abi armeabi-v7a --ap android-25`

Cleaned up the project in Android studio, rebuild... same problem. The build does not seem to pick-up libcpp_tests.so. 

Why is there no gradle rule to do the ndk build?

**Comment by samodadela** [comment]
Found this about problems building with gradle:
http://discuss.cocos2d-x.org/t/do-we-work-with-android-studio-yet/20383/14

Basically it talks about problems using gradle to build.

Is this still valid? Can the android studio project build the required libcpp_tests.so?

**Comment by samodadela** [comment]
Note that I even downgraded sdk tools to r25.2.3 in which case I was able to compile proj.android. However  I did not manage to get proj.android-studio going - not even from cli.

**Comment by dumganhar** [comment]
@natural-law , could you take a look at this issue? Thanks.

**Comment by minggo** [comment]
@slackmoehrle I think we should update [this doc](http://cocos2d-x.org/docs/installation/Android-terminal/index.html). `android-build.py` is removed, we should use `cocos command` instead. And we need a doc about how to use Android Studio to develop android apps.

**Comment by slackmoehrle** [comment]
@minggo ok, I'll start working on this doc. We have an Android Studio doc that you and I worked on a while back. I'll review this as well.

**Comment by minggo** [comment]
thanks

**Comment by DCMay** [comment]
when I do cocos compile -p android I get :
 `Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0.`
what the hell is going on ?
I can not find any useful information in anywhere.
can anybody please tell me what  should I do ?

**Comment by chenjienan** [comment]
I have the same problem as @DCMay 

I think the project cannot find the cocos2d library.
Please let me know if there is a solution.
if I run "cocos compile -p android -d android-studio" I got "Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0."

Very frustrating, please help.

**Comment by minggo** [comment]
@chenjienan you should copy tools folder from older Android SDK version.

**Comment by chenjienan** [comment]
@minggo  which version of the SDK should I use?

**Comment by minggo** [comment]
Older than 25

**Comment by chenjienan** [comment]
@minggo I tried to copy and paste the `tools` from android sdk 24.4.1. 
I got this "The directory 'android-13' can't be found in ANDROID_SDK_ROOT/platforms, please use -
-ap to set needed API level"

**Comment by minggo** [comment]
Your SDK doesn't include API level 13, and the default API level is 13. You should use --ap to she the API level. I think the log is clear.

**Comment by chenjienan** [comment]
@minggo You're right. Apologize for that stupid question. Yes, it solve the "cocos compile" problem. However, my android project still cannot find the cocos2d library. 

<img width="775" alt="screen shot 2017-04-26 at 7 50 22 pm" src="https://cloud.githubusercontent.com/assets/3772868/25465889/04c2a5de-2aba-11e7-8580-518988bd67a0.png">

<img width="979" alt="screen shot 2017-04-26 at 7 51 01 pm" src="https://cloud.githubusercontent.com/assets/3772868/25465891/08b9dc84-2aba-11e7-8fd0-cb010deea931.png">

**Comment by minggo** [comment]
As you can see, there is bug when building .so, you should fix the issue first.

**Comment by chenjienan** [comment]
You are right! It's a build issue.

**Comment by drelaptop** [comment]
cocos2d-x docs have been updated, new docs site http://cocos2d-x.org/docs/cocos2d-x/en/

please new issues or discuss at [forum](https://discuss.cocos2d-x.org/c/cocos2d-x/cpp) if building errors occur when using 3.17 release.
