### ISSUE TITLE
Impossible Dependency in setCenterRectNormalized 

### ISSUE THREAD

**Issue by jaunt** [cocos2d/cocos2d-x#17521]
- cocos2d-x version: 3.14.1 (downloaded from website)
- devices test on: (simulator iOS 10)
- developing environments
   - NDK version:
   - Xcode version: 8.2.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Call setCenterRectNormalized in default RenderMode::POLYGON mode with the intent of switching to RenderMode::SLICE9 mode (this is currently the only function that will set _renderMode to RenderMode::SLICE9.
2. Function returns immediately because it depends on being in QUAD or SLICE9 mode already.

Seems to me since the function is capable of switching into SLICE9 mode, it should be fine to enter it from POLYGON mode.

**Comment by minggo** [comment]
Yep, this feature only support for scale9 sprite.

**Comment by jaunt** [comment]
But I don't see how this code can be triggered in any circumstance.  Hence my "impossible dependency".  The only place you can set it into SLICE9 mode currently is through this function yet you can't call this function unless it's in SLICE9 mode.

What am I missing?

**Comment by minggo** [comment]
Sorry, i don't quite understand what you want to do.

**Comment by jaunt** [comment]
I just want the new cocos2d::sprite to work as a scale9 sprite.  The only way I can see this happening is if I call setCenterRectNormalized.  In 3.14.1, how do you make a scale9 sprite?  Seems impossible.  If I simply remove the assert in setCenterRectNormalized, my code works fine.  Clearly I'm missing something.  My apologies for that.  My entire game was functioning perfectly in 3.10 but once I upgraded all the ui:button scale9 stuff stopped working as well as all scale9 functionality I was depending on.

**Comment by minggo** [comment]
How did you create the sprite? The default render mode is `Sprite::RenderMode::QUAD`.
