### ISSUE TITLE
CallFunc called twice when wrapped in TargetedAction

### ISSUE THREAD

**Issue by AknEp** [cocos2d/cocos2d-x#17559]
Title says all.

- cocos2d-x version: 3.14.1 π :)
- devices test on: iOS Simulator [iPhone 7 Plus - iOS 10.2 (14C89) ]
- developing environments
   - Xcode version: 8.2.1 (8C1002)

Steps to Reproduce:

1. clone https://github.com/AknEp/TargetedActionExample
2. run in xcode & check output

and, core reproduction is ...

```cpp
# in the Scene ...
this->runAction(TargetedAction::create(this, CallFunc::create([this](){
    CCLOG("Called");
})));
```
"Called" message is printed twice.

```
// with my reproduction code, counter variable is incremented.
myActionB: 0
myActionB: 1
```

Although `TargetedAction` wrapping isn't nessesary in this case, but I met this issue in my real product.

I didn't test other `Action` ( e.g. `FadeIn` ) wrapped in `TargetedAction`. Some `Action` might has same problem.

**Comment by myxrome** [comment]
I've fixed the same bug here https://github.com/cocos2d/cocos2d-x/pull/17190

**Comment by AknEp** [comment]
@myxrome great!

( ... I've searched only `TargetedAction` in issues ... sorry! )
