### ISSUE TITLE
cocos deploy -p win32 doesn't contain a .exe file

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#17565]
- cocos2d-x version: v3.14.1
- devices test on: PC (windows 10)
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: VS Enterprise 2015
   - browser type and version:

Steps to Reproduce:

1. run $cocos deploy -p win32 -m release
2. it will create a bin folder with all the correct files but there wont be any .exe
3. you can copy the exe from the  Release.win32 folder into your bin folder to make it work.

**Comment by minggo** [comment]
We tested and it could copy the exe file.
