### ISSUE TITLE
cc.Node.setPosition native build set position to NaN

### ISSUE THREAD

**Issue by yuriilychak** [cocos2d/cocos2d-x#17584]
- cocos2d-x version: 3.14.1
- devices test on: Mac-Mini

Hello.
When I try to override `cc.Node.setPosition(newPosOrxValue, yValue)` and setting value by `cc.p`. Sprite coords setting to NaN. I think this problem cause virtual machine interpretate yValue that equels 'undefined', as varible and use `setPosition (float x, float y)`.

**Comment by minggo** [comment]
how reproduce it?

**Comment by yuriilychak** [comment]
Use native platform
1) Create your own class with overriding method setPosition:
```
setPosition: function (newPosOrxValue, yValue) {
        this._super(newPosOrxValue, yValue);
        this.updateIsoPosition();
    },
```
2) Create object of this class and set position by point: 
```
var myNode = new MyNode();
      myNode.setPosition(new cc.p(200, 200));
      cc.log(myNode.getPosition().x + " " + myNode.getPosition().y); // log "NaN NaN" on native platform
```
