### ISSUE TITLE
CCNode.h setAnchorPoint - function documentation mentions wrong default anchor point value

### ISSUE THREAD

**Issue by klnvnv** [cocos2d/cocos2d-x#17588]
- cocos2d-x version: all

The documentation for the setAnchorPoint function in CCNode.h mentions the wrong default value for _anchorPoint in Node - it says (0.5,0.5) and it should be (0, 0). It trips me up sometimes when I forget from what I did subclass from - Node or Sprite.
[patch.txt](https://github.com/cocos2d/cocos2d-x/files/871024/patch.txt)

**Comment by klnvnv** [comment]
Never mind that other patch, I did that edit in a hurry, so I messed it up.
This one is correct and sounds better.
[patch.txt](https://github.com/cocos2d/cocos2d-x/files/871022/patch.txt)

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17597
