### ISSUE TITLE
UIEditBox's two issues:setText when editting; iOS placeholder's font and color

### ISSUE THREAD

**Issue by sail1024** [cocos2d/cocos2d-x#17608]
- cocos2d-x version:3.13 and later
- devices test on:iPhone 7 Andriod device
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. When call setText in the text changed event(some time, I need to modify the input at the same time, eg:divide the input Phone Number by '-' every four letter or limit the input), it will display the overlay.I reviewed the EditBox's implament,  found that the normal display label(CCLabel) is set hidden when beginning edit  and visible end edit. But when I call the setText it will set the label visible if the text's lenght is not zero which contribute to the overlay.My resolution is:
  define a bool  variable(named editting) in the EditBoxImplCommon class, set it true in the EditBoxImplCommon::editBoxEditingDidBegin and false in the EditBoxImplCommon::editBoxEditingDidEnd, then in the EditBoxImplCommon::setText, if editting then don't call the refreshInactiveText(the method update the label's display)
void EditBoxImplCommon::editBoxEditingDidBegin()
{
    // LOGD("textFieldShouldBeginEditing...");
    _editting = true;
    cocos2d::ui::EditBoxDelegate *pDelegate = _editBox->getDelegate();
    
    if (pDelegate != nullptr)
    {
        pDelegate->editBoxEditingDidBegin(_editBox);
    }

  void EditBoxImplCommon::editBoxEditingDidEnd(const std::string& text, EditBoxDelegate::EditBoxEndAction action)
{
    // LOGD("textFieldShouldEndEditing...");
    _text = text;
    _editting = false;

void EditBoxImplCommon::setText(const char* text)
{
    this->setNativeText(text);
    _text = text;
    if (!_editting)
        refreshInactiveText();
}
2. iOS placeholder's font and color, the iOS native input view if UITextField but the inputModel is EDITBOX_INPUT_MODE_ANY, the most simple handle is just add a method in the UITextField's Category:UITextField+CCUITextInput.mm
- (UILabel *)ccui_placeholderLabel
{
    return [self valueForKey:@"_placeholderLabel"];
}
but you shoud setup the editbox in the follow order:
setInputMode->setPlaceHolder->setPlaceholderFont or setPlaceholderFontColor, if not, you may get nil from the function ccui_placeholderLabel's return.
The best method is set the UITextFiled's attributedPlaceholder whith string、 font and color.

**Comment by summerinsects** [comment]
hey, I found a similar issues about platform android
it wont display any text in EditBox when you call 'setText' just after creating sometimes(occasionally reproduce)
My resolution is similar to yours, but I don't modify the method 'setText'

**Comment by zilongshanren** [comment]
@summerinsects  @tinysail 
The duplicated text display issue when call `setText` in textChanged callback is fixed now.
Thanks for your contribution.
