### ISSUE TITLE
Can not build latest version from github (android and win32)

### ISSUE THREAD

**Issue by BPri1** [cocos2d/cocos2d-x#17617]
- cocos2d-x version: latest from github 3.14.1+ or 3.15
- devices test on:
- developing environments
   - NDK version: R13b R12b
   - VS version: 2015 2017
   - AndroidStudio version: 2.3

Steps to Reproduce:

1. Download a branch from github (branch v3 or v3.15)
2. Download the cocos console
3. Install JDK, SDK, NDK, Python, Ant,
VS, Eclipse, AndroidStudio (Yeah, I tried everything)
4. Run download-deps.py
NOTE: download-deps.py does not ask me any more if I want to save the zip file or not
and I'm not sure if this works correctly now.

5. Run setup.py

6. Create a new project
cocos new cc2dTEST -p com.cc2dtest -l cpp -d D:\
NOTE: the creation of a new project seems to be faster than usual.
It looks like there are missing some libraries or something.

7. Then
cocos compile -p android --ap android-19 -s D:\cc2dTEST

Or try to open in Visual Studio

Or try to open and build in Android Studio

Please see the topic for more information.
http://discuss.cocos2d-x.org/t/android-ndk-jni-android-mk-cannot-find-module-with-tag-cocos-in-import-path/35287
The whole topic please.

NOTE: 3.14.1 works. The latest versions do not work.

**Comment by minggo** [comment]
v3.14.1 is the latest version.

**Comment by BPri1** [comment]
Oook. What I mean by the "latest version":

If I download https://github.com/cocos2d/cocos2d-x/tree/cocos2d-x-3.14.1
Then it works.

But!
I need a version with fixed audio decoding. And maybe some other fixes.

So I tried to download https://github.com/cocos2d/cocos2d-x/tree/v3
or https://github.com/cocos2d/cocos2d-x/tree/v3.15
which have a more "later" hotfix than 3.14.1.
I called "3.14.1+" and "3.15", respectively.

And as I said both of these "latest" versions do not work.

**Comment by pmichos** [comment]
Same problem here with "Latest" version of github. Possible the new paths of android.mk is the problem

3.14.1 Works Fine!

**Comment by BPri1** [comment]
@devkatara Thank you so much! Now I know that I'm not alone.

@minggo Do you see now? Sometimes I'm not sure that the cocos team even reads topics. So sad.

**Comment by pmichos** [comment]
@BPri1 it's ok... Cocos is free project and we must stay patience

**Comment by BPri1** [comment]
Yes, it's the free project, but its engineers do not work for free.

I try to be patient, and I hate being not polite. But while communicating with the three of team members on this issue, I have a feeling that none of them actually read the topic/issue.
I understand that they can be busy. But three of them... It looks like a pattern.

Now I feel like I was... er... not clever because I chose cocos instead of Unity. And all this time, studying the engine was just wasted.

I really hate being not polite.

**Comment by minggo** [comment]
@BPri1 sorry about it. The last three days are holiday here. We just come back from holiday. About the latest v3.15 branch, the QA team just tested it and don't find the issue. I will try the latest codes now.

**Comment by minggo** [comment]
I just tried latest v3.15 branch, created a new cpp project and with with VS2015, no problem. I will try android later.

**Comment by BPri1** [comment]
Hi @minggo !
I understand that you can be busy and I understand that you have holidays.
I'm  little not happy that I needed to explain the problem several times.

I just installed the new win10 and VS2017 (It seems that I can not download VS2015 anymore, I had the same issue with VS2015, so it probably does not depend on the version of VS).

Branch v3.15. Same issue.

Now I installing Android Studio.

You just download the branch, then use download-deps.py, then setup.py, right?

I can give you access to my PC if you want. With TeamViewer or something else. Now I have a pure win10 so it's safe.

**Comment by minggo** [comment]
win10 + vs2017 can not work right now. If you want to build on VS, you don't have to install Android Studio. You can try VS first. 

> You just download the branch, then use download-deps.py, then setup.py, right?

I just checkout the branch and update external libraries locally, because i cloned 3rd party bin repo. And i don't run `setup.py` as i already set it before.  You should do it if you haven't done it before.

**Comment by minggo** [comment]
@BPri1 what's you error message of using VS2015 to build the new created project?

**Comment by BPri1** [comment]
I use VS to build a win32 project, not an android. Because it's faster for me to write most of the code in the studio. But my target platform is an android.

> and update external libraries locally

Can it give a different result than using download-deps.py?

I have no VS2015 right now, but the error was that it could not find lib while open of the project. Screenshot with the same error but in VS2017 you can see in the topic.

**Comment by minggo** [comment]
I think `download-deps.py` don't have problem, because i used it to make zip file for QA team, and they don't meet the problem. In the topic you posted in forum, the error is because VS2010 is not supported.

**Comment by BPri1** [comment]
So should I get VS2015?
And thank you very much for helping.

**Comment by minggo** [comment]
Yep, you should use VS2015 or VS2013. And there is not problem using VS2017 on windows7 but have issue on win10 which we should fix it.

**Comment by BPri1** [comment]
@minggo Ok, I finally got VS2015. Still same issue. I added the new screenshot to the topic.

**Comment by BPri1** [comment]
Just in case, I'll duplicate it here. The problem is found.
http://discuss.cocos2d-x.org/t/android-ndk-jni-android-mk-cannot-find-module-with-tag-cocos-in-import-path/35287/29

@minggo Thank you for your help!
