### ISSUE TITLE
onCreateView in AppActivity.java of template file

### ISSUE THREAD

**Issue by flyingkisser** [cocos2d/cocos2d-x#17621]
templates/js-template-default/frameworks/runtime-src/proj.android-studio/app/src/org/cocos2dx/javascript/AppActivity.java

should comment this function for your OpenGLES 2.0 or 3.0 choosing.

@Override
    public Cocos2dxGLSurfaceView onCreateView() {
        Cocos2dxGLSurfaceView glSurfaceView = new Cocos2dxGLSurfaceView(this);
        // TestCpp should create stencil buffer
        glSurfaceView.setEGLConfigChooser(5, 6, 5, 0, 16, 8);

        return glSurfaceView;
    }

**Comment by minggo** [comment]
Yep, you are right. Now all attributes should be set in cpp codes.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17680
