### ISSUE TITLE
Memory leak on setDimentions if overflow mode is set to shrink

### ISSUE THREAD

**Issue by flener** [cocos2d/cocos2d-x#17639]
- cocos2d-x version: 3.13.1 ( and 3.14.1 )
- devices test on: Ubuntu 14.04 (amd64)
- developing environments
   - NDK version: -- 
   - Xcode version: --
   - VS version: --
   - browser type and version: --

Steps to Reproduce:

1.  Create a label and setOverflow to Shrink
2. Use setDimensions 
3. Close program. Leak Occurs

I wrote a more detailed explanation in forum: http://discuss.cocos2d-x.org/t/bug-report-memory-leak-on-label-setdimentions/36018

**Comment by Rubonnek** [comment]
@minggo This issue can be closed since #17756 was merged which fixes this issue.

**Comment by minggo** [comment]
thanks
