### ISSUE TITLE
Cannot build Android project using cocos compile -p android

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#17640]
- cocos2d-x version: v3 branch up to git commit acc97516d8
- developing environments
   - NDK version: r14b

Steps to Reproduce:

1. Create a new project using git commit acc97516d8 and try to compile for Android
 ````shell
cocos new -l cpp android_build_test
cd android_build_test
cocos compile -p android --ap android-19 -m release -j`nproc` --ndk-toolchain arm-linux-androideabi-4.9
````
2. You'll get the following error:

````
make: Entering directory `.../project_root/proj.android'
make: *** No rule to make target `jni/jni/hellocpp/main.cpp', needed by `obj/local/armeabi/objs-debug/MyGame_shared/jni/hellocpp/main.o'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory `.../project_root/proj.android'
````

Possible fix:

This issue was introduced in commit 55362547fa. Removing  `$(LOCAL_PATH)` from `LOCAL_SRC_FILES` in `proj.android/jni/Android.mk` fixes this issue.

**Comment by minggo** [comment]
v3.15 doesn't includes the commit `5536254`.

**Comment by Rubonnek** [comment]
Right, I meant I was using the v3 branch. `cocos --version` returns `cocos2d-x-3.15` on that branch.

I just noticed the v3.15 branch does not include that commit 5536254. I updated the first comment.
