### ISSUE TITLE
Compilation freezes when compiling JS Bindings example projects with 4GB of RAM

### ISSUE THREAD

**Issue by jpsarda** [cocos2d/cocos2d-x#1765]
It seems that when Xcode 4.5 tries to compile those files cocos2dx.cpp / coccos2dx.hpp , it runs out of memory on my macbook pro with 4GB of RAM. The hard drive swaps and Xcode is stuck for ever. Maybe if I would wait a _lot_ that would compile the file, but I've never waited enough to see this.

Problem described here : http://www.cocos2d-iphone.org/forum/topic/106185#post-260846

**Comment by ashlovemira** [comment]
Im also had the same problem. using xCode 4.5. MacBook Pro version 10.7.5, Processor 2.4, Memory 4GB. it works when compile for simulator but stuck when compile for devices.

**Comment by jpsarda** [comment]
Any news on this from the admins? I think splitting cocos2dx.cpp in several pieces would solve it but I'm far far away from being able to do this myself.

**Comment by minggo** [comment]
I haven't met this problem. It really consume some time to compile the file, because the file is too large.
So please be patient to wait for it.

**Comment by jpsarda** [comment]
I've been waiting for 10 minutes and still not compiled. I stopped. This is not an acceptable workflow for developing a game. My Macbook is almost new (6 months old). If this is the official answer to this problem, I guess I'll have to switch to something else.

**Comment by dumganhar** [comment]
@jpsarda 
Did you try cocos2d-iphone jsbinding sample projects?
Did it also freeze?
As i know, in cocos2d-iphone jsbinding, there are also some big files for binding.
So could you try that to make sure that whether this issue just occurs on cocos2d-x jsbinding?

Thanks.

**Comment by jpsarda** [comment]
Yes it works without a problem with cocos2d-iphone. Seems that the problems is related to cocos2d-x then.

**Comment by dumganhar** [comment]
@jpsarda , try to switch the compiler to _Apple LLVM compiler 4.1_. By default, jsbinding project is built under _GCC4.2_, there is an ugly bug if using _LLVM compiler_ in debug mode when running application on device.
So please check whether this can work on simulator. Thanks.

![ 2013-01-05 10 08 02](https://f.cloud.github.com/assets/493372/45088/8a23789e-5741-11e2-8961-471387493217.png)

**Comment by jpsarda** [comment]
Yes it compiled with 4.1. I got an error when executing it but don't think ti's related to 4.1. Thx.

**Comment by dumganhar** [comment]
Did you get the _vm_protect_ error on device? And did it work ok on simulator?

**Comment by jpsarda** [comment]
Yes exactly :D

**Comment by dumganhar** [comment]
Good to hear that it works.
So i think it's no problem since when you need to run your application on device, just switch the target to **release** mode. You could debug your application on simulator.

**Comment by godyZ** [comment]
@jpsarda  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
