### ISSUE TITLE
download-deps.py needs to be fixed

### ISSUE THREAD

**Issue by BPri1** [cocos2d/cocos2d-x#17652]
- cocos2d-x version: branch v3 v3.15

download-deps.py uses git to clean external folder, that is causing the error if git is not installed.

Please see http://discuss.cocos2d-x.org/t/android-ndk-jni-android-mk-cannot-find-module-with-tag-cocos-in-import-path/35287/36

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17677
