### ISSUE TITLE
[android] Crash while launching on the devices only support OpenGL ES 2

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17665]
It's caused after merging https://github.com/cocos2d/cocos2d-x/pull/17537
- cocos2d-x version: v3 branch
- devices test on: Meizu MX3
- developing environments
   - NDK version: r10e
Steps to Reproduce:

1.  Just run cpp-empty-test

**Comment by Rubonnek** [comment]
This issue is also related to #17642. I also got the crash on LG G3 Stylus (Android 5.0.2) which has a Mali-400MP2 GPU that only supports OpenGL ES 2.
