### ISSUE TITLE
Where to get the source Protos.proto file

### ISSUE THREAD

**Issue by xhcnb** [cocos2d/cocos2d-x#17667]
protobuffer file 
https://github.com/cocos2d/cocos2d-x/blob/v3/tools/simulator/libsimulator/lib/runtime/Protos.pb.h
but, there is no source file Protos.proto
Anyone knows where to find it?
thanks.

**Comment by minggo** [comment]
the json file for flatbuffer is in https://github.com/cocos2d/cocos2d-x/tree/v3/cocos/editor-support/cocostudio/fbs-files
