### ISSUE TITLE
Audio Engine crash on Android when playing and stopping some audios repeatedly

### ISSUE THREAD

**Issue by pwang08** [cocos2d/cocos2d-x#17707]
- cocos2d-x version: 3.14.1 (with latest audio engine from v3)
- devices test on: all Android test devices of my company
- developing environments
   - NDK version: r10d
   - Xcode version: 
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Play 3 or 4 audios simultaneously
2. Stop them all and re-play the same audios
3. The crash occurs after repeating several times.

**Comment by pwang08** [comment]
Ok, I have fixed this issue, see pr #17716

**Comment by dumganhar** [comment]
https://github.com/cocos2d/cocos2d-x/pull/17748

**Comment by dumganhar** [comment]
Merge this PR at https://github.com/cocos2d/cocos2d-x/pull/17923
Closed this one. Thanks @pwang08 .
