### ISSUE TITLE
Update GLFW to 3.2.1

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17700]
Refer to https://github.com/cocos2d/cocos2d-x/issues/16481

**Comment by Bilalmirza** [comment]
@minggo please update this... people have been asking for this for over a year.

**Comment by minggo** [comment]
@Bilalmirza sorry about it, i will update it after releasing v3.16. I am busy with creator cpp support for a long time.

**Comment by Bilalmirza** [comment]
@Bilalmirza , the upgrade will not be in v3.15 since it's in RC now.I create an issue #17700 here.It will probably be in v3.16.
--
:( :( :( :( :(

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/18434
