### ISSUE TITLE
Regenerating Projects after updating CmakeLists?

### ISSUE THREAD

**Issue by jojojames** [cocos2d/cocos2d-x#17711]
Hi, was wondering how to update other project files using Cmake after modifying CmakeLists.

https://github.com/cocos2d/cocos2d-x/issues/8911

Is a similar question though the answer leads to an xcode only solution (and the xcode solution isn't similar to what would be built with 'cocos new'.

**Comment by Rubonnek** [comment]
I had the same question some time ago and as far as I know there is no official way of doing this. Using the cmake generators will not regenerate the project templates that are provided in the repository.

A quick-and-dirty way to go about this this would be to parse the `CMakeLists.txt` and updating the other project files as needed. You can use Ruby and [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) to do this.

I wrote my own tool to for updating the win32, win10, Android, Mac and iOS project files with that and a bit of Perl, but it's still a work in progress and has not been open sourced yet.

As far as I can tell, the best way to do this would be to fix all the cmake-related files to properly regenerate the projects, but I'm not sure if we'll be able to regenerate all of them -- I'm not a CMake expert.

**Comment by jojojames** [comment]
@Rubonnek That's unfortunate. Cmake would be a good one stop. Automatic project generation on a CMake would be a great next first step.

I'd be interested if you ever open sourced your work around that.

**Comment by Rubonnek** [comment]
@jojojames the [code has been released](https://github.com/Rubonnek/ucm) under the GPL v3. If you are using Arch Linux, there's a [PKGBUILD in the AUR](https://aur.archlinux.org/packages/ucm/).

**Comment by jojojames** [comment]
@Rubonnek Thanks. I'll be keeping a close watch on that!

**Comment by Rubonnek** [comment]
By the looks of it, it seems like Urho3D is already able to do this for all their supported platforms. Under the [Urho3D CMake folder](https://github.com/urho3d/Urho3D/tree/master/CMake) there seems to be the necessary CMake modules and whatnot to generate the iOS, Mac, Android, and Windows builds. Perhaps someone could modify that back to work with Cocos since those files are also under the MIT license.

**Comment by drelaptop** [comment]
@jojojames @Rubonnek Cocos2d-x latest code(https://github.com/cocos2d/cocos2d-x/commit/4675ee79cd134ca63c8fd258c4e8a49f14fe9639 and later) have supported cmake build on all supported platforms. Welcome to use and feedback. Refer to [cmake/README.md](https://github.com/cocos2d/cocos2d-x/blob/v3/cmake/README.md)

please close this issue @minggo
