### ISSUE TITLE
API/ABI changes review for Cocos2d-x

### ISSUE THREAD

**Issue by lvc** [cocos2d/cocos2d-x#17715]
The review of API/ABI changes for Cocos2d-x since 3.8 version: https://abi-laboratory.pro/tracker/timeline/cocos2d-x/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![cocos2d-1](https://cloud.githubusercontent.com/assets/1517837/25081058/0bc057a4-2359-11e7-8e02-cd5ba794801a.png)
![cocos2d-2](https://cloud.githubusercontent.com/assets/1517837/25081091/45e394d2-2359-11e7-8433-86ce14769053.png)

## Environment
* Linux x86_64
* GCC 4.9
* Cocos2d-x 3.8 and higher

**Comment by minggo** [comment]
How does the tool work? What is defined compatibility? Does add new functions be treated compatible?

**Comment by lvc** [comment]
It is generally comply with https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C++.

Adding new functions is OK (green color in the report). Adding new virtual functions may not be OK in several cases (red color).

Thank you.
