### ISSUE TITLE
Singleline EditBox not return right Action when keyboard closed

### ISSUE THREAD

**Issue by quannv108** [cocos2d/cocos2d-x#17714]
- cocos2d-x version: 3.15, 3.14
- devices test on: iphone 5c
- developing environments
   - NDK version: ...
   - Xcode version: 8.3.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. create a single line editbox in code and run this code to device
auto bg = ui::Scale9Sprite::create("chat_boxchat.png");
```
    bg->setContentSize(editBoxSize);
    ui::EditBox *editbox = ui::EditBox::create(editBoxSize, bg);
    this->addChild(editbox, ChildTagInputBox, ChildTagInputBox);
    editbox->setAnchorPoint(Vec2::ANCHOR_MIDDLE);
    editbox->setPosition(winSize*0.5);
    editbox->setDelegate(this);
    editbox->setReturnType(ui::EditBox::KeyboardReturnType::SEND);
    editbox->setFont("fonts/Roboto-Medium.ttf", 30);
    editbox->setInputMode(cocos2d::ui::EditBox::InputMode::SINGLE_LINE);
    editbox->setInputFlag(cocos2d::ui::EditBox::InputFlag::SENSITIVE);
    editbox->setMaxLength(75);
```
3a. in application tap on editbox, write some things, and click "send", view the log return by delegate: editBoxEditingDidEndWithAction: 3 (3 mean return)
4a. tap in editbox again, write something, tap outside keyboard, the log say: editBoxEditingDidEndWithAction: 3 (this must be 0)
3b. force close application, run it again, but now, after write some things, tap on screen (out of keyboard), the log say: editBoxEditingDidEndWithAction: 0 (it return right on the first time only)
4b. tap editbox again, now click "return", it will return editBoxEditingDidEndWithAction: 3.
from now on, when keyboard was show, you tap out of keyboard or return it will always return editBoxEditingDidEndWithAction: 3 

5. How to fix ?
I found the way: 

```
- (BOOL)textFieldShouldBeginEditing:(UITextField *)sender        // return NO to disallow editing.
{
    CCLOG("textFieldShouldBeginEditing...");
    _editState = YES;
    _returnPressed = NO;   //add this
...
}
```

**Comment by JoHuang** [comment]
I met this, too.
