### ISSUE TITLE
cocos3.15 SocketIO can't support ssl with public key is rsa2048, sha2 signature?

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#17724]
socketio 不支持 sha2签名的ssl证书啊。（sha256 ， rsa:2048)
会报这个错 Websocket error received: 1

sha1签名的ssl证书是支持的

求确认， 求这个版本解决啊

**Comment by dumganhar** [comment]
Did you create a `self-signed certificate`? How did you create it?

**Comment by huangapple** [comment]
aliyun create
https://help.aliyun.com/knowledge_detail/42218.html

openssl req -new -nodes -sha256 -newkey rsa:2048 -keyout myprivate.key -out mydomain.csr
