### ISSUE TITLE
G++ Compile Error With backslash

### ISSUE THREAD

**Issue by ljwlaji** [cocos2d/cocos2d-x#17742]
- cocos2d-x version: 3.15
- devices test on: none
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:2015
   - browser type and version:

Steps to Reproduce:

1.  typing cocos compile -p android
...
...
when compile libmygame.so
arm-linux-androideabi -g++: error: E:testcocos2dexternal/xxx/xxx/xxx/xxx.a No Such file or dir
arm-linux-androideabi -g++: error: E:testcocos2dexternal/xxx/xxx/xxx/xxx.a No Such file or dir
arm-linux-androideabi -g++: error: E:testcocos2dexternal/xxx/xxx/xxx/xxx.a No Such file or dir
arm-linux-androideabi -g++: error: E:testcocos2dexternal/xxx/xxx/xxx/xxx.a No Such file or dir

libMyGame.so Error 1

when I update virsion from 3.13.1 To 3.15 those Error comes out

**Comment by minggo** [comment]
It seems the path is error. Can you build the tests shift by engine?

**Comment by minggo** [comment]
close it since it is unresponsible
