### ISSUE TITLE
Has Screenshot! How to apply color effect like FLASH in cocos2dx?

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#17744]
- cocos2d-x version:3.10
I want to write a function to apply the same color effect (at below) in cocos2dx, but have no idea yet.
Can somebody give me a help~ THANKS!

![color_effect](https://cloud.githubusercontent.com/assets/848803/25369620/d6be9f6a-29b7-11e7-9dc7-8dfbed4d0a6a.png)

**Comment by yuriilychak** [comment]
Hello. Open cocos test case. I think you need to see the examples: 
45. Node:Sprite -> 30. Testing SpriteBatchNode Color & opacity.
59. Shader - Basic.
If you know russian I know a little tutorial for  [base Adobe Flash filters](http://abdulgalimov.com/Cocos2d/Shader-Examples/) in javascript version of engine. in C++ code will be the same

**Comment by liuyi** [comment]
@yuriilychak Thanks for your advise. I checked the Russian sample,  maybe I need learn more  OPENGL before write this color effect...   !_!

**Comment by liuyi** [comment]
I found a article introduced color martrix, it looks like what I need, but I don't know how to use it in cocos2dx...

 [http://www.graficaobscura.com/matrix/](url)
 
OK, here is an nice project!  

[https://github.com/stevetranby/cocos2dx-shader-cookbook/blob/master/docs/E12_ColorMatrix.md](url)

**Comment by liuyi** [comment]
@yuriilychak Do you know how to use this shader? 
Can someone write an simple code example?
No OPEN GL experience...

FSH:

#ifdef GL_ES
precision mediump float;
#endif

uniform mat4 u_ColorMatrix;

varying vec2 cc_FragTexCoord1;

void main(){
	gl_FragColor = u_ColorMatrix * texture2D(CC_Texture0, cc_FragTexCoord1);
}


//-----------------------------
vsh:
uniform vec2 u_NoiseTexturePixelSize;
uniform vec2 cc_ViewSizeInPixels;

attribute vec4 a_position;
attribute vec2 a_texCoord;
attribute vec4 a_color;

#ifdef GL_ES
varying mediump vec4 cc_FragColor;
varying mediump vec2 cc_FragTexCoord1;
#else
varying vec4 cc_FragColor;
varying vec2 cc_FragTexCoord1;
#endif

void main()
{
	gl_Position = CC_PMatrix * a_position;
	cc_FragColor = clamp(a_color, 0.0, 1.0);
	cc_FragTexCoord1 = a_texCoord;
}

[shader.zip](https://github.com/cocos2d/cocos2d-x/files/954268/shader.zip)

**Comment by liuyi** [comment]
Resolved!

 var _self=this;

        _self.shader = new cc.GLProgram("res/shader/E12_ColorMatrix.vsh", "res/shader/E12_ColorMatrix.fsh");
        //_self.shader.retain();
        _self.shader.link();
        _self.shader.updateUniforms();

         var glProgram_state = cc.GLProgramState.getOrCreateWithGLProgram(_self.shader);
        var u_ColorMatrix=[
            1,0,0,0,
            0,1,0,0,
            0,0,1,0,
            0,0,0,1
        ];
        // u_ColorMatrix=[
        //     -1,255,0,0,
        //     0,-1,0,0,
        //     0,0,1,0,
        //     0,0,0,1
        // ];

        // u_ColorMatrix=[
        //     0.3086, 0.6094, 0.0820, 0,
        //     0.3086, 0.6094, 0.0820, 0,
        //     0.3086, 0.6094, 0.0820, 0,
        //     0    , 0    , 0    , 1
        // ];
        //

        u_ColorMatrix=[
            1,0,0,0,
            0,0,0,0,
            0,0,0,0,
            0.5,0,0,0.3
        ];
        var martixBuffer=new Float32Array(u_ColorMatrix);

        glProgram_state.setUniformMat4("u_ColorMatrix", u_ColorMatrix);


        target.setGLProgramState(glProgram_state);

Shader come from https://github.com/stevetranby/cocos2dx-shader-cookbook/blob/master/docs/E12_ColorMatrix.md
[shader.zip](https://github.com/cocos2d/cocos2d-x/files/954373/shader.zip)
