### ISSUE TITLE
xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH

### ISSUE THREAD

**Issue by fuyifan** [cocos2d/cocos2d-x#17758]
- cocos2d-x version: 3.14.1
- devices test on: mac
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  Run cocos console : cocos compile -p ios -m release -j4 --sign-identity "iPhone Developer"
2. Get the error: cocos compile -p ios -m release -j4 --sign-identity "iPhone Developer"

**Comment by minggo** [comment]
Did you use Xcode 8.3+? `PackageApplication ` is deprecated in Xcode 8.3 +. It seems [this thread](http://stackoverflow.com/questions/43094380/whats-the-replacement-for-xcodes-packageapplication) has a solution, but i can not even compile the project using the command of `cocos compile -p ios -m release -j4 --sign-identity "iPhone Developer: XXXX"`. I met the error:

```
Signing for "cpp-empty-test iOS" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
```

**Comment by fuyifan** [comment]
Mingo, iPhone developer is the sign for publish the formal IPA. Without the signing you can only compiled and get the simulated i386 package. The issue is related with xcode8.3

**Comment by minggo** [comment]
Yep, i pass the sign information in `--sign-identity`, but it seems now it can not work just pass sign information.

**Comment by fuyifan** [comment]
mingo, I use the PackageApplication from the older xcode version and it compiled successful. However, it seems the compiled ipa contains only the 32bit app and after installation in iphone it shows dialog 应用开发者需要更新此应用以改进其兼容性. But if i use xcode to build the package it doesn't show this issue.

**Comment by minggo** [comment]
So it seems there are 3 issues:

* PackageApplication with Xcode 8.2 or lower version has compatibility issue
* PackageApplication is deprecated in Xcode 8.3+
* console can not build with Xcode 8.3+

**Comment by minggo** [comment]
@fuyifan i run the command `cocos compile -p ios -m release -j4 --sign-identity "iPhone Developer"`, only build simulated i386 package. Are you sure you use the command like that?

**Comment by minggo** [comment]
Ok, meet the same error as i mentioned above again.
@fuyifan did you meet the error?
```
Signing for "cpp-empty-test iOS" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
```

**Comment by minggo** [comment]
Ok, should have to select develop team using Xcode.

**Comment by minggo** [comment]
[The ticket](https://stackoverflow.com/questions/39674237/xcrun-command-to-export-ipa-file-xcode8-for-iphoneos10-0) provides a solution that uses `xcodebuild archive` to generate `.xcarchive` first, then generate `.ipa`. But `xcodebuild archive` will `do a full rebuild of all targets` every time.

**Comment by minggo** [comment]
fix it in https://github.com/cocos2d/cocos2d-console/pull/421

Edit: update cocos2d-x's console in https://github.com/cocos2d/cocos2d-x/pull/17862
