### ISSUE TITLE
ProgressTimer Bug on move parent

### ISSUE THREAD

**Issue by edmand46** [cocos2d/cocos2d-x#17755]
- cocos2d-x version: 3.14.1, 3.15
- devices test on: Mac OS Chrome 58
   - browser type and version:

Steps to Reproduce:
```
  var crosshire = new cc.Sprite(res.cursoir_png);
    var coolDownTimer = new cc.ProgressTimer(new cc.Sprite(res.reloading_png));
    coolDownTimer.setType(cc.ProgressTimer.TYPE_RADIAL);
    coolDownTimer.setPercentage(100);
    crosshire.addChild(coolDownTimer);

    uiLayer.addChild(crosshire);

```
And mouse down, in mouse move i update position crosshire
```
  onMouseDown: function (event) {
                coolDownTimer.runAction(
                    cc.sequence(cc.progressFromTo(1, 0, 100),
                        cc.callFunc(function () {
                            .....
                        })
                    )
                );
```

http://discuss.cocos2d-x.org/t/progress-timer-radial/36492
![0a425a871245594b1545ba56728ee2e110dbc4dd](https://cloud.githubusercontent.com/assets/10086099/25445265/a0b5d37a-2ab6-11e7-9f94-c47333053e89.gif)

**Comment by ty5236305** [comment]
@minggo this bug is really serious. Could you fix it?

**Comment by minggo** [comment]
@pandamicro please take a look.

**Comment by ty5236305** [comment]
I try it and it works! Thank you! @minggo @pandamicro
