### ISSUE TITLE
cocos3.15  热更新 使用https， 安卓， win 失败， ios可以

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#17763]
详情见这边
http://forum.cocos.com/t/creator1-4-5s-https-certificate-for-cdn-qiyimofang-com-doesnt-match-any-of-the-subject-alternative-names-ucd1-pp-uc-cn/44489/8

**Comment by plutoo** [comment]
It is a duplicate issue as  https://github.com/cocos2d/cocos2d-x/issues/17473. @minggo
