### ISSUE TITLE
我想问一下你们统一的测试开发编译环境，NDK版本用的哪个，targetSdk version是哪个，compileSDK version是哪个，谢谢！

### ISSUE THREAD

**Issue by xygahs0801** [cocos2d/cocos2d-x#17773]

**Comment by minggo** [comment]
We don't have the uniform environments. I always use NDK r13. targetSDk version and compile SDK version depends on what versions you want to support.

**Comment by xbpiao** [comment]
编译Android版本无所谓的，用最新的NDK也没问题，Lua绑定的脚本支持android-ndk-r9d或者android-ndk-r10d

其它版本就得自己改改.py了
