### ISSUE TITLE
Latest cocos2d-x v3.15 not using latest Box2D v2.3.2

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#17776]
Cocos2d-x v3.15 uses old Box2D v2.3.0.

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/blob/v3/Box2D/Common/b2Settings.cpp#L24

Need update to v2.3.2

https://github.com/erincatto/Box2D/blob/master/Box2D/Box2D/Common/b2Settings.cpp#L24

**Comment by Anywhere-Music-Player** [comment]
@minggo ?

**Comment by minggo** [comment]
I think you can update it yourself easily.

**Comment by Anywhere-Music-Player** [comment]
For sure, but it's not about that.
