### ISSUE TITLE
websockets can't connect to localhost ws server , can't initiate connection

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#17770]
- cocos2d-x version: 3.15 c++
- devices test on: windows 10
- developing environments
  - VS version: 2015 64 bit 
 c++ 

Steps to Reproduce:
simple code that is taken from the WebSocketsTest cocos2dx example i setup simple web socket server 
running local host
trying to make simple websocket connection to the server without success , connecting from HTML5 working great so the server is working 
i call the InitManager() from another sprite 
i compiled the websocket with full debug level : 
here is the log: 
```
Ready for GLSL
Ready for OpenGL 2.0

{
	gl.version: 4.4.0 - Build 21.20.16.4550
	gl.supports_NPOT: true
	cocos2d.x.version: cocos2d-x-3.15
	cocos2d.x.compiled_with_profiler: false
	cocos2d.x.build_type: DEBUG
	cocos2d.x.compiled_with_gl_state_cache: true
	gl.max_texture_size: 16384
	gl.supports_OES_packed_depth_stencil: false
	gl.vendor: Intel
	gl.renderer: Intel(R) HD Graphics 520
	gl.max_texture_units: 192
	gl.supports_ETC1: false
	gl.supports_S3TC: true
	gl.supports_ATITC: false
	gl.supports_PVRTC: false
	gl.supports_BGRA8888: false
	gl.supports_discard_framebuffer: false
	gl.supports_vertex_array_object: true
	gl.supports_OES_map_buffer: false
	gl.supports_OES_depth24: false
}


cocos2d: fullPathForFilename: No file found at /cc_2x2_white_image. Possible missing file.
cocos2d: QuadCommand: resizing index size from [-1] to [2560]
SpriteBase::onTouchBegan id = 0, x = 242.995331, y = 219.901718
sprite began... x = 52.995331, y = 49.901718
D/WebSocket.cpp (416): WebSocket thread start, helper instance: 0947BE58

D/WebSocket.cpp (168): NOTICE: Initial logging level 1023


D/WebSocket.cpp (168): NOTICE: Libwebsockets version: 2.1.0 desktop-8c9aqu5\cocosengine@DESKTOP-8C9AQU5-v3.4-141-gcddc296


D/WebSocket.cpp (168): NOTICE: IPV6 not compiled in


return true
D/WebSocket.cpp (168): NOTICE: libev support not compiled in


D/WebSocket.cpp (168): NOTICE: libuv support not compiled in


D/WebSocket.cpp (168): NOTICE:  Threads: 1 each 30000 fds


D/WebSocket.cpp (168): NOTICE:  Compiled with OpenSSL support


D/WebSocket.cpp (168): NOTICE:  mem: per-conn:          392 bytes + protocol rx buf


D/WebSocket.cpp (874): scheme: ws, host: 127.0.0.1, port: 0, path: /wsapi

D/WebSocket.cpp (168): NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 off


'WebSocketTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptsp.dll'. Cannot find or open the PDB file.
'WebSocketTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rsaenh.dll'. Cannot find or open the PDB file.
'WebSocketTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcrypt.dll'. Cannot find or open the PDB file.
D/WebSocket.cpp (168): NOTICE: lws_protocol_init


'WebSocketTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mswsock.dll'. Cannot find or open the PDB file.
'WebSocketTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wshqos.dll'. Cannot find or open the PDB file.
'WebSocketTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WSHTCPIP.DLL'. Cannot find or open the PDB file.
'WebSocketTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wship6.dll'. Cannot find or open the PDB file.
D/WebSocket.cpp (1323): WebSocket (0955B368) Unhandled websocket event: 32

D/WebSocket.cpp (1323): WebSocket (0955B368) Unhandled websocket event: 29

D/WebSocket.cpp (1323): WebSocket (0955B368) Unhandled websocket event: 33

D/WebSocket.cpp (1198): WebSocket (0955B368) onConnectionError, state: 0 ...

D/WebSocket.cpp (1227): WebSocket (0955B368) onConnectionClosed, state: 2 ...

D/WebSocket.cpp (1257): onConnectionClosed, WebSocket (0955B368) is closing by server.

D/WebSocket.cpp (1280): WebSocket (0955B368) onConnectionClosed DONE!

D/WebSocket.cpp (1227): WebSocket (0955B368) onConnectionClosed, state: 3 ...

D/WebSocket.cpp (168): NOTICE: lws_header_table_detach: wsi 09429F30: ah held 4s, ah.rxpos 0, ah.rxlen 0, mode/state 34 4,wsi->more_rx_waiting 0


Error was fired, error code: 1
An error was fired, code: 1
onClose: websocket instance (0955B368) closed.
Send Binary WS was closed
D/WebSocket.cpp (546): In the destructor of WebSocket (0955B368)

D/WebSocket.cpp (566): before join ws thread

D/WebSocket.cpp (168): NOTICE: lws_context_destroy


'WebSocketTest.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\WSHTCPIP.DLL'
'WebSocketTest.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\wship6.dll'
'WebSocketTest.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\wshqos.dll'
The thread 0x2950 has exited with code 0 (0x0).
D/WebSocket.cpp (426): WebSocket thread exit, helper instance: 0947BE58

D/WebSocket.cpp (568): after join ws thread

The thread 0x1ec4 has exited with code 0 (0x0).

``` 

 here is the code : 
```
#include "WebSocketManager.h"
 
 
WebSocketManager::WebSocketManager()
	: 
	 _wsiSendBinary(nullptr)
	, _sendBinaryTimes(0)	 
	, _sendBinaryStatus("")	 
{
	
}

WebSocketManager::~WebSocketManager()
{

}

//void WebSocketManager::onExit()
//{
//	
//
//	if (_wsiSendBinary)
//	{
//		_wsiSendBinary->closeAsync();
//	}
//
//	
//	Node::onExit();
//}

void WebSocketManager::InitManager()
{
	 
	
	_wsiSendBinary = new network::WebSocket();
	

	std::vector<std::string> protocols;
	protocols.push_back("wsapi");
	//protocols.push_back("myprotocol_2");
	
	protocols.erase(protocols.begin());
	if (!_wsiSendBinary->init(*this, "ws://127.0.0.1/wsapi",&protocols))
	{
		CC_SAFE_DELETE(_wsiSendBinary);
	}
	else
	{
		retain(); // Retain self to avoid WebSocketManager instance be deleted immediately, it will be released in WebSocketManager::onClose.
	}

}

// Delegate methods
void WebSocketManager::onOpen(network::WebSocket* ws)
{
	char status[256] = { 0 };
	sprintf(status, "Opened, url: %s, protocol: %s", ws->getUrl().c_str(), ws->getProtocol().c_str());

	if (ws == _wsiSendBinary)
	{
		_sendBinaryStatus = status;
		log("_sendBinaryStatus %s", _sendBinaryStatus.c_str());
	}
	else
	{
		CCASSERT(0, "error test will never go here.");
	}
}

void WebSocketManager::onMessage(network::WebSocket* ws, const network::WebSocket::Data& data)
{
	
		_sendBinaryTimes++;
		char times[100] = { 0 };
		sprintf(times, "%d", _sendBinaryTimes);

		std::string binaryStr = "response bin msg: ";

		for (int i = 0; i < data.len; ++i) {
			if (data.bytes[i] != '\0')
			{
				binaryStr += data.bytes[i];
			}
			else
			{
				binaryStr += "\'\\0\'";
			}
		}

		binaryStr += std::string(", ") + times;
		log("%s", binaryStr.c_str());
		_sendBinaryStatus = binaryStr;
	
}

void WebSocketManager::onClose(network::WebSocket* ws)
{
	log("onClose: websocket instance (%p) closed.", ws);
	if (ws == _wsiSendBinary)
	{
		_wsiSendBinary = nullptr;
		_sendBinaryStatus = "Send Binary WS was closed";
		log("%s", _sendBinaryStatus.c_str());
	}
	else 
	{
		
		log("onClose error");
	}
	// Delete websocket instance.
	CC_SAFE_DELETE(ws);
	//log("WebSocketManager ref: %u", _referenceCount);
	//release();
}

void WebSocketManager::onError(network::WebSocket* ws, const network::WebSocket::ErrorCode& error)
{
	log("Error was fired, error code: %d", static_cast<int>(error));
	char buf[100] = { 0 };
	sprintf(buf, "An error was fired, code: %d", static_cast<int>(error));

	if (ws == _wsiSendBinary)
	{
		_sendBinaryStatus = buf;
		log("%s", _sendBinaryStatus.c_str());
	}
	else
	{		 
		log("_wsiSendBinary onError");
	}
}




void WebSocketManager::onSendBinary()
{
	if (!_wsiSendBinary) {
		return;
	}

	if (_wsiSendBinary->getReadyState() == network::WebSocket::State::OPEN)
	{
		_sendBinaryStatus ="Send Binary WS is waiting...";
		log("%s", _sendBinaryStatus.c_str());

		char buf[] = "Hello WebSocket,\0 I'm\0 a\0 binary\0 message\0.";
		_wsiSendBinary->send((unsigned char*)buf, sizeof(buf));
	}
	else
	{
		std::string warningStr = "send binary websocket instance wasn't ready...";
		log("%s", warningStr.c_str());
		_sendBinaryStatus = warningStr.c_str();
		log("%s", _sendBinaryStatus.c_str());
	}
}




```

Header : 
```
class WebSocketManager  : public cocos2d::Sprite, public cocos2d::network::WebSocket::Delegate
{
public:
	CREATE_FUNC(WebSocketManager);

	WebSocketManager();
	virtual ~WebSocketManager();

	//virtual void onExit() override;

	virtual void onOpen(cocos2d::network::WebSocket* ws)override;
	virtual void onMessage(cocos2d::network::WebSocket* ws, const cocos2d::network::WebSocket::Data& data)override;
	virtual void onClose(cocos2d::network::WebSocket* ws)override;
	virtual void onError(cocos2d::network::WebSocket* ws, const cocos2d::network::WebSocket::ErrorCode& error)override;

	
	void onSendBinary();
	void InitManager();
	

private:
	cocos2d::network::WebSocket* _wsiSendBinary;
	int _sendBinaryTimes;
	std::string  _sendBinaryStatus;
	
};
```

**Comment by Rubonnek** [comment]
Have you tried connecting using "http://" instead of "ws://"? For example, change

````cpp
_wsiSendBinary->init(*this, "ws://127.0.0.1/wsapi",&protocols)
````
to

````cpp
_wsiSendBinary->init(*this, "http://127.0.0.1/wsapi",&protocols)
````
libwebsockets should handle the http handshake for you. I'm not quite sure if that will work -- I haven't tested it, but it seems like your server expects an `http` connection first that will then be upgraded to a `websocket` connection.

I coded my own websocket server in C and the Cocos2D-X wrapper works as expected, but in my case I never upgrade the connections from `http` nor `https`. I just use pure `ws` and `wss`.

**Comment by meiry** [comment]
Hey , no i didn't as the standard is ws:: . 
well in my case i don't think its even reaching to the server .... will try with wireshark ...

**Comment by Rubonnek** [comment]
@meiry I knew your username sounded familiar -- I used your tutorial to make my websockets server in C. I even sent you an email with the memory leak patch I found in the Cocos2D-X client code wrapper (which is at #17653), and to which you replied to. Sir, I will personally help you with your C++ client code. Thanks again for the tutorial, it was very helpful.

We are on the same boat when it comes to server code since we are using the same C library. So, let's strip the C++ client code down to the very basics, and let me give a full overview just to cover the basics. I tested everything before in Linux, and I just tested this in Windows again and this works with my server -- should work with yours too.

## Minimal Setup

For completeness sake, let's create a brand new project just to test our connection:

```shell
cocos new -l cpp websockettest
```

All you really need to write, just get the libwebsockets `LWS_CALLBACK_ESTABLISHED` callback on the server, is the following: [a subclass of the `cocos2d::network::WebSocket::Delegate`](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L7-L42) to add the client logic, and to [run the `cocos2d::network::WebSocket::init`](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L106-L111) function when the `cocos2d::network::WebSocket` object has been created.

## Client Delegate - Member Functions Call Order

Assuming we only want to receive something once and that the connection to the server was successful, the order of the `WebSocket::Delegate` subclass callbacks go as written in the test: [onOpen -> onMessage -> onClose](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L20-L41). onError will obviously be called when there's an error after a successful connection to the server, but if the connection to the server is not successful, none of the delegate functions will be called. 

## Memory Management

The pointer that points to the [memory allocated for the network::WebSocket object](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L106) gets passed around in the WebSocket::Delegate functions in the first parameter. Since the [onClose function will be the last function called from the delegate subclass, we can free the memory there](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L35-L41) if needed.

## How to close all the websocket connections at once

According to the documentation, the code that closes all the connections must run in the cocos thread, and not the websockets thread. Therefore, whenever you want to close all the connections, all you have to write is:

````cpp
cocos2d::Director::getInstance()->getScheduler()->performFunctionInCocosThread(
	[] ()
	{
		cocos2d::network::WebSocket::closeAllConnections();
	}
	);
````
I left a [commented block here](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L114-L119), just in case anyone else finds the code online.

I believe this should be enough to get you started on your C++ client. Let me know if you have any questions, I'll be glad to help.

**Comment by meiry** [comment]
Hey @Rubonnek
Thanks allot for your kind words and the help . 
The problem with my code I guess is that 
I do not use libwebsockets as the server as in the tutorial . 
This time I'm using uWS as server 
https://github.com/uWebSockets/uWebSockets
And I guess the problem is in that server.
As setting up uWS server and libwebsockets client do not work 

Ok i tryed your code using the latest cocos code .
but again strange behavior let me point out that when i open simple web sockets connection from JavaScript every thing is working on the server .
using your simple code : im getting those print logs in the cocos client : 
```
D/WebSocket.cpp (1323): WebSocket (08A6F428) Unhandled websocket event: 32

D/WebSocket.cpp (1323): WebSocket (08A6F428) Unhandled websocket event: 29

D/WebSocket.cpp (1323): WebSocket (08A6F428) Unhandled websocket event: 33

D/WebSocket.cpp (1198): WebSocket (08A6F428) onConnectionError, state: 0 ...

D/WebSocket.cpp (1227): WebSocket (08A6F428) onConnectionClosed, state: 2 ...

D/WebSocket.cpp (1257): onConnectionClosed, WebSocket (08A6F428) is closing by server.

D/WebSocket.cpp (1280): WebSocket (08A6F428) onConnectionClosed DONE!

D/WebSocket.cpp (1227): WebSocket (08A6F428) onConnectionClosed, state: 3 ...

```

here is when the code is invoked on OnError: 

![vs](https://cloud.githubusercontent.com/assets/1107316/25692653/f4a3f812-30ac-11e7-9f1c-c8d73ac5efbf.PNG)


And also the wireshark image that shows that there is some kind of connectivity to the server but very minimal .
![wshark](https://cloud.githubusercontent.com/assets/1107316/25692670/11f3fe9e-30ad-11e7-9e10-2f68c907e0b3.PNG)

**Comment by Rubonnek** [comment]
That's strange. I compiled the [uWS echo server](https://github.com/uWebSockets/uWebSockets/blob/master/examples/echo.cpp) in Linux and I was able to connect. After sending the text "Test", I received the same text on my client.

Mind if we double check the URL you are using? The [uWS echo server example](https://github.com/uWebSockets/uWebSockets/blob/master/examples/echo.cpp#L11) listens in port 3000, this has to be added to the `WebSocket::init` function. Using my test, just [change line 107](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L107) to:

````cpp
	if(!websocket_test->init(*WebSocketClientDelegate::getInstance(), "ws://127.0.0.1:3000")) 
````

After running my test, you should see "onOpen" on the log messages somewhere between all the other messages.

**Comment by Rubonnek** [comment]
Here, let me add how the log looks when I successfully connected to the uWS echo server and sent the "Test" text:

````
D/WebSocket.cpp (415): WebSocket thread start, helper instance: 0x37b2950
D/WebSocket.cpp (167): NOTICE: Initial logging level 911
D/WebSocket.cpp (167): NOTICE: Libwebsockets version: 2.1.0 cocosengine@cjh-ubuntu-v3.4-142-geae656d
D/WebSocket.cpp (167): NOTICE: IPV6 compiled in and enabled
D/WebSocket.cpp (167): NOTICE: libev support not compiled in
D/WebSocket.cpp (167): NOTICE: libuv support not compiled in
D/WebSocket.cpp (167): NOTICE:  Threads: 1 each 1024 fds
D/WebSocket.cpp (167): NOTICE:  mem: platform fd map:  8192 bytes
D/WebSocket.cpp (167): NOTICE:  Compiled with OpenSSL support
D/WebSocket.cpp (167): NOTICE:  mem: per-conn:          512 bytes + protocol rx buf
D/WebSocket.cpp (873): scheme: ws, host: 192.168.2.142, port: 3000, path: 
D/WebSocket.cpp (167): NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 on
D/WebSocket.cpp (167): NOTICE: lws_protocol_init
D/WebSocket.cpp (1322): WebSocket (0x37b2740) Unhandled websocket event: 32
D/WebSocket.cpp (1322): WebSocket (0x37b2740) Unhandled websocket event: 29
D/WebSocket.cpp (1322): WebSocket (0x37b2740) Unhandled websocket event: 24
D/WebSocket.cpp (1322): WebSocket (0x37b2740) Unhandled websocket event: 2
D/WebSocket.cpp (1163): onConnectionOpened...: 0x37b2740, client protocols: , server selected protocol: 
D/WebSocket.cpp (1061): Safely done, msg(2)!
D/WebSocket.cpp (1064): msg(2) append: 0 + 4 = 4
D/WebSocket.cpp (1065): msg(2) was totally sent!
D/WebSocket.cpp (1081): -----------------------------------------------------------
D/WebSocket.cpp (1102): Receiving data:index:1, len=4
D/WebSocket.cpp (1136): Notify data len 4 to Cocos thread.
Received message: Test
D/WebSocket.cpp (744): closeAsync: WebSocket (0x37b2740) is closing...
D/WebSocket.cpp (935): Closing websocket (0x37b2740) connection.
D/WebSocket.cpp (1322): WebSocket (0x37b2740) Unhandled websocket event: 33
D/WebSocket.cpp (1322): WebSocket (0x37b2740) Unhandled websocket event: 50
D/WebSocket.cpp (1322): WebSocket (0x37b2740) Unhandled websocket event: 4
D/WebSocket.cpp (1226): WebSocket (0x37b2740) onConnectionClosed, state: 2 ...
D/WebSocket.cpp (1252): onConnectionClosed, WebSocket (0x37b2740) is closing by client asynchronously.
D/WebSocket.cpp (1279): WebSocket (0x37b2740) onConnectionClosed DONE!
D/WebSocket.cpp (545): In the destructor of WebSocket (0x37b2740)
D/WebSocket.cpp (565): before join ws thread
D/WebSocket.cpp (167): NOTICE: lws_context_destroy
D/WebSocket.cpp (425): WebSocket thread exit, helper instance: 0x37b2950
D/WebSocket.cpp (567): after join ws thread
````

To get the log above, you'll have to [rewrite the `onOpen` and `onMessage`](https://github.com/Rubonnek/minimal-cocos2d-x-websocket-client/blob/master/Classes/HelloWorldScene.cpp#L20-L28) delegate methods in my test with the following: 

````cpp
virtual void onOpen(network::WebSocket* ws) override
{
	//CCLOG("onOpen called");
	ws->send("Test");
	return;
}

virtual void onMessage(network::WebSocket* ws, const network::WebSocket::Data& data) override
{
	CCLOG("Received message: %s", (char *)data.bytes);
	ws->closeAsync();
}
````

**Comment by meiry** [comment]
Thanks for your testing , i know you are using linux as your working box . 
maybe the problem is im using windows and uWS have problem there ...
can you test on windows ? if it is working on windows . 
definitely the problem is my . 
as im using VSC++ 2015 both client and server on the same machine.

**Comment by Rubonnek** [comment]
You are right -- I was able to reproduce the connection error on Windows when both client and server are running on the same machine. I also tried connecting from Linux to my Windows machine running the uWS server and I got a timeout error, as if the communication got stuck while connecting. Seems like [uWebSockets issue #582](https://github.com/uWebSockets/uWebSockets/issues/582) could be related to this, the only difference being that that issue happened on Mac. The underlying problem could be entirely unrelated though.

I also tested with uWS v0.14.3, but I still got the same errors.

**Comment by meiry** [comment]
Great ! thanks so we are on something , there is problem lts try to fix it .. 

Did testing down to version v0.10.0 and still it is not working .. i guess not need to get lower then this . 
There is major bug there ..

**Comment by ghost** [comment]
@meiry You are most probably mixing Ipv6 and Ipv4 up. Windows servers only listen to either, not both. Make sure what you listen for is the same you connect to. You can use listen option ONLY_IPV4 on Windows to force Ipv4 server side. Just because you feel frustrated with an issue doesn't mean you can just drop it at me without making any kind of effort to figure things out youself.

**Comment by Rubonnek** [comment]
@minggo This issue can be closed. It's not related to the websockets client implementation in cocos2d-x, but the server. @meiry already found the issue and he said so in the last comment of [uWebSockets issue #582](https://github.com/uWebSockets/uWebSockets/issues/582).

**Comment by minggo** [comment]
K, thanks for the information.
