### ISSUE TITLE
sprite culling bug when using SpriteFrame

### ISSUE THREAD

**Issue by G17hao** [cocos2d/cocos2d-x#17797]
-- cocos2d-x version:3.15
-- platform: win32 (i didn't try other platform)
--[[
create a lua project
copy this code to main.lua
run it.
the helloWorld.png will be hide when it close to top of screen
--]] 
------------------------------------
local s = cc.Scene:create()

local spr = cc.Sprite:create("res/HelloWorld.png");
local tex = spr:getTexture();
print(tex)
local sz = spr:getContentSize()
sz.x = 0
sz.y = 0
local sf = cc.SpriteFrame:createWithTexture(tex,sz);
sf:setOffset({x=300,y=-300})
local spr1 = cc.Sprite:create();
spr1:setSpriteFrame(sf)

s:addChild(spr1)
spr1:runAction(cc.RepeatForever:create(cc.Sequence:create(cc.MoveTo:create(3,{x=480,y=960}),cc.MoveTo:create(3,{x=480,y=480}))))

cc.Director:getInstance():runWithScene(s)
print("end")

**Comment by minggo** [comment]
Why you set this
```
sf:setOffset({x=300,y=-300})
```

**Comment by G17hao** [comment]
ohh. ok. it not a issue.
it also Reproduce for spritesheet frame.
we have some spritesheet animation, all frame in spritesheet has offset. 
i just seted offset. but didn't set the OriginalSize.
