### ISSUE TITLE
run JS_CallFunctionValue in Sub-Thread produce JS: <no filename="filename">:0:too much recursion

### ISSUE THREAD

**Issue by yemingyu** [cocos2d/cocos2d-x#17793]
- cocos2d-x version: latest
- devices test on: iOS
- developing environments
   - NDK version:
   - Xcode version: 8.3
   - VS version:
   - browser type and version:

**Comment by DavidDeSimone** [comment]
You should only interact with Spidermonkey on the main cocos thread. If you interact with Spidermonkey on any other thread besides the main cocos thread, it may cause bizarre bugs and hard to track down issues.

**Comment by minggo** [comment]
@yemingyu did you use SpiderMonkey as @DavidDeSimone said?

**Comment by yemingyu** [comment]
@minggo Yes, and I need to use SpiderMonkey to run js code in  any other thread besides the main cocos thread,run js code in main cocos thread would cause Interface Caton

**Comment by yemingyu** [comment]
Do you know how to build a threadsafe Spidermonkey @DavidDeSimone @minggo

**Comment by minggo** [comment]
@yemingyu sorry, i don't know. I think SpiderMonkey can not be thread-safe.
