### ISSUE TITLE
AudioEngine Issues in cocos2dx-v3.8.1

### ISSUE THREAD

**Issue by yunmin97** [cocos2d/cocos2d-x#17801]
- cocos2d-x version:   3.8.1
- devices test on:   android7.0
- developing environments
   - NDK version:     ndk-10re
   - VS version:   vs2015
问题： 
1、 以前因为音频无法完美循环问题，根据官方建议把v3.12版本的AudioEngine移植到3.8.1版本下来使用，确实解决了不完美循环的问题，但是现在发现移植后的音频在android7.0机型下卡顿严重甚至播放不出声音！！
2、请问现在3.15版本的AudioEngine模块是否解决了不完美循环和是否在android7.0机型上面会卡顿?
3、如果3.15版本的AudioEngine完全没问题，那么是否有无可能移植到3.8.1版本上使用？
4、如果能够移植，官方有没有移植的具体方案？

备注：以前把v3.12版本的AudioEngine移植到3.8.1版本的移植：#16144

**Comment by fuyifan** [comment]
你直接将Audio下的所有东西复制过去试试就可以了吧，我记得我之前3.7升级到3.12版本的没有问题3.14升3.15也是可以的。

**Comment by yunmin97** [comment]
是的，已经完成移植，谢谢。。
