### ISSUE TITLE
Not stable delta time in default update() method, CADisplayLink duration or timestamp not used?

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#17806]
- Cocos2d-x 3.15 and other
 - Devices test on: iPhone 6 and any other

Steps to Reproduce:

1. Create a simple HelloWorld project and add only `scheduleUpdate(); `
2. Check `delta` from 
```
void HelloWorld::update(float delta) {
    CCLOG("%f",delta);
 }
```

Notice output like this: 

```
0.018591
0.015011
0.017311
0.015939
0.017793
0.015640
0.016709
0.016957
0.017268
0.015884
0.016776
0.016478
0.016699
0.018520
```

For compare, same setup but using **cocos2d-iphone v3**, so Objective C, gives me rock and solid output:

```
0.016720
0.016674
0.016676
0.016675
0.016675
0.016675
0.016707
0.016687
0.016672
0.016677
0.016632
0.016644
```

As result, using cocos2d-x for my game(I ported it from cocos2d-iphone) gives me a different result in terms of image quality. Main character moves quickly and as result image is not so.. clear, nice and smooth as was before in cocos2d-iphone. I'm not talking about jitter or other very noticeable things, but this problem I can clearly identify. And it's really caused by that not stable numbers comes from `update()`.

**Comment by Anywhere-Music-Player** [comment]
@minggo I've found some info: http://www.learn-cocos2d.com/2013/10/game-engine-multiply-delta-time-or-not/ 

> This is a particular issue with cocos2d because it does not use the CADisplayLink duration property. Instead it relies on system timers to calculate the time difference. As a result, cocos2d’s delta time is merely an approximation and ever-so-slightly disconnected from the actual refresh rate. Other game engines may or may not have the same issue.

So, as I see, this was fixed since that time for cocos2d-iphone v3, but currently a problem for cocos2d-x.

**Comment by Anywhere-Music-Player** [comment]
@minggo Here is how it works for cocos2d-iphone 
https://github.com/cocos2d/cocos2d-objc/blob/v3.5.0/cocos2d/Platforms/iOS/CCDirectorIOS.m#L379

I believe this should be same for cocos2d-x for iOS. More stable delta - more smooth and more quality from game. Thats what I'm seeing when playing my game compiled under cocos2d-iphone v3..

**Comment by Anywhere-Music-Player** [comment]
Also, this similar solution was for android https://github.com/cocos2d/cocos2d-objc/blob/v3.4/cocos2d/Platforms/Android/CCDirectorAndroid.m#L195

**Comment by Anywhere-Music-Player** [comment]
Okay, so what is needed to do is back this code to iOS: 

```
// Overriden in order to use a more stable delta time
-(void) calculateDeltaTime
{
    // New delta time. Re-fixed issue #1277
    if( _nextDeltaTimeZero || _lastDisplayTime==0 ) {
        _dt = 0;
        _nextDeltaTimeZero = NO;
    } else {
        _dt = _displayLink.timestamp - _lastDisplayTime;
        _dt = MAX(0,_dt);
    }
    // Store this timestamp for next time
    _lastDisplayTime = _displayLink.timestamp;

	// needed for SPF
	if( _displayStats )
		gettimeofday( &_lastUpdate, NULL);

#if DEBUG
	// If we are debugging our code, prevent big delta time
	if( _dt > 0.2f )
		_dt = 1/60.0f;
#endif
}
```

and for android:

```
// Overriden in order to use a more stable delta time
-(void) calculateDeltaTime
{
    static unsigned long long last = 0;
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    unsigned long long now = t.tv_sec * 1e9 + t.tv_nsec;
    if (now != last)
    {
        if (last != 0)
        {
            _dt = (now - last) / (double)NSEC_PER_SEC;
        }
        last = now;
    }
}
```
I'm not really familiar with engine code.. and my C++ knowledge is limited just for my game needs, so I can't implement this.. anyone can help?

**Comment by minggo** [comment]
@KAMIKAZEUA thanks for the information. But it seems it just a tricky method
```c++
#if DEBUG
	// If we are debugging our code, prevent big delta time
	if( _dt > 0.2f )
		_dt = 1/60.0f;
#endif
```
It just change the delta time in debug mode to make it smooth, it is not the really delta time.

**Comment by Anywhere-Music-Player** [comment]
@minggo 0.016 and 0.2 .. hmm o_0 this code do nothing about VSYNC...
Actually cocos2d-x has same code  https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/CCDirector.cpp#L353

So, issue with cocos2d because it does not use the CADisplayLink duration property. Instead it relies on system timers to calculate the time difference. As a result, cocos2d’s delta time is merely an approximation and ever-so-slightly disconnected from the actual refresh rate.

You can remove that debug predef and nothing will change about this problem.
What I'm talking is for iOS should be used displayLink.timestamp, it's needs vsync. This all fixed in cocos2d-iphove v3, all just need is copy code :) and maybe for android too, don't know, maybe later will check...

I'm really waiting for fix and I'm happy to test this on my game. Actually this not smooth bug takes me already 2 weeks+ trying to fix what can't be fixed, because of non synced frames..omg

**Comment by minggo** [comment]
@KAMIKAZEUA you are right. But there is not an elegant way to override `calculateDeltaTime `.

**Comment by Anywhere-Music-Player** [comment]
The hard way is the only way :)

**Comment by minggo** [comment]
I sent https://github.com/cocos2d/cocos2d-x/pull/17852 to fix it. It is the only relative elegant way i can find.

**Comment by Anywhere-Music-Player** [comment]
Tested. Fixed. THanks.
