### ISSUE TITLE
Cross-compilation

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#17804]
- cocos2d-x version: 3.15
- devices test on: my linux mint 18.1

I'm not sure about this feature, but it will be really cool, if cross-compilation with extrenal compilers will be possible. For example, I want to deploy my game to steam, but have only linux machine and using virtualbox with windows is impossible. Today we have migwin64 for this.

Any ideas?

**Comment by minggo** [comment]
Did you mean can compile any target platform on any platform? I think it is not possible, for example you can not compile for Mac on Windows. I may wrong, but it may take a lot effect if possible.

**Comment by v1993** [comment]
I'm not sure about cross-compilation on mac or windows, but there is some tools/scripts for linux.
Of couse, it isn't easy to do, as I see.

**Comment by v1993** [comment]
Yes, I mean compiling for any target platform on any platform if you have compiler.

**Comment by v1993** [comment]
There was a lot of changes in CMake, is there any news?

**Comment by drelaptop** [comment]
@v1993 Now the Cocos2d-x CMake build support Cross-compilation, Windows (MSVC compiler), Linux (GCC), macOS(clang), iOS(clang), Android Native build(clang). 

support IDE: Visual Studio (Windows), XCode(macOS), CLion(Linux/macOS/Windows) only MSVC compiler on windows, not include mingw64 yet.

With CMake, we have the ability to support all CMake supported platforms, but now not every platform, just most popular platform. because the difference of platforms need time to cover.

**Comment by v1993** [comment]
@drelaptop I meant something like building .exe on linux (there are some tools for that).

**Comment by drelaptop** [comment]
@v1993 do you know any other open-source software implement this? which one

**Comment by v1993** [comment]
Yep, I meant mingw32/64. No other tools known for me.

P.S.: I saw some tools to build for macOS (and iOS probably) on linux.

**Comment by drelaptop** [comment]
I think it's impossible to build macOS/iOS on Linux, please supply some useful infos if you think it is.

**Comment by v1993** [comment]
Something like https://github.com/tpoechtrager/osxcross.

**Comment by drelaptop** [comment]
it's not necessary to support this inside cocos2d-x, some one can build cocos2d-x by simulating the macOS build environment in Linux if he like.

**Comment by v1993** [comment]
So, is there any plans/possibility of supporing mingw with cmake?

P.S.: is it possible to use icons (game.ico) with cmake?

**Comment by drelaptop** [comment]
> So, is there any plans/possibility of supporing mingw with cmake?

it's possiable, but no plan yet.

>  is it possible to use icons (game.ico) with cmake?

possiable, and I plan to do it before next milestone released.

**Comment by drelaptop** [comment]
cocos2d-x cmake existed cross-compilation with some limitation, supported iOS & Android on Mac, Android on Windows.

> we have no plan to do other cross-compilation.
