### ISSUE TITLE
AudioEngine loops get eventually cut

### ISSUE THREAD

**Issue by kmaker** [cocos2d/cocos2d-x#17800]
- cocos2d-x version: 3.15
- devices test on: iPad
- developing environment: Xcode version:

Steps to Reproduce:
1. Using AudioEgine, play a sound bigger than PCMDATA_CACHEMAXSIZE (1048576) with loop
2. Let the file loop a few times and eventually it will stop looping

The problem seems to be that AudioPlayer::rotateBufferThread will feed the buffer with 100ms of data and sleep for 75ms. If the thread gets delayed a few ms, the decoder will consume all the buffer and stop the sound. Then AudioEngineImpl::update will detect that the sound is stopped and delete the AudioPlayer, ending the loop.

It looks like AudioPlayer::rotateBufferThread is failing to manage all 3 buffers, but I'm not very sure of that (please note that AudioPlayer has 'hardcoded' the buffer count in 3, but there is a define QUEUEBUFFER_NUM that I guess it should be used instead).

A quick fix is to double the data on the buffer to 200ms (#define QUEUEBUFFER_TIME_STEP (0.2f)), or to lower the sleep time on AudioPlayer::rotateBufferThread, although I prefer the first one.

**Comment by dumganhar** [comment]
@kmaker , thanks for your report.
Does this issue exist by a specific audio file or most audio files?
If it happen by a specific audio file, could you please upload one for reproducing?

**Comment by kmaker** [comment]
I've seen it with many different files (at least 6). The shorter the file, the faster it breaks (since it loops more frequently). Keep in mind that the file must still be bigger than PCMDATA_CACHEMAXSIZE to enable the "streaming mode". Let me know if you are not able to reproduce it and I could upload an audio file of mine.

**Comment by cptnoblivious** [comment]
We have been experiencing the same issue. Here's an MP3 that's trimmed as close to the PCMDATA_CACHEMAXSIZE as we can get: https://www.dropbox.com/s/umgyzh650wjosjy/trimed_music_fails_to_loop.mp3?dl=0

While I haven't been able to reproduce the looping error in the last hour of testing using the file alone, shaving off tiny fractions of QUEUEBUFFER_TIME_STEP does more reliably reproduce the issue after a couple of loops.

We will have to take kmaker's suggested workaround into production for the time being. 200ms time step seems to work very well, at least for our game that doesn't require specific music timing.

**Comment by dumganhar** [comment]
@kmaker @cptnoblivious 
I have successfully reproduced this issue. I have got a solution for this.
Basically, we need to register a listener of `AL_BUFFERS_PROCESSED` event, if we get this event, the thread of rotating streaming buffer need to be waked up to handle the new buffers.

**Comment by dumganhar** [comment]
@kmaker @cptnoblivious ,
I sent a Pull Request to resolve this issue: https://github.com/cocos2d/cocos2d-x/pull/17947
Could you help to test it? Thanks.

**Comment by kmaker** [comment]
Looks like it's working. Thanks @dumganhar !
