### ISSUE TITLE
A bug in action, can't stop action at once.

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#17808]
- cocos2d-x version: 3.15
- devices test on: win7
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:
![u84 mv789yia 6e x zq_0](https://cloud.githubusercontent.com/assets/5201160/25986440/8f0211f2-3722-11e7-8280-8975b9307504.png)

```
    local actionTag = 111
    local seq = transition.sequence({
        cc.DelayTime:create(0),
        cc.CallFunc:create(function()
            self:stopActionByTag(actionTag)
            print("aaa")
        end),
    })
    local action = cc.RepeatForever:create(seq)
    action:setTag(actionTag)
    transition.execute(self, action)
```
output 
```
aaa
aaa
```
this ```aaa``` will be execute twice, but we need only once.

**Comment by minggo** [comment]
Yep, it is an issue, fixed in https://github.com/cocos2d/cocos2d-x/pull/17849

**Comment by Dauch** [comment]
Thanks @minggo
