### ISSUE TITLE
Is cocos2d-x suitable for win32 desktop games?

### ISSUE THREAD

**Issue by SeniorPlayer** [cocos2d/cocos2d-x#17810]
Win32 desktop games need D3D for render. But I can't find any support in cocos2d-x.

**Comment by yuangu** [comment]
What about cocos2dx for uwp。It's use  angel (for more: https://github.com/google/angle) . sorry for my english. 

我觉得我还是用中文说一遍吧，毕竟我的英语不是很好。我觉得你可以用使用cocos2dx 中的uwp工程。毕竟那个是用angle做的支持。它是用DX来模仿opengl的api。如果你只是找一个DX的引擎，我建议你可以使用monogame ，https://github.com/MonoGame/MonoGame

**Comment by SeniorPlayer** [comment]
看了一下 cocos2dx for uwp 是不是只支持win10？

**Comment by yuangu** [comment]
呃，你是中国人啊？我个去，我还说了这么一大堆。嗯，uwp肯定 只支持win10。你为啥只要dx实现呢？

**Comment by perminovVS** [comment]
Yes cocos2d-x support Win32 and WinRT.
cocos2d-x use OpenGL for render(WinRT use angel as wrapper on Direct3D)
My game run on Windows XP and later.

**Comment by lavapx** [comment]
perminov is right. You don't need DirectX, even on Windows. I wrote this article on opengl in cocos2dx. The first part explains opengl vs DirectX a bit:
http://www.lavaxp.net/an-intro-to-opengl-using-cocos2d-x/

**Comment by madrazo** [comment]
We have the issue that there is no Joystick for Windows and you can't toggle Fullscreen (Alt+Enter).

**Comment by Bilalmirza** [comment]
@madrazo just update glfw to fix joystick issue

**Comment by minggo** [comment]
please discuss such topic in forum: http://discuss.cocos2d-x.org/c/cocos2d-x

**Comment by bpdubey87** [comment]
@perminovVS Hello , You mentioned that your app run on Windows Xp. I also want to run my cocos2dx app on win xp but it is not running. I made build using Visual Studio 2017 and Cocos2d-x3.15.1. It run successfully on Windows 7+. But on xp it gives error that "It is not a valid application".
I also set platfrom toolset in proj properties to "Windows xp". But same error. Please help

**Comment by slackmoehrle** [comment]
@bpdubey87 Make sure you are building a 32-bit app and not a 64-bit or UWP app.

**Comment by bpdubey87** [comment]
@perminovVS Hi can you please tell where to set those parameter? Actually this is my first app on Windows platform. So I dont know much where to set those properties.

**Comment by perminovVS** [comment]
@bpdubey87 hello, you need rebuild all 3rd-party and cocos and you app for platform toolset xp.
