### ISSUE TITLE
Why use non-thread safe Spidermonkey

### ISSUE THREAD

**Issue by yemingyu** [cocos2d/cocos2d-x#17816]

**Comment by DavidDeSimone** [comment]
Threading in Spidermonkey is complicated, and it would be a very large undertaking to support. In general, cocos2d-x is not a thread safe engine.

If you really need a degree of multi-threaded JavaScript, I can provide you with some information on how to implement it yourself. Cocos uses a specific fork of Spidermonkey, located here: https://github.com/cocos2d/Spidermonkey/tree/v33/build. I believe the version of Spidermonkey used in cocos is new enough that JS_THREADSAFE is on by default. You can read more about that flag and how it is used here: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_reference/JS_THREADSAFE

It's important to understand that **Each thread that uses the JavaScript engine must essentially operate in a totally separate region of memory.**. **Even in JS_THREADSAFE builds, threads cannot safely share objects or strings.** If your hope is that you can have two threads using a single Javascript context at the same time, you will be disappointed.

**Comment by yemingyu** [comment]
@DavidDeSimone Thank you for your reply，I make sure 2 threads do not make calls on a single Javascript context simultaneously by using mutex. Could I access the property, run Javascript code and do other things in context from different threads? I want to use context from sub thread, this can not block the main thread

**Comment by yemingyu** [comment]
@DavidDeSimone This is the default configuration in https://github.com/cocos2d/Spidermonkey/tree/v33/build, and it disable threadsafe, does it still support to access context content from different threads? Does the contents of the context are shared in different threads?
../configure --with-ios-target=iPhoneSimulator --with-ios-version=$IOS_SDK --with-ios-min-version=$MIN_IOS_VERSION --with-ios-arch=i386 \
            --disable-shared-js --disable-tests --disable-ion --disable-jm --disable-tm --enable-llvm-hacks --disable-methodjit --disable-monoic --disable-polyic \
            --enable-optimize=-O3 --enable-strip --enable-install-strip \
            --disable-debug --without-intl-api --disable-threadsafe \
            --disable-gcgenerational --disable-exact-rooting

**Comment by minggo** [comment]
cocos2d-x is not thread safe, so we don't need a thread-safe SpiderMonkey. And a js context can not be visit in different threads, it is not safe.
