### ISSUE TITLE
A bug in Action JumpTo,can't stop at the place we supposed

### ISSUE THREAD

**Issue by Lavinci** [cocos2d/cocos2d-x#17818]
- cocos2d-x version: 3.15
- devices test on: win7 x64
- developing environments
   - NDK version: Not Used
   - Xcode version: Not Used
   - VS version: vs2015
   - browser type and version: Not Used

Steps to Reproduce:

```c++
void ActionScene::goCall(Ref * pSender)
{
	auto size = Director::getInstance()->getVisibleSize();
	auto origin = Director::getInstance()->getVisibleOrigin();

	sprite->runAction(JumpTo::create(2,Vec2(origin.x+size.width/2,origin.y+size.height/2),30,5 ) );
}
```
**The code of JumpTo can run correctly when the Botton
 clicked once,but it does't run well when multiple clicked.The sprite can't stop at the place we supposed**

**Comment by lavapx** [comment]
This is not a bug. You need to control input. If youre already jumping you dont want to be able to jump again. You can use bools and if statements to track the state youre in or build a state machine:
http://www.lavaxp.net/a-player-class-and-state-machine-in-cocos2d-x/
Also look into sequences so you can call custom functions after your jumpTo ends.

**Comment by Lavinci** [comment]
ok，I really appreciate you for the answers.thanks.
