### ISSUE TITLE
setIgnoreAnchorPointForPosition(false) does not work for node

### ISSUE THREAD

**Issue by hussain-sohaib** [cocos2d/cocos2d-x#17811]
- cocos2d-x version: 3.15
- devices test on: 6S+

  Size visibleSize = Director::getInstance()->getWinSize();

  auto node= Node:: create();
  auto sprite= Sprite::create("test.png");
  node->addChild(sprite);
  sprite->setPosition(Vec2(sprite->getContentSize().width*.5,sprite->getContentSize().height*.5 ));
  node->setPosition(Vec2(visibleSize.width*.5,visibleSize.height*.5));
  node->setAnchorPoint(Vec2::ANCHOR_MIDDLE);
  node->setIgnoreAnchorPointForPosition(false);
  this->addChild(node);

   this code place bottom left corner of node at the center of screen. This same code work for Layer 
   but not for Node, but it should work for Node as well.
   
   //auto node= Layer:: create(); works fine.

**Comment by minggo** [comment]
Node's anchor point value is (0,0), so no matter `node->setIgnoreAnchorPointForPosition(true or false)`, there is not different.
