### ISSUE TITLE
replaceScene in TouchEventListener of Button Crashes

### ISSUE THREAD

**Issue by Arman92** [cocos2d/cocos2d-x#17819]
- cocos2d-x version: 3.15
- devices test on: Linux env
Steps to Reproduce:

1. Create a button widget and add an TouchEventListener to it, call replaceScene, crashes on 
```c++
CCASSERT(!_running, "Node still marked as running on node destruction! Was base class onExit() called in derived class onExit() implementations?");
```

Sample code tested:
```c++
    auto backBtn = Button::create("btn.png", "btn.png", "btn.png")
    backBtn->addTouchEventListener([&](Ref *sender, Widget::TouchEventType type) {
    		if (type == ui::Widget::TouchEventType::ENDED)
    		{
    			auto loginScene = LoginScene::createScene();
    			loginScene->autorelease();
    			Director::getInstance()->replaceScene(loginScene);
    		}
    	});
    ;
```

I have never overrided onExit() of any of my classes.
The current Scene which is being replaced by new scene, is similar to this [tutorial](http://cocos.sonarlearning.co.uk/docs/scenes)

Possible duplicates: 
Issue #12483
Issue #10834

**Comment by Arman92** [comment]
Can anyone help me here please?

**Comment by Arman92** [comment]
Can someone help me here please?

**Comment by minggo** [comment]
```c++
auto loginScene = LoginScene::createScene();
loginScene->autorelease();  // don't have to invoke this, since it is autoreleased
```

**Comment by Arman92** [comment]
Thanks! That fixed it.

But what happens if I call `autorelease()` ? Why does it make such a problem?

**Comment by minggo** [comment]
Then it will be released more times, which will cause problem. release will minus reference count, when reference count equals 0, it will be deleted, so the pointer will be wild.
