### ISSUE TITLE
Sound in new AudioEngine won't loop

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#17839]
- cocos2d-x version: 3.14.1 with 3.15 audio engine
- devices test on: Nexus 6P with Android 7.1.1
- developing environments
   - NDK version: r13b
   - Xcode version: n/a
   - VS version: n/a
   - browser type and version: n/a

So, I was using 3.14.1 with some adjustments and new audio engine. Lastly I've updated audio directory from 3.15 and now sound won't loop:

`soundId = cocos2d::experimental::AudioEngine::play2d(filename, true);`

Plays only once. It causes extra problems: when I'm trying to stop soundId after first loop (so it's not playing as it should) app would crash.

**Comment by minggo** [comment]
Did you try the audio engine in 3.15? May be there are some problem when porting the audio engine into v3.14 because it is not self-complete, it has some relationship with other modules.

**Comment by piotrros** [comment]
Ok I've recovered old cocos2d-x 3.14 (with modifications) from timemachine and it's working. I guess I screwed something up. 

I tried 3.15, audio was fine, but I'm impacted by problems with cocos studio - I don't see any labels.
