### ISSUE TITLE
Can not find blur shader on cocos2djs, can someone give a example?

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#17842]
I only find a simple_blur.fsh file in cocos2dx cpp samples folder, and have not found how to use it in cocos2djs(web).

Can some one give me a example or just .vsh and .fsh file?

Thanks!

**Comment by minggo** [comment]
please ask these questions in forum http://discuss.cocos2d-x.org/. Since WebGL is similar to OpenGL ES, so the shaders are similar too.
