### ISSUE TITLE
How to convert the gaussian-blur to cocos2dJs? The guy write it with nodejs

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#17843]
https://github.com/Jam3/glsl-fast-gaussian-blur

I need apply gaussian-blur on html5 game, but I am not good at shader, so   found this  nice project with demo.
But I don't know how to convert  it to cocos2djs.
Can somebody help me?      help~~ and thanks! @pandamicro @minggo

**Comment by minggo** [comment]
Please use [forum](http://discuss.cocos2d-x.org/) for the help, this is for issues.
Thanks.
