### ISSUE TITLE
camera movement on a layer that is added as a child of scrollview

### ISSUE THREAD

**Issue by hussain-sohaib** [cocos2d/cocos2d-x#17854]
- cocos2d-x version: 3.15
- devices test on: 6S+

I want to create a similar movement that is available in cpp test NewRendererTest BugAutoCulling::BugAutoCulling() but in vertical direction. But I am not able to create it. See the attached file for full code and resources. 

So the layer on which I am trying to move the camera is added as a child to the scrollview and I want that when the camera move user should see the effect of moving layer but actually camera is moving like that in  cpp test NewRendererTest BugAutoCulling::BugAutoCulling() .

for full code please see the attached files as well.

see here as well
http://discuss.cocos2d-x.org/t/camera-movement-on-layer-that-is-a-child-of-scroll-view/36996

[Classes.zip](https://github.com/cocos2d/cocos2d-x/files/1019300/Classes.zip)

**Comment by hussain-sohaib** [comment]
@minggo can you please have a look on this. I really want this to work.

Thanks

**Comment by minggo** [comment]
The code should change to `_mainLayer->setCameraMask(2, true);`. The mask is `2`, not 1.
