### ISSUE TITLE
Failed to build cocos2d-x on x64 due to error C2065: 'GWL_WNDPROC': undeclared identifier 

### ISSUE THREAD

**Issue by KarenHuang2016** [cocos2d/cocos2d-x#17851]
We tried to build cocos2d-x on Windows with VS2015 Update 3. It failed to build on x64 due to the error C2065: 'GWL_WNDPROC': undeclared identifier. 'GWL_WNDPROC' is defined in C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\WinUser.h like below. But if _WIN64 is defined. 'GWL_WNDPROC' will be undefined. So error C2065 is reported when build on x64. Could you please take a look at this issue? Thanks in advance!
WinUser.h
**#define GWL_WNDPROC         (-4)**
#define GWL_HINSTANCE       (-6)
#define GWL_HWNDPARENT      (-8)
#define GWL_STYLE           (-16)
#define GWL_EXSTYLE         (-20)
**#define GWL_USERDATA        (-21)**
#define GWL_ID              (-12)

**#ifdef _WIN64**
**#undef GWL_WNDPROC**
#undef GWL_HINSTANCE
#undef GWL_HWNDPARENT
**#undef GWL_USERDATA**
#endif /* _WIN64 */

**Steps to Reproduce:**
1. git clone https://github.com/cocos2d/cocos2d-x.git D:\Cocos2dx\src
2. Open a VS 2015 command prompt and browse to D:\Cocos2dx
3. mkdir build_x64 && pushd build_x64
4. cmake -G "Visual Studio 14 Win64" -DCMAKE_SYSTEM_VERSION=10.0.14393.0 ..\src
5. popd
6. msbuild /m /p:Configuration=Release;Platform=x64 build_x64\Cocos2d-X.sln /t:Rebuild

**Actual result:**
D:\Cocos2dx\src\cocos\ui\UIEditBox\UIEditBoxImpl-win32.cpp(64): **error C2065: 'GWL_WNDPROC': undeclared identifier** [D:\Cocos2dx\build_x64\cocos\cocos2dInternal.vcxproj]
         D:\Cocos2dx\src\cocos\ui\UIEditBox\UIEditBoxImpl-win32.cpp(103): error C2065: 'GWL_WNDPROC': undeclared identifier [D:\Cocos2dx\build_x64\cocos\cocos2dInternal.vcxproj]
         D:\Cocos2dx\src\cocos\ui\UIEditBox\UIEditBoxImpl-win32.cpp(130): **error C2065: 'GWL_USERDATA': undeclared identifier** [D:\Cocos2dx\build_x64\cocos\cocos2dInternal.vcxproj]
         D:\Cocos2dx\src\cocos\ui\UIEditBox\UIEditBoxImpl-win32.cpp(131): error C2065: 'GWL_WNDPROC': undeclared identifier [D:\Cocos2dx\build_x64\cocos\cocos2dInternal.vcxproj]
         D:\Cocos2dx\src\cocos\ui\UIEditBox\UIEditBoxImpl-win32.cpp(159): error C2065: 'GWL_USERDATA': undeclared identifier [D:\Cocos2dx\build_x64\cocos\cocos2dInternal.vcxproj]
         D:\Cocos2dx\src\cocos\ui\UIEditBox\UIEditBoxImpl-win32.cpp(160): error C2065: 'GWL_WNDPROC': undeclared identifier [D:\Cocos2dx\build_x64\cocos\cocos2dInternal.vcxproj]

**Comment by minggo** [comment]
Please don't use cmake, just open `build/cocos2d-win32.sln` to run tests.

**Comment by KarenHuang2016** [comment]
@minggo, the build/cocos2d-win32.sln has no x64 configuration. It only has Win32 configuration. So we use cmake to generate the x64 solution. The issue I reported only can be repro on x64. The root cause is that on WIN64 there is no definition for GWL_WNDPROC in WinUser.h file.

**Comment by KarenHuang2016** [comment]
Also, we can build the x64 solution successfully on previous revision 4fccfb2. But it failed on latest revision.

**Comment by KarenHuang2016** [comment]
I found the root cause. In cocos/ui/UIEditBox/UIEditBoxImpl-win32.cpp, we should use **GWLP_WNDPROC** instead of GWL_WNDPROC. Then the error will not be reported.

**From**
s_prevCocosWndProc = (WNDPROC)SetWindowLongPtr(s_hwndCocos, **GWL_WNDPROC**, (LONG_PTR)hookGLFWWindowProc);
**changed to** 
s_prevCocosWndProc = (WNDPROC)SetWindowLongPtr(s_hwndCocos, **GWLP_WNDPROC**, (LONG_PTR)hookGLFWWindowProc);

**Comment by minggo** [comment]
@zilongshanren please take a look of it.
Thanks @KarenHuang2016

**Comment by PhoebeHui** [comment]
Any updates?

**Comment by KarenHuang2016** [comment]
This issue is already fixed. Close this issue.

**Comment by sajsaleem** [comment]
Hi,
I am trying to build cocos2d-x project for 64 bit which will be then be ported to ps4 .. I followed your steps but when I run project on visual studio 2017 I am getting multiple glfw errors . Please refer to attachment and any help in this regard will be great. Thanks
![screenshot 3](https://user-images.githubusercontent.com/8329349/52854889-ceaaa280-30d4-11e9-87d2-944b8181c256.png)

**Comment by ilqvya** [comment]
Try to use CMake generated solution

**Comment by Stinkfist0** [comment]
Hi. How was this supposedly fixed? I am encountering this with the 3.17.1 download and also with the latest code from GitHub on my own project (generated using "Visual Studio 15 Win64" CMake generator). As a quick workaround, I added the following to UIEditBoxImpl-win32.cpp:
```cpp
#ifdef _WIN64
#define GWL_WNDPROC GWLP_WNDPROC
#define GWL_USERDATA GWLP_USERDATA
#endif
```
After this, I am getting lots of linker errors, but that's different issue.

**Comment by BonBonSlick** [comment]
Used cmake .sln file, same errors for cocos2dx on windows 10 x64

**Comment by PatriceJiang** [comment]
x86_64 is not supported. If you are using VS2019, run 
```
cmake .. -A win32
```

**Comment by BonBonSlick** [comment]
Not sure is it cocos2d or VisulStudio, but x64 build is not supported
https://github.com/cocos2d/cocos2d-x/issues/20411
