### ISSUE TITLE
End is not working in Android Nougat.

### ISSUE THREAD

**Issue by isairz** [cocos2d/cocos2d-x#17867]
- cocos2d-x version: 3.13.1
- devices test on: Samsung Galaxy S7, LG V20, LG G6
- developing environments
   - NDK version: r12b
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. run `cocos2d`
2. call `cocos2d::Director::getInstance()->end();`

`cocos2d::Director::getInstance()->end();` is working well in other Android, but it is not in Nougat.

**Comment by isairz** [comment]
Maybe related to #13878

**Comment by piotrros** [comment]
Strange, I'm using cocos2d-x 3.14.1, ndk r13b and on Nexus 6P (android 7.1.1) it works fine.

**Comment by BlackCatz94** [comment]
Sometimes very very rarely, app will start again after calling end(); also happened on Marshmallow devices.

**Comment by isairz** [comment]
I found out that is a problem in Miles not in cocos.
(I use Miles as sound library)

Cocos waits for the sound object is destroyed, but Miles is hanging because it fail to close driver in nougat.
