### ISSUE TITLE
cocos2d-x js-binding cc.orbitCamera can not working.

### ISSUE THREAD

**Issue by keppelcao** [cocos2d/cocos2d-x#17866]
- cocos2d-x version: 3.15
- devices test on: iphone6 iphone6s ipad mini 2
- developing environments
   - NDK version: ?
   - Xcode version: 8.3.2
   - VS version: ?
   - browser type and version: ?

Steps to Reproduce:
orbitCamera action has not any effect, and log msg as following:
[Action update]. override me
[Action update]. override me
[Action update]. override me
[Action update]. override me

test code like following:
var orbit = cc.OrbitCamera.create(8, 1, 0, 0, 360, 45, 0);
var forever = cc.repeatForever(orbit);
var sp = new cc.Sprite("xxx.png");
this.addChild(sp);
sp.runAction(forever);

**Comment by keppelcao** [comment]
I test same code and writing in C++ code, it works fine.

**Comment by sasivarnan** [comment]
@keppelcao Can you share how you used `OrbitCamera` with `javascript`?
Thanks in advance.
