### ISSUE TITLE
CocosStudio .csb reading bug.

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#17869]
- cocos2d-x version: 3.15
- devices test on: win32
- developing environments
   - VS version: 2013

Steps to Reproduce:
1.  In cocos empty test add content of archive https://www.dropbox.com/s/zut1fdlsvbxid39/cocos_studio_outline_crash.zip?dl=0
 into Resources folder (there is scene with label with enabled outline).
2.  In cocos empty test add 
`const flatbuffers::CSParseBinary * content_binary = nullptr;`
`cocos2d::Data data = FileUtils::getInstance()->getDataFromFile( "Scene.csb" );`
`const flatbuffers::CSParseBinary * flat_buffer = flatbuffers::GetCSParseBinary( data.getBytes() );`
`cocos2d::Node* scene = CSLoader::getInstance()->nodeWithFlatBuffers(flat_buffer->nodeTree());`
`this->addChild( scene );`
into 
`HelloWorld::init()`

Add some includes : 
`#include "cocostudio/FlatBuffersSerialize.h"`
`#include "cocostudio/CSParseBinary_generated.h"`
`#include "cocostudio/ActionTimeline/CSLoader.h"`
3. Comment `#include "ExtensionMacros.h"` in FlatBufferSerialize.h
4. compile and run

Will crash at reading .csb file.
Caused by updating flatbuffer to 1.5 version with generating new headers by existing fbs files.

I understand that you closed support of CocosStudio without promise of backward capability, but I don't understand why you need to update flatbuffer. It's used in CocosStudio reader only ( There is no other usages, I'v checked ). If you don't want to support it anymore - remove it. If you still support it keep it working.

**Comment by minggo** [comment]
flatbuffer is asked to be updated by [this issue](https://github.com/cocos2d/cocos2d-x/issues/17269). I don't know it will break compatibility, because cpp-tests also uses .csb files and there is not problem.

**Comment by minggo** [comment]
As many developers meet the issue, i think i have to revert the PR of updating flatbuffer. Sorry about that.

**Comment by minggo** [comment]
sent https://github.com/cocos2d/cocos2d-x/pull/17930 to revert updating flatbuffers
