### ISSUE TITLE
Problems with labels loaded from csb file

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#17868]
- cocos2d-x version: 3.15

Reproduce:
Load scene made in Cocos Studio.

If using custom size, all the labels are aligned on the center.
If using auto size, all the labels are aligned on the left.
Vertical alignment seems to not work at all.
Sometimes labels does not show at all. 

More info here:
http://discuss.cocos2d-x.org/t/cocostudio-bug-in-cocos2d-x-3-15/36591/9

It works fine in cocos2d-x 3.14.1.

Solution:
use old cocosstudio directory from 3.14.1.

Please fix this :) It does not require changing anything in Cocos Studio itself.

**Comment by minggo** [comment]
i think it is resolved as the issue: https://github.com/cocos2d/cocos2d-x/issues/17869
