### ISSUE TITLE
Segmentation fault with nil arg

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#17878]
- cocos2d-x version: 3.15
- devices test on: linux

Steps to Reproduce:

1. Use `nil` as arg to `:addComponent`
2. Get crash with `Segmentation fault (core dumped)`

I accidentally ran

```
    self:addComponent(phbody);
```
without `phbody`.

**Comment by minggo** [comment]
can not pass nil to addComponent, can refer to the [cpp code](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCComponentContainer.cpp#L57).

**Comment by v1993** [comment]
But I've got segfault, not just ignore or exit.

**Comment by minggo** [comment]
yep, it pass the value to cpp. the binding codes just pass the value directly to cpp.
