### ISSUE TITLE
Set window icon on desktop

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#17877]
- cocos2d-x version: 3.15
Is it possible to set/change window icon for all desktop platforms and how? If not, it is a feature request.

**Comment by summerinsects** [comment]
maybe you can modify this file : proj.win32/res/game.ico

**Comment by v1993** [comment]
But what about other platforms?

**Comment by pyrosphere** [comment]
Each platform gets its icon from different files:
- Android: proj.android/res/drawable-*dpi/icon.png
- Android-Studio: proj.android-studio/app/res/mipmap-*dpi/ic_launcher.png
- iOS: proj.ios_mac/ios/Icon-*.png
- Mac: proj.ios_mac/mac/Icon.icns
- Windows: proj.win32/res/game.ico

**Comment by v1993** [comment]
But what about linux?

**Comment by pyrosphere** [comment]
I have very little experience with Linux and don't know how icons work there, sorry. Someone else might know?
