### ISSUE TITLE
Run iOS produce "invalid literal for float(): 8.3.2"

### ISSUE THREAD

**Issue by LucaComanducci** [cocos2d/cocos2d-x#17873]
- cocos2d-x version: 3.15 (commit 639737286f594f3e06c07b22b352dddb01858883)
- developing environments
   - Xcode version: 8.3.2

Steps to Reproduce:

1. Run 'cocos new MyGame -p com.your_company.mygame -l cpp -d NEW_PROJECTS_DIR'
2. Run 'cd NEW_PROJECTS_DIR/MyGame'
3. Run 'cocos run -p ios'

Then the console print:

Python 2.7.10
Building mode: debug
Building...
invalid literal for float(): 8.3.2
Build failed: Take a look at the output above for details.

**Comment by minggo** [comment]
Ok, it is not 3.15. The version will be updated until releasing.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17912
