### ISSUE TITLE
sometime crash in v3.15 (android platform)

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#17886]
- cocos2d-x version: v3.15
- devices test on: android
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

after upgrade from 3.13 to 3.15, sometimes crash, this is logcat upload to my backstage, can someone give me some infomation?
```
# GLThread 186(186)
java.lang.IllegalArgumentException
1 com.google.android.gles_jni.EGLImpl._eglCreateContext(Native Method)
2 com.google.android.gles_jni.EGLImpl.eglCreateContext(EGLImpl.java:54)
3 android.opengl.GLSurfaceView$DefaultContextFactory.createContext(GLSurfaceView.java:771)
4 android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1030)
5 android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
6 android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by mahesh0756** [comment]
Hello Dauch,
I am getting same issue of crash, but on 3.13.
Have you resolved the issue, please help me if solved.

**Comment by Dauch** [comment]
Sorry, I couldn't make out a solution. :(
