### ISSUE TITLE
Action sometimes be revocation.

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#17884]
- cocos2d-x version: cur v3 branch
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. run those code in hello world.
```
local time = 2
local seq = transition.sequence({
    cc.DelayTime:create(time),
    cc.CallFunc:create(function()
        print("aaa")
    end),
})
transition.execute(self, seq)
```
2. . I didn't do anything to stop this action. But sometimes it happen this action do not print ```aaa```, it is rarely happen, but do happen in ```v3.15```, I upgrade before ```v3.13```, but not ever happen in  ```v3.13```, please have a look, thanks

[Chinese forum issue](http://forum.cocos.com/t/v3-15/47014)

may be reference to this patch. [Flag the end of ActionInstant and ActionInterval. ](https://github.com/cocos2d/cocos2d-x/pull/17557)

could you have a look ? @j-jorge

**Comment by minggo** [comment]
Yep, i think it is a problem, because the duration of instant action is zero.

**Comment by minggo** [comment]
@Dauch could you please try the PR: https://github.com/cocos2d/cocos2d-x/pull/17906.
Thanks.

**Comment by minggo** [comment]
And i think `Spawn` also has similar issue.

**Comment by Dauch** [comment]
Sorry, I don't know how to reproduce this bug. It is rarely happen

**Comment by minggo** [comment]
Got it, but you can try the PR and see if it will happen again. If it is resolved, than it should not happen again. Thanks.

**Comment by minggo** [comment]
I will try to make a test that can do auto testing.

**Comment by Dauch** [comment]
No problem, I will try.

**Comment by Dauch** [comment]
> Yep, i think it is a problem, because the duration of instant action is zero.

no, It's not 0, is 2.
after I merge this PR, something bad happen, the action will never stop. :(

**Comment by minggo** [comment]
Sequence may have instant action, so the duration is just interval actions, which make instant actions will be missed if it is at last.

> after I merge this PR, something bad happen, the action will never stop. :(

I will have a try.

**Comment by minggo** [comment]
> after I merge this PR, something bad happen, the action will never stop. :(

Yep, because InstantAction::step() is not invoked, Sequence just invoke action's update directly. And _done in Instant actions are set in InstantAction::step().

**Comment by minggo** [comment]
@Dauch i updated the PR.

**Comment by Dauch** [comment]
Great job! It works. :)

**Comment by minggo** [comment]
Thanks. Please let me know whether the action will not be invoked now.

**Comment by Dauch** [comment]
It is normal now, thanks, I think this PR will fix this bug. I close this, if happen not be invoked, I will reopen.
