### ISSUE TITLE
Scheduler insecurely trigger callback after unschedule

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#17898]
![wechatimg99](https://cloud.githubusercontent.com/assets/632460/26780280/92edd402-4a1b-11e7-9cb9-3b44a5497b2c.jpeg)

The logic in Timer::update will trigger multiple times the callback if time passed is longer than one interval, it's designed to make sure the scheduled task is invoked accurately with time passed.

The problem is that it's not checking whether the timer is still valid. User could unschedule the task in the first trigger, then trigger the callback more times is no longer safe. As you can see, I met a crash here.

So to reproduce the problem:

1. Set the fps to 10 fps for example.
2. new / malloc a variable for example (A).
3. Schedule a task which uses the variable A with a frequency of 60 times per second.
4. The task will unschedule itself directly in the callback and delete / free variable A.
5. Then during the second time your task is being scheduled, you will access to a wild pointer A.

**Comment by minggo** [comment]
It is fixed in https://github.com/cocos2d/cocos2d-x/pull/17431
