### ISSUE TITLE
the correctness of the newest CCDownloader-android on android

### ISSUE THREAD

**Issue by toreinkun** [cocos2d/cocos2d-x#17914]
I use CCDownloader to download zip of hotupdate. During downloading, i changed wifi to 4g or wifi to another wifi, the downloaded zip's md5 is not equals to the original zip. But the zip can decompress and the files is equls to original files. 
![image](https://user-images.githubusercontent.com/22761531/26972119-f67acfd2-4d42-11e7-9c01-8b2d1b9ed303.png)

But these case won't happen on iOS.

**Comment by toreinkun** [comment]
and there is a strange case,  for example, the dowloading file's progress is 50%, then i change the wifi, the progress will reduce to 30%.

**Comment by toreinkun** [comment]
i replaced loopj to okhttp.

**Comment by Dauch** [comment]
may be you can make a patch.
