### ISSUE TITLE
iOS Compile Error: "invalid literal for float(): 8.3.3"

### ISSUE THREAD

**Issue by sabify** [cocos2d/cocos2d-x#17928]
- cocos2d-x version: 3.15.1
- Cocos Console version: 2.3
- devices test on: -
- developing environments
   - NDK version: -
   - Xcode version: 8.3.3
   - VS version: -
   - browser type and version: -

Steps to Reproduce:

1. command "cocos compile -p ios"

**Comment by minggo** [comment]
duplicated issue of https://github.com/cocos2d/cocos2d-x/issues/17873
