### ISSUE TITLE
cocos2d::ccCardinalSplineAt should take arguments by const reference

### ISSUE THREAD

**Issue by kepler-5** [cocos2d/cocos2d-x#17926]
This function is used internally by CardinalSplineTo (and other actions derived therefrom), but it is also useful outside as a friendly library function (as its placement in the header file for CCActionCatmullRom would suggest is its purpose).

The current function signature is `Vec2 ccCardinalSplineAt(Vec2 &p0, Vec2 &p1, Vec2 &p2, Vec2 &p3, float tension, float t)`.  The `Vec2` arguments are taken by reference, helpfully to avoid making unnecessary copies (they are _not_ modified inside the function), but because they are not `const` references, it makes the function frustrating to use, because non-`const` 'lvalue references' cannot bind to the result of an expression:
```
Vec2 pointA, pointB;
const Vec2 pointC;
// ...
auto result = ccCardinalSplineAt(
    pointA + pointB, // error: no matching function for call to 'ccCardinalSplineAt'. 1st argument ('const Vec2&') would lose const qualifier
    pointA - pointB, // same error
    pointC, // same error
    pointA.getNormalized(), // same error, etc.
    1.f,
    1);
```

One must resort to frustrating things, such as spelling out all the arguments in local variables beforehand, or doing evil things like casting away `const` on `pointC` above.

The interface would be much friendlier with a simple addition of `const`. To clarify, this would not break any existing user code*; it would make the function strictly more usable in more places. My proposed new function signature is:
```
Vec2 ccCardinalSplineAt(const Vec2 &p0, const Vec2 &p1, const Vec2 &p2, const Vec2 &p3, float tension, float t)
```

\* unless they were explicitly referring to the signature as-is, in their own prototype declaration within `namespace cocos2d`, instead of `#include`ing CCActionCatmullRom.h

I would have submitted this as a pull request, but I'm brand new to the community and wanted to say hi first.  Hello!

**Comment by minggo** [comment]
@kepler-5 feel free to send a PR.
