### ISSUE TITLE
Multi-Resolution Support

### ISSUE THREAD

**Issue by CodeSnooker** [cocos2d/cocos2d-x#1793]
@walzer 

Hi Walzer

Regarding the multi-resolution support, I followed the approach as mentioned by you over here: http://www.cocos2d-x.org/projects/cocos2d-x/wiki/Multi_resolution_support

Sad to say that the solution is buggy and easily reproducible even in the Test App provided within the Cocos2d-x.

Please check the test app over iPad or iPad HD. 

The elements that are positioned at the corner are going out of screen.

For example,

Step 1: Set the multi-resolution support as mentioned in the link: http://www.cocos2d-x.org/projects/cocos2d-x/wiki/Multi_resolution_support

Step 2: Add a sprite with anchor point (0.5, 0.5) with position (0.0f, 0.0f).

Step 3: Check the image it is not visible at all on the iPad or iPad-HD whereas it is is visible on iPhone or iPhone-HD

Please let me know if you need any other help to reproduce this issue.

Thanks,
Paras Mendiratta

**Comment by dumganhar** [comment]
Hi CodeSnooker,
    I think the problem is at step 2.
I am sure you are using kNoBorder mode, so you should place your sprite
based on visible rectangle. In our TestCpp sample,we provide a class named
`VisibleRect` to easily place ui elements by 9 points.
    Let me know if it still can't work. Thanks.

James
ÔÚ 2012-12-27 ÉÏÎç5:34£¬"CodeSnooker" notifications@github.comÐ´µÀ£º

**Comment by CodeSnooker** [comment]
@dumganhar 

Thanks for the update and seems that I misread the information. However, it's really difficult to follow the approach as I am placing the elements using CocosBuilder. :(

**Comment by dumganhar** [comment]
I'm not familiar with CocosBuilder, but it seems that it also supports relative postion in the latest version of CocosBuilder.

**Comment by CodeSnooker** [comment]
@dumganhar 

Well I am using relative positioning in CocosBuilder as I am trying to support all resolutions of Android and iOS devices.

But even if I use relative position its not going to solve the problem. For example,

Relative position to screen is set to zero percent then coordinates in all screen resolutions will be 0, 0 only.

**Comment by dumganhar** [comment]
So i think you should hack the CCBReader.cpp. And make the 9 relative positions point to visible rectangle rather than winSize. Then it'll be able to work.

**Comment by CodeSnooker** [comment]
:)

On Fri, Dec 28, 2012 at 8:33 PM, James Chen notifications@github.comwrote:

> So i think you should hack the CCBReader.cpp. And make the 9 relative
> positions point to visible rectangle rather than winSize. Then it'll be
> able to work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-x/issues/1793#issuecomment-11733405.

## 

Enjoy till last breath...

From,
Paras Mendiratta

**Comment by CodeSnooker** [comment]
@dumganhar 

I have found another hack without modifying CCBReader.cpp

Currently working fine on all iOS devices but for Android different resolution it needs to be tested. Unfortunately I don't have all major resolution Android devices. Not sure but on Android emulator, Cocos2D-x applications are not working.

Any other way to test it?

Thanks,
Paras Mendiratta

**Comment by dumganhar** [comment]
@CodeSnooker 
You could test different resolutions on Win32 and Mac platform.
And modify the window size in main.cpp(win32) and AppController.mm(Mac).
Then you will be able to debug all resolutions.

**Comment by dumganhar** [comment]
BTW, which way you are using without hacking CCBReader.cpp ?
