### ISSUE TITLE
long string could not display in the label (Texture2D: Error uploading compressed texture level: 0 . glError: 0x0501)

### ISSUE THREAD

**Issue by knuth** [cocos2d/cocos2d-x#17946]
- cocos2d-x version: 3.15
- devices test on: 
- developing environments
   - NDK version:
   - Xcode version: 8.3.3
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. create a new lua project using cocos2d-x 3.15 (old version has the same issue)
2. in the MainScene:onCreate() function, input the following code:

```lua
-----code begin----
   -- add label
    local str = "Developer/CoreSimulator/Devices/2062FCB0-D48C-4EF6-9F79-183861FCE72E/data/Containers/Bundle/Application/18FB6F4E-51E2-49CE-9000-AE5D95AC4502/star-battleapp/src/app//Developer/CoreSimulator/Devices/2062FCB0-D48C-4EF6-9F79-183861FCE72E/data/Containers/Bundle/Application/A875FC8F-20A2-4FCD-B90E-D719DF26880A/star-battle.app"
    --str = "This is a short text" --works well for the short string
    local lable = cc.Label:createWithSystemFont(str, "Arial", 30)
        :move(display.cx, display.cy + 200)
        :addTo(self)
    local size = lable:getContentSize()
    print(size.width, size.height)
-----code end----
```

Result: nothing is shown up, and the size of the label is (0,0).
I see "cocos2d: Texture2D: Error uploading compressed texture level: 0 . glError: 0x0501" in Xcode log.

**Comment by zilongshanren** [comment]
@knuth  thanks, I will take a look at this issue later.

**Comment by er-bpradip** [comment]
I am also facing same problem. @knuth Is this problem solved? Please let me know the solution if the issue is solved.

**Comment by gbrsh** [comment]
Same problem here when trying to set a long string in ui::Text.

**Comment by drelaptop** [comment]
fix by strip the extra text, refer to https://github.com/cocos2d/cocos2d-x/pull/19174
