### ISSUE TITLE
Problem with SpriteFrameCache class

### ISSUE THREAD

**Issue by BobyIlea** [cocos2d/cocos2d-x#17949]
The SpriteFrameCache holds a list of sprite frames that have already been loaded and a list of .plist files that have already been parsed and 'transformed' to sprite frames and cached. So, when adding a .plist to the SpriteFrameCache the second time, execution time will be minimum and no fps drop will occur.

**The problem:**
Every time methods like `SpriteFrameCache::removeSpriteFrames()`, `SpriteFrameCache::removeUnusedSpriteFrames()` etc. are called, the list containing the loaded files is erased. The sprite frames that have been cached for persistency DO remain cached but the record of the .plist file that they were loaded from is destroyed. Loading .plist files to the SpriteFrameCache can be very costly and sometimes produce FPS drops, and because of this issue we cannot do this operation when frame rate is not important(for example on a loading screen) and have the guarantee that files will stay cached for as long as we want.

**Notes:**
The fact that the list of already parsed .plist files gets erased whenever a sprite frame is removed from the cache is known by the cocos team. In the source files I've found a fixme comment: `// FIXME:. Since we don't know the .plist file that originated the frame, we must remove all .plist from the cache.`

I've checked the latest cocos release(3.15) and the problem is still not fixed(in my opinion, in order to fix this, changes have to be done to multiple classes, including `SpriteFrame` class and maybe `Texture2D`).

**Comment by Sinix512** [comment]
It has been a year since this issue were opened. Although it is not hard to fix for experienced users, it does cause serious problem frequently for amateurs.

**Comment by DeRealMorgan** [comment]
Finaly I came to this issue file.

Thanks for stating this one year ago!

Good to see that it is not fixed by now, it just took me 2h to figure out that it isnt actually my fault.
