### ISSUE TITLE
Websocket server

### ISSUE THREAD

**Issue by n-bes** [cocos2d/cocos2d-x#17944]
Hello everybody. I want to make a websocket server on the device. After I saw that the server support was [disabled](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/blob/v3/contrib/src/websockets/rules.mak) (-DLWS_WITHOUT_SERVER=1, I originally tried to connect the client). I tried to rebuild the library, but got link errors after replace **libwebsockets.a**. Please enable server support, or help me rebuild the libwebsockets. If you need a log / sources, I'll send them. Thx

**Comment by dumganhar** [comment]
Cocos2d-x just uses the client source of libwebsockets and `WebSocket` class is a wrapper for libwebsockets client. We don't have any plans to support of setting up a websocket server in engine.

**Comment by n-bes** [comment]
I don't use `Websocket` class. Now, i want server functions to be included in the libwebsockets, but not the cocos2dx engine. I'll write `WebSocketServer` myself (using `lws_create_context`, etc).

**Comment by dumganhar** [comment]
So you probably need to go to https://github.com/warmcat/libwebsockets for help.

**Comment by n-bes** [comment]
I'm solve my problem after update from 3.14.1 to 3.15.1 and rebuild libwebsockets

**Comment by RockJoey** [comment]
@013ez can you solve your problem by using 3.16? I use the latest one, but can't work.

**Comment by PatriceJiang** [comment]
WebSocket server added to static libraries. @minggo

**Comment by brantxiong** [comment]
> WebSocket server added to static libraries. @minggo

Hi, @minggo Thanks for adding WebSocket Server. But I cannot find any document about how to use the WebSocket Server in js. 

Could you give an example on how to setup a WebSocket Server in js script in Cocos Creator V2.1.2? Thanks so much!

**Comment by minggo** [comment]
Cocos Creator doesn't use cocos2d-x, you should ask it in the forum or Cocos Creator repo.
