### ISSUE TITLE
Run time error Hello World 

### ISSUE THREAD

**Issue by halcyonx** [cocos2d/cocos2d-x#17953]
- cocos2d-x version: 3.15.1
- devices test on: Huawei Mediapad Youth 2
- developing environments
   - NDK version: android-ndk-r10e
   - Xcode version: -
   - VS version: VS Community 2015
   - browser type and version: -

Steps to Reproduce:

1.  cocos run -p android --ap android-21
2.  log 

> 
> E/AndroidRuntime(28120): FATAL EXCEPTION: main
> **E/AndroidRuntime(28120): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libMyGame.so"...**
> E/AndroidRuntime(28120): 	at java.lang.Runtime.loadLibrary(Runtime.java:361)
> E/AndroidRuntime(28120): 	at java.lang.System.loadLibrary(System.java:525)
> E/AndroidRuntime(28120): 	at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:245)
> E/AndroidRuntime(28120): 	at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:261)
> E/AndroidRuntime(28120): 	at android.app.Activity.performCreate(Activity.java:5234)
> E/AndroidRuntime(28120): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
> E/AndroidRuntime(28120): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2310)
> E/AndroidRuntime(28120): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2399)
> E/AndroidRuntime(28120): 	at android.app.ActivityThread.access$900(ActivityThread.java:148)
> E/AndroidRuntime(28120): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
> E/AndroidRuntime(28120): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime(28120): 	at android.os.Looper.loop(Looper.java:137)
> E/AndroidRuntime(28120): 	at android.app.ActivityThread.main(ActivityThread.java:5471)
> E/AndroidRuntime(28120): 	at java.lang.reflect.Method.invokeNative(Native Method)
> E/AndroidRuntime(28120): 	at java.lang.reflect.Method.invoke(Method.java:525)
> E/AndroidRuntime(28120): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:879)
> E/AndroidRuntime(28120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
> E/AndroidRuntime(28120): 	at dalvik.system.NativeStart.main(Native Method)
> I/ActivityManager(  911): Notify an ApplicationCrash

**Comment by minggo** [comment]
`cocos run -p android --ap android-21` seems you build for android-21. And what's your Android OS version of your device?

**Comment by halcyonx** [comment]
Android OS verion on device is 4.3, I've installed older API, android-18, android-19 via **android** command, after this I've tried the command **cocos run -p android --ap android-18**, but it was failed with output message:
```
...
[armeabi] StaticLibrary  : libbullet.a
[armeabi] StaticLibrary  : libcocos2dandroid.a
[armeabi] StaticLibrary  : libcpufeatures.a
[armeabi] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi/gdbserver
[armeabi] Gdbsetup       : libs/armeabi/gdb.setup
[armeabi] SharedLibrary  : libTheGame.so
C:/projects/TheGame/TheGame/cocos2d/cocos/./2d/CCParticleSystem.cpp:608: error: undefined reference to 'rand'
C:/projects/TheGame/TheGame/cocos2d/cocos/./platform/CCFileUtils.cpp:275: error: undefined reference to 'atof'
C:/projects/TheGame/TheGame/cocos2d/cocos/./platform/CCFileUtils.cpp:284: error: undefined reference to 'atof'
C:/projects/TheGame/TheGame/cocos2d/cocos/./base/CCConsole.cpp:1232: error: undefined reference to 'srand'
C:/projects/TheGame/TheGame/cocos2d/cocos/./base/CCConsole.cpp:1233: error: undefined reference to 'rand'
C:/projects/TheGame/TheGame/cocos2d/cocos/./base/CCConsole.cpp:1261: error: undefined reference to 'srand'
C:/projects/TheGame/TheGame/cocos2d/cocos/./base/CCConsole.cpp:1262: error: undefined reference to 'rand'
C:/projects/TheGame/TheGame/cocos2d/cocos/./base/ccUtils.cpp:255: error: undefined reference to 'atof'
C:/projects/TheGame/TheGame/cocos2d/cocos/./base/ccRandom.h:117: error: undefined reference to 'rand'
C:/projects/TheGame/TheGame/cocos2d/cocos/./2d/CCActionTiledGrid.cpp:278: error: undefined reference to 'srand'
C:/projects/TheGame/TheGame/cocos2d/cocos/./2d/CCActionTiledGrid.cpp:603: error: undefined reference to 'srand'
collect2.exe: error: ld returned 1 exit status
make.exe: *** [obj/local/armeabi/libTheGame.so] Error 1
make.exe: Leaving directory `C:/projects/TheGame/TheGame/proj.android'
Error running command, return code: 2.
```

**Comment by halcyonx** [comment]
@minggo, but command **cocos run -p android --ap android-21** still builds fine without errors, but apk still crashing on old device

**Comment by minggo** [comment]
You should make sure that, build with android-21 can not make sure run on Android devices with older devices. It is the same that, application build for windows 7 can not make sure run on windows xp.

**Comment by halcyonx** [comment]
Yes, but with older android api I'm getting error, I described that in my second comment

**Comment by BlackCatz94** [comment]
> Yes, but with older android api I'm getting error, I described that in my second comment

You just need to clean build folder first.

**Comment by halcyonx** [comment]
Yes, I've cleaned bin/, gen/ and libs/, and build has success. Thanks.
