### ISSUE TITLE
No window after install Debian

### ISSUE THREAD

**Issue by ivosu** [cocos2d/cocos2d-x#17972]
Hey,
I have Debian 9 (Stretch). I followed the installation guide and compiled everything.
But now when I try to run cpp-empty-test or any other test - nothing happens. CPU is doing SOMETHING but no window, no error on terminal.
Does anyone know what is happening or at least how to get some info or error from the program?
PS: Tried install from this repo and it doesn't compile and says a lot of errors like "relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC". The successful compile was from the download page for 3.15.1  
Edit:
I installed it on the same version on my laptop and it works, so I think it is because I use Nvidia drivers on the other PC. Can someone confirm that?

**Comment by minggo** [comment]
cocos2d-x only supports ubuntu, other platforms can not make sure to work.
