### ISSUE TITLE
cocos gen-libs - does not work witk latest android sdk

### ISSUE THREAD

**Issue by crazyhappygame** [cocos2d/cocos2d-x#17973]
- cocos2d-x version: 15.1
- devices test on: 
- developing environments
   - NDK version:14b
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. cocos gen-libs -p android --app-abi armeabi-v7a
Error:
Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0.
Error running command, return code: 101.

**Comment by minggo** [comment]
Yep, you should copy `tools` folder from older Android SDK version.
