### ISSUE TITLE
libc.so tgkill

### ISSUE THREAD

**Issue by deguilardi** [cocos2d/cocos2d-x#17988]
- cocos2d-x version: 3.14.1
- devices test on: varius
- developing environments
   - NDK version: 15.0.4075724 (bundle)
   - Xcode version: 8.3.3 (8E3004b)

Steps to Reproduce:
This error occurs 1 time for each 200 times you open the app. Android 6 and 7 only.
The app crashes on startup. I am getting this error 3k times a day on production.

Android 6.0 backtrace #1:

backtrace:
  native: pc 00000000000427bc  /system/lib/libc.so (tgkill+12)
  native: pc 00000000000403c9  /system/lib/libc.so (pthread_kill+32)
  native: pc 000000000001caab  /system/lib/libc.so (raise+10)
  native: pc 0000000000019d29  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 000000000001756c  /system/lib/libc.so (abort+4)
  native: pc 00000000003313f3  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+210)
  native: pc 00000000000f447b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
  native: pc 000000000034fc07  /system/lib/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv.part.170+378)
  native: pc 0000000000136b4b  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+34)
  native: pc 000000000029e429  /system/lib/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+812)
  native: pc 0000000000203e78  /data/app/com.guilardi.eusei-2/lib/arm/libMyGame.so (_ZN7cocos2d7network27_preloadJavaDownloaderClassEv+48)
  native: pc 00000000001cfa05  /data/app/com.guilardi.eusei-2/lib/arm/libMyGame.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeInit+176)
  native: pc 0000000001729e0d  /data/app/com.guilardi.eusei-2/oat/arm/base.odex

Android 6.0 backtrace #2:
  native: pc 0000000000043c18  /system/lib/libc.so (tgkill+12)
  native: pc 0000000000041ee1  /system/lib/libc.so (pthread_kill+32)
  native: pc 000000000001bb4f  /system/lib/libc.so (raise+10)
  native: pc 0000000000018d01  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 00000000000168c0  /system/lib/libc.so (abort+4)
  native: pc 000000000031f58d  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+212)
  native: pc 00000000000f3b49  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2092)
  native: pc 00000000000f0377  /system/lib/libart.so (_ZN3art7BarrierD2Ev+182)
  native: pc 0000000000345ec5  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+144)
  native: pc 000000000031f649  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+400)
  native: pc 00000000000f3b49  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2092)
  native: pc 000000000033a771  /system/lib/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv.part.170+360)
  native: pc 00000000001333f3  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+26)
  native: pc 000000000028ddef  /system/lib/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+770)
  native: pc 0000000000203e78  /data/app/com.guilardi.eusei-2/lib/arm/libMyGame.so (_ZN7cocos2d7network27_preloadJavaDownloaderClassEv+48)
  native: pc 00000000001cfa05  /data/app/com.guilardi.eusei-2/lib/arm/libMyGame.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeInit+176)
  native: pc 00000000016f007d  /data/app/com.guilardi.eusei-2/oat/arm/base.odex

Android 7.0 backtrace:

backtrace:
  native: pc 0000000000049c44  /system/lib/libc.so (tgkill+12)
  native: pc 00000000000473e3  /system/lib/libc.so (pthread_kill+34)
  native: pc 000000000001d535  /system/lib/libc.so (raise+10)
  native: pc 0000000000019081  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 00000000000170e4  /system/lib/libc.so (abort+4)
  native: pc 0000000000319011  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+252)
  native: pc 00000000000b4979  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+864)
  native: pc 00000000003325c3  /system/lib/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv+602)
  native: pc 00000000000e4619  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+28)
  native: pc 000000000026011f  /system/lib/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+1878)
  native: pc 0000000000203e78  /data/app/com.guilardi.eusei-2/lib/arm/libMyGame.so (_ZN7cocos2d7network27_preloadJavaDownloaderClassEv+48)
  native: pc 00000000001cfa05  /data/app/com.guilardi.eusei-2/lib/arm/libMyGame.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeInit+176)
  native: pc 0000000000a8f255  /data/app/com.guilardi.eusei-2/oat/arm/base.odex

**Comment by deguilardi** [comment]
not a cocos issue

**Comment by semgilo** [comment]
I got the same issue, how did you deal with it in the end
