### ISSUE TITLE
Execution failed for task ':xxx:processDebugResources'. > java.lang.IllegalArgumentException (no error message)

### ISSUE THREAD

**Issue by kyleYang** [cocos2d/cocos2d-x#17985]
- cocos2d-x version: 3.15.1
- devices test on: cocos compile -p android --android-studio
- developing environments
   - NDK version: android studio 2.3.3 , mananger by android studio ,maybe the latest release version
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  clone cocos2d-x from github , download and setup
2. cocos new a coco2d-x lua project 
3. complile android --android-studio 
Failed ,and the 
Execution failed for task ':xxx:processDebugResources'.
> java.lang.IllegalArgumentException (no error message)

**Comment by kyleYang** [comment]
Hello ,anyone know this problem?

**Comment by chlinxxoo** [comment]
NDK pass but failed in making APK. Plz check your resources(Java code and assets).

**Comment by kyleYang** [comment]
@haolinchen1991 ,Thanks for your reply.
I don't write any code for my new project(Mac OS).
I just run cocos create new project, then cocos compile.
I have checked the jave code and assets, all of that is create by cocos.

**Comment by chlinxxoo** [comment]
@kyleYang The code created by cocos may be is unreliable. I suggest you can fix the java code where throw error even comment it.

**Comment by kyleYang** [comment]
@haolinchen1991 Hello
I am not family with Android。
The error print only java.lang.IllegalArgumentException , no more message.

```
---- the java code ---
package org.cocos2dx.lua;
import android.os.Bundle;
import org.cocos2dx.lib.Cocos2dxActivity;
public class AppActivity extends Cocos2dxActivity{

    @Override
    protected void onCreate(Bundle savedInstanceState) { //create by myself
        super.onCreate(savedInstanceState);
    }
}

```

--- the xml file -----

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.gfn510K.510k" 
    android:installLocation="auto">

    <uses-feature android:glEsVersion="0x00020000" />
    
    <application
        android:label="@string/app_name"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher">
        
        <!-- Tell Cocos2dxActivity the name of our .so -->
		<meta-data android:name="android.app.lib_name"
				   android:value="cocos2dlua" />
		
        <activity
            android:name="org.cocos2dx.lua.AppActivity"
            android:screenOrientation="landscape"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:label="@string/app_name"
            android:theme="@android:style/Theme.NoTitleBar.Fullscreen" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>  
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>  
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>  
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>  
    
  	<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
 	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

</manifest>
---- strings.xml-----
<resources>
    <string name="app_name">510K</string>
</resources>

```

-------------
Is that problem cause by the libcocos2dx?

**Comment by haolinchen1991** [comment]
You run the APK on device and it crash and throw the error?Or it throw error during running gradle for making APK?

**Comment by chlinxxoo** [comment]
@kyleYang You run the APK on device and it crash and throw the error?Or it throw error during running gradle for making APK?

**Comment by kyleYang** [comment]
@haolinchen1991 
throw error during running gradle. 
I have no idea how to resolve this problem and I can not find any answer for this question

**Comment by chlinxxoo** [comment]
@kyleYang Can you show me the message in **Gradle Console**?
![832b1ac1-98bc-4144-aed1-15e279719fdf](https://user-images.githubusercontent.com/5053268/27595408-2f7ee11a-5b8f-11e7-9300-d30899db6971.png)

**Comment by kyleYang** [comment]
@haolinchen1991 
Hello , I have resolved this problem .
Thanks!
Yestoday , I am thought that It's maybe the application id wrong .
Before it was com.xxxxx.510xxx  and I change it to com.xxxx.wushixxx
Now everthings seems be OK!

**Comment by thanhthien2010** [comment]
thanks :D
