### ISSUE TITLE
WebSocket.cpp close method  send signal sigpipe

### ISSUE THREAD

**Issue by yuanyouli** [cocos2d/cocos2d-x#17992]
- cocos2d-x version:3.15.1
- devices test on:ios
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.   There will send  a  signal sigpipe when close WebSocket 
2.  Xcode will stop at WebSocket.cpp line 725 _closeCondition.wait(lkClose) , but app not crash.

**Comment by huangapple** [comment]
@dumganhar  
@gdboy
I have same issue.

**Comment by huangapple** [comment]
https://github.com/cocos2d/cocos2d-x/issues/17965

**Comment by dumganhar** [comment]
signal pipe isn't a crash.
In libwebsockets, it just ignore signal pipe event, but xcode still got this event and break down.
You could click `resume` button to make your app continue running without any problems.
![7613ebe8-116b-46f4-8cfe-8dd3376e9583](https://user-images.githubusercontent.com/493372/27624440-582ea6a2-5c13-11e7-8c8f-01a600c50f2d.png)

**Comment by continuemycoding** [comment]
@dumganhar 没整明白怎么就不相信这是你们的死锁bug，调试的时候多线程等待可能不触发是再正常不过的事情了，手动按下resume的时候都好久了。所有native平台都有那个死锁bug。

**Comment by dumganhar** [comment]
@gdboy signal pipe & "`dead lock`" are different issues. I just explain the signal pipe issue.

**Comment by yuanyouli** [comment]
http://blog.csdn.net/arthurchenjs/article/details/7049175  about signal pipe

**Comment by yuanyouli** [comment]
use closeAsync also have signal pipe

**Comment by dumganhar** [comment]
@yuanyouli , yep, closeAsync may also trigger signal pipe event.
This event is triggered by `libwebsockets` internally.

**Comment by continuemycoding** [comment]
@dumganhar 不能因为是libwebsockets内部问题就不解决了吧，不用纠结术语，现象就是socket关闭时程序就大概率出现卡死，因为没满足信号条件。

**Comment by continuemycoding** [comment]
问题还没解决就急着关闭干嘛。。

**Comment by dumganhar** [comment]
@gdboy , you have to know the following
1. It's not us closed this issue.
2. signal pipe is only triggered when you're using xcode to debug, it's a bug of xcode since libwebsocket code has ignored that signal but xcode still trigger it. But it will not affect anything, you could click `resume` button in the xcode to make your app continue running. Running your app by clicking app  icon directly will not make your app crash.

**Comment by continuemycoding** [comment]
@dumganhar 我解释过了啊，随便多点击几次就出现了，不是只会出现在xcode调试环境下，native平台都会出现。平均出现概率保守估计达到三分之一，也就是没三次会出现一次。
