### ISSUE TITLE
create project with precompild libraries 

### ISSUE THREAD

**Issue by frenzyfrenzyfrenzy** [cocos2d/cocos2d-x#17991]
**cocos2d-x-3.15.1
Cocos Console 2.3
ndk r15b
cocos installed from source code on ubuntu 16.04.**

I run
 `cocos gen-libs -c -p android --ap android-22 --app-abi x86`
 and then I'm trying to create new game using static libraries with 
`cocos new ProjectName -p projectname.com.name -l cpp -t binary` 
and it says 
`Template named 'binary' is not found`, while cocos `gen-templates` says 
```
Error: argument 'gen-templates' not found.
Try with cocos -h
```
What am I doing wrong?

**Comment by minggo** [comment]
the prebuilt template is added for cocos studio, as cocos studio is canceled, they are not supported.

**Comment by ahcox** [comment]
So does this mean that only source builds are supported now? If so these docs need updating: http://www.cocos2d-x.org/docs/editors_and_tools/cocosCLTool/index.html#using-the-pre-built-libraries-in-your-projects

**Comment by minggo** [comment]
there is command of building prebuilt libs, but not corresponding template for it.

**Comment by meiry** [comment]
Is there any tutorial or example on how to build new template ?
Also is there any alternative way to create project using prebuild libs ?
