### ISSUE TITLE
Fedora 23 git build fails

### ISSUE THREAD

**Issue by ambitslix** [cocos2d/cocos2d-x#18008]
cmake..
make

[ 99%] Building CXX object tests/cpp-tests/CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/NetworkTest/WebSocketTest.cpp.o
[ 99%] Linking CXX executable ../../bin/cpp-tests/cpp-tests
/usr/bin/ld: ../../../external/websockets/prebuilt/linux/64-bit/libwebsockets.a(libwebsockets.c.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
tests/cpp-tests/CMakeFiles/cpp-tests.dir/build.make:3378: recipe for target 'bin/cpp-tests/cpp-tests' failed
make[2]: *** [bin/cpp-tests/cpp-tests] Error 1
CMakeFiles/Makefile2:530: recipe for target 'tests/cpp-tests/CMakeFiles/cpp-tests.dir/all' failed
make[1]: *** [tests/cpp-tests/CMakeFiles/cpp-tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Does this look familiar to anyone? I built websockets, libgflw from git...

**Comment by Rubonnek** [comment]
Seems like you are linking against a different library at some point. It builds successfully in Arch Linux.

Did you run:

```shell
python2 ./setup.py
python2 ./download-deps.py
```

from the root of the repository? There should be no need to build libwebsockets from other repositories, nor  libglfw. I'm not sure, but there should be a package for libglfw in Fedora.

**Comment by ambitslix** [comment]
I did the following:
git clone...
cd cocosd2d-x
setup.py
download-deps
git update submodule init
$ cd cocos2d-x/build
$ ./install-deps-linux.sh <-- did not work so I dnf installed the missing libs, or compiled them from source
$ cmake ..
$ make

**Comment by ambitslix** [comment]
Maybe this helps:
make VERBOSE=1

cd /home/alian/local/cocos2d-x/BUILD/tests/cpp-tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/cpp-tests.dir/link.txt --verbose=1
/usr/bin/c++    -std=c++11 -Wno-deprecated-declarations -Wno-reorder -Wno-invalid-offsetof -fPIC -O3 -DNDEBUG   CMakeFiles/cpp-tests.dir/Classes/ActionManagerTest/ActionManagerTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ActionsEaseTest/ActionsEaseTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ActionsProgressTest/ActionsProgressTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ActionsTest/ActionsTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/AllocatorTest/AllocatorTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/AppDelegate.cpp.o CMakeFiles/cpp-tests.dir/Classes/BaseTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/BillBoardTest/BillBoardTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-CCDrawNode.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-1159.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-1174.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-350.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-422.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-458/Bug-458.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-458/QuestionContainerSprite.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-624.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-886.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-899.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-914.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-12847.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-15594.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-15776.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/Bug-Child.cpp.o CMakeFiles/cpp-tests.dir/Classes/BugsTest/BugsTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/Camera3DTest/Camera3DTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ChipmunkTest/ChipmunkTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ClickAndMoveTest/ClickAndMoveTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ClippingNodeTest/ClippingNodeTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/CocosDenshionTest/CocosDenshionTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ConfigurationTest/ConfigurationTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ConsoleTest/ConsoleTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/CurlTest/CurlTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/CurrentLanguageTest/CurrentLanguageTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/DataVisitorTest/DataVisitorTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/DownloaderTest/DownloaderTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/DrawPrimitivesTest/DrawPrimitivesTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/EffectsAdvancedTest/EffectsAdvancedTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/EffectsTest/EffectsTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/AssetsManagerExTest/AssetsManagerExTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/ExtensionsTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/NetworkTest/HttpClientTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/TableViewTest/CustomTableViewCell.cpp.o CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/TableViewTest/TableViewTestScene.cpp.o CMakeFiles/cpp-tests.dir/Classes/FileUtilsTest/FileUtilsTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/FontTest/FontTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/InputTest/MouseTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/IntervalTest/IntervalTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/LabelTest/LabelTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/LabelTest/LabelTestNew.cpp.o CMakeFiles/cpp-tests.dir/Classes/LayerTest/LayerTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/LightTest/LightTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/MaterialSystemTest/MaterialSystemTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/MenuTest/MenuTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/MotionStreakTest/MotionStreakTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/MultiTouchTest/MultiTouchTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/NewAudioEngineTest/NewAudioEngineTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/NewEventDispatcherTest/NewEventDispatcherTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/NewRendererTest/NewRendererTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/NavMeshTest/NavMeshTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/NodeTest/NodeTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/OpenURLTest/OpenURLTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ParallaxTest/ParallaxTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/Particle3DTest/Particle3DTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ParticleTest/ParticleTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/PhysicsTest/PhysicsTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ReleasePoolTest/ReleasePoolTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/RenderTextureTest/RenderTextureTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/RotateWorldTest/RotateWorldTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/SceneTest/SceneTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/SchedulerTest/SchedulerTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ShaderTest/ShaderTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ShaderTest/ShaderTest2.cpp.o CMakeFiles/cpp-tests.dir/Classes/SpineTest/SpineTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/Scene3DTest/Scene3DTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/Sprite3DTest/DrawNode3D.cpp.o CMakeFiles/cpp-tests.dir/Classes/Sprite3DTest/Sprite3DTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/SpritePolygonTest/SpritePolygonTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/SpriteTest/SpriteTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/TerrainTest/TerrainTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/TextInputTest/TextInputTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/Texture2dTest/Texture2dTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/TextureCacheTest/TextureCacheTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/TexturePackerEncryptionTest/TextureAtlasEncryptionTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/TileMapTest/TileMapTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/TileMapTest/TileMapTest2.cpp.o CMakeFiles/cpp-tests.dir/Classes/TouchesTest/Ball.cpp.o CMakeFiles/cpp-tests.dir/Classes/TouchesTest/Paddle.cpp.o CMakeFiles/cpp-tests.dir/Classes/TouchesTest/TouchesTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/TransitionsTest/TransitionsTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/CocosGUIScene.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIButtonTest/UIButtonTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIRadioButtonTest/UIRadioButtonTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIFocusTest/UIFocusTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UILayoutTest/UILayoutTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIListViewTest/UIListViewTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIRichTextTest/UIRichTextTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIScale9SpriteTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIScene.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UISceneManager.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UISliderTest/UISliderTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UITextTest/UITextTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/CocoStudioGUITest/UITabControlTest/UITabControlTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UITest/UITest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UnitTest/RefPtrTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UnitTest/UnitTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/UserDefaultTest/UserDefaultTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/VisibleRect.cpp.o CMakeFiles/cpp-tests.dir/Classes/VibrateTest/VibrateTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ZwoptexTest/ZwoptexTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/SpriteFrameCacheTest/SpriteFrameCacheTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/controller.cpp.o CMakeFiles/cpp-tests.dir/Classes/VRTest/VRTest.cpp.o CMakeFiles/cpp-tests.dir/proj.linux/main.cpp.o CMakeFiles/cpp-tests.dir/Classes/WindowTest/WindowTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/Physics3DTest/Physics3DTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/NetworkTest/SocketIOTest.cpp.o CMakeFiles/cpp-tests.dir/Classes/ExtensionsTest/NetworkTest/WebSocketTest.cpp.o  -o ../../bin/cpp-tests/cpp-tests -rdynamic ../../lib/libcocos2d.a -lfontconfig -lfreetype -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 ../../../external/freetype2/prebuilt/linux/64-bit/libfreetype.a -lcurl ../../lib/libcocos2dInternal.a -lGLU -lGL -lGLEW -lglfw3 -lrt -lm -lXrandr -lXinerama -lXext -lXcursor -lXrender -lXfixes ../../lib/libunzip.a ../../lib/libtinyxml2.a -lX11 -lpthread -lxcb -lXau ../../../external/linux-specific/fmod/prebuilt/64-bit/libfmod.so -lpthread -lz ../../../external/jpeg/prebuilt/linux/64-bit/libjpeg.a -lpng ../../../external/tiff/prebuilt/linux/64-bit/libtiff.a ../../../external/websockets/prebuilt/linux/64-bit/libwebsockets.a ../../../external/openssl/prebuilt/linux/64-bit/libssl.a ../../../external/openssl/prebuilt/linux/64-bit/libcrypto.a -lX11 -lpthread -lxcb -lXau ../../../external/linux-specific/fmod/prebuilt/64-bit/libfmod.so -lpthread -lz ../../../external/jpeg/prebuilt/linux/64-bit/libjpeg.a -lpng ../../../external/tiff/prebuilt/linux/64-bit/libtiff.a ../../../external/websockets/prebuilt/linux/64-bit/libwebsockets.a ../../../external/openssl/prebuilt/linux/64-bit/libssl.a ../../../external/openssl/prebuilt/linux/64-bit/libcrypto.a -lfontconfig -lfreetype -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 ../../../external/freetype2/prebuilt/linux/64-bit/libfreetype.a -lcurl ../../lib/libxxhash.a ../../../external/webp/prebuilt/linux/64-bit/libwebp.a ../../../external/chipmunk/prebuilt/linux/64-bit/libchipmunk.a ../../../external/bullet/prebuilt/linux/64-bit/libBulletDynamics.a ../../../external/bullet/prebuilt/linux/64-bit/libBulletCollision.a ../../../external/bullet/prebuilt/linux/64-bit/libBulletMultiThreaded.a ../../../external/bullet/prebuilt/linux/64-bit/libLinearMath.a ../../../external/bullet/prebuilt/linux/64-bit/libMiniCL.a ../../lib/librecast.a -ldl -Wl,-rpath,/home/alian/local/cocos2d-x/external/linux-specific/fmod/prebuilt/64-bit 
/usr/bin/ld: ../../../external/websockets/prebuilt/linux/64-bit/libwebsockets.a(libwebsockets.c.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
tests/cpp-tests/CMakeFiles/cpp-tests.dir/build.make:3378: recipe for target 'bin/cpp-tests/cpp-tests' failed

**Comment by ambitslix** [comment]
Resolved, for those of you who may run into this, the library builds after I exclude CPP and JS tests:

**cmake -G "Unix Makefiles" -DBUILD_CPP_TESTS=OFF -DBUILD_LUA_LIBS=OFF -DBUILD_JS_TESTS=OFF ..**

make -j8

Then we still need:

sudo cp ../external/linux-specific/fmod/prebuilt/64-bit/libfmod* /usr/local/lib
sudo cp ../external/linux-specific/fmod/include/fmod.h /usr/local/include
sudo ln -s /usr/local/lib/libfmod.so /usr/local/lib/libfmod.so.6

**Comment by whatisor** [comment]
This is not solution, you just HIDE issue by turning off cpp-test
