### ISSUE TITLE
Debug and release builds cannot coexist in Linux when using the cocos console tool

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#18018]
- cocos2d-x version: 3.15.1

Steps to Reproduce:

1. Create a new project and get into the directory:
```
cocos new -l cpp build_coexist
cd build_coexist
```
2. Compile the project for debug mode:
```
cocos compile -p linux -m debug -j`nproc`
```
3. Compile the project for release mode:
```
cocos compile -p linux -m release -j`nproc`
```
4. Compile the project in debug mode again:
```
cocos compile -p linux -m debug -j`nproc`
```

And the whole building process will start from the beginning.

I'm aware I can just create another folder and use CMake to separate the builds and let them coexist, but it would be great if one could keep both builds when using `cocos` without having to recompile everything.

**Comment by drelaptop** [comment]
now the cmake build on linux divide the `bin` dir into `bin/Debug` and `bin/Release`, So that Debug and release builds can coexist. please reopen this if you find same problem when using GitHub latest code.

please close this issue @minggo
