### ISSUE TITLE
cocos web版本密码模式输入框文本不隐藏。

### ISSUE THREAD

**Issue by continuemycoding** [cocos2d/cocos2d-x#18011]
- cocos2d-x version:3.15
- devices test on:chrome
![image](https://user-images.githubusercontent.com/8704149/27731525-e36928ac-5dbf-11e7-8269-7786ddb252ce.png)
![image](https://user-images.githubusercontent.com/8704149/27731586-3b314ae2-5dc0-11e7-95c8-23e7d74b3ab8.png)
![image](https://user-images.githubusercontent.com/8704149/27731354-310451c8-5dbf-11e7-819c-ec87952d75a7.png)

**Comment by continuemycoding** [comment]
发现再设置下inputMode为非cc.EDITBOX_INPUT_MODE_ANY是可以隐藏的，比如cc.EDITBOX_INPUT_MODE_SINGLELINE。

**Comment by zilongshanren** [comment]
@gdboy  inputMode 本来就要设置为 `cc.EDITBOX_INPUT_MODE_SINGLELINE`
