### ISSUE TITLE
[iOS] Could not trigger 'onclose' event after network status is changed

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#18022]
- cocos2d-x version: v3.15.1
- devices test on: iPhone6
- developing environments
   - NDK version:
   - Xcode version: 8.3.3
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Go to cpp-tests/extension tests/WebSocketTest
2. Start webSocket test
3. Switch network from wifi to 4G or from 4G to wifi
4. No 'onclose' event is received and 'send'ed message also go into black hole.

**Comment by PatriceJiang** [comment]
This issue does not exist on the current version.  @minggo
