### ISSUE TITLE
Deadlock in WebSocket / Update libwebsockets to 2.2.0

### ISSUE THREAD

**Issue by j-jorge** [cocos2d/cocos2d-x#18026]
- cocos2d-x version: 3.15
- devices test on: iOS
- developing environments
   - Xcode version: 8.3.1

Steps to Reproduce:

1. Open a WebSocket
2. Turn off the iPhone's screen
3. Wait 3 minutes
4. Turn on the iPhone
5. Call `WebSocket::close()`
6. Observe that the app is frozen

When the app is in the background the web socket may be disconnected without notifying the client code. If one tries to close `cocos2d::WebSocket` then a deadlock occurs. The issue is [fixed in libwebsocket](https://github.com/warmcat/libwebsockets/issues/809) in 2.2.0 by notifying the client code that the socket has been disconnected.

Please update the dependency to `libwebsocket` in Cocos2d-X to fix the issue.

**Comment by dumganhar** [comment]
The latest release of libwebsocket is 2.2.1, shall we upgrade it to 2.2.1?

**Comment by huangapple** [comment]
upgrade it!

**Comment by continuemycoding** [comment]
@dumganhar 没人要求一定要最新版吧，但是cocos3.15之前的版本不会有这种问题，你们不能明知道有问题的情况下不去修复吧？我感觉你们维护团队有点不负责任。。

**Comment by continuemycoding** [comment]
https://github.com/cocos2d/cocos2d-x/issues/17992
https://github.com/cocos2d/cocos2d-x/issues/17965

@dumganhar

**Comment by continuemycoding** [comment]
@Dauch 难道我说的不是？反馈的问题也不给点回应，问题还没解决就把帖子关闭了。这是什么解决态度？

**Comment by Dauch** [comment]
你责任都搞不明白就开喷，有意思吗？

**Comment by continuemycoding** [comment]
@Dauch 那请问应该是谁背锅？libwebsocket？我项目出现cocos的bug也应该跟老板说是你们的责任就撒手不管了？

**Comment by Dauch** [comment]
libwebsocket

**Comment by Dauch** [comment]
你应该在libwebsocket那里喷，你们怎么写出bug了，导致我项目有问题！

**Comment by continuemycoding** [comment]
@Dauch 你们用了有问题的版本不是你们的责任？然后就放任不管帖子关闭？你确定这是正常解决问题的态度？

**Comment by continuemycoding** [comment]
@Dauch 我只是希望cocos变的更好，不然谁有空跟你扯这些。我自己顺手修复了提给你们干嘛？

**Comment by continuemycoding** [comment]
@Dauch 还有声明一下，我只是喷你们维护团队解决问题的态度，谁写代码没bug，bug没什么好喷的。

**Comment by dumganhar** [comment]
@gdboy, and all
I'm digging into this issue, we don't ignore any feedback of our developers.
Sometimes we did have some higher priority task to deal with, therefore, we probably can't reply to everyone quickly.
I posted a thread about websocket problem on iOS/macOS, could you guys give me some advice?
https://github.com/cocos2d/cocos2d-x/issues/17326

**Comment by dumganhar** [comment]
@gdboy, BTW, we need to use English for communication.

**Comment by continuemycoding** [comment]
@dumganhar 我不觉得用英文交流更高效，我不觉得你能说出我看不懂的英文，同时我并不认为你们的开发者外国人居多。用英语的话，可能很多国人要看懂就要借助于词典翻译。用中文，国际友人想看懂请自行翻译。同样是中国人，你喜欢用英语，习惯用英语我表示理解，但是要求国人和你交流也用外语就有点。。。让我不知所措

**Comment by continuemycoding** [comment]
@dumganhar 这是一个设备无关的bug，任何设备都会出现。

**Comment by j-jorge** [comment]
@dumganhar 2.2.1 is OK indeed. My first post has a typo, it's actually the one I have tested.

**Comment by fuyifan** [comment]
@dumganhar coz we don't have the experience to change the 3rd party library for cocos, so we guys may have the idea that the job might not take too much time. Actually we DO want to contribute our effort to make cocos better if the document is fine.

**Comment by fuyifan** [comment]
I see mingo sent a pull #17968 Is It fixed this issue?

**Comment by continuemycoding** [comment]
@fuyifan 自力更生吧，我那样改之后在几个平台上测试都是正常的。

**Comment by letrungtrung** [comment]
@j-jorge I have same problem. Can you give me the libwebsocket v2.2.1 was built for cocos?

**Comment by j-jorge** [comment]
@letrungtrung You can use the scrip below to build the updated library yourself. Please adapt it to fit your need. 

[libwebsockets-cocos2d-x.txt](https://github.com/cocos2d/cocos2d-x/files/1256475/libwebsockets-cocos2d-x.txt)

**Comment by PatriceJiang** [comment]
This issue was solved after refactor.  @minggo

**Comment by minggo** [comment]
Cool, i will close this issue. Will reopen it if anyone meet it again.
