### ISSUE TITLE
setRotation not working for particles inside ParticleBatchNode

### ISSUE THREAD

**Issue by jenthone** [cocos2d/cocos2d-x#18039]
- cocos2d-x version: 3.15.1
If my particles are inside Node, rotation works ok. But if parent is ParticleBatchNode, rotation is always 0.
Any ideas how to fix this? Thanks!

**Comment by minggo** [comment]
could you please provide a test case to reproduce it?

**Comment by jenthone** [comment]
Sorry for my late reply. I have to try another way to use ParticleBatchNode with rotation.

    auto emitter1 = ParticleSystemQuad::create("Particles/LavaFlow.plist");
    emitter1->setRotation(90); // Not working for batchnote
    emitter1->setStartColor(Color4F(1,0,0,1));
    auto emitter2 = ParticleSystemQuad::create("Particles/LavaFlow.plist");
    emitter2->setStartColor(Color4F(0,1,0,1));
    auto emitter3 = ParticleSystemQuad::create("Particles/LavaFlow.plist");
    emitter3->setStartColor(Color4F(0,0,1,1));

    auto s = Director::getInstance()->getWinSize();

    emitter1->setPosition(Vec2( s.width/1.25f, s.height/1.25f));
    emitter2->setPosition(Vec2( s.width/2, s.height/2));
    emitter3->setPosition(Vec2( s.width/4, s.height/4));

    auto batch = ParticleBatchNode::createWithTexture(emitter1->getTexture());

    batch->addChild(emitter1, 0);
    batch->addChild(emitter2, 0);
    batch->addChild(emitter3, 0);

    addChild(batch, 10);
