### ISSUE TITLE
iOS CCFileUtils.mm should use NSDocumentDirectory instead of NSCachesDirectory

### ISSUE THREAD

**Issue by CyberBotX** [cocos2d/cocos2d-x#1805]
Since version 2.0.2 of cocos2d-x, the iOS CCFileUtils.mm has been using NSCachesDirectory instead of NSDocumentDirectory, due to the commit of https://github.com/cocos2d/cocos2d-x/commit/411e1848c22edd38a4d59fbef1f6bb94e3009157

It was also mentioned on the forum http://www.cocos2d-x.org/boards/6/topics/16422 but it appears that the gles20 branch, which contains the released versions, does not have this fixed.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2662
