### ISSUE TITLE
inconsistant delta value from "void update(float delta)" when app is back active in Release mode.

### ISSUE THREAD

**Issue by Paco777** [cocos2d/cocos2d-x#18072]
- cocos2d-x version: 3.15.1
- devices test on: different  iOS devices  with different iOS versions
- developing environments : Xcode Version 8.3.3 (8E3004b)

If you open the notification center, the app is paused (music still working).
If you close if few seconds layer, the app is resumed.

This is good and works as expected when compiled in Debug mode but there is a problem in Release mode.

In Release mode the current animations are not resumed correctly, and are usually directly ended.
This is because the elapsed time (while the notification center was displayed) is taken into account in Release mode (but not in Debug mode).

We can see the same problem with the delta time value from the update(float delta) method (triggered when scheduleUpdate has been performed).

The first frame (the first update(float delta) call), after the app is back active (the notification center being hidden), will have a usual low value (e.g .01s) in Debug mode, but will have a high value (e.g 5s) in release mode, according to the time spent while paused.

**Comment by minggo** [comment]
have you tried this PR: https://github.com/cocos2d/cocos2d-x/pull/18041?

**Comment by Paco777** [comment]
Hi,
I just did.

Unfortunately this fix doesn't seems to solve the problem.

You should be able to reproduce the problem (in Release mode) by displaying the control center with a swipe from the bottom, wait a few seconds, and touch the screen to make it disappear.
The next delta time will be equal to the few seconds spent during that wait time.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/18084
thanks for feedback

**Comment by Paco777** [comment]
Thank you for your hard work !
