### ISSUE TITLE
sprite flicker when replaceScene with action CCTransitionFlipX / Y

### ISSUE THREAD

**Issue by skyblue** [cocos2d/cocos2d-x#1807]
![iOS 2012-12-31 1 39 19 ](https://f.cloud.github.com/assets/248937/36330/8e6440f2-530c-11e2-8075-9ae93a4ab873.png)

![iOS 2012-12-31 1 39 50 ](https://f.cloud.github.com/assets/248937/36331/e85fefe8-530c-11e2-82e1-23972a5823af.png)

**Comment by dumganhar** [comment]
Hello, @skyblue 
Was this issue fixed?

**Comment by skyblue** [comment]
I set  CCDirector::sharedDirector()->setDepthTest(false)  then it looks ok
