### ISSUE TITLE
[Android] Bad Request

### ISSUE THREAD

**Issue by kienvn** [cocos2d/cocos2d-x#18076]
I tested Android 7.0.1
I request this link http://vportal.static.zingplay.com/susun/mobile/version.manifest
It take error:
400 - Bad Request

**Comment by minggo** [comment]
What's your engine version? How did you do request?

**Comment by kienvn** [comment]
I use cocos2d-x 3.15, AssestsManagerEx to update game, i tried many other host is ok, except this link.
