### ISSUE TITLE
Crash on Cocos2dxGLSurfaceView.onSizeChanged(int, int, int, int) when using setContentView()

### ISSUE THREAD

**Issue by lance-gray** [cocos2d/cocos2d-x#1809]
Is cocos2d-x 2.0.4 not using layout XML files for android anymore?
I see Cocos2dxGLSurfaceView creates its layout by code and not by XML and the res/layout folder is missing on the samples.

Is it possible to use layout XMLs again for cocos2d-x-2.0.4? I need to use them for MoPub ads as it uses layout XML to position ads on screen.

I tried using `setContentView( R.layout.main_game_layout );` (and I have `res/layout/main_game_layout.xml` for the layout file) on the `src/com/mycompany/myapp/myapp.java`'s `onCreate()` method but the app crashes when the app starts. I get logs that the app has started as it shows that `cocos2d: cocos2d-2.0-x-2.0.4` message on the LogCat.

My guess is that the app crashes when the GLSurfaceView is being created. The crash points me to: `Cocos2dxGLSurfaceView.onSizeChanged(int, int, int, int) line: 275`.

**Comment by godyZ** [comment]
@lance-gray  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2661
