### ISSUE TITLE
Broken touch processing after widget removed and added again

### ISSUE THREAD

**Issue by newnon** [cocos2d/cocos2d-x#18104]
- cocos2d-x version:3.15+
- devices test on: mac, ios, android
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. add button to scene
2. retain it
3. remove it from scene
4. add it to scene again

button will by not clickable

commit that broke this
https://github.com/cocos2d/cocos2d-x/commit/95baff70869c130922fe3fe5cf46d86fe5524e0c

_eventDispatcher->removeEventListenersForTarget(this);

but on adding button again _touchEnabled is true but listener will by not added again

**Comment by Anywhere-Music-Player** [comment]
@dumganhar this issue breaks development of my game. @minggo this really requires fix.

**Comment by minggo** [comment]
@dumganhar please take a look.

**Comment by dumganhar** [comment]
@newnon , @KAMIKAZEUA  if you want to remove it from scene and add it to another scene, please don't cleanup node. I mean, don't use `node->removeFromParent();` or `node->removeFromParent(true)`. Without an argument or with a argument `true` will cleanup `action`, `schedule` and `eventlistener` associated with that node. Instead, you need to call `node->removeFromParent(false)` which means keep the `action`, `schedule` and `eventListener`, they will not be cleanup.  This is what `cleanup` used for.

The commit 95baff7 just corrects the wrong logic code.

**Comment by newnon** [comment]
but if you add it again it touches can't be enabled normally if you just call call setTouchEnabled it will do nothing because flag _touchEnabled already true
may be check this flag and add _touchListener again?

**Comment by Anywhere-Music-Player** [comment]
@dumganhar I'm just using `runAction` :
```
Sequence::createWithTwoActions(DelayTime::create(0.31),
RemoveSelf::create()));
```
And I'm adding it to the same Node next time.

**Comment by dumganhar** [comment]
@newnon 
> but if you add it again it touches can't be enabled normally if you just call call setTouchEnabled it will do nothing because flag _touchEnabled already true
may be check this flag and add _touchListener again?

Did you try `node->removeFromParent(false)`? Did you mean this also didn't work for you?
If it's ,did you try to revert(delete) this line `_eventDispatcher->removeEventListenersForTarget(this);` in Node::cleanup to see whether it's caused by this line?

@KAMIKAZEUA 
If I understand correctly, did you add a same action to different nodes? If so, it's an invalid operation, you should use `action->clone()` to make a cloned action and add it to another node.

**Comment by Anywhere-Music-Player** [comment]
@dumganhar I just described how I'm removing node. It's just pause popup. It's removes itself when user tap resume button and that action executes. And I'm adding it at the same node again, when user press pause button again.

**Comment by newnon** [comment]
@dumganhar node->removeFromParent(false) solve problem but if i want really cleanup node?
i think we need to ad some code in widget that will be add listener again after adding it to scene again

**Comment by AIGRIND-LLC** [comment]
Just want to confirm that this issue broke our project too.

**Comment by Anywhere-Music-Player** [comment]
I've used that fix and all okay now.. but some logic looks like not really good.. anyway it woks.

**Comment by sbrednikhin** [comment]
Confirm issue. Looks like it would be better to remove all event listeners except touch listeners.

**Comment by frozax** [comment]
Issue took me a few hours to understand when upgrading to 3.16, too. My use case is that I have a complex node that I only want to create once (with touch listeners and many sprites), but if I need it again, I retained it and add it again to the scene.

**Comment by Anywhere-Music-Player** [comment]
Just use fix as I'm https://github.com/newnon/cocos2d-x/commit/bc560c36b189907f82739ae973cc803651b3316d after that I got no problems so far. Current logic in cocos2d-x is wrong...

**Comment by dumganhar** [comment]
Indeed, current logic of removeEventListener in Node::cleanup is correct. It was wrong before v3.16.

> node->removeFromParent(false) solve problem but if i want really cleanup node?
i think we need to ad some code in widget that will be add listener again after adding it to scene again

@newnon , you see that Node::pause, Node::resume

```c++
void Node::resume()
{
    _scheduler->resumeTarget(this);
    _actionManager->resumeTarget(this);
    _eventDispatcher->resumeEventListenersForTarget(this);
}

void Node::pause()
{
    _scheduler->pauseTarget(this);
    _actionManager->pauseTarget(this);
    _eventDispatcher->pauseEventListenersForTarget(this);
}
```
Scheduler, ActionManager, EventDispather are all associated with Node, and in Node::cleanup, we remove Schedule, Action. Why shouldn't we remove EventListeners for the Node.

It's a cleanup method, cleanup means that everything associated with current Node should be removed.

If a node is cleaned up, all its actions, schedulers, event listeners should be reseted by user's code.

Yes, I know that this change break the compatibility of version before 3.16, however, I think if we make a mistake and keep it there forever, it's difficult to improve.

```c++
node->retain();
node->removeFromParent(true);  // all actions, schedulers, event listeners will be removed.
// if you want to add node to another parent, you have the responsibility to add actions, schedulers, event listeners again.
```

**Comment by dumganhar** [comment]
Reverting code is easy, but before that, we need to think which is more important between keeping compatibility and correcting wrong code logic.

**Comment by dumganhar** [comment]
> I just described how I'm removing node. It's just pause popup. It's removes itself when user tap resume button and that action executes. And I'm adding it at the same node again, when user press pause button again.

@KAMIKAZEUA , 
```c++
static RemoveSelf * create(bool isNeedCleanUp = true);
```

The create method of RemoveSelf takes an argument of `isNeedCleanup`. So you need to set it to false if you don't want to cleanup node and just wanna remove it from parent.

**Comment by Anywhere-Music-Player** [comment]
That should be like official warning, because old code will break, like for other ppl. So they will feel, that after upgrading something will be broken next again. And now I should check this in all code places in my games..

**Comment by newnon** [comment]
@dumganhar it ok to remove EventListeners on cleanup but i think you must implement some code for standard classes like button to add it again if developer add it to scene again. At this moment there is no possibility to reuse button after removeFromParent(true);

**Comment by dumganhar** [comment]
But you could use pass false to removeFromParent. I'm thinking reverting
the change, I mean keep old wrong logic. Yes, it's wrong, but its also a
feature on the other hand. What do you think？

newnon <notifications@github.com>于2017年12月14日 周四18:45写道：

**Comment by frozax** [comment]
I agree with the last comment of @newnon. It's especially complicated if you removeFromParent a main Node where one of its child is a button. Maybe you want a cleanup on the "main" node but not on the child button node. In fact, I do retain my child button node to reuse it, but listeners were removed indirectly by a parent or grand-parent.

**Comment by dumganhar** [comment]
@frozax , 
I guess you want some customized functionality of removeFromParent/removeChild(cleanup = true) for `Button`.
Yes, it's possible to achieve that since `Button` could override the virtual `cleanup`.

But this will make thing more complex and worse.

**Comment by dumganhar** [comment]
I have sent a PR for reverting this change:

https://github.com/cocos2d/cocos2d-x/pull/18565

Reverting this will not affect the users who use `removeFromParent(false)` in v3.16.
Yes, I didn't consider enough of that user code may have wrong usage of removeFromParent API.
As Riq has said something like that "Yes, it's wrong, but perhaps it's also a feature.".
I will keep in mind of this.
Thanks for you guys about reporting this issue.
Best Wishes!

**Comment by dumganhar** [comment]
I have also posted a thread in our forum:

http://discuss.cocos2d-x.org/t/note-compatibility-issue-of-node-cleanup-in-cocos2d-x-v3-16/40560

**Comment by meiguizhinian** [comment]
why not setTouchEnable(false) in cleanup?
