### ISSUE TITLE
Lua add modules directory

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18119]
- cocos2d-x version: git
- devices test on: linux mint 18.2

Steps to Reproduce:

1. Create directory `lib` in `src`
2. Add this code to `main.lua`:

 

    package.path = ';./lib/?.lua;./lib/?/init.lua'
3. Create this structure in lib:

 

    lib +
         |- test1.lua
         |- test2 +
                      |- init.lua
4. For some reasons I can do `require 'test1'`, but can't `require 'test2'`.
How can I make possible to load `test2` in cocos2d-x?  
P.S.: it works in pure lua.

**Comment by v1993** [comment]
@minggo What do you think about this problem?

**Comment by minggo** [comment]
I am not sure. This feature may not be supported, but you can use full path to require the lua file.

**Comment by v1993** [comment]
Does cocos2d-x implement its own require function?

**Comment by minggo** [comment]
this function: https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/lua-bindings/manual/Cocos2dxLuaLoader.cpp

**Comment by v1993** [comment]
This function doesn't understand pathes without `?.lua` at end, so it is a problem's source.

**Comment by v1993** [comment]
It should replace `?` with module's name with `.` replaced with `/`. More details: https://www.lua.org/manual/5.1/manual.html#pdf-package.loaders.

**Comment by v1993** [comment]
I'm fixing it right now, and will open PR soon.

**Comment by v1993** [comment]
Pull request: #18171
