### ISSUE TITLE
SIGSEGV on exit

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18118]
- cocos2d-x version: git
- devices test on: linux mint 18.2

Steps to Reproduce:

1. build any game
2. launch and close it

I found a strange bug with cocos: it always crashes on exit. No matter which project, which language, which way to close - always segfault on exit. Some information from gdb:

    ...
    Program received signal SIGSEGV, Segmentation fault.
    0x00007f7c4eae1a30 in ?? ()
    (gdb) continue
    Continuing.
    
    Program terminated with signal SIGSEGV, Segmentation fault.
    The program no longer exists.

**Comment by minggo** [comment]
how did you exit the program?

**Comment by v1993** [comment]
:endToLua, closing window - always crash.

**Comment by minggo** [comment]
endToLua just invoke `Director::end()`. I always click window's close item, didn't find crash.

**Comment by drelaptop** [comment]
As I confirmed, `endToLua ` works on iOS platform after https://github.com/cocos2d/cocos2d-x/pull/19236 patch.
