### ISSUE TITLE
Problem with playEffect several times

### ISSUE THREAD

**Issue by zabumba69** [cocos2d/cocos2d-x#1811]
01-03 01:39:00.227: D/OPENSL_ENGINE.CPP(6472): failed to recreate
01-03 01:39:00.522: E/libOpenSLES(6472): Too many objects
01-03 01:39:00.522: W/libOpenSLES(6472): Leaving Engine::CreateAudioPlayer (SL_RESULT_MEMORY_FAILURE)

**Comment by minggo** [comment]
It seems that you create play too many effects at the same time.

**Comment by zabumba69** [comment]
My game has just one sound effect played many times and only happened on my device Galaxy S2 (I9100 model), but in my other device, Galaxy S3 (I9300 model), I have other bug, The playEffect with loop YES not return soundID and I can't stopped the sound effect.

I see that in SimpleAudioEngine.cpp exist a condition with the models 9100 and because this it happens in one but not in the other.

unsigned int SimpleAudioEngine::playEffect(const char\* pszFilePath, bool bLoop)
{
    if (s_bI9100)
    {
        return SimpleAudioEngineOpenSL::sharedEngine()->playEffect(pszFilePath, bLoop);
    }
    else 
    {
        return playEffectJNI(pszFilePath, bLoop);
    }
}

Thank you for your answer.

**Comment by zabumba69** [comment]
I'm using the last version: cocos2d-2.1beta3-x-2.1.0 with JS binding. (my game is in javascript JSB)
