### ISSUE TITLE
CCScrollView bug

### ISSUE THREAD

**Issue by ivyshao** [cocos2d/cocos2d-x#1812]
1.  when add a menu in scrollview, will not scroll if click on the menu
   - need to set touch priority to kCCMenuHandlerPriority-1
2. after fix the first one, after scroll, the button click event is also triggered
   - need claim touch
3. button out of scroll content size, is still clickable
   - need check if touch is in the content size area

**Comment by dumganhar** [comment]
So did you fix these issues? If so, could you send the patch to us?

**Comment by ivyshao** [comment]
no, I meet same issues for cocos2d-iphone, and fixed. But no patch for cocos2d-x.

**Comment by dumganhar** [comment]
Could you send me the patch you fixed for cocos2d-iphone?
I could help to make it works on cocos2d-x.
Thanks.

**Comment by ivyshao** [comment]
diff: 

wrong one: 

fixed one: 

Changes:
1. claimTouch in ccTouchMoved
2.registerWithTouchDispatcher with priority kCCMenuTouchPriority - 1
3. in ccTouchBegan:
    if (!CGRectContainsPoint(frame, [container_ convertToWorldSpace:[container_ convertTouchToNodeSpace:touch]])) {
        return YES;
    }
4. removeTouchInChildren in ccTouchEnded if touch is not handle in CCTouchBegin

BR

**Comment by ivyshao** [comment]
I have fixed this. I override CCScrollView and CCMenu, to make it work. will send you my code

**Comment by dumganhar** [comment]
OK, thank you. :)

**Comment by ztoky** [comment]
Is this bug fixed?

**Comment by dumganhar** [comment]
@ztoky 
You could refer to https://github.com/cocos2d/cocos2d-x/pull/2081 .
It isn't merged now.
