### ISSUE TITLE
使用Console->addCommand 添加远程调试命令，调用命令时偶现的崩溃情况

### ISSUE THREAD

**Issue by G17hao** [cocos2d/cocos2d-x#18133]
- cocos2d-x version:3.15.1
- devices test on:all platform

Steps to Reproduce:

1. using console->addCommand in project
2. use it

addCommand添加回调时是在Console的socket接收线程中直接回调的（包括导出到lua和js），存在同步问题，应考虑使用performFunctionInCocosThread在主线程中执行（导出到lua和js则是必要的）

**Comment by G17hao** [comment]
提个bug已经费了些时间，还要说英语实在是很打击别人提bug的积极度。
尤其我这种英语渣

**Comment by minggo** [comment]
please create a new one in english, thanks.
You can use google translate to translate Chinese and paste them, such as
```
问题是这样的

question is that ...
```
