### ISSUE TITLE
热更新重大bug，必现

### ISSUE THREAD

**Issue by continuemycoding** [cocos2d/cocos2d-x#18139]
- cocos2d-x version:3.15

热更新不能断点续传，没更新完成的时候断开，下次不但不能断点续传而且不能重新下载，把cocos creator的热更新复制过去替换重新绑定就好了。试过很多次都能正常断点续传。

**Comment by zcgit** [comment]
cocos creator的热更新在哪？

**Comment by kyleYang** [comment]
热更新我Android出现不能下载问题，能问下你吗？

**Comment by continuemycoding** [comment]
everything搜索下文件就知道在哪了 @zcgit @kyleYang

**Comment by kyleYang** [comment]
@gdboy ，我是用 cocos2dx-lua 的。没有用cocos creator。 而且我刚接触cocos2dx 。遇到好多坑。 我热更新在iOS上面是OK，但是在Android里面就不行。在Android的机器上面，也没有在data/data 路径下找到下载的文件。
整个社区，发现在github上面提问，被回答的比较慢。很急

**Comment by gdboy** [comment]
可能是https的问题，android和windows你试试http。@ykleYang

**Comment by continuemycoding** [comment]
可能是https的问题，android和windows你试试http。 @kyleYang

**Comment by kyleYang** [comment]
@gdboy 我这边没有用https，我只是简单的架设在阿里云的 oss上面。地址我刚看了是http的。在其他的人里面看到了https的问题。但是貌似我这边没有。

**Comment by continuemycoding** [comment]
那我就不知道了，我那个问题是断点续传的问题，下载本身是正常的。 @kyleYang

**Comment by kyleYang** [comment]
@gdboy 嗯。好的，谢谢你了。

**Comment by minggo** [comment]
please use english, thanks
