### ISSUE TITLE
JNI 相关函数存在没有释放引用的情况

### ISSUE THREAD

**Issue by G17hao** [cocos2d/cocos2d-x#18130]
- cocos2d-x version: 3.13.1
- devices test on: 网易MOMO
- developing environments
   - NDK version: r10e

Steps to Reproduce:
Java_org_cocos2dx_lib_Cocos2dxHelper.cpp
conversionEncodingJNI
这个函数调用次数超过512次时程序崩溃，报错提示
E/dalvikvm( 3307): JNI ERROR (app bug): local reference table overflow (max=512)
检查发现newArray没有释放

其他地方也可能存在没有释放的情况，建议加上相关测试。

**Comment by minggo** [comment]
please use english, thanks
