### ISSUE TITLE
TintTo action does not change color at all if duration is 0.0f

### ISSUE THREAD

**Issue by Shukalovich** [cocos2d/cocos2d-x#18151]
- cocos2d-x version: cocos2d-x-3.15.1
- devices test on: iPhone 7
- developing environments
   - NDK version: not use
   - Xcode version: Version 8.3.3 (8E3004b)
   - VS version: not use
   - browser type and version: not use

Steps to Reproduce:
auto sprite = cocos2d::Sprite::create("SpriteSileName.png");
sprite->setColor(cocos2d::Color3B::WHITE);
sprite->runAction(cocos2d::TintTo::create(0.0f, cocos2d::Color3B::RED));

In example above sprite does not change it's color all. 

But this code works properly
auto sprite = cocos2d::Sprite::create("SpriteSileName.png");
sprite->setColor(cocos2d::Color3B::WHITE);
sprite->runAction(cocos2d::TintTo::create(**0.0001f**, cocos2d::Color3B::RED));

It's needed to add zero multiplying check. At first glance cocos2d::TintBy action has same problem.

**Comment by minggo** [comment]
i think the effect is right. TintTo is a finite time action, it is not instant action. If you want to change the color without duration, you can set the color directly or use CallFunc to change the color.

**Comment by Shukalovich** [comment]
But if I calculate duration dynamically and it passible to be zero. At this point I must write additional if statement like:  duration == 0.0f ? cocos2d::CallFuncN::create([](auto node) { node->setColor(color); }) : cocos2d::TintTo::create(duration, color). 
Do you think it's normal? I think it's **redundant**.

**Comment by minggo** [comment]
May be you can change duration to 0.0001 when it is 0?

**Comment by Shukalovich** [comment]
Yes, I can. I already have done this. But it's not perfect for cocos2d API. I wasted some time in debugger while I looked up the problem in my code.
