### ISSUE TITLE
.gitignore for cocos2d-x

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18161]
Is there any `.gitignore` examples for cocos2d-x projects? It would be useful.

**Comment by v1993** [comment]
My .gitignore for `frameworks/runtime-src/proj.android`:

    # Dirs
    /assets
    /bin
    /gen
    /libs
    /obj
    
    # Files
    /local.properties

**Comment by v1993** [comment]
My .gitignore for project's root (only linux build, please help with other platforms):

    # Common place
    /simulator
    
    # Linux build
    /linux-build
    
    # Prerequisites
    *.d
    
    # Object files
    *.o
    *.ko
    *.obj
    *.elf
    
    # Linker output
    *.ilk
    *.map
    *.exp
    
    # Precompiled Headers
    *.gch
    *.pch
    
    # Libraries
    *.lib
    *.a
    *.la
    *.lo
    
    # Executables
    *.exe
    *.out
    *.app
    *.i*86
    *.x86_64
    *.hex
    
    # Debug files
    *.dSYM/
    *.su
    *.idb
    *.pdb

**Comment by minggo** [comment]
you can take a look of this file :https://github.com/cocos2d/cocos2d-x/blob/v3/.gitignore. And the ignore files depends your need, you can adjust them to meet your requirements.
