### ISSUE TITLE
How to upgrade AudioEngine from 3.10 to 3.51?

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#18160]
- cocos2d-x version:3.10 JSB
- devices test on: Android/Ios

Hi, guys.
I want upgrade AudioEngine from 3.10(jsb) to 3.51, because there are lots of issues be fixed.
But can I only replace AudioEngine, and how to do it?

**Comment by minggo** [comment]
yep, you can update it yourself, but it is not easy to describe it. What i think are:

- replace AudioEngine folder
- fix compiling error
- update corresponding 3rd party libraries for audio
- update binding codes if needed
