### ISSUE TITLE
crash on loading csb at TextFieldReader::setPropsWithFlatBuffers

### ISSUE THREAD

**Issue by qianwen36** [cocos2d/cocos2d-x#18162]
- cocos2d-x version: 3.15.1
- devices test on: simulator on win32 or android
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:2013
   - browser type and version:

Steps to Reproduce:
1. make a scene with text field, generate .csb file
2. test with lua. when loading the file. it crash on following
```
    void TextFieldReader::setPropsWithFlatBuffers(cocos2d::Node *node, const flatbuffers::Table *textFieldOptions)
    {
        TextField* textField = static_cast<TextField*>(node);
        auto options = (TextFieldOptions*)textFieldOptions;
        
        std::string placeholder = options->placeHolder()->c_str();

```
It seems the TextFieldOptions::placeHolder() got a null pointer.
when i differ the CSParseBinary_generated.h between 3.15.1 and 3.6, I found that 'isLocalized' field was insert before 'placeHolder' so make the data bad.

Look at the fbs description from 3.15.1

```
table TextFieldOptions
{
    widgetOptions:WidgetOptions;

    fontResource:ResourceData;
    fontName:string;
    fontSize:int;
    text:string;
    isLocalized:bool = false;
    placeHolder:string;
    passwordEnabled:bool = false;
    passwordStyleText:string;
    maxLengthEnabled:bool = false;
    maxLength:int;
    areaWidth:int;
    areaHeight:int;
    isCustomSize:bool = false;
}
```

and I hope is there some .fbs file I can get from cocos2d 3.6 or more other that i can produce the parse code myself to fix the bad exception.

**Comment by qianwen36** [comment]
why the field 'isLocalized' was insert before 'placeHolder'? and I think the .fbs has some error

**Comment by minggo** [comment]
It is because flatbuffer is updated, and the .fbs files seems not correct. The reader and flatbuffer will  be reverted in v3.16. So i suggest you revert them manually to fix it.
