### ISSUE TITLE
Got crash when lots of sprites executed update at js side(jsb)

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#18172]
- cocos2d-x version:3.10
- devices test on:ios
 
Steps to Reproduce:
1.Class MySprite Extend cc.Sprite 
2. override update with empty:

update:function(deltaTime){
          var _self = this;
            _self._super(deltaTime);
            return;
}
3. create more than 50 MySprite with texture( png ), and all open scheduleUpdate

4.Wait more some minutes, apps crashed...

How to avoid this problem, Thanks!

![image](https://user-images.githubusercontent.com/848803/29405973-2f512544-8372-11e7-911b-973708ceb94f.png)

**Comment by minggo** [comment]
could you please provide a test case?

**Comment by liuyi** [comment]
After upgrade to 3.15.1, this problem looks like fixed already.
Thanks!

**Comment by minggo** [comment]
thanks for the information
