### ISSUE TITLE
CCEventDispatcher.cpp几率崩溃

### ISSUE THREAD

**Issue by bingle123** [cocos2d/cocos2d-x#18184]
- cocos2d-x version:3.15
- devices test on:android
- developing environments
   - NDK version:android-ndk-r14b
   - Xcode version:8.3.3
   - VS version:
   - browser type and version:

问题规律总结:

1. 在响应触屏事件时，回调业务逻辑之前偶尔崩溃，与具体业务无关，在好几处业务场景都有发生
2.多次崩溃Crash reason总是SIGSEGV,Crash address不定，有时候是0x0，有时候不是。
3.崩溃最后指向都是setDirtyForNode-> _Rb_tree_insert_and_rebalance,tree.cc无源代码，应该是在标准std库里面。

breakpad抓捕分析后的调用栈如下：
Crash reason:  SIGSEGV
Crash address: 0x0
Process uptime: not available
Thread 12 (crashed)
 0  libcocos2dlua.so!std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) [tree.cc : 282 + 0x2]
     r0 = 0x00000001    r1 = 0x00000000    r2 = 0x00000000    r3 = 0x00000001
     r4 = 0x794b2940    r5 = 0x401691d0    r6 = 0x794b2940    r7 = 0x76d44288
     r8 = 0x00000001    r9 = 0x00000000   r10 = 0x76d4428c   r12 = 0x783d3435
     fp = 0x7da069d8    sp = 0x7876b8f0    lr = 0x7805e9d8    pc = 0x783d3498
    Found by: given as instruction pointer in context
 1  libcocos2dlua.so!cocos2d::EventDispatcher::setDirtyForNode(cocos2d::Node*) [stl_tree.h : 1175 + 0xa]
     r4 = 0x7e4ae340    r5 = 0x76d441c8    r6 = 0x7db4d8a8    r7 = 0x76d44288
     r8 = 0x00000000    r9 = 0x7da069c8   r10 = 0x7da06a68    fp = 0x7da069d8
     sp = 0x7876b910    pc = 0x7805e9d8
    Found by: call frame info
 2  libcocos2dlua.so!cocos2d::EventDispatcher::setDirtyForNode(cocos2d::Node*) [CCEventDispatcher.cpp : 1549 + 0xa]
     r4 = 0x7be1967c    r5 = 0x76d441c8    r6 = 0x7be1967c    r7 = 0x76d44218
     r8 = 0xffffffff    r9 = 0x7da069c8   r10 = 0x7da06a68    fp = 0x7da069d8
     sp = 0x7876b930    pc = 0x7805e968
    Found by: call frame info
 3  libcocos2dlua.so!cocos2d::EventDispatcher::setDirtyForNode(cocos2d::Node*) [CCEventDispatcher.cpp : 1549 + 0xa]
     r4 = 0x7a77996c    r5 = 0x76d441c8    r6 = 0x7a77996c    r7 = 0x76d44218
     r8 = 0xffffffff    r9 = 0x7da069c8   r10 = 0x7da06a68    fp = 0x7da069d8
     sp = 0x7876b950    pc = 0x7805e968
    Found by: call frame info
 4  libcocos2dlua.so!cocos2d::EventDispatcher::resumeEventListenersForTarget(cocos2d::Node*, bool) [CCEventDispatcher.cpp : 348 + 0xa]
     r4 = 0x76d441c8    r5 = 0x00000000    r6 = 0x7d8f7db0    r7 = 0x76d44218
     r8 = 0xffffffff    r9 = 0x7da069c8   r10 = 0x7da06a68    fp = 0x7da069d8
     sp = 0x7876b970    pc = 0x7805eaac
    Found by: call frame info
 5  libcocos2dlua.so!cocos2d::Node::onEnter() [CCNode.cpp : 1331 + 0xe]
     r4 = 0x7a77996c    r5 = 0x7d8f7db0    r6 = 0x7a77996c    r7 = 0x7d8f7f28
     r8 = 0xffffffff    r9 = 0x7da069c8   r10 = 0x7da06a68    fp = 0x7da069d8
     sp = 0x7876b990    pc = 0x77fe085c
    Found by: call frame info
 6  libcocos2dlua.so!cocos2d::Node::addChildHelper(cocos2d::Node*, int, int, std::string const&, bool) [CCNode.cpp : 988 + 0xe]
     r4 = 0x76fc7ca8    r5 = 0x7d8f7db0    r6 = 0x00000000    r7 = 0x7d8f7f28
     r8 = 0xffffffff    r9 = 0x7da069c8   r10 = 0x7da06a68    fp = 0x7da069d8
     sp = 0x7876b9a0    pc = 0x77fe26d8
    Found by: call frame info
 7  libcocos2dlua.so!cocos2d::Node::addChild(cocos2d::Node*, int, std::string const&) [CCNode.cpp : 950 + 0xe]
     r4 = 0x00000001    r5 = 0x7a62a1c0    r6 = 0x7864b8e8    r7 = 0x40169394
     r8 = 0x76fc7ca8    r9 = 0x7da069c8   r10 = 0x7da06a68    fp = 0x7da069d8
     sp = 0x7876b9c0    pc = 0x77fe2840

**Comment by bingle123** [comment]
这个问题应该可以定位了，跟UIWidget.cpp克隆有关。
void Widget::copyProperties(Widget *widget)
{
         ...
        _touchEventListener = widget->_touchEventListener;
        ...
}
这个是有问题的，克隆的widget与原widget共享一个_touchEventListener对象，想象一下任意一个克隆的widget对象与原widget对象析构了，释放了_touchEventListener，会怎样？

**Comment by bingle123** [comment]
请触控的兄弟把上面的问题代码修复下-:) 我自己的代码是做了适时retain和适时release处理，问题已经得到解决。

**Comment by dumganhar** [comment]
I found this changes in https://github.com/cocos2d/cocos2d-x/pull/6885
I'm trying to make a simple demo for reproducing this issue.

**Comment by dumganhar** [comment]
```c++
CC_DEPRECATED_ATTRIBUTE void addTouchEventListener(Ref* target,SEL_TouchEvent selector);
```
@bingle123 , did you use this method for listening touch event? This method was deprecated, 
Uses `void addTouchEventListener(const ccWidgetTouchCallback& callback);` instead.

**Comment by dumganhar** [comment]
@bingle123, could you provide a demo for reproducing this issue? Thanks.

**Comment by minggo** [comment]
please create a new one in english, thanks

**Comment by MerlinYu** [comment]
@bingle123 我想请教的是另一个问题在我们的项目中同样遇到Crash reason: SIGSEGV，
Crash address是0x1，这种问题该 怎么定位？

**Comment by godisadog** [comment]
@bingle123 请问一下你现在什么怎么处理的UIWidget.cpp这个问题的，我也遇到了这个问题，能不能把你改后的UIWidget.cpp的代码贴一下，谢谢！

**Comment by bingle123** [comment]
你好，

我这边的cocos2d-x的项目已经停了许久，具体情形不太记得，我只能从git库里找到记录，看能否帮到你。





如果以上的代码修改确实能帮到你，回复下，让我也高兴高兴，哈哈。:)



在 2018/6/19 上午10:42, zhenwei 写道:

**Comment by godisadog** [comment]
@bingle123 我这里看不到你发的git记录，我刚把我的代码改了一下，在使用clone的地方都改了，还是会出现crash，而且我的这个不是在触摸屏幕的时候crash的是在运行完第一个界面在加载第二个界面的时候报错的，报的错是

#00 pc 01da8a2a /data/app/-1/lib/arm/libcocos2dlua.so [armeabi-v7a]
--
2 #01 pc 018a1cd8 /data/app/-1/lib/arm/libcocos2dlua.so (std::_Rb_tree_iterator<cocos2d::Node*> std::_Rb_tree<cocos2d::Node*, cocos2d::Node*, std::_Identity<cocos2d::Node*>, std::less<cocos2d::Node*>, std::allocator<cocos2d::Node*> >::_M_insert_<cocos2d::Node* const&>(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, cocos2d::Node* const&&&)+240) [armeabi-v7a]
3 #02 pc 0189cc3c /data/app/-1/lib/arm/libcocos2dlua.so (std::pair<std::_Rb_tree_iterator<cocos2d::Node*>, bool> std::_Rb_tree<cocos2d::Node*, cocos2d::Node*, std::_Identity<cocos2d::Node*>, std::less<cocos2d::Node*>, std::allocator<cocos2d::Node*> >::_M_insert_unique<cocos2d::Node* const&>(cocos2d::Node* const&&&)+128) [armeabi-v7a]
4 #03 pc 01899474 /data/app/-1/lib/arm/libcocos2dlua.so (std::set<cocos2d::Node*, std::less<cocos2d::Node*>, std::allocator<cocos2d::Node*> >::insert(cocos2d::Node* const&)+68) [armeabi-v7a]
5 #04 pc 0189693c /data/app/1/lib/arm/libcocos2dlua.so (cocos2d::EventDispatcher::setDirtyForNode(cocos2d::Node*)+160) [armeabi-v7a]
6 #05 pc 018969b0 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::EventDispatcher::setDirtyForNode(cocos2d::Node*)+276) [armeabi-v7a]
7 #06 pc 018969b0 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::EventDispatcher::setDirtyForNode(cocos2d::Node*)+276) [armeabi-v7a]
8 #07 pc 017908b0 /data/app/1/lib/arm/libcocos2dlua.so (cocos2d::Node::sortAllChildren()+76) [armeabi-v7a]
9 #08 pc 01790e04 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+236) [armeabi-v7a]
10 #09 pc 01235ea0 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::ui::Layout::stencilClippingVisit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+1576) [armeabi-v7a]
11 #10 pc 01235834 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::ui::Layout::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+168) [armeabi-v7a]
12 #11 pc 01790f5c /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+580) [armeabi-v7a]
13 #12 pc 01790f5c /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+580) [armeabi-v7a]
14 #13 pc 017bce84 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::Scene::render(cocos2d::Renderer*, cocos2d::Mat4 const*, cocos2d::Mat4 const*, unsigned int)+700) [armeabi-v7a]
15 #14 pc 017bcbbc /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::Scene::render(cocos2d::Renderer*, cocos2d::Mat4 const&, cocos2d::Mat4 const*)+68) [armeabi-v7a]
16 #15 pc 01841a48 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::GLView::renderScene(cocos2d::Scene*, cocos2d::Renderer*)+472) [armeabi-v7a]
17 #16 pc 018857cc /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::Director::drawScene()+344) [armeabi-v7a]
18 #17 pc 0188a020 /data/app/-1/lib/arm/libcocos2dlua.so (cocos2d::Director::mainLoop()+124) [armeabi-v7a]
19 #18 pc 00a3ec1b /data/app/-1/lib/arm/libcocos2dlua.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeRender+18) [armeabi-v7a]
，有的是在addChild的时候报这种错。
