### ISSUE TITLE
renderTexture->saveToFile() bugged for image alpha values

### ISSUE THREAD

**Issue by hotcoco11** [cocos2d/cocos2d-x#18193]
- cocos2d-x version: 3.15.1
- devices test on: Windows

Steps to Reproduce:

Take any image that has transparent pixels in it and try to save it as a png using renderTexture. The transparent pixels will get added with the background color of the renderTexture despite setting the background's alpha channel to zero with clear(0,0,0,0). Below is the code I used:

```
auto sprite = Sprite::create("original.png");
auto renderTexture = RenderTexture::create(64, 64, Texture2D::PixelFormat::RGBA8888);
renderTexture->clear(0,0,0,0);
renderTexture->begin();
sprite->setAnchorPoint(Vec2(0, 0));
sprite->setPosition(Vec2(0,0));
sprite->visit();
renderTexture->end();
renderTexture->saveToFile("rendertexture.png", Image::Format::PNG);
```
So in the above case because I cleared with rgba(0,0,0,0), my transparent pixels will end up being darker. One would assume that having an alpha of zero shouldn't change the image at all.

I posted an example image on the forums:
[http://discuss.cocos2d-x.org/t/rendertexture-savetofile-bugged-for-image-alpha-values/38810](url)

**Comment by Anywhere-Music-Player** [comment]
@minggo I've reproduced this bug in the latest cocos.

**Comment by Anywhere-Music-Player** [comment]
Also http://discuss.cocos2d-x.org/t/rendertexture-savetofile-artifacts/38787/6

**Comment by Anywhere-Music-Player** [comment]
Hey @minggo currently I'm start using RenderTexture in my game and it's really broken. 
It's renders that artefacts to my image. Thats really like urgent, because for other people RenderTexture is really used component. 
Just take code and images to test from [this post](http://discuss.cocos2d-x.org/t/rendertexture-savetofile-artifacts/38787/6)

**Comment by KAMIKAZEUA** [comment]
@minggo any news?

**Comment by KAMIKAZEUA** [comment]
@hotcoco11 can you re-attach bugged image? It's lost on the forum..

**Comment by Anywhere-Music-Player** [comment]
@minggo 

Just want to assume this bug and add something.

For image: 
![1](https://user-images.githubusercontent.com/3391456/33527146-2a727410-d854-11e7-8409-8a4ac64c797f.png)

Use code: 

Create a simple HelloWorld project add transparent image bellow and add this code. 
```
auto sprite = Sprite::create("1.png");
sprite->setPosition(Vec2(visibleSize.width * 0.5, visibleSize.height * 0.5));
addChild(sprite);
    
auto render = RenderTexture::create(visibleSize.width, visibleSize.height);
render->begin();
visit();
render->end();
render->saveToFile("rendered.png");
```

I have this scene: 

![sceme](https://user-images.githubusercontent.com/3391456/33527152-5c03e52c-d854-11e7-84e3-7c717500a0d0.png)

Result rendered image of this scene: 

![rendered](https://user-images.githubusercontent.com/3391456/33527160-7e8e0afa-d854-11e7-873e-668a379baa2f.png)

Take a closer look: 

![screen shot](https://user-images.githubusercontent.com/3391456/33527163-835a7bcc-d854-11e7-90b7-33f093b4479f.png)

Notice that not only transparent image but text has some artefacts. 

Even more: 

Add this code on top of code posted before: 

```
auto gradient = LayerGradient::create(Color4B(100, 250, 100, 255.0), Color4B(5, 5, 5, 0.0));
gradient->setContentSize(visibleSize);
addChild(gradient);
```

Result of rendered image compare to actual scene with gradient: 

Left - rendered. Right - actual scene. 

![screen shot 1](https://user-images.githubusercontent.com/3391456/33527197-1a1a5834-d855-11e7-802d-9479e2c01608.png)

Notice - rendered gradient is different than actual saved file.

It’s like has some transparency where it should’t have. Top of gradient isn’t transparent, but on rendered image - it’s transparent: 

![screen shot](https://user-images.githubusercontent.com/3391456/33527329-5f0d9878-d857-11e7-8765-86810ed67852.png)

**Comment by minggo** [comment]
it is in my task list, i will take a look after fixing some other issues

**Comment by Anywhere-Music-Player** [comment]
Thats just currently deal breaker for me. Before that, I've found way to not use RenderTexture in my game. But currently I have situation where I can't not to use it, but it's broken.

**Comment by minggo** [comment]
The default blend function of Sprite is BlendFunc::ALPHA_NON_PREMULTIPLIED, which will blend with background. So you should change the blend function before visit, such as 
```

auto sprite = Sprite::create("original.png");
auto renderTexture = RenderTexture::create(64, 64, Texture2D::PixelFormat::RGBA8888);
renderTexture->clear(0,0,0,0);
renderTexture->begin();
sprite->setAnchorPoint(Vec2(0, 0));
sprite->setPosition(Vec2(0,0));
sprite->setBlendFunc({GL_ONE, GL_ZERO});   ---》 change the blend function
sprite->visit();
renderTexture->end();
renderTexture->saveToFile("rendertexture.png", Image::Format::PNG);
```

And you may change to default blend function after rendering into render texture. Because `saveToFile` is finished in next frame, so you'd better change to use original blend function in the call back of `saveToFile`.

**Comment by Anywhere-Music-Player** [comment]
@minggo  If I have a design in my game so I can't change `sprite->setBlendFunc`? 

Just simple fact: I’m using RenderTexture for some sprites and got artifacts on final image. 
I’m not sure, but in some old previous versions I haven’t faced with this problem for same situation with my same game. Other users reported, that cocos v2 has no this problem. 
Also, I can’t change blending of sprite to visit, by my game design. How to solve this? 
This is an issue.

**Comment by Anywhere-Music-Player** [comment]
@minggo any comments? I can't change `BlendFunc` before visit. Also, I'm `visit` a `Node` but not a just some single Sprite, and on my `Node` there are a lot of other objects: `LayerGradient`, `ClippingNode`, 'Sprite' s and `LayerColor` and more. Some of them have a children added.

upd: even with just tested 1 sprite with mask, I'm getting this bug. Disable blend not helped me.

**Comment by Anywhere-Music-Player** [comment]
@minggo @drelaptop this issue is not **fixed**.

Other developers faced this same problem, see details in this post:  
https://discuss.cocos2d-x.org/t/rendertexture-savetofile-bugged-for-image-alpha-values/38810/6

@minggo with `ClippingNode` your `fix` with disabling blendfunc does not work.

**Comment by minggo** [comment]
Ok, it can be another issue.

**Comment by Anywhere-Music-Player** [comment]
@minggo Yea, that’s the same problem, this issue was closed wrongly, reopen it and assign to drela.
