### ISSUE TITLE
wrong parse for lua search path

### ISSUE THREAD

**Issue by ZhouWeikuan** [cocos2d/cocos2d-x#18195]
- cocos2d-x version: latest
- devices test on: any
- developing environments
   - NDK version: any
   - Xcode version: any
   - VS version: any
   - browser type and version: any

Steps to Reproduce:

1.  in file:  cocos2d-x/cocos/scripting/lua-bindings/manual/Cocos2dxLuaLoader.cpp
2.  at about line 80: 
         std::string prefix = searchpath.substr(begin, next);

It will parse out a wrong path for prefix,
Should replace it with: 
         std::string prefix = searchpath.substr(begin, next - begin);

parameters for C++ string.substr should be (startPos, len), but not (startPos, endPos)

**Comment by v1993** [comment]
I dont't know what are you talking about, look at git: https://github.com/cocos2d/cocos2d-x/blob/18709f38d14daf9c30c1eb382367ea9983c6347a/cocos/scripting/lua-bindings/manual/Cocos2dxLuaLoader.cpp#L76

**Comment by ZhouWeikuan** [comment]
Checked.
It is in version 3.15.1/3.16,  you 've just fixed it 5 days ago?
 look #18171
Should be a dup.

**Comment by v1993** [comment]
I think that `cocos2d-x version: latest` means `git version`. So my pull request already fixed it. Also, just for interest, you can check related question on stack owerflow: https://stackoverflow.com/q/45713055/5697743. You can close this issue, it is related to `next` milestone.

**Comment by ZhouWeikuan** [comment]
OK, thanks!
