### ISSUE TITLE
3.15.1 setEndListener doesn't work any more.

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#18201]
- cocos2d-x version:3.15.1
- devices test on: android & ios native app
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

 var hero =  sp.SkeletonAnimation.createWithJsonFile(_self.res.anim.dd.spine_json, _self.res.anim.dd.spine_atlas, 0.18);
hero.anchorX = 0.5;
hero.anchorY = 0;
hero.setTimeScale(_self.roleAnimSpeed);
hero.setAnimation(0, "jump", false);
hero.setEndListener(function (animIndex) {
  //this callback can not work....
  
   
});

**Comment by liuyi** [comment]
Maybe I fixed this ：
Modified file:AnimationState.c
spTrackEntry* _spAnimationState_trackEntry (spAnimationState* self, int trackIndex, spAnimation* animation, int /*boolean*/ loop, spTrackEntry* last) {
	spTrackEntry* entry = NEW(spTrackEntry);
	entry->trackIndex = trackIndex;
	entry->animation = animation;
	entry->loop = loop;

	entry->eventThreshold = 0;
	entry->attachmentThreshold = 0;
	entry->drawOrderThreshold = 0;

	entry->animationStart = 0;
	entry->animationEnd = animation->duration;
	entry->animationLast = -1;
	entry->nextAnimationLast = -1;

	entry->delay = 0;
	entry->trackTime = 0;
	entry->trackLast = -1;
	entry->nextTrackLast = -1;
    entry->trackEnd = (loop==0)?animation->duration:(float)INT_MAX;//(float)INT_MAX; //修改了这一行 
	entry->timeScale = 1;

	entry->alpha = 1;
	entry->mixAlpha = 1;
	entry->mixTime = 0;
	entry->mixDuration = !last ? 0 : spAnimationStateData_getMix(self->data, last->animation, animation);
	return entry;
}

**Comment by minggo** [comment]
i think you can send a PR to spine runtime, according spine's license, cocos2d-x can not modify the codes.
