### ISSUE TITLE
webview渲染有问题，如果后面有骨骼动画会一直闪屏

### ISSUE THREAD

**Issue by continuemycoding** [cocos2d/cocos2d-x#18261]

**Comment by gdboy** [comment]
@dumganhar

**Comment by minggo** [comment]
please use english to create a new one, thanks

**Comment by gdboy** [comment]
@minggo 问题没解决为什么关闭了？没用英语cocos官方人员看不懂？中国人交流一定要这么浮夸？

**Comment by minggo** [comment]
cocos不单是我们开发的，全世界的开发者共同维护的。如果每个开发者用自己的语言，那还怎么维护？如果你一定要用中文，可以到中文论坛: http://forum.cocos.com/。另外你可以用google translate来翻译成英文。请尊重非中文国家的开发者。谢谢。

cocos not only we developed, the world's developers to maintain the common. If each developer with their own language, then how to maintain? If you have to use Chinese, you can go to the Chinese forum: http://forum.cocos.com/. In addition you can use google translation to translate into English. Please respect non-Chinese country developers. Thank you.

**Comment by gdboy** [comment]
@minggo 不伦不类的翻译我很难受，你喜欢英文你可以用英文来回复，我只希望你们能重视提出的bug，而不要纠结于语言，别人肯定不会用法语、德语、俄语之类的语言来和你们交流，这点你们可以放心。

**Comment by gdboy** [comment]
@minggo 提在这里你们都基本没重视，你让我提到中文论坛，那不是更石沉大海？

**Comment by dumganhar** [comment]
@pandamicro

**Comment by pandamicro** [comment]
Hi, @gdboy WebView on web is a simple iframe on the same page, you can access to the iframe element by `webview._renderCmd._iframe`, I suppose you are facing some browser related bugs, normally, you can adjust the iframe's css to get things right. Please give it a try.

By the way, can you share the device, browser, browser version informations.

**Comment by minggo** [comment]
@gdboy you can use Chinese but you should paste the corresponding english(may be translated by google translate) too for other developers to join it. Thanks.
