### ISSUE TITLE
File Reading on UI Thread

### ISSUE THREAD

**Issue by shaniamjad** [cocos2d/cocos2d-x#18277]
- cocos2d-x version: cocos2d-x-3.15.1
- devices test on: Samsung Galaxy S7
Steps to Reproduce:
Enabled StrictMode to investigate Possible ANR investigation on my game and got this violation in logcat. I am attaching the text file containing the Stack traces of all violations. These operations might leads to an ANR on android devices. so it would be great if these can be fixed? Thanks

Enabled Strictmode using this code from AppActivity:
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
.detectAll()
.penaltyLog()
.build());

[StrictMode-Logs.txt](https://github.com/cocos2d/cocos2d-x/files/1306010/StrictMode-Logs.txt)

**Comment by shaniamjad** [comment]
@minggo Can you please give it a look.. There are many violations inside cocos2dx.. Which may leads to ANR and right now our game is suffering from ANR's

**Comment by minggo** [comment]
```
Enabled Strictmode using this code from AppActivity:
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
.detectAll()
.penaltyLog()
.build());
```
Could you please describe it in more detail?

**Comment by shaniamjad** [comment]
Kindly paste this code it on onCreate method of AppActivity class and this code tells us on Logcat if we are doing any I/O operation on UIThread which is a violation on Android platform and this may leads to an ANR. 
In the Logcat you can see violations logs similar to the one i have shared in the file. There are many violations i have noticed inside Cocos2dxActivity.java and Cocos2dxHelper.java. Which needs to be fixed. Let me know if still anything unclear so i could explain more.

**Comment by minggo** [comment]
Thanks for the information. I will take a look ASAP.

**Comment by minggo** [comment]
It seems all violations are cause in `Cocos2dxActivity.onCreate()`.

**Comment by minggo** [comment]
`and right now our game is suffering from ANR's` does your game meet ANR at startup?

**Comment by shaniamjad** [comment]
Correct, All violations noted on Cocos2dxActivity.onCreate(). By Looking at the ANR's its not really clear when this ANR is occurring.. but it does tell that an I/O operation is causing this. Which i found using this method. So i suspect that might be causing on some devices.

**Comment by minggo** [comment]
I will fix violations as possible, but i am not sure i can fix all, because some codes are sequence dependent.

**Comment by shaniamjad** [comment]
Thanks @minggo Your best is enough for me.

**Comment by minggo** [comment]
I fixed some violations in https://github.com/cocos2d/cocos2d-x/pull/18309, there are two violations i can not fix:

- Activity.onCreate()
`Cocos2dxActivity.onCreate()` will invoke `Activity.onCreate()`, and Activity.onCreate() has violation, i have not idea how to fix it.
- loading .so file
`Cocos2dxActivity.onCreate()` will invoke `Cocos2dxActivity.onLoadNativeLibraries()` to load .so files. It is needed for later codes, should be loaded first.

**Comment by minggo** [comment]
And @dumganhar has a suggestion that, can load libraries in static field, such as
```java
public abstract class Cocos2dxActivity extends Activity implements Cocos2dxHelperListener {
    static {
        // should change to use real .so name, it is just a sample
        System.loadLibrary("cpp_empty_test");
    }
}
```
Then all violations are fixed. But cocos2d-x can not use this method, because engine doesn't know the real `.so` name, should get the name dynamically. I put it here just for some developer that want to fix all violations. You can use this method because you know the real .so name.

**Comment by shaniamjad** [comment]
Thanks alot @minggo I will integrate them into out game asap.

**Comment by minggo** [comment]
Sounds good, could you please let me know if it works.

**Comment by shaniamjad** [comment]
Sure. Will confirm on this thread after integration.

**Comment by shaniamjad** [comment]
Sorry for the late update.. I have integrated the changes and it removed most of the violations. I hope that now i see less ANR's in my game. Thanks @minggo and @dumganhar for your help
