### ISSUE TITLE
应用内跳转，切回来会处于半卡死状态。

### ISSUE THREAD

**Issue by wzx110113627** [cocos2d/cocos2d-x#18280]
- cocos2d-x version:3.15.1

这个版本做应用内跳转的时候，如果跳转的应用也是用cocos2d-x 开发的，那么跳回来之后，应用处于半瘫痪状态。每秒4-5帧，且所有子系统，例如动画，音频，全部都不工作。 如果跳转的是其他非2dx应用，就没有问题.

**Comment by yiyang-tang** [comment]
Android or iOS?

**Comment by tangyiyang** [comment]
Android or iOS ?
可以多给一些细节么。

**Comment by minggo** [comment]
Please use english, at least you should paste google translate result with Chinese.
