### ISSUE TITLE
CCProgressTimer

### ISSUE THREAD

**Issue by CodeMasterYi** [cocos2d/cocos2d-x#18379]
<= v3.16
```
void ProgressTimer::setMidpoint(const Vec2& midPoint)
{
    _midpoint = midPoint.getClampPoint(Vec2::ZERO, Vec2(1, 1));
}
```

expected:
```
void ProgressTimer::setMidpoint(const Vec2& midPoint)
{
    _midpoint = midPoint;
}
```

我们该如何实现圆形进度条 用任意点作为中心（包括纹理矩形范围之外）！

**Comment by gestern** [comment]
No, generally the middle point should belong to the normalised vector (or unit vector) is a vector of length 1, so the code with ``getClampPoint()`` is correct.

**Comment by gestern** [comment]
BTW, better (to avoid hardcode) will be:
```c
void ProgressTimer::setMidpoint(const Vec2& midPoint) {
    _midpoint = midPoint.getClampPoint(Vec2::ZERO, Vec2::ONE);
}
```

**Comment by CodeMasterYi** [comment]
BUT, In this way, i must provide a full circle image, while i just want to make a fan-shaped progress~
I tried TexturePacker with trim-mode, but the actual texture rect is also trimmed~

**Comment by CodeMasterYi** [comment]
咦，这哪年的issue咋还没人处理？

**Comment by gestern** [comment]
> 咦，这哪年的issue咋还没人处理？

Honestly, I thought you caught up three years ago that you were wrong. Be that as it may, you have a chance to write your own "correct" version of this class. Typically, a programmer with 10+ years of experience takes about two days for this (including tests).

**Comment by CodeMasterYi** [comment]
Just Close It!
