### ISSUE TITLE
Build with USE_PREBUILT_LIBS:BOOL=OFF on Ubuntu Linux fails with "Could NOT find FMOD" 

### ISSUE THREAD

**Issue by cirosantilli** [cocos2d/cocos2d-x#18395]
Why I want this: overcome quirks wth prebuilt binaries, e.g. https://github.com/cocos2d/cocos2d-x/issues/18399 

Platform:

- cocos2d-x version: 0398875a22702b5c781ecb87dd8ca592e5895717
- devices test on: Ubuntu 17.04

Reproduce:

```
cmake -DUSE_PREBUILT_LIBS:BOOL=OFF
make
```

Outcome:

```
It appears you are building natively for Linux with GCC
-- OpenGL include dirs: /usr/include                       
-- GLEW include dirs: /usr/include                               
-- PkgConfig found                                         
-- GLFW3 include dirs: /usr/local/include/GLFW        
-- SQLite3 include dirs: /usr/include                
CMake Error at cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find FMOD (missing: FMOD_LIBRARIES FMOD_INCLUDE_DIRS)
Call Stack (most recent call first):                     
  cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFMOD.cmake:48 (find_package_handle_standard_args)
  cmake/Modules/CocosBuildHelpers.cmake:44 (find_package)
  cmake/Modules/BuildModules.cmake:21 (cocos_find_package)
  CMakeLists.txt:98 (BuildModules)                  
                                                              
                                                               
-- Configuring incomplete, errors occurred!                
See also "/home/ciro/git/cocos2d-x/build-make-nodep/CMakeFiles/CMakeOutput.log".
See also "/home/ciro/git/cocos2d-x/build-make-nodep/CMakeFiles/CMakeError.log".
Makefile:440: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1 
```

Expected behavior: downloads external lib source and compiles them all from scratch.

Kind of expected since FMOD is a blob, wondering if there is a way to point to FMOD but still build all other libraries from source.

**Comment by MyZeD** [comment]
Maybe it help you to copy "external/linux-specific/fmod/prebuilt/64-bit/libfmod.so" to "/usr/lib/libfmod.so" and set a Symlink to "/usr/lib/libfmod.so.6"

**Comment by drelaptop** [comment]
please check your `external/` path, did you run this script `download-deps.py`?

if cmake found fmod success in `external/` path, it won't execute `FindFMOD.cmake` script.

**Comment by cirosantilli** [comment]
Sorry, I can't work on this at the moment, I'll close for now and reopen if I get back to it.

**Comment by jiaojianhua** [comment]
Hi Ciro,

Please change your mail name, it will hurt this maillist.

**Comment by cirosantilli** [comment]
@jiaojianhua does it show somewhere public or just on your private mailbox?

If admins explicitly tell me to change it, I will start contributing with a separate account.

I'm not actively working on this anymore in any case.
