### ISSUE TITLE
Android.mk is not self-contained

### ISSUE THREAD

**Issue by rynkowsg** [cocos2d/cocos2d-x#18392]
VERSION
---------
v3

PROBLEM
----------

From the perspective of a developer that link his target with
`cocos2dx_static` library, it should specify in his `Android.mk` only
a path to a makefile that defines that module, by

a) using `import-add-path` and `import-module`

    $(call import-add-path, <path-to-cocos-root>)
    $(call import-module, cocos)

  or ...

b) using directly an `include` command

    include <path-to-cocos-root>/cocos/Android.mk

Unfortunately the current configuration of cocos' Android.mk doesn't
specify (using `import-add-path`) locations of modules that it uses.
In result, every dev that uses cocos to create Android app has to
populate NDK_MODULE_PATH at his Android.mk files by adding two lines:

    $(call import-add-path, <path-to-cocos-root>/cocos)
    $(call import-add-path, <path-to-cocos-root>/external)

Those lines have to be placed at cocos/Android.mk file.

The current configuration of build script breaks a good practice of
hiding internal details from clients of library or component. In fact
the script exposes internal dependencies and require from a dev to make
them out.

---

Steps to Reproduce:

1. Generate cocos2d-x app.
2. Use in Android app the `cocos2dx_static` library by importing it's definition in one of described above ways.
3. You will get a build script issue like:

        Android NDK: jni/../../cocos2d/cocos/Android.mk: Cannot find module with tag 'freetype2/prebuilt/android' in import path
        Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?

**Comment by minggo** [comment]
`path-to-cocos-root` is added into NDK_MODULE_PATH by default in cocos command. And i still don't understand how to reproduce the issue.

**Comment by rynkowsg** [comment]
@minggo yep, that proofs what I said. `cocos` command sets `NDK_MODULE_PATH` to provide paths for cocos modules. Problem is that everyone who doesn't use `cocos` command, had to provide the missing paths for modules imported inside of `cocos/Android.mk` in his mk files, by adding lines like:

    $(call import-add-path, <path-to-cocos-root>/cocos)
    $(call import-add-path, <path-to-cocos-root>/external)

_(actually in cocos templates, as I checked just now, you also add the above commands, probably to support Android Studio integration)_

Very sorry if my previous description how to reproduce was not clear.

1. Create an example cocos project.

2. Go to Android.mk file of your project and check:
 
    - that you are linking with cocos lib (`cocos2dx_static` must be set at `LOCAL_STATIC_LIBRARIES`)
    - you are importing information about `cocos2dx_static` target by one of two below ways:
 
        a) 

            $(call import-add-path, <path-to-cocos-root>)
            $(call import-module, cocos)

        b) _(equivalent of the previous one)_

            include <path-to-cocos-root>/cocos/Android.mk

    - you don't have below commands in your makefile

           $(call import-add-path, <path-to-cocos-root>/cocos)
           $(call import-add-path, <path-to-cocos-root>/external)

 3. Try to compile using ndk-build whithout specifying those paths from command line.

---

I understand that `cocos` command might be a recommended way of compiling cocos Android projects, but many members of community prefer to do it through `ndk-build` or `gradle` integration. While `cocos` command might be a very good tool, it should not contain build details like populating `NDK_MODULE_PATH`. Android Studio that integrates by gradle with ndk-build, doesn't use `cocos` command. In result, probably every Android project that uses cocos and Android Studio had to have in its `Android.mk` additional `import-add-path` commands or additional gradle code to set NDK_MODULE_PATH.

---

I briefly checked and it looks that you are setting `NDK_MODULE_PATH` manually in three different places:

- in cocos command: https://github.com/cocos2d/cocos2d-console/blob/v3/plugins/plugin_compile/build_android.py#L337
- in build.gradle files: https://github.com/cocos2d/cocos2d-x/blob/cocos2d-x-3.16/templates/cpp-template-default/proj.android-studio/app/build.gradle#L24
- in Android.mk files: https://github.com/cocos2d/cocos2d-x/blob/v3/templates/cpp-template-default/proj.android-studio/app/jni/Android.mk#L6

Obviously, if the location of imported modules in `cocos/Android.mk` have been specified in that file, adding paths manually in all above places would not been needed.

If something is needed in `cocos/Android.mk`, it should be also hidden there. What we have now, is that that problem is fixed everywhere, but not in the place it should be - in `cocos/Android.mk`. 

If it still not clear enough, send me an e-mail and we can schedule a video call to talk about it. After merging this change, I can also help with correcting all places that had been affected by this mistake.

**Comment by minggo** [comment]
Thanks for explanation, sounds reasonable. And i will modify the places you mentioned above after merging the PR.

**Comment by minggo** [comment]
> Obviously, if the location of imported modules in cocos/Android.mk have been specified in that file, adding paths manually in all above places would not been needed.

Then how can you import `cocos/Android.mk` in your app?

**Comment by minggo** [comment]
I got it, should add `$(call import-add-path, xxx)` to the app to import it.

**Comment by minggo** [comment]
I have sent https://github.com/cocos2d/cocos2d-x/pull/18405 to remove setting of NDK_MODULE_PATH.

**Comment by rynkowsg** [comment]
> Then how can you import cocos/Android.mk in your app?

> I got it, should add $(call import-add-path, xxx) to the app to import it.

Yep, I think you got it 👍 

Just to be clear. If someone wanted to use cocos library in his Android.mk, there are two ways of doing it:

* by using `include` command directly:

        include <cocos-root>/cocos/Android.mk

* or by using NDK commands `import-add-path` and `import-module`

        $(call import-add-path, <cocos-root>)
        $(call import-module, cocos)

The second approach is a "nicer" way of what we have in the first approach. 'cocos' passed to the `import-module` command is a directory name, where NDK is looking for `Android.mk` makefile.


Obviously, as I described earlier, currently anyone who want to use cocos2d lib, has to set somehow NDK_MODULE_PATH with `<cocos-root>/cocos` and `<cocos-root>/external` (by passing a define to `ndk-build` call or by adding in his makefile additional `import-add-path` commands with those paths) :)

**Comment by minggo** [comment]
yep, but it may meet issue in travis building. In travis building, Android projects shares `built .obj files` files to speed up building speed, or it may timeout issue. Can refer to [the codes](https://github.com/cocos2d/cocos2d-x/blob/v3/tools/travis-scripts/run-script.sh#L61) for detail info.

After using `$(call import-add-path, <cocos-root>)`, cpp project can not share `built .obj files` because the relative path to `cocos2d-x root` is different, so it will meet timeout issue again.

**Comment by rynkowsg** [comment]
I think I don't understand the problem here. I don't see any reason why command `import-add-path` would affect the location of obj/ directories.  
Can you send me a link to the problematic build log?

**Comment by minggo** [comment]
No problem, i fixed it.
