### ISSUE TITLE
Incorrect sprite with etc + alpha texture rendering.

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#18408]
- cocos2d-x version: 3.16
- devices test on: any
- developing environments: any

Steps to Reproduce:

1. Create sprite with normal texture.
2. Change sprite texture through `setTexture` to etc texture with additional alpha texture.
Result sprite will be rendered without alpha channel.

Problem is in 
`
if(_glProgramState == nullptr)
{
setGLProgramState(GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_NO_MVP, texture));
}
`

**Comment by tangyiyang** [comment]
It breaks with this issue, you may consider add this line in you local repo.
https://github.com/cocos2d/cocos2d-x/pull/17938
