### ISSUE TITLE
Proposal: a new resolution & node location policy.

### ISSUE THREAD

**Issue by acrazing** [cocos2d/cocos2d-x#18401]
When I read the document, I find that the cocos2d-x only supports some scale resolution policy, it's not enough. For example:

We have a scene, it contains a square sprite, which is located at the bottom right corner, just like this:

![designed](https://user-images.githubusercontent.com/10029810/31877830-8f6a5306-b79d-11e7-93d9-5d2627cc4869.png)

And we want to:

- the scene always fills the screen, just like NO_BORDER
- the sprite always at the bottom right corner
- the sprite always to be a square

The five policy provided by cocos2d-x could not satisfy the requirements. But, we can use another policy to do this:

At first, a sprite(node) should contain the following properties:

```ts
interface NodeRect {
  width: number;
  height: number;
  x: number;
  y: number;
  originX: number;
  originY: number;
}
```

The fields `originX` and `originY` are the relative coordinate system `(0, 0)` in the world coordinate system, this maybe finished by the parent layer, but the different is the `width` and `height` must be in the same scale.

And then when scale the scene, the `originX` and `originY` should be scaled by the scene `width`, `height`, and calculate the `x`, and `y` property, and, the `width`, `height` should be calculated by the key edge scale radio, which is the `short` one if the screen `width`, `heigh`.

For example:

We design a game in the size of `320 * 240` ( width * height), and the game has a sprite at the right bottom corner, its properties like follow:

```ts
const designRect = {
  width: 100,
  height: 100,
  x: -100,
  y: 0,
  originX: 320,
  originY: 0,
}
```

- when the screen size is `640 * 480`, the sprite should be render at(the parent coordinate system):
  ```ts
  const renderRect = {
    width: 200,
    height: 200,
    parentX: 280,
    parentY: 0,
  }
  ```
- when the screen size is `640 * 500`(*shorter* than the design resolution), the sprite's properties is:
  ```ts
  const renderRect = {
    width: 200,
    height: 200,
    parentX: 300,
    parentY: 0,
  }
  ```
- when the screen size is `700 * 480`(*longer* than the design resolution), the sprite's properties is:
  ```ts
  const renderRect = {
    width: 200,
    height: 200,
    parentX: 300,
    parentY: 0,
  }
  ```

In general, the formula as follow:

```ts
// global variables:
// screenWidth: the current screen width
// screenHeight: the current screen height
// designWidth: the design width
// designHeight: the design height

// the key edge scale radio
const scaleRadio = Math.min(screenWidth / designWidth, screenHeight / designHeight)

// the scaled node width
const width = designRect.width * scaleRadio

// the scaled node height
const height = designRect.height * scaleRadio

// the scaled node origin x
const originX = designRect.originX / designWidth * screenWidth

// the scaled node origin y
const originY = designRect.originY / designHeight * screenHeight

// the scaled node x relate to originX
const x = designRect.x / designRect.width * width

// the scaled node y relate to originY
const y = designRect.y / designRect.height * height

// the scaled node x, y in the world/layer coordinate system
const parentX = originX + x
const parentY = originY + y
```

The result as follow:

![designed](https://user-images.githubusercontent.com/10029810/31877844-9e4a2090-b79d-11e7-8cbc-8c363fe84384.png)

The design properties(in world coordinate system):

- scene
  - width: 320
  - height: 240
- sprite:
  - width: 100
  - height: 100
  - x: 220
  - y: 0

![scale same](https://user-images.githubusercontent.com/10029810/31877858-a7924038-b79d-11e7-934c-9a5849ac051b.png)

render in the screen `640 * 480`(normal screen):

- scene
  - width: 640
  - height: 480
- sprite:
  - width: 200
  - height: 200
  - x: 440
  - y: 0

![scale short](https://user-images.githubusercontent.com/10029810/31877869-af2095d4-b79d-11e7-819b-206ebe46ad13.png)

render in the screen `700 * 480`(short screen):

- scene
  - width: 700
  - height: 480
- sprite:
  - width: 200
  - height: 200
  - x: 500
  - y: 0

![scale long](https://user-images.githubusercontent.com/10029810/31877881-b6460010-b79d-11e7-87a0-9316177994dd.png)

render in the screen `640 * 500`(long screen):

- scene
  - width: 640
  - height: 500
- sprite:
  - width: 200
  - height: 200
  - x: 440
  - y: 0

**Comment by Priority10** [comment]
> And we want to:
> 
> the scene always fills the screen, just like NO_BORDER
> the sprite always at the bottom right corner
> the sprite always to be a square

You can do this by setting `ResolutionPolicy` to `NO_BORDER` and 
`square->setPosition(visibleOrigin.x + visibleSize.width - square->getContentSize().width/2, visibleOrigin.x + square->getContentSize().height/2);`
Or you can use constant values instead of `square->getContentSize().width/`2 and `square->getContentSize().height/2`.

I do not see a problem here.

In my opinion

- You can easily achieve the same result using the current interfaces.

- The Node class is complex enough, it is not needed to modify it without extreme necessity.

@minggo You let me tag you. This is one of those cases when I think that this is not an issue.

**Comment by minggo** [comment]
thanks @Priority10

**Comment by acrazing** [comment]
@Priority10 The `NO_BORDER` policy will resize the node with changing the ratio of its `width` and `height`, if the screen size ratio (width/height) is different to the design screen. For example:

If the design screen is `100 * 100`, and a node's size is `50 * 50`, and then, if the display screen's size is `200 * 100`, the rendered node's size will be `100 * 50`, it is not a square.

**Comment by Priority10** [comment]
@acrazing No, no, no, please test again.
In case of NO_BORDER, scaleX = scaleY. What you describe is EXACT_FIT.

http://discuss.cocos2d-x.org/t/multi-resolution-code-in-the-default-template/39445/15?u=priority10

Read after the words

> - Note
> 
> Despite the fact that this is working solution, I prefer to use design resolution.

**Comment by Priority10** [comment]
@minggo No problems. :)
