### ISSUE TITLE
Plugin-X for JS callFuncWithParam pass argument with errors

### ISSUE THREAD

**Issue by krasnorutsky** [cocos2d/cocos2d-x#18420]
When I call Plugin-X method from Javascript like this - 

        var AdCel = plugin.PluginManager.getInstance().loadPlugin("AdCelSDKPlugin");
        AdCel.callFuncWithParam("start", new plugin.PluginParam(plugin.PluginParam.ParamType.TypeString, "appId"), new plugin.PluginParam(plugin.PluginParam.ParamType.TypeString, "adContentType"));

- I expect to get "appId" for the first parameter and "adContentType" for the second
But in fact - both parameters have the same value - "appId" - this is because of simple bug in your source code file

jsb_pluginx_manual_protocols.cpp

which contain lines of code where you extract arguments from the function - 

```
 		uint32_t i = 1;
 		while (i < argc) {
 			JSObject *tmpObj = args.get(1).toObjectOrNull(); // BUG is here
            if (tmpObj == NULL)
                break;

            proxy = jsb_get_js_proxy(tmpObj);
 			cocos2d::plugin::PluginParam* item = (cocos2d::plugin::PluginParam*)(proxy ? proxy->ptr : NULL);
 			JS_TEST_NATIVE_OBJECT(cx, item)
 			params.push_back(item);
 			i++;
 		}
```

the bug is in the line
 			JSObject *tmpObj = args.get(1).toObjectOrNull(); // BUG is here
you always extract the first argument value for all arguments. This should be fixed so:
 			JSObject *tmpObj = args.get(i).toObjectOrNull(); // FIXED

you should use "i" instead of "1"

**Comment by minggo** [comment]
plugin-x is not maintained for years. You can use SDKBox or AnySDK.
