### ISSUE TITLE
Failed to build cocos2d-x on x86 due to cmake error: Could not find GLFW3 (missing: GLFW3_LIBRARIES GLFW3_INCLUDE_DIR)

### ISSUE THREAD

**Issue by shanshan0309** [cocos2d/cocos2d-x#18446]
I build cocos2d-x with Visual studio 2017 compiler on Windows Server 2016, but it failed with cmake error: Could not find GLFW3 (missing: GLFW3_LIBRARIES GLFW3_INCLUDE_DIR). This issue can be reproduced from v3 revision [1d356a1](https://github.com/cocos2d/cocos2d-x/commit/1d356a160a42e438083bdba81fe603d10343699b). Could you help have a look about this issue? Thanks in advance!

**Steps to Reproduce:**
1. git clone --recursive  https://github.com/cocos2d/cocos2d-x.git D:\Cocos2dx\src
2. Open a VS 2017 command prompt and browse to D:\Cocos2dx
3. mkdir build_x86 && pushd build_x86
4. cmake -G "Visual Studio 15" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src

**Actual result:**
-- GLEW include dirs: D:/Cocos2dx/src/external/win32-specific/gles/include/OGLES
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- PkgConfig not found, if you have only static glfw library, you build can fail
**CMake Error at cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find GLFW3 (missing: GLFW3_LIBRARIES GLFW3_INCLUDE_DIR)**
Call Stack (most recent call first):
  cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindGLFW3.cmake:152 (find_package_handle_standard_args)
  cmake/Modules/CocosBuildHelpers.cmake:44 (find_package)
  cmake/Modules/BuildModules.cmake:12 (cocos_find_package)
  CMakeLists.txt:98 (BuildModules)

**Comment by davidstl** [comment]
I am having the same issue. Even after installing GLFW and pointing to the proper path.
But this is not a cocos2d-x related issue. It's more to do about CMake and how to make it work on Windows with dependencies.

**Comment by drelaptop** [comment]
@davidstl did you run the script `download-deps.py`, GLFW3 is external libs, it located at `cocos2d-x\external\glfw3\prebuilt\win32`

and do you use the GitHub latest code to run the cmake on Windows? if yes, please supply the cmake print information, below is print info with `GLFW3` found:
```sh
-- COCOS2DX_ROOT_PATH:F:/cocos2d-x
-- CMAKE_MODULE_PATH:F:/cocos2d-x/cmake/Modules/
-- COCOS_EXTERNAL_DIR:F:/cocos2d-x/external
-- ENGINE_BINARY_PATH:F:/cocos2d-x/win32-build/engine
-- CMAKE_BUILD_TYPE: Debug
-- It appears you are building natively for Windows Desktop with Visual Studio C++
-- using Windows MSVC generate cocos2d-x project, MSVC_VERSION:1912 check pass
......
-- glfw3 GLFW3_INCLUDE_DIRS: F:/cocos2d-x/external/glfw3/include/win32;F:/cocos2d-x/external/glfw3/include/win32
-- glfw3 GLFW3_LIBRARIES: F:/cocos2d-x/external/glfw3/prebuilt/win32/glfw3.lib
......
-- GLFW3 include dirs: F:/cocos2d-x/external/glfw3/include/win32;F:/cocos2d-x/external/glfw3/include/win32
......
```

@shanshan0309 please use the GitHub latest code, I have tested CMake build on win32.

**Comment by drelaptop** [comment]
cmake build have supported MSVC compiler, https://github.com/cocos2d/cocos2d-x/commit/4675ee79cd134ca63c8fd258c4e8a49f14fe9639 and later commits.

please close this issue @minggo
