### ISSUE TITLE
`cocos gen-libs` specify specific libraries to build

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#18443]
From forum users:

I’m using prebuilt libs with Xcode. Work really fast and easy to use.
But when I’m updating cocos2d-x from git, each time I need to rebuild them using command:

```sh
cocos gen-libs -p ios -p mac
```

And I get on output, counting all files:
```
libcocos2d Mac.a
libjscocos2d Mac.a
libluacocos2d Mac.a
libsimulator Mac.a
libcocos2d iOS.a
libjscocos2d iOS.a
libluacocos2d iOS.a
libsimulator iOS.a
Build time for all this libs is really slow…
```
Instead I need just only 2 libs which I’m using for my game:
```
libcocos2d Mac.a
libcocos2d iOS.a
```
And I want to save a lot of wasted time for building unused libs.

Can some flag be added to achieve this? I don’t know… just specify build only libcocos2d?

**Comment by Anywhere-Music-Player** [comment]
It's not about cocos2d-x, but about console. 
Anyway notice time when I created this bug: https://github.com/cocos2d/cocos2d-console/issues/413 and now, so nobody cares.

**Comment by slackmoehrle** [comment]
Good point, there is already an issue.
