### ISSUE TITLE
cocos2dx_js template fails to copy jsprototypes.h to project folder

### ISSUE THREAD

**Issue by rboyd** [cocos2d/cocos2d-x#1844]
With a fresh checkout (d8db3037fc69bd814d3b6b5d3607448c091e7bf9)

```
git clone git://github.com/cocos2d/cocos2d-x.git
git submodule update --init
sudo ./install-templates-xcode.sh -f
```

Create new Xcode project with cocos2dx_js template

Build fails with:

/testproj/libs/javascript/spidermonkey-ios/include/jspubtd.h:14:10: 'jsprototypes.h' file not found

Copying from cocos2d-x/scripting/javascript/spidermonkey-ios/include/jsprototypes.h into project folder /testproj/libs/javascript/spidermonkey-ios/include/ results in passing build.

**Comment by dumganhar** [comment]
Hi @rboyd 
I forgot to update the xcode template after upgrading the library of spidermonkey.
Thank you for reminding this.:) I will update it and let you know ASAP.

**Comment by dumganhar** [comment]
Hey, @rboyd 
I have updated the xcode template here(https://github.com/cocos2d/cocos2d-x/pull/1845).
Could you try again?
Plz let me know whether it works now. Thanks.

**Comment by rboyd** [comment]
Thank you for the update. It works now.
