### ISSUE TITLE
Missing #include <list> in apple/AudioEngine-inl.h

### ISSUE THREAD

**Issue by glennerichall** [cocos2d/cocos2d-x#18450]
- cocos2d-x version: cocos2d-x-3.16
- devices test on: MacOS Sierra 10.12.6
- developing environments
   - Xcode version: Xcode 9.1
   - CMAKE_VERSION: 3.9.0-rc3

Missing #include <list> 

cocos2d/cocos/audio/apple/AudioEngine-inl.h:76:10: error: no type named 'list' in namespace 'std'

https://github.com/cocos2d/cocos2d-x/blob/540980ab2496362bba632b3a8ef3fc5313d5eab5/cocos/audio/apple/AudioEngine-inl.h#L76

**Comment by protito** [comment]
yes, I got this same error in cLion, why does this happen in cLion but not in xCode?

**Comment by summerinsects** [comment]
Maybe you can submit a PR to fix it

**Comment by wingyplus** [comment]
It fixed in PR https://github.com/cocos2d/cocos2d-x/pull/18452
