### ISSUE TITLE
I don't know why I should put .py all the times

### ISSUE THREAD

**Issue by sofaking41** [cocos2d/cocos2d-x#18456]
when I need to run cocos I should put '.py' at the CMD all the times... and I don't know the reason why...
 

FE) cocos.py -new

It doesn't have any problems to use cocos2d but it's a little pain in my neck

help me how can I fix this problem please

**Comment by zhishu520** [comment]
cd cocos2d-x-3.15.1
./setup.py

**Comment by sofaking41** [comment]
um.... I already installed 3.16 duhhhh should I install 3.15.1??

**Comment by slackmoehrle** [comment]
Sorry? Why is this an issue? It is a python script.

**Comment by zhishu520** [comment]
@sofaking41  no, it's my
cd cocos2d-x-3.16/tools/cocos2d-console/bin
![image](https://user-images.githubusercontent.com/8665898/32642268-a8c94e7a-c598-11e7-898b-a126ca999f78.png)
Is it still there?
i mean you maybe delete it

PS. sorry for my poor english....

**Comment by drelaptop** [comment]
@sofaking41 please check your PATH, cat ~/.bash_profile you will see something like:
```
# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/Users/.../cocos2d-x-3.16/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH
``` 
then `cd $COCOS_CONSOLE_ROOT` to see the contents

**Comment by minggo** [comment]
Close it since it is not an issue. Just a misusage.
