### ISSUE TITLE
build  status does not working

### ISSUE THREAD

**Issue by wnddpd01** [cocos2d/cocos2d-x#18455]
- cocos2d-x version:
- devices test on: Windows 10
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version: Chrome, latest

Steps to Reproduce:

Build status in README.md not working, cant connect to http://45.56.80.45:8080/job/daily-build-v3

**Comment by minggo** [comment]
I fixed it in https://github.com/cocos2d/cocos2d-x/pull/18630. Now use travis for iOS, android, linux, and mac, and use appvepor for windows.
