### ISSUE TITLE
xcpretty is a required tool to build on Mac

### ISSUE THREAD

**Issue by richardgroves** [cocos2d/cocos2d-x#18453]
- cocos2d-x version:3.16
- devices test on:N/A
- developing environments
   - NDK version:
   - Xcode version:9.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Follow instructions in README.md to start a new project
2. At line 'cocos run -p ios' the build will fail if xcpretty gem is not installed

Solution:

Add 'gem install xcpretty' to the setup process

**Comment by slackmoehrle** [comment]
Are you sure? I am not seeing this. I just tested, latest from GitHub

```
$ cocos new MyGame -p com.com.com -l cpp -d .
$ cd MyGame/proj.ios_mac/
$ cocos run -p ios

** BUILD SUCCEEDED **

Build succeed.
Deploying mode: debug
Starting application.
Using simulator: iPhone 8 Plus (11.0.1)
running: 'xcrun instruments -w "50080324-6EE5-44C1-85D5-4D93EE808BA3"'
```

**Comment by richardgroves** [comment]
On a different machine today and I can't get it to repeat the problem either. Not sure if it was a symptom of a first build failing, or the path with a space issue (although repeating that doesn't trigger it).

xcpretty is used in the build tools though, just not sure how I triggered an action that used it, as it appears to be in travis/jenkins CI routes:

Richards-MacBook-Pro:cocos2d-x-3.16 richard$ grep -i xcpretty -R *
tools/travis-scripts/run-script.sh:    xcodebuild -project $COCOS2DX_ROOT/build/cocos2d_tests.xcodeproj -scheme "build all tests Mac" -jobs $NUM_OF_CORES -arch x86_64 build | xcpretty
tools/travis-scripts/run-script.sh:    ##xcpretty has a bug, some xcodebuid fails return value would be treated as 0.
tools/travis-scripts/run-script.sh:    xcodebuild -project $COCOS2DX_ROOT/build/cocos2d_tests.xcodeproj -scheme "build all tests iOS" -jobs $NUM_OF_CORES  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" build | xcpretty
tools/jenkins-scripts/slave-scripts/framework/mac-build.sh:python tools/framework-compile/bin/gen_cocos_libs.py -c --mac | xcpretty
tools/jenkins-scripts/slave-scripts/runtime/mac-build.sh:xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" clean | xcpretty
tools/jenkins-scripts/slave-scripts/runtime/mac-build.sh:xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" build | xcpretty
tools/jenkins-scripts/slave-scripts/runtime/ios-build.sh:cocos compile -p ios -s $cocos_project_path | xcpretty
tools/jenkins-scripts/slave-scripts/runtime/ios-build.sh:# xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" clean | xcpretty
tools/jenkins-scripts/slave-scripts/runtime/ios-build.sh:# xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" build | xcpretty
tools/jenkins-scripts/slave-scripts/tests/mac-build.sh:xcodebuild -project "$COCOS2DX_ROOT"/build/cocos2d_tests.xcodeproj -scheme "build all tests Mac" clean | xcpretty
tools/jenkins-scripts/slave-scripts/tests/mac-build.sh:xcodebuild -project "$COCOS2DX_ROOT"/build/cocos2d_tests.xcodeproj -scheme "build all tests Mac" build | xcpretty
tools/jenkins-scripts/slave-scripts/tests/mac-build.sh:#xcpretty has a bug, some xcodebuid fails return value would be treated as 0.
tools/jenkins-scripts/slave-scripts/tests/ios-build.sh:xcodebuild -project "$COCOS2DX_ROOT"/build/cocos2d_tests.xcodeproj -scheme "build all tests iOS"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" clean | xcpretty
tools/jenkins-scripts/slave-scripts/tests/ios-build.sh:xcodebuild -project "$COCOS2DX_ROOT"/build/cocos2d_tests.xcodeproj -scheme "build all tests iOS"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" build | xcpretty
tools/jenkins-scripts/slave-scripts/templates/mac-build.sh:cocos compile -p mac -s $cocos_project_path | xcpretty
tools/jenkins-scripts/slave-scripts/templates/mac-build.sh:# xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" clean | xcpretty
tools/jenkins-scripts/slave-scripts/templates/mac-build.sh:# xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" build | xcpretty
tools/jenkins-scripts/slave-scripts/templates/ios-build.sh:cocos compile -p ios -s $cocos_project_path | xcpretty
tools/jenkins-scripts/slave-scripts/templates/ios-build.sh:# xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" clean | xcpretty
tools/jenkins-scripts/slave-scripts/templates/ios-build.sh:# xcodebuild -project $projectpath -target "${schemename}"  -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" build | xcpretty
Binary file tools/cocos2d-console/plugins/plugin_compile/project_compile.pyc matches
tools/cocos2d-console/plugins/plugin_compile/project_compile.py:    def append_xcpretty_if_installed(self, command):
tools/cocos2d-console/plugins/plugin_compile/project_compile.py:        if spawn.find_executable("xcpretty") == None:
tools/cocos2d-console/plugins/plugin_compile/project_compile.py:        return command + " | xcpretty"
tools/cocos2d-console/plugins/plugin_compile/project_compile.py:            command = self.append_xcpretty_if_installed(command)
tools/cocos2d-console/plugins/plugin_compile/project_compile.py:            command = self.append_xcpretty_if_installed(command)
Richards-MacBook-Pro:cocos2d-x-3.16 richard$

**Comment by richardgroves** [comment]
Back on the machine I had the problem with an after 'gem uninstall xcpretty' it fails to build again - then re-install it and all ok.

Output file attached with some spacing added so you can more easily see the commands I ran. Some noise about an Apple TV I have attached to the machine, but it doesn't seem to bother it the second time.

[cocos2d-x build issue.txt](https://github.com/cocos2d/cocos2d-x/files/1461112/cocos2d-x.build.issue.txt)

**Comment by minggo** [comment]
[The codes](https://github.com/cocos2d/cocos2d-console/blob/v3/plugins/plugin_compile/project_compile.py#L573) will find `xcpretty` but should not cause issue if it is not exist.
