### ISSUE TITLE
[Android] Build all third-party libraries with clang in ndk-r16.

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#18473]
For more detail information, plz refer to https://github.com/cocos2d/cocos2d-x/pull/18470

**Comment by dumganhar** [comment]
I doubt building SpiderMonkey by using clang will be the most difficult thing. :(

**Comment by Priority10** [comment]
@minggo Can this be closed now? :)

**Comment by minggo** [comment]
Will close it when submodule is updated to cocos2d-x.

**Comment by Priority10** [comment]
I'm sorry, probably I'm not yet too good at the structure of the engine.
I thought it was the same https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/310

**Comment by minggo** [comment]
No problem @Priority10 .
cocos2d-x depends on 3rd party bin, after updating 3rd party bin, cocos2d-x should be changed to depends on new version of 3rd party bin.

**Comment by Priority10** [comment]
I see. Thank you! )
