### ISSUE TITLE
[iOS] Provides an interface for getting SafeArea on iPhone X

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#18474]
That will be easier for developer to align UI elements by code.

**Comment by Priority10** [comment]
In the iPhone X screen coordinate system or in the Design Resolution coordinate system?

I think that the second option is more useful.
Something like getIPhoneXSafeAreaOrigin() and getIPhoneXSafeAreaSize().

But if the screen size is not equal to 2436x1125 or 1125x2436 (ie it is not the iPhone X or a copy), then the calculations will not be correct.
What should the functions return in this case? visibleOrigin and visibleSize respectively?

**Comment by 0megaD** [comment]
Whatever the function names are called, I think safeArea should always return the actual area you can draw in 'safely'.

So on phones like the iPhone X it will be the iPhone X safe area. On other phones that do not have UI / hardware overlapping the screen the full screen is the safe area.

I think it makes the most sense and also prevents us from having to do checks all the time.

`if iphoneX { this } else { that }`

**Comment by dumganhar** [comment]
@Priority10 , 
I agree with @0megaD , one interface, probably called `GLView::getSafeAreaRect` is enough.
And it should return the safe area rectangle in Design Resolution Coordinate.
If it's not a iPhone X, this interface just returns the rectangle with the same value return by `GLView::getVisibleOrigin/Size`.

**Comment by Priority10** [comment]
@0megaD @dumganhar 
Yep, guys, I meant the same, except 
1. The name that @dumganhar  suggested is much better.
2. I doubt a little about one interface. Yes it is better, and yes it is enough. But for Visible Area of Design Resolution, the engine has two interfaces (`getVisibleOrigin()` and `getVisibleSize()`). Is not it better to add two interfaces to keep the same style?

**Comment by dumganhar** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/18489

I prefer just one interface called `getSafeAreaRect`. getSafeAreaOrigin and getSafeAreaSize seem redundant.

**Comment by Priority10** [comment]
@dumganhar 
Oops, I did not notice that the engine has `GLView::getVisibleRect()`. Nice then. :)
