### ISSUE TITLE
 if (system(command.c_str()) >= 0)  xcode 9.1 编译不过 

### ISSUE THREAD

**Issue by G0561** [cocos2d/cocos2d-x#18484]
- cocos2d-x version: cocos316
- devices test on: iphone6s
- developing environments
   - NDK version:
   - Xcode version: 9.1
   - VS version:
   - browser type and version:

Steps to Reproduce:
cocos2dx316\cocos\platform\CCFileUtils.cpp
xcode 9.1 编译,发现  if (system(command.c_str()) >= 0) 提示system 在ios系统不存在

**Comment by dumganhar** [comment]
There will not be any problem from v3.15.
If you upgrade your project from old version, please refer to the patch.
https://github.com/cocos2d/cocos2d-x/pull/17921
