### ISSUE TITLE
How can I use CREATE_FUNC(Box2DTest)?

### ISSUE THREAD

**Issue by sofaking41** [cocos2d/cocos2d-x#18497]
- cocos2d-x version: 3.16
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: 2015
   - browser type and version:

Steps to Reproduce:
in the Box2dTest.h there is a function which name is CREATE_FUNC(Box2DTest).

But I don't know how to use this function cuz there is no this function's define...

I'm not that clever so I can't deal with it if there's no description.

**Comment by Priority10** [comment]
Firstly, this is not a function, it is a macro. See
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/CCPlatformMacros.h

Secondly, this is not an issue. Stop using github for such questions.
This issue must be closed.

@minggo  @dumganhar  Why do you have 1100+ issues? Many of the issues are either out of date (like crash on android 2.3.6), or like this one. Do you like it, seriously?

**Comment by minggo** [comment]
No, i don't like it, i am just busy with other things.

**Comment by Priority10** [comment]
OK. How can the situation be improved and/or when?

Can I tag you if I think that an issue is not correct or outdated?

How about a large number of PRs?

If you answer like
Our company does not care about it, then ok, then I have no more questions. :)

**Comment by minggo** [comment]
> Can I tag you if I think that an issue is not correct or outdated?

You are appreciated if you can help to do it.

**Comment by Priority10** [comment]
OK, I'll do it when I have a minute.
