### ISSUE TITLE
add google mirror in build.gradle file 

### ISSUE THREAD

**Issue by giangm9** [cocos2d/cocos2d-x#18507]
-- cocos2d-x version:
cocos2d-x-3.16
Cocos Console 2.3

- devices test on: Android
- developing environments
   - NDK version: android-ndk-r16
   - Xcode version: none
   - VS version: none
   - browser type and version: none
i build cocos to android, use android-studio project, android-platforms-tool 25
ubuntu 17.10
Steps to Reproduce:

1.  `cocos compile -p android --android-studio`
2. Resource missing. [HTTP GET: https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom]
3. I changed my `build.gradle` to this
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    google()
    jcenter()
    mavenCentral()
    maven {
      url "https://maven.google.com"
    }

  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.0.1'

      // NOTE: Do not place your application dependencies here; they belong
      // in the individual module build.gradle files
  }
}

allprojects {
  repositories {
    google()
    jcenter()
    mavenCentral()
    maven {
      url "https://maven.google.com"
    }
  }
}
```
and it build successfuly

**Comment by madebymozart** [comment]
This is addressed in this PR slated for 3.17 (https://github.com/cocos2d/cocos2d-x/pull/18470)

**Comment by Priority10** [comment]
@mozartalouis Do you think this issue should be closed?

**Comment by madebymozart** [comment]
It should
