### ISSUE TITLE
TrianglesCommand hashing technique doesn't take padding into account

### ISSUE THREAD

**Issue by Jakz** [cocos2d/cocos2d-x#18538]
Material hashing in `TrianglesCommand` was modified some commits ago to use directly the pointer of the `GLProgramState` instead that the identifier of its program, now it's the following:

```
struct {
  GLuint textureId;
  GLenum blendSrc;
  GLenum blendDst;
  void* glProgramState;
} hashMe;
```
This, on x64 platforms may lead to 4 byes of padding because `alignof(hashMe) == 8`. This also implies that

    _materialID = XXH32((const void*)&hashMe, sizeof(hashMe), 0);

will hash uninitialized garbage data contained into padding thus generating different hashes for same materials.

There are multiple way to fix the problem but I don't know which one could be preferred.

### Memsetting the struct before initializing

Simple as said:

    std::memset(&hashMe, 0, sizeof(hashMe));
    hashMe.textureId = _textureID;
    hashMe.blendSrc = _blendType.src;
    ....

This solves the problem because padding is always initialized to 0 but you waste some CPU cycles to compute the hash of 4 more bytes.

### Pack the structure

We could use `__attribute__((packed)` (or `#pragma pack`) to remove padding from the structure, which can verified with a static_assert eg `static_assert(sizeof(void*)+sizeof(GLuint)+sizeof(GLenum)+sizeof(GLenum) == sizeof(material_hash_t), "")`. Moving the `void*` field to the beginning would be a good idea since there are more chances it's already aligned to 8 bytes in case. 

### Use a byte array

Just messy I guess:

    uint8_t hashMe[sizeof(GLuint)*2 + sizeof(GLenum) + sizeof(void*));
    std::memcpy(hashMe, &_glProgramState, sizeof(void*));
    std::memcpy(hashMe + sizeof(void*), &_blendType.src, sizeof(GLenum));
    ....

### Offseting the hash calculation

We can calculate xxhash only on significant bytes, eg:

    constexpr size_t offset = offsetof(decltype(hashMe), textureId);
    constexpr size_t length = offsetof(delctype(hashMe), glProgramState) + sizeof(void*);
    XXH32(&hashMe + offset, length, 0);

of course this requires to have padding only at beginning or end of the structure.

**Comment by dumganhar** [comment]
Good finding.
I prefer:
> Moving the void* field to the beginning would be a good idea since there are more chances it's already aligned to 8 bytes in case.

But that would not resolve the problem too, because

```c++
struct {
    void* glProgramState; // 8
    GLuint textureId; // 4
    GLenum blendSrc; // 4
    GLenum blendDst; // 4
// there are also padding 4 here.
} hashMe;
```

will also make a padding 4 at the end of struct. It's caused by the struct size have to be multiplied by 8, it means it's also 24 bytes with 4 padding bytes.

I provide another approach:

### Uses Constructor to Reset Struct

```c++
struct hashMe {
    hashMe() {
        memset(this, 0, sizeof(*this));
    }
    void* glProgramState; // 8
    GLuint textureId; // 4
    GLenum blendSrc; // 4
    GLenum blendDst; // 4
// there are also padding 4 here.
};
```

**Comment by dumganhar** [comment]
I found that hashMe is a private struct.
So probably, call memset after its definition is also ok.
```c++
    struct {
        void* glProgramState; // Change order there.
        GLuint textureId;
        GLenum blendSrc;
        GLenum blendDst;
    } hashMe;
    memset(&hashMe, 0, sizeof(*hashMe)); // add this line here
    hashMe.textureId = _textureID;
    hashMe.blendSrc = _blendType.src;
    hashMe.blendDst = _blendType.dst;
    hashMe.glProgramState = _glProgramState;
    _materialID = XXH32((const void*)&hashMe, sizeof(hashMe), 0);
```

**Comment by dumganhar** [comment]
Pull Request is here: 
https://github.com/cocos2d/cocos2d-x/pull/18543

**Comment by Jakz** [comment]
Yes, using `std::memset` is definitely fine but you waste computing hash on 4 more bytes, which could be negligible but it's nice to point it out.
