### ISSUE TITLE
SSL certificate expired on cocos2d-x.org

### ISSUE THREAD

**Issue by yaakov-h** [cocos2d/cocos2d-x#18530]
The SSL certificate on cocos2d-x.org has expired.

This is breaking the Microsoft Visual Studio installer.

Visual Studio Installer attempts too download the following file: `https://go.microsoft.com/fwlink/?linkid=854219`

This is a redirect to `https://cocos2d-x.org/filedown/CocosCreator_v1.5.2_win`.

This URL fails to load in the Installer and all web browsers, as SSL certificate on cocos2d-x.org is only valid until ‎`Saturday, ‎2 ‎December ‎2017 10:59:59 AM`, which is now in the past.

**Comment by Priority10** [comment]
This issue has already been reported.
http://discuss.cocos2d-x.org/t/cocos2d-x-website-certificate/40318

Thanks!
Could you close this issue now because it is not a cocos2d-x issue?

**Comment by TurnOffNOD** [comment]
@Priority10 Hi, the SSL certificate on cocos2d-x.org expires again.
And excuse me for disturbing here, I don't have an account on discuss.cocos2d-x.org.

**Comment by minggo** [comment]
@TurnOffNOD thanks, you can create an account to report it in future.
