### ISSUE TITLE
New cocos project android binding messed up

### ISSUE THREAD

**Issue by madebymozart** [cocos2d/cocos2d-x#18546]
Probably by mistake, but in removing the old android code using ant, the auto renaming and things in android are messed up and doesn't change the package names in `build.gradle` and other files.

- cocos2d-x version: latest github commit
- devices test on: N/A
- developing environments
   - NDK version: N/A
   - Xcode version: N/A
   - VS version: N/A
   - browser type and version: N/A

Steps to Reproduce:
1. Checkout latest version of cocos2d-x on github & set it up
2. run ```cocos new Mygame -l cpp -p com.example.mygame```

### Screenshots
![screen shot 2017-12-10 at 3 05 19 am](https://user-images.githubusercontent.com/5649571/33803177-60a22a6e-dd57-11e7-9649-e62a4e4e599b.png)

![screen shot 2017-12-10 at 3 10 11 am](https://user-images.githubusercontent.com/5649571/33803200-ba46a9b4-dd57-11e7-81e1-2e78ba14afbb.png)

**Comment by formatCvt** [comment]
confirm bug

> cocos2d-x-3.17
> Cocos Console 2.3

**Comment by stevetranby** [comment]
I think you can just remove all yellows from template, but someone should confirm.
`tools/cocos2d-console/plugins/plugin_generate/bin-templates/cpp-template-default/cocos-project-template.json`

When I do a grep within a `cocos new` root folder I find 8 occurrences of 'HelloCpp' in 6 files.
One of those files is the CMakeList.txt, which should probably also get replacement, but the rest are the 5 files shown in green in your screenshot.

**Comment by drelaptop** [comment]
@mozartalouis this have been fixed when cocos2d-x 3.17 release, you can test it by cocos2d-x-3.17 tag
