### ISSUE TITLE
Request for plans about color emoji suport.

### ISSUE THREAD

**Issue by sbrednikhin** [cocos2d/cocos2d-x#18550]
Are there any plans to support color emoiji's? Is it in some roadmap?

**Comment by drelaptop** [comment]
Please run cpp-tests project, and see `51:Node: UI` -> `1:GUI Dynamic Create Test` -> `1:UIEditBox Test`. 

Color emoji have been supported in EditBox.

**Comment by sbrednikhin** [comment]
It's "ok" if UIEditBox (of TextField) initialized with system font, but I need to render it with custom font.

UIEditBox and TextField both uses cocos2d::Label for rendering. And Label uses FontAtlas to form texture. 
It forms A8 or AI88 texture. I can make it RGBA8888 texture and get color smiles from custom font, but freetype library was build without color support. 
To make color support for custom fonts, freetype library build with color support and some local changes in FontAtlas are required. Do you have plans of making it in near future, or I can try to do it by myself?

**Comment by drelaptop** [comment]
sorry for no plans of making it in near future, but yeah! you can do it by yourself. Please make a PR when you finish it, all developers will be very grateful to you.

**Comment by sbrednikhin** [comment]
No problem. I'll make it. 
How can I deal with library rebuilding? If I will do it only on my side it will brake tests. Should I create an issue to https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src ? It looks like correct variant because https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src is managed by cocos team.

**Comment by drelaptop** [comment]
oh! beyond of my knowledge, this is the main member @minggo of cocos team, I think he could answer your question, just wait a moment.

**Comment by minggo** [comment]
@sbrednikhin yep, you can use `https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src` to build needed 3rd party libs. But it can work on iOS, Android, macos and linux. Please let me know what issue you meet.

**Comment by sbrednikhin** [comment]
@minggo I just need freetype library to be rebuildув with png support to enable color emoji support in custom fonts.
You mentioned that it's possible in future:
https://github.com/cocos2d/cocos2d-x/pull/17179

Looks like only thing needed is to build freetype with
`#define FT_CONFIG_OPTION_USE_PNG`
Is it possible? Should I create issue in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src ?

**Comment by minggo** [comment]
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/blob/v3/contrib/src/freetype/rules.mak#L20 you can modify the configure parameter to build with png support.

**Comment by minggo** [comment]
And yep, you can create an new issue of it.
