### ISSUE TITLE
build error only on arm64-v8a

### ISSUE THREAD

**Issue by CodeMasterYi** [cocos2d/cocos2d-x#18569]
- cocos2d-x version: 3.16
- devices test on: mac air (OSX 10.13.2)
- developing environments
   - NDK version: latest(ndk bundle in android sdk)

Steps to Reproduce:

1. add abi arm64-v8a
2. build with Android Studio
3. then we will see this:
![4f3941c7-6240-42e4-b58e-889bda4911bd](https://user-images.githubusercontent.com/10430162/34073362-1e01bfea-e2d3-11e7-8394-6095563f395f.png)

but we won't see this error on armeabi-v7a, & x86.
I can not figure out why this happen! =.=
certainly, we can simpply add this to avoid this error:
```
#include <cstring>
```

(PS: i only build my project on these ABIs)

**Comment by drelaptop** [comment]
Similar problem occurred to me, and it was solved after I keep Android Studio and all tools on `SDK Tools` latest. Update your tools and try again.

**Comment by CodeMasterYi** [comment]
Maybe you encounted another problem.
I'm keeping them up-to-date~
latest Android Studio
latest ndk-bundle
latest build tool
APP_PLATFORM=15
TARGET_SDK_VERSION=26

**Comment by CodeMasterYi** [comment]
Although, it is not a fatal issue, it is not perfect~

**Comment by drelaptop** [comment]
@dumganhar will help you, he known this clear. please wait some time, for he is a little busy today.

**Comment by coder-free** [comment]
Edit mp3reader.cpp. Change #include \<string\> to  #include \<cstring\>.
Edit CCAllocatorStrategyGlobalSmallBlock.h. Add #include \<cstring\>.
See [here](https://stackoverflow.com/questions/2505365/compiler-error-memset-was-not-declared-in-this-scope)

**Comment by CodeMasterYi** [comment]
Absolutely, you r right, and i also mentioned this in my issue description.
I just think it should be more official.
is it ugly "every time, a new engine user or others find this question"？

**Comment by drelaptop** [comment]
thanks for your both mention it, I will submit a PR

**Comment by drelaptop** [comment]
when I try to modify files in the GitHub latest version, I found #18476 it seems like solved this issue. it added `<string.h>` and have much discuss. please have a look.

**Comment by CodeMasterYi** [comment]
oh, i see! v3.17 will fix this~
