### ISSUE TITLE
The libSpine is crashed.

### ISSUE THREAD

**Issue by LSilent** [cocos2d/cocos2d-x#18566]
- cocos2d-x version: 3.16
- devices test on: Windows 7
- developing environments
   - VS version: vs2017
Steps to Reproduce:
1. run cpp-tests
2. click the "44:Node:Spine" test.
The thrid example,"GoblinsExample", is crashed in SkeletonAnimation::createWithJsonFile

**Comment by drelaptop** [comment]
out-of-date issue ,fixed in https://github.com/cocos2d/cocos2d-x/pull/18582, please close @minggo
