### ISSUE TITLE
fix warning UIEditBoxImpl-android.h#66

### ISSUE THREAD

**Issue by CodeMasterYi** [cocos2d/cocos2d-x#18578]
[https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/ui/UIEditBox/UIEditBoxImpl-android.h](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/ui/UIEditBox/UIEditBoxImpl-android.h)
warning: 'setNativeTextHorizontalAlignment' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

**Comment by kaplad** [comment]
Have created a [PR](https://github.com/cocos2d/cocos2d-x/pull/18580) for this
