### ISSUE TITLE
about android Proguard

### ISSUE THREAD

**Issue by CodeMasterYi** [cocos2d/cocos2d-x#18574]
- cocos2d-x version: 3.16

NOW we can not see any Proguard file for cocos2d-x project,
but we may need this for the future when we are going to import multiple SDKs and multiple java or android function library which causes method's reference count large than 65535.
Although, google provides multidex support library trying to resolve the issue, but it is ugly.
The best solution may be use proguard to reduce the method's reference count.

my proguard code for THIS engine is:
```
-dontwarn org.cocos2dx.lib.**
-keep public class org.cocos2dx.lib.**{*;}
```

BUT, i am not sure that it is enough~

**Comment by minggo** [comment]
it is fixed in latest code
