### ISSUE TITLE
Issue with label right alignment and max width

### ISSUE THREAD

**Issue by Dimon4eg** [cocos2d/cocos2d-x#18571]
Label with max width (for word wraping) and right alignment works with issue: some words have additional space from right side.

![image](https://user-images.githubusercontent.com/1271541/34075133-cf5ea46e-e2c5-11e7-948d-a1b073a0de6b.png)

- cocos2d-x version: 3.16 
- devices test on: windows
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: 2017
   - browser type and version:

Steps to Reproduce:

1. run cpp-tests
2. open "30: Node: Label - New API"
3. go to 8 test
4. select right at bottom

**Comment by drelaptop** [comment]
since solved by #18751 , issue should be closed
