### ISSUE TITLE
Get a PR, some of Effects was cut off when multiple Effect play at same time. How to solve it on IOS

### ISSUE THREAD

**Issue by xueyuetianxi** [cocos2d/cocos2d-x#18590]
- cocos2d-x version: cocos2d-lua 3.10
- devices test on: android and ios (just expand the audio stream on android (cocos2dSound.java MAX_SIMULTANEOUS_STREAMS_DEFAULT) )
- developing environments
   - NDK version: r10e
   - Xcode version: --
   - VS version: 2013
   - browser type and version:

Steps to Reproduce:

1. Not is bound to happen
2.

**Comment by drelaptop** [comment]
cocos 中文社区: http://forum.cocos.com/
cocos English forum: http://discuss.cocos2d-x.org/

I think [中文社区](http://forum.cocos.com/) is a better choice for you to solve this question. many Lua developers discuss on that site. Issues usually are used to report bugs with a `Steps to Reproduce`
