### ISSUE TITLE
liblto_plugin-0.dll: could not load plugin library: The parameter is incorrect.

### ISSUE THREAD

**Issue by alagiyanirav** [cocos2d/cocos2d-x#18603]
C:/Users/ob_server/AppData/Local/Android/android-ndk-r16b/build//../toolchains/x86-4.9/prebuilt/wind
ows-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld.exe: error:
 C:/Users/ob_server/AppData/Local/Android/android-ndk-r16b/build//../toolchains/x86-4.9/prebuilt/win
dows-x86_64/bin/../libexec/gcc/i686-linux-android/4.9.x/liblto_plugin-0.dll: could not load plugin l
ibrary: The parameter is incorrect.

collect2.exe: error: ld returned 1 exit status
make: *** [D:/game/StartGame/proj.android-studio/app/build/intermediates/ndkBuild/debug/obj/local/x8
6/libMyGame.so] Error 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED 

- cocos2d-x version: 3.16
- devices test on: NA
- developing environments
   - NDK version: android-ndk-r16b
   - Xcode version: NA
   - VS version: NA
   - browser type and version: NA 

Steps to Reproduce:

1. cocos new StartGame -p com.nra.app -l cpp -d D:\game
2.  cocos compile -p android --android-studio

**Comment by minggo** [comment]
When releasing v3.16, r16+ is not released, so cocos2d-x v3.16 may not work with r16b. You can refer to `cocos2dx_root/docs/RELEASE_NOTES.md` for the ndk version tested with v3.16.

**Comment by alagiyanirav** [comment]
Hi Minggo,

Thanks for your reply.

Is there any workaround of this issue?
