### ISSUE TITLE
When will cc.sys.WECHAT_GAME supporting be added to Cocos2d-JS ?

### ISSUE THREAD

**Issue by JiekeZhu** [cocos2d/cocos2d-x#18602]
As title.

Currently cocos2d-x 3.16 does not have this feature. 
Hope you can understand the importance of this feature. 
I know this has been supported with CocosCreator v1.8.
But I guess there are a lot of developers just like me using the old version.

BR.

**Comment by drelaptop** [comment]
As far as I know it's on schedule, you can get more informations on [Chinese forum](http://forum.cocos.com/) by @ the member
 of `引擎开发团队`, such as __panda__.

**Comment by drelaptop** [comment]
refer to: http://forum.cocos.com/t/cocos2d-html5-3-16/55119

please close this issue @minggo
