### ISSUE TITLE
how to recreate Cocos2dxActivity

### ISSUE THREAD

**Issue by wlssing** [cocos2d/cocos2d-x#18628]
1. .in native  i have one Cocos2dxActivity
2.then i jump to another Activity(is not Cocos2dxActivity) may be not one Activity
3.  then  i want to jump the first Cocos2dxActivity,

i know that ios can use method that removed glview and add glview   to do this
 but in android  when i remove glview i find glview thread recreated  then opps bang !!
 there is any method i can sloved this problem

**Comment by wlssing** [comment]
i think put glview in windowManger   find crash:
/libcocos2djs.so (_ZNKSt8functionIFbPN7cocos2d13EventListenerEEEclES2_+88)
/libcocos2djs.so (_ZN7cocos2d15EventDispatcher24dispatchEventToListenersEPNS0_19EventListenerVectorERKSt8functionIFbPNS_13EventListenerEEE+1032)
libcocos2djs.so (_ZN7cocos2d15EventDispatcher13dispatchEventEPNS_5EventE+356)
libcocos2djs.so (_ZN7cocos2d15EventDispatcher19dispatchCustomEventERKSsPv+72)
libcocos2djs.so (_ZN11AppDelegate30applicationWillEnterForegroundEv+132)
libcocos2djs.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnResume+78)
arm/base.odex (offset 0x1f5c000)

**Comment by minggo** [comment]
Doesn't support to recreate Cocos2dxActivity, i don't know why you need to recreate it. And please discuss it in forum: http://discuss.cocos2d-x.org/.
