### ISSUE TITLE
Kerning disabled in CCLabelBMFont

### ISSUE THREAD

**Issue by scottd72** [cocos2d/cocos2d-x#1864]
createFontChars doesn't appear to currently use any of the kerning information from the font file (despite all the hard work of extracting the information from the file and stashing it away having been done already).

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2660
