### ISSUE TITLE
希望新版加入对android studio 3.x的支持

### ISSUE THREAD

**Issue by samge1988** [cocos2d/cocos2d-x#18653]
升级了as和gradle的版本，libcocosdx不会自动导入到as，也不能Run起来，请问需要怎么配置，谢谢

**Comment by drelaptop** [comment]
新的 as 工程在 `proj.android` 下，没在 `proj.android-studio` 下，最新版的 as 是可以用的。因为新版本 Android 的 Eclipse 工程被去除了，原 as 的工程就迁到了 `proj.android` 下，正式发布后 `proj.android-studio`  文件夹会消失。

尝试更新 GitHub 最新代码，重新尝试，如果出错，请说明一下操作步骤，截图报错信息

**Comment by samge1988** [comment]
ok, 3q

**Comment by drelaptop** [comment]
@minggo please close
