### ISSUE TITLE
Crash on onCreate main activity

### ISSUE THREAD

**Issue by deguilardi** [cocos2d/cocos2d-x#18655]
- cocos2d-x version: 3.16
- devices test on: samsung GT-S5310B
- developing environments
   - NDK version: 416b

Steps to Reproduce:

1. compile and run on an old slow device.

Explanation:
The main activity is being destroyed at its very fist run by a "workaround" at Cocos2dxActivity.onCreate line 118.
The matter is that the onDestroy method (line 206) is calling the Cocos2dxAudioFocusManager.unregisterAudioFocusListener that tries to call runOnGLThread. Right,  the runOnGLThread needs the Activity running to work. Cocos2dxHelper.runOnGLThread tries to runOnGLThread and the app crashes!

conclusion:
It's a loop that never closes. The Cocos2dxHelper creates a thread that tries to access the activity that was just destroyed.

fix:
removing the workaround at the Cocos2dxActivity was the only thing that made the app works again

**Comment by drelaptop** [comment]
> destroyed at its very fist run by a "workaround" at Cocos2dxActivity.onCreate 

"workaround" code block should not been triggered when normally start cocos2d-x activity, refer to https://github.com/cocos2d/cocos2d-x/pull/19010 to get more in detail.
