### ISSUE TITLE
cocos gen-libs -pios error

### ISSUE THREAD

**Issue by deguilardi** [cocos2d/cocos2d-x#18667]
- cocos2d-x version: 3.17
- devices test on: N/A
- developing environments
   - NDK version: 13b
   - Xcode version: 9.2
   - VS version:  N/A
   - browser type and version: N/A

Steps to Reproduce:

1. run command cocos gen-libs -p ios

ERROR LOG:

** BUILD FAILED **

The following build commands failed:
	CompileC build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/Objects-normal/i386/lua_cocos2dx_extension_auto.o /Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/auto/lua_cocos2dx_extension_auto.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error running command, return code: 65.

**Comment by slackmoehrle** [comment]
`v3.17`? Are you sure?

I used the `v3` branch just now and things compiled fine. `cocos gen-libs -p ios -m release`

**Comment by deguilardi** [comment]
yes, I am sure

$ cocos -v
Python 2.7.10
cocos2d-x-3.17
Cocos Console 2.3

**Comment by slackmoehrle** [comment]
```
$ cocos -v
Python 2.7.10
cocos2d-x-3.17
Cocos Console 2.3
```

**Comment by deguilardi** [comment]
more details:

CompileC build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/Objects-normal/x86_64/select.o /Users/deguilardi/cocosWorkspace/lib-cocos2d/external/lua/luasocket/select.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/deguilardi/cocosWorkspace:/Users/deguilardi/cocosWorkspace/lib-cocos2d/tools/cocos2d-console/bin:/bin:/Users/deguilardi/Library/Android/sdkv25.2.5/platform-tools::/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/deguilardi/cocosWorkspace:/Users/deguilardi/cocosWorkspace/lib-cocos2d/tools/cocos2d-console/bin:/Users/deguilardi/Library/Android/sdkv25.2.5/platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=188 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -Wno-trigraphs -fpascal-strings -Os -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wuninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wno-int-conversion -Wbool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DNDEBUG -DUSE_FILE32API -DCC_TARGET_OS_IPHONE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mios-simulator-version-min=6.0 -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/libluacocos2d\ iOS.hmap -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../.. -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../.. -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../base -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../3d -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../2d -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../deprecated -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../physics -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../2d/platform -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../audio/include -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../editor-support -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../editor-support/spine -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../editor-support/cocostudio -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../editor-support/cocosbuilder -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../ui -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../storage -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../extensions -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external/chipmunk/include -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external/lua -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external/lua/luajit/include -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external/lua/tolua -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../editor-support/cocostudio/ActionTimeline -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../physics3d -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../navmesh -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external/bullet/include/bullet -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external/bullet/include -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../platform/ios -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/../../../../external/curl/include/ios -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/prebuilt/ios/simulator/include -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/DerivedSources/x86_64 -I/Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/DerivedSources -F/Users/deguilardi/cocosWorkspace/lib-cocos2d/prebuilt/ios/simulator -MMD -MT dependencies -MF /Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/Objects-normal/x86_64/select.d --serialize-diagnostics /Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/Objects-normal/x86_64/select.dia -c /Users/deguilardi/cocosWorkspace/lib-cocos2d/external/lua/luasocket/select.c -o /Users/deguilardi/cocosWorkspace/lib-cocos2d/cocos/scripting/lua-bindings/proj.ios_mac/build/cocos2d_lua_bindings.build/Release-iphonesimulator/libluacocos2d\ iOS.build/Objects-normal/x86_64/select.o

**Comment by deguilardi** [comment]
After downgrading to v3.16 everything worked flawlessly.
Android project still not working as reported on #18668

**Comment by drelaptop** [comment]
`gen-libs` have been tested when 3.17 release

please reopen it if you reproduce same issue with cocos2d-x 3.17 @deguilardi

**Comment by abrajam92** [comment]
Hello, I am experiencing the same issue with cocos 2d-x 3.17.2

> 2 errors generated.
> 
> CompileC /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysicsJoint.o /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/physics/CCPhysicsJoint.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'libcocos2d Mac' from project 'cocos2d_libs')
>     cd /Users/abrajam/Downloads/cocos2d-x-3.17.2/build
>     export LANG=en_US.US-ASCII
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.7 -fmessage-length=126 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c++11 -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror=incompatible-pointer-types -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wnon-virtual-dtor -Woverloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCOCOS2D_DEBUG=1 -DUSE_FILE32API -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DCC_TARGET_OS_MAC -DCC_KEYBOARD_SUPPORT -D_USRDLL -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wblock-capture-autoreleasing -Wno-strict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-generated-files.hmap -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-own-target-headers.hmap -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-all-target-headers.hmap -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-project-headers.hmap -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2 -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/editor-support -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/chipmunk/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/extensions -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri/common -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri/sweep -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include/bullet -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/Box2D/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/png/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/tiff/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/webp/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/jpeg/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/freetype2/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/glfw3/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/websockets/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/curl/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/freetype2/include/mac/freetype2 -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/openssl/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include/bullet -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/uv/include -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/prebuilt/mac/include -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources-normal/x86_64 -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources/x86_64 -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources -F/Users/abrajam/Downloads/cocos2d-x-3.17.2/prebuilt/mac -include /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12705300621253826175/cocos2d-prefix.pch -MMD -MT dependencies -MF /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysicsJoint.d --serialize-diagnostics /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysicsJoint.dia -c /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/physics/CCPhysicsJoint.cpp -o /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysicsJoint.o
> 
> CompileC /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DWorld.o /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/physics3d/CCPhysics3DWorld.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'libcocos2d Mac' from project 'cocos2d_libs')
>     cd /Users/abrajam/Downloads/cocos2d-x-3.17.2/build
>     export LANG=en_US.US-ASCII
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.7 -fmessage-length=126 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c++11 -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror=incompatible-pointer-types -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wnon-virtual-dtor -Woverloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCOCOS2D_DEBUG=1 -DUSE_FILE32API -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DCC_TARGET_OS_MAC -DCC_KEYBOARD_SUPPORT -D_USRDLL -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wblock-capture-autoreleasing -Wno-strict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-generated-files.hmap -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-own-target-headers.hmap -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-all-target-headers.hmap -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-project-headers.hmap -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2 -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/editor-support -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/chipmunk/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/extensions -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri/common -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri/sweep -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include/bullet -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/Box2D/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/png/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/tiff/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/webp/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/jpeg/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/freetype2/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/glfw3/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/websockets/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/curl/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/freetype2/include/mac/freetype2 -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/openssl/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include/bullet -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/uv/include -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/prebuilt/mac/include -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources-normal/x86_64 -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources/x86_64 -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources -F/Users/abrajam/Downloads/cocos2d-x-3.17.2/prebuilt/mac -include /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12705300621253826175/cocos2d-prefix.pch -MMD -MT dependencies -MF /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DWorld.d --serialize-diagnostics /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DWorld.dia -c /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/physics3d/CCPhysics3DWorld.cpp -o /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DWorld.o
> 
> CompileC /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DShape.o /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/physics3d/CCPhysics3DShape.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'libcocos2d Mac' from project 'cocos2d_libs')
>     cd /Users/abrajam/Downloads/cocos2d-x-3.17.2/build
>     export LANG=en_US.US-ASCII
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.7 -fmessage-length=126 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c++11 -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror=incompatible-pointer-types -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wnon-virtual-dtor -Woverloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCOCOS2D_DEBUG=1 -DUSE_FILE32API -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DCC_TARGET_OS_MAC -DCC_KEYBOARD_SUPPORT -D_USRDLL -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wblock-capture-autoreleasing -Wno-strict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-generated-files.hmap -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-own-target-headers.hmap -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-all-target-headers.hmap -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/libcocos2d\ Mac-project-headers.hmap -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2 -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/editor-support -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/chipmunk/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/extensions -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri/common -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/poly2tri/sweep -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include/bullet -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/Box2D/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/png/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/tiff/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/webp/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/jpeg/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/freetype2/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/glfw3/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/websockets/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/curl/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/freetype2/include/mac/freetype2 -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/openssl/include/mac -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/bullet/include/bullet -iquote /Users/abrajam/Downloads/cocos2d-x-3.17.2/external/uv/include -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/prebuilt/mac/include -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources-normal/x86_64 -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources/x86_64 -I/Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/DerivedSources -F/Users/abrajam/Downloads/cocos2d-x-3.17.2/prebuilt/mac -include /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12705300621253826175/cocos2d-prefix.pch -MMD -MT dependencies -MF /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DShape.d --serialize-diagnostics /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DShape.dia -c /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/physics3d/CCPhysics3DShape.cpp -o /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysics3DShape.o
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC /Users/abrajam/Downloads/cocos2d-x-3.17.2/build/build/cocos2d_libs.build/Debug/libcocos2d\ Mac.build/Objects-normal/x86_64/CCPhysicsSprite3D.o /Users/abrajam/Downloads/cocos2d-x-3.17.2/cocos/physics3d/CCPhysicsSprite3D.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> Error running command, return code: 65.

**Comment by deguilardi** [comment]
3.17.2 is giving the very same error
