### ISSUE TITLE
Can't play .ogg sound on iOS

### ISSUE THREAD

**Issue by xerosugar** [cocos2d/cocos2d-x#18666]
- cocos2d-x version: 3.16
- devices test on: iPhone 6s
- Xcode version: 9.2 (9C40b)

Steps to Reproduce:
I just tried playing it like this:
`AudioEngine::play2d("sounds/sfx.ogg", false, volume);`

Works fine when I try to play the same sound as a .wav file, though.

**Comment by slackmoehrle** [comment]
We don't support `.ogg` on iOS, AFAIK. `.mp3` and `.caf` on IOS.

**Comment by xerosugar** [comment]
that's a shame. thanks for the reply.
.wav and .aif can also be used I think.

**Comment by deguilardi** [comment]
@xerosugar Shame on Apple as it doesn't like open formats. This is not a cocos matter.

**Comment by drelaptop** [comment]
this issue have been replied, so close it
