### ISSUE TITLE
How to add UIViewController in 3.X Project

### ISSUE THREAD

**Issue by unix2dos** [cocos2d/cocos2d-x#18678]
- cocos2d-x version: 3.17

I need add a UIViewController in games, how to add UIViewController or replace Scene to UIViewController

**Comment by unix2dos** [comment]
@minggo thanks

**Comment by drelaptop** [comment]
About question like this, suggest to discuss it in forum

English https://discuss.cocos2d-x.org/c/cocos2d-x/cpp

Chinese https://forum.cocos.com/c/cocos2d-x
