### ISSUE TITLE
未能找到项目 cocos2d-x\external\Box2D\proj.win32\libbox2d.vcxproj

### ISSUE THREAD

**Issue by samge1988** [cocos2d/cocos2d-x#18676]
- cocos2d-x version: 3.17 仓库最新的代码
- devices test on: win32
Steps to Reproduce:

1. git clone https://github.com/cocos2d/cocos2d-x.git
2. python download-deps.py
3.git submodule update --init
4.new一个新项目后，用vs2017打开报这个错误

**Comment by drelaptop** [comment]
I guess you forget to run `setup.py`, and a old version `cocos` existed in your system, please run `cocos -v` to see detail
```sh
Python 2.7.10
cocos2d-x-3.17
Cocos Console 2.3
```

**Comment by samge1988** [comment]
有setup.py，setup.py之后再new的，是必现的，我又试了一次还是一样(截止2.4仓库最新的代码)，好像是new win32这块改动了吧？

**Comment by drelaptop** [comment]
仓库最新代码，在win7上用vs2015测试了，不存在这个问题。libbox2d.vcxproj 在最新代码中已经没有了，中文讨论建议移步到 中文论坛 http://forum.cocos.com/c/cocos2d-x
