### ISSUE TITLE
Failed to build cocos2d-x on x86 due to cmake error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by shanshan0309** [cocos2d/cocos2d-x#18689]
I build cocos2d-x with Visual studio 2017 update2 on Windows Server 2016, but it failed with CMake Error: The following variables are used in this project, but they are set to NOTFOUND. This issue can be reproduced from v3 revision edee972. Could you help have a look about this issue? Thanks in advance!

**Steps to Reproduce:**
1. git clone --recursive https://github.com/cocos2d/cocos2d-x.git D:\Cocos2dx\src
2. Open a VS 2017 command prompt and browse to D:\Cocos2dx
3. mkdir build_x86 && pushd build_x86
4. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src

**Actual result:**
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SPIDERMONKEY_LIBRARY
    linked by target "jscocos2d" in directory D:/Cocos2dx/src/cocos/scripting/js-bindings

**Comment by josemariabooymts** [comment]
Shan?

**Comment by drelaptop** [comment]
@shanshan0309 thanks for testing the cmake in developing, as the https://github.com/cocos2d/cocos2d-x/commit/edee97278f602512c02ec6f5ffa30d29243930d8 said `V3 android cmake support, add mac/ios support`, not include win32. __cmake support win32 is here__ #18683 , it not been merged yet.

In PR: #18683 ,this error you reported have been fixed, you can merge this PR manually. I have test those changed, cmake suppport win32 for cpp works well.

this discuss shows the progress http://discuss.cocos2d-x.org/t/in-progress-cmake-support-all-platform-for-cocos2d-x/41164

**Comment by shanshan0309** [comment]
@drelaptop, thank you very much for looking into this issue. Meanwhile, thanks for letting me know the progress of this fix.

**Comment by drelaptop** [comment]
3.17 version have supported cmake build using VS++, this issue have been fixed between 3.16 and 3.17. please refer to [cmake/README.md](https://github.com/cocos2d/cocos2d-x/blob/v3/cmake/README.md)

please close this issue. @minggo
