### ISSUE TITLE
[Question] CCRect::containsPoint 

### ISSUE THREAD

**Issue by progsource** [cocos2d/cocos2d-x#18680]
- cocos2d-x version: v3

https://github.com/cocos2d/cocos2d-x/blob/18a6d8241d9a1290bfd6341ea6159877906d780a/cocos/math/CCGeometry.cpp#L176-L187

As issue #2423 was closed as far as I can see with somehow unrelated commits, I simply wanted to ask, if it is really wanted behavior to have an inclusive containsPoint method. My expectation would have been, that it should be exclusive.

**Comment by Priority10** [comment]
Please explain why do you think so?

This method is often used for simple collision detection. It seems to me quite logical that this is inclusive.

**Comment by progsource** [comment]
So - let's say we have a `Rect(1, 1, 2, 2)` - blue in the image.

![grid](https://user-images.githubusercontent.com/1206026/41227795-5e0f2d2e-6d76-11e8-953d-0c76973a0ed0.png)

And now we have the following results from containsPoint:

| input | output |
-------  | ---------
Vec2(0, 0) | false
Vec2(1, 0) | false
Vec2(2, 0) | false
Vec2(3, 0) | false
Vec2(0, 1) | false
Vec2(1, 1) | true
Vec2/(2, 1) | true
**Vec2(3, 1)** | **true**
Vec2(0, 2) | false
Vec2(1, 2) | true
Vec2(2, 2) | true
**Vec2(3, 2)** | **true**
Vec2(0, 3) | false
**Vec2(1, 3)** | **true**
**Vec2(2, 3)** | **true**
**Vec2(3, 3)** | **true**

So what I think is, that the bold marked outputs (red in the image) should actually not be inside of the rectangle, because the rectangle is only 2x2 and not 3x3. So it's like some kind of border added to it, which is now "inside" of the rectangle.

**Comment by progsource** [comment]
`getMaxX`and `getMaxY` return 3 in the above case. Maybe that should be instead 2.
https://github.com/cocos2d/cocos2d-x/blob/b26e1bb08648c11a9482d0736a236aebc345008a/cocos/math/CCGeometry.cpp#L146-L149
https://github.com/cocos2d/cocos2d-x/blob/b26e1bb08648c11a9482d0736a236aebc345008a/cocos/math/CCGeometry.cpp#L161-L164

**Comment by stevetranby** [comment]
The reason for inclusiveness is that the Rect/Vec2 are mathematical concepts. You’re thinking in rasterized pixels. If you take the mathematical rectangle {Vec2{1,1},Size{2,2}} is effectively your CYAN rectangle and doesn’t include the red area. However, when you rasterize a mathematical Rect into pixels then that is where the maxX/maxY pixel row/column is exclusive (instead of inclusive). I could probably explain better with some diagrams, but hope that makes enough sense.

**Comment by progsource** [comment]
Ok, got it. But then, would it maybe make sense to clarify the function a little bit (for example renaming it to `containsPointInclusive` and setting `containsPoint` to deprecated) , or maybe even adding a `containsPointExclusive` function?

**Comment by Priority10** [comment]
@progsource I am sorry for the late reply.

As @stevetranby  perfectly explained, mathematically this is right.

Maybe it is a good idea to have `containsPointInclusive `and `containsPointExclusive`. But then the mathematically correct version of `containsPointExclusive` will look like

```
 bool Rect::containsPointExclusive(const Vec2& point) const 
 { 
     bool bRet = false; 
  
     if (point.x > getMinX() && point.x < getMaxX() 
         && point.y > getMinY() && point.y < getMaxY()) 
     { 
         bRet = true; 
     } 
  
     return bRet; 
 } 
```
and with your image it also will not give you the desired result.

To my shame I do not know how rasterization works in the engine and I can not tell if this is an eternal conflict of mathematics vs rasterization, or just rasterization does not work as it does on your image.

**Comment by v1993** [comment]
By the way, why we use `if` there at all?! Just write this function as

    bool Rect::containsPoint(const Vec2& point) const
    {
        return (point.x >= getMinX() && point.x <= getMaxX() 
             && point.y >= getMinY() && point.y <= getMaxY())
    }
It is much easier!

**Comment by Priority10** [comment]
@v1993 Good point.

**Comment by progsource** [comment]
So - in the end I would be fine with just making it clear in code (either with changing the method name or adding a comment), that the current method is inclusive by intention. And well - what v1993 said ;)

**Comment by minggo** [comment]
I created https://github.com/cocos2d/cocos2d-x/pull/19155 to make the codes more clean and make the comment more clear.
