### ISSUE TITLE
Why remove *.a files for armeabi?

### ISSUE THREAD

**Issue by zhangjiequan** [cocos2d/cocos2d-x#18691]
- cocos2d-x version:3.16

Why remove *.a files for armeabi?
I find that the newest version of cocos2dx has removed *.a files for armeabi under "external" Folder.
Is it means the machine with armeabi cpu can't run this version of cocos2dx game?

**Comment by drelaptop** [comment]
ABI | Supported Instruction Set(s) | Notes
-- | -- | --
armeabi | ARMV5TE and laterThumb-1 | Deprecated in r16. Will be removed in r17. No hard float.
armeabi-v7a | armeabi Thumb-2 VFPv3-D16 Other, optional | Incompatible with ARMv5, v6 devices.

use armabi-v7a might be the better choice, see this https://developer.android.com/ndk/guides/abis.html

**Comment by drelaptop** [comment]
__armeabi__ have been Deprecated in r16. Will be removed in r17. No hard float.
