### ISSUE TITLE
[regression] RenderTexture - does not work on android and win32 

### ISSUE THREAD

**Issue by crazyhappygame** [cocos2d/cocos2d-x#18695]
- cocos2d-x version: 3,16 and latest from github
- devices test on: Sony Xperia T (Android 4.3), HTC Desire C (Android 4.0), Samsung Galaxy S6,
- developing environments
   - NDK version: 14b cocos2d-x 3.16, ndk16b latest from github 
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  Download (or build) latest Android/win32 cpp-test
Android:
https://ci.appveyor.com/api/projects/minggo/cocos2d-x/artifacts/debug/CppTests-debug.apk?job=Environment%3A%20build_type%3Dandroid_cpp_tests&pr=false
Win32:
https://ci.appveyor.com/api/projects/minggo/cocos2d-x/artifacts/release_win32.7z?job=Environment%3A%20build_type%3Dwindows32&pr=false

2.  Run cpp-test "42:Node: RenderTexture"
3.  On first "42:Node: RenderTexture" test try to draw lines

Bug1:  Android 4.3 (and older),  win32:  line is not drawn. All sprites disappear. Screen is black on Android 4.3 (and older),  win32 after first line
Bug2: Android 7.1: draw many lines (about 10 is enough on may android device) on android 7.1 screen is black, all sprites disappear
Bug3: after press home button and open again (without killing) ui is distorted. Like in:
http://discuss.cocos2d-x.org/t/ui-distortion-due-to-drawnode-in-cocos2d/41535

Comments:
1. For sure worked 2 years ago on Android and win32 :)

**Comment by crazyhappygame** [comment]
@minggo It is critical regression. Could you fix it in 3.17?

**Comment by crazyhappygame** [comment]
@slackmoehrle Could you ask developers to fix this regression?

**Comment by slackmoehrle** [comment]
@crazyhappygame The engineering team will look at this as time permits. They are very busy at the moment.

**Comment by crazyhappygame** [comment]
@slackmoehrle Thank you!

**Comment by drelaptop** [comment]
@crazyhappygame this have been fixed at 3.17 release, it's due to https://github.com/cocos2d/cocos2d-x/pull/18629, that PR have been revert.
