### ISSUE TITLE
Missing Cmake references

### ISSUE THREAD

**Issue by remolive** [cocos2d/cocos2d-x#18696]
Hi! I'm trying to build a cocos2d-x3.17 project on Ubuntu 16.04.
What I did:

    > git clone --recursive https://github.com/cocos2d/cocos2d-x.
    > cd cocos2d-
    > python download-deps.
    > git submodule update --
    > ./setup.
    > source ~/.
    > cd build
    > ./install-deps-linux.
    > cd -
    > cocos new FirstGame -l cpp -d .
    > cd FirstGame
    > cocos run -p linux

Then I got:

    Building mode: debug
    running: 'cmake -DCMAKE_BUILD_TYPE=Debug -DDEBUG_MODE=ON ..'

    -- The C compiler identification is GNU 4.9.4
    -- The CXX compiler identification is GNU 4.9.4
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:41 (include):
      include could not find load file:

        CocosBuildSet

    CMake Error at CMakeLists.txt:42 (CocosBuildSet):
       Unknown CMake command "CocosBuildSet".

     -- Configuring incomplete, errors occurred!
    See also "/home/oremy/cocos2d-x/FirstGame/linux-build/CMakeFiles/CMakeOutput.log".

I think I missed something and I'm not familiar with CMake.
I searched a lot about this kind of issue but didn't find anything working for me.
I'm just looking for some help or guidelines!

**Comment by drelaptop** [comment]
just copy this file `cocos2d-x-root/cmake/Modules/CocosBuildSet.cmake` into the correspond cmake dir on new project. the reason is `CocosBuildSet.cmake` is a new file, cocos-console din't copy it when `cocos new`, it's a mistake.

@minggo I remember that you said cocos-console will auto update after the new added file is merged

**Comment by minggo** [comment]
I just merged https://github.com/cocos2d/cocos2d-x/pull/18687, i think it is ok now.
