### ISSUE TITLE
After Phone call events EVENT_HIDE & EVENT_SHOW not triggering

### ISSUE THREAD

**Issue by rameshkumarit1990** [cocos2d/cocos2d-x#18701]
- cocoscreator version: 1.6.2 
- devices test on: IOS
- developing environments
   - NDK version: 16

Steps to Reproduce:

1. While user is playing game (if user receives a call) after ending  call/facetime game gets stuck , unable to trigger EVENT_HIDE & EVENT_SHOW. 
cc.game.on(cc.game.EVENT_HIDE, function () {
        if (G.Game.state == G.GameManager.State.Run && (G.Game.pauseMenu.active == false && G.Game.countL.active == false)) {

            self.openPausePopup();
        }

    });
    // For event when the app entering foreground
    cc.game.on(cc.game.EVENT_SHOW, function () {
        if (G.Game.state == G.GameManager.State.Run && (G.Game.pauseMenu.active == false && G.Game.countL.active == false)) {

            self.openPausePopup();
        }

    });

**Comment by drelaptop** [comment]
please feedback cocos creator issue at https://github.com/cocos-creator/cocos2d-x-lite, not cocos2d-x repo
