### ISSUE TITLE
CC_SYNTHESIZE syntax error

### ISSUE THREAD

**Issue by Fredmomo** [cocos2d/cocos2d-x#18713]
- cocos2d-x version: 3.16
- devices test on: ios
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. using CC_SYNTHESIZE macro giving syntax error in xcode
 the error is "unknown type name" "C++ requires a type specifier for all declarations"
2. here's code:
`CC_SYTHESIZE(float, _energy, Energy);
    CC_SYTHESIZE(Point, _pivot, Pivot);
    CC_SYTHESIZE(Point, _tip, Tip);
    CC_SYTHESIZE(float, _lineLength, LineLength);`

**Comment by anhbng** [comment]
> * cocos2d-x version: 3.16
> * devices test on: ios
> * developing environments
>   
>   * NDK version:
>   * Xcode version:
>   * VS version:
>   * browser type and version:
> 
> Steps to Reproduce:
> 
> 1. using CC_SYNTHESIZE macro giving syntax error in xcode
>    the error is "unknown type name" "C++ requires a type specifier for all declarations"
> 2. here's code:
>    `CC_SYTHESIZE(float, _energy, Energy); CC_SYTHESIZE(Point, _pivot, Pivot); CC_SYTHESIZE(Point, _tip, Tip); CC_SYTHESIZE(float, _lineLength, LineLength);`

hey, do you know why? I stuck on it too. Using Cmake to generate project and xcode shows the error
