### ISSUE TITLE
Suggestion: Rust language bindings

### ISSUE THREAD

**Issue by 3442853561** [cocos2d/cocos2d-x#18711]
I think if cocos2d-x have Rust language bindings it will more easy to use, as well as I can help with this job

**Comment by drelaptop** [comment]
no any plan for Rust language bindings

**Comment by TheBearodactyl** [comment]
I know I'm EXTREMELY late to this, but I recently autogened bindings for a modified distribution of cocos2d-x (it has some extras, almost nothing is missing)

[Here you go :D](https://github.com/TheBearodactyl/geode/blob/rwiir/crates/cocos2dx/src/lib.rs)
