### ISSUE TITLE
Dead roadmap

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18714]
It looks like trello roadmap (https://trello.com/b/Np6obnuE/cocos2d-x-roadmap) isn't updated long time. What is current plans? Where can I find it?  
You probably should remove that link from README.md

**Comment by trimax-items** [comment]
I think they will focus on javascript.

**Comment by slackmoehrle** [comment]
We now use GitHub for what Trello used to do for us.

**Comment by trimax-items** [comment]
@slackmoehrle Can you please post the exact github link where we can see roadmap?

**Comment by v1993** [comment]
There is still trello link in README.md, please reopen.

**Comment by slackmoehrle** [comment]
We use GitHub milestones now
