### ISSUE TITLE
FileUtils::listFiles does not work on Android

### ISSUE THREAD

**Issue by sbelloz** [cocos2d/cocos2d-x#18725]
- cocos2d-x version: 3.16
- devices test on: Nexus 5, OnePlus 5
- developing environments
   - NDK version: any

Steps to Reproduce:

1. Calling `FileUtils::getInstance()->listFiles("path/folder)` returns always an empty vector

Files exist. I've tried with relative and absolute paths but with no success.

Similar issue described here: [http://discuss.cocos2d-x.org/t/full-path-to-directory-not-to-a-file/8919](http://discuss.cocos2d-x.org/t/full-path-to-directory-not-to-a-file/8919)

**Comment by imtrobin** [comment]
Is this fixed? I'm still seeing the same problem on 3.17.1
