### ISSUE TITLE
Cocos2dx failed to build on x64 due to the error C2338: JS_STATIC_ASSERT

### ISSUE THREAD

**Issue by shanshan0309** [cocos2d/cocos2d-x#18720]
**Environment:**
Windows Server 2016 + VS2017 Update 5 + cocos2d-x v3 branch latest srouce code

We tried to build cocos2d-x on Windows. It failed to build on x64 due to error C2338: JS_STATIC_ASSERT. **Could you please help take a look at this? Thanks in advance!**

**Steps to Reproduce:**
1. git clone --recursive https://github.com/cocos2d/cocos2d-x.git D:\Cocos2dx\src
2. Open a VS 2017 command prompt and browse to D:\Cocos2dx
3. mkdir build_x64 && pushd build_x64
4. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_VERSION=10.0.16299.0 ..\src 
5. msbuild /m /p:Configuration=Release;Platform=x64 build_x64\Cocos2d-X.sln /t:Rebuild

**Actual result:**
_The full log file is attached._
[log_x64_build.log](https://github.com/cocos2d/cocos2d-x/files/1795914/log_x64_build.log)
28>d:\cocos2dx\src\external\spidermonkey\include\win32\js/Value.h(345): error C2338: JS_STATIC_ASSERT (compiling source file D:\Cocos2dx\src\cocos\scripting\js-bindings\manual\jsb_opengl_manual.cpp) [D:\Cocos2dx\build_x64\engine\cocos\js-bindings\jscocos2d.vcxproj]
    28>d:\cocos2dx\src\external\spidermonkey\include\win32\js/Value.h(1334): error C2338: JS_STATIC_ASSERT (compiling source file D:\Cocos2dx\src\cocos\scripting\js-bindings\manual\jsb_opengl_manual.cpp) [D:\Cocos2dx\build_x64\engine\cocos\js-bindings\jscocos2d.vcxproj]

**Comment by drelaptop** [comment]
cocos2d-x didn't supply proper external x64 libraries for windows, I suggest you to build 32bit application on windows.

**Comment by shanshan0309** [comment]
Thanks for looking into this issue, @drelaptop. But cocos2dx supported x64 on Windows before. So is  it because of code changes  recently that cannot support x64?

**Comment by drelaptop** [comment]
I think cocos team didn't have enough time to keep the support the x64 on windows, and keep support x86 is enough to develop mobile platform game. I haven't heard some one develop a popular x64 Windows game using cocos2d-x.

**Comment by shanshan0309** [comment]
Thanks for your confirm

**Comment by drelaptop** [comment]
you are welcome, please close this issue @shanshan0309

**Comment by Bilalmirza** [comment]
@drelaptop  what would be the steps to take If i want to build win64 project.
