### ISSUE TITLE
Outdated version of uthash

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#18728]
- cocos2d-x version: master +

Cocos2d-x is using an out-dated version of [uthash](https://github.com/troydhanson/uthash). Some users are wondering if this is causing issues with `Scheduler` in 3.16+

http://discuss.cocos2d-x.org/t/potential-problem-in-cocos2d-scheduler/41839

**Comment by Dimon4eg** [comment]
Probably we don't need uthash at all as we plan to switch to std::unordered_map https://github.com/cocos2d/cocos2d-x/issues/16661
