### ISSUE TITLE
cocos compile could not work on win7+codeblocks environment

### ISSUE THREAD

**Issue by hutaocheng** [cocos2d/cocos2d-x#18732]
- cocos2d-x version:3.15.1
- devices test on:win7
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: but codeblocks 16.1
   - browser type and version:

Steps to Reproduce:

1.  cocos new HelloWorld -p game.cocos2dx
2.  cd HelloWorld
3.  cocos compile -p win32
it warn me Visual Studio not installed while I had MinGW(in codeblocks setup directory)
4 cocos compile -p android
which warn me that ANT is not supported when android sdk version is greater than 23

**Comment by chenyu0532** [comment]
you can try to download VS，then try it again

**Comment by drelaptop** [comment]
I have replied in the Chinese Forum [here](http://forum.cocos.com/t/gcc-helloworld/57457/4?u=2627993092), Cocos2d-x didn't support CodeBlock, please use Visual Studio 2015 for Cocos2d-x 3.15.1. The IDE of C++ is too much, we can't supply every IDE's project files. 

In the latest Github Code, we are trying to support CMake in every platform, so our developers can use the IDE that CMake supported.

**Comment by hutaocheng** [comment]
@drelaptop
I see that the last cocos2dx version is 3.16, is makefile supported in this version?

**Comment by drelaptop** [comment]
3.16 not, the coming cocos2d-x 3.17 support cmake on Windows/Mac/Linux, you can refer to https://github.com/cocos2d/cocos2d-x/blob/v3/cmake/README.md

but we didn't consider MinGw on Windows, so it's possible to use CodeBlock on Ubuntu by CMake generated, Visual Studio is the only IDE on Windows we supported.

**Comment by drelaptop** [comment]
@citihome Now you can select to use CLion and VS compiler to use cmake on Windows. CodeBlocks  isn't be considered to support.

I think we should close this issue. @minggo
