### ISSUE TITLE
cocos2dx 3.16  ETC1 + ALPHA

### ISSUE THREAD

**Issue by pjdd** [cocos2d/cocos2d-x#18735]
- cocos2d-x version:cocos2dx 3.16
- devices test on: Android
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. I create ImageView  by  using  texture etc1 + alpha ,the  imageview can't display the alpha texture, but   in cocos2dx 3.15    is  ok  , the  engin  changed ?
2.

**Comment by halx99** [comment]
please see ralative PR: https://github.com/cocos2d/cocos2d-x/pull/18260

**Comment by pjdd** [comment]
thank you!
