### ISSUE TITLE
LuaMinxXmlHttpRequest::——sendRequest Memory Leak

### ISSUE THREAD

**Issue by pengyansheng** [cocos2d/cocos2d-x#18742]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

if(!response->isSucceed() )
{
//xxxxx

//add
release();
return;
}

**Comment by drelaptop** [comment]
not any description, add more details if reopen
