### ISSUE TITLE
Wrong doc description

### ISSUE THREAD

**Issue by xahon** [cocos2d/cocos2d-x#18757]
https://github.com/cocos2d/cocos2d-x/blob/6317e35f01383943202517d639456299e9eb1bec/cocos/2d/CCNode.h#L600

this function returns value in radians

P.S. I noticed that `setRotation` accept radians too

**Comment by drelaptop** [comment]
review the `setRotation` in test case, it's degrees (0 - 360), not radian (0 - 2 PI) @xahon
