### ISSUE TITLE
libfmod.so.6 symlinks lost when package a version

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x#18754]
when I clone the __cocos2d-x-3rd-party-libs-bin__ repo, the link keep:
```sh
-rwxr-xr-x  1 laptop  staff   1.5M Mar  5 17:41 libfmod.so
lrwxr-xr-x  1 laptop  staff    10B Mar  5 17:41 libfmod.so.6 -> libfmod.so
-rwxr-xr-x  1 laptop  staff   1.6M Mar  5 17:41 libfmodL.so
lrwxr-xr-x  1 laptop  staff    11B Mar  5 17:41 libfmodL.so.6 -> libfmodL.so
```
but when I download the depend external libs by download-deps.py, link lost:
```
-rwxr-xr-x  1 laptop  staff   1.5M Mar 19 11:35 libfmod.so
-rwxrwxrwx  1 laptop  staff    10B Mar 19 11:35 libfmod.so.6
-rwxr-xr-x  1 laptop  staff   1.6M Mar 19 11:35 libfmodL.so
-rwxrwxrwx  1 laptop  staff    11B Mar 19 11:35 libfmodL.so.6
```
the `lrwxr-xr-x` was changed to `-rwxrwxrwx`, and then using tools/make-package/git-archive-all to generate a cocos2d-x package.

so it will cause symlinks error when  using the cocos2d-x package on Linux:

> “error while loading shared libraries: libfmod.so.6: cannot open shared object file: No such file or directory”

related PR: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/304

Need to solve it before the 3.17 release!

**Comment by slackmoehrle** [comment]
What version of Linux are you using?

**Comment by drelaptop** [comment]
Ubuntu 16.04，soft link information is lost on Mac too. but it only have a bad effect on Linux build, for fmod libs is only used on Linux platform. 

so that our developers have to make a soft link manually on linux, when build and run using cocos2d-x __zip__ package

**Comment by slackmoehrle** [comment]
Interesting. I am running 16, 17, 18 and I don't have this issue. My build works correctly. Are you doing anything special during your build?

**Comment by drelaptop** [comment]
`unzip cocos2d-x.zip` to release the package? can you try to use  `tools/make-package` to generate a zip file, and then unzip the zip package, build using the package content.

another special, generated the package on mac platform, and then using the package on Linux

and please run `cpp-tests` to test the build

**Comment by slackmoehrle** [comment]
I need to read download-deps source, I think. It seems that perhaps it doesn't copy symlinks. Which might be a flag we can add to the code.

**Comment by drelaptop** [comment]
thanks, any progress with this issue?

`ln -sf libfmod.so libfmod.so.6`
