### ISSUE TITLE
Question: Run action on condition

### ISSUE THREAD

**Issue by xahon** [cocos2d/cocos2d-x#18759]
- cocos2d-x version: 3.16

Copied from my SO question https://stackoverflow.com/q/49598709/6119618

I want to create player moving using actions. I created function void move(float x, float y); That function creates actions RotateTo and MoveTo. I want to move player only if angle between its forward and target - forward is less that some value; I tried to add runAction(moveAction) in if condition in update function with bool lock variable but any call of runAction inside update fails with SIGSEGV signal;

Here are fields of my class derived from Node:

```
cocos2d::Action* moveAction;
cocos2d::Action* rotationAction;
In move function:

void GameObject::move(float x, float y) {
  startPosition = getPosition();
  endPosition   = Vec2(x, y);

  stopAllActions();

  rotationAction = RotateTo::create(
      angleBetweenForwardAndTarget(endPosition) / rotateSpeed,
      -Mathf::normalizeAngle(Mathf::getAngle(lookAtPosition(endPosition)))
  );
  runAction(rotationAction);

  moveAction = MoveTo::create(
      endPosition.distance(startPosition) / moveSpeed,
      Vec2(x, y)
  );
  runAction(moveAction);
}
```

But now rotation and translation occurs in the same time How to implement it?

**Comment by gestern** [comment]
There may be several possible solutions, but there are three most applicable ones:

1. By using `schedule()` call with custom update callback
1. By using [`ActionFloat`](http://www.cocos2d-x.org/reference/native-cpp/V3.9/db/d7d/classcocos2d_1_1_action_float.html) and within body `update(delta)` you have to write two parametric functions from delta time with `setPosition()` for  your `MoveTo` and `setRotation()` for your `RotateTo`
1. By inheriting from a class `ActionInterval` with your logic within its `update()`

**Comment by xahon** [comment]
@gestern i tried third but i had a lot of problems. Can you show me minimal example of 1 and 2 cases?

**Comment by xahon** [comment]
I'm transferred this issue to http://discuss.cocos2d-x.org/t/run-action-on-condition/42201
