### ISSUE TITLE
Cocos2dx NDK build error on android studio

### ISSUE THREAD

**Issue by peterSweter** [cocos2d/cocos2d-x#18766]
- cocos2d-x version: cocos2d-x-3.16
- devices test on: Xiaomi redmi 4x
- developing environments
   - NDK version: 16.1
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Build on android studio.

I have following error when I try to build my game on android studio:

    Error:(81) Android NDK: Application targets deprecated ABI(s): armeabi    
    Error:(82) Android NDK: Support for these ABIs will be removed in a future NDK release.    

Run from command line works fine.

**Comment by drelaptop** [comment]
the `armabi` should be change to `armabi-v7a`, and then some NDK compile errors should be fixed, with the upgrade of Android Studio and NDK

**Comment by peterSweter** [comment]
How can I change armabi, grep -r "armabi" in project directory did not find anything interesting ?

**Comment by drelaptop** [comment]
modified the `gradle.properties`, please refer to the GitHub latest configs:

https://github.com/cocos2d/cocos2d-x/blob/712b093b2724fa1011ba0a9f8031e8e8cfaa57bd/tests/cpp-empty-test/proj.android/gradle.properties#L35
https://github.com/cocos2d/cocos2d-x/blob/712b093b2724fa1011ba0a9f8031e8e8cfaa57bd/tests/cpp-empty-test/proj.android/gradle.properties#L36

**Comment by peterSweter** [comment]
Thank you, now it is working correctly.
