### ISSUE TITLE
SimpleAudioEngine::setEffectsVolume(0.0f) does not work in iOS11.3

### ISSUE THREAD

**Issue by seventhrank** [cocos2d/cocos2d-x#18761]
- Use cocos2dx 3.14.1 & 3.15 & 3.16.
- iOS 11.3 only problem.(or later?)

Steps to Reproduce:
1. CocosDenshion::SimpleAudioEngine::getInstance()->setEffectsVolume(0.0f);
2. CocosDenshion::SimpleAudioEngine::getInstance()->playEffect(“se.wav”);
The SE will sound.

I think I will use "AudioEngine".

**Comment by slackmoehrle** [comment]
I can reproduce this with `SimpleAudioEngine`.

**Comment by huangwei1024** [comment]
I encounter this problem. you can use `SimpleAudioEngine::playEffect(const char* pszFilePath, bool bLoop, loat pitch, float pan, float gain)` with `gain=0` bypass the bug.

**Comment by huangwei1024** [comment]
```
- (void) setMasterGain:(ALfloat) newGainValue {
    if (mute_) {
        _preMuteGain = newGainValue;
    } else {    
        alListenerf(AL_GAIN, newGainValue);
    }    
}
```

I step into `cocos2d-x\cocos\audio\ios\CocosDenshion.m`, the `newGainValue=0.0` is correct, but the `alListenerf` no any effect. so I think the openAL need be upgrade.

**Comment by lzubiaur** [comment]
Same issue here with `SimpleAudioEngine`. Again only since iOS 11.3.
Settings the sound volume to a very low value (e.g. `FLT_MIN`) will "mute" the sound effects but `0.0f` won't work.

**Comment by ct1676** [comment]
Had the same problem,  I set the sound effects 0.001f to reduce the issue
