### ISSUE TITLE
Can't build android. Execution failed for task ':generateJsonModelDebug'.

### ISSUE THREAD

**Issue by xahon** [cocos2d/cocos2d-x#18769]
- cocos2d-x version: 3.16
- devices test on: Ubuntu 16.04.3 / Android 7.0
- developing environments
   - NDK version: 16.1.4479499
   - Xcode version: - 
   - VS version: - 
   - browser type and version: Chrome 64.0.3282.167 (64-bit)

Steps to Reproduce:

1. cd ./proj.android-studio
2. ./gradlew installDebug

I also tried `cocos compile -p android --android-studio` and the output is similar:

> Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':MyGame:**generateJsonModelDebug**'.] from daemon DaemonInfo{pid=30011, address=[8d24e913-ad79-4f14-9106-79ca6d74ad9b port:40839, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1523267414942, context=DefaultDaemonContext[uid=0ec6a2d4-d0c4-4b8b-81c1-2b06a8699a48,javaHome=/usr/lib/jvm/java-8-openjdk-amd64,daemonRegistryDir=/home/ilya/.gradle/daemon,pid=30011,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).

And in android studio the same error

**Comment by xahon** [comment]
Is this magic issue? Am I the only one who has this?

**Comment by drelaptop** [comment]
Using android studio, you can find the detail errors in Gradle Console, AFAIK, when you use 3.16 version, and update the NDK to 16, you will get some compiling errors to fix.

**Comment by xahon** [comment]
@drelaptop what is the most stable version of cocos and NDK I can use to avoid compilation errors?

**Comment by drelaptop** [comment]
### use the tested NDK version

3.16 <-> NDK r14
GitHub latest <-> NDK r16

refer to http://www.cocos2d-x.org/docs/cocos2d-x/en/installation/prerequisites.html

**Comment by xahon** [comment]
nooo. I have successfully compiled and NDK is not the reason. My scene class was named `MainGameScene.cpp/h` instead of `HelloWorldScene.cpp/h` and it was in subdirectory within `Classes`. Moving them to upper level and renaming solved my issue but ...

I need to add all paths to my `cpp`s into `cocos/Android.mk` and rename all includes in it to be relative instead of absolute from `Classes`. A lot of work. I have no mac and I already expect a big number of similar problems

**Comment by drelaptop** [comment]
Why add `cpp`s into `cocos/Android.mk`? I guess you should add your `cpp`s into `proj.android\app\jni\Android.mk`.

`cocos/Android.mk` is the engine core module.

**Comment by drelaptop** [comment]
today same issue occurs to me, it trouble me for hours. Finally I found the reason is __dirty__ build folder. 

Some older build files existed at my template folder, (maybe I build `lua-template` directly in template folder), so that I run `cocos new -l lua`, and then run `cocos compile -p android --build-type cmake`.  At this step, `generateJsonModelDebug FAILED` occurred. after I deleted `proj.android/.gradle`, `proj.android/.idea` and all others different the origin `proj.android`. this issue was solved.

Hope this will help you @xahon 

> By the way, import the project into Android Studio, click `Build/Refresh Linked C++ Projects` will solve this too.

**Comment by gitcalculus** [comment]
I get the same issue. 
And [this answer](https://stackoverflow.com/questions/54500937/cocos2d-x-android-build-failed) save my day.
`generateJsonModelDebug` is not real error. Error is CMake error: not find [`Ninja`](https://github.com/ninja-build/ninja).
And build & run on device succeed with cocos2d-x-3.17.1 & NDK r17b.

**Comment by ghost** [comment]
update ndk to r16e ,it worked~
