### ISSUE TITLE
Android.mk contains useless "tagged" comments?

### ISSUE THREAD

**Issue by gestern** [cocos2d/cocos2d-x#18778]
What is the need for the Andorid.mk to use the following comments:

- ``# _COCOS_HEADER_ANDROID_BEGIN``
- ``# _COCOS_HEADER_ANDROID_END``
- ``# _COCOS_LIB_ANDROID_BEGIN``
- ``# _COCOS_LIB_ANDROID_END``
- ``# _COCOS_LIB_IMPORT_ANDROID_BEGIN``
- ``# _COCOS_LIB_IMPORT_ANDROID_END``

Unfortunately I could not find any documentation on these "tags"? Are they still in use? If so, where? If not - let's delete them, they just confuse the developers.

**Comment by drelaptop** [comment]
those tags was used on __cocos2d-console__

**Comment by gestern** [comment]
For what needs? Are there any links to the code or documentation where can read about it?

**Comment by drelaptop** [comment]
this is the link to the code

https://github.com/cocos2d/cocos2d-console/blob/03d1f8d291ed63439918fa4b180c7b9d698a2bfd/plugins/plugin_package/helper/add_framework_helper.py#L39
