### ISSUE TITLE
因为Cocos2dSound.java的线程问题，准备把audioengine加入2.2.6版本

### ISSUE THREAD

**Issue by JammeLee** [cocos2d/cocos2d-x#18772]
- cocos2d-x version: 2.2.6
- devices test on:
- developing environments
   - NDK version: r9d
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

把3.x版本的audio模块加入2.2.6版本，使用r9d编译的时候，报错提示找不到SLES/OpenSLES.h，不知道这种做法对不对，如果可以的话，不知道应该怎么处理这个错误。

```
/cocos2dx/audio/android/../../audio/android/AudioEngine-inl.h:29:27: fatal error: SLES/OpenSLES.h: No such file or directory
compilation terminated.
make.exe: *** [obj/local/armeabi/objs/audioengine_static/AudioEngine-inl.o] Error 1
```

**Comment by Anywhere-Music-Player** [comment]
Непонял? Почему не на английском? Уважайте других.

**Comment by slackmoehrle** [comment]
@KAMIKAZEUA Please stop trolling. Seriously. Our teams communicate in English and Chinese. There is no disrespect here. If I have to ask you again I will ban you from our repos just as you were ban from our forums. Please e-mail me if you have concerns.

**Comment by drelaptop** [comment]
@JammeLee not a bug, please discuss this at Chinese forum http://forum.cocos.com/c/cocos2d-x
