### ISSUE TITLE
Failed to connect to socketio 2.0 server.

### ISSUE THREAD

**Issue by zw1988** [cocos2d/cocos2d-x#18770]
cocos2d: fullPathForFilename: No file found at script/jsb_prepare.jsc. Possible missing file.
cocos2d: fullPathForFilename: No file found at script/jsb_boot.jsc. Possible missing file.
Cocos2d-JS v3.16
2018-04-10 19:40:35.560565+0800 js-tests iOS[26606:31301633] cocos2d: surface size: 1136x640
cocos2d: QuadCommand: resizing index size from [-1] to [2560]
JSB SocketIO.connect method called
Calling native SocketIO.connect method
In the constructor of HttpClient!
JSB SocketIO.on method called
JSB SocketIO eventName to: 'connect'
JSB SocketIO.on method called
JSB SocketIO eventName to: 'message'
JSB SocketIO.on method called
JSB SocketIO eventName to: 'echotest'
JSB SocketIO.on method called
JSB SocketIO eventName to: 'testevent'
JSB SocketIO.on method called
JSB SocketIO eventName to: 'disconnect'
2018-04-10 19:41:17.344848+0800 js-tests iOS[26606:31302335] Starting to load http://192.168.1.33:3000/socket.io/1/?EIO=2&transport=polling&b64=true
2018-04-10 19:41:17.432799+0800 js-tests iOS[26606:31302335] Received response from request to url http://192.168.1.33:3000/socket.io/1/?EIO=2&transport=polling&b64=true
D/WebSocket.cpp (415): WebSocket thread start, helper instance: 0x6040002aaf20
D/WebSocket.cpp (167): NOTICE: Initial logging level 911

D/WebSocket.cpp (167): NOTICE: Libwebsockets version: 2.1.0 james@James-Chen.local-v3.4-139-gbdcf7f8

D/WebSocket.cpp (167): NOTICE: IPV6 compiled in and enabled

D/WebSocket.cpp (167): NOTICE: libev support not compiled in

D/WebSocket.cpp (167): NOTICE: libuv support not compiled in

D/WebSocket.cpp (167): NOTICE:  Threads: 1 each 2560 fds

D/WebSocket.cpp (167): NOTICE:  mem: platform fd map: 20480 bytes

D/WebSocket.cpp (167): NOTICE:  Compiled with OpenSSL support

D/WebSocket.cpp (167): NOTICE:  mem: per-conn:          512 bytes + protocol rx buf

D/WebSocket.cpp (873): scheme: ws, host: 192.168.1.33, port: 3000, path: /socket.io/1/websocket/96
D/WebSocket.cpp (167): NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 on

D/WebSocket.cpp (167): NOTICE: lws_protocol_init

D/WebSocket.cpp (1322): WebSocket (0x7fde3f70f870) Unhandled websocket event: 32
D/WebSocket.cpp (1322): WebSocket (0x7fde3f70f870) Unhandled websocket event: 29
D/WebSocket.cpp (1322): WebSocket (0x7fde3f70f870) Unhandled websocket event: 24
D/WebSocket.cpp (1197): WebSocket (0x7fde3f70f870) onConnectionError, state: 0 ...
D/WebSocket.cpp (1226): WebSocket (0x7fde3f70f870) onConnectionClosed, state: 2 ...
D/WebSocket.cpp (1256): onConnectionClosed, WebSocket (0x7fde3f70f870) is closing by server.
D/WebSocket.cpp (1279): WebSocket (0x7fde3f70f870) onConnectionClosed DONE!
D/WebSocket.cpp (1322): WebSocket (0x7fde3f70f870) Unhandled websocket event: 45
Websocket error received: 1
JSB SocketIO::SIODelegate->onClose method called from native
JSB SocketIO::SIODelegate->fireEventToScript method called from native with name 'disconnect' data: 
D/WebSocket.cpp (1322): WebSocket (0x7fde3f70f870) Unhandled websocket event: 33
Test Client disconnected!
D/WebSocket.cpp (545): In the destructor of WebSocket (0x7fde3f70f870)
D/WebSocket.cpp (565): before join ws thread
D/WebSocket.cpp (167): NOTICE: lws_context_destroy

D/WebSocket.cpp (425): WebSocket thread exit, helper instance: 0x6040002aaf20
D/WebSocket.cpp (567): after join ws thread

**Comment by WangJiaChun930** [comment]
I have same problem.
Who can help me?

**Comment by PatriceJiang** [comment]
this issue is fixed in https://github.com/cocos2d/cocos2d-x/pull/18936, @minggo
