### ISSUE TITLE
CCConesole.cpp will not compile with C++17 and clang

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#18781]
- cocos2d-x version: 3.15 and 3.16
- devices test on: N/A
- developing environments
   - NDK version: r16b
   - Xcode version: N/A
   - VS version: 2017
   - browser type and version: N/A

Steps to Reproduce:

1. In Application.mk for Android Studio compilation, add -std=c++1z to APP_CPPFLAGS.
2. Set "NDK_TOOLCHAIN_VERSION=clang" in build.gradle
2. Compile...

cocos2d/cocos/./base/CCConsole.cpp:219:72: error: no member named 'ptr_fun' in namespace 'std'
      s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::ptr_fun<int, int>(std::isspace))));

std::ptr_fun no longer exists, and std::not1 is deprecated in C++17.

To fix the issue, replace the:

std::not1(std::ptr_fun<int, int>(std::isspace))

with a lambda function, as follows:

[](int c) {return !std::isspace(c);}

Refer to this for more info:
https://stackoverflow.com/questions/44973435/stdptr-fun-replacement-for-c17

**Comment by drelaptop** [comment]
cocos team didn't adapt the code to c++17 yet, most of the code is compiled by c++11.

**Comment by rh101** [comment]
@drelaptop I can see that they haven't updated the code to support  C++17 yet, otherwise I wouldn't have had any compilation issues. ;-)

std::ptr_fun was deprecated in C++11, and removed in C++17, yet it's still being used in that section of the Cocos2d-x code.  It's a simple fix too, as indicated in my original post.

**Comment by drelaptop** [comment]
thanks for mention it, I will submit a PR to fix this.
