### ISSUE TITLE
打包出来的APK安装在android模拟器上面接受不到按键事件问题

### ISSUE THREAD

**Issue by yunmin97** [cocos2d/cocos2d-x#18788]
- cocos2d-x version:  3.15
- devices test on:  MuMu模拟器等模拟器
- developing environments
   - NDK version:  r10d
   - Xcode version: 无
   - VS version:  2015

Steps to Reproduce:
1. 打包apk
2. 安装到android模拟器或者接外部键盘的android设备，测试发现onKeyPressed(EventKeyboard::KeyCode keycode, cocos2d::Event *event)只能接受到： 
        KEY_DPAD_LEFT,（对应键盘上的“左”键）
        KEY_DPAD_RIGHT,（对应键盘上的“右”键）
        KEY_DPAD_UP,（对应键盘上的“上”键）
        KEY_DPAD_DOWN,（对应键盘上的“下”键）
        KEY_ENTER，（对应键盘上的“Enter”键）
        KEY_ESCAPE，（对应键盘上的“Esc”键）
这些事件，其他的事件接受不到（按其他任何按键onKeyPressed都接收不到消息!）
3.在windows上什么按键事件都正常.

请问：
1. android模拟器上面的按键是怎么对应的？
2. android模拟器上面能触发的键盘按键有哪些？
3. 现在游戏apk想安装到TV机顶盒（其实就是运行android模拟器的TV机顶盒）上面玩耍，请问案件应该怎么处理？
4. 现在cocos2dx开发的游戏有没有发布到TV上面的产品？2cocos2dx 3.15版本的支持吗？

**Comment by drelaptop** [comment]
[game-controller-test](https://github.com/cocos2d/cocos2d-x/tree/v3/tests/game-controller-test) 完成的任务是监听游戏手柄的事件，可以参考。
[game-controller-test](https://github.com/cocos2d/cocos2d-x/tree/v3/tests/game-controller-test)  is to monitor the events of the gamepad. please refer to it.

建议到中文社区讨论，传送：http://forum.cocos.com/c/cocos2d-x

**Comment by drelaptop** [comment]
[game-controller-test](https://github.com/cocos2d/cocos2d-x/tree/v3/tests/game-controller-test) 完成的任务是监听游戏手柄的事件，可以参考。
[game-controller-test](https://github.com/cocos2d/cocos2d-x/tree/v3/tests/game-controller-test)  is to monitor the events of the gamepad. please refer to it.

建议到中文社区讨论，传送：http://forum.cocos.com/c/cocos2d-x

**Comment by yunmin97** [comment]
谢谢！！
