### ISSUE TITLE
Outdated cmake build script on performance-tests 

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18796]
- cocos2d-x version: git
- devices test on: linux mint 18.3

Steps to Reproduce:

1. try to compile performance-tests
2. get error about unsupported platform (and see win10 project)
3. copy CMakesLists.txt and proj.linux
4. try again and get another error:

       CMake Error at /home/v/compile/cocos2d-x/cmake/Modules/CocosBuildHelpers.cmake:222 (add_executable):
       Cannot find source file:
       
           Classes/AppMacros.h

**Comment by drelaptop** [comment]
thanks for mention this, when I updated the cmake build script, I only update 5 test projects(cpp-empty-test, cpp-tests, js-tests, lua-empty-test, lua-tests) and 3 template projects(cpp-template, js-template, lua-template), others not.

**Comment by drelaptop** [comment]
developers can implement this refer to other 5 tests project.
