### ISSUE TITLE
Add a setMaterial function to PhysicsBody

### ISSUE THREAD

**Issue by xerosugar** [cocos2d/cocos2d-x#18800]
- cocos2d-x version: 3.16

In the constructor for PhysicsBody you can set offset and material:
```auto b = PhysicsBody::createPolygon(pts.data(), pts.size(), PHYSICSBODY_MATERIAL_DEFAULT, Vec2(0,0))```
and you can later change the offset through `setPositionOffset` but there's no similar method for setting the material. I'd like to see a 'setMaterial' or similar.

**Comment by PatriceJiang** [comment]
Since `_material` is a field of `PhysicsShape` and multiple shapes may co-exist in one `PhysicsBody`, 
it should be updated through methods like 
```cpp
auto b = PhysicsBody::createPolygon(...);
b->getFirstShape()->setMaterial(...);
```
We don't need a new `setMaterial` method on `PhysicsBody`.

**Comment by minggo** [comment]
There already has the method: https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/physics/CCPhysicsShape.cpp#L107
