### ISSUE TITLE
Firebase BoringSSL compatibility issue

### ISSUE THREAD

**Issue by kiranb47** [cocos2d/cocos2d-x#18805]
Hey guys,
There is a issue with firebase integration. Please check the following link. It will be great if you guys can do anything to resolve it.

https://github.com/firebase/firebase-ios-sdk/issues/1216

**Comment by gsoltis** [comment]
See https://github.com/grpc/grpc/issues/6111 for the underlying issue, it's a gRPC compatibility problem in general, not specific to Firebase or Firestore.

**Comment by drelaptop** [comment]
from the discuss above, I think it's not a cocos2d-x issue, just close it. Reopen if you disagree @kiranb47
