### ISSUE TITLE
(android) CCFileUtils::getWriteablePath() doesn't work on MultiUser environment

### ISSUE THREAD

**Issue by moadib** [cocos2d/cocos2d-x#1880]
Currently cocos2d-x returns hardcoded path and it is not works for multiple users.

Look here http://developer.android.com/about/versions/android-4.2.html#MultipleUsers

**Comment by dumganhar** [comment]
@moadib
Cocos2d-x now uses `pContext.getCacheDir().getAbsolutePath();` to get the writable path.

<pre>
Saving data in a multi-user environment
Whenever your app saves user preferences, creates a database, or writes a file to the user’s internal or external storage space, that data is accessible only while running as that user.
To be certain that your app behaves properly in a multi-user environment, do not refer to your internal app directory or external storage location using hard-coded paths and instead always use the appropriate APIs:
For access to internal storage, use getFilesDir(), getCacheDir(), or openFileOutput().
For access to external storage, use getExternalFilesDir() or getExternalStoragePublicDirectory().
No matter which of these APIs you use to save data for a given user, the data will not be accessible while running as a different user. From your app’s point of view, each user is running on a completely separate device.
</pre>

So `pContext.getCacheDir().getAbsolutePath();` will return unique path even if in Multi-User environment?

**Comment by moadib** [comment]
Oh, missed https://github.com/cocos2d/cocos2d-x/commit/bd6aa9844551e3cc22a5c971864698671af00af9 :) Yep, with this approach everything must be ok :)
