### ISSUE TITLE
Add Android P cutout (aka notch) support

### ISSUE THREAD

**Issue by mars3142** [cocos2d/cocos2d-x#18810]
I just want to add a reminder, that Android P will support natively cutouts and every game, which target is below P will have reduced screen sizes.

So the framework should be Android P ready, if the final SDK will be released and someone can upload new and updated apps to the PlayStore.

**Comment by piotrros** [comment]
Maybe we can use `Director::getSafeAreaRect()` for it?

**Comment by mars3142** [comment]
We should use it, but the current targetSDK isn't an integer, so it can't included into the v3 branch until the Android P SDK is final.

**Comment by mars3142** [comment]
Since yesterday the Android API 28 is final, so we are able to implement it into the framework.

**Comment by gestern** [comment]
Guys, I've implemented this functionality for Android (Including deep support of Android P), the details will be later, now I'm testing on devices

**Comment by drelaptop** [comment]
thanks for @gestern contribution, refer to https://github.com/cocos2d/cocos2d-x/pull/19043 discuss if you have doubt.

**Comment by formatCvt** [comment]
hmm, looks like only rounded corners support added not cutout
