### ISSUE TITLE
Failed to generate v1 signature (gen-libs -p android)

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18811]
- cocos2d-x version: git
- devices test on: linux mint 18.3 (build machine)
- developing environments
   - NDK version: android-ndk-r17
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Run `cocos gen-libs -p android -m release --ap android-16 --app-abi armeabi-v7a`
2. get error:

 

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':CppEmptyTest:packageRelease'.
    > Failed to generate v1 signature

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 3s
    59 actionable tasks: 4 executed, 55 up-to-date
    Error running command, return code: 1.
    Error running command, return code: 14.

**Comment by drelaptop** [comment]
this issue have been fixed at https://github.com/cocos2d/cocos2d-console/pull/440, and have been updated into cocos2d-x, so close this issue.

further discuss at  https://github.com/cocos2d/cocos2d-x/pull/18787
