### ISSUE TITLE
assert error when using listFilesRecursively on win10

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x#18835]
- cocos2d-x version: GitHub latest
- devices test on: Windows 10

https://github.com/cocos2d/cocos2d-x/pull/18833 added a test case on cpp-empty-project, when tested on win10, assert error, code:
```
    std::vector<std::string> icons;
    fileutils->listFilesRecursively("icons", &icons);
```
research the code, found `std::string fullpath = fullPathForFilename(dirPath);` return empty string when `dirPath` is a folder name

console log,
```
cocos2d: fullPathForFilename: No file found at icons. Possible missing file.
Assert failed: Invalid path
Assertion failed!

Program: ...-x\build\Debug.win32\cpp-empty-test\libcocos2d.dll
File: f:\cocos2d-x\cocos\platform\ccfileutils.cpp
Line: 1079

Expression: !dirPath.empty()
```
`icons` is a folder name, and located at `Debug.win32\cpp-empty-test\icons`, path is right.

**Comment by v1993** [comment]
Just to mention: test from #18833 is temporary limited only to linux due to this bug.

**Comment by PatriceJiang** [comment]
This issue is fixed in https://github.com/cocos2d/cocos2d-x/pull/19044/files#diff-cb65223cd3edf30671fefad4a1883edf  and can be closed. @drelaptop
