### ISSUE TITLE
reduce the 3D effect when only using 2D feature

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x#18840]
- cocos2d-x version:3.17

for not any members in cocos2d-x team to maintain the 3D feature yet

-----------updated--------

**Thanks for feedback, what we should do is to reduce the 3D effect when only using 2D feature, NOT remove 3D**

**Comment by crookedbard** [comment]
3D features works great in cocos, why to remove them?

**Comment by drelaptop** [comment]
thanks for telling this. 

some developers only using 2D feature in cocos2d-x, hold a idea that 3D have a bad effect on 2D performance.

**Comment by gestern** [comment]
@drelaptop What kind of bad effect do you say now? Can you give more details?

**Comment by Dimon4eg** [comment]
I think it's mostly compile time and binary size.

In ccConfig.h there are config defines for physics:
CC_USE_PHYSICS
CC_USE_3D_PHYSICS

For 2D game would be good to cut off 3D part also.

**Comment by gestern** [comment]
Good idea!

**Comment by umitgoren** [comment]
It should be improved in v4. Why should we use Unity3D?

**Comment by Dimon4eg** [comment]
@umitgoren Unity3D?

**Comment by umitgoren** [comment]
@Dimon4eg If 3D is removed some Cocos2d-x users will prefer Unity3D for its advanced 3D features.

**Comment by Dimon4eg** [comment]
No, I propose to add define to ccConfig.h for 3D part of engine.
If define is 0 then 3D part is disabled.

**Comment by drelaptop** [comment]
@gestern another possible reason is about the performance, the cocos2d-x without 3D added own a better performance than cocos2d-x with 3D added, when only use 2D feature. This need to be tested and proved, I can't make sure. 

thanks @Dimon4eg , we should reduce the 3D effect when only using 2D feature in deed.

**Comment by ghost** [comment]
I'm disposed to agree with @Dimon4eg , add define to `ccConfig.h` for 3D part of cocos2d-x.

```
#define CC_USE_3D 0
```

And as I know, some guys are developing 3D for [Creator](https://github.com/cocos-creator/cocos2d-x-lite). So please do not remove the 3D of cocos2d-x but add 3D to [Creator](https://github.com/cocos-creator/cocos2d-x-lite).
