### ISSUE TITLE
Typo in cocos_find_prebuilt_lib_by_name

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#18845]
- cocos2d-x version: 3.17
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

In CocosBuildHelpers.cmake:

Function: cocos_find_prebuilt_lib_by_name

message(STATUS "find cocos prebuilt library: ${found_lib}")

should be

message(STATUS "found cocos prebuilt library: ${found_lib}")

The text in the logs from this function is misleading, since it's implying it's finding something, rather than it's found something.

**Comment by drelaptop** [comment]
thanks, I will correct it @rh101
