### ISSUE TITLE
Can not access http://discuss.cocos2d-x.org/

### ISSUE THREAD

**Issue by Priority10** [cocos2d/cocos2d-x#18859]
I know that github is not the place for such questions, but since I can not access the en forum... so this is the only option for me. I will close the issue later.

When I try to access the site http://discuss.cocos2d-x.org/ I get this

> This site can’t be reached
> The connection was reset.
> ERR_CONNECTION_RESET.

Sometimes I can access, but 99% of the time I can not. It started about a month ago.
What is it? USA Sanctions? The last time I checked I was not on the sanctions list. :)

Maybe this is somehow connected with the fact that the Russian government is trying to block Telegram. And ip of the forum now in the blocked list. I am not sure.

@slackmoehrle Please, help.

**Comment by v1993** [comment]
@Priority10 I don't have any problems, but use TOR and can't access http://discuss.cocos2d-x.org/ without it (I'm almost sure that it is russian-specific block). Can you also try TOR, please?

**Comment by Priority10** [comment]
@v1993  Probably I will use Tor (never used it before) or some vpn services, if @slackmoehrle  can not do some admin magic. Other forums that using discourse.org work for me, so I thought it is something specific to this forum.
and for Russia of course. Thank Roskomnadzor. : /

**Comment by Priority10** [comment]
So, it is been 6 days, and there is no response.
I am beginning to seriously think that this is like local anti-Russian sanctions.

@minggo @drelaptop Could you get any comment from @slackmoehrle , please?

**Comment by drelaptop** [comment]
@Priority10 In China I can access http://discuss.cocos2d-x.org/ in my apartment, but recently I can't access it until some VPN service is enabled in office. Probably because of different network service provider or something special. I don't know why. Do you know something about it @slackmoehrle ?

**Comment by slackmoehrle** [comment]
@Priority10 According to Discourse you haven't been on the forums since Feb 10, 2018

<img width="377" alt="screen shot 2018-06-03 at 10 18 19 am" src="https://user-images.githubusercontent.com/7491758/40887478-892a5b24-6717-11e8-95f6-fe534831f18a.png">

The ERR you are getting is weird. What country are you in? Perhaps their are local blocking issues, this why TOR was mentioned or a VPN. We host the forums at Digital Ocean in the USA. Some specific reasons I found could be:

Your internet connection proxy server may be disable that’s why you face the error.
    
Internet IP address may be blocked that’s created this error 101.
    
Sometimes old registry, firewall and antivirus block the connection and create this type of error.

Wi-Fi power cycle and ISP firewall also block the internet connection and create this type of DNS error.

Has this started since GDPR went in to effect?

And Oh, Telegram. Sorry how are you using Telegram? Perhaps there are blocks in place. We were receiving some unwanted traffic so perhaps an IP was blocked that is common amongst the ways users are trying to access our site.

**Comment by Priority10** [comment]
@drelaptop Thanks for the reply! It is strange that you have this problem, too.

@slackmoehrle In fact, I check the forum several times a week, I just do not log in. :p

> Your internet connection proxy server may be disable that’s why you face the error.
> 
> Internet IP address may be blocked that’s created this error 101.
> 
> Sometimes old registry, firewall and antivirus block the connection and create this type of error.
> 
> Wi-Fi power cycle and ISP firewall also block the internet connection and create this type of DNS error.
> 
> Has this started since GDPR went in to effect?

Nope. Nope. Nope. Nope. Nope.

> And Oh, Telegram. Sorry how are you using Telegram?

I do not use Telegram, but when I googled the reasons why the forum is not available in Russia, I accidentally found the news about the blocking of Telegrams and many other sites along with it. Now when you mentioned Digital Ocean, I found that likely the reason is really in this blocking.

I do not know if this will help, but I found this
https://twitter.com/digitalocean/status/986633645963337731
Can you do something about this?

**Comment by slackmoehrle** [comment]
We already use a floating IP from DO so we can't change IP's like that.  So you can access the forums unless you need to login?

**Comment by Priority10** [comment]
@slackmoehrle What is DO?
OK, I used to read the forum several times a week in the past, but now it is just not available to me 99 percent of the time. And like I said 

> It started about a month ago.

Since the Telegram and some of the Digital Ocean ips were blocked on April 17-18, I am 99 percent sure that now the forum is not available to ALL users from Russia. I do not know if you care about this category of users, but.. okay, I just hope that you can somehow fix this for me.))

**Comment by slackmoehrle** [comment]
> not available to ALL users from Russia.

There are users from Russia on the forums every day.

If there is an IP block someplace, I am not sure how I would solve this. I dont know anything about Telegram or how it is used or what people use it for.

**Comment by Priority10** [comment]
I think that they use VPN or something like that. In fact, now you have more opportunities to ask them than I do.
And as @v1993  said the forum is not available to him without Tor.

About Telegram

It is a messenger with special attention to privacy.
It something did not please the Russian government (I do not know and I do not care) and they decided to block it (I do not care), BUT together with Telegram they blocked the whole subnets of the Digital Ocean (they do not care), as a result many sites inaccessible in Russia. : /

So the forum is now dead to me and many others, most likely forever, and you can not do anything, right?

**Comment by slackmoehrle** [comment]
@Priority10 if Digital Ocean has blocked IP's, I can surely create a ticket and ask. Perhaps they can allow a hole to access our forums. I honestly don't know how this type of thing goes. 

Edit: I have opened a support request.

**Comment by slackmoehrle** [comment]
Digital Ocean replied with:
```
Thank you for contacting DigitalOcean Support.

We're aware of a disruption in traffic from some areas in Russia to some of our data centers. It appears that traffic has been blocked at some other point in the Internet, which is beyond our control. All circuits into these data centers are fully functional.
```
So it looks like it is out of our hands for now.

**Comment by Priority10** [comment]
@slackmoehrle 
Ok, Thanks for trying. )
I close the issue.

**Comment by alexander-koval** [comment]
Hello. I can't access to the forum http://discuss.cocos2d-x.org/. Whats wrong?
