### ISSUE TITLE
COCOS2D_DEBUG=1 is missing in Win32 MSVC debug build

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#18854]
- cocos2d-x version: 3.17
- devices test on: N/A
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: 2017 Community Edition
   - browser type and version:

Steps to Reproduce:

1. As per the CMake Cocos2d-x guide, run:
cmake .. -G"Visual Studio 15 2017" -Tv141

2. Open the solution file in VS, and you will notice that for the debug build COCOS2D_DEBUG is not defined at all.

The problem is in file:    CocosCompileOptions.cmake

"-DCOCOS2D_DEBUG=1" is missing for the MSVC debug configuration, yet it exists for all other platforms and build environments, as you can see in the CMake snippet below.

CMAKE_C_FLAGS_DEBUG has DCOCOS2D_DEBUG=1, then this is copied to CMAKE_CXX_FLAGS_DEBUG, but when it checks for "if(MSVC)", it overwrites the CMAKE_CXX_FLAGS_DEBUG with this:

`set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} /MDd")`

which effectively deletes all previous additions to the list.

I presume this is an error, and it should be 

`set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MDd")`

and maybe do this too:
```
     if(CMAKE_BUILD_TYPE STREQUAL "Debug")
         add_definitions(-DCOCOS2D_DEBUG=1)
     endif()

```

Here is the faulty section of the CMake file:

```
*** NOTE **** both of these "set" lines are pointless, since they are overwritten in the conditional statements below them...
 set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -DCOCOS2D_DEBUG=1")    
 set(CMAKE_CXX_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG})

 # Compiler options
 if(MSVC)

     set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} /MDd")   <== HERE IS THE PROBLEM
     set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} /MD")
     set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} /NODEFAULTLIB:msvcrt /NODEFAULTLIB:libcmt")
     set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /NODEFAULTLIB:libcmt")

     .....

 else()
     if(CMAKE_BUILD_TYPE STREQUAL "Debug")
         add_definitions(-DCOCOS2D_DEBUG=1)
     endif()
     set(CMAKE_C_FLAGS_DEBUG "-g -Wall")
     set(CMAKE_CXX_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG})

     .....
 endif(MSVC)
```

**Comment by drelaptop** [comment]
@rh101 could you review and test https://github.com/cocos2d/cocos2d-x/pull/18856 ? 

that PR fix this issue, and clear `set compile options` and `set macro definitions`.

**Comment by rh101** [comment]
@drelaptop Sure, I'll test today.

One more thing, at the moment optimizations are turned on for the debug build, which means you cannot step through the source properly if debugging.  I've turned it on in the game CMakeLists.txt, so it's not an issue, but in case you want it enabled in the compiler options, then add the /Od flag to the CMAKE_CXX_FLAGS_DEBUG in the MSVC section too:

set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /Od")

**Comment by rh101** [comment]
@drelaptop I tested both the Android build with Android Studio, and Win32 build with Visual Studio 2017, and they both seem to work fine with the changes you've made in #18856
