### ISSUE TITLE
[Windows / Android Studio] long file path cause build errors

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x#18867]
- cocos2d-x version: 3.17
- devices test on: empty lua project by `cocos new` generate
- developing environments
   - Android Studio
- build by Android.mk

error logs like:
```
E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/jni/../../../../cocos2d-x/cocos/../external/bullet/include/bullet\LinearMath/btHashMap.h:20:10: fatal error: 'btAlignedObjectArray.h' file not found
  #include "btAlignedObjectArray.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~
  [armeabi-v7a] Compile++ arm  : cocostudio_static <= CCDisplayManager.cpp
  In file included from E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/jni/../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../manual/physics3d/lua_cocos2dx_physics3d_manual.cpp:33:
  In file included from E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/jni/../../../../cocos2d-x/cocos/3d/..\physics3d/CCPhysics3D.h:55:
  In file included from E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/jni/../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../../../../external/bullet/prebuilt/android/../../include\bullet/btBulletCollisionCommon.h:35:
  In file included from E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/jni/../../../../cocos2d-x/cocos/../external/bullet/include/bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h:22:
  In file included from E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/jni/../../../../cocos2d-x/cocos/../external/bullet/include/bullet/BulletCollision/CollisionShapes/btTriangleInfoMap.h:20:
  E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/jni/../../../../cocos2d-x/cocos/../external/bullet/include/bullet\LinearMath/btHashMap.h:20:10: fatal error: 'btAlignedObjectArray.h' file not found
  #include "btAlignedObjectArray.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  make: *** [E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/cocos2d_lua_static/__/auto/lua_cocos2dx_physics3d_auto.o] Error 1
  make: *** Waiting for unfinished jobs....
  1 error generated.
  make: *** [E:/cocos/cocos2d-x-3.17/projects/LuaDemo2/frameworks/runtime-src/proj.android/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/cocos2d_lua_static/__/manual/physics3d/lua_cocos2dx_physics3d_manual.o] Error 1
```
move project folder `LuaDemo2` into `E:/`, errors disappear. but it's unfriendly.

**Comment by drelaptop** [comment]
Another developer report this, this is a bad design to own so depth path for external header files， especially for JS & Lua project.

```
[armeabi-v7a] Compile++ arm : cocos2d_js_static <= jsb_cocos2dx_extension_auto.cpp
In file included from E:/HocTap/CocosJsWorkspaces/DownloadResources/frameworks/runtime-src/proj.android/app/jni/…/…/…/…/cocos2d-x/cocos/scripting/js-bindings/proj.android/…/auto/jsb_cocos2dx_3d_auto.cpp:1:
In file included from E:/HocTap/CocosJsWorkspaces/DownloadResources/frameworks/runtime-src/proj.android/app/jni/…/…/…/…/cocos2d-x/cocos/3d/…\scripting/js-bindings/auto/jsb_cocos2dx_3d_auto.hpp:5:
E:/HocTap/CocosJsWorkspaces/DownloadResources/frameworks/runtime-src/proj.android/app/jni/…/…/…/…/cocos2d-x/cocos/scripting/js-bindings/proj.android/…/…/…/…/external/spidermonkey/prebuilt/android/…/…/include/android\jsapi.h:12:10: fatal error: ‘mozilla/FloatingPoint.h’ file not found
```
 https://discuss.cocos2d-x.org/t/cocos2d-x-v3-17-released/42614/23

**Comment by crazyhappygame** [comment]
Is it new issue? I mean in new cocos2d-x.3.17 or new Ndk 16 ?

**Comment by drelaptop** [comment]
yep, a new issues, cocos2d-x 3.17  on Windows. 

It seems like errors occur when the file path is  more than 256 . A cocos2d-x user develop a tool to solve this issue, refer to https://discuss.cocos2d-x.org/t/the-solution-of-ndk-compile-system-longpaths-issue-on-windows-platform/42705

**Comment by Priority10** [comment]
I just want to hug @halx99 for it! :D

**Comment by crazyhappygame** [comment]
It seems like it can be improved by *_SHORT_COMMANDS. Please see:
https://developer.android.com/ndk/guides/android_mk
And what about "android cmake". Do we have the same issue?

**Comment by halx99** [comment]
@crazyhappygame I think it isn't the same issue, In our project, already set APP_SHORT_COMMANDS := true, but still can't compile LongPath source files.

**Comment by halx99** [comment]
The patch is update to v2.1: fix windows command pipe redirect do not support LongPath
https://github.com/halx99/wsLongPaths/

**Comment by drelaptop** [comment]
I found set `buildDir` is another solution, refer to the __answer 2nd__ of below link:

https://stackoverflow.com/questions/33905687/error-file-path-too-long-on-windows-keep-below-240-characters

**Comment by halx99** [comment]
ndk-r17 clang-6.0.x:
[ndk-wsls-2.2.1.zip](https://github.com/cocos2d/cocos2d-x/files/2382536/ndk-wsls-2.2.1.zip)

ndk-r16 clang-5.0.x:
[ndk-wsls-3.0.zip](https://github.com/cocos2d/cocos2d-x/files/2382537/ndk-wsls-3.0.zip)

**Comment by halx99** [comment]
I have download llvm and clang source code to do a little debug.
And find thus, the clang, both 5.0.x and 6.0.x will process windows long path, and add prefix ```R"(\\?\)"```, but the 5.0.x has a little bug for it.
such as 5.0.x will simply add prefix with out path qualified  ```R"(\\?\D:/xxx...)"```, but windows api need ```R"(\\?\D:\xxx...)"``` for a long path, so the ndk-r16b clang compile system will failed at this situation.

**Comment by drelaptop** [comment]
another side, I think the Gradle build config changes from 3.16

https://github.com/cocos2d/cocos2d-x/blob/f467d42e02d2b664731a45f9df39f13a01cfd1b5/templates/lua-template-default/frameworks/runtime-src/proj.android-studio/app/build.gradle#L24

into 3.17 

https://github.com/cocos2d/cocos2d-x/blob/5c381d8ee60078b1ff8380b794836ea61d4ed2ee/templates/lua-template-default/frameworks/runtime-src/proj.android/app/build.gradle#L18

increase the times "long path error" appeared, so that the error is so nervous on 3.17, not on 3.16.

commit this PR https://github.com/cocos2d/cocos2d-x/pull/19045 to correct it

**Comment by halx99** [comment]
Yes, it's good, but it's a workaround, I think. the real reason is Android NDK compile system not process windows long path well. it's a ndk compile system issue/bug. not cocos.

**Comment by drelaptop** [comment]
agree with you. that's a defect in Android NDK compile system. it's awful we have to adapt.

**Comment by drelaptop** [comment]
close this issue since we agree that it's a ndk compile system issue/bug. not cocos.

**Comment by Ahmad-Mustafaa** [comment]
any solution for built ndk-built i am stuck at this :(

**Comment by Ahmad-Mustafaa** [comment]
i have received theses error 2.2.2 ndk 21 any solution ?
wsls-copy: \\?\D:\android long path software\ndk-wsls-2.2.1\cc1plus.exe.bridge --> C:\Users\Amoda\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\libexec\gcc\arm-linux-androideabi\4.9.x\cc1plus.exe.bridge failed, error: 3
wsls-copy: \\?\D:\android long path software\ndk-wsls-2.2.1\wow64helper.exe --> C:\Users\Amoda\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\libexec\gcc\arm-linux-androideabi\4.9.x\wow64helper.exe failed, error: 3
wsls-copy: \\?\D:\android long path software\ndk-wsls-2.2.1\wsLongPaths.dll --> C:\Users\Amoda\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\libexec\gcc\arm-linux-androideabi\4.9.x\wsLongPaths.dll failed, error: 3
Installing patch for cc1plus.exe succeed.
Installing patch for collect2.exe...
wsls-copy: \\?\D:\android long path software\ndk-wsls-2.2.1\wsls-core.exe --> C:\Users\Amoda\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\libexec\gcc\arm-linux-androideabi\4.9.x\collect2.exe failed, error: 3
wsls-copy: \\?\D:\android long path software\ndk-wsls-2.2.1\collect2.exe.bridge --> C:\Users\Amoda\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\libexec\gcc\arm-linux-androideabi\4.9.x\collect2.exe.bridge failed, error: 3
wsls-copy: \\?\D:\android long path software\ndk-wsls-2.2.1\wow64helper.exe --> C:\Users\Amoda\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\libexec\gcc\arm-linux-androideabi\4.9.x\wow64helper.exe failed, error: 3
wsls-copy: \\?\D:\android long path software\ndk-wsls-2.2.1\wsLongPaths.dll --> C:\Users\Amoda\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\libexec\gcc\arm-linux-androideabi\4.9.x\wsLongPaths.dll failed, error: 3

**Comment by halx99** [comment]
well, the ndk patch was test on ndk-r14~r17, not test on r20+

**Comment by halx99** [comment]
install failed?

**Comment by halx99** [comment]
please post issue to  https://github.com/simdsoft/wsLongPaths

**Comment by Ahmad-Mustafaa** [comment]
> install failed?

some are installed fine or may be already installed 
but some shows these errors

**Comment by Ahmad-Mustafaa** [comment]
okay

**Comment by halx99** [comment]
Edit: the wsLongPaths, since v3.4, both cmake and ndk-build system(r14b~r21d) are supported on win7/win10 
New project url: https://github.com/simdsoft/wsLongPaths
