### ISSUE TITLE
CMake project still named "TemplateCpp" after using cocos tool

### ISSUE THREAD

**Issue by sergey-shambir** [cocos2d/cocos2d-x#18862]
- cocos2d-x version: 3.17
- devices test on: Desktop Linux - Ubuntu 18.04
- developing environments
   - NDK version: -
   - Xcode version: -
   - VS version: -
   - browser type and version: -

Steps to Reproduce:

1. Run `cocos new AnyGame -p org.AnyCompany.AnyGame -l cpp` to create project with cocos2dx command-line tool
2. Open `CMakeLists.txt`
3. Now you can see an issue: project named "TemplateCpp" instead of "AnyGame":

```
set(APP_NAME TemplateCpp)
project(${APP_NAME})
```

**Comment by drelaptop** [comment]
thanks for this feedback, the cocos tool only copy all the CMakeLists.txt files directly now, and this feature should be done in 3.18.
