### ISSUE TITLE
Open GL ES is deprecated in iOS 12

### ISSUE THREAD

**Issue by kiranb47** [cocos2d/cocos2d-x#18877]
Apps built using OpenGL ES will continue to run in iOS 12, but Open GL ES is deprecated in iOS 12. Games and graphics-intensive apps that previously used OpenGL ES should now adopt Metal.

https://developer.apple.com/ios/whats-new/#deprecationofopengles

Any plans cocos to adopt metal api?

**Comment by superrad** [comment]
If Metal support is added to cocos2dx it can't remove OpenGL ES support for older iOS devices.

Things like the iPhone 5, iPhone 5c and 2012 iPad support up to iOS 10 and don't support Metal. If Apple maintains their deprecation schedule of iOS versions (we're currently on iOS 11 and they still support iOS 8) when iOS 13 (the version after 12) it's likely that 10 will still be supported after OpenGL ES has been deprecated.
 
It would be preferrable to support both as I suspect there will be an overlap where both OpenGL ES and Metal devices will be supported and can download apps from the App Store.

Being able to dynamically select a renderer at start up based on capabilities of the device would be the best option for supporting as many devices as possible with a single App store build.

**Comment by gegegi** [comment]
minimum device that support iOS12 is 5s.
so OpenGL ES must be supported until the minimum target) is reached or exceeded 5s
Supporting metal is really a pleasure, but I do not think it is a top priority.

**Comment by kiranb47** [comment]
I think MoltenVK will be a solution. 
https://github.com/KhronosGroup/MoltenVK

**Comment by sp-dani-garcia** [comment]
Good opportunity to move to https://github.com/bkaradzic/bgfx like discussed here https://trello.com/c/B3M75FKd/133-grahpics-metal-render.

**Comment by slackmoehrle** [comment]
Thanks everybody for the input. As you can imagine this is news to us and we will need to decide how we handle this. I don't have any information or a plan of attack yet to share. Stay tuned.

**Comment by minggo** [comment]
Yep, we should start to support metal before OpenGL ES is removed. And we will keep OpenGL ES support as well since Android needs it too. And i think Android may deprecated OpenGL ES some time.

**Comment by vkreal** [comment]
Good to hear about path moving forward! @minggo what will replace OpenGL ES for Android?

**Comment by minggo** [comment]
I think OpenGL ES will be kept for a long time, we plan to support multi-backend.

**Comment by minggo** [comment]
I think we will choose vulkan.

**Comment by minggo** [comment]
metal is supported in `metal-support` branch
