### ISSUE TITLE
Sprite line thickness is strange. And then disappear (v3.17)

### ISSUE THREAD

**Issue by seventhrank** [cocos2d/cocos2d-x#18873]
https://discuss.cocos2d-x.org/t/the-thickness-of-the-line-falls-apart/42712

cocos2dx 3.17 (C++)
NDK r16b
Android 6.0 (huawei vns-l22)

I draw lines with Sprite.
After updating to v3.17, the thickness of lines become disjointed with some Android.
It is beautifully lined up in v3.14.1.

Sprite line code.
```
for (int x = 0; x <= size.width*0.5f; x++) {
	Rect rect_x = Rect( 0.0f, 0, 1.0f, 200.0f);
	Sprite* line_x = Sprite::create();
	line_x->setTextureRect( rect_x );
	line_x->setPosition( x*2 , 400);
	line_x->setAnchorPoint(Vec2::ANCHOR_TOP_LEFT);
	line_x->setOpacity(255);
	this->addChild(line_x);

	Rect rect_x2 = Rect( 0.0f, 0, 1.0f, 200.0f);
	Sprite* line_x2 = Sprite::create();
	line_x2->setTextureRect( rect_x2 );
	line_x2->setPosition( (x*2+1) , 800);
	line_x2->setAnchorPoint(Vec2::ANCHOR_TOP_LEFT);
	line_x2->setOpacity(255);
	this->addChild(line_x2);
}

for (int x = 0; x <= size.height*0.5f; x++) {
	Rect rect_y = Rect( 0.0f, 0, 200.0f, 1.0f);
	Sprite* line_y = Sprite::create();
	line_y->setTextureRect( rect_y );
	line_y->setPosition( 0  , x*2 );
	line_y->setAnchorPoint(Vec2::ANCHOR_TOP_LEFT);
	line_y->setColor(Color3B::WHITE);
	line_y->setOpacity(255);
	this->addChild(line_y);

	Rect rect_y2 = Rect( 0.0f, 0, 200.0f, 1.0f);
	Sprite* line_y2 = Sprite::create();
	line_y2->setTextureRect( rect_y2 );
	line_y2->setPosition( 400  , (x*2+1) );
	line_y2->setAnchorPoint(Vec2::ANCHOR_TOP_LEFT);
	line_y2->setColor(Color3B::WHITE);
	line_y2->setOpacity(255);
	this->addChild(line_y2);
}
```

3.17
<img src="https://user-images.githubusercontent.com/32508053/40882664-2256292a-6724-11e8-9dc1-e26f5d19239c.png" width="400">

3.14.1
<img src="https://user-images.githubusercontent.com/32508053/40882671-2a2d336e-6724-11e8-947f-6acc7b76eee3.png" width="400">

**Comment by seventhrank** [comment]
It's very troubled.
Is there a solution?

**Comment by seventhrank** [comment]
cocos2dx 3.16 is no problem.
It is probably a bug of 3.17.

3.16
<img src="https://user-images.githubusercontent.com/32508053/40959491-cc76b2da-68d7-11e8-86df-0f79b1334c47.png" width="400">

**Comment by slackmoehrle** [comment]
I can confirm this happening on 3.17 and on iOS too.

v3.16 no problem. Works as expected.

**Comment by seventhrank** [comment]
Do you have any progress?
I am looking forward to this fix.

**Comment by seventhrank** [comment]
Probably resolved.

This issue has been helpful.
https://github.com/cocos2d/cocos2d-x/issues/18983

When I undo this fix, it worked normally.　(v3.17.1)
https://github.com/cocos2d/cocos2d-x/pull/18606
https://github.com/cocos2d/cocos2d-x/commit/457de1cce1395717fd66f5c3c4ffa3a3ebc99ae7#diff-e6062325f2f0caa142c1bd4ab1cb5d33

Please confirm.

**Comment by seventhrank** [comment]
@slackmoehrle @drelaptop 
Are you busy?
Can you confirm it?

**Comment by minggo** [comment]
So it seems the `precision` affect the result. May be we should change to use 
```
headersDef = "#version 100\n precision highp float;\n precision highp int;\n";
```

**Comment by seventhrank** [comment]
> So it seems the `precision` affect the result. May be we should change to use
> 
> ```
> headersDef = "#version 100\n precision highp float;\n precision highp int;\n";
> ```

Solved it, It worked perfectly.

**Comment by minggo** [comment]
Will it affect the performance?

**Comment by seventhrank** [comment]
It seems that there is no problem.
but, I did not test for a long time.

**Comment by seventhrank** [comment]
#19633
Solved.
