### ISSUE TITLE
Error while loading shared libraries: libfmod.so.6: file too short

### ISSUE THREAD

**Issue by keyzj** [cocos2d/cocos2d-x#18882]
- cocos2d-x version: cloned right from git
- devices test on: Debian 9

Steps to Reproduce:
So, i've been following readme.md from github mainpage.
But when build of my project is over i got this message:
`/home/keyzj/Документы/cocos2d-x/TestGameDir/TestGame/bin/debug/linux/TemplateCpp: error while loading shared libraries: /home/keyzj/Документы/cocos2d-x/TestGameDir/TestGame/cocos2d/external/linux-specific/fmod/prebuilt/64-bit/**libfmod.so.6: file too short**
Error running command, return code: 127.`
I've already tried some solutions: cp and add symlinks (both /usr/lib and /usr/local/lib), manually installed fmod, but it didn't help me at all.

**Comment by drelaptop** [comment]
please refer to, https://github.com/cocos2d/cocos2d-x/issues/18754

**Comment by slackmoehrle** [comment]
@drelaptop link should help. If not, please tell me how you installed Cocos2d-x, meaning the steps you took exactly. Thanks. I replied to your forum post as well.

**Comment by keyzj** [comment]
Thank you very much for your's quick answers!
My problem is solved now!
The keypoint was to do `ln -sf libfmod.so libfmod.so.6` in `cocos2d/external/linux-specific/fmod/prebuilt/64-bit/ `and **don't** do symlink for **libfmodL.so** !
