### ISSUE TITLE
dirty memory read while in generateMaterialID

### ISSUE THREAD

**Issue by gxloveyy** [cocos2d/cocos2d-x#18881]
- cocos2d-x version: 3.16
- devices test on: onePlus 3
- developing environments

Steps to Reproduce:
In some level of my game, the Gl-call araises to almost 200. After debuging, I am sure the problem is the wrong material-ID, which breaks the batch command. details below:
 
In "generateMaterialID" there is a struct:
struct {
GLuint textureId;
GLenum blendSrc;
GLenum blendDst;
void* glProgramState;
} hashMe;

In 64bit machine, "sizeof(hashme)" is 24, considering the align requirement. But the appended 4 bytes are not been cleared. So different hash id returned even for the same texture, some blend function and glPrograme.

We need use "memset" before assigning value.

**Comment by gxloveyy** [comment]
@drelaptop Can you take a look at this? Thanks

**Comment by drelaptop** [comment]
@gxloveyy this have been fixed at https://github.com/cocos2d/cocos2d-x/pull/18543 , 3.17 milestone

> when found a bug at older release, you could look into the latest code, might it have been fixed.

**Comment by gxloveyy** [comment]
thanks
