### ISSUE TITLE
Finding assets

### ISSUE THREAD

**Issue by Swipes13** [cocos2d/cocos2d-x#18886]
In cocos creator when i have some asset named for example "NotificationBanner" i need to find it in "Search..." box with perfect match like: "NotificationBanner". 
Plz, make it with some regex like "Not*Ban". It Will be great!

**Comment by drelaptop** [comment]
cocos creator have its own repo, please feedback this there, sorry for this.

https://github.com/cocos-creator/cocos2d-x-lite
https://github.com/cocos-creator/engine
