### ISSUE TITLE
When the program exits, it may be possible to get a crash.

### ISSUE THREAD

**Issue by yuangu** [cocos2d/cocos2d-x#18892]
- cocos2d-x version:3.16
carsh info:

`

0 FZIphone | cocos2d::Ref::~Ref() + 48
-- | --
1 FZIphone | cocos2d::Ref::~Ref() + 44
2 FZIphone | cocos2d::GLViewImpl::~GLViewImpl() + 12
3 FZIphone | cocos2d::AutoreleasePool::clear() + 48
4 FZIphone | cocos2d::AutoreleasePool::~AutoreleasePool() + 20
5 FZIphone | cocos2d::PoolManager::~PoolManager() + 44
6 FZIphone | cocos2d::PoolManager::destroyInstance() + 28
7 FZIphone | cocos2d::ApplicationProtocol::~ApplicationProtocol() + 40
8 FZIphone | AppDelegate::~AppDelegate() + 12

`

this Ref code:

`Ref::~Ref()
{
#if CC_ENABLE_SCRIPT_BINDING
    // if the object is referenced by Lua engine, remove it
    if (_luaID)
    {
        ScriptEngineManager::getInstance()->getScriptEngine()->removeScriptObjectByObject(this);
    }
#if !CC_ENABLE_GC_FOR_NATIVE_OBJECTS
    else
    {
        ScriptEngineProtocol* pEngine = ScriptEngineManager::getInstance()->getScriptEngine();
        if (pEngine != nullptr && pEngine->getScriptType() == kScriptTypeJavascript)
        {
            pEngine->removeScriptObjectByObject(this);
        }
    }
#endif // !CC_ENABLE_GC_FOR_NATIVE_OBJECTS
#endif // CC_ENABLE_SCRIPT_BINDING

#if CC_REF_LEAK_DETECTION
    if (_referenceCount != 0)
        untrackRef(this);
#endif
}`

`    virtual ~ApplicationProtocol(){
#if CC_ENABLE_SCRIPT_BINDING
        ScriptEngineManager::destroyInstance();
#endif
        /** clean auto release pool. */
        PoolManager::destroyInstance();
    }`

**Comment by yuangu** [comment]
英语说的不够顺溜 吧，~ApplicationProtocol中的析构的时序好像不太对。ScriptEngineManager::destroyInstance();放在PoolManager::destroyInstance();后面比较合适

**Comment by drelaptop** [comment]
after this commit https://github.com/cocos2d/cocos2d-x/pull/19236/commits/65ed005b80857a2297505c543da08e1b2d09cbfb , this issues should be solved, also you can check the whole PR https://github.com/cocos2d/cocos2d-x/pull/19236
