### ISSUE TITLE
don't put any ad into issues

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#18891]

**Comment by v1993** [comment]
@drelaptop @minggo What this ads do here?!

**Comment by slackmoehrle** [comment]
@v1993 Thanks. I have contacted @drelaptop about this.

**Comment by liuyi** [comment]
This is NOT AD...  WE JUST REALLY NEED YOU GUYS!  It's very difficult to looking for some people who can write cocos2dx(js) very well...

**Comment by drelaptop** [comment]
This a awful behavior，you should  apologize for this @liuyi

**Comment by liuyi** [comment]
Sorry for this post, if you guys don't like.
I just want find some people join us.
HOW TO DELETE THIS?

**Comment by drelaptop** [comment]
thanks，you are a good guy.

**Comment by slackmoehrle** [comment]
Post on our forums in "Collaboration and Hiring" 
https://discuss.cocos2d-x.org (English)
http://forum.cocos.com (Chinese)
