### ISSUE TITLE
Cannot build a Project in Linux (Debian Stretch)

### ISSUE THREAD

**Issue by juliolugo96** [cocos2d/cocos2d-x#18899]
- cocos2d-x version: 3.17
- devices test on: PC
- developing environments
   - NDK version: nil
   - Xcode version: nil
   - VS version: nil
   - browser type and version: nil

Hello, I've downloaded Cocos2d-x and I've not been able to run any project yet. I've been researching in some issues, but I haven't found one similar to mine. My OS is Debian Stretch x86 arch. Need your help, thank you!

Steps to Reproduce:

1. Download **v3** on GitHub
2. Follow exact instructions as marked in README.md
3. Install all deps except g++-4.9 because Debian 9 has 6.3.0 by default and libpng-dev (It seems it's not in the Debian repositories).
4. run ` cocos run -p linux`

This was the output I got:

Building mode: debug
running: 'cmake -DCMAKE_BUILD_TYPE=Debug -DDEBUG_MODE=ON ..'

-- COCOS2DX_ROOT_PATH:/home/julio/AyDA/MyGame/cocos2d
-- CMAKE_MODULE_PATH:/home/julio/AyDA/MyGame/cocos2d/cmake/Modules/
-- COCOS_EXTERNAL_DIR:/home/julio/AyDA/MyGame/cocos2d/external
-- ENGINE_BINARY_PATH:/home/julio/AyDA/MyGame/linux-build/engine
-- CMAKE_BUILD_TYPE: Debug
-- It appears you are building natively for Linux with GCC
-- chipmunk CHIPMUNK_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/chipmunk/include
-- freetype2 FREETYPE_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/freetype2/include/linux
-- jpeg JPEG_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/jpeg/include/linux
-- tiff TIFF_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/tiff/include/linux
-- webp WEBP_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/webp/include/linux
-- websockets WEBSOCKETS_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/websockets/include/linux
-- openssl OPENSSL_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/openssl/include/linux
-- bullet BULLET_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/bullet/include;/home/julio/AyDA/MyGame/cocos2d/external/bullet/include/bullet
-- Box2D Box2D_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/Box2D/include
-- fmod FMOD_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/linux-specific/fmod/include
-- glfw3 GLFW3_INCLUDE_DIRS: /home/julio/AyDA/MyGame/cocos2d/external/glfw3/include/linux
-- glfw3 GLFW3_LIBRARIES: /home/julio/AyDA/MyGame/cocos2d/external/glfw3/prebuilt/linux/libglfw3.a
-- OpenGL include dirs: /usr/include
-- SQLite3 include dirs: /usr/include
-- GLEW include dirs: /usr/include
-- GLFW3 include dirs: /home/julio/AyDA/MyGame/cocos2d/external/glfw3/include/linux
CMake Error at cocos2d/cmake/Modules/FindFMOD.cmake:47 (include):
  include could not find load file:

    /home/julio/AyDA/MyGame/cocos2d/cmake/Modules/FindPackageHandleStandardArgs.cmake
Call Stack (most recent call first):
  cocos2d/cmake/Modules/CocosBuildHelpers.cmake:376 (find_package)
  cocos2d/cmake/Modules/CocosBuildModules.cmake:29 (cocos_find_package)
  cocos2d/cmake/Modules/CocosBuildSet.cmake:45 (include)
  CMakeLists.txt:35 (include)

CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find FMOD (missing: FMOD_LIBRARIES FMOD_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cocos2d/cmake/Modules/FindFMOD.cmake:48 (find_package_handle_standard_args)
  cocos2d/cmake/Modules/CocosBuildHelpers.cmake:376 (find_package)
  cocos2d/cmake/Modules/CocosBuildModules.cmake:29 (cocos_find_package)
  cocos2d/cmake/Modules/CocosBuildSet.cmake:45 (include)
  CMakeLists.txt:35 (include)

-- Configuring incomplete, errors occurred!
See also "/home/julio/AyDA/MyGame/linux-build/CMakeFiles/CMakeOutput.log".
See also "/home/julio/AyDA/MyGame/linux-build/CMakeFiles/CMakeError.log".
Error running command, return code: 1.

**Comment by slackmoehrle** [comment]
`ln -sf libfmod.so libfmod.so.6`?

**Comment by juliolugo96** [comment]
Good night, thank you for your answer.

Yep, I did it, I also followed the steps in this thread: https://discuss.cocos2d-x.org/t/error-while-building-for-linux-libfmod-so-6/26553/12

But doesn't seem to work. Where exactly do you execute that command?

A few days ago I tried modifying the file FindFMOD.cmake, but it didn't work anyway.

**Comment by drelaptop** [comment]
> CMake Error at cocos2d/cmake/Modules/FindFMOD.cmake:47 (include):

Did you Debian is 32bit OS? we only supply a 64-bit  libfmod.so prebuilt library. CMake in cocos2d-x won't call `Find*.cmake` if it found headers and libs in `external` successful.

**Comment by juliolugo96** [comment]
It seems @drelaptop got a point there.  I've a 32bit OS

I finally installed Cocos with no issues in a 64bit Linux Mint. Time to code for me now! :)

Thank you for your time to you both!
