### ISSUE TITLE
Can't use cmake build for android when using cocos console

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18916]
- cocos2d-x version: git
- devices test on: XUbuntu 18.04
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Run `cocos run -p android --build-type cmake`
2. Get `Value of '--build-type' should be one of ['ndk-build', 'none'].`

What is wrong?

**Comment by drelaptop** [comment]
thanks for report this. you are a so careful man. 

'--build-type' should be one of ['ndk-build', 'none']. the optional `cmake` value is waiting to  be added.

**Comment by v1993** [comment]
@drelaptop I just want to support only one build file, and using external library (outside of `Classes/`) directory broke ndk build. I know, that it is possible, but it is complicated for me.

**Comment by drelaptop** [comment]
For now, you can use the Android Studio in Linux to use cmake. or run `./gradlew build -PPROP_BUILD_TYPE=cmake` in `proj.android` directory to use cmake.

**Comment by crazyhappygame** [comment]
+1 use gradlew for Android and cmake for others

**Comment by v1993** [comment]
@crazyhappygame I already do so. :smile:

**Comment by v1993** [comment]
If anyone is interested, there is my build script: https://gist.github.com/v1993/b48378e1a0371125ab2c481ea8e445fc

Limitations: require posix (linux) system and lua `posix` module. For colors, install `ansicolors` lua module.
