### ISSUE TITLE
RenderTexture depend on Chipmunk

### ISSUE THREAD

**Issue by v1993** [cocos2d/cocos2d-x#18914]
- cocos2d-x version: git
- devices test on: XUbuntu 18.04, Android 7.1 (LineageOS)
- developing environments
   - NDK version: r17
   - Xcode version: ---
   - VS version: ---
   - browser type and version: ---

Steps to Reproduce:

1. Build with `USE_CHIPMUNK=0`
2. Try to use `RenderTexture::getSprite()`, it will return invalid pointer (not `nullptr`, just invalid).
3. Access that pointer and get happy SEGFAULT.

**Comment by v1993** [comment]
@drelaptop @minggo Can you take a look on it, please? To reproduce this bug add

    set(USE_CHIPMUNK FALSE CACHE BOOL "")
to project `CMakeLists.txt`, use CMake build and run anything what use `RenderTexture::getSprite` (e.g., `RenderTextureZbuffer` test).

**Comment by v1993** [comment]
@drelaptop Can you take a look at this, please?

**Comment by v1993** [comment]
Anyone, please! It is valid bug!

**Comment by minggo** [comment]
Yep, we will take a look, and fix it in next version.

**Comment by v1993** [comment]
@minggo Not only linux, but also at least android (probably other systems too?).

**Comment by drelaptop** [comment]
yep, it more likely a common issue. I found the modules enable/disable feature on CocosSelectModule.cmake didn't works as expected. 

for example you want disable physics feature, so you set `USE_CHIPMUNK` to `OFF`, set `USE_BOX2D` to `OFF` and set `USE_BULLET` to `OFF`, you will get compile errors.

**Comment by v1993** [comment]
@drelaptop I don't have any compile errors, but disableling chipmunk cause this issuee. Please, remove `platform:linux` tag.

**Comment by drelaptop** [comment]
I reproduce this issue on mac, and solved it in related PR.  @v1993 

the reason is macro defines `CC_USE_PHYSICS` is different between app target and library target, I think it's cmake defect when set macro in older cmake style.

when I set macro define in modern style, for example:
```CMake
target_compile_definitions(cocos2d PUBLIC CC_USE_PHYSICS=1)
```
the macro was set rightly on target `cocos2d` and targets which depend on `cocos2d`
