### ISSUE TITLE
ios 12 IdleShipHeroes Buying diamonds but not receiving

### ISSUE THREAD

**Issue by chainofhonor** [cocos2d/cocos2d-x#18918]
Hello, I downloaded the IdleShipHeroes game in app shore, and then bought 25 hot metal coins, but the payment has been successful and the diamond has not been received.

In addition, feedback bug, I just started to see the advertising will be given gold coins and diamonds, but later on to see nothing to the advertising, is this bug did not receive diamonds?

I contacted Apple customer service, customer service to this website.
My appleID is 648473061@qq.com
Order number: MQ0HKSLFYJ
Document number: 193215612089

**Comment by v1993** [comment]
This is game engine bug tracker. It is useless to write here, it is like writing to Unity support about crash.

You need to contact game developer, not game engine team.

**Comment by v1993** [comment]
@drelaptop What about adding `invalid` tag?

**Comment by drelaptop** [comment]
reasonable, I have added __invalid__ label.
