### ISSUE TITLE
AVAudioSessionCategoryAmbient disable the audio input in iOS

### ISSUE THREAD

**Issue by danlee2025** [cocos2d/cocos2d-x#18910]
- cocos2d-x version: 3.16
- devices test on: iPhone6P
- developing environments
   - NDK version: No NDK
   - Xcode version: Xcode 8
   - VS version: No VS
   - browser type and version: No browser

Steps to Reproduce:

1. Use Audio Unit to real time record sound need set category to "AVAudioSessionCategoryPlayAndRecord"
2. But cocos2d_libs source file "AudioEngine-ini.mm" set category to "AVAudioSessionCategoryAmbient" . Refer to  [NextPrevious
Audio Session Categories and Modes](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionCategoriesandModes/AudioSessionCategoriesandModes.html#//apple_ref/doc/uid/TP40007875-CH10-SW1), This category will disable the audio input (record). 

This does not make any sense. May be change to AVAudioSessionCategoryPlayAndRecord is better?

**Comment by drelaptop** [comment]
Cocos2d-x didn't support __Audio Record__ , no plan to do it recently. 

you can custom this feature as your need on iOS, but I don't think it's proper to add it internally.
