### ISSUE TITLE
macOS Mojave 10.14 Xcode 10 - Message from debugger: unable to attach

### ISSUE THREAD

**Issue by crookedbard** [cocos2d/cocos2d-x#18919]
- cocos2d-x version: 3.17
- devices test on: mac
- developing environments
   - Xcode version: Version 10.0 beta 2 (10L177m)

Steps to Reproduce:

1.  cocos new {app name} -p {app id} -l cpp -d {path}
2. Build successful. But debugger does not start. In the output window it throws : Message from debugger: unable to attach. When opening product directly it opens successfully, but I can't debug code with Xcode. When I create any other non cocos2d-x projects then debugger works fine. It does not work with cocos2d-x projects.

**Comment by JuanCasado** [comment]
It happens to me too, to "fix" it you need to make any change in your code, even adding some spaces and deleting them afterwards works, the problem occurs if you build for the first time or if you build two times consecutively without performing changes to the code, I don't know why it happens.

 @crookedbard

**Comment by rshimoda** [comment]
I had the same issue until I added a development team to my target. Hope that helps, good luck!
