### ISSUE TITLE
3.17 can not play  spine animation which made by spine 3.5.35

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#18922]
I thought Spine runtime  can play low version animation.
Or am I wrong?

**Comment by v1993** [comment]
I think that you should adress this question to spine developers, not cocos2d-x.

**Comment by liuyi** [comment]
I am not sure.
Because i don't know who wrote this module in cocos2dx.

**Comment by drelaptop** [comment]
the spine code comes from [spine-runtimes/spine-cocos2dx](https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-cocos2dx), you can new a issue at spine runtime Repo https://github.com/EsotericSoftware/spine-runtimes
