### ISSUE TITLE
Can spine animation  read images without  atlas file?

### ISSUE THREAD

**Issue by liuyi** [cocos2d/cocos2d-x#18921]
Because I want use user's profile image to  instead default face of avatar. These are more than one user in the same scene.

因为做用户头像和骨骼动画的合成。我之前是将用户的头像和SPINE的图集合成一张图，然后去调用的。
但是现在需要在同一个场景显示多人。用这样的方式比较不环保，请问是否可以只读散图，我就可以将用户的头像替换默认头像了

**Comment by gestern** [comment]
Short answer - yes, but you have to replace an image which would be not found (because you have not an atlas) with a red rectangle or ignore (for example) of the same size

**Comment by NotAPenguin0** [comment]
This issue can be closed
