### ISSUE TITLE
hot updates always have a small probability of random occurrence of a file update failure

### ISSUE THREAD

**Issue by yp0403130231** [cocos2d/cocos2d-x#18927]
- cocos2d-x version:3.16，lua
- devices test on:iphone、ipad(未在安卓上测试，不排除安卓发生)
- developing environments
   - NDK version:15
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:
cc.EventAssetsManagerEx.EventCode.ERROR_UPDATING下的错误信息有The request timed out.、The network connection was lost.、The Internet connection appears to be offline.、The file “CFNetworkDownload_zbvKxi.tmp” doesn’t exist.、The operation couldn’t be completed. (NSURLErrorDomain error -1001.)等等

**Comment by drelaptop** [comment]
> The request timed out.、The network connection was lost.

I think it may be a network issue. for the log shows __timed out__.
