### ISSUE TITLE
macOS Mojave 10.14 Xcode 10 - Traditional headermap style is no longer supported

### ISSUE THREAD

**Issue by crookedbard** [cocos2d/cocos2d-x#18920]
- cocos2d-x version: 3.17
- devices test on: macbook
- developing environments
   - Xcode version: Xcode version: Version 10.0 beta 2 (10L177m)

Steps to Reproduce:

1. cocos new {app name} -p {app id} -l cpp -d {path}
2. I get such warning when building app:
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'mac')

**Comment by JuanCasado** [comment]
I have the same problem, maybe if you add some labels to the issue it gets more visibility and someone help us.

**Comment by Anywhere-Music-Player** [comment]
@minggo @drelaptop this actually requires a lot of fixes, so better to start now, otherwise when `ALWAYS_SEARCH_USER_PATHS` will be removed from Xcode, means it set to `NO` - cocos2d-x will FAIL to build with 100+ errors.

**Comment by stevetranby** [comment]
Mainly need to move the platform-specific paths for the prebuilt third-party libraries from USER_HEADER_SEARCH_PATHS to  HEADER_SEARCH_PATHS and fix up any related issues, likely change any unwanted "" to <> for include paths.

I was able to get up and running with not too much work beyond those changes to build settings. I did find `tinyxml` and `xxhash` as examples of non-platform-specific include statements that I needed to change across the project. I changed them to longer paths for easier reference, but do as you like to fix:
```
#include "external/tinyxml2/tinyxml2.h"
#include "external/xxhash/xxhash.h"
```

If there's a lot of work it'll probably be in updating all the associated test projects (cpp, js, lua, perf, etc). 

Edit: adding `path/to/project/Classes/` path into user header search paths will likely help.

**Comment by Guy-kun** [comment]
Why was this closed, is it fixed yet?
If this was fixed it'd help a lot to have the commit where it was done so that those of us with branched source can apply a patch

**Comment by Anywhere-Music-Player** [comment]
@minggo how this updated with new Xcode?

**Comment by minggo** [comment]
I will take a look.

**Comment by minggo** [comment]
When i was fixing this issue, i found many 3rd party libraries uses `<>`, such as `spine`, `openssl`. I have to think more about it.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/19395
