### ISSUE TITLE
`cc.loader.load` convert url error 

### ISSUE THREAD

**Issue by PatriceJiang** [cocos2d/cocos2d-x#18949]
`+` in URL is mapped to `%20`, which will cause the error.

**Comment by PatriceJiang** [comment]
![_20180720162501](https://user-images.githubusercontent.com/40414978/42991895-98576500-8c39-11e8-89a6-cbc037dce291.jpg)

> android-async-http turns `+` into `' '` space, then into `%20`
>  The `+` in the signature becomes `%20`, which causes the signature to fail to be authenticated and the remote image cannot be loaded.

**Comment by minggo** [comment]
Please don't use Chinese.

**Comment by PatriceJiang** [comment]
Translated
