### ISSUE TITLE
PageView中的item可以循环利用吗？  

### ISSUE THREAD

**Issue by 215090240** [cocos2d/cocos2d-x#18942]
比如只创建三个ITEM，每次滑动时刷新ITEM中的视图

**Comment by drelaptop** [comment]
Excuse me, issues was used to track bug, not to be used like you done. If you have so many questions, you should to forum ask help firstly. And the issues will be show to all over the world developers, it's better to use English, not Chinese. So I will close those issues, please ask help to forum firstly.

Issues 主要是用来报告 bug 的，不是这样用的。另外报告 bug 时，最好使用英语，因为全球各地的开发者都能看到你的问题，帮助一起解决。

我把你创建的 issues 关闭，请先到论坛反馈。@215090240

English forum：https://discuss.cocos2d-x.org 中文论坛：http://forum.cocos.com
