### ISSUE TITLE
test cpp donesn't support websockets with ssl .

### ISSUE THREAD

**Issue by midgithub** [cocos2d/cocos2d-x#18966]
- cocos2d-x version:2.2.6
- devices test on:win
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. change ws host to wss host , run test cpp project.
2. websocket connection doesn't connecte.

**Comment by midgithub** [comment]
hope to get some help late !

**Comment by PatriceJiang** [comment]
Please attach some log info  @midGitub.

**Comment by midgithub** [comment]
@PatriceJiang ...sorry .i just change the code in  WebSocketTest.cpp .

change the test url. ws://echo.websocket.org to wss://echo.websocket.org

it shows

![image](https://user-images.githubusercontent.com/20261416/43501494-5fdd441c-9588-11e8-9252-94222eb5d4dc.png)

testCpp print nothing when run this test..... 

i change the testCpp in cocos 3.x 。 it can run well. successfully connect the websocket-test-url



   if (!_wsiSendText->init(*this, "wss://echo.websocket.org"))
    {
        CC_SAFE_DELETE(_wsiSendText);
    }
    
    if (!_wsiSendBinary->init(*this, "wss://echo.websocket.org"))
    {
        CC_SAFE_DELETE(_wsiSendBinary);
    }
    
    if (!_wsiError->init(*this, "wss://invalid.url.com"))
    {
        CC_SAFE_DELETE(_wsiError);
    }
.

**Comment by midgithub** [comment]
![image](https://user-images.githubusercontent.com/20261416/43501858-38ea42c2-958a-11e8-9355-76642d7183fa.png)
when run the testcpp in 3.17. the result is above.

**Comment by midgithub** [comment]
@PatriceJiang  do you need other info..

**Comment by minggo** [comment]
Sorry, v2.x is not maintained now.
