### ISSUE TITLE
instalation problem, Fedora 28

### ISSUE THREAD

**Issue by antivir88** [cocos2d/cocos2d-x#18973]
[casper@localhost cocos]$ ./setup.py 

Setting up cocos2d-x...
->Check environment variable COCOS_CONSOLE_ROOT
  ->Search for environment variable COCOS_CONSOLE_ROOT...
    ->COCOS_CONSOLE_ROOT is found : /home/casper/Загрузки/cocos/tools/cocos2d-console/bin

->Check environment variable COCOS_X_ROOT
  ->Search for environment variable COCOS_X_ROOT...
    ->COCOS_X_ROOT is found : /home/casper/Загрузки

->Check environment variable COCOS_TEMPLATES_ROOT
  ->Search for environment variable COCOS_TEMPLATES_ROOT...
    ->COCOS_TEMPLATES_ROOT is found : /home/casper/Загрузки/cocos/templates

->Configuration for Android platform only, you can also skip and manually edit "/home/casper/.bashrc"

->Check environment variable NDK_ROOT
  ->Search for environment variable NDK_ROOT...
    ->NDK_ROOT is found : /opt/android/ndk_bundle

->Check environment variable ANDROID_SDK_ROOT
  ->Search for environment variable ANDROID_SDK_ROOT...
    ->ANDROID_SDK_ROOT is found : /opt/android

->Check environment variable ANT_ROOT
  ->Search for environment variable ANT_ROOT...
    ->ANT_ROOT is found : /usr/bin

Please execute command: "source /home/casper/.bashrc" to make added system variables take effect

[casper@localhost cocos]$ 
[casper@localhost cocos]$ ./download-deps.py 
=======================================================
==> Prepare to download external libraries!
Traceback (most recent call last):
  File "./download-deps.py", line 341, in <module>
    main()
  File "./download-deps.py", line 335, in main
    installer = CocosZipInstaller(workpath, os.path.join(workpath, 'external', 'config.json'), os.path.join(workpath, 'external', 'version.json'), "prebuilt_libs_version")
  File "./download-deps.py", line 97, in __init__
    self._extracted_folder_name = os.path.join(self._workpath, self._repo_name + '-' + self._current_version[1:])
  File "/usr/lib64/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 13: ordinal not in range(128)
[casper@localhost cocos]$ uname -a
Linux localhost.localdomain 4.17.5-200.fc28.x86_64 #1 SMP Tue Jul 10 13:39:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by drelaptop** [comment]
Linux existed many distributions, we tested the installation on the most popular distribution __Ubuntu__ . 

refer to http://cocos2d-x.org/docs/cocos2d-x/en/installation/Linux.html

**Comment by nnn1590** [comment]
Same as Ubuntu 18.04 LTS...
```
=======================================================
==> Prepare to download external libraries!
Traceback (most recent call last):
  File "./download-deps.py", line 379, in <module>
    main()
  File "./download-deps.py", line 373, in main
    installer = CocosZipInstaller(workpath, os.path.join(workpath, 'external', 'config.json'), os.path.join(workpath, 'external', 'version.json'), "prebuilt_libs_version")
  File "./download-deps.py", line 98, in __init__
    self._extracted_folder_name = os.path.join(self._workpath, self._repo_name + '-' + self._current_version[1:])
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 11: ordinal not in range(128)
```
