### ISSUE TITLE
audio engine crash on ios platform when enable/disable it frequently 

### ISSUE THREAD

**Issue by zzyAZU** [cocos2d/cocos2d-x#18971]
- cocos2d-x version:3.17
- devices test on:ios 11 iphone 8 plus
- developing environments
   - NDK version:
   - Xcode version:<------
   - VS version:
   - browser type and version:

Steps to Reproduce:
进游戏不断的开关声音几率性崩溃

0 AudioToolbox | _CrashIfClientProvidedBogusAudioBufferList + 56
-- | --
1 AudioToolbox | AudioConverterConvertComplexBuffer + 868
2 AudioToolbox | AUSpatialMixer::Render(unsigned int&, AudioTimeStamp const&, unsigned int) + 2048
3 AudioToolbox | AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 172
4 AudioToolbox | AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 492
5 AudioToolbox | AUMethodRender(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 44
6 AudioToolbox | AUInputElement::PullInput(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 140
7 AudioToolbox | AUInputFormatConverter2::InputProc(OpaqueAudioConverter*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription**, void*) + 220
8 AudioToolbox | AudioConverterChain::CallInputProc(unsigned int) + 640
9 AudioToolbox | AudioConverterChain::FillBufferFromInputProc(unsigned int*, CABufferList*) + 128
10 AudioToolbox | BufferedAudioConverter::GetInputBytes(unsigned int, unsigned int&, CABufferList const*&) + 192
11 AudioToolbox | Resampler2Wrapper::RenderOutput(CABufferList*, unsigned int, unsigned int&) + 192
12 AudioToolbox | SampleRateConverter::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) +48
13 AudioToolbox | BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 804
14 AudioToolbox | AudioConverterChain::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) +120
15 AudioToolbox | BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 804
16 AudioToolbox | AudioConverterFillComplexBuffer + 964
17 AudioToolbox | AUConverterBase::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 632
18 AudioToolbox | AURemoteIO::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 156
19 AudioToolbox | AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 172
20 AudioToolbox | AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 492
21 AudioToolbox | AURemoteIO::PerformIO(unsigned int, unsigned int, unsigned int, AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioBufferList*, int&) + 744
22 AudioToolbox | _AURIOCallbackReceiver_PerformIO + 356
23 AudioToolbox | __XPerformIO + 104
24 AudioToolbox | _mshMIGPerform + 232
25 AudioToolbox | _MSHMIGDispatchMessage + 40
26 AudioToolbox | AURemoteIO::IOThread::Run() + 284
27 AudioToolbox | AURemoteIO::IOThread::Entry(void*) + 156
28 AudioToolbox | CAPThread::Entry(CAPThread*) + 88
29 libsystem_pthread.dylib | __pthread_body + 272
30 libsystem_pthread.dylib | __pthread_body

这是报错堆栈，这个错误只有 ios11版本才有其他设备都没问题，我这边已经用 simple audio engine 替代 临时解决几率性崩溃问题，望关注下这个
ps. cocos 现在越来越稳定了，祝你们发展的越来越好
![image](https://user-images.githubusercontent.com/5827910/43387715-bdfcc24a-9419-11e8-81de-1dfbd711c3f1.png)

**Comment by zzyAZU** [comment]
ios 10 也有类似崩溃

**Comment by drelaptop** [comment]
could you add a test case to reproduce it, I know it's seldom occur, you can simulate that situation like https://github.com/cocos2d/cocos2d-x/issues/18597 did

> 你能加个测试例，去重现这个问题吗？问题是不太好重现，你可以尝试模拟那种频繁操作的情景，像 https://github.com/cocos2d/cocos2d-x/issues/18597 做的那样

**Comment by zzyAZU** [comment]
抱歉很难定位... 崩溃几率很小，太难重现

**Comment by drelaptop** [comment]
@CarlZhongZ duplicate with https://github.com/cocos2d/cocos2d-x/issues/18948 , so close this. please discuss this issue there.
