### ISSUE TITLE
[BUG] renderTexture->saveToFile() bugged for image alpha values, wrong output 

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#18980]
This issue was reported a long time ago: [https://github.com/cocos2d/cocos2d-x/issues/18193](https://github.com/cocos2d/cocos2d-x/issues/18193)

Still **NOT** fixed. `ClippingNode`or not whatever: just `renderTexture->saveToFile` works wrong with any graphics: layers, gradients and sprites. 
I have on my scene a `LayerGradient` and after render it's colors gets changed, dramatically. It's `renderTexture` output renders wrong image.

Just take examples from this my comment: [https://github.com/cocos2d/cocos2d-x/issues/18193#issuecomment-348789587](https://github.com/cocos2d/cocos2d-x/issues/18193#issuecomment-348789587). 
As you can see - `Sprite`and `LayerGradient` are differently rendered on output image!
This is currently same **bug** for **cocos2d-x v3.17.**

I can't simply create a screen-shoot of the scene! 

    RenderTexture *render = RenderTexture::create(WS.width, WS.height);
    render->begin();
    this->visit();
    render->end();
    render->saveToFile("render.png");

This code renders me a very **different** image of what I see. Please help!

@minggo @drelaptop @walzer 

upd.: also, `setBlendFunc(BlendFunc::DISABLE);`works ONLY for `render->getSprite()` - **Sprite** object, but when I just do `render->saveToFile`- it's looks like ignored.

**Comment by crazyhappygame** [comment]
@KAMIKAZEUA 
For screen-shot below code works for me:
```
    std::unique_ptr<cocos2d::Image> image(cocos2d::utils::captureNode(this));
    image->saveToFile(filePath);
```

**Comment by Anywhere-Music-Player** [comment]
@crazyhappygame sorry for late response, I just stop using cocos2d-x. It's dead for me.
No support, no fixes for years. Sadly.
