### ISSUE TITLE
[QUESTION] should it modify setColor to setTextColor for Label in RichText when rendering?

### ISSUE THREAD

**Issue by summerinsects** [cocos2d/cocos2d-x#18984]
SetColor will overwrite emojis' origin color

```c++
ui::RichText *richText = ui::RichText::create();
richText->pushBackElement(ui::RichElementText::create(0, Color3B::BLACK, 128, "Test emoji \xF0\x9F\x98\x81\xF0\x9F\x98\x82\xF0\x9F\x98\x83\xF0\x9F\x98\x84\xF0\x9F\x98\x85", "Arail", 14));
```

result:
![default](https://user-images.githubusercontent.com/7703197/43936317-9cbe021e-9c8a-11e8-81c3-9d993089d9fb.png)
expected:
![default](https://user-images.githubusercontent.com/7703197/43936349-af7d4b26-9c8a-11e8-9dc9-3d35f4da900d.png)

**Comment by drelaptop** [comment]
thanks for this patch
