### ISSUE TITLE
The EditBox (3.3) application has not been displayed for a long time without displaying the soft keyboard & nothing is displayed after the input is completed.

### ISSUE THREAD

**Issue by joiyao** [cocos2d/cocos2d-x#18994]
- cocos2d-x version: 3.3
- devices test on: Android
- developing environments
   - NDK version: r10d
   - Xcode version: 9.4.1
   - VS version:-
   - browser type and version:-

Steps to Reproduce:

1.  长时间开着应用，频繁输入，概率偶现

**Comment by liuyi** [comment]
建议你自己根据GITHUB上的代码 将这一模块更新到最新。毕竟你的版本太低了。
You can  check the change log and merge the latest code from cocos2d-x repo.

**Comment by joiyao** [comment]
版本低不是问题的根源，毕竟3.3用了近两年，是一个非常稳定的版本。即便更新了，我也得知道为什么会出现这个问题吧？

**Comment by liuyi** [comment]
你可以去看changelog 和editbox有关的地方  这个应该修改过很多地方了。

**Comment by joiyao** [comment]
谢谢，我确实在看CHANGELOG，3.3的时候还是Dialog实现的，但是到3.8的时候EditBox直接重新实现了。这着实让我头疼，我不确定此前最近的一个版本是不是没有问题了。毕竟是偶现问题，1000次出1次是问题，1000000次出1次也是问题。

**Comment by joiyao** [comment]
Well, my colleague just found this issue #12887.
This is exactly what I wanna say : The EditBox does not display soft keyboard or does not display input after typing finished. It happens occasionally after app running for a long time or coming foreground from other apps.  I'm using Cocos2d-x 3.3. :)
