### ISSUE TITLE
ENGINE_PATH when using -e switch with 'cocos new' command

### ISSUE THREAD

**Issue by mer23** [cocos2d/cocos2d-x#18999]
cocos2d-x version: 3.16
devices test on: ubuntu 16.04
developing environments
CLion 2017.3.4

I'm trying to make a new project using `cocos new` comand with the `-e` switch so it points to a remote cocos2d directory instead of copying a new one.
I tried passing the content of the zip I downloaded from cocos2d website (`-e /path/to/cocos2d-x-3.16`) as the ENGINE_PATH, but it still made a whole new copy for the new project.
Any guidance will be appreciated.

**Comment by drelaptop** [comment]
when `cocos new` to create a project, we only supported copy the engine source. because no link template supplied longer.

and it didn't do a whole copy, it copy engine files depend on `templates/cocos2dx_files.json`
