### ISSUE TITLE
Target tvos - Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by crookedbard** [cocos2d/cocos2d-x#19001]
- cocos2d-x version: 2.17
- devices test on: apple tv
- developing environments
   - Xcode version: 12

Steps to Reproduce:

1.  Build cocos2d libs for target tvos

Undefined symbols for architecture arm64:
  "btCollisionDispatcher::btCollisionDispatcher(btCollisionConfiguration*)", referenced from:
      cocos2d::Physics3DWorld::init(cocos2d::Physics3DWorldDes*) in libcocos2d tvOS.a(CCPhysics3DWorld.o)
  "btSequentialImpulseConstraintSolver::btSequentialImpulseConstraintSolver()", referenced from:
      cocos2d::Physics3DWorld::init(cocos2d::Physics3DWorldDes*) in libcocos2d tvOS.a(CCPhysics3DWorld.o)
  "btDefaultCollisionConfiguration::btDefaultCollisionConfiguration(btDefaultCollisionConstructionInfo const&)", referenced from:
      cocos2d::Physics3DWorld::init(cocos2d::Physics3DWorldDes*) in libcocos2d tvOS.a(CCPhysics3DWorld.o)
  "btDbvtBroadphase::btDbvtBroadphase(btOverlappingPairCache*)", referenced from:
      cocos2d::Physics3DWorld::init(cocos2d::Physics3DWorldDes*) in libcocos2d tvOS.a(CCPhysics3DWorld.o)
  "btAlignedAllocInternal(unsigned long, int)", referenced from:
      cocos2d::Physics3DWorld::init(cocos2d::Physics3DWorldDes*) in libcocos2d tvOS.a(CCPhysics3DWorld.o)
  "btDiscreteDynamicsWorld::btDiscreteDynamicsWorld(btDispatcher*, btBroadphaseInterface*, btConstraintSolver*, btCollisionConfiguration*)", referenced from:
      cocos2d::Physics3DWorld::init(cocos2d::Physics3DWorldDes*) in libcocos2d tvOS.a(CCPhysics3DWorld.o)
  "btAlignedFreeInternal(void*)", referenced from:
      cocos2d::Physics3DWorld::init(cocos2d::Physics3DWorldDes*) in libcocos2d tvOS.a(CCPhysics3DWorld.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by minggo** [comment]
There is not plan to support them, especially for v2.
