### ISSUE TITLE
What is the main repository for Spine?

### ISSUE THREAD

**Issue by gestern** [cocos2d/cocos2d-x#19026]
@minggo, If I did a couple of important things in the Spine Framework (`setBlendFunc()`  etc). Where will I have to contribute them:

- Into https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-cocos2dx ?
- or within cocos-2dx repo?

**Comment by crazyhappygame** [comment]
I think that order should be following
1. PR to https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-cocos2dx 
2. Get latest spine release from https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-cocos2dx and use it cococ2d-x source

**Comment by minggo** [comment]
Yep, you have to send PR to `spine-runtimes` then use it in cocos2d-x. But i am not sure which branch of `spine-runtimes` should contribute to.

**Comment by gestern** [comment]
Ok, thanks, got it.
