### ISSUE TITLE
Site down: http://forum.cocos2d-objc.org

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#19084]
http://forum.cocos2d-objc.org will be hosted or abandoned now fully?

**Comment by KAMIKAZEUA** [comment]
Best admin ever? @slackmoehrle

**Comment by slackmoehrle** [comment]
I am not the admin of those forums. Thanks for reaching out. I talked to the admin and they decided to take them offline.

**Comment by KAMIKAZEUA** [comment]
@slackmoehrle sorry, who is that admin and who is they?

**Comment by slackmoehrle** [comment]
If you have questions, please direct them to me.

**Comment by KAMIKAZEUA** [comment]
Thats what I did, you don't want to answer?

**Comment by slackmoehrle** [comment]
Ha, no. You will just e-mail them in the charming way that you do and not leave them alone if you don't get what you want. If you have questions about those forums, please ask me.

**Comment by KAMIKAZEUA** [comment]
I'm asking just - who exactly you talked to, who decided to take site offline?

**Comment by slackmoehrle** [comment]
I talked to the former admin and there was a conversation with team member that was such that those forums cost a lot to run, mostly spam and answers generally available on SO. They were taken down. We added an Obj-c category to our other forums for the one-off-questions.

**Comment by KAMIKAZEUA** [comment]
Again and again you can't simply answer: who exactly that was?

**Comment by slackmoehrle** [comment]
I don't want to give out their contact information without their permission. You come off to strong and the last thing I want to do is put you in contact with them and have you harass them like you do other members of our team.

Whatever you need to ask them, you can ask me.

**Comment by KAMIKAZEUA** [comment]
You don't listening me. Read carefully. 
1. I'm asking any personal info
2. I already know who admins are and already contacted them before in a past
3. This your answers make no sense.
4. I just know cocos don't have a money to support ObjC site.
5. Silly.

**Comment by slackmoehrle** [comment]
If you are unhappy with my answers then why continue this conversation. I told you the reasons why and the gist of conversation that was had by members of our team and the admin. 

1. Site was a lot of SPAM
2. It costs money to run that we didn't feel was a good use.
3. SO seems like a suitable replacement for most questions now
4. We added an Obj-c category to the other forums to help with any rare questions.

**Comment by slackmoehrle** [comment]
Cocos2d-objc hasn't been supported in years really. Everyone should move to -x or Creator.

**Comment by KAMIKAZEUA** [comment]
I'm not about only ObjC version...

**Comment by slackmoehrle** [comment]
You are entitled to your opinions. This issue is now closed.

**Comment by KAMIKAZEUA** [comment]
Yea sure, thats why you ban me on forums when I posting my opinion and any other developers. 
You close/hide/remove any topics from any other developers who telling their opinion about real state of cocos2d-x and ask typical question like: "Is Cocos2dx going to shut down". 
You think this will change anything? It's just a pity to look at. Do something useful, like a new C ++ tutorial for example.

**Comment by slackmoehrle** [comment]
Again, you are entitled to your opinion. If you disagree with the scope and vision of our products you can choose another game engine.

**Comment by slackmoehrle** [comment]
Again, as I have stated, you are entitled to your opinion. It doesn't mean that everyone has to accept your opinion as fact. If you disagree with the scope and vision of our products you can choose another game engine.

**Comment by slackmoehrle** [comment]
Again, as I have stated, you are entitled to your opinion. It doesn't mean that everyone has to accept your opinion as fact. If you disagree with the scope and vision of our products you can choose another game engine.

**Comment by KAMIKAZEUA** [comment]
![200](https://user-images.githubusercontent.com/3391456/47051499-224fc280-d1ad-11e8-8ec0-4bd1b860ca0b.gif)
