### ISSUE TITLE
ListView create a huge number of draw calls for overlapped objects

### ISSUE THREAD

**Issue by gestern** [cocos2d/cocos2d-x#19087]
- cocos2d-x version: **ALL**
- devices test on: **ALL**

**Steps to Reproduce:**

1. It is enough to create a more or less expensive content (it is what will later be inserted as a function parameter of `ui::ListView::pushBackCustomItem()` or `ui::ListView::pushBackDefaultItem()`) in the `ui::ListView`.
2. `Render` spends GPU time on `ListView` content objects (its childs) that are outside the render view window and should not be drawn logically.

The existence of this problem has been known for quite some time. For example: 

1. [How to optimize ListView](https://discuss.cocos2d-x.org/t/how-to-optimize-listview/29777)
2. [ccui.ListView terrible preformence on web](https://discuss.cocos2d-x.org/t/ccui-listview-terrible-preformence-on-web/37042)
3. [Android rendering performance issue](https://github.com/cocos2d/cocos2d-x/issues/15652#issuecomment-280248792)

> **Important note**
> The problem is that absolutely all the classes inherited from `ScrollView` suffer from this same “disease”:
> 1. `ScrollView`;
> 2. `ListView`;
> 3. `PageView`.

**The good news**
The good news is that I found a solution to this performance problem. The main idea is to proactively hide the child nodes that currently cannot be displayed to the user (all those who currently clipped out by `ListView` viewport ). The basic idea of applying a function when displaying components each time when the `ListView` content was changed, the common example here:
```cpp
void ListView::paintItems() {
    
    ssize_t lowerBound = _items.size() - 1;
    ssize_t upperBound = 0;
    
    if(_direction != ScrollView::Direction::VERTICAL) {
        // all directions possible except VERTICAL
        lowerBound = getIndex(getRightmostItemInCurrentView());
        upperBound = getIndex(getLeftmostItemInCurrentView());
    }
    
    if (_direction != ScrollView::Direction::HORIZONTAL) {
        // all directions possible except HORIZONTAL
        lowerBound = std::min(getIndex(getTopmostItemInCurrentView()), lowerBound);
        upperBound = std::max(getIndex(getBottommostItemInCurrentView()), upperBound);
    }
    
    for(size_t i = 0 ; i < _items.size() ; i++) {
        _items.at(i)->setVisible(lowerBound <= i && i <= upperBound);
    }
}
```
This function reduces the number of  GPU draw calls by using within `ListView` somewhere in one and a half to two times and can increase productivity by several times

**Limitations of this solution**

1. Cocos2d-x ONLY (But the solution can be easily transferred to the JavaScript);
2. Was tested with `ListView` and `PageView` (not `ScrallView`);
3. The solution cannot involves the situation when user set `setClippingEnabled(false)`

**Comment by umair6** [comment]
@gestern any reason why above changes were done in ListView and not in ScrollView classes? In scroll view class, we can check for all child nodes which are outside the visible rect and hide them.

**Comment by gestern** [comment]
> @gestern any reason why above changes were done in ListView and not in ScrollView classes?

This commit was rejected, so nothing to talk about
