### ISSUE TITLE
RichText can't load image from plist when ignoreContentAdaptWithSize is false

### ISSUE THREAD

**Issue by chongchaoyu** [cocos2d/cocos2d-x#19114]
- cocos2d-x version: cocos2d-x-js 3.17
- devices test on: mac simulator
- developing environments
   - NDK version: r16b
   - Xcode version: 10.0 (10A255)
   - VS version: -
   - browser type and version: -

Steps to Reproduce:

1. create star.plist and load it
2. Type the followings code, then run it.
![1](https://user-images.githubusercontent.com/12747983/46901746-8479a080-ceeb-11e8-8ccd-afe5900c8259.jpg)

3. star.png doesn't show on screen.

I have post a PR, #19107.

**Comment by PatriceJiang** [comment]
I read the code of `createWithXML` and did some test on my machine. I found that the parameter `type` is misused.

https://github.com/cocos2d/cocos2d-x/blob/f3ef6b80dece594d58523e893e56fb1a8c3c5bcf/cocos/ui/UIRichText.cpp#L438-L444

so, if you are going to load `star.png` from disk, you should set `type="0"`

**Comment by chongchaoyu** [comment]
I don't want to load star.png from disk, I want to load it from plist. But If I set ignoreContentAdaptWithSize=true, RichTextUI JUST try to load star.png from disk, the type is ignored, as the followings code, you can find RichTextUI doestn't try to load sprite from plist, `Sprite* imageRenderer = Sprite::create(filePath);` 
![e8f9352b9c4f490232d197f41d824bec](https://user-images.githubusercontent.com/12747983/46991768-dca5e200-d139-11e8-8ea3-93d54fd1ce99.jpg)
![5145870a75eb4353f01c5740aed4c94b](https://user-images.githubusercontent.com/12747983/46991790-f21b0c00-d139-11e8-9943-dca904e29c63.jpg)

**Comment by PatriceJiang** [comment]
I did met this issue when I invoke `richText->ignoreContentAdaptWithSize(false)` rather than `true`. Can you confirm it?

**Comment by chongchaoyu** [comment]
Oh, yes, you are right. I confirm that when `richText->ignoreContentAdaptWithSize(false)`, this issue occurs.

**Comment by PatriceJiang** [comment]
Can you please fix the titles of this issue and related pr.

**Comment by chongchaoyu** [comment]
Done, thanks:)
