### ISSUE TITLE
sth about spine anim.

### ISSUE THREAD

**Issue by zcgit** [cocos2d/cocos2d-x#19154]
As I read the latest version code, I found the cocos always read and decode the skeletonJsonFile & atlasFile when load the spine animation. so if an animation is very complex , it will take a lot of IO and decoding time.
 In fact, it always do 3 things when using a spine anim: 1.read skeletonJsonFile; 2.read atlasFile; 3.read the imageFile. 
 I wonder if we can separate the 3 things?  just loading the config file(skeletonJsonFile & atlasFile) when we need, and then loading a png when we really want to use the spine anim.
 In my real working situations I could load 30-50 and more spines' config files before we really use the spine anim. so it will make a good experience when you really want to use the spine which config file was loaded, because you just need to load a png file any more, and then you can also release the png and config files separately.

**Comment by zcgit** [comment]
anyone check it out ?  https://github.com/cocos2d/cocos2d-x/pull/19163

**Comment by gestern** [comment]
If you keep all animations in a **single atlas**, then this is not a problem at all.
