### ISSUE TITLE
record cpp-tests crash issues on latest v3

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x#19168]
__should be solved before 3.17.1 released__ , tested use latest commit https://github.com/cocos2d/cocos2d-x/commit/ae61f8fbc6e0ca6eed57a795f6a3890dce8e3760

- crash 7th cases of __3:Action-Basic__ on macOS
1. run Node:Scene3D
2. run Action-Basic cases one by one, crash will occur on 7th cases

revert v3 to https://github.com/cocos2d/cocos2d-x/pull/19013 crash still occurs, but the commit before this PR this crash gone.

**Comment by drelaptop** [comment]
that PR is about remove __Remove ccglstatecache__ , please check it if you are available @minggo 

![image](https://user-images.githubusercontent.com/26329291/48462741-610c8300-e814-11e8-90d9-3f457a06426e.png)

**Comment by drelaptop** [comment]
2nd crash situation is related with wrong behavior on adding same name plist files, caused by https://github.com/cocos2d/cocos2d-x/pull/19083 , should be solved before 3.17.1 release @PatriceJiang

**Comment by drelaptop** [comment]
3rd crash is caused by wrong png format convert, caused by https://github.com/cocos2d/cocos2d-x/pull/18908, fixed on https://github.com/cocos2d/cocos2d-x/pull/19170

**Comment by PatriceJiang** [comment]
`FileUtils::getFileSize` not implemented on win32 cause crash on windows. fixed https://github.com/cocos2d/cocos2d-x/pull/19176
