### ISSUE TITLE
using Deprecated "Always Search User Paths" settings.

### ISSUE THREAD

**Issue by daiki1003** [cocos2d/cocos2d-x#19196]
- cocos2d-x version:
3.16

- devices test on:
iPhoneX

- developing environments
   - Xcode version: 10.1

Steps to Reproduce:

1. Build 'cocos2d-libs' xcodeproj only.

Xcode produces error below.
"Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'libcocos2d iOS')

**Comment by stevetranby** [comment]
Duplicate Issue: https://github.com/cocos2d/cocos2d-x/issues/18920
