### ISSUE TITLE
[lua] downloader binding breaks other custom class registering

### ISSUE THREAD

**Issue by sonyps5201314** [cocos2d/cocos2d-x#19253]
lua_cocos2dx_network_manual.cpp中
调用register_downloader后将导致之后无法再注册成功用户的自定义类了，注释掉就恢复了，坑爹啊。
以后能不能测试后再合并用户提交的代码到主分支啊。自己重现吧，难得提交重现代码了，没时间。应该是register_downloader内部写法不规范导致的。不会用就别强撸嘛，老老实实tolua_beginmodule，tolua_endmodule不好吗？

English:
A call to register_downloader will result in a custom class that cannot be registered with a successful user.
Can the code that user submits be merged again after testing later advocate branch.Redo it yourself, it's hard to submit new code, no time.Should be register_downloader internal writing is not standardized.If you don't know how to use it, don't use it. Honestly, tolua_beginmodule, tolua_endmodule, is that bad?

**Comment by PatriceJiang** [comment]
我们在正式发布版本之前会进行若干轮的测试，尽量提高可靠性。 这个过程也需要广大开发者的帮助，积极反馈存在各种的问题，毕竟测试能覆盖场景有限。  非常感谢您在迁移版本过程中能够发现并且反馈问题。
这个问题暂时没有通过现有的测试用例暴露，如您能在百忙之中抽出时间 提供更多的重现方法，这样可以帮助更多其他的开发者， 我感激不尽！

It is more standardized to use `tolua` to bind `Downloader`, I will do it in the current release.  
Before that, could you please provide more info on how to reproduce the issue? @sonyps5201314

**Comment by PatriceJiang** [comment]
@sonyps5201314 Can you please test if this PR fix the issue https://github.com/cocos2d/cocos2d-x/pull/19255?

**Comment by sonyps5201314** [comment]
嗯，这个问题的确是修复了，感谢。
不过使用新版本编译公司项目后，还发现一个问题，估计不是同一个问题，可能需要另外开一个问题。
这个是3.17的9月多某个git版本编译的。
![image](https://user-images.githubusercontent.com/20564099/50210498-45ffd680-03b1-11e9-9ede-a4fdf1e40669.png)
下面这个是最新git版本编译的.
![image](https://user-images.githubusercontent.com/20564099/50210670-b9a1e380-03b1-11e9-9297-6c39b0bfcd5c.png)
为什么会缩小了呢？

**Comment by PatriceJiang** [comment]
perhaps there may exist multiple images of the same filename in a different resolution?
