### ISSUE TITLE
Missing Libuv_a.a

### ISSUE THREAD

**Issue by neonguyen** [cocos2d/cocos2d-x#19252]
- cocos2d-x version: 3.17.1
- devices test on: iOS Simulator 
- developing environments
   - Xcode version: 10.1

Steps to Reproduce:

1. I used cocos command to create project "cocos new {Name} -p {BundleId} -l cpp"
2. After that, I used Xcode to build the project and I got the error

![screen shot 2018-12-18 at 11 14 01 am](https://user-images.githubusercontent.com/8515901/50131715-0a341680-02b6-11e9-8ff5-a33e27bacb90.png)

**Comment by drelaptop** [comment]
please update external deps, by :
```
 $ cd cocos2d-x
  cocos2d-x $ python download-deps.py
```

existed at https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/tree/v3/uv/prebuilt/ios

**Comment by neonguyen** [comment]
> please update external deps, by :
> 
> ```
>  $ cd cocos2d-x
>   cocos2d-x $ python download-deps.py
> ```
> existed at https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/tree/v3/uv/prebuilt/ios

Thanks, It's worked perfectly
