### ISSUE TITLE
3.17.1 loading CocosBuilder .csb file becomes extremely slow

### ISSUE THREAD

**Issue by EricDDK** [cocos2d/cocos2d-x#19268]
![test_ccloader_img](https://user-images.githubusercontent.com/33505774/50440075-7b676f80-092f-11e9-8ff5-9791a9cb5cf5.png)
when the textureSize is 546,using time is 18400 ms.
In 3.17,it's correct. 
I'm blowsing the changing from 3.17 to 3.17.1.
Of course I can submit the res of .csb file.

[CardPosLayer.zip](https://github.com/cocos2d/cocos2d-x/files/2709877/CardPosLayer.zip)

**Comment by EricDDK** [comment]
ValueMap dict = FileUtils::getInstance()->getValueMapFromFile(fullPath); 
this function in void SpriteFrameCache::addSpriteFramesWithFile(const std::string& plist) will use more than 70ms every time in for loop.

**Comment by EricDDK** [comment]
I forgot something that the sprite frames are in memory.

**Comment by PatriceJiang** [comment]
How long does it take to load 546 textures in 3.17? @EricDDK

**Comment by EricDDK** [comment]
@PatriceJiang 18000+ms in vs 2015 debug module 
You can see the indicator in my picture.

**Comment by EricDDK** [comment]
@PatriceJiang it use 120 ms in 3.17.

**Comment by PatriceJiang** [comment]
Can you upload a `plist` with images files which take 70 ms to load?  Most test cases I have tried only takes around 3ms.

**Comment by EricDDK** [comment]
@PatriceJiang I change back the CCSpriteFrameCache.h and CCSpriteFrameCache.cpp to 3.17.
The bug is fixed.

I gave you the lua project which I test.
New a 3.17.1 lua project and replace the src and res.

**Comment by PatriceJiang** [comment]
I make a PR at https://github.com/cocos2d/cocos2d-x/pull/19269, please check if your problem is fixed. 
@EricDDK

**Comment by EricDDK** [comment]
@PatriceJiang OK,thanks.
I will test it and reply u.

**Comment by EricDDK** [comment]
@PatriceJiang I test it and it's fixed.
Thanks.
