### ISSUE TITLE
3d features are not supported

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#19306]

**Comment by minggo** [comment]
first PR: https://github.com/cocos2d/cocos2d-x/pull/19366, it is not complete

**Comment by minggo** [comment]
second PR: https://github.com/cocos2d/cocos2d-x/pull/19392, more Sprite3D test cases work.

**Comment by PatriceJiang** [comment]
OpenGL 3D feature list
- [x] Mesh
- [x] Sprite3D
- [x] Skybox #19401 
- [x] Terrain #19442
- [x] MotionStreak3D #19414
- [x] BillBoard #19407
- [x] Plane
- [x] 3D particles  #19464 
- [x] CameraBackgroundBrush #19454 

Metal 3D features
- [x] Mesh
- [x] Sprite3D 
- [x] Skybox
- [x] Terrain #19510 
- [x] MotionStreak3D
- [x] BillBoard
- [x] Plane
- [x] 3D particles #19508 
- [x] CameraBackgroundBrush
