### ISSUE TITLE
‘environment.sh’ file not found

### ISSUE THREAD

**Issue by devefx** [cocos2d/cocos2d-x#19304]
- cocos2d-x version:3.17.1

I see it 

```shell
source ../environment.sh
```

but I can't find this file in the project

https://github.com/cocos2d/cocos2d-x/blob/v3/tools/travis-scripts/run-script.sh#L124

Please tell me where this file is, thank you

**Comment by drelaptop** [comment]
generated file at setup_android.py, refer to

https://github.com/cocos2d/cocos2d-x/blob/8978825fd255d13b68b2c81b7628d2f598b1acdf/tools/appveyor-scripts/setup_android.py#L100
