### ISSUE TITLE
Why was TextureCache::getInstance deprecated?

### ISSUE THREAD

**Issue by thekie** [cocos2d/cocos2d-x#19300]
I just migrate an old project to cocos-x v3 and saw that `sharedTextureCache()` was deprecated in CCTextureCache.h, which I encountered for a lot of other singletons already. But why was `getInstance()` also deprecated on CCTextureCache.h?

If that was intentional, could you please tell me the right way to access the TextureCache singleton? Is it better to go via the Director?

**Comment by EricDDK** [comment]
In 3.17.1
the function is 
![78id npdkoa5 e0zknqey](https://user-images.githubusercontent.com/33505774/51228393-58ab0280-1993-11e9-8301-6af184d1ea4f.png)

**Comment by NotAPenguin0** [comment]
This issue can be closed I suppose?

**Comment by minggo** [comment]
Just use Director::getInstance()->getTextureCache(). We want to directory to manage all memories if possible.

**Comment by learner-crapy** [comment]
I also get the error, the log as the following, I don't konw how to deal with:

jni/../../Classes/CacheManager.cpp: In member function 'cocos2d::Texture2D* CacheManager::loadImage(const string&, bool)':
jni/../../Classes/CacheManager.cpp:39:50: warning: 'static cocos2d::TextureCache* cocos2d::TextureCache::getInstance()' is deprecated (declared at E:/BaiduNetdiskDownload/BaiRiMen/BaiRiMenSourceCode/ClientSourceCode/work/client/frameworks/runtime-src/proj.android/../../cocos2d-x/cocos//network/../renderer/CCTextureCache.h:68) [-Wdeprecated-declarations]
         if ((texture = TextureCache::getInstance()->addImage(path)))
