### ISSUE TITLE
Remove Xcode projects

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#19319]
Should just use cmake to construct projects as other platforms.

**Comment by drelaptop** [comment]
with https://github.com/cocos2d/cocos2d-x/issues/18717#issuecomment-455471357 discuss, we hold same idea to remove Xcode build files. and have made cmake works on iOS/macOS too.

the reason to keep it in alpha release is that iOS generated Xcode project don't so convenient like origin build files.

1. info.plist issues
1. iOS sign config

that is said if developer add a file, and re-execute `cmake ..`, all custom config at Xcode will disappear. could we improve it, or just let developers to accept it? @crazyhappygame

**Comment by minggo** [comment]
If using cmake, then developers should do custom configuration in cmake. Is there any configuration that can not do in cmake?

**Comment by drelaptop** [comment]
I think no necessary feature cmake can't support, only some are complex, not friendly. 

__options:__
1. custom all __build__ configurations, for example headers include, link libs ... , cmake works well, and convenient for users. for we known cmake is great cross-platform build tools.

2. custom all __pack__ configurations isn't so convenient, compare with operation at Xcode UI. especially features special with other platform.

    - for example, signing operation https://github.com/cocos2d/cocos2d-x/pull/19263
    - for example, the ` iOS Deployment Target` for root project, needed by __Product -> archive__, cmake don't support until 3.11 release. https://github.com/cocos2d/cocos2d-x/pull/19315

**Comment by crazyhappygame** [comment]
Signing is very easy
I successfully signed iOS by adding following two lines: 
```
        SET_XCODE_PROPERTY(${APP_NAME} CODE_SIGN_IDENTITY "iPhone Developer")
        SET_XCODE_PROPERTY(${APP_NAME} DEVELOPMENT_TEAM "XXXXXXXXXX")
```

**Comment by drelaptop** [comment]
above comment is the way to sign iOS, but it's not obvious to find `DEVELOPMENT_TEAM` value.

- the right way to find it by the __Organizational Unit__ 

```
Applications -> Utilities -> Keychain Access.
Under the 'login' Keychain, go into the 'Certificates' category.
Scroll to find your development or distribution certificate. They will read:
iPhone Distribution: Team Name (certificate id)
or
iPhone Developer: Team Name (certificate id)
Simply double-click on the item, and the
"Organizational Unit"
```
> https://stackoverflow.com/questions/18727894/how-can-i-find-my-apple-developer-team-id-and-team-agent-apple-id

**Comment by minggo** [comment]
I think sign information can be set in Xcode by developers after Xcode is generated by Cmake.  Currently, all tests doesn't set sign information, you should set it manually.

**Comment by drelaptop** [comment]
- `sign issues` solved by above PR

> if you want to sign iOS app in CMake, you will need to fill development team ID into set_xcode_property(${APP_NAME} DEVELOPMENT_TEAM ""), or select to sign in Xcode after project files generated.

- `info.plist issues` don't need to solve.

> As said above: If using cmake, then developers should do custom configuration in cmake.

> user can custom info.plist by modify [cmake/Modules/iOSBundleInfo.plist.in](https://github.com/cocos2d/cocos2d-x/blob/v3/cmake/Modules/iOSBundleInfo.plist.in), and most situations, don't need to modify it.

- another cmake have supported switch Debug/Release in IDE, it's more convenient. 

The only thing to prevent removing Xcode projects,  AFAIK is precompiled headers, cmake don't existed native support on it, so as to build time is more longer than supplied Xcode project. 

If we think it's optional feature, I think we can remove Xcode projects now for `metal-support` branch.

**Comment by minggo** [comment]
> user can custom info.plist by modify cmake/Modules/iOSBundleInfo.plist.in, and most situations, don't need to modify it.

Then it will effect all new projects, it is not a friendly. 

> another cmake have supported switch Debug/Release in IDE, it's more convenient.

Is it possible now?

**Comment by drelaptop** [comment]
> Then it will effect all new projects, it is not a friendly.

when execute `cocos new`, `iOSBundleInfo.plist.in` template file will be copied too. At this time user modify it will only have  effect on single project.

>   Is it possible now?

yes, it is. The big difference is copy resource occurs at build process, instead of config process.

**Comment by minggo** [comment]
Sounds good, let's remove it.

**Comment by minggo** [comment]
done in https://github.com/cocos2d/cocos2d-x/pull/19448
