### ISSUE TITLE
Remove simulator targets for iOS

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#19318]
As metal doesn't support iOS simulator, so should remove simulator targets.
![2741547633156_ pic_hd](https://user-images.githubusercontent.com/488203/51373766-e6295680-1b3b-11e9-9444-30513d8974c1.jpg)

**Comment by drelaptop** [comment]
as I confirmed, it's a Xcode itself config, not a project config. so we can't config it at `xcodeproj` or cmake.

but we can disable any specific simulator by this way

https://stackoverflow.com/questions/33577934/can-i-set-the-default-simulator-for-new-projects-in-xcode-7-1-or-latest

after disable all simulators, we will get device only. even change to another project, device only too.

**Comment by drelaptop** [comment]
We can't custom it at project config, so tell users `metal doesn't support iOS simulator` is OK
