### ISSUE TITLE
Remove 3rd party libraries used for iOS simulator

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#19317]
Since metal doesn't support iOS simulator, so should remove these libraries.

**Comment by drelaptop** [comment]
Do we consider to add a macro to allow developer to switch metal & opengl on iOS?

**Comment by minggo** [comment]
Currently, it is not easy to do it. And i don't think it is needed since if want to use opengl, then just use older versions.

**Comment by minggo** [comment]
May be we need to support OpenGLES as @drelaptop said, but i don't know if it is possible to switch to OpenGLES or metal at runtime.
