### ISSUE TITLE
runAction stop bug

### ISSUE THREAD

**Issue by roripika** [cocos2d/cocos2d-x#19324]
- cocos2d-x version: 3.15.1
- devices test on: iPad Pro 12.9 inch
- developing environments
   - NDK version: r14b
   - Xcode version: 10.1
   - VS version: none
   - browser type and version: none

C++

Steps to Reproduce:

```C++
                        cocos2d::Vector<cocos2d::FiniteTimeAction *> actions;
                        auto move = cocos2d::MoveTo::create(0.1f,nextPosition);
                        auto scale1 = cocos2d::ScaleTo::create(0.2f,1.0f,1.5f);
                        auto scale2 = cocos2d::ScaleTo::create(0.2f,1.0f,1.0f);
                        actions.pushBack(Spawn::create(move,cocos2d::Sequence::create( scale1,scale2, nullptr)));
                        auto call = cocos2d::CallFunc::create([=]()
                        {
                	            _endAnimation = true;
                        });
                        actions.pushBack(call);
                        
                        _endAnimation = false;
                        enemy->runAction(cocos2d::Sequence::create(actions));
```
When this program is executed, "_endAnimation" occasionally does not become true.

Currently working on updating from version 3.13.1 to 3.15.1, it was running properly in version 3.13.1.

Usually I can only use Japanese, I will not post. I can not stand it but I only know Japanese but posted it using google translation.

**Comment by Dimon4eg** [comment]
It's not cocos2d issue. 
Try this :

```
cocos2d::CallFunc::create([&_endAnimation]()
                        {
                	            _endAnimation = true;
                        });
```

**Comment by roripika** [comment]
Sorry, the test code was not good, I will post again when the situation changes

**Comment by yukio-oohara** [comment]
_endAnimation

menber value

this->_endAnimation
