### ISSUE TITLE
androidstudio无法打开项目

### ISSUE THREAD

**Issue by AmazingKevin** [cocos2d/cocos2d-x#19332]
- cocos2d-x version:3.17.1
- devices test on: PC(windows)
- developing environments
   - NDK version:android-ndk-r16b
   - Xcode version:NO
   - VS version:NO
   - browser type and version:

Steps to Reproduce:

1. 下载安装3.17.1
2. 创建新的项目 cocos new test -p test.jinlong.www -l cpp -d
3.使用 android studio 打开项目出错

> Task :libcocos2dx:extractDebugAnnotations
file or directory 'D:\cocos2d\test\cocos2d\cocos\platform\android\libcocos2dx\src\main\java', not found
file or directory 'D:\cocos2d\test\cocos2d\cocos\platform\android\libcocos2dx\src\main\java', not found
file or directory 'D:\cocos2d\test\cocos2d\cocos\platform\android\libcocos2dx\src\debug\java', not found
Task ':libcocos2dx:extractDebugAnnotations' is not up-to-date because:
  No history is available.
file or directory 'D:\cocos2d\test\cocos2d\cocos\platform\android\libcocos2dx\src\main\java', not found
file or directory 'D:\cocos2d\test\cocos2d\cocos\platform\android\libcocos2dx\src\debug\java', not found

:libcocos2dx:extractDebugAnnotations (Thread[Task worker for ':',5,main]) completed. Took 1.063 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test:generateJsonModelDebug'.
> com.android.ide.common.process.ProcessException: Error configuring

**Comment by AmazingKevin** [comment]
[== "CMake Server" ==[

{"cookie":"","errorMessage":"Configuration failed.","inReplyTo":"configure","type":"error"}

]== "CMake Server" ==]

Configuration failed.
External native generate JSON debug: JSON generation completed with problems

:test:generateJsonModelDebug (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 0.331 secs.

> Task :libcocos2dx:transformClassesAndResourcesWithSyncLibJarsForDebug
Task ':libcocos2dx:transformClassesAndResourcesWithSyncLibJarsForDebug' is not up-to-date because:
  No history is available.
All input files are considered out-of-date for incremental task ':libcocos2dx:transformClassesAndResourcesWithSyncLibJarsForDebug'.

:libcocos2dx:transformClassesAndResourcesWithSyncLibJarsForDebug (Thread[Task worker for ':',5,main]) completed. Took 0.591 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test:generateJsonModelDebug'.
> com.android.ide.common.process.ProcessException: Error configuring

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
34 actionable tasks: 3 executed, 31 up-to-date
VCS Checkout Cache (D:\cocos2d\test\proj.android\.gradle\vcsWorkingDirs) has not been cleaned up in 0 days
执行命令出错，返回值：1。

**Comment by drelaptop** [comment]
please install ninja firstly, refer to https://github.com/cocos2d/cocos2d-x/pull/19298

**Comment by AmazingKevin** [comment]
> please install ninja firstly, refer to #19298

怎么安装,怎么使用的呢
