### ISSUE TITLE
Missed EventHandler in Blackberry implementation of CCEGLView

### ISSUE THREAD

**Issue by moadib** [cocos2d/cocos2d-x#1934]
I've made some changes which were accepted https://github.com/cocos2d/cocos2d-x/pull/730 to gles11(former master). But in gles20 version they are not presented

@dducharme can you comment this? This is required for handling events in user app, IAP for example.

**Comment by dducharme** [comment]
Can you port those over to the gles20 version?  I thought I had grabbed the most recent branch when I did the port.

**Comment by godyZ** [comment]
@moadib  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
