### ISSUE TITLE
3.17.1 android studio compiling error.

### ISSUE THREAD

**Issue by EricDDK** [cocos2d/cocos2d-x#19352]
- cocos2d-x version: 3.17.1
- devices test on: Android Studio 3.0
- developing environments
   - NDK version: r16
   - Xcode version:
   - VS version:
   - browser type and version:

Everything is OK and click Make Project in AS.
the error occurs that :

`Build command failed.
Error while executing process E:\android\adt-bundle-windows-x86_64-20140702\sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\work\ShenChengMahjong\shen021Mahjong\frameworks\runtime-src\proj.android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target cocos2dlua}
[1/3] Building CXX object engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o
FAILED: engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o 
E:\android\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi --gcc-toolchain=E:/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=E:/android/android-ndk-r16b/sysroot   -I../../../../../../Classes -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/auto -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/manual -I../../../../../../../cocos2d-x/external/lua/luajit/include -I../../../../../../../cocos2d-x/external/lua/tolua -I../../../../../../../cocos2d-x/tools/simulator/libsimulator/lib -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../../.. -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../manual -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../manual/platform/android -I../../../../../../../cocos2d-x/external/lua/tolua/. -isystem E:/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include -isystem E:/android/android-ndk-r16b/sources/android/support/include -isystem E:/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++abi/include -isystem E:/android/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -fsigned-char -O0 -fno-limit-debug-info  -fPIC   -std=gnu++11 -MD -MT engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o -MF engine\cocos\lua-android\CMakeFiles\lua_android_spec.dir\__\manual\platform\android\jni\Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o.d -o engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o -c ../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp
Assembler messages:
Fatal error: can't create engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o: No such file or directory
clang++.exe: error: assembler command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.`

`Caused by: org.gradle.internal.UncheckedException: Build command failed.
Error while executing process E:\android\adt-bundle-windows-x86_64-20140702\sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\work\ShenChengMahjong\shen021Mahjong\frameworks\runtime-src\proj.android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target cocos2dlua}
[1/3] Building CXX object engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o
FAILED: engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o 
E:\android\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi --gcc-toolchain=E:/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=E:/android/android-ndk-r16b/sysroot   -I../../../../../../Classes -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/auto -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/manual -I../../../../../../../cocos2d-x/external/lua/luajit/include -I../../../../../../../cocos2d-x/external/lua/tolua -I../../../../../../../cocos2d-x/tools/simulator/libsimulator/lib -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../../.. -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../manual -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../manual/platform/android -I../../../../../../../cocos2d-x/external/lua/tolua/. -isystem E:/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include -isystem E:/android/android-ndk-r16b/sources/android/support/include -isystem E:/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++abi/include -isystem E:/android/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -fsigned-char -O0 -fno-limit-debug-info  -fPIC   -std=gnu++11 -MD -MT engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o -MF engine\cocos\lua-android\CMakeFiles\lua_android_spec.dir\__\manual\platform\android\jni\Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o.d -o engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o -c ../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp
Assembler messages:
Fatal error: can't create engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o: No such file or directory
clang++.exe: error: assembler command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: Build command failed.
Error while executing process E:\android\adt-bundle-windows-x86_64-20140702\sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\work\ShenChengMahjong\shen021Mahjong\frameworks\runtime-src\proj.android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target cocos2dlua}
[1/3] Building CXX object engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o
FAILED: engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o 
E:\android\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi --gcc-toolchain=E:/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=E:/android/android-ndk-r16b/sysroot   -I../../../../../../Classes -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/auto -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/manual -I../../../../../../../cocos2d-x/external/lua/luajit/include -I../../../../../../../cocos2d-x/external/lua/tolua -I../../../../../../../cocos2d-x/tools/simulator/libsimulator/lib -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../../.. -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../manual -I../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/proj.android/../manual/platform/android -I../../../../../../../cocos2d-x/external/lua/tolua/. -isystem E:/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include -isystem E:/android/android-ndk-r16b/sources/android/support/include -isystem E:/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++abi/include -isystem E:/android/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -fsigned-char -O0 -fno-limit-debug-info  -fPIC   -std=gnu++11 -MD -MT engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o -MF engine\cocos\lua-android\CMakeFiles\lua_android_spec.dir\__\manual\platform\android\jni\Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o.d -o engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o -c ../../../../../../../cocos2d-x/cocos/scripting/lua-bindings/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp
Assembler messages:
Fatal error: can't create engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o: No such file or directory
clang++.exe: error: assembler command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

	at com.android.build.gradle.tasks.ExternalNativeBuildTaskUtils.executeBuildProcessAndLogError(ExternalNativeBuildTaskUtils.java:244)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:307)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.build(ExternalNativeBuildTask.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 45 more

`

**Comment by drelaptop** [comment]
> Fatal error: can't create engine/cocos/lua-android/CMakeFiles/lua_android_spec.dir/__/manual/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxLuaJavaBridge.cpp.o: No such file or directory

long path error, please move your project into root directory.

**Comment by EricDDK** [comment]
@drelaptop  No other resolution?
I fix the ndk build about this error by google. But the Cmake is which I want to use.
The only solution to use CMake is move to root directory?
