### ISSUE TITLE
Very Low performance of metal version

### ISSUE THREAD

**Issue by kkafaseb** [cocos2d/cocos2d-x#19353]
Is very often the case that games and especially puzzle games such as match-3 have a lot of opengl calls. Engine should have very good performance with 200-300 open gl calls. 

- cocos2d-x version: metal-support 
- devices test on:iphones xs max
- Xcode version: 10.1

Steps to Reproduce:

1. Create empty scene.
2. Add a lot of LayerColor

    for (int i=0; i<200; i++){
           this->addChild(LayerColor::create(Color4B::RED, 300, 300));
    }

3. Compare with cocos2d-x 3.17.1

Results:
200 LayerColor 
Cocos2d-x v3.17.1 Open GL: 45Fps
Metal: 20 fps

![image 2019-01-24 10 53 48](https://user-images.githubusercontent.com/42576559/51666364-56196000-1fc6-11e9-80a0-4b403cc0893c.jpg)
![image 2019-01-24 10 49 11](https://user-images.githubusercontent.com/42576559/51666372-5c0f4100-1fc6-11e9-809d-ddb8cf72b831.jpg)

300 LayerColor
Cocos2d-x v3.17.1 Open GL: 31 fps
Metal: 12 Fps

![image 2019-01-24 10 49 03](https://user-images.githubusercontent.com/42576559/51666384-616c8b80-1fc6-11e9-8f72-0403015df77a.jpg)
![image 2019-01-24 10 48 46](https://user-images.githubusercontent.com/42576559/51666391-65001280-1fc6-11e9-9bbb-95cf9c33bead.jpg)

What i noticed is that:
50 x LayerColor -> 60fps
100 x LayerColor -> 25-30fps

@minggo

**Comment by minggo** [comment]
Fixed in https://github.com/cocos2d/cocos2d-x/pull/19367. It is strange that creating MTLRenderEncoder is time consuming.

@kkafaseb could you please check it too? Thanks.

**Comment by kkafaseb** [comment]
@minggo  sure will do it today.

**Comment by kkafaseb** [comment]
@minggo As i understand from the code you changed, the issue with performance was general in Renderer and not related to LayerColor correct? But i assume its convienient to measure using LayerColor since it's easy to increase number of GL calls with each new object placed on scene.

I run a second test, this time on a different device, iphone-x. I compared OpenGL v3.17.1 vs latest metal version vs old metal version. However, i did not use cocos fps reporting becuase i believe its far from accurate. As i understand, when fps is high up to 20fps, cocos reporting seems accurate. However, if fps is really low e.g. on old metal version, the fps reporting i saw on cocos2d-x was very far different from what apple was reporting in xcode. Thefore, i will stick with xcode one. Test was placing 300 LayerColor on screen. -> 300 GL Calls, 1800 GL Verts

OpenGl - Around 18fps - 56ms gpu time - 16% cpu utilization
![screen shot 2019-01-30 at 2 05 09 pm](https://user-images.githubusercontent.com/42576559/51980389-8f574180-2498-11e9-8be5-71d7cfb30697.png)

Old Metal Version - Around 5fps - 200ms gpu time - 33% cpu utlization
![screen shot 2019-01-30 at 2 05 58 pm](https://user-images.githubusercontent.com/42576559/51980420-a6962f00-2498-11e9-9121-2f2e0164ec1a.png)

Latest Metal Version - Around 17fps - 58ms gpu time - 41% cpu utilization
![screen shot 2019-01-30 at 2 06 54 pm](https://user-images.githubusercontent.com/42576559/51980433-b150c400-2498-11e9-8767-de69555ed804.png)

Based on these results:
1. It seems GPU time was greately improved so great work!
2. It seems CPU utilization took a bit hit from 33% to 40% and its far worse vs OpenGl version. 

Some thoughts: 
1. You should check why Metal version is using much more CPU and if possible drop it to same levels as OpenGl. 
2. As i am aware, Metal by nature uses more cpu and less GPU? if thats the case, we should see a big improvement in GPU, something that is not here yet as the results are just a bit worse vs OpenGl. I would expect metal to superpass OpenGl performance on iOS devices since its apple's own rendering library and advertised as much more efficient. 
3. I also saw in merge "//FIXME: optimize it, cache the result as possible." so we should expect further optimisation improvements?

I know performance was not your first priority all these weeks since you were focusing on first supporting all features, but i believe it's a must to make this engine super fast before releasing. One of the main reasons we could look Unity3D in the eyes was a very fast renderer so lets keep it up )

**Comment by minggo** [comment]
Yep, the performance is not LayerColor but the engine. Sure, we will continue to polish the performance before releasing. And i will keep this issue until we fix all things.

**Comment by minggo** [comment]
disable metal validation and capture GPU in release mode to reduce CPU usage: https://github.com/cocos2d/cocos2d-x/pull/19374

**Comment by minggo** [comment]
Cache renderpipeline sate to reduce CPU usage: https://github.com/cocos2d/cocos2d-x/pull/19375

**Comment by minggo** [comment]
@kkafaseb the CPU usage is reduced a lot.

**Comment by minggo** [comment]
And we will continue reduce the CPU time after https://github.com/cocos2d/cocos2d-x/issues/19316 is done.

**Comment by kkafaseb** [comment]
Ok ping me when you are ready and i will run again the tests on my side )

**Comment by minggo** [comment]
I think you can test it now. #19316 will not be fixed quickly.
