### ISSUE TITLE
CCScale9Sprite and CCControlButtons in cocosbuilder break down

### ISSUE THREAD

**Issue by tiantian20007** [cocos2d/cocos2d-x#1938]
Some of my ui, such as CCScale9Sprite and CCControlButton, is breaked after upgrade to 2.1.1.
It seems it failed to scale my images by insets which is set in cocosbuilder;
My images are packed by TexurePacker.

**Comment by dumganhar** [comment]
> My images are packed by TexurePacker.

So did you create CCScale9Sprite from spriteframe?
If you create it from a normal sprite file, does it work?

**Comment by tiantian20007** [comment]
Yeah, I created it from spriteframe. However, not all CCScale9Sprite created from spriteframe break down;
It works well for normal sprtie file;

**Comment by dumganhar** [comment]
Could you add a test demo to `TestCpp/ExtensionsTest/Scale9SpriteTest`?
It will be easy for us to find the reason. Thanks.

**Comment by fnz** [comment]
There's a bug when using CCScale9Spite created from CCSpriteFrame with rotated property set to true, in method updateWithBatchNode coordinates of CCScale9Sprite pieces are not calculated properly, exact place is

// Set up the image
//
if (rotated)
{
HERE
}

**Comment by folecr** [comment]
This should fix it https://github.com/cocos2d/cocos2d-x/pull/1974

**Comment by tiantian20007** [comment]
Textures rotated in spriteSheet still breaks;

**Comment by godyZ** [comment]
The issue is migrated to http://www.cocos2d-x.org/issues/2659
