### ISSUE TITLE
Missing Chinese characters when using custom .ttf font

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#19382]
- cocos2d-x version: 3.17
- devices test on: iPhone
- developing environments
   - Xcode version: 10.1
Steps to Reproduce:

1. Use `font.ttf` which does not include `zh-Hans` or `zh-Hant` language. Basically it's any font, example: https://www.1001freefonts.com/flottflott.font (I picked a random from free fonts)
2. Create `Label` using this `.ttf` Set Chinese text to it, example:` 纪录：`
3. Run and notice that it's empty. I tested and only interested in iOS.

Why cocos doesn't takes standard font from system, if character or system language is `zh-*` ?

How can I change the engine to fix this? Basically to make it work like this: 
 - check what is system languge
 - if it's Chinese, use `Helvetica` for all `Labels`
 - otherwise, use set `.ttf` font file

@minggo @zilongshanren @drelaptop Could you please help me?
I really wondering, because as I remember, in cocos2d-objc, if font doesn't contains Chinese, it will use system font automatically.

**Comment by kkafaseb** [comment]
We have created a wrapper for this case. I think you will find it useful. Change according to your needs:
 ```
Label * _buildLabel(const char * text, const char * font, const float ptsize, const double max_width, const bool isBold) {
    Label * label = Label::createWithTTF(text, font, system_pt2px(ptsize));
    bool use_system = false;
    std::u16string utf16String;
    if (!StringUtils::UTF8ToUTF16(text, utf16String)) {
        massert0;
        use_system = true;
    } else {
        label->updateContent();
        bool all_valid = true;
        auto * atlas = label->getFontAtlas();
        for(const auto& c16 : utf16String) {
            cocos2d::FontLetterDefinition letterDefinition;
            if (!atlas->getLetterDefinitionForChar(c16, letterDefinition)) {
                all_valid = false;
                break;
            }
        }
        if (!all_valid) {
            use_system = true;
        }
    }
    
    if (use_system) {
        label = Label::createWithSystemFont(text, isBold ? "Helvetica-Bold" : "", system_pt2px(ptsize));
        if (max_width > 0.0) {
            label->setDimensions(max_width, 0.0f);
            label->setOverflow(Label::Overflow::RESIZE_HEIGHT);
        }
    } else {
        if (max_width > 0.0) {
            label->setMaxLineWidth(max_width);
        }
    }
    return label;
}
 ```

**Comment by Anywhere-Music-Player** [comment]
@kkafaseb 
I have it actually for all types: buttons, label and text. 
However, after I asking this question I later tried to use system font, and it looks ugly and eats memory. There are some like cutted shadow around all text. 
Do you have the same issues?

**Comment by minggo** [comment]
No, engine doesn't change to use system font if the ttf failed. There is why Label has different functions for different fonts. Developer should do it manually, engine can not estimate needed behavior.

**Comment by Anywhere-Music-Player** [comment]
@minggo
in cocos2d-objc, if font doesn't contains Chinese, it will use system font automatically. Why this not the same for cocos2d-x?

**Comment by minggo** [comment]
I don't know the behavior of cocos2d-objc, cocos2d-x doesn't have to the same behavior as it is.

**Comment by Anywhere-Music-Player** [comment]
So, how to support multilanguage in cocos2d-x ? For English, Chinese and say Russian?

**Comment by minggo** [comment]
Use different ttf files for different languages. Cocos2d-x doesn't support localization now, and there is not plan for it, you should do it yourself.

**Comment by Anywhere-Music-Player** [comment]
But can cocos2d-x works same as cocos2d-ojbc, so in it's can't find a symbol in .ttf file it uses some other automatically. That was typical behaviour for a good engine. 
Because now, I just got empty Labels, that so AWKWARD.

**Comment by Dimon4eg** [comment]
@KAMIKAZEUA you can try do it by self and create PR.
I guess cocos2d team is busy with metal support.

**Comment by Anywhere-Music-Player** [comment]
I have no skills to do such task.

**Comment by ilqvya** [comment]
You never get such skills without even try to do it

**Comment by Anywhere-Music-Player** [comment]
Who said I didn't tried :D ?

**Comment by ilqvya** [comment]
So, DO NOT GIVE UP! ;)
