### ISSUE TITLE
img->saveToFile doesn't work with transparency on Android

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#19418]
- cocos2d-x version: 3.17
- devices test on: Google Pixel 3XL
- developing environments
   - NDK version: r13b
   - Xcode version: 10.1
   - VS version: N/A
   - browser type and version: N/A

Steps to Reproduce:

1. Load a PNG file with some transparency into Image
2. Re-save it as a transparent PNG (saveToFile(filename, false))
3. Now load the re-saved image. It has broken alpha on Android. Works fine on iOS.

It may be related to: https://github.com/cocos2d/cocos2d-x/issues/18193 but I'm not even using RenderTexture, nor ClippingNode. 

Here's an example source code:

```
    auto img = new Image();
    img->initWithImageFile("coloring.png");

    std::string path = FileUtils::getInstance()->getWritablePath() + "coloring_saved.png";
    img->saveToFile(path, false);

    auto sprite = Sprite::create(path);
    sprite->setAnchorPoint(Point::ZERO);

    auto drawNode = DrawNode::create(); //white background
    drawNode->drawSolidRect(Vec2::ZERO, Vec2(sprite->getContentSize().width, sprite->getContentSize().height), Color4F::WHITE);

    addChild(drawNode);
    addChild(sprite);
```

helps a bit, but I'm getting some strange outlines:
`img->setPNGPremultipliedAlphaEnabled(false); `
Here's example image, which I use:

![coloring](https://user-images.githubusercontent.com/8133606/53089599-50ebfa00-350d-11e9-8671-2021988833c7.png)

**Comment by piotrros** [comment]
Of course this is very simplified example. In my real project I use img->getData(), which is a colour array. I modify it by drawing with different kinds of brushes, then I save it for later use.

**Comment by Anywhere-Music-Player** [comment]
For me this call works: 
https://github.com/cocos2d/cocos2d-x/issues/18980#issuecomment-410534926

**Comment by piotrros** [comment]
Doesn't work for me. I'm getting black background and no alpha at all.

**Comment by Anywhere-Music-Player** [comment]
For iOS and macOS it works.

**Comment by piotrros** [comment]
For iOS/macOS my code works anyway. The problem is Android.

**Comment by piotrros** [comment]
I pretty much tested every possible way and never succeeded on Android:

- saving via image->saveToFile (also tried setting setPNGPremultipliedAlphaEnabled to true and false)
- saving via RenderTexture with or without setting blending to DISABLE, ALPHA_PREMULTIPLIED and ALPHA_NON_PREMULTIPLIED
- doing the same as above, but with modified class RenderTexture class: https://pastebin.com/cbM3MJCW named RenderTextureAlpha
- using utils::captureNode (which internally uses RenderTexture anyway)
- I've also tried modifying Image class itself to put similar fix as in the pastebin code

I'm getting darker image or completely broken colours.

**Comment by piotrros** [comment]
Okay, I've solved it:

After deep analysis, I couldn't find a solution. I've come up with the idea that it might be a problem with libpng, but it wasn't. In the end, I've extracted from device saved file and to my shock it was fine (non premultiplied). Conclusion: saving works fine. Three damn days!

So, maybe there's something wrong with loading a file. It turned out to be true. 

I load file like this:

```
    img = new Image();
    img->initWithImageFile(filename);
    texture = new Texture2D();
    texture->initWithImage(img);
    sprite = Sprite::createWithTexture(texture);
```

Looks like img->initWithImageFile premultiplies alpha for some reason. Solution is very simple. Just use:

`img->setPNGPremultipliedAlphaEnabled(false);`

before `img->initWithImageFile`

And voila! It works! However, there are two things we need to fix now:

For some strange reason setPNGPremultipliedAlphaEnabled is static as well as PNG_PREMULTIPLIED_ALPHA_ENABLED property:
`static void setPNGPremultipliedAlphaEnabled(bool enabled) { PNG_PREMULTIPLIED_ALPHA_ENABLED = enabled; }`

So, after this change everything is affected. Any Sprite::create or img->initWithImageFile will work differently. Anyway, easy to fix. Just:

`img->setPNGPremultipliedAlphaEnabled(true);`

when you're done with your problematic image.

Now, there's a second problem. When you run the app on iOS, images will be lightened. So, make sure to wrap setPNGPremultipliedAlphaEnabled calls within:

```
#if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
    img->setPNGPremultipliedAlphaEnabled(false);
#endif
```

After this, everything works fine for me.
