### ISSUE TITLE
#19276 will due to crash when button->loadTexture("xxx") on android platform

### ISSUE THREAD

**Issue by EricDDK** [cocos2d/cocos2d-x#19428]
- cocos2d-x version:3.17.1
- devices test on:
- developing environments
   - NDK version:r17
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

button->loadTexture("xxx"). the button is cocostudio button.

![26aj vc7i6hdr p7rttv47q](https://user-images.githubusercontent.com/33505774/53225827-386a1400-36b4-11e9-8e5b-440efa4e211e.png)

**Comment by EricDDK** [comment]
#19276

**Comment by minggo** [comment]
The PR just make some functions as virtual. Will it cause crash?

**Comment by EricDDK** [comment]
> The PR just make some functions as virtual. Will it cause crash?

I rolled back the part of this PR only, the crash disappeared.
cocos2d-x 3.17.1 lua project

**Comment by minggo** [comment]
Does the button need to be created by cocos studio? Cocos Studio is not maintained for a long time.

**Comment by EricDDK** [comment]
> Does the button need to be created by cocos studio? Cocos Studio is not maintained for a long time.

yep... it's cocostudio.

**Comment by gocpplua** [comment]
@minggo does this pr solve?

**Comment by minggo** [comment]
I don't know, cocos studio is not maintained for a long time.

**Comment by gocpplua** [comment]
ok, thank you the same

minggo <notifications@github.com> 于2019年10月30日周三 下午5:13写道：
