### ISSUE TITLE
cocos console should work with cmake

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#19446]

**Comment by crazyhappygame** [comment]
@minggo for what cocos console is needed with cmake?
To compile:
mkdir build
cd build
cmake.. 
cmake --build .

To create new project:
cp -R tests/cpp-empty-test my_new_project

Should work for all platforms.

**Comment by minggo** [comment]
I mean cocos console commands, such as `cocos compile -p mac`.

**Comment by minggo** [comment]
As i know`cmake --build ` can not work on Android. Right?

**Comment by minggo** [comment]
Sorry, i mean can not use cmake to run Android application.

**Comment by crazyhappygame** [comment]
For Android:
build:
```
$ cd proj.android
$ gradlew assembleRelease
```
install:
`$ adb install proj.android/app/build/outputs/apk/release/my.apk`

**Comment by minggo** [comment]
Thanks. I will use these commands in cocos console. I have to make cocos console work to keep compatibility, and it is easy to use the same commands on different platforms.

**Comment by minggo** [comment]
https://github.com/cocos2d/cocos2d-x/pull/19466: cpp tests lua empty test work, `lua tests` itself can not build correctly.

Things left:

- [x] lua tests: https://github.com/cocos2d/cocos2d-x/pull/19471
- [ ] js tests
- [x] new project

**Comment by minggo** [comment]
Since JSB is removed, so close this issue.
