### ISSUE TITLE
Spine not show when add to Billboard

### ISSUE THREAD

**Issue by kienvn** [cocos2d/cocos2d-x#19491]
- cocos2d-x version: 3.17.1
- devices test on: Mac

`
bool HelloWorld::init()
{
    //////////////////////////////
    // 1. super init first
    if ( !Layer::init() )
    {
        return false;
    }
    
    auto visibleSize = Director::getInstance()->getVisibleSize();
    auto origin = Director::getInstance()->getVisibleOrigin();

    
	auto camera = Camera::createPerspective(13, visibleSize.width / visibleSize.height, 700, 10000);
	camera->setCameraFlag(CameraFlag::USER2);
	camera->setPosition3D(Vec3(-1110, 71, 0));
	camera->lookAt(Vec3(0.f, 23, 0.f));
	addChild(camera);

	auto billboard = BillBoard::create(BillBoard::Mode::VIEW_POINT_ORIENTED);
	this->addChild(billboard);

	SkeletonAnimation* sp = SkeletonAnimation::createWithJsonFile("fish_freeze_idle.json", "img.atlas", 1);
	sp->setAnimation(0, "run", true);
	sp->setCameraMask((unsigned short)CameraFlag::USER2);
    sp->setDebugSlotsEnabled(true);
	billboard->addChild(sp);

    return true;
}
`

This code worked on 3.15 before

**Comment by kienvn** [comment]
I've fixed this bug by init trianglesCommand with flags = 0, spine node will be 2D

**Comment by pandaGames** [comment]
why close this issue?it is still not work on 3.17.2
