### ISSUE TITLE
Crash bug in screen-locked Android device

### ISSUE THREAD

**Issue by kernys** [cocos2d/cocos2d-x#1950]
When device locked and runs your cocos2d-x application, it just crashes
down, because CCApplication::sharedApplication() is NULL and nativeOnPause called.

Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnPause.

This patch fixes this problem and awaits for unlocking screen.

``` cpp
   JNIEXPORT void JNICALL Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnPause() {
      if(CCApplication::sharedApplication()) <== ADDED
           CCApplication::sharedApplication()->applicationDidEnterBackground();

      if(CCNotificationCenter::sharedNotificationCenter()) <== ADDED
           CCNotificationCenter::sharedNotificationCenter()->postNotification(EVENT_COME_TO_BACKGROUND, NULL);
    }
```

I don't know how to use github well. but could you apply this patch for next release? Thank you so much.

**Comment by dumganhar** [comment]
>  if(CCNotificationCenter::sharedNotificationCenter()) <== ADDED

Is this line needed?

**Comment by kernys** [comment]
Oops. absolutely not. sorry.

by the way, I found small bug in CCRenderTexture.cpp 316 Line

Below code is for creating depth buffer of CCRenderTexture. but because of wrong if condition never reachable.

``` cpp
        if (m_uDepthRenderBufffer != 0) 
        {
            //create and attach depth buffer
            glGenRenderbuffers(1, &m_uDepthRenderBufffer);
            glBindRenderbuffer(GL_RENDERBUFFER, m_uDepthRenderBufffer);
            glRenderbufferStorage(GL_RENDERBUFFER, uDepthStencilFormat, (GLsizei)powW, (GLsizei)powH);
            glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, m_uDepthRenderBufffer);

            // if depth format is the one with stencil part, bind same render buffer as stencil attachment
            if (uDepthStencilFormat == GL_DEPTH24_STENCIL8)
            {
                glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_RENDERBUFFER, m_uDepthRenderBufffer);
            }
        }
```

I think it's small typo. I think if condition must be fixed like this.

``` cpp
- if (m_uDepthRenderBufffer != 0) 
+ if (uDepthStencilFormat != 0)
```

Sorry for my poor english. thank you

**Comment by dumganhar** [comment]
You are right, thx.
The issue (http://www.cocos2d-x.org/issues/1697) was created.
