### ISSUE TITLE
FileUtils::getInstance() JNI Runtime Error

### ISSUE THREAD

**Issue by MuratAl** [cocos2d/cocos2d-x#19553]
- cocos2d-x version: 3.17.1
- devices test on: Samsung Galaxy S3 (Android Jelly Bean 4.3)
- developing environments
   - NDK version: r16

Steps to Reproduce:
I've started a Game with Cocos2dx v3.15 and switched to new Version 3.17.1. 
Now I've realized that the _C++ <-> Java "Communication"_ has been rewritten. 
_FileUtils* fileUtils = FileUtils::getInstance();_ produces a Runtime Error on my old smart phone Samsung Galaxy S3... but not on other devices like Xiaomi Redmi 4x and LG G4.

I did some Research and FileUtils::getInstance() leads to an error in the File 
**JniHelper.cpp Line 48:**

_jclass _claz

z = (jclass) **env->CallObjectMethod**(cocos2d::JniHelper::classloader, cocos2d::JniHelper::loadclassMethod_methodID, _jstrClassName);_

cocos2d::JniHelper::classloader = NULL
cocos2d::JniHelper::loadclassMethod_methodID = NULL

some Details:
[JNI Error.txt](https://github.com/cocos2d/cocos2d-x/files/3009485/JNI.Error.txt)

**Comment by crazyhappygame** [comment]
Hi. Could you reproduce this issue on latest cpp-tests from CI. https://ci.appveyor.com/api/buildjobs/69nq0r1w78srhw5m/artifacts/release%2FCppTests-release-unsigned.apk

**Comment by MuratAl** [comment]
Thank you @crazyhappygame. 
I used the cpp-tests (I built it for myself) and it worked.
So I looked at Google for a solution and found other (non cocos2dx-specific threads) with almost the same issue. Seems to be a problem with JNI and unreleased resources... I dont know. I do not have time to go deeper into this topic.
I'm also using JNI for some tasks (like ads, notifications, etc.)... this seems to be the problem… and this is the only difference between my Code and the cpp-tests Code.

My Code works fine with cocos2dx v3.15 (for all of my devices).
I do not know how many devices will be affected by this "bug" when I release my game (with CCv3.17+) :-/

**Additional Information:** My Game worked one time of almost 100 tryouts. So I assume that it really has something to do with Memory corruption or similar.

**Comment by crazyhappygame** [comment]
Could you create simple test case?

**Comment by MuratAl** [comment]
yes. but that would take some time. 
The JNI Part of my Code/Game is no magic. it's based on [SonarSystems Cocos-Helper](https://github.com/SonarSystems/Cocos-Helper). I'm using (of course) newer Versions of the used Services... but the JNI Part (functionality) is the same.

**Comment by imtrobin** [comment]
I have Samsung S3, my JNI seems working, also from older 3.X series.

**Comment by MuratAl** [comment]
Ok, after removing all my JNI Stuff and reimplementing it with all new APIs... My Project works now on older Devices too. My JNI implementation is the same... I just changed the APIs like UnityAds, AdMob, Google Play Services etc. I have also updated the Google Play App.
