### ISSUE TITLE
Introduce version number defines 

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#19576]
Is it at all possible to introduce version number preprocessor defines so that game code can check and selectively activate certain code that works in one version of Cocos2d-x but not in another?

For instance, the new v4 release will force significant changes in the code base of games and extensions (like Spine for Cocos2d-x), but in updating code to support v4, it means the code can no longer compile for v3 of Cocos2d-x.

https://cmake.org/cmake-tutorial/ lists a way to do this, under the section "Adding a Version Number and Configured Header File"

Something along the lines of this in the root CMakeLists.txt, which currently contains "set(COCOS2D_X_VERSION 3.17.1)":

```
...
set(COCOS2D_X_VERSION 3.18.0)

# The version number
set (COCOS2DX_VERSION_MAJOR 3)
set (COCOS2DX_VERSION_MINOR 18)
set (COCOS2DX_VERSION_REVISION 0)
 
# configure a header file to pass some of the CMake settings
# to the source code
configure_file (
  "${PROJECT_SOURCE_DIR}/CCVersionConfig.h.in"
  "${PROJECT_BINARY_DIR}/CCVersionConfig.h"
  )
...
```

Inside CCVersionConfig.h.in, you would put this:

```
// the configured options and settings for Tutorial
#define COCOS2DX_VERSION_MAJOR @COCOS2DX_VERSION_MAJOR@
#define COCOS2DX_VERSION_MINOR @COCOS2DX_VERSION_MINOR@
#define COCOS2DX_VERSION_REVISION @COCOS2DX_VERSION_REVISION@
```
This will allow our code to check for the version number, and include the correct code accordingly. For instance:

```
#include "CCVersionConfig.h"

#ifndef COCOS2DX_VERSION_MAJOR
   // Must be v3.17.1 or below since these defines do not exist in that version
#else 
    #if COCOS2DX_VERSION_MAJOR >= 4
        // Version 4 code
    #else 
       // Version 3 code
    #endif
#endif 

```

**Comment by minggo** [comment]
It seems good, but in v3, we not just use CMake, so it is not suitable in v3.

**Comment by rh101** [comment]
@minggo Sorry, I should have mentioned that this is related to the upcoming version 4 release, and not specifically to do with version 3.  We just need a way to check if it's v4 at compile time.

**Comment by minggo** [comment]
Sorry about it. But we haven't decided the version name. Many developers, especially Chinese developers think it is not suitable to name it v4. And @linshun also think so.

**Comment by rh101** [comment]
Well, a possible solution is to introduce a new header file with the version info that should be manually updated on each release, so it's no longer the responsibility of CMake to generate the file with the version number.  We really do need a way to differentiate between versions, especially given the significant and breaking changes related to the new rendering code etc.

**Comment by minggo** [comment]
We will use CMake here, just need to determine the version.

**Comment by rh101** [comment]
@minggo I didn't realise that there already is a version define present in cocos2d.h:

```
#define COCOS2D_VERSION 0x00031701
```

That is good enough to use, and there is no longer a need to generate a header using CMake.  The only thing is that it can't be accessed from CMake to include certain files and not others, but I'm not sure that's a big issue.  You can close this specific issue if you wish.

**Comment by rh101** [comment]
The defines exist, even though there are several locations that need to be updated each time a new release is being prepared, so care should be taken in updating all of them.  This issue is not relevant given that there are ways to check for the version number.
