### ISSUE TITLE
Issue of reading sprite sheet when loading CCControlButton created by CocosBuilder

### ISSUE THREAD

**Issue by jordyli** [cocos2d/cocos2d-x#1958]
I packed my UI images using TexturePacker, and checked "Allow Rotation". Then I created a CCControlButton using images from that sprite sheet, but the button image is incorrect when running in simulator. Everything is fine if uncheck the "Allow Rotation" when packing.
I am using cocos2d-x v2.1beta3-x-2.1.1 and CocosBuilder 3 Alpha.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2658
