### ISSUE TITLE
No cc.ParticleSystemQuad for JS binding

### ISSUE THREAD

**Issue by ayuer** [cocos2d/cocos2d-x#1960]
cc.ParticleSystemQuad API is not generated for JS binding, we had to use cc.ParticleSystem to run particles, but it would be nice to have the same API.

**Comment by minggo** [comment]
Because CCParticlePoint is deleted, so there is only CCPartileQuad.
So CCParticle exported by JS binding is an alias name of CCParticleQuad.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
