### ISSUE TITLE
Spine runtime initialization takes much longer than v3

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#19616]
A developer found that Spine runtime has much more function call in [this PR](https://github.com/EsotericSoftware/spine-runtimes/pull/1244). The corresponding forum topic is [here](https://discuss.cocos2d-x.org/t/metal-support-alpha1-released/46282/9).

**Comment by PatriceJiang** [comment]
fixed in https://github.com/EsotericSoftware/spine-runtimes/pull/1244/commits/a8241185191857cf4650f10af23e933e26039e62
