### ISSUE TITLE
Update Glfw to 3.3

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#19610]
Glfw 3.3 released today and it adds a lot of features and fixes. 
@minggo  Will it be possible to include this in the next version of cocos2d-x?

**Comment by minggo** [comment]
Sure.

**Comment by minggo** [comment]
I tried to update to 3.3, but met the error on mac, then could not show the application content
```
2019-04-28 17:34:02.354991+0800 cpp-empty-test Mac[39829:1293351] Unknown class 'AppController', using 'NSObject' instead. Encountered in Interface Builder file at path /Users/minggo/Library/Developer/Xcode/DerivedData/cocos2d_tests-fxkupjwuhtxygugcbsprxsripwej/Build/Products/Debug/cpp-empty-test Mac.app/Contents/Resources/en.lproj/MainMenu.nib.
2019-04-28 17:34:02.355237+0800 cpp-empty-test Mac[39829:1293351] Could not connect action, target class NSObject does not respond to -toggleFullScreen:
```

I have not idea with it. My commit is [here](https://github.com/minggo/cocos2d-x-3rd-party-libs-src/commit/963607d21845b2eaacbecdb9656e5303a2a37082).

**Comment by Bilalmirza** [comment]
Sorry I didn't get a chance to use your commit.
I built glfw using cmake and replaced with the current and everything worked fine for me.

**Comment by minggo** [comment]
It is wired. What's your environment?

**Comment by Bilalmirza** [comment]
tested this on macOS only

**Comment by rh101** [comment]
@minggo I'll try to do a test on my Mac Mini to see what happens within the next few days, and I'll post back here.  On Windows (Win32) the GLFW 3.3 worked fine with Cocos2d-x.

**Comment by rh101** [comment]
@minggo I just built the template game code on Mac OS X with GLFW 3.3 successfully without issues (except some Spine SkeletonRenderer ambiguous type, just changing Rect => cocos2d::Rect fixed it).  I had to build the GLFW3.3 library, libglfw3.a, first, since one wasn't available to download.  This is using macOS Mojave 10.14.4, and Xcode 10.2.1.

The only other step is to make sure the updated GLFW3.3 headers, glfw3.h and glfw3native.h, are copied into all cocos2d/external/glfw3/include/linux, /mac and /win32 folders.

**Comment by minggo** [comment]
@rh101 how did you compile GLFW 3.3?

**Comment by rh101** [comment]
@minggo I did the following:

1) Downloaded the source package (or you can clone from Github tag 3.3): https://github.com/glfw/glfw/releases/download/3.3/glfw-3.3.zip

2) Generated out-of-build CMake project for Xcode as described [here ](https://www.glfw.org/docs/latest/compile_guide.html#compile_generate)

```
mkdir glfw-build
cd glfw-build
cmake <glfw-root-dir>
```

Then I opened up the generated project in Xcode 10.2.1, and compiled. Once that was complete, I copied over the header files and the newly built libglfw3.a file to Cocos2d-x, and compiled a test project.

**Comment by minggo** [comment]
I used scripts in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src to test. We will try later after releasing v4.0.
