### ISSUE TITLE
Cannot build to Android using the lateset Cocos version

### ISSUE THREAD

**Issue by cocos56** [cocos2d/cocos2d-x#19632]
- cocos2d-x version:3.17.1
- devices test on:Win10
- developing environments
   - NDK version:android-ndk-r18b and android-ndk-r19c
   - Xcode version:None
   - VS version:VS 2019Microsoft Visual Studio Enterprise 2019 16.0.2
VisualStudio.16.Release/16.0.2+28803.202
![image](https://user-images.githubusercontent.com/36597804/56496449-1530d900-652c-11e9-9f82-80277d22dea0.png)
Steps to Reproduce:
1.  Run "cocos compile -p android" using cmd
![image](https://user-images.githubusercontent.com/36597804/56497032-87a2b880-652e-11e9-96a1-74463fc2d840.png)

![image](https://user-images.githubusercontent.com/36597804/56496575-8ff9f400-652c-11e9-8726-64997ab46908.png)

I have trouble in configuring the development environment, could you provide me the tools that I needed. Such as SDK, NDK, you can packed these and then send to me. My email is zj175@139.com. Thank you in advance.  
Cause I have trouble in downloading tools from Google. You know , Chinese government ban access to Google in China Mainland. And even I can access Google by other ways, I can't distinguish the tools version that I downloaded matches Cocos.

**Comment by HTC77** [comment]
> * cocos2d-x version:3.17.1
> * devices test on:Win10
> * developing environments
>   
>   * NDK version:android-ndk-r18b and android-ndk-r19c
>   * Xcode version:None
>   * VS version:VS 2019Microsoft Visual Studio Enterprise 2019 16.0.2
>     VisualStudio.16.Release/16.0.2+28803.202
>     ![image](https://user-images.githubusercontent.com/36597804/56496449-1530d900-652c-11e9-9f82-80277d22dea0.png)
>     Steps to Reproduce:
> 
> 1. Run "cocos compile -p android" using cmd
>    ![image](https://user-images.githubusercontent.com/36597804/56497032-87a2b880-652e-11e9-96a1-74463fc2d840.png)
> 
> ![image](https://user-images.githubusercontent.com/36597804/56496575-8ff9f400-652c-11e9-8726-64997ab46908.png)
> 
> I have trouble in configuring the development environment, could you provide me the tools that I needed. Such as SDK, NDK, you can packed these and then send to me. My email is [zj175@139.com](mailto:zj175@139.com). Thank you in advance.
> Cause I have trouble in downloading tools from Google. You know , Chinese government ban access to Google in China Mainland. And even I can access Google by other ways, I can't distinguish the tools version that I downloaded matches Cocos.

https://docs.cocos2d-x.org/cocos2d-x/en/installation/prerequisites.html

**Comment by cocos56** [comment]
@HTC77 Thank you, I have solved this and write a Chinese article. https://blog.csdn.net/COCO56/article/details/89392349
