### ISSUE TITLE
can't access cocos forum http://discuss.cocos2d-x.org/

### ISSUE THREAD

**Issue by wijesijp** [cocos2d/cocos2d-x#19647]
I know this is not the place to ask this question but I have no option.

I can't access cocos forum at http://discuss.cocos2d-x.org/
Also can't access the documentation.

It is giving me following error 

This site can’t be reached discuss.cocos2d-x.org 
refused to connect.

Can someone provide some help?
Is there any information you need to sort this?

**Comment by minggo** [comment]
@slackmoehrle could you please take a look?

**Comment by slackmoehrle** [comment]
This should be fixed. There was an nginx issue Sunday night. @minggo please close.
