### ISSUE TITLE
Android Studio Gradle Warning for API 'variant.getMergeAssets()' 

### ISSUE THREAD

**Issue by HTC77** [cocos2d/cocos2d-x#19683]
- cocos2d-x version: 3.17.1
- devices test on:
- developing environments
   - NDK version: r16b
   - Xcode version:
   - VS version: 2015
   - browser type and version:
   - Android Studio version: 3.3.2
Steps to Reproduce:

1. Open proj.android in Android Studio
2. Build and run project
3. Gradle Warning will be appear:
API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.

**Comment by minggo** [comment]
@HTC77 could you please send a pull request to fix it?

**Comment by minggo** [comment]
duplicated with https://github.com/cocos2d/cocos2d-x/issues/19363
