### ISSUE TITLE
Crash on device with android 2.3.6

### ISSUE THREAD

**Issue by zabumba69** [cocos2d/cocos2d-x#1970]
When I try run the Testjavascript on Device 2.3.6 I got crash without error on logcat, only "Trying to load lib lib/libgame.so"

Non of the examples are working. Any ideas?

it's working fine in android 4.x

My cocos2d-x version is cocos2d-x v2.1beta3-x-2.1.0

Thanks in advance

**Comment by folecr** [comment]
How did you build the app?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2657
