### ISSUE TITLE
使用自定义字体文件xxx.ttf时，如果字库中不存在某个字时，会不显示，可以用系统字代替吗？

### ISSUE THREAD

**Issue by fndppx** [cocos2d/cocos2d-x#19709]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by minggo** [comment]
You should do it yourself, engine will not do it automatically. And please use english in future, thanks.
