### ISSUE TITLE
Cocos for WebAssembly

### ISSUE THREAD

**Issue by TedaLIEz** [cocos2d/cocos2d-x#19757]
As WebAssembly becomes supported by major browsers, I wonder whether cocos has an official release of wasm version. I found some [discussions](https://discuss.cocos2d-x.org/t/c-to-web-webassembly-polling-for-feature-request/33721) about this feature but it doesn't have a conclusion yet. Do cocos have such plan for wasm?

**Comment by minggo** [comment]
please discuss in forum, thanks
