### ISSUE TITLE
On Blackberry CocosDenshion doesn't support multiple background musics, used only last loaded.

### ISSUE THREAD

**Issue by moadib** [cocos2d/cocos2d-x#1976]
It's awful.

**Comment by haxpor** [comment]
Is that supposed to be the case for other platforms? Mostly 1 music but multiple of sfx played in the game.
Anyway better waiting for other contributors to answer this.

**Comment by moadib** [comment]
On IOS, Android and Windows too we can preload two(for example) tracks and switch them by calling `PlayBackgroundMusic("source1");` or `PlayBackgroundMusic("source2");`
