### ISSUE TITLE
TTF label set shader error

### ISSUE THREAD

**Issue by twolight** [cocos2d/cocos2d-x#19776]
- cocos2d-x version:3.17.1
- devices test on:mac os

OpenGL error 0x0502 in /Users/twolight/Documents/droidhang/idleheroes/hd/hd/hookheroes/frameworks/cocos2d-x/cocos/renderer/CCTextureAtlas.cpp drawNumberOfQuads 699

shader code:

#ifdef GL_ES
precision mediump float;
#endif

varying vec4 v_fragmentColor;
varying vec2 v_texCoord;

void main(void)
{
	vec4 c = texture2D(CC_Texture0, v_texCoord);
	gl_FragColor.xyz = vec3(0.2126*c.r + 0.7152*c.g + 0.0722*c.b);
	gl_FragColor.w = c.w;
}

**Comment by minggo** [comment]
It is better to provide a test case to reproduce it.

**Comment by twolight** [comment]
> It is better to provide a test case to reproduce it.

use default cocos2d-x demo

```bool HelloWorld::init()
{
    if ( !Scene::init() )
    {
        return false;
    }

    auto visibleSize = Director::getInstance()->getVisibleSize();
    auto glprogrom = GLProgramCache::getInstance()->getGLProgram(GLProgram::SHADER_NAME_POSITION_GRAYSCALE);
    
    auto label = Label::createWithTTF("Hello World", "fonts/arial.ttf", 24);
    label->setTextColor(Color4B(255, 0, 0, 70));
    label->setPosition(Vec2(visibleSize.width / 2,visibleSize.height / 2));
    label->setGLProgram(glprogrom);
    this->addChild(label, 1);
    
    return true;
}```

**Comment by minggo** [comment]
You can not replace gl program like this, it may have problem. As label with TTF has its own shader, and the draw codes heavily depends on the shader(can refer [here](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCLabel.cpp#L1565)). If you want to replace the shader, you should make sure it matches the codes or you should write your own drawing codes.
