### ISSUE TITLE
TTF label set shader error

### ISSUE THREAD

**Issue by twolight** [cocos2d/cocos2d-x#19775]
- cocos2d-x version:3.17.1
- devices test on:mac os

OpenGL error 0x0502 in /Users/twolight/Documents/droidhang/idleheroes/hd/hd/hookheroes/frameworks/cocos2d-x/cocos/renderer/CCTextureAtlas.cpp drawNumberOfQuads 699

shader code:

**Comment by minggo** [comment]
Could you please provide a test case?
