### ISSUE TITLE
COCOS2D_DEBUG is still set to 1 in release on android

### ISSUE THREAD

**Issue by ijm700** [cocos2d/cocos2d-x#19787]
I had a if(COCOS2D_DEBUG == 1) { do something } and on iOS it's not defined in release but on Android it is and even if you build in release mode it still runs the if statement pretty much saying that COCOS2D_DEBUG is equal to 1 

more info:
https://discuss.cocos2d-x.org/t/how-to-build-an-apk-in-in-release-mode-from-android-studio/25906
https://discuss.cocos2d-x.org/t/cocos2d-debug-in-release-builds/23434

**Comment by minggo** [comment]
What's your engine version? And how did you build with release mode on Android?

**Comment by ijm700** [comment]
engine version is 3.17.1, and I just changed the build variant to release, on iOS it works it doesn't define it for release but Android keeps it defined to '1' you could test it out to see just try a if statement with COCOS2D_DEBUG == 1 and you will see on both release and debug it runs the statement

**Comment by minggo** [comment]
I think it is fixed in https://github.com/cocos2d/cocos2d-x/pull/19291 which is merged in 3.17.2.

**Comment by ijm700** [comment]
@minggo is it possible to edit CocosConfigDefine.cmake ? I want to include this change in my project but I do not want to update to 3.17.2 just yet

**Comment by minggo** [comment]
Sure.

**Comment by ijm700** [comment]
I figured out how to do it :)

**Comment by ijm700** [comment]
whats the code doing differently ?

![Screen Shot 2019-06-03 at 9 47 10 PM](https://user-images.githubusercontent.com/24462583/58847637-58ad5580-8649-11e9-9a68-b89909f2c436.png)

**Comment by minggo** [comment]
I am not familiar with cmake too, it is just to set the COCOS2D_DEBUG to 1 in debug mode.
