### ISSUE TITLE
Add CCTextFieldTTF JS Binding

### ISSUE THREAD

**Issue by acrosslimited** [cocos2d/cocos2d-x#1979]
Please add the JS binding for the CCTextFieldTTF and having the same API for the cocos2d-html5.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to  https://github.com/cocos2d/cocos2d-x/issues/1979
