### ISSUE TITLE
Mac OS X apps don't quit

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#1980]
This can be seen in the HelloCpp project. Pressing the 'power' icon at the bottom right clears the window to white but the window doesn't close and application doesn't quit.
The code calls `CCDirector::sharedDirector()->end();` which (as I understand it) should cause the application to quit. Is this correct or is there another recommended way to quit the program?

I am using OS X 10.6.8, cocos2d-2.1beta3-x-2.1.1

**Comment by linguofeng** [comment]
add

``` cpp
#if (CC_TARGET_PLATFORM == CC_PLATFORM_MAC)
    exit(0);
#endif
```

**Comment by ghost** [comment]
OK. Are you saying this should go into all my projects (and the  HelloCpp project) - would it not be better in the OS X specific part of cocos2d-x?

**Comment by godyZ** [comment]
@peterhull90 Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2654
