### ISSUE TITLE
remove simple audio engine

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#19801]
New audio engine is designed to replace simple audio engine, and it is used for a long time, so it is time to remove simple audio engine. As new audio engine has different features compared to simple audio engine, can not use new audio engine to implement simple audio engine to keep compatibility.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/19802

**Comment by ijm700** [comment]
does this mean we will have to make any changes in our code if we use simple audio engine ?

**Comment by minggo** [comment]
Yep, use audio engine instead. It is only removed in v4, not in v3.x.

**Comment by minggo** [comment]
Yep, use audio engine instead. It is only removed in v4, not in v3.x.
