### ISSUE TITLE
win64 release 编译失败，debug可以

### ISSUE THREAD

**Issue by QiuleiWang** [cocos2d/cocos2d-x#19835]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by minggo** [comment]
May be it is similar to https://github.com/cocos2d/cocos2d-x/issues/19836. And please use english in future.

**Comment by rh101** [comment]
I don't think it's quite the same as #19836 since compiling for Windows x64 produces errors about missing libraries.  The external 3rd party pre-built libraries don't include x64 versions yet.

**Comment by MrCapone** [comment]
Check #18390

**Comment by Xrysnow** [comment]
@minggo I really need win64 version cocos, will it be formally supported in 4.0?

**Comment by FlyingdutchmanC** [comment]
https://github.com/FlyingdutchmanC/Cocos2d-x_WIN64 offers a solution for Windows x86 and x64 and linux for Release and Debug mode. Visual Studio 2017 and 2019 is supported.
