### ISSUE TITLE
Cocos2d-x 3.17.2 has the incorrect COCOS2D_X_VERSION set in CMakeLists.txt

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#19854]
- cocos2d-x version: 3.17.2

The cocos2d/cocos/CMakeLists.txt has not been updated to reflect the correct version number, so it is still as follows:

`set(COCOS2D_X_VERSION 3.17.1)`

There's nothing that can really be done about this given 3.17.2 has already been released, but please make a note to update it in the future, since developers may rely on this value to do conditional checks in the CMakeLists.txt file, such as:

```
if (COCOS2D_X_VERSION VERSION_GREATER 3.17.1)
else()
endif()
```

Close this issue at your convenience.

**Comment by slackmoehrle** [comment]
it is worth fixing: https://github.com/cocos2d/cocos2d-x/pull/19869
