### ISSUE TITLE
这个报错到底是什么意思？！换成陈述句不是更好吗？！

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#19877]
- cocos2d-x version: 3.17.2

出现下面这个报错的时候绝大部分人不知道到底要不要在继承类的onExit中调用父类的onExit()
换成陈述句不是更好吗？

CCASSERT(!_running, "Node still marked as running on node destruction! Was base class onExit() called in derived class onExit() implementations?");

**Comment by ghost** [comment]
这个问题老外都提到过，老外也没看明白

**Comment by minggo** [comment]
@slackmoehrle could you please help to fix it? Thanks.
