### ISSUE TITLE
[docs] The new renderer backend

### ISSUE THREAD

**Issue by PatriceJiang** [cocos2d/cocos2d-x#19879]

**Comment by Mee-gu** [comment]
1. Director::setDepth() is removed.
2. ShaderModule and feature not supported.
3. replace program

**Comment by Mee-gu** [comment]
[here is a doc show how to use backend](https://github.com/cocos2d/cocos2d-x-docs/pull/238)

**Comment by Mee-gu** [comment]
[add some api document](https://github.com/cocos2d/cocos2d-x/pull/19909)

**Comment by Mee-gu** [comment]
[V4 tutorials](https://github.com/cocos2d/cocos2d-x-docs/pull/243)
[V4 basic usage](https://github.com/cocos2d/cocos2d-x-docs/pull/238)
