### ISSUE TITLE
Js binding debugger failed to start in MoonWarriors sample project

### ISSUE THREAD

**Issue by tiantian20007** [cocos2d/cocos2d-x#1989]
When I turn JSB_ENABLE_DEBUGGER on in js_bindings_config.h and run the project, get error: MoonWarriors.app/main.debug.js:11:TypeError: cc.log is not a function

Then I add require("jsb.js") in main.debug.js and run again, It crashes with a exc_bad_access error:

Cocos2d: JS: ***\* will start debugger ****
Assertion failure: !cx->isExceptionPending(), at ../jscntxtinlines.h:367

github version: b1f4130 February 18, 2013 2:03:07 PM GMT+08:00
xcode 4.6 simulator 6.1

BTW, how exactly to use the debugger to set a breakpoint in js?

**Comment by dumganhar** [comment]
- Try to apply a patch of debugger for spidermonkey in this thread(https://github.com/cocos2d/cocos2d-x/pull/1832#issuecomment-13398678).
- Follow the tutorial here (https://github.com/funkaster/cxx-generator/tree/master/targets/spidermonkey/common)
