### ISSUE TITLE
Sprite initialization need optimization

### ISSUE THREAD

**Issue by PatriceJiang** [cocos2d/cocos2d-x#19907]
Sprite initialization is slower than v3

**Comment by PatriceJiang** [comment]
The hash procedure is heavy for static string in ccShaders. 

https://github.com/cocos2d/cocos2d-x/blob/77b1535a9d56860ad15a266c23b8135cb4e479ac/cocos/renderer/backend/ProgramCache.cpp#L84-L90

**Comment by JohnCoconut** [comment]
```cpp
std::string shaderSource = vertexShader + fragmentShader; 
```
Is this string concatenation necessary? Could we create a new hash bash based on two sub string hashes? Like this one in cppreference,  https://en.cppreference.com/w/cpp/utility/hash

```cpp
struct S {
    std::string first_name;
    std::string last_name;
};

// custom hash can be a standalone function object:
struct MyHash
{
    std::size_t operator()(S const& s) const noexcept
    {
        std::size_t h1 = std::hash<std::string>{}(s.first_name);
        std::size_t h2 = std::hash<std::string>{}(s.last_name);
        return h1 ^ (h2 << 1); // or use boost::hash_combine (see Discussion)
    }
};
```

**Comment by Mee-gu** [comment]
fixed in [19998](https://github.com/cocos2d/cocos2d-x/pull/19998)
