### ISSUE TITLE
A Crash occurs using Donwloader on some Android devices

### ISSUE THREAD

**Issue by jiny90** [cocos2d/cocos2d-x#19911]
- cocos2d-x version: 3.17

Fatal Exception: java.lang.RuntimeException
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.isDirectory()' on a null object reference
com.loopj.android.http.AsyncHttpResponseHandler.onUserException (AsyncHttpResponseHandler.java:304)
com.loopj.android.http.AsyncHttpResponseHandler.handleMessage (AsyncHttpResponseHandler.java:395)
com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage (AsyncHttpResponseHandler.java:510)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5601)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:964)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:759)
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.io.File.isDirectory()' on a null object reference
org.cocos2dx.lib.Cocos2dxDownloader$3.run (Cocos2dxDownloader.java:364)
android.app.Activity.runOnUiThread (Activity.java:5402)
org.cocos2dx.lib.Cocos2dxDownloader.enqueueTask (Cocos2dxDownloader.java:430)
org.cocos2dx.lib.Cocos2dxDownloader.createTask (Cocos2dxDownloader.java:404)
org.cocos2dx.lib.HeadTaskHandler.onSuccess (Cocos2dxDownloader.java:128)
com.loopj.android.http.AsyncHttpResponseHandler.handleMessage (AsyncHttpResponseHandler.java:351)
com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage (AsyncHttpResponseHandler.java:510)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5601)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:964)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:759)

This crash occurs while using Downloader on some Android devices.
59% Android 5
37% Android 6
2% Android 7
1% Android 8

39% HUAWEI
25% KYOCERA
9% asus
7% FUJITSU

**Comment by minggo** [comment]
It seems it crashed in 

https://github.com/cocos2d/cocos2d-x/blob/e7dd2c50c9cffae2931d954b5edf3902767f533d/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxDownloader.java#L363-L364

What's the path of `_tempFile`?

**Comment by jiny90** [comment]
> What's the path of `_tempFile`?

I get path using this java function

 public static String getDocPath(String fileName) {
        Context context = getContext();
        return context.getFilesDir().getPath() + "/" + fileName;
    }

and Cocos2d-x function is

    std::unique_ptr<network::Downloader> downloader;
    downloader.reset(new network::Downloader());
    downloader->createDownloadFileTask(strDownloadUrl, Cocos2dExt::NativeInterface::getDocPath(strFileName));

**Comment by jiny90** [comment]
I changed this part 

`downloader->createDownloadFileTask(strDownloadUrl, Cocos2dExt::NativeInterface::getDocPath(strFileName));`

to

`    downloader->createDownloadFileTask(strDownUrl, FileUtils::getInstance()->getWritablePath() + strFileName);`

And now above error doesn't occur.

**Comment by minggo** [comment]
So, when it crashes, what's the value of it? Is it a meaningful path?
