### ISSUE TITLE
dubious pointer casting in CCDrawNode

### ISSUE THREAD

**Issue by JohnCoconut** [cocos2d/cocos2d-x#19967]
- cocos2d-x version: current master branch

in `CCDrawNode.cpp`,

```C++
void DrawNode::drawDot(const Vec2 &pos, float radius, const Color4F &color)
{
    unsigned int vertex_count = 2*3;
    ensureCapacity(vertex_count);

    V2F_C4B_T2F a = {Vec2(pos.x - radius, pos.y - radius), Color4B(color), Tex2F(-1.0, -1.0) };
    V2F_C4B_T2F b = {Vec2(pos.x - radius, pos.y + radius), Color4B(color), Tex2F(-1.0,  1.0) };
    V2F_C4B_T2F c = {Vec2(pos.x + radius, pos.y + radius), Color4B(color), Tex2F( 1.0,  1.0) };
    V2F_C4B_T2F d = {Vec2(pos.x + radius, pos.y - radius), Color4B(color), Tex2F( 1.0, -1.0) };

    V2F_C4B_T2F_Triangle *triangles = (V2F_C4B_T2F_Triangle *)(_buffer + _bufferCount);
    V2F_C4B_T2F_Triangle triangle0 = {a, b, c};
    V2F_C4B_T2F_Triangle triangle1 = {a, c, d};
    triangles[0] = triangle0;
    triangles[1] = triangle1;

    _bufferCount += vertex_count;

    _dirty = true;
}
```

Here, _buffer is declared as `V2F_C4B_T2F *_buffer = nullptr;`, and `V2F_C4B_T2F_Triangle` is a struct of three `V2F_C4B_T2F` members.

Is this casting allowed? It seems to me that it violates this rule, https://wiki.sei.cmu.edu/confluence/display/c/EXP36-C.+Do+not+cast+pointers+into+more+strictly+aligned+pointer+types

We may use `alignas` to fix that. https://en.cppreference.com/w/cpp/language/alignas

**Comment by minggo** [comment]
I this case, i think there is not problem. `V2F_C4B_T2F` makes sure it is 4/8 bytes aligned, and `V2F_C4B_T2F_Triangle ` will not add padding between 3 `V2F_C4B_T2F `.

But it is easy to make error if the struct changes. And how will you use `alignas` to fix it?

**Comment by JohnCoconut** [comment]
@minggo Thanks for your clarification. I got confused somehow.

There is an example in cppreference, showing how to use `alignas`.

```c++
// every object of type sse_t will be aligned to 16-byte boundary
struct alignas(16) sse_t
{
    float sse_data[4];
};
 
// the array "cacheline" will be aligned to 128-byte boundary
alignas(128) char cacheline[128];
 
```
