### ISSUE TITLE
new bug from pr #19960

### ISSUE THREAD

**Issue by acvrp-lab** [cocos2d/cocos2d-x#19973]
there's definitely some bug about this modification somewhere, although i havent done much research. maybe because *= returns a reference to itself and assign to itself

buttons cant be clicked on if it or one of it's parent nodes is scaled up. there must be some miscalculation on it's bounding box.

https://github.com/cocos2d/cocos2d-x/pull/19960

**Comment by minggo** [comment]
The codes are reverted, thanks.
