### ISSUE TITLE
Using Donwloader to download large file downloads half crashes

### ISSUE THREAD

**Issue by lbllm** [cocos2d/cocos2d-x#19978]
- cocos2d-x version:3.17.2
- devices test on:android
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:
crash:
![image](https://user-images.githubusercontent.com/46704556/61810351-aab46f80-ae71-11e9-90fa-6ec660604af6.png)

**Comment by PatriceJiang** [comment]
The "data task" will save all data in memory, it will fail if memory is not enough. You can try to create a file task and delete the file after use.
