### ISSUE TITLE
Metal renderer backend: memory leaks on every render loop.

### ISSUE THREAD

**Issue by OlehKulykov** [cocos2d/cocos2d-x#19997]
- cocos2d-x version: cocos2d-x-4.0beta
- devices test on: macOS
- developing environments
   - NDK version:
   - Xcode version: Version 10.3 (10G8) (latest for now)
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Pull latest changes from 'v4' branch.
2. Confirgure as on Readme for mac with the next command: 
`cmake .. -GXcode -DBUILD_EDITOR_COCOSTUDIO:BOOL=OFF -DBUILD_EDITOR_SPINE:BOOL=OFF`
3. Open mac-build/Cocos2d-x.xcodeproj
4. Select "HelloCpp" demo app target.
5.1. Run in debug mode (CMD+R) a look into debug memory report tab(every 10 sec. + ~100 Mb RAM).
5.2. Profile in a release mode (CMD+I) and check memory leaks. 

![Screenshot 2019-07-30 at 13 12 45](https://user-images.githubusercontent.com/2852710/62124949-e87b2300-b2cb-11e9-8a26-adad9be983d8.png)

Following the documentation, the next drawable object must be used within autorelease pool.
https://developer.apple.com/documentation/quartzcore/cametallayer/1478172-nextdrawable?language=objc

**Comment by Mee-gu** [comment]
@OlehKulykov It's strange, it seems there is still a memory leak issue when I embed the render loop within an autorelease pool block:
![image](https://user-images.githubusercontent.com/29719737/62276044-c45b4580-b475-11e9-9fca-6bf7c54d6da2.png)
And it is seems still related to drawable?

**Comment by OlehKulykov** [comment]
Hi @Mee-gu , Not cool man, not cool! 
Please use at least metal documentation or apple's sample code or google. 
Let me help you: https://www.raywenderlich.com/7475-metal-tutorial-getting-started
Check step #1 "Creating a Display Link" then step #2 "Creating a Render Pass Descriptor" of the "Rendering the Triangle" tutorial part and do the same.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/20131
