### ISSUE TITLE
ui::Text is not displayed (v3.17.2)

### ISSUE THREAD

**Issue by seventhrank** [cocos2d/cocos2d-x#19992]
- cocos2d-x version: 3.17.2 (C++)
- devices test on: Android Nexus5
- developing environments
   - NDK version:  r19c
   - sdkbox IAP 2.4.3.3

ui::Text is not displayed at the "onSuccess" event after purchase (sdkbox IAP).

```
void ShopLayer::onSuccess(const Product &p)
{
    ui::Text *text = ui::Text::create();
    text->setPosition(Vec2(300.f, 300.f));
    text->setString("aaaaa");
    text->setFontSize(33);
    addChild(text);
}
```

It is displayed in 3.17.1

can work this issue below

```
void ShopLayer::onSuccess(const Product &p)
{
    scheduleOnce( [this](float f){
        ui::Text *text = ui::Text::create();
        text->setPosition(Vec2(300.f, 300.f));
        text->setString("aaaaa");
        text->setFontSize(33);
        addChild(text);
    }, 0.1f, "aaa");
}
```

**Comment by minggo** [comment]
I think i may caused by https://github.com/cocos2d/cocos2d-x/pull/19256. You can un comment `super.onPause();`.

**Comment by seventhrank** [comment]
It worked when commenting out `super.onPause();` of Cocos2dxGLSurfaceView.java

**Comment by minggo** [comment]
i sent https://github.com/cocos2d/cocos2d-x/pull/19996 to fix it
