### ISSUE TITLE
overlap problem on MI8

### ISSUE THREAD

**Issue by smilerfu** [cocos2d/cocos2d-x#20003]
- cocos2d-x version:3.17
- devices test on: MI 8
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. when you in the game，click the power button to lock the screen，and then after you unlock the screen and reenter the game， it will cause the overlap problem。
2. but After switching back and forth, it can return to normal。
3. If the developer mode is turned on and the lock screen is chosen to unlock and enter the system directly, there is no problem.
4. It may be related to the bottom log output:

07-19 15:39:27.499 791-791/? D/SurfaceFlinger: duplicate layer name: changing SurfaceView - com.xxx.AppActivity to SurfaceView - com.xxx.AppActivity#1
07-19 15:39:27.500 791-791/? D/SurfaceFlinger: duplicate layer name: changing Background for - SurfaceView - com.xxx.AppActivity to Background for - SurfaceView - com.xxx.AppActivity#1

https://tieba.baidu.com/p/5662537312?red_tag=3289231485

![68469566d0160924c248524dd80735fae7cd34b7](https://user-images.githubusercontent.com/5005827/62274740-0e8ef780-b473-11e9-992c-c7e7eb556c4f.jpg)
![5cb99dafa40f4bfb86bd6e020f4f78f0f63618b7](https://user-images.githubusercontent.com/5005827/62274747-1353ab80-b473-11e9-8b11-74379fb03ea1.jpg)

**Comment by AIGRIND-LLC** [comment]
I can only confirm the same issue.

**Comment by AIGRIND-LLC** [comment]
@smilerfu have you fixed this issue?

**Comment by wonyee** [comment]
maybe it's the same bug I encountered.
https://github.com/cocos2d/cocos2d-x/issues/20424

**Comment by AIGRIND-LLC** [comment]
@wonyee Thanks for the tip! It works for me!

**Comment by smilerfu** [comment]
@wonyee Thanks！It works for me too!
