### ISSUE TITLE
3.17.2 unzip don't use

### ISSUE THREAD

**Issue by QiuleiWang** [cocos2d/cocos2d-x#20013]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

cocos2d-x 3.17.2  win32 Vs vesion: vs2015 

appdelegate add code

#ifdef MINIZIP_FROM_SYSTEM
#include <minizip/unzip.h>
#else // from our embedded sources
#include "external/unzip/unzip.h"
#endif

#define BUFFER_SIZE    8192
#define MAX_FILENAME   512
bool uncompress(string outFileName, string _storagePath)
{
	// Open the zip file
	unzFile zipfile = unzOpen(FileUtils::getInstance()->getSuitableFOpen(outFileName).c_str());
	if (!zipfile)
	{
		CCLOG("can not open downloaded zip file %s", outFileName.c_str());
		return false;
	}
	return true;
}

error:

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "void * __cdecl cocos2d::unzOpen(char const *)" (?unzOpen@cocos2d@@YAPAXPBD@Z)，该符号在函数 "bool __cdecl uncompress(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?uncompress@@YA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z) 中被引用	testlua	E:\testlua\frameworks\runtime-src\proj.win32\AppDelegate.obj	1

**Comment by ChinaJoy88** [comment]
编译时宏定义重复了，将ioapi.h和unzip.h里面修改为即可解决：
#include "platform/CCPlatformConfig.h"
// #define CC_DLL

**Comment by QiuleiWang** [comment]
> 编译时宏定义重复了，将ioapi.h和unzip.h里面修改为即可解决：
> #include "platform/CCPlatformConfig.h"
> // #define CC_DLL

谢谢，我试试
