### ISSUE TITLE
cocos2d-x 3.15 使用websocket在IOS真机崩溃

### ISSUE THREAD

**Issue by baiyangzuoshu** [cocos2d/cocos2d-x#20030]
- cocos2d-x version:3.15
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:10.2.1
   - VS version:
   - browser type and version:

![image](https://user-images.githubusercontent.com/18391188/62942753-8c57e900-be0b-11e9-99f0-3469948d3a04.png)

**Comment by PatriceJiang** [comment]
Can you please describe how to reproduce it?
