### ISSUE TITLE
JniHelper ERROR```?

### ISSUE THREAD

**Issue by colamax** [cocos2d/cocos2d-x#2003]
02-19 12:55:29.770: D/JniHelper(3054): Failed to find static method id of getCocos2dxCacheDirectory

Ndk problems · ~?

**Comment by dumganhar** [comment]
Could you describe issues more clearly?
Which version of cocos2d-x you are using?

**Comment by colamax** [comment]
On the current git version

**Comment by colamax** [comment]
I want to know what the situation will be the error appears · · 
This error will affect cost framework?

**Comment by dumganhar** [comment]
So was it compiled ok by ndk, and was the .so file generated?
And did you import <code>cocos2dx/platform/android/java</code> to eclipse?

**Comment by colamax** [comment]
![ 2013-02-19 3 01 38](https://f.cloud.github.com/assets/680746/170327/5c267a38-7a62-11e2-9f01-3434b69df4a6.png)
![ 2013-02-19 3 02 16](https://f.cloud.github.com/assets/680746/170328/5c74b892-7a62-11e2-8fa3-73e2ee7d6be0.png)

this?

**Comment by colamax** [comment]
but`
error``
![ 2013-02-19 3 05 36](https://f.cloud.github.com/assets/680746/170330/d412d8c0-7a62-11e2-9bce-06e12200b2c3.png)

**Comment by colamax** [comment]
What it to?

**Comment by dumganhar** [comment]
Did sample projects also have this issue?
I mean that sample/Cpp/HelloCpp .

**Comment by colamax** [comment]
not `I was in other projects```so I would like to know what this error due to some

**Comment by dumganhar** [comment]
Try to refresh all projects in the _Package Explorer_ of eclipse.

**Comment by colamax** [comment]
What is the correct method of import cocos2dx/platform/android/java to eclipse?

**Comment by dumganhar** [comment]
![0DB75163-5977-455B-86A6-B5D0659CC4AE](https://f.cloud.github.com/assets/493372/170392/daee7f60-7a66-11e2-941c-74a8a5ecbf75.png)

**Comment by colamax** [comment]
![ 2013-02-19 3 38 50](https://f.cloud.github.com/assets/680746/170403/712e4ac8-7a67-11e2-9cde-cad4726147a2.png)

**Comment by dumganhar** [comment]
Yes.
Your game project also needs to be imported.

**Comment by colamax** [comment]
![ 2013-02-19 3 42 12](https://f.cloud.github.com/assets/680746/170412/eab6710e-7a67-11e2-8bc3-77bde5ca6f97.png)
whis~~?

**Comment by dumganhar** [comment]
Yep.

**Comment by colamax** [comment]
refresh all projects  always error``!
![ 2013-02-19 3 05 36](https://f.cloud.github.com/assets/680746/170416/43220b1e-7a68-11e2-8635-7928e8ea6540.png)

**Comment by dumganhar** [comment]
How about clean all projects?

**Comment by dumganhar** [comment]
Please make sure that HelloCpp sample could work..............

**Comment by colamax** [comment]
probject -> Claen....

**Comment by colamax** [comment]
i always copy org.cocos2dx.lib to the probject is work`~!

**Comment by colamax** [comment]
import cocos2dx/platform/android/java to eclipse but can't projec references for my probject ``!?

**Comment by colamax** [comment]
What is the correct method of import cocos2dx/platform/android/java to eclipse?
or What is the correct method of create cocos2d-x android probject in eclipse`?

**Comment by dumganhar** [comment]
Please refer to this page http://www.cocos2d-x.org/projects/cocos2d-x/wiki/How_to_build_and_run_HelloWorld_on_Android(gles20_branch).
