### ISSUE TITLE
ccui.TextField can't input multistage text (like chinese) in ios 13 beta7 

### ISSUE THREAD

**Issue by wulv1985** [cocos2d/cocos2d-x#20050]
- cocos2d-x version: 3.17.2 (lua)
- devices test on: iphone 6sp
- developing environments
   - NDK version:
   - Xcode version:  11.0（beta）/ 10.1  (both has this problem)
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.compile 3.17.2 lua test project
2.in the 69th test WebViewTest, there is a textfield which can input the url address. if the target devices is under ios13, we can input chinese. but in ios13 beta7, we can't. just no response after we press the keyboard.

**Comment by wulv1985** [comment]
@minggo

**Comment by minggo** [comment]
With latest codes, i can input Chinese on iPhone11 with iOS 13. I don't know what's the problem.

**Comment by lydjy-035** [comment]
系统原声输入法不可以。你可以试试。搜狗输入法可以

**Comment by wulv1985** [comment]
@minggo Sorry, i forgot to check this issue before.
1. my solution is similar to the discussion in #20174 , i manage the marked text by myself.
2. then i met the 2nd problem, when i close the IME, it open again! I found that there were several gestureRecognizer objects and subviews under main view, which were not existed in ios12 ! Remove the gestureRecognizer objects can solve the problem, but i finally decided to disable the gesture utility in main view, by return NO in function gestureRecognizerShouldBegin.
3. then i met the 3rd problem, when i enter the game, i found that the touchEnd message was delayed. after my finger left screen, i need to wait about 0.3s to receive the touchEnd msg. by reading apple doc, i realized it might be caused by the gestureRecognizer i mention before. i set the delaysTouchesEnded property to NO in the recognizers, and then everything is ok.

i did all this only in ios13, by checking the system version.

**Comment by minggo** [comment]
Thanks for sharing it. Now it seems i resolved keyboard issue in another way. But i don't notice the 3rd problem. Does 3rd problem only happen when using TextField?

**Comment by wulv1985** [comment]
yes, it only happen after i use TextField to input Chinese .

if i use TextField to input English or number, it will not happen either, because the gestureRecognizers will not appear !  it seems that the gestureRecognizers will only appear when i input Chinese

**Comment by minggo** [comment]
After you close the keyboard, does 3rd problem disappear too?

**Comment by wulv1985** [comment]
no, because the gestureRecognizers will not be detached from the main view

**Comment by minggo** [comment]
Now v3 uses a subview to receive input characters, so i think it doesn't have 3rd problem in main view now.
