### ISSUE TITLE
system fonts are not working on catalina

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#20076]
- cocos2d-x version: 3.17.1
- devices test on: macbook 2018
- developing environments
   - Xcode version: 10.3

Steps to Reproduce:

1.  make a new project (cocos new test -l cpp)
2. Run mac build
3. Use label::createWithSystemFont
4. https://www.dropbox.com/s/92e6a9glfw7wcom/Screenshot%202019-09-02%2010.26.31.png?dl=0
5. font is distorted

**Comment by minggo** [comment]
I tried `cpp-empty-test` on catalina(10.15 beta), it works correctly.
My environment:
- macOS Catalina(10.15 beta 19A646d)
- MBP Retina 15-inch Early 2013
- Xcode 10.3

**Comment by minggo** [comment]
I use latest engine codes.

**Comment by Bilalmirza** [comment]
I am redownloading everything to test

**Comment by Bilalmirza** [comment]
Are you trying ccp-empty-test Mac?

**Comment by Bilalmirza** [comment]
System fonts works fine on iOS. It fails on MacOS

**Comment by Bilalmirza** [comment]
https://www.dropbox.com/s/gotx8mj0by1kcu6/screen%20recording%202019-09-03%20at%202.14.54%20pm.mov?dl=0

**Comment by minggo** [comment]
Yep, i tried cpp-empty-test Mac.

**Comment by minggo** [comment]
The video showed that you used `cpp-tests`? It seems ttf font can not work. I will try it too.

**Comment by minggo** [comment]
I tried the same test case as you, and all are correct.

**Comment by Bilalmirza** [comment]
https://www.dropbox.com/s/but9b77xzc2xiim/Screen%20Recording%202019-09-03%20at%202.34.53%20PM.mov?dl=0

Its not working for me. Can you suggest what I should try.
MacOs Catalina : 10.15 Beta (19A546d)
Xcode : 10.3

**Comment by Bilalmirza** [comment]
Also i didn't pull from git... I downloaded from Website(https://cocos2d-x.org/download) 3.17.2

**Comment by minggo** [comment]
May be you can try to clone the codes to have a try.

**Comment by minggo** [comment]
If it works, then try to find what modification make it work.

**Comment by minggo** [comment]
@Bilalmirza any progress?

**Comment by Bilalmirza** [comment]
@minggo  Not really but something really weird is happening.

In macbook pro 2018 & 2017 this bug occurs.
I also managed to test it on 2014 macbook pro and everything works. I'm guessing the problem is at apples end, But I still need to fix this so build doesn't get rejected

**Comment by Bilalmirza** [comment]
For all languages I'm using ttf which works completely fine. I need to use system font for arabic because only system fonts support joining letters in arabic. My ios build was approved since in iOS the system font works fine as well.

**Comment by Bilalmirza** [comment]
v4 branch has the same result. 
Is it possible for you to test it on a newer mac?

**Comment by Bilalmirza** [comment]
@minggo I'm really sorry for spamming. But I'm stuck and my build got rejected

So far this is reproducible on:
Macbook 2017+  (haven't tested 2016)

cocos2d-x versions:
3.17.1
3.17.2
4.0 rc

If you have a monitor attached and if you go in displays->arrangement and set the monitor as the primary screen everything also starts working... It has to do something with the new macbooks retina display. But still not sure. Please take a look at the following video. 

https://www.dropbox.com/s/gullt7nuud2ikbm/macTestBug.MOV?dl=0

Let me know if you get any suggestions.

**Comment by slackmoehrle** [comment]
I can probably upgrade one of my laptops to Catalina over this coming weekend since it is a holiday.

**Comment by minggo** [comment]
Ok, i will use MBP 2018 to have a test.

**Comment by minggo** [comment]
My MBP 2018 can not install Catalina. I don't know why, i tried many times.
<img width="798" alt="Screen Shot 2019-09-11 at 3 03 30 PM" src="https://user-images.githubusercontent.com/488203/64675336-848c7280-d4a5-11e9-8ef4-c3bcf2bc853c.png">

**Comment by minggo** [comment]
After restart, it is installing now.

**Comment by minggo** [comment]
@Bilalmirza i fixed it with this commit https://github.com/minggo/cocos2d-x/commit/a0b46a9754345669b418b3f6f173b678fecacb2e. You can have a try. I will send PR after do more testing. I have to test if it work on before macOS Catalina.

After installing macOS Catalina, i can not use Astrill(it is a 32 bit system), so i can not use VPN now. Then i can not use google services now :(

**Comment by minggo** [comment]
@Bilalmirza have you tried it?

**Comment by Bilalmirza** [comment]
@minggo hello, I just came into office. I'm gonna try it now. 
And thank you so much you are a life saver :D

**Comment by Bilalmirza** [comment]
@minggo its working fine for me ... I'll get the QA team to perform tests on different device and ill report back.
Thanks again for all the trouble

**Comment by Bilalmirza** [comment]
Tested on:
macbook pro 2018  15" os : 10.15
macbook pro 2015  15" os: 10.14.4
macbook pro 2013 13" os: 10.15
Macbook Pro 2016 15" os: 10.14.6
Macbook Pro 2015 13" os: 10.14.3
iMac 2013 late os: 10.14.6

Everything working fine.

**Comment by minggo** [comment]
Thanks for the feedback, i will send a PR later.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/20124
