### ISSUE TITLE
Android: WebView in software mode when setting transparent background

### ISSUE THREAD

**Issue by bolino** [cocos2d/cocos2d-x#20108]
- cocos2d-x version: 3.17
- devices test on: Samsung Galaxy S9, Samsung Galaxy S6 

Hi, I noticed that when calling `webView->setBackgroundTransparent()` the performance of the webview is trashed on android, easily noticeable when scrolling. 
Upon further investigation I found the following code:
```
public static void setBackgroundTransparent(final int index) {
        if(android.os.Build.VERSION.SDK_INT >10) {
            sCocos2dxActivity.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Cocos2dxWebView webView = webViews.get(index);
                    if (webView != null) {
                        webView.setBackgroundColor(Color.TRANSPARENT);
                        try {
                            Method method = webView.getClass().getMethod("setLayerType",int.class,Paint.class);
                            method.invoke(webView,WebView.LAYER_TYPE_SOFTWARE,null);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }
            });
        }
    }
```

Setting the layer to software mode is the culprit, obviously, since the webview has to be rendered several times when scrolling. Commenting out the software layer code makes the webview run smoothly on both devices I tested.

I'm wondering why the layer is being set to software mode and if it's really necessary.

**Comment by imtrobin** [comment]
I think for older devices, it might be a bug

https://stackoverflow.com/questions/12806094/android-webview-flicker-bug-while-animating-view-on-device

**Comment by minggo** [comment]
@bolino i don't know why need to set layer, and @imtrobin 's comment seems reasonable. Is it because it uses reflection here that affect the performance? If so, i think can remove reflection here since supporting Android 10+ is enough.

**Comment by bolino** [comment]
From @imtrobin's link it seems they are actually animating/moving the WebView itself, this is not exactly my case. What is animated is the web page being displayed (just scrolling when using swipe) and this is when the performance really drops.

@minggo great! I reported it since I couldn't understand why software mode was being forced. As I said in my original post the performance drop is most likely caused due to the constant re-render (during scrolling) which is now using software mode because of the setLayerType call. I don't think it's related to the reflection itself, just to the WebView being set to software rendering.

**Comment by minggo** [comment]
@bolino got it, may be we should delete it. Have you found any issue after deleting it?

**Comment by bolino** [comment]
@minggo tried it on both Samsung Galaxy S9 and Samsung Galaxy S6 and couldn't notice anything wrong.
We just released an update for our game using this code and haven't got any reports regarding it, so far it seems to be working okay.

**Comment by minggo** [comment]
@bolino thanks, i will send a PR to fix it.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/20152

**Comment by minggo** [comment]
v4 fixed in https://github.com/cocos2d/cocos2d-x/pull/20155
