### ISSUE TITLE
doesn't support cygwin in windows 10

### ISSUE THREAD

**Issue by vince-styling** [cocos2d/cocos2d-x#20112]
- cocos2d-x version : cocos2d-x-3.17.2
- devices test on : windows 10
 
`setup.py` should support cygwin as :
```
def _isLinux(self):
        return sys.platform.startswith('linux') or sys.platform.startswith('cygwin')
```

i tested on my environments describe on first.

**Comment by minggo** [comment]
Indeed, we don't test cygwin, and we can not make sure it works.
