### ISSUE TITLE
I can't post to the forums

### ISSUE THREAD

**Issue by PudyJapan** [cocos2d/cocos2d-x#20117]
I'm really sorry to post that here, but I tried several times to reply to the new users thread on the forums to be able to create new posts but the reply button doesn't appear on the link below for my account.

https://discuss.cocos2d-x.org/t/new-users-read-this-new-user-guidance/25673

My username is the same as github.

**Comment by minggo** [comment]
@slackmoehrle could you please take a look?

**Comment by PudyJapan** [comment]
![image](https://user-images.githubusercontent.com/13039210/64982283-1b9a6580-d8be-11e9-9747-3be314d98ac3.png)
@minggo 
@slackmoehrle 
still, no reply button :(

**Comment by mnievas** [comment]
Hi, I have a similar problem.  In 2014 I fulfilled the requirements and post a thread. Now, I cannot and the reply is not showing even though I have completed my profile.  Here my old post.
Can somebody take a look? 
https://discuss.cocos2d-x.org/t/install-template-is-missing-in-cocos2d-x-3-2/15992/3

**Comment by AlexandreK38** [comment]
@minggo @slackmoehrle Hi! I'm facing the same issue, I can't write anywhere whereas I could in 2019... I have probably rights issues since then because I don't have reply button or whatever, even on the new user thread. Could you have a look please? My username on the forum is Kumamon38

**Comment by slackmoehrle** [comment]
@AlexandreK38 please e-mail me at slackmoehrle@cocos2d-x.org with your forum id.
