### ISSUE TITLE
Qt editor for v4?

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#20113]
Reading [this](https://retro.moe/2017/04/16/cocos2d-in-a-glimpse/) article from one of the Cocos2D creators - Ricardo Quesada, I think about his words: 

>  Work on just one editor: the Qt editor

Cocos2d-x already tried to make it. Please give a like if you think this is a cool idea to have such editor and work on C++ only side :)

**Comment by ghost** [comment]
I would recommend using [imgui](https://github.com/ocornut/imgui) to develop the editor.

**Comment by Anywhere-Music-Player** [comment]
Qt is not just for cross-platform GUI, but for real WYSIWYG. 
Idea is the same as was in SpriteBuilder: cocos engine renders everything inside the editor, another words it’s integrated as subproject of the editor project.

**Comment by Anywhere-Music-Player** [comment]
Closed as make no sense.

**Comment by Anywhere-Music-Player** [comment]
@piotrros you now a quiet as mouse? You asked a simple question and stated a truth about creator and your topic was removed. Now you understand that there is no future here?

**Comment by piotrros** [comment]
I'm not :) I couldn't answer in time on GitHub - issue was locked before I could do anything. I wasn't banned on forums (why should I be banned? I only asked nicely), but deleting all topics related to this issue was really cheap and silly move from whoever did that.

**Comment by Anywhere-Music-Player** [comment]
@piotrros I just was banned for the same, but I posted much more and pointed directly into the problems. You just like at the 1st stage of that) and yea, you asking nicely, well sometimes) "js is crap".. better not to say it there, if you don't want to be banned. 

Yea, very cheap and silly, and actually you know who did that, there is only 1 moderator, it's in all topics, because no one from cocos checking that forum, except if he calls it by name.

**Comment by Anywhere-Music-Player** [comment]
@piotrros So what he answered to you about removing your topic?

**Comment by Anywhere-Music-Player** [comment]
@piotrros also, what the reason of removing? Should be posted to your inbox. I just really wondering..
