### ISSUE TITLE
I can't compile with cocos console command

### ISSUE THREAD

**Issue by Joilnen** [cocos2d/cocos2d-x#20119]
- cocos2d-x 3.9 and 4.0:
- devices test on: PC
please see it
https://pastebin.com/UjdY1FNR

**Comment by minggo** [comment]
From the link it seems it is nothing about cocos.

**Comment by Joilnen** [comment]
I make a project with this command "cocos new -p com.dmood.risk -d ~ -l cpp Risk" and next "cocos compile -p linux" and got that output in ~/Risk/linux-build/CMakeFiles/CMakeError.log
Seems it is generating -lpthread and not -pthread in cocos new linux project
