### ISSUE TITLE
 argument value 10880 is outside the valid range [0, 255]

### ISSUE THREAD

**Issue by mars3142** [cocos2d/cocos2d-x#20129]
- cocos2d-x version: 3.17.2
- developing environments
   - Xcode version: 11.0 (11A420a)

Steps to Reproduce:

1. compile macOS version gets **argument value 10880 is outside the valid range [0, 255]** in btVector3.h in line 330.

**Comment by mrzhangjing** [comment]
#define BT_SHUFFLE(x, y, z, w) (((w) << 6 | (z) << 4 | (y) << 2 | (x)) & 0xff)

**Comment by dearbar** [comment]
@mrzhangjing  Hey, Thank you for your answer. What is the meaning of add `& 0xff` ?

**Comment by minggo** [comment]
To make sure it will not exceed 255.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/20163
