### ISSUE TITLE
cocos2dx lua class方法bug

### ISSUE THREAD

**Issue by QuiQiJingFeng** [cocos2d/cocos2d-x#20121]
cocos所有版本
![1](https://user-images.githubusercontent.com/12683327/64932660-24197e80-d873-11e9-806e-a69ada243b42.png)

线上有个报错，某个类里面的数据不存在，原因就是由于上面的self.super:ctor的写法造成的，
因为cocos的class只是模拟的类，当A和B继承C的时候,也就是他们公用一个C表，而不是各有一份C,这就造成了
当公用父类的时候会造成数据的相互覆盖问题

改成self.super.(self,...)又会出现死循环的问题

**Comment by QuiQiJingFeng** [comment]
![2](https://user-images.githubusercontent.com/12683327/64932739-8ffbe700-d873-11e9-8f91-15cfa94540fd.png)

**Comment by QuiQiJingFeng** [comment]
最后解决办法是改成了parent.ctor(self,...)

**Comment by QuiQiJingFeng** [comment]
还有一种是改class，但是有一些依赖class结构的地方不确定，所以没有改，比如iskindof就依赖于class现有的结构
![4](https://user-images.githubusercontent.com/12683327/64932768-d94c3680-d873-11e9-9081-8efe079cf396.png)

**Comment by kangzixiang** [comment]
i think this isn't a issue! just design thinking problem
