### ISSUE TITLE
warning: don't update it again

### ISSUE THREAD

**Issue by loohoo** [cocos2d/cocos2d-x#20149]
- cocos2d-x version: 3.17.2
- project type : cocos2d-js + win32 

Steps to Reproduce:
1. edit xxx.csd on  cocos studio 3.10 normally, and export xxx.json.
2. load xxx.json with  `this.addChild(ccs.load('xxx.json').node);`
3. build and run. 
4. `warning: don't update it again` comes out in the  console.

**Comment by minggo** [comment]
I think you can ignore it, and don't have resource on cocos studio related issues.
