### ISSUE TITLE
 Class AVAudioSession is implemented in both cocos2d and AVFoundation.framework. One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by anhbng** [cocos2d/cocos2d-x#20179]
- cocos2d-x version: 3.17.1
- devices test on: macosx10.15
- developing environments
   - NDK version: 
   - Xcode version: 11.0
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. build mac project with cmake and run with xcode
2. Log Class AVAudioSession is implemented in both...

**Comment by liumazi** [comment]
Hi, How did you solve the problem ？
