### ISSUE TITLE
Firefox can't debug v3.17+,  crashed when connected.

### ISSUE THREAD

**Issue by wumingbo** [cocos2d/cocos2d-x#20180]
- cocos2d-x version: 3.17.x
- devices test on: mac/ios
- developing environments
   - NDK version:
   - Xcode version:10/11
   - VS version:
   - browser type and version:firefox 60.x

Steps to Reproduce:

1. example

v3.16 is fine, crashed on v3.17.x

**Comment by loohoo** [comment]
me too!
I am using cocos2d-x 3.17.2. 
@minggo

**Comment by minggo** [comment]
The debug server is copied and modified from firefox, so it may not work with high version of firefox. We will not put more energy on it since it is not easy. So please use old version of firefox.

**Comment by loohoo** [comment]
try from firefox 30 to firefox 60.x, neither of them works.
cocos2d-x 3.16 works well.

**Comment by minggo** [comment]
> cocos2d-x 3.16 works well. 

What's the firefox version?

**Comment by loohoo** [comment]
> > cocos2d-x 3.16 works well.
> 
> What's the firefox version?

HI!, firefox v33.+
