### ISSUE TITLE
android lua random crashes

### ISSUE THREAD

**Issue by semgilo** [cocos2d/cocos2d-x#20222]
- cocos2d-x version:3.17   (external/lua had upgraded to 3.17.2)
- devices test on:samsung SM-G9650
- developing environments
   - NDK version:19.2.5345600

There are random crashes in 3.17 luajit, so I upgraded to 3.17.2's lua , armeabi7v is ok, but arm64-v8a is not.

**Comment by minggo** [comment]
You can try latest codes. It updated luajit.

**Comment by semgilo** [comment]
Do I need to update luacompiler ?I used luajit from cocos2d-x 3.17.2

**Comment by minggo** [comment]
I think you should update luajit.a in `external/lua/luajit`, and luajit bin in `tools/cocos2d-console/plugins/plugin_luacompile/bin`.

**Comment by semgilo** [comment]
ok thx, There is some trouble with the resources that were compiled with the old luacompile and the new luacompile, if they are not compatible.

**Comment by minggo** [comment]
Yep, you are right.

**Comment by semgilo** [comment]
I don't use new luacompile, and it seems be ok. I'll test more devices.
