### ISSUE TITLE
UI Editor? How do people create their UI?

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-x#20254]
Hi All,

@minggo 

I want to build the UI of my game in a a drag and drop editor. Is there such a thing in cocos2dx.?

I am using c++. I would like to create buttons, tables, labels etc and move and positon them in an easy way.

How do other people create their screen UI?

At this moment is seems that there is no good solution for UI/scene editing in cocos2d-x. Unfortunately, Cocos Studio won’t open anymore on Mac OS Catalina and Cocos Creator exporter for cocos2d-x hasn’t been updated in a long time and it doesn’t work very well. Also, didn’t hear anything new about SpriteBuilderX for a long time. It would be great to have a good scene editor for cocos2d-x, but it seems that the Cocos team is not really interested in 2dx anymore, so I’m not very optimistic about any future good news.

https://discuss.cocos2d-x.org/t/ui-editor-how-do-people-create-their-ui/46754

**Comment by halx99** [comment]
@KAMIKAZEUA

You can try: ```x-studio```: https://x-studio365.com/ it's compatible with CocosStudio but no TimeLine supported.
And there is anthoer powerful UI solution: http://www.fairygui.com/, it's have full feature of UI, but you need lean it, and you should use it's own SDK to load ui at game.

**Comment by Anywhere-Music-Player** [comment]
C++ only and open-source.

**Comment by crazyhappygame** [comment]
@KAMIKAZEUA for me it looks like forum question.
I am also curious what people are using...

**Comment by Anywhere-Music-Player** [comment]
I banned there by only 1 moderator for years, with a crown on his head.
So I'm asking here.

**Comment by deflinhec** [comment]
Cocos creator with serval tweaks to adapt my game.

**Comment by Anywhere-Music-Player** [comment]
@crazyhappygame do you think anyone interested in building such editor? I'm not sure who actually using cocos these days. Any new game is built with unity.

**Comment by imtrobin** [comment]
I will pay to have a good ui editor but it must support C++, not javascript.

**Comment by Anywhere-Music-Player** [comment]
From the https://discuss.cocos2d-x.org/t/creator-with-c-issues/48172
@piotrros This is actually a result of "smart move" by owners of this engine. 

The truth if simple, cocos2dx now has only one way direction - into the China and javascript, which is popular there. Asking about C++ is actually make no sense. 

And future of cocos2dx C++ part overall is very limited, considering previous direction into the js. 
 
As minggo said: "creator_to_cocos2dx is failure project", so this is the same will for the **Metal** support for cocos2d-x soon or later. 

For now idea is simple, make **Metal** work in some kind of way, like just make it compiled and no crash at launch, [great)](https://discuss.cocos2d-x.org/t/metal-support-rc0-released/47797). 
Next, push a topic on the forum and test on some users - so they should report issues and find bugs. Then gather these errors and try to fix them. Repeat.

This is a poor implementation of the process of development, with no real QA and development resources(like people and costly devices) are overall too costly to finalize. And question - why after all its needed to be done? [if no-one uses this at real](https://discuss.cocos2d-x.org/t/are-you-using-v4-metal-currently/47145) and direction is JS? Also, it will be production ready quality? Lol, ofc no. Think about it.

**Comment by imtrobin** [comment]
The whole issue is about money right? I mean, cocos2d as a company, needs revenue for dev work to continue, so an editor would be a rev source.

I can't and won't move to javascript, so unfortunately, cocos2dx editor decided to move in that direction.

**Comment by deflinhec** [comment]
> The whole issue is about money right? I mean, cocos2d as a company, needs revenue for dev work to continue, so an editor would be a rev source.
> 
> I can't and won't move to javascript, so unfortunately, cocos2dx editor decided to move in that direction.

I don't think money is the issue, it just not worth it. 

Unity achieved success with component-base system several years ago, and developers realize that the cost of building an UI editor under child-based system would takes a lot of effort than component-base system.

Consider of the complexity of modern games, I believe component-base system is taking the lead. If any one wants to build a reliable UI editor for Cocos2dx , they will rather aim for a long-term solution than a short-term solution.

**Comment by piotrros** [comment]
Thanks for mentioning my topic. I'm wasn't following all changes in creator and I thought it's for sure that c++ plugin works. What was being said hit me hard. We're now official without any editor and that's really a problem in the long term for our company. Almost all of our games use cocos2d-x and we still have to use Cocos Studio. I thought we'll eventually port to creator, but now it's impossible (I don't even consider rewriting everything to JS, which is nuts!).

**Comment by Anywhere-Music-Player** [comment]
You can try my SpriteBuilderX, but I’m not using it.. compiling under latest Xcode and Catalina gives me a bunch of problems, so switched to unity. Anyway in future, without Metal, it will be fully abandoned and not possible to use.

**Comment by piotrros** [comment]
Problems on Catalina doesn't seem promising. I've always wanted to try it out, but the big downside is that is requires different branch of cocos2d-x, which is now 16981 commits behind the main branch. In my opinion, an external editor (and possibly internal too) should not require different cocos2d-x branch and it requires to be constantly updated. As for Metal, you mean Metal support in SpriteBuilderX? Yeah, that may be the case.

We're thinking of Unity for new projects, but it's a big task. And we still have to maintain old projects. I like cocos2d-x workflow a lot more.

**Comment by Anywhere-Music-Player** [comment]
I've used this cocos branch for production game with millions of downloads. All stable.
But you can easily patch it with any new updates from main repo, but at your own risk ofc. 

You want too much, hold on :D 

Metal for SBX and for cocos2d-x actually too, because it's not ready and will not be I'm for 100% sure, just it's matter of time, when Apple fully remove OpenGL will be end of cocos2d-x era.

**Comment by crazyhappygame** [comment]
@KAMIKAZEUA could you share links to you apps with +millions of downloads?

**Comment by piotrros** [comment]
Apple will remove OpenGL some day, but cocos2d-x is being updated to Metal, right? They might also remove OpenGL on MacOS, but do these apps (Cocos Studio, SpriteBuilderX) even use Metal in the first place?

**Comment by Anywhere-Music-Player** [comment]
@crazyhappygame no.
@piotrros how it's being updated and it's quality I've already described. Again, will you use that update for production game?

**Comment by crazyhappygame** [comment]
@KAMIKAZEUA FYI similar topic created https://discuss.cocos2d-x.org/t/how-do-you-create-ui/48199

**Comment by Anywhere-Music-Player** [comment]
I banned there by only 1 moderator and he is really like a Dr. Evil with big crown. 

I'm not waiting any proper answer, as I said before - nobody cares about C++, thats all just mimics, when he said on the forums "we", there is no any actual we. 

Also, remember this cr@p)?  https://discuss.cocos2d-x.org/t/answering-the-questions-about-cocos-creator-the-engine-and-editor/38665 
Ohmy, that was fun, so much lie and not understanding of the future.

**Comment by Anywhere-Music-Player** [comment]
Also, all this lie continues, why all topic closed so) if people worried? 
https://discuss.cocos2d-x.org/t/the-future-of-cocos2d-x-c/42392

Just search https://discuss.cocos2d-x.org/search?q=future%20of%20cocos2d%20c%2B%2B 

Why bugs not been fixed for years? https://github.com/cocos2d/cocos2d-x/issues/18616 

Also, I can't find there some topic created by me, with **vote** C++ vs JS, and 80% voted for C++, but that topic was removed I guess, but closed for sure and after that I was banned, for telling and showing a truth.

**Comment by piotrros** [comment]
Unity might be only way in the long term... the problem is in China everyone uses Javascript, that's why they invest in it so much and they don't care about c++, because it's not popular in China. It's the opposite in the other places of the world. Maybe it's not like no one uses javascript for games, but there are other engines. For c++ not so much, at least not that popular as cocos2d-x. 

As I understand why they don't want to maintain 2 editors, open-sourcing is the simplest they can do. 

The same is for the engine itself. From a one hand, there are a lot of commits, but they're almost small fixes only. There are more than 1200 issues opened. Your bug is one of many examples. I don't know how many times I've struggled with audio. Luckily, cocos2d-x is open-source, so I could fix it myself.

**Comment by Anywhere-Music-Player** [comment]
I have a plan to build and own engine, C++ only for engine and ObjC for development, so quick and easy development... Just a dream..

**Comment by piotrros** [comment]
Yeah, just a dream. Creating a good engine from scratch is for big companies, which have resources to do so.

**Comment by Anywhere-Music-Player** [comment]
I want to become a big company :) 

And yea, just see what shit was thrown into your faces recently:

<img width="1206" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/68387915-2360e280-0168-11ea-85e7-90a2b0f1e638.png">

No, seriously. This is a C++ game engine, you and me and many other developers created many cool games for US, EU and other world market, but anyway direction was not the China.

I don't even know what tha heck is wechat is and don't even want to know. I'm as developer just want to develop games with ease for App Store and Google market.

**Comment by halx99** [comment]
Yeah, WeChat is not a correct direction.

**Comment by Anywhere-Music-Player** [comment]
p.s. @piotrros if this admin with crown will get here, he will ban me from cocos2dx repo too) so it's been nice to talk with you here.

**Comment by piotrros** [comment]
WeChat is a WhatsApp clone for China.

**Comment by deflinhec** [comment]
Godot might be an alternative solution? Which is an open source game engine written in C++.
They are working on Vulkan renderer and support Metal through MoltenVK, but still Metal support are not currently ready yet.

**Comment by Anywhere-Music-Player** [comment]
I don't like it, GUI and overall design like a product not for me. It's like comes from Windows guys...

**Comment by Anywhere-Music-Player** [comment]
@piotrros are you banned on the forum now lol? I see now all that topics removed) you made this idiot get angry, finally)) ahaha

upd. all topics even very old(was hidden and closed) and new were just deleted).

**Comment by minggo** [comment]
Sorry, i have to lock the topic as it is for issues.

**Comment by jareguo** [comment]
FairyGUI supports cocos2d-x. See http://en.fairygui.com/ and http://en.fairygui.com/guide/sdk/cocos2dx.html
