### ISSUE TITLE
Apple installation issues

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#20267]
- cocos2d-x version: latest from v3 branch
- devices test on: Mac OS 10.14
- developing environments
   - Xcode version: 11.1
   
Steps to Reproduce:

1. clone of v3 branch, `git submodule update --init`, `git submodule update`, `./download-deps.py`

2. `cocos new MyTest -l cpp -d .`

3. `cd MyTest`

4. ` cocos compile -p ios` -->  ERROR
```sh
** BUILD SUCCEEDED **

Build succeed.
Deploying mode: debug
Starting application.
CoreData: annotation:  Failed to load optimized model at path '/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'
Using simulator: iPhone 11 Pro Max (13.1)
running: 'xcrun simctl boot "6B53F7EA-A830-45B0-9211-31126BCD81B9"'

running: 'open `xcode-select -p`/Applications/Simulator.app'

running: 'xcrun simctl install "6B53F7EA-A830-45B0-9211-31126BCD81B9" "/Users/jason/MyTest/bin/debug/ios/MyTest-mobile.app"'

An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleShortVersionString.
Ensure your bundle contains a CFBundleShortVersionString.
Error running command, return code: 22.
```

__Reason:__

__proj.ios_mac/ios/Info.plist__ contains __CFBundleShortVersionString__ key but the string value is empty.

<img width="438" alt="Screen Shot 2019-10-29 at 15 41 32" src="https://user-images.githubusercontent.com/7491758/67803322-30444e80-fa63-11e9-96b0-ed7c6a452925.png">

__Solution:__

put a value in key ___CFBundleShortVersionString__ in ___proj.ios_mac/ios/Info.plist__ 

Compile successful.

<img width="1437" alt="Screen Shot 2019-10-29 at 15 48 39" src="https://user-images.githubusercontent.com/7491758/67803521-992bc680-fa63-11e9-9e8e-33f9a0db3f6e.png">

**Comment by Mee-gu** [comment]
Got it. I'll fix it.

**Comment by Mee-gu** [comment]
Got it.

> 4\. `cocos compile -p ios` -->  ERROR

@slackmoehrle  After going through from step 1 to step 4, there is no error, it compiles success.

**Comment by Mee-gu** [comment]
fixed in [20268](https://github.com/cocos2d/cocos2d-x/pull/20268)
