### ISSUE TITLE
cocos lua app will crash if lua include paths order is incorrect！！！

### ISSUE THREAD

**Issue by sonyps5201314** [cocos2d/cocos2d-x#20273]
- cocos2d-x version: 3.17.2 git latest
- devices test on:windows 8.1
- developing environments
   - VS version:vs 2017 latest

Steps to Reproduce:

1. create vs client game project,include path is $(EngineRoot)external\lua\lua;$(EngineRoot)external\lua\luajit\include
2. call lua_getstack(L, depth, &entry); next the program will crash with memory error.
fix solution:fix #define LUA_IDSIZE	512 in frameworks\cocos2d-x\external\lua\lua\luaconf.h as same to frameworks\cocos2d-x\external\lua\luajit\include\luaconf.h

我再用中文说一遍嘛，怕你们不懂，如果用户创建的游戏工程包含路径中$(EngineRoot)external\lua\lua在$(EngineRoot)external\lua\luajit\include前面因为都有luaconf.h这个文件，所以VS的编译器会使用第一个目录下的luaconf.h即frameworks\cocos2d-x\external\lua\lua\luaconf.h，但是这个目录下的LUA_IDSIZE宏的定义和luajit下的是不同的，cocos的patch文件只修改了luajit中的这个宏值为512，所以一旦调用lua_Debug结构体相关的函数如lua_getstack，lua_getinfo等，luajit内部就会写入512个字节到lua_Debug的short_src字段，而这里被定义成了60个大小和luajit内部中的不一致，所以导致了写多了字节进去，进而导致其他变量的缓冲区被覆盖了，进而可能引起崩溃，甚至远程代码执行漏洞。所以请两个地方都同步修改成512就没事了，或者修改回原来的60，即去掉cocos的这个patch。

**Comment by minggo** [comment]
@sonyps5201314 which patch cause the problem?

**Comment by minggo** [comment]
Ok, i see the difference between the two `luaconf.h`, i will track the log to see why they are different.

**Comment by minggo** [comment]
I track the log, it seems it is modified by luajit itself, no by us. And i think developers should not include lua and luajit at the same time. It is dangerous, and i think there will be many warnings.

**Comment by sonyps5201314** [comment]
this path is this file: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/blob/v3/contrib/src/luajit/luajit-v2.1.0-beta3.patch ,and other two patch files in the same folds.
but [the template project file](https://github.com/cocos2d/cocos2d-x/blob/v3/templates/lua-template-default/frameworks/runtime-src/proj.win32/HelloLua.vcxproj) was use the standand lua include files not the luajit includes. so every projects will occur this problem if them call these lua debug functions like above lua_getstack，lua_getinfo.

**Comment by minggo** [comment]
Yep, i din't notice it before. And i don't know why the patch is needed. I think you are right, we should not use it. And should not include both header files in the template.

**Comment by sonyps5201314** [comment]
yep，cocos use the standand lua include files，but use luajit import library and dll as default.

**Comment by minggo** [comment]
@PatriceJiang please update lujit and remove lua library as all platforms uses luajit.

**Comment by minggo** [comment]
https://github.com/cocos2d/cocos2d-x/pull/20277 fix the header file issue. And @PatriceJiang will rebuild luajit without the patch.

**Comment by sonyps5201314** [comment]
thanks

**Comment by minggo** [comment]
luajit is updated in https://github.com/cocos2d/cocos2d-x/pull/20306.
