### ISSUE TITLE
bullet/linearmath/btidebugdraw.h' file not found

### ISSUE THREAD

**Issue by tungnguyenvan** [cocos2d/cocos2d-x#20351]
- cocos2d-x version: 3.17.2
- devices test on: Macbook pro retina 13inch 2014
- developing environments
   - NDK version:
   - Xcode version: 11
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  In HelloScene include <3d/Physics3D>
2. create sprite3D with physics same in test project
3. build and error

**Comment by qzslz** [comment]
Have you find any way to solve this?

**Comment by tungnguyenvan** [comment]
I re-include any file .h in each error. Hope this solution can help you.

**Comment by qzslz** [comment]
> I re-include any file .h in each error. Hope this solution can help you.

thank you

**Comment by devekaam** [comment]
Hi, I encountered the same problem, but I cannot solve this.

What is the meaning of  "re-include any file .h in each error"?
I can't understand what should I do.

I hope you show the detail.
Thank you.

**Comment by devekaam** [comment]
> I re-include any file .h in each error. Hope this solution can help you.

Hi, I encountered the same problem, but I cannot solve this.

What is the meaning of "re-include any file .h in each error"?
I can't understand what should I do.

I hope you show the detail.
Thank you.

**Comment by devekaam** [comment]
I found the solution.

・Xcode
TARGETS > Build Settings > Search Paths > Header Search Paths

Add 2 values below. (YOUR_PROJ_FOLDER is cocos2d-x project folder path)

/YOUR_PROJ_FOLDER/cocos2d/external/bullet/include/bullet
/YOUR_PROJ_FOLDER/cocos2d/external/bullet/include

It works for me.
