### ISSUE TITLE
welcome cocos2d-x club!!!!

### ISSUE THREAD

**Issue by chanboo1985** [cocos2d/cocos2d-x#20367]
散落在成都各区的Cocosers,是否觉得在研发的浩海中微不足道，是否没有人进行battle,又或者找不到人解答目前的疑惑。希望能够通过“成都COCOS俱乐部”，为每一个cocos牵线搭桥，通过不定期举办俱乐部活动，增进彼此的联系，促进技术和生活的交流。
“成都COCOS俱乐部”人数超过10人后，我们将定期免费举办技术交流和大牛分享会。欢迎大家加入，共同开启俱乐部的未来。
![image](https://user-images.githubusercontent.com/8817112/69418246-450bbd80-0d55-11ea-9a3d-905ac4ddb6dd.png)

**Comment by minggo** [comment]
It is just for issues, please don't create similar issues again.
