### ISSUE TITLE
[v4] Xcode project generated by cmake cannot run on iOS simulator

### ISSUE THREAD

**Issue by ijk19** [cocos2d/cocos2d-x#20414]
- cocos2d-x version: v4 (at commit 9b2a2db6e3130fd6627733a2402c442d5cdb71c2)
- devices test on: Xcode 11.1 iPhone Simulator
- developing environments
   - NDK version: N/A
   - Xcode version: 11.1
   - VS version: N/A
   - browser type and version: N/A
   - cmake (homebrew) version: 3.15.5

Steps to Reproduce:
1. 
``` 
cocos new -l cpp test1
cd test1
mkdir ios-build
cd ios-build
cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos
open  test1.xcodeproj
```

2. In Xcode , change build target to test1->iPhone 8 Simulator,  cmd+r. 
Building will be successful but Xcode cannot run the product on simulator saying CFBundleExecutable in Info.plist is missing or invalid.

Extra info:
The problem seems to be caused by the recent commit  8214f279827e11cd9f67619522906f66ca2bbe40. It can be solved by ```git co ff333f7c0ad284def961d26be53454fadcddc6d3``` (the preceding commit just before the said one) in cocos2d-x repository.

**Comment by minggo** [comment]
@PatriceJiang please take a look.

**Comment by banujj** [comment]
Anybody looking for quick fix meanwhile:
Check your info.plist

```
<key>CFBundleDisplayName</key>
    <string></string>
    <key>CFBundleExecutable</key>
    <string></string>
```

Note that these key values are empty

Update them like below.

```
 <key>CFBundleDisplayName</key>
    <string>MyGame</string>
    <key>CFBundleExecutable</key>
    <string>MyGame</string>
```
