### ISSUE TITLE
Rendering bug (maybe) caused by using opengl device context when Acitivity is paused on Android 8.0+ devices

### ISSUE THREAD

**Issue by wonyee** [cocos2d/cocos2d-x#20424]
- cocos2d-x version: 3.17.2
- devices test on: OPPO A5 PBBM30 Android 8.1.0
- developing environments
   - NDK version: 16.1.4479499
   - Android Studio 3.3.2
   - Target SDK version: 28

Brief:
  I guess my lua code created Label TTF when AppActivity is paused, thus something goes wrong when I call setString.

Steps to Reproduce:
(*can't reproduce on system below Android 8.0)
1. create a new lua project
2. integrate some SDK that need to be initialized in AppActivity.onCreate
If the SDK arises AppActivity.onPause, and lua code created something with device context, then the objects may probably being created after onPause and before nativeOnPause, which caused some render problems

here is my log (with some code snippets)
<pre><code>
2019-12-24 15:58:03.554 D/AppActivity onCreate Called
2019-12-24 15:58:05.076 D/AppActivity onResume Called
2019-12-24 15:58:05.076 D/Cocos2dxActivity: onResume()
2019-12-24 15:58:05.302 D/Cocos2dxRenderer onSurfaceCreated
2019-12-24 15:58:05.737 D/AppActivity onPause Called
2019-12-24 15:58:05.737 D/Cocos2dxActivity: onPause()
2019-12-24 15:58:06.407 D/cocos2d-x debug info: [LUA-print] 15:58:06 before createWithTTF is Called
2019-12-24 15:58:06.628 D/cocos2d-x debug info: [LUA-print] 15:58:06 runWithScene Called
2019-12-24 15:58:06.901 D/Cocos2dxRenderer Cocos2dxRenderer.nativeInit Done
2019-12-24 15:58:06.932 D/Cocos2dxRenderer handleOnPause Called
2019-12-24 15:58:09.210 D/AppActivity: onResume Called
2019-12-24 15:58:14.297 D/cocos2d-x debug info: [LUA-print] setString Called
</code></pre>
<pre><code>
[in Cocos2dxRenderer.java]
    @Override
    public void onSurfaceCreated(final GL10 GL10, final EGLConfig EGLConfig) {
        Log.d("Cocos2dxRenderer","onSurfaceCreated");
        Cocos2dxRenderer.nativeInit(this.mScreenWidth, this.mScreenHeight);
        Log.d("Cocos2dxRenderer","Cocos2dxRenderer.nativeInit Done");
        this.mLastTickInNanoSeconds = System.nanoTime();
        mNativeInitCompleted = true;
    }
</code></pre>
<pre><code>
[in main.lua]
...
function main()
    local scene = cc.Scene:create()
    local layer = cc.LayerColor:create(cc.c4b(255,255,255,255))
    scene:addChild(layer)

    print("before createWithTTF is Called")
    local str = "ABCDEFG"
    local txt = cc.Label:createWithTTF(str,"fnt.ttf",32)
    txt:setColor(cc.c3b(0,0,0))
    txt:setPosition(cc.p(500,100))
    scene:addChild(txt)

    cc.Director:getInstance():runWithScene(scene)
    print("runWithScene Called")

    local delay = cc.DelayTime:create(5)
    local sequence = cc.Sequence:create(delay, cc.CallFunc:create(
        function()
            layer:setOpacity(128)
            txt:setString("AB")
            print("setString Called")
        end))
    layer:runAction(sequence)
end

main()
</code></pre>
<pre><code>
[in Cocos2dxRenderer.java]
    public void handleOnPause() {
        Log.d("Cocos2dxRenderer","handleOnPause Called");
        /**
         * onPause may be invoked before onSurfaceCreated, 
         * and engine will be initialized correctly after
         * onSurfaceCreated is invoked. Can not invoke any
         * native method before onSurfaceCreated is invoked
         */
        if (! mNativeInitCompleted)
            return;
        Cocos2dxHelper.onEnterBackground();
        Cocos2dxRenderer.nativeOnPause();
    }
</code></pre>

The log indicates LabelTTF's creation is after
"Cocos2dxActivity: onPause()"
and before
"Cocos2dxRenderer.nativeOnPause".
Is that the cause of the bug?

So, is it dangerous to switch between activities because 'actions that may arise onPause' will conflict with 'actions dealt with device context'?
![image](https://user-images.githubusercontent.com/6661018/71416870-6c7be000-269d-11ea-9df5-b260f930578a.png)

**Comment by drelaptop** [comment]
as I known  remove ` glSurfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT);` will solve some transparent issues occurs on activity onPause/onResume. so I suggest you to try it @wonyee

**Comment by wonyee** [comment]
@drelaptop 
It works! Comment out the following code solved the problem.
```
 //this line is need on some device if we specify an alpha bits
 if(this.mGLContextAttrs[3] > 0) glSurfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT);
```
But I'm not sure whether there's side effect?

**Comment by AIGRIND-LLC** [comment]
@drelaptop It works for me too! Great catch!
As I see this line is already commented in v4.0 by default.
