### ISSUE TITLE
CCEditBox position incorrect in a non-fullscreen CCNode.

### ISSUE THREAD

**Issue by heyfluke** [cocos2d/cocos2d-x#2043]
let's see this situation:
a CCLayerColor set width to half screen width and position to the right side of the screen.
a CCEditBox called eb.
in CCLayerColor:
eb->setPosition(ccp(100,100));
addChild(eb)

We can see a eb's background picture in the correct position - CCLayerColor's (100,100),
but the Placeholder of eb is in the screen's (100,100).

this problem is caused by CCEditBox::m_pEditBoxImpl, it seems to be a external control which is not draw by cocos2d-x's drawing system.

**Comment by heyfluke** [comment]
I try to fix this issue with the code below:

```
/* override function */
void CCEditBox::setPosition(const CCPoint& pos)
{
    CCControlButton::setPosition(pos);
    if (m_pEditBoxImpl != NULL)
    {
#if 0  // original code
        m_pEditBoxImpl->setPosition(pos);
#else  
        // fix external control position problem, by <fluke.l@gmail.com>
        // CCEditBox user must addChild() to parent before setPosition()
        if(m_pParent) {
            CCPoint p = m_pParent->convertToWorldSpace(pos);
            m_pEditBoxImpl->setPosition(p);
        } else {
            m_pEditBoxImpl->setPosition(pos);
        }
#endif
    }
}
```

but I can imagine that there still be a bug with drawing clipping region.

**Comment by dumganhar** [comment]
Thank you. I'll test the approach you provided. :)

**Comment by dumganhar** [comment]
@heyfluke 
I fixed the bug at https://github.com/cocos2d/cocos2d-x/pull/2045.
Could you pull the latest sources and try again?
Thank you.

**Comment by dumganhar** [comment]
> but I can imagine that there still be a bug with drawing clipping region.

You are right, but i think we can't avoid this problem since CCEditBox on iOS is using system ui control(UITextField) . I don't know how to cut the region of UITextField.
If you find the way, please let me know. Thanks.

**Comment by heyfluke** [comment]
OK. I will try to test. The first thing I need to figure out is how to update the system cocos2d-x to git version.

For the UITextField clipping region problem, I have no idea. cocos2d-x is not a UI framework.

**Comment by dumganhar** [comment]
> The first thing I need to figure out is how to update the system cocos2d-x to git version.

You could clone the source from github by:

<pre>
git clone https://github.com/cocos2d/cocos2d-x.git
git submodule update --init
</pre>

If you have cloned the repo, please use `pull` to get the latest sources.

<pre>
git pull https://github.com/cocos2d/cocos2d-x.git master
git submodule update --init
</pre>

**Comment by heyfluke** [comment]
@dumganhar , I just update my cocos2d-x and migrate my code. I have tested this issue too. It's fixed. Thank you!

**Comment by dumganhar** [comment]
That's cool. :) Thanks for testing.

**Comment by heyfluke** [comment]
sorry im not familiar with github's work flow. 
should I close this issue now?

**Comment by dumganhar** [comment]
OK, I closed it.
