### ISSUE TITLE
v4 JS/TS support dropped?

### ISSUE THREAD

**Issue by AlexReff** [cocos2d/cocos2d-x#20446]
I apologize if this is the wrong place for questions but I cannot find any discussion of why javascript support was dropped - is javascript support dropped going forward? Cocos Creator still supports javascript and typescript, why is it missing from here? Should I be looking to another repo? Or stick with v3?

**Comment by minggo** [comment]
Yep, JS is dropped. If you want to use Javascript, you can choose Cocos Creator.
