### ISSUE TITLE
DrawNode constructor and clear() behaviour different between V3 and V4

### ISSUE THREAD

**Issue by rh101** [cocos2d/cocos2d-x#20441]
- cocos2d-x version: Cocos2dx v3.17.2 and v4.0
- devices test on: Windows 10
- developing environments
   - VS version: VS2019

Steps to Reproduce:

In cocos2d-x v3.xx, `DrawNode` has the following constructor declaration and definition, and `DrawNode::clear()` method:

```
DrawNode(float lineWidth = DEFAULT_LINE_WIDTH);

DrawNode::DrawNode(GLfloat lineWidth)
: _lineWidth(lineWidth)
, _defaultLineWidth(lineWidth)
{
...
}

void DrawNode::clear()
{
    _bufferCount = 0;
    _dirty = true;
    _bufferCountGLLine = 0;
    _dirtyGLLine = true;
    _bufferCountGLPoint = 0;
    _dirtyGLPoint = true;
    _lineWidth = _defaultLineWidth;
}
``` 

In cocos2d-x v4.0:

```
DrawNode(float lineWidth = DEFAULT_LINE_WIDTH);

DrawNode::DrawNode(float lineWidth)
: _lineWidth(lineWidth)
{
...
}

void DrawNode::clear()
{
    _bufferCount = 0;
    _dirty = true;
    _bufferCountGLLine = 0;
    _dirtyGLLine = true;
    _bufferCountGLPoint = 0;
    _dirtyGLPoint = true;
    _lineWidth = 0;
}
```

You can immediately see several issues. Firstly, in v3, the constructor stores the passed in line width in a member variable, `_defaultLineWidth`. On a `DrawNode::clear()`, the line width is reset to the value contained in `_defaultLineWidth`.  That seems like a perfectly reasonable implementation.

Now with v4, `_defaultLineWidth` no longer exists, so the passed in line width on construction is no longer available, and even more, a call to `DrawNode::clear()` is setting the `_lineWidth` to 0, and not even the `DEFAULT_LINE_WIDTH`.

Was there a specific purpose for this change between v3 and v4? The v3 implementation was perfectly fine, so I personally can't see why it would have been changed.

The issue now is that calling `clear()` causes the line width to go to 0, breaking all code that expects the DrawNode to persist the line width that was passed in on construction of the object.

It honestly makes no sense at all to reset `_lineWidth` to 0, since that isn't even a valid line width, and not something that would be expected to happen given that even the `DEFAULT_LINE_WIDTH` is a value of 2.

IMHO, this should really be reverted back to the v3 implementation, re-introducing the `_defaultLineWidth` member etc.

**Comment by minggo** [comment]
Metal doesn't support line width, and yep, v4 should keep compatible as v3 if possible.

**Comment by rh101** [comment]
Line width still works on OpenGL, so on Android and Windows, calling `setLineWidth()` does change the width of the line.  Perhaps there should be a compile-time warning or an assert statement in 'setLineWidth()` if it is used while compiling for any platform that uses Metal, otherwise this would be inconsistent behavior between platforms that the developer will not know about unless they see the issue while the app is running with the Metal backend renderer.

In my case, I'll have to stop using `DrawNode`, since it's pretty much pointless now without the ability to set the line width for all rendering backends.

**Comment by Mee-gu** [comment]
fixed in [PR 20442](https://github.com/cocos2d/cocos2d-x/pull/20442)
