### ISSUE TITLE
4.0移除了js支持，怎么想的呢？要推广自家的cocos creator吗？

### ISSUE THREAD

**Issue by mingz2013** [cocos2d/cocos2d-x#20479]
4.0移除了js支持，怎么想的呢？要推广自家的cocos creator吗？

**Comment by xzben** [comment]
不废除js 不足以逼迫大家使用cocos creator哈哈哈哈

**Comment by minggo** [comment]
Please use english in future. The reason is that, we don't have enough resource to maintain it, and creator is also use JS, which is better support JS than cocos2d-x.

**Comment by pandamicro** [comment]
Of course, we don't have enough resources and we don't want our own products to fight each other.
And the old version of Cocos2d-x jsb is always there open sourced, there is really no barriers
