### ISSUE TITLE
android-async-http is no longer maintained

### ISSUE THREAD

**Issue by lyzz0612** [cocos2d/cocos2d-x#20480]
cocos used android-async-http for downloader on android platform.
The project posted a [notice](https://github.com/android-async-http/android-async-http#this-project-is-no-longer-maintained-and-is-currently-deprecated-and-insecure-to-use) and was archived recently. the last version is 1.4.10, fixed some tls/ssl problems like sni, but still many issues was ignored. will cocos upgrade or replace it with other library like okhttp?

**Comment by lyzz0612** [comment]
I have met several download problems on android recently. post here for someone the same with me.
my version is cocos3.15
1. download from https failed, the traceback tells the certificate not match。use wireshark to unpack packet, the server returns an certificate of other domain which run on the same server. it seems the client didn't send [`sni`](https://www.cloudflare.com/learning/ssl/what-is-sni/) to server on handshake. upgrade `android-async-http.jar` to 1.4.10 or init `AsyncHttpClient` with `AsyncHttpClient(true, 80, 443)` can fix it.
2. I set an network delegate on wifi setting just for testing(to separate debug from release environment), every device works fine except huawei. from the delegate server log, the client didn't  used the delegate to download.  `setProxy` by yourself.
3. when download a big file, on the progress, you turn down the network and turn on it before timeout. the download resume, but will start from zero, and more seriously, the downloading file didn't been remove, which means if you turn down on 50%, then turn on, and then turn down on 30%, then turn on. when finally finished, the file's content is (0-50%)+(0-30%)+(0-100%). change the `FileTaskHandler` 's parent class to `RangeFileAsyncHttpResponseHandler` will fix it. 
4. we put our resources on aliyun oss, and some file use `chunked` to transfer. the `totalBytesExpected` becomes zero(it is right logic, just a remind). I changed the parent class to `RangeFileAsyncHttpResponseHandler` for problem 3, and then it saved nothing because [`contentLength`](https://github.com/android-async-http/android-async-http/blob/e14a642befd778d76f0ad8aeb293449acd37cb69/library/src/main/java/com/loopj/android/http/RangeFileAsyncHttpResponseHandler.java#L86) is -1, override `getResponseData` to remove the judge will be ok.
5. we used `gzip` to compress data on transmission. the problem is similar to problem 4. the `contentLength` is compressed size, but the `RangeFileAsyncHttpResponseHandler` make it as the max size to write. it will of course lose some data.

**Comment by JoHuang** [comment]
I'm encountering the same issue on android platform seriously.
Apparently the resume function is broken and cause the files broken, it wastes server's bandwidth and user's time, and even though I checked the size of file to validate the files, the files may be still broken with the correct size.

@lyzz0612 Could you share some code to fix the downloader' issues, especially the FileAsync and resume-related ? thanks

**Comment by lyzz0612** [comment]
> I'm encountering the same issue on android platform seriously.
> Apparently the resume function is broken and cause the files broken, it wastes server's bandwidth and user's time, and even though I checked the size of file to validate the files, the files may be still broken with the correct size.
> 
> @lyzz0612 Could you share some code to fix the downloader' issues, especially the FileAsync and resume-related ? thanks

Is your problem the same with my problem 3? then just change the parent class of `FileTaskHandler` to `RangeFileAsyncHttpResponseHandler`. the reason why it didn't resume from last download position because it didn't send `Range` header, and `RangeFileAsyncHttpResponseHandler` [did it](https://github.com/android-async-http/android-async-http/blob/e14a642befd778d76f0ad8aeb293449acd37cb69/library/src/main/java/com/loopj/android/http/RangeFileAsyncHttpResponseHandler.java#L106). the request will add the header only when the handler is a type of `RangeFileAsyncHttpResponseHandler.java`, see [this]( https://github.com/android-async-http/android-async-http/blob/19ff79cc13b4164360dc5dac1dbb67573d55f48e/library/src/main/java/com/loopj/android/http/AsyncHttpRequest.java#L142).

Seriously, if you changed the parent class, you may meet my problem 4.

the solution is not for all situation. if the server use chunk or doesn't support `range` header, it is not suitable to use `RangeFileAsyncHttpResponseHandler` in fact.

**Comment by JoHuang** [comment]
@lyzz0612 Thanks for reply.
I'm a little bit confused.
I saw the Cocos2dDownloader.java sending range header.
https://github.com/cocos2d/cocos2d-x/blob/e3438ed3fd10a304b7ca2cd3dad9b29fead818d2/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxDownloader.java#L372-L377
Do you mean the Cocos2dDownloader.java implementation is not working?

**Comment by JoHuang** [comment]
<img width="812" alt="Screen Shot 2020-04-13 at 10 46 46 PM" src="https://user-images.githubusercontent.com/4118159/79129985-ca613e80-7dd8-11ea-881e-42622a989c8a.png">

Here is my modification for someone who encounters the same issue.
It should work as expected. About servers which use chunked transmission, I have no idea how to support it based on this code.

Thanks @lyzz0612

**Comment by lyzz0612** [comment]
> @lyzz0612 Thanks for reply.
> I'm a little bit confused.
> I saw the Cocos2dDownloader.java sending range header.
> https://github.com/cocos2d/cocos2d-x/blob/e3438ed3fd10a304b7ca2cd3dad9b29fead818d2/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxDownloader.java#L372-L377
> 
> 
> Do you mean the Cocos2dDownloader.java implementation is not working?

these codes work only on download start, not for resume. if you killed process on half progress, it will start from range when next start download. but turn off network and then turn on, it would not recall these code.

for the chunked transmission, my solution is not good, but I posted here wish it helps.
![image](https://user-images.githubusercontent.com/5645137/79180335-4345b200-7e3c-11ea-92aa-840eb6a67f15.png)
