### ISSUE TITLE
V4 have a render issue on the android Emulator

### ISSUE THREAD

**Issue by neo-godlike** [cocos2d/cocos2d-x#20505]
- cocos2d-x version:V4
- devices test on: android emulator like“夜神模拟器” “逍遥模拟器”
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. cpp-test project running in android emulator like “夜神模拟器” “逍遥模拟器” all sprite is red like this

<img width="490" alt="无标题" src="https://user-images.githubusercontent.com/18025536/80286071-d4c9f380-875b-11ea-88c3-ad50e89ca0f6.png">

and i tired created a new project it is look like same. can you guys have any idea?

2.

**Comment by halx99** [comment]
It fixed by engine-x, please see: https://github.com/c4games/engine-x/issues/41

**Comment by neo-godlike** [comment]
> It fixed by engine-x, please see: [c4games/engine-x#41](https://github.com/c4games/engine-x/issues/41)

thank a lot.u guys save the world lol:)
