### ISSUE TITLE
Problem compiling v4 in Android

### ISSUE THREAD

**Issue by makiolo** [cocos2d/cocos2d-x#20515]
- cocos2d-x version: 4.0
- devices test on: Android
- developing environments: Android Studio 3.6

Steps to Reproduce:

1. Build -> Make Project
2. Have this error:

```
CMake Error at cocos2d/cocos/CMakeLists.txt:151 (if):
if given arguments:
"3.6.0-rc2" "VERSION_GREATER_EQUAL" "3.16.0"
Unknown arguments specified
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```
The original code with problems is:
```
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.16.0")
    message("CMake 3.16 target_precompile_headers")
    target_precompile_headers(cocos2d PRIVATE 
       "$<$<COMPILE_LANGUAGE:CXX>:cocos2d.h>")
endif()
```
Probably is not a good solution, but works for me replacing by:
```
if(WINDOWS)
    message("CMake 3.16 target_precompile_headers")
    target_precompile_headers(cocos2d PRIVATE 
       "$<$<COMPILE_LANGUAGE:CXX>:cocos2d.h>")
endif()
```

I hope this helps.
Regards.
Ricardo.

**Comment by crazyhappygame** [comment]
Please install CMake 3.10.2
https://developer.android.com/studio/projects/install-ndk
CMake 3.6 is 4 years old.

**Comment by rh101** [comment]
You may need to add the `version "3.10.2"` line to your `proj.android/app/build.gradle` file, like this:

        externalNativeBuild {
            cmake {
                targets 'MyGame'
                arguments "-DCMAKE_FIND_ROOT_PATH=", "-DANDROID_STL=c++_static", "-DANDROID_TOOLCHAIN=clang", "-DANDROID_ARM_NEON=TRUE"
                cppFlags "-frtti -fexceptions -fsigned-char"
                version "3.10.2"
            }
        }

**Comment by crazyhappygame** [comment]
@rh101 
> Projects that don't set a specific CMake version in build.gradle are built with CMake 3.10.2.

https://developer.android.com/studio/projects/add-native-code#vanilla_cmake

**Comment by rh101** [comment]
@crazyhappygame Thank you for pointing that out! I didn't know they changed it, and the last time I saw that documentation it was still referencing 3.6 as the default.

**Comment by rh101** [comment]
@makiolo If what was posted in this thread fixes the problem you are having, then please let us know, and close this issue so it doesn't remaining in the list of open issues.

**Comment by makiolo** [comment]
I upgrade something (I am not sure, gradle, I think so), revert my change ... and now works.

I try add "version "3.10.2"" and also works. Probably my default cmake version changed upgrading AndroidStudio/Gradle.

Thanks @rh101 & @crazyhappygame
