### ISSUE TITLE
CCImage.mm on new macbook retina not work

### ISSUE THREAD

**Issue by linguofeng** [cocos2d/cocos2d-x#2051]
![eOdNN](https://f.cloud.github.com/assets/460328/199402/30240468-8080-11e2-813f-0e1a269f0294.png)

see: https://github.com/cocos2d/cocos2d-iphone/commit/25f71c130aad5b4373c6c53e84df2c19f015df73

**Comment by minggo** [comment]
Thank you.

**Comment by minggo** [comment]
Fixed in this [PR]:(https://github.com/cocos2d/cocos2d-x/pull/2054).
