### ISSUE TITLE
CCImageCommonWebp.cpp include problem

### ISSUE THREAD

**Issue by heyfluke** [cocos2d/cocos2d-x#2053]
I just upgrade to the git  version of cocos2d-x and found a problem.

CCImageCommonWebp.cpp
# include "decode.h"   // this include may conflit with some user's header file, because it's too common.

I suggest change to 
# include "webp/decode.h"

because platform/ios is in the header search path, and webp folder is right in platform/ios folder.

**Comment by minggo** [comment]
If it is a problem iOS specific, i think you can don't worry about it.
Because there is a xcode project for cocos2dx.

But your suggestion is good.

**Comment by dumganhar** [comment]
Hi @heyfluke @minggo 
I think you are right.
But the structure of third_party libraries is different on different platforms, please look inside `cocos2dx\platform\third_party`

<pre>
For android:
third_party/android/prebuilt/libwebp/include
</pre>

<pre>
For iOS and MAC:
third_party/ios/webp/
</pre>

<pre>
For windows:
third_party/win32/libwebp/
</pre>

It's a big problem that i didn't do that in your way.

**Comment by heyfluke** [comment]
@minggo @dumganhar I will suggest change decode.h to webpdecode.h then.

**Comment by dumganhar** [comment]
I don't suggest to modify the source codes of libwebp.

**Comment by heyfluke** [comment]
@dumganhar , do you think it's a good idea to keep subdirectory's structure in the same form under every platform ?

**Comment by dumganhar** [comment]
@heyfluke 
I think we could add another folder named `webp` like this. What do you think about that?

<pre>
For android:
third_party/android/prebuilt/libwebp/include/webp/(header files)
</pre>

<pre>
For iOS and MAC:
third_party/ios/webp/webp/(header files)
</pre>

<pre>
For windows:
third_party/win32/libwebp/webp/(header files)
</pre>

**Comment by heyfluke** [comment]
@dumganhar, that's great.
