### ISSUE TITLE
Sorry for this channel - I cannot post anymore to the Cocos2d-x Forum

### ISSUE THREAD

**Issue by Diomedea7** [cocos2d/cocos2d-x#20556]
Hi!

I read the topic "NEW USERS READ THIS!" and followed all advice except replying "Hi" because there was no reply button. I already posted to the Cocos2d-x Forum before but now I can't and I would be very grateful if you tell me what I am doing wrong or fix a potential forum issue.

My username in the Forum is "Diomedea".

Many thanks and best regards from Germany,
Jens

**Comment by minggo** [comment]
I have asked somebody to take a look. Sorry about that.

**Comment by minggo** [comment]
They told me that it is fixed, could you please try it again? Thanks.

**Comment by Diomedea7** [comment]
Many thanks, minggo!  :-)

**Comment by minggo** [comment]
You are welcome.
