### ISSUE TITLE
error: Objective-C was disabled in PCH file but is currently enabled

### ISSUE THREAD

**Issue by CaichaoGitHub** [cocos2d/cocos2d-x#20607]
- cocos2d-x version:V4
- devices test on: MAC
- developing environments
   - NDK version:
   - Xcode version: 12.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/12059897/98495991-7093fa80-227b-11eb-9b0a-66bbbf493554.png)

ERROR:
[ 16%] Building CXX object engine/cocos/core/CMakeFiles/cocos2d.dir/platform/apple/CCDevice-apple.mm.o
[ 17%] Building CXX object engine/cocos/core/CMakeFiles/cocos2d.dir/platform/mac/CCApplication-mac.mm.o
[ 17%] Building CXX object engine/cocos/core/CMakeFiles/cocos2d.dir/platform/apple/CCFileUtils-apple.mm.o
errorerror: : Objective-C was disabled in PCH file but is currently enabledObjective-C was disabled in PCH file but is currently enabled
error: Objective-C was disabled in PCH file but is currently enabled

I want to build cocos2d using cmake 

Following steps blew:

1、mkdir build & cd build
2、cmake --target cocos2d ..
3、make -j 3

**Comment by dmllr** [comment]
Hi @CaichaoGitHub, why did you close the issue?
I have a same problem while using cmake on mac, would you mind to describe a solution if you find it.

**Comment by CaichaoGitHub** [comment]
> Hi @CaichaoGitHub, why did you close the issue?
> I have a same problem while using cmake on mac, would you mind to describe a solution if you find it.

instead built it from original src, you should generate a cocos project , and built it in your project

**Comment by dmllr** [comment]
Same error even after generating new empty project for most recent sources but worked for 4.0.0.
Anyway I made a new issue for my trouble: https://github.com/cocos2d/cocos2d-x/issues/20621

**Comment by cainbit** [comment]
the issue is caused by the commit https://github.com/cocos2d/cocos2d-x/commit/7157fad9b908b671a4b06e3fc51a09fe096dea1b

I just modified the cocos2d/cocos/CMakeLists.txt
from

```
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.16.0")
    message("CMake 3.16 target_precompile_headers")
    target_precompile_headers(cocos2d PRIVATE
       "$<$<COMPILE_LANGUAGE:CXX>:cocos2d.h>")
endif()
```

to

```
if(!APPLE)
    if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.16.0")
        message("CMake 3.16 target_precompile_headers")
        target_precompile_headers(cocos2d PRIVATE
           "$<$<COMPILE_LANGUAGE:CXX>:cocos2d.h>")
    endif()
endif()
```

**Comment by crazyhappygame** [comment]
Under options would be to use Xcode generator
```
cmake -B b -S . -GXcode
cmake --build b --target cocos2d
```

**Comment by haodeon** [comment]
I am on macOS 10.14, my development tools consist of vscode, Xcode CLTools 11.3.1.0.1.1576735732 and CMake 3.22.1.

When I try and run `cmake -B b -S . -GXcode` I get `CMake Error:  Xcode 1.5 not supported.`

I applied the fix @cainbit shared above and managed to get around the error during build.
