### ISSUE TITLE
libcocos2d.dll is faulty

### ISSUE THREAD

**Issue by cfpwastaken** [cocos2d/cocos2d-x#20679]
- devices test on: my main computer (seems to be working on my laptop)

Steps to Reproduce:

1. Try to open any game with cocos2d
2. See the bug

Event Viewer:
```
Faulting application name: GeometryDash.exe, version: 0.0.0.0, timestamp: 0x5a13638c
Faulting module name: libcocos2d.dll, version: 0.0.0.0, timestamp: 0x5a1360bc
Exception code: 0xc00000fd
Error offset: 0x00116157
Faulting process id: 0x57a0
Faulting application start time: 0x01d7817b74c27de1
Faulting application path: C: \ Program Files (x86) \ Steam \ steamapps \ common \ Geometry Dash \ GeometryDash.exe
Faulting module path: C: \ Program Files (x86) \ Steam \ steamapps \ common \ Geometry Dash \ libcocos2d.dll
Report ID: 985a2c64-e642-4093-95bc-f49526c8a70c
Full name of the faulty package:
Application ID relative to the failed package:
```

I am sorry if I am not supposed to ask stuff like this here.
I tried posting it on the forum but I can't create new topics.

**Comment by kenzies100** [comment]
Hi, Have you found a solution to this problem? I've been dealing with this for over a year now.

**Comment by cfpwastaken** [comment]
Sadly no. I have since switched over to linux where the game just works using wine/proton.
It could be an issue with some operating system settings you have tho. Or your hardware just doesnt want idk

Which also means I can basically just close this issue.
If anyone found out a solution, please drop it here so others that have this issue too can fix it.
