### ISSUE TITLE
最近vs2017编译cocos成为

### ISSUE THREAD

**Issue by weiyu666** [cocos2d/cocos2d-x#20676]
- cocos2d-x version:4.0
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:2017
   - browser type and version:

Steps to Reproduce:

1. 下载完代码，download-deps.py下载依赖项，再然后setup.py，最后用cmake构建CMakeLists
2. 用vs2017打开编译出错如下图：
![image](https://user-images.githubusercontent.com/22174508/120953878-92594f80-c780-11eb-969d-2fbc1577d33f.png)

3. 环境变量各方面都是好的
![image](https://user-images.githubusercontent.com/22174508/120953930-a735e300-c780-11eb-8af5-7b72c354862d.png)

**Comment by wonyee** [comment]
GWL_WNDPROC -> GWLP_WNDPROC
GWL_USERDATA->GWLP_USERDATA

**Comment by weiyu666** [comment]
Unfortunately still not possible~
![image](https://user-images.githubusercontent.com/22174508/122515009-66bb4c80-d03f-11eb-8022-40dcef0dd747.png)

**Comment by wonyee** [comment]
我的意思是，把GWL_WNDPROC改成GWLP_WNDPROC...

**Comment by weiyu666** [comment]
谢谢大佬，都是国人；底下这些测试什么的用去理他吗？或者怎么解决？
![image](https://user-images.githubusercontent.com/22174508/122536099-c2dd9b00-d056-11eb-8696-50d4ce435155.png)
