### ISSUE TITLE
Packaging iOS applications in the GitHub Actions workflow

### ISSUE THREAD

**Issue by YCZ01111** [cocos2d/cocos2d-x#20789]
Since I don't have a Mac, I wanted to use GitHub Actions for packaging, but encountered many problems, such as "ModuleNotFoundError: No module named 'disttils'". I'm not sure if there are any examples of using Cocos to package iOS applications through GitHub Actions that I can learn from.

**Comment by minggo** [comment]
In order to build on iOS, you need to first use editor to build target for iOS. So it is not possible do it without a Mac.
