### ISSUE TITLE
SimpleAudioEngine::playBackgroundMusic() sets the volume to 1.0 on linux

### ISSUE THREAD

**Issue by jsambuo** [cocos2d/cocos2d-x#2078]
On linux, after calling playBackgroundMusic(), the bgm volume is set to 1, no matter what it was before. On Android, the volume does not change after calling playBackgroundMusic().

Here is the test case:

```
CocosDenshion::SimpleAudioEngine::sharedEngine()->setBackgroundMusicVolume(0.123f);
float oldBGMVol = CocosDenshion::SimpleAudioEngine::sharedEngine()->getBackgroundMusicVolume();
CocosDenshion::SimpleAudioEngine::sharedEngine()->playBackgroundMusic("sound.wav");
float newBGMVol = CocosDenshion::SimpleAudioEngine::sharedEngine()->getBackgroundMusicVolume();
CCLOG("BGM - before: %f  after: %f", oldBGMVol, newBGMVol);
CCAssert(oldBGMVol == newBGMVol, "Volume should not change after playBackgroundMusic()");
```

I'm using Kubuntu 12.10 x64, using code from the HEAD of the master branch.

**Comment by jsambuo** [comment]
Looking through FmodAudioPlayer, it looks like this is happening because when playBackgroundMusic() is called, the previous channel is stopped, discarded, and a new channel is retrieved. The new channel has it's own volume.
Effects work fine because they operate on a channel group, and the volume is set to the group.

I see two potential solutions:
1. Make BGM work on a channel group (similar to how effects work)
   - Requires bigger changes
   - Might be the cleaner solution
2. Save the old channel's volume and set the new channel's volume.
   - This is quicker and requires minimal changes
   - May still have another volume issue (see below)

My original test case won't actually work, even if playBackgroundMusic() didn't change the volume. Setting the volume before playing BGM won't do anything, since a channel doesn't exist. This might be another issue, which if is is, solution 1 would probably solve it.

```
SimpleAudioEngine *audioEngine = SimpleAudioEngine::sharedEngine();
audioEngine->playBackgroundMusic("music.wav");
audioEngine->setBackgroundMusicVolume(0.123f); //this doesn't work unless you play music first. preloading it won't work (preloading doesn't set pBGMChannel)
float oldBGMVol = audioEngine->getBackgroundMusicVolume();
audioEngine->playBackgroundMusic("music.wav");
float newBGMVol = audioEngine->getBackgroundMusicVolume();
CCLOG("BGM - before: %f  after: %f", oldBGMVol, newBGMVol);
CCAssert(oldBGMVol == newBGMVol, "Volume should not change after playBackgroundMusic()");
```

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to  http://www.cocos2d-x.org/issues/2653
