### ISSUE TITLE
CCSpriteBatchNode capacity increasing is working incorrect on some Android devices

### ISSUE THREAD

**Issue by moadib** [cocos2d/cocos2d-x#2079]
http://cocos2d-x.org/boards/6/topics/22674?r=23757

Requesting @minggo  in thread :)

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2652
