### ISSUE TITLE
android/prebuilt/libwebp/Android.mk cupfeature problem

### ISSUE THREAD

**Issue by heyfluke** [cocos2d/cocos2d-x#2088]
please read ndk manual CPU-FEATURES.html

it saids:

```
To use it, you must:

  * List 'cpufeatures' in your list of static library dependencies, as in:

        LOCAL_STATIC_LIBRARIES := cpufeatures

  * At the end of your Android.mk, import the 'android/cpufeatures' module,
    as in:

        $(call import-module,android/cpufeatures)
...
```

notice $(call import-module,android/cpufeatures) not $(call import-module,cpufeatures) .

if you use $(call import-module,android/cpufeatures) some where and $(call import-module,cpufeatures) in other place, ndk will claim redefinition of cpufeatures module.

**Comment by dumganhar** [comment]
@heyfluke 
Thank you, http://www.cocos2d-x.org/issues/1760 was created.

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2095 . :)
So could this issue be closed?

**Comment by heyfluke** [comment]
yes. thank you @dumganhar .
