### ISSUE TITLE
Packaging fails on BlackBerry project

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#2094]
After creating a BlackBerry using the create-blackberry-project.sh script the packager fails with the message: 

Packaging failed:1
Error: Invalid asset path "empty/../../../CocosDenshion/proj.blackberry/Device-Debug/libCocosDenshion.so"

![image](https://f.cloud.github.com/assets/2378847/215008/8e8be31a-845c-11e2-82e7-bb3e35eeb466.png)

I believe this is due to the 'empty' part of the file path included in the default bar-descriptor.xml

**Comment by dumganhar** [comment]
Hey, did the projects in the `samples` folder work?

**Comment by ghost** [comment]
Yes, the samples work fine. I think the problem is caused by the `empty` folder not being copied over in `create-blackberry-project.sh`. 

Why is `empty/empty` required? Can't the path just be `../../CocosDenshion`?

**Comment by dumganhar** [comment]
Yes, the relative path `../../CocosDenshion` actually can't work. 
Anyway, i can not make it work. Maybe you should have a try. :)

**Comment by ghost** [comment]
Yeah, happy to give it a go :) What didn't work? That path worked fine for me after I imported the CocosDenshion project into Momentics and built it.
