### ISSUE TITLE
OpenSLEngine.cpp can't load res from sd

### ISSUE THREAD

**Issue by waiter** [cocos2d/cocos2d-x#2096]
CocosDenshion\android\opensl\OpenSLEngine.cpp

line: 219
 LOGD("file not found! Stop preload file: %s", filename);
to :
 //LOGD("file not found! Stop preload file: %s", filename);

function : initAudioPlayer
if (FILE_NOT_FOUND == fd)
{
    return false;
}

to :

if (FILE_NOT_FOUND == fd)
{
    FILE\* fp = fopen(filename , "rb");
    if(fp){
    SLDataLocator_URI loc_fd = {SL_DATALOCATOR_URI , (SLchar*)filename};
    SLDataFormat_MIME format_mime = {SL_DATAFORMAT_MIME, NULL, SL_CONTAINERTYPE_UNSPECIFIED};
    (player->audioSrc) = {&loc_fd, &format_mime};
    return createAudioPlayerBySource(player);
    }
    LOGD("file not found! Stop preload file: %s", filename);
    return false;
}

**Comment by minggo** [comment]
@waiter 
Could you please send a pull request to fix it?

**Comment by waiter** [comment]
@minggo 
I'm new here. So I need time to learn how to pull request ...

**Comment by waiter** [comment]
It can be closed.
