### ISSUE TITLE
android crashes handing .png image with CgBI chunk.

### ISSUE THREAD

**Issue by heyfluke** [cocos2d/cocos2d-x#2097]
I got some pics with CgBI chunk ( which seems added by apple ) works on IOS normally but crashes android.

![chook1](https://f.cloud.github.com/assets/201604/215285/c7332508-8479-11e2-9ad3-9e67eb18205e.png)

**Comment by dumganhar** [comment]
Could you upload the `png` images for us to testing?

**Comment by heyfluke** [comment]
@dumganhar , I uploaded the image but the browser may not show correctly.

you  can also generate a file for yourself in http://convert-iphone-png-online.protonail.com/.

I think this should not be a bug of cocos2-x because apple break the standard.

I just wander if you  can add a specific err number when the code parsing this type of image instead of crash.

**Comment by godyZ** [comment]
@heyfluke  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2647
