### ISSUE TITLE
CCEditBox cannot focus in a non-fullscreen CCNode under android platform.

### ISSUE THREAD

**Issue by heyfluke** [cocos2d/cocos2d-x#2098]
The situation is like issue #2043 .

I find the editbox not responsable under android.

**Comment by dumganhar** [comment]
@heyfluke 
On Android, it's just a CCControlButton. No system ui control cover on it.
It should not have this problem. Could you tell me how to reproduce it?

**Comment by heyfluke** [comment]
you can simply wirite a sublayer using CCLayerColor inside the helloworldlayer, set the rect to the right half of screen, then add a cceditbox inside the sublayer.

you will find the cceditbox displays normal but without click effect, that means when you click on the editbox no keyboard will raise.

**Comment by godyZ** [comment]
@heyfluke Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
