### ISSUE TITLE
Error compiling SimpleGame for BlackBerry target

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#2101]
I receive the following error when compiling the SimpleGame sample: 

qcc -o SimpleGame main.o Classes/HelloWorldScene.o Classes/GameOverScene.o Classes/AppDelegate.o -lcocos2dx -lCocosDenshion -lEGL -lGLESv2 -lbps -lcurl -lxml2 -ltiff -ljpeg -lpng -lfreetype -lscreen -lm -lz -lOpenAL -lalut -lasound -V4.6.3,gcc_ntoarmv7le_cpp -w1 -lang-c++ -g -Wl,-z,relro -Wl,-z,now -L/Applications/bbndk/target_10_x_x_xxx/qnx6/../target-override/armle-v7/lib -L/Applications/bbndk/target_10_x_x_xxx/qnx6/../target-override/armle-v7/usr/lib -L../../../../../cocos2dx/proj.blackberry/Device-Debug -L../../../../../CocosDenshion/proj.blackberry/Device-Debug -L../../../../../cocos2dx/platform/third_party/blackberry/libraries/armle-v7 -Wl,../../../../../cocos2dx/proj.blackberry/Device-Debug/libcocos2dx.a

../../../../../cocos2dx/proj.blackberry/Device-Debug/libcocos2dx.a(CCImageCommonWebp.o): In function `WebPGetFeatures':
/Users/doturner/Documents/workspace-bbndk/cocos2d-x/cocos2dx/proj.blackberry/Device-Debug/../../../cocos2dx/platform/third_party/blackberry/include/libwebp/decode.h:394: undefined reference to`WebPGetFeaturesInternal'

**Comment by ghost** [comment]
This is caused by the webp library not being included in the linker libraries. Solution is to add it: 

![image](https://f.cloud.github.com/assets/2378847/216533/720d1972-84c8-11e2-8404-547b1c042be7.png)

**Comment by ghost** [comment]
Needs fixing by updating the project properties of the samples

**Comment by djogon** [comment]
Unfortunately - I get the same error even though -lwebp is included in linking parameters. See below

***\* Internal Builder is used for build               ****
qcc -o main.o ../main.cpp -V4.6.3,gcc_ntoarmv7le_cpp -w1 -I/Applications/bbndk/target_10_1_0_1020/qnx6/usr/include/freetype2 -I/Applications/bbndk/target_10_1_0_1020/qnx6/../target-override/usr/include -I../../Classes -I../../../ -I../../../cocos2dx -I../../../cocos2dx/include -I../../../cocos2dx/kazmath/include -I../../../cocos2dx/platform -I../../../cocos2dx/platform/blackberry -I../../../CocosDenshion/include -D_FORTIFY_SOURCE=2 -c -g -fstack-protector-strong 
qcc -o Classes/HelloWorldScene.o ../../Classes/HelloWorldScene.cpp -V4.6.3,gcc_ntoarmv7le_cpp -w1 -I/Applications/bbndk/target_10_1_0_1020/qnx6/usr/include/freetype2 -I/Applications/bbndk/target_10_1_0_1020/qnx6/../target-override/usr/include -I../../Classes -I../../../ -I../../../cocos2dx -I../../../cocos2dx/include -I../../../cocos2dx/kazmath/include -I../../../cocos2dx/platform -I../../../cocos2dx/platform/blackberry -I../../../CocosDenshion/include -D_FORTIFY_SOURCE=2 -c -g -fstack-protector-strong 
qcc -o Classes/AppDelegate.o ../../Classes/AppDelegate.cpp -V4.6.3,gcc_ntoarmv7le_cpp -w1 -I/Applications/bbndk/target_10_1_0_1020/qnx6/usr/include/freetype2 -I/Applications/bbndk/target_10_1_0_1020/qnx6/../target-override/usr/include -I../../Classes -I../../../ -I../../../cocos2dx -I../../../cocos2dx/include -I../../../cocos2dx/kazmath/include -I../../../cocos2dx/platform -I../../../cocos2dx/platform/blackberry -I../../../CocosDenshion/include -D_FORTIFY_SOURCE=2 -c -g -fstack-protector-strong 
qcc -o HelloCocos2D main.o Classes/HelloWorldScene.o Classes/AppDelegate.o -lCocosDenshion -lwebp -lEGL -lGLESv2 -lbps -lcurl -lxml2 -lOpenAL -lalut -lasound -ljpeg -lpng -lfreetype -lscreen -lm -lz 
...ETC...

../../../cocos2dx/proj.blackberry/Device-Debug/libcocos2dx.a(CCImageCommonWebp.o): In function `WebPGetFeatures':
/Users/djogon/Projects/cocos2d-2.1rc0-x-2.1.2/cocos2dx/proj.blackberry/Device-Debug/../../../cocos2dx/platform/third_party/blackberry/include/libwebp/decode.h:394: undefined reference to`WebPGetFeaturesInternal'
../../../cocos2dx/proj.blackberry/Device-Debug/libcocos2dx.a(CCImageCommonWebp.o): In function `WebPInitDecoderConfig':
/Users/djogon/Projects/cocos2d-2.1rc0-x-2.1.2/cocos2dx/proj.blackberry/Device-Debug/../../../cocos2dx/platform/third_party/blackberry/include/libwebp/decode.h:429: undefined reference to`WebPInitDecoderConfigInternal'
../../../cocos2dx/proj.blackberry/Device-Debug/libcocos2dx.a(CCImageCommonWebp.o): In function `cocos2d::CCImage::_initWithWebpData(void*, int)':
/Users/djogon/Projects/cocos2d-2.1rc0-x-2.1.2/cocos2dx/proj.blackberry/Device-Debug/../../platform/CCImageCommonWebp.cpp:65: undefined reference to`WebPDecode'
cc: /Applications/bbndk/host_10_1_0_132/darwin/x86/usr/bin/ntoarm-ld error 1
Build complete for project HelloCocos2D

I verified that libwebp.a is in the proper place (along with libtiff.a) 

Any ideas?

**Comment by djogon** [comment]
figured it out. One has to go to "Extra Options" under QCC linker and add the webp library there. tiff library is already in there webp is missing. Sigh.

**Comment by adagar** [comment]
Where are you guys accessing these properties? I'm not seeing them in xcode.

**Comment by minggo** [comment]
BlackBerry is not supported because of c++ 11.

**Comment by godyZ** [comment]
@doturner Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
