### ISSUE TITLE
build error in linux

### ISSUE THREAD

**Issue by mink365** [cocos2d/cocos2d-x#2105]
build in linux need some pthread library to be added.

diff --git a/cocos2dx/proj.linux/Makefile b/cocos2dx/proj.linux/Makefile
index d741870..a0a482c 100644
--- a/cocos2dx/proj.linux/Makefile
+++ b/cocos2dx/proj.linux/Makefile
@@ -170,7 +170,7 @@ STATICLIBS = $(STATICLIBS_DIR)/libfreetype.a \
                                $(STATICLIBS_DIR)/libtiff.a \
                                $(STATICLIBS_DIR)/libwebp.a

-SHAREDLIBS = -lglfw -lcurl -lfontconfig -lGLEW 
+SHAREDLIBS = -lglfw -lcurl -lfontconfig -lGLEW -lpthread

diff --git a/samples/Cpp/TestCpp/proj.linux/Makefile b/samples/Cpp/TestCpp/proj.linux/Makefile
index 861ba46..a678a10 100644
--- a/samples/Cpp/TestCpp/proj.linux/Makefile
+++ b/samples/Cpp/TestCpp/proj.linux/Makefile
@@ -159,7 +159,7 @@ SHAREDLIBS += -Wl,-rpath,../../$(SHAREDLIBS_DIR)

 SHAREDLIBS += -Wl,-rpath,../$(STATICLIBS_DIR)
-SHAREDLIBS += -lcurl
+SHAREDLIBS += -lcurl -lpthread -lGL

**Comment by azmeuk** [comment]
I can confirm the need for -lpthread with a Fedora 18 64bits.

**Comment by mdkcore0** [comment]
Confirm it is needed on Slackware 64 bits too (current)

On Fri, Mar 8, 2013 at 6:52 AM, Éloi Rivard notifications@github.comwrote:

> I can confirm the need for -lpthread with a Fedora 18 64bits.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-x/issues/2105#issuecomment-14613816
> .

## 

Rodrigo Gonçalves de Oliveira
Manaus, Brazil
rodrigo@thecoreme.org | rodrigo.golive@gmail.com
+55 92 82599445
http://br.linkedin.com/in/rodrigogoliveira
