### ISSUE TITLE
CCControlButton setTouchPriority not working.

### ISSUE THREAD

**Issue by vipsbpig** [cocos2d/cocos2d-x#2110]
As this post http://www.cocos2d-x.org/boards/6/topics/23041
I found the CCControlButton just can't be touched on an layer with registerWithTouchDispatcher();
I use CCControlButton object to  setTouchPriority ,but it just work the same.
Now
I change CCControl::registerWithTouchDispatcher() 

void CCControl::registerWithTouchDispatcher() {
CCDirector::sharedDirector()->getTouchDispatcher()->addTargetedDelegate(this, m_nDefaultTouchPriority, true);
}

into
    //Menu - Events
void CCControl::registerWithTouchDispatcher()
{
    CCDirector::sharedDirector()->getTouchDispatcher()->addTargetedDelegate(this, getTouchPriority(), true);
}

then it work..so is this a bug?or I just use the CCControlButton in wrong way?

**Comment by dumganhar** [comment]
@vipsbpig 
I think you change is right. :)
So could you send us a Pull Request?

**Comment by vipsbpig** [comment]
#2117 I think I just Pull Request on cocos2d-x ,am I doing right?..I am totally newbie to github.I think I should spent a little time on git stuff.

**Comment by minggo** [comment]
Well done.
