### ISSUE TITLE
CCEditBox Issue in Android

### ISSUE THREAD

**Issue by yashavantha** [cocos2d/cocos2d-x#2112]
Hi I am using cocos2d-x released on 28-jan-2013..i am porting my ios app to android ..CCEditBox  behaviour is unexpected..when i click on edit box, the edit box will be opened at the top of screen..

**Comment by dumganhar** [comment]
> the edit box will be opened at the top of screen..

? On android, it opens another view for input text.

**Comment by bhavnasahu89** [comment]
Hi can u please tell how to fix this problem......?

**Comment by dumganhar** [comment]
> Hi can u please tell how to fix this problem......?

It's designed to this for android.

**Comment by murilobianchini** [comment]
When we are talking on usability on android, it's really not a common way to type a text, despite the fact that it locks the screen until you press the "done/enter" button on the keyboard. It's just an opinion, I know it's the easiest way to make it work, but it can decrease the user experience in the android version of the game. Thanks for the answer.

**Comment by dumganhar** [comment]
@zergsbo 

> it's really not a common way to type a text

Yep, especially for a c++ game engine on android. It's hard to achieve `EditBox` like which on iOS, since different devices, android version have different behaviors, it's really hard to find a way to embed a system control onto opengl view. 

Maybe we could add `OK` and `Cancel` button on the view for input. What's your opinion?

**Comment by godyZ** [comment]
@zergsbo  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2708
