### ISSUE TITLE
jsval_to_ccdictionary - JS to native CCDictionary mapping problem

### ISSUE THREAD

**Issue by jdmunro** [cocos2d/cocos2d-x#2148]
Mapping a JS associative array to a native CCDictionary doesn't seem to be functional at the minute. As an example, passing data into initWithSpriteFrame on cc.AnimationFrame:

``` javascript
function exampleCrash(frame)
{
    var temp = new cc.AnimationFrame();
    temp.initWithSpriteFrame(frame, 1, { "apple": 0, "banana" : 1 });
    return temp;
}
```

This will cause either an assertion failure due to compartment mismatch (my guess is JSAutoCompartment should be used within jsval_to_ccdictionary as this one is not consistent) or the following assertion failure:

```
Assertion failure: JSVAL_IS_OBJECT_OR_NULL_IMPL(JSVAL_TO_IMPL(v))
```

On the following line:

```
JSObject *tmp = JSVAL_TO_OBJECT(prop);
```

**Comment by dumganhar** [comment]
@jdmunro 
OK, we will check it. Thanks for your replay.

**Comment by jdmunro** [comment]
OK thanks - I'll also take a look some time.

**Comment by dumganhar** [comment]
@jdmunro 
I fixed this issue in https://github.com/cocos2d/cocos2d-x/pull/2156.
You could try it by pull my branch. I think it will be merged soon.

**Comment by jdmunro** [comment]
Great, thanks!

**Comment by dumganhar** [comment]
:) If you try it, plz let me know whether it works. Thanks.

**Comment by dumganhar** [comment]
Well, you should generate js binding glue codes by entering `tools/tojs/` and `./genbindings.sh` since i moved the implementation of cc.Node.getChildren to jsb_cocos2dx_auto.h/.cpp .

**Comment by jdmunro** [comment]
@dumganhar Thanks, that seems to solve the problem for me :smile:

**Comment by dumganhar** [comment]
Good to hear that it works. :)

**Comment by dumganhar** [comment]
So could you close this issue?
