### ISSUE TITLE
CCClippingNode issue  after scene run scale action  

### ISSUE THREAD

**Issue by skyblue** [cocos2d/cocos2d-x#2162]
CCClippingNode

before  scene scale up
![1](https://f.cloud.github.com/assets/248937/257904/4d0219d6-8c7d-11e2-86ca-3b03c9b02c44.png)

after scene scale down:
![image](https://f.cloud.github.com/assets/248937/257899/cf5b6e1a-8c7c-11e2-8781-0615cf6b01c1.png)

**Comment by skyblue** [comment]
if CCClippingNode is a child of CCNode ,then CCClippingNode must setPosition with CCNode 's center point ,
But still looks like it's a issue of CCClippingNode

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2646
