### ISSUE TITLE
CCSize::equals is writing wrong .

### ISSUE THREAD

**Issue by vipsbpig** [cocos2d/cocos2d-x#2188]
bool CCSize::equals(const CCSize& target) const
{
    return ((width == target.width) && (height == target.height));
}

two float can not be compared like this ......

**Comment by dumganhar** [comment]
Hi @vipsbpig 
You are right. I think we should refactor that.

**Comment by dumganhar** [comment]
Thanks for your feedback.

**Comment by dumganhar** [comment]
Issue http://www.cocos2d-x.org/issues/1935 was created.
