### ISSUE TITLE
CCEditBox setFont retina display problems (iOS)

### ISSUE THREAD

**Issue by bomski** [cocos2d/cocos2d-x#2190]
I tried CCEditBox::setFont on a retina ios device and if you select the input field the font size gets doubled and if you release the focus the font gets back to normal font size.

This only happens on retina devices.

I fixed the problem by change the code in `CCEditBoxImplIOS::setFont` to this:

`UIFont *textFont = nil;
if ( m_bInRetinaMode ) {
  textFont = [UIFont fontWithName:fntName size:fontSize / 2];
}
else {
  textFont = [UIFont fontWithName:fntName size:fontSize];
}`

**Comment by dumganhar** [comment]
@bomski 
If i change the codes as you mentioned above, the font size will be smaller when input.
I tested it on iphone-retina 4.0-inch simulator.
Any ideas?
![ 2013-03-18 8 57 26 PM](https://f.cloud.github.com/assets/493372/270545/79035e4a-8fcb-11e2-9c7e-d1c2161d7c43.png)

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2191.
Thanks for your feedback.
