### ISSUE TITLE
CCControlSwitchSprite

### ISSUE THREAD

**Issue by KirillBarkousky** [cocos2d/cocos2d-x#2208]
All CCSprites changed texture to mask sprite from control switch. 
How to check:
start TestCpp project on android device-> go to Extension -> CCControl -> ControlSwitch
Power Off screen or wait for device sleep. Wake up device
![SC20130319-165628](https://f.cloud.github.com/assets/2129059/275865/ea2c2fc6-909c-11e2-9dee-6638497519b9.png)

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2644

**Comment by minggo** [comment]
It is fixed.
