### ISSUE TITLE
Multiline CCLabelBMFont has the wrong height after scaling

### ISSUE THREAD

**Issue by bomski** [cocos2d/cocos2d-x#2209]
I create a new CCLabelBMFont object and everything works fine. But if i scale this object to something like 0.7 the height get reduce but not in the correct way its still to big.

Because the `m_pConfiguration->m_nCommonHeight` are not scaling and always have the same value, just the `quantityOfLines` are changed.

```
void CCLabelBMFont::createFontChars()
{
...
totalHeight = m_pConfiguration->m_nCommonHeight * quantityOfLines;
...
}
```

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2642
