### ISSUE TITLE
CCNode::setZOrder should be protected method

### ISSUE THREAD

**Issue by WangZhiyong** [cocos2d/cocos2d-x#2235]
the method should be privated or protected method, like in Cocos2d-iPhone. otherwise it will make you very confused.

In fact, although you can call the method(it's public), but if the node's parent node is a CCSprite(overided CCNode::reorderChild) node, it never works as what you want! 

The only right and necessary way should be call the parent node's CCNode::reorderChild method, so call the CCNode::setZOrder directly is meaningless.

**Comment by minggo** [comment]
Cocos2d-iphone declares the method like this

```
@property(nonatomic,assign) NSInteger zOrder;
```

Is it means it is a protected method?

**Comment by WangZhiyong** [comment]
In the previous version, it's readonly, so I think the set method is "protected".

@property(nonatomic,readonly) NSInteger zOrder;

Sure, the current version changed to:

@property(nonatomic,assign) NSInteger zOrder;

So, I think it has same problem now. Because CCNode's setZOrder: changed it's zOrder_ first before calling the parent node's reorderChild:z: method calling, so the reorderChild:z: method will do nothing.

------------------ Original ------------------
