### ISSUE TITLE
error LNK2019 when using tinyxml2

### ISSUE THREAD

**Issue by tiantian20007** [cocos2d/cocos2d-x#2238]
In the newest 2.1.2 version, open HelloWorldScene.cpp in HelloCpp win32 project
add code:
tinyxml2::XMLDocument xx = new tinyxml2::XMLDocument();
run it:
1>HelloWorldScene.obj : error LNK2019: 无法解析的外部符号 "public: virtual __thiscall tinyxml2::XMLDocument::~XMLDocument(void)" (??1XMLDocument@tinyxml2@@UAE@XZ)，该符号在函数 "public: static class cocos2d::CCScene \* __cdecl HelloWorld::scene(void)" (?scene@HelloWorld@@SAPAVCCScene@cocos2d@@XZ) 中被引用
1>HelloWorldScene.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall tinyxml2::XMLDocument::XMLDocument(bool,enum tinyxml2::Whitespace)" (??0XMLDocument@tinyxml2@@QAE@_NW4Whitespace@1@@Z)，该符号在函数 "public: static class cocos2d::CCScene \* __cdecl HelloWorld::scene(void)" (?scene@HelloWorld@@SAPAVCCScene@cocos2d@@XZ) 中被引用
1>D:\cocos2d-x\Debug.win32\HelloCpp.exe : fatal error LNK1120: 2 个无法解析的外部命令

**Comment by minggo** [comment]
Tinyxml2 is not exported.

**Comment by tiantian20007** [comment]
OK, so if I need it, I have to include it again in my code. Is that a good idea?

**Comment by minggo** [comment]
Yep, you can do it like this on windows.
But it will meet problem in other platforms.

**Comment by toughrogrammer** [comment]
Hey, so couldn't I use tinyxml2?
Why tinyxml2 is existing on cocos2d-x-2.1.3 in cocos2dx\support\tinyxml2\?
And how can i use tinyxml2 for every platform?

**Comment by tiantian20007** [comment]
The latest version 2.1.4 has export tinyxml2. So now we can use it without include the source file again;
