### ISSUE TITLE
Chinese characters turn into unreadable code when using std_string_to_jsval

### ISSUE THREAD

**Issue by tiantian20007** [cocos2d/cocos2d-x#2240]
After upgrade to cocos2dx 2.1.2, Chinese characters turn into unreadable code when using std_string_to_jsval;

**Comment by dumganhar** [comment]
Is your chinese string an UTF8 string?

**Comment by tiantian20007** [comment]
Yes, it is. It works fine in the previous version of cocos2dx;

**Comment by dumganhar** [comment]
Hi, I think it's an issue. You could try to fix it like the following:

<pre>
jsval std_string_to_jsval(JSContext* cx, std::string& v) {
    return c_string_to_jsval(cx, v.c_str());
}
jsval c_string_to_jsval(JSContext* cx, const char* v) {
    jsval ret = JSVAL_NULL;
    jschar* strUTF16 = (jschar*)cc_utf8_to_utf16((char*)v);
    JSString* str = JS_NewUCStringCopyZ(cx, strUTF16);
    if (str != NULL) {
        ret = STRING_TO_JSVAL(str);
    }
    delete[] strUTF16;
    return ret;
}
</pre>

**Comment by dumganhar** [comment]
Let me know whether it works. Thanks.

**Comment by dumganhar** [comment]
This issue is caused by SpiderMonkey 19, we can't use the old way to generate js string.
Since there isn't a test case in TestJavascript to check this function, i will add one ASAP.
Thanks for your feedback.

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2244.
Could you try again?

**Comment by tiantian20007** [comment]
Yes, it works. Thx a lot;
