### ISSUE TITLE
WebP library is not universal on mac

### ISSUE THREAD

**Issue by billy1380** [cocos2d/cocos2d-x#2241]
There is an issue when attempting to build a project on mac while targeting both x86 and x86_64 i.e. universal binaries.

The linker throws a warning that it will ignore libwebp.a then you get the Undefined symbols for architecture x86_64 messages.

**Comment by dumganhar** [comment]
Yes, all the tests for MAC are set to  32bit target. So we didn't build a library of x86_64 version.

**Comment by billy1380** [comment]
Just in case anyone was interested I have used the framework quite extensively on mac x86_64 and everything builds and runs nicely. Most of the frameworks used e.g. libcurl, libxml2 are universal on mac so none of them have caused any issues. Would you like me to have a look at what it involves to build wepb as a universal binary and try to add it?

**Comment by dumganhar** [comment]
If you could help to generate a universal library of webp, that will be great. :)
You could find the source in my repo(https://github.com/dumganhar/cocos2dx-third-party-libs).
Thanks.

**Comment by billy1380** [comment]
So, I forked the repo and trying to figure out how to get it to build a universal version based on http://www.gnu.org/software/autoconf/manual/autoconf.html#Multiple-Architectures

In the mean time I have found that I can get a prebuilt version of the library using 

``` bash
sudo port install webp +universal
```

I have tested the x86_64 build with it and it works (no errors)

My question is this: is there any reason we can't just use that?

**Comment by dumganhar** [comment]
> My question is this: is there any reason we can't just use that?

I don't know the webp version installed by `port`.
We use the same source of webp to keep the behavior to be the same.
Therefore, i think it's better to build it by ourself. :)

**Comment by dumganhar** [comment]
Also, could you add x64 targets for MAC projects?

**Comment by billy1380** [comment]
I will give it a shot...

**Comment by billy1380** [comment]
I have submitted a pull request, not sure whether this is the best way to solve the problem... but it certainly stops the test app from crashing because the addresses are not being truncated. See what you think.

**Comment by billy1380** [comment]
@dumganhar are you happy for me to close this one?

**Comment by dumganhar** [comment]
I closed it. Thanks.
