### ISSUE TITLE
Imported Fonts Render Too High On iOS

### ISSUE THREAD

**Issue by Clarinexus** [cocos2d/cocos2d-x#2250]
On iOS, when we try to use a non-system TTF font that we've imported, the font renders higher than normal. Screenshot here: http://screencast.com/t/KrzVipgj On Android, it works just fine. We're having this issue with CCLabelTTF's loaded through both CCB and programmatically, and it seems to affect all non-default fonts that we could test.

(We also saw this on the cocos2d-iphone engine on Zynga Slots, and it was never fixed)

**Comment by ricardoquesada** [comment]
What should be the expected behavior ? The blue, pink or green ?

**Comment by Clarinexus** [comment]
The expected behavior should be the green line, which is Times, the system font.

The other two fonts are imported fonts.
