### ISSUE TITLE
onNodeLoaded will be called twice if add ccb as a CCBFile to another ccb

### ISSUE THREAD

**Issue by young40** [cocos2d/cocos2d-x#2253]
There are two ccb files in my Cocosbuilder project.
"MainScene.ccb", "Part.ccb"

and "Part.ccb" is bind to C++ class "PartLayer", and the class is a subclass of CCNodeLoaderListener, has a method "onNodeLoaded()"

then add "Part.ccb" as a CCBFile node to "MainScene.ccb".

if we load "MainScene.ccbi" in game, will be find "onNodeLoaded()" of "PartLayer" will be call twice.

It's is normal "onNodeLoaded" be called twice?

**Comment by dumganhar** [comment]
Thanks for your feedback. 
Issue http://www.cocos2d-x.org/issues/1860 was created.

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2369.  Thanks. Could you try again and give feedbacks to us?

**Comment by dumganhar** [comment]
If no problem, please close this issue. :)
