### ISSUE TITLE
CCLabelBMFont::setFntFile doesn't take effect immediately

### ISSUE THREAD

**Issue by csy1988525** [cocos2d/cocos2d-x#2255]
when i do setfntfile to a cclabelbmfont, it won't take effect. early patch is ok

**Comment by dumganhar** [comment]
Thanks for your feedback.
But in `LabelTest/BMFontInit`, it invokes setFntFile, and it works ok.

<pre>
BMFontInit::BMFontInit()
{
    CCSize s = CCDirector::sharedDirector()->getWinSize();
    CCLabelBMFont* bmFont = new CCLabelBMFont();
    bmFont->init();
    bmFont->autorelease();
    //CCLabelBMFont* bmFont = [CCLabelBMFont create:@"Foo" fntFile:@"arial-unicode-26.fnt"];
    bmFont->setFntFile("fonts/helvetica-32.fnt");
    bmFont->setString("It is working!");
    this->addChild(bmFont);
    bmFont->setPosition(ccp(s.width/2,s.height/4*2));
}
</pre>

![ 2013-03-25 11 12 26 AM](https://f.cloud.github.com/assets/493372/296450/e8a80dbc-94f9-11e2-9629-c72f2db48341.png)

**Comment by dumganhar** [comment]
So could you tell me how to reproduce this issue by step?

**Comment by totallyeviljake** [comment]
@dumganhar try setting the font file after the label has been set. In your example, set a delay selector that sets the font file after 1 or 2 seconds and see if the label changes size, or how quickly it changes. make sure you use a font file that is a different size.

**Comment by csy1988525** [comment]
I'm so sorry, I made a mistake that the setFntFile really does work. I use it in a wrong way. Sorry.
