### ISSUE TITLE
CCLabelTTF line break (\n) not working properly on iOS

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-x#2260]
When there are two \n one after another in a string to display with CCLabelTTF then not all lines will be shown on iOS. For example code below will not show the last line:
CCLabelTTF\* info = CCLabelTTF::create("line1\nline2\n\nline3\nline4", "Arial", 32 / CC_CONTENT_SCALE_FACTOR());

**Comment by godyZ** [comment]
@fins Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2639
