### ISSUE TITLE
CCUserDefault in iOS may not save immediately.

### ISSUE THREAD

**Issue by Yehsam23** [cocos2d/cocos2d-x#2262]
The CCUserDefault in iOS may not save immediately.

So the "flush()" function should add like this

void CCUserDefault::flush()
{
    [[NSUserDefaults standardUserDefaults] synchronize];
}

thanks

**Comment by dumganhar** [comment]
Thank you. Issue http://www.cocos2d-x.org/issues/1863 was created.

**Comment by Yehsam** [comment]
#2344 has fixed it

**Comment by minggo** [comment]
Yep, i modify it when i testing.
