### ISSUE TITLE
CCRect:: intersectsRect  not support  negative size.

### ISSUE THREAD

**Issue by xdxttt** [cocos2d/cocos2d-x#2263]
int cocos2d CGRectIntersectsRect  support negative size in CGRect.  and it works well.

in cocos2d-x  CCRect:: intersectsRect  not support  negative size. it make intersectsRect return wrong result.

here is the code to fix it.  :)

float CCRect::getMaxX() const
{
    return (float) MAX((origin.x + size.width),origin.x);
}

float CCRect::getMidX() const
{
    return (float)(origin.x + size.width / 2.0);
}

float CCRect::getMinX() const
{
    return MIN((origin.x + size.width),origin.x);
}

float CCRect::getMaxY() const
{
    return MAX((origin.y + size.height),origin.y);
}

float CCRect::getMidY() const
{
    return (float)(origin.y + size.height / 2.0);
}

float CCRect::getMinY() const
{
    return MIN((origin.y + size.height),origin.y);
}

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2513
