### ISSUE TITLE
Crash when drawNumberOfQuads

### ISSUE THREAD

**Issue by stubma** [cocos2d/cocos2d-x#2264]
branch master-v2

for following code, if comment out first drawNumberOfQuads, then second drawNumberOfQuads will crash. 
        CCSpriteBatchNode\* sheet = ...;
        CCTextureAtlas\* atlas = sheet->getTextureAtlas();
        atlas->drawNumberOfQuads(1, 0);
        atlas->drawNumberOfQuads(1, 1); // crash when previous call is commented out

or, if I insert a getQuads before second drawNumberOfQuads, it will crash also.
        CCSpriteBatchNode\* sheet = _iter;
        CCTextureAtlas_ atlas = sheet->getTextureAtlas();
        atlas->drawNumberOfQuads(1, 0);
        atlas->getQuads();
        atlas->drawNumberOfQuads(1, 1); // crash

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2637
