### ISSUE TITLE
CCTransitionCrossFade and glScissor Bug

### ISSUE THREAD

**Issue by bomski** [cocos2d/cocos2d-x#2266]
Hi,

i found a bug in the `CCTransitionCrossFade`, that the textures which the crossfade creates are not correct if a layer of the scene is using `glScissor` and you have set before the designResolution and are not on the designResolution.

<b>Reproduce steps:</b>

<ul><li>Set the design resolution with CCEGLView::sharedOpenGLView()->setDesignResolutionSize(...)
</li>
<li>Start the simulator with a different resolution</li>
<li>Crossfade to a scene with a layer which use glScissor (for example a layer with a CCScrollview)</li>
<li>Part of the texture where the glScissor is used is wrong</li>
</ul>

<b>Problem:</b>
In `CCTransitionCrossFade::onEnter()` this 

```
inTexture->begin();
m_pInScene->visit();
inTexture->end();
```

is called to render the scene to the `CCRenderTexture`, but in this case to add `m_obViewPortRect.origin` in `void CCEGLViewProtocol::setScissorInPoints` lead to a wrong scissor rect.

**Comment by ttencate** [comment]
@minggo: Did you use the right issue number in the above commit? It seems to be unrelated to this issue, and indeed I'm probably having the same problem as described above in 2.1.4, which was released after this commit. So maybe this should be reopened?
