### ISSUE TITLE
[Android] CCClippingNode is not working after apps comes from background

### ISSUE THREAD

**Issue by felixjingga** [cocos2d/cocos2d-x#2269]
@dumganhar 
How To Reproduce:
1. Compile and run TestCpp project and run it in android.
2. Choose the "ClippingNode Test"
3. After the test show, press home button of your android device. This will bring the apps to background.
4. Reopen the apps, and we can see that the rotating image is not showing.

I'm currently still searching where the problem arise. If I find any, I'll post what I find in here. But, hopefully someone who know about ccclippingnode better than me can fix this issue.

Thanks,

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2636
