### ISSUE TITLE
Chipmunk (Javascript binding) - Arbiter.getA() / Arbiter.getB() not supported

### ISSUE THREAD

**Issue by Tokyonono** [cocos2d/cocos2d-x#2298]
Hi,
In the javascript version of Chipmunk (used by Cocos2d-HTML5), the methods to get the bodies of an Arbiter are getA() and getB(), but to make it work on iPhone, we need to use getBodies() instead. It is inconsistent and forces to have different code depending on the platform.
Thanks for the wonderful framework anyways.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2634

**Comment by felipesaruhashi** [comment]
Seems that this issue persist, on version 3.9 still have this problem.
