### ISSUE TITLE
linking in linux only with -lpthread in cocos2dx/Makefile, ubuntu 12.04

### ISSUE THREAD

**Issue by Joilnen** [cocos2d/cocos2d-x#2308]
linking in linux only with -lpthread in cocos2dx/Makefile, ubuntu 12.04

**Comment by azmeuk** [comment]
See #2212 :)

**Comment by godyZ** [comment]
@ Joilnen Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
