### ISSUE TITLE
Why CCTextureCache::addImageAsync does not support pvr? 

### ISSUE THREAD

**Issue by tiantian20007** [cocos2d/cocos2d-x#2320]
There's a sync version of CCTextureCache::addPVRImage, Why CCTextureCache::addImageAsync does not support pvr? Or it's just not implemented yet?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2629
