### ISSUE TITLE
CCLabelTTF displays Different between windows and androids

### ISSUE THREAD

**Issue by vipsbpig** [cocos2d/cocos2d-x#2329]
![android](https://f.cloud.github.com/assets/1953549/354977/b455fd10-a0bd-11e2-9479-32643aaa7957.png)
![windows](https://f.cloud.github.com/assets/1953549/354978/b4584a70-a0bd-11e2-8b83-e1a4baf4f777.jpg)

I am really satisfy in Android displays Text,but in windows is really buggy.
I can't get the some result between two platform.

I use LabelTTF like this Way.In cocos2dx-2.1rc0-2.1.2
//code
   std::string message;
   message="A really loooooooooooooooooooooooooong Content!!!!!!";
   pTextLabel = CCLabelTTF::create(message.c_str(),TEXT_FONT, 23, CCSizeMake( size.width - 80, 0), kCCTextAlignmentLeft, kCCVerticalTextAlignmentCenter);
   pTextLabel->setColor(ccc3(255,255,255));
   pTextLabel->setPosition(ccp(pTextBackground->getContentSize().width/2,pTextBackground->getContentSize().height/2));
   pTextBackground->addChild(pTextLabel);

**Comment by soulin** [comment]
i had the same problem. it can't line feed.
how can i fix it?

**Comment by dumganhar** [comment]
Thank you. Issue http://www.cocos2d-x.org/issues/2041 was created.
