### ISSUE TITLE
CCLabelTTF render failed

### ISSUE THREAD

**Issue by fantasyni** [cocos2d/cocos2d-x#2336]
when i use CCLabelTTF ,it renders not fonts i expect, it renders like this ? what is wrong with it ?  
![image_20130409165551](https://f.cloud.github.com/assets/1411347/355887/582f7832-a0f3-11e2-8bd3-56912e8e878c.png)

**Comment by dumganhar** [comment]
Could you provide more informations about how you use it.

**Comment by fantasyni** [comment]
i use an async i/o library to handle network i/o, so when i do a request, a request callback will be called to deal with data from server, then in this callback function , i create a CCLabelTTF and add it to a layer i already created , but it failed , it shows above ...

**Comment by dumganhar** [comment]
Did you create CCLabelTTF on sub thread?
cocos2d-x is not thread safe, you should make sure that all cocos2d-x apis are invoked at main thread.

**Comment by fantasyni** [comment]
ao, it seems that it is invoked in a sub thread , i will try to fix my app , thx

**Comment by cooolinx** [comment]
I met the same problem, but by a newbie to cocos2d-x & C++ (>_<), is there anyone can tell me how to notify the main thread from a sub thread? Very appreciate.

P.S. I used "dispatch_async(dispatch_get_main_queue(), ...)" in Objective-C & cocos2d-iphone, is there any similar thing in cocos2d-x & C++?
