### ISSUE TITLE
The CCControl "addTargetWithActionForControlEvents()" in the js method without binding

### ISSUE THREAD

**Issue by fym201** [cocos2d/cocos2d-x#2353]
The CCControl "addTargetWithActionForControlEvents()" in the js method without binding。
Please check it, thank you

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2625
