### ISSUE TITLE
Js bingding generator generate code who call autorelease on class which is not a subclass of CCObject

### ISSUE THREAD

**Issue by tiantian20007** [cocos2d/cocos2d-x#2355]
Js auto binding generate Js_MYCLASS_ctor method for my class which is not a subclass of CCObject and call autorelease on it , caused compile error.

**Comment by tiantian20007** [comment]
Newest versions in github.

**Comment by dumganhar** [comment]
We didn't bind CCObject to js.
All native objects generated by js will be an autorelease object since we are using the lifecycle of native to control the lifecycle of js.
So autorelease isn't needed. You should never invoke it in your js logic.
BTW, cocos2d-html5 has no CCObject, we didn't bind it for compatibility of cocos2d-html5.

**Comment by tiantian20007** [comment]
I mean, I ues cxx-generator to generate js binding code for my own c++ class, and the generated code invoke autorelease on non-CCObject class:

``` c++
static JSBool js_stateMachine_Js_SceneManager_ctor(JSContext *cx, uint32_t argc, jsval *vp)
{
    JSObject *obj = JS_THIS_OBJECT(cx, vp);
    SceneManager *nobj = new SceneManager();
    js_proxy_t* p;
    JS_NEW_PROXY(p, nobj, obj);
    nobj->autorelease();
    JS_AddNamedObjectRoot(cx, &p->obj, "SceneManager");
    JS_SET_RVAL(cx, vp, JSVAL_VOID);
    return JS_TRUE;
}
```

These code are auto generated by cxx-generator.
SceneManager is not a subclass of CCObject, so nobj->autorelease() cause compile error.

**Comment by dumganhar** [comment]
You should add a config argument in your `.ini` file.

<pre>
# Determining whether to use script object(js object) to control the lifecycle of native(cpp) object or the other way around. Supported values are 'yes' or 'no'.
script_control_cpp = yes
</pre>

**Comment by dumganhar** [comment]
Please give me the feedback whether it works, thanks.

**Comment by tiantian20007** [comment]
I tried "script_control_cpp = yes", and I understand how it works. However, I want the lifecycle of native to control the lifecycle of js indeed. The case is, some of my c++ class are CCObject subclass, some are not. All code generate for CCObject subclass is fine, but for which are not ,will cause compile error.  
I thought it can be change like this, then all things is fine: (compare to https://github.com/cocos2d/cocos2d-x/issues/2355#issuecomment-16273907)

``` c++
static JSBool js_stateMachine_Js_SceneManager_ctor(JSContext *cx, uint32_t argc, jsval *vp)
{
    JSObject *obj = JS_THIS_OBJECT(cx, vp);
    SceneManager *nobj = new SceneManager();
    js_proxy_t* p;
    JS_NEW_PROXY(p, nobj, obj);
    cocos2d::CCObject *_ccobj = dynamic_cast<cocos2d::CCObject *>(nobj);
    if (_ccobj) {
         _ccobj->autorelease();
    }
    JS_AddNamedObjectRoot(cx, &p->obj, "SceneManager");
    JS_SET_RVAL(cx, vp, JSVAL_VOID);
    return JS_TRUE;
}
```

Just like generated SceneManager_constructor do

``` c++
JSBool js_stateMachine_Js_SceneManager_constructor(JSContext *cx, uint32_t argc, jsval *vp)
{
    if (argc == 0) {
        SceneManager* cobj = new SceneManager();
        cocos2d::CCObject *_ccobj = dynamic_cast<cocos2d::CCObject *>(cobj);
        if (_ccobj) {
            _ccobj->autorelease();
        }
        TypeTest<SceneManager> t;
        js_type_class_t *typeClass;
        uint32_t typeId = t.s_id();
        HASH_FIND_INT(_js_global_type_ht, &typeId, typeClass);
        assert(typeClass);
        JSObject *obj = JS_NewObject(cx, typeClass->jsclass, typeClass->proto, typeClass->parentProto);
        JS_SET_RVAL(cx, vp, OBJECT_TO_JSVAL(obj));
        // link the native object with the javascript object
        js_proxy_t *p;
        JS_NEW_PROXY(p, cobj, obj);
        JS_AddNamedObjectRoot(cx, &p->obj, "SceneManager");
        return JS_TRUE;
    }

    JS_ReportError(cx, "wrong number of arguments: %d, was expecting %d", argc, 0);
    return JS_FALSE;
}
```

**Comment by tiantian20007** [comment]
I think the issue can be change into:
When generate js binding function MyClass_ctor for c++ class: MyClass, need to check whether it is a CCObject's subclass before call autorelease on it.

**Comment by dumganhar** [comment]
> I tried "script_control_cpp = yes", and I understand how it works. However, I want the lifecycle of native to control the lifecycle of js indeed. The case is, some of my c++ class are CCObject subclass, some are not. All code generate for CCObject subclass is fine, but for which are not ,will cause compile error.

Your solution seems great.I will update bindings-generator to support it.
But there is an issue, in this case, we use the lifecycle of native object to control the lifecycle of js object, 
since SceneManager is not a subclass of CCObject, when will it be released? 
Also since js object has been added to `root`, it can't be released too.
That's the problem.

# Maybe the solution could be:

You make another config file only for the object that wasn't inherited from CCObject, and use `script_control_cpp = yes` only for these objects. This issue will be fixed.

**Comment by tiantian20007** [comment]
Inspiring. I'll do it ^^
