### ISSUE TITLE
CCHttpRequest callback selector type

### ISSUE THREAD

**Issue by coolengineer** [cocos2d/cocos2d-x#2365]
In CCHttpRequest member, the selector's type is **SEL_CallFuncND** which means CCNode \* object as the first argument. 

> SEL_CallFuncND     _pSelector;      /// callback function, e.g. MyLayer::onHttpResponse(CCObject *sender, void *data)

And this selector is used at CCHttpClient:: dispatchResponseCallbacks as this way.

> ```
>    if (pTarget && pSelector) 
>    {
>        (pTarget->*pSelector)((CCNode *)this, response);
>    }
> ```

Here, the 'this' is a **CCHttpClient** instance which derived from **CCObject**, but by the type of selector, there exists oddly casting. Why this invalid casting is needed? Is the reason there is no selector type which takes **(CCObject *, void *)** as its parameters? If so, how about adding new type for supporting those cases?

**Comment by dumganhar** [comment]
Yes, i think it's better to add a new type, such as `SEL_HttpResponse`, and its definition maybe `typedef void (CCObject::*SEL_HttpResponse)(CCHttpClient* client, CCHttpResponse* response);`
