### ISSUE TITLE
Singleton refactoring???

### ISSUE THREAD

**Issue by martell** [cocos2d/cocos2d-x#2374]
Hey guys I'm looking for opinions in singleton class creation.

Would there be an advantage in changing to this.
I'm working on a project using a few singletons and was just interested

It looks cleaner but I was wondering if there would be a speed increase as the
code that's generated doesn't have to jump do a block of code after the singleton is already created?

It's going to be a negligible difference but still its interesting. 

CCDirector\* CCDirector::sharedDirector()
  {
    if (s_SharedDirector) return s_SharedDirector; // at the top ??
    s_SharedDirector = new CCDisplayLinkDirector();
    s_SharedDirector->init();
    return s_SharedDirector;
}

vs

CCDirector\* CCDirector::sharedDirector(void)
{
    if (!s_SharedDirector)
    {
        s_SharedDirector = new CCDisplayLinkDirector();
        s_SharedDirector->init();
    }
    return s_SharedDirector;
}

**Comment by gelldur** [comment]
CCDirector\* CCDirector::sharedDirector(void)
{
if (s_SharedDirector == NULL)
{
s_SharedDirector = new CCDisplayLinkDirector();
s_SharedDirector->init();
}
return s_SharedDirector;
}

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2624
