### ISSUE TITLE
CCImage::getDataLen returns number of pixels not data length which is confusing

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-x#2389]
CCImage::getDataLen returns number of pixels not the data length which is confusing. Check http://www.cocos2d-x.org/boards/6/topics/26655

**Comment by godyZ** [comment]
@fins Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated http://www.cocos2d-x.org/issues/2621
