### ISSUE TITLE
Java_org_cocos2dx_lib_Cocos2dxRenderer.cpp have a different method signature with javah

### ISSUE THREAD

**Issue by congling** [cocos2d/cocos2d-x#2393]
most of the method is lack of the first and the second parameter 

such like Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeGetContentText, it should be

JNIEXPORT jstring JNICALL Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeGetContentText
  (JNIEnv *, jclass);

**Comment by dumganhar** [comment]
Hey, please look at https://github.com/cocos2d/cocos2d-x/blob/master/cocos2dx/platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxRenderer.cpp#L39
