### ISSUE TITLE
Control CCBAnimation rate from CCbAnimationManager is not there

### ISSUE THREAD

**Issue by suraj-tmg** [cocos2d/cocos2d-x#2409]
The solution to the issue :

Ability to control the CCBAnimation rate through CCBAnimationManager.
1) Scale the duration in between two successive frames.
2) Scale also total duration of the animation . 

Inside CCAnimationManger class:

class   CCAnimationManger
{
public:
CCAnimationManager()
{
  m_rate =1.0f;
}
void setAnimationRate(float rate)
{
m_rate = rate; 
}
float getAnimationRate()
{
  return m_rate;
}

private:
  m_rate; 

}

CCActionInterval\* CCBAnimationManager::getAction(CCBKeyframe *pKeyframe0, CCBKeyframe *pKeyframe1, const char *pPropName, CCNode *pNode)
{
    float duration = pKeyframe1->getTime() - (pKeyframe0 ? pKeyframe0->getTime() : 0);
    duration = duration \* m_rate; //Multiply with animation rate

}

void CCBAnimationManager::runAnimationsForSequenceIdTweenDuration(int nSeqId, float fTweenDuration)
{
//Multiply the animation rate with total duration

 CCBSequence *seq = getSequence(nSeqId);
    CCAction *completeAction = CCSequence::createWithTwoActions(CCDelayTime::create(seq->getDuration() *m_rate + fTweenDuration),
                                                                CCCallFunc::create(this, callfunc_selector(CCBAnimationManager::sequenceCompleted)));

}

//This will really help in controlling the animation rate from client side .

**Comment by godyZ** [comment]
@1771987 Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2620
