### ISSUE TITLE
Move templates in to separate repositories

### ISSUE THREAD

**Issue by gdagley** [cocos2d/cocos2d-x#2412]
It feels that the [project templates](https://github.com/cocos2d/cocos2d-x/tree/master/template) and the project generators should be pulled in to separate repos and have cocos2d-x as a dependency.  Right now the generators drop the new project right in the middle of the cocos2d-x project and trying to copy the templates assumes some directory structure where the template is nested in the cocos2d-x code.

**Comment by minggo** [comment]
I am not sure if it is a good idea to use a separate repo for project templates. I think project templates is cocos2d-x depended.

**Comment by gdagley** [comment]
Are templates for testing or to be used as same projects for getting started with cocos2d-x? It seems like the templates and generators are good examples of how to structure multiple platform projects, but having them nested in the cocos2d-x project makes them a little more challenging to use to bootstrap an new project.  I agree that they depend on cocos2d-x, but I don't know that they need nested in the project. Each template could have its folder structure such that it makes managing the cocos2d-x dependency easier to manage.

**Comment by gdagley** [comment]
Started an example of what I mean at https://github.com/gdagley/cocos2d-x-multi-platform-js

**Comment by gdagley** [comment]
I am going to close this.  I have decided to make my project a little more specific to what I am looking for.  I will definitely contribute back any useful bits that would help the cocos2d-x project along.  Keep up the great work!
