### ISSUE TITLE
CCDirectorCaller never release from mainloop.

### ISSUE THREAD

**Issue by bugttle** [cocos2d/cocos2d-x#2429]
First, call cocos2d::CCDirector::sharedDirector()->end().

Next, call [CCDirectorCaller destroy] from CCEGLView::end().

But, NEVER call CCDirectorCaller instanced "dealloc" method. Because
"displayLink" added to MainLoop.

**Comment by bugttle** [comment]
I tried to fix 5e21867efd82f2324779624a766fad3f3fb4c4be
Please look at this.

**Comment by godyZ** [comment]
@uqtimes  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2630
