### ISSUE TITLE
LuaJIT bytecode parsing error on Android device

### ISSUE THREAD

**Issue by mustime** [cocos2d/cocos2d-x#2450]
I found there's a parsing error when I was porting a project using LuaJIT bytecode on Android device:  
////////////////////////////////////////////////////////////////////////
D/cocos2d-x debug info: [LUA ERROR](binary): cannot load malformed bytecode
////////////////////////////////////////////////////////////////////////
But the same LuaJIT bytecode work perfectly on iOS.

I turn back to vanilla Lua bytecode after I got this error(Of couse I've changed the default LuaJIT module back to Lua). Still error appear on Android device:
////////////////////////////////////////////////////////////////////////
D/cocos2d-x debug info: [LUA ERROR] binary string: unexpected end in precompiled chunk
////////////////////////////////////////////////////////////////////////

I'm wondering whether it's relevant to the difference between CCLuaEngine::executeString and CCLuaEngine::executeScriptFile(In some case that work, like quick-cocos2d-x).

**Comment by dumganhar** [comment]
I'll check it. Thanks for your feedback.

**Comment by godyZ** [comment]
@mustime  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2632
