### ISSUE TITLE
Loading more than 32 sounds on Galaxy SII GT-I9100 causes crash

### ISSUE THREAD

**Issue by MarkEHenderson** [cocos2d/cocos2d-x#2460]
The openSL implementation used by the I9100 causes an application crash when > 32 sounds are played.  At the very least, the c++ implementation should count the sounds preloaded and stop loading more, rather than crashing the app.

Preferably, the implementation should keep the most recent 32 sounds in memory and clean up older sound effects.

Some background of why this is GT-I9100 specific: http://www.cocos2d-x.org/projects/cocos2d-x/wiki/Use_OpenSL_ES_to_play_effect_on_Android

**Comment by walzer** [comment]
It's a known bug of Samsung i9100 on Android 2.x. If you upgrade the firmware to Android v4.0, this bug will not existed. Also, other android phones has no this limitation.
I don't think we need to handler Samsung's audio driver bug in cocos2d-x.

**Comment by MarkEHenderson** [comment]
On the contrary - anyone using cocos2dx will get customer complaints and possibly lost revenue due to this.  The entire point of using an engine like cocos2dx is to be able to write an app without having to know all the different device compatibilities and bugs. 

Considering that Cocos2dx already has an i9100 specific sound system in it, it makes complete sense to have that programming fully functional and not crashing.

**Comment by walzer** [comment]
Well, you've persuaded me. In next version it will be fixed. 
Bug http://www.cocos2d-x.org/issues/1284 reopen.

**Comment by MarkEHenderson** [comment]
Great, thank you.

**Comment by folecr** [comment]
> it makes complete sense to have that programming fully functional and not crashing.

The code should definitely run without crashing. This is critical.

Should it be fully functional on old, buggy devices? No.

**Comment by rtissera** [comment]
Many i9100 users are "mainstream" users.
They have no idea they can upgrade firmware, or any will to do do.
I agree it should not crash on i9100 / 2.x combo since it still represents a whopping number of sales/downloads.

**Comment by minggo** [comment]
I think #2563 fixed the crash issue.
Could you please have a try.
