### ISSUE TITLE
android debug problem

### ISSUE THREAD

**Issue by jxgzxh111** [cocos2d/cocos2d-x#2464]
Is anyone who knows how to debug android app, with ndk-gdb.sh or other ways on windows platform?  I have used CCLog to print information on eclipse LogCat, but it is not an excellent solution as i think, thank you for all the replies!

**Comment by danielhaaser** [comment]
This isn't the right place for this question.  You should try asking in the [forums](http://www.cocos2d-x.org/projects/cocos2d-x/boards) instead.

I have successfully set up debugging in Eclipse using the ARM DS-5 debugger.  It took a lot of set up and tweaking to get it to work.  Here's a slightly dated tutorial on how to do it.

http://kernel.ozandroid.info/?p=83

**Comment by jxgzxh111** [comment]
OK, I will pay attention to it in the next time, and also thanks for your link!

**Comment by jxgzxh111** [comment]
@danielhaaser  I have set up, and work, but I can not see the variable value in the break point position when debugging, only showing is Disassembly on the right place of Eclipse

**Comment by kaplad** [comment]
There is a nice program https://github.com/cgdb try it out.
