### ISSUE TITLE
Add Jpeg-XR support

### ISSUE THREAD

**Issue by battlebottle** [cocos2d/cocos2d-x#2492]
For those unaware, Jpeg-XR is a image format with a similar feature set to WebP. Like WebP is supports lossless and lossy modes along with transparency. Jpeg-XRs differentiating feature though is native support for a wide variety of colour formats, including formats relevant to games like RGB565. Adding Jpeg-XR support would add support for images with many useful colour formats that are not supported with either Jpeg, PNG or WebP today. This _should_ result in smaller filesizes for textures and I'd imagine faster decoding times due to removing the need for some colour format converting steps.

Jpeg-XR also has superior lossy compression to jpeg, but in my own testing it appears explicitly inferior to WebP and rather close to Jpeg2000 compression quality. In this regard I don't think it should be considered a WebP replacement as WebP performs far better in sheer lossy compression.

Microsoft have a BSD licenced library for Jpeg-XR that could be used for this at: https://jxrlib.codeplex.com/

If no one else is interested I might take a shot at implementing it into cocos2d-x myself. It doesn't look like it would take a huge amount of work.

Before I try that, is there any appetite for this format being supported in cocos2d-x by the dev team? Would it's features be considered useful?

The Wikipedia page has a nice summary of the format: https://en.wikipedia.org/wiki/JPEG_XR

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2627
