### ISSUE TITLE
CCScale9Sprite Scales Badly when Not Centered

### ISSUE THREAD

**Issue by Clarinexus** [cocos2d/cocos2d-x#2497]
When a CCScale9Sprite has its anchor point set to center, everything is fine, but it doesn't scale in the right direction and resets to center if it is loaded with non-centered anchor points.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2619
