### ISSUE TITLE
CCControlButtons Sometimes Don't Activate When Touched

### ISSUE THREAD

**Issue by Clarinexus** [cocos2d/cocos2d-x#2498]
For some reason, short touches on CCControlButtons don't activate the selector, but the zoom-on-touch is registered. Because of this, the user sees the button zooming, but not working, and it looks like a bug. ALL touches, regardless of length (that aren't cancelled) should activate a control button.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2618
