### ISSUE TITLE
CCBReader Memory leak when pushScene

### ISSUE THREAD

**Issue by allen-hsu** [cocos2d/cocos2d-x#2508]
when i have two scene. i use cocosbuild and use CCBReader read ccbi. when i since "A" Scene call pushScene to "B". and i close my Application. i recive memory leak info.
if I popScene to "A". and not have memory leak info.

memory leak info:

Call Stack:
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\gui\cccontrolextension\ccscale9sprite.cpp (291): BladeAndSword_Plus.exe!cocos2d::extension::CCScale9Sprite::updateWithBatchNode + 0xA bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\gui\cccontrolextension\ccscale9sprite.cpp (99): BladeAndSword_Plus.exe!cocos2d::extension::CCScale9Sprite::initWithBatchNode
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\gui\cccontrolextension\ccscale9sprite.cpp (546): BladeAndSword_Plus.exe!cocos2d::extension::CCScale9Sprite::initWithSpriteFrame + 0x69 bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\gui\cccontrolextension\ccscale9sprite.cpp (564): BladeAndSword_Plus.exe!cocos2d::extension::CCScale9Sprite::initWithSpriteFrame + 0x2D bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\gui\cccontrolextension\ccscale9sprite.cpp (571): BladeAndSword_Plus.exe!cocos2d::extension::CCScale9Sprite::createWithSpriteFrame + 0x1C bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\gui\cccontrolextension\cccontrolbutton.cpp (516): BladeAndSword_Plus.exe!cocos2d::extension::CCControlButton::setBackgroundSpriteFrameForState + 0x9 bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\cccontrolbuttonloader.cpp (96): BladeAndSword_Plus.exe!cocos2d::extension::CCControlButtonLoader::onHandlePropTypeSpriteFrame + 0x18 bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\ccnodeloader.cpp (229): BladeAndSword_Plus.exe!cocos2d::extension::CCNodeLoader::parseProperties + 0x31 bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\ccbreader.cpp (623): BladeAndSword_Plus.exe!cocos2d::extension::CCBReader::readNodeGraph + 0x24 bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\ccbreader.cpp (734): BladeAndSword_Plus.exe!cocos2d::extension::CCBReader::readNodeGraph + 0xF bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\ccbreader.cpp (357): BladeAndSword_Plus.exe!cocos2d::extension::CCBReader::readFileWithCleanUp + 0xA bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\ccbreader.cpp (278): BladeAndSword_Plus.exe!cocos2d::extension::CCBReader::readNodeGraphFromData + 0xE bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\ccbreader.cpp (255): BladeAndSword_Plus.exe!cocos2d::extension::CCBReader::readNodeGraphFromFile + 0x17 bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\extensions\ccbreader\ccbreader.cpp (231): BladeAndSword_Plus.exe!cocos2d::extension::CCBReader::readNodeGraphFromFile
    c:\workspace\projectspace\bsp\bsp-client\classes\scene\bstitlescene.cpp (114): BladeAndSword_Plus.exe!BSTitleScene::initLayer + 0x11 bytes
    c:\workspace\projectspace\bsp\bsp-client\classes\scene\bstitlescene.cpp (90): BladeAndSword_Plus.exe!BSTitleScene::init + 0x8 bytes
    c:\workspace\projectspace\bsp\bsp-client\classes\scene\bstitlescene.h (22): BladeAndSword_Plus.exe!BSTitleScene::create + 0xAE bytes
    c:\workspace\projectspace\bsp\bsp-client\classes\bsframework.cpp (91): BladeAndSword_Plus.exe!BSFrameWork::init + 0x5 bytes
    c:\workspace\projectspace\bsp\bsp-client\classes\appdelegate.cpp (74): BladeAndSword_Plus.exe!AppDelegate::applicationDidFinishLaunching + 0x20 bytes
    c:\workspace\projectspace\bsp\bsp-client\lib\cocos2dx\cocos2dx\platform\win32\ccapplication.cpp (47): libcocos2d.dll!cocos2d::CCApplication::run + 0xF bytes
    c:\workspace\projectspace\bsp\bsp-client\proj.win32\main.cpp (24): BladeAndSword_Plus.exe!wWinMain + 0x19 bytes
    f:\dd\vctools\crt_bld\self_x86\crt\src\crtexe.c (528): BladeAndSword_Plus.exe!__tmainCRTStartup + 0x15 bytes
    f:\dd\vctools\crt_bld\self_x86\crt\src\crtexe.c (377): BladeAndSword_Plus.exe!wWinMainCRTStartup

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2610
