### ISSUE TITLE
 CCProgressTimer Tint and Fade no effect

### ISSUE THREAD

**Issue by jaoye617** [cocos2d/cocos2d-x#2512]
Tint and Fade

testCpp code
 CCProgressTo *to = CCProgressTo::create(6, 100);
 CCAction *tint = CCSequence::create(CCTintTo::create(1, 255, 0, 0),
 CCTintTo::create(1, 0, 255, 0),
 CCTintTo::create(1, 0, 0, 255),
 NULL);
 CCAction *fade = CCSequence::create(CCFadeTo::create(1.0f, 0),
 CCFadeTo::create(1.0f, 255),
 NULL);
 CCProgressTimer *left = CCProgressTimer::create(CCSprite::create(s_pPathSister1));
 left->setType(kCCProgressTimerTypeBar);
 // Setup for a bar starting from the bottom since the midpoint is 0 for the y
 left->setMidpoint(ccp(0.5f, 0.5f));
 // Setup for a vertical bar since the bar change rate is 0 for x meaning no horizontal change
 left->setBarChangeRate(ccp(1, 0));
 addChild(left);
 left->setPosition(ccp(100, s.height/2));
 left->runAction(CCRepeatForever::create((CCActionInterval *)to->copy()->autorelease()));
 left->runAction(CCRepeatForever::create((CCActionInterval *)tint->copy()->autorelease()));

Tint and Fade no effect

2.1.1 is ok 
 2.1.2 2.1.3 no effect

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2609
