### ISSUE TITLE
Split keyboard does not work on iPad

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-x#2545]
Below are steps to reproduce the bug:
1. Open TestCpp project in samples
2. Choose the text input test
3. Click the input field, till now, everything is fine
4. Split the keyboard by swiping the keyboard apart with two fingers
5. Now the keyboard hangs and it won't take user interations. If keyboard is still active, repeat step 4, and finally it will hang

Additional links:
http://www.cocos2d-x.org/boards/6/topics/27927
http://www.cocos2d-x.org/boards/6/topics/15809
http://stackoverflow.com/questions/9445505/keyboard-splitting-hangs-in-opengl-app

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2607
