### ISSUE TITLE
HelloLua proj.linux core dump on Ubuntu12.04

### ISSUE THREAD

**Issue by spin6lock** [cocos2d/cocos2d-x#2547]
This is the gdb bt content: https://gist.github.com/spin6lock/5552879

I've run the HelloCpp demo successfully, so I assume that the environment has been setup properly. And I've tried remaking but still got stuck in core dump.

Is it the problem of cocos2d::CCGLProgram::initWithVertexShaderByteArray?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2606
