### ISSUE TITLE
CCEditBox problem of Android

### ISSUE THREAD

**Issue by ucchen** [cocos2d/cocos2d-x#2549]
why not achieve CCEditBoxImplAndroid closeKeyboard() func. In Android Impl use showEditTextDialogJNI  to openKeyboard, however,  have closeEditTextDialogJNI ?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2605
