### ISSUE TITLE
Texture corruption when using texture format sizes other than 4 bytes and small widths.

### ISSUE THREAD

**Issue by silverscania** [cocos2d/cocos2d-x#2550]
Hi there, for my example I have a solid green texture size of 1x16 pixels and a format of RGBA4444.

When using this, the texture is uploaded incorrectly and results in corruption. 
Here you see a quad using this texture repeated in x:
![corrupted](https://f.cloud.github.com/assets/3884307/493058/6b3d7ec8-bb16-11e2-867d-b920f1554f85.jpg)

The fix is just to select the row alignment mode (GL_UNPACK_ALIGNMENT) using a more general case than the one in use now: https://github.com/silverscania/cocos2d-x/commit/e66e7cfcca2676d8e1b3fa44b27e096729c68f5a
This will now correctly upload textures of all formats and sizes.

Now with the fix the quad looks as it should:
![fixed](https://f.cloud.github.com/assets/3884307/493060/f105a15c-bb16-11e2-8b8d-b7fcace83219.jpg)

Pull request here: https://github.com/cocos2d/cocos2d-x/pull/2551

**Comment by minggo** [comment]
The PR is merged.
