### ISSUE TITLE
setAccelerometerEnabled crashs CCLayerColor in Android

### ISSUE THREAD

**Issue by Joilnen** [cocos2d/cocos2d-x#2562]
http://www.cocos2d-x.org/boards/6/topics/27565?r=27577#message-27577

This seems stills happen in last rc candidate.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2604
