### ISSUE TITLE
Broken compilation in Visual Studio 2012

### ISSUE THREAD

**Issue by slobodin** [cocos2d/cocos2d-x#2571]
AssetsManager.cpp/h in libExtensions is the problem.

The errors is like this
`cannot convert parameter 1 from 'int' to 'const ptw32_handle_t &'`

I think it's because `pthread_t` on linux is just integer but on windows it is this structure:
`typedef struct {
    void * p;
    unsigned int x;
} ptw32_handle_t;`

So we can't convert integer to this type. And we can't convert this type to bool.

Error lines are:
AssetsManager constructor (line 81)
line 189 in AssetsManager.cpp: `self->_tid = 0;`
and 
`if (_tid) return;` in `update` function. (line 196)

**Comment by minggo** [comment]
Thank you.
I fixed it in #2574.

**Comment by metalbass** [comment]
I was about to complain about it too, haha!
When is this going to get merged?

**Comment by minggo** [comment]
Can't you resolve it by #2574?
It was brought by the PR to load resources in a new thread.
I am sorry about it.

**Comment by metalbass** [comment]
I've merged that PR into my fork, don't worry, it's all working fine.
I was asking because I want to some PR of my own and my commits include that fix as well.

**Comment by slobodin** [comment]
Will it be merged with master branch?
