### ISSUE TITLE
LL_DELETE2_VS2008 Macro redefinition

### ISSUE THREAD

**Issue by akof1314** [cocos2d/cocos2d-x#2585]
utlist.h  file  line 408 
It should be “#define LL_DELETE2 LL_DELETE2_VS2008”？

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2603
