### ISSUE TITLE
issues android cocos2d-x lock screen

### ISSUE THREAD

**Issue by s20031124** [cocos2d/cocos2d-x#2592]
I have set up a lock screen on my device. If I press the hardware sleep button when my application is opened, then unlock the device from the lock screen, everything in my application goes blank (displays black screen). There is no problem if I disable the lock screen. How can I fix this?

This problem only appears on Android, not on iOS.

**Comment by Tsiannian** [comment]
Maybe you turn on the Developer options>> Don't keep activities. the new cocos2d-x use a method to fixed issue #1758 , you can change it back if you have not much textures to reload.

**Comment by kejunxia** [comment]
+1 Same issue.

Testing device: Galaxy S3

When pressing home button to push the game to background and then coming back has no issue.

But if on/off button is pressed to force locking screen and then unlock the screen, all sprite images went black. SpriteBatchNode is used.

**Comment by billy1380** [comment]
I suspect this is a knock-on from this [http://www.cocos2d-x.org/issues/1613#change-6735]  fix

**Comment by kejunxia** [comment]
I just found this problem after I upgrade my cocos2dx framework to cocos2d-2.1rc0-x-2.1.3. The previous version doesn't have this problem.

**Comment by s20031124** [comment]
so how to fix this problem?

**Comment by s20031124** [comment]
i try to use 320 \* 480 image then solve the android problem

**Comment by kejunxia** [comment]
After blood, sweat and tears I finally found the reason for my case. Hope works for yours too.

Remove the targetSdkVersion in AdnroidManifest.xml. Or change to some others, I haven't tried others but removal worked.

<uses-sdk
        android:minSdkVersion="9"
        android:targetSdkVersion="17" /> //git rid of this guy

**Comment by sosoayaen** [comment]
kejunxia said:
+++++++++++++++++++++++++++++++
Remove the targetSdkVersion in AdnroidManifest.xml. Or change to some others, I haven't tried others but removal worked.

android:minSdkVersion="9"
android:targetSdkVersion="17" /> //git rid of this guy
+++++++++++++++++++++++++++++++

Oh, yes!! This solution is worked well on my SAMSUNG S3. You are amazing!!!

**Comment by victorcfk** [comment]
This worked for me as well. Samsung s3 and Samsung note 1. I added that specific line of android:minSdkVersion="9". I didnt find any targetSdkversion line in my manifest. Many thanks!

**Comment by liu7yong** [comment]
Still have this problem on my Galaxy Nexus (both 4.2 and 4.3), the cocos2d-x I'm using is 2.1.4.

**Comment by minggo** [comment]
I think this issue is the same as #3029.
If so, please close this issue.

Thanks.

**Comment by godyZ** [comment]
@s20031124 Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
