### ISSUE TITLE
Errors when running Build-win32.bat

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#262]
I just downloaded cocos2d-x-cocos2d-0.99.5-x-0.8.2-124 and ran the Build-win32.bat script according to this tutorial 

http://www.cocos2d-x.org/projects/cocos2d-x/wiki/Cocos2d-x_Application_Wizard_for_Visual_Studio_User_Guide

and I received the following errors:

"C:\gameDev\cocos2d-cocos2d-x-9613dce\cocos2d-win32.vc2010.sln" (default target
) (1) ->
"C:\gameDev\cocos2d-cocos2d-x-9613dce\cocos2dx\proj.win32\cocos2d-win32.vcxproj
" (default target) (5) ->
(Link target) ->
  CCDirector.obj : error LNK2019: unresolved external symbol "public: static vo
id __cdecl cocos2d::CCUserDefault::purgeSharedUserDefault(void)" (?purgeSharedU
serDefault@CCUserDefault@cocos2d@@SAXXZ) referenced in function "protected: voi
d __thiscall cocos2d::CCDirector::purgeDirector(void)" (?purgeDirector@CCDirect
or@cocos2d@@IAEXXZ) [C:\gameDev\cocos2d-cocos2d-x-9613dce\cocos2dx\proj.win32\c
ocos2d-win32.vcxproj]
  C:\gameDev\cocos2d-cocos2d-x-9613dce\Release.win32\libcocos2d.dll : fatal err
or LNK1120: 1 unresolved externals [C:\gameDev\cocos2d-cocos2d-x-9613dce\cocos2
dx\proj.win32\cocos2d-win32.vcxproj]

**Comment by ghost** [comment]
0.99.5-x-0.8.0-0 is the latest version that builds with no errors.

**Comment by walzer** [comment]
sorry, I think it's our mistake. add CC_DLL into the declaration of class CCUserDefault will fix this build error.

**Comment by walzer** [comment]
The bug is fixed in 0.8.3. Thanks for your bug report :)
