### ISSUE TITLE
The textField_ should not be added right after a CCEditBox is created

### ISSUE THREAD

**Issue by sunxiaoyu** [cocos2d/cocos2d-x#2638]
The textField_ in CCEditBoxImplIOS should not be added right after a CCEditBox is created,just move it into the openKeyboard,otherwise after the parent layer is reEntered,the CCEditBox dosen't work any more!In my experience,it is safe for a UIView to be added to another UIView for times!
-(void) openKeyboard
{
    [[EAGLView sharedEGLView] addSubview:textField_];
    [textField_ becomeFirstResponder];
}

-(void) closeKeyboard
{
    [textField_ resignFirstResponder];
    [textField_ removeFromSuperview];
}

**Comment by dumganhar** [comment]
Make sense, so could you send a PR to `develop` branch?

**Comment by godyZ** [comment]
@sunxiaoyu  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2601
