### ISSUE TITLE
CCTouchDispatcher touch handlers ordering issue

### ISSUE THREAD

**Issue by gfzabarino** [cocos2d/cocos2d-x#2668]
More than an issue, is the way it works I don't feel comfortable with. Either targeted or standard, I think the correct way to process touch handlers is in the order they were registered. A targeted touch handler can swallow the touch if it wants to, and stop the touch processing (at least for that particular touch). But if for example (and this is my actual problem) we have a top/last added CCEditBox and a previous added background targeted touch handler layer which swallow touches, I really think the touch should be sent to the CCEditBox first, and then continue with the rest of touch handlers. Right now my targeted touch handler layer is swallowing the touch and it doesn't get to the CCEditBox ccTouchesBegan method.
If you're interested, I'm implementing a modal dialog.

Let me know what you think.

Thanks for this awesome cross platform framework!

Best,
Gian Franco Zabarino

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2600
