### ISSUE TITLE
CCRepeat sometime cannot execute the give times

### ISSUE THREAD

**Issue by leopay** [cocos2d/cocos2d-x#2674]
in https://github.com/cocos2d/cocos2d-x/blob/develop/cocos2dx/actions/CCActionInterval.cpp#L495

```
void CCRepeat::update(float dt)
{
    //if add a log here, will print Infinite when times = 20
    if (dt >= m_fNextDt)
    {
        while (dt > m_fNextDt && m_uTotal < m_uTimes)
        {

            m_pInnerAction->update(1.0f);
            m_uTotal++;

            m_pInnerAction->stop();
            m_pInnerAction->startWithTarget(m_pTarget);
            m_fNextDt += m_pInnerAction->getDuration()/m_fDuration;
        }
```

as m_fNextDt is float, in last loop  m_fNextDt may more than dt
e.g. 

if m_uTimes =18
in the finally exection,dt is 1.0000000000 but m_fNextDt is 1.0000002384
dt cannot more than m_fNextDt any more, m_uTimes is 18 but m_uTotal is 17

if m_uTimes = 17
any thing is going as   expectation
dt is 1.0000000000 and m_fNextDt is 1.000000000

**Comment by leopay** [comment]
after update to latest version ,still have the problem.

**Comment by leopay** [comment]
maybe another guys have the same problem http://cocos2d-x.org/boards/6/topics/27075

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2599
