### ISSUE TITLE
jsbinding of plugin-x  for android  compile erro

### ISSUE THREAD

**Issue by zj831007** [cocos2d/cocos2d-x#2677]
I create a project as the sample of HelloAnalytics-JS, but there have man erro when built it, such as: jni/../../../../plugin/jsbindings/auto/jsb_pluginx_umeng_auto.cpp:571:74: error: 'CCLOGINFO' was not declared in this scope  and so on, It is same as there are man .h file  that not in the namespace of plugin can not find,  how to setting the plugin project?
My Android.mk file is like this:
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := cocos2djs_shared

LOCAL_MODULE_FILENAME := libcocos2djs

LOCAL_SRC_FILES := wuxia/main.cpp \
                   ../../Classes/AppDelegate.cpp \
                   ../../../../plugin/jsbindings/manual/jsb_pluginx_spidermonkey_specifics.cpp  \
                   ../../../../plugin/jsbindings/manual/pluginxUTF8.cpp \
                   ../../../../plugin/jsbindings/manual/jsb_pluginx_basic_conversions.cpp \
                   ../../../../plugin/jsbindings/manual/jsb_pluginx_manual_iap.cpp \
                   ../../../../plugin/jsbindings/manual/jsb_pluginx_extension_registration.cpp \
                   ../../../../plugin/jsbindings/auto/jsb_pluginx_umeng_auto.cpp \
                   ../../../../plugin/jsbindings/auto/jsb_pluginx_protocols_auto.cpp 

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes \
                    $(LOCAL_PATH)/../../../../plugin/jsbindings \
                    $(LOCAL_PATH)/../../../../plugin/jsbindings/auto \
                    $(LOCAL_PATH)/../../../../plugin/jsbindings/manual 

LOCAL_WHOLE_STATIC_LIBRARIES := cocos2dx_static 
LOCAL_WHOLE_STATIC_LIBRARIES += cocosdenshion_static
LOCAL_WHOLE_STATIC_LIBRARIES += chipmunk_static
LOCAL_WHOLE_STATIC_LIBRARIES += spidermonkey_static
LOCAL_WHOLE_STATIC_LIBRARIES += scriptingcore-spidermonkey
LOCAL_WHOLE_STATIC_LIBRARIES += PluginProtocolStatic
LOCAL_WHOLE_STATIC_LIBRARIES += PluginUmengStatic

LOCAL_EXPORT_CFLAGS := -DCOCOS2D_DEBUG=2 -DCOCOS2D_JAVASCRIPT

include $(BUILD_SHARED_LIBRARY)

$(call import-module,cocos2dx)
$(call import-module,CocosDenshion/android)
$(call import-module,external/chipmunk)
$(call import-module,scripting/javascript/spidermonkey-android)
$(call import-module,scripting/javascript/bindings)
$(call import-module,plugins/umeng/android)
$(call import-module,protocols/android)

**Comment by natural-law** [comment]
Hi, can you tell me which version of plugin-x code you're using? I just tried the code on develop branch, the compiling is also failed.
The code of plugin-x in the stable version must can be compiled success.
But if you're trying the newest code. Please waiting for a few days. Because I'm refactoring the framework of plugin-x. The work will be done in a few days.
Thanks for your attention.

**Comment by zj831007** [comment]
Thanks for reply so quickly, I am use the version of develop branch,  I switch the stable version and try again. Thank you!

**Comment by zj831007** [comment]
Hello, Natural-law,  I add PluginUmeng and PluginProtocol to my game object, and config the settings as the demo project, but it always compile with error, can you help me to find what am wrong, thanks very much,it is confused me a whole day!!

Undefined symbols for architecture i386:
  "cocos2d::plugin::ProtocolSocial::onShareResult(cocos2d::plugin::ShareResultCode, char const_)", referenced from:
      js_pluginx_protocols_ProtocolSocial_onShareResult(JSContext_, unsigned int, JS::Value_) in jsb_pluginx_protocols_auto.o
  "cocos2d::plugin::ProtocolSocial::setResultListener(cocos2d::plugin::ShareResultListener_)", referenced from:
      js_pluginx_protocols_ProtocolSocial_setResultListener(JSContext_, unsigned int, JS::Value_) in jsb_pluginx_protocols_auto.o
      js_pluginx_ProtocolSocial_setResultListener(JSContext_, unsigned int, JS::Value_) in jsb_pluginx_manual_iap.o
  "typeinfo for cocos2d::plugin::ProtocolSocial", referenced from:
      pluginx::TypeTestcocos2d::plugin::ProtocolSocial::s_id() in jsb_pluginx_protocols_auto.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by godyZ** [comment]
this issue is migrated to http://www.cocos2d-x.org/issues/2710.
