### ISSUE TITLE
js binding missed CCRemoveSelf

### ISSUE THREAD

**Issue by lava-hammer** [cocos2d/cocos2d-x#2691]
we have CCRemoveSelf in c++ but not bind to js.

**Comment by minggo** [comment]
CCRemoveSelf is cocos2d-x specific. cocos2d-iphone and cocos2d-html5 don't have it.
And we should keep jsb interfaces the same as cocos2d-iphone jsb and cocos2d-html5.

**Comment by lava-hammer** [comment]
Well, that is not a big problem. I can still implement it by using a func call action.
BTW, CCRemoveSelf is really a good component.
