### ISSUE TITLE
[Android]Doing so may leave the black screen when you return the app.

### ISSUE THREAD

**Issue by novaoki** [cocos2d/cocos2d-x#2692]
Hi.
I will start the app.
I will return to the home screen.
It remains black screen very rarely when you return the app.
Is it possible to solve do not you?

cocos2d-x v2.1.3
Android 2.3.3
LG Optimus LTE(L-01D)

**Comment by minggo** [comment]
cocos2d-x doesn't reload resources any more. It will save time and memory usage. Fishing Joy, which has 0.2 billion users also use this method, and don't receive error feedback about this modification.

The modification is [here](http://www.cocos2d-x.org/projects/native/repository/revisions/b26d64715f818c036df2f4cb5dcdf7cd0b320a20/diff). You can revert this modification and have a try.

**Comment by novaoki** [comment]
Thank you for answer.
If you change the setting back there, the longer it takes really to return from the background.

**Comment by minggo** [comment]
I think this issue is the same as #3029.
If so, please close this issue.

Thanks.
