### ISSUE TITLE
the missing extension ios project is still not added now

### ISSUE THREAD

**Issue by davidxifeng** [cocos2d/cocos2d-x#2695]
https://github.com/cocos2d/cocos2d-x/pull/2123
this pull request has been closed but the ios project is not merged to master.

**Comment by davidxifeng** [comment]
and current master sample hellolua couldn't compile and link in ios project for the luaapi use extensions.

**Comment by dumganhar** [comment]
I closed that PR since the author didn't answer my question and there are something need to be modified.

**Comment by davidxifeng** [comment]
或者,我建议把lua脚本绑定中api拆分成两部分,一个cocos2dx一个extension.
不要把所有的都放到这里.
LuaCocos2d.cpp
