### ISSUE TITLE
ScriptingCore: jsval_to_long_long and long_long_to_jsval don't match

### ISSUE THREAD

**Issue by nicolasgramlich** [cocos2d/cocos2d-x#2698]
When converting a long long from native to JS and back, the uint32_t portions are flipped: https://github.com/cocos2d/cocos2d-x/blob/master/scripting/javascript/bindings/ScriptingCore.cpp#L1047

I.e.: the long long `1`(Hex: `0x1`) get's _roundtrip-converted_ to `4294967296` (Hex:`0x100000000`).

This might or might not be limited to Android (Little Endian, ARM).

Quick fix that is working for me is to flip the array indices in https://github.com/cocos2d/cocos2d-x/blob/master/scripting/javascript/bindings/ScriptingCore.cpp#L1055 and https://github.com/cocos2d/cocos2d-x/blob/master/scripting/javascript/bindings/ScriptingCore.cpp#L1057 of which I'm unsure of if it is the proper solution.

**Comment by dumganhar** [comment]
Thanks. I'll check that.

**Comment by dumganhar** [comment]
Hi @nicolasgramlich 
I noticed that in cocos2d-x, we just define these functions, however, we don't use it.
Could you tell me how to test it ?
The implementation of `jsval_to_long_long` is just copied from cocos2d-iphone.

**Comment by nicolasgramlich** [comment]
- @ricardoquesada

I will talk to riq today.

**Comment by ricardoquesada** [comment]
Hi, apparently cocos2d-x is using an outdated version of `JSB_jsval_to_longlong`.
In cocos2d-iphone I am using strings to represent long longs:
https://github.com/zynga/jsbindings/blob/master/src/manual/jsb_basic_conversions.mm#L572

@dumganhar Could you update the cocos2d-x bindings ? Thanks.

**Comment by dumganhar** [comment]
@ricardoquesada 
OK, i'll check that.
