### ISSUE TITLE
CCLabelTTF setString() on android causes crash [overstep the boundary]

### ISSUE THREAD

**Issue by jxgzxh111** [cocos2d/cocos2d-x#2700]
![image](https://f.cloud.github.com/assets/4264734/594721/b792f2a4-caab-11e2-9d54-d174b36af083.png)
Hi,This place should be put a jugdement, on line 298 of the function divideStringWithMaxWidth(final String pString, final int pMaxWidth, final Paint pPaint),in Cocos2dxBitmap.java file, please check it!

**Comment by zcgit** [comment]
yes,it's a bug!

**Comment by minggo** [comment]
@jxgzxh111 
Could you send a pull request for it?

**Comment by jxgzxh111** [comment]
@minggo 
Sorry, I am a beginner for github, how to send a pull request, any tutorial for me?Thanks

**Comment by jxgzxh111** [comment]
@minggo 
I have done it!

**Comment by jxgzxh111** [comment]
https://github.com/cocos2d/cocos2d-x/pull/3043
