### ISSUE TITLE
constant variables of jsbinding  missing

### ISSUE THREAD

**Issue by zj831007** [cocos2d/cocos2d-x#2721]
The follow variabile should be add to jsb_cocos2d_constants.js

cc.kTargetWindows = 0;
cc.kTargetLinux = 1;
cc.kTargetMacOS = 2;
cc.kTargetAndroid = 3;
cc.kTargetIphone = 4;
cc.kTargetIpad = 5;
cc.kTargetBlackBerry = 6;
cc.kTargetNaCl = 7;
cc.kTargetEmscripten = 8;
cc.kTargetTizen = 9;

**Comment by dumganhar** [comment]
Yes, you are right.
cc.TARGET_WINDOWS = 0;
cc.TARGET_LINUX = 1;
xxx
will be better.
