### ISSUE TITLE
The std::sort function in CCTouchDispatcher::rearrangeHandlers may lead to unstable sort result when there exist servral handlers with same priority in the array. How about changing the std::sort to std::stable_sort?

### ISSUE THREAD

**Issue by singingcoder** [cocos2d/cocos2d-x#2730]

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2598
