### ISSUE TITLE
a bug in CCEditBox initWithSizeAndBackgroundSprite method

### ISSUE THREAD

**Issue by zcgit** [cocos2d/cocos2d-x#2734]
if you create a CCEditBox , for example , CCEditBox\* pCCEditBox = CCEditBox::create(CCSize(100, 50) , pCCScale9Sprite);
then call initWithSizeAndBackgroundSprite method again,it will excute 
CCControlButton::initWithLabelAndBackgroundSprite --> CCControl::init()  --> CCLayer::init(),
in CCLayer::init() we just set m_bTouchEnabled = false; exactly we should excute CCLayer::setTouchEnabled(false).

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2596
