### ISSUE TITLE
CCScrollView crash when extends from jsbinding

### ISSUE THREAD

**Issue by zj831007** [cocos2d/cocos2d-x#2774]
When extends cc.ScrollView from jsbinding,for example:cc.ScrollView.extend({...}), and the game is crash when lanuch,  and the problem is like  m_pTouches is NULL in the code:
CCScrollView::~CCScrollView(){
    m_pTouches->release();
}
 If it should be use CC_SAFE_DELETE(m_pTouches)?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2595
