### ISSUE TITLE
CCBAniamtion Bug

### ISSUE THREAD

**Issue by allen-hsu** [cocos2d/cocos2d-x#2806]
CCBReader CCBAnimation CCAction Bug

while i use CCBAnimation 
and i use rootnode or use CCBAnimation CCNode when call runAction function

runAction function not work because

CCBAnimation void runAnimationsForSequenceIdTweenDuration

this function to stop all action

and i hope CCBAnimation public function can change to virtual function

and i can Inherit it

thank you

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2593
