### ISSUE TITLE
[Android]cocos2d-x 2.1.3 CCUserDefault lost

### ISSUE THREAD

**Issue by novaoki** [cocos2d/cocos2d-x#2830]
I use CCUserDefault to save data.
There are reports save data to lost often from user.
I was using the cocos2d-x v2.0.4 previously.
I upgraded because I saw the information that you are using SharedPreference in CCUserDefault in v2.1.3.
However phenomenon has been improved a little, but it does not seem to have been fixed completely.
There anything I can do is there any way?

cocos2d-x v2.1.3
Android 4.1.1
Galaxy Note2

**Comment by minggo** [comment]
Did you invoke flush() after saving?

**Comment by novaoki** [comment]
Thank you  minggo.
Yes. I am calling the flush().
This phenomenon seems to occur rarely.

**Comment by novaoki** [comment]
Hi  minggo.
Another questions.
Do I need to call the flush() Among AppDelegate::applicationDidEnterBackground()?

**Comment by godyZ** [comment]
@NovAoki Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2592
