### ISSUE TITLE
Build error: extension.cpp:63:31: error: ignoring return value

### ISSUE THREAD

**Issue by bakwc** [cocos2d/cocos2d-x#2831]
../spine/extension.cpp: In function «char\* cocos2d::extension::_readFile(const char_, int_)»:
../spine/extension.cpp:63:31: error: ignoring return value of «size_t fread(void_, size_t, size_t, FILE_)», declared with attribute warn_unused_result [-Werror=unused-result]
cc1plus: all warnings being treated as errors

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2591
