### ISSUE TITLE
Windows 7 , visual studio 2010 express errors when loading projects

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#2857]
when loading cocos2d-win32.vc2010.sln 
im getting the errors that :
project - common
project - cpp 
project - js
project -lua 
Solution folders not supported in this version of application . 

and then they are grayout in the Visual studio IDE

**Comment by godyZ** [comment]
The issue is migrated to http://www.cocos2d-x.org/issues/2707
