### ISSUE TITLE
window 7 . visual studio 2012 express template exist  but doesn't start new project

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#2860]
I able to load all the cocos2dx projects into visual studio express 2012
all the samples working great , when i try to start new project and using the installed 
Cocos2d-win32 application project , i see the icon and the template entry in the 
Add new project window , but when trying to press Ok ( to create the project ) 
nothing happening .

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2589
