### ISSUE TITLE
Consider performing JSB garbage collection on application memory warning

### ISSUE THREAD

**Issue by jdmunro** [cocos2d/cocos2d-x#2882]
I'm not sure if there is a similar hook in Android, but in iOS there is an application memory warning that enables the app to free up some of its resources. I checked and currently cocos2dx does not force JSB garbage collection at this point, although the texture cache and file utils cached data are purged.

It could help to free up more resources. Can anyone think of a reason why we shouldn't do this? I could prepare a patch.

One downside is that it may cause a more noticeable stutter if the app is running at the time.

**Comment by dumganhar** [comment]
Hi jdmunro ,
So ,do you mean that we should force garbage collection when purge `CCTextureCache`.
IMO, we don't need to force GC in engine. It's developer's responsibility to do that.
For instance , when a scene is exiting, or a new scene is entering, it's a good time to do a `force GC` in game's source code.
Do you agree?

**Comment by jdmunro** [comment]
Hi,

I don't mean coupling the JSB to CCTextureCache in any way. However, when the application receives a memory warning (`applicationDidReceiveMemoryWarning` in iOS) we're already freeing up some resources, such as in the texture cache.

Since the application has a responsibility to free up resources at this point, one thing that could potentially be cleared up is the garbage objects from JSB. I know that GC happens on-demand handled by the runtime itself, and also that the developer can perform this themselves as you mentioned. However right now there is no way to handle the application memory warning event in the JS runtime, and it seems to me that it could be the engine's responsibility to ensure that enough resources are freed so that the application is less likely to get purged by the OS when memory is low.

Furthermore, I believe that the JSB exists in cocos2dx to make it easier/more convenient for developers to create games. JavaScript itself lets you not worry about memory management (well, kind of..!) so perhaps we should not rely on developers to consider performing GC themselves when the application already knows that their is a low memory warning.

**Comment by jdmunro** [comment]
Something like this:

```
- (void)applicationDidReceiveMemoryWarning:(UIApplication *)application {
    /*
     Free up as much memory as possible by purging cached data objects that can be recreated (or reloaded from disk) later.
     */
    cocos2d::CCDirector::sharedDirector()->purgeCachedData();

    cocos2d::ScriptingCore::getInstance()->performGarbageCollection();
}
```

**Comment by godyZ** [comment]
@ jdmunro Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2706
