### ISSUE TITLE
Undeclared problem about ''jsb_get_js_proxy'

### ISSUE THREAD

**Issue by Huwell** [cocos2d/cocos2d-x#2890]
I want to study cocos2d-js from 'How to bind C++ to Javascript' on Cocos2d-x Wiki, but I met these error when I finished the instruments of the article.

/Users/Eric/Documents/Development/bindings-generator/test/simple_test_bindings/autogentestbindings.cpp:120:22: Use of undeclared identifier 'jsb_get_js_proxy'

/Users/Eric/Documents/Development/bindings-generator/test/simple_test_bindings/autogentestbindings.cpp:322:24: Use of undeclared identifier 'jsb_new_proxy'

How to fix them? I cannot found the implements of jsb_get_js_proxy and jsb_new_proxy

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2584
