### ISSUE TITLE
How can I create a callbacks of timeline in cocosbuilder

### ISSUE THREAD

**Issue by happy253650035** [cocos2d/cocos2d-x#2891]
![2013-06-14 4 26 25](https://f.cloud.github.com/assets/2668153/653074/cf4500c4-d4cc-11e2-95e6-5221e7a05757.png)
I want to create a callbacks in timeline like this, but I don't know how can I create it, have anyone help me?

**Comment by gelldur** [comment]
use CCCallFunction ? http://www.cocos2d-x.org/reference/native-cpp/dd/d6e/classcocos2d_1_1_c_c_call_func.html#a295f0933a3ab207e3ea24eedc5acdf82

**Comment by d5j6** [comment]
option+click
