### ISSUE TITLE
Nfc app black screen

### ISSUE THREAD

**Issue by alenl2** [cocos2d/cocos2d-x#2893]
When i NFC beem my cocos2d-x with js bindings to another device that has the app already runing in the background the app on receiving device will be black appart from everything you reload manually. It happens in the same way as https://github.com/cocos2d/cocos2d-x/issues/2592

**Comment by godyZ** [comment]
@alenl2 Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
