### ISSUE TITLE
CCMenuItemImage does not render in portrait mode

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#2894]
Hi 
I build an App with with Cocosbuilder. the main screen contains a CCLayer which contains one CCMenu and a CCMenuItemImage. If I run the app in Landscape the whole screen renders correct. 
When I run the app in Portrait the CCMenuItemImage does not render. It seems to be loading correct and bind the Selector just like it did in Landscape but the control does not render on the screen.

I am using cocos2dx on the client. find the ccb file at: 
http://www.cocos2d-x.org/attachments/2097/HomeScene.ccb

Hulluperuna

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2583
