### ISSUE TITLE
calling static method crashes 2.1.3 cocos2dx framwork

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#2905]
Hi

I just tried to switch from 2.1.2 code line to the 2.1.3 codeline and found the following issue. Calling a static method from a static method causes a "exc_bad_instruction" in xcode

if you add the folloing test class below to any project and call the static method runall from the appdelegate it will crash!
Header:

```
class Test
{
public:
    Test();
    static bool runAllTests();
    static int test1();
};
```

C++:

```
Test::runAllTests(){
    int testErrorCount = 0;
    testErrorCount = Test::test1();
    Test *tLE = new Test();
    //    tLE->mLayer = layer;
    return true;
}
Test::Test(){

}

int Test::test1(){
    CCFileUtils* fileUtil;
    string filename = fileUtil->getWritablePath();
    filename.append("test.txt");
    int error = remove((char*)filename.c_str());
    return error;
}
```

**Comment by waiter** [comment]
int Test::test1(){
    string filename = CCFileUtils::sharedFileUtils()->getWritablePath();
    filename.append("test.txt");
    int error = remove((char*)filename.c_str());
    return error;
}

what about this. 
@hulluperuna

**Comment by ghost** [comment]
OK This solves the issue! 

Thanks waiter
