### ISSUE TITLE
Error parsing the nested project section in solution file

### ISSUE THREAD

**Issue by walnutfalls** [cocos2d/cocos2d-x#2906]
This happens on this latest commit, but not the distribution at http://www.cocos2d-x.org/projects/cocos2d-x/wiki/Download

When running build-win32.bat, Build fails right away with the error 

"Error parsing the nested project section in solution file"

Fixed: Just open solution in visual studio, create empty text file, delete it, clean solution, save, close.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2582
