### ISSUE TITLE
CCPoolManager push()/pop() not balanced in CCDirector

### ISSUE THREAD

**Issue by melode11** [cocos2d/cocos2d-x#2910]
hi:
The push()/pop() call seems not balanced in CCDirector. I understand that the CCPoolManager still works because it will keep at least one pool in the stack, but its impossible for me to balance my own call to push()/pop() elsewhere outside the CCDirector.
If that is because the performance reason for not balancing the push()/pop(), I suggest that we'd better not warp our API to gain performance.
Thanks.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2581
