### ISSUE TITLE
windows 7 , visual studio 2010 express dosn't compile is it supported ?

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#2912]
Hey 
the bug in visual studio 2012 express is fixed , but when loading cocos2d-win32.vc2010.sln
to visual studio 2010 express it doesn't build the projects , and there are massages about projects not supported .

1>------ Build started: Project: libcocos2d, Configuration: Debug Win32 ------
1>Error: Object reference not set to an instance of an object.
2>------ Build started: Project: libchipmunk, Configuration: Debug Win32 ------
2>Error: Object reference not set to an instance of an object.
3>------ Build started: Project: libBox2D, Configuration: Debug Win32 ------
3>Error: Object reference not set to an instance of an object.
4>------ Build started: Project: libCocosDenshion, Configuration: Debug Win32 ------
4>Error: Object reference not set to an instance of an object.
5>------ Build started: Project: libExtensions, Configuration: Debug Win32 ------
5>Error: Object reference not set to an instance of an object.
6>------ Build started: Project: HelloCpp, Configuration: Debug Win32 ------
6>Error: Object reference not set to an instance of an object.
7>------ Build started: Project: liblua, Configuration: Debug Win32 ------
7>Error: Object reference not set to an instance of an object.
8>------ Build started: Project: libJSBinding, Configuration: Debug Win32 ------
8>Error: Object reference not set to an instance of an object.
9>------ Build started: Project: TestCpp, Configuration: Debug Win32 ------
9>Error: Object reference not set to an instance of an object.
10>------ Build started: Project: WatermelonWithMe, Configuration: Debug Win32 ------
10>Error: Object reference not set to an instance of an object.
11>------ Build started: Project: TestJavascript, Configuration: Debug Win32 ------
11>Error: Object reference not set to an instance of an object.
12>------ Build started: Project: MoonWarriors, Configuration: Debug Win32 ------
12>Error: Object reference not set to an instance of an object.
13>------ Build started: Project: TestLua, Configuration: Debug Win32 ------
13>Error: Object reference not set to an instance of an object.
14>------ Build started: Project: HelloLua, Configuration: Debug Win32 ------
14>Error: Object reference not set to an instance of an object.
15>------ Build started: Project: CrystalCraze, Configuration: Debug Win32 ------
15>Error: Object reference not set to an instance of an object.
16>------ Build started: Project: CocosDragonJS, Configuration: Debug Win32 ------
16>Error: Object reference not set to an instance of an object.
17>------ Build started: Project: AssetsManagerTest, Configuration: Debug Win32 ------
17>Error: Object reference not set to an instance of an object.
========== Build: 0 succeeded, 17 failed, 0 up-to-date, 0 skipped ==========

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2580
