### ISSUE TITLE
Keypad menu event not pass to javascript logic code

### ISSUE THREAD

**Issue by greathqy** [cocos2d/cocos2d-x#2914]
void CCLayer::keyBackClicked(void)
{
    if (m_pScriptKeypadHandlerEntry || m_eScriptType == kScriptTypeJavascript)
    {
        CCScriptEngineManager::sharedManager()->getScriptEngine()->executeLayerKeypadEvent(this, kTypeBackClicked);
    }
}

void CCLayer::keyMenuClicked(void)
{
    if (m_pScriptKeypadHandlerEntry)
    {
        CCScriptEngineManager::sharedManager()->getScriptEngine()->executeLayerKeypadEvent(this, kTypeMenuClicked);
    }
}

menu event can't pass to js code

**Comment by dumganhar** [comment]
Could you provide more informations about how you used it in js?

**Comment by godyZ** [comment]
@greathqy Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2579
