### ISSUE TITLE
visual studio 2010 express , when starting new project via template can't compile

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#2915]
Hey 
after compiling the cocos2d-x 2 latest source code from this git , via build-win32.bat
making sure it compiled with vs 2010 express and compilation done with success .
then i installing the templates using install-templates-msvc.bat.
when i start fresh new project using the cocos2d-x -templatand try to compile it 
im getting this error:

1>------ Build started: Project: Test1.win32, Configuration: Debug Win32 ------
1>  main.cpp
1>d:\dev\cpp\cocos2d-x\tutorials\vs2010\test1\test1\proj.win32\main.h(11): fatal error C1083: Cannot open include file: 'CCStdC.h': No such file or directory
1>  HelloWorldScene.cpp
1>d:\dev\cpp\cocos2d-x\tutorials\vs2010\test1\test1\classes\helloworldscene.h(4): fatal error C1083: Cannot open include file: 'cocos2d.h': No such file or directory
1>  AppDelegate.cpp
1>d:\dev\cpp\cocos2d-x\tutorials\vs2010\test1\test1\classes\appdelegate.cpp(1): fatal error C1083: Cannot open include file: 'cocos2d.h': No such file or directory
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by dumganhar** [comment]
Hello, we have removed vs template. Please use tools/project-creator to create multi-platform project. Thanks.
I forgot to delete install-templates-msvs.bat. :(

**Comment by meiry** [comment]
Hey thanks for the fast replay , 
i run this script like this :
D:\dev\cpp\cocos2d-x\cocos2d-x_git\tools\project-creator>create_project.py -project Test2 -package com.test2.meiry -language cpp
proj.ios                : Done!
proj.android            : Done!
proj.win32              : Done!
proj.mac                : Done!
proj.blackberry         : Done!
proj.linux              : Done!
proj.marmalade          : Done!
New project has been created in this path: D:\dev\cpp\cocos2d-x\cocos2d-x_git\tools\project-creator/../../projects/Test2
Have Fun!

now i loaded the Test2.sln to fresh VS 2010 express try to build it , and im getting this :
1>------ Build started: Project: libcocos2d, Configuration: Debug Win32 ------
1>Error: Object reference not set to an instance of an object.
2>------ Build started: Project: libBox2D, Configuration: Debug Win32 ------
2>Error: Object reference not set to an instance of an object.
3>------ Build started: Project: libchipmunk, Configuration: Debug Win32 ------
3>Error: Object reference not set to an instance of an object.
4>------ Build started: Project: libCocosDenshion, Configuration: Debug Win32 ------
4>Error: Object reference not set to an instance of an object.
5>------ Build started: Project: libExtensions, Configuration: Debug Win32 ------
5>Error: Object reference not set to an instance of an object.
6>------ Build started: Project: Test2, Configuration: Debug Win32 ------
6>Error: Object reference not set to an instance of an object.
========== Build: 0 succeeded, 6 failed, 0 up-to-date, 0 skipped ==========

The only way i could create new project in VS 2010 express is to use the template that created 
and create new project ONLY  in the same solution as the Cocose2d-x project. only inside it .

**Comment by meiry** [comment]
also tried to use the new create project script in VS 2012 script again gives errors:

1>------ Build started: Project: metroid-runner, Configuration: Debug Win32 ------
1>  main.cpp
1>  HelloWorldScene.cpp
1>d:\dev\cpp\cocos2d-x\cocos2d-x-develop_2012\cocos2d-x-develop\projects\metroid-runner\classes\helloworldscene.cpp(42): warning C4996: 'cocos2d::CCMenuItemImage::create': was declared deprecated
1>          d:\dev\cpp\cocos2d-x\cocos2d-x-develop_2012\cocos2d-x-develop\cocos2dx\menu_nodes\ccmenuitem.h(327) : see declaration of 'cocos2d::CCMenuItemImage::create'
1>  AppDelegate.cpp
1>  Generating Code...
1>  2 File(s) copied
1>AppDelegate.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification
1>HelloWorldScene.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall cocos2d::CCObject::acceptVisitor(class cocos2d::CCDataVisitor &)" (?acceptVisitor@CCObject@cocos2d@@UAEXAAVCCDataVisitor@2@@Z)
1>HelloWorldScene.obj : error LNK2001: unresolved external symbol "public: virtual class cocos2d::CCSize const & __thiscall cocos2d::CCNode::getContentSize(void)const " (?getContentSize@CCNode@cocos2d@@UBEABVCCSize@2@XZ)
1>HelloWorldScene.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall cocos2d::CCNode::getTag(void)const " (?getTag@CCNode@cocos2d@@UBEHXZ)
1>D:\dev\cpp\cocos2d-x\cocos2d-2.1rc0-x-2.1.3\cocos2d-2.1rc0-x-2.1.3\Debug.win32\metroid-runner.exe : fatal error LNK1120: 3 unresolved externals
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========

**Comment by toughrogrammer** [comment]
Hello, I didn't know this tool. I did use create_project.py right now, but it generate only vs2010 version's .sln file. When it support vs2012?

**Comment by toughrogrammer** [comment]
Oh, sorry. It was all right. File icon was just vs2010. When i run this .sln file, vs2012 was run successfully. (My Visual Studio version is 2012) But i'm wonder about this file icon. Why this icon is vs2010's image?

**Comment by godyZ** [comment]
@meiry Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.

**Comment by minggo** [comment]
vs2010 is not supported now because of c++11.
