### ISSUE TITLE
Why I can't build cocos2dx? (Window)

### ISSUE THREAD

**Issue by toughrogrammer** [cocos2d/cocos2d-x#2926]
I cloned this project, but i coudn't build.
I'm using vs2012. But build-win32.bat is also not running successfully.

But building cocos2d-x-2.1.3 and cocos2d-x-2.1.4 is well.
Why?

**Comment by toughrogrammer** [comment]
Here is error message. I think that this error is most important. 
c:\work\cocos2dx\cocos2d-x-github\cocos2dx\platform\android\ccgl.h(40): fatal error C1083: 'GLES2/gl2platform.h': No such file or directory

There are many error with below, but other is most 'Can't open libcocos2d.lib' message.

**Comment by dumganhar** [comment]
Which branch? master or develop?
Why to build `platform\android\ccgl.h`?

**Comment by toughrogrammer** [comment]
develop branch.
I just want to build cocos2d-win32 project. ( Exactly, open cocos2d-win32.vc2012.sln and build it. )

**Comment by dumganhar** [comment]
Let me check that. :)

**Comment by godyZ** [comment]
@growingdever Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2578
