### ISSUE TITLE
a potential bug in Layer.

### ISSUE THREAD

**Issue by zcgit** [cocos2d/cocos2d-x#2948]
bool Layer::init()
{
    bool bRet = false;
    do 
    {  
        Director \* pDirector;
        CC_BREAK_IF(!(pDirector = Director::sharedDirector()));
        this->setContentSize(pDirector->getWinSize());
        _touchEnabled = false;
        _accelerometerEnabled = false;
        // success
        bRet = true;
    } while(0);
    return bRet;
}

we should replace "_touchEnabled = false;" to setTouchEnabled(bool);

**Comment by dumganhar** [comment]
Hey, is it needed?
in the constructor:

``` cpp
Layer::Layer()
_touchEnabled(false)
```

in Layer::init():
If invoking setTouchEnabled(false), it'll take no effect. You could look inside the logic of `Layer::setTouchEnabled`

**Comment by zcgit** [comment]
I'm sure it's a potential bug.
for example:
    1.you create a Layer by Layer\* pLayer = Layer::create(),
    2.added it to a Node, then pLayer is running. 
    3.then do pLayer-> setTouchEnabled(true); so it will invoke registerWithTouchDispatcher() to addXXXDelegate.
    4.execute pLayer->init(); at this time _touchEnabled is false; but it never removed XXXDelegate!

**Comment by dumganhar** [comment]
But `init` should not be invoked since you're using `create` pattern.
Or it should only be called right after `Layer* p = new Layer();`

**Comment by zcgit** [comment]
yes , but if you do this in CCLayerColor , you will find if you do these below:
1.you create a Layer by CCLayerColor\* pLayer = CCLayerColor::create(),
2.added it to a Node, then pLayer is running. 
3.then do pLayer-> setTouchEnabled(true); so it will invoke registerWithTouchDispatcher() to addXXXDelegate.
4.execute pLayer->init(); at this time _touchEnabled is false; but it never removed XXXDelegate!

often , we want to execute pLayer->init() to reset CCLayerColor. so if we do this , it will cause add twice XXXDelegate to CCLayerColor if you call setTouchEnabled(true) again. just suppose we forgot invoked setTouchEnabled before.

**Comment by dumganhar** [comment]
It makes sense. So could you please send a Pull Request for this issue?
