### ISSUE TITLE
May be find the reason Why issues #1649 occur with libcurl.a when build armeabi-v7a

### ISSUE THREAD

**Issue by waiter** [cocos2d/cocos2d-x#2992]
https://github.com/cocos2d/cocos2d-x/issues/1649
@minggo 
https://github.com/cocos2d/cocos2d-x/blob/1c567534383b2c96243e52dd7074df9a5ffd00fa/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a
In this commit the libcurl.a is only about 2.6M. And It's 4M in the develpp branch, and also in the master branch.
And with the 2.6M libcurl.a, these is no warmings.
Something may be goes wrong here.
And It's the reason why we still get these warmings and you can not.
cocos2d-x 2.1.4 should still have this problem.

**Comment by minggo** [comment]
I don't have warnings now.
Which architecture did you test on?

**Comment by waiter** [comment]
@minggo 
I use:
NDK version: r8e
cocos2d-x version: 2.1.4 or 2.1.3
Application.mk:
APP_ABI := armeabi armeabi-v7a x86
when building armeabi-v7a, it will show warnings with libcurl.a like #1649 

And I found:
https://github.com/cocos2d/cocos2d-x/commits/develop/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a
you commit a pull request 4 months ago. 
Then the libcurl.a is about 4M, and this problem is exist in the later cocos2d-x versions.

**Comment by harikrishnar** [comment]
Yup, Same configs, and even i see those warnings..

**Comment by minggo** [comment]
> > https://github.com/cocos2d/cocos2d-x/blob/1c567534383b2c96243e52dd7074df9a5ffd00fa/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a
> > In this commit the libcurl.a is only about 2.6M. And It's 4M in the develpp branch, and also in the master branch.
> > And with the 2.6M libcurl.a, these is no warmings.

Because libcurl.a now supports ssh and crypto, so the size is more bigger.
4M is the result i stripped unneeded symbols.
Original size without stripping is about 17M.

Yep, it has warnings with ndk-r8e.
I should update unstripped version.

**Comment by minggo** [comment]
@waiter 
May be you can try ndk-r8d.
I think i have tried without warnings.

Can not use ndk-r8d with latest codes.
Because it doesn't support c++11 well.

**Comment by godyZ** [comment]
@waiter Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
