### ISSUE TITLE
CCGrid3D & ContentFactor != 1(in my test case it's 2) cause blurred.....

### ISSUE THREAD

**Issue by JoHuang** [cocos2d/cocos2d-x#2994]
Sample Test Cpp On iPhone retina 640x960. Design size 320x480. content factor = 2.

Please look at these two screeshots. 
No action running on 1st one, you can find the texts and images are sharp.
![ios simulator screen shot 2013 6 26 1 43 56](https://f.cloud.github.com/assets/4118159/704514/bda81b90-ddc2-11e2-8062-cab6130ab6e3.png)

The 2nd one, the page turn action is running and I force the time parameter in update function is 0. The expecting result should be the same as the first screenshot. But you can see the quality is bad. Texts and images seem to be downsampled (like down size by factor 2 and then upscale to original size).

![ios simulator screen shot 2013 6 26 2 01 55](https://f.cloud.github.com/assets/4118159/704515/bddf9f20-ddc2-11e2-9e8f-515dfb4a199d.png)

If the content factor is 1, the issue doesn't exist.
So what I'm thinking is to set design resolution to 640x960 to avoid this issue. But I have to reset all position and size in code or ccb files. And the cocosbuilder does not recommend it. 

Please give me some advisements.

Thanks a lot!

Jo

**Comment by JoHuang** [comment]
After some debug with Xcode, I found that the texture drawn to frame buffer of CCGrid3D is 50% width and 50% height.
Then scale up. So the resolution is half of the original texture.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2574
