### ISSUE TITLE
Bug on CCParallaxNode

### ISSUE THREAD

**Issue by toughrogrammer** [cocos2d/cocos2d-x#2997]
![28](https://f.cloud.github.com/assets/1473538/705007/2ee5aec6-ddcd-11e2-8e8c-4ed8dd53a29b.png)

On this bug, just CCParallaxNode is scrolling to left. 
Sprite is added to CCParallaxNode every 2 seconds.
When sprite added, first, it's coordinate is wrong, but next update, it is ok.(Please look above image.)

You can download project on below link.
http://cocos2d-x.org/boards/6/topics/30450

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2572
