### ISSUE TITLE
Building error on VS2012 express

### ISSUE THREAD

**Issue by nlstone** [cocos2d/cocos2d-x#3016]
I just download latest zip: cocos2d-x-2.1.4.zip, and tried to build it with VS2012 express, it doesn't work, and error msg shows one more "\" added to direcotry "WatermelonWithMe", something like this: "Debug.win32\WatermelonWithMeRes", "Debug.win32\CocosDragonJSRes\"

Then I download code from git, and tried both develop branch & master branch, they both can't work, following is the error message for master branch:

Error   9   error C1083: Cannot open source file: '..\generated\jsb_cocos2dx_extension_auto.cpp': No such file or directory D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\scripting\javascript\bindings\proj.win32\c1xx  libJSBinding
Error   10  error C1083: Cannot open source file: '..\generated\jsb_cocos2dx_auto.cpp': No such file or directory   D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\scripting\javascript\bindings\proj.win32\c1xx  libJSBinding
Error   11  error C1083: Cannot open include file: 'generated/jsb_cocos2dx_auto.hpp': No such file or directory d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\bindings\cocos2d_specifics.cpp    6   1   libJSBinding
Error   12  error MSB3073: The command "if not exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\Debug.win32\" mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\Debug.win32\"
if exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\Debug.win32\MoonWarriorsRes" rd /s /q "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\Debug.win32\MoonWarriorsRes"
mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\Debug.win32\MoonWarriorsRes"
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\scripting\javascript\bindings\js*.js" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\Debug.win32\MoonWarriorsRes" /e /Y
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32....\Shared\games\MoonWarriors" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\MoonWarriors\proj.win32........\Debug.win32\MoonWarriorsRes\" /e /Y
:VCEnd" exited with code 4. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets  124 5   MoonWarriors
Error   13  error MSB3073: The command "if not exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\" mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\"
if exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\TestJavascriptRes" rd /s /q "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\TestJavascriptRes"
mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\TestJavascriptRes"
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\TestJavascript\proj.win32........\scripting\javascript\bindings\js*.js" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\TestJavascriptRes\" /e /Y
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\TestJavascript\proj.win32....\Shared\tests" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\TestJavascriptRes\" /e /Y
:VCEnd" exited with code 4. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets  124 5   TestJavascript
Error   14  error MSB3073: The command "if not exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\" mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\"
if exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CocosDragonJSRes" rd /s /q "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CocosDragonJSRes"
mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CocosDragonJSRes"
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\CocosDragonJS\proj.win32........\scripting\javascript\bindings\js*.js" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CocosDragonJSRes" /e /Y
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\CocosDragonJS\proj.win32....\Shared\games\CocosDragonJS\Published files Android" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CocosDragonJSRes\" /e /Y
:VCEnd" exited with code 4. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets  124 5   CocosDragonJS
Error   15  error MSB3073: The command "if not exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\" mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\"
if exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\WatermelonWithMeRes" rd /s /q "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\WatermelonWithMeRes"
mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\WatermelonWithMeRes"
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\WatermelonWithMe\proj.win32........\scripting\javascript\bindings\js*.js" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\WatermelonWithMeRes" /e /Y
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\WatermelonWithMe\proj.win32....\Shared\games\WatermelonWithMe" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\WatermelonWithMeRes\" /e /Y
:VCEnd" exited with code 4. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets  124 5   WatermelonWithMe
Error   16  error MSB3073: The command "if not exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\" mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\"
if exist "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CrystalCrazeRes" rd /s /q "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CrystalCrazeRes"
mkdir "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CrystalCrazeRes"
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\CrystalCraze\proj.win32........\scripting\javascript\bindings\js*.js" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CrystalCrazeRes" /e /Y
xcopy "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\samples\Javascript\CrystalCraze\proj.win32....\Shared\games\CrystalCraze\Published-Android" "D:\Myprojects\VC\cocos2d-x-git\cocos2d-x\Debug.win32\CrystalCrazeRes\" /e /Y
:VCEnd" exited with code 4. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets  124 5   CrystalCraze
Warning 17  warning C4800: 'size_t' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\jsutil.h   324 1   AssetsManagerTest
Warning 18  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 968 1   AssetsManagerTest
Warning 19  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 973 1   AssetsManagerTest
Warning 20  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 983 1   AssetsManagerTest
Warning 21  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 988 1   AssetsManagerTest
Warning 22  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 993 1   AssetsManagerTest
Warning 23  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 998 1   AssetsManagerTest
Warning 24  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1003    1   AssetsManagerTest
Warning 25  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1008    1   AssetsManagerTest
Warning 26  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1013    1   AssetsManagerTest
Warning 27  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1018    1   AssetsManagerTest
Warning 28  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1023    1   AssetsManagerTest
Warning 29  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1028    1   AssetsManagerTest
Warning 30  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1033    1   AssetsManagerTest
Warning 31  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1038    1   AssetsManagerTest
Warning 32  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1043    1   AssetsManagerTest
Warning 33  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1049    1   AssetsManagerTest
Warning 34  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1054    1   AssetsManagerTest
Warning 35  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1130    1   AssetsManagerTest
Warning 36  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\js\value.h 1443    1   AssetsManagerTest
Warning 37  warning C4800: 'const uint32_t' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\jsclass.h  315 1   AssetsManagerTest
Warning 38  warning C4800: 'JSBool' : forcing value to bool 'true' or 'false' (performance warning) d:\myprojects\vc\cocos2d-x-git\cocos2d-x\scripting\javascript\spidermonkey-win32\include\jsfriendapi.h  451 1   AssetsManagerTest
Error   39  error C1083: Cannot open include file: 'generated/jsb_cocos2dx_auto.hpp': No such file or directory d:\myprojects\vc\cocos2d-x-git\cocos2d-x\samples\cpp\assetsmanagertest\classes\appdelegate.cpp  11  1   AssetsManagerTest

**Comment by minggo** [comment]
@nlstone
What did you do? Could you please describe it step by step?

**Comment by dumganhar** [comment]
Where did you download v2.1.4? Github or official release?

**Comment by nlstone** [comment]
@dumganhar 
In my first step, I download from official website: http://www.cocos2d-x.org/, and then download from Github.

@minggo 
For cocos2d-x-2.1.4.zip, I just unzip it and then open cocos2d-win32.vc2012.sln and build solution in vs2012 express, get error message like this: error: ... "...Debug.win32\WatermelonWithMeRes", "Debug.win32\CocosDragonJSRes\"
And then I also have tried to run install-templates-msvc.bat, then build in vs2012 express again, error is the same.

**Comment by nlstone** [comment]
Eh, the more "\" should be like this: "...Debug.win32\\WatermelonWithMeRes", "Debug.win32\\CocosDragonJSRes\"

**Comment by dumganhar** [comment]
So what's the problem in your first step?
install-templates-msvc.bat has been deprecated. Please use _tools/project-creator_ instead.

**Comment by nlstone** [comment]
@dumganhar 
In my first step, I got 2 buiding Errors: 
Error   1   error MSB3073: The command "if not exist "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\" mkdir "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\"
if exist "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\WatermelonWithMeRes" rd /s /q "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\WatermelonWithMeRes"
mkdir "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\WatermelonWithMeRes"
xcopy "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\samples\Javascript\WatermelonWithMe\proj.win32........\scripting\javascript\bindings\js*.js" "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\WatermelonWithMeRes" /e /Y
xcopy "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\samples\Javascript\WatermelonWithMe\proj.win32....\Shared\games\WatermelonWithMe" "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\WatermelonWithMeRes\" /e /Y
:VCEnd" exited with code 4. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets  124 5   WatermelonWithMe
Error   2   error MSB3073: The command "if not exist "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\" mkdir "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\"
if exist "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\CocosDragonJSRes" rd /s /q "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\CocosDragonJSRes"
mkdir "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\CocosDragonJSRes"
xcopy "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\samples\Javascript\CocosDragonJS\proj.win32........\scripting\javascript\bindings\js*.js" "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\CocosDragonJSRes" /e /Y
xcopy "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\samples\Javascript\CocosDragonJS\proj.win32....\Shared\games\CocosDragonJS\Published files Android" "D:\Myprojects\VC\cocox2d-x-214\cocos2d-x-2.1.4\Debug.win32\\CocosDragonJSRes\" /e /Y
:VCEnd" exited with code 4. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets  124 5   CocosDragonJS

**Comment by minggo** [comment]
@nlstone 
About  cocos2d-x-2.1.4.zip released, please refer to [release note](http://www.cocos2d-x.org/projects/cocos2d-x/wiki/Release_Note_v214). It doesn't contain some resources because of uploading size of google code.

**Comment by nlstone** [comment]
@minggo 
Thanks, I'll check this soon.

**Comment by nlstone** [comment]
Follow the release note, the offiicial 214.zip works well with vs2012 express, thank minggo & dumganhar!
