### ISSUE TITLE
CCEditBox crashed on Galaxy S2(4.0.4)

### ISSUE THREAD

**Issue by honeboy** [cocos2d/cocos2d-x#3021]
CCEditBox crashed on Galaxy S2(4.0.4).
But there is no problem on other devices include Galaxy S2(2.3.3)

This is the same issue at Forum.
http://www.cocos2d-x.org/boards/18/topics/30248

**Comment by zcgit** [comment]
oh ,no , I'm using it in my game.

**Comment by dumganhar** [comment]
Which version of cocos2d-x are you using?

**Comment by honeboy** [comment]
dumganhar // I'm using cocos2d-x v2.1.4 :)

**Comment by dumganhar** [comment]
Could you try the demo you provided on 2.1.3? 
The codes of CCEditBox on android has never changed. If it exists in 2.1.4, the versions before 2.1.4 should also have this problem. 
Please help us check that. Thanks.

**Comment by honeboy** [comment]
dumganhar //

I tested TestCpp - Extensions Test - EditBoxTest

cocos2d-2.1rc0-x-2.1.3
--> NO PROBLEM

cocos2d-x-2.1.4
--> PROBLEM

I will use 2.1.3 for a while.
Thanks.

**Comment by zcgit** [comment]
how about version 2.1.2, I'm using it, sorry about that  I dont't have  Galaxy S2(4.0.4) device.

**Comment by zcgit** [comment]
cocos2d-x-2.1.4 has changed cclabelttf to support shadow and stoke, maybe this caused your problem?

**Comment by dumganhar** [comment]
@zcgit 
I don't think it's relative to shadow and stoke, probably it's because this issue: http://www.cocos2d-x.org/boards/6/topics/27903?page=1&r=30577

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2570
