### ISSUE TITLE
Bug on TableView

### ISSUE THREAD

**Issue by llhbadboy** [cocos2d/cocos2d-x#3024]
I'm using cocos2dx-2.12 JSB.
I have never seen it before yesterday, but I see it very often now.

![p n beinm_h 1_ydp zj8 v](https://f.cloud.github.com/assets/1784401/719710/bd689fc8-df94-11e2-9ba8-827be77896c3.jpg)

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2954 .
You could modify your 2.1.2 codes according to this PR. Be careful to the changes in CCNode.cpp
Thanks.
