### ISSUE TITLE
CCLabelTTF text alignment ignored....

### ISSUE THREAD

**Issue by terenctb** [cocos2d/cocos2d-x#304]
```
CCLabelTTF* pLabel = CCLabelTTF::labelWithString(testString->m_sString.c_str(),CCSizeMake(50,18),CCTextAlignmentRight,"Thonburi", 18);
//CCLabelTTF* pLabel = CCLabelTTF::labelWithString(testString->m_sString.c_str(),"Thonburi", 18);
```

Both these lines have the text in the same position...Alignment is ignored.

Test on iOS

**Comment by walzer** [comment]
I just modify HelloWorldScene.cpp

// add a label shows "Hello World"
// create and initialize a label
CCLabelTTF\* pLabel = CCLabelTTF::labelWithString("Hello World", CCSizeMake(480, 50),
                                                     CCTextAlignmentRight, "Thonburi", 34);

The text alignment right works. Please try to set a larger CCSizeMake, e.g. CCSizeMake(480, 50)

**Comment by walzer** [comment]
Hi, terenctb, I posted a screenshot for you http://www.cocos2d-x.org/boards/6/topics/1969
