### ISSUE TITLE
can make libextension.a but can not make libcocos2d.a (ndk r8e,cocos2dx2.1.4)

### ISSUE THREAD

**Issue by aaronxie** [cocos2d/cocos2d-x#3075]
StaticLibrary  : libcocos2d.a
/cygdrive/f/android/ndk/build/core/build-binary.mk:352: recipe for target `obj/local/armeabi/libcocos2d.a' failed
make: **\* [obj/local/armeabi/libcocos2d.a] Segmentation fault
make: 离开目录“/cygdrive/f/cocos2d-x-2.1.4/ox/proj.android”

**Comment by minggo** [comment]
Which sample did you run?

**Comment by aaronxie** [comment]
not a sample,run crate-android-project.bat,and create a project named ox,and then run build_native.sh

**Comment by minggo** [comment]
I don't know what'e wrong.
I think you can checkout the difference between new project and HelloWorld.

**Comment by aaronxie** [comment]
some computer successed,but some failed;

**Comment by aaronxie** [comment]
run the sample has the same problem.

**Comment by minggo** [comment]
I am sorry.
It seems that it is the error of ndk.
I don't know how to resolve it.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2571
