### ISSUE TITLE
create-android-project.sh invokes a script that doesn't exist

### ISSUE THREAD

**Issue by fastrde** [cocos2d/cocos2d-x#3087]
In create-android-project.sh line 135: 
$COCOS2DX_ROOT/template/linux/mycopy_files.sh is called on linux systems, but the folder $COCOS2DX_ROOT/template/linux/ doesn't exist.

lg

fastr

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2569
