### ISSUE TITLE
template/android/copy_files.sh can't copy jni and src

### ISSUE THREAD

**Issue by fastrde** [cocos2d/cocos2d-x#3088]
template/android/copy_files.sh is called from create-android-project.sh like "... sh template/android/copy_files.sh ..." in line 141
sh can't resolve the statement {jni,src} in copy_files.sh line 34

to ways to solve it:
1. call "... bash template/android/copy_files.sh ... " in create-android-project.sh
2. make 2 single statements to cp jni and src folders in copy_files.sh

lg 

fastr

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2568
