### ISSUE TITLE
CCMenu Issue

### ISSUE THREAD

**Issue by valentiplunge** [cocos2d/cocos2d-x#3089]
I created a CCMenu object and added some CCMenuItems as children with Z increasing in every CCMenuItem, something like:

addChild(CCMenuItem, 1)
addChild(CCMenuItem, 2)
...

But when I touched them the priority was inverted, when I touched the CCMenuItem with z:2 I activated the CCMenuItem with z:1. For additional information the first CCMenuItem was a background and the second one was a button over it. I looked up in the code of CCMenu and I think it is fault of a CCARRAY_FOREACH that should be CCARRAY_FOREACH_REVERSE.

Thank you.

**Comment by metalbass** [comment]
I can reproduce this. It's easy to notice when the items overlap.

**Comment by valentiplunge** [comment]
Yes, I will try to remember it.

Thank you very much.

**Comment by godyZ** [comment]
:)

**Comment by godyZ** [comment]
The issue is migrated to http://www.cocos2d-x.org/issues/2711
