### ISSUE TITLE
Bug about CCControlSwitch on 2.1.4 release

### ISSUE THREAD

**Issue by emmychen** [cocos2d/cocos2d-x#3093]
I got this error message from CCControlSwitch

Cocos2d: OpenGL error 0x0502 in /Users/emmychen/cocos2d-x-proj/cocos2dx/proj.ios/../sprite_nodes/CCSprite.cpp draw 591

```
CCControlSwitch *switchControl = CCControlSwitch::create
(
 CCSprite::create("switch-mask.png"),
 CCSprite::create("switch-on.png"),
 CCSprite::create("switch-off.png"),
 CCSprite::create("switch-thumb.png"),
 CCLabelTTF::create("On", "Arial-BoldMT", 16),
 CCLabelTTF::create("Off", "Arial-BoldMT", 16)
 );
```

The switch-mask.png does not show on the screen.  
It happened in the TestCpp too.  

Emmy

**Comment by dumganhar** [comment]
Thanks @emmychen 
Yep, it's a bug in v2.1.4. But it was fixed at 

https://github.com/cocos2d/cocos2d-x/pull/3065/files  (First Pull Request, not resolved)
https://github.com/cocos2d/cocos2d-x/pull/3067/files  (Second Pull Request, Resolved)

You could easily modify the codes based on v2.1.4 to resolve this issue.
If there is any difficulty, please let me know. Thanks.

James

**Comment by emmychen** [comment]
Hi James:
Thanks for the quick respond.  I have an issue about kShader_PositionColor. 

Where did you define kShader_PositionColor?

Emmy

**Comment by dumganhar** [comment]
In cocos2dx/shaders/CCGLProgram.h:

```
#define kShader_PositionColor                     "ShaderPositionColor"
```

**Comment by emmychen** [comment]
found it. it works now.  Thanks for the help!

**Comment by dumganhar** [comment]
My pleasure. :)

**Comment by emmychen** [comment]
![error](https://f.cloud.github.com/assets/2636388/759968/6e9b77bc-e7a0-11e2-9cb2-bca8f9ef7696.png)

When I created more than one CCControlSwitch, I got the problem like displayed on the image.  Any idea how to fix it?

**Comment by dumganhar** [comment]
No idea yet.
I created an issue http://cocos2d-x.org/issues/2381 here.

**Comment by emmychen** [comment]
Is there anyway to fix this earlier? I am about ready to release this app.  Just waiting for this to be fixed.

**Comment by dumganhar** [comment]
OK, I'll check it out as soon as possible, but you know that we're very busy. :)
Anyway, when I get the result, I'll let you know.

**Comment by emmychen** [comment]
Thanks.  I will use other menu items to work around this for now.

**Comment by dumganhar** [comment]
@emmychen 
It was fixed at https://github.com/cocos2d/cocos2d-x/pull/3113 .
Could you test it ?

**Comment by dumganhar** [comment]
Now, you need to apply patch in 
1) https://github.com/cocos2d/cocos2d-x/pull/3065/files (First Pull Request, not resolved)
2) https://github.com/cocos2d/cocos2d-x/pull/3067/files (Second Pull Request, Resolved)
3) https://github.com/cocos2d/cocos2d-x/pull/3113

Hope it works. :)
