### ISSUE TITLE
CC_SAFE_DELETE is redundant

### ISSUE THREAD

**Issue by metalbass** [cocos2d/cocos2d-x#3099]
CCObject\* ptr = NULL;
delete ptr;  <-- The behaviour of this is defined and it's a NOP (no operation).

CC_SAFE_DELETE should be defined as a delete, avoding the if, as the system already does that.

**Comment by minggo** [comment]
@metalbass 

> CCObject\* ptr = NULL;
> delete ptr; <-- The behaviour of this is defined and it's a NOP (no operation).

Good to know.
Any link for it?
Thanks.

**Comment by metalbass** [comment]
I've read that in Scott Meyers' Effective C++ 3rd edition. I don't have a link by now, I could get it for you latter if you want :)

**Comment by minggo** [comment]
I wrote a sample running on iOS, deleting a nullptr doesn't cause crash. It is great.

**Comment by metalbass** [comment]
I highly recommend Effective C++ to everyone, it's a incredible source of knowledge :)

**Comment by ricardoquesada** [comment]
Good catch.

The same is true for `free(NULL)`
http://answers.yahoo.com/question/index?qid=20080213231138AAtFGJO

We should deprecate `CC_SAFE_DELETE()` (not remove it since some users might be using it), but replace `CC_SAFE_DELETE()` with `delete` in our code.

**Comment by minggo** [comment]
@ricardoquesada 
Agreed.

**Comment by metalbass** [comment]
I close this isssue as the pull request is merged. Thanks :)
