### ISSUE TITLE
CCEditBox text positioning is invalid when moving parent

### ISSUE THREAD

**Issue by metalbass** [cocos2d/cocos2d-x#3100]
Steps to reproduce:
1. Create a CCScene (at position 0,0).
2. Create a CCEditBox anywhere and add it to previous scene
3. CCEditBox is shown correctly both normal and while editing
4. Move parent scene to somewhere not (0,0)
5. CCEditBox is shown correctly unless you edit it.

I found that adding `this->setPosition(this->getPosition());` to `CCEditBox::keyboardWillShow` so it internally calls `CCEditBoxImplIOS::adjustTextFieldPosition` in `CCEditBoxImplIOS::setPosition`

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2566
