### ISSUE TITLE
signal 4 (SIGILL), code 1 (ILL_ILLOPC) using JSB with cocos2d-x 2.1.4 release on Kindle Fire HD

### ISSUE THREAD

**Issue by jhurt** [cocos2d/cocos2d-x#3119]
On cocos2d-x 2.1.4 release version, if you try to run any of the JavaScript samples on a Kindle Fire HD with Form Factor: 7.1.5, the game will crash with a stack dump similar to the following:

07-09 15:44:15.140: DEBUG/dalvikvm(542): Trying to load lib /data/data/org.cocos2dx.watermelonwithme/lib/libwatermelonwithme.so 0x40515280
07-09 15:44:15.310: INFO/DEBUG(30): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
07-09 15:44:15.310: INFO/DEBUG(30): Build fingerprint: 'generic/sdk/generic:2.3.4/GRJ22/eng.abprasad.20120613.112236:eng/test-keys'
07-09 15:44:15.310: INFO/DEBUG(30): pid: 542, tid: 542  >>> org.cocos2dx.watermelonwithme <<<
07-09 15:44:15.310: INFO/DEBUG(30): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 8166e7c4
07-09 15:44:15.310: INFO/DEBUG(30): r0 00000000  r1 81a6b33c  r2 00000000  r3 ffff000f
07-09 15:44:15.310: INFO/DEBUG(30): r4 81a6ab3c  r5 00000006  r6 81a6ab1c  r7 81a6ab14
07-09 15:44:15.310: INFO/DEBUG(30): r8 81a6ab00  r9 81a6ab38  10 81a6ab18  fp 00000008
07-09 15:44:15.310: INFO/DEBUG(30): ip 81a6b33c  sp beabf008  lr b00037f5  pc 8166e7c4  cpsr 60000010
07-09 15:44:15.589: INFO/DEBUG(30): #00  pc 8166e7c4  /data/data/org.cocos2dx.watermelonwithme/lib/libwatermelonwithme.so
07-09 15:44:15.589: INFO/DEBUG(30): #01  lr b00037f5  /system/bin/linker
07-09 15:44:15.611: INFO/DEBUG(30): code around pc:
07-09 15:44:15.611: INFO/DEBUG(30): 8166e7a4 e5813004 e2811008 e151000c 1afffff7
07-09 15:44:15.611: INFO/DEBUG(30): 8166e7b4 e59f40ec e3a00000 e1a02000 e08f4004
07-09 15:44:15.611: INFO/DEBUG(30): 8166e7c4 e6ef1072 e201703f e1a03321 e2033001
07-09 15:44:15.611: INFO/DEBUG(30): 8166e7d4 e1a013c1 e1a06083 e1866003 e2235001
07-09 15:44:15.611: INFO/DEBUG(30): 8166e7e4 e1836086 e1a01f81 e1836086 e1815f05
07-09 15:44:15.611: INFO/DEBUG(30): code around lr:
07-09 15:44:15.611: INFO/DEBUG(30): b00037d4 2a002601 1e48d003 18e40083 00b64276
07-09 15:44:15.611: INFO/DEBUG(30): b00037e4 e0061c0d 19a46823 32031e5a 4798d800
07-09 15:44:15.611: INFO/DEBUG(30): b00037f4 2d003d01 bd70dcf6 1c03b510 1c0433e8
07-09 15:44:15.611: INFO/DEBUG(30): b0003804 28006818 3304d004 22016819 ffdef7ff
07-09 15:44:15.619: INFO/DEBUG(30): b0003814 682334f4 d0002b00 bd104798 4c05b510
07-09 15:44:15.619: INFO/DEBUG(30): stack:
07-09 15:44:15.619: INFO/DEBUG(30): beabefc8  00000000
07-09 15:44:15.619: INFO/DEBUG(30): beabefcc  814aedf4  /data/data/org.cocos2dx.watermelonwithme/lib/libwatermelonwithme.so
07-09 15:44:15.619: INFO/DEBUG(30): beabefd0  00000002
07-09 15:44:15.619: INFO/DEBUG(30): beabefd4  0000000a
07-09 15:44:15.619: INFO/DEBUG(30): beabefd8  00000002
07-09 15:44:15.619: INFO/DEBUG(30): beabefdc  00000001
07-09 15:44:15.619: INFO/DEBUG(30): beabefe0  00000011
07-09 15:44:15.619: INFO/DEBUG(30): beabefe4  00000000
07-09 15:44:15.619: INFO/DEBUG(30): beabefe8  00001000
07-09 15:44:15.619: INFO/DEBUG(30): beabefec  814a9fe8  /data/data/org.cocos2dx.watermelonwithme/lib/libwatermelonwithme.so
07-09 15:44:15.629: INFO/DEBUG(30): beabeff0  00000002
07-09 15:44:15.629: INFO/DEBUG(30): beabeff4  00000000
07-09 15:44:15.629: INFO/DEBUG(30): beabeff8  00000000
07-09 15:44:15.629: INFO/DEBUG(30): beabeffc  00000003
07-09 15:44:15.629: INFO/DEBUG(30): beabf000  df002777
07-09 15:44:15.629: INFO/DEBUG(30): beabf004  e3a070ad
07-09 15:44:15.629: INFO/DEBUG(30): beabf008  81a6aa90
07-09 15:44:15.629: INFO/DEBUG(30): beabf00c  81a6b33c
07-09 15:44:15.629: INFO/DEBUG(30): beabf010  81a6b348
07-09 15:44:15.629: INFO/DEBUG(30): beabf014  81a6aaf4
07-09 15:44:15.629: INFO/DEBUG(30): beabf018  81a6ab34
07-09 15:44:15.629: INFO/DEBUG(30): beabf01c  81a6ab2c
07-09 15:44:15.629: INFO/DEBUG(30): beabf020  81a6aaf8
07-09 15:44:15.629: INFO/DEBUG(30): beabf024  81a6b340
07-09 15:44:15.629: INFO/DEBUG(30): beabf028  81a6aafc
07-09 15:44:15.629: INFO/DEBUG(30): beabf02c  81a6ab20
07-09 15:44:15.629: INFO/DEBUG(30): beabf030  819fd538  /data/data/org.cocos2dx.watermelonwithme/lib/libwatermelonwithme.so
07-09 15:44:15.629: INFO/DEBUG(30): beabf034  000000bc
07-09 15:44:15.629: INFO/DEBUG(30): beabf038  00000004
07-09 15:44:15.629: INFO/DEBUG(30): beabf03c  00000000
07-09 15:44:15.629: INFO/DEBUG(30): beabf040  aca11f40  /system/lib/libdvm.so
07-09 15:44:15.629: INFO/DEBUG(30): beabf044  0000ce48  [heap]
07-09 15:44:15.629: INFO/DEBUG(30): beabf048  4214cc18
07-09 15:44:15.629: INFO/DEBUG(30): beabf04c  44064dcc  /data/dalvik-cache/data@app@org.cocos2dx.watermelonwithme-2.apk@classes.dex
07-09 15:44:15.629: INFO/DEBUG(30): beabf050  b000d164
07-09 15:44:15.639: INFO/DEBUG(30): beabf054  b000d160
07-09 15:44:15.639: INFO/DEBUG(30): beabf058  00002712
07-09 15:44:15.639: INFO/DEBUG(30): beabf05c  b00038a7  /system/bin/linker
07-09 15:44:15.639: INFO/DEBUG(30): beabf060  00a92000
07-09 15:44:15.639: INFO/DEBUG(30): beabf064  afd00000  /system/lib/libc.so
07-09 15:44:15.649: INFO/DEBUG(30): beabf068  00000022
07-09 15:44:15.649: INFO/DEBUG(30): beabf06c  b000d080
07-09 15:44:15.649: INFO/DEBUG(30): beabf070  81a28cd4  /data/data/org.cocos2dx.watermelonwithme/lib/libwatermelonwithme.so
07-09 15:44:15.649: INFO/DEBUG(30): beabf074  b000d080
07-09 15:44:15.649: INFO/DEBUG(30): beabf078  00002712
07-09 15:44:15.649: INFO/DEBUG(30): beabf07c  b0004f9f  /system/bin/linker
07-09 15:44:15.649: INFO/DEBUG(30): beabf080  00000022
07-09 15:44:15.649: INFO/DEBUG(30): beabf084  b000d10c
07-09 15:44:15.649: INFO/DEBUG(30): beabf088  b000d080
07-09 15:44:15.649: INFO/DEBUG(30): beabf08c  00000007
07-09 15:44:15.649: INFO/DEBUG(30): beabf090  00000001
07-09 15:44:15.649: INFO/DEBUG(30): beabf094  0000abe0  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf098  00000000
07-09 15:44:15.649: INFO/DEBUG(30): beabf09c  b000d088
07-09 15:44:15.649: INFO/DEBUG(30): beabf0a0  00000000
07-09 15:44:15.649: INFO/DEBUG(30): beabf0a4  b000d080
07-09 15:44:15.649: INFO/DEBUG(30): beabf0a8  001590e0  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf0ac  0015910d  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf0b0  40515280  /dev/ashmem/dalvik-heap (deleted)
07-09 15:44:15.649: INFO/DEBUG(30): beabf0b4  b0004fe9  /system/bin/linker
07-09 15:44:15.649: INFO/DEBUG(30): beabf0b8  b000d080
07-09 15:44:15.649: INFO/DEBUG(30): beabf0bc  b0004b01  /system/bin/linker
07-09 15:44:15.649: INFO/DEBUG(30): beabf0c0  001590e0  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf0c4  beabf124
07-09 15:44:15.649: INFO/DEBUG(30): beabf0c8  001590e0  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf0cc  40515280  /dev/ashmem/dalvik-heap (deleted)
07-09 15:44:15.649: INFO/DEBUG(30): beabf0d0  001590e0  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf0d4  beabf124
07-09 15:44:15.649: INFO/DEBUG(30): beabf0d8  001590e0  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf0dc  b00059d1  /system/bin/linker
07-09 15:44:15.649: INFO/DEBUG(30): beabf0e0  0000ce48  [heap]
07-09 15:44:15.649: INFO/DEBUG(30): beabf0e4  aca4813b  /system/lib/libdvm.so
07-09 15:44:15.649: INFO/DEBUG(30): beabf0e8  40515280  /dev/ashmem/dalvik-heap (deleted)
07-09 15:44:15.649: INFO/DEBUG(30): beabf0ec  000007ff
07-09 15:44:15.649: INFO/DEBUG(30): beabf0f0  00000001
07-09 15:44:15.649: INFO/DEBUG(30): beabf0f4  001590e0  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf0f8  aca9e5c0  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf0fc  00000001
07-09 15:44:15.669: INFO/DEBUG(30): beabf100  0000006e
07-09 15:44:15.669: INFO/DEBUG(30): beabf104  aca4e49f  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf108  00000000
07-09 15:44:15.669: INFO/DEBUG(30): beabf10c  40515280  /dev/ashmem/dalvik-heap (deleted)
07-09 15:44:15.669: INFO/DEBUG(30): beabf110  001590e0  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf114  beabf188
07-09 15:44:15.669: INFO/DEBUG(30): beabf118  4006fed0  /dev/ashmem/dalvik-heap (deleted)
07-09 15:44:15.669: INFO/DEBUG(30): beabf11c  aca601f7  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf120  0000ce48  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf124  00000000
07-09 15:44:15.669: INFO/DEBUG(30): beabf128  4272f902  /data/dalvik-cache/system@framework@core.jar@classes.dex
07-09 15:44:15.669: INFO/DEBUG(30): beabf12c  4214cc48
07-09 15:44:15.669: INFO/DEBUG(30): beabf130  beabf180
07-09 15:44:15.669: INFO/DEBUG(30): beabf134  aca16fd8  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf138  aca1c050  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf13c  beabf180
07-09 15:44:15.669: INFO/DEBUG(30): beabf140  00000001
07-09 15:44:15.669: INFO/DEBUG(30): beabf144  00000000
07-09 15:44:15.669: INFO/DEBUG(30): beabf148  0000ce50  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf14c  0008e830  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf150  beabf460
07-09 15:44:15.669: INFO/DEBUG(30): beabf154  acaa3d08
07-09 15:44:15.669: INFO/DEBUG(30): beabf158  44064dcc  /data/dalvik-cache/data@app@org.cocos2dx.watermelonwithme-2.apk@classes.dex
07-09 15:44:15.669: INFO/DEBUG(30): beabf15c  aca1c0e0  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf160  beabf180
07-09 15:44:15.669: INFO/DEBUG(30): beabf164  0000ce48  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf168  aca1c050  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf16c  42328fc0  /dev/ashmem/dalvik-LinearAlloc (deleted)
07-09 15:44:15.669: INFO/DEBUG(30): beabf170  fffffec4
07-09 15:44:15.669: INFO/DEBUG(30): beabf174  aca1afd4  /system/lib/libdvm.so
07-09 15:44:15.669: INFO/DEBUG(30): beabf178  41908f70
07-09 15:44:15.669: INFO/DEBUG(30): beabf17c  acaa4036
07-09 15:44:15.669: INFO/DEBUG(30): beabf180  44064dcc  /data/dalvik-cache/data@app@org.cocos2dx.watermelonwithme-2.apk@classes.dex
07-09 15:44:15.669: INFO/DEBUG(30): beabf184  4214ccbc
07-09 15:44:15.669: INFO/DEBUG(30): beabf188  405220d0  /dev/ashmem/dalvik-heap (deleted)
07-09 15:44:15.669: INFO/DEBUG(30): beabf18c  00000007
07-09 15:44:15.669: INFO/DEBUG(30): beabf190  4223a53c  /dev/ashmem/dalvik-LinearAlloc (deleted)
07-09 15:44:15.669: INFO/DEBUG(30): beabf194  00016f18  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf198  0000ce48  [heap]
07-09 15:44:15.669: INFO/DEBUG(30): beabf19c  beabf138
07-09 15:44:15.669: INFO/DEBUG(30): beabf1a0  4214a300
07-09 15:44:15.689: INFO/DEBUG(30): beabf1a4  0000ce50  [heap]
07-09 15:44:15.689: INFO/DEBUG(30): beabf1a8  41908f70
07-09 15:44:15.689: INFO/DEBUG(30): beabf1ac  acaa4036
07-09 15:44:15.689: INFO/DEBUG(30): beabf1b0  acaa4078
07-09 15:44:15.689: INFO/DEBUG(30): beabf1b4  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf1b8  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf1bc  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf1c0  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf1c4  aca77a25  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1c8  0000ce48  [heap]
07-09 15:44:15.689: INFO/DEBUG(30): beabf1cc  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf1d0  acaa2ad8  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1d4  00002000
07-09 15:44:15.689: INFO/DEBUG(30): beabf1d8  41908f01
07-09 15:44:15.689: INFO/DEBUG(30): beabf1dc  aca16cb8  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1e0  aca16d30  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1e4  aca16bd8  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1e8  aca16c00  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1ec  aca16c30  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1f0  aca16c54  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1f4  aca77a25  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf1f8  00000001
07-09 15:44:15.689: INFO/DEBUG(30): beabf1fc  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf200  acaa2ad8  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf204  00002000
07-09 15:44:15.689: INFO/DEBUG(30): beabf208  00000001
07-09 15:44:15.689: INFO/DEBUG(30): beabf20c  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf210  aca16d30  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf214  aca16bd8  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf218  aca16c00  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf21c  aca16c30  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf220  aca16c54  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf224  aca77a25  /system/lib/libdvm.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf228  00000000
07-09 15:44:15.689: INFO/DEBUG(30): beabf22c  a811d267  /system/lib/libutils.so
07-09 15:44:15.689: INFO/DEBUG(30): beabf230  0016cd58  [heap]
07-09 15:44:15.689: INFO/DEBUG(30): beabf234  beabf37c
07-09 15:44:15.689: INFO/DEBUG(30): beabf238  0020ad9c  [heap]
07-09 15:44:15.689: INFO/DEBUG(30): beabf23c  00000000
07-09 15:44:15.699: INFO/DEBUG(30): beabf240  00179368  [heap]

I have tested on the 2.1.3 release version and the JavaScript sample games run fine. Also note that the games run fine on an x86 Kindle Fire HD emulator, it only crashes using the armeabi binary.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2563
