### ISSUE TITLE
CCRenderTexture: assertion on Samsung Galaxy Tab 7.7

### ISSUE THREAD

**Issue by sergey-shambir** [cocos2d/cocos2d-x#3134]
Looks like this assertion from CCRenderTexture.cpp triggers on this device.
`CCAssert(glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE, "Could not attach texture to framebuffer");`

I cannot check because have no access to this device.

P.S. of course, assertion does not stop game in release build.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2562
