### ISSUE TITLE
Problem of Obfuscating the Javascript source code

### ISSUE THREAD

**Issue by llhbadboy** [cocos2d/cocos2d-x#3137]
First, it's so hard!!!

I have a custom JSB Class named FDScrollView, and I defined it in my obfuscate_exclude_XXX.js
var sv = function(){};
CSSProperties.prototype.FDScrollView;
CSSProperties.prototype.setMinZoomFactor;
CSSProperties.prototype.setMaxZoomFactor;
...

then I generate my game.js, everything is ok except one line.
source code:
var scrollView = sv.FDScrollView.create(winSize, this.layer);
scrollView.setContentSize(mapSize);
scrollView.setDirection(cc.SCROLLVIEW_DIRECTION_BOTH);

in game.js
e.setContentSize(b);
e.setDirection(cc.Ok);

where is my first line?????

**Comment by llhbadboy** [comment]
BTW, is there an easy way to protect my JSB source code? Obfuscate is too hard, I must modify a lot of codes and debug in the obfuscated code, I almost lost my mind!!!

**Comment by dumganhar** [comment]
You could use jscompile in cocos2d-console to compile your js to bytecode.
- James
  ÔÚ 2013-7-12 ÉÏÎç10:20£¬"llhbadboy" notifications@github.comÐ´µÀ£º

**Comment by llhbadboy** [comment]
I generate *.jsc, how to use it?

**Comment by dumganhar** [comment]
Just the same as normal js.

``` cpp
ScriptingCore::getInstance()->runScript("xxxx.js", ...)
```

This API will search .jsc file firstly.
