### ISSUE TITLE
How to use *.jsc?

### ISSUE THREAD

**Issue by llhbadboy** [cocos2d/cocos2d-x#3138]
I generated javascript byte code using command line, and I replaced *.js with *.jsc, then it crashed.
the log is in the attachment.
![5c61c6de-ac00-403e-8590-08f289f22059](https://f.cloud.github.com/assets/1784401/786208/a282c106-eaa3-11e2-8e50-70ba9014a0a4.png)

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2561
