### ISSUE TITLE
CCParallaxNode removeChild

### ISSUE THREAD

**Issue by samueldedavid** [cocos2d/cocos2d-x#3168]
ccparallaxnode::removeChild(ccnode); removes child but according to DisplayStats objects are not removed .Also when I call ccparallaxnode::removeallchildren() application crashes.Please look into.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2560
