### ISSUE TITLE
Content scale factor issue 

### ISSUE THREAD

**Issue by vladubogdan** [cocos2d/cocos2d-x#3184]
Hey Riq,

I have a very big problem in Cocos2d-X. The sprites are not the same size when using content scaling factor.

I have the following HD frame rectangle (screenshot 1)

![screenshot 1](https://f.cloud.github.com/assets/1398772/817214/fc9b1cca-ef6b-11e2-8687-2d87a95cabaa.png)

and the SD counterpart (as you see the frame, source size and all related info is twice smaller) (screenshot 2)
![screenshot 2](https://f.cloud.github.com/assets/1398772/817215/fccc84e0-ef6b-11e2-921b-69701b68782c.png)

Now when loading this info in - i get the following result on retina iPhone 4 (screenshot 3)
![screenshot 3](https://f.cloud.github.com/assets/1398772/817219/fcf286a4-ef6b-11e2-80d3-d45257e1ccd2.png)

while on non retina iPhone the sprite is much much bigger (screenshot 4)
![screenshot 4](https://f.cloud.github.com/assets/1398772/817217/fcf37eec-ef6b-11e2-98b8-6d7c4c8ccabe.png)

The correct sprite size is the one from Normal iPhone (Screenshot 4)

Looking at TestCpp test cases in cocos2d-x inside AppDelegate you have this line

CCEGLView::sharedOpenGLView()->setDesignResolutionSize(designSize.width, designSize.height, kResolutionNoBorder);

If you comment this line you will get the same result in your test cases (screenshot 5 and 6)
![screenshot5](https://f.cloud.github.com/assets/1398772/817218/fcf9ed68-ef6b-11e2-9080-62fbb0c2f4bc.png)
![screenshot 6](https://f.cloud.github.com/assets/1398772/817216/fcecd722-ef6b-11e2-87ed-5f86da770102.png)

I should not be forced to use a design resolution since i provide plist with correct sizing. 

You should not transform the rectangle from a hd plist.

Right now cocos2d-x divides the sprite size by the content scale factor making the sprite twice smaller. This is not needed and its causing this issue.

Please let me know if this is desired behaviour or how it's supposed to work.

**Comment by ricardoquesada** [comment]
Issue duplicated here:
http://www.cocos2d-x.org/issues/2493
