### ISSUE TITLE
Unable to extend TableView in Javascript. Multiple issues.

### ISSUE THREAD

**Issue by asfdfdfd** [cocos2d/cocos2d-x#3199]
Tested on master branch.

This code is enough.

``` javascript
var MyTableView = cc.TableView.extend({});
```

It crashes in CCObject:release on assert.

To avoid this problem i've commented out m_pTouches->release() in CCScrollView. It is ugly hack of course.

But then program started to crash in another place. Assume that we have such code

``` javascript
var TableViewSelectable = cc.TableView.extend({

    onTouchBegan: function (touch, event) {
        var retval = this._super(touch, event);
        // smth.
        return retval;
    },

    onTouchMoved: function (touch, event) {
        var retval = this._super(touch, event);
        // smth.
        return retval;
    },

    onTouchEnded: function (touch, event) {
        var retval = this._super(touch, event);
        // smth.
        return retval;
    }
});

TableViewSelectable.create = function (dataSource, size, container) {
    var table = new TableViewSelectable();
    table.initWithViewSize(size, container);
    table.setDataSource(dataSource);
    table._updateContentSize();
    return table;
};
```

And i'm using it in a such way.

``` javascript
this._tablePuzzles = TableViewSelectable.create(dataSource, cc.size(123, 123));
```

Now it is crashing (on creation) in JSVAL_TO_OBJECT. Well. I've fixed it with function call modification. Now it is.

``` javascript
this._tablePuzzles = TableViewSelectable.create(dataSource, cc.size(123, 123), cc.Layer.create());
```

After it crashed in CCTableView::_updateContentSize on float maxPosition = m_vCellsPositions[cellsCount]; line.

Ok. I've moved code from my "create" function and using it instead of call create function. Now it does not crash - just does not work (onTouchBegan, onTouchEnded, onTouchMoved does not called, but they should) and my engine knowledge to produce ugly hacks finished.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2513

**Comment by asfdfdfd** [comment]
Correct issue link now is http://www.cocos2d-x.org/issues/2558

**Comment by godyZ** [comment]
@asfdfdfd  sorry it's my mistake.
