### ISSUE TITLE
Add JS scripting for Blackberry

### ISSUE THREAD

**Issue by amerkoleci** [cocos2d/cocos2d-x#3222]
Integrate SpiderMonkey building for blackberry and cocos2D-x JS binding.

https://github.com/blackberry/SpiderMonkey

**Comment by dumganhar** [comment]
That library is too old. 2 years ago.....

**Comment by amerkoleci** [comment]
Yes but the QNX build script are the same i suppose.

**Comment by dumganhar** [comment]
Blackberry port has been removed on the github codes since it doesn't support `c++11` well.
