### ISSUE TITLE
where "Time::gettimeofdayCocos2d" is?

### ISSUE THREAD

**Issue by sunzhaoping** [cocos2d/cocos2d-x#3223]
platform.h is missing in new version of develop branch, why make so much changes of  type names?

code:
    struct cocos2d::cc_timeval now;
    cocos2d::Time::gettimeofdayCocos2d(&now, NULL);

**Comment by minggo** [comment]
It is duplicated codes since all unix like system already has gettimeofday().
Only win32 doesn't have this interface, and it is implemented in CCStdC.h.

platform.cpp/.h only has the implementation of cocos2d::Time. It is useless.
We should remove as many files as possible to keep engine simple.

**Comment by sunzhaoping** [comment]
I see, thanks!
