### ISSUE TITLE
CCLayerColor can't change color or opacity when parent setColor or setOpacity

### ISSUE THREAD

**Issue by Yehsam23** [cocos2d/cocos2d-x#3240]
If CCLayerColor is CCNodeRGBA's child

When setColor or setOpacity to CCNodeRGBA, CCLayerColor doesn't change color or opacity

CCLayerColor class should add

virtual void updateDisplayedColor(const ccColor3B& parentColor);
virtual void updateDisplayedOpacity(GLubyte parentOpacity);

.cpp should add

void CCLayerColor::updateDisplayedColor(const ccColor3B& parentColor)
{
    CCLayerRGBA::updateDisplayedColor(parentColor);
    updateColor();
}

void CCLayerColor::updateDisplayedOpacity(GLubyte opacity)
{
    CCLayerRGBA::updateDisplayedOpacity(opacity);
    updateColor();
}

Sorry i don't know how to use pull request!!

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2557
