### ISSUE TITLE
Missing protocol in IAP plugin

### ISSUE THREAD

**Issue by ezhozhe** [cocos2d/cocos2d-x#3274]
In IAP plugin, we only have protocol to pay for a product.
Like: public void payForProduct(Hashtable<String, String> cpInfo);

Could we have protocol to pay for virtual coins? For example, the function "ndUniPayForCoin" for Nd91

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2555
