### ISSUE TITLE
CCDictElement optimization!

### ISSUE THREAD

**Issue by harikrishnar** [cocos2d/cocos2d-x#3324]
Hi All,

In CCDictElement the key is a 256 long char array, how can we optimize it?

When i change it to char\* and use malloc inside the constructor of CCDictElement to allocate memory and copy the string, 

HAS_FIND_STR returns NULL always?

Whats the approach i should take?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2552
