### ISSUE TITLE
(JSB) Chipmunk: pointQueryFirst not working on device

### ISSUE THREAD

**Issue by jhneves** [cocos2d/cocos2d-x#3325]
I was testing pointQueryFirst on an iPhone 4s and it didnt work.

I set a breakpoint at its c function:
cpSpacePointQueryFirst(cpSpace *space, cpVect point, cpLayers layers, cpGroup group)

the argument "layers" is always ZERO on device...

it DOES work on simulator though...

**Comment by jhneves** [comment]
The value I was trying to pass on layer argument was "1<<31", which worked on web and iphone simulator but didnt on device (iPhone 4S)

I guess I found a solution for now: when using cp.ALL_LAYERS (~0) it does works everywhere.... but I guess there might still be a bug there?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2551
