### ISSUE TITLE
Build demo TestCpp for Tizen error at  for ( auto &item: *touches )

### ISSUE THREAD

**Issue by kienvn** [cocos2d/cocos2d-x#3360]
Error at:

for ( auto &item: _touches )
    {
        Touch_ touch = static_cast<Touch*>(item);
        ....
    }

///////////////////////////////////////////////////
It worked when I change:

 for (auto item = touches->begin(), end = touches->end(); item != end; ++item)
    {
        Touch\* touch = static_cast<Touch*>(*item);
        .....
    }

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2548
