### ISSUE TITLE
HttpResponse bug on Mac OS X

### ISSUE THREAD

**Issue by rubenvanrooij** [cocos2d/cocos2d-x#3373]
This is my first issue ever. So I haven't any clue on how to do this properly. I found a bug in cocos2d-x 3.0-pre-alpha0 when doing an HttpRequest on Max OS X. It just crashes when doing a request.. EXC_BAD_ACCESS error. I tried to find a solution but so far no good.

The NetworkTest in the samples project also crashes on Max OSX.

HttpClient.cpp 
Line 189
// write data to HttpResponse
response->setResponseCode(responseCode);

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2545
