### ISSUE TITLE
Cocos2d-x 3.0 - Tilemap Image Source Path

### ISSUE THREAD

**Issue by notamonopoly** [cocos2d/cocos2d-x#3375]
The issue is with TMXTiledMap in release 3.0alpha0-pre.

The source image used in the tmx file should be relative to the that file, but in this version CCTMXLayer looks in the main resource folder.

The error occurs in the file CCTMXLayer.cpp, TMXLayer::initWithTilesetInfo(TMXTilesetInfo *tilesetInfo, TMXLayerInfo *layerInfo, TMXMapInfo *mapInfo)

Version 3:
texture = TextureCache::getInstance()->addImage(tilesetInfo->_sourceImage.c_str());

Version 2 (worked properly):
texture = CCTextureCache::sharedTextureCache()->addImage(tilesetInfo->m_sSourceImage.c_str());

m_sSourceImage contained the full path to the image file, where _sourceImage only has the file name.

The code to reproduce the problem is simply:
map = TMXTiledMap::create("tmx/level1.tmx");
this->addChild(map);

Note: The tmx file and image file have to be in a sub-folder to reproduce the error, if you move the tmx and source image into the main resource folder it works.

**Comment by ricardoquesada** [comment]
Issue duplicated here:
http://www.cocos2d-x.org/issues/2492
