### ISSUE TITLE
The project created by "create_project.py" cannot move to other dir

### ISSUE THREAD

**Issue by huaz836** [cocos2d/cocos2d-x#3389]
windows7 + vs2012 + cocos2d-x-2.1.4
I use _tools/project-creator/create_project.py_ to create new project, 
and the project work well in _COCOS2DX_DIR/prjoects_.

But when move to other dir("E:\"), it cannot work.  
says cannot found 
_E:\CocosDenshion\proj.win32\CocosDenshion.vcxproj_, _E:\extensions\proj.win32\libExtensions.vcxproj_  etc.

How to do with the situation?
I think if it possible to add an option to specify the project dir in the script?
Thanks.

**Comment by winipcfg** [comment]
If you use create_project.py to create project, all paths in the solution/project files are relative paths and assume cocos2d is the root folder. So it does not work if you move your project to another folder.
