### ISSUE TITLE
CallFuncN  clone  Issues...

### ISSUE THREAD

**Issue by LeeMyoungYeol** [cocos2d/cocos2d-x#3391]
CallFuncN \* CallFuncN::clone() const
{
    // no copy constructor
    auto a = new CallFuncN();

```
if( _selectorTarget) {
    a->initWithTarget(_selectorTarget, _callFuncN);
}
else if( _functionN ){                             <- //@Issues
    a->initWithFunction(_functionN);
}

a->autorelease();
return a;
```

}
1. change
   _function -> _functionN

**Comment by minggo** [comment]
Yep, you are right.
Could you please send a pull request to resolve it?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2544
