### ISSUE TITLE
android link error 

### ISSUE THREAD

**Issue by sunzhaoping** [cocos2d/cocos2d-x#3395]
when i used build_native.sh to build the project, many link error existed:

jni/game/main.cpp:18: error: undefined reference to 'cocos2d::JniHelper::setJavaVM(_JavaVM*)'
jni/game/main.cpp:27: error: undefined reference to 'cocos2d::EGLView::getInstance()'
jni/game/main.cpp:31: error: undefined reference to 'cocos2d::Application::getInstance()'
jni/game/main.cpp:31: error: undefined reference to 'cocos2d::Application::run()'
jni/../../Classes/AppDelegate.cpp:32: error: undefined reference to 'cocos2d::Application::~Application()'
jni/../../Classes/AppDelegate.cpp:32: error: undefined reference to 'cocos2d::Application::~Application()'
jni/../../Classes/AppDelegate.cpp:23: error: undefined reference to 'cocos2d::Application::Application()'
jni/../../Classes/AppDelegate.cpp:25: error: undefined reference to 'cocos2d::Application::~Application()'
jni/../../Classes/AppDelegate.cpp:79: error: undefined reference to 'cocos2d::EGLView::getInstance()'
jni/../../Classes/AppDelegate.cpp:91: error: undefined reference to 'cocos2d::FileUtils::getInstance()'
jni/../../Classes/AppDelegate.cpp:96: error: undefined reference to 'cocos2d::FileUtils::getInstance()'
jni/../../Classes/AppDelegate.cpp:100: error: undefined reference to 'cocos2d::FileUtils::getInstance()'
./obj/local/armeabi/objs/game_shared/__/**/Classes/AppDelegate.o:AppDelegate.cpp:function typeinfo for AppDelegate: error: undefined reference to 'typeinfo for cocos2d::Application'
./obj/local/armeabi/objs/game_shared/**/**/Classes/AppDelegate.o:AppDelegate.cpp:function vtable for AppDelegate: error: undefined reference to 'cocos2d::Application::setAnimationInterval(double)'
./obj/local/armeabi/objs/game_shared/**/**/Classes/AppDelegate.o:AppDelegate.cpp:function vtable for AppDelegate: error: undefined reference to 'cocos2d::Application::getCurrentLanguage()'
./obj/local/armeabi/objs/game_shared/**/__/Classes/AppDelegate.o:AppDelegate.cpp:function vtable for AppDelegate: error: undefined reference to 'cocos2d::Application::getTargetPlatform()'
......

**Comment by JiekeZhu** [comment]
Hi,
I meet this same problem now. I wonder if you have resolved it or not ?
And how to resolve it.
Thanks.

**Comment by zilongshanren** [comment]
@JiekeZhu  `./build_native.py` is deprecated, you should use cocos_console instead.

**Comment by darkdukey** [comment]
use `cocos compile -p android` instead of build_native.py

**Comment by zilongshanren** [comment]
@darkdukey  please check the Jenkins slaves in US office. Both of them are broken. :(
Thanks.

**Comment by darkdukey** [comment]
I think might be a power outage, I'll check tmr.
