### ISSUE TITLE
SimpleAudioEngine playEffect() stop working after several entering background and re-entering foreground.

### ISSUE THREAD

**Issue by pktangyue** [cocos2d/cocos2d-x#3400]
platform (ios)
platform version (6.1.3)
device (ipad3)
cocos2d-x version(cocos2d-2.1rc0-x-2.1.3)

In `TestCpp` project CocosDenshionTest, it is easy to reproduce.

And in http://www.cocos2d-x.org/boards/6/topics/3153, many people have met this problem.

**Comment by ricardoquesada** [comment]
Could you re-add the redmine issue on the "issue tracker" ?
http://www.cocos2d-x.org/projects/cocos2d-x/issues/new

We will close the github issue tracker soon.
Thanks.

**Comment by pktangyue** [comment]
Done it.

**Comment by ricardoquesada** [comment]
Thanks!
Link to redmine isuse: http://www.cocos2d-x.org/issues/2512
