### ISSUE TITLE
Black screen after running Android sample application Xperia S

### ISSUE THREAD

**Issue by maciekczwa** [cocos2d/cocos2d-x#3405]
I compiled Android application HelloCpp from samples.
After I run the application the screen is all black.
When i go to the background and back to the application with home button everything becomes visible.

It happens on Sony Xperia S  Android 4.1.2

It works ok on Samsung Galaxy Ace S5830i running Android 2.3.7

When I disabled CC_ENABLE_CACHE_TEXTURE_DATA in CCPlatformMacros.h it is always displaying black screen on Xperia S.

On previous versions it worked ok.

**Comment by maciekczwa** [comment]
On commit 06560a3dfad4d12f0213c349a2e27ae2f985178a it works OK.

But I don't know exactly when it was broken.

Could anyone give me a hint what to look for?

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2542
