### ISSUE TITLE
armeabi-v7a problem on cocos2d-x-3.0alpha0-pre

### ISSUE THREAD

**Issue by linziwen** [cocos2d/cocos2d-x#3409]
when i compile my project with APP_ABI := armeabi-v7a ,i encounter a problem like this:
/android-ndk-r8e/toolchains/arm-linux-androideabi-4.7/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.7/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 19 of /Downloads/cocos2d/cocos2d-x-3.0alpha0-pre/cocos2d-x-3.0alpha0-pre/projects/RichMen/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(file.o) for Cortex-A8 erratum because it has no mapping symbols.

and many many warning analogous to above:
![untitled2](https://f.cloud.github.com/assets/4770703/942799/a0e58c82-01d4-11e3-9a95-fe189f06d1a7.jpg)

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2539
