### ISSUE TITLE
Transitions "zoom" slightly when entering

### ISSUE THREAD

**Issue by ttencate** [cocos2d/cocos2d-x#3412]
Run the TransitionsTest from the C++ test suite, and hit the green button. If you look closely, you should notice that the current scene is zoomed in very slightly (1 pixel or even 0.5 pixel) around its centre, before it is replaced by the next scene. This happens in many different transitions, like CCTransitionProgressHorizontal, CCTransitionCrossFade and CCTransitionProgressRadialCW.

It looks like either the contents of the framebuffer object are not a pixel-perfect replica of the scene on the screen, or the framebuffer's texture isn't drawn to the screen in a pixel-perfect way.

Reproduced using cocos2d-x 2.1.4 on these systems:
- Ubuntu Linux 12.04, with NVIDIA GeForce 9800 GT
- Android 4.2.2 on Nexus 7

So I think it's a real bug and not a platform problem.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2538
