### ISSUE TITLE
Point::normalize calls sqrtf twice

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#3421]
This is only a very minor point but `Point::normalize` (CCGeometry.h:218) gets the vector length with `getLength()` and stores it in a variable, but then gets the length again instead of using the stored value. `getLength()` calls `sqrtf` which I believe can be slow on some platforms if it is not optimized out.
Also (please ask an expert on FP maths!) but I think comparing `length` (a float) to 0. (a double precision constant) is not ideal.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2537
