### ISSUE TITLE
新浪微博分享的bug

### ISSUE THREAD

**Issue by AIRIA** [cocos2d/cocos2d-x#3444]
android平台下在使用plugin分享的时候 总是会提示Failed to receive access token 查了很多资料 后来发现是因为新浪的sdk有问题 在com.weibo.sdk.android.Weibo类的Dialog方法中目前的代码是这样

> parameters.add("response_type", "token");  

但是最新版的新浪sdk已经改成了

> parameters.add("response_type", "code");

替换成新版的sdk后由于方法有变化 plugin就不能用了 希望可以尽早解决下这个问题

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2616

**Comment by AIRIA** [comment]
ok ,thanks!

**Comment by godyZ** [comment]
with pleasure :)
