### ISSUE TITLE
setKeypadEnabled not working on android 4.2

### ISSUE THREAD

**Issue by sunzhaoping** [cocos2d/cocos2d-x#3449]
I used setKeypadEnabled(true) in a Layer's init method .

The  method keyBackClicked was not called  by the dispatcher but exit the app when I pressed the back key of the device .  
there's  not problem in version  2.1.4.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2703

**Comment by sunzhaoping** [comment]
Oh , I see
