### ISSUE TITLE
performance on android 4.x is much slower then 2.3.3

### ISSUE THREAD

**Issue by sixian** [cocos2d/cocos2d-x#3451]
I run performance test on the same device with different version android(4.1 & 2.3),and i found that  fps on 4.1 is much lower then 2.3

device: samsung s2
test: testcpp -> PerformanceSpriteTest
fps: 60fps on 2.3
       37fps on 4.1

all devices are turn off power saving
apk build with ndk r8e

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2701
