### ISSUE TITLE
Problem with dictionary in scheduled method

### ISSUE THREAD

**Issue by 1755** [cocos2d/cocos2d-x#3476]
Hello, i have next singletone for game settings:

``` c++
static MSettingsCenter* s_settingsCenter = NULL;
static Dictionary* s_dict = NULL;

MSettingsCenter* MSettingsCenter::getInstance()
{
    if(s_settingsCenter == NULL) {
        s_settingsCenter = new MSettingsCenter;
        s_dict = Dictionary::createWithContentsOfFile("settings.plist");
    }
}

MSettingsCenter::MSettingsCenter()
{
}

String* MSettingsCenter::value(const char *path) const
{
    CCLOG("load setting: %s", path);
    String* value = (String*)s_dict->objectForKey(path);
    if(value == NULL) {
        CCLOG(" [!cannot find value]");
    }

    return value;
}

```

It work nice, but when i call settings->value('path'); in scheduled method it every time return NULL (s_dict, s_settingsCenter is correct values)

p.s
cocos2dx 3.0-alpha0-pre

**Comment by godyZ** [comment]
@e-gress  Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2717
