### ISSUE TITLE
a little bug about Color4F's constructor

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#3477]
It's wrong:

```
explicit Color4F(const Color3B &color3B)
    : r(color3B.r)
    , g(color3B.g)
    , b(color3B.b)
    , a(1.f)
{}
```

and I think this is right:

```
explicit Color4F(const Color3B &color3B)
    : r(color3B.r / 255.0f)
    , g(color3B.g / 255.0f)
    , b(color3B.b / 255.0f)
    , a(1.f)
{}
```

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2718
