### ISSUE TITLE
Please avoid $(SolutionDir) in Project configuration

### ISSUE THREAD

**Issue by ChristianFischer** [cocos2d/cocos2d-x#399]
The project configuration uses $(SolutionDir) on several settings, which makes it impossible to add the cocos projects into own solutions.

For example, in cocos2dx, PreLinkEvent this command is used:
<code>if not exist "$(OutDir)" mkdir "$(OutDir)"
xcopy /Y /Q "$(SolutionDir)cocos2dx\platform\third_party\win32\libraries*.*" "$(OutDir)"</code>

This could be replaced with:
<code>if not exist "$(OutDir)" mkdir "$(OutDir)"
xcopy /Y /Q "<b>$(ProjectDir)..</b>\platform\third_party\win32\libraries*.*" "$(OutDir)"</code>

The lua project uses $(SolutionDir) in it's include paths, where it can be replaced with "../../" relative paths.

This changes shouldn't affect existing projects, but should allow to add them into own visual studio solutions somewhere else on your hard disk.

**Comment by ciaranj** [comment]
I'm running up a patch for this atm for the lua template generator ...

**Comment by ciaranj** [comment]
If you want to see the work I've done on this so far, please take a look at : https://github.com/ciaranj/cocos2d-x/tree/vs_template_branch  

This isn't suitable for pulling at-the-moment, but will be shortly.  I've only resolved the issue for VS2010 projects & solutions so far, could anyone comment on whether this is the correct approach or not??

**Comment by godyZ** [comment]
@ciaranj Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2696
