### ISSUE TITLE
iOS5 and scale factor ?

### ISSUE THREAD

**Issue by cyrildiagne** [cocos2d/cocos2d-x#552]
Hi, I just upgraded my iphone 4 to iOS5 and the graphics are now all messed up in my cocos2d-x 1.0.1 game.
It does use the retina graphics but the positions are all messed up.

Everything runs fine on the 4.3 simulator, but I have same problem in the 5.0 simulator.

I tried to google and look in the CCDirector a hint on that bug but I couldn't find anything..

Is that a known issue ?

**Comment by walzer** [comment]
I'm downloading xcode4.2 with ios5 sdk currently, several hours are required to complete. Hope I can reproduce this bug today.

**Comment by cyrildiagne** [comment]
Thanks Walzer!
And many thanks for all the awesome work on cocos2d-x!

**Comment by cyrildiagne** [comment]
Hmm don't know if it comes from the update I did on github or the fact that I unchecked the supported device orientation in xcode project's setting. But it seems to work fine now !
