### ISSUE TITLE
Crash when application closed and currently transition scene active

### ISSUE THREAD

**Issue by ferreus** [cocos2d/cocos2d-x#566]
Application crashed when trying to exit, while changing scene (Transition active).
The debuger shows that it crashed on: CCTexture2d.cpp:81 ( In destructor: glDeleteTextures(1, &m_uName);)
This http://www.cocos2d-x.org/boards/12/topics/4738?r=4747  suggests that InScene doesn't receive onExit calls.
And it doesn't. There is a comment in CCTransition.cpp:onExit call: 
"// inScene should not receive the onExit callback
    // only the onEnterTransitionDidFinish"

But actually adding the onExit call does solves the crash.

**Comment by ferreus** [comment]
Yep, it should not get the onExit call.

**Comment by moadib** [comment]
It's shouldn't receive onExit in all cases except of immediately application close.

**Comment by gzito** [comment]
Hi ferreus,

if you're talking about marmalade (a.k.a. airplay) port, I fixed this bug in #610.

**Comment by ferreus** [comment]
No, i had this crash on win32.

**Comment by godyZ** [comment]
@ferreus Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2694
