### ISSUE TITLE
TargetConditionals.h could be included somewhere for iOS ?

### ISSUE THREAD

**Issue by cyrildiagne** [cocos2d/cocos2d-x#576]
Hi,

I just came across an issue where TARGET_IPHONE_SIMULATOR wasn't defined when I compiling for the iOS simulator.

I found out after some investigations that I needed to include the "TargetConditionals.h" file to get that macro defined.

Maybe that file could be added somewhere in iOS classes ? Not sure where though :/

thanks!

**Comment by minggo** [comment]
We want to include this file to determine if it is iOS or simulator, but we can include it only it is on iOS platform. So it seems a dead lock.

**Comment by cyrildiagne** [comment]
Thanks for your reply minggo.

True! But I've added this in one of my class so that I can now determine wether i'm in the iOS simulator or not (using #if TARGET_IPHONE_SIMULATOR) :

#if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
    #include "TargetConditionals.h"
#endif

Is that a correct approach ?

**Comment by minggo** [comment]
Yes, if you know it is on iOS, you can use it like this.

**Comment by cyrildiagne** [comment]
Ok thanks!
