### ISSUE TITLE
modify template msvc AppDelegate

### ISSUE THREAD

**Issue by webmutation** [cocos2d/cocos2d-x#620]
Add This check so that Hybrid Android Projects are not rendered rotated 90º as per forum post http://www.cocos2d-x.org/boards/6/topics/6019

//Android does not need setup. It uses XML
    #if (CC_TARGET_PLATFORM == CC_PLATFORM_WIN32)
        pDirector->setDeviceOrientation(kCCDeviceOrientationLandscapeLeft);
    #endif  // CC_PLATFORM_WIN32

**Comment by godyZ** [comment]
@dan-mendes Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2692
