### ISSUE TITLE
Compiling with ndk-r7 still not working

### ISSUE THREAD

**Issue by Bahamut** [cocos2d/cocos2d-x#626]
Under windows, i can finally compile using ndk-r7 withouth problems (just some warnings) but the APK generated is not OK... at least i always get black screens with android 2.1 and 2.2 emulators (works with android 4 emulators).

This doens't happens with ndk-r6b.
I dont know about mac or unix, i just use cygwing, last cocos2dx stable and latest ndk r7.

**Comment by sapsaldog** [comment]
When I compiled using by ndk-r7 in mac, It works perfect.

but actually I didnt tested on emulators, just tested on devices

**Comment by Bahamut** [comment]
It should work with emulators, i don't know why it shoudlnt...
