### ISSUE TITLE
Broken include guard in CCActionEase.h

### ISSUE THREAD

**Issue by qbit86** [cocos2d/cocos2d-x#673]
Closing include guard is broken.

Expected:

<pre>}

#endif // __ACTION_CCEASE_ACTION_H__</pre>

Actual:

<pre>#endif // __ACTION_CCEASE_ACTION_H__

}</pre>

**Comment by minggo** [comment]
Oh, how carefully you are.
Thank you.

**Comment by donaldalanmorrison** [comment]
@minggo
This one is fixed. :-)
