### ISSUE TITLE
Naming clash in CCTouchDispatcher.cpp

### ISSUE THREAD

**Issue by qbit86** [cocos2d/cocos2d-x#674]
There is a problem with less() function:

<pre>static bool less(const cocos2d::CCTouchHandler *p1, const cocos2d::CCTouchHandler *p2)
{
    return ((cocos2d::CCTouchHandler*)p1)->getPriority() &lt; ((cocos2d::CCTouchHandler*)p2)->getPriority();
}</pre>

In some circumstances (Mac OS X, XCode, order of #include's) one can get an error here (line 304):

<pre>void CCTouchDispatcher::rearrangeHandlers(CCMutableArray&lt;CCTouchHandler*> *pArray)
{
    std::sort(pArray->begin(), pArray->end(), less);
}</pre>

Probably, it is due to disambiguation with std::less, which is accessible via ADL (Koenig lookup) [1] or something like that.

Possible solution:

<pre>namespace /* [2] */ { namespace details {
    
bool less(const cocos2d::CCTouchHandler *p1, const cocos2d::CCTouchHandler *p2)
{
    return ((cocos2d::CCTouchHandler*)p1)->getPriority() &lt; ((cocos2d::CCTouchHandler*)p2)->getPriority();
}

} }</pre>

<pre>
void CCTouchDispatcher::rearrangeHandlers(CCMutableArray&lt;CCTouchHandler*> *pArray)
{
    std::sort(pArray->begin(), pArray->end(), details::less);
}</pre>

[1] http://en.wikipedia.org/wiki/Argument-dependent_name_lookup
[2] http://stackoverflow.com/questions/154469/unnamed-anonymous-namespaces-vs-static-functions

**Comment by minggo** [comment]
Did you mean that, less function should be put into namespace cocos2d?
cocos2d-x don't support Mac OS X, so you port it to Mac OS X?

**Comment by minggo** [comment]
Do you mind posting issues in official forum later?
The link is http://www.cocos2d-x.org/projects/cocos2d-x/boards.

Thank you.

**Comment by qbit86** [comment]
> Did you mean that, less function should be put into namespace cocos2d?

No fear, it's one-time function (as far as I understood), it should not pollute API namespace, it should be only accessible in that compilation unit.

I placed it into anonymous namespace, because it's (according to Stroustrup) preferred way to restrict function visibility:
“The use of the static keyword is deprecated when declaring objects in a namespace scope, the unnamed-namespace provides a superior alternative.”

> cocos2d-x don't support Mac OS X, so you port it to Mac OS X?

No, I just building under Mac OS X targeting iOS 4.3. I've got a compilation error on XCode, but everything is OK on MSVS 2010 under Windows. There are actually some differences in #include'ing headers of “stable” libraries (Cocos2d-x, Loki, Boost, STL) in precompiled header in Visual C++ and prefix header in XCode.

**Comment by qbit86** [comment]
Probable steps to reproduce (have not checked yet):
1) Create XCode project with Cocos2d-x template. Source code of Cocos2d-x will be included in xcodeproj directly. Therefore prefix header will be implicitly added to every compilation unit.
2) Edit Prefix.pch:

<pre>#ifdef __OBJC__
    #import &lt;Foundation/Foundation.h>
    #import &lt;UIKit/UIKit.h>
#elif defined __cplusplus
    #include &lt;functional>
#endif</pre>

3) Try to build.

**Comment by donaldalanmorrison** [comment]
<pre>
@Qbit86 : That PCH file is incorrect.  Both __OBJC__ and __cplusplus are both defined when a .cpp or .mm file is compiled. 
In other words, the conditions should be nested, instead of being disjunct.
</pre>

**Comment by godyZ** [comment]
@Qbit86 Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August
