### ISSUE TITLE
SimpleAudioEngine on Linux port

### ISSUE THREAD

**Issue by xal** [cocos2d/cocos2d-x#689]
While try to play background music on linux port

``` c++
SimpleAudioEngine::sharedEngine()->playBackgroundMusic("background.wav", true);
```

Nothing happens

But, when i play effect

``` c++
 SimpleAudioEngine::sharedEngine()->playEffect("move.wav");
```

It's played twice

I try other sound format's and but nothing has changed.
Also I add this code before play sound 

``` c++
SimpleAudioEngine::sharedEngine()->preloadEffect("move.wav");
SimpleAudioEngine::sharedEngine()->preloadBackgroundMusic("background.wav");
```

Nothing has changed too.

I compile and run same project on win32 it's work perfectly.

MySystem : Linux Mint 11 x32 (based on Ubuntu 11.04)
cocos2d : latest release from github

**Comment by minggo** [comment]
Did you run CocosDenshionTest?

**Comment by xal** [comment]
Of course, I did.
I got same result, as in first post

**Comment by minggo** [comment]
Ok, I will test it.

**Comment by godyZ** [comment]
Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
