### ISSUE TITLE
Android, Build : Build dependencies using official tools and from source

### ISSUE THREAD

**Issue by folecr** [cocos2d/cocos2d-x#720]
Cocos2D-X on Android depends on the following external BINARY libraries :
- libxml2
- libjpeg
- libpng
  
  ... also due to the current build system it automatically incorporates
- some Crystax libraries
- libiconv
- unneeded portions of libjpeg in the prebuilt binaries

This needs to be fixed.
## Explanation

Currently external depenencies are built using Crystax's toolchain and distributed as prebuilt binaries.
Reasons :
1. There are no distributable makefiles in the Cocos sources for these dependencies
2. For a long time Android did not support C++ fully
3. It is assumed that the build time will be very long (possibly because of Android's poor build sytem)
### The fix is now possible because Android NDK has
- Better makefiles
- Better C++ support
## Suggested fix
1. Modularize the Android NDK makefiles
2. Add Cocos2dx/Android specific makefiles to external dependencies
3. Fork a correct version of external depenencies to Cocos2D's github
4. Build external dependencies from source
5. Use standard toolchain
6. Remove depenency on 3rd-party toolchain
7. Prove that compile time is reasonable (so that it is possible to distribute as source)

**Comment by folecr** [comment]
I'll submit a pull request to fix these issues. I currently have the fix and successfully building HelloWorld.
I am testing HelloLua.

**Comment by folecr** [comment]
Here are the source repositories for the dependencies

#### libxml2
- https://github.com/folecr/platform_external_libxml2
- Note : uses an old version of libxml2 that does not depend on iconv or icu4c

#### libpng
- https://github.com/folecr/platform_external_libpng
- Version used by Android Gingerbread with modified makefiles

#### libjpeg
- https://github.com/folecr/jpeg8d
- Newer version than that used by Android Gingerbread
- Cocos2D-x uses functions that are available in latest version so I used this version instead of hacking the old

**Comment by minggo** [comment]
Great.
I think we should use prebuilt lib as default to reduce build time.
We also provide resource code for those who want to build from source code.

What's your opinion?

**Comment by folecr** [comment]
I will commit changes and let you decide : I did not see significant
slowdown in build time.

On Feb 12, 2012, at 6:01 PM, minggo
reply@reply.github.com
wrote:

**Comment by folecr** [comment]
FYI, changes are here : https://github.com/folecr/cocos2d-x/tree/externals

I am tracking down a crash in libjpeg when running HelloLua. When I am satisfied that it is stable I will submit a pull request.

**Comment by minggo** [comment]
Ok, thank you.

**Comment by folecr** [comment]
BTW, where can I find the scripts/makefiles used to build the currently used binary libraries? I want to check the build flags used. Thanks.

**Comment by minggo** [comment]
You can refer HelloWorld/android/build_native.sh.

**Comment by folecr** [comment]
I have submitted a pull request.

> You can refer HelloWorld/android/build_native.sh.

Thanks - that only builds from prebuilt binaries. I wanted to check what the original flags and options were to generate the binaries.
