### ISSUE TITLE
Missing "return" in CocosDenshion method for android

### ISSUE THREAD

**Issue by pyrosphere** [cocos2d/cocos2d-x#745]
The method getEffectsVolume in CocosDenshion/android/SimpleAudioEngine.cpp is missing the return.

float SimpleAudioEngine::getEffectsVolume()
{
    getEffectsVolumeJNI();
}

**Comment by dumganhar** [comment]
Hi, pyrosphere
The bug was fixed, refer to https://github.com/cocos2d/cocos2d-x/pull/746.
Thanks for your feedback. :)
