### ISSUE TITLE
Wrong directory name in linux makefiles

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#757]
In CocosDenshion/proj.linux and cocos2dx/proj.linux, there are two places each where the "linux" directory is referenced as "Linux", preventing ./build-linux.sh from competing.

../platform/Linux/CCAplication_linux.o \
../platform/Linux/CCEGLView_linux.o \

OBJECTS =   ../Linux/FmodAudioPlayer.o \
                        ../Linux/SimpleAudioEngine.o

**Comment by minggo** [comment]
Thank you, we will fix it.
Because we share file between windows and linux, so it doesn't check the capitalization.
