### ISSUE TITLE
Linux 64-bit needs correct lib and header files

### ISSUE THREAD

**Issue by rajeebk** [cocos2d/cocos2d-x#776]
build-linux.sh doesn't copy the correct CocosDenshion fmod library for 64-bit. It should detect 64-bit and copy CocosDenshion/third_party/linux/fmod/lib64/api/lib/_-_.so files. It also needs to create a symlink for each of them on the fly, since the zip archive doesn't save proper symlink files (they extract to regular files libfmodex64.so and libfmodexL64.so).

The header files for 3rd party are still in 32-bit mode. For example, cocos2dx/platform/third_party/linux/curl/curbuild.h has wrong SIZEOF values.

**Comment by ivzave** [comment]
Eclipse project files provided do not support 64-bit. I think 2 new configurations need to be added (e.g. Debug64 and Release64).

**Comment by ivzave** [comment]
I suppose it's fixed now in #1777.
