### ISSUE TITLE
CC_SYNTHESIZE.* not working with CC.*Dictionary

### ISSUE THREAD

**Issue by Zakay** [cocos2d/cocos2d-x#785]
CC_SYNTHESIZE_READONLY(CCMutableDictionary<std::string, CCObject *> *, dict, Dict);
Yeilds error:
"too many arguments provided to function-like macro invocation"

**Comment by l4u** [comment]
This is an issue of c++ macros.
Assume you are using int for key and string for value.

typedef CCMutableDictionary<int, string> \* dictType;
CC_SYNTHESIZE(dictType, dict, Dict);

**Comment by Zakay** [comment]
Yeah, that was the way I solved it. I though it was fixable in the macros, thats why I reported.

**Comment by donaldalanmorrison** [comment]
This issue can be closed "as designed".

http://stackoverflow.com/questions/608409/select-template-argument-at-runtime-in-c

**Comment by donaldalanmorrison** [comment]
I can't close the issue myself....maybe adding @walzer will help :-)

**Comment by godyZ** [comment]
@Zakay Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2688
