### ISSUE TITLE
Button doesn’t work when only Title was set

### ISSUE THREAD

**Issue by darkdukey** [cocos2d/cocos2d-x#7960]
The following code won't trigger button callback, also won't calculate `contentSize` correctly

``` cpp
auto b = Button::create();
b->setNormalizedPosition(Vec2(0.5, 0.3));
b->setTitleText("PLAY GAME");
b->setPressedActionEnabled(true);
b->setTouchEnabled(true);
b->addTouchEventListener([this](Ref* sender, TouchEventType eventType) {
    CCLOG("touched!");
});
this->addChild(b);
```

Here is the [forum link](http://discuss.cocos2d-x.org/t/resolved-ccui-button-doesnt-activate-on-touched/16481)

**Comment by minggo** [comment]
@andyque
Will you take a look.

**Comment by zilongshanren** [comment]
@minggo OK, I will take a loot at it.

**Comment by zilongshanren** [comment]
@darkdukey 
Yes, it is a bug. I will fix it later.

**Comment by zilongshanren** [comment]
@darkdukey 
I have fixed the bug. I think this issue could be closed now.
