### ISSUE TITLE
To close the event on the ccui.TextField IME distribution problem

### ISSUE THREAD

**Issue by rplees** [cocos2d/cocos2d-x#7977]
Description:
When I test is when you open a IME second times will distribute off - "open two events,
The first close any close event and then after each time you open ime will distribute the opening and closing of two events.
Version: js3.0 RC2
Test environment: Android Samsung 9300

**Comment by minggo** [comment]
Please use English in future, thanks.

**Comment by minggo** [comment]
@andyque
Could you please take a look this issue.
Thanks.

**Comment by zilongshanren** [comment]
@rplees  It should be fixed now.
If it still exists, feel free to reopen.
