### ISSUE TITLE
Using cocos3.2  ,Can't build Project with cmakelist.txt

### ISSUE THREAD

**Issue by chenleijava** [cocos2d/cocos2d-x#8004]
hi cocos team ,  on windows ,using mingw and cmake ,i try to build project ,but faild.
IDE  is  CLion. there some errors report:

![make](https://cloud.githubusercontent.com/assets/3043963/4229767/2bd80afa-3978-11e4-98b9-5a19e7455db5.png)

please tracking it  ,thanks a lot.

**Comment by minggo** [comment]
We now support CMake on linux. Other platforms will be supported in v3.4. And if we want to support CMake on windows, we will not want to support mingw, we will use CMake to generate VS project.

**Comment by chenleijava** [comment]
@minggo  got it ,thanks!

**Comment by minggo** [comment]
You are welcome.
It is great to support as many platforms  as possible, but we are limited in human resource.
