### ISSUE TITLE
Install cocos2d-x v3.3 on Ubuntu 14.04

### ISSUE THREAD

**Issue by sysads** [cocos2d/cocos2d-x#8024]
Hi

I have tried to follow the install steps but nothing seems to happen when I run cocos. no command 'cocos'. The install steps are not clear, anyone able to provide me with the exact installation steps? I see run this ./install-deps-linux.sh and also see run this 'download-deps.py'.

So I am confused on the right steps

**Comment by sysads** [comment]
anyone with any idea on how to run this on ubuntu 14.04

**Comment by felixjingga** [comment]
Hi, have you installed python? if you already installed python, you can use "python download-deps.py" to initiate the download..

**Comment by sysads** [comment]
Hi @felixjingga 

I already did that but what next. How do I run it. Thanks

**Comment by felixjingga** [comment]
@sysads 
you can do that by running the command in the terminal (command line) like you do the sudo things etc.

**Comment by zilongshanren** [comment]
@sysads 
I think the README of Cocos2D-X repository is a good start point for your to run tests on Ubuntu.

**Comment by minggo** [comment]
@sysads 
Have you fixed you issue?

**Comment by sysads** [comment]
no luck yet. the instruction isn't clear and confusing.

**Comment by minggo** [comment]
What's the error you met?
Could you describe what you did step by step and paste the error message?

**Comment by minggo** [comment]
@sysads 
Have you resolved your problem?

**Comment by sysads** [comment]
sorry been working on other builds. This is what I have done so far:

sudo apt-get install git
git clone https://github.com/cocos2d/cocos2d-x.git
cd cocos2d-x/build
./install-deps-linux.sh

what next should i do?

**Comment by minggo** [comment]
python ./download-deps.py
git submodule update --init
cd build
cmake ..
make

Then you will see a folder named `bin` which includes all tests.

**Comment by sysads** [comment]
its still running make so will wait till it finishes but thanks for the steps

**Comment by minggo** [comment]
It will build all tests.
You can also use 
`make cpp-empty-test`
to just build one test.

**Comment by sysads** [comment]
Hi

Thanks so far with your help. Just one more question. How do I know what version of cocos2d-x was installed?

**Comment by minggo** [comment]
You can view it in `cocos/cocos2d.cpp`.
Can i close this issue?

**Comment by sysads** [comment]
Thanks
