### ISSUE TITLE
editbox bug in v3

### ISSUE THREAD

**Issue by dannyjiajia** [cocos2d/cocos2d-x#8073]
v3 的 editbox没有长度限制时 输入内容超过contentsize 然后取消输入焦点 文字会消失 应该是CCLabel的setDimensions函数bug
testcpp 项目中也存在这个bug

**Comment by zilongshanren** [comment]
@dannyjiajia 
文字不是消失了，而是被裁掉了，因为输入文本超过了 EditBox 的边界，设计如此。要么你把 EditBox 的宽度变大，要么把字体设置小一点。要么设置 maxLength.
