### ISSUE TITLE
Node:clipping -> Clipping to RenderTexture crash

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8076]
Step to reproduce the issue:
- run test-cpp
- enter `Node:clipping -> Clipping To RenderTexture`
- will crash sometimes on iOS and will 100% crash on Android

The problem is in this code

``` c++
auto button = MenuItemFont::create("Reproduce bug", [&](Ref *sender) {
        enumerateChildren("remove me [0-9]", [&](Node *node) {
            this->removeChild(node);
            this->reproduceBug();
            return false;
        }
                          );
    });
```

Invoke `removeChild()` and `addChild()`(invoked in `reproduceBug()`) in the callback of  `enumerateChildren()`. Because `enumerateChildren()` will iterate children, so it is not safe to remove or add a child.

@ricardoquesada 
I found you added the test case, and i don't know why you do it like this. 
Any idea?

**Comment by ricardoquesada** [comment]
You are correct. The test case will crash because of the `removeChild()`.
I can't remember why I added that code.
I won't be able to fix now, but feel free to comment the `removeChild()` out and add a comment saying why you commented out that line. thanks.

**Comment by minggo** [comment]
And it will invoke `addChild()` in `this->reproduceBug();`.
Can i comment it as `removeChild()`?

**Comment by minggo** [comment]
May be i know why you need to invoke `removeChild()`. Because `reproduceBug()` will add a container, if clicked `Reproduce bug` may times, the performance will be slow.

**Comment by minggo** [comment]
So may be you should not use `Node::enumerateChildren to remove a child`, should use tag to add/remove a child here.

**Comment by minggo** [comment]
@ricardoquesada 
If you are agree with it.
I will modify it as i mentioned above.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8824
