### ISSUE TITLE
EditBox::setFontSize shouldn't rely on font name property

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#8090]
![lr5 n28 z t jz22 31n](https://cloud.githubusercontent.com/assets/632460/4301845/978f9b70-3e53-11e4-9493-f28b1adc8726.jpg)

In EditBox's setFontSize function, it checks whether user set the font name or not. But it's possible that users just want to use the default font, and simply set the size, then they will find it not possible to do.

I personally think it's a logic issue: the font size shouldn't have dependency on font name property.

**Comment by minggo** [comment]
@andyque
Could you please take a look?
Thanks.

**Comment by zilongshanren** [comment]
@minggo 
OK. I will check it later.

**Comment by zilongshanren** [comment]
it's fixed
