### ISSUE TITLE
sometimes vector will out of range when using 'addArmatureFileInfoAsync' on 3.2 release

### ISSUE THREAD

**Issue by kary24** [cocos2d/cocos2d-x#8104]
version: cocos2d-x 3.2 release
platform:windows 7 with VS2012
sometimes the program will crash and popup an error which means vector is out of range.but i cant get the breakpoint and debug info when i use debug-run. just popup the crash info frame.

**Comment by pandamicro** [comment]
Hi, @kary24 we can't reproduce the issue with such limited informations, please test our latest engine and provide detailed informations to help us reproduce the issue.
