### ISSUE TITLE
CMakeList error

### ISSUE THREAD

**Issue by whinc** [cocos2d/cocos2d-x#8105]
When i use QtCreator + CMakeList + VC++ to compile the cocos2d-x project. The compile occur a error:can not find header files  "CCPlatformDefine.h" .etc. So, i look up the included_directories() statement in CMakeList.txt, i find a error in it.

The Line 80~83 in CMakeList.txt is below:
  ${COCOS2D_ROOT}/cocos/2d/renderer
  ${COCOS2D_ROOT}/cocos/2d/platform
  ${COCOS2D_ROOT}/cocos/2d/platform/desktop
  ${COCOS2D_ROOT}/cocos/2d/platform/win32
But actually, there is no any directory named "platform" under directory "XX/cocos2d/cocos/2d . I search the missing header file and i find it in directory "XX/cocos2d/cocos", So the correct directories should be below(remove the directory litera "/2d"):
  ${COCOS2D_ROOT}/cocos/renderer
  ${COCOS2D_ROOT}/cocos/platform
  ${COCOS2D_ROOT}/cocos/platform/desktop
  ${COCOS2D_ROOT}/cocos/platform/win32

**Comment by minggo** [comment]
What's the engine version?

**Comment by whinc** [comment]
version: cocos2d-x v3.2 
platform: window 7 + VS2013

**Comment by whinc** [comment]
It is OK if i use VS2013  open the solution  generated by CMake.

**Comment by minggo** [comment]
Will you try latest github codes?

**Comment by whinc** [comment]
I will try it latter. No matter this question if still exist, i will reply you.

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
Any update?

**Comment by whinc** [comment]
Today, i update cocos2d-x to version 3.3 alpha. In this version, i find i can not build directly from CMakeList.txt on window platform. CMake error:
"CMake Error at cocos2d/cocos/CMakeLists.txt:436 (message):
  Unsupported platform, CMake will exit"

Locate the error location(below), i find the configuration support only "LINUX" and "MACOSX" exclude "WINDOWS". There many places like this situation in file "cocos2d/cocos/CMakeLists.txt".
if(LINUX)
    set(COCOS2D_PLATFORM_SRC
        ${COCOS2D_DESKTOP_SRC}
        platform/linux/CCApplication-linux.cpp
        platform/linux/CCCommon-linux.cpp
        platform/linux/CCDevice-linux.cpp
        platform/linux/CCFileUtils-linux.cpp
        platform/linux/CCStdC-linux.cpp
    )
elseif(MACOSX)
    set(COCOS2D_PLATFORM_SRC
        ${COCOS2D_DESKTOP_SRC}
        platform/mac/CCApplication-mac.mm
        platform/mac/CCCommon-mac.mm
        platform/mac/CCDevice-mac.mm
        platform/apple/CCLock-apple.cpp
        platform/apple/CCFileUtils-apple.mm
        platform/apple/CCThread-apple.mm
        )
else()
    message( FATAL_ERROR "Unsupported architecture, CMake will exit" )
endif()

I urgent hope cocos2d-x can support QtCreator IDE, becault it can build directly from CMakeList.txt and it is a corss-platform IDE wirtten in C++, so it is fast and friendly to C++ programer.

**Comment by minggo** [comment]
Please refer to this thread: http://discuss.cocos2d-x.org/t/cmake-for-mac-qtcreator-and-clion/16889/36.

**Comment by minggo** [comment]
Will support Cmake on all platforms next version.

**Comment by whinc** [comment]
soga, I will expect.

**Comment by minggo** [comment]
So can i close this issue since it is not supported right now.
