### ISSUE TITLE
Contact Test in "Node: Physics" test suite crashes after a few taps on the plus sign

### ISSUE THREAD

**Issue by SvDyer** [cocos2d/cocos2d-x#8140]
Issues occurs in v3 branch (tried on Samsung Galaxy S III, SPH-L710, Android 4.3)

Steps:
1. Run CppTest > "Node: Physics" test suite > Contact Test
2.  Tap on the '+' sign about 20 times (sometimes fewer taps would do it too if done fast) 

Result: Test fails, CppTests app crashes

**Comment by minggo** [comment]
@Dhilan007 
Could you please take a look.
Thanks.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8209
