### ISSUE TITLE
LuaMinXmlHttpRequest can not get error message if failed to connect network

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8142]

**Comment by samuele3hu** [comment]
When LuaMinXmlHttpRequest fails to connect network, it would output the log in the console as follow:
`cocos2d: Response failed, error buffer: Connection timed out after 30132 milliseconds`

**Comment by samuele3hu** [comment]
Add callback when connect network,the related pr is at https://github.com/cocos2d/cocos2d-x/pull/8868
