### ISSUE TITLE
.fnt file doesn't work as expected without double quotes in the png file name

### ISSUE THREAD

**Issue by claudiofreitas** [cocos2d/cocos2d-x#8150]
When the instruction on .fnt file in which .png file to read from is written without double quotes, the program fails to find the png file in the path. It actually uses a wrong full path.

.fnt partial content:
`page id=0 file=numbers_font.png`

Error message:

```
cocos2d: cocos2d: fullPathForFilename: No file found at fonts/page id=0 file=numbers_font.png. Possible missing file.
cocos2d: Get data from file(fonts/page id=0 file=numbers_font.png) failed!
```

It considers the whole line as the path.

Updating it to `page id=0 file="numbers_font.png"` solved my problem.

Please, refer to this post for more info:
http://discuss.cocos2d-x.org/t/solved-labelbmfont-doesnt-appear-on-ios-no-file-found-at-possible-missing-file/17240/3

**Comment by minggo** [comment]
Thanks, we will take a look.
.fnt file is generated by some tools, does output form the tool doesn't include " " for png file name?

**Comment by claudiofreitas** [comment]
I'm sorry. I just checked it now and the program (ShoeBox) generates it with " ", but it includes the full directory name from my computer (eg.: "/Users/claudiofreitas/Desktop/font.png").

I don't know if the double quotes are always expected, so I might have removed them when I changed the full path to just the file name of the png file.

If they are always expected, then this issue doesn't exist. Sorry.

But it is still kind of weird for cocos to detect the whole line "`page id=0 file=numbers_font.png`" as the full path of the png file...

**Comment by minggo** [comment]
Yep, i think it is needed. Because we haven't received similar issue.

**Comment by claudiofreitas** [comment]
Ok. I'll close the issue then.
Sorry for not checking it before.

**Comment by minggo** [comment]
No problem.
