### ISSUE TITLE
Random Crash in Android Device because of LuaJIT, please update it.

### ISSUE THREAD

**Issue by yestein** [cocos2d/cocos2d-x#8154]
My App random crashed on Android Device. And I found the crash happnes in LuaJIT,so I try to update my LuaJIT to 2.0.3 from 2.0.1. And the Crash no longer happens until now.

**Comment by minggo** [comment]
Thanks for the information.
We will update it.

**Comment by minggo** [comment]
And could you paste some example codes that will cause crash?
Thanks.

**Comment by dualface** [comment]
It's a bug of LuaJIT 2.0.1, please upgrade to LuaJIT 2.0.3.

**Comment by minggo** [comment]
Thanks.
What's the error?
Is there any document in luagit mentioned it?
I want to know it because i will write it in changlog to mention it.

**Comment by dualface** [comment]
Sorry, this bug remained exists. we must turn off JIT on Android.

Bug report: http://comments.gmane.org/gmane.comp.lang.lua.luajit/2133

Maybe fix in next release of LuaJIT.

**Comment by yestein** [comment]
I do not know the real reason of crash. I found this problem when I developed on windows, it random crash in LuaJIT, so I try to upgrade it on windows, and the problem is resolved, but it remains on Android, so I try to upgrade it on Android, it is resolved too. And Here is my record about this problem:
http://wp.me/p1ilbZ-bA

**Comment by dualface** [comment]
Latest LuaJIT fixed many bugs. We need upgrade.

**Comment by samuele3hu** [comment]
Yes,I will update the LuaJIT in this version.

**Comment by minggo** [comment]
@dualface 
Yep, we need to update.
Did you mean jit can not be turn on on Android even we update.

**Comment by dumganhar** [comment]
dualface has sent a PR for this: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/52
@minggo , how about to merge it ?
