### ISSUE TITLE
GLContextAttrs glContextAttrs = {8, 8, 8, 8, 24, 8}; do not work on old android phones

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#8160]

**Comment by minggo** [comment]
Please refer to #8157 for detail information.
So we should disable it by default.

And please add comment to describe why we disable it by default and paste the link of this issue url.

**Comment by minggo** [comment]
Have confirmed it on g10.

**Comment by edwardzhou** [comment]
ZTE U970 crash too on this config.
after changed to 
GLContextAttrs glContextAttrs = {5, 6, 5, 0, 16, 8};

it works fine.

**Comment by minggo** [comment]
@edwardzhou 
Thanks for your feedback.
I think engine should check if the device supports stencil buffer or not, if not support, should:
- disable stencil buffer automatically
- print a warning to say that stencil buffer is not support

**Comment by edwardzhou** [comment]
nice feature~.

Cocos GUI is very dependent on Stencil.

**Comment by hamburml** [comment]
I am sorry but I really need to ask. Is the stencil buffer stuff added with v3.3? I am just asking because v3.2 was fine and we had no problems. To read that Cocos GUI is very dependent on Stencil is a bit strange or did you change something?

**Comment by minggo** [comment]
@Michael-Hamburger 
The problem is that, stencil buffer is enabled by default: https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-empty-test/Classes/AppDelegate.cpp#L24 in v3.3.

**Comment by hamburml** [comment]
Yes, I know that. I meant the "Cocos GUI is very dependent on Stencil." When something is added in v3.3 which is just beta and not official released I can't see the dependency.

**Comment by minggo** [comment]
TableView uses stencil buffer(ClippingNode), it is not a new feature.

**Comment by hamburml** [comment]
Okay, but that means that in 3.2 stencil buffer was added/created when TableView is used? I don't want to annoy someone but the http://en.wikibooks.org/wiki/OpenGL_Programming/Stencil_buffer#Limitations clearly says that 24 bit depth and 8 bit stencil is not supported in OpenGL ES 2.0. That doesn't mean that the device doesn't support stencil buffer in general. Right? Just pointing that out. (edwardzhou said that 16 bit depth and 8 bit stencil worked. Shouldn't that be the default?)

**Comment by minggo** [comment]
No, in v3.2, stencil buffer is not enabled by default. 
Because stencil buffer should be enabled when creating GL context, which means you should enable it by yourself in v3.2.

**Comment by hamburml** [comment]
Ahh, Thanks! Got it.

**Comment by dabingnn** [comment]
It seems the pull request #8172 would not work on meizu 3.
It is very strange.

**Comment by dabingnn** [comment]
Pull request #8599 fixed meizu3 bug
