### ISSUE TITLE
Animation中关于_totalDelayUnits的问题

### ISSUE THREAD

**Issue by xiedantibu** [cocos2d/cocos2d-x#8161]
在Animation方法initWithAnimationFrames中有这么一句话 _totalDelayUnits += animFrame->getDelayUnits();

这里可能写的笔误应该改为_totalDelayUnits++；

**Comment by yangws** [comment]
```
    for (auto& animFrame : _frames)
    {
        _totalDelayUnits += animFrame->getDelayUnits();
    }
```

The codes iterate all frames, every frame may be have different delay units, which is a member field in class AnimationFrame. The codes is correct:)
