### ISSUE TITLE
[cocos2d-x-3.3beta0] Wrong includes in lots/all of cocostudio-classes?

### ISSUE THREAD

**Issue by hamburml** [cocos2d/cocos2d-x#8163]
Hi.

I just tried cocos2d-x-3.3beta0 and wanted to use the CCArmatureDataManager. I included it and got linker-error (no such file or directory) in CCArmatureDataManager.h". 

All cocostudio-classes include other cocostudio-files with cocostudio/ as prefix. I think that's wrong now, right? We now have only libcocos2d and due to that we don't have libcocostudio anymore. I removed cocostudio/ prefix from all includes I have found in libcocos2d/cocostudio/\* and now it works.

FYI: In CCDisplayFactory.h the CocosStudioExport.h is included two times.

**Comment by minggo** [comment]
@Michael-Hamburger 
Could you describe how to reproduce it step by step?

**Comment by minggo** [comment]
And what's the platform you tested on?

**Comment by hamburml** [comment]
Win 8.1 x64 VS2013 Express

Create a new cocos2d-x3.3beta0 project with cocos console.
Open *.sln and add #include "editor-support/cocostudio/CCArmature.h"
Build the project. Aaaand Error that "cocostudio/CCArmatureDefine.h" can't be found (which is included in CCArmature.h"

**Comment by minggo** [comment]
@Michael-Hamburger 
Thanks.

@andyque 
Could you please check it?
Thanks.

**Comment by hamburml** [comment]
Instead of removing the cocostudio prefix from all files it's also possible to add
$(EngineRoot)cocos\editor-support;
as include-directory in VS 2013. Just wanted to say that.

**Comment by zilongshanren** [comment]
@Michael-Hamburger 
I think you should include "cocostudio/CocoStudio.h" instead of "editor-support/cocostudio/CCArmature.h".
It is the same you should include "cocos2d.h" rather than "cocos/2d/CCSprite.h" for using the Sprite class.

**Comment by hamburml** [comment]
@andyque VS2013 Error: "cocostudio/CocoStudio.h": No such file or directory.
I searched the CocoStudio.h inside the libcocos2d-project and found it under libcocos2d/cocostudio/json.
Is that the right place for it?

Should I provide an example repository?

**Comment by zilongshanren** [comment]
@Michael-Hamburger 
The file "cocostudio/CocoStudio.h" is under "cocos/editor-support/cocostudio/" directory.

**Comment by hamburml** [comment]
@andyque I know where it's located. I just wanted to try "cocostudio/CocoStudio.h". Look here pls https://github.com/Michael-Hamburger/cocosstudiococos2d-xbug Pull the project, copy cocos2d folder or run download cocos2d.sh, open cocosstudiobug.sln with VS 2013 and build it.
I also added a comment in the HelloWorldScene.cpp next to the #include.

**Comment by zilongshanren** [comment]
@Michael-Hamburger  Ok, I will take a loot at it.
Thanks for your patient.

**Comment by zilongshanren** [comment]
@Michael-Hamburger 
Thanks very much.
I have cloned your test repo and we could fix this issue by adding `$(EngineRoot)cocos\editor-support;` to the search path of VS 2013. 

In fact, other project settings(Like Xcode) also set this path in the include path.

 I will send a PR later to fix this issue.
After that, please help me to verify the correctness.
Thanks:)

**Comment by zilongshanren** [comment]
@Michael-Hamburger 
Here is the [PR](https://github.com/cocos2d/cocos2d-x/pull/8610)
