### ISSUE TITLE
使用UI动画导致内存泄露问题..

### ISSUE THREAD

**Issue by jackie7788** [cocos2d/cocos2d-x#8186]
从3.0版本开始到3.2正式版发布.UI动画导致的内存泄露一直存在.望尽快解决
说明:
使用Cocos Studio 1.6.0->UI编译->对一个UI制作动画(这里无所谓是否勾选重复播放)->带入Json,运行程序->就会出现大量的内存泄露.
其他:
我检查过很多次.也搞过很久.但是都未找到解决办法.大致原因应该是 添加的UI动画帧因为某种原因有的被多retain() > 1 次,最后就产生了这样的泄露.这里我提交下内存泄露的Log,望尽快解决.谢谢.如果可以,解决后新版本周知一下.(PS:本人英文的确不好,故只能中文发表.请勿介意.谢谢)
Bug Log:
Leaked object at 0EC548C8 (size 56, CCActionInterval.cp:1937)
Leaked object at 0EC54830 (size 56, CCActionInterval.cp:1937)
Leaked object at 0EC54960 (size 64, CCActionInterval.cp:158)
Leaked object at 0EC54AA0 (size 64, CCActionInterval.cp:158)
Leaked object at 0EC54A00 (size 64, CCActionInterval.cp:158)
Leaked object at 0EC54B40 (size 64, CCActionInterval.cp:158)
Leaked object at 0EC54FC0 (size 56, CCActionInterval.cp:638)
Leaked object at 0EC550F0 (size 56, CCActionInterval.cp:638)
Leaked object at 0EC55058 (size 56, CCActionInterval.cp:638)
Leaked object at 0EC55188 (size 56, CCActionInterval.cp:638)
Leaked object at 0EC699D8 (size 56, CCActionInterval.cp:638)
Leaked object at 0EC69A70 (size 56, CCActionInterval.cp:638)
Leaked object at 0EC69BA0 (size 56, CCActionInterval.cp:638)
Leaked object at 0EC69B08 (size 56, CCActionInterval.cp:638)
Leaked object at 0ED09390 (size 80, CCActionInterval.cp:1080)
Find in -> Line = 128 -> Size = 8596

其实很多,这里只是一部分...

**Comment by joewan** [comment]
最好是能提供有问题的资源。
可以尝试解决一下。

------------------ 原始邮件 ------------------
发件人: "jackie7788";notifications@github.com;
发送时间: 2014年9月28日(星期天) 中午11:41
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 

主题: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

从3.0开始到3.2正式版发布.UI动画导致的内存泄露一直存在.望尽快解决
 实现:
 使用Cocos Studio ->UI编译->调整一个动画(这里无所谓是否勾选重复播放)->带入Json,运行程序->就会出现大量的内存泄露.
 我检查过很多次.也搞过很久.但是都未找到解决办法.大致原因应该是

**Comment by minggo** [comment]
Please use English in future, guys.
Thanks.

**Comment by jackie7788** [comment]
Resource file In ‍attachment , ‍Please find.thx.‍
If the modification is convenient. Please let us know, I need to be modified. Wait for the next version afraid ihave time . ‍Thank you very much.‍

------------------ 原始邮件 ------------------
发件人: "minggo";notifications@github.com;
发送时间: 2014年9月28日(星期天) 下午4:06
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

Please use English in future, guys.
 Thanks.

**Comment by minggo** [comment]
@chengstory
Could you please take a look.
Thanks.

**Comment by jackie7788** [comment]
What? Didn't understand.Can you give a complete combo address? thx

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月28日(星期天) 下午4:54
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

@chengstory
Could you please take a look.
Thanks.

**Comment by minggo** [comment]
@jackie7788 
What's the matter?

**Comment by jackie7788** [comment]
you said "Could you please take a look."

 i say "I didn't understand what you mean."

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月28日(星期天) 下午5:06
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

@jackie7788 
What's the matter?

**Comment by minggo** [comment]
Sorry, i asked @chengstory to take a look.

**Comment by jackie7788** [comment]
Sorry,I understand the wrong.hehe.
 By the way, UI animation dislocation  Ver 3.3 beta0 solved?

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月28日(星期天) 下午5:11
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

Sorry, i asked @chengstory to take a look.

**Comment by minggo** [comment]
I am not sure.
So i asked @chengstory to take a look.

**Comment by jackie7788** [comment]
OK.thx
 There is a place I want to say, too. Ver 3.3 also exist. But don't know whether I Bug.  Detect here also has a memory leak
1. cocostudio\WidgetReader didn't release all the singleton pattern in the last, I was using instance CheckBoxReader - > autorelease ().
2.  buffer = (unsigned char*)malloc() Use the CC_SAFE_DELETE (). Where exactly?I also forgot. Please check it.

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月28日(星期天) 下午5:23
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

I am not sure.
So i asked @chengstory to take a look.

**Comment by jackie7788** [comment]
Other all wish cocos2d-x 3d function is more and more complete. Early launch Cocos Studio 3d, I will always support the cocos2d-x and your team.

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月28日(星期天) 下午5:23
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

I am not sure.
So i asked @chengstory to take a look.

**Comment by jackie7788** [comment]
If UI animation dislocation 3.3 OK, please tell me. I am good to replace version. If not. I only  delete this animations. Thank you

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月28日(星期天) 下午5:23
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

I am not sure.
So i asked @chengstory to take a look.

**Comment by minggo** [comment]
Sure.
We will update it here.

**Comment by jackie7788** [comment]
The UI animation memory leak problem be solved?

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月28日(星期天) 晚上6:51
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

Sure.
 We will update it here.

**Comment by minggo** [comment]
I have asked cocos studio guys to help.
They may be too busy to response it.
Sorry about it.

**Comment by jackie7788** [comment]
That's ok, if there are any news. Please let us know. Thank you

------------------ 原始邮件 ------------------
发件人: "minggo"notifications@github.com; 
发送时间: 2014年9月30日(星期二) 中午12:04
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

I have asked cocos studio guys to help.
 They may be too busy to response it.
 Sorry about it.

**Comment by minggo** [comment]
I will.

**Comment by chengstory** [comment]
I asked @2youyou2 to take a look.

**Comment by chengstory** [comment]
Sorry, I asked @liamcindy to take a look.

**Comment by jackie7788** [comment]
Hi,Animation memory leak problem solving?

------------------ 原始邮件 ------------------
发件人: "cheng.zhang"notifications@github.com; 
发送时间: 2014年9月30日(星期二) 下午2:49
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

Sorry, I asked @liamcindy to take a look.

**Comment by jackie7788** [comment]
cocos2d-x 3.3 RC0  Memory leaks solves the UI animation? thx

------------------ 原始邮件 ------------------
发件人: "cheng.zhang"notifications@github.com; 
发送时间: 2014年9月30日(星期二) 下午2:49
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "等待→缘份"21196183@qq.com; 
主题: Re: [cocos2d-x] 使用UI动画导致内存泄露问题.. (#8186)

Sorry, I asked @liamcindy to take a look.

**Comment by zilongshanren** [comment]
@chengstory  Any updates?

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
