### ISSUE TITLE
about CCRenderTexture and CCClippingNode

### ISSUE THREAD

**Issue by SnowStorms** [cocos2d/cocos2d-x#8220]
一旦CCRenderTexture的绘制包含了任何裁剪控件相关的节点，那么CCRenderTexture的绘制结果就会出错：多了一个全屏白色、裁剪失效、白色层覆盖了其他节点。

错误产生的原因应该是clipping的visit  用于裁剪的全屏白色也被绘制到了render里

**Comment by minggo** [comment]
We only fix critical bugs in v2.x.
And please use english in future.

Thanks.
