### ISSUE TITLE
Editbox emojis scale down

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8225]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/2845). It was created at 2013/09/25 07:36:10 +0000
# Description

When I tap on an editbox, the keyboard appears and I introduce a few emojis that display correctly. But when the keyboard disappears the emojis scale down. The same happens if I introduce the emojis programatically and I disable the editbox.

**Comment by yangws** [comment]
Test engine version 3.7 on android and ios devices:  emojis displayed correct in edit box.
![android](https://cloud.githubusercontent.com/assets/488183/8450778/71243b04-2010-11e5-8ea1-94edfcfe02f1.png)
![ios](https://cloud.githubusercontent.com/assets/488183/8450777/70c90a0e-2010-11e5-997e-93a6fc1d8923.png)

**Comment by minggo** [comment]
@yangws Good job.
Thanks.
