### ISSUE TITLE
CCHttpClient - Time Out 

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8227]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/2876). It was created at 2013/10/02 09:42:44 +0000
# Description

I have noticed that the Time Out when the method CCHttpClient::getInstance()->send(request) is called is not working at all, even when I change the timeout it does not change the time that the game is stuck. I have tested on Samsung Galaxy S2 and Galaxy Nexus.

**Comment by pandamicro** [comment]
v2 bugs will be closed, we won't have time for testing or any fix.
