### ISSUE TITLE
CCSpriteFrameCache + CCTextureCache addImage Bug

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8228]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/2877). It was created at 2013/10/02 19:06:06 +0000
# Description

When using CCSpriteFrameCache addSpriteFramesWithFile and CCTextureCache addImage method, pre existing texture can be corrupted.

How to reproduce this bug:
1. Create a new project in cocos2d-x (I confirmed this bug exist in 2.1.5 and 2.2, don’t know about version < 2.1.5)
2. Make a simple generated PVR file (test.plist and test.pvr) using texture packer (in this case I generate the test.pvr using the cocos2d-x HelloWorld.png)
3. Add that files (test.plist and test.pvr) to the resource.
4. In the HelloWorldScene.cpp, in the init() method, comment all other code and make it like this

```
bool HelloWorld::init()
{
    //////////////////////////////
    // 1. super init first
    if ( !CCLayer::init() )
    {
        return false;
    }
    CCTexture2D::PVRImagesHavePremultipliedAlpha(true);
    CCSpriteFrameCache::sharedSpriteFrameCache()->addSpriteFramesWithFile("test.plist");
    return true;
}
```
1. After that, run the project in the simulator, and you will notice that the fps texture is corrupted.

It’s not only PVR files that affected but also pvr.ccz files.
# Comments
- KingHu added comment:
  Fun Dev wrote:
  > When using CCSpriteFrameCache addSpriteFramesWithFile and CCTextureCache addImage method, pre existing texture can be corrupted.
  > 
  > How to reproduce this bug:
  > 1. Create a new project in cocos2d-x (I confirmed this bug exist in 2.1.5 and 2.2, don’t know about version < 2.1.5)
  > 2. Make a simple generated PVR file (test.plist and test.pvr) using texture packer (in this case I generate the test.pvr using the cocos2d-x HelloWorld.png)
  > 3. Add that files (test.plist and test.pvr) to the resource.
  > 4. In the HelloWorldScene.cpp, in the init() method, comment all other code and make it like this
  > 
  >     bool HelloWorld::init()
  >     {
  >         //////////////////////////////
  >         // 1. super init first
  >         if ( !CCLayer::init() )
  >         {
  >             return false;
  >         }
  >         CCTexture2D::PVRImagesHavePremultipliedAlpha(true);
  >         CCSpriteFrameCache::sharedSpriteFrameCache()->addSpriteFramesWithFile("test.plist");
  >         return true;
  >     }
  > 
  > 5. After that, run the project in the simulator, and you will notice that the fps texture is corrupted.
  > 
  > It’s not only PVR files that affected but also pvr.ccz files.

Same bug for me (Sorry for my english). I am programing a game. Everything is fine except the Release version in iOS. Somebody said changing the Project->BuildSetting->Optimization Level would be okay. But nothing fixed after I changed the build setting & clean the products & rebuild the release version. After a few days debug (God! 2 days more!). I found the problem, here is the code:
`CCSpriteFrameCache::sharedSpriteFrameCache()->addSpriteFramesWithFile("test.plist");`
Adding a plist file to the CCSpriteFrameCache, it failed!, But when I execute the same code twice, it work!
`
CCSpriteFrameCache::sharedSpriteFrameCache()->addSpriteFramesWithFile("test.plist");
CCSpriteFrameCache::sharedSpriteFrameCache()->addSpriteFramesWithFile("test.plist");
`
Getting inside of the addSpriteFramesWithFile() fun, target line
`CCTexture2D *pTexture = CCTextureCache::sharedTextureCache()->addImage(texturePath.c_str());`
pTexture is null first time and not null second time.
This bug only happen in pvr format (also pvr.ccz). Please anyone tell me how to fix the problem!
- KingHu added comment:
  @Fun Dev, Thanks @Oren Bengigi, I find the answer here: 
  http://www.cocos2d-x.org/forums/6/topics/18390?r=43651
- thesp2 added comment:
  funkata wrote:
  
  > When using CCSpriteFrameCache addSpriteFramesWithFile and CCTextureCache addImage method, pre existing texture can be corrupted.
  > 
  > How to reproduce this bug:
  > 1. Create a new project in cocos2d-x (I confirmed this bug exist in 2.1.5 and 2.2, don’t know about version < 2.1.5)
  > 2. Make a simple generated PVR file (test.plist and test.pvr) using texture packer (in this case I generate the test.pvr using the cocos2d-x HelloWorld.png)
  > 3. Add that files (test.plist and test.pvr) to the resource.
  > 4. In the HelloWorldScene.cpp, in the init() method, comment all other code and make it like this
  > 
  > ```
  > bool HelloWorld::init()
  > {
  >     //////////////////////////////
  >     // 1. super init first
  >     if ( !CCLayer::init() )
  >     {
  >         return false;
  >     }
  >     CCTexture2D::PVRImagesHavePremultipliedAlpha(true);
  >     CCSpriteFrameCache::sharedSpriteFrameCache()->addSpriteFramesWithFile("test.plist");
  >     return true;
  > }
  > ```
  > 1. After that, run the project in the simulator, and you will notice that the fps texture is corrupted.
  > 
  > It’s not only PVR files that affected but also pvr.ccz files.

I encounter this problem, too!
cocos2d-x 2.1.5&2.2.3
And I suspect this problem also makes CCArmature display incorrect with PVR images!
- thesp2 added comment:
  I've solved the problem that CCArmature display incorrect with PVR images.
  TexturePacker must check the "Premultiply Alpha" option, and cpp must add line:

`CCTexture2D::PVRImagesHavePremultipliedAlpha(true);`

But FPS is still corrupted as @funkata said!

**Comment by yangws** [comment]
Test in engine version 3.7, can't reproduct this bug on v3.
![2015-07-02 15 16 24](https://cloud.githubusercontent.com/assets/488183/8471676/756bada6-20cd-11e5-89a9-5212d429d6b9.png)

**Comment by minggo** [comment]
Thanks @yangws .
