### ISSUE TITLE
HttpClient raised ANR error when the connected WIFI is disconnected from internet.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8229]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/2889). It was created at 2013/10/07 11:47:31 +0000
# Description

Antonio Cld reported a bug of CCHttpClient, I quote his email below

> The problem appears when the device is connected to WIFI, but the router has no connection to Internet, this causes a ANR when making a request. I also followed the tutorial in http://www.cocos2d-x.org/wiki/How\_to\_use\_CCHttpClient. I created an example uploaded on Git and posted on cocos2dx forum, but our client insists in solving this issue. https://github.com/antoniocid/test\_http
-   Platform: Android
-   Device: Is an Itermittent nature and may happen on any device. Most times that I seen is in Nexus S, furthermore in Android Emulator I can reproduce it always.
-   Android SDK Tools 22.0.1
-   Cocos2dx 2.1.5

**Comment by pandamicro** [comment]
v2 bugs will be closed, we won't have time for testing or any fix.
