### ISSUE TITLE
Uninitialized variables in extensions/CocoStudio/Reader/CCSGUIReader.cpp

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8234]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3021). It was created at 2013/10/21 20:32:37 +0000
# Description

In commit d02dfb3 from october 8th the variable dicHelper is initialized on line 99 and 200 as: `DictionaryHelper* dicHelper = dicHelper;`

This throws fatal error c4700 (Uninitialized local variable ‘dicHelper’ used) in Visual Studio 2012. Looking at the previous code, I believe/guess that the correct initialization should be: `DictionaryHelper* dicHelper = DICTOOL;`

**Comment by kompjoefriek** [comment]
I don't think this problem exists any longer. Current implementations of widgetFromJsonDictionary do not have this error.
Please see: /cocos/editor-support/cocostudio/CCSGUIReader.cpp line [534](https://github.com/cocos2d/cocos2d-x/blob/38b0d25bc5823f9a0bd4c8ad1f0effeaedbe86e0/cocos/editor-support/cocostudio/CCSGUIReader.cpp#L534) and [1449](https://github.com/cocos2d/cocos2d-x/blob/38b0d25bc5823f9a0bd4c8ad1f0effeaedbe86e0/cocos/editor-support/cocostudio/CCSGUIReader.cpp#L1449)
