### ISSUE TITLE
CCLabelTTF setFontName overwrites the default font

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8236]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3023). It was created at 2013/10/21 21:05:21 +0000
# Description

Hey, I’m having an issue with CCLabelTTF where once I create it with a font name different than the default one “Marker Felt.ttf”, all my text (including the labels using “Marker Felt” as font and the new created labels) starts using the new font. As if the setFontName overwrites the default one.

**Comment by WenhaiLin** [comment]
Replace 'setFontName' with 'setFontNameObj' for set the font name  of 'MenuItemFont' object. 'setFontName' is a static methond,which is using for set the default font name of 'MenuItemFont'.
