### ISSUE TITLE
App will be black when it starts on nexus s.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8237]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3043). It was created at 2013/10/22 09:24:18 +0000
# Description

versions:3.0 alpha0
equipment:nexus s
# Comments
- schngrg added comment:
  Can you try this fix, maybe it is same bug:

https://github.com/cocos2d/cocos2d-x/pull/3769/files
 https://github.com/cocos2d/cocos2d-x/pull/3769

**Comment by pandamicro** [comment]
No report for latest versions, close
