### ISSUE TITLE
Fix for can't pause/stop looped sound effect in windows

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8238]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3045). It was created at 2013/10/23 01:30:56 +0000
# Description

I discovered this issue when I ported my game to windows using VS 2012. When I looped a sound effect I couldn’t stop that sound effect when calling stopEffect or pauseEffect. It appears that the issue is how the command variable is passed, an int versus unsigned int. I dug into CocosDenshion::MciPlayer and changed the function MciPlayer::_SendGenericCommand to MciPlayer::_SendGenericCommand(UINT nCommand) which resolved the issue.
- mightymenace added comment:
  It appears that my “solution” doesn’t completely resolved the issue. Most of the times the sound does stop/pause but sometimes it does not. However repeat calls of the stop/pause command eventually stops/pauses the sound.
- jianhan513@163.com added comment:
  I got similar bug in android. I just can’t stop looped sound effect sometimes. If I call stopEffect serval times. It will be stopped.

**Comment by wildbunny** [comment]
I have exactly the same problem in windows. Stopping a looping sound doesn't work if you have another stream playing at the same time.

**Comment by minggo** [comment]
Please use new audio instead.
