### ISSUE TITLE
EAGLView is not removed from NSNotificationCenter

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8239]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3066). It was created at 2013/10/25 00:04:40 +0000
# Description

The bug appears to be in Apple’s sample code EAGLView. If the view is released then keyboard events crash the process. Fix is simple:
cocos2dx/platform/ios/EAGLView.mm
- (void)didMoveToWindow;
  {
  if (self.window) {
  [[NSNotificationCenter defaultCenter] addObserver:self
  selector:`selector(onUIKeyboardNotification:)
                                                     name:UIKeyboardWillShowNotification object:nil];
  
  ```
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:`selector(onUIKeyboardNotification:)
  ```
  
  name:UIKeyboardDidShowNotification object:nil];
  [[NSNotificationCenter defaultCenter] addObserver:self
  selector:`selector(onUIKeyboardNotification:)
                                                     name:UIKeyboardWillHideNotification object:nil];
  
  ```
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:`selector(onUIKeyboardNotification:)
  ```
  
  name:UIKeyboardDidHideNotification object:nil];
  } else {
  [[NSNotificationCenter defaultCenter] removeObserver:self];
  }
  }

**Comment by dabingnn** [comment]
Issue out of date.
The code is very different in current version.
