### ISSUE TITLE
CCParticleQuad setTotalParticles issue if count is bigger than before

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8242]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3091). It was created at 2013/10/31 07:48:56 +0000
# Description

For example:
- Load a plist with a value of 10 for “maxParticles”
- Then after the create process try to set the totalParticles to 20.
- The emitter will be invisible and not working.
- Instead if I reduce the count of particles it works.
- ppg_dkk added comment:
  Reproduced with version 2.1rc0-x-2.1.4

**Comment by yangws** [comment]
Test on engine version 3.7, can't reproduct this bug by codes below:

```
void ParticleIssue8242::onEnter()
{
    ParticleDemo::onEnter();

    _color->setColor(Color3B::BLACK);
    removeChild(_background, true);
    _background = nullptr;

    auto winSize = Director::getInstance()->getWinSize();

    auto particle = ParticleSystemQuad::create("Particles/BoilingFoam.plist");
    particle->setPosition(Vec2(winSize.width * 0.5f, winSize.height * 0.5f));
    addChild(particle);

    _emitter = particle;
    _emitter->retain();

    // to the work described in issue https://github.com/cocos2d/cocos2d-x/issues/8242
    _emitter->setTotalParticles(_emitter->getTotalParticles() * 2);
}
```

**Comment by minggo** [comment]
Thanks @yangws .

**Comment by zjsxcm** [comment]
The bug happened in 2.x version. 
Then I have find a method called "updateTexCoords" in v3.7 with note fix issue. After copy the method to v2.x  the issue fixed.
