### ISSUE TITLE
Black screen on full HD android devices

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8246]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3097). It was created at 2013/10/31 23:32:31 +0000
# Description

I have noticed that the android version of my game displays a black screen on devices with a full HD screen like the Samsung Galaxy S4 and a few other devices. The game does not crash or anything and I believe that it is actually running in the background however nothing is displayed on the screen. I’m sorry I cannot give you more information as I don’t actually have a full HD android device to test it on I have just had reports from friends that it does not work and have received no crash reports.
- lochlanna added comment:
  I’m using Cocos2D-x 2.1.5

**Comment by purepure** [comment]
Hi guy!
I got this issue too. I am using cocos2dx v3.0

**Comment by minggo** [comment]
@purepure how to reproduce it? Will you please create a new issue?

**Comment by purepure** [comment]
I use that version of cocos2dx:
branch: v3
commit b5de8ba0ea83f5fb84aa04f4cc36d2b5a2d4236f
Merge: 9943c83 9c35ded
Author: minggo xiaoming.zhang@chukong-inc.com
Date:   Mon Jul 18 15:01:10 2016 +0800

Simply I created a project of c++ then build. When I put this flag APP_ABI:= armeabi armeabi-v7a x86 in Application.mk file then build -> the game seem work normally, include sound effect, but black screen
I also tried to build only for armeabi-v7a  architect, it work!, but build for all, it failed

**Comment by dumganhar** [comment]
@purepure , could you upload the logcat output? That will be easier for us to find the problem.
Or could you upload an APK file to reproduce this issue?

**Comment by purepure** [comment]
@minggo I will migrate this to new issue the upload apk include logfile. This may take a little long time because building cc is never fast.
[new issue](https://github.com/cocos2d/cocos2d-x/issues/16840)
