### ISSUE TITLE
Crashes after first loop on real device of ios7

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8251]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3135). It was created at 2013/11/09 17:50:32 +0000
# Description

very simple code:

```
    CCSprite* pSprite = CCSprite::create("HelloWorld.png");

    pSprite->setPosition(ccp(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y));
    pSprite->runAction(CCRepeatForever::create(CCSequence::create(CCMoveBy::create(0.5, ccp(-40, 0)), CCMoveBy::create(.5, ccp(80, 0)))));
```

it should repeat forever, but when the sprite move to the very right, just before it rewind, it crashes!
BUT it runs well on simulator !
![](http://www.cocos2d-x.org/attatchments/2742/)
# Comments
- rickytan added comment:
  I think I’ve found out the problem, just add a NULL to the end of var list
  
  pSprite->runAction(CCRepeatForever::create(CCSequence::create(CCMoveBy::create(0.5, ccp(-40, 0)), CCMoveBy::create(.5, ccp(80, 0)), NULL)));

**Comment by dabingnn** [comment]
issue has been resolved
