### ISSUE TITLE
CCClippingNodeTest按照裁剪图片的*大小*而不是*alpha值*来裁剪

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8252]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3155). It was created at 2013/11/11 10:40:25 +0000
# Description

我现在在windows7 64位系统下，发现CCClippingNode不能正常工作：
裁剪不是根据alpha值来工作，而是根据裁剪图片的大小来的（如果被裁剪图片大于裁剪图片，那么被裁剪图片将按照裁剪图片的矩形大小来裁剪，否则，无效果）。
我的环境：
Windows7 64位旗舰版，
Visual Studio 2012 Exprese，
Cocos2d-x 2.2版，
复现步骤：
打开TestCpp.exe,选择ClippingNodeTest->Sprite Inverted Basic Test，可以看到这个反向裁剪是错误的。（我自己写的测试例子中，正向裁剪也是错误的）
截图如下：![](http://www.cocos2d-x.org/attatchments/2748/)(见附件)
# Comments

**Comment by yangws** [comment]
Can't reproduct this issue with engine version 3.7 on windows 8.1.
![2015-07-02 17 59 58](https://cloud.githubusercontent.com/assets/488183/8474679/5f6ee8a8-20e4-11e5-8848-fdb6bdd76592.png)

**Comment by minggo** [comment]
Thanks @yangws .
