### ISSUE TITLE
onResume can be called when the application is in background

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8254]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3158). It was created at 2013/11/11 15:49:29 +0000
# Description

In Android onResume may be called when the lock screen of the phone is
still locked. For example music may start playing while the screen is locked.

Info: http://stackoverflow.com/questions/11731285/onresume-being-called-over-and-over-while-phone-screen-is-locked

I changed the code to make notification AppDelegate::applicationWillEnterForeground just when the application became visible for the user.

Pull request: https://github.com/cocos2d/cocos2d-x/pull/4096

**Comment by yangws** [comment]
Can't reproduct this bug with engine version 3.7 on Nexus5 android 4.4.4, which metioned in that stackoverflow post. onResume and onPause called once when lock/unlock screen.

**Comment by minggo** [comment]
Thanks @yangws.
