### ISSUE TITLE
Animation from getSpriteFrameByName() wiggles on iOS and some Android devices

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8256]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3166). It was created at 2013/11/12 20:13:38 +0000
# Description

For details, please see:
http://www.cocos2d-x.org/forums/6/topics/38696

I have a cocos2d-x 3.0alpha example project but I cannot upload it (see http://www.cocos2d-x.org/issues/3165)
- hawkwood added comment:
  This seems to be an ongoing issue with Cocos2d-iphone also:
  https://code.google.com/p/cocos2d-iphone/issues/detail?id=1345

but the current work-around seems to have performance implications unless extra effort is taken to only use it on sprites that will be animated. Additionally, the fact that this happens on iOS devices but does NOT happen on the Xcode simulator, and inconsistently on Android devices, implies that this is a deeper Cocos2d issue.
- ricardo added comment:
  Justin Hawkwood wrote:
  > This seems to be an ongoing issue with Cocos2d-iphone also:
  > https://code.google.com/p/cocos2d-iphone/issues/detail?id=1345
  >
  > but the current work-around seems to have performance implications unless extra effort is taken to only use it on sprites that will be animated. Additionally, the fact that this happens on iOS devices but does NOT happen on the Xcode simulator, and inconsistently on Android devices, implies that this is a deeper Cocos2d issue.

Correct. The solution is to use `high` precision vars on the shader.

**Comment by pandamicro** [comment]
Already upgraded to v2 in latest v3.8

**Comment by pandamicro** [comment]
The maintenance for v2 have been stopped, so this kind of bug will only be reopen if some one reproduce it in v3 versions
