### ISSUE TITLE
WM_TOUCH dpi-aware scaling problem

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8258]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3216). It was created at 2013/11/16 15:46:45 +0000
# Description

Firstly, I am a PC user with MS surface pro - windows8/x64. And I use modified dpi settings.
The option’s: Control Panel ~~> Appearance and Personalization~~> Display and select Larger - 150% radio box.
I ran the HelloCpp sample project and touch feature was not working properly.
I traced to line 411 of CCEGLView.cpp: input.x = TOUCH_COORD_TO_PIXEL(ti.x);
It seems like input.x is wrongly scaled.
The same issue could be found on http://git.chromium.org/gitweb/?p=chromium/chromium.git;a=commitdiff;h=aae0617a702629b6bc0602cc9e1821b6fcb4898f

**Comment by yangws** [comment]
Can't reproduct this issue with engine version 3.7 on windows 8.1, which set Display and select Larger - 150% radio box.

**Comment by minggo** [comment]
Thanks @yangws.
