### ISSUE TITLE
CCScrollView && CCTableView not working correctly on wp8 

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8260]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3230). It was created at 2013/11/19 13:59:31 +0000
# Description

just run the default TestCpp project, choose extension test~~>cocosbuilder test~~>scrollview test,

it not only functioning incorrect, but also runed everything after running this.
- ex3 added comment:
  detect this under env:

cocos2d-x version 2.2 (download the default package)
windows 8.0
vs2012 & wp8 emulator

**Comment by adilghaffar** [comment]
Any progress in this issue ?

**Comment by minggo** [comment]
v2.x will only fix critical bugs.
WP8 is maintained by developers in v2.x.
