### ISSUE TITLE
Latest CURL

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8267]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3287). It was created at 2013/11/27 04:37:24 +0000
# Description

Currently cocos2d-x is using v7.26.0 libcurl library. It’s already more than 1 year old and during that time libcurl team has done so many bug fixes and improvements.

Please consider to update the libcurl library to the latest version (v7.33.0). Also, it’s much more appreciated that there’s documents to help us to generate both 64-bit and 32-bit version libcurl library for all platforms with SSL support.
- hawkwood added comment:
  Second this.  Due to a bug in curl 7.26.0 an iOS app can crash if the internet connection is poor (high number of packets lost).  This bug is fixed in 7.33.0.  I have been manually swapping out the iOS version, so having it updated in Cocos2d-x libs would be a great help.

**Comment by tmsoft** [comment]
Anyone else get compile errors with libcurl?

/Users/todd/dev/android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: jni/../../cocos2d/external/curl/prebuilt/android/armeabi/libcurl.a(sha512-armv4.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/Users/todd/dev/android/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/map:1055: error: relocation overflow in R_ARM_THM_CALL
jni/../../cocos2d/external/curl/prebuilt/android/armeabi/libcurl.a(url.o):function IsPipeliningPossible: error: relocation overflow in R_ARM_THM_CALL
jni/../../cocos2d/external/curl/prebuilt/android/armeabi/libcurl.a(url.o):function fix_hostname.isra.1: error: relocation overflow in R_ARM_THM_CALL
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: **\* [obj/local/armeabi/libcompulsive.so] Error 1

**Comment by pandamicro** [comment]
We should recompile lib curl with -fPIC, it seems solved when we test our machines. Please try it out on your side, you can download the new binary in this pull request:

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/54
