### ISSUE TITLE
Invalid OpenGL Surface in Rare Scenario (Android - pre JellyBean)

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8270]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3295). It was created at 2013/11/28 02:05:43 +0000
# Description

Hi,

In some cases the GLSurfaceView can fail to be re-created. The best way to reproduce this is to launch another activity while your activity is starting (I am doing this to launch pre-roll ads in my case). One the bug occurs you get a black screen and the only way to recover from it is to press the back button, then re-enter (note: home button doesn’t fix it).

Here’s the error you get:

```
11-16 16:32:06.991: E/GLSurfaceView(6652): eglCreateWindowSurface
11-16 16:32:06.991: E/GLSurfaceView(6652): java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
11-16 16:32:06.991: E/GLSurfaceView(6652):     at com.google.android.gles_jni.EGLImpl._eglCreateWindowSurface(Native Method)
11-16 16:32:06.991: E/GLSurfaceView(6652):     at com.google.android.gles_jni.EGLImpl.eglCreateWindowSurface(EGLImpl.java:90)
11-16 16:32:06.991: E/GLSurfaceView(6652):     at android.opengl.GLSurfaceView$DefaultWindowSurfaceFactory.createWindowSurface(GLSurfaceView.java:798)
11-16 16:32:06.991: E/GLSurfaceView(6652):     at android.opengl.GLSurfaceView$EglHelper.createSurface(GLSurfaceView.java:1065)
11-16 16:32:06.991: E/GLSurfaceView(6652):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1433)
11-16 16:32:06.991: E/GLSurfaceView(6652):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)
```

On stackoverflow is a post that could explain this: [[http://stackoverflow.com/questions/12855103/eglcreatewindowsurface-fails-with-java-lang-illegalargumentexception]]
I tried this solution out and it worked fine. Basically I back-ported GLSurfaceView from Android Level 19 and had Cocos2dxGLSurfaceView extend that version of GLSurfaceView. I also had to make the following change:

```

---
>                         if (mEglHelper.createSurface()) {
1486,1489c1479,1481
< //                                mFinishedCreatingEglSurface = true;
< //                                mSurfaceIsBad = true;
< //                                sGLThreadManager.notifyAll();
<                                 sGLThreadManager.wait();

---
>                                 mFinishedCreatingEglSurface = true;
>                                 mSurfaceIsBad = true;
>                                 sGLThreadManager.notifyAll();
1491,1492d1482
<                               
<                               Thread.sleep( 250 );
1509c1499
<                         GLSurfaceView19 view = mGLSurfaceViewWeakRef.get();

---
```

This fixes the problem for me. Unfortunately the GLSurfaceView from level 19 is incompatible with Android 2.2 - so now I’m looking into backporting an older version.

Has anybody experienced this issue? Any better ideas for fixing this?
Thanks

**Comment by txwjj33** [comment]
你好，我也遇到了这个问题，使用的是cocos2d 2.1.4,请问要怎么修改，你上面给出的那段代码应该添加到哪里，非常感谢。

**Comment by toilet1paper** [comment]
现在这个问题有什么进展了嘛？

**Comment by toilet1paper** [comment]
尝试了很多办法 还是会有这个问题

**Comment by yangws** [comment]
Can't reproduct this issue using engine version 3.7 on android JellyBrain, which that post mentioned.
@minggo

**Comment by minggo** [comment]
Thanks @yangws .
