### ISSUE TITLE
_unflippedOffsetPositionFromCenter 变量未初始化

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8271]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3308). It was created at 2013/11/28 09:08:52 +0000
# Description

cocos2dx3.0版本
Sprite在用initWithTexture函数初始化的时候_unflippedOffsetPositionFromCenter 没有初始化，这样将导致， 如果一个Sprite先用做SpriteFrame(initWithSpriteFrame),SpriteFrame有offset，_unflippedOffsetPositionFromCenter 被赋值。然后，这个Sprite又用作一个纹理(initWithTexture)，这时_unflippedOffsetPositionFromCenter 没有初始化，setTextureRect对_offsetPosition赋值的时候，将会用之前的_unflippedOffsetPositionFromCenter ，出现bug。

**Comment by yangws** [comment]
As design, one Sprite instance should only init once, the behavior of the sprite which init twice is undefined.
As your description, after create a Sprite for initWithSpriteFrame, you should create another Sprite instance for initWithTexture.
@minggo

**Comment by minggo** [comment]
Thanks @yangws .
