### ISSUE TITLE
Add an API Texture2D* TextureCache::addImage(Image *image, cons char * key)

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8273]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3324). It was created at 2013/11/30 05:04:02 +0000
# Description

I am using TextureCache::addImage, why not add an API

Texture2D* TextureCache::addImage(Image **image, cons char**key) ?
- birdflying1005 added comment:
  I am sorry, I mean to add an API like :

Texture2D * TextureCache::addImage(const std::string &path, const std::string &key);
- birdflying1005 added comment:
  Texture2D * TextureCache::addImage(const std::string &path)

Currently, the implementation is to convert the path to the real path, and put the real path as the key to store image into map.

_textures.insert( std::make_pair(fullpath, texture) );

When I use TextureCache::getInstance()->getTextureForKey to get the image, I have to input the real path of the image as the key to query it. Complicated and unreasonable a bit.

Regards,
Sean

**Comment by pandamicro** [comment]
Already done
