### ISSUE TITLE
[Important]license or copyright issue on PNG file.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8281]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3381). It was created at 2013/12/13 02:54:30 +0000
# Description

I think it is very important issue.

I noticed that cocos2dx repository contains the follows file…

https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-tests/Resources/Images/spritesheet1.png
![](https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-tests/Resources/Images/spritesheet1.png?raw=true)

I guess that It’s a license violation for “Nintendo Co., Ltd.” or “The Pokémon Company”.
I suggest that cocos2dx project should improvement of above issue immediately.

Best Regards,

**Comment by pandamicro** [comment]
We will move out performance test cases, in the meantime, @natural-law Please replace this image with another sprite sheet which won't cause any license issues. This is a good place to dig something out: http://opengameart.org/
