### ISSUE TITLE
Potential SERIOUS MEMORY LEAK on CCDirector::popScene(void)

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8284]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3415). It was created at 2013/12/17 07:46:42 +0000
# Description

I found CCDirector::popScene may cause memory leak on some occasions.
The thing is, when u popScene more than once in a single frameupdate, like

```
CCDirector::sharedDirector()::popScene()
CCDirector::sharedDirector()::popScene()
```

then everything between current scene and last scene will be leaked out. Which could be a lot of stuffs out there.
I modified the code as below and it worked fine until now.

```
void CCDirector::popScene(void)
{
    CCAssert(m_pRunningScene != NULL, "running scene should not null");

    CCScene *current = (CCScene*)m_pobScenesStack->lastObject();
    if( current->isRunning() )
    {
        current->onExit();
    }
    current->cleanup();

    m_pobScenesStack->removeLastObject();
    unsigned int c = m_pobScenesStack->count();

    if (c == 0)
    {
        end();
    }
    else
    {
        m_bSendCleanupToScene = false;
        m_pNextScene = (CCScene*)m_pobScenesStack->lastObject();
    }
}
```

**Comment by pandamicro** [comment]
I personally do not think it's a bug, our implementation don't support to pop multiple scenes at one time and user shouldn't do this. If we want to support it, it's a new feature requested.
