### ISSUE TITLE
to support with AssetsManager for wp8

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8297]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3589). It was created at 2014/01/07 09:23:27 +0000
# Description

http://www.cocos2d-x.org/forums/6/topics/42275

**Comment by stammen** [comment]
This is fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/8926
