### ISSUE TITLE
3.0alpha ClippingNode can not work on IOS5

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8301]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3624). It was created at 2014/01/09 03:45:40 +0000
# Description

I use the cocos2d-x with 3.0alpha1 , the ClippingNode works ok on IOS6 and IOS7, but on the IOS5, it’s cant not work.

The test device is ipad1 and ipad2

**Comment by pandamicro** [comment]
Not reported for latest versions, close
