### ISSUE TITLE
cocos2d-x 3.0 beta is not properly working on Galaxy S2, Android 2.3.3

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8304]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3663). It was created at 2014/01/10 04:13:15 +0000
# Description

Hello.

cocos2d-x 3.0 beta is not properly working on Galaxy S2, Android 2.3.3.
It runs but renders nothing.
App freezes when press hardware button.

it seems same problem.
http://www.cocos2d-x.org/forums/6/topics/42349

Thanks.
- pyrasis added comment:
  please see this page http://www.cocos2d-x.org/forums/6/topics/42923

**Comment by pandamicro** [comment]
Not reported for latest version, close
