### ISSUE TITLE
在有些设备上调用SimpleAudioEngine::playBackgroundMusic会抛出这个异常，偶尔会导致宕机

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8313]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3699). It was created at 2014/01/14 07:16:58 +0000
# Description

01-12 10:39:28.019 29105 30411 MediaPlayer release() mWfdReceiver: null
01-12 10:39:28.023 29105 29399 MediaPlayer mPlayerID = 435
01-12 10:39:28.034 29105 30411 MediaPlayer Don’t notify duration to cc.hilink.eoa!
01-12 10:39:28.040 29105 30411 MediaPlayer Don’t notify duration to cc.hilink.eoa!
01-12 10:39:28.041 29105 30411 MediaPlayer start() mSourceType: 0
01-12 10:39:28.041 29105 30411 MediaPlayer getMetadata
01-12 10:39:28.041 29105 30411 MediaPlayer getMetadata() isDrm: true
01-12 10:39:28.041 29105 30411 MediaPlayer initSecureFlag() mSourceType: 2 mWfdReceiver: null
01-12 10:39:28.041 29105 30411 MediatekClassFactory createInstance(): Begin = 66490651
01-12 10:39:28.041 29105 30411 MediatekClassFactory create Instance with : interface com.mediatek.common.drm.ISecureWarningPrompt
01-12 10:39:28.041 29105 30411 MediatekClassFactory create Instance from mediatek-framework library : com.mediatek.drm.SecureWarningPrompt
01-12 10:39:28.041 29105 30411 MediatekClassFactory Exception: java.lang.ClassNotFoundException
01-12 10:39:28.041 29105 30411 MediatekClassFactory createInstance(): End = 66490652
01-12 10:39:28.041 29105 30411 MediatekClassFactory null object during finding : interface com.mediatek.common.drm.ISecureWarningPrompt
01-12 10:39:28.042 29105 30411 System.err java.lang.RuntimeException
01-12 10:39:28.042 29105 30411 System.err at com.mediatek.common.MediatekClassFactory.createInstance(MediatekClassFactory.java:487)
01-12 10:39:28.042 29105 30411 System.err at android.media.MediaPlayer.initSecureFlag(MediaPlayer.java:1112)
01-12 10:39:28.042 29105 30411 System.err at android.media.MediaPlayer.start(MediaPlayer.java:1091)
01-12 10:39:28.042 29105 30411 System.err at org.cocos2dx.lib.Cocos2dxMusic.playBackgroundMusic(Unknown Source)
01-12 10:39:28.043 29105 30411 System.err at org.cocos2dx.lib.Cocos2dxHelper.playBackgroundMusic(Unknown Source)
01-12 10:39:28.043 29105 30411 System.err at org.cocos2dx.lib.Cocos2dxRenderer.nativeTouchesEnd(Native Method)
01-12 10:39:28.043 29105 30411 System.err at org.cocos2dx.lib.Cocos2dxRenderer.handleActionUp(Unknown Source)
01-12 10:39:28.043 29105 30411 System.err at org.cocos2dx.lib.Cocos2dxGLSurfaceView\$9.run(Unknown Source)
01-12 10:39:28.043 29105 30411 System.err ![]()at android.opengl.GLSurfaceView\$GLThread.guardedRun(GLSurfaceView.java:1462)
01-12 10:39:28.043 29105 30411 System.err at android.opengl.GLSurfaceView\$GLThread.run(GLSur![]()faceView.java:1240)
01-12 10:39:28.043 29105 30411 MediaPlayer initSecureFlag() exception
在有些设备上调用SimpleAudioEngine::playBackgroundMusic会抛出这个异常，偶尔会导致宕机

我测试的设备是 Asus ME173X ![]()![]()
# Comments

**Comment by oktears** [comment]
请问是如何解决的BUG？

**Comment by minggo** [comment]
@oktears 
This issue is migrated from redmine, it is an old issue.
Did you meet the issue?

**Comment by hiki343726700** [comment]
@minggo 
this the issue ,from cocos2dx3.2 and android Blade E,How to solve？thanks

**Comment by WenhaiLin** [comment]
@hiki343726700 This issue should be fixed at https://github.com/cocos2d/cocos2d-x/pull/9088 . Please refer to https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxMusic.java

**Comment by WenhaiLin** [comment]
@hiki343726700 Sorry,i got it wrong.

**Comment by WenhaiLin** [comment]
@hiki343726700 Please try this solution: https://github.com/cocos2d/cocos2d-x/pull/12256

**Comment by hiki343726700** [comment]
check passed
