### ISSUE TITLE
Back key event doesn't dispatch on CCLayer.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8320]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3797). It was created at 2014/01/20 19:44:28 +0000
# Description

Pressing back key on WP8 application quits. It must dispatch back key press event to the Layer having enabled keypad and overridden keybackClicked() method. Both WP8 native and WP8 XAML with Native templates missing back key handling.

I have documented workaround here on my blog:
http://patidarvikas.blogspot.in/2014/01/handle-back-key-event-in-cocos2dx-222.html

**Comment by pyrosphere** [comment]
The workaround works for the v2 branch but the v3 branch handles key events differently, see this issue for a possible workaround: https://github.com/cocos2d/cocos2d-x/issues/8485
