### ISSUE TITLE
Fullscreen support for Mac Desktop / OS X

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8321]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3798). It was created at 2014/01/20 22:37:42 +0000
# Description

Every new app created with Xcode supports so called **“FullScreen”** out of the box. Just need to set NSWindow property in interface builder.

This allows to switch from windowed mode to FullScreen on another desktop workspace or another display. It is great feature, giving user better usage experience, if of course it is supported by application. Difference with other “fullscreen” modes in for example Windows x86 app (where full screen is just resized window), is that OS X fully controls window position and size, which is switched to a different workspace or display.

This is **_the only**_ preffered by API, OS X way of FullScreen application experience.

At this time, cocos2d-x/OS X does not seem to support this feature. For a user, this is additional button in right upper corner of the window, that let’s him switch to FullScreen mode.

https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/FullScreenApp/FullScreenApp.html

Some tips:

http://support.apple.com/kb/PH11359
http://lwjgl.org/forum/index.php/topic,4671.msg27932.html\#msg27932
http://www.cocoanetics.com/2012/11/the-lions-full-screen-mode
http://stackoverflow.com/questions/10096529/howto-is-nswindow-in-fullscreen-mode-lion-and-enabling-disabling
- ricardo added comment:
  fixed:
  https://github.com/cocos2d/cocos2d-x/pull/5183

The only feature that is missing is switching back to Window mode.
We will add that feature once glfw v3.1 is released, since glfw v3.0 doesn't support it now.

**Comment by kaplad** [comment]
Can I implement this issue?

**Comment by minggo** [comment]
@kaplad 
Sure. You are appreciated if you can send a pull request for it.

**Comment by sidshekar** [comment]
HI was this feature implemented :D ?? Thanks for @kaplad for trying to implement it.

**Comment by kaplad** [comment]
Not yet :) Soooon

**Comment by sidshekar** [comment]
Excited!!! :D

**Comment by stevetranby** [comment]
Related issue opened: https://github.com/cocos2d/cocos2d-x/issues/11127

**Comment by jonnyijapan** [comment]
Is this implemented? How does it work?

**Comment by RustyMoyher** [comment]
I'm very excited for this feature too! Any thought when it might happen?

**Comment by jonnyijapan** [comment]
I'll just add that if running a Mac app in fullscreen as it is implemented now, if the app crashes then, it's very hard to get out of the fullscreen mode because the app "swallows" any keyboard input...

**Comment by digitalhoax** [comment]
"very hard" for me means powering off the mac and rebooting, potentially loosing all of the data open in the background.

**Comment by jonnyijapan** [comment]
As far as I remember I used another computer on the network to ssh into the frozen computer and shut the cocos process down.

**Comment by minggo** [comment]
It is already supported.
