### ISSUE TITLE
App freezes on taping Cancel button during in app purchase confirmation in iOS 7

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8326]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3843). It was created at 2014/01/25 07:29:52 +0000
# Description

Hello,

I thank you in advance for your help to fix issue which i m not able to fix since yesterday. My app was working fine for iOS 6 but when iOS 7 came in i am experiencing this issue.
step 1. Press Buy button
step 2. In pop's to buy, there cancel.
step 3. It takes user to game again. Then again press buy that freeze game.

additional information is that when i am debugging the game in XCode, i follow above mentioned steps app freezes. At that stage when i Stop the debug from XCode i see the spring board and the pop up from the store kit which asks for the confirmation to buy.

The code to perform in app in app purchase is very simple and it had no problem in iOS 6

if ([SKPaymentQueue canMakePayments]) {
        SKMutablePayment *payment = [[SKMutablePayment alloc] init] ;
        payment.productIdentifier = productId;
        payment.quantity = 1;
        [[SKPaymentQueue defaultQueue] addPayment:payment];

```
} else {
    NSLog(@"Can't make purchases. Parental control is probably enabled.");
}
```

Looking forward to see you earlier response. Thanks

**Comment by pandamicro** [comment]
IAP is not an in engine feature, besides, no related bug reports for latest versions, so close
