### ISSUE TITLE
cc_2x2_white_image  is missing , giving warning at runtime

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8328]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3886). It was created at 2014/01/30 12:55:16 +0000
# Description

In CCSprite.cpp
there is #define CC_2x2_WHITE_IMAGE_KEY  "/cc_2x2_white_image" definnition 
but there is no file by this name 
in runtime there is warning that looks like this :

```
cocos2d: fullPathForFilename: No file found at /cc_2x2_white_image. Possible missing file.
```
- zhangxm added comment:
  The data is in the byte array named `cc_2x2_white_image` in CCSprite.cpp. You don't have to care about it. It is used when there is not a texture for a `Sprite`.

**Comment by pandamicro** [comment]
It's not a bug
