### ISSUE TITLE
add getter to  _textureFilename  in CCSpriteFrame 

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8332]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3892). It was created at 2014/02/04 12:20:50 +0000
# Description

currently there is no way to get the _textureFilename from CCSpriteFrame 
there is protected member that called _textureFilename that keeps the Texture File name
please add getter to this variable so we can get the file name of the frame

**Comment by pandamicro** [comment]
Solution: 

TextureCache::getInstance()->getTextureFilePath(texture);
