### ISSUE TITLE
crash when load plist in new scene and load amazon ad

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8334]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3918). It was created at 2014/02/08 03:42:39 +0000
# Description

I create a game for android use c++ cocos2dx. 
I add Amazon AD in the game. But I fount the game crash when turn to second scene. And frequently crash.
I use cocos2dx 2.1.4

1.load LOGO scene and wait 2 sec. the same time load Amazon ad.
2.when Amazon ad loaded and turn to second scene. And second scene load plist file in it.
3.It will high rate crash.

**Comment by dabingnn** [comment]
Bug could not be reproduced.
