### ISSUE TITLE
cocos2dx can't active "keyBackClicked" function after click amazon ad.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8335]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3919). It was created at 2014/02/08 03:45:13 +0000
# Description

it strange out by step:
1.add Amazon Ad to my game.
2.run game and show amazon ad banner.
3.click amazon ad banner . then popup a web page in game.
4.close the web page and back game.
5.press "back" button . the game can't active "keyBackClicked" function

I use cocos2dx 2.1.4

**Comment by pandamicro** [comment]
The maintenance for v2 have been stopped, so this kind of bug will only be reopen if some one reproduce it in v3 versions
