### ISSUE TITLE
JniHelper - multi-threaded environment issues

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8338]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3993). It was created at 2014/02/11 20:34:02 +0000
# Description

Hi, 

In v2.2.2 JniHelper's getEnv() was changed. Namely, it set env as a thread specific variable with pthread_setspecific. 
This seems to have made it so that JniHelper can no longer be used by multiple threads. v2.2.1 does not have this problem and allows access to the JNI via multiple threads. 

To reproduce, simply spawn a new pthread and call getWritablePath(). The app will then crash in JniHelper with an invalid env variable.

Thanks

**Comment by minggo** [comment]
It is fixed.

**Comment by jainayush1993** [comment]
Can you tell me the pull request in which this was fixed? @minggo  @WenhaiLin
