### ISSUE TITLE
MenuItemImage创建的bug

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8343]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4045). It was created at 2014/02/16 04:57:23 +0000
# Description

当我使用MenuItemImage创建一个菜单项的时候，如果使用了不存在的文件名，但是代码仍然可以运行，但是创建的菜单仍然可也以显示

**Comment by pandamicro** [comment]
Not a bug, no crash experience
