### ISSUE TITLE
 'kResolutionNoBorder' policy shown error in real device of wp8

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8345]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4050). It was created at 2014/02/17 07:33:57 +0000
# Description

http://www.cocos2d-x.org/forums/6/topics/43443
It changes to kResolutionExactFit in hellocpp project.
- chenjc added comment:
  https://github.com/MSOpenTech/cocos2d-x/issues/38
- suveerjacob added comment:
  hello,
  I am waiting for the solution of this problem. Some else have also reported the same issue and suggested some nearby solution at this link: https://github.com/MSOpenTech/cocos2d-x/issues/38.

I have another game ready to be ported on windows 8, i am waiting for this issue to get solved.

**Comment by pandamicro** [comment]
The maintenance for v2 have been stopped, so this kind of bug will only be reopen if some one reproduce it in v3 versions
