### ISSUE TITLE
CCTextureAtlas resizeCapacity()

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8346]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4057). It was created at 2014/02/18 02:13:08 +0000
# Description

resizeCapacity() has crashed for me in two different circumstances. 
More details for each can be found at the following links:
http://cocos2d-x.org/forums/6/topics/36099?r=36144#message-36144 
http://cocos2d-x.org/forums/6/topics/45179
- siauw added comment:
  Is this related to my thread here? Because I'm using SpriteBatchNode also to render the background, and I'm using phone with Adreno 200 ( HTC One V)

http://www.cocos2d-x.org/forums/6/topics/45118?r=45882

**Comment by pandamicro** [comment]
This should have been fixed : http://discuss.cocos2d-x.org/t/drawing-via-cctextureatlas-fails-on-certain-android-devices/9126/6?u=pandamicro
