### ISSUE TITLE
about 3d projection bug in Director::setProjection()

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8354]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4275). It was created at 2014/03/05 04:08:21 +0000
# Description

If we use 3d projection mode, we will set the modelview matrix by kmMat4LookAt function, where we need to calculate the eye position whose coordniate-z is derived from the function of getZeye().
In this function, (_winSizeInPoints.height / 1.1566f) is simplication of (_winSizeInPoints.height / 2 / tanf(pi/6)) where there is some deviation, the exact value should be 1.1547005383793f.
Normally this deviation can be igonred, however if we use framebuffer(RenderTexture), we may use the projection more than once, then the deviation error will be amplified, and we may get an unwished result.

**Comment by cwq** [comment]
@minggo I was wondering why not use the exact value, and use 1.1566f.

**Comment by minggo** [comment]
@ricardoquesada do you have any idea?

**Comment by ricardoquesada** [comment]
@minggo yes, we should use the exact value.
that number came from cocos2d-iphone, and IIRC, I added that harcoded number in cocos2d-iphone because it worked for me.

**Comment by ricardoquesada** [comment]
fixed.

**Comment by ricardoquesada** [comment]
reopened since `tanf(pi/6) * 2` doesn't work as expected. See comments here:  #16369

**Comment by newnon** [comment]
@ricardoquesada @TheCodez i made pull request for this problem, 2 days my team spend to find why cocos crop some pixels on screen border. And it is because constant error i think  @TheCodez got artefact because wrong texture but before cocos always crop one pixel on every side of screen.
