### ISSUE TITLE
Set SpriteFrames directly on cocos2d::ui elements

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8361]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4376). It was created at 2014/03/14 08:35:03 +0000
# Description

I noticed that the current development of the UI classes in the develop branch does not allow direct setting of SpriteFrames. In particular, the ui::Button and ui::ImageView. The usual `setSpriteFrame(SpriteFrame*)` method has been replaced by `loadTexture(const char *fileName, TextureResType texType)`.

I have submitted a pull request for the ui::Button which has yet to be acted upon here: https://github.com/cocos2d/cocos2d-x/pull/5448 a lot of changes has been made since that pull request so I doubt that the merge will be clean. I could create another pull request but I want to know if it's necessary.

Is the omission intentional or just an oversight? I needed that interface because my sprites/spriteframes are loaded by some other means other than the SpriteFrameCache (the textures are cached, but the sprite frames are not) because of our asset pipeline.

**Comment by zilongshanren** [comment]
not a required feature..
