### ISSUE TITLE
It should be sizeof(wszBuf)/sizeof(wszBuf[0]) but not sizeof(wszBuf) @ _log(..) in CCConsole.cpp

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8363]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4379). It was created at 2014/03/15 02:55:00 +0000
# Description

cocos2d-x 3.0beta2
File: CCConsole.cpp
Func: static void _log(const char *format, va_list args)
# BUG:

~~sizeof(wszBuf)~~ ----> should be 
sizeof(wszBuf) / sizeof(wszBuf[0]) or MAX_LOG_LENGTH ?

WideCharToMultiByte(CP_ACP, 0, wszBuf, ~~sizeof(wszBuf)~~, buf, sizeof(buf), NULL, FALSE); ---->
WideCharToMultiByte(CP_ACP, 0, wszBuf, **-1**, buf, sizeof(buf), NULL, FALSE);?

**Comment by pandamicro** [comment]
Fixed in v3
