### ISSUE TITLE
libGUI：Widget not works correctly with runAction(  FadeIn、FadeOut、FadeTo  )

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8364]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4380). It was created at 2014/03/15 06:18:28 +0000
# Description

cocos2d-x 3.0beta2

libGUI：Widget (and it's subclasses) not works correctly with runAction( FadeIn、FadeOut、FadeTo )

**Comment by pandamicro** [comment]
No more report for latest versions, close
