### ISSUE TITLE
(Widget::setContentSize() -> _contentSize)  !=  (Widget::getContentSize()  <- _size)

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8368]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4397). It was created at 2014/03/16 16:41:27 +0000
# Description

`Widget::setContentSize() -> _contentSize`, but `(Widget::getContentSize() == **_size**) != _contentSize`

When we write a function as:

``` cpp
void someFunc(Node* parent, Node* node) {
    // Now we have to check whether it is a Widget or a Node

    Widget* wParent = dynamic_cast<Widget*>(parent);
    Widget* wNode = dynamic_cast<Widget*>(node);

    Size vSize = (wParent ? wParent->getSize() : parent->getContentSize());
    Size cSize = (wNode ? wNode->getSize() : node->getContentSize());

    // ...
}
```
- walzer added comment:
  Well, it's a serious problem. Nutty is working on merging UIWidgets more compatible with the node system.

**Comment by pandamicro** [comment]
This have been fixed in v3
