### ISSUE TITLE
Sprite is rendered incorrect when method setVertexZ() invoked

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8372]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4445). It was created at 2014/03/19 06:41:32 +0000
# Description

Here is a related post from developer : http://www.cocos2d-x.org/forums/6/topics/47414

Reproduce the problem in TestCpp:
Modify the method `TMXIsoVertexZ::TMXIsoVertexZ()` in file `TileMapTest/TileMapTest.cpp` like this:

```
TMXIsoVertexZ::TMXIsoVertexZ()
{
    auto map = TMXTiledMap::create("TileMaps/iso-test-vertexz.tmx");
    addChild(map, 0, kTagTileMap);

    auto s = map->getContentSize();
    map->setPosition( Point(-s.width/2,0) );
    CCLOG("ContentSize: %f, %f", s.width,s.height);

    // because I'm lazy, I'm reusing a tile as an sprite, but since this method uses vertexZ, you
    // can use any Sprite and it will work OK.

    // @warning The code before modify (effect is ok) 
    // auto layer = map->getLayer("Trees");
    // _tamara = layer->getTileAt( Point(29,29) );
    // _tamara->retain();

    // @warning The code to reproduce the problem
    _tamara = Sprite::create(s_pathSister1);
    _tamara->retain();
    addChild(_tamara);
    _tamara->setAnchorPoint(Point(0.5, 0));
    _tamara->setScale(0.5, 0.5);
    _tamara->setPosition(Point(30,30));
    _tamara->setVertexZ(1);

    auto move = MoveBy::create(10, Point(300,250) * (1/CC_CONTENT_SCALE_FACTOR()));
    auto back = move->reverse();
    auto seq = Sequence::create(move, back,NULL);
    _tamara->runAction( RepeatForever::create(seq) );

    schedule( schedule_selector(TMXIsoVertexZ::repositionSprite));
}
```

The incorrect effect screenshot:
![http://www.cocos2d-x.org/attatchments/3814/](http://www.cocos2d-x.org/attatchments/3814/)
# Comments
- zhangbin added comment:
  The reason of the problem is: The using of `RenderCommand::_globalOrder` conflict with the DepthTest in OpenGL.
- zhangxm added comment:
  So what's the status of this issue?
- zhangbin added comment:
  I have no solution for the issue. It's related with the implementation of the new renderer.
  @dabingnn know the issue, and he also doesn't know how to solve it by now.:( 
- zhangxm added comment:
  @Nite
  @Riq
  Any thought?
- ricardo added comment:
  why this bug was tagged as private ?
- ricardo added comment:
  The problem is in the alpha function.
  The sprite needs to use an special shader for that, and we removed the "alpha testing shader" feature from tmx, since the rendering was not good and error prone.
- zhangxm added comment:
  Because v3.1 is private, because it is a plan, an we may adjust it.
- ricardo added comment:
  all the plans can be changed in the future... even Firefox, Linux, Blender... all the major open source projects can change their plans in the future... but they keep their roadmap and issues open, so they can receive input from the community.

I think there is no point in making issues privates... specially for cocos2d-x.
- zhangxm added comment:
  Ok.
  Changed it to public.
- stevetranby added comment:
  I believe I am seeing this issue where an isometric tilemap is not behaving well using setPositionZ() in 3.x where we were using setVertexZ() in 2.x. From the release notes it appeared to be that setPositionZ was settings OpenGL's z coordinate, but it looks like this isn't the case and instead is just used to sort the render commands?

Is this fixed in the latest repository commit? and if not, is it planned to fix with the new tilemap renderer?

**Comment by lyubomirv** [comment]
I believe this should be the same issue as #8524. Is it fixed or are there plans to fix it? This is a real showstopper for moving to version 3, at least for me.

**Comment by pandamicro** [comment]
Fixed in https://github.com/cocos2d/cocos2d-x/issues/8524
