### ISSUE TITLE
upgrade WebP support from 0.2.1 to 0.4.0

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8375]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4501). It was created at 2014/03/21 10:14:02 +0000
# Description

the current webp support is outdated. The decoder is very slow (on Nexus 4, 1.2 seconds for 3674x717 webp image; on LG Optimus One P500, 5.7 seconds).
# Comments
- alexodus added comment:
  I have another benchmark test with this example project:
  https://code.google.com/p/webp/downloads/detail?name=webpiosapp-0.4.0.tar.gz&can=2&q=
  -Simulator iOS (on MacBook Pro 2,4Ghz Intel Core 2 Duo) : ~ 260 milliseconds
  -Simulator iOS (on MacBook Pro 2,4Ghz Intel Core 2 Duo) with  lib file libwebp.a(*) inside Cocos2D-X 3.0rc0: ~ 400 milliseconds

GOOD! :)

(*) in ./cocos2d/external/webp/prebuilt/ios/ folder
- colprog added comment:
  i've tested webp 0.4.0 on a 1366x720 image on ios and android. and the result looked very promising.

webp decode performance on iphone 5:
Webp(lossy) : 0.079884s
Webp(loseless) : 0.115118s
Png : 0.197729s

webp decode performance on xiaomi 2s: 
Webp (lossy): 0.100315s
Webp(leseless) : 0.090699s
Png : 0.165843s

and the image size reduction is also remarkable:
PNG:  535 KB
WEBP(lossless): 172KB
WEBP(lossy): 48KB

going forward, now that webp support animated webp, it might be plausible to make webp the default image format for cocos2d-x.
- alexodus added comment:
  Changelog for 0.4.1 version of libwebp:
- 7/24/14: version 0.4.1
  This is a binary compatible release.
  - AArch64 (arm64) & MIPS support/optimizations
  - NEON assembly additions:
    - ~25% faster lossy decode / encode (-m 4)
    - ~10% faster lossless decode
    - ~5-10% faster lossless encode (-m 3/4)
  - dwebp/vwebp can read from stdin
  - cwebp/gif2webp can write to stdout
  - cwebp can read webp files; useful if storing sources as webp lossless

**Comment by pandamicro** [comment]
webp lib have been upgraded to v2 in latest version, close
