### ISSUE TITLE
Tag problem when using CCMenuItemToggle

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8376]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4502). It was created at 2014/03/21 10:39:28 +0000
# Description

Hi, I notice a bug with CCMenuItemToggle.

If I set a tag to CCMenuItem before creating the CCMenuItemToggle, the tag will change after CCMenuItemToggle is created.

if I save the tags before and try to get the tag in callback, all CCMenuItems have same tag so I can't differentiate which CCMenuItem is active right now.

Is this how the CCMenuItemToggle supposed to work?

**Comment by pandamicro** [comment]
Indeed, MenuItemToggle uses `kCurrentItem(0xc0c05001)`  as the tag of the toggled item. So tag have been used, it should be refined.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/13746
