### ISSUE TITLE
cocos2d::gui::UITextField showing black boxes when in Portrait (android)

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8391]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4609). It was created at 2014/03/31 08:17:06 +0000
# Description

Thread: http://cocos2d-x.org/forums/6/topics/49404?r=49407

**What's the issue?**
**UITextField** displays black boxes instead of the text when used in portrait mode.

**What's the engine version?**
Cocos2d-x 3.0 beta 1

**How to reproduce it?**
1. Create an Android Project.
2. Set `screenOrientation` to `portrait`.
3. Add a `UITextField` on a scene.
4. Test on an Android device.

OR
1. Build, Compile, and Run TestCPP on Portrait mode.
2. Go to `ExtensionsTest` > `CocosStudioGUITest` > `gui TextField Test`.
3. lance_gray added comment:
   Issue does not appear in Landscape mode, only in Portrait.

**Comment by pandamicro** [comment]
Not reported in latest versions, close
