### ISSUE TITLE
a bug in cocos/2d/CCLabelTTF.cpp

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8394]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4632). It was created at 2014/04/01 13:37:17 +0000
# Description

```
std::string LabelTTF::getDescription() const
{
    return StringUtils::format("<LabelTTF | FontName = %s, FontSize = %.1f, Label = '%s'>", _renderLabel->getFontName().c_str(), (float)_renderLabel->getFontSize(), _renderLabel->getString().c_str());
}
```

a `(float)` should be placed before `_renderLabel->getFontSize()`, otherwise it will crash.

**Comment by WenhaiLin** [comment]
@minggo It's work normal now.We can close this issue.
