### ISSUE TITLE
label->enableShadow()    Moving letters

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8397]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4687). It was created at 2014/04/04 17:30:23 +0000
# Description

Cocos2d-x v3.0 RC1.

How to reproduce:
Label::createWithBMFont(...)
label->getLetter(i)->runAction(JumpBy::create(...))

It will jump, but shadow color changed to White (during action) instead of maintaining  black or predefined color of shadow.

**Comment by qiululu** [comment]
I think it has already been fixed at latest version. it works correctly
