### ISSUE TITLE
Using Follow as camera as mentioned in code does not work

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8403]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4716). It was created at 2014/04/08 23:11:48 +0000
# Description

I have described some behaviour here:  http://www.cocos2d-x.org/forums/6/topics/49326

```
/** 
@brief Follow is an action that "follows" a node.

Eg:
@code
layer->runAction(Follow::actionWithTarget(hero));
@endcode

Instead of using Camera as a "follower", use this action instead.
@since v0.99.2
*/
```

When hero is added to layer and the hero moves, layer positioning is adjusted to attempt to center the hero, however it looks like the hero's position is updated as well (rendering the follow useless).

Perhaps I am using this function incorrectly, however it works perfectly fine on cocos2d-iphone

**Comment by ricardoquesada** [comment]
closing it as deprecated. The correct way to do is to use `Camera` now.
