### ISSUE TITLE
viewDidLoad not called

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8406]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4736). It was created at 2014/04/09 18:20:19 +0000
# Description

Currently, the view property of the view controller is being assigned in the AppController.mm file:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {   
...
    // Init the CCEAGLView
    CCEAGLView *eaglView = [CCEAGLView viewWithFrame: [self.window bounds]
                                         pixelFormat: kEAGLColorFormatRGB565
                                         depthFormat: GL_DEPTH24_STENCIL8_OES
                                  preserveBackbuffer: NO
                                          sharegroup: nil
                                       multiSampling: NO
                                     numberOfSamples: 0];
    // Override point for customization after application launch.

    // Use RootViewController manage EAGLView
    viewController = [[RootViewController alloc] initWithNibName:nil bundle:nil];
    //viewController.wantsFullScreenLayout = YES;
    viewController.view = eaglView;
...
}
```

However, this way the "viewDidLoad" method is not called, because according to Apple when not loading the view controller from a NIB or a Storyboard, the "loadView" method should be overriden (https://developer.apple.com/library/ios/documentation/uikit/reference/UIViewController_Class/Reference/Reference.html). 

This can be solved by moving this code, to the "loadView" method of the RootViewController:

```
- (void)loadView {

    // Init the CCEAGLView
    CCEAGLView *eaglView = [CCEAGLView viewWithFrame: [[UIScreen mainScreen] bounds]
                                         pixelFormat: kEAGLColorFormatRGB565
                                         depthFormat: GL_DEPTH24_STENCIL8_OES
                                  preserveBackbuffer: NO
                                          sharegroup: nil
                                       multiSampling: NO
                                     numberOfSamples: 0];

    self.view = eaglView;
}
```

The only modification in the AppController is removing those lines, because the "loadView" is called automatically the first time the "view" property is used. And the "viewDidLoad" is called as expected.

**Comment by xpol** [comment]
@minggo 
Closed? Why? The templates has not changed any.
`viewDidLoad` still not get called.
