### ISSUE TITLE
Child sprite render position error

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8412]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4787). It was created at 2014/04/14 06:13:04 +0000
# Description

Follow steps can reproduce this error. 
1. Add Sprite S to Layer L
2. Remove Sprite S from Layer L
3. Move Layer L to new position
4. Add Sprite S to layer L

I have figured out that this issue is because when S is added to L in step4, _transformUpdated of Layer L is set to false which makes Sprite S unable to update its transform. 
Adding statement '_transformUpdated = true' to Node::addChild can fix this issue
- xiaonanln added comment:
  I have changed the statement '_transformUpdated = true;' to 'child->_transformUpdated = child->_transformDirty = child->_inverseDirty = true;' in my local copy of cocos2d-x.

don't know if this is the proper fix

**Comment by pandamicro** [comment]
No more issue in v3
