### ISSUE TITLE
[v3.0stable]ControlSwitch not displayed properly on Android device

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8431]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5004). It was created at 2014/05/03 10:36:31 +0000
# Description

ControlSwitch is not displayed properly on my Android phone([HTC Evo 4G](http://en.wikipedia.org/wiki/HTC_Evo_4G) 2.3.4).
My code is copied from the cpp-tests.

```
    ControlSwitch *switchControl = ControlSwitch::create
    (
     Sprite::create("extensions/switch-mask.png"),
     Sprite::create("extensions/switch-on.png"),
     Sprite::create("extensions/switch-off.png"),
     Sprite::create("extensions/switch-thumb.png"),
     Label::createWithTTF("On", "fonts/Marker Felt.ttf", 16),
     Label::createWithTTF("Off", "fonts/Marker Felt.ttf", 16)
     );

    auto l = Node::create();
    l->addChild(switchControl);
    l->setContentSize(Size(80, 0));
    l->setPosition(Point(100, 100));
    addChild(l);
```
# Comments
- sodaigomi added comment:
  There is no problems on iOS devices
- sodaigomi added comment:
  I managed to find the reason. 
  In android you need to enable the Stencil buffer while in iOS it is already enabled.
  In the AppActivity.java, modify as follows

```
    public Cocos2dxGLSurfaceView onCreateView() {
        Cocos2dxGLSurfaceView glSurfaceView = new Cocos2dxGLSurfaceView(this);
        // TestCpp should create stencil buffer
        glSurfaceView.setEGLConfigChooser(5, 6, 5, 0, 16, 8);

        return glSurfaceView;
    }
```

**Comment by pandamicro** [comment]
Fixed in latest versions
