### ISSUE TITLE
Add or remove a node does not dirty the transformation

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8433]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5030). It was created at 2014/05/06 18:33:50 +0000
# Description

If you remove a child, move the former parent and then add it back to it, the node is drawn in the old position.
- Antaka added comment:
  I'm using the tag 'cocos2d-x-3.0' from git.
- Antaka added comment:
  Ok, I think this only happens if the parent node is drawn before you add the child back, that way the parent and the child transforms are both clean at that time and the child is not updated correctly.

So the steps are:
Have a parent and a child nodes.
Remove the child.
Change the position/scale/skew/etc of the parent.
Let a few updates go by so that the parent node is drawn and it's matrix is calculated.
Without changing anything to the child node, add I back to it's former parent.
The child node will have an outdated transform if you don't change anything from one of the nodes.

I fixed it in my game by toggling the visibility besides the add/removeChild, but it feels more like a hack than a fix.

**Comment by pandamicro** [comment]
Fixed in latest versions
