### ISSUE TITLE
ParticleSystem triggers assert if invoke ParticleSystem::addParticle at schedule 

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8441]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5331). It was created at 2014/05/22 09:12:53 +0000
# Description

How to reproduce it:

```
bool init()
{
     ...
     _fire = ParticleFire::create();
     this->addChild(_fire);
     schedule(updateParticle, 0.5);
     ...
}

void updateParticle(float delta)
{
    _fire->addParticle();
}
```

**Comment by pandamicro** [comment]
No assertion found in `ParticleSystem::addParticle`, close
