### ISSUE TITLE
TextField with text cutomization

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8442]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5346). It was created at 2014/05/25 13:03:25 +0000
# Description

It is necessary to have a text field that supports all this:
- text alignment (left, right, center)
- text shadow
- text shadow color, angle, distance
- text stroke

This is very important and I am surprised that it is missing even in cocos2d-x 3.1 version. I belie there are lots of game that input, for example, player name in a fancy designed text field.

It would be nice if this functionality was implemented form `TextBox` rather than for `TextField`, as `TextBox` is easier to use in terms of getting text input. 
- zhangxm added comment:
  Yep. `TextField` will be replaced by `TextBox`.
- naghekyan added comment:
  Good to know that `TextBox` will replace `TextField` :). But text box will support bitmap font? Or it will just support shadow, alignment and so on?
- zhangxm added comment:
  Sorry.
  What i mean is that `TextField` will be merged into UI system.
  And the name may not be `TextBox`. 
  The features you listed may not support at first.

**Comment by shauket** [comment]
Did you solved this issue guys ?? i need to show text in middle of the textfield.

**Comment by Arman92** [comment]
What is the status of this issue? It's pretty old!

**Comment by minggo** [comment]
@zilongshanren what's your plan of this feature request?

**Comment by zilongshanren** [comment]
@minggo  
I think we should focus on improving EditBox, TextField is less powerful and the input experience is not as good as EditBox.

**Comment by minggo** [comment]
@zilongshanren i agree with you.
@Arman92 you can try EditBox.

**Comment by Arman92** [comment]
@minggo ok thank you, 
By the way I have problem with RTL (Right to left) languages (e.g. Persian/Arabic) in EditBox, the glyphs are not loaded and it shows rectangles instead of characters, is it the font file I'm using? Or it's global in Cocos2d?

**Comment by minggo** [comment]
@Arman92 does your environment installs the font you used?
