### ISSUE TITLE
Support Scroll Bars with Native Appearance in UIScrollView and/or CCScrollView

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8446]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5373). It was created at 2014/05/27 08:39:31 +0000
# Description

Please add support for scroll bars with native appearance to UIScrollView and/or CCScrollView.

**Comment by pandamicro** [comment]
Done in v3.8
