### ISSUE TITLE
Default search path on win32 points to current directory not Resources folder

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8451]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5388). It was created at 2014/05/27 19:40:45 +0000
# Description

This is broken on latest v3 branch c44a5a2b3e4f0d4fc80aed6af6b859dd9422162e
s_resourcePath should be appended by "/../Resources/" in checkPath method

static void _checkPath()
{
    if (0 == s_resourcePath.length())
    {
        WCHAR utf16Path[CC_MAX_PATH] = {0};
        GetCurrentDirectoryW(sizeof(utf16Path)-1, utf16Path);

```
    char utf8Path[CC_MAX_PATH] = {0};
    int nNum = WideCharToMultiByte(CP_UTF8, 0, utf16Path, -1, utf8Path, sizeof(utf8Path), NULL, NULL);

    s_resourcePath = convertPathFormatToUnixStyle(utf8Path);
    s_resourcePath.append("/../Resources/");
}
```

}

**Comment by Sheado** [comment]
I just updated to latest and had this issue. It should be:

```
s_resourcePath = convertPathFormatToUnixStyle(utf8ExeDir);
s_resourcePath.append("../../Resources/");
```

**Comment by minggo** [comment]
The search path should be the path that the app lies in, because generated app may be put in any place.
