### ISSUE TITLE
applicationDidEnterBackground not called on win32

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8452]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5389). It was created at 2014/05/27 19:46:49 +0000
# Description

This method used to be called on cocos v2 when window got minimized.
Not working since cocos v3.
- Asmodehn added comment:
  This post seems to be related and may have the solution :
  http://discuss.cocos2d-x.org/t/appdelegate-applicationdidenterbackground-is-not-called-when-the-window-focus-is-lost/13509

**Comment by stevetranby** [comment]
Bump. Is there a best practice method for getting an event for the game window not being active - window focus/blur.

**Comment by minggo** [comment]
I just tested latest codes, the issue is fixed.
