### ISSUE TITLE
在Widget里面的TouchEventType::ENDED消息中，remove自己会死机

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8470]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5551). It was created at 2014/06/12 11:49:44 +0000
# Description

cocos2d-x 3.1.1中，在Widget里面的TouchEventType::ENDED消息中，remove自己会死机

UIWidget.CPP第656行，如果在控件注册TouchEventType::ENDED函数中remove自己，调用removeFromParent，
执行到  if (_touchEventListener && _touchEventSelector)，此时widget已经被释放，这两个指针指向非法的值死机。

请问如何解决？

void Widget::releaseUpEvent()
{

```
if (_touchEventCallback) {
    _touchEventCallback(this, TouchEventType::ENDED);
}

if (_touchEventListener && _touchEventSelector)
{
    (_touchEventListener->*_touchEventSelector)(this,TOUCH_EVENT_ENDED);
}
```

}

**Comment by terryblood** [comment]
我的解决方法是让widget retain一下,虽然有问题,但是至少不会崩掉了,不知道哪位大神有更好的绝招

**Comment by edwardzhou** [comment]
@terryblood
改用 widget->runAction(RemoveSelf::create()); 行不行？

**Comment by pandamicro** [comment]
Removing a node during its event callback is not allowed, you should schedule a task to remove the widget.
