### ISSUE TITLE
Accept Drag-and-Drop Files from Windows Explorer.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8471]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5571). It was created at 2014/06/17 08:01:24 +0000
# Description

Result: glfwSetDropCallback() exclude in the current GLFW version.
Except:
Enable the Drag function code example as following:
HWND hDesktop = GetActiveWindow();
DragAcceptFiles(hDesktop, TRUE); 
glfwSetDropCallback(_mainWindow,GLFWEventHandler::onGLFWWindowDropFunCallback);

Reson: The Drop handler "glfwSetDropCallback()" is missing in current glfw3.h.

**Comment by Cupidazul** [comment]
Hi Minggo,

Is this fixed ? Can we use glfwSetDropCallback and create a DropZone ? 
Is this availlable crossplatforms ? Or is it limited to some ? 
I saw that this was added into IOS_MAC https://searchcode.com/codesearch/view/95986730/ I don't see it on windows / linux / android ; 

Is this feasible ? Can you give me an example ?
