### ISSUE TITLE
RichText ignores fade actions

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8475]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5582). It was created at 2014/06/20 09:25:14 +0000
# Description

RichText ignores fade actions.

For example:
ui::RichText\* richText = ui::RichText::create();
richText->setCascadeOpacityEnabled(true);
ui::RichElementText\* textPart = ui::RichElementText::create(0, Color3B::WHITE, 255, "TEXT", "Arial", 32);
richText->pushBackElement(textPart);
richText->runAction(FadeTo::create(0.5, 0));
- zhangxm added comment:
  Thanks for feedback.
  We will check it.
  What's the engine version you test?
- unoave added comment:
  I use v3.1.1

**Comment by zilongshanren** [comment]
I can confirm this issue on cocos2d-x v3.3rc1. I will fix it later.
