### ISSUE TITLE
Android: Cocos2dxSound::playEffect sometimes returns a wrong streamId so later stopEffect or pauseEffect don’t work correctly

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8479]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5590). It was created at 2014/06/23 08:30:33 +0000
# Description

When a sound file is not preloaded beforehand playEffect starts loading it and waits until it is loaded. This wait is implemented using mSemaphore. The problem is that acquire and release on this semaphore aren’t paired correctly. Release is called in onLoadComplete so basically every time when a sound file is loaded. Acquire is called only by playEffect and only if a file wasn’t preloaded beforehand. So in a scenario when I preloaded a bunch o files, onLoadComplete is called and number of permits held by mSemaphore is set to number of preloaded files. Then when I call playEffect on file which wasn’t preloaded acquire doesn’t block because number of permits in the semaphore is high and playEffect returns invalid streamId value from mStreamIdSyn. 

The fix is to call release only when acquire was called previously. Since instance of SoundInfoForLoadedCompleted  is added to mEffecToPlayWhenLoadedArray only when acquire is called the fix can use this to decide when release should be called.  

```
        public void onLoadComplete(SoundPool soundPool, int sampleId, int status) {
            // only play effect that are in mEffecToPlayWhenLoadedArray
            for ( SoundInfoForLoadedCompleted info : mEffecToPlayWhenLoadedArray) {
                if (sampleId == info.soundID) {
                    if (status == 0)
                    {
                        // set the stream id which will be returned by playEffect()
                        mStreamIdSyn = doPlayEffect(info.path, info.soundID, info.isLoop);
                    } 
                    else 
                    {
                        mStreamIdSyn = Cocos2dxSound.INVALID_SOUND_ID;
                    }

                    // remove it from array, because we will break here
                    // so it is safe to do
                    mEffecToPlayWhenLoadedArray.remove(info);

                    mSemaphore.release();

                    break;
                }
            }
        }

```

**Comment by minggo** [comment]
There is new audio, so please use new audio instead.

**Comment by zjinpeng** [comment]
I got the same problem on android.
CocosDenshion::SimpleAudioEngine::sharedEngine()->playEffect();
I get -1.
v3.7.1
