### ISSUE TITLE
自定义字体的渲染效率

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8480]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5596). It was created at 2014/06/24 04:48:41 +0000
# Description

自定义字体，包括ttf或fnt字体，其渲染效率很低，我创建了10个按钮，共享同一种字体，无论使用ttf还是fnt，GL call的次数都增加了20次，在当前的3.0版本中没有找到合适的优化方法。

**Comment by minggo** [comment]
@Dhilan007 
Could you please take a look?

**Comment by WenhaiLin** [comment]
It will consume more CPU resources if using QuadCommand for reduce GL call

**Comment by WenhaiLin** [comment]
Label has supported auto batch with bitmap font or char map: https://github.com/cocos2d/cocos2d-x/pull/13201
