### ISSUE TITLE
about Animation3D

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8481]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5601). It was created at 2014/06/25 01:35:33 +0000
# Description

Using example c3t files can be normal to play 3d animation, but used 3dmax export FBX convert to c3t file cannot be read properly.
Could you tell me how to convert right c3t file can be read properly?
sorry for my engilsh

http://www.cocoachina.com/bbs/read.php?tid=209637
# Comments

**Comment by minggo** [comment]
@super626 
Any idea of this issue?

**Comment by super626** [comment]
It crashed when multiple texture coordinate exist at that time.
It is fixed now.
However, it will crash when there are 4 texture coordinates (Harrison has commented some).  The best way is that do not bind the predefined attributes.
