### ISSUE TITLE
[WP8][CocosDenshion] stopAllEffects() stops background music

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8483]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5616). It was created at 2014/06/27 15:50:19 +0000
# Description

Hi cocos2d-x team!

I'm using Cocos2d-X in few games and I was porting one of them on Windows Phone 8. I use CocosDenshion and I had no problem on iOS & Android. But on WP8 I had an issue with SimpleAudioEngine::stopAllEffects method.
If I play one or multiple sound effects and a background music then I call:
`SimpleAudioEngine::sharedEngine()->stopAllEffects();`
all sounds are stopped including background music.

I watched the code and the problem is that music and effects are calling the same code. So when it stops effects, it stops also background music.

You could simply fix it by verifying that you don't stop the "effect" that have the same id than the background music.

I will post a code fix later.
- TheArsenik added comment:
  I fixed this issue by ignoring the "sound effect" that corresponds to the background music in `Audio::StopAllSoundEffects`.
  Here is the code 

```
void Audio::StopAllSoundEffects()
{
    if (m_engineExperiencedCriticalError) {
        return;
    }

    EffectList::iterator iter;
    for (iter = m_soundEffects.begin(); iter != m_soundEffects.end(); iter++)
    {
        // Don't stop background music
        if (iter->first == m_backgroundID) {
            continue;
        }
        StopSoundEffect(iter->first);
    }
}
```

But there is the same problem in `Audio::PauseAllSoundEffects` and `Audio::ResumeAllSoundEffects`. I also fixed them by the same if statement.
Here is the code:

```
void Audio::PauseAllSoundEffects()
{
    if (m_engineExperiencedCriticalError) {
        return;
    }

    EffectList::iterator iter;
    for (iter = m_soundEffects.begin(); iter != m_soundEffects.end(); iter++)
    {
        // Don't pause background music
        if (iter->first == m_backgroundID) {
            continue;
        }
        PauseSoundEffect(iter->first);
    }
}

void Audio::ResumeAllSoundEffects()
{
    if (m_engineExperiencedCriticalError) {
        return;
    }

    EffectList::iterator iter;
    for (iter = m_soundEffects.begin(); iter != m_soundEffects.end(); iter++)
    {
        // Don't resume background music
        if (iter->first == m_backgroundID) {
            continue;
        }
        ResumeSoundEffect(iter->first);
    }
}
```

I hope this fix will be included in Cocos2d-x-2.x soon.

**Comment by ghost** [comment]
Already fixed in https://github.com/cocos2d/cocos2d-x/pull/6243
More information about this http://www.cocos2d-x.org/issues/4762
