### ISSUE TITLE
[WP8] Inconsistent behaviour

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8485]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5623). It was created at 2014/06/29 08:16:44 +0000
# Description

On Android pressing the back button generates a key press/release event with the `KEY_ESCAPE` keycode. On WP8 the application simply exits, making scene transitions impossible.

Moreover, calling `Director::getInstance()->end()` on WP8, freezes the app but does not exit. This is contrary to behavior on other platforms.

Expected the same behavior on all platforms.

**Comment by pyrosphere** [comment]
I solved these issues for my game by doing some minor changes to cocos2d/cocos/platform/wp8/CCGLView.cpp (on v3.2, on the current version this file seems to have been renamed to CCGLViewImpl-wp8.cpp):

```
void GLView::end()
{
    m_windowClosed = true;
    if (m_delegate)
    {
        // Terminate app on Director::getInstance()->end();
        m_delegate->Invoke(Cocos2dEvent::TerminateApp);
    }
}

void GLView::OnBackKeyPress()
{
    // Dispatch keyboard events instead of always terminating app on back key press
    EventKeyboard event(EventKeyboard::KeyCode::KEY_ESCAPE, false);
    Director::getInstance()->getEventDispatcher()->dispatchEvent(&event);
}
```
