### ISSUE TITLE
[GENTOO] cocos compile -p linux. SIZE_MAX, UINT32_MAX macros not found

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8488]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5631). It was created at 2014/06/30 19:57:34 +0000
# Description

Game compilation via **cocos compile -p linux** fails on _Gentoo-linux_ while compiling **jsbinding_ui** library.

Compilation error (cut from log):

```
../frameworks/js-bindings/external/spidermonkey/include/linux/js/HashTable.h: In static member function 'static js::detail::HashTable<T, HashPolicy, AllocPolicy>::Entry* js::detail::HashTable<T, HashPolicy, AllocPolicy>::createTable(AllocPolicy&, uint32_t)':
../frameworks/js-bindings/external/spidermonkey/include/linux/js/HashTable.h:983:39: error: 'SIZE_MAX' was not declared in this scope
../frameworks/js-bindings/external/spidermonkey/include/linux/js/HashTable.h: In member function 'bool js::detail::HashTable<T, HashPolicy, AllocPolicy>::init(uint32_t)':
../frameworks/js-bindings/external/spidermonkey/include/linux/js/HashTable.h:1021:55: error: 'UINT32_MAX' was not declared in this scope
... and so on
```

To solve this:
- Open main projects **CMakeList.txt**;
- Find and change line:
  `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`  
  to this one: `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -D__STDC_LIMIT_MACROS")`

**Comment by Islam94** [comment]
Hello,

I am trying to install opencv on a beagleboneblack to use in a school project but this error pops up when running the command line make

Please help...
![capture2](https://cloud.githubusercontent.com/assets/24612503/21275159/514c9172-c380-11e6-962d-3aeaa0be461a.PNG)

**Comment by minggo** [comment]
I think you should read the documentation of opencv about the compiling environment.
