### ISSUE TITLE
RenderTexture Save To File - Incorrect Results

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8489]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5645). It was created at 2014/07/02 17:36:11 +0000
# Description

Please see this thread:

http://discuss.cocos2d-x.org/t/rendertexture-save-to-file-incorrect-results/15273

**Comment by minggo** [comment]
I think it is fixed.
@huangshiwu Could you please verify it?

**Comment by hawkwood** [comment]
This is probably related to the issue I just experienced:
http://discuss.cocos2d-x.org/t/rendertexture-renders-partially-darker-than-what-is-displayed-when-using-a-blendfunc-and-clippingnode-update/21688/5
