### ISSUE TITLE
UIButton - can’t set title colour independently of button color

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8490]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5646). It was created at 2014/07/02 17:42:37 +0000
# Description

Please see this thread:

http://discuss.cocos2d-x.org/t/uibutton-cant-set-title-colour-independently-of-button-color/15173

**Comment by minggo** [comment]
@andyque 
It is fixed, right?

**Comment by zilongshanren** [comment]
@minggo 
Yes, it's already fixed.
Now we have `setColor` for changing button's color and `setTitleColor` for changing button title color only.
