### ISSUE TITLE
setPositionZ - no effect

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8491]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5647). It was created at 2014/07/02 17:45:14 +0000
# Description

Using setPositionZ can have no effect if a node's x and y position don't change, but the z position does.

This is because setPosition, which setPositionZ calls, checks to see if x and y have changed, but not z. So if z changes, but x and y don't, then the new z position doesn't take effect.

**Comment by dabingnn** [comment]
There is a bug of calling `setPosition3D` with the same x and y in old version. It has been fixed.
I have tested the bug against the newest version of cocos2d-x, there is no bug in the newest version.
