### ISSUE TITLE
FATAL ERROR: after Label::createWithBMFont

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8492]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5648). It was created at 2014/07/03 03:18:04 +0000
# Description

Fatal error occurs when you create label with createWithBMFont, and have a Chinese or Japanese character string that is longer than one line and you set dimensions that are not enough to fit the string.

Code to reproduce error:
    Size dim = Size(92,60);
    auto label1 = Label::createWithBMFont("fonts/bitmapFontChinese.fnt", "中国中国", TextHAlignment::CENTER, dim.width);
    label1->setPosition(100,100);
    label1->setDimensions(dim.width, dim.height);
    addChild(label1);

Cocos2dx version 3.1.1

**Comment by WenhaiLin** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/8580

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8854
