### ISSUE TITLE
LuaStack::executeFunctionReturnArray low bug

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8493]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5649). It was created at 2014/07/03 06:00:48 +0000
# Description

int LuaStack::executeFunctionReturnArray(int handler,int numArgs,int numResults,__Array& resultArray)
{
    if (pushFunctionByHandler(handler))  
    {
        if (numArgs > 0)
        {
              ....
        }
    }
    lua_settop(_state, 0);
    return 1;
}

if numArgs==0  function skip all processing

**Comment by samuele3hu** [comment]
This problem has already fixed in the early version.
