### ISSUE TITLE
UIScrollView inertia bugs

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8495]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5652). It was created at 2014/07/03 15:48:12 +0000
# Description

In 3.2alpha0 there are a few bugs with a UIScrollView's inertia behaviour.

Firstly, at the top of:

ScrollView::scrollChildrenVertical
ScrollView::scrollChildrenHorizontal
ScrollView::scrollChildrenBoth

scrollenabled should be set to true.

Then there is a second issue.

If a scroll view contains child widgets such as UIButtons, these can break the inertia behaviour if the user performs the scrolling by touching the child objects.

This is because in UIScrollView's interceptTouchEvent, _touchBeganPosition and _touchEndPosition need to be updated with the child widget's _touchBeganPosition and _touchEndPosition values.

So in interceptTouchEvent, add the additional lines shown below:

```
    case TouchEventType::BEGAN:
        _touchBeganPosition.x = touch->getStartLocation().x; // add this

    case TouchEventType::ENDED:
        _touchEndPosition.x = touch->getLocation().x; // add this
```

**Comment by zilongshanren** [comment]
@minggo 
This issue doesn't exists in the latest code base.  I think we could safely close it now.
