### ISSUE TITLE
No binding for EditBox::setDelegate, so you cann't receive the change message for editbox in lua

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8500]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5660). It was created at 2014/07/04 14:11:04 +0000
# Description

there is no binding for the EditBox::setDelegate in lua, so there's no way for receiving the msg of changing of editbox, suggesting that you can add the interface of setDelegate in lua or change the code to send the changed event to lua engine even that you didnot invoke the setDelegate

**Comment by zilongshanren** [comment]
should be fixed now.
