### ISSUE TITLE
V3.2RC0 Label have some bugs on Android with TTF font

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8508]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5691). It was created at 2014/07/08 13:09:15 +0000
# Description

用自己的TTF文件创建的Label会在安卓上产生各种显示问题，经常运行了一阵以后就出现如下截图的各种问题。

有时候是切换到桌面再切换回来的时候也会有问题。

不知道是不是因为有些字是设置了outline的原因。
# Comments

**Comment by WenhaiLin** [comment]
@minggo Confirmed fixed in v3 branch.We should close this issue.

**Comment by ahmed-belal** [comment]
@Dhilan007 Can you please guide me to the commit in which this issue is fixed? I am having LabelTTF turning to black boxes after switching to home screen and back on android, using v3.2.
