### ISSUE TITLE
cocos2d-x 3.2 rc0  ui::PageView Controller Crash When call removeAllPage() without onExit()

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8512]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5711). It was created at 2014/07/11 10:08:18 +0000
# Description

when PageView onEnter it is start scheduleUpdate();

and the update() across the code that access to _leftBoundaryChild or _rightBoundaryChild member.

However，when the removeAllPages() is called,but _leftBoundaryChild is not be update by call  updateBoundaryPages()， so the _leftBoundaryChild is invalid,and then crash!

solution:
add updateBoundaryPages() to removeAllPages() and removePageAtIndex() ..

**Comment by minggo** [comment]
@anyque
Could you please take a look?

**Comment by zilongshanren** [comment]
I have worked out a tests but I can't reproduce this issue. 
The left and right boundary child will be updated when layout is dirty.
So I think there is no problem here.
