### ISSUE TITLE
Label:The letters sometimes slightly cut.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8516]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5734). It was created at 2014/07/21 02:08:03 +0000
# Description

This thread http://discuss.cocos2d-x.org/t/cocos2d-v3-label-bugs-cannot-disable-outline-labels-cut/15623/2 reported the issue.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/7770
