### ISSUE TITLE
LabelTTF's setFontFillColor doesn't work correctly on mac

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8517]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5739). It was created at 2014/07/22 04:06:26 +0000
# Description

This issue was already reported as Bug #5578 for ios.

But it still exist on mac. So every time I upgrade to latest cocos2d, I have to manually replace some codes like this:

Change from:
cocos2d_libs.xcodeproj/platform/mac/CCDevice.mm#235

```
 if (! _initWithString(text, align, textDefinition._fontName.c_str(), textDefinition._fontSize, &info, nullptr)) //pStrokeColor))
  { 
    break;
  }
```

to:

```
  Color3B color = textDefinition._fontFillColor;

  if (! _initWithString(text, align, textDefinition._fontName.c_str(), textDefinition._fontSize, &info, &color)) //pStrokeColor))
  { 
    break;
  }
```

My project has some requirement of display Text on Mac, so It would be kind if cocos2dx team could resolve this issue in future release.

**Comment by minggo** [comment]
@Dhilan007 
Could you please take a look?

**Comment by WenhaiLin** [comment]
@minggo Confirmed fixed in v3 branch.We should close this issue.
