### ISSUE TITLE
Cocos2d-x 3.2 : addChild after drawing ListView

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8521]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5748). It was created at 2014/07/25 08:37:05 +0000
# Description

Hi,

I found a bug using ListView with Cocos2d-x 3.2 release.
My scenario is like the following.

Layout \* m_Layout = static_cast<Layout *>(GUIReader::getInstance()->widgetFromJsonFile("some.ExportJson"));
auto listView = static_cast<ListView *>(m_Layout->getChildByName("list"));
<< add some rows into listView >>
this->addChild(m_Layout);

auto label = LabelTTF::create("Hello World", "Arial", 24);
label->setPosition(Vec2(100, 100));
this->addChild(label);

After label is added, the listView is gone. But,

m_Layout->addChild(label);

this is ok.

Anyway, in Cocos2d-x 3.1, this->addChild(label) was also ok.

Please look into it.

Thanks and regards,
Junhee

**Comment by minggo** [comment]
@andyque 
Could you please take a look?

**Comment by zilongshanren** [comment]
@minggo 
I think this issue is related with `_orderOfArrival(0)`, I have fixed it at https://github.com/cocos2d/cocos2d-x/pull/8009
