### ISSUE TITLE
Bug Report   tolua_cocos2dx_GLProgram_setUniformLocationF32

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8522]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5749). It was created at 2014/07/25 09:17:51 +0000
# Description

tolua_cocos2dx_GLProgram_setUniformLocationF32 implements seems wrong, especailly when you get f2, f3, f4 from stack top 3(actually it is f1) and if there are 5 argcs which is very frequently used cocos will never get to the right process cause the absent minded copy pasted code. Hope you will fix it soon, thanks~

**Comment by minggo** [comment]
@samuele3hu 
Could you please take a look?

**Comment by samuele3hu** [comment]
This problems caused by the copy-pasted code exist.

**Comment by minggo** [comment]
Is it fixed?

**Comment by samuele3hu** [comment]
Already fixed,I will give a pr soon.

**Comment by samuele3hu** [comment]
The related pr is https://github.com/cocos2d/cocos2d-x/pull/8856.
