### ISSUE TITLE
RelativePath Android - back directory issue

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8523]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5752). It was created at 2014/07/25 11:42:09 +0000
# Description

When relative path contains "back folder" such as: map/../sprite/background.png
then I get exception: asset is nullptr.
In win32 project is OK, and also when I've removed back folder part of path.

**Comment by minggo** [comment]
Yep, it may have problem.
Because it is in .apk file.
But i think we should make it work.

**Comment by WenhaiLin** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/8640

**Comment by litefeel** [comment]
fixed at #8204
