### ISSUE TITLE
UserDefault::getInstance()->isXMLFileExist() is invalid on the android devices.

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8527]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5837). It was created at 2014/08/21 04:06:58 +0000
# Description

`UserDefault::getInstance()->isXMLFileExist()` is always return false on the android devices.

**Comment by minggo** [comment]
Yep, now `UserDefault` doesn't  use xml file to story values. It uses Android preferences. So please don't use this API.

**Comment by joewan** [comment]
we should give some asserts when developers use this API or print some warnings.

**Comment by minggo** [comment]
Yep, i think you are right.

@Dhilan007 
Could you please fix it.

**Comment by Kingson** [comment]
same issue on iOS device, any solution for this？（cocos2d-x 2.2.6）
