### ISSUE TITLE
ActionNode::initWithBinary have initialization sequence issue

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8529]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5852). It was created at 2014/08/25 17:49:42 +0000
# Description

in ActionNode::initWithBinary need read "tweenType" first before other property such as positon, to make the tween work Correct.
but the CSB（use cocosstudio 1.6.0） file store "positon" before "tweentype",so the code should change or csb file should.

**Comment by minggo** [comment]
@chengstory
Could you please take a look?

**Comment by lbfamous** [comment]
excuse me,Is this bug fixed or not ?

**Comment by pandamicro** [comment]
ActionNode is no longer being maintained, please use Cocos Studio v2.x
