### ISSUE TITLE
void ActionManagerEx::initWithBinary only read first animation

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8530]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5853). It was created at 2014/08/25 17:55:49 +0000
# Description

in void ActionManagerEx::initWithBinary, there is a type error.
is always use the first actionnode to init animation action.

this line 
action->initWithBinary(cocoLoader, actionNode->GetChildArray(cocoLoader), root);
should be
action->initWithBinary(cocoLoader, actionNode->GetChildArray(cocoLoader)[i], root);

or such equal.

**Comment by minggo** [comment]
@chengstory
Could you please take a look?

**Comment by chengstory** [comment]
I think it is right!

**Comment by minggo** [comment]
I think it is duplicated with #8653.

**Comment by minggo** [comment]
Duplicate with #8563.
