### ISSUE TITLE
Black flicker on iOS launch

### ISSUE THREAD

**Issue by pyrosphere** [cocos2d/cocos2d-x#8540]
There seems to be an issue when launching a cocos2d-x v3 app on iOS. The screen goes black for a split second when the app starts, after the splash image. This is especially noticeable when the splash image and the first scene are the same or similar.

I checked the HelloCpp sample on v2.2.5, and there's a smooth cross fade transition between the splash image and the first scene. I made it more noticeable by making the HelloWorldScene background be the splash image:

```
    CCSprite* pSprite = CCSprite::create("Default-568h@2x.png"); // splash image for the iPhone 5
    pSprite->setRotation(90);
```

Then I checked the launch on v3.2, v3.3beta0 and on the current repository and, when launching, the screen shows the splash image, then the first scene fades in from black. It takes less than a second and is a minor difference, but it makes the launch look more disagreeable compared to v2.

I tried looking into it, but wasn't able to tell what is making v2 and v3 look different when launching.

**Comment by minggo** [comment]
@huangshiwu
Could you please take a look?

**Comment by ghost** [comment]
I have checked this issue and I found that may due to SDK version's different: iOS7.1 has the problem. iOS8.0 and iOS7.0 are ok. 
@pyrosphere Can you help to test if it is the reason?

**Comment by pyrosphere** [comment]
@huangshiwu You are right, I updated one of my devices from 7.1 to 8.0 and there's no flicker anymore.
I don't know about 7.0. Also tested it on a 5.1.1 and the flicker is there too. 

I put together a workaround method removeFlicker: in AppController.mm called after initializing the window. It basically creates a UIImageView with the launch image behind the GL view and removes it after a few seconds. It's far from elegant but gets the job done for now:

```
#define IS_IPAD (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
#define IS_SIZE(s) ([[UIScreen mainScreen]bounds].size.height == (s) || [[UIScreen mainScreen]bounds].size.width == (s))
- (void)removeFlicker {
    NSString *launch = @"LaunchImage-iOS"; // name in the .xcasset
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) { // iPad
        launch = @"LaunchImage-Portrait";
    } else { // iPhone
        if (IS_SIZE(568)) {
            launch = @"LaunchImage-iOS-568h";
        } else if (IS_SIZE(667)) {
            launch = @"LaunchImage-iOS-800-667h";
        } else if (IS_SIZE(736)) {
            launch = @"LaunchImage-iOS-800-Portrait-736h";
        }
    }
    UIImageView *view = [[UIImageView alloc] initWithImage:[UIImage imageNamed:launch]];
    [window addSubview:view];
    [view performSelector:@selector(removeFromSuperview) withObject:nil afterDelay:4.0];
}
```

**Comment by minggo** [comment]
>  Also tested it on a 5.1.1 and the flicker is there too

Did you mean Xcode 5.1.1?

I think we can not fix like this:
- it is not elegant
- most devices will update to iOS 8

@pyrosphere 
I think we should fix it if there is an elegant version.
But the your method is good for the guys who want it.

**Comment by pyrosphere** [comment]
I meant iOS 5.1.1 on another device. I keep an iPhone with an old version of iOS just to make sure things run in there.

I wasn't suggesting using this workaround on cocos2d-x itself, just showing a way someone might still get a smooth transition in their own game if they really wanted.

Overall it's already a minor issue and you're right, since most devices are updating to 8.0, it will become even less of an issue.

**Comment by minggo** [comment]
@pyrosphere 
Yep, your solution is good for guys who want.
Thanks.
