### ISSUE TITLE
[c++, CocoStudio] TextField for Password

### ISSUE THREAD

**Issue by mingzhej** [cocos2d/cocos2d-x#8553]
![textfield for password 1 normal mode](https://cloud.githubusercontent.com/assets/9006659/4504010/16c63d5c-4ae0-11e4-94bb-624895bac4dc.jpg)
![textfield for password 2 edit mode](https://cloud.githubusercontent.com/assets/9006659/4504011/16cd4fa2-4ae0-11e4-8cc9-236ee50c1cde.jpg)
When I click password input editor, it shows real password characters.
I'd like to show " \* "s instead of real password characters on edit mode.

**Comment by minggo** [comment]
What's the engine version?
And what platform did you test on?

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
