### ISSUE TITLE
Unable to execute dex: Multiple dex files define Lorg/cocos2dx/lib/Cocos2dxAccelerometer;

### ISSUE THREAD

**Issue by stblue** [cocos2d/cocos2d-x#8555]
i have downloaded cocos2d x v3.3 beta and created a project in windows using this command

cocos.py new Tutorialv3cocos -p com.ghostdreamstudo.learning -l cpp -d D:\Development\Learning

Then i have imported project to eclipse and tried to run but eclipse gives me following error

[2014-10-03 18:40:39 - Dex Loader] Unable to execute dex: Multiple dex files define Lorg/cocos2dx/lib/Cocos2dxAccelerometer;
[2014-10-03 18:40:39 - Tutorialv3cocos] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lorg/cocos2dx/lib/Cocos2dxAccelerometer;

Does anyone face the same problem or know how to solve this issue??

**Comment by minggo** [comment]
Did you import more than one Android project that contains `org/cocos2dx/lib/Cocos2dxxxx.java`?

**Comment by swastikit** [comment]
I also have same issue.
And yes I am importing two projects which uses cocos2dx v2.3.x and another one using v3.1.x.
How to fix the issue? please help.

**Comment by minggo** [comment]
It is better to remove one of them.

**Comment by swastikit** [comment]
The two projects are two game apps and we want to put both of them in 1 app.

**Comment by ijunaid** [comment]
Same Issue :( as "swastikit" facing.

@minggo Can you please tell the better solution as we are also facing the same issue and we are using two game projects (cocos2dx projects) in one android app.

**Comment by minggo** [comment]
Hi guys,

Could you show us how to reproduce it step by step?

**Comment by minggo** [comment]
@Dhilan007 
Could you please take a look?

**Comment by jooddang** [comment]
I have the same issue.. Did you fix it?

**Comment by minggo** [comment]
Did you copy cocos2d-x java codes into your project?
You should reference the project.
More detail information please refer to [this document](http://cocos2d-x.org/programmersguide/C/).

**Comment by jooddang** [comment]
I didn't copy it. I reference it from $(AndroidProjectDir)/../cocos2d/cocos/platform/android/java . But somehow, cocos2dx path was on project property -> Java Build Path -> Source. And, I resolved this problem by removing it.

**Comment by minggo** [comment]
@jooddang 
How did you resolve it?
Modify which file?

**Comment by jooddang** [comment]
![screenshot 2015 01 06 21 52 55](https://cloud.githubusercontent.com/assets/1115552/5641499/adc9b248-95ee-11e4-9724-0429f9888428.png)
like this, I removed the cocos2dx path from source path..

**Comment by quanghoangminh** [comment]
thanks jooddang, it work fine for me.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9897

**Comment by CarineAmiot** [comment]
Thanks for your help.
