### ISSUE TITLE
cocos2d-x 3.2: ui::ListView cause display problem on xiaomi phone and xiaomi pad

### ISSUE THREAD

**Issue by yscheng** [cocos2d/cocos2d-x#8560]
Once create a ui::ListView in a layer with a background sprite, screen shows white background with a green rectangle. Only found the problem in xiaomi phone and xiaomi pad.

Failed to upload a screenshot, tried many times.

**Comment by minggo** [comment]
@andyque 
Could you please take a look?

**Comment by zilongshanren** [comment]
@yscheng 
Have you enabled the Stencil buffer? You could take a loot at [this post](http://discuss.cocos2d-x.org/t/problem-with-uiscrollview-and-uilistview/16324) for more information.

**Comment by minggo** [comment]
@yscheng 
Any update?

**Comment by yscheng** [comment]
Hi, sorry for the delay. The problem is solved after enabled Stencil Buffer, thank you.
