### ISSUE TITLE
Win32: Webview introduces dependency on MS ATL.

### ISSUE THREAD

**Issue by CraigJamesMitchell** [cocos2d/cocos2d-x#8561]
UIWebViewImpl-win32.cpp includes atlbase.h etc...
These headers are not part of VS2013 Express (and possibly earlier versions.)
There appears to be no way to get the headers except by using paid-for versions of VS.

**Comment by minggo** [comment]
@andyque 
Could you take a look please.

@gin0606 
Could you please take a look?

**Comment by summerinsects** [comment]
I'm so sorry for that.
There may be some way to solve this issue(refer to http://stackoverflow.com/questions/2681050/atlbase-h-not-found-when-using-visual-c-express-2010/7885201#7885201)

**Comment by minggo** [comment]
I didn't find a way to fix it.
Does ATL needed?
Can we use other functions instead?

**Comment by summerinsects** [comment]
Yes. My implementation depends on ATL. If there is no way to fix it, revert my PR.
I'm very sorry about that

**Comment by minggo** [comment]
@andyque yque
Could you please fix this issue ASAP?
It will break many developers.

Thanks.

**Comment by zilongshanren** [comment]
@minggo  ok.

**Comment by minggo** [comment]
@andyque 
Could you please revert it currently, and re-add it after it is fixed.
