### ISSUE TITLE
UIEditbox setMaxLength is invalid in mac

### ISSUE THREAD

**Issue by vvhh2002** [cocos2d/cocos2d-x#8562]
the UIEditBox-Impl-mac.mm should change like this:

/**
- Called each time when the text field's text has changed.
  */
  - (void)controlTextDidChange:(NSNotification _)notification
    {
    if (getEditBoxImplMac()->getMaxLength() > 0)
        {
          NSTextField_ textField = [notification object];
          NSString\* value = [textField stringValue];
          if ([value length] > getEditBoxImplMac()->getMaxLength())
              { [textField setStringValue:[value substringWithRange:NSMakeRange(0, getEditBoxImplMac()->getMaxLength())]];
              }
          else
              { [textField setStringValue:value];
              }
        }
    cocos2d::extension::EditBoxDelegate\* pDelegate = getEditBoxImplMac()->getDelegate();
    if (pDelegate != NULL)
    {
    pDelegate->editBoxTextChanged(getEditBoxImplMac()->getEditBox(), getEditBoxImplMac()->getText());
    }
# if CC_ENABLE_SCRIPT_BINDING

```
cocos2d::extension::EditBox*  pEditBox= getEditBoxImplMac()->getEditBox();
if (NULL != pEditBox && 0 != pEditBox->getScriptEditBoxHandler())
{
    cocos2d::CommonScriptData data(pEditBox->getScriptEditBoxHandler(), "changed",pEditBox);
    cocos2d::ScriptEvent event(cocos2d::kCommonEvent,(void*)&data);
    cocos2d::ScriptEngineManager::getInstance()->getScriptEngine()->sendEvent(&event);
}
```
# endif

}

**Comment by minggo** [comment]
@andyque 
Could you please take a look?

**Comment by zilongshanren** [comment]
@vvhh2002 
Thanks, your fix works but I think it's not the perfect way to restrict max length of NSTextField.
Here is a link explains why: http://stackoverflow.com/questions/827014/how-to-limit-nstextfield-text-length-and-keep-it-always-upper-case

I will try to fix this issue by applying the method proposed in stackoverflow.
