### ISSUE TITLE
In cocostudio, ActionManagerEX::initWithBinary,  it can only load one UI animation

### ISSUE THREAD

**Issue by coldfog** [cocos2d/cocos2d-x#8563]
I used cocostudio UI Editor to add three UI animation in my game. And I find the method ActionManagerEX::initWithBinary could only load the first UI animation in my editor. After I read the source code of cocos2dx. I think it's a bug. 
In file  `cocos / editor-support / cocostudio / CCActionManagerEx.cpp` line 106:

```
action->initWithBinary(cocoLoader, actionNode->GetChildArray(cocoLoader), root);
```

It should be changed to

```
action->initWithBinary(cocoLoader, &actionNode->GetChildArray(cocoLoader)[i], root);
```

**Comment by minggo** [comment]
@chengstory
Could you please take a look?

**Comment by chengstory** [comment]
Thanks @coldfog!  You are right!  @minggo It  can be merged!

**Comment by minggo** [comment]
@chengstory
It is an issue. 
Not a pull request.

Could you please send a pull request for it?

**Comment by coldfog** [comment]
@minggo I have sent a pull request just now.[#8657](https://github.com/cocos2d/cocos2d-x/pull/8657)

**Comment by minggo** [comment]
Thanks @coldfog .
