### ISSUE TITLE
ui::Button Title Only Content Size Not Available Immediately

### ISSUE THREAD

**Issue by ahlwong** [cocos2d/cocos2d-x#8567]
In Cocos2d-x 3.3beta0

When creating a button with a title only, the buttons content size is not immediately updated.

Button\* button = Button::create();
button->setTitle("My Title");
button->getContentSize(); // == Size::ZERO, not available yet

I fixed this by adding an updateSizeAndPosition to setTitleText

void efcc::Button::setTitleText(const std::string& text)
{
    ui::Button::setTitleText(text);
    updateSizeAndPosition(_parent ? _parent->getContentSize() : Size::ZERO);
}

**Comment by minggo** [comment]
@andyque 
Could you please take a look?

**Comment by zilongshanren** [comment]
@ahlwong 
Thanks, I have confirmed the issue.
Consider your fix, I think the following way would be better:

```
void Button::setTitleText(const std::string& text)
{
    _titleRenderer->setString(text);
    if (_ignoreSize)
    {
        Size s = getVirtualRendererSize();
        this->setContentSize(s);
    }
}
```

Because `updateSizeAndPosition` is used for updating children node's size and position.

What's your opinion?

**Comment by zilongshanren** [comment]
@ahlwong 
I have created a patch here: https://github.com/cocos2d/cocos2d-x/pull/8606  
If you find any issues, please let me know.
