### ISSUE TITLE
LabelAtlas opacity do not change when setting parent node's opacity

### ISSUE THREAD

**Issue by weibobo** [cocos2d/cocos2d-x#8569]
cocos2dx version: 3.2
Add LabelAtlas to a node, and set node->setCascadeOpacityEnabled(true),  then node->setOpacity(128) do not affect labelAtlas

**Comment by weibobo** [comment]
test code:
    local testbb = cc.LabelAtlas:_create("123456789", "ui/battle_font.png", 43, 62, 48)
    testbb:setPosition(cc.p(50,50))

```
local node = cc.Node:create()
node:setCascadeColorEnabled(true)
node:setCascadeOpacityEnabled(true)
node:addChild(testbb)    
self:addChild(node)
node:setOpacity(128)
```

**Comment by minggo** [comment]
@Dhilan007 
Could you please take a look?

**Comment by WenhaiLin** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/8573
