### ISSUE TITLE
Scale9Sprite's bounds clip its content

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#8581]
Scale9Sprite's bounds' zOrder equals to 1 or 2 which can be seen in Scale9Sprite::updateWithBatchNode. This will due to an annoying problem that its content can be clipped by the bounds. 

While the content node is added to a Scale9Sprite without indicate the zOrder, the content node's zOrder will be 0 which is smaller than the bounds. And the clip effect can be reproduced. Please refer to these two image:

![clipped](https://cloud.githubusercontent.com/assets/632460/4557755/cee8a89e-4ed6-11e4-8f4b-3d7f1381210c.jpg)
![correct](https://cloud.githubusercontent.com/assets/632460/4557756/d6ccad94-4ed6-11e4-972c-aa462e99e0ee.jpg)

I consider it as an issue of our engine, because user should be free to choose the zOrder of the child node, however, a zOrder smaller than 2 isn't a good choice in Scale9Sprite.

**Comment by minggo** [comment]
@andyque 
Please take a look.

**Comment by zilongshanren** [comment]
@pandamicro 
What's the engine version to reproduce this issue?
I think it should be fixed after v3.2.

**Comment by pandamicro** [comment]
Thanks for confirming it
