### ISSUE TITLE
Opacity for Labels in 3.3beta0 on Win32

### ISSUE THREAD

**Issue by metalpasman** [cocos2d/cocos2d-x#8582]
Hi, there is an issue with opacity in Labels create with createWithBMFont() on Win32 platform. Neither setOpacity nor actions like FadeIn/FadeOut/FadeTo work. 

Also cpp-tests related to this do not work either.

TTF Labels work properly.

Thank you.

**Comment by metalpasman** [comment]
label->setOpacityModifyRGB(true) does the trick

**Comment by WenhaiLin** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/8588
