### ISSUE TITLE
CCLabel enableOutline shift on Android Cocos2d-x 3.3beta0

### ISSUE THREAD

**Issue by ahlwong** [cocos2d/cocos2d-x#8583]
EDIT:
After looking into the problem further I was able to replicate the issue on iOS too. The issue is related to TTFConfig fonts vs SystemFonts. I was loading fonts by the font name on iOS and by their resource path on Android. When I switched to loading Fonts by their resource path on iOS, I encountered the same issue.

Either way, the issue is that when you enableOutline on a TTFConfig font, the text is rendered in a higher position. It should render in-place.

ORIGINAL:
On Android when you enableOutline on a CCLabel it causes the text to shift positions up. (Tested on multiple Android devices)

It looks as though the text is positioned so that the anchor is BOTTOM even though it reads and is set as MIDDLE. The shift does not occur on iOS devices.
![screen](https://cloud.githubusercontent.com/assets/1441263/4569044/8aab68fc-4f43-11e4-9f68-c4ac6ce6102b.jpg)

**Comment by minggo** [comment]
@Dhilan007 
Could you please take a look?

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8904

**Comment by ahlwong** [comment]
Fixed!

**Comment by mirth** [comment]
It have occurred for me on 3.6. It also happens in Cocos Studio (2.3.2 Beta). 
![outline](https://cloud.githubusercontent.com/assets/1296970/9664401/37c552e6-5272-11e5-9533-f7d7fd62dcfd.png)
What is more it only occures when outline size is >1.

**Comment by WenhaiLin** [comment]
@mirth Please try fix it by apply this pr:https://github.com/cocos2d/cocos2d-x/pull/11720

**Comment by mirth** [comment]
Unfortunately it didn't help.

**Comment by mirth** [comment]
Resolved by increasing the label node content size.
