### ISSUE TITLE
CCSpriteNode heirarchy

### ISSUE THREAD

**Issue by onedayitwillmake** [cocos2d/cocos2d-x#859]
Hello,

I have a CCSpriteBatchNode, with a texture of for example the alphabet.

I'm attempting to create a simple display hierarchy in which, i can create a abstract 'wordEntity' which is added to the alphabetBatchNode, but is in reality composed of for example 5 'letterEntities'
The reason I want to do this, is because I want the 'word' transformations applied to the 'wordEntity' such as position, rotation, etc, to be applied to the 'letterEntities'

This seems like a very normal usage, and it works.
Except once I create the second entity it crashes the application.

If I do not add the second 'wordEntity' to the display hierarchy everything is fine, except of course I cannot see it.
If I add only the second letter to the display hierarchy, and not the first everything is also fine.
If add the 'letterEntity's to the alphabetBatchNode directly, everything also is fine.

So i do not believe the error i in my creation of the objects etc.
Is this a bug in Cocos2d? I've used the same methodology in a game for Cocos2D-iphone

**Comment by donaldalanmorrison** [comment]
@onedayitwillmake Can you post the code and the errors?

**Comment by godyZ** [comment]
onedayitwillmake Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August
