### ISSUE TITLE
MultiTouchTest behave wrongly if moving two fingers quickly

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8597]
- run cpp-tests
- goto MultiTouchTest
- two fingers touch the screen
- moving two fingers quickly

Then you will found the line of color changed.

**Comment by masterhou** [comment]
Hi, guys, have some feedback?
I test iOS 8, I think g_touchIdReorderMap's key is Touch ptr, the ptr mybe changed, so, the index changed.

**Comment by dumganhar** [comment]
@masterhou, I could not reproduce this issue on my iOS8 device(ipad2 v8.1).
Which device were you testing on?

**Comment by pandamicro** [comment]
If there is further informations, I will reopen it
