### ISSUE TITLE
cocos studio for mac ,the PageView can't turn page!!!

### ISSUE THREAD

**Issue by chenleijava** [cocos2d/cocos2d-x#8600]
hello cocos team, i export ui form cocos studio in windows,
auto node = GUIReader:getInstance()->widgetFromJsonFile(filename) ,ok work well under the mac .
but when i export ui form cocos studio for mac,using this way .
NodeReader::getInstance()->createNode(filename);
then page can't turn.  but  the studio for mac of simulator work well ! it's a "坑 啊"，噗～～～～

**Comment by chengstory** [comment]
Thanks @chenleijava ,  I ask @pipu to check it.

**Comment by joewan** [comment]
I also met some similar problems,
Some UI files can not show correct content on android.

发自我的 iPad

**Comment by pandamicro** [comment]
It should already been fixed
