### ISSUE TITLE
Where is Dragonbone Design Panel for cocos2dx v2 and cocos2dx v3 ? 

### ISSUE THREAD

**Issue by kameal** [cocos2d/cocos2d-x#8607]
I found that Armature support load data from DragoboneDesignPanel export data (.xml file).
https://github.com/dumganhar/ccs-res/blob/v3/armature/robot.xml
https://github.com/dumganhar/ccs-res/blob/v3/armature/knight.xml
https://github.com/dumganhar/ccs-res/blob/v3/armature/cyborg.xml
https://github.com/dumganhar/ccs-res/blob/v3/armature/Dragon.xml
. I try hard to find that tool match with cocos2dx but not. i try to use DragonboneDesignPanel from cocoachina but that not work for cocos2dx. something wrong when animation run..?|
So where is Dragonbone Design Panel for this extentsion ?

**Comment by litefeel** [comment]
now. dragonbones and CCArmature of cocos2dx are not compatible.
if you use cocos2dx v3.2, use [dragonbonesCPP](https://github.com/DragonBones/DragonBonesCPP) and [DesignPanel](https://github.com/DragonBones/DesignPanel).

**Comment by kameal** [comment]
Thanks so much!
