### ISSUE TITLE
Sprite3D initialize incorrectly or crash in current running scence

### ISSUE THREAD

**Issue by tangziwen** [cocos2d/cocos2d-x#8612]
Sprite3D use the "current scence" to get lights info ,but when users (probably) initialize Sprite3D obj in  scene in init() method ,it will crash cause the _runningScene is in valid or get be incorrect when user switch to another scence since that scene may not be set as "_runningScene"  immediately.

**Comment by minggo** [comment]
Could you paste some codes to explain it?

**Comment by minggo** [comment]
@super626 
Could you please take a look?

**Comment by super626** [comment]
I have fixed it. And I will sent a pull latter.

**Comment by minggo** [comment]
@super626 
Great, thanks.

**Comment by minggo** [comment]
@super626
And update?
I didn't see the pull request.
