### ISSUE TITLE
listview的问题，在android上会出现背景、样式等消失。

### ISSUE THREAD

**Issue by lpcdma** [cocos2d/cocos2d-x#8618]
![qq 20141010140639](https://cloud.githubusercontent.com/assets/2943003/4589230/bc80fbb8-5050-11e4-8468-7d8c9e7b6bb3.png)
Effect on the graph is win, and cocostudio designed is the same, is also the result I want.
Did not make any changes, but the same code in a different effect on android.As shown in figure
![screenshot_2014-10-10-15-25-00](https://cloud.githubusercontent.com/assets/2943003/4589249/03322e1a-5051-11e4-9d52-efa5ad9ff7d2.png)

**Comment by lpcdma** [comment]
Node\* node = static_cast<Node*>(cocostudio::GUIReader::getInstance()->widgetFromJsonFile("fuckbg/fuckbg.ExportJson"));
this->addChild(node, 0);
This is my code, version 3.1, 3.2 \ tested respectively lua and c + +

**Comment by zilongshanren** [comment]
@lpcdma 
Have you enabled Stencil buffer on Android? Please refer to [this thread](http://www.cocoachina.com/bbs/read.php?tid=199760) for more information.

BTW, please use English here such that other developers could help you.

**Comment by lpcdma** [comment]
@andyque 
THX!
I will try.

**Comment by minggo** [comment]
@lpcdma 
Any update?

**Comment by joewan** [comment]
I have also met this problem.
My cocos is 3.2.0.
Does we fix this bug in cocos 3.3.0.

**Comment by zilongshanren** [comment]
@joewan @lpcdma 
Could you try cocos2d-x v3.8? I think this problem has resolved.

**Comment by pandamicro** [comment]
Closing this issue, if reproduced in latest version and more informations provided, I will reopen it
