### ISSUE TITLE
XCode templates dont work anymore: CCTouch::view() is missing

### ISSUE THREAD

**Issue by Klaim** [cocos2d/cocos2d-x#862]
I tried using the current master branch (0ab4ead04b) to generate a new cocos2d-x project.
Compilation fails because CCTouch don't have the member function view() that is called somewhere in the tutorial (I dont have the test case anymore at hand but I guess it s easy to reproduce).

**Comment by minggo** [comment]
Yeap, view id is removed. It is useless.
You can get test case from github https://github.com/cocos2d/cocos2d-x.git

**Comment by Klaim** [comment]
I dont mind the change actually, it's the project template that seems not-up-to date though.

**Comment by minggo** [comment]
Which platform's project?
And the engine version?

**Comment by Klaim** [comment]
Sorry, forgot those informations.

IOS, engine version is 0ab4ead in the repository.

I switch back to last stable version tag to continue my work.

**Comment by minggo** [comment]
Thank you.
