### ISSUE TITLE
cpp-empty-test has a frame unstable in some Android devices

### ISSUE THREAD

**Issue by jongchul-woo** [cocos2d/cocos2d-x#8622]
http://youtu.be/mrLREgR67x0

I tested Optimus G (Android 4.4.2 and disable Eco & power save mode)
cocos2d-x 3.2, ndk r9d

I was tracking
FPS font CCLabelTTF
FPS Cocos2dxRenderer FPS controlling

I found a similar Issue
http://discuss.cocos2d-x.org/t/android-performance-low-frame-rate-and-flickering/4226
However, the problem still remains

Why is this happening appear on empty projects?

thanks

**Comment by minggo** [comment]
Did you build with release mode?
As the thread said, java GC will cause problem, and printing log may slow too.

And will you comment the codes in Cocos2dxRenderer.onDrawFrame()? Make it just invoke `Cocos2dxRenderer.nativeRender();`

``` java
@Override
    public void onDrawFrame(final GL10 gl) {
            Cocos2dxRenderer.nativeRender();
    }
```

**Comment by jongchul-woo** [comment]
I tried build command "python ${ProjDirPath}/build_native.py -b release"

and libcocos2dx Cocos2dxRenderer.java FPS controlling algorithm was commented

It doesn't work

**Comment by minggo** [comment]
It is strange.
We will take a look.
Any other device has the issue?

**Comment by jongchul-woo** [comment]
Thanks for your attention
Unfortunately I only have two Android devices
