### ISSUE TITLE
CMakeLists is missing def COCOS2D_X_VERSION for linux build

### ISSUE THREAD

**Issue by Svenito** [cocos2d/cocos2d-x#8630]
Created a new project on Ubuntu according to the instructions in the README.md. When running the  `cocos run -p linux` command, it errors with 

```
CMake Error at cocos2d/cocos/CMakeLists.txt:612 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

Tracked this error down to `COCOS2D_X_VERSION` being undefined in this file.

**Comment by minggo** [comment]
@dabingnn 
Could you please take a look?

**Comment by Svenito** [comment]
I think this was only the case for the beta release. The master version has this fixed. 

Should be good to close.

**Comment by minggo** [comment]
Thanks @Svenito.
