### ISSUE TITLE
Label outline/glow implementation is problematic

### ISSUE THREAD

**Issue by zeyangl** [cocos2d/cocos2d-x#8632]
Right now Label's outline/glow are implemented as mutually exclusive effects, and the output color is effectColor \* fontColor.
There are 2 problems with this. 
1. Stroke/glow should not be exclusive of each other. And when they do, it should be clearly documented.
2. glow/stroke color should simply be the effect other, otherwise there is no way to have a red glow on a black text.

**Comment by minggo** [comment]
@Dhilan007 
Please take a look of it.

**Comment by minggo** [comment]
I think it is fixed in latests codes, please reopen it if it has problem.
