### ISSUE TITLE
Cocos Studio NodeReader ignore the names for Node

### ISSUE THREAD

**Issue by darkdukey** [cocos2d/cocos2d-x#8636]
Forum Post for this bug
http://discuss.cocos2d-x.org/t/buttons-have-their-names-but-sprites-dont/17575

Here is the code for reading Node
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/editor-support/cocostudio/ActionTimeline/CCNodeReader.cpp#L266

**Comment by chengstory** [comment]
Thanks! I ask @pipu to review this code.
