### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by pipu** [cocos2d/cocos2d-x#8651]
Text in adaptive mode, the text of the attribute is horizontal to the right, space text added is increased from the left

**Comment by minggo** [comment]
Paste some codes is better.

**Comment by zilongshanren** [comment]
Thanks, @pipu

How could I reproduce this issue?

**Comment by pipu** [comment]
You can reproduce this issue at LabelTTFAlignmentNew::LabelTTFAlignmentNew() method in LabelTestNew.cpp

Code:
auto s = Director::getInstance()->getWinSize();
TTFConfig config("fonts/tahoma.ttf",16);
auto ttf0 = Label::createWithTTF(config,"Alignment 0\nnew line",TextHAlignment::LEFT);
ttf0->setAnchorPoint(Vec2(0.5f, 0.5f));
ttf0->setHorizontalAlignment(TextHAlignment::RIGHT);
ttf0->setString("Text LabelAAAAAAAAA");
ttf0->setPosition(Vec2(s.width - ttf0->getContentSize().width,(s.height/6)*2 - 30));
this->addChild(ttf0);

If you call ttf0->setString("Text LabelAAAAAAAAA"); Effect is correct.
If you call ttf0->setString("Text Label         "); Effect is incorrect.

![2014-10-11 6 24 49](https://cloud.githubusercontent.com/assets/3690622/4602326/f2f93bc0-5130-11e4-8584-2816e516e0bf.png)
![2014-10-11 6 27 45](https://cloud.githubusercontent.com/assets/3690622/4602328/4727e8cc-5131-11e4-9113-78b60e183c26.png)

**Comment by WenhaiLin** [comment]
![t2](https://cloud.githubusercontent.com/assets/5234286/4608728/17f1716a-5288-11e4-93e2-0596a3c6040b.PNG)
I test it on mac,it's work as expected.

**Comment by minggo** [comment]
@pipu 
Is it an issue?
Would you please double check it?

**Comment by pipu** [comment]
I submitted the other issue to describe this issue.
https://github.com/cocos2d/cocos2d-x/issues/8664

**Comment by minggo** [comment]
Please don't do it like this, or all comments will be lost.
Why not continue to discuss it in this one?

**Comment by minggo** [comment]
So please close #8664 and continue discussing in this one.

**Comment by pipu** [comment]
New comment:

Effect are different

1.
bool UITextTest::init()
{
if (UIScene::init())
{
Size widgetSize = _widget->getContentSize();

```
Text* alert = Text::create("Text","fonts/Marker Felt.ttf", 30);
alert->setColor(Color3B(159, 168, 176));
alert->setPosition(Vec2(widgetSize.width / 2.0f, widgetSize.height / 2.0f - alert->getContentSize().height * 1.75f));
_uiLayer->addChild(alert);        

// Create the text
Text* text = Text::create("Text", "AmericanTypewriter", 30);
text->setAnchorPoint(Vec2(0.0f, 0.5f));
text->setTextHorizontalAlignment(TextHAlignment::RIGHT);
text->setString("TextAAAAAAAA");
text->setPosition(Vec2(widgetSize.width - text->getContentSize().width, widgetSize.height / 2.0f + text->getContentSize().height / 4.0f));
_uiLayer->addChild(text);

return true;
```

}
return false;
}

pay attention line: text->setString("TextAAAAAAAA");
Effect Image
![2014-10-13 8 12 16](https://cloud.githubusercontent.com/assets/3690622/4659259/94f5e43c-550a-11e4-8015-43e5a0a5cc47.png)

2.
bool UITextTest::init()
{
if (UIScene::init())
{
Size widgetSize = _widget->getContentSize();

```
Text* alert = Text::create("Text","fonts/Marker Felt.ttf", 30);
alert->setColor(Color3B(159, 168, 176));
alert->setPosition(Vec2(widgetSize.width / 2.0f, widgetSize.height / 2.0f - alert->getContentSize().height * 1.75f));
_uiLayer->addChild(alert);        

// Create the text
Text* text = Text::create("Text", "AmericanTypewriter", 30);
text->setAnchorPoint(Vec2(0.0f, 0.5f));
text->setTextHorizontalAlignment(TextHAlignment::RIGHT);
text->setString("Text        ");
text->setPosition(Vec2(widgetSize.width - text->getContentSize().width, widgetSize.height / 2.0f + text->getContentSize().height / 4.0f));
_uiLayer->addChild(text);

return true;
```

}
return false;
}

pay attention line: text->setString("Text ");
"space character" are left side of "Text"
I think that is incorrect
Effect Image
![2014-10-13 8 15 41](https://cloud.githubusercontent.com/assets/3690622/4659261/9eda9a06-550a-11e4-9788-245134898a14.png)

**Comment by pipu** [comment]
ok.

I had closed #8664https://github.com/cocos2d/cocos2d-x/issues/8664?.

---

发件人: minggo notifications@github.com
发送时间: 2014年10月16日 15:52
收件人: cocos2d/cocos2d-x
抄送: 周楠（开发者平台）
主题: Re: [cocos2d-x] Text bug (#8651)

So please close #8664https://github.com/cocos2d/cocos2d-x/issues/8664 and continue discussing in this one.

**Comment by minggo** [comment]
Thanks.

**Comment by zilongshanren** [comment]
@Dhilan007 
Please take a loot at this Label issue, thanks.

**Comment by WenhaiLin** [comment]
@pipu It's look like right-aligned text automatically move space to left side on iOS 7 above. I can't find any solution to fix it.

**Comment by pipu** [comment]
Okay
