### ISSUE TITLE
wrong position problem when add a Sprite in a Button.

### ISSUE THREAD

**Issue by nocrim** [cocos2d/cocos2d-x#8653]
when i add a sprite as a child to a UIButton the sprite's position can't get right.
when a button calls the "loadTextureNormal" it triggers "onSizeChanged", then the child node of the button some how changes its worldspace position.
It seems like when the button(a widget) changes its content size(which will change its anchorpointInPoints), the sprite's position doesn't modify with its parent.
if i skip the "loadTextureNormal" method, the sprite will just position right.

Now i add a ImageView instead of a Sprite. and do the setting:
    ImageView *img = ImageView::create();
    img->setPositionType(Widget::PositionType::PERCENT);
    img->setPositionPercent(Vec2(0.5, 0.5));
the position is correct then.

i wanna know is there some bugs when a Widget update its children's position.
Today i use timeline to read a .ExportJson file exported from "CocosStudio for Mac", part of the contents of the ui file have the same wrong position problem.
Somebody help... T^T

My engine ver is 3.2.

**Comment by minggo** [comment]
@andyque
Does this issue fixed in latest code?

**Comment by zilongshanren** [comment]
thanks, @nocrim 
Could you paste some screenshot here to show me the "right behavior" and the "wrong behavior"?
Or could you please make a sample project at Github and I will take a loot at it.

The logic to update Widget's children's position should be right.

**Comment by nocrim** [comment]
@andyque sorry for reply so late. 
I just created a new project, only file "HelloWorldScene.cpp" has been modified.
Link: https://github.com/nocrim/testWIdget. 
note the codes commented out.

I thing maybe it's something in method "void Widget::updateSizeAndPosition(const cocos2d::Size &parentSize)".
Thx.

**Comment by nocrim** [comment]
Right behavior:
![ios 2014 10 14 12 02 07](https://cloud.githubusercontent.com/assets/2887937/4623849/ee624c82-5356-11e4-859e-2dc6917929ad.png)

Wrong behavior:
![ios 2014 10 14 12 02 24](https://cloud.githubusercontent.com/assets/2887937/4623888/e5b37bfa-5357-11e4-99f9-f6cc3a8c6815.png)

**Comment by zilongshanren** [comment]
@nocrim 
Thanks, I will take a look at your code.

**Comment by zilongshanren** [comment]
@nocrim 
Thanks for your code:

```
 auto img = ImageView::create();
    img->setPositionType(Widget::PositionType::PERCENT);
    img->setPositionPercent(Vec2(0.5, 0.5));
    img->loadTexture("HelloWorld.png", TextureResType::LOCAL);
    img->setScale(0.5);

    //wrong behavior code1:
//    auto img = Sprite::create("HelloWorld.png");
//    img->setScale(0.5);

    //wrong behavior code2:
//    auto img = ImageView::create();
//    img->loadTexture("HelloWorld.png", TextureResType::LOCAL);
//    img->setScale(0.5);

    auto button = Button::create("HelloWorld.png");
    button->addChild(img);
    button->setPosition((Vec2(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y)));
```

I don't think the "wrong behavior" is really a problem. If you try two sprites instead, it still behavior the same way.

The Widget class's content size in V2 is always ZERO. When adding a widget as a child to another widget, it will ignore the widget's content size. But in V3 all the Widget's content size is equals to its inner rendering component. I think this is what you said "wrong behavior".

Why the following code snippet behavior as you expected is because:

```
 img->setPositionType(Widget::PositionType::PERCENT);
    img->setPositionPercent(Vec2(0.5, 0.5));
```

You set the child widget's position always center to its parent.
If anything is unclear, please let me know. 
Thanks.

**Comment by nocrim** [comment]
@andyque thx.
I get it now. But why it's that when i edit some UI in cocostudio for mac the position rule still behavior as same as in V2. The editor is developed base on V2? 
Here's a ui I downloaded from cocoachina. Link: http://www.cocoachina.com/bbs/read.php?tid=215055
in editor:
![2014-10-16 11 41 29](https://cloud.githubusercontent.com/assets/2887937/4657278/5f10f92a-54e6-11e4-9a78-c1c96e08d9ce.png)

run in game:
![2014-10-16 11 41 15](https://cloud.githubusercontent.com/assets/2887937/4657304/c08b2162-54e6-11e4-88ac-5476e83f01b4.png)

**Comment by zilongshanren** [comment]
@nocrim 
That's because the Cocostudio editor still use V2, I think the new version of CocosSudio will solve this issue and it should be behavior the same as V3.
I mean the version in the  CocoaChina Developer Conference. Please stay tune for the new release.
Thanks.

**Comment by edwardzhou** [comment]
May I know when V3 version can be available?

**Comment by minggo** [comment]
We will release v3.3rc0 on Oct.21.
And release v3.3 final two weeks later after v3.3rc0.

**Comment by nocrim** [comment]
@andyque
when will new version of CocosStudio for mac be published?

**Comment by dumganhar** [comment]
Hi all , any updates for this issue? Was it fixed in the latest cocos studio?

**Comment by minggo** [comment]
@nocrim
It will be release on Dec.5.

So this issue can be closed?

**Comment by zilongshanren** [comment]
@nocrim 
Please confirm this issue with the later CocosStudio, thanks.
