### ISSUE TITLE
UIWebView is a separate subview

### ISSUE THREAD

**Issue by virgilcwylie** [cocos2d/cocos2d-x#8654]
UIWebView is in a separate subview because of which when i use Kamcord for recording, it doesn't get recorded. ... And i can't even add sprites on top of UIWebView.. I got project in which i need to also record WebView along with the Game Play.... Could we be able to add sprites on top of UIWebView in future?

**Comment by summerinsects** [comment]
UIWebView is not a GL drawn control, which is base on each platform, thus, it seems be topmost

**Comment by virgilcwylie** [comment]
Any work around to get it working with Kamcord? its recording my ViewController.

**Comment by minggo** [comment]
we just use system's WebView to implement UIWebView, we will not make sprite on top of it
