### ISSUE TITLE
Question of UITextTest::init() 2

### ISSUE THREAD

**Issue by pipu** [cocos2d/cocos2d-x#8665]
Effect is incorrect

Code:
bool UITextTest::init()
{
    if (UIScene::init())
    {
        Size widgetSize = _widget->getContentSize();

```
    Text* alert = Text::create("Text","fonts/Marker Felt.ttf", 30);
    alert->setColor(Color3B(159, 168, 176));
    alert->setPosition(Vec2(widgetSize.width / 2.0f, widgetSize.height / 2.0f - alert->getContentSize().height * 1.75f));
    _uiLayer->addChild(alert);        

    // Create the text
    Text* text = Text::create("Text", "AmericanTypewriter", 30);
    text->ignoreContentAdaptWithSize(false);
    text->setTextAreaSize(Size(100, 100));
    text->setString("TextLabel\nTextLabel\nTextLabel\nTextLabel\n");
    text->setPosition(Vec2(widgetSize.width / 2.0f, widgetSize.height / 2.0f + text->getContentSize().height / 4.0f));
    _uiLayer->addChild(text);

    return true;
}
return false;
```

}

pay attention:
text->ignoreContentAdaptWithSize(false);
text->setTextAreaSize(Size(100, 100));
text->setString("TextLabel\nTextLabel\nTextLabel\nTextLabel\n");
It seems that these three lines are not available.

Effect Image:
![2014-10-13 8 22 57](https://cloud.githubusercontent.com/assets/3690622/4613248/b22862e8-52d3-11e4-8aae-a2ee57493872.png)

**Comment by zilongshanren** [comment]
@pipu 
Thanks, what's the engine version and target platform?

**Comment by pipu** [comment]
v3 version
target platform iOS

**Comment by zilongshanren** [comment]
@pipu 
This issue was fixed at https://github.com/cocos2d/cocos2d-x/pull/9248

Please verify it, thanks.
