### ISSUE TITLE
RenderTexture Size Bug on Android devices with On-Screen Buttons Cocos2d-X 3.3beta0

### ISSUE THREAD

**Issue by ahlwong** [cocos2d/cocos2d-x#8668]
I'm creating a (partial) screen capture using the following code. On Android devices with on-screen home and back buttons, the RenderTexture is trying to capture too much of the texture. I think RenderTexture or maybe setVirtualViewport (or getting dimensions) captures the screen height of the application + the height of the on-screen buttons.

You can see this in the photo I attached. The original node clips in the middle of "G" in "Vogue". In the RenderTexture, the texture clips in the middle of "E". The RenderTexture is trying to capture too much of the screen and squishes the height to fit. I believe this is because of the on-screen buttons.

I've tested the code below and it works correctly on iOS and Android devices without the on-screen buttons.

Additional information:

The bug is present on Samsung Nexus 3 device with Android versions 4.2.2.

// console output
SIZE OF NODE: 320.000000 x 527.000000
WIN SIZE: 320.000000 x 527.000000
WIN SIZE PIXELS: 1280.000000 x 2108.000000

// from screenshot
Screenshot sizes (using Android screenshot, not cocos2dx) is 720px x 1280px and the height of the on-screen bar is 96px.

// code
RenderTexture\* renderTexture = RenderTexture::create(size.width, size.height, Texture2D::PixelFormat::RGBA8888, GL_DEPTH24_STENCIL8_OES);

renderTexture->setKeepMatrix(true);
Size winSize = Director::getInstance()->getWinSize();
Size winSizeInPixels = Director::getInstance()->getWinSizeInPixels();
renderTexture->setVirtualViewport(Point(0.0f, 0.0f), Rect(0.0f, 0.0f, winSize.width, winSize.height), Rect(0.0f, 0.0f, winSizeInPixels.width, winSizeInPixels.height));
renderTexture->setAutoDraw(false);

renderTexture->beginWithClear(0, 0, 0, 0, 1.0f);
node->visit();
Director::getInstance()->getRenderer()->render();

sprite = Sprite::createWithTexture(renderTexture->getSprite()->getTexture());
sprite->setFlippedY(true);
return sprite;

![render-texture-bug](https://cloud.githubusercontent.com/assets/1441263/4623543/4e01626e-5351-11e4-8828-ef62cabcbe7c.png)

**Comment by ghost** [comment]
@ahlwong What is the "node"? A layerColor?

**Comment by ghost** [comment]
@ahlwong I think you should use 
`renderTexture->setVirtualViewport(Director::getInstance()->getVisibleOrigin(), Rect(0.0f, 0.0f, winSize.width, winSize.height), Rect(0.0f, 0.0f, winSizeInPixels.width, winSizeInPixels.height));`

**Comment by ahlwong** [comment]
Sorry for the delay in response, I've been really busy with our current project.

The visibleOrigin doesn't seem to fix it. For some reason, the RenderTexture is still capturing too much. It's capturing > 527px and then distorting the vertical scale of the resulting texture to fit. However, renderTexture->getSprite()->getTextureRect() has the correct size.

Here's the output:
01-21 18:46:11.589: D/cocos2d-x debug info(6630): getWinSize: 320.000000 x 527.000000
01-21 18:46:11.589: D/cocos2d-x debug info(6630): getWinSizeInPixels: 1280.000000 x 2108.000000
01-21 18:46:11.589: D/cocos2d-x debug info(6630): getVisibleOrigin: 0.000000, 0.000000
01-21 18:46:11.589: D/cocos2d-x debug info(6630): getVisibleSize: 320.000000 x 527.000000
01-21 18:58:06.207: D/cocos2d-x debug info(6933): node->getContentSize: 320.000000 x 527.000000

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@ahlwong

**Comment by thienphuoc** [comment]
Hi @drelaptop  please reopen this case ! I have a problem with setVirtualViewport on android device !
