### ISSUE TITLE
Explicit namespace qualifier is missing in macro definitions in CCObject.h

### ISSUE THREAD

**Issue by qbit86** [cocos2d/cocos2d-x#867]
Macro definitions should involve full namespace qualification (to be independent from usage context).

Expected:
`#define schedule_selector(_SELECTOR) (::cocos2d::SEL_SCHEDULE)(&_SELECTOR)`
or even preferable
`#define schedule_selector(_SELECTOR) static_cast<::cocos2d::SEL_SCHEDULE>(&_SELECTOR)`

Actual:
`#define schedule_selector(_SELECTOR) (SEL_SCHEDULE)(&_SELECTOR)`

The latter causes a compilation error if namespace cocos2d is not imported in user's code (to prevent namespace pollution for example):

```
// No using's.
auto const f = schedule_selector(DemoScene::Update); // error C2065: 'SEL_SCHEDULE' : undeclared identifier
```

**Comment by minggo** [comment]
All engine codes are qualified in name space cocos2d, you should use the name space to invoke any engine codes. So is it needed?

**Comment by qbit86** [comment]
> All engine codes are qualified in name space cocos2d

After expanding macros in user code their content is NOT in predictable context or namespace.

> you should use the name space to invoke any engine codes.

I cannot qualify _the macro_ with namespace. I forced to import namespace, because i cannot say something like that

```
// Pseudocode:
auto const f =  cocos2d::schedule_selector(DemoScene::Update);
```

> So is it needed?

I think the opposite question should be asked :) Is there any reason to NOT specify namepace in macro definition? Well-known libraries (Boost for example) do always specify full “namespace path” to their identifiers in macro definitions. It's written once, and used frequently, so why not to do this?

**Comment by minggo** [comment]
Yeap, you are right.
http://www.cocos2d-x.org/issues/1192 is created for it.

Thank you.

**Comment by donaldalanmorrison** [comment]
Cross-reference #1192 no longer exists. @minggo Are all the "using namespace _;" macros fixed?
