### ISSUE TITLE
Update Spine runtime to latest version

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8670]
Should not modify the codes.

**Comment by hamburml** [comment]
Wouldn't is be easier to add the spine-repository as a git submodule? When the spine-repos gets an update, the developer can do an update and everything is updated?

**Comment by minggo** [comment]
@Michael-Hamburger 
It is a good idea. We will try it in future.
But this time we will not modify it since it is close to releasing time.

I will create another issue for it.

**Comment by minggo** [comment]
@Michael-Hamburger 
I forgot one thing, we planned to use prebuilt version in future.
Because spine license limit us to use unmodified version.

**Comment by minggo** [comment]
lua-binding and test case fixed in #8760.
