### ISSUE TITLE
关于RenderTexture交替绘制导致边缘拉伸

### ISSUE THREAD

**Issue by x5471140** [cocos2d/cocos2d-x#8686]
问题描述如 http://www.cocoachina.com/bbs/read.php?tid=207893
请问边缘拉伸是何原因？目前3.3依然没有解决这个问题

**Comment by minggo** [comment]
Duplicate with #8533?

**Comment by minggo** [comment]
@x5471140 
Is it duplicated with #8533?
If so, please close this one and add comments in #8533.
Thanks.
