### ISSUE TITLE
Warning when loading png files

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8705]
![image](https://cloud.githubusercontent.com/assets/488203/4640937/ccab84be-542d-11e4-92e9-8862c6af3331.png)

**Comment by minggo** [comment]
And developers report that it will slow down the application.

**Comment by WenhaiLin** [comment]
@andyque  We should upgrade libpng.

**Comment by zilongshanren** [comment]
@minggo We don't need to upgrade libpng, the warning was caused by the wrong png format.
We could use `convert in.png out.png` to solve this issue.

And we should also replace the ccFPSImages.c file.

**Comment by lalaloha** [comment]
@andyque how to fix this issue? what is "convert" command here? i use the terminal, and "convert" is not detected. What could be the problem? how should we save the png format next time to not encounter this issue? thanks,

**Comment by zilongshanren** [comment]
@lalaloha 
I think I have posted the solution in this ticket.

At first, you should install ImageMagick. If you are using MacOSX and you are also an Homebrew user， you could simply install it by executing the following command:

```
brew install imagemagick --buid-from-source
```

Then if you encounter the same warning when loading a specific png file, you could convert the png file like this:

```
convert foo.png foo.png
```

Done.

**Comment by lalaloha** [comment]
@andyque Hi, there's no mention of ImageMagick before. Thanks for the detail. Anyway, I want to know in the first place, Why this issue happened, and how should we save the png next time to not encounter this anymore without using the convert tool from imagemagick? Thanks

**Comment by zilongshanren** [comment]
![qq20141229-2](https://cloud.githubusercontent.com/assets/785541/5565675/3573bb12-8f41-11e4-836e-1e1c1b3b803e.png)

When export your png file from Photoshop, you should leave out the "embed  sRGB color" option in the above screenshot.

**Comment by zilongshanren** [comment]
@lalaloha 
And you could also refer to this post: http://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

**Comment by lalaloha** [comment]
@andyque Thx for the detailed information..
