### ISSUE TITLE
UI element can't handle touch properly when Camera moves.

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#8709]
How to reproduce this issue:
1. Add a arbitrary camera 
2. Add a  layer and a UI element to the layer.
3. Move the camera and the layer

Now the UI element can't be touched any more!

**Comment by Dredok** [comment]
any news on this issue?
this is slowing my development a lot. Any hack for quickly use ui elements and camera movement together?

**Comment by super626** [comment]
@Dredok 
https://github.com/super626/cocos2d-x/pull/332/files

You can try this.
However, it is not perfect. It will failed if rotation exists.

**Comment by zilongshanren** [comment]
already resolve in v3.8.
