### ISSUE TITLE
Make resources output by Cocos Studio automatically packed into ipa

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8710]
Because cocos studio will export resources in `Resources`, and they need to be packed into app automatically.

Should add search path in c++ codes too.

**Comment by litefeel** [comment]
plist in export json use relative path.
why need search path?

**Comment by minggo** [comment]
Because `Resources` will be a blue folder, which means there will be a folder named `Resources` in app.

**Comment by minggo** [comment]
Only need add search path for iOS and Mac OS X.

**Comment by litefeel** [comment]
in my project, `Resources` folder is not blue, becase it has other file, the other file don't packed to ipa.

if `Resources` is blue, you can put export resources to `Resources/ui`.
why do need search path?

**Comment by minggo** [comment]
The problem is that Cocos Studio will output resources in `Resources`, and these resources should be packed into ipa automatically.

As i discussed with @Dhilan007 , it is not make sense to add `Resources` as blue folder. May be add a folder named `ccs-res` in template, and add it as blue folder is better. But i needs to add search path too. Because Cocos Studio will use the resources relative to `ccs-res`.

**Comment by litefeel** [comment]
i use cocostudio, export  `.ExportJson`, it find plist relative `.ExportJson`.

**Comment by minggo** [comment]
Issue is that:
- Need to automatically pack added resources, which means new added resources should be in a blue folder. Am i wrong?
- Because new added resources in a blue path, which means it should be added to search path.

**Comment by litefeel** [comment]
> Because new added resources in a blue path, which means it should be added to search path.

why?  `Resources/ui` is  blue folder in my project, and it not need search path.

**Comment by minggo** [comment]
Because cocos studio uses relative path to the blue folder. How does engine know it?

**Comment by litefeel** [comment]
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos%2Feditor-support%2Fcocostudio%2FCCSGUIReader.cpp#L211-L239

cocos studio uses relative path to the `.json` or `.ExportJson` file.

**Comment by minggo** [comment]
Thanks.
I will check it tomorrow.
Now it uses protocol buffer.

**Comment by WenhaiLin** [comment]
Done at https://github.com/cocos2d/cocos2d-x/pull/8728

**Comment by minggo** [comment]
@lite3 
We just added `res` under `Resources` and add it as a blue folder.

**Comment by litefeel** [comment]
@minggo 
cocos studio export document use protocol buffer,  where is the `.proto` file?
if I has `.proto` file, I can modify it to suit my project .

**Comment by minggo** [comment]
It is exported to a .csb file.
I didn't see .proto file.

**Comment by litefeel** [comment]
`.proto` file is description of protobuf, it like struct, 
if has `.proto`, i will now how to parse `.csb` file.

**Comment by minggo** [comment]
@chengstory 
Did you know the `.proto` file?

**Comment by pipu** [comment]
Yes,  Cocos Studio export .csb file by .proto file.

**Comment by litefeel** [comment]
@pipu 
where are `.proto` file?

**Comment by litefeel** [comment]
@pipu 
where are .proto file?
