### ISSUE TITLE
issues with framerate in android

### ISSUE THREAD

**Issue by thinkong** [cocos2d/cocos2d-x#8711]
I am currently using cocos2dx 3.2 (stable) from the cocos2dx website.. 
when i compilie my source code for android i get around 60 fps

I would like it to do something like 30 fps.

but when i use setanimationinterval(1/30); it won't work..

i did get the code in the cocos2dxrenderer.java from the repo. 

But that didn't help.

any ideas?

**Comment by minggo** [comment]
the frame limitation codes are added again, and it works
