### ISSUE TITLE
set "Panel" anchor point Y to 1.0

### ISSUE THREAD

**Issue by volzhs** [cocos2d/cocos2d-x#8713]
I just set "Panel" anchor point Y to 1.0.
When load it and run,
It looks different from cocos studio.
Maybe bug?

I'm using cocostudio 1.6 and cocos2d-x 3.2.

![panel](https://cloud.githubusercontent.com/assets/8281454/4644299/345319c6-5459-11e4-9783-9fb9d69efe63.jpg)

**Comment by jonigata** [comment]
+1

**Comment by chengstory** [comment]
@minggo  Please let guanghui to take a look, It is not reader‘s bug.

**Comment by litefeel** [comment]
this is cocostudio bug. this tools fix export json.
http://www.litefeel.com/tools/cocostudioPositionFixer.php

**Comment by liam** [comment]
Wrong Liam

**Comment by jonigata** [comment]
I read the source codes because our designer says that he thinks CocoStudio's behavior is expected one, and I found the code which specialize "Panel(Layout)" in here( https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/editor-support/cocostudio/CCSGUIReader.cpp#L1508 ). When I try removing this line, expected behavior was shown.
For what is this condition?

**Comment by Cybertwip** [comment]
This may be of help: https://github.com/cocos2d/cocos2d-x/issues/14520, we solved the situation with normal and percent positions.

**Comment by liam** [comment]
Please don't use @Liam as it sends a mail to me.

Thanks
@Liam

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
