### ISSUE TITLE
Samsung Nexus 7 Tablet Android 4.3 CPPTest Crash Cocos2dX3.3Beta0

### ISSUE THREAD

**Issue by ahlwong** [cocos2d/cocos2d-x#8718]
Trying to run CPPTests on our Nexus 7 Tablet results in the following crash:

10-15 18:12:49.064: E/AndroidRuntime(3720): FATAL EXCEPTION: GLThread 284
10-15 18:12:49.064: E/AndroidRuntime(3720): java.lang.IllegalArgumentException: No configs match configSpec
10-15 18:12:49.064: E/AndroidRuntime(3720):     at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:863)
10-15 18:12:49.064: E/AndroidRuntime(3720):     at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
10-15 18:12:49.064: E/AndroidRuntime(3720):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
10-15 18:12:49.064: E/AndroidRuntime(3720):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

Tablet details:
Model: Samsung Nexus 7 Tablet
Android Version 4.3
Kernel Version: 3.1.10-g1e8b3d8
Build number: JWR66y

**Comment by minggo** [comment]
I think it is fixed in #8160.
Will you try latest codes?

**Comment by ahlwong** [comment]
Yes, that did fix the issue. The test will run now. ClippingNode doesn't work on Nexus 7 however. Is there a workaround or if we use ClippingNode will the device have to support stencil buffer?

**Comment by minggo** [comment]
Yep, `ClippingNode` depends on stencil buffer.
You can try `ClippingRectangleNode`, which is added latest.
But it can only clip rectangle.
