### ISSUE TITLE
libpng.a only has x86_64 version on iOS

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8730]
It will have problem if using iOS 6.0 or lower version. Because iOS simulator in iOS 6.0 is 32 bit.

**Comment by zilongshanren** [comment]
This issue is not exists in the latest version.  @minggo  We could close it now.

**Comment by zilongshanren** [comment]
For testing the arch of libpng.a

```
lipo -info libpng.a
```

```
lipo -info /Users/guanghui/cocos2d-x-v2/external/png/prebuilt/ios/libpng.a 
Architectures in the fat file: /Users/guanghui/cocos2d-x-v2/external/png/prebuilt/ios/libpng.a are: armv7 armv7s i386 x86_64 arm64
```

As shown above, it does have the i386 arch.

**Comment by zilongshanren** [comment]
@minggo  We could close this issue now.
