### ISSUE TITLE
AssetsManagerExTest: log output  "Asset background : Unable to download file" on win7.

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#8733]

**Comment by minggo** [comment]
It is a known bug on windows because of libcurl selection.

**Comment by WenhaiLin** [comment]
@andyque I think we should upgrade libcurl to make AssetsManagerEx work as expected on window.

**Comment by stammen** [comment]
@minggo What is the known bug? We are seeing the same problem with Windows Phone builds.

**Comment by minggo** [comment]
It seems the version of libcurl of windows have some bugs.
We should update libcurl to fix it.

**Comment by stammen** [comment]
What version do you recommned?

**Comment by dumganhar** [comment]
@andyque, was the library of libcurl for windows updated?

**Comment by zilongshanren** [comment]
@dumganhar Not yet, the build scripts for win32 will be finished this week.

**Comment by stammen** [comment]
What version of libcurl will you be using?

**Comment by zilongshanren** [comment]
@stammen 
we are using curl 7.26.

**Comment by kaminaritukane** [comment]
This issue stlll exists in v3.3 final version. Can you fix it ASAP?

**Comment by zilongshanren** [comment]
@kaminaritukane 
I will fix it in v3.4, thanks.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9729
