### ISSUE TITLE
[win7 lua-tests]Fail to enter ExtensionsTest-->CCControlButtonTest and output error message.

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#8751]
[LUA ERROR] [string ".\ExtensionTest/ExtensionTest.lua"]:345: attempt to index field 'Scale9Sprite' (a nil value)

**Comment by samuele3hu** [comment]
Already fixed,please review

**Comment by WenhaiLin** [comment]
@minggo Fix is confirmed
