### ISSUE TITLE
LanguageType support Chinese Traditional

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8752]

**Comment by eldaranne** [comment]
Hello,
Any news on this issue? 
More than just supporting traditional chinese, I think it would be a good thing to have access to the ISO3 language code and possibly the country code (including the JNI calls for these). It would allow the end users to have more flexibility on language detection. There are other examples of overloaded languages like portuguese/brazilian portuguese from the top of my head.

**Comment by minggo** [comment]
no plan to support it, reopen it when needed
