### ISSUE TITLE
[win7 lua-tests]Don't see the expected behaviour in 'FastTiledMapTest-->TMX tile flip run time test'.

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#8753]
output:[LUA ERROR] [string ".\FastTiledMapTest/FastTiledMapTest.lua"]:988: attempt to call field '_and' (a nil value)

**Comment by samuele3hu** [comment]
Already fixed,please review

**Comment by WenhaiLin** [comment]
@minggo Fix is confirmed
