### ISSUE TITLE
DrawNode - can't change opacity

### ISSUE THREAD

**Issue by zawasp** [cocos2d/cocos2d-x#8764]
I just noticed DrawNode doesn't support opacity changes. Once the item is drawn, setOpacity, FadeIn, FadeOut actions etc. have no effect on DrawNode.

Please add this feature.

**Comment by minggo** [comment]
It is a new feature.
We will fix it in next version if we accept it since it is close to releasing v3.3.

**Comment by metalim** [comment]
Any update on this one? It's obvious DrawNode isn't complete without opacity. From developer's point of view there's not much difference between image and DrawNode.

**Comment by purepure** [comment]
I am looking for this issue too.

**Comment by liangma87** [comment]
is the fix released?

**Comment by slackmoehrle** [comment]
Not yet. I am working on a test case to demonstrate some DrawNode issues and I will throw this in too.

**Comment by dapetcu21** [comment]
Any news of this? I kinda need it for my game

**Comment by zilongshanren** [comment]
@zawasp  I have added the opacity support to DrawNode at https://github.com/cocos2d/cocos2d-x/pull/17248

please give it a try.
