### ISSUE TITLE
Question that set rotation of UIScrollView

### ISSUE THREAD

**Issue by pipu** [cocos2d/cocos2d-x#8769]
Reproduce steps:

When direction of ScrollView is vertical,
setting rotation as 180 or 90, scrolling direction of ScrollView is not correct
![tmp3db144d2](https://cloud.githubusercontent.com/assets/3690622/4673691/2240da8a-55a7-11e4-87c4-df8295cdb363.png)

**Comment by minggo** [comment]
@pipu
It is fixe in #8783.
Would you please test it?
I haven't merged it, just wait CI result.
