### ISSUE TITLE
[Mac]Crash on the cpp-tests/Extensions/CocoStudioSceneTest/loadSceneEditorFile Test

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8770]
Click `Chang to load with binary file`

**Comment by minggo** [comment]
@chengstory 
Please take a look.

**Comment by chengstory** [comment]
Thanks，today I fix it.

**Comment by pipu** [comment]
Fixed it, please review

**Comment by minggo** [comment]
@samuele3hu 
It is fixed in #8770.
Could you please merge that branch and test it?
