### ISSUE TITLE
[MAC]The display of cpp-tests/Node:Label - New API/New Lablel + .TTF has a error

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8772]
SubTitle is : New Label with CJK + ASCII characters

**Comment by minggo** [comment]
What's the error?
Please describe it in more detail.

**Comment by samuele3hu** [comment]
The last letter exceed the limit of the width of line.

**Comment by samuele3hu** [comment]
![new label ttf error](https://cloud.githubusercontent.com/assets/4231014/4674108/8b777236-55af-11e4-81c6-22c0ba661458.png)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8854

**Comment by minggo** [comment]
@samuele3hu 
Could you please check it?

**Comment by samuele3hu** [comment]
Already fixed.
