### ISSUE TITLE
[MAC] cpp-tests/Node: UI/GUI Dynamic Create Test/EditBox Test has a error display for Password

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8775]
![ui editorbox error](https://cloud.githubusercontent.com/assets/4231014/4674162/f2768dcc-55b0-11e4-84af-eaa3daf2d476.png)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10114
