### ISSUE TITLE
[Mac] The display of cpp-tests/GUI Dynamic Create Test/Test/UITextTest_LineWrap has a error

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8777]
![uitext_linewrap](https://cloud.githubusercontent.com/assets/4231014/4674861/888dd346-5602-11e4-8d15-5e5a33cb2bea.png)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8889

**Comment by samuele3hu** [comment]
Already fixed

**Comment by zilongshanren** [comment]
@minggo 
please close this issue, it has  already been solved.
thanks.
