### ISSUE TITLE
[Mac] cpp-tests/Performance tests/Texture Perf Test has a error

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8780]
The error tip as follows:
fullPathForFilename: No file found at Images/landscape-1024x1024.png. Possible missing file.
cocos2d: Get data from file(Images/landscape-1024x1024.png) failed!
cocos2d:  ERROR

**Comment by ghost** [comment]
To figure out this issue need to add two missing png to cpp-test's resources depository:
LANDSCAPE IMAGE   Images/landscape-1024x1024.png
SPRITESHEET IMAGE Images/PlanetCute-1024x1024.png
but I don't know the demand details of the two images for this test.
