### ISSUE TITLE
[Mac] lua-tests/LabelTest/Testing cc.LabelTTF Word Wrap error

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8797]
![image](https://cloud.githubusercontent.com/assets/4231014/4676067/8dd07dc2-55d5-11e4-962e-3915e0bb2662.png)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8889

**Comment by samuele3hu** [comment]
Already fixed
