### ISSUE TITLE
[Mac] lua-tests/CocoStudioGuiTest/TextArea line wrap error

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8798]
![lua-test cocostudio textarea error](https://cloud.githubusercontent.com/assets/4231014/4676133/73f60934-55d6-11e4-8759-0eaf57911a3a.png)

**Comment by happyfire** [comment]
I have meet the same problem, and when I put a Text in a vertical list view, and set the gravity of Text to left, it is OK if I don't call setTextArea, and it will changed to center align if I call setTextArea.

**Comment by zilongshanren** [comment]
@happyfire @samuele3hu 
I think this issue has already solve in the latest code. 
@minggo 
we could close it now.

**Comment by samuele3hu** [comment]
Yes,it has already solved in the latest version.
