### ISSUE TITLE
[Mac] lua-tests/Performance/PerformanceTextureTest error like cpp-tests

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#8799]
Error tip is :
cocos2d: cocos2d: fullPathForFilename: No file found at Images/landscape-1024x1024.png. Possible missing file.
cocos2d: Get data from file(Images/landscape-1024x1024.png) failed!
cocos2d: [LUA-print]  ERROR

**Comment by ghost** [comment]
Similar to #8780, can be closed.
