### ISSUE TITLE
console test case crash (linux cpp, 3.3 rc test)

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#8809]

**Comment by dumganhar** [comment]
When I tested it on Ubuntu 32bit with QTCreator, I didn't see the crash. :(
But I think it's a potential issue. :)

**Comment by pandamicro** [comment]
Linux have a low priority, it won't be fixed recently. I will close it, when linux have a higher priority or when we plan to seriously support it, we will re-run all the test cases and make sure all works well.

Currently, the plan is to guarantee the compilation on Linux
