### ISSUE TITLE
[linux]Wrong effect for Label old API Test case

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#8810]
3.3 rc
linux cpp
![screen shot 2014-10-17 at 11 43 18 am](https://cloud.githubusercontent.com/assets/4794489/4676696/3cb43c5e-55de-11e4-8490-9c7a811e31a8.png)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/8863

**Comment by minggo** [comment]
@dabingnn 
Could you please check it?

**Comment by dabingnn** [comment]
Color is fixed,but with some jags.

**Comment by dabingnn** [comment]
![screen shot 2014-10-20 at 3 42 44 pm](https://cloud.githubusercontent.com/assets/4794489/4697885/4c04a120-582d-11e4-9788-c7458b5fcba4.png)
