### ISSUE TITLE
[linux]LuaTest->Camera3DTest no scene and actor in screen

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#8813]
lua linux in 3.3 RC

**Comment by dabingnn** [comment]
cocos2d: [LUA ERROR] [string "Camera3DTest/Camera3DTest.lua"]:155: attempt to index global 'bit' (a nil value)

**Comment by samuele3hu** [comment]
Already fixed,please review

**Comment by dabingnn** [comment]
Fixed.
