### ISSUE TITLE
[cpp-test all] GUI Slider Editor Test 

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#8838]
Scale9 slider doesn't work. Maybe there are something wrong with the Resource.
@chengstory  Please don't change the resource name while adding new one.  WP8 can't accept very long file path. I have changed all the paths of UI editor tests. 

Thanks.

**Comment by chengstory** [comment]
Thanks andyque, Today I fix it.

**Comment by minggo** [comment]
We will release v3.3rc0 on Oct.21.
Please fix it quickly.
