### ISSUE TITLE
CCScene class transformations (scale,position,rotation) don't effect anything

### ISSUE THREAD

**Issue by Yamomota** [cocos2d/cocos2d-x#8841]
Any transformations (scale,position,rotation) of any instance of CCScene class don't effect anything but they used to effect in all previous version of cocos2d-x.
Thank you in advance for fixing this.

Yamomota

**Comment by walzer** [comment]
1. Could you paste some source code about how to reproduce this bug?
2. You said: all previous version of cocos2d-x. But what's your current version?

**Comment by ricardoquesada** [comment]
Closed as fixed. Please reopen it if you think it is still valid. Please, add more info in that case.
