### ISSUE TITLE
Crash DrawNode::drawPoint()

### ISSUE THREAD

**Issue by ledenis** [cocos2d/cocos2d-x#8843]
Try the following code in cpp-tests, DrawPrimitivesTest.cpp in `DrawNodeTest()`

```
Vec2 positions[100];
for (int i = 0; i < 100; i++) {
    draw->drawPoint(Vec2(i, 5), 1, Color4F(CCRANDOM_0_1(), CCRANDOM_0_1(), CCRANDOM_0_1(), 1));
}
```

It causes a crash.
Tested as win32 app in Visual Studio 2013.

**Comment by dumganhar** [comment]
Thanks for your reply. I also reproduced this issue on Mac. 
It's an `out of range` issue. In the DrawNode::init, we ensure the point capacity to 64. I will try to fix it. :)
![drawpoint](https://cloud.githubusercontent.com/assets/493372/4764698/f4729948-5b2a-11e4-962b-7350379b0020.png)

**Comment by dumganhar** [comment]
Hi ledenis, I fixed the issue at https://github.com/cocos2d/cocos2d-x/pull/8918

**Comment by ledenis** [comment]
Thank you!
