### ISSUE TITLE
Question of Button::onPressStateChangedToDisabled() in UIButton.cpp

### ISSUE THREAD

**Issue by pipu** [cocos2d/cocos2d-x#8873]
Code:
void Button::onPressStateChangedToDisabled()
{
    _buttonNormalRenderer->setVisible(false);
    _buttonClickedRenderer->setVisible(false);
    _buttonDisableRenderer->setVisible(true);
    _buttonNormalRenderer->setScale(_normalTextureScaleXInSize, _normalTextureScaleYInSize);
    _buttonClickedRenderer->setScale(_pressedTextureScaleXInSize, _pressedTextureScaleYInSize);
}

pay attention to:
_buttonNormalRenderer->setScale(_normalTextureScaleXInSize, _normalTextureScaleYInSize);
_buttonClickedRenderer->setScale(_pressedTextureScaleXInSize, _pressedTextureScaleYInSize);

These two line above make _buttonNormalRenderer, _buttonClickedRenderer turn flip.

**Comment by minggo** [comment]
What's the issue?

**Comment by pipu** [comment]
When call setBright(false), onPressStateChangedToDisabled() is called in setBright(), 
then onPressStateChangedToDisabled() that override version in class Button is called, 
and this line: 
_buttonNormalRenderer->setScale(_normalTextureScaleXInSize, _normalTextureScaleYInSize); is executed.
This line makes _buttonNormalRenderer turn flipped.

I think that I only would like to call setBright(false) in order to change the state of Button, however, the result what I talk about is incorrect, effect is that Button is turned flipped.

**Comment by minggo** [comment]
@andyque 
Could you please take a look?

**Comment by zilongshanren** [comment]
@pipu 
Thanks. Because we mix use `flip` and `scale` in Scale9Sprite. I think the problems only appears when we are using Scale9 Button, right?

**Comment by pipu** [comment]
@andyque  
Yep. What you said is right.
The problem only appears when using Scale9 Button.

**Comment by zilongshanren** [comment]
@pipu 
Hi, could you please test the latest version from the Github.
I think this issue is solve here https://github.com/cocos2d/cocos2d-x/pull/9057
