### ISSUE TITLE
Using TTF, crash when press home button on Android

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#8874]
Tested version: cocos2d-x-3.2, cocos2d-x-3.3beta0
Tested device : Galaxy Note 3
### Reproduct step:
1. Create TTF Label with string with "" (This bug only occurs with empty string)
2. Make a button as a trigger to set string having length over 1 when touch a button
3. Press home button
4. Unlock and resume
5. Crash or broken texture shows

**Comment by ghost** [comment]
### My own solution

Insert codes below into Label() constructor

``` cpp
Label::Label(...)
{
    setAnchorPoint(Vec2::ANCHOR_MIDDLE);
    reset();

    auto purgeTextureListener = EventListenerCustom::create(FontAtlas::EVENT_PURGE_TEXTURES, [this](EventCustom* event){
        if (_fontAtlas && _currentLabelType == LabelType::TTF && event->getUserData() == _fontAtlas)
        {
            Node::removeAllChildrenWithCleanup(true);
            _batchNodes.clear();
            _batchNodes.push_back(this);

            /* Delete this */
            // alignText();

            // New code to insert[start]
            this->updateFont();
            this->setTTFConfig(_fontConfig);
            this->updateContent();
            // New code to insert[end]
        }
    });
    _eventDispatcher->addEventListenerWithSceneGraphPriority(purgeTextureListener, this);
}
```

**Comment by WenhaiLin** [comment]
I can't recreate the problem. Could you give me some sample code for recreate the problem.
Tested version: latest version on github
Tested device : MEIZU MX 3
