### ISSUE TITLE
[Win7 CppTests]Don't see the expected behavior in 'Node:Clipping-->Clipping to RenderTexture Test'.

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#8875]
![c1](https://cloud.githubusercontent.com/assets/5234286/4712520/33ff3304-58cf-11e4-996a-02d7fcdf96eb.png)

![c2](https://cloud.githubusercontent.com/assets/5234286/4712527/3f662194-58cf-11e4-97f8-76d79c6b0a78.png)

**Comment by XueChenChen** [comment]
thanks
