### ISSUE TITLE
EaseActions reverse broken

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/cocos2d-x#888]
Hey,

Allmost all EaseXXX::reverse actions are broken.

The problem is that cocos2d-x is using the cocos2d-iphone pattern for the reverse. And this pattern is not valid on C++.

cocos2d-iphone code:
https://github.com/cocos2d/cocos2d-iphone/blob/gles20/cocos2d/CCActionEase.m#L130

cocos2d-x code:
https://github.com/cocos2d/cocos2d-x/blob/gles20/cocos2dx/actions/CCActionEase.cpp#L185

Basically, cocos2d calls:
  [self class]... this means that the code will work for any subclass

While cocos2d-x calls:
CCEaseRateAction::... creating a EaseRateAction.

So, when the subclass of CCEaseRateAction call "reverse", instead of creating an instance of their self, it will create an instance of CCEaseRateAction.

I guess this could be fixed by:
a) Each subclass shall implement the reverse action (easier way)
b) or each subclass should implement the clone() pattern.

**Comment by minggo** [comment]
Yeap, thank you.
We will fix it.

http://www.cocos2d-x.org/issues/1217 is created for it.

**Comment by minggo** [comment]
I have fixed in the commit 
https://github.com/minggo/cocos2d-x/commit/07ac3fb02bf3a41423d97daf41add29c15b3f991

**Comment by ricardoquesada** [comment]
Thanks :)

**Comment by donaldalanmorrison** [comment]
@minggo The cross-referenced #1217 is marked as closed. :-)
