### ISSUE TITLE
[Win7 LuaTests]Don't see the expected behavior in 'Texture2DTest-->Texture2D:drawInRect' and 'Texture2DTest-->Texture2D:drawAtPoint'

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#8882]
![c3](https://cloud.githubusercontent.com/assets/5234286/4713798/c2495320-58e7-11e4-988f-7431fb48fe10.png)

![c4](https://cloud.githubusercontent.com/assets/5234286/4713800/c6c6a16e-58e7-11e4-8ca4-9fc4b6c33185.png)

**Comment by samuele3hu** [comment]
Fix at https://github.com/cocos2d/cocos2d-x/pull/8903.

**Comment by minggo** [comment]
@Dhilan007 
Could you please check it?
