### ISSUE TITLE
Update GAFExamples to v3.3

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8897]
Github address of this sample is: https://github.com/cocos2d/cocos2d-x-samples/tree/v3/samples

**Comment by ghost** [comment]
GAFExample is update in https://github.com/cocos2d/cocos2d-x-samples/pull/25
now iOS, android, win32, wp8 are supported

**Comment by stammen** [comment]
What do we need to do to support the Windows 8.1 Universal App?

**Comment by minggo** [comment]
@stammen
I don't think we need to do anything for Windows 8.1 Universal App.

Is it right, @huangshiwu ?

**Comment by minggo** [comment]
@stammen 
Does Windows 8.1 Universal App supporting finished?

**Comment by ghost** [comment]
@minggo do you mean that the examples don't need to provide Windows 8.1 Universal App?

**Comment by minggo** [comment]
No, i don't mean that.
I don't know what we need to do to support Windows 8.1 Universal App.
As you said, WP8 was supported, right?

**Comment by ghost** [comment]
Yes, now WP8 is supported on GAFExamples and LiquidFun-Testbed. 
@stammen Does create Windows 8.1 Universal project similar to create WP8 project.If so, I think we can handle it.

**Comment by stammen** [comment]
@minggo Were you able to fix cocos console to generate the correct project names for the Windows 8.1 Universal App?

**Comment by minggo** [comment]
@stammen 
#8923 is created for it.

**Comment by minggo** [comment]
@stammen 
After having Windows 8.1 Universal App, we don't need WP8 project, right?
And now only template has problem, all other things for WP8.1 are ok, right?

**Comment by stammen** [comment]
We still need the WP8 project for Windows Phone 8. The Universal App does not support WP8 only 8.1.? Microsoft did not provide a universal solution for Windows 8.0 projects.

**Comment by stammen** [comment]
All other things are good for WP8.1. I will be making more pull requests with minor fixes.

**Comment by minggo** [comment]
> We still need the WP8 project for Windows Phone 8. The Universal App does not support WP8 only 8.1.? Microsoft did not provide a universal solution for Windows 8.0 projects.

Oh, it is not a good news. And we have to have a WP8.2 project when WP8.2 ready?

**Comment by stammen** [comment]
I could add the WP8 project to the Universal App project. It would be all of the separate project files required by the WP8 build. The developer would need to add their classes code twice, once for the 8.1 and again for WP8. 

I do not yet know the visual studio project plans for Windows 10, but based on past experience it will require new project files.

Another team at Microsoft is working on CMake for WinRT and Windows Phone. Once they have universal app support accepted by Kitware I will add our platforms to CMake in cocos to make things easier.

**Comment by minggo** [comment]
@stammen 
Thanks for your answer.

But in VS, VS2013 can open VS2012 project, it makes sense that we only have one VS project.
If we have to have each project for WP, it is not convenient.

**Comment by stammen** [comment]
If I add the WP8 project into the universal app project, the developer will have to use Visual Studio 2013. They will no longer be able to open the project with VS 2012.

**Comment by minggo** [comment]
I am not sure.
Let's keep as it is now.
I will discuss it in our forum.

**Comment by stammen** [comment]
That is fine with me. In order to build the Universal App, the developer will need Visual Studio 2013 Update 3. They can build the WP8 version with either VS2013 or VS2012.

**Comment by minggo** [comment]
Got it.
Thanks.

**Comment by minggo** [comment]
But if he wants to compile shaders, he has to use VS2013 Update 3 now.
Right?

**Comment by stammen** [comment]
Yes. Currently that is true.

**Comment by minggo** [comment]
Ok, got it.
So may be VS2013 Update 3 is needed because developers will use their own shaders.
Any way, i will discuss in forum and invite you to join it.

Thanks.

**Comment by ghost** [comment]
GAFExample is update in https://github.com/cocos2d/cocos2d-x-samples/pull/31
add linux and mac platform support
