### ISSUE TITLE
Update LiquidFun-EyeCandy to v3.3

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8899]
Github address is: https://github.com/cocos2d/cocos2d-x-samples/tree/v3/samples

**Comment by samuele3hu** [comment]
LiquidFun-EyeCandy updated in the https://github.com/cocos2d/cocos2d-x-samples/pull/27.Now iOS/mac,win32 and android platform are supported,and win32 platform would crash when loading shader.

**Comment by samuele3hu** [comment]
Linux's support was added at the cocos2d/cocos2d-x-samples#29 and https://github.com/cocos2d/cocos2d-x-samples/pull/30
And now run it would trigger crash because of the problem of gl.
