### ISSUE TITLE
Update LiquidFun-Testbed to v3.3

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8900]
Github address is https://github.com/cocos2d/cocos2d-x-samples/tree/v3/samples

**Comment by samuele3hu** [comment]
LiquidFun-Testbed updated in the https://github.com/cocos2d/cocos2d-x-samples/pull/27.Now iOS/mac,win32 and android platform are supported.

**Comment by samuele3hu** [comment]
Linux's support was added at the https://github.com/cocos2d/cocos2d-x-samples/pull/29 and https://github.com/cocos2d/cocos2d-x-samples/pull/30

**Comment by dumganhar** [comment]
@samuele3hu , @minggo , was the upgrade finished?

**Comment by samuele3hu** [comment]
I have been updated the newest cocos2d-x submodule, and modify the related android configure to support `cocos run` command and remove the `build_native.py`. At the same time,update the CMakeLists.txt for Linux.The pr is in https://github.com/cocos2d/cocos2d-x-samples/pull/34. When release the rc1, i  will check it again.
