### ISSUE TITLE
There is no pitch and pan in new AudioEngine

### ISSUE THREAD

**Issue by milos1290** [cocos2d/cocos2d-x#8906]

**Comment by tankorsmash** [comment]
Has this been addressed in anyway yet?

**Comment by sappho192** [comment]
I think not..

**Comment by milos1290** [comment]
Not yet, soon i hope

**Comment by tankorsmash** [comment]
What can a casual dev do to help this along?

**Comment by walzer** [comment]
I put it in the unplanned roadmap. We had to focus on the rendering system, 3D, and editors firstly. Audio has lower priority.
If you need this feature in a hurry, please consider `fmod`.

**Comment by tankorsmash** [comment]
Thanks for the update. [Here's fmod](http://www.fmod.org/)

**Comment by minggo** [comment]
no plan to support it currently, reopen it if needed

**Comment by Glidos** [comment]
Any plans yet to add support for pan? Use of FMOD seems a bit of a sledgehammer to crack a nut, given support for pan is all that is needed for a game developer to implement reasonable 3D sound.
