### ISSUE TITLE
Question of UICheckBox

### ISSUE THREAD

**Issue by pipu** [cocos2d/cocos2d-x#8907]
When call the below 2 lines:

checkBox->setSelected(false);
checkBox->setBright(false);

CheckBox can still be touched.
I think that checkbox should become disabled state.

**Comment by zilongshanren** [comment]
@pipu 
Hi， there are some historical problems why it behaviors this way.
Currently we use `setEnable` only to disable touch event and we use `setBright(false)` to change the control to disable state.  These two methods need to be used together.

We have discussed it already, but to keep back compatibility, we should just keep it like this.

**Comment by zilongshanren** [comment]
@pipu 
And this issue is already discussed here https://github.com/cocos2d/cocos2d-x/issues/8137

**Comment by pipu** [comment]
Thanks a lot.
I'll check up it.

**Comment by minggo** [comment]
If it is a duplicate issue.
Please close it.
