### ISSUE TITLE
ScrollView::jumpToBottom() don't works

### ISSUE THREAD

**Issue by yushenglu** [cocos2d/cocos2d-x#8910]
I have loaded my csb file with a tall ScrollView, and want to set it to bottom after my init:

```
ScrollView* scroller = dynamic_cast<ScrollView*>(getChildByName("ScrollView_2"));
scroller->jumpToBottom();
```

But it doesn't work. The scrollView is still on the left-top area.

p.s. The problem occurs in the newest version,  older versions are ok.

**Comment by zilongshanren** [comment]
@yushenglu 
Thanks for your reporting.
What does you mean "older version"? V3.2 or v3.3beta?

**Comment by doomsdayer** [comment]
@andyque 
I'm LuYuSheng of CocoStudio Team in Beijing.
Sorry I only know the OK version is a developing version of 3.3(cuz I copied that from other's pc)，and the newest cocos2d-x on github still make this issue.

If necessary, u can contact me for the demo with this issue~
rtx: 卢玉升
qq: 1119616884
mail: yusheng.lu@chukong-inc.com

**Comment by zilongshanren** [comment]
@doomsdayer 
We should call this method on the `onEnter` method.
Since it is very historical issue and I can't find a perfect solution in a short time.

**Comment by powerhyn** [comment]
@yushenglu this problem just calling refreshView  (if your version is v3.3) before call jumpToBottom();
