### ISSUE TITLE
How to generate *.xcodeproj files by cmake?

### ISSUE THREAD

**Issue by stonejiang208** [cocos2d/cocos2d-x#8911]
How to generate *.xcodeproj files by cmake?

Thanks.

**Comment by vovkasm** [comment]
I do it that way:

If you need only to build cocos itself, then in cocos2d-x source folder do

```
mkdir cocos-build ; cd cocos-build
cmake -G Xcode ..
open Cocos2d-X.xcodeproj
```

But it will be Xcode project for Mac platform, not for iOS.

But if you need to make self-projects with cmake and cocos, then things got not so easy...
