### ISSUE TITLE
fbx-conv in windows create files without file name 

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#8912]
when running this command :
cocos2d-x-3.3rc0\tools\fbx-conv\win>fbx-conv.exe -a ........\cocos2d-x-3.3rc0\Projects\IsoTest\Resources\3d\earth.fbx

2 files created :
.c3b
.c3t
as you can see it created with out the file name 
also it create in the fbx-conv.exe not where the earth.fbx is

**Comment by minggo** [comment]
@meiry 
What's the issue?
Did you mean the output folder is not suitable?

**Comment by dumganhar** [comment]
@meiry probably means that the generated files should be 

```
earth.c3b
earth.c3t
```

but the results are just extension without file names

```
.c3b
.c3t
```

**Comment by meiry** [comment]
@dumganhar
yes this what happen if i do it with the long path 
it dosnt happen when i do it without the long path 
@minggo
also what is this empty  earthblend.fbm directory that created when i run for example:

```
fbx-conv.exe -a earthblend.fbx
```

**Comment by minggo** [comment]
@super626 
Could you please check it?

**Comment by super626** [comment]
ok，we will fix it. Thanks.

**Comment by super626** [comment]
It is the bug of fbx-conv, we have fixed it. It will work on next release.
@minggo 
You can close this issue.
