### ISSUE TITLE
VC++ 2012 project source not in place  in version 3.3 rc0

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#8913]
when creating new VC project the source are not in place and empty src virtual directory created 
see image :
![vc_notinplace](https://cloud.githubusercontent.com/assets/1107316/4753398/bfed3fe4-5ab6-11e4-8f74-bfd33f9e3a4b.png)

**Comment by minggo** [comment]
How did you create a new project?
Please use cocos to create a cross-platform project.

**Comment by meiry** [comment]
@minggo 
i allways do it from cocos console i don't think there is other way 
by the way is there any way in cocos console to create only project without copy all the cocos2d sources ?
my command is :

```
cocos new -p com.test.game -l cpp -d D:\dev\cpp\2d\cocos2d-x-3.3beta0\cocos2d-x-3.3beta0\Projects TestGame   


```

**Comment by minggo** [comment]
@Dhilan007 
Could you please check it?
You tested it before releasing v3.3rc0, right?

**Comment by WenhaiLin** [comment]
@minggo Yes,I tested it before releaseing v3.3rc0.This issue does not affect compile.
@meiry Thanks. Fixed at https://github.com/cocos2d/cocos2d-x/pull/8927
