### ISSUE TITLE
a curl static library error in cocos2d-x-3.3rc0

### ISSUE THREAD

**Issue by lpcdma** [cocos2d/cocos2d-x#8915]
I try to build lua-empty-test use the nkd-r10c,but failed.
the luajit error has been resolved.use "cocos2d-x-3.3rc0/external/lua/luajit/build_android.sh" recompile static library.
maybe the curl static libray need recompiled,but I don't know compile it.
At the same time, I found that can be used libcurl.a in 3.1.
Please help to solve this problem, thank you!

error log:
/Users/xxx/sandbox/android-ndk-r10c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /Users/xxx/sandbox/cocos2d-x-3.3rc0/build/../external/curl/prebuilt/android/armeabi/libcurl.a(sha512-armv4.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/Users/xxx/sandbox/cocos2d-x-3.3rc0/build/../external/lua/luajit/prebuilt/android/armeabi/libluajit.a(lib_base.o):lib_base.c:function lj_cf_print: error: undefined reference to '__swbuf'
/Users/xxx/sandbox/cocos2d-x-3.3rc0/build/../external/lua/luajit/prebuilt/android/armeabi/libluajit.a(lib_base.o):lib_base.c:function lj_cf_print: error: undefined reference to '__swbuf'
/Users/xxx/sandbox/cocos2d-x-3.3rc0/build/../external/lua/luajit/prebuilt/android/armeabi/libluajit.a(lib_io.o):lib_io.c:function io_file_read: error: undefined reference to '__srget'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [obj/local/armeabi/liblua_empty_test.so] Error 1
make: Leaving directory `/Users/xxx/sandbox/cocos2d-x-3.3rc0/tests/lua-empty-test/project/proj.android'
Build dynamic library for project [ /Users/xxx/sandbox/cocos2d-x-3.3rc0/build/../tests/lua-empty-test/project/proj.android ] fails!

**Comment by minggo** [comment]
Please don't use NDKr10, it has a problem.
You can refer to [this thread](http://cocos2d-x.org/news/307) for detail information.

**Comment by ombug** [comment]
@lpcdma are you successed in NDK10 !
