### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by araratispiroglu** [cocos2d/cocos2d-x#8917]
![screen shot 2014-10-23 at 19 06 05](https://cloud.githubusercontent.com/assets/1640626/4756628/f576eb8e-5ace-11e4-8d37-6503adc446f3.png)

I'm trying to compile older project with latest cocos2d-x library for iPhone 6. For iOS there's not problem. But for Android it crashes, even if I create new Test project with HelloWorld file it's not compiling. When I setup project and compile it, for the first time compilation it starting to compile some and then it's stops with error something like this 'multiple dex files define in Cocos2d-x accelerometer'. Then if I close and repoen the eclipse, it throws NullPointerException. If I try to compile it again, it's crashes strangely. I'm trying to compile it Eclipse Lune on OS X Yosemite. Is there any reason to fix this, or is this library fault ?

**Comment by minggo** [comment]
How to reproduce it?

**Comment by araratispiroglu** [comment]
I don't know how to reproduce it, but it can be general problem. Because if I crate project and try to build HelloWorld in another mac os, same error occuring. I think the problem begins after version 3.1.1. I can build with 3.1.1 without errors, but if I create project with version 3.2 or 3.3rc0 it crashes.

**Comment by minggo** [comment]
@araratispiroglu 
Could you describe it step by step?

**Comment by araratispiroglu** [comment]
@minggo Here I uploaded video showing step by step. You must download the video for watch in HD quality http://1drv.ms/1uUYcZY

**Comment by araratispiroglu** [comment]
After I upgraded cocos2d-x 3.4 version project compiles successfully for the first time, when I closed eclipse and reopened again same errors happened again. But this time I found some solution via stackoverflow, here's the link: http://stackoverflow.com/questions/25462415/cocos2d-x-android-set-up-error-java-lang-nullpointerexception/25892787#25892787

**Comment by minggo** [comment]
@Dhilan007 
Please take a look.

**Comment by minggo** [comment]
I have't met the error using eclipse for a long time, so close it.
