### ISSUE TITLE
[cocos2d-console] Compile on win32 failure due to 'devenv' not found

### ISSUE THREAD

**Issue by thenewvu** [cocos2d/cocos2d-x#8936]
Sorry for this duplication. I posted this issue on cocos2d-console repo, but no anwser for long time.

I have an issue when compile cocos2d-x projects on win32 by using cocos2d-console.

My dev environment:
- Windows 7 x64
- Visual Studio express 9, 10, 11, 12

This is what I got:

> $ cocos run -p win32
> Running command: compile
> Building mode: debug
> building
> Required VS version : 11.0
> 64bit
> find vs in reg : 32bit
> Find VS path : C:\Program Files (x86)\Microsoft Visual Studio 11.0\
> running: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\devenv" "D:\workspaces\mine\projects\hello-cocos2d-x\hellococos2dx_2\proj.win32\hellococos2dx_2.sln" /Build "Debug|Win32" /Project "hellococos2dx_2"'
> 
> '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\devenv"' is not recognized as an internal or external command,
> operable program or batch file.
> Error running command, return code: 1

I found out that 'devenv' is not exists in Visual Studio express.

Moreover, I found a solution to resolve this issue. That is using 'msbuild' instead of 'devenv'. 'msbuild' can be used to build cocos2d-x projects on VS pro, ultimate and express also (I did a research on ... Google :v:).

I'm intent on doing a PR, but I open this issue first if who had a local WIP stuff to resolve the problem.

**Comment by minggo** [comment]
@thenewvu 
coocs2d-x supports VS2012 or higher version. 
And you said it has problem even on VS2012, right?

@natural-law 
Could you please take a look?

**Comment by thenewvu** [comment]
@minggo : even on VS2012 (v11) and VS2013 (v12), but express versions.

**Comment by natural-law** [comment]
It's a known issue. The reason is:
Now the cocos command is using `devenv` to update the VS project if user is using VS2013.
But the Express version of VS is not contains `devenv` command tool. 

I'm sorry I have no solution for the issue by now.

**Comment by thenewvu** [comment]
So I will do a PR to resolve the issue. I'm not sure that it's stable, hope some persons help me test the solution.

**Comment by takaken1994** [comment]
Can we use MSBuild?

**Comment by natural-law** [comment]
@takaken1994, MSBuild can only build the project, but can't update it.

**Comment by thenewvu** [comment]
@minggo , @natural-law , @takaken1994 : I did a [PR](https://github.com/cocos2d/cocos2d-console/pull/171), please take a look.

**Comment by natural-law** [comment]
@thenewvu 
It's looks OK. I will try your PR later. And I will merge it as soon as possible.
Thanks for your contribution!

**Comment by thenewvu** [comment]
@natural-law : Thank you :dancers:

**Comment by natural-law** [comment]
@thenewvu 
I have reviewed your PR. It's very good!
But here is a little problem should be fixed. I have added a feedback in the PR.
Please check it. Thank you very much!

**Comment by thenewvu** [comment]
@natural-law : I fixed it. It's obviously faster. Please help me double-check it. Thanks.

**Comment by natural-law** [comment]
@thenewvu, The PR is merged. Thank you!

**Comment by minggo** [comment]
Thanks guys.

**Comment by mirth** [comment]
I have custom C++ bindings.
I'm trying to Build Runtime in Cocos Code IDE and getting the following.
Is it related error?

> Running command: compile
> Building mode: debug
> building
> Required VS version : 11.0
> find vs in reg : 64bit
> find vs in reg : 32bit
> Find VS path : C:\Program Files (x86)\Microsoft Visual Studio 11.0\
> Not found devenv. Try to use msbuild instead.
> Found msbuild path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe
> running: '"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe" "C:\Work\projectname\frameworks\runtime-src\proj.win32\projectname.sln" /target:projectname /property:Configuration=Debug /maxcpucount:2'
> 
> Error running command, return code: 1

**Comment by thenewvu** [comment]
Could you run this command alone, then post the output to here, pls ?

```
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe" "C:\Work\projectname\frameworks\runtime-src\proj.win32\projectname.sln" /target:projectname /property:Configuration=Debug /maxcpucount:2 /verbosity:diagnostic
```

The purpose is to get detail log that comes from MSBuild.

**Comment by mirth** [comment]
There is as much as i can copy http://pastebin.com/YZXvnajC. Sorry for Russian. The same project successfuly compiles on mac.
Tail:

> СБОЙ сборки.

```
               "C:\Work\projectname\frameworks\runtime-src\proj.win32\dreamla
               nd.sln" (целевой объект projectname ) (1) ->
               "C:\Work\projectname\frameworks\runtime-src\proj.win32\dreamla
               nd.vcxproj.metaproj" (целевой объект по умолчанию) (2) ->
               "C:\Work\projectname\frameworks\js-bindings\bindings\proj.win3
               2\libJSBinding.vcxproj" (целевой объект по умолчанию) (3) ->
                 C:\Work\projectname\frameworks\js-bindings\bindings\proj.win
               32\libJSBinding.vcxproj(93,3): error MSB4019: импортированны
               й проект "C:\Microsoft.Cpp.Default.props" не обнаружен. Пров
               ерьте путь в объявлении <Import> и наличие файла на диске.


               "C:\Work\projectname\frameworks\runtime-src\proj.win32\dreamla
               nd.sln" (целевой объект projectname ) (1) ->
               "C:\Work\projectname\frameworks\runtime-src\proj.win32\dreamla
               nd.vcxproj.metaproj" (целевой объект по умолчанию) (2) ->
               "C:\Work\projectname\frameworks\js-bindings\cocos2d-x\cocos\2d
               \libcocos2d.vcxproj" (целевой объект по умолчанию) (4) ->
                 C:\Work\projectname\frameworks\js-bindings\cocos2d-x\cocos\2
               d\libcocos2d.vcxproj(19,3): error MSB4019: импортированный п
               роект "C:\Microsoft.Cpp.Default.props" не обнаружен. Проверь
               те путь в объявлении <Import> и наличие файла на диске.

Предупреждений: 0
Ошибок: 2
```

> Затраченное время: 00:00:00.70
> 
> C:>

**Comment by thenewvu** [comment]
Actually I dont have any solution for your problem. But I see a topic on StackOverlow that can solve your problem. Give it a try.

   http://stackoverflow.com/questions/16092169/why-does-msbuild-look-in-c-for-microsoft-cpp-default-props-instead-of-c-progr

**Comment by mirth** [comment]
Topic link is missed probably.
