### ISSUE TITLE
UserDefault.xml missing from win32 debug build dir [Cocos2d-x v3.3rc0]

### ISSUE THREAD

**Issue by MFHSchoonbrood** [cocos2d/cocos2d-x#8937]
Hi guys,

In platform\win32\CCFileUtils-win32.cpp 2 lines got commented out in the getWritablePath() function.
This results in the debug build no longer reading/writing the UserDefault.xml in the debug build dir, which was pretty useful :)

I'm assuming these got commented out by accident while testing something.

Could you please enable them again in the next version?

To be precise, it's line 281: "//#ifndef _DEBUG" and the corresponding line 309: "//#endif // not defined _DEBUG".

Kind regards,
Michaël

**Comment by samuele3hu** [comment]
This modification is requested by the Cocos IDE to guarantee the writable path of release and debug the same.In this mechanism,the UserDefault.xml is not in the debug build dir.You could trace the code to get the detail of path.I have been tried in the debug condition, i could read/write the UserDefault.xml.
