### ISSUE TITLE
update to 3.3rc0, it crashed when load cocostudio json file, crash in function createNodeWithSceneFile

### ISSUE THREAD

**Issue by jacket-code** [cocos2d/cocos2d-x#8942]
when I update to 3.3rc0, it crashed when load cocostudio json file, 
crash in function createNodeWithSceneFile, can you give me some help?
the json file is ok , the content is : 
{
  "version": "1.0.0.0",
  "designWidth": 960,
  "designHeight": 640,
  "dataScale": 1.0,
  "textures": [],
  "texturesPng": [
    "ICGE-logo-iep.png"
  ],
  "nodeTree": {
    "options": {
      "$type": "EditorCommon.JsonModel.Component.GUI.RootGUISurrogate, EditorCommon",
      "visible": true,
      "frameEvent": null,
      "name": "Node",
      "classname": "Node"
    },
    "children": [
      {
        "options": {
          "$type": "EditorCommon.JsonModel.Component.GUI.ImageViewSurrogate, EditorCommon",
          "fileNameData": {
            "resourceType": 0,
            "path": "ICGE-logo-iep.png",
            "plistFile": ""
          },
          "scale9Width": 256.0,
          "scale9Height": 256.0,
          "x": 480.0,
          "y": 320.0,
          "visible": true,
          "ZOrder": 1,
          "classType": "ImageView",
          "width": 256.0,
          "height": 256.0,
          "positionPercentX": 1.0,
          "positionPercentY": 1.0,
          "sizePercentX": 0.166666672,
          "sizePercentY": 0.25,
          "actionTag": 684370143,
          "tag": 8,
          "ignoreSize": true,
          "name": "IcgeLogo",
          "classname": "ImageView"
        },
        "children": [],
        "classname": "ImageView"
      }
    ],
    "classname": "Node"
  },
  "action": {
    "speed": 1.0,
    "timelines": []
  }
}

**Comment by jacket-code** [comment]
my step is : 
1. create a project using3.3rc0
2. use cocostudio(mac) to export a json (just a simple layer with a texture sprite)
3. load the json file using createNodeWithSceneFile
4. it crashed when read the json file
5. crash at get the json value "classname"

why?

**Comment by minggo** [comment]
@chengstory
Could you please take a look?

**Comment by jacket-code** [comment]
tonight, I do it again, and just add a few line code, it still crash, it breaks my heart, can you fixed it fast?
thank you.
tonight, the step is : 
1. create a new project using 3.3rc0
cocos new TestGame -p com.jacket.tgame -l cpp -d /Users/jack/Test
2. in HelloWorldScene.cpp, I just add the fallowing codes:
   at file top:

---

``` C++
    #include "cocostudio/CocoStudio.h"
    #include "ui/CocosGUI.h"
    USING_NS_CC;
    using namespace ui;
    using namespace cocostudio;
```

---

   in init() function:

---

``` C++
    Node *pNode = 
    SceneReader::getInstance()->createNodeWithSceneFile("LoginSceneBgLayer.json");
```
1. command + R
2. it crashed at CCSSceneReader.cpp line:260 (the reason is className is NULL)
   
    259: const char *className = DICTOOL->getStringValue_json(dict, "classname");
    260: if(strcmp(className, "CCNode") == 0) ---> (no CCNode word in json file, it is funny!)
3. I print the json file content is ok, but it can't read the jsonvalue "classname", the old json 
   files are the same error, the json file is exported out at imac
4. the 3.0 is ok, o, my god, please help me
   crash image:
   ![Uploading 7F830F3D-016A-4961-AE73-FC42D91AD3CD.png . . .]()

**Comment by jacket-code** [comment]
I test it using other code, it has problem in the reading order
my test codes:

``` C++
     string jsonpath     = 
     FileUtils::getInstance()->fullPathForFilename("LoginSceneBgLayer.json");
     string contentStr   = FileUtils::getInstance()->getStringFromFile(jsonpath.c_str());
     CCLOG("the jsonpath is %s", jsonpath.c_str());
     CCLOG("the pBuffer is %s", contentStr.c_str());
     rapidjson::Document uiDoc;
     uiDoc.Parse<rapidjson::kParseDefaultFlags>(contentStr.c_str());
     if (uiDoc.HasParseError()) {
         CCLOG("LoadScene GetParseError %s\n", uiDoc.GetParseError());
     } else {
         if (uiDoc.HasMember("designHeight")) {
             CCLOG("json value is %d", uiDoc["designHeight"].GetInt());
         }
         if (uiDoc.HasMember("version")) {
             CCLOG("json value is %s", uiDoc["version"].GetString());
         }
         if (uiDoc.HasMember("classname")) {
             CCLOG("json value is %s", uiDoc["classname"].GetString());
         }
     }
```

it only prints : 
cocos2d: json value is 640
cocos2d: json value is 1.0.0.0
so the classname is can't be read!!!, it maybe the order question?
and the func : createNodeWithSceneFile() inside is : 

``` C++
        _node = nullptr;
        rapidjson::Document jsonDict;
        do {
            CC_BREAK_IF(!readJson(fileName, jsonDict));
            _node = createObject(jsonDict, nullptr, attachComponent);
            TriggerMng::getInstance()->parse(jsonDict);
        } while (0);
```

the createObject() function first the "classname", it can't be read, it that right?

**Comment by jacket-code** [comment]
last time I reconlize that my misstakes
then I use 
    auto uiLayer = cocostudio::GUIReader::getInstance()->widgetFromJsonFile("LoginSceneBgLayer.json");
it still crash,
using windows cocostudio 1.3 is ok, but mac cocostudio is still crash

**Comment by chengstory** [comment]
mac cocostudio?   2.0.0.0 beta0?

**Comment by jacket-code** [comment]
mac cocostudio 1.0.0.0 beta, it will crash when i run the code:
 auto uiLayer = cocostudio::GUIReader::getInstance()->widgetFromJsonFile("LoginSceneBgLayer.json");

and when i use mac cocostudio 2.0.0.0beta, loading the csb file,  it will show nothing when i run the code:
 auto uiLayer = cocostudio::GUIReader::getInstance()->createNodeWithSceneFile("LoginSceneBgLayer.csb");

**Comment by chengstory** [comment]
if you use cocos studio 2.0beta, please refer to：
http://www.cocoachina.com/bbs/read.php?tid-236704.html

**Comment by jacket-code** [comment]
the refer is ok for mac 1.0.0.0beta and 2.0.0.0 beta
but auto uiLayer = cocostudio::GUIReader::getInstance()->widgetFromJsonFile("LoginSceneBgLayer.json");
auto uiLayer = cocostudio::GUIReader::getInstance()->createNodeWithSceneFile("LoginSceneBgLayer.csb");
still error, and have some problems

**Comment by chengstory** [comment]
1,  x.csb that 2.0.0.0 beta exported needs to use "CSLoader::createNode("x.csb")",
2,  x.json that UI Editor exported needs to use "cocostudio::GUIReader::getInstance()->widgetFromJsonFile("x.json")".
3,  x.json that Scene Editor exported needs to use cocostudio::SceneReader::getInstance()->createNodeWithSceneFile("x.json").

**Comment by jacket-code** [comment]
I use mac 1.0.0.0 to export the ui x.json, and used "cocostudio::GUIReader::getInstance()->widgetFromJsonFile("x.json")".
it will crash,  i use CSLoader::createNode("x.json") is ok, 
when i use windows cocostudio 1.3.0.1 to export ui and 
use CSLoader::createNode("x.json"), it will be also crash,
why?

**Comment by chengstory** [comment]
If file(json or csb) is exported by mac 1.0.0.0 or mac 2.0.0.0 beta0, please use CSLoader::createNode("xxx"), because new data format is used in mac version.
if file(json or csb) is exported by windows 1.x, please use parse function of GUIReader, 
SceneReader and Armature.

**Comment by jacket-code** [comment]
OK, thank you very much, i hope that the engine will suport one interface to do all things in the further, like load the resources files
