### ISSUE TITLE
[WP8] The orientation of app cannot be changed along with the orientation of emulator

### ISSUE THREAD

**Issue by tealcwu** [cocos2d/cocos2d-x#8943]
Test Environment: 
Windows 8.1 Enterprise English, Visual Studio 2012 Update 4, Windows Phone 8.0 SDK.

Repro Steps:
1. Download Cocos2d-x v3.3rc0 from http://cn.cocos2d-x.org/download/.
2. Unzip it when the download is completed, e.g. unzip it to folder D:\cocos2d-x-3.3rc0.
3. In Command Promote, run "D:\cocos2d-x-3.3rc0\tools\cocos2d-console\bin\cocos new -l cpp TestGame" to create a new Cocos2d-x project.
4. Open ..\TestGame\proj.wp8-xaml\TestGame.sln with Visual Studio 2012, open MainPage.xaml in TestGame project. Update line #13 to:
SupportedOrientations="PortraitOrLandscape" Orientation="Landscape"
select "Emulator WVGA 512MB" as target platform and build the solution.
5. When build is finished, deploy it to "Emulator WVGA 512MB" (or any Windows Phone 8.0 emulator, just make sure the orientation of the emulator is portrait), 
6. Run TestGame on this emulator. The orientation of the test app is portrait.
7. Change the orientation of the emulator to "Landscape" (rotate 90 degrees to left). Check the orientation of the app.
=== Expected Result: The orientation of the app is landscape.
=== Actual Result: The orientation of the app is portrait. Please refer to "Screenshot 1".
8. Close TestGame. Run TestGame on emulator (Make sure the orientation of the emulator is landscape). The orientation of the test app is landscape.
9. Change the orientation of the emulator to "Portrait" (rotate 90 degrees to right). Check the orientation of the app.
=== Expected Result: The orientation of the app is portrait.
=== Actual Result: The orientation of the app is landscape. Please refer to "Screenshot 2".

![cc_p-l](https://cloud.githubusercontent.com/assets/359581/4797882/eeaa9592-5e0e-11e4-809d-8498b6fe4222.png)
![cc_l-p](https://cloud.githubusercontent.com/assets/359581/4797888/0695fc8c-5e0f-11e4-9226-92869295406f.png)

**Comment by minggo** [comment]
@huangshiwu 
Could you please take a look?

**Comment by stammen** [comment]
In MainPage.xaml change

```
SupportedOrientations="Landscape" Orientation="Landscape"
```

to

```
SupportedOrientations="PortraitOrLandscape" Orientation="Landscape"
```

**Comment by tealcwu** [comment]
yes, I have updated the SupportedOrientation in step 4.

**Comment by tealcwu** [comment]
Please notice the text "Memory:xxxxMB Peak xxxxMB" in screeshots, its orientation can be changed correctly.

**Comment by ghost** [comment]
For now this is because in function GLViewImpl::UpdateWindowSize can't process ResolutionPolicy::UNKNOWN case, so you need to add code in AppDelegate.cpp like this:
glview->setDesignResolutionSize(640,480,ResolutionPolicy::SHOW_ALL);
We will keep trying to find a better solution.

**Comment by tealcwu** [comment]
Thanks for the workaround! I added the following code snippet to method AppDelegate::applicationDidFinishLaunching() can fix this issue.

auto _winSize = director->getWinSize();
glview->setDesignResolutionSize(_winSize.width, _winSize.height, ResolutionPolicy::SHOW_ALL);

**Comment by ghost** [comment]
Cocos2d-x now don't support portrait and landscape at the same time in one product for that almost all games just have one orientation version.Or if you use the engine to develop some app need to support portrait and landscape at the same time?

**Comment by tealcwu** [comment]
Gotcha, I just realized what you said after opening this issue. I'm a newbie to Cocos2d-x and found this problem when trying some features. I compared Cocos2d-x with normal Xaml app design subconsciously. Anyway this issue doesn't affect games design. So you can close it for now.

**Comment by ghost** [comment]
OK, thanks for your feedback and welcome to join cocos2d-x developer family!
