### ISSUE TITLE
SimpleAudioEngine::sharedEngine()->playBackgroundMusic(); Crashes on Lollipop

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#8962]
I've test it with ndk r9 and ndk-10c 
Everything works fine on android 4.0+ .... but playbackgroundmusic() causes crash on 5.0.... All of my cocos2dx games have stopped workinig. This is a Critical issue.

Thanks!

**Comment by minggo** [comment]
@Dhilan007 
Please take a look.
It is critical bug.

**Comment by Bilalmirza** [comment]
hey,

was this fixed?

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9088. It's seem some system issue that  MediaPlayer causes an immediate freeze on Lollipop.For more information: https://code.google.com/p/android-developer-preview/issues/detail?id=1787

**Comment by minggo** [comment]
@Bilalmirza 
What device did you test on?

**Comment by Bilalmirza** [comment]
nexus 5.... this is fixed at #9088

Thanks :D

**Comment by minggo** [comment]
Ok.
Thanks.

**Comment by Bilalmirza** [comment]
There is another issue .... some of the fonts .ttf arent picked up on lollipop nexus 5
and the same fonts work perfectly in android 4.0

**Comment by minggo** [comment]
Could you create a new issue for it?

**Comment by Bilalmirza** [comment]
sure

**Comment by minggo** [comment]
Thanks.
