### ISSUE TITLE
SSE issue on x86

### ISSUE THREAD

**Issue by angelvet** [cocos2d/cocos2d-x#8964]
Application crashes on startup with error:
- Unhandled exception at 0x0FA8D528  (libcocos2d.dll) in TestApp.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF. (on Windows)
- A/libc(1489): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128) ( on Android x86)

when reaching MathUtil::multiplyMatrix from MathUtilSSE.inl. line 43.

Tested clean cocos2d-x application debug build on android x86 and windows with sse instructions enabled.

**Comment by minggo** [comment]
Can run cpp-tests reproduce it?

**Comment by angelvet** [comment]
Yes, I have built and run cpp-empty-test on android and got the same issue.
To reproduce you just need to enable x86 ABI before compiling and run it on x86 device/emulator.

**Comment by minggo** [comment]
Ok, i will test it.

**Comment by KrissMu** [comment]
Hello,

Any news concerning this issue ? I'm facing it too and I can't find any workaround ...

Does this mean that we can't build application running on x86 terminal ? I'm new to Android development.

Thanks

**Comment by angelvet** [comment]
As a workaround you can disable SSE instructions for x86 build, just add -U__SSE__ onto your compiler flags list.

**Comment by minggo** [comment]
Sorry for late reply.
We already tested on x86 device, not problem.
Could you please test it with latest codes?
We will confirm it too.

**Comment by minggo** [comment]
@Dhilan007 
Please check it again.

**Comment by KrissMu** [comment]
Well I might be wrong because I can't say for sure that the error I get is related to SSE.

I have the error message:
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128)

occuring when I use APP_ABI = x86 and an x86 AVD, but no error with arm and an arm AVD.
I'm using Android Studio, worth mentioning it I guess.

I'm very new to Cocos and Android, and I don't know how I could investigate deeper where the error is, I only have this message.

**Comment by angelvet** [comment]
Earlier I have created a bug on Issue Tracker  http://www.cocos2d-x.org/issues/6002#change-14796
There is a logcat attached, probably it would help.

**Comment by KrissMu** [comment]
At first look, it seems to be quite similar than mine.

You talked earlier about deactivating SSE in compiler, using "-U__SSE__", I'm not quite sure where I would have to use this.
Is it something I need to add in one of the .mk files ? In the .gradle ?

Thank you for your help.

**Comment by angelvet** [comment]
Hello,

Yes, you can check by extending APP_CPPFLAGS directive on your Application.mk file like
APP_CPPFLAGS :=  [other flags...] -U__SSE__

Probably there also must be some logic added to disable sse instructions for x86 ABI only, instead of all declared abis within APP_ABI directive.

**Comment by KrissMu** [comment]
OK it works great, thanks !

Now last (maybe ;) ) questions: is it ok to distribute an application like that (having SSE disabled for x86) ?
Should we expect some update (even if it might not be urgent) that would solve this issue ? Is it related with Cocos2d-x ? (I guess so, but as I said before, I'm new to all this development environment and I'm still learning :) ).

Thanks again.

**Comment by WenhaiLin** [comment]
Hi all,  i can't reproduce this issue  base on the latest codes on github.
Tested device : ASUS K011
Android Version: 4.4.2
NDK version:r10c

**Comment by KrissMu** [comment]
For information, I've updated to NDK r10c and I'm still facing the issue: works with "-U__SSE__", does not work without.

**Comment by angelvet** [comment]
I have upgraded to android-ndk-r10c and cocos2d-x-3.3rc2 and still experiencing this issue:

Program received signal SIGSEGV, Segmentation fault.
0xabaee9a1 in cocos2d::MathUtil::multiplyMatrix(float __vector(4) const_, float __vector(4) const_, float __vector(4)*) (
    m1=0xa0d14a8, m2=0xab581400, dst=0xa0d14a8)
    at ../cocos2d/cocos/./math/MathUtilSSE.inl:48
48  __m128 v0 = _mm_mul_ps(m1[0], e0);

**Comment by minggo** [comment]
Hi guys,

How to reproduce it?

**Comment by KrissMu** [comment]
Hi,

I have updated NDK to r10d and I'm using cocos2d-x-3.3 (downloaded yesterday).
I'm still experiencing the SSE issue.

What I did:
I used cocos console to create a new project, then I import the project into Android Studio (import, not open, it then creates some folders and so on).
I had to do some tricks here and there to make it work such as copying Resources folderto a newly created assets folder, and some updates in the gradle and mk files (including definition of APP_ABI and APP_PLATFORM).

Then, when I run the HelloWorld stuff in an x86 emulator, I got the error, all works fine in arm emulator. 
I still need to validate it will work in x86 with the "-U__SSE__" option added to APP_CPPFLAGS in Application.mk. I can't do it now.

Do you need any more detail ? I'm still quite noobish with Android Studio configuration, so I might be wrong too, but for the moment this is what I get.

**Comment by minggo** [comment]
@KrissMu 
Thanks for feedback.

There is a known issue when build with Android 21 for x86 architecture. You can refer to [this issue](https://github.com/cocos2d/cocos2d-x/issues/9204) for detail information. It is nothing about engine.

And we haven't tested Android studio, is there any problem if you don't use Android studio?

**Comment by KrissMu** [comment]
I can't try outside of Android Studio at the moment, but changing the API version of the emulator from 15 to 16 or 19 has a different behavior. It can launch, but will crash after a few seconds.
Anyway, I don't think it's the same issue than above. It has someting to do with x86, but not with SSE I guess.

Edit:
After a long debugging session, I finally think it's still related to the same function MathUtil::multiplyMatrix from MathUtilSSE.inl.
Unfortunately, these versions of Cocos/NDK seem to refuse compiling without SSE ...

Well I need to try this from command line with cocos console, but I can't figure out how to run the app on an emulator from there, any help is welcome.

**Comment by minggo** [comment]
But we built with Android SDK lower than 21 and run on X86 device, it doesn't have problem. I am not sure if it is caused by Android Studio or not.

**Comment by KrissMu** [comment]
I'm still investigating to see if I can find the exact thing that does not work. 

However, could it be related to the emulator ? As far as I know, Android Studio does nothing else than using NDK tools to compile the C++ code and copy/run the apk on the emulator. I don't really see what could be different from cocos console, except for the emulator definition/configuration.

**Comment by minggo** [comment]
You don't test on android device?

**Comment by angelvet** [comment]
Hello minggo,

NDK r10c, cocos2d-x-3.3rc2

See my steps to reproduce,
- create initial cocos application with 'cocos new -l cpp ...'
- cocos compile -v -p android -m debug -j 8 --ap android-10
- adb -s emulator-5554 install -s "application.apk"'
- run app on emulator.

My emulator setup are: Android 4.0.3 (API Level 15), CPU/ABI: Intel Atom (x86), Use Host GPU option is set.

Also I tested with NDK r10d on x86 emulator and got another SIGSEGV that wasn't related to the SSE issue.

I have tested x86 build only on the emulator.

**Comment by KrissMu** [comment]
minggo,

Unfortunately I don't have a real x86 device, so I have to test this architecture on a virtual one (API 19 for now).

After several hours of various tests, I can confirm that the crash happens when dst is modified at the end of the multiplyMatrix(const __m128 m1[4], const __m128 m2[4], __m128 dst[4]) function.
It won't happen the first call, but quite regularly after about 2000 calls.

I have tested with and without HAXM Intel x86 Emulator Accelerator.

At this point, I can't really do more, I expect this to be related to virtual devices even if they are supposed to mirror real ones behaviour. I cannot have access to an x86 real device and I don't even know how many of them there are on the market (all devices I got are ARM-based).

**Comment by minggo** [comment]
@KrissMu 
We tested on x86 real device, there is not problem. 
As we always suggestion, i suggest you test on real device in Android world.

**Comment by KrissMu** [comment]
Ok fine for me then, I'll try to report the issue to the AVD developers if I can find them.

Thanks

**Comment by ondesly** [comment]
Hi guys,
I started to get crash logs with this issue after update to 3.3. I think it happens only on few devices. That's why it's hard to reproduce.
Devices:
Asus ME302C, K00Z, T00G
Samsung P5200, P5210, P5220
Motorola XT890

**Comment by minggo** [comment]
@ondesly 
Could you please turn off SSE to have a try?
We will take a look.
Thanks

**Comment by ondesly** [comment]
@minggo 
It works with -U__SSE__ flag.

But after that I caught crash in release mode in another place on the same device (only x86).
App works fine few seconds and then crash happens. I disabled all rotation animations and it started to work fine.

CCNode.cpp:1712:
   float radiansX = -CC_DEGREES_TO_RADIANS(_rotationZ_X);
   float radiansY = -CC_DEGREES_TO_RADIANS(_rotationZ_Y);      <- Crash here

I tried to fix it and found that this works (without minus):
   float radiansX = CC_DEGREES_TO_RADIANS(_rotationZ_X);
   float radiansY = CC_DEGREES_TO_RADIANS(_rotationZ_Y);

But I couldn't make it negative in another place, crash happened there. It's like mysticism.
I tried to clean and rebuild several times. And I found that if I change NDK from r10d to r10c, it works.

So I returned to NDK r10c for now.

**Comment by sunzhuoshi** [comment]
hi @KrissMu @ondesly 
Sorry for such a late response.
I wrote SSE code in cocos2d-x, and I'm trying to reproduce and fix it. 
Unfortunately, I still can't reproduce the issue by now :(

cocos2d-x version: 3.3
test app: cpp-tests
Dev env: MacOS X
Device: Samsung P5200, Asus K011
Android: 4.2.2
NDK: r10c

Would you please share your test apks to me? my email is sunzhuoshi#gmail.com.
thanks a lot

**Comment by ondesly** [comment]
Hi @sunzhuoshi
I checked build with r10c. It works fine.
It seems that you should use r10d to reproduce this issue.

**Comment by sunzhuoshi** [comment]
@ondesly  thanks and you mean with SSE on or off?

**Comment by ondesly** [comment]
@sunzhuoshi 
Build with r10c works with SSE on and off.
Build with r10d works only with SSE off.

Target SDK = 21
cocos2d-x = 3.3
Device = Asus ME302C, Android 4.3

**Comment by sunzhuoshi** [comment]
@ondesly thanks for your valuable information, I'll check and try to fix it.

**Comment by KrissMu** [comment]
Hi, any news about this issue ? Working on emulators with x86 is far faster than ARM, but the application randomly crashes because of this.

Thanks.

**Comment by sunzhuoshi** [comment]
@KrissMu 
Sorry about the late update.
I've tried to fix it, but the root cause is not the engine code.
The only workaround now is to use NDK r10c and turn off SSE via "-U__SSE__"
:(

**Comment by KrissMu** [comment]
I have downgraded my NDK version to r10c, but I can't compile with SSE off, I get the message:

android-ndk-r10c/toolchains/llvm-3.5/prebuilt/windows-x86_64/bin..\lib\clang\3.5\include\xmmintrin.h:28:2: error: "SSE instruction set not enabled"

just like in r10d :(

**Comment by sunzhuoshi** [comment]
@KrissMu 
Show you full log here.
It looks strange, for all SSE header files SHOULD be included as follows:

``` cpp
#ifdef __SSE__
#include <xmmintrin.h>
#endif
```

**Comment by KrissMu** [comment]
Hi,

Here is the log

```
In file included from jni/sources/main.cpp:1:
In file included from jni/../../../../../Classes\AppDelegate.h:4:
In file included from jni/../../../../../cocos2d/cocos/3d/..\cocos2d.h:42:
In file included from jni/../../../../../cocos2d/cocos/3d/../base/CCRefPtr.h:30:
In file included from jni/../../../../../cocos2d/cocos/3d/..\base/ccMacros.h:73:
In file included from jni/../../../../../cocos2d/cocos/3d/..\base/ccRandom.h:29:
In file included from E:/Software/AndroidStudio/android-ndk-r10c/sources/cxx-stl/gnu-libstdc++/4.8/include\random:51:
In file included from E:/Software/AndroidStudio/android-ndk-r10c/sources/cxx-stl/gnu-libstdc++/4.8/libs/x86/include\bits/opt_random.h:33:
In file included from E:/Software/AndroidStudio/android-ndk-r10c/toolchains/llvm-3.5/prebuilt/windows-x86_64/bin\..\lib\clang\3.5\include\x86intrin.h:29:
In file included from E:/Software/AndroidStudio/android-ndk-r10c/toolchains/llvm-3.5/prebuilt/windows-x86_64/bin\..\lib\clang\3.5\include\immintrin.h:36:
In file included from E:/Software/AndroidStudio/android-ndk-r10c/toolchains/llvm-3.5/prebuilt/windows-x86_64/bin\..\lib\clang\3.5\include\emmintrin.h:31:
E:/Software/AndroidStudio/android-ndk-r10c/toolchains/llvm-3.5/prebuilt/windows-x86_64/bin\..\lib\clang\3.5\include\xmmintrin.h:28:2: error: "SSE instruction set not enabled"
#error "SSE instruction set not enabled"
 ^
```

Note that I have the following line at the beginning of Application.mk:

```
NDK_TOOLCHAIN_VERSION := clang
```

If I remove it, the compiler complains about not finding "std" stuff like thread or mutex.

**Comment by larsven** [comment]
I have to include "-U__SSE__" to be able to run my game in Genymotion. With other emulators, or when running directly on devices, this is not needed.

I have tested with both r10c and r10d and there is no difference.

**Comment by sunzhuoshi** [comment]
Sorry @KrissMu  I failed to reproduce your issue.
cocos2d-x: 3.3
OS: windows 7
NDK: r10c
I tried to build "cpp-empty-test" project via "build/android-build.py cpp-empty-test", it just passed.

**Comment by KrissMu** [comment]
@sunzhuoshi I think the compile error I had was related to the flag APP_STL := gnustl_static I was using. I changed it to what CppTest is using (APP_STL := c++_static) and it's working now.

Thanks

**Comment by Dimon4eg** [comment]
For me also helped this:
APP_CPPFLAGS += -U__SSE__

It crashed all the time on CHUWI Hi10plus (x86) device.

cocos2d-x 3.16

signal 11 (SIGSEGV), code 128 (SI_KERNEL)
cht_cr_mrd_w, Android 5.1

backtrace:
  #00  pc 0000000000792fd3  /data/app/xxx/lib/x86/libcocos2djs.so (_ZN7cocos2d8MathUtil14multiplyMatrixEPKDv4_fS3_PS1_+19)
  #01  pc 00000000006da98b  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&, cocos2d::Mat4 const&, cocos2d::Mat4*)+43)
  #02  pc 00000000006da9c7  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&)+39)
  #03  pc 0000000000651e2a  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Node::getNodeToParentTransform() const+634)
  #04  pc 000000000068bd71  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Sprite::updateTransform()+993)
  #05  pc 000000000068e2cf  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::SpriteBatchNode::insertQuadFromSprite(cocos2d::Sprite*, int)+447)
  #06  pc 00000000006384f7  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Label::updateQuads()+855)
  #07  pc 000000000063be5e  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Label::alignText()+702)
  #08  pc 0000000000638b43  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Label::updateContent()+387)
  #09  pc 00000000006339d5  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::Label::getContentSize() const+37)
  #10  pc 00000000005a8e46  /data/app/xxx/lib/x86/libcocos2djs.so (cocos2d::ui::Text::setFontName(std::string const&)+166)
  #11  pc 00000000004ddd03  /data/app/xxx/lib/x86/libcocos2djs.so (js_cocos2dx_ui_Text_setFontName(JSContext*, unsigned int, JS::Value*)+371)
  #12  pc 0000000000a4fa27  /data/app/xxx/lib/x86/libcocos2djs.so
  #13  pc 0000000000a4a01a  /data/app/xxx/lib/x86/libcocos2djs.so
  #14  pc 0000000000a4eda3  /data/app/xxx/lib/x86/libcocos2djs.so
  #15  pc 0000000000a4f93a  /data/app/xxx/lib/x86/libcocos2djs.so
  #16  pc 0000000000931c12  /data/app/xxx/lib/x86/libcocos2djs.so
  #17  pc 0000000000a4fa27  /data/app/xxx/lib/x86/libcocos2djs.so
  #18  pc 0000000000a4a01a  /data/app/xxx/lib/x86/libcocos2djs.so
  #19  pc 0000000000a4eda3  /data/app/xxx/lib/x86/libcocos2djs.so
  #20  pc 0000000000a4f93a  /data/app/xxx/lib/x86/libcocos2djs.so
  #21  pc 0000000000931c12  /data/app/xxx/lib/x86/libcocos2djs.so
  #22  pc 0000000000a4fa27  /data/app/xxx/lib/x86/libcocos2djs.so
  #23  pc 0000000000a4a01a  /data/app/xxx/lib/x86/libcocos2djs.so
  #24  pc 0000000000a4eda3  /data/app/xxx/lib/x86/libcocos2djs.so
  #25  pc 0000000000a4f93a  /data/app/xxx/lib/x86/libcocos2djs.so
  #26  pc 0000000000a5059b  /data/app/xxx/lib/x86/libcocos2djs.so
  #27  pc 0000000000c242cc  /data/app/xxx/lib/x86/libcocos2djs.so
  #28  pc 0000000000006904  [anon:js-jit-code]
  #29  pc 000000000080e6c7  [heap]
  #30  pc 0000000000000859  [anon:js-jit-code]
  #31  pc 0000000000c2f456  /data/app/xxx/lib/x86/libcocos2djs.so
  #32  pc 0000000000c2f668  /data/app/xxx/lib/x86/libcocos2djs.so
  #33  pc 0000000000a4e2c9  /data/app/xxx/lib/x86/libcocos2djs.so
  #34  pc 0000000000a4eda3  /data/app/xxx/lib/x86/libcocos2djs.so
  #35  pc 0000000000a4f93a  /data/app/xxx/lib/x86/libcocos2djs.so
  #36  pc 0000000000931c12  /data/app/xxx/lib/x86/libcocos2djs.so
  #37  pc 0000000000a4fa27  /data/app/xxx/lib/x86/libcocos2djs.so
  #38  pc 0000000000a4a01a  /data/app/xxx/lib/x86/libcocos2djs.so
  #39  pc 0000000000a4eda3  /data/app/xxx/lib/x86/libcocos2djs.so
  #40  pc 0000000000a4f93a  /data/app/xxx/lib/x86/libcocos2djs.so
  #41  pc 0000000000a5059b  /data/app/xxx/lib/x86/libcocos2djs.so
  #42  pc 0000000000c242cc  /data/app/xxx/lib/x86/libcocos2djs.so
  #43  pc 0000000000006904  [anon:js-jit-code]
  #44  pc 000000000080e6c7  [heap]
  #45  pc 0000000000000859  [anon:js-jit-code]
  #46  pc 0000000000c2f456  /data/app/xxx/lib/x86/libcocos2djs.so
  #47  pc 0000000000c2f668  /data/app/xxx/lib/x86/libcocos2djs.so
  #48  pc 0000000000a4e2c9  /data/app/xxx/lib/x86/libcocos2djs.so
  #49  pc 0000000000a4eda3  /data/app/xxx/lib/x86/libcocos2djs.so
  #50  pc 0000000000a4f93a  /data/app/xxx/lib/x86/libcocos2djs.so
  #51  pc 0000000000931c12  /data/app/xxx/lib/x86/libcocos2djs.so
  #52  pc 0000000000a4fa27  /data/app/xxx/lib/x86/libcocos2djs.so
  #53  pc 0000000000a4a01a  /data/app/xxx/lib/x86/libcocos2djs.so
  #54  pc 0000000000a4eda3  /data/app/xxx/lib/x86/libcocos2djs.so
  #55  pc 0000000000a4f93a  /data/app/xxx/lib/x86/libcocos2djs.so
  #56  pc 0000000000a5059b  /data/app/xxx/lib/x86/libcocos2djs.so
  #57  pc 0000000000c242cc  /data/app/xxx/lib/x86/libcocos2djs.so
  #58  pc 0000000000006904  [anon:js-jit-code]
  #59  pc 000000000080e6c7  [heap]
  #60  pc 0000000000000859  [anon:js-jit-code]
  #61  pc 0000000000c2f456  /data/app/xxx/lib/x86/libcocos2djs.so
  #62  pc 0000000000c2f668  /data/app/xxx/lib/x86/libcocos2djs.so
  #63  pc 0000000000a4e2c9  /data/app/xxx/lib/x86/libcocos2djs.so
