### ISSUE TITLE
New AudioEngine in 3.3rc0 does not loop on Android 2.3.x

### ISSUE THREAD

**Issue by hawkwood** [cocos2d/cocos2d-x#8965]
I built (using NDK r9d) and installed CppTests an original Kindle Fire (Android 2.3.3) and Samsung Nexus S (Android 2.3.4), selected "Audio - NewAudioEngine", tapped "enabled-loop" (which changed to "disable-loop") and tapped play.  The audio played through once and stopped.  I have verified that it does work properly on a Kindle Fire HDX.

**Comment by minggo** [comment]
So, you mean it only happened on Kindle Fire?

**Comment by hawkwood** [comment]
No, it failed to loop on both the original Kindle Fire (Android 2.3.3) and Samsung Nexus S (Android 2.3.4)

**Comment by minggo** [comment]
Thanks.
So it happened on some Android devices, not all Android devices.
Right?

**Comment by hawkwood** [comment]
Correct.  On my little investigation I would surmise that it has to do with Android 2.3.x, as The Fire HDX runs Android 4.x and worked fine.

**Comment by minggo** [comment]
Thanks.
We will check it.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9098

**Comment by minggo** [comment]
@hawkwood 
Could you check it?

**Comment by hawkwood** [comment]
Downloaded zip of repo, built, installed, ran, tapped "Audio - NewAudioEngine" and the app crashed.  The folder .../tests/cpp-tests/Resources/ccs-res/ was empty.  Copied content of folder from RC0, built, installed, ran, and it works!  And loops correctly too. 

Verified on Samsung Google phone (Android 2.3.4) and Kindle Fire (Android 2.3.3)
