### ISSUE TITLE
New WebView and VideoPlayer in 3.3rc0 in wrong place on Android 2.3.x

### ISSUE THREAD

**Issue by hawkwood** [cocos2d/cocos2d-x#8966]
I built (using NDK r9d) and installed CppTests an original Kindle Fire (Android 2.3.3) and Samsung Nexus S (Android 2.3.4), selected "Node: UI" > "GUI Dynamic Create Test" > "VideoPlayerTest" or "WebViewTest".  In  both instances, the view appeared in the upper-left hand corner, not centered as expected.  I have verified that it does work properly on a Kindle Fire HDX.

**Comment by WenhaiLin** [comment]
Fix at https://github.com/cocos2d/cocos2d-x/pull/9105

**Comment by minggo** [comment]
@hawkwood 
Could you please test it?

**Comment by hawkwood** [comment]
Verified web view works properly in CppTests on Samsung Google phone (Android 2.3.4).  On Kindle Fire (Android 2.3.3) looks like the GL layer is incorrectly sized, not taking in to account the bar at the bottom.  This is a general issue of Cocos, not specific to the web view/video player issue.

![img_1962](https://cloud.githubusercontent.com/assets/672455/5035175/f6ea7682-6b29-11e4-93f3-30c6ecac9b61.JPG)

Video player:
On Kindle Fire HDX (Android 4.x), the video player jumps from the upper left corner to correct location when starting a video for the first time.  Subsequent video starts without leaving the scene were in the correct location.
On Samsung Google phone (Android 2.3.4) the jump from corner is more notable, but the video does not start giving an "unsupported format" pop up.
On Kindle Fire (Android 2.3.3) the video player appears in the corner, does not move and shows an "unsupported format" pop up.

**Comment by minggo** [comment]
@hawkwood
Could you please create new issue for the wrong size?
Thanks.
