### ISSUE TITLE
Use same image（.png） file ,the ImageView（UIimageview） darker than sprite

### ISSUE THREAD

**Issue by hanrea** [cocos2d/cocos2d-x#8978]
Use same image file（.png）,the ImageView（UIimageview） darker than sprite.please @andyque to deal it.

If need help，please contact me with code ”FGv6wBTkI4THMBDFEwGY0bY9h2_gJII“

**Comment by zilongshanren** [comment]
@hanrea 
Thanks for reporting this issue. I have tested it but I can't notice the differences.

Could you please upload some screenshot here?
