### ISSUE TITLE
can't check right Shift and right Ctrl now

### ISSUE THREAD

**Issue by sappho192** [cocos2d/cocos2d-x#8988]
It seems that KeyCode in cocos2d-x is not able to check right Shift and right Ctrl.  
I think this should be solved.
And how can I check these keys in current version?(3.3 rc0)

**Comment by dumganhar** [comment]
@sappho192 , thanks for your feedback.
Yes, desktop platforms need to distinguish `left control key` and `right control key`.
What i'm thinking about is how to make compatibility with the old design? I mean we have `KeyCode::KEY_SHIFT`, if we add `KeyCode::KEY_LEFT_SHIFT` and `KeyCode::KEY_RIGHT_SHIFT`, should we dispatch `KEY_SHIFT` event?

**Comment by sappho192** [comment]
I agree with make compatibility, but don't understand what "dispatch KEY_SHIFT event" exactly mean. Are you saying should we leave KeyCode::KEY_SHIFT for compatibility issue? Then, I think yes. How about regard KEY_SHIFT as KEY_LEFT_SHIFT(because most think Shift as Left Shift) and mark KEY_SHIFT as deprecated? Then people wil fix if they need to do it.

![image](https://cloud.githubusercontent.com/assets/7788738/5185763/0ee50290-7505-11e4-9b2d-4e181c410923.png)
Plus, I could find "CCGLViewImpl-Desktop.cpp" which assigns "GLFW_KEY_something" to EventKeyboard::KeyCode. And it regards left function keys and right function keys as same thing. I think we just need to modify this one and EventKeyboard class, right?

**Comment by dumganhar** [comment]
@sappho192 , I sent a PR #9241 for fix this issue. Could you take a look? Thanks.

**Comment by sappho192** [comment]
It's a little bit hard to understand the codes in line 664~697 of CCGLViewImpl-desktop.cpp. Does this codes separate Left events and Right events? Then, I think you did a great job! Thanks!

**Comment by dumganhar** [comment]
> Does this codes separate Left events and Right events? 

Yes. New enums have been added. If there are left or right CONTROL event, the original CONTROL without `left` and `right` will also be triggered for compatibility.

**Comment by sappho192** [comment]
Hmm...Then actually 2 events are triggered, right?

**Comment by dumganhar** [comment]
Yes, is there any problem of this ? Developer will never focus on `KEY_LEFT_SHIFT` and `KEY_SHIFT` at the same time.

**Comment by sappho192** [comment]
I'm making rhythm game using cocos2d-x, and there will be a judgement for double input of shift key..

**Comment by dumganhar** [comment]
What do you mean of `a judgement for double input`? Could you paste some pseudo codes?

**Comment by minggo** [comment]
We fire both key just to keep compatibility.

**Comment by sappho192** [comment]
@dumganhar didn't make code yet, but I can explain.
![image](https://cloud.githubusercontent.com/assets/7788738/5215342/b51144ac-7669-11e4-835f-762e7d8403c7.png)
In this image, user will press a key which corresponds to Scratch(leftmost or rightmost red note) soon. In general the red note will removed by pressing Left Shift(for 1P player) or Right Shift(for 2P player).
Like your solution, KEY_LEFT_SHIFT and KEY_SHIFT will triggered so there will be actually 2 Shift input, right? Then the program will judge both input..

**Comment by minggo** [comment]
@sappho192 
I think it will have problem if the application response KEY_SHIFT and KEY_LEFT_SHIFT. 
In your sample, the app should only response KEY_LEFT_SHIFT, it will not response KEY_SHIFT.
Right?

**Comment by sappho192** [comment]
@minggo Exactly. So I said on above,

> How about regarding KEY_SHIFT as KEY_LEFT_SHIFT(because most think Shift as Left Shift) and mark KEY_SHIFT as deprecated? Then people wil fix if they need to do it.

![image](https://cloud.githubusercontent.com/assets/7788738/5224397/c43fb4a6-7716-11e4-9491-c12d4504728f.png)
I think it can be done by same enumeration like above.

**Comment by minggo** [comment]
@sappho192 
I think it is better.

**Comment by minggo** [comment]
@Dhilan007 
Could you please fix it？

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9449

**Comment by sappho192** [comment]
I checked it. Thanks @Dhilan007 .
