### ISSUE TITLE
cocos2s-x-emscripten frame rate divided by 2 after small browser usage

### ISSUE THREAD

**Issue by TheJohnTalent** [cocos2d/cocos2d-x#8989]
Compiled cocos2s-x emscripten based demos (particle effects) goes from 60 fps frame rates
continually to 30 fps frame rate from then on after small browser you tube viewing occurs in between.

i am using the latest debian Iceweasel (firefox) browser under debian 7.7 (3.2 kernel) linux.

If you have any questions i can be reached at lutz.john@yahoo.com.

Thanks!

**Comment by walzer** [comment]
Sorry, we haven't support emscripten since v3.0.
