### ISSUE TITLE
ScrollView with solid color crash

### ISSUE THREAD

**Issue by miguel12345** [cocos2d/cocos2d-x#8991]
## Steps:

1 - Download latest commit of cocos2d-x from github repo
2 - Download depedencies
3 - Create a simple scene 
4 - Add a scrollview as its child like so:

```
    ui::ScrollView* crashingScrollView = ui::ScrollView::create();
    crashingScrollView->setContentSize(Size(400,400));
    crashingScrollView->setBackGroundColorType(cocos2d::ui::Layout::BackGroundColorType::SOLID);
    crashingScrollView->setBackGroundColor(cocos2d::Color3B::GRAY);
    scene->addChild(crashingScrollView);
```

5 - Run the application

Expected result : The list view should appear
Observed result : The application crashes here:

![screenshot 2014-11-02 11 53 19](https://cloud.githubusercontent.com/assets/1169497/4875160/e040e282-6286-11e4-8fda-254504249ea2.png)
## Notes:

This only affects ScrollView and subclasses. If using a Layout like so:

```
    ui::Layout* workingLayout = ui::Layout::create();
    workingLayout->setContentSize(Size(400,400));
    workingLayout->setBackGroundColorType(cocos2d::ui::Layout::BackGroundColorType::SOLID);
    workingLayout->setBackGroundColor(cocos2d::Color3B::GRAY);
    scene->addChild(workingLayout);
```

it works ok.

If using a background image like so:

```
    ui::ScrollView* workingScrollView = ui::ScrollView::create();
    workingScrollView->setContentSize(Size(400,400));
    workingScrollView->setBackGroundImage("HelloWorld.png");
    scene->addChild(workingScrollView);
```

it works ok too.

**Comment by zilongshanren** [comment]
@miguel12345 
Thanks for reporting the issue. I will check it later.

**Comment by Almax27** [comment]
I have also experienced this issue. The crash point is either at glDrawArrays seen above or occasionally: 

**CCEAGLView-ios.mm (line 318)**

``` c++
if(![context_ presentRenderbuffer:GL_RENDERBUFFER])
{
//         CCLOG(@"cocos2d: Failed to swap renderbuffer in %s\n", __FUNCTION__);
}
```

http://stackoverflow.com/questions/22693753/bad-access-error-in-eaglview-mm

-- similar issue here: possibly somewhere is not unbinding VAO after use
http://stackoverflow.com/questions/14196977/gpus-returnguiltyforhardwarerestart-crash

**Comment by zilongshanren** [comment]
@miguel12345 @Almax27 
Thanks. 
This issue was solved at https://github.com/cocos2d/cocos2d-x/pull/9052

Please check the latest code from Github. I think it is solved now.

**Comment by miguel12345** [comment]
Checked latest code from Github and I can confirm that the crash no longer happens.
