### ISSUE TITLE
Different header search paths on iOS and android

### ISSUE THREAD

**Issue by miguel12345** [cocos2d/cocos2d-x#8994]
## Steps:

1 - Download latest commit of cocos2d-x from github repo
2 - Download dependencies
3 - Create new project
4 - Include UILayout in HelloWorldScene.cpp

```
#include "UILayout.h"
```

5 - Compile on android and on iOS

Expected result - Should compile successfully on both platforms
Observed result - Fails to compile on Android
## Problem

Inside iOS cpp template `HEADER_SEARCH_PATHS` contains `"$(SRCROOT)/../cocos2d/cocos/ui"`  but on android's `cocos/ui/Android.mk` doesn't have `$(LOCAL_PATH)` in `LOCAL_EXPORT_C_INCLUDES` therefore we can't include UILayout directly in the sample project

We need to have coherence here. Is the user supposed to be able to directly import UILayout or not?

```
#include "UILayout.h"
```

or

```
#include "ui/UILayout.h"
```

**Comment by zilongshanren** [comment]
@miguel12345  We should include "ui/CocosGUI.h" instead of including "ui/UILayout.h".
I

**Comment by minggo** [comment]
it is fixed
