### ISSUE TITLE
Why EventListener's isRegistered, isPaused, getFixedPriority, getAssociatedNode functions are protected ?

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#8996]
I think these functions are useful and should be public for user. For example, if a user register listeners dynamically in his game, and he didn't know for sure whether the listener have been registered, he should have a way to know it.
Personal opinion, happy to hear different voices

**Comment by minggo** [comment]
I think it is reasonable to make the functions public. @dumganhar , is there reason that they are declared as protected?

**Comment by minggo** [comment]
The benefit i can image is that, we don't have to bind it to lua/js if they are not needed.
