### ISSUE TITLE
UIText使用自己的.ttf字体会产生内存泄露问题

### ISSUE THREAD

**Issue by puckery** [cocos2d/cocos2d-x#9000]
UIText使用自己的.ttf字体会产生内存泄露问题，使用系统字体是正常的。
原生CCLabel是没问题的。

**Comment by aeonmine** [comment]
now all of the ui widget object occur memory leak 
it fixed   #8999

**Comment by puckery** [comment]
我用的是3.2版本

**Comment by elonlo** [comment]
这个问题是什么原因导致的？

**Comment by minggo** [comment]
Duplicated with #8999.
