### ISSUE TITLE
Label和Text生成产生的内存差别非常大！！

### ISSUE THREAD

**Issue by puckery** [cocos2d/cocos2d-x#9004]
```
   // 66M
for (int i = 0; i < 1000; i++)
{

    Text* alert = Text::create("Text","my.ttf", 30);
    alert->setPosition(Vec2(100 + i * 10, 100));
    this->addChild(alert);
}

   // 45M
for (int i = 0; i < 1000; i++)
{
    Label* alert = Label::createWithTTF("Text","my.ttf", 30);
    alert->setPosition(Vec2(100 + i * 10, 100));
    this->addChild(alert);
}
```

如上，在3.2版本中测试，直接用Label生成1000个是45M，用Text是66M.
(3.3版本存在同样问题)

**Comment by zilongshanren** [comment]
@puckery 
Thanks, We will test it and give you feedback later.

**Comment by walzer** [comment]
@andyque Any update?

**Comment by zilongshanren** [comment]
@walzer  ui::Text is a Node + cocos2d::Label + some extra attributes. But cocos2d::Label is just a node.
That's why ui::Text consumes more memory.

I think I can't optimize much in current architecture unless we change to Component instead of Inheritent

**Comment by zilongshanren** [comment]
@puckery I have optimized the ui::Text in v3.7, could you help me to test it?
The memory consumption should be reduced now.
But as I mentioned above, they are still extra memory consumption in ui::Text.
Thanks.
