### ISSUE TITLE
New feature - AudioEngine::cache

### ISSUE THREAD

**Issue by zawasp** [cocos2d/cocos2d-x#9008]
We need to be able to cache the sound effects, to avoid delays when playing the sound for the first time (similar to preloadSoundEffect in SimpleAudioEngine).

Thanks.

**Comment by sappho192** [comment]
I think this is necessary, too!

**Comment by WenhaiLin** [comment]
Hi @zawasp Which platform do you develop for?

**Comment by zawasp** [comment]
Hi @Dhilan007, I develop for Android and iOS, but do the development on Windows in Visual Studio. I added some code for win32 and iOS in my branch:

https://github.com/zawasp/cocos2d-x/tree/v3-audio-cache

This is based on a part of AudioEngine::play2d method on win32 and iOS.

**Comment by sappho192** [comment]
Thanks for the win32 implement, @zawasp .

**Comment by sappho192** [comment]
did this applied on official branch?

**Comment by zawasp** [comment]
@sappho192 There's no pull request for it yet. I just modified it for my own use - feel free to use it and add it to the official branch.

**Comment by sappho192** [comment]
Thanks @zawasp . I was exactly needed it. So you don't think pull request to the official branch now?

**Comment by zawasp** [comment]
@sappho192 I will refactor it a bit a do a pull request these days.

**Comment by sappho192** [comment]
nice!

**Comment by sappho192** [comment]
@WenhaiLin Has this feature been implemented?

**Comment by WenhaiLin** [comment]
@sappho192 Now that preload(cache) feature  is implemented except Android.

**Comment by sappho192** [comment]
@WenhaiLin  OK. Thanks.

**Comment by minggo** [comment]
And Android cache will be added, can refer to #15875 for detail information.

**Comment by minggo** [comment]
So close this issue and please refer to the PR.
