### ISSUE TITLE
setScale of Scene didn't run in the v3.3rc0

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#9031]

**Comment by samuele3hu** [comment]
Take Controller scene of cpp-tests for example,modify controller.cpp as follows:
void TestController::menuCallback(Ref \* sender)
{
   ....
   int idx = menuItem->getLocalZOrder() - 10000;

```
// create the test scene and run it
```

//    auto scene = g_aTestNames[idx].callback();
//
//    if (scene)
//    {
//        scene->runThisTest();
//        scene->release();
//    }
    auto scene = Director::getInstance()->getRunningScene();
    if (nullptr != scene) {
        scene->setScale(0.5);
    }
}
before call Scene:setScale:
![before_setscale](https://cloud.githubusercontent.com/assets/4231014/4947431/d0fdbeee-6623-11e4-9cdd-6c7d118ce234.png)

after call Scene:setScale:
![after_setscale](https://cloud.githubusercontent.com/assets/4231014/4947437/e4679ba8-6623-11e4-9e2c-d8dc610e75ee.png)

you can see the controller scene didn't scale and some menu item aren't clicked.

**Comment by minggo** [comment]
@samuele3hu 
Please test it.
Thanks.
