### ISSUE TITLE
luac from cocos2d-x 3.3rc0 console's luacompile cant not run on iPhone5s\iPhone6(64bit devices)

### ISSUE THREAD

**Issue by kary24** [cocos2d/cocos2d-x#9064]
luac from cocos2d-x 3.3rc0 console's luacompile cant not run on iPhone5s\iPhone6(64bit devices)

**Comment by minggo** [comment]
Yep, luac uses luagit to generate binary format.
And we use lua compiler on iPhone5s\iPhone6(64bit devices) because luajit doesn't support 64 bit.

**Comment by kary24** [comment]
emm but its not a good idea to make two diffent ipa for 32bit or 64bit devices .is that any good idea to fix the problem？

**Comment by samuele3hu** [comment]
I think we could optimize `cocos luacompile`.Now we already support xxtea encrypt,but this mechanism only takes effect after the files compiled by the `luajit`.I have modified the related luacompile files manually to let xxtea encryp can used to the original lua files,and verified on 32bit and 64bit iOS simulator,the result is ok.How do you think this solution?

**Comment by kary24** [comment]
@samuele3hu its great .But how can i do that.
