### ISSUE TITLE
使用CocosStudio2.0中的.csb资源创建Node出现错误

### ISSUE THREAD

**Issue by zhourihu5** [cocos2d/cocos2d-x#9065]
使用CocosStudio资源来创建节点等报错load_library(linker.cpp:760): library "libmaliinstr.so" not found 这个是什么原因造成的，怎么解决？

auto rootNode = CSLoader::createNode("MainScene.csb");

```
addChild(rootNode);

auto closeItem = static_cast<ui::Button*>(rootNode->getChildByName("Button_1"));
closeItem->addTouchEventListener(CC_CALLBACK_1(HelloWorld::menuCloseCallback, this));
```

![wvx5c 8sa1qy6ae l 9p](https://cloud.githubusercontent.com/assets/6065046/4964125/d0c28736-6784-11e4-8e5d-8568cb54d098.jpg)

**Comment by chengstory** [comment]
@pipu Please take a look.

**Comment by einverne** [comment]
same error

**Comment by zilongshanren** [comment]
The problem is not related to CocoStudio, it is the libmaliinstr.so which can't be loaded.
