### ISSUE TITLE
cocos2d-x 3.2 and 3.3rc0's "Accelerometer" out of control especially in IOS8.1 

### ISSUE THREAD

**Issue by waitingfy** [cocos2d/cocos2d-x#9079]
1. My game just use acc->x, when I left greatly inclined the mobile phone after a few seconds, and then right inclined the mobile phone, the value of acc->x still is Negative。
2. It happed in IOS 8.1. IOS 7 sometimes happend。
3. Accelerometer works well in android, but I only test it in one android mobile phone.

因为我的游戏类似doodle jump的，只用到了陀螺仪的x值变化。 陀螺仪获得的值有时候会很奇怪，必现操作: 一直把手机往左大幅度倾斜，acc->x 的值是负的，过了几秒后，把手机往右倾斜，acc->x的值还是负的，等了几秒后，才会变成正的。

**Comment by waitingfy** [comment]
1. It's my problem
   how I fix:
2. before change scene, use  "Device::setAccelerometerEnabled(false);"
3. set interval much lower: 
   Device::setAccelerometerInterval(0.1);
   Device::setAccelerometerEnabled(true);

**Comment by dumganhar** [comment]
@waitingfy so was your solution a workaround?

> 1. before change scene, use "Device::setAccelerometerEnabled(false);"
> 2. set interval much lower: Device::setAccelerometerInterval(0.1); Device::setAccelerometerEnabled(true);

**Comment by waitingfy** [comment]
yes
