### ISSUE TITLE
Cocos2d-x 3.3rc0 webView setOnShouldStartLoading Android

### ISSUE THREAD

**Issue by davidboya** [cocos2d/cocos2d-x#9086]
setOnShouldStartLoading callback doesn't work on Android, I get no callback.
Tested it using cpp-tests. No callback there either. 
Using One Plus One with Android 4.4.4. This callback works fine on iOS though.

**Comment by zilongshanren** [comment]
Hi, @davidboya 
I have tested the `setOnShouldStartLoading` callback on Android and it works for me.

One thing you should make sure: you should add a `http://` prefix to the url.

**Comment by davidboya** [comment]
@andyque Very weird... I am using `http://` for all my URLs. But the weirdest thing is that `setOnShouldStartLoading` works nice on iOS simulator with exactly the same code. (Tested with cpp-tests, and my own app)

I've tested this on my app and cpp-tests on the following devices without any result getting a callback on `setOnShouldStartLoading`, something must be wrong with my development environment?
- HTC Incredible S (Android version 4.0.4)
- Samsung Galaxy S4 (Android version 4.4.2)
- One Plus One (Android version 4.4.4)

**Comment by zilongshanren** [comment]
@davidboya 
I'm not sure whether your development environment is wrong or not. 
I have tested on my Xiaomi Android phone(Android version is 4.4.4) and it works well.

I will try to test the cpp-test on Samsung Galaxy S4.
Thanks.

**Comment by dumganhar** [comment]
@davidboya, could you try the latest version to test it again?
