### ISSUE TITLE
关于FileUtils::getWritablePath(), ios app 审核被拒绝 Reason 2.23

### ISSUE THREAD

**Issue by colayue** [cocos2d/cocos2d-x#9093]
我的应用在审核时被拒绝，原因如下：
2.23: Apps must follow the iOS Data Storage Guidelines or they will be rejected
因此我查看了 iOS Data Storage Guidelines并找到了被拒绝的原因，如下：
我在我的应用中，使用了FileUtils::getWritablePath()作为下载路径，即<Application_Home>/Documents，这是不被允许的，在新的ios系统中，该路径只能用于存储用户产生的数据，并且会被icloud自动备份。如果需要存储下载数据，则应该使用<Application_Home>/Library/Caches路径。详见 iOS Data Storage Guidelines。
因此我在 FileUtils 加入了 getDownloadPath()函数，如下：
//cocos2d-x 3.2
std::string FileUtilsApple::getDownloadPath() const
//cocos2d-x 2.2.3
std::string CCFileUtilsIOS::getDownloadPath() const
{
    // save to document folder
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    std::string strRet = [documentsDirectory UTF8String];
    strRet.append("/");
    return strRet;
}

**Comment by dumganhar** [comment]
Yep, I also referred to https://developer.apple.com/icloud/documentation/data-storage/index.html 
the downloaded game resources should `not` be placed at `Documents` folder.
I think `getDownloadPath` isn't specified enough. How about just using `getCacheDirectory`?
