### ISSUE TITLE
Cocos2d-x v3.3rc0 Visual Studio Release build compile setting

### ISSUE THREAD

**Issue by MFHSchoonbrood** [cocos2d/cocos2d-x#9094]
Hi guys,

The release builds in visual studio always do a full rebuild, which takes a lot of time.
If you set Configuration Properties -> C/C++ -> General -> Debug Information Format to "Program Database (/Zi) for libbox2d, libcocos2d and libSpine, then the release version doesn't rebuild everything all the time anymore.

The above setting together with turning on incremental linking will speed up building release versions by a huge amount. The user can always chose to do a free rebuild to rebuild everything.

Could you set this as the default release settings?

Kind regards,
Michaël

**Comment by nurbed** [comment]
Ciao!
I have the same problem, but set the Debug Information Format option isn't a real solution... any other suggestion?

**Comment by tryy** [comment]
3d/3dExport.h
base/CCPlatformConfig.h
base/CCPlatformMacros.h
are miss, remove them from libcocos2d project.
