### ISSUE TITLE
CMake Errors

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#9102]
Hi,

I tried to use the v3.3 rc0 on a mac, with CLion, and got these errors from the cmake file : 

```
Error:include could not find load file:
    Classes/CMakeLists.txt
Error:Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
```

The first one comes from the line 61 of the cmake file, there is this line `include(Classes/CMakeLists.txt)` if we are running on a mac, which is weird because there is no `CMakeLists.txt` in the `Classes` directory. I just deleted it, is it ok ?

For the other one, I just don't know where to look... can you help me with this ?

**Comment by dariodepaolis** [comment]
I'm trying to resolve a similar issue on windows, cmake and clion.
I've written something here: http://discuss.cocos2d-x.org/t/trying-to-make-clion-working-with-cmake-and-cocos2dx/21405

**Comment by minggo** [comment]
there is not plan to support cmake+clion, and cmake works correctly on mac, so close this issue
