### ISSUE TITLE
CSParseBinary.proto

### ISSUE THREAD

**Issue by martell** [cocos2d/cocos2d-x#9109]
Where is this file?
If someone uses a different version of google's protobuf
They get this error
CSParseBinary.pb.h:18:2: error: 
# error This file was generated by an older version of protoc which is
# error incompatible with your Protocol Buffer headers.  Please
# error regenerate this file with a newer version of protoc.

I have no idea what protobuf does but we need the source not a generated binary blob

Can someone give instructions on how to generate the header and source file from this also

@ricardoquesada This may interest you :)

**Comment by minggo** [comment]
We will use flat buffer instead of protocol buffer before releasing v3.3.

**Comment by martell** [comment]
Thanks for the reply minggo :)
I am in the middle of releasing a cocos.py for msys2.
and the end user cant use CCB or CCS because of this.

The sooner the better on this so I can get in time for testing before 3.3 :)

**Comment by minggo** [comment]
already use flatbuffer for studio reader, so close this issue
