### ISSUE TITLE
cocos2dx v3.3rc0 The labelTest, layoutTest,labelTestNew will cause freeze on Android L 

### ISSUE THREAD

**Issue by aeonmine** [cocos2d/cocos2d-x#9114]
in cocos2dx v3.3rc0 The labelTest, layoutTest, labelTestNew can not work on Android L,

and the files exported from cocosstudio 1.5 json   and  cocosstudio 2.0 csb when using bitmap font in design will cause freeze on Android L

please fix this as soon as ..

in cocos2dx v3.2 it works fine.

**Comment by aeonmine** [comment]
i think the issue is caused by BmFont

**Comment by aeonmine** [comment]
I tested in cocos2dx v3.3rc0
all using BMFont can not work on Android L

**Comment by aeonmine** [comment]
I change the cocos2dx v3.3 rc0 Application.mk  to cocos2dx v3.2 it works fine 
and the httpclient also works fine 

I guess the APP_LDFLAGS := -latomic in  cocos2dx v3.3 rc0 has a problem

thanks

**Comment by aeonmine** [comment]
@minggo 
For BMFont and Httpclient Crash on Android L 
I fixed it by use cocos2dx v3.2 Androidk  instedof cocos2dx v3.3rc0 Androidk 

ex:
  Android.MK   in cocos2dx v3.3 rc0   (this will crash on Android L)

```
          APP_STL := c++_static
          NDK_TOOLCHAIN_VERSION=clang 
           APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
           APP_LDFLAGS := -latomic   this line may caused issue
           ifeq ($(NDK_DEBUG),1)
               APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
               APP_OPTIM := debug
            else
            APP_CPPFLAGS += -DNDEBUG
            APP_OPTIM := release
            endif
```

Android.MK   in cocos2dx v3.2 (this works fine  )

```
         NDK_TOOLCHAIN_VERSION=4.8
         APP_STL := gnustl_static
         APP_CPPFLAGS := -frtti -DCOCOS2D_DEBUG=1 -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
         APP_CPPFLAGS += -fexceptions 
```

**Comment by jgod** [comment]
Hey I'm running into this freeze now with v3.3.rc0. 
You said it might be `-latomic` but these lines are also changed (seem pretty drastic):

```
APP_STL := c++_static
NDK_TOOLCHAIN_VERSION=clang 
```

I'm working on a massive project that takes a while to recompile, any assistance to narrow it down is greatly appreciated!

I'll see if the sample projects will behave in my env in the meantime.

**Comment by jgod** [comment]
Some testing with release at `HEAD` (I forked it and added a couple things but it's pretty much the same):
Using ndk-r9d
- Created new project "LabelTest"
- Left default `.mk` files
- **Text-based .fnt freezes, Binary-based .fnt doesn't** (confirming [this](http://discuss.cocos2d-x.org/t/android-5-0-lollipop-freezes-with-cocos2dx-3-2-version-l-api-21/17811))

**Comment by aeonmine** [comment]
this line also had a problem

NDK_TOOLCHAIN_VERSION=clang 
->
NDK_TOOLCHAIN_VERSION=4.8

**Comment by WenhaiLin** [comment]
This issue is cause by 'sscanf' function. The specific reasons is unclear

**Comment by WenhaiLin** [comment]
This issue should be fixed in NDK r10c. For more information : https://code.google.com/p/android/issues/detail?id=77988
