### ISSUE TITLE
New AudioEngine will crash when play same audio file in same time

### ISSUE THREAD

**Issue by aeonmine** [cocos2d/cocos2d-x#9116]
the following code will crash in New AudioEngine  on Android

local sound_flg = 0
  local audio_id = 0
  local function update()
    if sound_flg == 0 then
      cclog("1".." aucioId "..audio_id)
      ccexp.AudioEngine:stop(audio_id)
      cclog("2".." aucioId "..audio_id)
      audio_id = ccexp.AudioEngine:play2d("/res/test.ogg")
      cclog("3".." aucioId "..audio_id)
      sound_flg = 1
    else
      cclog("4".." aucioId "..audio_id)
      ccexp.AudioEngine:stop(audio_id)
      cclog("5".." aucioId "..audio_id)
      audio_id = ccexp.AudioEngine:play2d("/res/test.ogg")
      cclog("6".." aucioId "..audio_id)
      sound_flg = 0
    end
  end

  self.layer:scheduleUpdateWithPriorityLua(update,1)

**Comment by aeonmine** [comment]
if change ccexp.AudioEngine:stop(audio_id) to ccexp.AudioEngine:pause(audio_id) that will not crash

**Comment by aeonmine** [comment]
but this issue can resolve by how to use

just change 

ccexp.AudioEngine:stop(audio_id) to 

ccexp.AudioEngine:pause(sound_id_02)
ccexp.AudioEngine:resume(sound_id_01)
ccexp.AudioEngine:setCurrentTime(sound_id_01,0)

it will run well

**Comment by WenhaiLin** [comment]
@aeonmine I can't reproduce this issue by your codes.I used the latest codes on github.
