### ISSUE TITLE
Scrollview crash when put a sprite or a button in front of it

### ISSUE THREAD

**Issue by huangliu** [cocos2d/cocos2d-x#9120]
Scrollview crash when put a sprite or a button in front of it, I use cocostudio2.0, but I think it's engine's bug

**Comment by zilongshanren** [comment]
@huangliu 

Could you please give me more information about this issue?
Some code snippets would be great. :)

Thanks.

**Comment by zilongshanren** [comment]
@huangliu 
I have tested this issue and added a sprite to a scrollView, then add the scrollView to the scene.

It works very well, no crash. Please help me to confirm this issue?

Thanks.

**Comment by huangliu** [comment]
@andyque 
Not add a sprite to the scrollView, instead of add a sprite to the scrollView's parent node, and in front of the scrollView, maybe set scrollView's color too.My thinkpad X200 crash on LayerColor::onDraw() function, when call glDrawArrays function inside.

**Comment by miguel12345** [comment]
He mentioned having set the scrollView's color and crashing on glDrawArrays, most likely its this issue

https://github.com/cocos2d/cocos2d-x/issues/8991

that was already solved. @huangliu Could you download the latest version from repo and confirm if the crash still happens?

**Comment by zilongshanren** [comment]
@huangliu 
I think @miguel12345  is right here, the issue was solved. Please help us to verify the latest code.
Thanks.

**Comment by huangliu** [comment]
@miguel12345 @andyque Which version you solved it? The issue occur in cocos2d-js v3.1 which embedded cocos2d-x v3.3-rc0

**Comment by zilongshanren** [comment]
@huangliu 
I think the latest cocos2d-x v3.3-rc1 has solved this issue.

**Comment by huangliu** [comment]
@andyque 
I tested the issue and it occur again with cocos2d-x v3.3-rc1. It hasn't been solved yet!

**Comment by zilongshanren** [comment]
@huangliu 
How do you test it？
could you paste some code here？and what platform do you use？

**Comment by huangliu** [comment]
@andyque 
The code is very simple like this:
Node *node = CSLoader::createNode("test.csb");
this->addChild(node);

and my platform is windows 8.1, thinkpad X200.

**Comment by zilongshanren** [comment]
@huangliu 
I have used the CocosStudio 2.0 to create a sample scene with a ScrollView and a button on top of it.
It works very well.

I have tested it on MacOSX 10.10.

If you are using Windows, please check the resources path is correct. 
And please paste the error stack and any output from your console to here.

Thanks.

**Comment by andriisavin** [comment]
The crash with the latest version (just 10 mins ago downloaded) on win 7. In Cocos studio 2.0.6 add ScrollView and press "play" -> crash. Or run the code
Node\* resource = CSLoader::createNode("test.csb");
addChild(resource);
Result again  -> crash 
For this line: glDrawArrays(GL_TRIANGLE_STRIP, 0, 4); of CCLayer.cpp (615)
