### ISSUE TITLE
iOS PIE 

### ISSUE THREAD

**Issue by Zambiorix** [cocos2d/cocos2d-x#9140]
I have noticed that the cocos2d-x libraries for iOS (OSX?) are not PIE enabled. I know that Apple still accepts non-PIE libraries, but at some point that will change.

The issues are with a few external libraries : 
libjpeg.a
libtiff.a

Currently I have replaced the libraries (together with the header files + there one extra .h file) with those from ImageMagick:
http://www.imagemagick.org/download/iOS/

That solves the problem. But it's inconvenient to redo this every time I run the downloads script.

Maybe it's time to update the libraries to PIE compatible ones?

Cheers

Gerd

**Comment by minggo** [comment]
Yep.
We will update them when 3rd party build script is ready.

**Comment by walzer** [comment]
Duplicate with #11153 , let's track that issue instead.
