### ISSUE TITLE
Fonts don't have crispness (looks very ghostly) and thickness varies between browsers

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#9145]
I've been trying to fix the quality of fonts for a while now. I'm using CCLabelTTF and the font thickness seems to vary a lot between browsers as well. Here's an example of MuseoSans_100.ttf:
Safari:

![screen shot 2014-11-17 at 7 50 48 pm](https://cloud.githubusercontent.com/assets/8293968/5082310/11921bf4-6e93-11e4-9390-0e470460750b.png)

Chrome:

![screen shot 2014-11-17 at 7 48 40 pm](https://cloud.githubusercontent.com/assets/8293968/5082304/e45dbc92-6e92-11e4-8568-06c5fe730380.png)

FireFox:

![screen shot 2014-11-17 at 7 51 13 pm](https://cloud.githubusercontent.com/assets/8293968/5082313/1a7475c8-6e93-11e4-9a9d-af1a9b6016f9.png)

I tried loading other fonts as well and the light weight ones look very ghostly.I looked at a lot of articles online for this and none of them seem to fix this issue. The version of Cocos I'm using is 2.2.2 but this seems to happen for V3.1 as well. I tried looking at a few other cocos2d html5 games out there and they all seem to have a very similar font quality.

**Comment by minggo** [comment]
I think you should create this issue here: https://github.com/cocos2d/cocos2d-js.
