### ISSUE TITLE
Emoji working incorrect on android

### ISSUE THREAD

**Issue by Spellzlol** [cocos2d/cocos2d-x#9150]
Emoji in text labels does not work on android version.

Code sample for sample application:    

```
Label* emoji = Label::createWithSystemFont("���", "Arial", 25);
this->addChild(emoji);
emoji->setPosition(visibleSize.width/2, visibleSize.height/2);
```

Ios result:

![ios simulator - iphone 6 - iphone 6 ios 8 1 12b411 2014-11-18 11-22-44](https://cloud.githubusercontent.com/assets/4716576/5084274/4827c704-6f15-11e4-9b28-a44946149a04.jpg)

Android result:

![screenshot](https://cloud.githubusercontent.com/assets/4716576/5084295/8bccdb8e-6f15-11e4-99dc-de152d653239.png)

Emoji used in label has Utf code 1F619 (KISSING FACE WITH SMILING EYES)

**Comment by WenhaiLin** [comment]
Fixed at:https://github.com/cocos2d/cocos2d-x/pull/11451
