### ISSUE TITLE
Cocosstudio animation sequence is not always correct

### ISSUE THREAD

**Issue by MatthijsSpaans** [cocos2d/cocos2d-x#9153]
every object in an animation appears to start at the first frame it is defined, not on their place in the timeline. 

For example i have three buttons which move from left to right. Horizontally on the same path, vertically spaced.

i have an animation timetime as follows. 

button 1 : start at 0ms move into view for 1000ms
button 2 start at  500ms move for 1000 ms
button 3 start at 1000 ms move into view for 1000ms. 

In cocosstudio animation mode all is going well, when playing the animation all buttons start to move into view at the same time.

**Comment by minggo** [comment]
cocos studio is canceled, so close this issue
