### ISSUE TITLE
Android UIWebView loadHTMLString uses baseURL as Mimetype

### ISSUE THREAD

**Issue by irisdominguez** [cocos2d/cocos2d-x#9155]
I'm working with the UIWebView on both android and iOS, providing some dynamic HTML code with the loadHTMLString method. I was having problems with the Android implementation, as the HTML code was being rendered as plain text.

I just realized that on the Android implementation, the baseURL argument falls to the mimetype of the text on the actual WebView. Thus, something like:

<pre>webView->loadHTMLString("<html><body style=\"background-color:#00FF00;\">HELLO WORLD!</body></html>", "text/html");
</pre>

is the only way to make the code work on both Android and iOS, while the standard way:

<pre>webView->loadHTMLString("<html><body style=\"background-color:#00FF00;\">HELLO WORLD!</body></html>", "");
</pre>

will only work on iOS. On Android, all the code will be rendered as plain text.

For my problem, I don't need the baseURL (I use HTML only for formatting text), and this workaround is enough, but I think this could be a problem for someone in the future, if not fixed. Nothing urgent, just wanted to let you know.

The real solution, I think, would be changing the loadHTMLStringJNI method of UIWebViewImpl-android.cpp , and making:

<pre>t.env->CallStaticVoidMethod(t.classID, t.methodID, index, jString, jBaseURL,nullptr);</pre>

become

<pre>t.env->CallStaticVoidMethod(t.classID, t.methodID, index, jString, "text/html",nullptr);</pre>

But I'm quite new to all this and not really sure of the possible problems of this fix. Also, this way the baseURL is never used, which doesn't seem right :/.

**Comment by jgod** [comment]
:+1: 

 I noticed this too, same use case as you, except I actually did need the baseURL (using javascript, html, css, linked resources).

This is what I ended up with:

`Cocos2dxWebViewHelper.java`:

```
    @SuppressWarnings("unused")
    public static void loadHTMLString(final int index, final String htmlString, final String baseURL) {
        cocos2dxActivity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Cocos2dxWebView webView = webViews.get(index);
                if (webView != null) {
                    webView.loadDataWithBaseURL(baseURL, htmlString, null, null, null);
                }
            }
        });
    }
```

All those nulls translate into the default mimetypes and stuff (looked at [Android api docs](http://developer.android.com/reference/android/webkit/WebView.html#loadDataWithBaseURL%28java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String%29), so it works fine -- at least better than using the html string as the mimetype hahaha.

`UIWebViewImpl-android.cpp`:

```
void loadHTMLStringJNI(const int index, const std::string &string, const std::string &baseURL) {
    // LOGD("error: %s,%d",__func__,__LINE__);
    cocos2d::JniMethodInfo t;
    if (cocos2d::JniHelper::getStaticMethodInfo(t, CLASS_NAME, "loadHTMLString", "(ILjava/lang/String;Ljava/lang/String;)V")) {
        jstring jString = t.env->NewStringUTF(string.c_str());
        jstring jBaseURL = t.env->NewStringUTF(baseURL.c_str());
        t.env->CallStaticVoidMethod(t.classID, t.methodID, index, jString, jBaseURL);

        t.env->DeleteLocalRef(jString);
        t.env->DeleteLocalRef(jBaseURL);
        t.env->DeleteLocalRef(t.classID);
    }
}
```

With these changes, the API can actually be used the way it's supposed to :)

PS: If you're using HTML string in iOS be aware of [this issue](https://github.com/cocos2d/cocos2d-x/issues/9117).

**Comment by irisdominguez** [comment]
Ohhhh, that's really nice. my kludge works, but having the baseURL available seems much more nice. And yes, you already saved me before with the iOS fix.

Thanks!

**Comment by jgod** [comment]
You're welcome. Trying to get this and the other issue's prs accepted in the meantime, don't think I missed anything.
