### ISSUE TITLE
I think the types to handle time are not consistent.

### ISSUE THREAD

**Issue by sappho192** [cocos2d/cocos2d-x#9156]
I found DisplayLinkDirector::setAnimationInterval gets argument "interval" which is double, and schedule methods in Node class get argument "delay" which is float.
AFAIK, schedule methods are belong to setAnimationInterval but they have different types to control time. I think this makes data loss and dulls time precision, right?

It needs to be same type(especially double) to save data and sharpen the precision.

**Comment by minggo** [comment]
Yep, you are right.
I think we should use float in `DisplayLinkDirector::setAnimationInterval()` too.

**Comment by sappho192** [comment]
How about unify to double?

**Comment by minggo** [comment]
Because most of other API uses float.
