### ISSUE TITLE
expected unqualified-id before '(' token in CCActionCamera.cpp:107

### ISSUE THREAD

**Issue by Borluse** [cocos2d/cocos2d-x#916]
I pulled the newest version from branch master, tried to compile under windows and had these errors :

Compile++ thumb : cocos2dx_static  <=  CCActionCamera.cpp
F:/xxxxxxxxx/cocos2dx/actions/CCActionCamera.cpp: In member function 'virtual void cocos2d::CCOrbitCamera::startWithTarget(cocos2d::CCNode *)':
F:/xxxxxxxxx/cocos2dx/actions/CCActionCamera.cpp:107: error: expected unqualified-id before '(' token
F:/xxxxxxxxx/cocos2dx/actions/CCActionCamera.cpp:109: error: expected unqualified-id before '(' token
F:/xxxxxxxxx/cocos2dx/actions/CCActionCamera.cpp:111: error: expected unqualified-id before '(' token 

I've resolved this bug by removing "std::" from "std::isnan" in those lines.

**Comment by plesiecki** [comment]
its because of #69232ee1e49fb53a56d4ed8bf119138ddeb6995e

**Comment by donaldalanmorrison** [comment]
@walzer Does the master branch need to build?  The current branch being developed is gles20.

**Comment by godyZ** [comment]
@Borluse Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to  http://www.cocos2d-x.org/issues/2513
