### ISSUE TITLE
ui::ScrollView causing strange render issues on some Android devices

### ISSUE THREAD

**Issue by SilkyPants** [cocos2d/cocos2d-x#9161]
Hi,

I've noticed a strange render issue on my Nexus 7 test device, that I cannot replicate on other android devices (yet). It seems that if I use a ui::ScrollView in my scene, the entire screen is taken up with a white image, with a green box where my scrollview would be.

I'm guessing this might have something to do with the stencil buffer or something? I haven't had a chance to dig deeper into the cause, and will be trying to set up a simple test app shortly for confirmation.

**Comment by minggo** [comment]
Yep, i think it is something about stencil buffer.

**Comment by SilkyPants** [comment]
Yep - it's not enabled :)

Is this something I can turn on/off myself, or is this a case that certain devices do not support Cocos2dx implementation?

## Logcat

D/OpenGLRenderer(18458): Render dirty regions requested: false
D/Atlas   (18458): Validating map...
D/libEGL  (18458): loaded /system/lib/egl/libEGL_tegra.so
D/libEGL  (18458): loaded /system/lib/egl/libGLESv1_CM_tegra.so
D/libEGL  (18458): loaded /system/lib/egl/libGLESv2_tegra.so
I/OpenGLRenderer(18458): Initialized EGL, version 1.4
D/OpenGLRenderer(18458): Enabling debug mode 0
D/cocos2d-x debug info(18458): 
D/cocos2d-x debug info(18458): {
D/cocos2d-x debug info(18458):  cocos2d.x.version: cocos2d-x 3.3rc0
D/cocos2d-x debug info(18458):  cocos2d.x.compiled_with_gl_state_cache: true
D/cocos2d-x debug info(18458):  gl.supports_S3TC: true
D/cocos2d-x debug info(18458):  cocos2d.x.build_type: DEBUG
D/cocos2d-x debug info(18458):  gl.supports_vertex_array_object: false
D/cocos2d-x debug info(18458):  cocos2d.x.compiled_with_profiler: false
D/cocos2d-x debug info(18458):  gl.renderer: NVIDIA Tegra 3
D/cocos2d-x debug info(18458):  gl.vendor: NVIDIA Corporation
D/cocos2d-x debug info(18458):  gl.version: OpenGL ES 2.0 14.01003
D/cocos2d-x debug info(18458):  gl.supports_ATITC: false
D/cocos2d-x debug info(18458):  gl.supports_ETC1: true
D/cocos2d-x debug info(18458):  gl.max_texture_units: 16
D/cocos2d-x debug info(18458):  gl.supports_PVRTC: false
D/cocos2d-x debug info(18458):  gl.max_texture_size: 2048
D/cocos2d-x debug info(18458):  gl.supports_NPOT: true
D/cocos2d-x debug info(18458):  gl.supports_discard_framebuffer: false
D/cocos2d-x debug info(18458):  gl.supports_BGRA8888: false
D/cocos2d-x debug info(18458): }
D/cocos2d-x debug info(18458): 
D/cocos2d-x debug info(18458): 
D/cocos2d-x debug info(18458): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(18458): Stencil buffer is not enabled.
D/cocos2d-x debug info(18458): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(18458): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(18458): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(18458): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(18458): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(18458): cocos2d: SpriteBatchNode: resizing TextureAtlas capacity from [30]

**Comment by zilongshanren** [comment]
you should enable stencil buffer
