### ISSUE TITLE
[cocos2d-x 3.3 RC0 bug] UIImageView with scale9 enabled is upside down.

### ISSUE THREAD

**Issue by happyfire** [cocos2d/cocos2d-x#9163]
After upgrade to cocos2d-x 3.3 RC0, we found that the ImageViews create in the cocos studio 1.6 with scale9 enabled are upside down in game. And I try to call setFlippedY(true) in lua code to make it right, but it have no effect.

**Comment by zilongshanren** [comment]
This issue was solve at here: https://github.com/cocos2d/cocos2d-x/pull/9057

**Comment by dumganhar** [comment]
@happyfire ,could you please pull the latest codes on v3 branch to have a try?
If it was fixed, we should close this issue. :)
