### ISSUE TITLE
CCDirector::getInstance()->setAnimationInterval() dose not work on iOS in 3.3rc0

### ISSUE THREAD

**Issue by kary24** [cocos2d/cocos2d-x#9164]
it's work on win32,but does not work on iOS.
i have set setAnimationInterval(1/10),but the game still run 60FPS rate in iPhones

**Comment by minggo** [comment]
I have tested in cpp-tests, it can work.

**Comment by kary24** [comment]
@minggo 
i  try to use it at both c++(Appdelegate::applicationDidFinishLaunching) and lua's main function ,it can work when i run my game at win32 platform.but dose not work at ios....the same code

**Comment by kary24** [comment]
@minggo 
there is my lua main function .it's the first function will be called at lua and i set animationInterval and never change it again. it take effect on win32 but doesnt work on ios.

## 

local function main()
    collectgarbage("collect")
    -- avoid memory leak
    collectgarbage("setpause", 100)
    collectgarbage("setstepmul", 5000)
    -- initialize director
    local director = cc.Director:getInstance()
    local glview = director:getOpenGLView()
    if nil == glview then
        -- glview = cc.GLViewImpl:createWithRect("nousGame", cc.rect(0,0,1136,640))
        glview = cc.GLViewImpl:createWithRect("nousGame", cc.rect(0,0,1280,800))
        -- glview = cc.GLViewImpl:createWithRect("nousGame", cc.rect(0,0,960,640))
        -- glview = cc.GLViewImpl:createWithRect("nousGame", cc.rect(0,0,1920,1080))
        director:setOpenGLView(glview)
    end

```
glview:setDesignResolutionSize(1136, 640, cc.ResolutionPolicy.FIXED_HEIGHT)

--turn on display FPS
director:setDisplayStats(true)

--set FPS. the default value is 1.0/60 if you don't call this
director:setAnimationInterval(1.0 / 40)

local schedulerID = 0
--support debug
local targetPlatform = cc.Application:getInstance():getTargetPlatform()
if (cc.PLATFORM_OS_IPHONE == targetPlatform) or (cc.PLATFORM_OS_IPAD == targetPlatform) or
   (cc.PLATFORM_OS_ANDROID == targetPlatform) or (cc.PLATFORM_OS_WINDOWS == targetPlatform) or
   (cc.PLATFORM_OS_MAC == targetPlatform) then
    cclog("result is ")
    --require('debugger')()

end
```

  cclog(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")

---

  local visibleSize = cc.Director:getInstance():getVisibleSize()
  local origin = cc.Director:getInstance():getVisibleOrigin()

  cclog("visibleSize>>width:%0.2f height:%0.2f",visibleSize.width,visibleSize.height)
  cclog("origin>>%s",origin)

  -- run
  require("initializer").new():run()

## end

**Comment by minggo** [comment]
May be your c++ codes change it too.
So please check your c++ codes in AppDelegate.cpp.

**Comment by kary24** [comment]
@minggo  i checked it yet.but i have not found i changed it at another where.:(

**Comment by minggo** [comment]
You said c++ project can not work too, right?
Will you please try cpp-test or cpp-empty-test to take a look?
I just tried cpp-tests, modified codes in `AppDelegate.cpp`, and it worked on iOS simulator.

Thanks.

**Comment by kary24** [comment]
i said it's work on win32.but it is not work on ios Simulator and iPhone devices....but it is use the same code....

**Comment by minggo** [comment]
> i try to use it at both c++(Appdelegate::applicationDidFinishLaunching) and lua's main function

Did you mean new c++ project can not set FPS too?

**Comment by kary24** [comment]
中文吧- -我的英文确实挫。。
我的意思是..我一样的代码 在windows上 是可以的..然后在ios上是不行的..包括ios的模拟器和ios的真机设备都不行.但我还没尝试cpp-tests里面的 我一会试试看.但我已经check过我的代码 包括在cpp还有lua的代码 均没有再次设置fps

**Comment by samuele3hu** [comment]
@kary24, The DisplayLinkDirector class has the declarations as follows:

```
 @brief DisplayLinkDirector is a Director that synchronizes timers with the refresh rate of the display.

 Features and Limitations:
  - Scheduled timers & drawing are synchronizes with the refresh rate of the display
  - Only supports animation intervals of 1/60 1/30 & 1/15
```

I have been check it by calling setAnimationInterval(1/30) and setAnimationInterval(1/15),the results are ok.

**Comment by kary24** [comment]
ok thx..
