### ISSUE TITLE
cocos2d-x label position is not right when upgrade from v3.1 to v3.3rc0 in iOS

### ISSUE THREAD

**Issue by richieyan** [cocos2d/cocos2d-x#9165]
version: cocos2d-x 3.3 rc0
issue: label position is a little upwards when upgrade from v3.1 to v3.3rc0 in iOS but android is normal.

before upgrade:
![image](https://cloud.githubusercontent.com/assets/839363/5101635/6a36e752-6ff7-11e4-9498-ccb04eec0ad4.png)
after upgrade:
![image](https://cloud.githubusercontent.com/assets/839363/5101637/76c1bb32-6ff7-11e4-8246-2d2d3de623a0.png)

Font file for the label is SourceHanSansK-Bold.ttf

**Comment by minggo** [comment]
Could you please paste some codes for this issue?
Thanks.

**Comment by minggo** [comment]
And could you share the .ttf file.

**Comment by richieyan** [comment]
code like this:

``` cpp
    static Label* newLabel(const std::string& text, const std::string& font, float fontSize){
        return Label::createWithSystemFont(text,font,fontSize);
    }
   ...
   //somewhere
    _energyLabel = wt::newLabel(StringUtils::format("%d/30",energy),rs::s_font_name,24);
    _energyLabel->setPosition(Vec2(100,300));
    view->addChild(_energyLabel);
```

font file: http://yun.baidu.com/s/1sjkCORr

**Comment by yasuharu519** [comment]
I got same issue as here. Is that already fixed? @minggo

**Comment by maginemu** [comment]
I'm in the same situation too.  It occurs only on ios Device.  but ios-simulator is normal.
