### ISSUE TITLE
cocos2dx 3.2 使用哪个spine版本？

### ISSUE THREAD

**Issue by chenyan2009** [cocos2d/cocos2d-x#9167]
cocos2dx 3.2使用spine生成的文件有问题，spine试过1.9.15和2.1，都不对
经过比较cocos自带的例子和自己用spine生成的文件，
发现主要问题有两个

一是 自己生成的.atlas文件多了一行size
二是 自己生成的.json文件多了一行"skeleton"，且"type"不能为"mesh"

请问，要用什么版本的spine？

**Comment by dabingnn** [comment]
Hi, spine lib has been updated to https://github.com/EsotericSoftware/spine-runtimes/tree/2.0.18 in cocos2d-x 3.3 rc0.
I cannot find a github link for cocos2d-x 3.2, but according to the license link https://github.com/cocos2d/cocos2d-x/commit/5a96751a19abce547257b6443a4cbdde67028a22
version 1.1 is used.

BTW, the license of spine has been changed, please refer to 
https://github.com/cocos2d/cocos2d-x/blob/v3/licenses/LICENSE_spine.txt
Thanks.

**Comment by chenyan2009** [comment]
I see,
Thanks a lot.

At 2014-12-01 10:03:51, "Huabing.Xu" notifications@github.com wrote:

Hi, spine lib has been updated to https://github.com/EsotericSoftware/spine-runtimes/tree/2.0.18 in cocos2d-x 3.3 rc0.
I cannot find a github link before cocos2d-x rc0, but according to the license link 5a96751
version 1.1 is used.

BTW, the license of spine has been changed, please refer to
https://github.com/cocos2d/cocos2d-x/blob/v3/licenses/LICENSE_spine.txt
Thanks.

¡ª

**Comment by pkxpp** [comment]
I copy cocos-3.3 spine model to cocos-3.2, and solve the erro.But the result is I see nothing when i create a chracter(sp.SkeletonAnimation:create) and setAnimation.can you help me?
