### ISSUE TITLE
Borders Drawing artifact

### ISSUE THREAD

**Issue by jonyrock** [cocos2d/cocos2d-x#9175]
Hi. 

An inherited from DrawNode class contains following methods:

``` C++
// see drawPolygon at https://github.com/cocos2d/cocos2d-x/blob/634fb98a5d365e2ddd3cb9cf204cdcbec5cf472d/cocos/2d/CCDrawNode.cpp#L757
void drawRect(cocos2d::Vec2 points[4], cocos2d::Color4F color) {    
    Color4F borderColor(color);
    borderColor.a = 0.5;
    drawPolygon(points, 4, color, 0.5, borderColor);
}
void buggyDraw() {
    float eps = 5;
    vector<Vec2> ppnts;
    Vec2 a(100, 100);
    Vec2 b(120, 120);
    Vec2 c = (a + b) / 2 + Vec2(eps, -eps);
    Vec2 d = (a + b) / 2 - Vec2(eps, -eps);

    ppnts.push_back(a);
    ppnts.push_back(c);
    ppnts.push_back(b);
    ppnts.push_back(d);

    drawRect(ppnts.data(), Color4F::BLACK);
}
```

Then play with `eps` value
eps = 0.1
<img src="https://trello-attachments.s3.amazonaws.com/546273eaeb982da2a29fc283/122x125/35b356cd467055cc2dbf1df0f7d010dc/Selection_045.png"/>
eps = 5
<img src="https://trello-attachments.s3.amazonaws.com/546273eaeb982da2a29fc283/87x84/fb8116167cb4ebee13a94054cfbc95c5/Selection_047.png" />
eps = 0.9
<img src="https://trello-attachments.s3.amazonaws.com/546273eaeb982da2a29fc283/91x74/0c12b71513b79903cc8a2a8a6fe43f16/Selection_048.png" />
eps = 19.9
<img src="https://trello-attachments.s3.amazonaws.com/546273eaeb982da2a29fc283/88x82/583a3447baa4e732455a35b4003f09d5/Selection_049.png" />

Then take a look at https://github.com/cocos2d/cocos2d-x/blob/634fb98a5d365e2ddd3cb9cf204cdcbec5cf472d/cocos/2d/CCDrawNode.cpp#L757

There is an explanation made by my computer graphics teacher 

<img src="https://trello-attachments.s3.amazonaws.com/546273eaeb982da2a29fc283/525x394/ceac2fd625c2f680ad25d0638919bf4e/unnamed.jpg" />

**Comment by ghost** [comment]
@jonyrock 
I can't get your idea clear, can you give me more information about it?

**Comment by jonyrock** [comment]
@huangshiwu 
can you reproduce the bug?

**Comment by ghost** [comment]
@jonyrock
I use your code and i don't know what you mean artifact, set the eps to 0.1 is strange, you just want to test the method's limit？

**Comment by jonyrock** [comment]
@huangshiwu 
Nope. Actually it is a problem for me. I have a game where I need to draw such tight rects. My `drawRect` procedure look like this.

``` C++
void FieldDrawer::drawRect(cocos2d::Vec2 points[4], cocos2d::Color4F color) {

    Color4F borderColor(color);
    borderColor.a = 0.5;

    float an = Vec2::angle(points[3] - points[0], points[1] - points[0]);
    float bn = Vec2::angle(points[0] - points[1], points[2] - points[1]);
    bool test1 = an < 0.12;
    bool test2 = bn < 0.12;
    if(test1 || test2) {
        drawSegment(points[0], points[2], 1.0, borderColor);
        drawSegment(points[1], points[3], 1.0, borderColor);
        return;
    }

    drawPolygon(points, 4, color, 0.5, borderColor);
}
```

**Comment by ghost** [comment]
@jonyrock 
When the angle is too small, the offset will be very big, so may be you can try the workaround as below:add the code in CCDrawNode.cpp
776   `offset = (offset.x*offset.x+offset.y*offset.y) > 4 ? v2fmult(v2fnormalize(offset), sqrt(4)) : offset;//you can try to change 4 to other number to get better result`
Help me to test it and let me know if it works as you want, thank you!

**Comment by jonyrock** [comment]
@huangshiwu it is working perfect now. Thank you!

**Comment by ghost** [comment]
@jonyrock
Have you try another number instead of 4? What number are you using for your game?

**Comment by jonyrock** [comment]
@huangshiwu Sorry, I've got confused. Artifact disappeared but I'm not sure whether it is drew right. Should the border be inside of the polygon? 
btw,  the reason I draw border is some kind of anti aliasing.

**Comment by ghost** [comment]
@jonyrock 
The drawPolygon method draw the border upside of the edge of the polygon, and you should set the border color's alpha value to see how it draw.

**Comment by dabingnn** [comment]
@jonyrock 
Thanks for you report. I found that the `drawPolygon()` function has a intrinsic bug as you proposed. Here is my suggestion:
1. fix bug if border width is 0 in this version.
2. Deprecate this method, and add a new pure `drawPolygon()` with parameters(vertices, count, color, fillmode), in the next version.

For your situation, could you please tell us what effect do you want to do, and we can give you our suggestions.

**Comment by ghost** [comment]
#9285 modify the internal implementation of DrawNode::drawPolygon
