### ISSUE TITLE
Studio coordinate positioning error

### ISSUE THREAD

**Issue by VisualSJ** [cocos2d/cocos2d-x#9192]
![image](https://cloud.githubusercontent.com/assets/7113508/5140121/59cc5af8-71a2-11e4-9da4-60d899e74024.png)

Figure, I inserted the layer (the big box)
Then insert a small sprite( position: 960, 0)(anchor: 1, 0)
Finally I insert a box in a small box inside.

The climax caming...
He appeared in 1 of the position.
Because of his relative to the box of bottom left corner .

But why I saw on Studio1.6, the box is displayed in the 2 position?

I see 1.6 studio think coordinate system relative to the anchor location.
ccui ignored the contentSize???

I don’t know how to fix the problem...
hacking contentSize?

**Comment by litefeel** [comment]
http://www.litefeel.com/tools/cocostudioPositionFixer.php

this tool will fixed.
1. put content of export json in left box.
2. click `转换=>` button.
3. copy content of right box to json file.

**Comment by VisualSJ** [comment]
Thanks for your tool @lite3
