### ISSUE TITLE
Android execution problem [Conversion to Dalvik format failed]

### ISSUE THREAD

**Issue by fdocr** [cocos2d/cocos2d-x#9200]
I followed step-by-step a great tutorial of Sonar Systems here: https://www.youtube.com/watch?v=2LI1IrRp_0w

iOS version compiles and run correctly on the simulator, but when opening Eclipse to run the Android application (after succesfully compiling using "python ./build_native.py") I recieve the following error:

```
[2014-11-23 23:32:15 - Dex Loader] Unable to execute dex: Multiple dex files define Lorg/cocos2dx/lib/Cocos2dxAccelerometer;
[2014-11-23 23:32:15 - TestCPP] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lorg/cocos2dx/lib/Cocos2dxAccelerometer;
```

I'm using OS X Yosemite (10.10.1), android-ndk-r9d, adt-bundle-mac-x86_64-20140702 and coco's latest stable release: cocos2d-x-3.3rc0.

**Comment by dabingnn** [comment]
@FernandoValverde Hi, there is a simpler way to run cocos2d tests
you just need to run two commands (after you have run `setup.py`)

`cocos new -l cpp` for cpp or `cocos new -l lua` for lua
then you can plug in your android device to computer, enter you project folder, run `cocos run -p android`

For more detailed information, you can ask questions in our forums.
http://forum.cocos2d-x.org
Thanks.

**Comment by minggo** [comment]
Please refer to #8555.
