### ISSUE TITLE
Fast TMX may cause black screen on some Android devices

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#9206]
Engine version: v3.2
Devices that have the issue:
- huawei G750-T01
- Lenovo A316

How to reproduce: just run corresponding test case in test-cpp.

**Comment by ghost** [comment]
V3.2 have the same problem on Huawei G750-T20, but v3.3 works well on this device.

**Comment by minggo** [comment]
It is fixed in latest code.

**Comment by ghost** [comment]
For Engine V3.2, can modify the code as bellow to fix the problem(base on v3.2's code):
CCFastTMXLayer.h:
246      `std::vector<int>  _indices;`   -->    `std::vector<GLushort>  _indices;`

CCFastTMXLayer.cpp:
192      `glDrawElements(GL_TRIANGLES, (GLsizei)count * 6, GL_UNSIGNED_INT, (GLvoid*)(offset * 6 * sizeof(int)));`  -->
           `glDrawElements(GL_TRIANGLES, (GLsizei)count * 6, GL_UNSIGNED_SHORT, (GLvoid*)(offset * 6 * sizeof(int)));`
311      `glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(int) * _indices.size(), &_indices[0], GL_DYNAMIC_DRAW);`   -->
           `glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(GLushort) * _indices.size(), &_indices[0], GL_DYNAMIC_DRAW);`

referred pr: https://github.com/cocos2d/cocos2d-x/pull/8082/files
