### ISSUE TITLE
层容器裁切问题

### ISSUE THREAD

**Issue by liamcindy** [cocos2d/cocos2d-x#9214]
层容器的裁切后，显示少裁切一个像素
![qq 20141027140223](https://cloud.githubusercontent.com/assets/2688189/5162520/2dadf4d0-73fb-11e4-887b-78eb4f4e99a4.png)

**Comment by zilongshanren** [comment]
怎么重现这个问题？有相关做代码片断吗？

How to reproduce this issue?  Could you give me some code snippets?

Thanks.

**Comment by zilongshanren** [comment]
I need to change the manual stencil configuration to ClippingNode.

**Comment by zilongshanren** [comment]
@liamcindy 
This issue need to change a lot of low level things, so we won't include it in the v3.4 version, we will do it in v4.0.
