### ISSUE TITLE
[Mac] EditBox placeholder text not disappeared when inputing starts

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#9226]
The EditBox's placeholder text don't disappear when text inputing starts.
![qq20141125-1](https://cloud.githubusercontent.com/assets/785541/5177618/3ca93c5a-7497-11e4-90d0-46622b293f94.png)

**Comment by Mazyod** [comment]
@andyque I think this is the default behavior provided by AppKit, and we shouldn't fight it.

**Comment by zilongshanren** [comment]
@Mazyod
thanks for pointing out it. Is there any documentation for this behavior?

**Comment by Mazyod** [comment]
@andyque Sorry, I couldn't find a documentation. So, I made a quick Cocoa app, and as you can see in the video, the behavior is that the placeholder doesn't go away:

https://www.dropbox.com/s/lzn79722zog7ilo/textfield-test.mp4?dl=0

**Comment by Mazyod** [comment]
@andyque I see that EditBox draws the placeholder on openGL _and_ the Cocoa control. You are referring to the OpenGL label here?

**Comment by zilongshanren** [comment]
@Mazyod 
Yes, exactly. When input start, the placeholder should disappear, but it still displayed.

**Comment by drelaptop** [comment]
when 3.17 release tested, same issue doesn't occurs. so close this

please reopen if you reproduce it using latest code. @zilongshanren
