### ISSUE TITLE
in Current Develop Version, can't fire EVENT_RENDERER_RECREATED event on Android!!!!

### ISSUE THREAD

**Issue by shrimpz** [cocos2d/cocos2d-x#9232]
in cocos\platform\android\javaactivity.cpp

void Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeInit(JNIEnv\*  env, jobject thiz, jint w, jint h)
{
    auto director = cocos2d::Director::getInstance();
    auto glview = director->getOpenGLView();
    if (!glview)
    {
        glview = cocos2d::GLViewImpl::create("Android app");
        glview->setFrameSize(w, h);
        director->setOpenGLView(glview);

```
    //cocos_android_app_init(env, thiz);

    cocos2d::Application::getInstance()->run();
}
else
{
```

/////// NO enter here!!!!!!!!!!!!!!
        cocos2d::GL::invalidateStateCache();
        cocos2d::GLProgramCache::getInstance()->reloadDefaultGLPrograms();
        cocos2d::DrawPrimitives::init();
        cocos2d::VolatileTextureMgr::reloadAllTextures();

```
    cocos2d::EventCustom recreatedEvent(EVENT_RENDERER_RECREATED);
    director->getEventDispatcher()->dispatchEvent(&recreatedEvent);
    director->setGLDefaultValues();
}
```

}

**Comment by dumganhar** [comment]
@minggo , please check this issue. If it does exist, we should fix it in 3.3rc1. :)

**Comment by minggo** [comment]
This event is fired only GL context is lost. 
We have checked it, there is not problem:
- select `don't keep activity` in setting
- run test-cpp, enter any test case
- click `HOME` button
- re-enter the app, and it will show the test case

**Comment by shrimpz** [comment]
ok, fired EVENT_RENDERER_RECREATED 

I will PR a patch for another crashed in android.
this "issue“ is found for write testcase for another crash bug.

now, this EVENT is fired, i will write testcase go on..

i'm sorry that i weak in english.

**Comment by shrimpz** [comment]
other PR, will commit in next day.....

**Comment by minggo** [comment]
Your english is good.
At least i can understand it.

Can i close this issue?

**Comment by shrimpz** [comment]
ok, close
