### ISSUE TITLE
ubuntu14.04 make error, linux platform not found glfw3.h

### ISSUE THREAD

**Issue by wcjscm** [cocos2d/cocos2d-x#9251]
Linking CXX executable ../../bin/cpp-empty-test/cpp-empty-test
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::GLViewImpl()':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:287: undefined reference to`glfwSetErrorCallback'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::initWithRect(std::string const&, cocos2d::Rect, float)':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:348: undefined reference to`glfwWindowHint'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:349: undefined reference to `glfwWindowHint'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:350: undefined reference to`glfwWindowHint'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:351: undefined reference to `glfwWindowHint'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:352: undefined reference to`glfwWindowHint'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o):/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:353: more undefined references to `glfwWindowHint' follow
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::initWithRect(std::string const&, cocos2d::Rect, float)':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:360: undefined reference to `glfwCreateWindow'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:361: undefined reference to`glfwMakeContextCurrent'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:364: undefined reference to `glfwSetCursorPosCallback'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:365: undefined reference to`glfwSetScrollCallback'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:368: undefined reference to `glfwSetWindowPosCallback'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:369: undefined reference to`glfwSetFramebufferSizeCallback'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:371: undefined reference to `glfwSetWindowIconifyCallback'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::initWithFullScreen(std::string const&)':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:399: undefined reference to `glfwGetPrimaryMonitor'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:403: undefined reference to`glfwGetVideoMode'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::initWithFullscreen(std::string const&, GLFWvidmode const&, GLFWmonitor*)':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:415: undefined reference to`glfwWindowHint'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:416: undefined reference to `glfwWindowHint'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:417: undefined reference to`glfwWindowHint'
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:418: undefined reference to `glfwWindowHint'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::end()':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:432: undefined reference to `glfwSetWindowShouldClose'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::windowShouldClose()':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:448: undefined reference to `glfwWindowShouldClose'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::updateFrameSize()':
/home/ubuntu/cocos2d-x/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:506: undefined reference to `glfwGetFramebufferSize'
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/cpp-empty-test/cpp-empty-test] Error 1
make[1]: **\* [tests/cpp-empty-test/CMakeFiles/cpp-empty-test.dir/all] Error 2
make: **\* [all] Error 2
ubuntu@build$

**Comment by zilongshanren** [comment]
Have you  run `build/install-deps-linux.sh` on your machine?

**Comment by zilongshanren** [comment]
My virtual machine is also ubuntu 14.04 and it's working.

**Comment by wcjscm** [comment]
I've been running build/install-deps-linux.sh

**Comment by zilongshanren** [comment]
try this patch please: https://github.com/cocos2d/cocos2d-x/pull/9250

**Comment by zilongshanren** [comment]
And please change your issue title and content to English. It would be friendly to other developers.

**Comment by wcjscm** [comment]
thanks

**Comment by vovkasm** [comment]
@wcjscm, see [this forum post](http://discuss.cocos2d-x.org/t/cmake-for-mac-qtcreator-and-clion/16889/108)
In short: check what exactly packages installed on you system `dpkg --get-selections | grep glfw`, if you see `libglfw-dev` or `libglfw2` that it may cause problems. Simply deinstall them. You should have `libglfw3` and `libglfw3-dev` installed.
We will add correct checks that shows problem early and/or can find right library, but for now workaround is uninstall old versions of glfw.

If this is not you problem, please post output of `cmake` command when you configure build dir!

**Comment by wcjscm** [comment]
Thank you for your help, This problem has solved
run:
sudo apt-get --purge remove libglfw-dev  libglfw2
and
sudo cocos2d-x/tools/travis-scripts/install_glfw.sh
