### ISSUE TITLE
一些第三方的TTF字体，加载以后返回的尺寸和渲染有差别

### ISSUE THREAD

**Issue by liamcindy** [cocos2d/cocos2d-x#9254]
比如：Willowheart.ttf

![1](https://cloud.githubusercontent.com/assets/2688189/5200692/63154f7a-75a3-11e4-888f-f279ba0e10dd.jpg)

**Comment by liamcindy** [comment]
![20141003_194012](https://cloud.githubusercontent.com/assets/2688189/5200746/2060c4f6-75a4-11e4-9d6b-7b592f94f15d.jpg)

**Comment by zilongshanren** [comment]
@liamcindy 
There are many exceptions here, so it might need one or more weeks to resolve it.
Thanks.

**Comment by WenhaiLin** [comment]
@liamcindy It's cause by the value of text height obtained from Willowheart.ttf is incorrect. I can't find any alternative schemes for FontFreeType::getFontMaxHeight(). Maybe I'm missing something here.

![1](https://cloud.githubusercontent.com/assets/5234286/5448373/92e7e7be-8519-11e4-9cd7-e5f33d865294.jpg)
