### ISSUE TITLE
label crashed in android.

### ISSUE THREAD

**Issue by shrimpz** [cocos2d/cocos2d-x#9255]
this issue will fix by me.
i need an issue code for write testcase.

:{

**Comment by shrimpz** [comment]
```
Size s = Director::getInstance()->getWinSize();
auto parent = Node::create();
parent->setPosition(s.width/2, s.height/2);
parent->setVisible(false);
this->addChild(parent);

auto label =  Label::createWithTTF("Crashed!!!", "fonts/HKYuanMini.ttf", 24);
label->setPosition(VisibleRect::center());
parent->addChild(label);
```

switch home & switch back, crashed

**Comment by akk0rd87** [comment]
Just look at this thread please http://discuss.cocos2d-x.org/t/test-for-issue-9255-crashed/39439.

**Comment by shrimpz** [comment]
I can't logon on discuss.cocos2d-x.org
run the testcase, no crashed, is normal
if the issue is not fixed, run this testcase will be crashed.
