### ISSUE TITLE
cocos2d::Label crash addChild with relative layout

### ISSUE THREAD

**Issue by travnick** [cocos2d/cocos2d-x#9259]
cocos2d::Label *label = cocos2d::Label::createWithBMFont(...);

widget->addChild(label); // it crashes if widget is panel with relative layout

**Comment by huytd** [comment]
Any update on this issue?
I got the same problem when trying to addChild a label created in code to widget loaded from json file

**Comment by travnick** [comment]
workaround: create another widget (with absolute positioning) and place label into it.

**Comment by huytd** [comment]
Thanks! I also post the detail of my problem include the workaround here #9661

**Comment by drelaptop** [comment]
close this issue since no developer care it for 4 years long.
