### ISSUE TITLE
'PerformanceSprite Test' does not work correctly on Window[lua tests]

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#9277]
error:
     cc.Texture2D:setDefaultAlphaPixelFormat argument 2 is 'nil'; 'number' expected.

[LUA ERROR] [string ".\PerformanceTest/PerformanceTest.lua"]:1249: invalid arguments in function 'lua_cocos2dx_Texture2D_setDefaultAlphaPixelFormat'

**Comment by samuele3hu** [comment]
Fix this error at https://github.com/cocos2d/cocos2d-x/pull/9302, please check it.
