### ISSUE TITLE
Building 8.1 Universal in VS 2013 Community and Express

### ISSUE THREAD

**Issue by garrettshearer** [cocos2d/cocos2d-x#9320]
The following situation occurs on Windows 8.1, in both Visual Studio 2013 Express and Community.  After having pulled the latest source from Github, running `python download-dependencies.py` and `git submodule update --init`, and created the "HelloWorld" C++ skeleton project from the cocos console.

While trying to build the HelloWorld skeleton project for Windows 8.1 (Store), I keep running into the errors:

```
error C2146: syntax error : missing ';' before identifier '_read_set' 
```

and 

```
error C4430: missing type specifier - int assumed. Note: C++ does not support default-int 
```

In relation to the definition of:

```
fd_set _read_set;
```

on line 131 of CCConsole.h

Supposedly `fd_set` should be defined in the statement `#include <WinSock2.h>`, however Visual Studio does not seem to be able to find it.  I have successfully built the project in Win32, but can not get the test project to build for 8.1 (The Windows Store) which seems somewhat crucial in an application being relevant.  Is anyone else able to build the project?  

I am mainly an iOS/OSX developer and am not particularly familiar with Visual Studio.  Are their any common pitfalls that I might be missing?  Or is there a problem with the fact that I have VS 2012 Express, VS 2013 Express, and VS 2013 Community installed?  Like I said, I am not the most familiar with Visual Studio so I might just be missing something.

**Comment by stammen** [comment]
Did you rerun setup.py and restart your console before generating the game? I just pulled the latest code and was able to build the game generated by the console.

I am using Visual Studio 2013 Community Update 4

**Comment by garrettshearer** [comment]
Yes I have reinstalled Cocos2d-x 3 times on my windows machine and two or three times on my mac.  Projects created from either installation won't build for me.  I also have reinstalled Visual Studio two or three times.

**Comment by stammen** [comment]
If the problem is the Windows Store build, are you sure you have Update 3 or 4? winsock api becomes enabled for Windows Store Apps only in Update 3 and higher.

If you are using Express, make sure you have Visual Studio Express 2013 with Update 4 for Windows installed and not just the Desktop version.

**Comment by garrettshearer** [comment]
I have Update 4.  The Windows machine is brand new.  The only things installed on it are Mercurial, Git, Python, and the three newest releases of VS 2012 and VS 2013.

I literally spent the entire weekend deleting everything, installing everything, creating a test project, and trying to get it to build.  Over and over and over again.  The Windows 8.1 builds are the only ones I can't get to work.  Everything else works fine, iOS, OSX, Android, and Win32.

Is there a set of SDK's or Libraries that aren't included in Visual Studio that need to be downloaded in addition?  Kinda wondering if there are some resources that most all Windows devs would already have installed, that someone coming from Linux or OSX wouldn't know they even needed.

**Comment by garrettshearer** [comment]
I find it somewhat fishy that I'm working on a completely fresh machine, following instructions to the letter over and over, and it doesn't want to work.  Makes me suspect that it will NEVER build with a standard install of Cocos2d-X, VS, and Windows.

**Comment by stammen** [comment]
FYI: This weekend I built a core i7 computer from scratch, installed a fresh copy of Windows 8.1, installed git and python, installed VS 2013 Community with the Windows Phone 8 and Maintain WIndows Store Apps options selected, cloned the cocos2d-x repo and it built and ran immediately without any problems.

Does the wp8-xaml project build for you?

**Comment by stammen** [comment]
What do you mean by " three newest releases of VS 2012 and VS 2013"?

You only need Visual Studio 2013 Community to build everything.

**Comment by garrettshearer** [comment]
VS 2012 Express for building Cocos2d-JS projects because Spine and Box2d from that repo won't build in VS 2013 Express or Community.  And I also installed VS 2013 Express and Community.  

From what you just said about doing a fresh build over the weekend makes me suspect there is another issue at play on my machine.  I will dig a little further and report back with my findings.  Thanks for the help!  I will also try the WP8-xaml project as suggested.

**Comment by garrettshearer** [comment]
Yes the wp8-xaml project built no problem.

**Comment by garrettshearer** [comment]
Out of curiosity, when installing Cocos2d-x on Windows, did you run the command line "As Administrator"?  I know I did not, and am wondering if somehow that has something to do with it.

**Comment by garrettshearer** [comment]
Reinstalling Cocos2d-X and creating a new project with the cocos-console, both running "As Administrator", did not make any difference.  So thats out.

**Comment by garrettshearer** [comment]
When I hold my cursor over `fd_set`, it reads off the error that `fd_set is undefined`.  However if I right-click on `#include <WinSock2.h>`, it shows me the header file which includes a definition of `fd_set`.  I can't figure out why the text-editor can find the header, but the compiler can't.

**Comment by garrettshearer** [comment]
@stammen, Thank you so much for your assistance.  I got it running.

For anyone else that runs into a similar issue, I re-ran the Visual Studio 2013 Community Installer.  However this time I did not uninstall Visual Studio before doing so.  Instead I ran the "Repair" option in the installer.  30 minutes and a restart later and the projects started building.

Thanks Again!

**Comment by stammen** [comment]
Thanks for the update. Uninstalling one version of Visual Studio can have side affects on other versions installed on your computer. I am glad you got it working!
