### ISSUE TITLE
trouble with setUniformLocationWith4iv v3.1.1

### ISSUE THREAD

**Issue by jminht** [cocos2d/cocos2d-x#9323]
hi there, i've trouble using setUniformLocationWith4iv in lua, v3.1.1
i read the src code and found that the param (int\* )from lua didn't get any valua in c++.
lua_cocos2dx_auto.cpp  L:33046
https://gist.github.com/jminht/22452e9b01f4e1f91cf9#file-gistfile1-txt-L5

**Comment by jminht** [comment]
how can i paste the code from gist??

**Comment by samuele3hu** [comment]
This setUniformLocationWith4iv was bound to lua by manual in the lua_coocos2dx_manual.cpp, you could refer to https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/lua-bindings/manual/cocos2d/lua_cocos2dx_manual.cpp L:3916.

**Comment by jminht** [comment]
@samuele3hu Got it, thank you!But what's the lua_cocos2dx_auto used for?Or which one should I treat as the REAL lua-binding code?

**Comment by samuele3hu** [comment]
Both lua_cocos2dx_manual and lua_cocos2dx_auto are REAL lua-binding code. Because not all  the functions can be bound automatically, so we add the manual lua-binding code to as extension.

**Comment by jminht** [comment]
@samuele3hu OK.Thank u.
