### ISSUE TITLE
Child node refer anchorPoint not correct

### ISSUE THREAD

**Issue by aeonmine** [cocos2d/cocos2d-x#9328]
local image_01 = cc.Sprite:create("Default/ImageFile.png")
  local image_02 = cc.Sprite:create("Default/ImageFile.png")
  image_01:setAnchorPoint(cc.p(0.5,0.5))
  image_01:setPosition(200,200)
  image_02:setPosition(0,0)
  image_02:setAnchorPoint(cc.p(0.5,0.5))
  image_01:addChild(image_02)

image_02 always refer anchorPoint(0,0) of image_01

**Comment by walzer** [comment]
Design as this because image_01 is the parent of image_02.
