### ISSUE TITLE
Label with some specific font is cropped

### ISSUE THREAD

**Issue by MinotaurosLee** [cocos2d/cocos2d-x#9333]
![image](https://cloud.githubusercontent.com/assets/1762194/5257488/923054d8-7a14-11e4-9ab7-830b94ee5caf.png)
![image](https://cloud.githubusercontent.com/assets/1762194/5257496/b2bb8e52-7a14-11e4-8f89-a1b156ad48e5.png)
![image](https://cloud.githubusercontent.com/assets/1762194/5257506/c7fb45fa-7a14-11e4-9cbb-48d317a0b5d9.png)

Already tried #7770 and #7004
Font used: LiHei Pro.ttf, download : http://pan.baidu.com/s/1zuLT8

**Comment by minggo** [comment]
There is not the engine version: v3.11.
And please paste some pseudocode to help to reproduce it.

Thanks.

**Comment by MinotaurosLee** [comment]
不好意思，版本是3.1。我们是使用cocostudio设计好文本控件UIText，然后在lua中获取该控件再填充文本内容，如果直接从lua中create一个UIText好像不会出现这种情况

**Comment by minggo** [comment]
@chengstory 
Please take a look.

**Comment by MinotaurosLee** [comment]
有结果么？

**Comment by jminht** [comment]
@MinotaurosLee 请问这个问题怎么样了？

**Comment by pandamicro** [comment]
@WenhaiLin  Please review this issue

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/13110

**Comment by WenhaiLin** [comment]
@MinotaurosLee @jminht @firegames Please try this solution:https://github.com/cocos2d/cocos2d-x/pull/13110
