### ISSUE TITLE
when is cocos2dx support admob officially like facebook?

### ISSUE THREAD

**Issue by takaaptech** [cocos2d/cocos2d-x#9343]
I hope tutorials will coming soon!
Thank so much!

**Comment by neokoala** [comment]
I wrote a complete tutorial for how to integrate Admob in Cocos2d-x v3.4 by using plugin-x. (OS X)

http://cocos2dmaster.blogspot.kr/2015/02/admob-integration-in-cocos2d-x-v34-with_4.html

Enjoy it ~~

**Comment by walzer** [comment]
Work scheduled in other products, `AnySDK` in China and `SDKBox` in US.
