### ISSUE TITLE
ANR on Nexus5 when use LabelBMPFont in cocos2dx3.3rc0

### ISSUE THREAD

**Issue by daneric** [cocos2d/cocos2d-x#9344]
Very simple code:
Label\* scoreLabel = Label::createWithBMFont("font.fnt", scores, TextHAlignment::CENTER);
    scoreLabel->setPosition(position);
    scoreLabel->runAction(Sequence::create(
        DelayTime::create(delay),
        FadeIn::create(1.0f),
        Spawn::create(
            ScaleTo::create(1.0f, 1.5f),
            MoveBy::create(1.0f, Vec2(0.0f, 50.0f)),
            Sequence::create(DelayTime::create(0.5f), FadeOut::create(0.5f), NULL),
        NULL),
        CallFunc::create(CC_CALLBACK_0(Node::removeFromParent, scoreLabel)),
        NULL));
    parent->addChild(scoreLabel, 4);

It's no problem on windows, and still no problem on other test android phones(Meizu MX4, OnePlus,  XiaoMi3/4 etc.), but when run on the Nexus5, ANR happened, and logcat output nothing then, the only thing I can do is kill the app progress.

When I change code to:
Label\* scoreLabel = Label::createWithTTF(scores, "Marker Felt.ttf", 32);
It works and leads to correct result. But I still want to use the bitmap font file. Please help me.

**Comment by WenhaiLin** [comment]
Please build cocos2d-x project base on NDK r10c on Android.

**Comment by daneric** [comment]
Thanks a lot! It did work when I have changed NDK version from NDK r10 to NDK r10c.

**Comment by dabingnn** [comment]
3.3 rc1 has been released, NDK 10c is recommended for android in Release Notes.

**Comment by xiaofengxyz** [comment]
It also has happened in cocos2dx3.2 on nexus5,  but the NDK need r9d. What should I do? Please help me.

**Comment by WenhaiLin** [comment]
@xiaofengxyz You can replace those  precompiled third party libraries with libraries in cocos2d-x 3.3 version,then build your project with NDK r10c +.

**Comment by xiaofengxyz** [comment]
Thanks a lot! It did work.
