### ISSUE TITLE
Mac版本文本渲染不一致的问题

### ISSUE THREAD

**Issue by liamcindy** [cocos2d/cocos2d-x#9345]
UIText输入文本为“TextLabel\n”的情况下，在MAC上边渲染效果不一致：

字体库为5.0版本的时候是正常的：
![1](https://cloud.githubusercontent.com/assets/2688189/5262834/3d5ece8e-7a65-11e4-86af-6b16662a0d45.jpg)

字体库为5.0.1版本的时候是不正常的：

![screenshot_1_1415781826_tmp339bd4ae](https://cloud.githubusercontent.com/assets/2688189/5262853/65c4c162-7a65-11e4-9724-c5dd43f7b893.png)

**Comment by zilongshanren** [comment]
@liamcindy 
The issue can't be resolved by us, since it is determined by operating system.

**Comment by WenhaiLin** [comment]
Whether you set the area size of Text by setTextAreaSize?

**Comment by liamcindy** [comment]
@Dhilan007 Just set ignoreContentAdaptWithSize ture
