### ISSUE TITLE
arm64 support for 2.x tree

### ISSUE THREAD

**Issue by KenRogoway** [cocos2d/cocos2d-x#9346]
Is there any chance of getting the arm64 support added to the 2.x tree?

**Comment by WenhaiLin** [comment]
Done.
arm64：https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/67
x86_64：https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/69
https://github.com/cocos2d/cocos2d-x/pull/9332

**Comment by minggo** [comment]
We will release v2.2.6 on Dec.12 to support iOS 64.
Detail information please refer to http://discuss.cocos2d-x.org/t/64-bit-and-ios-8-requirements-for-new-apps/17797/37.
