### ISSUE TITLE
cocos2d-x3.3rc0 UIEditBox crash

### ISSUE THREAD

**Issue by sgleizes** [cocos2d/cocos2d-x#9347]
What I know is this :
- The crash appears to come from UIEditBox since by removing it from the scene it works fine
- The crash occurs after the call to onEnter i.e. after Node construction.
- There is no log indicating an error source.
- I've been able to reproduce it on only two devices (out of ~50)

The devices have nothing in common:
- Tablet Samsung GT-P1000 running Android 4.0.4, cyanogen 9.1.0.pl
- A phone (I don't have the model number) running Android 2.3.6

I compiled cocos2d-x3.3rc0 with NDK r9d, could that be the source of the problem?

**Comment by zilongshanren** [comment]
@sgleizes
Could you please grab the crash log from your tested phone and paste it at here?
If I could see the crash log, it would be much simpler for me to find the reason.
Thanks.

**Comment by walzer** [comment]
Close this issue because: inactive in more than 3 months.
