### ISSUE TITLE
Is 3.3rc download link removed from the official website?

### ISSUE THREAD

**Issue by playgithub** [cocos2d/cocos2d-x#9349]
I download 3.3rc0 last month, now I am going to see if there is a newer one, but can find anyone, even 3.3rc0. Because the document is for 3.3, so I want to download the newest version of 3.3. Any suggestion, thanks.

**Comment by minggo** [comment]
Please refer to [this thread](http://discuss.cocos2d-x.org/t/where-is-the-cocos2d-x-3-3-rc1/18659).

**Comment by playgithub** [comment]
Fine, thanks.
