### ISSUE TITLE
Is cocos2d-x suitable for android app development?

### ISSUE THREAD

**Issue by playgithub** [cocos2d/cocos2d-x#9350]
Mainly consider battery energy consumption, can it consume battery energy as effectively as possible?

**Comment by minggo** [comment]
It will consume more energy compared to normal app. But i can implement effect easily. And you can slow down the FPS to save energy.

And please discuss these topics in cocos2d-x forum: http://discuss.cocos2d-x.org/.
Thanks.

**Comment by playgithub** [comment]
OK, thanks.
