### ISSUE TITLE
ProgrammersGuide.pdf bookmarks bug

### ISSUE THREAD

**Issue by playgithub** [cocos2d/cocos2d-x#9351]
![image](https://cloud.githubusercontent.com/assets/3665590/5276292/433c2794-7af0-11e4-8be4-7925294f7b28.png)

OS: Windows 7
Reader: Adobe Reader XI

**Comment by slackmoehrle** [comment]
The PDF is generated by Pandoc. Whats the real issue? That the bookmarks title is being cut off? I'll test this in a few readers to understand and decide on a fix.

**Comment by playgithub** [comment]
Yes.

**Comment by slackmoehrle** [comment]
I tested this in:

Preview, OS X 10.10
Adobe Reader, 11.0.09, OS X
Adobe Reader, 11.0.09, Windows

![screen shot 2014-12-03 at 10 31 21 am](https://cloud.githubusercontent.com/assets/7491758/5286283/be9a0fa0-7ad7-11e4-8fcc-a6b410fddd14.png)
![screen shot 2014-12-03 at 9 13 36 am](https://cloud.githubusercontent.com/assets/7491758/5286285/c2cb3b26-7ad7-11e4-93ad-bf63a259f1e5.png)

**Comment by playgithub** [comment]
I have downloaded it from http://cocos2d-x.org/programmersguide/ProgrammersGuide.pdf, it still has the same problem.

Windows 7
Adobe Reader 11.0.09

**Comment by slackmoehrle** [comment]
I did as well. I dont know what to say about it. It works on my end and I had another guy test it on his Windows/Reader as well.

**Comment by playgithub** [comment]
![capture_0](https://cloud.githubusercontent.com/assets/3665590/5293098/95ad4ca4-7ba6-11e4-8ac7-56073934c1b7.PNG)
![capture_1](https://cloud.githubusercontent.com/assets/3665590/5293099/95ae72aa-7ba6-11e4-8699-19c6ccb4dc9b.PNG)

**Comment by slackmoehrle** [comment]
What are you trying to show?

**Comment by playgithub** [comment]
The same problem exists, and Is it the newest .pdf file? Is the problem related to the fonts?

**Comment by slackmoehrle** [comment]
I'm not sure at this time. I dont run any special fonts on my Mac and the others that I had test this on Windows have no additional fonts installed. Their systems are pretty Vanilla. I'll see if I can fire a virtual machine, install vanilla windows and adobe and see if it persists.

**Comment by playgithub** [comment]
OK, thanks a lot.

**Comment by playgithub** [comment]
I have found that the wiki is has newer content, so I will read the wiki instead.
Thanks all the same.

**Comment by slackmoehrle** [comment]
What info on the wiki is newer?

**Comment by playgithub** [comment]
e.g. http://www.cocos2d-x.org/wiki/EditBox

**Comment by slackmoehrle** [comment]
This will be in chapter 6
