### ISSUE TITLE
Feature request: scroll bar on the cocos2d::ui::ScrollView

### ISSUE THREAD

**Issue by yagjak** [cocos2d/cocos2d-x#9356]
Hi,
me and many other developers need to the scroll bar on the  `cocos2d::ui::ScrollView` , it can really help us.
Thanks.

**Comment by litefeel** [comment]
how to scroll?

**Comment by playgithub** [comment]
horizontally and vertically, :), I don't often see scroll bars in games, but I think it's helpful when develop applications using cocos.

**Comment by yagjak** [comment]
@playgithub yes,  you're right

**Comment by stevetranby** [comment]
Actually some games have scroll bars and on mobile we could try to support making it visible only on scroll. I'll vote for this one!

**Comment by walzer** [comment]
Sounds reasonable: only visible on scrolling.

**Comment by dariodepaolis** [comment]
Or maybe you can set it like an option scrollbars: yes/no/auto

**Comment by zilongshanren** [comment]
implemented in v3.8
