### ISSUE TITLE
Projects generated with the cocos console are failing to build.in V3 branch

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#9363]
Projects generated with the cocos console are failing to build. templates/cocos2dx_files.json needs to be updated.

1>D:\GitHub\cocos2d-x-v3\projects\foo\cocos2d\cocos\editor-support\cocostudio/WidgetReader/WidgetReader.h(32): fatal error C1083: Cannot open include file: 'cocostudio/WidgetReader/NodeReaderProtocol.h': No such file or directory 
Etc…

**Comment by minggo** [comment]
This file is updated automatically.

**Comment by minggo** [comment]
https://github.com/cocos2d/cocos2d-x/pull/9360 is for it.

**Comment by stammen** [comment]
Thanks

**Comment by stammen** [comment]
I verified that it is fixed. Thanks.

**Comment by minggo** [comment]
Thanks.
