### ISSUE TITLE
Repeated sequence doesn't work correctly

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#9364]
```
auto move = MoveBy::create(0.5, Vec2(20.0f, 0.0f));
auto move_back = move->reverse();
auto move_seq = Sequence::create(move, move_back);
auto move_rep = Repeat::create(move_seq, 10);
sprite->runAction(move_rep);
```

This code snippet will trigger the issue, after every loop the sprite will be moved to the right by 20px.

By looking into the code of Sequence::update, it reset the state of the second action before running the first one, and the second action have a initial state which noted the position of the sprite (20px at the right due to the first action in the previous loop).

![t lubo1 f os d 1bn 4](https://cloud.githubusercontent.com/assets/632460/5294270/7d78ad24-7bbd-11e4-82a0-7451ee86dd0f.jpg)

**Comment by WenhaiLin** [comment]
This issue cannot be reproduced on the latest codes in V3 branch.
