### ISSUE TITLE
blend mode does not work with animated sprite

### ISSUE THREAD

**Issue by zeyangl** [cocos2d/cocos2d-x#9367]
This issue was reported long ago on the forum for 2.2, and it's still the same in 3.0. http://discuss.cocos2d-x.org/t/setblendfunc-does-not-work-when-sprite-runs-a-ccanimate-object/10639/5
This looks like a serious bug.

**Comment by minggo** [comment]
We migrate to github issue system a few months ago. And it is more efficient to report discuss issues here.

**Comment by zeyangl** [comment]
Understood. I just ran into the same issue and wonder if it's actually a bug.

**Comment by ghost** [comment]
@zeyangl  By now Sprite::setTexture use texture's blendfunc instead of sprite's blendfunc as new blendfunc. And we now are going to release v3.3 final so may change this behavior in future, and for your case, you can temporary modify the code(base on v3.3rc2, in file CCActionInterval.cpp) as below to get behavior you want:
![image](https://cloud.githubusercontent.com/assets/8086269/5370629/3ee6daa2-8060-11e4-8702-9b909d1d8ec0.png)

![image](https://cloud.githubusercontent.com/assets/8086269/5370635/57596208-8060-11e4-9d58-4d0e8f046370.png)

**Comment by urokuta** [comment]
I have same issue. Any progress or suggestions?
I also tried following code in 
http://stackoverflow.com/questions/22009687/can-i-use-blendfunc-in-ccanimation

```
// add sprite frames to the sprite frame cache
CCSprite *sprite = [CCSprite spriteWithSpriteFrame:spriteFramesArra[0]];
sprite.blendFunc = newBlendFunc;
[sprite runAnimation:animation];
```

but not worked.

**Comment by urokuta** [comment]
As a result,
I commented out few codes following stackoverflow.
http://stackoverflow.com/questions/22009687/can-i-use-blendfunc-in-ccanimation

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCSprite.cpp

```
void Sprite::updateBlendFunc(void)
{
    CCASSERT(! _batchNode, "CCSprite: updateBlendFunc doesn't work when the sprite is rendered using a SpriteBatchNode");

    // it is possible to have an untextured sprite
    if (! _texture || ! _texture->hasPremultipliedAlpha())
    {
        _blendFunc = BlendFunc::ALPHA_NON_PREMULTIPLIED;
        setOpacityModifyRGB(false);
    }
    else
    {
        _blendFunc = BlendFunc::ALPHA_PREMULTIPLIED;
        setOpacityModifyRGB(true);
    }
}
```

to

```
void Sprite::updateBlendFunc(void)
{
    CCASSERT(! _batchNode, "CCSprite: updateBlendFunc doesn't work when the sprite is rendered using a SpriteBatchNode");

    // it is possible to have an untextured sprite
    if (! _texture || ! _texture->hasPremultipliedAlpha())
    {
        //_blendFunc = BlendFunc::ALPHA_NON_PREMULTIPLIED;
        setOpacityModifyRGB(false);
    }
    else
    {
        //_blendFunc = BlendFunc::ALPHA_PREMULTIPLIED;
        setOpacityModifyRGB(true);
    }
}
```

and it works but I'm afraid of other impacts as same as "Ah Wen" in stackoverflow.
Would you please tell me whether it is correct or other choice?

UPDATED: @ghost way might be more appropriate.

**Comment by urokuta** [comment]
@ghost Sorry, finally I figured out what you mentioned.
Following your code, I changed CCActionInterval.cpp

```
void Animate::stop()
{
    if (_animation->getRestoreOriginalFrame() && _target)
    {
        auto blend = static_cast<Sprite*>(_target)->getBlendFunc();  // Added
        static_cast<Sprite*>(_target)->setSpriteFrame(_origFrame);
        static_cast<Sprite*>(_target)->setBlendFunc(blend);              // Added
    }

    ActionInterval::stop();
}
```

```
        if( splitTime <= t ) {
            auto blend = static_cast<Sprite*>(_target)->getBlendFunc();    // Added
            _currFrameIndex = i;
            AnimationFrame* frame = frames.at(_currFrameIndex);
            frameToDisplay = frame->getSpriteFrame();
            static_cast<Sprite*>(_target)->setSpriteFrame(frameToDisplay);
            static_cast<Sprite*>(_target)->setBlendFunc(blend);                // Added
```

I confirmed it worked as my expected.
just in case I will send pull request for fixing this issue but I don't know whether the way is correct.
please kindly merge if it is correct.
