### ISSUE TITLE
Cocos Studio exported armature animation with particles will crash when loading

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#9373]
Cocos Studio 1.5 or 1.6

Related issue: https://github.com/cocos2d/cocos2d-js/issues/1164

If we append a particle system on a armature bone in Cocos Studio, then in the export file's ResourceFileList section will include the particle's plist file. In this case, the reader doesn't treat the particle's plist correctly, it consider it as a sprite frames plist, and eventually lead to crash.

**Comment by walzer** [comment]
Sorry, insufficient resources to support studio v1.x anymore.
