### ISSUE TITLE
Android build_native.sh clears assets directory

### ISSUE THREAD

**Issue by bananer** [cocos2d/cocos2d-x#938]
The assets directory will be rm -rf'ed by the build scripts. This is not acceptable since the assets directory is a common place for data files needed in the app or other components (see [this report](http://support.scoreloop.com/discussions/getting-started/530-scoreloopmanagersingleton-cannot-be-resolved#comment_16259532)).

The comment in the script is also misleading.

```
# make sure assets is exist
if [ -d $HELLOWORLD_ROOT/assets ]; then
    rm -rf $HELLOWORLD_ROOT/assets
fi

mkdir $HELLOWORLD_ROOT/assets
```

**Comment by minggo** [comment]
We delete it and recreate it, then copy all resources into it.
Because resources may be changed.
I don't know if there is better solution.

**Comment by bananer** [comment]
I'm not familiar with the exact details of the cocos2dx build process, but here are two suggestions:
- You already `cp -rf` all your resources, that would overwrite any old versions, no need to delete them first. Only issue is that if a resource was moved/renamed, the old one would stay.
- Move all cocos2dx resources into a subfolder of assets/ and `rm -rf` only that subfolder.

**Comment by minggo** [comment]
Because all platforms share Resources/, so we should keep the same structure as Resources/.

**Comment by bananer** [comment]
Can't you put that structure into a subfolder of assets/ on Android, so cocos can coexist with other components there?

**Comment by mfellner** [comment]
On OS X and Linux it's possible to replace the assets/ folder with a symlink to the project resources.

**Comment by minggo** [comment]
Yeap, on linux or Mac OS X, we can do it like this.
But there is a situation that assets is created by eclipse, not by our shell script.

**Comment by godyZ** [comment]
@ bananer Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August
