### ISSUE TITLE
cocos2d-x v3.3-rc0 的lua版本编译报错

### ISSUE THREAD

**Issue by mrFranklin** [cocos2d/cocos2d-x#9380]
在官网上下载的最新版本：v3.3-rc0
使用命令新建了lua版本：
python cocos.py new HelloLua -p com.cocos2dx.org -l lua -d D:\Projects

打开frameworks/runtime-src/proj.win32/HelloLua.sln 编译会报如下错误：
frameworks\runtime-src\classes\lua_module_register.h(13): fatal error C1083: 无法打开包括文件:“lua/quick/lua_cocos2dx_quick_manual.hpp”: No such file or directory

网上搜了一下有两位也提到此问题，但没有得到官方的回复。
http://cn.cocos2d-x.org/tutorial/show?id=1717
http://www.cocoachina.com/bbs/read.php?tid=249903

请问该如何修改？

**Comment by kary24** [comment]
如果不是用quick的话 把这句注释了就好了

**Comment by minggo** [comment]
Fixed as @kary24 said.
