### ISSUE TITLE
Animate problem

### ISSUE THREAD

**Issue by playgithub** [cocos2d/cocos2d-x#9383]
In the guide: http://www.cocos2d-x.org/programmersguide/ch4.html
section: Animate

![image](https://cloud.githubusercontent.com/assets/3665590/5300344/4776aabc-7c0a-11e4-8268-9325921625f2.png)

Windows 7
Visual Studio 2013

**Comment by darkdukey** [comment]
Can you provide more detail about this issue? it's hard to tell what's wrong from the screen shot.

**Comment by playgithub** [comment]
![image](https://cloud.githubusercontent.com/assets/3665590/5309838/0d9f1b66-7c65-11e4-9f04-5767e530f715.png)

The extras in the red closure is always there when the animation is playing?

**Comment by darkdukey** [comment]
@slackmoehrle Have you see this happen before?

**Comment by slackmoehrle** [comment]
I'm on OS X, 10.10, with XCode 6 and this doesn't happen for me when using ios or osx as a target. We haven't yet tested the examples in the programmers guide with Windows. I'll create a virtual machine this weekend and create a visual studio project and try it.

**Comment by slackmoehrle** [comment]
If you have problems with the Programmers Guide, can you create an issue in its repo? https://github.com/chukong/programmers-guide/issues

Thanks I usually dont check this repo for issues unless I'm tagged in it.

**Comment by minggo** [comment]
@playgithub 
Would you please create a new issue in programmer guide repo and close this one?
Thanks.

**Comment by playgithub** [comment]
OK

**Comment by darkdukey** [comment]
Thanks a lot :)

**Comment by slackmoehrle** [comment]
You closed this without a resolution.
