### ISSUE TITLE
cocos2dx 3.3rc1 bug

### ISSUE THREAD

**Issue by 79630217** [cocos2d/cocos2d-x#9387]
本帖属于CocoaChina会员发表，转帖请写明来源和帖子地址
3.3rc1编译的bug
.\auto\lua_cocos2dx_3d_auto.cpp(794): error C2039: “getMeshCount”: 不是“cocos2d::Sprite3D”的成员
.\auto\lua_cocos2dx_auto.cpp(20388): error C2039: “setBoundarySet”: 不是“cocos2d::Follow”的成员
.\auto\lua_cocos2dx_auto.cpp(46913): error C2039: “hasContent”: 不是“cocos2d::ClippingNode”的成员
\auto\lua_cocos2dx_studio_auto.cpp(20498): error C2039: “setLastFrameCallFunc”: 不是“cocostudio::timeline::ActionTimeline”的成员
\auto\lua_cocos2dx_studio_auto.cpp(21068): error C2039: “clearLastFrameCallFunc”: 不是“cocostudio::timeline::ActionTimeline”的成员

cocos2d\extensions\gui\cccontrolextension\cccontrolutils.h(39): fatal error C1083: 无法打开包括文件:“extensions/ExtensionExport.h”: No such file or directory

**Comment by samuele3hu** [comment]
Which platforms and test-case did you use to compile.

**Comment by 79630217** [comment]
win8 x86_64
项目中添加了cocos\scripting\lua-bindings\proj.win32项目

**Comment by samuele3hu** [comment]
How was your project created?Can you check your `Additional Include Directories` refer to `lua-tests` or `lua-empty-test`

**Comment by 79630217** [comment]
cocos new 项目 -p org.项目.game -l cpp -d D:\cocos2d-x\
创建时创建的是c++的项目，因为项目里有一部分需要使用lua，所以就倒入了cocos\scripting\lua-bindings\proj.win32。这个错误在3.3rc0里没有出现

**Comment by 79630217** [comment]
cocos2d\extensions\gui\cccontrolextension\cccontrolutils.h(39): fatal error C1083: 无法打开包括文件:“extensions/ExtensionExport.h”: No such file or directory这个错误，把
#include "extensions/ExtensionExport.h"  =〉 #include "../../ExtensionExport.h" 就没有问题，lua得错误依旧没有解决

**Comment by samuele3hu** [comment]
Can you check whether those functions exists in c++ class?
