### ISSUE TITLE
 Cocos2dx 3.2 can’t read *.csb File . Result NULL

### ISSUE THREAD

**Issue by phatvan99** [cocos2d/cocos2d-x#9389]
I'm using cocos2dx 3.2 . The old *.csb file which were created by cocosStudio 2.0 then it can't load , result = NULL. my code these following:

//0. Header cocosStudio declaring :
include "ui/CocosGUI.h"
USING_NS_CC;
using namespace ui;

//1.set path to ROOM Folder

std::vectorstd::string vtStr;
vtStr.push_back("room");
FileUtils::getInstance()->setSearchPaths(vtStr);

//2.Load *.csb FILE
auto __root = cocostudio::GUIReader::getInstance()->widgetFromBinaryFile("room/main_scene.csb");

above result : __root always NULL .
I've downloaded Cocostudio 2.0.2 lastest in present. But the bug still happend. Please help me to fix it !

Thanks all you !

**Comment by phatvan99** [comment]
I have Debugged . It's leaved at line 362 (File: CCSGUIReader.cpp)
....
        if (rapidjson::kObjectType == tType || rapidjson::kArrayType == tType)
....

Basing on above code : My *.csb file . The my tType = -78  of Buffer OBJ not containing  rapidjson::kObjectType or rapidjson::kArrayType. So it leaved and return NULL for result

(T___T) how i can do ! thanks

**Comment by darkdukey** [comment]
Can you try `CSLoader`

**Comment by phatvan99** [comment]
CSLoader not available in 3.2 version. I think this problem is bug of  enginer with cocos version. It not synchronize .someone talked me use cocosstudio 1.6 for 3.2 cocos2dx, but I don't think so !

**Comment by ghost** [comment]
i updated my cocos2dx to 3.3rc2 with cocos studio being 2.0.2, still the bug persists, any update on this issue, also i dunno how to use CSLoader, unable to include

**Comment by thinkong** [comment]
I am having the same issue.. or almost the same issue..
we are using cocos2dx 3.3 rc0 and cannot load a csb file from the most recent cocostudio update

any help?

edit:
oh well never mind.. 
http://discuss.cocos2d-x.org/t/cocos2dx-3-2-cocosstudio-2-x-x-not-compatible/18764/4
guess the newest cocostudio wasn't compatible with cocos2dx 3.3rc0

**Comment by chengstory** [comment]
Cocos Studio correspondence with cocos2dx:
￼￼![111](https://cloud.githubusercontent.com/assets/2960368/5451015/0dff410e-8547-11e4-9072-099ee7877bc6.png)

**Comment by chengstory** [comment]
cocos2d-x version is minimum version to support Studio.

**Comment by minggo** [comment]
Thanks @chengstory.
I think it is better put these information in a url in english, then you can refer it in future.

**Comment by honeboy** [comment]
Where can I download cocos studio 2.0.6?

**Comment by chengstory** [comment]
We plan to release cocos studio 2.0.6 tomorrow(2014.12.17 in Beijing)

**Comment by thinkong** [comment]
@chengstory will it have a fix for the opacity stuff?
and.. do you have an estimated time? in Beijing time? I am super waiting for a 2.0.6@@

**Comment by dhb118** [comment]
yes, good job guys ,thanks.

2014-12-17 8:14 GMT+08:00 Kyuhun Lee notifications@github.com:

**Comment by BKChoi79** [comment]
so... where is the solution??
