### ISSUE TITLE
cocos2d-x-3.3rc1 Android BackgroundMusic incorrect lifecycle

### ISSUE THREAD

**Issue by qwertyway** [cocos2d/cocos2d-x#9391]
After playing background music and stopping it, you won't be able to start it again:

SimpleAudioEngine::getInstance()->playBackgroundMusic(filePath, true);
SimpleAudioEngine::getInstance()->stopBackgroundMusic(); 
SimpleAudioEngine::getInstance()->playBackgroundMusic(filePath, true);

Method stopBackgroundMusic calls mBackgroundMediaPlayer.stop();
According to http://developer.android.com/reference/android/media/MediaPlayer.html, after this you need to call prepare() before start(). But it's not happening in you cycle in playBackgroundMusic().

I'd suggest adding mStopped state (along with existing mPaused), and check it.

Thank you

**Comment by WenhaiLin** [comment]
@qwertyway This issue fixed at https://github.com/cocos2d/cocos2d-x/pull/9340
