### ISSUE TITLE
SIGFPE  and big .obj files

### ISSUE THREAD

**Issue by jonyrock** [cocos2d/cocos2d-x#9396]
Hi.
Lets try <a href="http://people.sc.fsu.edu/~jburkardt/data/obj/airboat.obj" > this .obj file </a> . We will get  `0` from `MeshData::getPerVertexSize()` and that zero will be used in division in `MeshVertexData::create()` 
Output is empty.

**Comment by jonyrock** [comment]
Similar happens with other files from here http://people.sc.fsu.edu/~jburkardt/data/obj/obj.html
The first one,`airboat.obj`, mentioned above

btw, I don't like it, but Unity opens this.

**Comment by minggo** [comment]
@super626 
Could you please take a look?

**Comment by super626** [comment]
ok

**Comment by super626** [comment]
@jonyrock 
Which version of cocos2d-x are you using?

@jonyrock , @minggo
I had checked this.
And I find it can work correctly since cocos2d-x-3.3rc0. Can you update your engine?

**Comment by jonyrock** [comment]
@super626 Thank you for your reply. 
My version is `cocos2d-x-3.3-rc0  Oct.21 2014` 
Do you want me to update the engine?

**Comment by minggo** [comment]
@super626 
It is better if you can tell @jonyrock how to fix it in the version it uses.
A pull request link is enough.

**Comment by minggo** [comment]
@jonyrock 
Since it is resolved in new engine version.
Can i close this issue?

**Comment by jonyrock** [comment]
@minggo I think so. I believe you that it is fixed :)

**Comment by minggo** [comment]
@jonyrock 
Thanks. If you find any problem, please reopen it again.
