### ISSUE TITLE
紧急，cocos2dx 3.2版本在iphone6上的bug

### ISSUE THREAD

**Issue by design365** [cocos2d/cocos2d-x#9397]
请教一下 ， 3.2版本是不是不支持iphone6 ，在iphone5上跑得好好的，到iphone6上跑刚启动就提示如下错误 ：
![41_354404_20fdb2f59b38175](https://cloud.githubusercontent.com/assets/3348948/5329325/4d4e5aa4-7de3-11e4-814e-ff072e8f84b8.png)

**Comment by minggo** [comment]
It supports iPhone 6.

**Comment by minggo** [comment]
What's the issue?
