### ISSUE TITLE
CCFileUtils.cpp line 1107, no closedir() after opendir(char*)

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#9398]
This behaviour will lead to subsequent `fopen` and `libcurl` internal errors. We need to closedir() after we don't need it.

This bug was reported by user in weibo http://www.weibo.com/1692965182/BzC8HwtLM?from=page_1005051692965182_profile&wvr=6&mod=weibotime

**Comment by minggo** [comment]
fix in #9401
