### ISSUE TITLE
Anchor point bug in Layer

### ISSUE THREAD

**Issue by woc2006** [cocos2d/cocos2d-x#9399]
Put this code in Stage::init

```
auto lc = LayerColor::create(Color4B::RED);
lc->setContentSize(Size(80, 80));
lc->setPosition(visibleSize.width, visibleSize.height);
lc->setAnchorPoint(Point(1,1));
this->addChild(lc, 6);
```

the red rect is not displayed.

and change line 3 to:

```
lc->setPosition(visibleSize.width - 80, visibleSize.height - 80);
```

the rect displayed as expect. Which means, the anchor point (1,1) works as Point(0, 0)

Tested in cocos2dx 3.2 3.3.

**Comment by milos1290** [comment]
try adding origin.x and origin.y to visible size. But since it works when subtracting 80 it could be that this is a bug.

**Comment by woc2006** [comment]
origin.x and origin.y of visible size is always 0.
and it doesn't works.

**Comment by jmogilner** [comment]
Agree with this bug. The anchor point is completely ignored.

**Comment by pandamicro** [comment]
It's because the anchor point is ignored by default for Layers: https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/2d/CCLayer.cpp#L64

please try 

```
lc-> ignoreAnchorPointForPosition(false);
```
