### ISSUE TITLE
SimpleAudioEngine will stop background music automatically in a low rate on iOS

### ISSUE THREAD

**Issue by kary24** [cocos2d/cocos2d-x#9435]
platform:ios 7.x
engine version:cocos2d-x 3.3 rc1

**Comment by minggo** [comment]
Will you try new audio?

**Comment by kary24** [comment]
i think won't until it can preload resources.

**Comment by kary24** [comment]
I don't want my game be lag when it play sound on first time

**Comment by minggo** [comment]
It uses stream internally.
So it is less lag.
Have you tried it?

**Comment by kary24** [comment]
@minggo u means new engine needn't preload and will not be lag?i have not tried it yet:)

**Comment by minggo** [comment]
Yep.
Indeed it is supported in v3.3rc1.

**Comment by kary24** [comment]
thx i m using 3.3rc1 i will try it later:) thx for ur answer:)
