### ISSUE TITLE
Replace "微软雅黑" with English name in TextFieldReader.cpp

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#9436]
Reported in the forum http://discuss.cocos2d-x.org/t/in-some-source-files-cause-compiler-error-on-vs2013/18790

> On Cocos2d-x 3.3 RC2 (or any previous versions) TextReader.cpp / TextField.cpp / ButtonReader.cpp etc. have "微软雅黑" as the font name and they cause error C2001 on Visual Studio 2013 on Windows. Please replace them with a font name in alphabets.

**Comment by ryukbk** [comment]
Thanks,
https://github.com/cocos2d/cocos2d-x/search?utf8=%E2%9C%93&q=%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91
TextField.cpp I mentioned is actualluy TextFieldReader.cpp

**Comment by minggo** [comment]
@chengstory 
Please take a look?

**Comment by chengstory** [comment]
@pipu Please take a look.

**Comment by ricardoquesada** [comment]
let's fix this for v3.3-final.

**Comment by minggo** [comment]
@chengstory 
What's the status?

**Comment by pipu** [comment]
I have fixed this, and submit pull request, and the pull request has been merged.
But I can't find the pull request id.
Please wait for a moment. I will continue to find the id.

**Comment by ryukbk** [comment]
So this didn't make it to 3.3 final it seems.

**Comment by minggo** [comment]
@ryukbk 
What did you mean?

**Comment by ryukbk** [comment]
@minggo Never mind, it seems I had mistaken 3.3 RC2 as 3.3, and the fix is indeed in. Thanks!

**Comment by minggo** [comment]
Got it.
No problem:)
