### ISSUE TITLE
Supports reading Android obb expansion files

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#9437]
Reported in the forum http://discuss.cocos2d-x.org/t/cocos2d-x-v3-has-anyone-managed-to-create-an-android-expansion/18476

For Android obb file, read this http://developer.android.com/google/play/expansion-files.html

We need to add this feature supported in `FileUtils` or some other places.

**Comment by jack887889** [comment]
Is it supported now?

**Comment by Guy-kun** [comment]
Is this still not on the roadmap? 
This is pretty critical for an engine that 'supports Android' and the lack of it is yet another blow to the half-baked Android support cocos2dx seems to have...

**Comment by adesentenac** [comment]
Hi @minggo, I've created a pull request to add OBB (zip) support into cocos2d-x: https://github.com/cocos2d/cocos2d-x/pull/15515

Regards,
Adrien

**Comment by minggo** [comment]
@adesentenac thanks, i will take a look

**Comment by jugnu-ali** [comment]
Is this feature implemented in v 3.14 or later

**Comment by minggo** [comment]
You can see the milestone in the right, it is marked as `3.12`.

**Comment by jugnu-ali** [comment]
Hi,
ok so can u guide me which api to use for this purpose. :)

**Comment by minggo** [comment]
I think you don't have to care about it, it will read the file automatically when needed. There is not an API to read from obb files, engine will read it when needed.

**Comment by jugnu-ali** [comment]
I am using csb file & i think i have to use something like this FileUtils::getInstance()->getAssetPath() or getResourcePath()
