### ISSUE TITLE
CocosStudio 2.0.5 csd not showing up

### ISSUE THREAD

**Issue by napjon** [cocos2d/cocos2d-x#9443]
I install cocostudio 2.0.2, and update it to 2.0.5 still get the same problem.
The sample csd (login or everything else) doesn't show any layer to edit, with output "Failed to Init GameWindow"

I'm using OSX 10.8.5

Is cocostudio have some kind of requirements?

**Comment by darkdukey** [comment]
I think it only supports 10.9 and up...

**Comment by chengstory** [comment]
Thanks @darkdukey ,  Only supports 10.9 and up.
