### ISSUE TITLE
（cocos2dx 2.x） 在自定义node的onEnter当中调用getParent()->addChild(); 相对于在数组遍历的时候往里面添加数据

### ISSUE THREAD

**Issue by ychua842655** [cocos2d/cocos2d-x#9445]
如果在onEnter中添加数据是合法的，那么是不是应该在onEnter中，对遍历方式进行更改？

**Comment by minggo** [comment]
Sorry, what's the issue?

**Comment by ychua842655** [comment]
在父层调用onEnter的时候，会随机崩溃 ，错误是 野指针

**Comment by ychua842655** [comment]
```
if (m_pChildren && m_pChildren->count() > 0)
{
    CCObject* child;
    CCNode* node;
    CCARRAY_FOREACH(m_pChildren, child)
    {
        node = (CCNode*)child;
        if (!node->isRunning())
        {
            node->onEnter();
        }            
    }
}
```

在这个遍历的时候， node->onEnter(){
  getParent()->addChild(d,0);
}
m_pChildren 发生变化

**Comment by minggo** [comment]
You can not modify array when looping.
It is not safe to do it like this.

**Comment by ychua842655** [comment]
嗯，是这样，看来我们只能自己多注意了，谢谢。

**Comment by minggo** [comment]
You are welcome.

**Comment by minggo** [comment]
Could you please use English in future?
Then more guys will help you.

Thanks.

**Comment by ychua842655** [comment]
Sorry, i have not login the github too many days and my English is really poor~~~i will do my best in future
