### ISSUE TITLE
cocos2d-x-3.1rc0 android版本，当同时起多个应用，并且与引擎来回切，会导致引擎所有的显示不正常（OpenGL error 0x0505 ）

### ISSUE THREAD

**Issue by jasofan** [cocos2d/cocos2d-x#9446]
描述：
cocos2d-x-3.1rc0 android版本，当同时起多个应用，并且与引擎来回切，会导致引擎所有的显示不正常

错误显示见附件

通过日志发下如下错误：
E/cocos2d-x assert(  361): /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCRenderTexture.cpp function:initWithWidthAndHeight line:275

![device-2014-11-21-140504](https://cloud.githubusercontent.com/assets/9956707/5372913/1840b4ba-808b-11e4-8f86-21b2719a3847.png)

D/cocos2d-x debug info(  361): OpenGL error 0x0505 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/ui/UILayout.cpp onBeforeVisitStencil 1061

D/cocos2d-x debug info(  361): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252

D/cocos2d-x debug info(  361): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252

D/cocos2d-x debug info(  361): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252

D/cocos2d-x debug info(  361): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252

D/cocos2d-x debug info(  361): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689

**Comment by minggo** [comment]
Duplicated with #9447.

**Comment by xiaoweiLoveyou** [comment]
这个解决了吗？？
