### ISSUE TITLE
cocos2d-x-3.1rc0 android版本，当同时起多个应用，并且与引擎来回切，会导致引擎黑屏（glError: 0x0505 ）

### ISSUE THREAD

**Issue by jasofan** [cocos2d/cocos2d-x#9447]
描述：
cocos2d-x-3.1rc0 android版本，当同时起多个应用，并且与引擎来回切，会导致引擎黑屏（glError: 0x0505 ）

完整日志：
11-20 15:41:11.098 D/cocos2d-x debug info( 1271): imgUrl: http://ottpic.bbtv.cn//20141024/F1896594.jpg
11-20 15:41:11.098 D/cocos2d-x debug info( 1271): cachePath: /data/data/com.bestv.ott.baseservices/rs_data/imagedata//20141024/F1896594.jpg
11-20 15:41:11.098 D/cocos2d-x debug info( 1271): image file is exist
11-20 15:41:11.158 D/cocos2d-x debug info( 1271): Assert failed: Could not attach texture to framebuffer
11-20 15:41:11.158 E/cocos2d-x assert( 1271): /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCRenderTexture.cpp function:initWithWidthAndHeight line:275
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): OpenGL error 0x0505 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./renderer/CCTexture2D.cpp initWithMipmaps 640
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): cocos2d: Texture2D: Error uploading compressed texture level: 0 . glError: 0x0505
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): Assert failed: Could not attach texture to framebuffer
11-20 15:41:11.218 E/cocos2d-x assert( 1271): /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCRenderTexture.cpp function:initWithWidthAndHeight line:275
11-20 15:41:11.218 E/cocos2d-x assert( 1271): /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./math/Mat4.cpp function:createOrthographicOffCenter line:141
11-20 15:41:11.218 E/cocos2d-x assert( 1271): /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./math/Mat4.cpp function:createOrthographicOffCenter line:142
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): OpenGL error 0x0505 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/ui/UILayout.cpp onBeforeVisitStencil 1061
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/ui/UILayout.cpp onBeforeVisitStencil 1061
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/ui/UILayout.cpp onBeforeVisitStencil 1061
11-20 15:41:11.218 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.228 E/cocos2d-x assert( 1271): /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./math/Mat4.cpp function:createOrthographicOffCenter line:141
11-20 15:41:11.228 E/cocos2d-x assert( 1271): /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./math/Mat4.cpp function:createOrthographicOffCenter line:142
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/ui/UILayout.cpp onBeforeVisitStencil 1061
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./2d/CCDrawNode.cpp onDraw 252
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): 
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): OpenGL error 0x0506 in /home/test/LEO_Inside/BesTV_EPG/proj.android/../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
11-20 15:41:11.228 D/cocos2d-x debug info( 1271): 
11-20 15:41:25.779 D/Cocos2dxGLSurfaceView( 1271): onKeyDown keyCode: 4
11-20 15:41:27.949 D/Cocos2dxGLSurfaceView( 1271): onKeyDown keyCode: 4
11-20 15:41:29.319 D/csAppActivity( 1271): onPause===

**Comment by Hioln** [comment]
is this fixed??

**Comment by jasofan** [comment]
还没有

**Comment by minggo** [comment]
i think it is fixed, if not please create a new issue
