### ISSUE TITLE
[v3.3  iOS] Console Custom Commands Test

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#9456]
When input `telnet localhost 5678` in terminal, it shows me the following erorors:

```
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...telnet: connect to address 127.0.0.1: Connection refused
Trying fe80::1...telnet: connect to address fe80::1: Connection refused
telnet: Unable to connect to remote host
```

**Comment by ricardoquesada** [comment]
you have to `telnet localhost 5678` when you run it in your mac/windows.
if you run it in iOS you have to replace "localhost" the the iOS ip address.

closed as invalid.
