### ISSUE TITLE
[v3.3 iOS]Extension->TimelineTest->TestChangePlaySection

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#9457]
Click the test and it will crash.

@chengstory  please take a look at it.

Thanks.

**Comment by chengstory** [comment]
@pipu please take a look at it.

**Comment by pipu** [comment]
@andyque 

I have fixed this bug and create a pull request. 
web is:
https://github.com/cocos2d/cocos2d-x/pull/9459

You could review this pull request.
Thanks
