### ISSUE TITLE
DrawNode can't run FadeOut and FadeIn action.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#9471]
`Version`: v3.3rc2
`Issue`: DrawNode can't run FadeOut and FadeIn action.
`Reproduce`: eg. HelloWolrd.cpp

``` cpp
void HelloWorld::runDrawNodeAction()
{
    auto dn = DrawNode::create();
    dn->drawLine(Vec2(0,0), Vec2(100,100), Color4F::WHITE);
    this->addChild(dn,100);
    dn->runAction(FadeOut::create(1.0f));
}
```

**Comment by hackthehackerman** [comment]
Hi, I am wondering if anyone is working on this issue? It seems that DrawNode does not respond to alpha channel at all unless the alpha value is defined during creation. It would be great if this can be fixed.

**Comment by ghost** [comment]
@yansuck This is a feature we may going to add in version 4.x.

**Comment by hackthehackerman** [comment]
@huangshiwu Good to know! Out of curiosity, is there a timeline for 4.x release? Also, awesome works guys, cocos2d-x is amazing.

**Comment by minggo** [comment]
@yansuck 
It will take months to finish v4.0.
Because it is a big version, it will support multiple GPU API, such as OpenGL and mental.
And we will start v4.0 on Jan.16.

**Comment by hackthehackerman** [comment]
@minggo Thanks! Thank you so much for all the works! Also, 春节快乐 in a month!

**Comment by minggo** [comment]
Thanks @yansuck .
The same to you.

**Comment by liketemple** [comment]
DrawNode still could not fadeOut at v3.10, hope to see this feature at v4.0. However not see it in the v4.0 alpha.

**Comment by minggo** [comment]
duplicated with #8764, so close this one
