### ISSUE TITLE
SocketIO Incompatibility

### ISSUE THREAD

**Issue by emadpres** [cocos2d/cocos2d-x#9479]
Hi;
Summary:
We just noticed that SocketIO class (in cocos2d-x v3.3) is not compatible with the socket.io library version 1 and above.

Detail:
The SocketIO class of cocos was designed for socket.io 0.9. Nowadays all server are using socket.io v1 (and above) and this causes some incompatibility issues in using cocos2dx. please update cocos2dx SocketIO Class to use new version protocol of socket.io  .

For Example in SocketIO.cpp>>SIOClientImpl::handshake() :

current code use this URL: "/socket.io/1"
But new socket.io versions need: "/socket.io/?transport=polling&b64=0"

**Comment by minggo** [comment]
We may not have enough resource in v3.4 as we planned to release v3.4beta0 on Dec.31.

**Comment by roed** [comment]
Is fixed in pull request: https://github.com/cocos2d/cocos2d-x/pull/10033

Hasn't been merged yet, but works for our project

**Comment by himynameschris** [comment]
Ive merged this feature with backwards compatibility into #11441

**Comment by pandamicro** [comment]
Final fix here: https://github.com/cocos2d/cocos2d-x/pull/11583
