### ISSUE TITLE
(v2) cc.ControlButton.addTargetWithActionForControlEvents silently fails on second button with same callback.

### ISSUE THREAD

**Issue by ethankennerly** [cocos2d/cocos2d-x#9480]
Workaround: For each target, create a unique function.

GOTCHA: In Cocos2d-x v2, adding the same function and event to a different target silently fails.
`if (it->second->_jsFunc == jsFunc && arg2 == it->second->_type)`
https://github.com/cocos2d/cocos2d-x/blame/v2/scripting/javascript/bindings/jsb_cocos2dx_extension_manual.cpp#L687

Test case:
cocos2d-html5 v2.2.2 accepts cc.Control.addTargetWithActionForControlEvents
However, cocos2d-x jsb this code had no apparent effect on second and third button.
The first button responds.
http://www.cocos2d-x.org/reference/html5-js/V2.2.3/index.html

Suggested fix:

A suggested fix would be to edit the above line to also require the target is the same object before canceling the listening.

Add a getter function `getJSTarget`.

```
    JSObject* getJSTarget()
    {
        return _jsTarget;
    }
```

Then require the JS target is the same at the citation above:

`if (it->second->_jsFunc == jsFunc && arg2 == it->second->_type && obj == it->second->getJSTarget())`

Until then, I am able to workaround by creating a unique function for each button.  Example workaround:

```
cc.addTargetWithActionForControlEvents = function(controlButton, methodOwner, method, event)
{
    var uniqueFunction = function(){
        return method.call(methodOwner, controlButton, event);
    };
    return controlButton.addTargetWithActionForControlEvents(methodOwner, uniqueFunction, event); 
};
```

**Comment by walzer** [comment]
Sorry, we have insufficient resources to support v2 any more.
If v3.4 or later version still have this bug, please open another issue to discuss it.
Thanks for your feedback.
