### ISSUE TITLE
PageView cannot only touch by horizontal, no matter how I try to rotate the pageview

### ISSUE THREAD

**Issue by RaoZiJian** [cocos2d/cocos2d-x#9484]
I'm running on Cocos2d-x 3.3 rc2.

The pageView can only touch by horizontal.
Even when I change the rotation , it still make no sense

**Comment by zilongshanren** [comment]
@RaoZiJian
Thanks for reporting this issue. I will check it out later.

**Comment by zilongshanren** [comment]
@RaoZiJian 
Currently PageView doesn't support touch by vertical. We will implement it in later version.

**Comment by pandamicro** [comment]
Duplicated with : https://github.com/cocos2d/cocos2d-x/issues/10778
