### ISSUE TITLE
cocos2d-x 3.2 getCurrentLanguage alway is en in iPhone6 simulator

### ISSUE THREAD

**Issue by kyo9999** [cocos2d/cocos2d-x#9487]
cocos2d-x 3.2 getCurrentLanguage alway is en in iPhone6 simulator
LanguageType Application::getCurrentLanguage()
{
    // get the current language and country config
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    NSArray *languages = [defaults objectForKey:@"AppleLanguages"];
    NSString *currentLanguage = [languages objectAtIndex:0];

```
// get the current language code.(such as English is "en", Chinese is "zh" and so on)
NSDictionary* temp = [NSLocale componentsFromLocaleIdentifier:currentLanguage];
NSString * languageCode = [temp objectForKey:NSLocaleLanguageCode];

LanguageType ret = LanguageType::ENGLISH;
if ([languageCode isEqualToString:@"zh"])
{
    ret = LanguageType::CHINESE;
}
else if ([languageCode isEqualToString:@"en"])
{
    ret = LanguageType::ENGLISH;
}
else if ([languageCode isEqualToString:@"fr"]){
    ret = LanguageType::FRENCH;
}
else if ([languageCode isEqualToString:@"it"]){
    ret = LanguageType::ITALIAN;
}
else if ([languageCode isEqualToString:@"de"]){
    ret = LanguageType::GERMAN;
}
else if ([languageCode isEqualToString:@"es"]){
    ret = LanguageType::SPANISH;
}
else if ([languageCode isEqualToString:@"nl"]){
    ret = LanguageType::DUTCH;
}
else if ([languageCode isEqualToString:@"ru"]){
    ret = LanguageType::RUSSIAN;
}
else if ([languageCode isEqualToString:@"ko"]){
    ret = LanguageType::KOREAN;
}
else if ([languageCode isEqualToString:@"ja"]){
    ret = LanguageType::JAPANESE;
}
else if ([languageCode isEqualToString:@"hu"]){
    ret = LanguageType::HUNGARIAN;
}
else if ([languageCode isEqualToString:@"pt"]){
    ret = LanguageType::PORTUGUESE;
}
else if ([languageCode isEqualToString:@"ar"]){
    ret = LanguageType::ARABIC;
}
else if ([languageCode isEqualToString:@"nb"]){
    ret = LanguageType::NORWEGIAN;
}
else if ([languageCode isEqualToString:@"pl"]){
    ret = LanguageType::POLISH;
}
return ret;
```

}

**Comment by minggo** [comment]
@kyo9999 
Did you change the language in simulator?

**Comment by kyo9999** [comment]
@minggo yes, i change the language in simulator, it ok in iphone4s/iphone5, but not ok in iphone6 resize simulator

**Comment by samuele3hu** [comment]
@kyo9999, Did you use Xcode6.1 and iOS 8.1.Referring to the  Xcode 6.1 release notes, simulator has some changes that might have caused this.
https://developer.apple.com/library/ios/releasenotes/DeveloperTools/RN-Xcode/Chapters/xc6_release_notes.html

**Comment by kyo9999** [comment]
yes, i use Xcode6.1 and iOS 8.1

**Comment by seobyeongky** [comment]
I got same issue. I use Xcode6.1.1 and [NSLocale preferredLanguages] always returns english on iPhone Simulator 8.1. And this function works ok on the real device. I think this is not a cocos2d-x bug.
