### ISSUE TITLE
setColor and TintTo/By work on a whole armature, but not on an individual bone

### ISSUE THREAD

**Issue by hawkwood** [cocos2d/cocos2d-x#9488]
Trying to setColor or run TintTo on just one bone in an armature does not work.  Verify by adding following code to the end of TestCSWithSkeleton::onEnter() of ArmatureScene.cpp

```
armature->setColor( Color3B(128, 0, 0));
Bone *hat = armature->getBone( "Layer136" );
hat->setColor( Color3B(0, 128, 128));
```

With this, hat should be black.  If line 1 is commented out, hat should be teal. If lines 2 & 3 are commented out, hat should be red.

The problem seems to be line 260 of CCBone.cpp, where _realColor is reset to WHITE, removing the individual bone's color.  Commenting out this line solves the issue, but I do not know what other ramifications this might cause.

Related, since line 266 of CCBone.cpp resets _realOpacity to 255, this means that opacity can not be set on a specific bone.

**Comment by chengstory** [comment]
@pipu   please take a look

**Comment by pipu** [comment]
@2youyouo2

Take a look, please.

**Comment by 2youyou2** [comment]
hi, hawkwood.
I have test it. It seems it's ok to remove those two lines in CCBone.cpp.
I forgot what problem to solve with those two lines.

**Comment by xiaofeng11** [comment]
Maybe line 260 & line 266 is used for Cocostudio force bone to been draw on screen, In user project these two line can be comment to avoid problem
