### ISSUE TITLE
3.3rc0 DrawNode drawRect 

### ISSUE THREAD

**Issue by GreatToad** [cocos2d/cocos2d-x#9493]
I find DrawNode drawRect , what it show not a rect , it is a circle! 
code: 
this->drawRect(Vec2(0,0),Vec2(0,100),Vec2(100,100),Vec2(100,0),Color4F::RED);

**Comment by ghost** [comment]
@GreatToad You should use another function drawRect(drawRect(const Vec2 &origin, const Vec2 &destination, const Color4F &color))
this->drawRect(Vec2(0,0),Vec2(100,100),Color4F::RED);
