### ISSUE TITLE
Different font has different display with the same text

### ISSUE THREAD

**Issue by liamcindy** [cocos2d/cocos2d-x#9500]
1.Fingerpop字体会不显示空格，并且将所有字体，包含文本中第二行的字体，渲染区压缩显示为1行；2.Runez of Omegd.ttf，在渲染区，会把空格变为换行

Text\* alert = Text::create("Text","fonts/Fingerpop.ttf", 20);
        alert->ignoreContentAdaptWithSize(false);
        alert->setContentSize(Size(200,200));
        alert->setString("Text Label : Fingerpop.ttf");
        alert->setColor(Color3B(159, 168, 176));
        alert->setPosition(Vec2(widgetSize.width / 2.0f, widgetSize.height / 2.0f));
        _uiLayer->addChild(alert);        

```
    Text* alert1 = Text::create("Text", "fonts/Runez of Omega.ttf", 20);
    alert1->ignoreContentAdaptWithSize(false);
    alert1->setContentSize(Size(200, 200));
    alert1->setString("Text Label : Runez of Omega.ttf");
    alert1->setColor(Color3B(159, 168, 176));
    alert1->setPosition(Vec2(widgetSize.width / 2.0f, widgetSize.height / 2.0f - 100));
    _uiLayer->addChild(alert1);
```

![100008492098810](https://cloud.githubusercontent.com/assets/2688189/5433199/e35004e2-847f-11e4-8ec1-1bce49e42227.png)

**Comment by zilongshanren** [comment]
@liamcindy 
Your code doesn't match the picture. What's the code to display "textInputTest" label?

**Comment by liamcindy** [comment]
@andyque 
Sorry, it's my mistake.

alert->setString("Text Label : TTF Test");
alert1->setString("Text Label : TTF Test");

**Comment by minggo** [comment]
@liamcindy 
Please change the title in English.
Thanks.

**Comment by liamcindy** [comment]
@andyque Fingerpop.ttf is still display different

**Comment by WenhaiLin** [comment]
Fixed spaces will be lost if label created with Fingerpop.ttf: https://github.com/cocos2d/cocos2d-x/pull/13230
