### ISSUE TITLE
cocos2dx 2.2.5 can't play background music ogg or mp3

### ISSUE THREAD

**Issue by zszen** [cocos2d/cocos2d-x#9502]
12-16 00:57:18.572: E/MediaPlayer(29018): Should have subtitle controller already set
12-16 00:57:18.572: E/MediaPlayer(29018): Should have subtitle controller already set
12-16 00:57:19.979: E/MediaPlayer(29018): start called in state 1
12-16 00:57:19.979: E/MediaPlayer(29018): error (-38, 0)
12-16 00:57:19.979: E/MediaPlayer(29018): Error (-38,0)

**Comment by minggo** [comment]
How to reproduce it?

**Comment by minggo** [comment]
And what's the Android version you tested on?
If you run on Android 5.0, it is fixed in v2.2.6.

**Comment by darmie** [comment]
@minggo I have this problem in Cocos2d-x 3.2 , and  I tested on Android 5.0.1

**Comment by minggo** [comment]
@darmie 
It is fixed in v3.3 and synchronized to v2.26.

**Comment by minggo** [comment]
You can refer to #9336 for detail information.
