### ISSUE TITLE
Material file loading for .obj 3D models

### ISSUE THREAD

**Issue by irisdominguez** [cocos2d/cocos2d-x#9503]
I have been experimenting with loading obj files on a Sprite3D, and the material files (.mtl) are not loaded for any object. I found the two bugs that are related to this issue, and I think I have found both solutions.

In the cocos2dx forum you can find an example of a cube failing and my solution:

http://discuss.cocos2d-x.org/t/sprite3d-materials-in-mtl-file-not-applied-to-object-in-game/16871
- CCBundle3D.cpp, Bundle3D::loadObj, line ~270:

The variable NMaterialData materialdata should be declared inside the loop, not outside it. Move it inside, to the line 287 aprox, just before `sprintf(str, "%d", i++);`.

This error makes models with several materials use the same texture for all the materials (as the new textures are always pushed back behind the texture of the first one).
- CCSprite3D.cpp, Sprite3D::loadFromObj, line ~105:

Line 112 should read something like

```
bool ret = Bundle3D::loadObj(meshdatas, *materialdatas, *nodeDatas, fullPath, fullPath.substr(0, fullPath.find_last_of("\\/") + 1).c_str());
```

instead of:

```
bool ret = Bundle3D::loadObj(meshdatas, *materialdatas, *nodeDatas, fullPath);
```

like it does.

This error makes it impossible for the program to find the material file to be used. It's supposed to be loaded from the same folder as the original .obj file, but the path is not propagated in the current code and that makes it fail.

I'm sorry but I don't have the experience nor the time to make a proper pull request, so I hope you can find some time to check this changes and incorporate them onto the code. At least, I wanted to state this findings for anyone with the same problem.

Thanks.

**Comment by minggo** [comment]
@super626 
Could you please take a look?

**Comment by lvlonggame** [comment]
@Greezael  
I think you are right, the  "NMaterialData materialdata" should be declared inside the loop.

**Comment by lvlonggame** [comment]
@Greezael
Could you give me more info about your second question or give me an example !

**Comment by irisdominguez** [comment]
The loadObj function has a fifth parameter (mtl_basepath) for the path were it will load the .mtl file, with the materials. Right now, it is left as default, just a nullptr.

Inside the Bundle3D::loadObj implementation, that parameter falls to the ObjLoader::LoadObj function, and from there to the LoadMtl function (inside CCObjLoader.cpp). As the parameter is always nullptr, when it tries to load the materials file (`std::ifstream ifs(filepath.c_str());`) the path is incomplete and it fails.

As an example, you can download the following cube model:

https://gist.github.com/Greezael/aebe1bc3b232ce46dede

Put the files inside a "cube" folder in the resources path.
Then, on the main class of the project, this code:

```
auto cube = Sprite3D::create("cube/cube3d.obj");
cube->setScale(100.0f);
cube->setNormalizedPosition(Vec2(0.5, 0.5));

addChild(cube);
```

With the path correction, it will look for the .mtl file in the same path it is loading the .obj file from, and the cube faces will get their textures. Without it, it will not load the .mtl file and the faces of the cube will be blank (red).

If you find any problem, just ask.

**Comment by lvlonggame** [comment]
OK!! I will try it, thank you.
