### ISSUE TITLE
Modification the default behavior of some UI widgets

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#9506]
As a user, we hope we could use minimal resources to create a widget.
1. Modification default resource usage of the following widgets:
   a) ui::CheckBox: "background selected state", "background disabled state" and "cross icon disabled state" resources are empty on default
   b) ui::Slider: "inner progress bar", "slider ball pressed state" and "slider ball disabled state" resources are empty on default
2. Add automatical interaction
   a) ui::Button, ui::CheckBox and ui::Slider， when selected state resource is empty. When pressed, the normal state image will scale.
   b)ui::Button , ui::CheckBox and ui::Slider, when disabled state resources are empty, when setting widget state to disabled, we should change the normal state texture to gray.

**Comment by minggo** [comment]
Need to add the modification in release note after the pull request is merged.
