### ISSUE TITLE
Timeline json support is broken

### ISSUE THREAD

**Issue by zhaijialong** [cocos2d/cocos2d-x#9508]
In the `ExtensionTest/CocoStudioActionTimeTest`, csb works well, but json not. You can try with `TestTimelineFrameEvent`, will get this error:

```
CCRef.cpp:126: void cocos2d::Ref::release(): Assertion `false' failed.
```

 If I revert the changes of retain & release in #https://github.com/cocos2d/cocos2d-x/commit/85fb2c91aba64c9945cbde1fc5cf802a250c17b8 , it turns ok.

**Comment by zhaijialong** [comment]
@pipu @andyque 
Any thought?

**Comment by pandamicro** [comment]
@chengstory

**Comment by chengstory** [comment]
The export file of json is not supported now.

**Comment by pipu** [comment]
The export file of json is not supported in current version of cocos2d-x and CocosStudio editor.

**Comment by zhaijialong** [comment]
ok , thanks.

**Comment by pandamicro** [comment]
So you mean Cocos2d-x 3.3 doesn't support Cocos Studio 1.6, am I correct?

**Comment by walzer** [comment]
Sorry, insufficient resources to support Cocos Studio v1.6.
Please use cocos v2.2 instead.
