### ISSUE TITLE
Opacity changing tweens in cocostudio 2.0.5 crashing game when loading.

### ISSUE THREAD

**Issue by thinkong** [cocos2d/cocos2d-x#9509]
we we're using 2.0.4 with cocos2dx 3.3 rc0.
and everything seemed to be fine.

but today we updated it to 3.3 final and 2.0.5 and now any cocostudio file with opacity changing tweens(timelines) seem to make it crash.

any help would be great

**Comment by thinkong** [comment]
I also opened up an issue here
https://github.com/darkdukey/Cocos-Studio/issues/29

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
