### ISSUE TITLE
Update libcurl to latest version

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#9523]

**Comment by stammen** [comment]
What versions of libcurl and png are you going to use?

**Comment by zilongshanren** [comment]
@stammen
I haven't started the update process yet. I want to update libpng to 1.6.15 and libcurl to 7.39.0.

What's your opinion?

BTW, could you give me some hints about how to compile static libraries for WP8.1 and WinRT8.1?
Some tutorials would be great.

Thanks.
