### ISSUE TITLE
The director's destructor will not be executed in IOS platform.

### ISSUE THREAD

**Issue by liu-ben** [cocos2d/cocos2d-x#9527]
The helloworld project generated by cocos (ver3.3rc0) command has following code when a user touch the quit button.

...
    Director::getInstance()->end();
# if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)

```
exit(0);
```
# endif

...

In the director's end() method, it just sets a flag to inform that in the next cycle the director will be purged. However, the following exit(0) will end the program immediately. So that the director will never get the chance to purge itself. And hence, all living scenes, nodes will not  be purged.
A possible solution is to put the exit(0) code at the end of the purgeDirector method to make sure the director can purge itself at the next cycle, and its destructor will be executed.

**Comment by minggo** [comment]
When invoking exit(0), the application will be terminated. There is not need to purge anything. All memories will be released to system.

But i am not sure what's the correct way to terminate an application on iOS.

**Comment by liu-ben** [comment]
The purgeDirector calls scene->onExit and other similar stuffs. A user may put code for saving user progresses in the onExit method, and it will not be executed on IOS platform. As I mentioned, putting the code at the end of purgeDirector,  it works for me.
#if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
exit(0);
#endif
