### ISSUE TITLE
GLEW_INCLUDE_DIR GLEW_LIBRARY win32-msvc-2013-x86.bat

### ISSUE THREAD

**Issue by samueldedavid** [cocos2d/cocos2d-x#9529]
it says glew not found GLEW_INCLUDE_DIR GLEW_LIBRARY
also zlib.h not found.when building after modifications

**Comment by vovkasm** [comment]
Hi, @samueldedavid 
I fix this (and some other errors) in [vovkasm/cocos2d-x branch dev/cmake-msvc-fixes](https://github.com/vovkasm/cocos2d-x/tree/dev/cmake-msvc-fixes)

Please test in you environment, but note, that other problems exists, for ex. tests not correctly placed in build directories, and can not be executed (to execute all *.dll should be copied in same dir, where exe file, also resource files should exists in current dir).
