### ISSUE TITLE
Engine scale the bones imported from cocostudio, but not scale the textures attached to it

### ISSUE THREAD

**Issue by nbtthief** [cocos2d/cocos2d-x#9532]
Hi, i'm not really sure if this is a bug, but i notice our engine only scale the bones but not the textures attached to it, that's why we have a problem with gaps between our sprites in armature when we don't have a set of resources specifically for that scale factor.

Would you please take a look at this topic, and my topic (linked on it)?
http://discuss.cocos2d-x.org/t/cocos-studio-2-feedback/18017/39?u=p3rnoptr

**Comment by chengstory** [comment]
@pipu Please take a look

**Comment by minggo** [comment]
cocos studio is canceled, so close this issue
