### ISSUE TITLE
Screen will blink once when portrait project launching on android.

### ISSUE THREAD

**Issue by natural-law** [cocos2d/cocos2d-x#9535]
How to reproduce the problem:
1. Modify the AndroidManifest.xml of cpp-empty-test. Replace `landscape` with `portrait`.
2. Run cpp-empty-test on android.

The performance of the problem:
The screen will blink once when `cpp-empty-test` is launching.

**Comment by pandamicro** [comment]
What's the state now?

**Comment by drelaptop** [comment]
> Modify the AndroidManifest.xml of cpp-empty-test. Replace landscape with portrait.
Run cpp-empty-test on android.

tested with v3 latest code, issues have gone, so close it.
