### ISSUE TITLE
cocos2d-x 3.3 iOS 8 GLView wrong frame

### ISSUE THREAD

**Issue by ruslanmaley** [cocos2d/cocos2d-x#9542]
GLView has wrong frame when keyboard is hiding at EditBox in landscape orientation. It seems that the new frame has the value corresponding to the portrait but not to landscape orientation.
I think, problem is at CCEAGLView-ios.mm file -(void) doAnimationWhenKeyboardMoveWithDuration:(float)duration distance:(float)dis method

**Comment by minggo** [comment]
@ruslanmaley 
I can not catch your idea.
What's the matter?

**Comment by ruslanmaley** [comment]
@minggo 
There is problem with OpenGL frame on iOS 8+ when keyboard is showing and hiding from EditBox. I'm attaching screenshot of my app when keyboard was hiding.
![img_0194](https://cloud.githubusercontent.com/assets/4919677/5514658/1b3f0cec-884d-11e4-911d-8364c199f35b.PNG)

**Comment by minggo** [comment]
So the issue is that, the screen is black?
And what's the engine version?

**Comment by minggo** [comment]
Oh sorry, you said the engine is v3.3 in title.

**Comment by zilongshanren** [comment]
@ruslanmaley 

How to reproduce this issue?  Thanks.

**Comment by ruslanmaley** [comment]
My application has only landscape orientation.  
Steps to reproduce:
1. Select editbox to show keyboard.
2. Tap Enter key on keyboard or somewhere in empty field of screen to hide keyboard.
After hiding keyboard screen changed his layout. You can see it at screenshot I've attached.
This bug reproduce only with iOS 8. iOS 7 work well.

**Comment by ruslanmaley** [comment]
@minggo the screen is black and my screen was moved down and cropped. You can see that at the bottom of screenshot

**Comment by ruslanmaley** [comment]
I'm sorry, I've found solution. Problem was with screen resolution detection, not with cocos2d-x.

**Comment by walzer** [comment]
@ruslanmaley, thank your all the same.

**Comment by songgravel** [comment]
@ruslanmaley , would you please tell me how you solved this problem? I've got the same situation in my project with cocos2d-x 3.0 and IOS7.1. But everything is all right in IOS8.0 . Thanks a lot
