### ISSUE TITLE
cocos2d-x 3.3 : TextFieldTTF::setTextColor issue

### ISSUE THREAD

**Issue by klemsFR** [cocos2d/cocos2d-x#9545]
The behaviour of the TextFieldTTF::setTextColor has changed between version 3.2 and 3.3:
In 3.2 the new color was applied after the call of setTextColor function
In 3.3 the new color is not applied despite the call to setTextColor until at least one call to setString is peformed (before or after the call to setTextColor, that makes no difference).
Otherwise the textfield remains greyed as if it were disabled. 

Is it a nominal behaviour or a small regression?

**Comment by zilongshanren** [comment]
Thanks, @klemsFR 
I think it's a normal behavior.

The `setTextColor` API is reserved for changing the color of user input text. 

But the TextFieldTTF control also has a placeholder text and a placeholder color. When the input text is zero length, we use the `_inputText` for displaying placeholder text, when the `_inputText` is larger than zero, we use it for displaying user inputed text. 

So if we don't add the guard  in `setTextColor`,  it will change the placeholder color unintentionally. 
If the user don't input anything, when calling `setTextColor`, it just save the color value. And at last when user input something, the text color property will take effect.

I think it will make things more clearer, thanks.

**Comment by klemsFR** [comment]
OK, thank you!

**Comment by zilongshanren** [comment]
@klemsFR 
You are welcome:)

@minggo 
I think we could close this issue now.
