### ISSUE TITLE
crash in android when using cocostudio 2.0 with 3.3

### ISSUE THREAD

**Issue by thinkong** [cocos2d/cocos2d-x#9548]
related thread
http://discuss.cocos2d-x.org/t/crash-in-android-after-upgrading-to-3-3-final/18982/2

dunno exactly how to reproduce it. but it works fine in windows but crashes in android.. any help please

**Comment by minggo** [comment]
I think it is about studio reader and engine mismatch issue.
Duplicated with #9389?

**Comment by thinkong** [comment]
@minggo 
Oh.. right.. :(
I thought I had already published my project files.. guess i forgot..
