### ISSUE TITLE
MotionStreak jittering

### ISSUE THREAD

**Issue by dotsquid** [cocos2d/cocos2d-x#9560]
TL;DR
When frame rate is higher than 60fps the motion streak is jerky. To be more precise, the 'beginning' of the motion streak freezes for a short time every second.
This is caused by assuming that the game will run at 60fps or less

Here is the description and a short conversation http://discuss.cocos2d-x.org/t/motionstreak-jittering/18158

**Comment by minggo** [comment]
@dotsquid 
Will you check @ericmux 's pull request?
