### ISSUE TITLE
Compilation warnings on Linux

### ISSUE THREAD

**Issue by raould** [cocos2d/cocos2d-x#9564]
I don't know if anybody cares about compiler warnings?

On Ubuntu 14.04 intel 32bit, I set up the simple 'hello lua' app using the "cocos" command line tool, then I did "cocos run -p linux" and the compilation spat out a few warnings here and there as it went along.

Here is a small part of all the warnings I've seen:

[  9%] Building CXX object cocos2d-x/cocos/CMakeFiles/cocos2d.dir/2d/CCFastTMXTiledMap.cpp.o
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXLayer.cpp: In member function ‘virtual void cocos2d::e\
xperimental::TMXLayer::draw(cocos2d::Renderer_, const cocos2d::Mat4&, uint32_t)’:
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXLayer.cpp:157:50: warning: comparison between signed a\
nd unsigned integer expressions [-Wsign-compare]
     if(_renderCommands.size() < _primitives.size())
                                                  ^
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXLayer.cpp: In member function ‘void cocos2d::experimen\
tal::TMXLayer::setFlaggedTileGIDByIndex(int, int)’:
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXLayer.cpp:685:27: warning: comparison between signed a\
nd unsigned integer expressions [-Wsign-compare]
     if(gid == _tiles[index]) return;
                           ^
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXLayer.cpp: In member function ‘void cocos2d::experimen\
tal::TMXLayer::setupTileSprite(cocos2d::Sprite_, cocos2d::Vec2, int)’:
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXLayer.cpp:841:21: warning: comparison between signed a\
nd unsigned integer expressions [-Wsign-compare]
         if (flag == kTMXTileHorizontalFlag)
                     ^
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXLayer.cpp:849:72: warning: comparison between signed a\
nd unsigned integer expressions [-Wsign-compare]
         else if (flag == (kTMXTileVerticalFlag | kTMXTileHorizontalFlag) )
                                                                        ^
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXTiledMap.cpp: In member function ‘cocos2d::TMXTilesetI\
nfo\* cocos2d::experimental::TMXTiledMap::tilesetForLayer(cocos2d::TMXLayerInfo_, cocos2d::TMXMapInfo_)’:
/home/superman/Dev/cocos2d-x/Test/MyTest/frameworks/cocos2d-x/cocos/2d/CCFastTMXTiledMap.cpp:141:69: warning: comparison between signe\
d and unsigned integer expressions [-Wsign-compare]
                         if( (gid & kTMXFlippedMask) >= tilesetInfo->_firstGid )

**Comment by walzer** [comment]
Already fixed in #10179
