### ISSUE TITLE
Trouble with setting up in VS Express 2012

### ISSUE THREAD

**Issue by anayi** [cocos2d/cocos2d-x#9571]
Good evening!

I am trying to set up Cocos2D-X version 3.3 and I am having trouble.

After opening 'cocos2d-win32.vc2012' in Visual Studio (as stated in Cocos2d-X's wiki page: http://www.cocos2d-x.org/wiki/Win32_Installation_and_Setup), this was displayed in the Output window:

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\cpp-tests\proj.win32\cpp-tests.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\cpp-tests\proj.win32\cpp-tests.vcxproj" could not be found.

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\lua-tests\project\proj.win32\lua-tests.win32.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\lua-tests\project\proj.win32\lua-tests.win32.vcxproj" could not be found.

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\cpp-empty-test\proj.win32\cpp-empty-test.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\cpp-empty-test\proj.win32\cpp-empty-test.vcxproj" could not be found.

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\lua-empty-test\project\proj.win32\lua-empty-test.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\tests\lua-empty-test\project\proj.win32\lua-empty-test.vcxproj" could not be found.

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\cocos\2d\libcocos2d.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\cocos\2d\libcocos2d.vcxproj" could not be found.

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\cocos\scripting\lua-bindings\proj.win32\libluacocos2d.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\cocos\scripting\lua-bindings\proj.win32\libluacocos2d.vcxproj" could not be found.

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\cocos\editor-support\spine\proj.win32\libSpine.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\cocos\editor-support\spine\proj.win32\libSpine.vcxproj" could not be found.

C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\external\Box2D\proj.win32\libbox2d.vcxproj : error : Project "C:\Users\I.T\AppData\Local\Temp\Temp1_cocos2d-x-3.3.zip\cocos2d-x-3.3\external\Box2D\proj.win32\libbox2d.vcxproj" could not be found.

**Comment by minggo** [comment]
How to reproduce the issue?
Did you open `build/cocos2d-win32.vc2012.sln` to build `cpp-tests`?

**Comment by walzer** [comment]
Close it because:
- inactive for more than 3 months
- we're removing vs2012 support in v3.7.
