### ISSUE TITLE
Cocos2d-x have conflict with iOS 8 third party IME (sogou)

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#9577]
Possibly related to some `system` call which have been deprecated.
This issue will due to random crash

How to reproduce:
Open and close IME panel repeatly in game

**Comment by walzer** [comment]
Which input class were you use? CCTextField, or CCEditBox or UIEditBox? I think there're different implementations. 
BTW: which engine version?

**Comment by pandamicro** [comment]
Both CCTextField / CCEditBox can reproduce the issue
At the time I report this bug, it have been tested with Cocos2d-x v3.3

**Comment by pandamicro** [comment]
@zilongshanren when you refine Editbox for iOS, can you give third party IME a try to make sure this issue is gone ?

**Comment by zilongshanren** [comment]
@pandamicro  I can't reproduce after refactoring iOS EditBox.

**Comment by Johncdy** [comment]
I have reproduce this issue recently, I'm using old version cocos2dx(v3.1), can you help me to slove this problem? I want to know why it cause random crash.
