### ISSUE TITLE
Hindi is missing in cocos2d::LanguageType

### ISSUE THREAD

**Issue by volzhs** [cocos2d/cocos2d-x#9581]
As wikipedia says, Hindi speakers rank 4th by population.

http://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

Would cocos2d-x team add Hindi language type?

**Comment by walzer** [comment]
Cocos2d-x team don't have mobile phones that supports Hindi, so even if we implement this feature, we can't test it.

Please try to implement this feature on your phone, test it, then send a pull request. 

Thanks in advance!
