### ISSUE TITLE
The position of BMFont Label  is not correct

### ISSUE THREAD

**Issue by twolight** [cocos2d/cocos2d-x#9582]
string is in chinese.
    label->setAnchorPoint(Point(0.5,1));
    label->setPosition(CCP(319,443));
    label->setWidth(int(422));
    label->setLineBreakWithoutSpace(true);
Label has not be setted to the position controlled by the AnchorPoint.

**Comment by twolight** [comment]
i guess that set 0.5 AnchorPoint caused the problem.

**Comment by twolight** [comment]
if the BMFontLabel set scale,then the middle point of label can not be canculated corrected.

**Comment by qiululu** [comment]
using the test code, there seems no problems. only in some very small sized ones it will have some slightly edge cuts.

**Comment by qiululu** [comment]
it seems that this bug has been fixed already . adding the code below : 

---

   Node\* setAnchorLab(const Vec2 &vec)
  {
    auto s = Director::getInstance()->getWinSize();
    auto label = Label::createWithBMFont("fonts/bitmapFontTest2.fnt", "cocos2D`@%^&*()");
    label->setAnchorPoint(vec);
    label->setPosition(Vec2(s.width/2, s.height/2));
    //label->setWidth(int(422));
    label->setLineBreakWithoutSpace(true);
    return label;
  }

```
auto label = setAnchorLab(Vec2(0,0));
this->addChild(label);

auto label2 = setAnchorLab(Vec2(1,1));
this->addChild(label2);

auto label3 = setAnchorLab(Vec2(0.5,0.5));
this->addChild(label3);
```

---

 to test demo and then you'll see effect like this:
<img width="604" alt="127681c4-61c5-4d4e-a5d6-5bda8798e942" src="https://cloud.githubusercontent.com/assets/5564318/8716651/d2c8fb18-2bc5-11e5-90c2-b4641ad2a485.png">
and it effects the positon by comment out the setWidth function, so it doesn't  confused.

**Comment by pandamicro** [comment]
@twolight Please check out the new versions of Cocos2d-x, v3.6 and v3.7. If you found any problem, you can reopen this issue
