### ISSUE TITLE
Botched rendering of 3D objects on Tegra 3 devices

### ISSUE THREAD

**Issue by maltium** [cocos2d/cocos2d-x#9587]
Tegra 3 devices (ex. Nexus 7) only support 16-bit non-linear depth buffers, hence initializing OpenGL with the default 24-bit depth buffer in v3.3 always fails. The fallback configuration specifies 0-bit depth buffer, so 3D objects are guaranteed to be rendered incorrectly.

**Comment by darkdukey** [comment]
Forum link [here](http://discuss.cocos2d-x.org/t/sprite3d-botched-rendering/19047)

**Comment by devekaam** [comment]
I tested cocos2d-x v3.4 with 2 Android devices which have Tegra.

One  has NVIDIA Tegra (A01SH Android4.0.3),
and the other has  NVIDIA Tegra 3 (Nexus7 2012 Android 4.2.2).

Both caused the same situation.

In AppDelegate.cpp,  void AppDelegate::initGLContextAttrs()

I set
GLContextAttrs glContextAttrs = {8, 8, 8, 8, 24, 8};

This causes depthBits:0  and 3D rendering is botched.

I set
GLContextAttrs glContextAttrs = {8, 8, 8, 8, 16, 8};

This works better, but not perfect.
The Border between 3D objects are large-meshed and looks terrible.

I hope this situation is fixed.
If someone knows some ways to avoid it, please show me.

Thanks.

**Comment by drelaptop** [comment]
close 3D module issues, no concern it for 3 years long.
