### ISSUE TITLE
editbox animate to a wrong position only on iPad with ios8

### ISSUE THREAD

**Issue by kary24** [cocos2d/cocos2d-x#9598]
i have used this PR:
https://github.com/cocos2d/cocos2d-x/pull/8149/files
it can work normally on iPhone(both ios7 and ios8)
but i move all the screen to a wrong place on iPad(ios8)...
it can work when i just apply 2 UISupportedInterfaceOrientations:
UIInterfaceOrientationLandscapeRight & UIInterfaceOrientationLandscapeLeft
and it cant work(move to a wrong place) when i set all 4 UISupportedInterfaceOrientations

**Comment by zilongshanren** [comment]
@kary24 
You can't  set all the 4 UISupportedInterfaceOrientations. Because cocos2d-x can only support portrait or landscape, not both.

Thanks.

**Comment by kary24** [comment]
emmmm but unipay need  4 UISupportedInterfaceOrientations(our game runs on lanscape).how can i fix  this problem??:)

**Comment by zilongshanren** [comment]
@kary24 
I don't understand why unipay needs 4 orientations, maybe you should contact with them.

**Comment by kary24** [comment]
they need  portrait ...but our game runs on landscape.

**Comment by walzer** [comment]
This is not a bug from engine, but the lack of unipay sdk.
Ask unipay sdk to support landscape for games instead.
