### ISSUE TITLE
Android: minimizing/restoring app causing assertion errors and OpenGL issues

### ISSUE THREAD

**Issue by maltium** [cocos2d/cocos2d-x#9599]
Minimizing the barebones cocos2d-x app created with _cocos new_ causes the following warning in logcat

`W/ManagedEGLContext(23450): doTerminate failed: EGL count is 3 but managed count is 1`

Additionally when restoring my game, I sometimes get an assertion error and numerous OpenGL errors. This is not reproducible with the barebones app.

```
12-23 21:11:42.831: D/JniHelper(23729): JniHelper::getJavaVM(), pthread_self() = 1610240568
12-23 21:11:43.409: D/cocos2d-x debug info(23729): reload all texture
12-23 21:11:44.197: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 360 
12-23 21:11:44.198: D/cocos2d-x debug info(23729): come to foreground of VertexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 32 91
12-23 21:11:44.198: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 2424 
12-23 21:11:44.198: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 3702 
12-23 21:11:44.199: D/cocos2d-x debug info(23729): come to foreground of VertexBuffer
12-23 21:11:44.199: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 64 2202
12-23 21:11:44.199: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.200: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 1824 
12-23 21:11:44.200: D/cocos2d-x debug info(23729): come to foreground of VertexBuffer
12-23 21:11:44.200: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 32 351
12-23 21:11:44.214: W/Adreno-ES20(23729): : GL_INVALID_VALUE
12-23 21:11:44.214: E/cocos2d-x assert(23729): jni/../../cocos2d/cocos/./renderer/CCGLProgramState.cpp function:setVec4 line:166
12-23 21:11:44.215: D/cocos2d-x debug info(23729): OpenGL error 0x0501 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.216: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.216: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.228: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.229: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.238: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.238: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.244: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.244: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
...
```

Link to Cocos-2dx forum [thread](http://discuss.cocos2d-x.org/t/android-minimizing-restoring-app-causing-warnings-and-errors/19059)

**Comment by maltium** [comment]
I pushed a fix for the assertion error. Please review it [here](https://github.com/maltium/cocos2d-x/commit/1bd130d494ceea160d32ffbeefc46d2ef40c5334?diff=split). The problem was that when the _EVENT_RENDERER_RECREATED_ event it triggered, the uniforms were not being updated immediately. So when `MeshCommand::batchDraw()` makes a call to `_glProgramState->setUniformVec4(...)`, it tries to access the old `Uniform*` structures which would have been deallocated when re-creating the GLPrograms. Sometimes the the data previously allocated to the `Uniform*`s would be overwritten and sometimes not - therefore the assertion error does not happen consistently.

There's still the problem in `TextureAtlas::drawNumberOfQuads(...)` remaining. The call to `glDrawElements(...)` is failing.

**Comment by minggo** [comment]
@dabingnn 
It is a critical bug, please review it ASAP.
Thanks.

**Comment by dabingnn** [comment]
assert error fixed, GL_INVALID_VALUE still exist.

**Comment by maltium** [comment]
Finally I've managed to create a small project that recreates the `GL_INVALID_VALUE` bug.

Create a standard Cocos2d-x v3.3 project and replace the applicable files with those from [here](http://1drv.ms/1AfVL4K).

Note specifically the code in the `onResume()` handler in the Android project. As soon as the `createBug()` method is executed, you should see the OpenGL errors in the logcat and one of the labels won't be rendered.

**Comment by dabingnn** [comment]
Hi, @maltium
By running your test case, I found the bug was caused by particle system. I will keep track on this.
If you have more information, please tell me. Thanks.

**Comment by dabingnn** [comment]
Hi, could you please try my pull request to fix `GL_INVALID_VALUE` bug? The pull request can fix your test case.

**Comment by maltium** [comment]
@dabingnn that seemed to fix the issue with the recurring `GL_INVALID_VALUE` messages.

I've made a small addition to the test case; loading and rendering a 3D Sprite and occasionally I'm getting another error in the log.

```
01-05 12:38:44.980: D/JniHelper(25327): JniHelper::getJavaVM(), pthread_self() = 1605500936
01-05 12:38:45.204: D/cocos2d-x debug info(25327): reload all texture
01-05 12:38:45.227: D/cocos2d-x debug info(25327): cocos2d: fullPathForFilename: No file found at Helvetica. Possible missing file.
01-05 12:38:45.228: D/cocos2d-x debug info(25327): cocos2d: fullPathForFilename: No file found at Helvetica. Possible missing file.
01-05 12:38:45.229: D/cocos2d-x debug info(25327): Dirty Uniform and Attributes of GLProgramState
01-05 12:38:45.239: D/cocos2d-x debug info(25327): Dirty Uniform and Attributes of GLProgramState
01-05 12:38:45.240: D/cocos2d-x debug info(25327): Dirty Uniform and Attributes of GLProgramState
01-05 12:38:45.240: D/cocos2d-x debug info(25327): come to foreground of VertexBuffer
01-05 12:38:45.240: D/cocos2d-x debug info(25327): recreate IndexBuffer with size 32 91
01-05 12:38:45.240: D/cocos2d-x debug info(25327): come to foreground of IndexBuffer
01-05 12:38:45.240: D/cocos2d-x debug info(25327): recreate IndexBuffer with size 2 360 
01-05 12:38:45.243: W/Adreno-ES20(25327): <core_glVertexAttribPointer:531>: GL_INVALID_VALUE
01-05 12:38:45.253: D/cocos2d-x debug info(25327): OpenGL error 0x0501 in jni/../../cocos2d/cocos/./2d/CCParticleSystemQuad.cpp postStep 365
```

This occasionally happens when starting the app on my Moto G. The error is only printed once, unlike the previous problem. I'm using v3.3 with the two fixes in this issue.

**Comment by dabingnn** [comment]
@maltium It seems that this issue contains too much work. Could you please add another issue for the newly reported problem?

**Comment by maltium** [comment]
@dabingnn sure, no problem.

Thank you!

**Comment by dabingnn** [comment]
@maltium  Thanks, I have update my pull request to reset `_VAOname` to 0 if VAO is supported.

This issue will be closed.
