### ISSUE TITLE
Really needed a set of file access functions

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#9621]
Cocos2d-x have three option for data storage: 
- FileUtils::writeToFile
- localStorageSetItem
- UserDefault

I want to talk about `FileUtils` which have a whole set of functions to read a file, and one function to write a map object to a file. The balance is obviously not quite well here. The reason we need a set equivalent functions to write content into a file are: 
1. To balance the API design.
2. In JS or Lua, if there are no such API bindings, then no way to write even a simple string into a file, user must write C++ code to achieve this and bind them manually.

So please consider it

**Comment by minggo** [comment]
What functions you think are needed?
Could you write more detail of requirement?

**Comment by pandamicro** [comment]
What we have now for reading:
- FileUtils::getStringFromFile
- FileUtils::getDataFromFile
- FileUtils::getFileDataFromZip
- FileUtils::getValueMapFromFile
- FileUtils::getValueVectorFromFile

For write access:
- FileUtils::writeToFile

The API `writeToFile` doesn't represent what we understand from the name, it actually write a value map to a file.

What I suggest:
- FileUtils::writeStringToFile
- FileUtils::writeDataToFile
- FileUtils::writeValueMapToFile // which is the current writeToFile
- FileUtils::writeValueVectorToFile

**Comment by minggo** [comment]
Thanks.
We will consider the requirements.

**Comment by pandamicro** [comment]
Here is a related user request: https://github.com/cocos2d/cocos2d-js/issues/1315

**Comment by pandamicro** [comment]
Another user requested similar features for FileUtils: https://github.com/cocos2d/cocos2d-js/issues/1323
1. Save content to file
2. Uncompress zip file
3. Calculate MD5 value for verification

**Comment by dumganhar** [comment]
> Another user requested similar features for FileUtils: cocos2d/cocos2d-js#1323
> 
> Save content to file
> Uncompress zip file
> Calculate MD5 value for verification

It will be awesome if these features could be supported. :)
It's really a strong requirement for games which use `Cocos2d-JS`. So please support it.

**Comment by walzer** [comment]
Do it in v3.8. Marked as highlight.

**Comment by TimothyZhang** [comment]
Unfortunately, `writeDataToFile` is not supported yet by JSB in cocos2d-x v3.8 

I created a pull request #13960 for this.

**Comment by jminht** [comment]
how about Lua?
we also need support like FileUtils::getDataFromFile.
@pandamicro @minggo
