### ISSUE TITLE
ccui's buttons weird behavior with multitouch

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#9627]
On mobile devices with multitouch:
1. one finger touch down a button, keep it touched
2. another finger touch another button
3. then release both at the same time

Both button will respond, is this expected behavior ?

**Comment by walzer** [comment]
Good test case! But I think we should keep this design because gamers perhaps really want that. They are very clear that they have touched 2 button at the same time, so the response is also 2 buttons.

What the engine act, is what you input, right?

**Comment by yue19870813** [comment]
I don't think so.You can give gamer two choice, because it's a trouble in my project.
