### ISSUE TITLE
cocos2dx3.3f spine:GLProgram

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#9629]
spine 动画使用 着色器 会导致 spine 动画坐标缩放等信息全部为默认值， 修改无效。或者是我代码写错了?

auto p = ShaderCache::getInstance()->getGLProgram(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR);
    p->initWithFilenames("res/Shader/gray.vsh", "res/Shader/gray.fsh");
    p->bindAttribLocation(GLProgram::ATTRIBUTE_NAME_POSITION, GLProgram::VERTEX_ATTRIB_POSITION);
    p->bindAttribLocation(GLProgram::ATTRIBUTE_NAME_COLOR, GLProgram::VERTEX_ATTRIB_COLOR);
    p->bindAttribLocation(GLProgram::ATTRIBUTE_NAME_TEX_COORD, GLProgram::VERTEX_ATTRIB_TEX_COORDS);
    p->link();
    p->updateUniforms();
    setGLProgram(p);

**Comment by walzer** [comment]
Please ask questions in the forum, not in this issue tracker.
