### ISSUE TITLE
Problem with TexParams after application comes from background in Android

### ISSUE THREAD

**Issue by rgngl** [cocos2d/cocos2d-x#963]
I have a CCSprite node of which I set it's texture's wrap parameters to GL_CLAMP_TO_EDGE for horizontal coordinates and GL_REPEAT for the vertical coordinates. This way I show a part of the texture and have spinning effect.

Under Android platform when my application comes back from background the texture wrapping parameters are set to GL_CLAMP_TO_EDGE both and it doesn't matter if I try to set that texture's parameters during CCApplication::applicationWillEnterForeground() or CCLayer::onEnter, the texture still looks clamped to the edge. 

When I set the texParams again right before I update the node it looks fine but still the artifacts are visible until I click any button to update the screen.

This behaviour is not observable under iOS.

**Comment by minggo** [comment]
Click any button to update the screen?
I don't know why you should do it like this.
Engine will draw frame infinitely.

**Comment by rgngl** [comment]
Sorry that's my bad. There's no problem about updating the screen. The only problem is about texture parameters I set get lost upon CCTextureCache::reloadAllTextures() and there's already an issue reported for that.

**Comment by minggo** [comment]
Yeap, it is an issue.
We should reset texture parameters when invoking CCTextureCache::reloadAllTextures() as you did.

Thank you.
