### ISSUE TITLE
[Feature] Add Title Alignment for ui::Button

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#9633]
Wish to have changes in UIButton.h and UIButton.cpp for titleAligment.

void setTitleAlignment(TextHAlignment hAlignment); 
void setTitleAlignment(TextHAlignment hAlignment, TextVAlignment vAlignment);
void Button::setTitleAlignment(TextHAlignment hAlignment)
{
_titleRenderer->setAlignment(hAlignment);
}

void Button::setTitleAlignment(TextHAlignment hAlignment, TextVAlignment vAlignment)
{
_titleRenderer->setAlignment(hAlignment, vAlignment);
}

And default title align setup in void Button::initRenderer()

_titleRenderer->setAlignment(TextHAlignment::CENTER, TextVAlignment::CENTER);

**Comment by Dimon4eg** [comment]
I implemented the feature but PR can't be merged automatically.
Could you please merge?
