### ISSUE TITLE
setColor of ImageView with cocostudio 1.6 not applied when load it with cocos2d-x 3.3 final

### ISSUE THREAD

**Issue by volzhs** [cocos2d/cocos2d-x#9639]
1. place a ImageView with cocostudio 1.6
2. set a png file and make 3x3 grids to ImageView
3. set Colot tint to ImageView
4. export json
5. load it with cocos2d-x 3.3

ImageView is not applied color.

**Comment by zilongshanren** [comment]
@chengstory 
Please take a look, thanks.

**Comment by chengstory** [comment]
@pipu Please take a look, Thanks.

**Comment by volzhs** [comment]
I found this ImageView looks fine when add it to Node.
But the ImageView color ignored when add it to ListView.

**Comment by pipu** [comment]
@volzhs 

I''ve tested this issue refer to your step.
I didn't discover that ImageView is not applied color.

Effect:
original:

![original](https://cloud.githubusercontent.com/assets/3690622/5796235/b266b7ca-9fde-11e4-9d57-2d79d7ae5a0c.PNG)

after set Colot tint to ImageView:
![setcolorwithgreen](https://cloud.githubusercontent.com/assets/3690622/5796244/0ea407cc-9fdf-11e4-9f26-17e64e29afa3.PNG)

**Comment by minggo** [comment]
cocos studio is canceled, so close this issue
