### ISSUE TITLE
Please Add a Head File crypt.h into external/unzip.cpp

### ISSUE THREAD

**Issue by xiaozzjl** [cocos2d/cocos2d-x#9654]
When I want to extract the encrypted compressed file.

I commentate “#define NOUNCRYPT” and call the function.

int ZEXPORT unzOpenCurrentFile3 (unzFile file, int\* method, int\* level, int raw, const char\* password).

then compile the code, xcode hint me the head file crypt.h was not found.

Hope the official will join this header file.

Forgive my poor English, hope someone can understand.

**Comment by minggo** [comment]
@xiaozzjl 
Where to get `crypt.h`?

**Comment by xiaozzjl** [comment]
@minggo @andyque 
I find it here
https://github.com/nmoinvaz/minizip/blob/master/crypt.h

**Comment by minggo** [comment]
@andyque 
Could you please add this header file.

**Comment by zilongshanren** [comment]
@minggo 
I will fix it the v3.4rc0

**Comment by zilongshanren** [comment]
@minggo We have added it in v3.4 rc0.  So we could close this issue now.
