### ISSUE TITLE
Can't get data from file when file was using by other application on windows

### ISSUE THREAD

**Issue by ffskyfan** [cocos2d/cocos2d-x#9655]
In my project,I use csv file to store my game config data. 
When I tried to get data from the csv file While I was using open-office open this file, I got an error code 32.
I solved this problem.
Change the 3th par of function CreateFileW  from NULL to FILE_SHARE_READ|FILE_SHARE_WRITE in function FileUtilsWin32::getFileData .It will make getFileData function read the file properly when other app using it.

**Comment by minggo** [comment]
Thanks.
Why not send a pull request for it?

**Comment by minggo** [comment]
@Dhilan007 
Could you please send a pull request for it?
