### ISSUE TITLE
Problem with loading widget from JSON file in cocos2d-x v3.2

### ISSUE THREAD

**Issue by huytd** [cocos2d/cocos2d-x#9661]
Hi, I have problem with loading widget from JSON file. 

After loaded, I want to modify some UI elements (for example: I have a widget contains a Label, for display highscore, I want to show the widget and change the highscore text)
But there are 2 problem when I get the Label inside widget and modify it: cannot `setString` and crash when use `addChild`. 

**Dev environment:**
- cocos2d-x v3.2
- CocoStudio 1.6.5
- Xcode 6.1
- iOS 8.1

**My widget:**

``` cpp
// Load my UI
highScorePanel = GUIReader::getInstance()->widgetFromJsonFile("ui/BrickHighscore.json");
// Then add it to scene
...
// Then, find the label I want to "play" with
auto lblScore = (Label*)highScorePanel->getChildByName("lblScore");
```

**Problem 1:**

``` cpp
// Set text for Label inside that UI, not work
lblScore->setString("Hello World!"); // nothing happend
```

**Workaround for 1:**
Don't use it =))

**Problem 2:**
Create another label (from `lblScore`'s config) and add it into highScorePanel

``` cpp
auto lblMyScore = Label::createWithSystemFont("Score: 0", "Helvetica", lblScore->getTTFConfig().fontSize);
highScorePanel->addChild(lblMyScore); // CRASH!!!!
```

**Workaround 2:**
Create `lblMyScore` with some defaultl config values, then set it to `lblScore` value later.

``` cpp
lblMyScore = Label::createWithSystemFont("Score: 0", "Helvetica", Director::getInstance()->getVisibleSize().height / 25);
// Then
lblMyScore->setTTFConfig(lblScore->getTTFConfig());
lblMyScore->setPosition(lblScore->getPosition());
// Then hide the UI's label
lblScore->setVisible(false);
// Add the real label to UI
highScorePanel->addChild(lblMyScore);
```

So, from above problems, the conclusion is: `Don't do anything with loaded UI, just use them as a placeholder and create another one in your code (facepalm)`

**Comment by minggo** [comment]
Since cocos studio is canceled, so close this issue.
