### ISSUE TITLE
EventListenerKeyboard.onKeyPressed event not firing for back button on Android?

### ISSUE THREAD

**Issue by tankorsmash** [cocos2d/cocos2d-x#9664]
Switching the listener to `onKeyReleased` instead of `onKeyPressed` works, ie this works:

```
auto pKeybackListener = EventListenerKeyboard::create();
pKeybackListener->onKeyReleased = CC_CALLBACK_2(my_listener_func, ptr_to_layer);
```

but 

```
auto pKeybackListener = EventListenerKeyboard::create();
pKeybackListener->onKeyPressed = CC_CALLBACK_2(my_listener_func, ptr_to_layer);
```

doesn't, specifically when trying to press the back button on the android hardware phone. The escape key works properly with both Pressed and Released on the PC, through VS2013.

**Comment by larsven** [comment]
I came across this problem too when trying to measure the time between onKeyPressed and onKeyReleased. Will have to find a workaround.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12644

**Comment by tankorsmash** [comment]
Thank you
