### ISSUE TITLE
频繁调用setContentScaleFactor，会拖慢游戏速度

### ISSUE THREAD

**Issue by hjcapple** [cocos2d/cocos2d-x#9681]
我的游戏中，所有屏幕尺寸都只使用一套图片。所以Director中的contentScaleFactor绝大多数时候为1。

而需要动态生成文字的时候，就根据屏幕尺寸设置contentScaleFactor，来生成更符合屏幕尺寸的文字（还有其它需要根据屏幕动态生成的矢量素材）。之后再还原旧的contentScaleFactor。

这样就使得我不断地调用setContentScaleFactor来修改恢复_contentScaleFactor。

而每次调用setContentScaleFactor，总是会调用createStatsLabel()来生成状态Label, 就算直接将_displayStats设置为false也一样。这样频繁调用就会拖慢运行速度。

我现在的做法是直接在源码中注释掉 Director::setContentScaleFactor中的createStatsLabel()语句。这里应该有更好的做法。

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10744
