### ISSUE TITLE
pushScene and popScene bug.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#9690]
`version:` v3.3Final
`issue:` repeat to push and pop scene. the program crashed.
`reproduce:` download the zip, then unzip to HelloWorld Project.
`How to fix it:` 
comment the following line:

``` cpp
bool MenuItemLabel::initWithLabel(Node* label, Ref* target, SEL_MenuHandler selector)
{
    _target = target;
//  CC_SAFE_RETAIN(_target);
    return initWithLabel(label, std::bind(selector,target, std::placeholders::_1) );
}
```

``` cpp
void MenuItem::onExit()
{
    Node::onExit();
    //CC_SAFE_RELEASE(_target);
}
```

but I don't know it is the right way or not? Somebody help?
[click me to download the zip](http://www.cocoachina.com/bbs/job.php?action=download&aid=83476)

**Comment by zachprinz** [comment]
I was having this issue. 

I checked out the recent changes made to CCMenuItem and saw that there was a commit made recently that overwrites the onExit method in CCMenuItem. 

https://github.com/cocos2d/cocos2d-x/commit/93fdcf1f041e2946b300f505dc3cc64805b27095

After I removed these additions in my CCMenuItem.h the issue no longer occurred.

**Comment by fusijie** [comment]
@Dhilan007 pls have a look~

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10299

**Comment by fusijie** [comment]
Thanks @Dhilan007
