### ISSUE TITLE
Paused game awaked by the Clock on Android

### ISSUE THREAD

**Issue by NewCai** [cocos2d/cocos2d-x#9691]
We can reproduce this bug by following steps:
1. Start a game normally which plays a BGM (this could be a indicator later)
2. Press the power button to lock the android devices.
3. Wait for the Clock to ring(assuming we have settled before)
4. Click the "take a nap" label on Screen(most android phones have this function). The device locked again but the game resumed!

I found the reason is that onResume method was invoked in this situation.But I have not found a good way to fix it.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10255
