### ISSUE TITLE
Sprite::getTextureRect should be const

### ISSUE THREAD

**Issue by dakikifr** [cocos2d/cocos2d-x#9694]
The getTextureRect method from cocos2d::Sprite should be const :

"inline const Rect& getTextureRect(void) const { return _rect; }"

instead of

"inline const Rect& getTextureRect(void) { return _rect; }"

**Comment by minggo** [comment]
Fixed in #9700.

**Comment by minggo** [comment]
Thanks.

**Comment by dakikifr** [comment]
I saw you have set getTextureAtlas to be const too, but I'm not sure it's true since it returns a pointer and not a const& like getTextureRect does.
Pointed data can be altered by the retriever so the method should not be set as const.
