### ISSUE TITLE
updatePhysicsBodyTransform not called if parent without physics is scaled.

### ISSUE THREAD

**Issue by mannewalis** [cocos2d/cocos2d-x#9695]
This update should be moved to where the transform is updated if dirty so that if parent nodes transforms change, then the physics body updates still occur. I.e. move the call into **processParentFlags** or **getNodeToParentTransform**. This will also solve the problem of being called multiple times depending on what changes. It will get called 3 times if you change scaleX, scaleY, scaleZ separately.

To speed up the update, pull the scale out of the transform instead of traversing all parents to calculate it. You can do the same for position and rotation too probably.

**Comment by minggo** [comment]
Yep. We are optimizing it.
Thanks.

@Dhilan007 
Please consider @mannewalis 's opinion.
