### ISSUE TITLE
there're two instances when using cocos run on android platform

### ISSUE THREAD

**Issue by calfjohn** [cocos2d/cocos2d-x#9702]
there is the steps:
1 run ' cocos new -l cpp testcpp1' in terminal
2 run ' cocos run -s testcpp1 -p android ' in terminal and wait until the application is running
3 back to the main screen on android device
4 click the new application icon of testcpp1

so, there's two instances of testcpp1 in your device.
repeat step 3 and 4, you may find more instances.

I test these on lenovo S90, xiaomi 2s, nexus 7.

**Comment by minggo** [comment]
As we discussed, it is the problem of cocos console.
