### ISSUE TITLE
Cocos2d-Console cannot generate new cpp project templates/*.*

### ISSUE THREAD

**Issue by joaopedronardari** [cocos2d/cocos2d-x#9716]
In the most recent version I can't generate a new cpp project.

I saw that another user had the same problem in another version:
https://github.com/cocos2d/cocos2d-x/issues/9293

But this message error bellow appeared in 3.3 (final version):
NOTE: I've used 3.3rc0 a month ago and worked. Now I used 3.3 final (in a new machine using Windows 8.1) and this problem appeared.

`C:\Users\myuser\Desktop\cocos2d-x-3.3>cocos new MyGame -p com.Project.MyGame
 -l cpp -d Project
Running command: new
Traceback (most recent call last):
  File "C:\Users\myuser\Desktop\cocos2d-x-3.3\tools\cocos2d-console\bin\/coc
os.py", line 745, in <module>
    run_plugin(command, argv, plugins)
  File "C:\Users\myuser\Desktop\cocos2d-x-3.3\tools\cocos2d-console\bin\/coc
os.py", line 708, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "C:\Users\myuser\Desktop\cocos2d-x-3.3\tools\cocos2d-console\plugins\
project_new\project_new.py", line 210, in run
    self.parse_args(argv)
  File "C:\Users\myuser\Desktop\cocos2d-x-3.3\tools\cocos2d-console\plugins\
project_new\project_new.py", line 139, in parse_args
    self.init(args)
  File "C:\Users\myuser\Desktop\cocos2d-x-3.3\tools\cocos2d-console\plugins\
project_new\project_new.py", line 80, in init
    self._templates = Templates(args.language, self._templates_paths, args.templ
ate)
  File "C:\Users\myuser\Desktop\cocos2d-x-3.3\tools\cocos2d-console\plugins\
project_new\project_new.py", line 244, in __init__
    self._scan()
  File "C:\Users\myuser\Desktop\cocos2d-x-3.3\tools\cocos2d-console\plugins\
project_new\project_new.py", line 263, in _scan
    dirs = [name for name in os.listdir(templates_dir) if os.path.isdir(
WindowsError: [Error 5] Access is denied: 'C:\\Users\\myuser\\templates/*.*'`

**Comment by minggo** [comment]
@natural-law 
Could you please take a look?

**Comment by natural-law** [comment]
@joaopedronardari 
I'm sorry for the problem. Here is a PR from another developer: https://github.com/cocos2d/cocos2d-console/pull/205
Could you please help me to check whether it's works? Because I don't have the environment to reproduce the problem.
Thank you very much!

**Comment by natural-law** [comment]
@joaopedronardari 
The problem is solved by this PR of cocos2d-x :https://github.com/cocos2d/cocos2d-x/pull/9743
The related PR in cocos2d-console is : https://github.com/cocos2d/cocos2d-console/pull/207

Thanks for your feedback!

**Comment by joaopedronardari** [comment]
@natural-law @minggo Thanks so much! I will try again next friday. =D
