### ISSUE TITLE
Critical Bug: New AudioEngine causes game 'freeze' on Android

### ISSUE THREAD

**Issue by bryanwong** [cocos2d/cocos2d-x#9730]
Cocos2D-X 3.3 finial. Tested on KuPai Dashen and Oppo with Android 4.2.2.  After playing about 10 minutes or 8-9 levels of the game. It just stopped to react to touch event. Game audio is playing OK, logcat works good.  
Error log:

12-31 10:57:53.362: D/(3549): audioPlayer_dispatch_headAtEnd_lockPlay callback
12-31 10:57:53.500: D/(3549): Callback 0x5d7e7a7c(0x5f19dfa8, 0x612e6a70, SL_PLAYEVENT_HEADATEND)
12-31 10:57:53.500: D/(3549): audioPlayer_dispatch_headAtEnd_lockPlay callback
12-31 10:57:53.643: E/Parcel(3549): writeDupFileDescriptor: error 24 dup fd 1023
12-31 10:57:53.644: E/SurfaceTextureClient(3549): queueBuffer: error queuing buffer to SurfaceTexture, -22
12-31 10:57:53.644: E/[EGL-ERROR](3549): void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1268: unable to queue buffer (0x5f07787c)
12-31 10:57:53.658: D/CallStack(3549): Mali#00  pc 000dd5a2  /system/lib/libMali.so (MtkMali_DumpCallStack+17)
12-31 10:57:53.658: D/CallStack(3549): Mali#01  pc 0000f4a4  /system/lib/libMali.so
12-31 10:57:53.658: D/CallStack(3549): Mali#02  pc 0000fe2c  /system/lib/libMali.so
12-31 10:57:53.658: D/CallStack(3549): Mali#03  pc 00053450  /system/lib/libMali.so
12-31 10:57:53.658: D/CallStack(3549): Mali#04  pc 0005273c  /system/lib/libMali.so
12-31 10:57:53.658: D/CallStack(3549): Mali#05  pc 00050cec  /system/lib/libMali.so (shim_eglSwapBuffers+88)
12-31 10:57:53.658: D/CallStack(3549): Mali#06  pc 0000e73a  /system/lib/libEGL.so (eglSwapBuffers+161)
12-31 10:57:53.658: D/CallStack(3549): Mali#07  pc 0005223a  /system/lib/libandroid_runtime.so
12-31 10:57:53.658: D/CallStack(3549): Mali#08  pc 0001e790  /system/lib/libdvm.so (dvmPlatformInvoke+112)
12-31 10:57:53.658: D/CallStack(3549): Mali#09  pc 0004e708  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const_, JValue_, Method const_, Thread*)+499)
12-31 10:57:53.659: E/SurfaceTextureClient(3549): dequeueBuffer: error duping fence: 24
12-31 10:57:53.662: W/MALI(3549): __egl_mali_post_color_buffer:650: _mali_frame_builder_swap, ret = -1
12-31 10:57:53.663: W/GLThread(3549): eglSwapBuffers failed: EGL_BAD_ALLOC
12-31 10:57:54.337: D/(3549): Callback 0x5d7e7a7c(0x613166c0, 0x6137b858, SL_PLAYEVENT_HEADATEND)
12-31 10:57:54.337: D/(3549): audioPlayer_dispatch_headAtEnd_lockPlay callback
12-31 10:57:54.426: I/View(3549): Touch down dispatch to org.cocos2dx.lib.Cocos2dxGLSurfaceView{4148e458 VFE..... .F....I. 0,0-540,960}, event = MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=123.7708, y[0]=750.2185, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=30142051, downTime=30142051, deviceId=3, source=0x1002 }
12-31 10:57:54.427: D/cocos2d-x debug info(3549): touch begin
12-31 10:57:54.427: D/cocos2d-x debug info(3549): touch begin, answers:13
12-31 10:57:54.457: I/View(3549): Touch up dispatch to org.cocos2dx.lib.Cocos2dxGLSurfaceView{4148e458 VFE..... .F....I. 0,0-540,960}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=123.7708, y[0]=750.2185, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=30142087, downTime=30142051, deviceId=3, source=0x1002 }

**Comment by bryanwong** [comment]
Hi dabingnn, 

This bug was critical. It happened 100% in my game and caused the game 'freeze'.  The problem was caused by new AudioEngine.  I switch back to SimpleAudioEngine on Android, the problem was gone. 

You may refer here https://groups.google.com/forum/#!msg/android-ndk/zANdS2n2cQI/AT6q1F3nNGIJ

Thanks,
Bryan

**Comment by minggo** [comment]
@Dhilan007 
Please check it.
It is very important for New Audio.

Thanks @bryanwong .

**Comment by minggo** [comment]
@bryanwong 
Could you please change the title?
Thanks.

**Comment by bryanwong** [comment]
@minggo Title changed.

If you guys need assistance, feel free to add my QQ  1766018980.

**Comment by minggo** [comment]
Thanks.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10149
