### ISSUE TITLE
[Bug ios-simulator] TMX Iso VertexZ 

### ISSUE THREAD

**Issue by zilongshanren** [cocos2d/cocos2d-x#9750]
Sprite should hide behind the trees.

But it also display on top of tree.

**Comment by zilongshanren** [comment]
@dabingnn 
This issue is still exists in v3.4 rc

**Comment by samuele3hu** [comment]
I also meet the same bug on the mac platform.

**Comment by dabingnn** [comment]
@darkdukey Could you please take a look at the mechanism of this?
It happen after refactor rendering.
