### ISSUE TITLE
Sprite3D::setGLProgram(...) does not work

### ISSUE THREAD

**Issue by maltium** [cocos2d/cocos2d-x#9767]
Calling `Sprite3D::setGLProgram(...)` with a program doesn't change the shader program. Using Cocos2d-x v3.3.

**Comment by minggo** [comment]
@super626
Could you please take a look?

**Comment by super626** [comment]
@maltium 
Can send me your .fbx file?

**Comment by maltium** [comment]
@super626 
To give you some more details, I'm using `GLProgram::createWithByteArrays()` to create a program and then passing the returned instance to `Sprite3D::setGLProgram(...)`.

You can download the FBX file from [here](http://1drv.ms/1Byvl01). It's a simple mesh without any animations.

**Comment by super626** [comment]
@maltium 

Sorry, I can not download the FBX. Can you send me via email. tony.yang@chukong-inc.com
Thanks.

**Comment by maltium** [comment]
@super626 Please let me know if you need anymore info

**Comment by walzer** [comment]
@maltium Thanks for your feedback. @super626 just reproduced this bug, and I put this issue into v3.7 roadmap.
