### ISSUE TITLE
When a Button is a child of ScrollView, any slight movement while pressing the button results in a cancelled press.

### ISSUE THREAD

**Issue by idrise** [cocos2d/cocos2d-x#9768]

**Comment by zilongshanren** [comment]
@idrise 
I think it's a normal behavior. There is a moving threshold when you press the button on top of ScrollView. If you don't like this value, you could simply change it in UIScrollView.cpp.

**Comment by zilongshanren** [comment]
@idrise 
How about this issue now?

**Comment by idrise** [comment]
Im afraid buttons still cancel if there is any slight movement during the click on a scrollview.

My beta testers continue to report this as a problem which means that they have to press the button multiple times and very deliberately to get a click to occur.

Dave Elliott.

**Comment by idrise** [comment]
I changed the #define MOVE_INCH to 1.0f from (7.0f/160.0f). Still the cancel occurred.
To recreate the issue...

Create a scrollview and a button on the scrollview. Press and hold the button and roll your finger very slightly then release, the button press is cancelled. I have seen one user (with biggish fingers) who couldn't get the button to press despite multiple attempts.

Is MOVE_INCH the moving threshold that you refer to in your comment Andy ?

**Comment by idrise** [comment]
Hi Andy, where is this threshold value ? What is it called ?

**Comment by idrise** [comment]
MOVE_INCH was in the scrollview defined in extensions. There appears to be no threshold in the scrollview defined in UI

**Comment by zilongshanren** [comment]
@idrise  This issue has been resolved . please check the latest code.
