### ISSUE TITLE
SimpleAudioEngine profile

### ISSUE THREAD

**Issue by joewan** [cocos2d/cocos2d-x#9773]
hi 
@minggo simpleAudioEngine::playEffect has serious performance problem,
even though I have cached the sound effect, it needs 0.03s to play a sound effect.
It has brought us significant confusion.
maybe this problem only happens on win32 platform.

can you give us some suggestions.   the new sound engine is in experimental status, is it a good idea to use it..

Test case:
1.cache a sound effect
2.and then play the same sound in a for loop, and look the interval of play sound effect.

**Comment by minggo** [comment]
New sound engine in experimental namespace is because it has not been implemented on all supported platforms. Now it supports iOS, Android, Mac, Windows. You can use it if you don't care linux and WP8/WP8.1.

**Comment by joewan** [comment]
new audio engine is great, this has solved our problem on win32, and I also need to verify it on android and ios.

do you know SimpleAudioEngine::playSoundEffect has performance problem, or I have used it in a wrong way.

**Comment by minggo** [comment]
I don't know if it has performance issue on Windows. But i suggest you use new audio engine instead, because we will deprecated SimpleAudioEngine in future.

**Comment by joewan** [comment]
thanks.
