### ISSUE TITLE
Libcurl does not work correctly on WP8

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#9774]
Post in cocos2d-x thread
http://discuss.cocos2d-x.org/t/req-upgrade-libcurl-version-in-wp8-please/18969
`curl_easy_perform()` return `CURLE_RECV_ERROR` on WP8.

@huangshiwu Could you please confirm that?

**Comment by shrimpz** [comment]
I'm sorry that my wrong approach leads this issue.
I ported my project to WP8 in cocos2d-x 3.2 (patch bug with self).
My team member use VS2013, but it link WP8's lib, so this issue is made.
later, I use VS2012 and link WP8's libcurl, it's ok.
but, This libcurl version had OpenSSL-Heartbleed ?
now, some appstore reject it.....

**Comment by ghost** [comment]
@shrimpz Some appstore?You mean android and iOS also have the problem?

**Comment by shrimpz** [comment]
@huangshiwu 

I have an another app published in google play.
some days ago, I recv google's mail:

> Your app XXXXXXXXXXXXXXXXXXXX is running an outdated version of OpenSSL, which has multiple security vulnerabilities. You should update OpenSSL as soon as possible.
> 
> The vulnerabilities were addressed in OpenSSL versions beginning with 1.0.1h, 1.0.0m, and 0.9.8za. To confirm your OpenSSL version, you can do a grep via ("$ unzip -p YourApp.apk | strings | grep "OpenSSL""). For more information about the vulnerability, please consult http://www.openssl.org/news/secadv_20140605.txt.
> 
> To confirm that you’ve upgraded correctly, upload the updated version to the Developer Console and check and after five hours.
> 
> This is the second warning we’ve sent you. Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered “dangerous products” and subject to removal from Google Play.

**So, I think that libcurl need upgrade...**

**Comment by ghost** [comment]
What's your app's engine version?

**Comment by ghost** [comment]
Now curl's OpenSSL had already been updated to 1.0.1j on android platform.

**Comment by shrimpz** [comment]
> I ported my project to WP8 in cocos2d-x 3.2 (patched bug with myself, such as: creash, label etc).

**Comment by ghost** [comment]
WP8's OpenSSL version is still 1.0.1c

**Comment by stammen** [comment]
I will be fixing this with the update to version 7.39.0.

**Comment by minggo** [comment]
@stammen update libcurl in cocos2d-x-3rd-party-libs-bin#80.

**Comment by minggo** [comment]
fix in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/80

**Comment by minggo** [comment]
@huangshiwu 
Please check it.

**Comment by stammen** [comment]
I updated openssl to 1.1.0.
