### ISSUE TITLE
Label 使用描边(enableOutline)异常！！！

### ISSUE THREAD

**Issue by BorgLee** [cocos2d/cocos2d-x#9782]
使用Label描边时，如果使用纯黑色的字和纯白色的描边会出现全都是黑色的情况。
TTFLabel我已通过修改ccShader_Label_outline.frag这个文件解决，修改如下：
 void main()
{
    vec4 sample = texture2D(CC_Texture0, v_texCoord);
    float fontAlpha = sample.a; 
    float outlineAlpha = sample.r; 
    if (outlineAlpha > 0.0){ 
        vec4 color = v_fragmentColor * fontAlpha + u_effectColor * (1.0 - fontAlpha);
        gl_FragColor = vec4( color.rgb,max(fontAlpha,outlineAlpha)*color.a);
    }
    else {
        discard;
    }
}

但如果使用系统字体，依然会出现该问题。由于本人能力有限，无法修复该BUG。往触控大神们尽快解决此BUG！！！非常感谢！

**Comment by csrongquan** [comment]
我也遇到了，先用你的方法解决一下。后面再看

**Comment by csrongquan** [comment]
多谢了

**Comment by BorgLee** [comment]
10几天过去了。真的很着急。能否给个临时的解决方案呢？

**Comment by Dhilan007** [comment]
Please replace setColor with setTextColor

**Comment by Dhilan007** [comment]
@minggo It's not a bug.

**Comment by Dhilan007** [comment]
@minggo It's not a bug.

**Comment by BorgLee** [comment]
不是setColor这个方法 是enableOutline这个方法

**Comment by Dhilan007** [comment]
Please try to do like this:
label->setTextColor(Color4B::BLACK);
label->enableOutline(Color4B::WHITE, 1);

**Comment by BorgLee** [comment]
enableOutline 在使用系统字体时 描边会出现异常，例如使用黑色字，白色描边。

**Comment by Dhilan007** [comment]
Which platform you develop for?

**Comment by BorgLee** [comment]
测试有效 非常感谢。
