### ISSUE TITLE
websocket库可能有问题

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [cocos2d/cocos2d-x#9785]
test里面的extension test，network test，websocket，服务器地址换成自己的测试服务器，就失败

服务器：
用erlang的cowboy里面的websocket的sample做了websocket的服务器（链接https://github.com/ninenines/cowboy/tree/master/examples/websocket）

网页测试连接：
https://www.websocket.org/demos.html
http://www.baiyangliu.com/lab/websocket/

平台：
mac，ios，android4.2的webkit

websocket服务器地址：
ws://127.0.0.1:8080/websocket

web测试结果没问题，但是用2dx的websocket库链接，test一直显示waiting，erlang代码通过排查发现是客户端主动close了（测试了mac，ios和android，结果都是一样）

这个问题在cocos2d js里面也有，在chrome下测试好好的，编译到设备上以后，都不行；最开始在android下测试不行，最开始还以为是android的版本问题，升级到4.2，结果也一样

备注：
cowboy，web 框架，自带websocket支持，需要机器先安装erlang
mac：brew install erlang
debian：sudo apt-get install erlang

**Comment by zilongshanren** [comment]
@ziyouchutuwenwu 
Thanks for report. Could you add my QQ: 254041321 
I want to know more details of the issue. But you guys use Chinese here...
I will compile another WebSocket for you.

**Comment by zilongshanren** [comment]
@ziyouchutuwenwu 
The problems would be the mismatch version of the websocket protocol provided by the Erlang server.

http://stackoverflow.com/questions/4245858/erlang-and-websockets

Still need more effort to confirm this issue.

**Comment by zilongshanren** [comment]
@ziyouchutuwenwu 

I will update the libwebsockets library in v3.4. 

Thanks for reporting.

**Comment by Weststreet** [comment]
@ziyouchutuwenwu 我也遇到相同的问题，请问你的问题解决了么？

**Comment by dumganhar** [comment]
@Weststreet ,try to use the latest version of cocos2d-x to check out whether it was fixed. thanks.

**Comment by Weststreet** [comment]
@dumganhar 用最新版试了下还是有问题
![image](https://cloud.githubusercontent.com/assets/11329810/23253204/9fd3f0de-f9ee-11e6-9e13-9c225ab12ee6.png)

**Comment by dumganhar** [comment]
@Weststreet , are you using erlang server too?

**Comment by Weststreet** [comment]
@dumganhar yes,erlang cowboy

**Comment by dumganhar** [comment]
@Weststreet , I think it's a different issue.
The issue you met was fixed at https://github.com/cocos2d/cocos2d-x/pull/17455. 
I have tested it with cowboy websocket server and it works.
You could pull the latest code to test it again.

**Comment by Weststreet** [comment]
@dumganhar thanks，i'll try

**Comment by fireyang** [comment]
我们用cowboy 2.0也有这个问题，降到1.0.2没问题。。。
