### ISSUE TITLE
read file of size 0 cause memory leak on win32

### ISSUE THREAD

**Issue by herojia2021** [cocos2d/cocos2d-x#9789]
i use vld to detect memory leak, in file CCFileUtilsWin32.cpp there is a function getData()

there must be a 

if(buffer)
    free(buffer);

in if(buffer == nullptr || size==0) block, i meet this bug when i use a spine file with no texture,
because i only need the skeleton info, but spine still export a empty atlas for read. thats the file with size 0.

**Comment by minggo** [comment]
Thanks.
