### ISSUE TITLE
Extract related physical auto-binding codes to manual-binding to add `CC_USE_PHYSICS` limit

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#9796]
By this method,if developer don't want to use physical module, they can define CC_USE_PHYSICS 0.It can reduce package size further.

**Comment by samuele3hu** [comment]
In the release mode，it can reduce the size of liblua_empty_test.so package size 0.4M and related apk size 0.1M.

**Comment by minggo** [comment]
Can auto-binding add macro automatically?
