### ISSUE TITLE
EditBox position wrong in web build

### ISSUE THREAD

**Issue by adamlwgriffiths** [cocos2d/cocos2d-x#9804]
Using various code from our the web, I've tried to place an EditBox.
The sprite appears where I have positioned it, but the text input itself is always located at the bottom of the screen (sometimes off it until I click near by, which moves it onto the screen).

![screen shot 2015-01-05 at 9 58 56 pm](https://cloud.githubusercontent.com/assets/1239156/5612258/16566bd6-9526-11e4-8dac-e1ff2d2f8ebb.png)

Occurs on both 3.1 and 3.2.
Occurs when adding to cc.Scene or cc.Layer.

Console claims the image I'm using can't be found, but it's clearly loaded and visible.

```
cocos2d: cc.SpriteFrameCahce: Frame res/ui/edit_box.png not found 
```

Very frustrating.

**Comment by minggo** [comment]
I think you should create issue in [this repo](https://github.com/cocos2d/cocos2d-js).

**Comment by adamlwgriffiths** [comment]
derp, thanks =P
