### ISSUE TITLE
cocos2d-x v3 compile errors

### ISSUE THREAD

**Issue by leoussama** [cocos2d/cocos2d-x#9805]
OS : Ubuntu 14.04 64bit
All requirements installed except gnutls-dev (there's no packege named "gnutls-dev" in the ubuntu repository but there's packege named "gnutls-bin" so i installed it)
I followed thease instructions http://www.cocos2d-x.org/wiki/Linux_Installation_and_Setup
and every thing gose right until the last step "Compile"
## When I try to compile the project there's some errors that said undefined reference to 'glfw...' (many functions begin with glfw) so I checked that file and didn't find any library to those functions here's the errors I get :

[ 57%] Built target cocos2d
Linking CXX executable ../../bin/cpp-empty-test/cpp-empty-test
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::GLViewImpl()':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:287: undefined reference to`glfwSetErrorCallback'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::initWithRect(std::string const&, cocos2d::Rect, float)':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:348: undefined reference to`glfwWindowHint'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:349: undefined reference to `glfwWindowHint'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:350: undefined reference to`glfwWindowHint'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:351: undefined reference to `glfwWindowHint'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:352: undefined reference to`glfwWindowHint'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o):/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:353: more undefined references to `glfwWindowHint' follow
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::initWithRect(std::string const&, cocos2d::Rect, float)':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:360: undefined reference to `glfwCreateWindow'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:361: undefined reference to`glfwMakeContextCurrent'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:364: undefined reference to `glfwSetCursorPosCallback'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:365: undefined reference to`glfwSetScrollCallback'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:368: undefined reference to `glfwSetWindowPosCallback'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:369: undefined reference to`glfwSetFramebufferSizeCallback'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:371: undefined reference to `glfwSetWindowIconifyCallback'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::initWithFullScreen(std::string const&)':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:399: undefined reference to `glfwGetPrimaryMonitor'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:403: undefined reference to`glfwGetVideoMode'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::initWithFullscreen(std::string const&, GLFWvidmode const&, GLFWmonitor*)':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:415: undefined reference to`glfwWindowHint'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:416: undefined reference to `glfwWindowHint'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:417: undefined reference to`glfwWindowHint'
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:418: undefined reference to `glfwWindowHint'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::end()':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:432: undefined reference to `glfwSetWindowShouldClose'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::windowShouldClose()':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:448: undefined reference to `glfwWindowShouldClose'
../../lib/libcocos2d.a(CCGLViewImpl-desktop.cpp.o): In function`cocos2d::GLViewImpl::updateFrameSize()':
/home/leoussama/Workspace/Progs/cocos2d-x/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:506: undefined reference to `glfwGetFramebufferSize'
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/cpp-empty-test/cpp-empty-test] Error 1
make[1]: **\* [tests/cpp-empty-test/CMakeFiles/cpp-empty-test.dir/all] Error 2

**Comment by zilongshanren** [comment]
@leoussama 

Have you successfully installed the libglfw3?

And you should also run `sudo apt-get remove libglfw2`.(N.B. The command would be wrong here, but the point is you should remove glfw2)

**Comment by zilongshanren** [comment]
@leoussama 
Any updates?

**Comment by leoussama** [comment]
there's no package named libglfw3 only libglfw 2 in ubuntu 14.04
please include all libraries dependencies in the source project so we can install every thing once and for all or you can compile and intall it on your owen machine then generate deb file using apt

**Comment by zilongshanren** [comment]
@leoussama 
I think the problems is the libglfw2 which is ship with ubuntu 14.04. Cocos2d-x depends on libglfw3.

So if you successfully calls the `install-linux-deps.sh`, you should also remove the libglfw2.

I will try to fix the install-linux-deps.sh scripts.

**Comment by leoussama** [comment]
you can just include it in the installation packages and link it localy

**Comment by zilongshanren** [comment]
@leoussama 
Hi, could you make a new ubuntu virtual machine and try the updated scripts in the PR 9984?

I think it should be working now.

Thanks.
