### ISSUE TITLE
 RenderTexture  3.0显示不出来  2.2.2可以

### ISSUE THREAD

**Issue by mooncode163** [cocos2d/cocos2d-x#9815]
以下是两个版本的工程代码：
http://pan.baidu.com/s/1pJC23tp

**Comment by zilongshanren** [comment]
In v3.x, you should call `Director::getInstance()->getRenderer()->render();`  .

```
renderTexture->setAutoDraw(false);

renderTexture->beginWithClear(1.0f, 0.0f, 0.0f, 0.0f);
sprite->setPosition(Vec2(visibleSize.width * 0.5f, visibleSize.height / 2 + origin.y));
sprite->visit();
renderTexture->end();
Director::getInstance()->getRenderer()->render();

renderTexture->begin();
sprite->setPosition(Vec2(visibleSize.width * 0.25f, visibleSize.height * 0.25f + origin.y));
sprite->visit();
renderTexture->end();
Director::getInstance()->getRenderer()->render();
```

**Comment by mooncode163** [comment]
我实验了一下，加了这个代码在我的工程里也显示不出来，可以能需要在我工程里具体分析吧，谢谢！

**Comment by zilongshanren** [comment]
ok, It's your turn now, haha @dabingnn

**Comment by mooncode163** [comment]
如果是 sprite可以显示出来 如果是其他的GL语句绘图就显示不出来

**Comment by dabingnn** [comment]
@Jaykie Is there any more info about this problem? Could you please give me a test case to reproduce the bug? Thanks.

**Comment by shutup** [comment]
@dabingnn follow tutorial shows one  http://blog.csdn.net/akof1314/article/details/9293797,it works in v2,but not in v3.6,and here is what i do to port it to v3.6 http://www.jianshu.com/p/431c74334cca .please also help me why the issue #8656 happen.

**Comment by minggo** [comment]
It is because in v3.x, render command is send to render queue to draw something. So can not use v2 codes directly in v3, should use custom command to do the same thing. Can refer to how `DrawNode` is implemented in v3.
