### ISSUE TITLE
在2d-x中的物理引擎，地面和物体弹力设置为0，也会弹跳的问题

### ISSUE THREAD

**Issue by ZengyiMa** [cocos2d/cocos2d-x#9817]
我发现这也发生在官方示例里面，你们看Node：physics里面的 physics Test当物体静止后和地面有反弹力，这是bug吗？

**Comment by WenhaiLin** [comment]
@codemzy Do you know how to reproduce this issue easier ?

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10643
