### ISSUE TITLE
CCGLView's Viewport rectangle not initialized on desktops

### ISSUE THREAD

**Issue by ericmux** [cocos2d/cocos2d-x#9821]
This is based upon the current tip of the `v3` branch. What I noticed is that unless the user explicitly calls the method `glview->setDesignResolutionSize(...);`  the variable `_viewPortRect` on CCGLView will not be set on desktops, since `GLViewImpl::initWithRect` never writes to it. This causes the touch events' coordinates from GLFW to not be converted correctly, and this is where I came across this issue. I noticed the `getLocationInview` method was not changing the position at all and then I saw this variable was not initialized. 

I suspect this was not the intended behavior (forcing the user to call `glview->setDesignResolutionSize(...)`) so I submitted a small PR with this fix, thanks!

**Comment by minggo** [comment]
@ericmux 
How to reproduce it?
