### ISSUE TITLE
The font files were useless by using cocostudio2.1beta,but in the cocostudio2.0.6  they had effect

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#9829]
The screenshot as follow:

![studio_erro](https://cloud.githubusercontent.com/assets/4231014/5640195/879292d8-965d-11e4-82b0-fdcd9eaf4939.jpg)

**Comment by xiaofeng11** [comment]
By the screen shoot, I think the beta version you used have assign FNT file to a wrong parser, so the file check failed. CocoStudio 2.3.2 will rewrite the fnt parser, please try new version.

**Comment by pandamicro** [comment]
Anyone met this issue, please try what @xiaofeng11 said, if issue still occur, please comment here
