### ISSUE TITLE
EditBox-PopScene-Bug

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#9834]
`version:` v3.3

`Issue:` the editbox is invalid to key anything once you pushScene and popScene on the Mac platform.

the error log is 

> NSSecureTextFieldCell detected a field editor ((null)) that is not a NSTextView subclass designed to work with the cell. Ignoring...

`platform:` Mac

`reproduce:`

download the 2 classes(HelloWorldScene & HelloWorldScene2) to v3.3 HelloWorld Project.

[https://github.com/fusijie/Cocos2dx-Issue/tree/master/EditBox-PopScene-bug](https://github.com/fusijie/Cocos2dx-Issue/tree/master/EditBox-PopScene-bug)

**Comment by zilongshanren** [comment]
@fusijie  @minggo 

It‘s a very strange problem here. Since it only exists on Mac platform, so we could take the priority a little down.  If I don't have enough time, I won't solve it in v3.4 final.

Now I should add the cell reuse mechanism back to ListView.

**Comment by minggo** [comment]
Ok.

**Comment by walzer** [comment]
I think we should unity `CCTextField`, `CCEditBox` and `UITextField` to only one.

**Comment by zilongshanren** [comment]
@walzer  I will keep EditBox.
