### ISSUE TITLE
Running `cocos run -p android -j 4` command for cpp-tests would meet a error on the android 2.3.6

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#9841]
Compile successful,but install failed.The error msg as follows:

```
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=org.cocos2dx.cpp_tests/org.cocos2dx.cpp_tests.AppActivity flg=0x10000000 }
```

**Comment by natural-law** [comment]
It's be solved in this PR: https://github.com/cocos2d/cocos2d-x/pull/9846
The related PR in cocos2d-console is : https://github.com/cocos2d/cocos2d-console/pull/210
