### ISSUE TITLE
TextBMFont created by cocostudio2.0.6 have different display between v3.3 and v3.4beta

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#9856]
V3.3 display as follow:
![v3_3_1](https://cloud.githubusercontent.com/assets/4231014/5656702/d65dfdda-971b-11e4-9684-c0965de9e476.png)

V3.4 display as follow:
![v3_4_1](https://cloud.githubusercontent.com/assets/4231014/5656719/0f8e2e86-971c-11e4-8428-07e516df6e64.png)

It seems that labelBMFontScaleChangedWithSize of TextBMFont have different processing logic:
![different_logic](https://cloud.githubusercontent.com/assets/4231014/5656653/52cd77fc-971b-11e4-8af1-1f466e421926.png)

**Comment by chengstory** [comment]
I ask @pipu to take a look.

**Comment by pipu** [comment]
You could check in definition of WidgetReader::setPropsWithFlatBuffers() in WidgetReader.cpp.
Focus on below code:
widget->setUnifySizeEnabled(false);
widget->setLayoutComponentEnabled(true);
widget->ignoreContentAdaptWithSize(false);
Size contentSize(options->size()->width(), options->size()->height());
widget->setContentSize(contentSize);

**Comment by samuele3hu** [comment]
In V3.4:
widget->ignoreContentAdaptWithSize(false);

In V3.3:
 bool ignoreSize = options->ignoreSize();
 widget->ignoreContentAdaptWithSize(ignoreSize);

Why?

**Comment by pipu** [comment]
1. Value ignoreSize is a variable of Widget in UI framework in cocos2d-x, its default value is false.
2. Almost all node and widget in CocoStudio Editor cannot be modified their property "ignoreSize".
3. Only 1 widget "Text" can be modified its property "ignoreSize", therefore, TextReader.cpp is responsible to parse value for "ignoreSize" from .csb file published from CocoStudio Editor.

**Comment by minggo** [comment]
So what's the conclusion?
The fact is that, effects are different in two versions.
It means it breaks compatibility.

**Comment by pipu** [comment]
Effects of the above two pictures seem same.

**Comment by edwardzhou** [comment]
exactly, not same. 
it will scale the text when add more (or minus more) '.' to the string.

I just tested with the latest engine code.

**Comment by chengstory** [comment]
exactly, not same. I have asked @pipu to fix it.

**Comment by pipu** [comment]
@samuele3hu 
Could you upgrade CocoStudio Editor to v2.1Beta?

**Comment by edwardzhou** [comment]
@pipu 
I have upgraded to CocoStudio Editor v2.1Beta (CocosStudioForMac-v2.1-Beta-2015-0112-1427-Small) which provided by @chengstory this afternoon. And then re-exported. still same problem.

**Comment by pipu** [comment]
@samuele3hu 
Could you give us your .fnt file which TextBMFont uses?

**Comment by doomsdayer** [comment]
![ios simulator screen shot 2015 1 12 8 27 34](https://cloud.githubusercontent.com/assets/3272795/5702908/0e2a7262-9a9a-11e4-8f61-fea19e0eb1be.png)

This is from Cocos2d-x 3.4Beta0 loading the csb file published by CocosStudio 2.1Beta, it's seems no problem, like your first picture.

Are you using the Cocos2d-x 3.4beta0 from the official site?

**Comment by edwardzhou** [comment]
I have just tested on Cocos2d-x 3.4beta0 downloaded from the official site (http://cocostudio.download.appget.cn/Cocos2D-X/cocos2d-x-3.4beta0.zip). 
Same problem.

here is the test case for u http://pan.baidu.com/s/1kTqWkwn (run with 'cocos run -pandroid -j8')

**Comment by doomsdayer** [comment]
This issue occurs when get the lable widget from csb file, and setString with longer text. The lable's size keeps constant, so every character becomes thinner.

To solve this issue, after the lable is gotten, execute:

```
label->ignoreContentAdaptWithSize(true);
```

**Comment by pandamicro** [comment]
Please use @doomsdayer 's solution, this is designed this way, not a bug
