### ISSUE TITLE
Cocos2d-x-js / JSB project crashes on android when using NDK-r10d

### ISSUE THREAD

**Issue by ddalcu** [cocos2d/cocos2d-x#9863]
E/AndroidRuntime(29440): FATAL EXCEPTION: main
E/AndroidRuntime(29440): Process: com.symplestudios.penguinwars, PID: 29440
E/AndroidRuntime(29440): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "atof" referenced by "libcocos2djs.so"...
E/AndroidRuntime(29440):        at java.lang.Runtime.loadLibrary(Runtime.java:364)
E/AndroidRuntime(29440):        at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(29440):        at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:85)
E/AndroidRuntime(29440):        at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:99)
E/AndroidRuntime(29440):        at android.app.Activity.performCreate(Activity.java:5600)
E/AndroidRuntime(29440):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
E/AndroidRuntime(29440):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
E/AndroidRuntime(29440):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
E/AndroidRuntime(29440):        at android.app.ActivityThread.access$900(ActivityThread.java:174)
E/AndroidRuntime(29440):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(29440):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(29440):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(29440):        at android.app.ActivityThread.main(ActivityThread.java:5748)
E/AndroidRuntime(29440):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29440):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(29440):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
E/AndroidRuntime(29440):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
E/AndroidRuntime(29440):        at dalvik.system.NativeStart.main(Native Method)

compiles and runs fine with NDK-r9d, however the screen is blank.

Running on android 4.4... from what I googled.. it should work fine on 5.0, however anything older will crash.

**Comment by minggo** [comment]
Please create the issue in [this repo](https://github.com/cocos2d/cocos2d-js).
