### ISSUE TITLE
cpp-tests.exe can not run in windows 7 64bit.

### ISSUE THREAD

**Issue by litefeel** [cocos2d/cocos2d-x#9866]
![qq 20150108154411](https://cloud.githubusercontent.com/assets/1288575/5659459/86e2cc18-974d-11e4-89a4-f9425b312af0.png)

vs 2012 update 4.
cocos2d-x-3.4

I can build and run cocos2dx3.2. but now I clone 3.4, build and not run.

**Comment by zilongshanren** [comment]
@lite3 
The latest code has solved this issue. You should clone the latest code and run `python download-deps.py`
Thanks.
