### ISSUE TITLE
[WP8.1] Test Node:RenderTexture-Touch the Screen draw lines too slow

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#9869]
In this test touch to draw lines works fast and well on other platform but WP8.1 draws too slow.

**Comment by minggo** [comment]
@stammen
Could you please take a look?

**Comment by minggo** [comment]
@huangshiwu 
Please track this issue.

**Comment by stammen** [comment]
We are aware of the issue. We will continue to investigate.
