### ISSUE TITLE
[MAC]Lua-tests->PhysicsTest->Pump  display wrong.

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#9871]
![b147ab06-a6d9-4fdf-a193-78ad5d947d5c](https://cloud.githubusercontent.com/assets/4231014/5659725/59a2bd62-9752-11e4-988b-96eca81b8181.png)

**Comment by minggo** [comment]
Please add platform information.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9888
