### ISSUE TITLE
CCClippingNode (cocos2dx v2) doesn't work on iOS 8

### ISSUE THREAD

**Issue by birdkingz** [cocos2d/cocos2d-x#9880]
Hi, I just realised CCClippingNode doesn’t on all iOS 8 devices. (It works on iOS 7 and below devices)
I’m currently using cocos2dx v2.2.1 (I did try to update to v2.2.6 but it’s still not working)
I found out it is because Stencil buffer is not enabled but I've already enabled the Stencil during the EAGLView initialization.

**Comment by minggo** [comment]
Have you tried cpp-tests?
There is a test case for CCClippingNode.

**Comment by walzer** [comment]
Sorry, we have no enough resource to support cocos2d-x v2, which is already 2 year old.
Please use v3 instead.
