### ISSUE TITLE
Problem with CCEditBox when CCMoveBy or CCScaleTo is used

### ISSUE THREAD

**Issue by priyanka91** [cocos2d/cocos2d-x#9893]
I have created CCSprite and added CCEditBox as its child,but whenever CCMoveTo or CCScaleTo action is run on that sprite,typing is not proper in editbox. Text is not shifting to left side.
  I would really appreciate any help..Thanks!!!

**Comment by minggo** [comment]
What's the engine version?

**Comment by priyanka91** [comment]
cocos2d-x 2.2.3..Initially it was working well, but after I upgraded my Xcode to 5.1,text is not shifting

**Comment by zilongshanren** [comment]
@priyanka91 
Cocos2d-x 2.2.3 is not maintained now. 
@minggo Should we skip this issue?

**Comment by zilongshanren** [comment]
@minggo  @priyanka91 
I have tested it on V3.4rc1 and it is working properly.
