### ISSUE TITLE
applicationDidEnterBackground() not called on the WP8

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#9894]
`version:` v3.3

`Issue:` applicationDidEnterBackground() don't called on the WP8 when press windows key. And applicationWillEnterForeground() don't called on the WP8 when return to the game.

`platform:` WP8

`reproduce:`

download the HelloWorldScene class to v3.3 HelloWorld Project.

[https://github.com/fusijie/Cocos2dx-Issue/tree/master/applicationDidEnterBackground-WP8-bug](https://github.com/fusijie/Cocos2dx-Issue/tree/master/applicationDidEnterBackground-WP8-bug)

**Comment by minggo** [comment]
@stammen
Could you please take a look?

**Comment by walzer** [comment]
Close this issue because Microsoft OpenTech will remove wp8 support since v3.7. Only wp8.1 and win10 will be supported.
