### ISSUE TITLE
EventDispatcher: crash if adding/removing event listeners and dispatching event in event callback function

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#9898]
`version:` v3.3

`Issue:` if dispatch the same event on the listener's event callback, the program will crash.

`reproduce:`

download the 2 classes(HelloWorldScene & BugUnit) to v3.3 HelloWorld Project.

[https://github.com/fusijie/Cocos2dx-Issue/tree/master/dispatchCustomEvent-crash](https://github.com/fusijie/Cocos2dx-Issue/tree/master/dispatchCustomEvent-crash)

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9963
