### ISSUE TITLE
drawing model in cocos2dx using md2 file format

### ISSUE THREAD

**Issue by shubham-jain** [cocos2d/cocos2d-x#9907]
I have been using md2 files to draw and animate 3d objects in cocos2dx. But for a particular case the texture on turns black for some frames while animating.
I am using CCModelMd2 class which is inherited from CCModel class .

**Comment by minggo** [comment]
@shubham-jain 
What's the issue? cocos2d-x now doesn't support md2 format.
Are you asking requirement of cocos2d-x?

**Comment by shubham-jain** [comment]
i am using cocos2dx 2.2.3, and i have used CCModel as base class to draw 3d models .
The problem is while animating this model the texture turns black sometimes.

**Comment by walzer** [comment]
`CCModel` is not an official class in cocos2d-x. Please use `fbx-converter` tool to convert fbx to c3b format.
