### ISSUE TITLE
SimpleAudioEngine::playEffect() lagged on Android 5.0.x

### ISSUE THREAD

**Issue by qiankanglai** [cocos2d/cocos2d-x#9911]
After updating Android 5.0.1, cocos2d-x 2.x freezes when playEffect()

I've found other's fix for [backgound music](https://github.com/cocos2d/cocos2d-x/pull/9088) and [preload](http://www.zhihu.com/question/24843109), but they don't work for me.

After some debugging, I find comment out `mSemaphore` works well. This makes `public int playEffect(final String pPath, final boolean pLoop, float pitch, float pan, float gain)` return `Cocos2dxSound.INVALID_SOUND_ID` all the time, but I wonder whether the return value is useful?

**Comment by mumreg** [comment]
Got same issue on Nexus 7 (2013), Android 5.0.1

**Comment by mumreg** [comment]
I think it may be the result of this bug: https://code.google.com/p/android/issues/detail?id=81187

**Comment by fbbarros** [comment]
So any news on a workaround for this issue? I've been looking into using OpenSL or optionally shipping a static libmedia.so with our app. How are you guys thinking of dealing with this issue?

**Comment by qiankanglai** [comment]
Finally I switched to fmod and ignore cocosdension

**Comment by mumreg** [comment]
Did the same thing, moved to fmod.

**Comment by walzer** [comment]
This is a known bug on Android 5.0.x. Many users are complaining on this.
The `SimpleAudioEngine` is lagged in `SoundPool.preload` android API.

So for users, please switch to `AudioEngine` instead of `SimpleAudioEngine`. `AudioEngine` use pure c++ implementation, can avoid this problem.
For us, my idea is to wrap `AudioEngine` to `SimpleAudioEngine` interfaces. This is planned in v3.7.

**Comment by neonaleon** [comment]
Is there any guide for how to use AudioEngine instead of SimpleAudioEngine in a 2.2.6 project?

**Comment by WenhaiLin** [comment]
Wrap AudioEngine to SimpleAudioEngine interfaces for Android 5.0.x: https://github.com/cocos2d/cocos2d-x/pull/12098

**Comment by Guy-kun** [comment]
So this was closed despite being critical with the only solution being to move to an 'experimental' player? (The experimental player has terrible latency too for sound effects and can't keep up)

**Comment by dumganhar** [comment]
@Guy-kun, I refactored `experimental::AudioEngine` recently, it should have addressed the latency problem. Do you mind to use the latest code on v3 branch to test?

**Comment by Guy-kun** [comment]
I've switched all of my audio to FMOD to avoid this a fair while ago so I'll have to leave it to someone else to try out.

**Comment by dumganhar** [comment]
OK. 👍
