### ISSUE TITLE
Please remove event tracking from lua-template-rumtime (cocos2d-x 3.4rc0)

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#9914]
Please remove event tracking from default Lua rumtime
- it's slow down application startup
- it's sending user's GUID to intenet :-(

It send event to **google-analytics** every-time application start
[/templates/lua-template-runtime/frameworks/runtime-src/Classes/AppDelegate.cpp](https://github.com/cocos2d/cocos2d-x/commit/d4681c115009bb6d70e126a9a8252cb0c11e692e#diff-064bbb0ec05aa6fbb632a17d9d7cfe43)

**Comment by ghost** [comment]
- It's better to track the event from 'Cocos Code IDE'.
  - Hash GUID before sending to internet.

**Comment by dualface** [comment]
- because the Google Analysis request is async, so it's not slow down startup
- we will hash GUID before sending to internet, thanks

**Comment by ghost** [comment]
Thank you for quick response. But my concern is Cocos2d-x + Lua runtime should not tracking .
- It should not  track from Cocos2d-x + Lua runtime,
  other developer don't known that the runtime send data to Google Analysis if they don't look in AppDelegate.cpp.
- Other case is user (who play game) was tracked, too.

**Comment by dualface** [comment]
Yes, you are right. we will remove google analysis from template, keep it in pre-build simulator. We need known how many developers use simulator for development.

Thanks for your advices.

**Comment by ghost** [comment]
Changed in 3.4rc1 is looking good.
- Tracking only in pre-build simulator
- Manual build is not tracking (both debug, and release)

Thank you
