### ISSUE TITLE
Win32 Video Player

### ISSUE THREAD

**Issue by hsdk123** [cocos2d/cocos2d-x#9918]
Hi, I originally posted a question on Win32 Video Player implementation back July 2014:

http://discuss.cocos2d-x.org/t/what-features-do-you-wish-cocos2d-x-provided/14822/45

I was told at the time that the feature would be on it's way, but it's currently Jan 2015 and I still hear no sound of an implementation. Win32 support (and future OSX) is currently crucial for the company games I work on - this is the only reason that I haven't been able to use cocos2d-x for my company projects so far.

What is the current progress on the Win32 Video Player?

**Comment by hsdk123** [comment]
@minggo Hi, do you have any idea on how progress is going for this feature?

**Comment by hsdk123** [comment]
@walzer @pandamicro  Hi, this issue's been open for more than half a year now - will this be available for 3.8?

**Comment by pandamicro** [comment]
Hi, @hsdk123 VideoPlayer is a experimental feature now, and win32 is not our focused platform, so this task has a low priority in our plan. Please stay tuned for the news

**Comment by hsdk123** [comment]
@pandamicro Thanks for the continuous replies - perhaps someone could work on this in the near future. I am sure this will allow a lot more teams to use cocos2d-x if this one feature is implemented.

**Comment by drelaptop** [comment]
As above said ___win32 is not our focused platform__ long times ago

> we have no play to do this in near feature, so I close it.
