### ISSUE TITLE
3.4rc0 PhysicsBody can't getPosition when addPhysicsBody

### ISSUE THREAD

**Issue by Yehsam23** [cocos2d/cocos2d-x#9938]
Node *testNode = Node::create();
testNode->setPosition(Vec2(100, 100));
this->addChild(testNode);

PhysicsBody *physicsBody = PhysicsBody::create()
testNode->setPhysicsBody(physicsBody);

Then physicsBody->getPosition() is Zero

Please fix issue.....

**Comment by minggo** [comment]
Does testNode be added into node tree?

**Comment by minggo** [comment]
PhysicsBody::getPosition() will return the attacked node's world position. Why you need to use it?

**Comment by Yehsam23** [comment]
Yes~~~

3.4rc0 update PhysicsBody position in "updatePhysicsBodyTransform" method
It will call updatePhysicsBodyTransform when next frame.

So......getPosition is correct when next frame.

But first frame always zero position.

**Comment by Yehsam23** [comment]
We need get shape position~~

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/9991
