### ISSUE TITLE
Universal App (wp8.1-win8.1) cannot use 3rd-party libs

### ISSUE THREAD

**Issue by pekayatt** [cocos2d/cocos2d-x#9946]
It looks like there is a problem with Visual C++ projects that even if they use XAML they can't use controls no designed exclusive for that.

The issue is that there is no Ad library available in this new method (except AdDuplex, but they don't pay for clicks).

Keep both version for the time being looks like the best way to support both freemium and paid apps (paid could use the native that has more performance).

**Comment by minggo** [comment]
close it since not support wp8.1 now
