### ISSUE TITLE
Optimize the bindings-generator tool

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#9958]
## Highlighted
- [x] Add finalize support of no-ref class
- [x] Add parse of public member variable
- [x] Should refine lambda support ( it doesn't support complexe parameters (like std::string) )
- [ ] Should support lambda in Lua bindings (@dualface can you take a look) 
- [ ] The return value is Object value, it would trigger the compile error.
- [ ] If the functions of class are limited by the macro, the binding function have get the macro limit.
- [x] Add automatic extend to JSB for classes "need to extend"
- [x] JSB configuration without namespace will cause compilation error
## Other improvments
- [ ] Make tools search the dependent library path automatically
- [ ] Make the enum class be generated automatically (Configurable)
- [ ] Add record of deprecated functions
- [ ] Record the binding function that have parse error
- [ ] Should support the include conversional heads files of different module by configure

**Comment by samuele3hu** [comment]
9.The return value is Object value, it would trigger the compile error.
10.If the functions of class are limited by the macro, the binding function have get the macro limit.
11.Enum class can't be bound automatically.
12.public member variable should be bound.
13.For Lua,no Ref Class have not collect function.

**Comment by pandamicro** [comment]
Highlighted tasks will be scheduled to v3.8

**Comment by pandamicro** [comment]
Done `Add automatic extend to JSB for classes "need to extend"` in https://github.com/cocos2d/cocos2d-x/pull/12974

**Comment by pandamicro** [comment]
Done `JSB configuration without namespace will cause compilation error` in https://github.com/cocos2d/bindings-generator/pull/175

**Comment by pandamicro** [comment]
v3.8 Tasks are finished here.
Future improvements will be scheduled in next versions
