### ISSUE TITLE
my ogg file can't be played

### ISSUE THREAD

**Issue by b562516128** [cocos2d/cocos2d-x#9961]
I use the newAudioEngine to play ogg file recently with the cocos2d-x 3.3 Final.
I change my ogg file to three qualities. High, Medium and Low with Format Factory . 
And I found that the Engine Could only play the ogg file of low quality.  The other two play with no sound and console didn't print any wrong message.
By the way, I use Windows+ VS.

**Comment by minggo** [comment]
Did you use SimpleAudioEngine or new audio?
SimpleAudioEngine doesn't support ogg format.

**Comment by walzer** [comment]
Inactive issue for more than 3 months.
