### ISSUE TITLE
iOS glClear crash

### ISSUE THREAD

**Issue by bryanwong** [cocos2d/cocos2d-x#9965]
Cocos2d-X 3.3 finial, iOS 7

glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);  Crashed on startup.

![screen shot 2015-01-13 at 8 03 34 pm](https://cloud.githubusercontent.com/assets/2644678/5720460/88cc5254-9b5f-11e4-8bfc-075f751713e7.png)

**Comment by minggo** [comment]
How to reproduce it?

**Comment by bryanwong** [comment]
@minggo I can't reproduce it, either.
It happened several times, and I guess it's relevant to the low memory?

**Comment by minggo** [comment]
So there is not problem in tests?

**Comment by walzer** [comment]
This issue can't be reproduced, and is inactive for more than 3 months.
