### ISSUE TITLE
Crash on Android devices with arm-v7a, but without NEON

### ISSUE THREAD

**Issue by ondesly** [cocos2d/cocos2d-x#9968]
LOCAL_ARM_NEON := true in cocos/Android.mk and APP_ABI := armeabi-v7a in Application.mk causes crash on launch (SIGILL) on Android devices with CPU arm-v7a, but without NEON instructions.

Such CPU is Nvidia Tegra 2. It supports arm-v7a, but it doesn't support NEON instructions.
Devices: Samsung Galaxy Tab 10.1 (P7500), Asus Transformer TF101, Motorola XOOM and others.

**Comment by minggo** [comment]
As you said, the device doesn't support NEON instructions, why you use `LOCAL_ARM_NEON := true`?

**Comment by ondesly** [comment]
I don't. It's enabled in cocos/Android.mk by default for all arm-v7a devices.

**Comment by dabingnn** [comment]
Because Neon support can not be checked when compiling the code.
So the solution for neon on android is that the neon code will always be include in the apk file, and when code is running, CPU features is checked, if neon is enabled, math computation will use NEON, or C implementation will be used.
Please refer to 
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/math/MathUtil.cpp

Could you please attach some crash logs to give us more info? Thanks

**Comment by minggo** [comment]
[this document](http://www.kandroid.org/ndk/docs/CPU-ARM-NEON.html) says

> LOCAL_ARM_NEON:
> Define LOCAL_ARM_NEON to 'true' in your module definition, and the NDK will build all its source files with NEON support. This can be useful if
> you want to build a static or shared library that specifically contains NEON code paths.

So we can not use `LOCAL_ARM_NEON := true` to select neon version of math library.

**Comment by minggo** [comment]
@ondesly 
Is it work correctly if you comment `LOCAL_ARM_NEON := true`?
Could you please help to check it because we don't have the devices you mentioned.

**Comment by Yehsam23** [comment]
I comment LOCAL_ARM_NEON := true....then i works fine on my device.

My device is Asus Transformer TF101.

So...we can comment this?

**Comment by minggo** [comment]
@Yehsam23 
Yep, it is safe to comment this line.
We use it to select neon version of math library.
As you know, neon instructions are more efficient.

**Comment by dabingnn** [comment]
@Yehsam23 
I submitted a pr #10157，it works on armv7 with neon support, could you try it?
I don't know if it works on armv7-a without neon

**Comment by ondesly** [comment]
@minggo 
I already released build without LOCAL_ARM_NEON := true. It works fine.
I haven't such device now, but I will get it soon and check @dabingnn solution.

**Comment by minggo** [comment]
Thanks @ondesly .

**Comment by Yehsam23** [comment]
@dabingnn 
I try your pr #10157 , it works on my device (ASUS TF101).
Thanks a lot.

**Comment by dabingnn** [comment]
Thanks.
