### ISSUE TITLE
WP8 and WP8.1 DrawNode's drawPoint do not work

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#9980]
In test case Node:Draw
1.WP8.1 can't draw point at all ,while WinRT8.1 works well
2.WP8 can't set point's size

**Comment by ghost** [comment]
@stammen
Could you please take a look?

**Comment by stammen** [comment]
Angle on WIndows Phone 8.1 does not yet implement glPointSize. Angle on Windows Phone 8.0 only supports a size of 1. Angle on WinRT 8.1 (with DirectX Level 10 or higher) can support glPointSprite using a compute shader which is not available to WIndows Phone (DirectX level 9_3).

The Angle developers are aware of this issue but have not released a solution yet.
